openthread/openthread

- src/core/meshcop/dataset.cpp
- src/core/meshcop/dataset.hpp
- src/core/meshcop/dataset_manager_ftd.cpp
- src/core/meshcop/meshcop_tlvs.cpp
- src/core/meshcop/meshcop_tlvs.hpp
This commit relocates `IsTlvValid()` to the `Dataset` class, emphasizing its specificity for validating Dataset TLVs and not other MeshCop TLVs.
> [dataset] relocate `IsTlvValid()` to `Dataset`

- include/openthread/instance.h
- include/openthread/thread_ftd.h
- src/cli/README.md
- src/cli/cli.cpp
- src/core/api/thread_ftd_api.cpp
- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
Reference devices that are part of the Thread test harness construct CoAP packets sent on TMF port 61631 for certain tests, for example in the 5.9.x series where they have to force address errors (a/ae) for duplicate DUA or re-registration tests. These tests started to fail when reference device firmware was updated recently to a newer OpenThread stack that included the change in https://github.com/openthread/openthread/pull/9437.
Example:
```
udp send fd00:db9:0:0:0:ff:fe00:5000 61631 -x 4102d63697b16e02646eff0401010010fd007d037d037d0389c3a350cdcf36e0'
Ip6-----------: Dropping TMF message from untrusted origin
```
For certification purposes, we are adding a cli toggle (for reference devices) under the `test` sub-command to disable the filter that drops TMF messages from unknown origins.
> [cli] add toggle to accept tmf udp messages from unknown origins

- src/core/common/callback.hpp
- src/core/meshcop/dataset_manager.cpp
- src/core/thread/anycast_locator.cpp
- src/core/thread/mle.cpp
- src/core/thread/mlr_manager.cpp
Will first clear the callback before invoking its handler so to allow the callback to be set again from the handler implementation.
> [callback] add `InvokeAndClearIfSet()` helper

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- tests/scripts/thread-cert/border_router/test_on_link_prefix.py
- tests/scripts/thread-cert/node.py
This commit updates `FindFavoredOnLinkPrefix()` to exclude discovered on-link prefixes with preferred lifetimes under 30 minutes.
> [routing-manager] exclude on-link prefixes with short preferred lifetime

- src/core/meshcop/secure_transport.cpp
This commit fixes again the same issue which was fixed by https://github.com/openthread/openthread/pull/8168 with the same approach.
The regression was unintentionally introduced by the initial TCAT commit https://github.com/openthread/openthread/pull/9210
See https://github.com/openthread/openthread/pull/8168 for the background and discussion.
> [dtls] fix undesired kernel filtering of connected UDP

- src/cli/cli_dns.cpp
- src/cli/cli_srp_client.cpp
- src/cli/cli_udp.cpp
The method `ParseEnableOrDisable` has been moved to  the `Utils` class and these components inherit the `Utils` class so there is no need to add namespace.
> [cli] fix namespace usage

- src/cli/cli.cpp
- src/cli/cli.hpp
- src/cli/cli_br.cpp
- src/cli/cli_commissioner.cpp
- src/cli/cli_dns.cpp
- src/cli/cli_history.cpp
- src/cli/cli_joiner.cpp
- src/cli/cli_network_data.cpp
- src/cli/cli_ping.cpp
- src/cli/cli_tcp.cpp
- src/cli/cli_udp.cpp
- src/cli/cli_utils.cpp
- src/cli/cli_utils.hpp
This PR moves a few static util methods from the `Interpreter` class
to the `Cli::Utils` class. Since the `Interpreter` class and other
classes for cli components inherit the `Cli::Utils`, they can still
access these methods. Putting these methods in utils class is more
intuitive. This change also makes other cli classes less dependent on
the `Interpreter` class.
> [cli] move a few static util methods to `Cli::Utils` class

- src/lib/spinel/radio_spinel.cpp
- src/lib/spinel/radio_spinel.hpp
- src/lib/spinel/spinel_driver.cpp
- src/lib/spinel/spinel_driver.hpp
- src/posix/platform/CMakeLists.txt
- src/posix/platform/coprocessor_type.h
- src/posix/platform/platform-posix.h
- src/posix/platform/radio.cpp
- src/posix/platform/radio.hpp
- src/posix/platform/spinel_manager.cpp
- src/posix/platform/spinel_manager.hpp
- src/posix/platform/system.cpp
- src/posix/platform/virtual_time.cpp
This PR is another subset of PR #9898.
This PR breaks down current posix radio module into `Radio` and
`SpinelManager`. The static instance of `SpinelDriver` is moved from
`Radio` to `SpinelManager`. The `platformRadioXXX` methods are also
broken down into `platformSpinelXXX` and `platformRadioXXX`. The
purpose is to make `platformSpinelXXX` resuable under both NCP and
RCP cases. And to use `platformSpinelInit` to detect to co-processor
type during initialization.
> [spinel] breakdown posix radio module

- src/lib/spinel/spinel_driver.cpp
- If we check inbetween SendReset() and WaitResponse(), mIsCoprocessorReady may become true before waitResponse() and if loop becomes false even successfully reset done.
- mIsCoprocessorReady is already checked before sendReset() to avoid resetting in case of Mulipan architecture. There is no need to check inbetween sendReset() and waitResponse().
- Removed mIsCoprocessorReady from if loop check between sendReset() and waitResponse().
> [spinel] remove `mIsCoprocessorReady` flag check (#10134)

- examples/platforms/simulation/misc.c
This commit removes the `LogCrit` example lines emitted from `otPlatLogCrashDump()` in simulation platform. These extra log lines can cause test failures.
---
Have been noticing these logs in some of the test output (those often ignored, but can cause failures in certain situations).
```
1: dataset commit active
2024-04-30 15:20:02,923 - INFO - Creating node 2: {'is_mtd': False, 'is_ftd': True, 'is_bbr': False, 'is_otbr': False, 'is_host': False, 'mode': 'rdn', 'allowlist': [1, 3], 'version': '1.3', 'router_selection_jitter': 1, 'name': 'LEADER', 'active_dataset': {'timestamp': 10, 'panid': 64206, 'channel': 19}, 'partition_id': 4294967295}
/Users/abtink/github/openthread/build/openthread-simulation-1.3/examples/apps/cli/ot-cli-ftd 2
2: extaddr 166e0a0000000002
2024-04-30 15:20:02,932 - …
```
> [simulation] remove example log lines from `otPlatLogCrashDump()`

- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
This commit adds a common `SendSetRequest(const Dataset &)` method that prepares and sends an MGMT_SET message with the given Dataset. This removes similar duplicate code.
----
~This PR currently contains the commit from #10111. Please check and review the last commit only. Thanks.~
> [dataset] simplify `SendSetRequest`

- src/core/meshcop/dataset.hpp
- src/core/meshcop/dataset_manager.hpp
- src/core/meshcop/dataset_manager_ftd.cpp
This commit adds `ProcessSetRequest()` to process a received `MGMT_SET` request message, validate the included `Dataset`, and determine if it affects connectivity or changes the network key. The now unused `DatasetTlv` is removed as TLVs are read directly from the `Message`. This change will also enable future support for `MGMT_REPLACE` request.
----
~This PR currently contains the commit from #10111. Please check and review the last commit only. Thanks.~
> [dataset] simplify dataset manager `MGMT_SET` request handling

- src/lib/spinel/radio_spinel.hpp
According to `style.md`, all #endif directives equal to or greater than 20 lines away from the #if or #ifdef directive to which they are related shall be decorated by language comment indicating the conditional they are associated with.
> [style] add comment to indicate the which conditional endif is associated with

- src/core/border_router/routing_manager.cpp
This commit corrects the order of calls to prefix methods `Tidy()` and `SetLength(kOmrPrefixLength)`. This was unintentionally reversed in PR #10000.
PD prefixes can be shorter than `kOmrPrefixLength` (as allowed by `IsValidPdPrefix()`). To use them as OMR prefixes, `Tidy()` is called first to clear any extra bits before potentially extending the prefix to `kOmrPrefixLength`.
> [routing-manager] ensure correct handling of shorter PD prefix

- src/core/meshcop/dataset_manager_ftd.cpp
This commit simplifies the code and adheres to the SHOULD requirement in the Thread specification, which states: "A Thread Device that is not a Leader MUST NOT process this message. Instead it SHOULD respond with 'Reject' state value".
> [dataset] send 'reject' response to `MGMT_SET` on non-leader

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit adds `CalculateExpirationTime()`, which simplifies the calculation of expiration times of discovered prefix entry by clamping a given lifetime to the maximum value (in seconds) first before converting to milliseconds.
> [routing-manager] add `CalculateExpirationTime()`

- src/lib/spinel/coprocessor_type.h
- src/lib/spinel/spinel_driver.hpp
- src/posix/platform/platform-posix.h
This PR moves the definition of coprocessor_type from posix to
lib/spinel directory. There are two reasons to do so:
1. Allow platforms other than posix to access the definition. For
example, nxp imt-rx.
2. Allow the user (posix/main.c) of OT system API to access the 
defifition. Currently the posix main depends on OT system API but
doesn't depend on definitions in 'platform-posix.h'. This should
be kept.
> [spinel] move definition of coprocessor type to `lib/spinel`

- src/core/common/owning_list.hpp
- src/core/net/mdns.cpp
- tests/unit/test_linked_list.cpp
This commit introduces a new method, `RemoveAndFreeAllMatching()`, to the `OwningList<Type>` class. This method removes and frees all entries in the list that match a given indicator. This is used to simplify the native mDNS implementation. The unit test `test_linked_list` is also updated to validate the newly added helper method.
> [owning-list] add `RemoveAndFreeAllMatching()` to `OwningList` class

- src/core/net/dns_types.cpp
- src/core/net/dns_types.hpp
- tests/unit/test_dns.cpp
This commit enhances `Dns::Name` to detect and handle cases where a compressed DNS name contains a loop spanning multiple labels. The `test_dns` unit test has been updated to include test cases for these invalid names.
> [dns] add checks for multi-label looped compressed DNS names

- src/lib/spinel/radio_spinel.cpp
During RCP recovery, the Host does not check if the RCP supports logging a crash dump. This causes RCP recovery to fail when the RCP is built with `OPENTHREAD_CONFIG_PLATFORM_LOG_CRASH_DUMP_ENABLE = 0`. This bug was introduced in #10061
This PR will make the Host only request crash logs from the RCP if the RCP supports it.
In this example, I have an RCP built with `OPENTHREAD_CONFIG_PLATFORM_LOG_CRASH_DUMP_ENABLE = 0` that is reset externally. When the Host runs through the RCP recovery, it fails here https://github.com/openthread/openthread/blob/226f239c5d85bfc0eb02cd771ddca65a34ca8f73/src/lib/spinel/radio_spinel.cpp#L2005
```php
May 08 15:37:16 test-machine ot-cli[3967014]: 00:00:03.535 [D] P-SpinelDrive-: Received spinel frame, flg:0x2, iid:0, tid:0, cmd:PROP_VALUE_IS, key:LAST_STATUS, …
```
> [spinel] only request crash logs on RCP recovery if capable

- src/cli/cli_udp.cpp
**Problem:**
Executing the `udp send` command in CLI without previously opening the example udp socket results in an unhandled null-pointer exception.
**Solution:**
Before anything is processed in the `UdpExample::Process<Cmd("send")>(Arg aArgs[])` method, the UDP socket is checked whether it's open or not. If not, the method returns with OT_ERROR_INVALID_STATE error avoiding the null-pointer exception.
> [cli] add UDP socket openness check before sending with `udp send`

- .clang-format
- .github/workflows/simulation-1.1.yml
- examples/platforms/simulation/simul_utils.c
- examples/platforms/simulation/simul_utils.h
- examples/platforms/simulation/system.c
- script/check-simulation-local-host
- tests/scripts/expect/_common.exp
This commit adds support to simulate Thread radio over IPv6.
With this commit, a simulation will be simulated over either IPv6 or IPv4. If it's simulated on IPv6, it communicates with other simulation nodes in IPv6 group `ff02::116`. And if it's simulated on IPv4, it communicates with other simulation nodes in IPv4 group `224.0.0.116`.
Note that simulating virtual time is not included in this commit.
> [simulation] support simulating radio over IPv6

- include/openthread/border_routing.h
- include/openthread/instance.h
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit refactors and simplifies `RoutingManager`:
- Introduces `OnLinkPrefix` and `RoutePrefix` classes, both derived from a common base class `LifetimedPrefix` (representing a prefix and its valid lifetime).
- Replaces the originally dual-purpose `DiscoveredPrefixTable::Entry` (used for both route and on-link prefixes) with a new template `Entry<Type>`, specifically used with `OnLinkPrefix`, `RoutePrefix`, and also `Router`.
- Updates `Router` to maintain separate lists for on-link and route prefixes.
- Utilizes `OnLinkPrefix` in `PdPrefixManager` for tracking DHCPv6-PD prefixes.
> [routing-manager] introduce `RoutePrefix` and `OnLinkPrefix` types

- src/core/meshcop/dataset.cpp
- src/core/meshcop/dataset.hpp
- src/core/meshcop/dataset_manager.hpp
- src/core/meshcop/dataset_manager_ftd.cpp
- src/core/thread/tmf.cpp
- src/core/thread/uri_paths.cpp
- src/core/thread/uri_paths.hpp
----
The OT stack did not previously support the `MGMT_ACTIVE_REPLACE` command on Leader devices. Although not a critical or widely-used command, this lack of support could lead to compatibility issues if a commissioner attempts to use it in the future. Any commissioner implementation utilizing this command should take this into account and handle it accordingly.
> [dataset] add support for handling `MGMT_ACTIVE_REPLACE` on leader

- script/clang-format
Homebrew installation of clang-format (satisfying >14.0 requirement) outputs the following version string:
```
Homebrew clang-format version 14.0.6
```
This change fixes the following error while running make-pretty:
```
*** ERROR: Homebrew clang-format version 14.0.6; clang-format 14.0 required
```
> [clang-format] accept different patch versions of `clang-format`

- src/core/api/dataset_api.cpp
- src/core/meshcop/dataset_local.cpp
- src/core/meshcop/dataset_local.hpp
- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
- src/core/meshcop/dataset_manager_ftd.cpp
- src/core/meshcop/dataset_updater.cpp
- src/core/meshcop/joiner.cpp
- src/core/meshcop/tcat_agent.cpp
This commit streamlines dataset-related helper methods:
- Renames all methods that save local dataset to `SaveLocal()` for consistency and to distinguish them from `Save()` methods, which set the partition's dataset and perform additional checks (e.g., ensuring the timestamp is ahead).
- Renames `SendSet()` to `SyncLocalWithLeader()` and passes `aDataset` as an input parameter to avoid redundant dataset reads.
- Removes the now unnecessary `HandleDatasetUpdated()` method, as its functionality can be inlined within `SaveLocal(const Dataset &)`.
- Consolidates additional dataset type-specific actions (e.g., starting a delay timer for Pending Dataset changes) into the base class `DatasetManager` methods `Save()` and `SaveLocal()`, simplifying the code and reducing redundancy.
- Modifies …
> [dataset] simplify dataset `Save()` methods

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- src/core/net/nd6.hpp
- tests/unit/test_routing_manager.cpp
This commit modifies the `CalculateHash()` method to use a zero checksum value for RA (ICMPv6) header for both received and emitted RA message. In prepared RA messages, the checksum is always set to zero, and the platform layer is responsible for calculating and updating it. For a received RA, while platforms typically zero out the checksum after validation, this behavior isn't explicitly required by `otPlatInfraIf` APIs. By ignoring the checksum(setting it to zero) during hash calculation, this change ensures correct calculation regardless of platform behavior.
This commit also updates `test_routing_manager` to intentionally modify the checksum field in an emitted RA message before passing it back to the OT stack. This validates the updated hash calculation behavior.
----
~This PR …
> [routing-manager] ignore checksum in RA hash calculation

- src/posix/main.c
- src/posix/platform/include/openthread/openthread-system.h
- src/posix/platform/system.cpp
This PR lets posix `otSysInit` return the Co-processor type by adding 
a field in `otPlatformConfig`. (This avoids breaking the existing 
code that uses `otSysInit`.) Returning the Co-processor type allows
the app layer has the information and can do initialization. For
example, the dbus server.
The PR also allows `otSysInit` and `otSysDeinit` to be completed when
the co-processor type is NCP. This doesn't mean `ot-daemon` can work
with NCP now. But this is required by further developing NCP support
in `otbr-agent` because these two methods are required. The native
posix app (ot-daemon) will still exit when it detects a co-processor other
than RCP.
When the co-processor type is RCP, `otSysInit` and `otSysDeinit` work
as usual. When the type is NCP, only spinel manager will be 
initialized …
> [posix] add return of co-processor type in otSysInit and allow posix plat run with NCP

- src/core/thread/network_data_leader.hpp
- src/core/thread/network_data_leader_ftd.cpp
This commit simplifies the `Leader::ContainsOmrPrefix()` method by eliminating the loop over sub-TLVs based on stable flag status. Since OMR prefixes must be marked as stable, the search for a given OMR prefix can be restricted to stable sub-TLV only.
> [network-data] optimize `ContainsOmrPrefix()`

- examples/platforms/simulation/simul_utils.c
- examples/platforms/simulation/simul_utils.h
- examples/platforms/simulation/system.c
This commit renames command line argument --local-host to --local-interface to reduce confusion as discussed in #10194.
This commit also add help message for local interface.
> [simulation] rename local host to local interface

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- src/core/thread/network_data_leader.cpp
- src/core/thread/network_data_leader.hpp
- src/core/thread/network_data_leader_ftd.cpp
This commit optimizes `RoutingManager`:
- Replaces `RoutingManager::NetworkDataContainsOmrPrefix()` with `ContainsOmrPrefix()`.
- Simplifies `OmrPrefixManager::ShouldAdvertiseLocalAsRio()` by utilizing `ContainsOmrPrefix()`.
- Relocates `ContainsOmrPrefix()` to `network_data_leader.cpp` and removes its FTD-only restriction.
----
~This PR contains the commit from https://github.com/openthread/openthread/pull/10239. Please check and review last commit. Thanks.~
> [routing-manager] utilize `Network::Leader::ContainsOmrPrefix()`

- include/openthread/dataset.h
- include/openthread/instance.h
- src/core/api/dataset_api.cpp
- src/core/common/settings.cpp
- src/core/common/settings.hpp
- src/core/meshcop/dataset_local.cpp
- src/core/meshcop/dataset_local.hpp
- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
- src/core/meshcop/dataset_manager_ftd.cpp
- src/core/meshcop/dataset_updater.cpp
- src/core/meshcop/joiner.cpp
This commit updates error handling when saving Active/Pending Operational Datasets in non-volatile settings. Previously, `kErrorNotImplemented` was permitted as a return value due to legacy behavior. Since non-volatile storage is now a mandatory requirement for Thread operation, we enforc successful saves by asserting on any error encountered during this process. Methods returning error types are updated, and some now return `void`.
The public APIs `otDatasetSetActive()` and `otDatasetSetPending()` are affected by this change. They now always return `OT_ERROR_NONE` and can essentially be treated as having a void return type. The `otError` return type is maintained solely for backward compatibility.
~This change will also update public APIs like `otDatasetSetActive ()` and …
> [dataset] enforce successful Dataset saves in non-volatile

- .gitignore
I noticed that there are a few `.cmake` files in the repo that shouldn't be ignored:
* etc/cmake/*.cmake
* examples/apps/cli/{ftd/mtd/radio}.cmake
* examples/apps/ncp/{ftd/mtd/radio}.cmake
* src/core/{ftd/mtd/radio}.cmake
* src/ncp/{ftd/mtd/radio}.cmake
* src/cli/{ftd/mtd/radio}.cmake
* src/posix/daemon.cmake                                                                                                                                               
* src/posix/platform/vendor.cmake                                                                                                                                      
* src/posix/platform/vendor_extension_example.cmake                                                                                                                    
* …
> [gitignore] do not ignore .cmake files

- src/core/meshcop/dataset.cpp
- src/core/meshcop/dataset.hpp
- src/core/meshcop/dataset_manager.cpp
This commit introduces the `ContainsAllTlvs()` method to `Dataset`, which checks if a dataset contains all the specified TLVs. This new method simplifies the implementation of `IsCommissioned()` and `ContainsAllRequiredTlvsFor(Type)`
> [dataset] add `ContainsAllTlvs()` helper method

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
This commit updates `Mle::HandleLeaderData()`:
- Simplify the checks for presence of Active/Pending Dataset TLV.
- Introduce `saveActive/PendingDataset` boolean flags to track whether we should read and save the included Dataset from the received message. These replace and consolidate a group of other local variables.
- Restrict the `IsLeader()` checks to FTD builds
> [mle] simplify `HandleLeaderData()`

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit renames the `DiscoveredPrefixTable` to `RxRaTracker`. The new name is shorter and emphasizes that this class is responsible for processing received RA messages and tracks useful information about the RAs (routers and their advertised flags and prefixes).
It also renames `RaInfo` to `TxRaInfo` to clarify its role for tracking information about emitted RAs.
> [routing-manager] rename `DiscoveredPrefixTable` to `RxRaTracker`

- src/core/meshcop/dataset.cpp
- src/core/meshcop/dataset.hpp
- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
- tests/toranj/cli/test-029-pending-dataset-key-change.py
- tests/toranj/openthread-core-toranj-config.h
- tests/toranj/start.sh
This commit refactors the logic that determines whether to replace the current Active Dataset with a Pending Dataset upon its delay timer expiration.
Instead of performing the check within the more general-purpose `DatasetManager::Save()` method, the logic is now moved directly into `PendingDatasetManager::HandleDelayTimer()`. This change makes the code more specific and prevents unintended checks in other situations where `Save()` is used (e.g., when Active Dataset is directly set).
The conditions remain the same: The Pending Dataset's Active Timestamp must be newer, or the Pending Dataset must contain a different network key.
This commit also adds `test-029-pending-dataset-key-change.py` to validate the roll-back of Active Timestamp using Pending Dataset.
----
Background:
- The check …
> [dataset] move Active Dataset replacement check in `PendingDatasetManager`

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- src/core/net/nd6.hpp
This commit moves the tracking of the RA header of locally generated RA messages from `TxRaInfo` to the `RxRaTracker` class. The tracked RA header is used when `RoutingManager` sends an RA, ensuring consistent RA headers across all RAs emitted from the device.
This aligns the logic by having `RxRaTracker` track all information from received RAs and simplifies stale time calculations.
----
~This PR contains the commit from https://github.com/openthread/openthread/pull/10255. Please check and review the last commit. Thanks.~
> [routing-manager] move tracking of local RA header to `RxRaTracker`

- third_party/mbedtls/mbedtls-config.h
> [mbedtls] remove config workaround

- src/core/net/mdns.cpp
- src/core/net/mdns.hpp
- tests/unit/test_mdns.cpp
This commit updates the native mDNS implementation to ensure the callback is invoked when a host is registered without any address (effectively unregistering the host and removing any previously registered addresses for the host-name).
The implementation ensures the callback is invoked after returning from the `RegisterHost()` call (invoked from a posted tasklet), as required by the mDNS API definitions.
Additionally, the `test_mdns` unit test is updated to cover registering a host with no address for the first time or updating a previous registration.
----
Fixes https://github.com/openthread/openthread/issues/10262
> [mdns] ensure callback is invoked when registering host with no address

- src/core/meshcop/dataset_manager.hpp
- src/core/meshcop/dataset_manager_ftd.cpp
This commit combines the `protected` and `private` sections of `DatasetManager`, adding `ActiveDatasetManager` and `PendingDatasetManager` as `friend`s. This simplifies the code and aligns with the goal of having more functions handled by the `DatasetManager` base class.
> [dataset-manager] combine `protected` and `private` sections

- src/posix/platform/radio.cpp
- src/posix/platform/spinel_driver_getter.hpp
- src/posix/platform/spinel_manager.cpp
- src/posix/platform/spinel_manager.hpp
This PR tries to resolve the issue in #10221 in another approach.
The PR adds a seperate header `posix/platform/spinel_driver_getter.hpp`
to expose `GetSpinelDriver` to the external posix app. `spinel_driver_getter.hpp`
doesn't include anything from OT core and is safe to be included by external
code. The API isn't added in `openthread-system.h` because it's a C header
while spinel_driver.hpp is a cpp header.
> [posix] add spinel driver getter to allow external app to access

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit moves functionality from `RoutingManager` to `RxRaTracker`:
- The `ShouldProcessPrefix/RouteInfoOption()` methods, which decide whether to skip or process a PIO/RIO, are moved to `RxRaTracker`.
- `RxRaTracker` is directly notified on network data change, using its new `HandleNetDataChange()` method. This replaces `UpdateRxRaTrackerOnNetDataChange()`.
> [routing-manager] move decision to process PIO/RIO to `RxRaTracker`

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit updates how `RxRaTracker` decides whether to process PIO/RIO from a received RA message:
- The checks are performed directly in related `Process()` methods, removing the `ShouldProcess()` methods.
- The check `Get<RoutingManager>().IsRunning()` is removed as it is already checked before processing the RA message.
- The check `IsValidOmrPrefix()` is removed for RIO route prefixes. Instead, all route prefixes are tracked, regardless of length (excluding link-local or multicast prefixes). With this change, there is no longer a need to specifically check and allow the default route.
----
~This PR currently contains the commit from https://github.com/openthread/openthread/pull/10270. Please check and review the last commit. Thanks.~
> [routing-manager] update and simplify decisions for processing PIO/RIO

- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
- src/core/thread/mle.cpp
- Update `DatasetManager::Clear()` to stop delay timer if it is Pending Dataset.
- Remove `PendingDatasetManager::ClearNetwork()` (use `Clear()` instead).
> [dataset] simplify `Clear()` methods

- include/openthread/border_routing.h
- include/openthread/instance.h
- src/cli/cli_br.cpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- tests/unit/test_routing_manager.cpp
This commit adds `mIsLocalDevice` in the `Router` class to track whether it represents the local device (e.g., another software entity on this device). This information is used to skip sending NS probes to this router. Tracking this information directly in the `Router` class is safer than checking the address using `mInfra.HasAddress()`, as the addresses may have changed since the last RA was received. This commit exposes this information through the public APIs and CLI command, and updates `test_routing_manager` unit test to validate the new flag.
> [routing-manager] track whether a discovered router is local device

- src/lib/spinel/radio_spinel.cpp
The RcpMinHostApiVersion capability should be parsed from SPINEL_PROP_CAPS response using SPINEL_CAP_RCP_MIN_HOST_API_VERSION, rather than using SPINEL_PROP_RCP_MIN_HOST_API_VERSION.
> [spinel] parse correct RcpMinHostApiVersion capability

- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
- src/core/meshcop/dataset_manager_ftd.cpp
- src/core/thread/mle.cpp
This commit simplifies the `Restore()` methods:
- A private overload `Restore(const Dataset&)` is added, taking the read `Dataset` as input to avoid duplicate reads.
- The public `Restore(void)` is updated to use the new private `Restore(const Dataset&)`.
- The `HandleDetach()` method is removed, and its use in the `Mle` class is replaced with `Restore()`.
> [dataset-manager] simplify `Restore()`

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit introduces the following changes:
- Adds a new callback `HandleLocalOnLinkPrefixChanged()` for `OnLinkPrefixManager` to signal changes to the local on-link prefix (derived from the extended PAN ID).
- Modifies `RxRaTracker` to always ignore a PIO prefix matching the local on-link prefix, regardless of the current state of `OnLinkPrefixManager`. Such a PIO originates from another Thread border router connected to the same Thread network and is not used by `OnLinkPrefixManager` to decide whether it needs to advertise the local on-link prefix.
- Updates `RxRaTracker` to be notified when the local on-link prefix changes. In its `HandleLocalOnLinkPrefixChanged()`, it removes any prefixes in the table matching the new prefix.
> [routing-manager] simplify how `RxRaTracker` handles local on-link prefix

- src/core/meshcop/dataset.cpp
- src/core/meshcop/dataset.hpp
- tests/unit/test_dataset.cpp
This commit adds a method `Dataset::IsSubsetOf()` to check whether one dataset is a subset of another. A dataset is considered a subset if all its TLVs, excluding Active/Pending Timestamp and Delay Timer TLVs, are present in the other dataset with exactly matching values.
This new method simplifies `Dataset::Info::IsSubsetOf()`. The unit test `test_dataset` is updated to validate the `IsSubsetOf()()` method.
> [dataset] simplify `IsSubsetOf()`

- src/core/thread/mle_router.cpp
This commit fixes the warning, when logs are disabled:
`src/core/thread/mle_router.cpp:1775:14: warning: variable "storedCount" set but not used [-Wunused-but-set-variable]`
> [mle] fix warning with storedCount

- src/core/border_router/routing_manager.cpp
- src/core/coap/coap.cpp
- src/core/common/timer.cpp
- src/core/common/timer.hpp
- src/core/meshcop/commissioner.cpp
- src/core/net/dns_client.cpp
- src/core/net/dnssd_server.cpp
- src/core/net/ip6_mpl.cpp
- src/core/net/sntp_client.cpp
- src/core/net/srp_advertising_proxy.cpp
- src/core/net/srp_client.cpp
- src/core/net/srp_server.cpp
- src/core/thread/mle.cpp
- src/core/thread/network_data_leader_ftd.cpp
- src/core/utils/slaac_address.cpp
This commit introduces `NextFireTime`, a helper object for tracking the next fire time along with the current time. It provides an `UpdateIfEarlier(Time)` method to update the tracked next fire time with a new given time only if it is earlier.
The `NextFireTime` class simplifies a common code pattern used across modules to determine the earliest fire time when scheduling a timer. It also ensures that the next fire time is never set before the current time, improving code safety.
> [timer] add `NextFireTime` class

- src/cli/cli_tcp.cpp
- tests/fuzz/fuzzer_platform.cpp
- tests/fuzz/oss-fuzz-build
The #10286 detected the issue with OSS-Fuzz. This PR introduces two independent commits which should resolve the issue (checked on my fork) and enhance fuzzing by fixing a typo.
**[cli] fix memory leak on TCP init failure**
This commit fixes potential memory leak for CLI TCP module (`tcp init tls [...]`)
**[fuzz] fix typo and enable SRP Advertising Proxy**
This commit fixes the typo and enables SRP_ADV_PROXY - now, when typo is fixed,
dependent components had to be enabled.
> [fuzz] fix memory leak in TCP and enhance fuzzing

- include/openthread/dataset_updater.h
- include/openthread/instance.h
- src/core/meshcop/dataset.cpp
- src/core/meshcop/dataset.hpp
- src/core/meshcop/dataset_updater.cpp
- src/core/meshcop/dataset_updater.hpp
This commit simplifies the `DatasetUpdater`:
- Restricts `DatasetUpdater::RequestUpdate()` to be used only when the device is fully configured and has a valid Active Dataset; otherwise, it returns `kErrorInvalidState`. This simplification allows for the removal of the timer (previously used to delay the update if no Active Dataset was present).
- Adds a check in `RequestUpdate()` to determine if the requested Dataset changes are already present in the current Active Dataset, returning `kErrorAlready` if so.
- Enhances `RequestUpdate()` to prepare and set the Pending Dataset immediately. It stores the requested Dataset as a sequence of TLVs and retains the Active and Pending Timestamp values for later use in determining update success or failure.
- Simplifies the code for checking Dataset …
> [dataset-updater] enhance `DatasetUpdater`

- src/core/net/mdns.cpp
- src/core/net/mdns.hpp
This commit updates the mDNS module to use the recently introduced general-purpose `NextFireTime` class, replacing the module-specific `TimerContext` class.
> [mdns] use `NextFireTime` class

- examples/platforms/utils/link_metrics.cpp
- examples/platforms/utils/link_metrics.h
Enh-ack link metrics required to reset/clear when radio(RCP) is reset to clear existing data. To support it, added API to reset/clear linked list of enh-ack link metrics.
> [utils] add API to reset/clear linked list of enh-ack link metrics

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- tests/unit/test_routing_manager.cpp
This commit updates `PdPrefixManager` to use the newly added `GetDeprecationTime()` method for managing the lifetime of a DHCPv6 PD prefix. This method calculates the deprecation time using the prefix preferred lifetime directly, instead of relying on the RA stale time constant  `GetStaleTime()`.
While the PD prefix may be determined by processing RA messages received on the Thread interface, the RA stale time is not relevant in this context. The RA stale time is only applicable to RA messages received over infra-if. It specifies the time that can pass after the last RA from a particular router on infra-if before assuming the router might be unavailable and triggering Router Solicitation (RS) messages.
> [routing-manager] fix lifetime management of PD prefix

- src/core/thread/child.cpp
- src/core/thread/child.hpp
- src/core/thread/dua_manager.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
This commit simplifies how `ProcessAddressRegistrationTlv()` signals DUA address changes. Signaling now occurs after all child addresses are registered, using a new `SignalDuaAddressEvent()` method. This method checks the old and new DUA addresses to determine the appropriate event to signal.
Additionally, `Child::GetDomainUnicastAddress()` is updated to return an `Error` and copy the DUA address into a provided `Ip6::Address` reference.
> [mle] simplify signaling of DUA address change

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- src/core/common/random.cpp
This commit updates constants in `RoutingManager`. Timing constants are now consistently specified as an interval with an associated jitter, where the actual interval is randomly selected within the range `[interval - jitter, interval + jitter]`.
The initial transmission of three RAs with a short interval of 16 seconds (± 2 seconds jitter) remains unchanged. However, subsequent RA transmissions now use a regular beacon interval of 3 minutes (± 15 seconds jitter), replacing the previous random interval selection within `[200, 600]` seconds.
The selection of 3 minutes as the regular RA beacon interval aligns the implementation with the latest stub router RFC draft's `RA_BEACON_INTERVAL` default value.
> [routing-manager] update and simplify RA beacon timing

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit updates the calculation of stale time for a discovered local RA header (to mirror), incorporating the default route lifetime specified in the header when it is non-zero, in addition to the RA stale time constant. This ensures proper behavior even if the RA header default route lifetime is shorter than the RA stale time.
Additionally, this commit adds `CalculateExpirationTime()` to determine the expiration time from a given update time and lifetime duration in seconds. If the given lifetime exceeds the supported range of `TimeMilli` (~24 days), it clamps the value to ensure time calculations remain within the valid `TimeMilli` range.
> [routing-manager] update stale time calculation for local RA header

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
This commit adds helper methods to `Mle::RxMessage` for reading and processing specific TLVs:
- `ReadModeTlv()`: Reads the Mode TLV as a bit mask and converts it to a `DeviceMode`.
- `ReadVersionTlv()`: Reads the Version TLV and verifies that it is at least 1.1 (the minimum supported version).
- `ReadAndMatchResponseTlvWith(const TxChallenge &)`: Reads the Response TLV and matches it against a given challenge.
> [mle] add helper methods to `RxMessage`

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- tests/unit/test_routing_manager.cpp
This commit updates the determination of stale times for discovered on-link or route prefixes. The stale time is now calculated per unique prefix. If multiple routers advertise the same on-link or route prefix, the stale time for the prefix is set to the latest among all corresponding entries.
This addresses an issue in the previous implementation where, for on-link prefixes, the stale time was determined as the latest stale time over all on-link entries, regardless of the actual prefixes. For route prefixes, the earliest stale time was used, also disregarding the possibility of multiple routers advertising the same prefix.
This commit also updates the `test_routing_manager` unit test to validate the corrected stale time calculation.
> [routing-manager] fix and enhance prefix stale time calculation

- src/core/meshcop/dataset_updater.cpp
- src/core/meshcop/timestamp.cpp
- src/core/meshcop/timestamp.hpp
This commit updates `Timestamp::AdvanceRandomTicks()` to ensure that the seconds value is incremented only if the ticks value overflows.
> [meshcop] update `Timestamp::AdvanceRandomTicks()`

- src/core/common/encoding.hpp
This allows their use when defining constant values.
> [encoding] declare `HostSwap()` functions as `constexpr`

- src/core/thread/mle.cpp
- src/core/thread/mle_tlvs.hpp
This is used to simplify `Mle::HandleParentResponse()`.
> [mle] add `ConnectivityTlv::IsSingleton()`

- src/lib/spinel/openthread-spinel-config.h
Following #10212, this PR removes the including of `openthread-core-config.h`
to make `lib/spinel` more portable.
`openthread-spinel-config.h` is included by many modules like 
`spinel_encoder`, `spinel_decoder`. To use these modules in external
projects, we need to remove the including of `openthread-core-config.h`.
> [spinel] remove including openthread-core-config.h

- third_party/mbedtls/BUILD.gn
- third_party/mbedtls/CMakeLists.txt
To resolve this build error:
```
fatal error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
[298/511] Building CXX object third_party/openthread/repo/src/core/CMakeFiles/openthread-ftd.dir/utils/slaac_address.cpp.o
ninja: build stopped: subcommand failed.
```
https://github.com/openthread/ot-br-posix/actions/runs/9359945142/job/25764511252?pr=2311
> [mbedtls] remove `-Wno-unused-but-set-variable`

- src/core/meshcop/dataset_manager.cpp
This commit updates and fixes how the Pending Dataset delay timer is started. It is now started only after the timestamps are checked and the local Pending Dataset is updated and saved to non-volatile storage from the `LocalSave()` method.
In particular, we no longer start the delay timer from the `Save()` method, which reads the `Dataset` from a received `Message`. This is because we may receive a Pending Dataset with a timestamp that is older than the currently saved local Pending Dataset. In this case, the local Dataset is correctly not updated but without this change, we could start the delay timer for the received stale Pending Dataset.
> [dataset-manager] enhance starting of Pending Dataset delay timer

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- tests/unit/test_routing_manager.cpp
This commit renames the entry stale time constant to `kStaleTime` and sets it to 10 minutes (from 30 minutes). This change aligns the `RoutingManager` with the recommended value in the latest stub router RFC draft (`STALE_RA_TIME`).
The unit test `test_routing_manager` is also updated to reflect this new constant.
> [routing-manager] update stale time constant to 10 minute

- src/core/net/ip6.cpp
Currently, sending an IPv6 multicast destined packet encoded in otMessage with the otIp6Send() function reports an error kErrorNoRoute if "host loopback allowed" flag is disabled (despite of packet being properly passed to Mesh Forwarder). This commit changes a flag checking statement to return kErrorNone instead.
> [ip6] do not report an error for disabled host loopback

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
This commit contains minor enhancements to `HandleParentResponse()`:
- Variable name `linkMarginOut` is used for the Link Margin TLV value included in the response from the parent candidate. This is used to `SetLinkQualityOut()`.
- `twoWayLinkMargin` variable name is now used to show the two-way link margin.
- `IsBetterParent()` is updated to calculate the two-way link quality for the new parent candidate from the two-way link margin (instead of getting it as a parameter).
> [mle] minor enhancements to `HandleParentResponse()`

- src/core/meshcop/dataset.cpp
- src/core/meshcop/dataset.hpp
- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager_ftd.cpp
This commit introduces new helper methods in the `Dataset` class to write or remove a Timestamp TLV (Active or Pending) to/from the Dataset. These are added alongside the existing `ReadTimestamp()` method.
> [dataset] add `WriteTimestamp()` and `RemoveTimestamp()`

- src/core/meshcop/dataset.hpp
- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
- src/core/meshcop/dataset_manager_ftd.cpp
- src/core/meshcop/dataset_updater.cpp
- src/core/meshcop/timestamp.cpp
- src/core/meshcop/timestamp.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
- tests/unit/test_meshcop.cpp
This commit enhances the handling of `Timestamp`.
Methods `SetToInvalid()` and `IsValid()` are added to the `Timestamp` class. The value where all bytes are set to `0xff` is used to represent an invalid `Timestamp`. This corresponds to max seconds, max ticks with the authoritative (`U`) flag set.
This helps simplify `DatasetManager`, where we need to track local and network Active/Pending timestamps, which may not be present. These are now represented by setting the `Timestamp` to the invalid value (replacing the earlier model where a `Timestamp` pointer was used with `nullptr` representing an invalid timestamp).
This allows us to simplify the `Timestamp::Compare()` method, now getting two `Timestamp &` instead of `Timestamp *`. With this, we can also define comparison operator overloads …
> [timestamp] add `IsValid()` and comparison operator overloads

- src/core/meshcop/dataset_updater.cpp
- src/core/thread/mle.cpp
This commit removes the `GetSeconds() != 0` check in `Mle::AppendPendingTimestampTlv()`. This allows `DatasetUpdater` to use a Pending Timestamp with random ticks and a zero seconds value if there is no pending Dataset.
----
~This PR currently contains commits from https://github.com/openthread/openthread/pull/10325 and https://github.com/openthread/openthread/pull/10320. Please check the last commit. Thanks.~
> [mle] allow appending pending timestamp TLV with zero seconds

- src/core/meshcop/dataset_manager.hpp
- src/core/meshcop/dataset_manager_ftd.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
This commit refactors the code for preparing and appending MLE TLVs, moving it from `DatasetManager` to the `Mle` class for better alignment of responsibilities.
It adds `TxMessage::AppendDatasetTlv()`, which appends an Active or Pending Dataset (if present) to an MLE message following the proper MLE TLV format. This includes removing the corresponding `Timestamp` from the dataset, as MLE messages include timestamps using their own MLE TLVs rather than within the dataset itself.
----------
~This PR currently contains the commit from https://github.com/openthread/openthread/pull/10333. Please check and review the last commit. Thanks.~
> [mle] add `Mle::TxMessage::AppendDatasetTlv()`

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
This commit adds `AppendActiveAndPendingTimestampTlvs()` helper method, which appends both Active and Pending Timestamp TLVs to the message. This helps simplify the code as the two TLVs are almost always included together in different MLE messages.
> [mle] add `TxMessage::AppendActiveAndPendingTimestampTlvs()`

- src/posix/main.c
- src/posix/platform/include/openthread/openthread-system.h
- src/posix/platform/system.cpp
This PR adds a new posix sys API `otSysInitCoprocessor` which only
initializes the platform spinel component. (Reset the co-processor
and get the type)
The intention is to let the app to get the co-processor type without
creating the otInstance. Currently only `otSysInit` can be called
which creates the otInstance. However in some cases, we don't want to
create the instance at the early stage. For example, in this [PR](https://github.com/openthread/ot-br-posix/pull/2309/),
after knowing the co-processor type, `otSysInit` will be again called.
If using `otSysInit` to get the co-processor type at first, otInstance 
will be created twice.
This PR doesn't break the existing usage of `otSysInit`. `otSysInitCoprocessor`
isn't required to be called at first.
Depends-On: …
> [posix] extract co-processor init out of otSysInit

- examples/platforms/simulation/ble.c
- include/openthread/ble_secure.h
- include/openthread/instance.h
- include/openthread/platform/ble.h
- include/openthread/tcat.h
- src/cli/cli_tcat.cpp
- src/core/api/ble_secure_api.cpp
- src/core/meshcop/meshcop.cpp
- src/core/meshcop/tcat_agent.cpp
- src/core/meshcop/tcat_agent.hpp
- src/core/radio/ble_secure.cpp
- src/core/radio/ble_secure.hpp
- src/posix/platform/ble.cpp
- tests/scripts/expect/cli-tcat-advertisement.exp
- tests/unit/test_platform.cpp
- tests/unit/test_tcat.cpp
Commit introduces implementation of TCAT advertisement over BLE compialnt with Thread 1.3.1 specification.
> [tcat] implement tcat advertisement

- src/core/net/mdns.cpp
- src/core/net/mdns.hpp
- tests/unit/test_mdns.cpp
This PR adds support for Legacy Unicast Response feature in mDNS module.
> [mdns] add support for legacy unicast response feature

- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
This commit adds `ReadAndSave{Active/Pending}Dataset()` helper methods to `Mle::RxMessage` to read the Active or Pending Dataset from a received MLE message and save it in the corresponding `DatasetManager`.
This commit also refactors the code for parsing the MLE TLVs, moving it from `DatasetManager` to the `Mle` class for better alignment of responsibilities.
> [mle] add `Mle::RxMessage::ReadAndSave{Active/Pending}Dataset()`

- src/core/net/srp_client.cpp
- src/core/net/srp_client.hpp
- tests/unit/test_srp_server.cpp
This commit updates `Srp::Client` to use sequential message IDs, replacing the previous model where message IDs were generated randomly.
When processing responses from the server, older message IDs are accepted as long as the corresponding older message was identical to the latest one. This helps in situations where the server's response may be delayed  (e.g., due to network congestion) and the client retry mechanism is retransmitting the same update message.
This commit also adds a unit test `TestSrpClientDelayedResponse()` to validate the new behavior.
----
Relates to [SPEC-1290](https://threadgroup.atlassian.net/browse/SPEC-1290)
> [srp-client] use sequential message IDs & allow older response IDs

- src/core/api/thread_api.cpp
- src/core/mac/mac.cpp
- src/core/thread/key_manager.cpp
- src/core/thread/key_manager.hpp
- src/core/thread/mle.cpp
- tests/scripts/thread-cert/Cert_5_8_02_KeyIncrement.py
- tests/scripts/thread-cert/Cert_5_8_03_KeyIncrementRollOver.py
- tests/scripts/thread-cert/Cert_6_6_01_KeyIncrement.py
- tests/scripts/thread-cert/Cert_6_6_02_KeyIncrementRollOver.py
- tests/scripts/thread-cert/thread_cert.py
This commit updates the resetting of the Key Switch Guard Timer. It is now reset under two conditions:
- The device itself triggers a key rotation and moves to the next key sequence after the rotation time has passed since the last switch.
- The device receives a MAC or MLE message with an incoming key index matching the next key index. Regarding MLE messages, this rule is applied regardless of the message being classified as Authoritative or Peer.
---
Relates to [SPEC-1293](https://threadgroup.atlassian.net/browse/SPEC-1293)
> [key-manager] update how the "Key Switch Guard Timer" is reset

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
This commit adds `AppendLinkAndMleFrameCounterTlvs()` to `Mle::TxMessage` for appending both Link and MLE Frame Counter TLVs. This mirrors the existing `RxMessage` method for reading these counters.
> [mle] add `TxMessage::AppendLinkAndMleFrameCounterTlvs()`

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit adds the `IsReachable()` helper method to `Router` class, which checks whether a router is considered reachable. It replaces the previous comparisons of `mNsProbeCount` in the code, improving readability. Neighbor Solicitation (NS) messages are used to determine reachability if the router has not been heard from for some time.
> [routing-manager] add `RxRaTracker::Router::IsReachable()`

- src/core/net/udp6.cpp
This commit modifies `Udp::Open()` to clear all properties of the passed-in `aSocket` using the `Clear()` method. This replaces the existing code, which only cleared the socket and peer address and port numbers. This change ensures that `void *mHandle` member variable in `otUdpSocket` is also set to `nullptr` before invoking platform UDP `otPlatUdpSocket()`.
> [udp] clear all properties in `SocketHandle` from `Udp::Open()`

- src/core/meshcop/dataset.cpp
- src/core/meshcop/dataset.hpp
- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
This commit refactors methods that save or read a specified Dataset TLV in/from secure storage under `PLATFORM_KEY_REFERENCES`. These methods are moved from the `Dataset` class to the `DatasetManager` class, consolidating related functionality and aligning with the responsibilities of each class. The `Dataset` class is focused on appending/parsing TLVs, while the `DatasetManager` class is responsible for managing and saving the Active and Pending Datasets.
> [dataset] move secure storage methods to `DatasetManager`

- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/network_data_service.cpp
- src/core/thread/router_table.cpp
This commit adds the `Mle::GetLeaderRloc16()` method, which returns the RLOC16 of the Leader. This simplifies code that previously used `GetLeaderId()` followed by a conversion to RLOC16.
> [mle] add `GetLeaderRloc16()` helper method

- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
This commit updates the code to use `RouterIdMatch()` for comparing the Router IDs of two given RLOC16 values. Additionally, it simplifies the `IsMinimalChild()` method.
> [mle] use `RouterIdMatch()` to compare Router IDs of two RLOC16 values

- src/core/api/thread_api.cpp
- src/core/api/udp_api.cpp
- src/core/meshcop/commissioner.cpp
- src/core/net/dhcp6_client.cpp
- src/core/net/ip6_mpl.cpp
- src/core/net/srp_client.cpp
- src/core/thread/address_resolver.cpp
- src/core/thread/anycast_locator.cpp
- src/core/thread/dua_manager.cpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/network_data_publisher.cpp
- src/core/thread/tmf.cpp
- src/core/utils/mesh_diag.cpp
- tests/unit/test_child.cpp
- tests/unit/test_srp_server.cpp
This commit renames the methods for retrieving mesh local addresses to `GetMeshLocalRloc()` and `GetMeshLocalEid()` (from `GetMeshLocal16()` and `GetMeshLocal64()`, respectively) to align with the terminology used in the Thread specification. Member and local variables are also renamed accordingly.
> [mle] rename mesh local address methods to use `Rloc` and `Eid`

- src/core/net/ip6.cpp
Use ToUlong cast helper to cast the uint32_t and use %lu format specifier to fix warning on all platforms
> [ip6] fix warning when logging enabled

- src/core/api/thread_api.cpp
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager_ftd.cpp
- src/core/net/nd_agent.cpp
- src/core/thread/address_resolver.cpp
- src/core/thread/dua_manager.cpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mlr_manager.cpp
- src/core/thread/network_data_notifier.cpp
- src/core/thread/network_data_service.cpp
- src/core/thread/tmf.cpp
- src/core/thread/tmf.hpp
- src/core/utils/mesh_diag.cpp
This commit enhances the generation of RLOC and ALOC addresses in the `Mle` class.
Methods retrieving RLOC/ALOC addresses no longer return an `Error` and are now `void`. The previous check for a valid `GetRloc16()` value, which returned `kErrorDetach` if unset, is removed because this scenario only occurred before the device's initial attachment. Post-attachment, the RLOC16 remains valid even if the device is detached. This change simplifies the code since RLOC/ALOC address retrieval happens after the initial attachment.
Additional enhancements include:
-  Changing the input parameter order in `GetCommissionerAloc()` to match `GetServiceAloc()`.
-  Using `Ip6::Address::SetToRoutingLocator()` to construct RLOC addresses, harmonizing address generation and improving code readability.
> [mle] enhance RLOC and ALOC address generation

- include/openthread/border_routing.h
- include/openthread/instance.h
- src/cli/README_BR.md
- src/cli/cli_br.cpp
- src/core/border_router/routing_manager.cpp
This commit adds `mIsReachable` to the `otBorderRoutingRouterEntry` structure to indicate whether a router is reachable. A router is marked unreachable after it fails to respond to multiple Neighbor Solicitation (NS) probes. Additionally, the `br` CLI commands are updated to display this information.
> [routing-manager] add `mIsReachable` to `otBorderRoutingRouterEntry`

- src/core/coap/coap.cpp
- src/core/coap/coap.hpp
- src/core/meshcop/joiner_router.cpp
- src/core/meshcop/joiner_router.hpp
- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
- src/core/net/dhcp6_client.cpp
- src/core/net/dhcp6_client.hpp
- src/core/net/dhcp6_server.cpp
- src/core/net/dhcp6_server.hpp
- src/core/net/dns_client.cpp
- src/core/net/dns_client.hpp
- src/core/net/dnssd_server.cpp
- src/core/net/dnssd_server.hpp
- src/core/net/sntp_client.cpp
- src/core/net/sntp_client.hpp
- src/core/net/srp_client.cpp
- src/core/net/srp_client.hpp
- src/core/net/srp_server.cpp
- src/core/net/srp_server.hpp
- src/core/net/udp6.cpp
- src/core/net/udp6.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- tests/unit/test_srp_server.cpp
This commit adds a new template `Udp::SocketIn<Owner, RxHandlerPtr>`, which defines a UDP socket for use within a specified `Owner` class. It includes a `HandleUdpReceive()` member method callback for processing received messages. This model, similar to `TimerMilliIn`, eliminates the need for each socket user to define boilerplate code for providing a static member function that simply casts and calls the member method. This is now handled by the template `SocketIn` class. The `Udp::Socket::Open()` method is also modified to no longer require the callback and context parameters.
> [udp] add template `SocketIn` class for easier socket usage

- src/lib/spinel/spinel_driver.hpp
- src/posix/platform/include/openthread/openthread-system.h
- src/posix/platform/system.cpp
This PR adds a new posix openthread system API `otSysGetSpinelDriver`
to get the instance of spinel driver.
As discussed in [here](https://github.com/openthread/ot-br-posix/pull/2329#discussion_r1639576181), we should not access posix headers from
external 
procjects. So we add a openthread system API with opaque class to make
`SpinelDriver` accessible.
> [posix] add OT sys API to get the spinel driver

- src/cli/README_UDP.md
- src/cli/cli_udp.cpp
> [cli] `udp bind` doc update to clarify that multicast address cannot be used as argument

- src/posix/platform/rcp_caps_diag.cpp
- src/posix/platform/rcp_caps_diag.hpp
This commit calls RadioSpinel `Set()`, `Get()`, `Insert()` and `Remove()` functions to check whether the RCP supports `RadioSpinel` used Spinel properties to check the Spinel compatibility between the host and RCP.
> [posix] checks whether the RCP support specified Spinel properties

- tools/otci/otci/command_handlers.py
The otci reports warning `DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead`. This commit updates the otci to fix this warning.
> [otci] fix the `setDaemon() is deprecated` warning

- src/core/backbone_router/backbone_tmf.cpp
- src/core/net/dnssd_server.cpp
- src/core/net/ip6.cpp
- src/core/net/ip6_address.cpp
- src/core/net/ip6_address.hpp
- src/core/net/ip6_filter.cpp
- src/core/net/netif.cpp
- src/core/net/srp_advertising_proxy.cpp
- src/core/net/srp_client.cpp
- src/core/thread/indirect_sender.cpp
- src/core/thread/link_metrics.cpp
- src/core/thread/lowpan.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle.cpp
- src/core/thread/neighbor_table.cpp
- src/core/thread/network_diagnostic.cpp
- src/core/thread/tmf.cpp
- src/posix/platform/multicast_routing.cpp
This commit adds `IsLinkLocalUnicastOrMulticast()` to `Ip6::Address` to indicate whether the address is either a link-local unicast or a link-local multicast address.
The existing `IsLinkLocal()` is renamed to `IsLinkLocalUnicast()` to clarify its purpose and align its name with `IsLinkLocalMulticast()` and the new method.
> [ip6] add `Ip6::Address::IsLinkLocalUnicastOrMulticast()`

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
This commit removes the `Mle::GetNextHop()` method, which returned the parent RLOC16 (when the parent state was valid) irrespective of a given destination.
The `Mle::GetNextHop()` method was only used on MTD builds and from `MeshForwarder::UpdateIp6Route()` method, where
`mle.GetNextHop(Mac::kShortAddrBroadcast)` served as an indirect way to get the parent RLOC16. This is now replaced with a direct `GetParentRloc16()` call, clarifying the intended purpose.
On FTD builds, the `MleRouter::GetNextHop()` is used instead of `Mle::GetNextHop()`. The `MleRouter` method remains unchanged. Since it would also return the parent's RLOC16 when the device is acting as a child, using `GetParentRloc16()` covers this case as well.
> [mle] replace `Mle::GetNextHop()` with `GetParentRloc16()`

- examples/platforms/simulation/diag.c
- include/openthread/diag.h
- include/openthread/instance.h
- include/openthread/platform/diag.h
- script/check-size
- script/git-tool
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/api/diags_api.cpp
- src/core/diags/factory_diags.cpp
- src/core/diags/factory_diags.hpp
- src/lib/spinel/radio_spinel.cpp
- src/lib/spinel/radio_spinel.hpp
- src/ncp/ncp_base.cpp
- src/ncp/ncp_base.hpp
- src/posix/platform/radio.cpp
- src/posix/platform/rcp_caps_diag.cpp
- src/posix/platform/rcp_caps_diag.hpp
- tests/fuzz/fuzzer_platform.cpp
- tests/unit/test_platform.cpp
- tests/unit/test_platform.h
The length of diag output messages is limited by the diag buffer size. Developers have to change the diag buffer size to allow diag module to output long messages. If diag output messages become longer and longer, developers have to keep changing the diag buffer size.
This commit adds an output callback to diag module to output diag messages. Then the length of diag output messages won't be limited by the diag buffer size.
Depends-On: openthread/ot-nrf528xx#822
> [diag] replace diag output buffer with diag output callback

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit simplifies `RxRaTracker::HandleRouterTimer()`. When all NS probes to a router fail and it is marked as unreachable, `HandleRouterTimer()` now directly removes/deprecates its route/on-link prefixes, replacing a separate method previously used for this purpose.
Additionally, a new helper method, `ShouldCheckReachability()`, is added to check if a reachability check (sending NS probes) is needed. This check is performed only if the router is not already marked as unreachable and is not the local device itself.
> [routing-manager] simplify `RxRaTracker::HandleRouterTimer()`

- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
This commit removes the `MleRouter::GetNextHop()` method and instead directly uses `RouterTable::GetNextHop()`. This improves consistency across all modules.
> [mle] remove `GetNextHop()` and directly use `RouterTable` method

- src/core/thread/address_resolver.cpp
- src/core/thread/child_table.cpp
- src/core/thread/child_table.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
This commit adds the `HasMinimalChild()` method to the `ChildTable` class and moves the logic for checking if a device has an MTD child with a given RLOC16 from the `MleRouter` class to `ChildTable`. This aligns better with the `ChildTable` class's responsibility of managing all children and providing methods to search and find child entries in the table.
> [child-table] add `HasMinimalChild()` and move logic from `MleRouter`

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_types.hpp
- src/core/thread/network_data.cpp
- src/core/thread/network_data_leader.cpp
- src/core/thread/network_data_notifier.cpp
- src/core/thread/network_data_publisher.cpp
- src/core/thread/router_table.cpp
- src/core/utils/mesh_diag.cpp
This commit adds `IsRouterRloc16()` (replacing `IsActiveRouter()`), which checks whether a given RLOC16 refers to a router and not a child. The new name clarifies that it is only a check on the RLOC16 value and does not verify if the corresponding router ID is allocated and active. This commit also adds `IsChildRloc16()`, which is similar to `IsRouterRloc16()` and checks if the given RLOC16 is for a child. This simplifies the code and improves readability.
> [mle] add `IsRouterRloc16()` and `IsChildRloc16()`

- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
This commit moves the `CheckReachability()` & `ResolveRoutingLoops()` methods from the `MleRouter` class to the `MeshForwarder` class now as `private` methods. This consolidates all `CheckReachability()` overloads within the `MeshForwarder` class.
> [mesh-forwarder] move `CheckReachability()` to `MeshForwarder`

- src/posix/platform/netif.cpp
This fixes a build error when the pre-processor define `OPENTHREAD_POSIX_CONFIG_NETIF_PREFIX_ROUTE_METRIC` is set:
```
/usr/src/ot-br-posix/third_party/openthread/repo/src/posix/platform/netif.cpp:486:26: error: ‘kLinkLocalScope’ does not name a type
486 |         static constexpr kLinkLocalScope = 2;
|                          ^~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```
> [posix] fix build with custom netif prefix route set

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder_ftd.cpp
- tests/toranj/cli/test-030-anycast-forwarding.py
- tests/toranj/start.sh
This commit updates how messages with an ALOC destination are forwarded. If the chosen ALOC destination is a child, its parent is used as the mesh destination unless the device itself is the parent. Additionally, if the selected ALOC destination is a sleepy child of the device, the parent node ensures to prepare the message for indirect transmission. These changes ensure correct forwarding to ED or SED devices when they register a service and want to receive messages on their service ALOC.
This commit also adds a new test, `test-030-anycast-forwarding.py`, which validates the forwarding to ALOC addresses on both ED and SED devices.
> [mesh-forwarder] update forwarding messages to ALOC destination

- src/core/thread/child.cpp
This commit modifies `Child::RemoveIp6Address()` to update the `mMlrToRegisterMask` and `mMlrToUnregisterMask` when a registered child IPv6 address entry is removed from the list. These bit-vector masks track the MLR state associated with the entry using its index in the array. Since `Array::Remove()` replaces the deleted entry with the last one in the array, the MLR masks are also updated to reflect this change.
---
~This PR contains the commit from https://github.com/openthread/openthread/pull/10422. Please check and review the last commit. Thanks.~
Fixes the issue mentioned here -> https://github.com/openthread/openthread/pull/10422#discussion_r1649497434
> [child] update MLR masks when removing registered IPv6 addresses

- src/core/meshcop/tcat_agent.cpp
This commit updates `HandleSetActiveOperationalDataset()` by removing the extra conversion from `Dataset` to `Dataset::Tlvs` and directly using the `Dataset` when saving the Active Operational Dataset.
> [tcat-agent] use `Dataset` directly when setting Active Dataset

- src/core/api/thread_api.cpp
- src/core/backbone_router/bbr_leader.cpp
- src/core/backbone_router/bbr_leader.hpp
- src/core/backbone_router/bbr_local.cpp
- src/core/backbone_router/bbr_manager.cpp
- src/core/backbone_router/bbr_manager.hpp
- src/core/net/srp_server.cpp
- src/core/thread/address_resolver.cpp
- src/core/thread/address_resolver.hpp
- src/core/thread/anycast_locator.cpp
- src/core/thread/child_table.cpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/neighbor.hpp
- src/core/thread/network_data_leader_ftd.cpp
- src/core/thread/network_data_notifier.cpp
- src/core/thread/network_data_service.cpp
- src/core/thread/network_data_tlvs.hpp
- src/core/utils/history_tracker.hpp
This commit aims to make the use of RLOC16-related constants and methods consistent across different modules.
- It replaces `Mac::kShortAddrInvalid` with `Mle::kInvalidRloc16` to refer to an invalid RLOC16 value (note that these constants use the same value `0xfffe`).
- It uses `Get<Mle::Mle>().GetRloc16()` to retrieve the device's RLOC16 instead of `Get<Mac::Mac>().GetShortAddress()`.
- It updates `AddressResolver` to consistently use `uint16_t` for RLOC16 (instead of the `Mac::ShortAddress` typedef).
> [core] use RLOC16-related constants and methods consistently across modules

- src/posix/platform/README_RCP_CAPS_DIAG.md
- src/posix/platform/rcp_caps_diag.cpp
- src/posix/platform/rcp_caps_diag.hpp
This commit adds a diag command to rcp capability diag module to check the  short and extended source match table size of the RCP.
> [posix] check the RCP supported short and extended source match table sizes

- src/core/api/thread_ftd_api.cpp
- src/core/thread/child.cpp
- src/core/thread/child.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mlr_manager.cpp
- src/core/thread/network_diagnostic.cpp
- tests/unit/test_child.cpp
This commit introduces several changes to the `Child` class for managing registered IPv6 addresses by MTD children:
- A new method, `Child::GetIp6Addresses()`, is added, returning the `Array` of registered IPv6 address entries. This array includes all tracked child IPv6 addresses except for the mesh-local EID, which can be retrieved using `Child::GetMeshLocalIp6Address()`.
- The simplified model enables easy iteration over the address array using `Array` range-based `for` loops. With this change, the complex `AddressIterator` and `AddressIteratorBuilder` nested classes are removed, streamlining the code.
- MLR state tracking for child IPv6 address entries is simplified with the introduction of a new class, `Child::Ip6AddrEntry`, representing a registered IPv6 address entry. This class …
> [child] add `GetIp6Addresses()` and simplify MLR state tracking

- src/core/meshcop/meshcop_tlvs.hpp
- src/core/thread/discover_scanner.cpp
- src/core/thread/mle_router.cpp
This commit simplifies the appending and parsing of `NetworkNameTlv` using `Append<StringTlvType>()` and `Read<StringTlvType>()` TLV helper methods.
> [meshcop] simplify appending and parsing of `NetworkNameTlv`

- src/posix/platform/spi_interface.cpp
The SPI interface may receive the garbage bytes 0xff or 0x00 at the start of the received SPI frame. This commit skips the 0x00 bytes at the start of the received SPI frame.
> [posix] skip 0x00 bytes at the start of the received SPI frame

- src/core/net/dns_client.cpp
- src/core/net/dnssd_server.cpp
- src/core/net/dnssd_server.hpp
- tests/unit/test_dns_client.cpp
This commit updates `Dns::Client` so that when resolving a service using `kServiceModeSrvTxtOptimize`, it switches to single-question query mode and sends separate parallel SRV and TXT queries upon the first response timeout. This is in addition to the existing behavior of switching to separate queries upon receiving a response with an error rcode from the server.
The `test_dns_client` unit test is also updated to validate this scenario. New `TestMode` configurations are added to server to control its behavior, allowing it to either reject multi-question queries (by sending a "FormatError" rcode) or ignore them (sending no response).
> [dns-client] switch to separate SRV/TXT queries on response timeout

- src/core/common/tlvs.cpp
- src/core/common/tlvs.hpp
- src/core/thread/discover_scanner.cpp
- src/core/thread/link_metrics.cpp
- src/core/thread/mle_router.cpp
This commit adds the `Tlv::ParseAndSkipTlv()` static method, which parses a TLV (regular or extended) in a message at a given offset. It validates that the TLV is fully contained within the message and updates the offset to skip over the entire parsed TLV.
This helper method is used in various modules where manual iteration over a sequence of TLVs is performed, specifically to skip over extended TLVs. The following methods are updated to utilize this new method and perform additional TLV checks:
- `DiscoverScanner::HandleDiscoveryResponse()`
- `MleRouter::HandleDiscoveryRequest()`
- `LinkMetrics::SubJect::AppendReport()`
- `LinkMetrics::Subject::HandleManagementRequest()`
- `LinkMetrics::Initiator::HandleReport()`
-----
- Should help …
> [tlv] ensure handling of extended TLVs when iterating over sub-TLVs

- src/core/api/thread_api.cpp
- src/core/thread/address_resolver.cpp
- src/core/thread/child_table.cpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_types.hpp
- src/core/thread/network_data_leader.cpp
- src/core/thread/network_data_notifier.cpp
- src/core/thread/router_table.cpp
- src/core/utils/mesh_diag.cpp
This commit introduces new helper methods in the `Mle` class:
- `HasRloc16()`: Checks if the device is using a given RLOC16.
- `MatchesRouterId()`: Checks if this device's RLOC16 matches a given Router ID.
- `HasMatchingRouterIdWith()`: Checks if this device's RLOC16 shares the same Router ID with a given RLOC16. This implies that the two devices are either directly related as parent and child or are children of the same parent within the Thread network.
- `ParentRloc16ForRloc16()` derives the router RLOC16 corresponding to the parent of a given (child) RLOC16.
These methods act as syntactic sugar, simplifying code and enhancing readability.
> [mle] add RLOC16 related helper methods in `Mle`

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- tests/unit/test_routing_manager.cpp
This commit adds the `OnLinkPrefix::IsFavoredOver()` method to determine if an on-link prefix is eligible to be considered as a favored prefix, and if so, is favored over another prefix. A numerically smaller prefix is considered favored.
Additionally, a new test case is added to `test_routing_manager` to validate the selection of favored on-link prefixes, including the the requirement of a minimum preferred lifetime of 1800 seconds for a prefix to be considered eligible.
> [routing-manager] add `OnLinkPrefix::IsFavoredOver()`

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
This commit introduces a new private struct `RxInfo` in the `MeshForwarder` class, encapsulating information related to a received frame during processing. The `RxInfo` struct contains `FrameData` to track the received frame data bytes, `ThreadLinkInfo`, and `Mac::Addresses`. This simplifies the code by allowing the `RxInfo` to be passed to different methods instead of passing the same information as separate parameters.
> [mesh-forwarder] add `RxInfo` to encapsulate received frame info

- src/lib/CMakeLists.txt
- src/lib/spinel/CMakeLists.txt
- src/lib/spinel/openthread-spinel-config.h
This PR allows user projects to override the ot lib configs by using
a customized lib config file, by setting `OT_LIB_CONFIG`.
> [spinel] allow custom config file for lib spinel

- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
This commit updates `GetForwardFramePriority()` to save the original `aRxInfo.mFrameData` before parsing the fragment header. The header parsing may modify `mFrameData` to skip over the parsed portion. The original `FrameData` is restored before returning, ensuring that forwarded frames include the fragment header and eliminating the need to create a copy of `aRxInfo`.
> [mesh-forwarder] restore `FrameData` in `GetForwardFramePriority()`

- CMakeLists.txt
CMake by default enables c extensions. As a result, gnu99 is used instead of c99. This commit explicitly disables c extensions.
> [cmake] disable c extensions

- src/core/common/tlvs.cpp
- src/core/common/tlvs.hpp
- src/core/thread/discover_scanner.cpp
- src/core/thread/link_metrics.cpp
- src/core/thread/link_metrics.hpp
- src/core/thread/mle_router.cpp
This commit updates `Tlv` helper methods to use `OffsetRange` in their implementation. It also makes the `Tlv::ParsedInfo` type public. This struct represents information about a parsed TLV in a message, including the TLV type, the `OffsetRange` for the full TLV, and the `OffsetRange` where the TLV's value resides in the message. This replaces and enhances the `ParseAndSkipTlv()` method.
The `ParsedInfo` provides two methods:
- `ParseFrom()`: Parses a TLV at a given offset or offset range.
- `FindIn()`: Searches for a given TLV type in a message.
These methods handle both extended and regular TLV formats, validating that the parsed TLV is well-formed and fully contained within the message and the given `OffsetRange`.
Modules that iterate over a sequence of TLVs in a message are updated to …
> [tlv] use `OffsetRange` and make `ParsedInfo` public

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
This commit adds `RxInfo::ToString()`, which generates a common log string about an `RxInfo` using the "len:%d, src:%s, dst:%s, sec:%s" format, providing frame length, source and destination addresses, and whether link security is used. This is then used in different logging methods, simplifying the code.
> [mesh-forwarder] add `RxInfo::ToString()` to simplify logging

- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
- src/core/net/ip6_headers.cpp
- src/core/net/ip6_headers.hpp
- src/core/net/ip6_mpl.cpp
- src/core/net/ip6_mpl.hpp
- src/core/thread/lowpan.cpp
This commit updates `Ip6` and `Lowpan` to use `OffsetRange` when iterating and parsing options in an HBH extension header. It also simplifies the `RemoveMplOption()` method by adding an `Action` enum, which determines how to remove the MPL option: whether to shrink the HBH header, fully remove the HBH header (if it contains no other options), or replace MPL option with padding.
> [ip6] use `OffsetRange` for parsing options in extension headers

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- src/core/config/border_routing.h
This commit adds a new feature to the `RoutingManager` to enable tracking information about peer Thread Border Routers that are connected to the same Thread network.
When enabled, the `RoutingManager` will maintain a record of advertised RIO/PIO prefixes discovered from received Router Advertisement (RA) messages of peer BRs. When disabled (the existing behavior), such entries are not tracked.
When tracked, these entries are marked to be disregarded and are not considered in any decision-making processes, such as selecting favored on-link prefixes or determining routes to publish in the Thread Network Data. They are primarily intended for debugging and telemetry (information gathering) purposes.
> [routing-manager] add support for tracking peer BRs

- src/core/thread/mesh_forwarder.cpp
This commit updates `PrepareNextDirectTransmission()` to use `RemoveMessageIfNoPendingTx()` if a message cannot be prepared for direct transmission. This ensures the message is not dequeued and freed if it is also queued for indirect transmission.
---
Should address https://github.com/openthread/openthread/issues/10469
> [mesh-forwarder] use `RemoveMessageIfNoPendingTx()` on direct tx fails

- src/core/thread/mle_router.hpp
This method was refactored in 25fe46d8dd (#8963) but its declaration was not removed.
> [mle] remove now undefined `UpdateChildAddresses()`

- src/core/meshcop/meshcop_tlvs.cpp
- src/core/meshcop/meshcop_tlvs.hpp
This commit updates `ChannelMaskTlv` to use `OffsetRange` when iterating over and parsing the list of entries contained in the TLV.
> [meshcop] update `ChannelMaskTlv` to use `OffsetRange`

- tests/scripts/thread-cert/border_router/test_advertising_proxy.py
This commit makes two changes in `test_advertising_proxy`:
- In the test step where the server is restarted, a longer wait time is used to account for the longer jitter interval used by SRP client in such a case.
- Due to the use of short lease time (10 seconds) in this test, the client will refresh the registered services quickly. Therefore, in `check_host_and_service()`, any of `Registered`, `ToRefresh`, or `Refreshing` states are accepted as indicating successful registration.
> [test] harden `test_advertising_proxy`

- src/core/BUILD.gn
- src/core/CMakeLists.txt
- src/core/mac/sub_mac.cpp
- src/core/mac/sub_mac.hpp
- src/core/mac/sub_mac_csl_receiver.cpp
This commit moves csl receiver related functions to sub_mac_csl_receiver.cpp to simply the sub_mac.cpp to improve the code readability.
This commit is a pure refactoring and doesn't contain any logic or code changes.
> [csl] move sub_mac csl receiver related functions to sub_mac_csl_receiver.cpp

- tools/cp-caps/README.md
- tools/cp-caps/rcp_caps_test.py
- tools/cp-caps/requirements.txt
- tools/otci/otci/otci.py
This commit implements a test `script tools/cp-caps/rcp_caps_test.py` to test which diag commands RCP supports using the DUT and reference device.
> [test] add script to test which diag commands RCP supports

- src/core/net/srp_client.cpp
- src/core/net/srp_client.hpp
This commit updates `Srp::Client` to apply a short random jitter (15 seconds) when calculating the lease renew time. The lease is renewed close to its expiration, using a guard interval of 120 seconds (renewing 120 seconds before expiration). The jitter is added to distribute client refreshes, in case many clients registered their services around the same time.
> [srp-client] apply short random jitter to lease renew time

- tools/otci/otci/otci.py
This commit adds high level Thread network management API 'create_dataset()', 'join()', 'leave()' and 'wait_for()' to otci.
> [otci] add network management API to otci

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
This commit adds an `Ip6::Header` field to `RxInfo`, along with the `ParseIp6Headers()` method to decompress and parse the IPv6 headers from the received frame. `RxInfo` now tracks whether the headers have been parsed before.
The IPv6 headers may be parsed from different code paths as the received frame is processed. For example, `UpdateRoutes()`, `GetFramePriority()`, and `CheckReachability()` may parse the IPv6 headers. By having `RxInfo` cache the parsed IPv6 headers, duplicate parsing is avoided.
> [mesh-forwarder] track parsed IPv6 header in `RxInfo`

- src/cli/cli_dataset.cpp
- src/cli/cli_dataset.hpp
This commit adds the `ParseTlvs()` helper method in the `Cli::Dataset` class, which parses TLVs (as hex strings) from an input argument. This is used in multiple methods to simplify the code.
The `Process<Cmd("set")>()` method is updated to avoid extra conversion and use of core-internal types.
> [cli] simplify parsing dataset TLVs

- tests/unit/test_srp_server.cpp
This commit updates `test_srp_server` to wait longer after the start of the SRP client before performing the test steps. This makes the test more robust against random jitter which may be applied by the client when registering.
---
Should help address failures like [link](https://github.com/openthread/openthread/actions/runs/9831798497/job/27139692103).
> [test] harden `test_srp_server`

- src/cli/cli.cpp
- src/cli/cli.hpp
This commit harmonizes header file include style in CLI source files. Most `#include` statements do not have any `#if` guard checks before them, but some do. This commit removes the extra `#if` guard checks. For CLI sub-modules, the `cli_<module>.hpp` header itself will have the proper `#if` guard checks.
> [cli] harmonize header include style

- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/network_data_leader.hpp
- src/core/thread/network_data_leader_ftd.cpp
This commit refactors the code and methods responsible for looking up anycast destination, moving them from the `MeshForwarder` class to the more appropriate `NetworkData::Leader` class. This better aligns the responsibilities of each module (e.g. `RouteLookup()` is provided by `NetworkData::Leader). This is a pure refactor with no changes or enhancements to the existing implementation.
---
I kept this as a pure refactor with no logic changes. In future PRs we can include enhancements (e.g., reusing existing methods in `NetworkData::Leader` for comparing network data entries when selecting a destination).
> [network-data] refactor anycast dest lookup to `NetworkData::Leader`

- src/posix/platform/hdlc_interface.cpp
Many USB radio devices (particularly those based on TI CC2652) have reset and bootloader activation directly connected to DTR/RTS lines. These devices will fail to start, in the default state where both DTR/RTS are asserted on connection.
This patch ensures flow control is disabled and both DTR and RTS are deasserted on startup while configuring the terminal. There is no impact on devices using hw flow control.
> [posix] deassert DTR and RTS if flow control is disabled

- src/core/meshcop/dataset_manager.cpp
This commit updates `DatasetManager::ApplyConfiguration()` to apply the rest of the parameters in the Dataset even if setting the channel fails.
> [dataset-manager] apply partial dataset config on channel set failure

- include/openthread/border_routing.h
- include/openthread/instance.h
- src/cli/README_BR.md
- src/cli/cli_br.cpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- tests/toranj/cli/test-503-peer-tbr-discovery.py
This commit updates the public API `otBorderRoutingGetNextRouterEntry` and `otBorderRoutingRouterEntry` structure to indicate whether a discovered router on an infrastructure link is likely a peer Thread Border Router (BR) connected to the same Thread mesh. The related CLI commands are also updated. Additionally, this commit adds new tests to validate the discovery and tracking of peer BRs.
----
~This PR currently contains the commit from https://github.com/openthread/openthread/pull/10445. Please check and review the last commit. Thanks.~
~This PR is rebased on https://github.com/openthread/openthread/pull/10453. Please check and review the last commit. Thanks.~
> [routing-manager] indicate peer BRs in discovered infra-if routers

- src/lib/spinel/radio_spinel.cpp
- src/lib/spinel/radio_spinel.hpp
- src/posix/platform/radio.cpp
- src/posix/platform/radio.hpp
This PR moves the definition of the 'RequiredRadioCaps' from `RadioSpinel` to posix `Radio` class. Because this definition depends on `OPENTHREAD_CONFIG_THREAD_VERSION`. And we want to remove lib's dependency on OT core. And lib as a tool should be able to decide what caps to check at runtime.
> [radio] move required radio caps from radio spinel into posix platform

- tools/cp-caps/README.md
- tools/cp-caps/rcp_caps_test.py
- tools/otci/otci/otci.py
This commit adds a test case to `cp-tests` to test whether the RCP supports the CSL transmitter.
> [test] test whether the RCP support CSL transmitter

- src/lib/spinel/BUILD.gn
- src/lib/spinel/CMakeLists.txt
- src/lib/spinel/radio_spinel.cpp
- src/lib/spinel/radio_spinel.hpp
- src/lib/spinel/spinel_helper.cpp
- src/lib/spinel/spinel_helper.hpp
This PR moves `RadioSpinel::SpinelStatusToOtError` to a seperate header `spinel_header.hpp` so that this method can be used externally. (For example, in `ot-br-posix`.
> [spinel] extract SpinelStatusToOtError method from RadioSpinel into a helper module

- tools/cp-caps/README.md
- tools/cp-caps/rcp_caps_test.py
This commit adds a test case to the `cp-tests` to test whether the RCP supports data poll transmitter and receiver.
> [test] test whether the RCP supports data poll

- src/lib/spinel/CMakeLists.txt
This PR adds `spinel_helper.cpp` in the target source list of `openthread-radio-spinel`.
When `openthread-radio-spinel` is used in external projects, there may be link issues (`SpinelStatusToError` cannot be found). Because currently `spinel_helper.cpp` is not in the target source list. 
This issue isn't found when the PR was submitted because `spinel_helper.cpp` is added in `COMMON_SOURCES` which is used to build `openthread-rcp-spinel` and ot-daemon also links this lib.
> [spinel] fix cmake source list for spinel_helper.cpp

- include/openthread/border_routing.h
- include/openthread/instance.h
- src/cli/README_BR.md
- src/cli/cli_br.cpp
- src/core/api/border_routing_api.cpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- tests/toranj/cli/cli.py
- tests/toranj/cli/test-503-peer-tbr-discovery.py
This commit adds a new mechanism in `RoutingManager` to discover and track peer BRs found in Network Data. The `NetDataPeerBrTracker` class implements this functionality, tracking a list of peer BR RLOC16s and their age (time since appearance in the Network Data).
This commit also implements public OT APIs to iterate over the peer BR list or get the total count, along with corresponding CLI commands (`br peers`), and a test case validating the behavior.
----
~This PR currently contains the commit from the #10453 and #10448. Please check and review the last commit. Thank.~
> [routing-manager] track peer BRs and their age from Network Data

- src/lib/spinel/spinel_driver.hpp
This PR adds a method to get spinel interface Id in `SpinelDriver`.
This is to enable the user class of `SpinelDriver` can compose the spinel header itself.
> [spinel] add get iid method

- src/posix/platform/settings.cpp
On platform settings deinit, the file descriptor is closed but the variable is not reset, which can lead to calling close on a stale fd leading to bad file descriptor error in case the API is invoked multiple times
> [settings] reset the platform settings file descriptor once closed

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder_ftd.cpp
This commit replaces direct calls to `DequeueAndFree()` with `RemoveMessageIfNoPendingTx()` in `EvictMessage()`, `HandleResolved()`, and `RemoveDataResponseMessages()`. This promotes consistency in message removal logic and eliminates the need to check if the removed message is `mSendMessage`, as this is already handled by `RemoveMessageIfNoPendingTx()`.
----
In all the above cases, using `DequeueAndFree()` is indeed correct (since we know message has no pending TX). Opted to use `RemoveMessageIfNoPendingTx()` to maintain consistency throughout the codebase.
> [mesh-forwarder] use `RemoveMessageIfNoPendingTx()`

- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
This commit updates `RemoveMessagesForChild()` to use a predicate function to determine which messages should be removed. This replaces the `Message::SubType` filtering and allows messages matching multiple sub-types to be removed together.
> [mesh-forwarder] `RemoveMessagesForChild()` to use a predicate fn

- src/core/thread/network_data_leader.cpp
- src/core/thread/network_data_leader.hpp
- src/core/thread/network_data_leader_ftd.cpp
- tests/toranj/cli/cli.py
- tests/toranj/cli/test-031-service-aloc-route-lookup.py
- tests/toranj/start.sh
This commit updates `NetworkData::Leader` to enhance route lookup for ALOC destinations. It contains the following changes:
- Adds `LookupRouteForServiceAloc()` to look up the route for a service ALOC. This method uses the common `CompareRouteEntries()`, which applies the same rules as in external route lookup.
- Adds `LookupRouteForAgentAloc()` to look up the route for DHCPv6 or ND agent ALOC.
- Adds `FindPrefixTlvForContextId()` to find a Prefix TLV matching a given Context ID (used in `GetContext()` and `LookupRouteForAgentAloc()`)
- Adds `LookupRouteIn()` to perform route lookup among all entries of a given `PrefixTlv` that match a given `EntryChecker` function (used for `DefaultRouteLookup()` or `LookupRouteForAgentAloc()`)
- Adds `test-031-service-aloc-route-lookup.py`
> [network-data] enhance route lookup for ALOC destination

- src/lib/spinel/multi_frame_buffer.hpp
- src/lib/spinel/spi_frame.hpp
The order of little endian in lib is incorrect.
> [spinel] fix little endian in lib

- src/core/net/srp_client.cpp
- tests/scripts/thread-cert/test_srp_auto_host_address.py
This commit updates SRP client's `AutoHostAddress` behavior to defer SRP updates on SLAAC address deprecation events.
Under `AutoHostAddressMode`, all preferred addresses on Thread Netif, excluding link-local and mesh-local addresses, are registered. If no eligible address is available, then the ML-EID will be registered.
This commit adds a new mechanism where if a previously registered address starts being deprecated (e.g., due to an OMR prefix removal from Network Data), the SRP update is deferred. The client will re-register after the deprecation time has elapsed and the address is removed. In the meantime, if any other event triggers the client to send an SRP update, the updated address list will be included in that update.
This commit also updates `test_srp_auto_host_address` to …
> [srp-client] defer SRP update on SLAAC address deprecation

- include/openthread/instance.h
- include/openthread/thread_ftd.h
- src/cli/README.md
- src/core/api/thread_ftd_api.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
- tests/toranj/cli/cli.py
- tests/toranj/cli/test-032-leader-take-over.py
- tests/toranj/start.sh
This commit updates the `otThreadBecomeLeader()` API (and its related core `MleRouter::BecomeLeader()` method) to allow an already attached device to take over as leader, creating a new partition. For this to work, the local leader weight (`otThreadGetLocalLeaderWeight()`) must be greater than the weight of the current leader (which can be retrieved using `otThreadGetLeaderWeight()`). If it is not, error code `OT_ERROR_NOT_CAPABLE` is returned to indicate to the caller that they need to adjust the local weight.
This commit also updates the related CLI command and adds a new test, `test-031-leader-take-over.py`, to validate the newly added mechanism.
----
Related to [SPEC-1140](https://threadgroup.atlassian.net/browse/SPEC-1140).
> [mle] update `otThreadBecomeLeader()` to allow leader take over

- .github/workflows/otbr.yml
The OTBR testing artifacts used to be at the root directory but they are now at `ot_testing/`.
> [continuous-integration] fix the path for uploading artifacts when the BR fails

- src/core/mac/sub_mac.cpp
- src/core/mac/sub_mac.hpp
- src/core/mac/sub_mac_csl_receiver.cpp
The `SubMac` uses `MilliTimer` or `MicroTimer` based on the configuration.  When the `SubMac` uses the timer, it has to distinguish the type of the timer. This commit optimizes the code to provide unified time related functions to `SubMac` to use time. This commit doesn't change the code logic.
> [sub-mac] optimize the time related functions

- include/openthread/instance.h
- include/openthread/platform/radio.h
- src/core/radio/radio.hpp
- src/core/radio/radio_callbacks.cpp
- src/core/radio/radio_platform.cpp
- src/core/thread/csl_tx_scheduler.cpp
- src/core/thread/csl_tx_scheduler.hpp
- src/lib/spinel/README_RADIO_SPINEL_DIAG.md
- src/lib/spinel/radio_spinel.cpp
- src/lib/spinel/radio_spinel.hpp
- src/posix/platform/radio.cpp
- src/posix/platform/radio_url.cpp
Implement `otPlatRadioGetBusLatency` and `otPlatRadioSetBusLatency` APIs, add optional latency arguments to ot-daemon and `rcp latency` CLI commands.
Add APIs to update frame request ahead from runtime, which recalculate `mCslFrameRequestAheadUs` value.
Changes allow setting a bus latency while starting a new session between host and RCP device. This way, one host can be connected to different devices and vice versa, ensuring that the latency will be added to `mCslFrameRequestAheadUs` calculations and CSL tx requests will not be sent too late.
Fixes https://github.com/openthread/openthread/issues/10410
> [low-power] enhance `mCslFrameRequestAheadUs` calculation for RCP

- src/core/mac/sub_mac.cpp
The original code uses the absolute time when staring the CSL TX delay in `SubMac`. The timer is a `MicroTimer` and the absolute time comes from the `mTxDelayBaseTime`. The `mTxDelayBaseTime` comes from the radio time `otPlatRadioGetNow ()`, the time of `MicroTimer` should come from `otPlatAlarmMicroGetNow()`. If the `MicroTimer` and the radio are using different timer sources, it will cause the unexpected issue.
This commit use the relative time when starting CSL TX delay to fix this issue.
> [sub-mac] use relative time when starting CSL TX delay

- script/check-simulation-local-host
- tests/scripts/expect/_common.exp
This commit adds default paths for expect scripts to make it easier for running expect scripts. With this change, we can run expect tests as follows:
```bash
./script/cmake-build simulation
./script/cmake-build posix
./tests/scripts/expect/cli-ping.exp
OT_NODE_TYPE=rcp ./tests/scripts/expect/cli-ping.exp
```
This commit also updates an existing test to cover the change.
> [test] set default paths of expect scripts

- src/core/api/border_agent_api.cpp
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
This commit updates the `BorderAgent` to directly respond to `MGMT_ACTIVE_GET` and `MGMT_PENDING_GET` requests from a non-active commissioner. Requests from an active commissioner are still forwarded to the leader. This aligns the implementation with Thread 1.4 requirements (ephemeral PSKc use case).
To achieve this, the following changes are made:
- New `State` values are added to distinguish between when a commissioner candidate is connected and when its petition to become the active commissioner is accepted. This determines whether the `MGMT_GET` request should be handled directly or forwarded to the leader.
- This state is tracked locally by `BorderAgent` instead of monitoring Network Data to determine whether an active commissioner exists. This ensures correct behavior even when …
> [border-agent] directly respond to MGMT_GET from non-active commissioner

- src/core/net/icmp6.cpp
- src/core/net/icmp6.hpp
- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
This commit updates `PassToHost()` to directly use the `Ip6::Header` and its `GetSource()` and `GetDestination()` methods when applying filter rules. This replaces the previous model where a `MessageInfo` was constructed from the received IPv6 header and passed to `PassToHost()`. The previous model indirectly assumed that the message was received, with the `MessageInfo` sock/peer addresses mapped accordingly. However, `HandleDatagram()` can also process messages originating from the device itself, where the notion of peer and sock addresses would be reversed. Using `Ip6::Header` directly makes the rules clearer and simplifies the logic of `PassToHost()`.
Additionally, this change simplifies the code by moving the construction of `MessageInfo` to the `Receive()` method, where the message …
> [ip6] simplify `PassToHost()` to directly use `Ip6::Header`

- src/core/net/ip6.cpp
This commit removes the checks previously performed on messages with the origin `HostTrusted` that are to be forwarded to the Thread mesh. This origin is used for messages generated by the OpenThread stack itself. These checks were unnecessarily restricting such messages from using Thread Control UDP port numbers (like TMF, MLE, etc.). The additional check `!IsLoopbackToHostAllowed()` (which is set to `true` by default on such messages) bypassed the entire block, preventing any functional impact.
Recent related changes (in #9437) added similar guard checks for messages with `HostUntrusted` origins.
---
Related to #10543
> [ip6] remove UDP port check for messages with `HostTrusted` origin

- src/ncp/ncp_base.cpp
This fixes a bug where diag get output callback was not set properly if we used instance with iid > 1, leading to failure output.
> [ncp] initialize diag output callback per instance in `NcpBase`

- src/core/net/ip6.cpp
This commit updates the code to avoid re-reading the IPv6 header when updating BR-related counters in `Ip6::PassToHost()`.
> [ip6] avoid re-reading IPv6 header when updating BR counters

- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
This commit updates `PassToHost()`, removing the `aApplyFilter` input and using `aReceive` to determine whether or not to apply the RX filter. The filter serves multiple purposes:
- Ensure Thread control UDP traffic (e.g., MLE, TMF, etc.) is filtered out when delivering IPv6 datagrams to the host.
- Apply ICMPv6 echo requests filtering, based on the configured mode (whether the OT stack should respond to pings for specific address types or they should be passed to the next layer).
- Filter TCP traffic when the native OT TCP stack is used.
In all cases, the filter should be applied only if the IPv6 message is supposed to be received by the device itself (i.e., the destination matches the device's address), which is indicated by the `aReceive` input.
The `aApplyFilter` input was previously …
> [ip6] update `PassToHost` to use `aReceive` for applying RX filter

- src/core/net/nat64_translator.cpp
- src/core/net/nat64_translator.hpp
This PR applies following enhancements to the `Translator::UpdateState`:
- Remove the `aAlwaysNotify` parameter to simplify its logic.
- Fix an issue that `mState` may not be updated when setting a CIDR.
> [nat64] enhancements for `Translator::UpdateState`

- examples/platforms/simulation/radio.c
- examples/platforms/utils/mac_frame.cpp
- examples/platforms/utils/mac_frame.h
- src/core/mac/mac_frame.cpp
- src/core/mac/mac_frame.hpp
- tests/fuzz/fuzzer_platform.cpp
- tests/unit/test_mac_frame.cpp
This commit adds the capability to support frames without sequence number.
> [mac] support frames without sequence number

- src/cli/README.md
- src/cli/cli_link_metrics.cpp
- src/cli/cli_link_metrics.hpp
- tests/scripts/thread-cert/node.py
- tests/scripts/thread-cert/v1_2_LowPower_7_1_01_SingleProbeLinkMetricsWithEnhancedAcks.py
- tests/scripts/thread-cert/v1_2_LowPower_7_1_02_SingleProbeLinkMetricsWithoutEnhancedAck.py
- tests/scripts/thread-cert/v1_2_LowPower_7_2_01_ForwardTrackingSeries.py
- tests/scripts/thread-cert/v1_2_LowPower_test_forward_tracking_series.py
- tests/scripts/thread-cert/v1_2_test_single_probe.py
The cli command `linkmetrics` only provides an asynchronous output method. It is difficult for scripts to call the `ot-ctl` to capture the results of asynchronous output. 
This commit replaces the command `linkmetrics mgmt` and `linkmetrics query` with commands `linkmetrics config` and `linkmetrics request`. Both the commands `linkmetrics config` and `linkmetrics request` are set to the `sync` mode by default, and an option `async` is added to these commands to support `async` mode.
> [cli] set the `linkmetrics` cli commands to `sync` mode by default

- src/lib/spinel/radio_spinel.cpp
- src/lib/spinel/radio_spinel.hpp
- src/posix/platform/openthread-core-posix-config.h
- src/posix/platform/platform-posix.h
- src/posix/platform/radio.cpp
- src/posix/platform/system.cpp
The radio_spinel periodically send Spinel command SPINEL_PROP_RCP_TIMESTAMP to RCP to synchronize time between host and RCP. Even if Thread stack is not running, it will periodically wake up the Thread host.
This commit stops the time sync when the Thread stack is not running to save host power.
https://github.com/orgs/openthread/discussions/10553
> [spinel] stop Spinel time sync when Thread satck is not running

- src/core/border_router/infra_if.cpp
- src/posix/platform/infra_if.cpp
- src/posix/platform/infra_if.hpp
- tests/toranj/openthread-core-toranj-config-posix.h
This PR moves the macro guard `OPENTHREAD_POSIX_CONFIG_INFRA_IF_ENABLE` in the code so that it can allow custom implementation of `otPlatInfraIfDiscoverNat64Prefix` when `OPENTHREAD_POSIX_CONFIG_INFRA_IF_ENABLE` is disabled.
The use case is on Android platform. We'll not let `ot-daemon` proactively discover the prefixes by DNS. Instead, System Server will do the discovery of NAT64 prefix on AIL and it will notify `ot-daemon` when the AIL NAT64 prefix is discovered/removed.
> [posix] allow custom implementation of `otPlatInfraIfDiscoverNat64Prefix`

- src/core/net/srp_client.cpp
- src/core/net/srp_client.hpp
This commit updates and renames the `Info` class to `MsgInfo`, which now includes `mMessage` as an `OwnedPtr` to the message to be prepared. This simplifies the code by encapsulating the `Message` and all its associated data needed to prepare an SRP update message into one data structure. This structure can be passed as a single input to different methods preparing various SRP update components, instead of as two separate inputs.  The OwnedPtr ensures automatic freeing of the message upon any error.
> [srp-client] update `MsgInfo` to include `mMessage`

- tests/scripts/thread-cert/node.py
This commit supresses the docker output unless verbose mode is enabled, which helps preventing unnecessary output from cluttering the console.
docker output is enabled when:
* env VERBOSE is set to a non-zero value
docker output is suppressed (redirecting to /dev/null) when:
* VERBOSE is not explicitly set in env, or
* env VERBOSE is set to 0
> [thread-cert] output docker stdout/stderr only when VERBOSE is non-zero

- src/core/net/srp_client.cpp
- src/core/net/srp_client.hpp
This commit introduces the `KeyInfo` type, which is a `typedef` to either `KeyPair` or `KeyPairAsRef` depending on whether the feature `KEY_REFERENCES_ENABLE` is enabled. This simplifies the code, removes repeated code, and eliminates extra `#if` checks when `KeyInfo` is used.
----
This PR currently contains the commit from https://github.com/openthread/openthread/pull/10577. Please check and review the last commit. Thanks.
> [srp-client] add `KeyInfo` type alias for `KeyPair` or `KeyPairAsRef`

- tests/scripts/thread-cert/thread_cert.py
In some cases that `_do_packet_verification` is False (e.g. verify() is not defined), the docker network is not correctly removed.
docker network interface should always be removed at the end of the test if it was created at the begin of the test
> [thread-cert] fix bug that docker network is not removed

- tools/cp-caps/README.md
- tools/cp-caps/rcp_caps_test.py
This commit adds a test case to `cp-tests` to test whether the RCP supports the Link Metrics.
> [test] test whether the RCP supports the Link Metrics

- include/openthread/instance.h
- include/openthread/platform/radio.h
- src/core/utils/power_calibration.cpp
- tests/unit/test_power_calibration.cpp
This commit updates the description of the function `otPlatRadioSetChannelTargetPower()` to make the function description more accurate, and updates the implementation of the function based on the latest description.
> [radio] update the description of `otPlatRadioSetChannelTargetPower()`

- include/openthread/instance.h
- include/openthread/thread.h
- src/core/BUILD.gn
- src/core/openthread-core-config.h
This commit moves the definition of `OT_THREAD_VERSION_*` constants from the config header to the `openthread/thread.h` OT public header file (where `otThreadGetVersion()` is declared). This allows other projects integrating the OT stack to also see and use these constants.
> [thread] move `OT_THREAD_VERSION_*` constants to public header

- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
This commit contains minor enhancements in the `Ip6` class:
- Removes unnecessary `static_cast<uint8>()` use,
- Combines repeated `case` statements,
- Use shorter variable/type names,
- Style fixes.
> [ip6] style fixes and minor enhancements

- src/lib/spinel/spinel_driver.hpp
Changed access of SendCommand to public to allow calling without variable arguments. This is to address compilation error in ot-br-posix repo NcpSpinel::ThreadErasePersistentInfo (while building for OpenWrt v23.05.4 for a mips target)(error: 'args' may be used uninitialized [-Werror=maybe-uninitialized])
> [spinel] make `SendCommand` public to allow calling without variable arguments

- src/core/net/dnssd_server.cpp
- src/core/net/dnssd_server.hpp
- tests/scripts/thread-cert/border_router/test_dnssd_server.py
- tests/scripts/thread-cert/border_router/test_dnssd_server_multi_border_routers.py
- tests/unit/test_dnssd_discovery_proxy.cpp
This commit adds support for responding to "A record" queries in the DNS-SD server and discovery proxy.
If the query matches a host registered with the SRP server, the host's IPv6 addresses are returned in the Additional Data section of the response. If the query is resolved by the proxy, the `otPlatDnssd` APIs are used to start/stop IPv4 address resolvers for the hostname on the infrastructure network.
The `test_dnssd_discovery_proxy` unit test is updated to validate the new functionality.
> [dsnsd-server] support handling of "A record" queries

- src/core/net/dns_client.cpp
- src/core/net/dns_client.hpp
- src/core/net/dnssd_server.hpp
- tests/unit/test_dns_client.cpp
This commit updates `Dns::Client` to remember servers/resolvers that are known to have trouble with multiple-question queries. This information is learned from earlier interactions with the server.
When `ResolveService()` is requested, if the user explicitly requests "optimize" service mode, the request is honored. Otherwise, if "optimize" service mode is chosen from the default configuration and the DNS server is known to have trouble with multiple-question queries, "separate" service mode is used instead.
This commit also updates the `test_dns_client.cpp` unit test to validate the newly added behavior.
> [dns-client] track limited query (one question) servers

- src/core/thread/address_resolver.cpp
- src/core/thread/address_resolver.hpp
This commit introduces a freshness timeout mechanism for address cache entries which is used to decide when removing stale entries when the associated RLOC16 is unreachable.
In `AddressResolver`, when resolving an EID from an existing cache entry, if the target RLOC16 is unreachable, the entry is typically considered stale and removed to allow a new address query to be sent. This commit adds a mechanism to skip this removal step if the entry has been recently updated, i.e., an `AddressNotify` has been received for it and its `FreshnessTimeout` has not yet expired.
The `FreshnessTimeout` check prevents repeated address query transmissions when mesh routes are not yet discovered (e.g., after initial attach) or if there is a temporary link issue.
> [address-resolver] freshness timeout mechanism for cache entries

- tests/scripts/thread-cert/border_router/test_multi_ail.py
- tests/scripts/thread-cert/config.py
- tests/scripts/thread-cert/node.py
This commit targets to support getting infra link-local address of a OtbrNode in docker test, which is usefully for future test cases.
The `test_multi_ail.py` is also updated to test the new method added.
> [thread-cert] support to get link-local address of the infra interface

- tests/scripts/thread-cert/border_router/test_multi_ail.py
- tests/scripts/thread-cert/node.py
This commit adds functions to read peer BRs and routers on infra link by wrapping the ot-ctl command `br peers` and `br routers`. 
`test_multi_ail.py` is also updated to test the new added functions.
> [thread-cert] wrap command `br peers` and `br routers`

- src/cli/README.md
- src/cli/cli_dns.cpp
Also adds missing CLI outputs in examples.
close #10396
> [cli] clarify docs - parameter use `dns config` to change service mode only

- src/lib/spinel/spinel.h
This commit aligns the documentation in `spinel.h` with the implementation for `SPINEL_PROP_IPV6_ADDRESS_TABLE` regarding the order of valid/preferred lifetime fields.
> [spinel] correct `SPINEL_PROP_IPV6_ADDRESS_TABLE` documentation

- src/core/net/srp_client.cpp
- src/core/net/srp_client.hpp
- src/core/thread/address_resolver.cpp
- src/core/thread/network_data_publisher.cpp
- src/core/thread/network_data_publisher.hpp
- src/core/thread/network_data_service.cpp
- src/core/thread/network_data_service.hpp
- tests/unit/test_network_data.cpp
This commit updates `Service::Manager::GetNextDnsSrpUnicastInfo()` to accept a `DnsSrpUnicast::Type`, indicating the desired entry type (either `kFromServiceData` or `kFromServerData`). This simplifies the code, which previously iterated over all types and performed type checks. Additionally, this change simplifies the `Publisher` methods used for counting existing DNS/SRP unicast entries of different types.
> [netdata] update `GetNextDnsSrpUnicastInfo()` to use `Type`

- src/posix/platform/config_file.cpp
- src/posix/platform/config_file.hpp
The length of the configuration file path may exceed the default defined max length 255.
This commit changes the name of file path max length from `kFileNameMaxSize` to `kFilePathMaxSize`, and sets the value of `kFilePathMaxSize` to the PATH_MAX.
Related issue: https://github.com/openthread/ot-br-posix/issues/2445
> [posix] update the max size of file path to PATH_MAX

- src/core/backbone_router/bbr_leader.cpp
- src/core/backbone_router/bbr_local.cpp
- src/core/net/srp_client.cpp
- src/core/net/srp_client.hpp
- src/core/thread/address_resolver.cpp
- src/core/thread/network_data_publisher.cpp
- src/core/thread/network_data_publisher.hpp
- src/core/thread/network_data_service.cpp
- src/core/thread/network_data_service.hpp
- tests/unit/test_network_data.cpp
This commit updates the `NetworkData::Service::Manager` class to provide helper methods for adding and removing different service types (DNS/SRP anycast or unicast services, backbone router service).
With this change, the definitions of `ServiceData` and `ServerData` formats for different service types are now `private` to the `Service::Manager` class. This centralizes the logic for constructing and parsing the service/server TLVs, making it easier to update and add new fields to these formats in the future.
----
~This PR contains the commit from https://github.com/openthread/openthread/pull/10620. Please check and review the second commit. Thanks.~
> [netdata] centralize service/server TLV logic in `Service::Manager`

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- tests/unit/test_routing_manager.cpp
This commit updates `RoutingManager::RioAdvertiser` to advertise deprecating prefixes with `NetworkData::kkRoutePreferenceLow`. `test_routing_manager` is updated to validate this new behavior.
-----
Related to [SPEC-1272](https://threadgroup.atlassian.net/browse/SPEC-1272).
> [routing-manager] advertise deprecating RIO prefixes with low preference

- include/openthread/border_agent.h
- include/openthread/coap_secure.h
- include/openthread/instance.h
- src/cli/README.md
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/cli/cli_coap_secure.cpp
- src/cli/cli_coap_secure.hpp
- src/core/api/border_agent_api.cpp
- src/core/api/coap_secure_api.cpp
- src/core/coap/coap_secure.cpp
- src/core/coap/coap_secure.hpp
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/meshcop/joiner.cpp
- src/core/meshcop/joiner.hpp
- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
- src/core/radio/ble_secure.cpp
- src/core/radio/ble_secure.hpp
- tests/scripts/thread-cert/border_router/test_ephemeral_key.py
- tests/scripts/thread-cert/border_router/test_ephemeral_key_counters.py
- tests/scripts/thread-cert/node.py
Adds API to get border agent counters which include counters for ePSKc, PSKc and coap messages.
> [epskc] add API for ePSKc telemetry

- src/core/thread/key_manager.cpp
- src/core/thread/key_manager.hpp
- src/posix/platform/backtrace.cpp
- src/posix/platform/netif.cpp
Fix one serious and two less serious uninitialized memory access bugs in openthread. All of these were found using valgrind.
- zero signal handler memory access
- zero otSecurityPolicy structure during SecurityPolicy class constructor
- do *not* access netlink message error TLVs if the extended ack flag is not set in the message
- this can happen when the kernel is too old to support the netlink socket option.
- this bug has led to segmentation faults and in one case a livelock.
> [core] valgrind reported memory access bugs

- src/core/coap/coap.cpp
- src/core/common/heap_string.cpp
- src/core/common/string.cpp
- src/core/common/string.hpp
- src/core/diags/factory_diags.cpp
- src/core/net/srp_client.cpp
- src/core/radio/trel_interface.cpp
- src/core/utils/parse_cmdline.cpp
This commit replaces the use of `strcmp()` with `StringMatch()`, which is an OT-specific internal function for comparing strings. This ensures consistent use of internal helper functions.
> [core] replace `strcmp()` with `StringMatch()`

- examples/platforms/simulation/alarm.c
- examples/platforms/simulation/radio.c
- examples/platforms/simulation/virtual_time/alarm-sim.c
- include/openthread/instance.h
- include/openthread/platform/time.h
- src/posix/platform/alarm.cpp
- src/posix/platform/hdlc_interface.cpp
- src/posix/platform/multicast_routing.cpp
- src/posix/platform/platform-posix.h
- src/posix/platform/radio.cpp
- src/posix/platform/spi_interface.cpp
This commit unifies macros used for time unit conversion so that we don't need to define them on different components.
> [time] unify macros for time unit conversion

- include/openthread/instance.h
- include/openthread/link.h
- src/core/api/link_api.cpp
- src/lib/spinel/radio_spinel.cpp
- src/lib/spinel/radio_spinel.hpp
This commit fixes an issue in `RadioSpinel` related to the tracking of the MAC frame counter used during RCP restoration. Previously, `RadioSpinel` tracked the last seen counter on any secured received/transmitted frame. However, the frame counter should only be tracked for frames that use Key ID Mode 1 and where the included Key ID in the frame matches the current Key ID being used. The `SubMac` module also tracks the current MAC frame counter, and it does perform Key ID Mode and Key ID checks.
This commit adds a new public API `otLinkGetFrameCounter()` to get the current frame counter. This is used by `RadioSpinel` to get the frame counter instead of having `RadioSpinel` track the frame counter itself.
---------
- Should resolve #10633
> [radio-spinel] fix tracking of current MAC frame counter

- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
This commit adds code to include the Link Margin TLV in MLE Child Update Request or Response messages sent by a parent to a child. This allows the child to learn and update its "link quality out" to its parent.
The change is designed to be backward compatible. Child devices running older firmware will simply disregard this additional TLV. When processing the message, the presence of the Link Margin TLV is checked (it is optional).
---
Related to [SPEC-1245](https://threadgroup.atlassian.net/browse/SPEC-1245).
~This PR currently contains the commit from https://github.com/openthread/openthread/pull/10627. Please review the last commit. Thanks.~
> [mle] include Link Margin TLV in Child Update messages

- src/core/diags/README.md
- src/core/diags/factory_diags.cpp
- src/core/diags/factory_diags.hpp
- tests/scripts/expect/cli-diags.exp
This commit extends the `diag frame` command by adding an argument `-s` to indicate whether the frame has been encrypted or not, so that the diag commands can be used to test frames having security processed in the host.
> [diag] support send security processed frames

- script/git-tool
This commit adds the `--no-rebase` flag to `git` command when applying dependencies because recent git versions doesn't have a default rebase strategy anymore.
Without this flag, if the dependency may fail to be pulled when a merge is required.
> [git-tool] explicit disable rebase

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/network_diagnostic_tlvs.cpp
- tests/toranj/cli/test-023-mesh-diag.py
This commit updates the code to include the Supervision Interval TLV in MLE messages sent from a child only when the child mode indicates it is sleepy (`!IsRxOnWhenIdle()`). The Network Diagnostic Child TLV is also updated to use zero for the "Supervision Interval" field when the child is not sleepy. The `test-023-mesh-diag.py` is updated to validate this new behavior.
The parent node still tracks the received supervision interval from a child in the `Child` entry. This parameter indicates the interval that would be used if the child were to be supervised.
----
Related to [SPEC-1302](https://threadgroup.atlassian.net/browse/SPEC-1302).
> [mle] include Supervision TLV only from sleepy child

- src/core/radio/radio_platform.cpp
This commit makes the default otPlatRadioGetNow implementation fallback to to otPlatTimeGet so that the default one is a correct implementation in single chip architecture.
> [radio] otPlatRadioGetNow fallback to otPlatTimeGet

- src/posix/platform/hdlc_interface.cpp
- src/posix/platform/radio_url.cpp
This lets us preserve legacy behavior where "`uart-flow-control`" was not required in radio URL parameters even with hardware flow control enabled.
> [posix] add radio URL parameter `uart-init-deassert` to deassert DTR and RTS on init when flow control is disabled

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- src/core/thread/tmf.cpp
This commit doesn't forward the MGMT*GET/SET commands directly to leader any more, and enforces the use of UDP Proxy for Thread Management Commands if needed for external commissioner
[SPEC-1316](https://threadgroup.atlassian.net/browse/SPEC-1316)
> [border-agent] not forward MGMT_GET/SET commands directly to leader

- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
The PR #10608 added ConnectEvent to notify the coap secure session connection status. It missed to set the event to `kDisconnectedLocalClosed` when the Disconnect() is called outside Process().
> [dtls] notify kDisconnectedLocalClosed when disconnect locally

- .code-spell-ignore
- include/openthread/ble_secure.h
- include/openthread/instance.h
- include/openthread/platform/multipan.h
- src/core/coap/coap.hpp
- src/core/common/heap_string.hpp
- src/core/common/string.hpp
- src/core/radio/ble_secure.hpp
- src/core/radio/radio.hpp
- src/core/thread/link_metrics.hpp
- src/core/thread/network_data_types.hpp
- src/lib/spinel/radio_spinel.hpp
- src/lib/spinel/spinel.h
- src/posix/platform/netif.cpp
- tests/scripts/thread-cert/command.py
- tests/scripts/thread-cert/test_crypto.py
This PR is done by `script/code-spell` with some manual fixes.
> [doc] fix typos in comments

- src/core/mac/data_poll_sender.cpp
- src/core/mac/mac.cpp
- src/core/mac/mac_frame.cpp
- src/core/mac/mac_frame.hpp
- src/core/mac/sub_mac_csl_receiver.cpp
- src/core/thread/mesh_forwarder.cpp
This commit provides unified methods for checking whether the CSL IE is present and getting the CSL IE.
> [csl] add `Mac::Frame` methods to process the CSL IE

- src/posix/platform/netif.cpp
- src/posix/platform/platform-posix.h
- src/posix/platform/resolver.cpp
- src/posix/platform/system.cpp
This PR introduces `platformResolver*` APIs so that `system.cpp` can treat resolver as an independent module. 
Reasons for this refactor:
- Simplify the integration on Android platform.
- The functionality of resolver is not related to the functionality of netif.
> [posix] decouple `resolver.cpp` from `netif.cpp`

- src/posix/platform/include/openthread/openthread-system.h
- src/posix/platform/resolver.cpp
- src/posix/platform/resolver.hpp
This PR adds 2 system APIs for resolver for integration on Android platform.
- `otSysUpstreamDnsServerSetResolvConfEnabled` is for enabling/disabling retrieving the DNS servers from `resolve.conf`.
- `otSysUpstreamDnsSetServerList` for specifying the DNS servers on the infra link.
> [posix] support specifying DNS server for resolver

- src/core/meshcop/tcat_agent.cpp
- src/core/meshcop/tcat_agent.hpp
- src/core/radio/ble_secure.cpp
- src/core/radio/ble_secure.hpp
- tools/tcat_ble_client/bbtc.py
- tools/tcat_ble_client/ble/ble_stream_secure.py
- tools/tcat_ble_client/ble/udp_stream.py
- tools/tcat_ble_client/cli/base_commands.py
* Fixes to connection state management and handling of Disconnect command TLV
* specifically, this now ensures that TCAT remains on (started) after a commissioner disconnects. Earlier, there was the problem that the 2nd commissioner couldn't connect anymore.
* specifically, in `ble_secure.cpp` the check for `if (mTcatAgent.IsEnabled())` is removed, since the `err = mTcatAgent.Connected(mTls)` will already check this and raise an error if not enabled. If not enabled, the Device is in a wrong state to handle TCAT Commissioner commands so now it closes the connection right away. That's better than to leave the Commissioner in limbo on the TLS connection. The Commissioner can now retry again and all will be well again.
* timeout of at most 10 seconds on UDP write operation in simulation mode …
> [tcat][ble] fixes to connection state mgmt and Disconnect cmd; comments updated

- src/core/mac/sub_mac.cpp
- src/ncp/ncp_base_mtd.cpp
This commit fixes the pcap callback for TX frames:
* Report the tx frame on each tx started callback, so that retransmissions can be captured.
* Set the RSSI to be invalid for TX frames.
> [pcap] fix pcap callback for TX frames

- src/lib/spinel/spinel.h
This commit corrects the description of STREAM_RAW.
- timestamp should be type `X`.
- channel can be both RX and TX channel.
> [spinel] correct description of STREAM_RAW

- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
Avoid processing announce messages with equivalent data that is stored in a pending dataset update.
Implements changes that support proposed spec text update in [SPEC-1311.](https://threadgroup.atlassian.net/browse/SPEC-1311)
> [mle] prioritize equivalent pending dataset update over MLE announce

- include/openthread/instance.h
- include/openthread/trel.h
- src/cli/README.md
- src/cli/cli.cpp
- src/core/api/trel_api.cpp
- src/core/radio/trel_interface.hpp
- tests/scripts/thread-cert/border_router/test_trel_connectivity.py
- tests/scripts/thread-cert/node.py
The test software for certification currently uses the mDNS packets of trel service responses to find out the trel port, and then use the port number to determine which packets in a capture should be decoded as TREL packets. However this may not be reliable since it depends on when the capture starts. Added a cli to get trel port, so this can be used by a THCI function.
> [trel] add cli to get TREL UDP port

- .github/workflows/otci.yml
This commit update the otci workflow to use ubuntu-22.04 because some dependency fails to build on ubuntu-20.04
> [test] use ubuntu 22.04 for otci workflow

- examples/platforms/utils/mac_frame.cpp
- examples/platforms/utils/mac_frame.h
- include/openthread/instance.h
- include/openthread/platform/radio.h
- src/ncp/ncp_base_mtd.cpp
This commit adds tx timestamp so that the pcap callback can get the time when a frame was transmitted. This commit also adds channel, LQI and timestamp info in pcap handler in ncp.
> [radio] add tx timestamp

- src/core/common/log.hpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
This commit simplifies logging methods (e.g., `LogIp6Message()`) in the `MeshForwarder` class:
- Log lines are prepared in a `String`, allowing new fields to be added conditionally. This simplifies the code and avoids complex `printf`-style formats for handling optional fields.
- New helper methods are added to prepare common labels in a log line (e.g., adding MAC address, adding security/error/priority fields).
- Logging IPv6 source/destination addresses is simplified by defining a new helper to log an address/port.
> [mesh-forwarder] simplify logging messages

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
This commit updates and simplifies the tracking of information (message priority, drop status) for forwarded mesh-header fragmented frames. This is used for consistent priority assignment to all fragments of the same message and facilitates delay-aware queue management, where dropping one fragment leads to dropping all subsequent fragments of the same message.
The entry type is renamed to `FwdFrameInfo`, and an `Array` is used to track the entries. Array helper methods such as `RemoveAllMatching()` and `FindMatching()` help simplify the code. Since `Array` tracks the current length, iterating over unused entries is avoided.
> [mesh-forwarder] use `Array` to track forwarded frame info

- include/openthread/ble_secure.h
- include/openthread/instance.h
- src/cli/cli_tcat.cpp
Commit adds documentation to tcat CLi commands, also removes incorrect parameter form `otBleSecureTcatStart`.
> [tcat] TCAT documentation cleanup

- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
- src/core/thread/router_table.cpp
- src/core/thread/router_table.hpp
This commit replaces uses of the term "FED" in comments and method names with "FTD child" where the logic applies to any FTD child (i.e., both FED and REED). This clarifies the behavior and aligns the code with Thread specification terminology.
> [mle] replace "FED" with "FTD child" when applicable

- examples/platforms/simulation/ble.c
- include/openthread/instance.h
- include/openthread/trel.h
- src/core/common/debug.hpp
- src/core/crypto/context_size.hpp
- src/core/crypto/hkdf_sha256.cpp
- src/core/crypto/hkdf_sha256.hpp
- src/core/diags/factory_diags.cpp
- src/core/net/ip6.cpp
- src/core/radio/max_power_table.hpp
- src/ncp/ncp_base_mtd.cpp
- src/posix/platform/firewall.hpp
- src/posix/platform/utils.hpp
- tests/unit/test_multipan_rcp_instances.cpp
This commit updates `#include` of public OT headers to follow the OT style guide and use brace (`<`) and (`>`) style.
> [include] fix `#include` style for public OT headers

- src/core/coap/coap_message.cpp
This commit updates `Coap::Message::ParseHeader()` to perform two crucial validations:
- It now checks if the message contains sufficient bytes to read the minimum 4-byte CoAP header.
- Afterwards, determines the CoAP token length from the read header, and then validates that the message has enough bytes to read the token.
These validations prevent the parsing and misinterpretation of a malformed or incomplete CoAP message as a valid one,
> [coap] ensure CoAP header and token length are validated

- include/openthread/border_agent.h
- include/openthread/instance.h
- src/core/common/settings.cpp
- src/core/common/settings.hpp
- src/core/meshcop/border_agent.cpp
This commit simplifies how Border Agent ID is saved in non-volatile `Settings` by utilizing generic methods designed for single-value setting entries. As a result, `Settings::BorderAgentId` now only needs to define the key and the associated entry value type. This eliminates the need for `otBorderAgentId` to be defined as packed, thereby simplifying this structure.
> [settings] simplify saving of Border Agent ID

- src/core/common/message.cpp
- src/core/common/message.hpp
- tests/unit/test_message.cpp
This commit updates and clarifies the behavior of `Message::ReadByte()` and `Message::Read()` overloads regarding partial reads.
- `ReadByte()` will read the available bytes and return the actual number of bytes read if fewer bytes are available in the message than the requested read length. This behavior remains unchanged. The documentation is updated to emphasize this behavior.
- `Read()` methods return `kErrorParse` if the requested length cannot be read. This is the existing behavior which remains unchanged. Previously, `Read()` methods would still perform a partial read and populate the buffer/object with as many bytes that could be read, even in case of failure and returning `kErrorParse`. This behavior has been changed in this commit so the method will skip reading/copying bytes if …
> [message] clarify partial read behavior of `Read()` vs `ReadByte()`

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
This commit renames `Mle::Handle{Command}()` methods where different overloads are provided (e.g. in `Mle` and `MleRouter`) based on device role or being an FTD. The method names now explicitly mention the constraints (e.g. `HandleChildUpdateRequestOnChild()` or `HandleAdvertisementOnFtd()`). This change aims to improve code readability, making it easier to determine the purpose of each method.
> [mle] rename `Mle::Handle{Command}()` methods to indicate constraints

- third_party/tcplp/bsdtcp/tcp_subr.c
When building and linking with link time optimizations and TCP is not enabled (OPENTHREAD_CONFIG_TCP_ENABLE = 0) the following error occurs:
tcp_subr.c:96: undefined reference to tcplp_sys_get_ticks'
To address the problem we are removing the __attribute__((used)) annotation on the initialize_tcb function which will prevent the function from being retained when no one references it.
> [tcplp] fix an issue that occurs when using LTO and TCP is not enabled

- src/core/radio/radio_platform.cpp
This commit adds the `extern "C"` specifier to all `OT_TOOL_WEAK` `otPlat` definitions to ensure correct linkage when compiled with a C++ compiler. It also explicitly includes `platform/time.h` in `radio_platform.cpp`.
> [radio-platform] add `extern "C"` for weak `otPlat` definitions

- src/core/mac/mac_frame.cpp
- src/core/thread/mle_tlvs.cpp
This commit removes redundant namespace qualifiers from two instances within core modules, preventing potential build warnings with certain toolchains.
> [core] remove redundant namespace usage

- tools/cp-caps/CHANGE_LOG.md
- tools/cp-caps/README.md
- tools/cp-caps/rcp_caps_test.py
This commit adds a version command to cp-caps to get the current version. And we release the current version of cp-caps as 0.1.0.
> [test] add version command to cp-caps

- include/openthread/border_agent.h
- include/openthread/instance.h
- src/cli/README.md
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
This commit enhances how ephemeral key timeout is used. If the timeout expires while a commissioner or commissioner candidate is connected, the session will be terminated. The Border Agent (BA) will then stop using the ephemeral key and revert to using PSKc.
The ephemeral key timeout timer starts when the ephemeral key is set on the BA. During this timeout interval, the ephemeral key can be used only once by an external commissioner to establish a secure connection.
---
Related to [SPEC-1310](https://threadgroup.atlassian.net/browse/SPEC-1310)
> [border-agent] update ephemeral key connection timeout handling

- include/openthread/dataset.h
- include/openthread/instance.h
- src/core/meshcop/meshcop_tlvs.hpp
- src/core/meshcop/network_name.cpp
- src/core/meshcop/network_name.hpp
- src/core/thread/mle_router.cpp
This commit adds the Thread Domain Name TLV (59) to the MLE Discovery Response message. The TLV is only included if not equal to 'DefaultDomain', as per Thread 1.4 spec Section 8.4.4.1.1.2.
Also, the TLV is only included for Thread 1.4 or higher builds.  This is because for Thread < 1.4 the inclusion of this TLV was only specified for CCM devices. Thread 1.4 changed this: the TLV is now included if the domain name is not equal to the default name "DefaultDomain" specified in Section 5.22. 
The purpose of including the domain name is to allow discovery of Thread Networks that belong to the same domain that the Joiner is part of. This is used by any commissioning methods where the Thread device can roam e.g. CCM/CCM-light or other (future) methods.
Related JIRA: …
> [mle] add Thread Domain Name TLV (59) to MLE Discovery Response

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/utils/slaac_address.cpp
- src/core/utils/slaac_address.hpp
- tests/toranj/cli/cli.py
- tests/toranj/cli/test-035-context-id-change-addr-reg.py
- tests/toranj/start.sh
This commit improves how MTD children register their IPv6 addresses with their parent. The `Slaac` class now tracks the Lowpan Context ID (from Network Data) for each SLAAC address. If the Context ID associated with an existing SLAAC address changes (due to Network Data updates), the `Slaac` module notifies the `Mle` to schedule a "Child Update Request" transmission (if the device is an MTD child). This ensures that the MTD child re-registers its addresses, resolving any previous registration failures caused by incorrect or outdated context ID compression.
This commit also adds `test-035-context-id-change-addr-reg.py` to validate the newly added behavior.
----
Related to https://github.com/openthread/openthread/issues/10737.
> [mle] enhance MTD child IPv6 address registration

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
This commit introduces the `DelayedSender` nested class within `Mle` to handle delayed MLE message transmissions, such as delayed responses. Existing methods related to delayed message handling have been refactored into this new class.
> [mle] add `DelayedSender` class to manage delayed msg tx

- src/core/net/dns_client.cpp
- tests/unit/test_dns_client.cpp
This commit fixes an issue in `Client::ReplaceWithIp4Query()` where an IPv6 address resolution query failure could lead to an incorrect IPv4 query being sent. The incorrect query type was being checked in this method, causing `ResolveIp4Address()` to keep sending queries.
----
[test] enhance `test_dns_client` to include addr resolution query (#10766)
This commit updates `test_dns_client` to validate independent address resolution queries (in addition to the existing service resolution tests). Specifically, it adds test cases for `ResolveIp4Address()` and scenarios where the server responds with an error RCODE.
----
Added a second commit that adds a test case. Having two commits makes it easier to cherry-pick the fix.
Addresses #10764
> [dns-client] fix handling of IPv4 resolve failure

- src/core/meshcop/border_agent.cpp
This commit updates how Keep Alive messages are handled by the Border
Agent. After establishing a secure session, a device has
`TIMEOUT_COMM_PET` (50 seconds) to take any action, including sending
a petition to become an Active Commissioner. This change ensures that
Keep Alive messages are ignored before a device becomes an Active
Commissioner, preventing candidates from extending their sessions.
Keep Alive messages are now processed only for Active Commissioners
(BA in `kStateAccepted` state), aligning the implementation with the
Thread specification. 
Update as clarification in [SPEC-1310](https://threadgroup.atlassian.net/browse/SPEC-1310)
> [border-agent] process Keep Alive messages only for active commissioner

- src/core/net/nd6.cpp
- src/core/net/nd6.hpp
This commit adds `CONFIG_BORDER_ROUTING_ENABLE` guard checks to `nd6.hpp` and `nd6.cpp` source files, as the definitions in these files are only used when the `BORDER_ROUTING` feature is enabled.
> [nd6] add `CONFIG_BORDER_ROUTING_ENABLE` guard check

- src/core/coap/coap.cpp
- src/core/coap/coap.hpp
- src/core/common/message.hpp
- src/core/meshcop/joiner_router.cpp
- src/core/meshcop/joiner_router.hpp
- src/core/net/dnssd_server.cpp
- src/core/net/dnssd_server.hpp
- src/core/net/ip6_mpl.cpp
- src/core/net/ip6_mpl.hpp
- src/core/net/sntp_client.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
This commit adds the `Message::FooterData<>` template class, which represents data (typically metadata) associated with a `Message` that is appended to the end of the message. It can be read later from the message, updated (re-written) in the message, or fully removed from it.
The `FooterData` class provides common helper methods such as `AppendTo()`, `ReadFrom()`, `UpdateIn()`, and `RemoveFrom()` in a generic way. This helps simplify the various `Metadata` types defined within the OT core modules, removing repeated definitions of similar methods for each type.
> [message] introduce `FooterData<DataType>` class

- src/core/common/frame_builder.cpp
- src/core/common/frame_builder.hpp
- src/core/mac/data_poll_sender.cpp
- src/core/mac/mac.cpp
- src/core/mac/mac_frame.cpp
- src/core/mac/mac_frame.hpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
- tests/unit/test_mac_frame.cpp
This commit simplifies the preparation of MAC and security frames. It introduces a `TxFrame::Info` structure that provides information about the frame, such as its type, version, source and destination addresses, PAN IDs, security level, and key ID mode. A new method `PrepareHeadersIn()` is added, which uses the `Info` structure to construct the MAC address and security headers in a given `TxFrame`.
This approach replaces the earlier `Mac::Frame::InitMacHeader()` where all the information was passed as a list of input arguments. The `TxFrame::Info` approach simplifies the code and allows for future extension to accommodate other parameters (e.g., Header IE entries).
> [mac-frame] add `TxFrame::Info` and simplify mac header preparation

- src/core/mac/mac_frame.cpp
- tests/unit/test_mac_frame.cpp
This commit updates `TxFrame::GenerateWakeupFrame()` to utilize the `FrameBuilder` class for constructing frame header fields.
It also updates the `TestMacWakeupFrameGeneration()` unit test in `test_mac_frame.cpp`:
- Uses source and destination address constants that are not reversible to validate that extended addresses are appended in the correct byte order.
- Includes minor style changes (renames constants and uses lowercase hexadecimal digits for consistency).
> [mac-frame] update `GenerateWakeupFrame()` to use `FrameBuilder`

- src/core/mac/mac_frame.cpp
- src/core/mac/mac_frame.hpp
- tests/unit/test_mac_frame.cpp
Recent changes updated `Mac::Frame` to use `FrameBuilder` for preparing frame headers. With the adoption of this model, the previously defined `Set` methods for setting source/destination address or PAN ID are no longer used or needed. This commit removes them.
> [mac-frame] remove unused `Set{Src/Dst}{Addr/PanId}()` methods

- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
`MBEDTLS_SSL_COOKIE_C` is only used on the server. There is no point in initializing it on the client side.
> [secure-transport] only initialize `mCookieCtx` on the server

- src/core/mac/mac_frame.cpp
- src/core/mac/mac_frame.hpp
This commit adds the `DetermineFcfAddrType()` helper function, which determines the Frame Control Field (FCF) address type for a given address. The result is bit-shifted based on whether the address is the source or destination and whether the frame uses the general format or is a multipurpose frame. This helper simplifies methods that prepare MAC headers.
> [mac-frame] add `DetermineFcfAddrType()` helper

- tools/tcat_ble_client/bbtc.py
- tools/tcat_ble_client/ble/ble_scanner.py
- tools/tcat_ble_client/ble/ble_stream.py
Added '-a', '--adapter' arguments to the bbtc.py arguments parser. This allows the selection of the HCI adapter for the scanning procedure.
According to 'Bleak' documentation of the 'BleakClient' class(https://bleak.readthedocs.io/en/latest/api/client.html#bleakclient-class), it's better to use the 'BLEDevice' object in 'BleakClient' during the object instantiation, therefore it has been changed for the scanning procedure.
> [tcat] feat: add 'adapter' argument and use 'BLEDevice'

- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
This commit reorders member variables in the `MleRouter` class, grouping booleans and `uint`s of the same size to avoid alignment gaps. It also reorders some of the private method declarations and adds sections for constants, nested types, methods, and variables.
> [mle] reorder `MleRouter` class member variables

- src/core/border_router/routing_manager.cpp
- src/core/net/nd6.hpp
This commit updates `RoutingManager::IsValidOnLinkPrefix()`, which checks whether a received PIO is a suitable on-link prefix. The updated check requires the `L` (on-link) flag to be set, along with either the `A` (autonomous address-configuration) flag or the `P` (DHCPv6-PD preferred) flag. This aligns the implementation with the latest SNAC router draft.
----
Relates to 
- https://github.com/ietf-wg-snac/draft-ietf-snac-simple/pull/92, and
- https://github.com/ietf-wg-snac/draft-ietf-snac-simple/issues/38
> [routing-manager] update valid on-link prefix (PIO) condition

- src/core/thread/mle.cpp
This commit updates the skip condition in `BecomeDetached()` to use positive boolean checks for improved readability. This condition applies when the device is already detached and is about to start an attach attempt.
> [mle] simplify condition in `Mle::BecomeDetached()`

- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
This commit updates `SendParentResponse()` to accept `aChild` as a `Child &` instead of a `Child *`, as it will always expect a valid child object and won't handle a `nullptr` input.
> [mle] update `SendParentResponse()` to use `Child &` input

- src/lib/spinel/radio_spinel.cpp
- src/ncp/ncp_base_radio.cpp
- tests/gtest/CMakeLists.txt
- tests/gtest/fake_coprocessor_platform.cpp
- tests/gtest/fake_coprocessor_platform.hpp
- tests/gtest/radio_spinel_rcp_test.cpp
This commit passes the tx power from host to coprocessor. This commit also adds a new fake platform for coprocessor to cover the changes in RadioSpinel and coprocess.
> [spinel] support per-frame TX power in coprocessor

- src/core/thread/indirect_sender.cpp
- src/core/thread/indirect_sender.hpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mle_router.cpp
This commit adds new helper methods in `IndirectSender` to find a queued message for transmission to a given sleepy child that also satisfies a certain condition (using a general-purpose predicate `MessageChecker` function pointer).
These helpers are then used in `IndirectSender` and `MleRouter` to simplify the code, particularly in `SendChildUpdateRequest()`, where sending multiple "Child Update Request" messages to a sleepy child being restored (after a parent restart/reboot) should be avoided.
> [indirect-sender] add `HasQueuedMessageForSleepyChild()`

- src/core/mac/mac_frame.cpp
- src/core/mac/mac_frame.hpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
This commit updates `TxFrame::Info` and `PrepareHeadersIn()` to prepare header IE entries along with MAC and security headers. New boolean fields in `TxFrame::Info` indicate whether CSL or Time IE entries should be appended to the frame. This simplifies the code, particularly `MeshForwarder::PrepareMacHeader()`, which now just sets these flags on `TxFrame::Info`. It also allows for the removal of `AppendHeaderIe<>()` and its related methods.
This commit also updates `GenerateWakeupFrame()` to use the new model for appending `RendezvousTimeIe` and `ConnectionIe` fields.
----
~This PR currently contain the commit from https://github.com/openthread/openthread/pull/10689. Please read and review the last commit on this PR. Thanks.~
> [mac] simplify preparation of header IE entries

- src/lib/spinel/spinel.h
- src/ncp/ncp_base.hpp
- src/ncp/ncp_base_ftd.cpp
- src/ncp/platform/infra_if.cpp
This PR implements sending InfraIf Icmp6 Nd messages on NCP.
This is to support border routing for NCP case. See this https://github.com/openthread/ot-br-posix/issues/2398#issuecomment-2348518919 for the whole picture of this series of changes.
In this PR, a new spinel property SPINEL_PROP_INFRA_IF_SEND_ICMP6 is added for the NCP to send the ICMP6 messages to the host.
> [ncp] add border routing InfraIf send ICMP6 ND

- .github/workflows/unit.yml
- src/core/border_router/routing_manager.cpp
- tests/unit/test_routing_manager.cpp
In some cases, the platform may send the new prefix without deprecating the existing prefix when renewing the prefix allocated by PD.
The existing code will stop the timer, causing the prefix to be active forever.
This PR fixes this issue.
PoC: The first commit of this PR should fail on the new unit test.
(See https://github.com/erjiaqing/openthread/actions/runs/11268919266/job/31336526974)
> [routing-manager] fix for updating prefix without deprecating the old one

- src/lib/spinel/spinel_decoder.hpp
This commit updates the doc of spinel decoder about the parameters are untouched on parsing error.
> [spinel] parameters untouched on decoding error

- tools/tcat_ble_client/cli/dataset_commands.py
- tools/tcat_ble_client/dataset/dataset.py
Added 'clear' command to the 'dataset' command tree. This allows to remove all entries in the 'ThreadDataset' object used by the script to store the dataset values.
The reason behind this feature is that in the current implementation of the script, the 'ThreadDataset' object entries are always initialized by 'initial_dataset' when running the script. No command allows to clear/remove the particular entry, which makes this script unable to send an active dataset to the target device without specific dataset values(custom dataset). To make this possible, the 'clear' command has been added to the 'dataset' command tree, which removes all entries from the 'ThreadDataset' object and, by using existing commands, sets the desired entries in the 'ThreadDataset' object from scratch. This enables …
> [tcat] feat: add dataset clear command

- examples/platforms/simulation/radio.c
- examples/platforms/utils/mac_frame.cpp
- examples/platforms/utils/mac_frame.h
This commit tracks the frame counter used for the previous key index and use it for the ACK frame to a frame still using previous key index.
> [radio] fix ACK frame counter using previous key

- include/openthread/instance.h
- include/openthread/platform/infra_if.h
- src/core/border_router/infra_if.cpp
- src/core/border_router/infra_if.hpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- src/core/net/nd6.cpp
- src/core/net/nd6.hpp
- tests/unit/test_routing_manager.cpp
This PR introduces a platform API to get the InfraIf link-layer address. And add the source link-layer address option to all ND6 messages generated from Openthread.
Related Issue: [Unicast NS sent from should contain source link-layer address option. #10588](https://github.com/openthread/openthread/issues/10588)
> [routing-manager] append source link-layer option in ND6 message

- src/core/common/message.cpp
- src/core/common/message.hpp
- src/core/thread/discover_scanner.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_types.hpp
- tests/unit/test_message.cpp
This commit adds a new field, `mMleCommand`, to `Message::Metadata` to track the MLE command type of the message. Helper methods, such as `IsMleCommand()`, are added to `Message` to get/set/check the MLE command type.
This replaces the previous model where `Message::SubType` was used to track a subset of MLE commands. It helps simplify the code and allow us to track all MLE commands.
> [message] track the MLE command type in Message

- src/core/net/dns_client.cpp
- src/core/net/dns_client.hpp
- tests/unit/test_dnssd_discovery_proxy.cpp
This commit updates the `ReplaceWithIp4Query()` method, which determines whether an unsuccessful IPv6 address query should be followed up with an IPv4 query.
The logic is changed as follows:
- If the response code to the IPv6 query indicates success but the answer section is empty (meaning the name exists but has no IPv6 address), or the response code indicates an error other than `NameError`, the query is replaced with an IPv4 address resolution query for the same name.
- If the server responds with `NameError` (RCode=3), indicating that the name doesn't exist, an IPv4 query is not attempted.
This replaces the previous behavior where a follow-up query was attempted for any error response code.
> [dns-client] enhance logic for following up with IPv4 address query

- .github/workflows/build.yml
Build checks for 32-bit arch are covered by arm-gcc.
> [github-actions] remove clang-32 checks

- script/check-size
See: https://www.shellcheck.net/wiki/SC2004
> [check-size] SC2004: `$`/`${}` is unnecessary on arithmetic variables

- src/core/mac/mac_frame.hpp
- src/core/mac/sub_mac.cpp
- src/core/mac/sub_mac_csl_receiver.cpp
- src/core/radio/radio.hpp
- src/core/thread/csl_tx_scheduler.cpp
This commit adds the `GetNow()` method to the `Radio` class, which maps to `otPlatRadioGetNow()`. This method is used within core modules to avoid calling the `otPlat` API directly, aligning with the practice for all other `otPlatRadio` APIs, which are called through the defined `Radio` class methods.
> [radio] add `Radio::GetNow()`

- tools/tcat_ble_client/cli/dataset_commands.py
- tools/tcat_ble_client/dataset/dataset.py
- tools/tcat_ble_client/dataset/dataset_entries.py
This commit extends the 'dataset hex' command in the bbtc.py script by allowing dataset TLVs to be set using a hex-encoded format.
Till now the 'dataset hex' command was only printing the 'ThreadDataset' object values in hex-encoded format, there was no functionality to set the TLVs using hex-encoded format. The 'dataset hex' command has been modified so the user can pass dataset TLVs in hex-encoded format as an argument to this command. This enables the script to set desired dataset TLVs in one command, instead of calling dataset commands individually. Example usage: 'dataset hex <hex-encoded TLVs>'
> [tcat] feat: extend dataset hex command

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mesh_forwarder_mtd.cpp
This commit adds a new helper method, `FinalizeAndRemoveMessage()`, which finalizes all direct and indirect transmissions of a message before removing it from the send queue. This helper is used by `EvictMessage()` and `RemoveDataResponseMessages()`, simplifying the code.
> [mesh-forwarder] introduce `FinalizeAndRemoveMessage()`

- src/core/net/dns_client.cpp
This commit fixes an issue in `Client::SendQuery` where `mSendLink.mLength` being uninitialized on hardware platform can lead to a `kErrorNoBuffs` error and `InitTcpSocket()` will never get to run due to a possible high value.
https://github.com/openthread/openthread/blob/7ec2c31816eaca343a1916f139b35ad327537b55/src/core/net/dns_client.cpp#L1136
> [dns-client] Initialize mSendLink structure in Client constructor

- tests/gtest/fake_platform.cpp
- tests/gtest/fake_platform.hpp
This PR adds some missing platform API implementation for FakePlatform.
These are added so that FakePlatform can be used to write unit tests in ot-br-posix.
The PR also guards the microSecondTimer code in `FakePlatform` with the marcro `OPENTHREAD_CONFIG_PLATFORM_USEC_TIMER_ENABLE` because `otPlatAlarmMicroFired` is only defined in OT timer.cpp when `OPENTHREAD_CONFIG_PLATFORM_USEC_TIMER_ENABLE` is true.
This PR also removes some parameter names in the fake implementation to avoid unused warnings.
> [test] add missing platform APIs in FakePlatform

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit adds `OnLinkPrefixManager::AddressMatchesLocalPrefix()` method, which checks whether a given address matches the current local on-link prefix only when the prefix is valid (being published, advertised, or deprecated by the BR). This method is used in `RxRaTracker::IsAddressOnLink()`, ensuring that the local prefix is always explicitly checked. This makes the check more robust and independent of whether `RxRaTracker` receives and tracks self-generated RAs.
> [routing-manager] check local on-link prefix in `IsAddressOnLink()`

- src/ncp/ncp_base_mtd.cpp
This PR fixes the bug in NCP Get `SPINEL_PROP_THREAD_ACTIVE_DATASET_TLVS` and `SPINEL_PROP_THREAD_PENDING_DATASET_TLVS`.
There are cases where dataset doesn't exist and `otDatasetGetActiveTlvs` returns `OT_ERROR_NOT_FOUND`. This will cause that the NCP doesn't send any responses to the host. This PR lets the implementation ignore the NOT_FOUND error and will encode empty data in this case.
> [ncp] fix implementation of NCP get dataset tlvs

- examples/apps/cli/main.c
- examples/apps/ncp/main.c
The implementation of `otTaskletsSignalPending` in `examples/apps/<app>/main.c` is exactly the same as the weak implementation in `tasklet_api.cpp`. No need to repeat it and blocking other implementations of that function
> [examples] remove unneeded implementation `otTaskletsSignalPending` in `main.c`

- include/openthread/instance.h
- include/openthread/platform/radio.h
Current radio platform defines three power related APIs: `otPlatRadioSetTransmitPower()`, `otPlatRadioSetChannelMaxTransmitPower()` and `otPlatRadioSetChannelTargetPower()`. However, the descriptions of these APIs do not clearly define the relationship between them, which causes a lot of confusion for radio platform developers.
https://github.com/orgs/openthread/discussions/10761 https://github.com/orgs/openthread/discussions/10611 https://github.com/orgs/openthread/discussions/9899
This commit updates the descriptions these APIs to clearly define the relationship between these power APIs.
> [api] update descriptions of the radio platform power APIs

- include/openthread/border_agent.h
- include/openthread/instance.h
- src/core/meshcop/border_agent.hpp
The docs are updated to mention that users can use the `otBorderAgentDisconnect()` API to forcely disconnect from commissioner sessions.
> [border-agent] update docs for set and clear ephemeral key APIs

- src/lib/spinel/radio_spinel.cpp
- src/lib/spinel/radio_spinel.hpp
- src/posix/platform/radio.cpp
This commit separates RCP version check and capability check in RadioSpinel so that the RCP caps is guaranteed to be initialized correctly.
> [radio-spinel] separate RCP version check and caps check

- include/openthread/instance.h
- include/openthread/nat64.h
- src/core/api/nat64_api.cpp
- src/core/net/nat64_translator.cpp
- src/core/net/nat64_translator.hpp
This PR introduces a new API `otNat64ClearIp4Cidr` which is useful when the in-use NAT64 CIDR is preempted and the platform fails to allocate a new IPv4 CIDR. In such a (rare) case we'd better notify OT that there isn't an available CIDR. `otNat64SetIp4Cidr` doesn't support an 0-length CIDR as the input so we'll have to introduce this new API.
> [nat64] add API `otNat64ClearIp4Cidr` 

- .code-spell-ignore
- src/core/net/nat64_translator.cpp
- tests/unit/test_nat64.cpp
When allocating a new NAT64 mapping table item to a transaction, the counters might be dirty, causing incorrect counter values in NAT64 mapping protocol counters.
> [nat64] clear NAT64 counters when allocating new mapping table item

- include/openthread/border_agent.h
- include/openthread/instance.h
- src/core/meshcop/border_agent.cpp
This commit updates the Border Agent to invoke the ephemeral key callback when a commissioner candidate successfully establishes a secure session using the ephemeral key. This can be identified by checking the state `otBorderAgentGetState()` and matching it with `OT_BORDER_AGENT_STATE_ACTIVE`. This new signal can be used to stop advertising the mDNS service "_meshcop-e._udp" earlier (since the ephemeral key is one-time use).
> [border-agent] invoke ephemeral key callback on session connection

- tests/scripts/thread-cert/border_router/internet/test_upstream_dns.py
There's a [CI failure](https://github.com/openthread/ot-br-posix/actions/runs/11590671688/job/32317956417?pr=2571) that the BR sends the query to 8.8.8.8 as the upstream DNS server and responded to the DNS client. This is undesired behavior. We want the BR to query our test DNS server instead.
The issue happened because 8.8.8.8 is already an entry in `/etc/resolv.conf`. To avoid querying it, we should fully overwrite the `/etc/resolv.conf` to ensure the BR queries the test DNS server.
There's another issue that `bind9` service was also running on the BR node which taken over all incoming DNS queries. `bind9` should only run on the upstream DNS server node. I'll try fix this in a more generic way later.
> [tests] fix `test_upstream_dns.py` 

- src/posix/platform/include/openthread/openthread-system.h
- src/posix/platform/openthread-posix-config.h
- src/posix/platform/system.cpp
- src/posix/platform/trel.cpp
The current TREL implementation uses TREL URL to pass in the TREL interface at system start. This works for devices that have a fixed interface for TREL.
There are devices that can dynamically switch infrastructure link, for those devices it's possible that infra link changes from ethernet to wifi and TREL should be re-configured on the new interface.
> [trel] add otSys API to init/deinit TREL

- include/openthread/instance.h
- include/openthread/udp.h
- src/core/net/udp6.cpp
- src/core/net/udp6.hpp
This commit updates `otUdpSocket` to track the associated network interface identifier to which the socket is bound. This simplifies the code for tracking backbone sockets, particularly how `Udp::HandlePayload()` finds a matching socket.
Previously, backbone sockets were placed at the end of the `mSockets` linked-list. The code tracked and updated a pointer to the entry before the first backbone socket in the list. This commit removes the need for this additional tracking and simplifies the implementation.
> [udp] track netif ID in socket and simplify handling of backbone sockets

- src/posix/platform/trel.cpp
Started from #10872, platform trel stays un-initialized if no TREL URL is passed in, it also allows deiniting platform TREL with `otSysTrelDeinit`. `otPlatTrelEnable` and `otPlatTrelDisable` asserted for `sInitialized`, and caused crashes when called. 
This PR changes the asserts to VerifyOrExit() to allow otPlatTrelEnable/Disable calls when platform TREL is not initialized, also added check for `sEnabled` when registering service to skip registering any services when uninitialized.
> [trel] fix crash

- src/core/api/link_raw_api.cpp
- src/core/mac/sub_mac.cpp
- src/core/radio/radio.cpp
- src/core/radio/radio.hpp
- src/core/thread/src_match_controller.cpp
This commit reverses the Extended Address in radio layer so that the reversing can be shared by multiple callers.
> [radio] reverse extended address in radio layer

- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
This commit applies style fixes and renames in the `SecureTransport` class, including using the `k` prefix for constants and removing unused member variables.
> [secure-transport] apply style fixes and renames

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
- tests/unit/test_dns_client.cpp
This commit updates how `Mle::DelayedSender` sends MLE messages after a delay.
Previously, a delayed message was fully prepared and placed in a queue, waiting for its delay duration to expire. In the new model, a delayed message is prepared when the requested delay time expires and the message transmission time is reached. The message is constructed right before transmission. This ensures that the delayed message includes the most up-to-date information and simplifies the methods that prepare and send different types of MLE messages.
`DelayedSender` now keeps track of the message type and the specific information required to construct the message later. For example, for a delayed Parent Response to a Parent Request, the extended address and the `RxChallenge` of the child are saved.
This …
> [mle] update `DelayedSender` to keep the tx schedule

- src/core/coap/coap.cpp
- src/core/coap/coap_secure.cpp
- src/core/coap/coap_secure.hpp
- src/core/common/message.hpp
- src/core/instance/instance.cpp
- src/core/meshcop/joiner_router.cpp
- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
- src/core/net/icmp6.cpp
- src/core/radio/ble_secure.cpp
- src/core/thread/mle.cpp
- src/core/thread/tmf.cpp
- tests/unit/test_message.cpp
This commit updates the `CoapSecure`, `Tmf`, and `SecureTransport` modules to use the `LinkSecurityMode` enum and its defined constants to indicate whether or not layer two security should be used. This replaces the use of boolean input parameters with `kWithLinkSecurity` or `kNoLinkSecurity` constants, improving code readability.
> [coaps] use `LinkSecurityMode` to determine layer two security usage

- tools/otci/otci/otci.py
The parameters of the method dataset_set_buffer() has been updated, but the method create_dataset() still uses the previous definition of dataset_set_buffer(). It causes the crash when calling the method create_dataset().
> [otci] add the parameter wakeup channel to the method create_dataset

- src/core/common/callback.hpp
- src/core/common/notifier.cpp
- src/core/common/notifier.hpp
This commit simplifies `Notifier` by using `Array` to track registered callbacks.
> [notifier] use `Array` to track external callbacks

- src/core/thread/child_supervision.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
This commit refines the Child Update Request mechanism within the MLE module. The `DelayedSender` class is now used to schedule these requests, enabling the aggregation of multiple updates into a single transmission.
The previous implementation, which relied on `mMessageTransmissionTimer` and a state variable, has been replaced
with the `DelayedSender` mechanism. This change aligns the Child Update Request process with the scheduling of other MLE messages,
ensuring consistency.
Additionally, the `mMessageTransmissionTimer` is now exclusively dedicated to retransmission handling, simplifying the logic and improving code readability. The introduction of two boolean variables, `mWaitingForChildUpdateResponse` and `mWaitingForDataResponse`, further streamlines retransmission handling by …
> [mle] use `DelayedSender` to delay & aggregate Child Update Requests

- src/core/mac/mac_frame.cpp
This commit adds an additional note next to the table from the specification text regarding valid combinations of flags within an encoded MAC header and the interpretation of the "PAN ID Compression" flag.
> [mac-frame] enhance comments regarding PAN ID compression behavior

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
- src/core/thread/mle_types.hpp
- src/core/thread/router.hpp
This commit updates how the Link Accept response timeout is tracked. It is now directly tracked in a `Router` entry using a new member variable, `mLinkAcceptTimeout`, which stores the remaining timeout in seconds. This value is decremented from `HandleTimeTick()` every second.
This model replaces the previous approach, which indirectly used `SetLastHeard()` for this purpose. The earlier method had shortcomings; primarily, `SetLastHeard()` could be called again on receiving a new advertisement, inadvertently pushing back the Link Accept timeout. This model also became problematic when a random delay was introduced before the transmission of Link Requests (e.g., after receiving an advertisement).
This commit also enhances the process for restoring a link when a router is aged (i.e., no …
> [mle] track Link Accept timeout in `Router` entry

- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
This commit renames and updates `HandleLinkAcceptVariant()` used to handle an MLE "Link Accept" or "Link Accept And Request". The method now takes the `MessageType` directly as an input parameter.
> [mle] simplify handling of Link Accept variants

- src/core/common/timer.cpp
- src/core/common/timer.hpp
- src/core/net/mdns.cpp
- src/core/net/mdns.hpp
- tests/unit/test_mdns.cpp
This commit implements response aggregation (RFC 6762 section 6.4) in the mDNS module. If multiple responses are scheduled to be sent, each delayed by a different interval, earlier responses are further delayed to allow aggregation with other responses scheduled to go out a little later.
Before preparing a response, we determine the next multicast transmission time that is explicitly after the current time. This is used for response aggregation. As the response is being prepared, different entries can decide whether to extend their answer delay duration if allowed (e.g., probe question answer delay cannot be extended) and possible (not extending the delay beyond the maximum allowed delay).
To realize this, the way we track the `AnswerTime` of records is changed. It is now tracked by two …
> [mdns] implement response aggregation

- src/core/mac/mac_frame.cpp
This commit ensures that the `mCslPresent` flag is set on `TxFrame` when the CSL IE header is appended to the frame. This addresses an issue introduced in #10692 where this flag can remain unset.
---
Resolves #10938
> [mac-frame] set `mCslPresent` on `TxFrame` when CSL IE is added

- src/core/thread/child.hpp
- src/core/thread/neighbor.hpp
This commit removes unnecessary documentation of private member variables in the `Neighbor` class and updates `enum` based constant , replacing it with `static constexpr`.
> [neighbor] update and clean up property documentation

- src/core/coap/coap.cpp
- src/core/meshcop/secure_transport.cpp
- src/core/net/socket.cpp
- src/core/net/socket.hpp
- src/core/net/srp_server.cpp
This commit adds `Ip6::MessageInfo::HasSamePeerAddrAndPort()` which checks if the peer address and port of two `MessageInfo` objects match. This method is used in different modules (`Coap`, `Srp::Server`, `SecureTransport`) to simplify the code.
> [ip6] add `MessageInfo::HasSamePeerAddrAndPort()`

- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
This commit contains changes to `SecureTransport`:
- Inlines simple methods (`Disconnect()` and `GetUdpPort()`).
- Removes/refactors simpler methods, such as `Receive()` and `HandleSecureTransportSend()`, which are now directly moved into `HandleMbedtlsTransmit()` and `HandleReceive()`.
- Removes unused `SetClientId()` and inlines its implementation.
- Removes extra `LogDebug` line (can be tracked by logging `State` changes).
- Simplifies `HandleMbedtlsReceive()` and how data is read from `mReceiveMessage`.
- Uses a consistent style to refer to function pointers.
> [secure-transport] smaller enhancements in `SecureTransport`

- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
This commit simplifies `SecureTransport::Process()`:
- The `mReceiveCallback` is invoked only after a successful `read()` Afterward, we `continue` back through the loop to check if it can read again.
- The `rval` checks are now combined into a single `switch()` statement to determine if the connection should be disconnected, reset, or if the process should wait, and then takes the proper action.
> [secure-transport] simplify `Process()` method

- examples/platforms/simulation/alarm.c
- examples/platforms/simulation/ble.c
- examples/platforms/simulation/infra_if.c
- examples/platforms/simulation/mdns_socket.c
- examples/platforms/simulation/radio.c
- examples/platforms/simulation/simul_utils.c
- examples/platforms/simulation/trel.c
- examples/platforms/simulation/uart.c
- examples/platforms/simulation/virtual_time/platform-sim.c
Sometimes `ot-rcp` will exit without any exit information in the log. It is hard for developers to know what happens on the `ot-rcp` side when the `ot-rcp` exits abnormally. This commit calls functions defined in `lib/platform/exit_code.h` to exit the program and log the exit information.
> [simulation] log the exit information when the program exits

- src/core/meshcop/secure_transport.cpp
This commit removes the calls to `mbedtls_ssl_close_notify()` in `SecureTransport::Process()` when, based on `rval`, it is determined that `Disconnect()` should be called, as the `Disconnect()` method itself will call `mbedtls_ssl_close_notify()`.
> [secure-transport] remove extra `mbedtls_ssl_close_notify()` calls

- src/core/coap/coap_secure.cpp
- src/core/coap/coap_secure.hpp
- src/core/instance/instance.hpp
- src/core/thread/tmf.cpp
- src/core/thread/tmf.hpp
This commit refactors COAPS classes, renaming the `CoapSecure` class as `CoapSecureBase`, which is the base class of `Tmf::SecureAgent` and a newly added `ApplicationCoapSecure` class. This change simplifies the code and class hierarchy and ensures that the Application COAP secure related functions are only provided by `ApplicationCoapSecure` and when the corresponding config feature `OPENTHREAD_CONFIG_COAP_SECURE_API_ENABLE` is enabled.
> [coap] add base class `CoapSecureBase` and `ApplicationCoapSecure`

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
This commit updates `DelayedSender` to allow scheduling of delayed MLE Link Request messages. This is then used to apply a random delay to send a Link Request when processing a MLE Advertisement from a neighbor.
Advertisement messages are multicast transmissions and can be received by multiple nodes, which could create a synchronized generation of Link Requests from all. This change helps distribute this time over a random window (of one second if the requester is itself a router or [1-2.5] seconds if it is a child).
This aligns the implementation with the Thread specification and can help improve situations where a new router is added (e.g., single device reboot or network-wide reboot due to power shutdown, etc).
----
~Builds on top of commit from …
> [mle] apply random delay when sending Link Request on Adv rx

- src/lib/spinel/radio_spinel.cpp
Return an `OT_ERROR_NO_BUFS` error when src entry count exceeds the maximum instead of crash.
> [spinel] return no_buf error when src entry count exceeds the maximum

- tools/tcat_ble_client/ble/ble_scanner.py
This commit adds 'normalize_uuid_str()' in 'scan_tcat_devices()'. It fixes an issue finding TCAT devices in newer versions of the 'bleak' module.
> [tcat] fix: use normalize_uuid_str() on BBTC_SERVICE_UUID

- tests/unit/test_spinel_prop_codec.cpp
This PR fixes an issue in spinel_prop_codec unit test.
We cannot use Spinel::Decoder::ReadUintPacked with a `spinel_prop_key_t` type. This will cause build errors on arm platforms. This PR should fix the error in ot-kw41z: https://github.com/openthread/ot-kw41z/actions/runs/11942223170/job/33288760985?pr=836
> [spinel] fix spinel_prop_codec unit test

- tests/fuzz/fuzzer_platform.cpp
The Sequence Number Suppression field and AR can be both 1 in fuzz test, in which case, the frame is not valid. And no ack should be expected. This commit changes the expectation in this case.
> [fuzz] expect no ACK if TX frame is invalid

- src/core/mac/data_poll_handler.cpp
- src/core/mac/data_poll_handler.hpp
- src/core/thread/csl_tx_scheduler.cpp
- src/core/thread/csl_tx_scheduler.hpp
- src/core/thread/indirect_sender.cpp
- src/core/thread/indirect_sender.hpp
This commit removes the `Callbacks` class defined for use between `IndirectSender` and its underlying `DataPollHandler` and `CslTxScheduler` components. This model was added earlier in #3952 to make all interactions between these modules asynchronous (callback-based). The objective was to move the handling of data polls and indirect transmissions closer to the MAC layer and allow `DataPollHandler` logic to be moved to RCP in an host and RCP architecture. With the introduction of CSL, this approach is no longer viable, but the callback style was still used. This commit removes this and simplifies the code.
> [indirect-sender] remove callbacks to its sub-components

- src/core/mac/wakeup_tx_scheduler.cpp
- src/core/radio/radio.hpp
- src/core/thread/csl_tx_scheduler.cpp
This commit adds `GetBusSpeed()` and `GetBusLatency()` methods to the `Radio` class, which map to the corresponding `otPlatRadio` platform APIs.
> [radio] add `GetBusSpeed()` and `GetBusLatency()` methods

- src/core/api/radio_stats_api.cpp
- src/core/instance/instance.hpp
- src/core/radio/radio.cpp
- src/core/radio/radio.hpp
- src/core/radio/radio_callbacks.cpp
This commit refactors `Radio::Statistics` to be a nested type within the `Radio` class. It is declared as a `friend` of `Radio` so that its interaction with `Radio` can be defined as `private` methods.
> [radio] refactor `Radio::Statistics`

- src/core/common/log.hpp
Commit aligns define guards on `LogAt` macto and `RegisterLogModule` to match. Previuosly `OT_SHOULD_LOG` was getting default value set as platform defined and log level was buy default set to none which caused misalignment.
> [logging] aling define guards on `RegisterLogModule` and `LogAt`

- src/core/common/num_utils.hpp
- src/core/mac/wakeup_tx_scheduler.cpp
- src/core/net/ip6_address.cpp
- src/core/net/nd6.hpp
- src/core/thread/csl_tx_scheduler.cpp
- tests/unit/test_serial_number.cpp
This commit introduces the `DivideAndRoundUp()` method, which divides two given unsigned integers and always rounds the result up.
> [num-utils] add `DivideAndRoundUp()` helper

- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/mac/wakeup_tx_scheduler.cpp
- src/core/mac/wakeup_tx_scheduler.hpp
- src/core/thread/csl_tx_scheduler.cpp
- src/core/thread/csl_tx_scheduler.hpp
This commit defines the `Mac::kCslRequestAhead` constant, which maps to `OPENTHREAD_CONFIG_MAC_CSL_REQUEST_AHEAD_US`. This constant is used within the core modules.
> [mac] define `Mac::kCslRequestAhead` constant

- src/ncp/ncp_base_ftd.cpp
This PR fixes the wrong implementation of the GetProperty handler of `SPINEL_PROP_SRP_SERVER_ENABLED` and `SPINEL_PROP_SRP_SERVER_AUTO_ENABLE_MODE`.
In GetProperty handlers only the body should be written. It doesn't need to and shouldn't call `BeginFrame` and `EndFrame`. If using `BeginFrame` here, it will get an error of INVALID_STATE.
> [ncp] fix get property handler of SRP SERVER

- src/core/net/ip6.cpp
- src/core/net/udp6.cpp
- src/core/net/udp6.hpp
This commit removes the `ShouldUsePlatformUdp()` call in `Ip6::PassToHost()` and `Udp::HandleMessage()`.
`ShouldUsePlatformUdp(port)` checks whether the port is NOT one of the port numbers used by the OT stack, such as the MLE port, TMF port, border agent port, or joiner port. This check is already covered by `Udp::IsPortInUse()`, which checks if there is a UDP socket bound to the given port.
Applying such a filter in `Udp::HandleMessage()` seems to have been added by mistake, as it blocks the use of UDP receivers, which should be able to receive and process on any port, not just the ports where we have a socket bound.
> [udp] remove extra `ShouldUsePlatformUdp()` checks

- src/core/api/udp_api.cpp
- src/core/coap/coap.cpp
- src/core/meshcop/joiner_router.cpp
- src/core/meshcop/secure_transport.cpp
- src/core/net/dhcp6_client.cpp
- src/core/net/dhcp6_server.cpp
- src/core/net/dns_client.cpp
- src/core/net/dnssd_server.cpp
- src/core/net/sntp_client.cpp
- src/core/net/srp_client.cpp
- src/core/net/srp_server.cpp
- src/core/net/udp6.cpp
- src/core/net/udp6.hpp
- src/core/thread/mle.cpp
- tests/unit/test_srp_server.cpp
This commit updates how the `NetifId` is set on a `Udp::Socket`. It is now specified as a parameter in the `Open()` call instead of `Bind()`.
This change makes the socket more flexible by allowing the `NetifId` to be known earlier (which can be used for future optimizations). It also allows the desired `NetifId` to be set even when `Bind()` is not explicitly called, such as when `Connect()` or `SendTo()` are used on a socket that is not yet bound. Previously, `kNetifThread` was assumed by default in these situations.
The public `otUdp` APIs are left unchanged to ensure backward compatibility.
> [udp] update `Socket::Open()` to include `NetifId`

- src/core/common/time.hpp
- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/mac/wakeup_tx_scheduler.cpp
- src/core/thread/csl_tx_scheduler.cpp
This commit adds `Mac::CalculateRadioBusTransferTime()`, which calculates the radio bus transfer time (in microseconds) for a given frame size based on `Radio::GetBusSpeed()` & `Radio::GetBusLatency()`. This helper method is used in the `CslTxScheduler` and `WakeupTxScheduler` classes to update frame request-ahead time.
> [mac] add `CalculateRadioBusTransferTime()` helper method

- tests/unit/test_spinel_prop_codec.cpp
This commit updates how address lists are compared in the unit test `spinel_prop_codec`, ensuring that the correct size based on the array length is passed to `memcmp()`.
> [test] fix address list comparison in `spinel_prop_codec`

- src/cli/cli_tcp.cpp
Avoid SSL context operations in TCP callbacks (for eg. `HandleTcpDisconnected`) when the context could have already been de-allocated after de-initialization.
In local testing, we found out after issuing `"deinit"`, which [frees the existing SSL context](https://github.com/openthread/openthread/blob/main/src/cli/cli_tcp.cpp#L300), we could hit a `HandleTcpDisconnected` callback late that [tries to perform operations on the SSL context](https://github.com/openthread/openthread/blob/main/src/cli/cli_tcp.cpp#L1022) and hits a fault.
> [cli] set `mUseTls` to false after de-initializing TCP session

- include/openthread/instance.h
- include/openthread/udp.h
- src/cli/cli_udp.cpp
- src/core/api/udp_api.cpp
- src/core/meshcop/joiner_router.cpp
- src/core/net/dhcp6_client.cpp
- src/core/net/dhcp6_server.cpp
- src/core/net/dnssd_server.cpp
- src/core/net/srp_client.cpp
- src/core/net/srp_server.cpp
- src/core/net/udp6.cpp
- src/core/net/udp6.hpp
- src/core/thread/mle.cpp
- src/core/thread/tmf.cpp
- src/posix/platform/udp.cpp
- tests/unit/test_srp_server.cpp
This commit introduces `kNetifThreadInternal` as a network interface option for UDP sockets. Unlike other options, this disallows the use of platform UDP for the socket, indicating that the socket should use the OpenThread internal Thread network interface only.
This model replaces the previous approach where `ShouldUsePlatformUdp()` would check the socket port against a set of port numbers used by different modules (such as MLE, TMF, Joiner Router, etc) to determine whether platform UDP APIs should be used. With the new model, each module decides whether to associate its socket with the 
`kNetifThreadInternal`.
This is a more flexible and extensible model, ensuring that sockets that should not use the platform do not waste resources (they will not be created or opened/closed on the …
> [udp] add `kNetifThreadInternal` which disallows platform UDP use

- src/core/thread/indirect_sender.cpp
This commit resets (to now) the timestamp of queued messages for a previously sleepy child when the child mode changes to non-sleepy. This ensures that delay-aware queue management is correctly applied to these messages and avoids them being dropped immediately.
---
Resolves https://github.com/openthread/openthread/issues/10971
> [indirect-sender] reset msg timestamp on child mode change to non-sleepy

- src/core/api/ble_secure_api.cpp
- src/core/coap/coap_secure.cpp
- src/core/coap/coap_secure.hpp
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/meshcop/joiner.cpp
- src/core/meshcop/joiner.hpp
- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
- src/core/meshcop/tcat_agent.cpp
- src/core/meshcop/tcat_agent.hpp
- src/core/radio/ble_secure.cpp
- src/core/radio/ble_secure.hpp
- src/core/thread/tmf.cpp
- src/core/thread/tmf.hpp
This commit updates `SecureTransport`. It introduces the `Extension` class within `SecureTransport`, providing support for additional cipher suites and related methods to configure the ciphers (e.g., `SetPreSharedKey()`, `SetCertificate()`).
This class decouples this functionality from the common `SecureTransport` object, allowing it to be added to any class. Classes like `ApplicationCoapSecure` or `BleSecure` can inherit from `Extension` to provide these methods. An `Extension` is then associated with a `SecureTransport` (or any of its subclasses). This approach ensures that only instances requiring extended cipher suite support incur the associated memory cost and avoid repeated code.
This commit also introduces `Dtls`, `DtlsExtended`, and `Tls` as subclasses of `SecureTransport` for …
> [secure-transport] introduce `Extension` class 

- src/cli/cli_ping.cpp
Fix the overflow issue when `mTotalRoundTripTime` is very large.
> [cli] fix the issue of overflow when calculating ping statistics

- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
This commit updates how MbedTLS timers are handled, ensuring that both intermediate and finish times are tracked in their own variables. This decouples the intervals from the underlying `TimerMilli` instance, allowing the same timer to be shared to support multiple sessions later.
> [secure-transport] update mbedtls timer to track finish time

- src/core/net/srp_server.cpp
- tests/scripts/thread-cert/border_router/test_advertising_proxy.py
- tests/unit/test_srp_server.cpp
This commit updates `Srp::Server` to associate its UDP socket with `kNetifThreadInternal`, ensuring that received messages are from the internal Thread network interface (i.e., from devices within the Thread mesh).
> [srp-server] use `kNetifThreadInternal` for UDP socket

- include/openthread/instance.h
- include/openthread/thread.h
- src/cli/README.md
- src/cli/cli.cpp
- src/core/api/thread_api.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
This commit adds a new mechanism to track the time duration since a device was last attached to a Thread mesh. This duration indicates how long the device has been connected, regardless of its role (child, router, or leader).
A related public OT API and CLI command are also added. This information can be used for debugging purposes and internally within the OT core to wait for the device to stabilize before enabling certain behaviors.
> [mle] add mechanism to track current attach duration

- src/cli/cli.cpp
This commit updates the `ba counters` CLI command to use a counter name lookup array. This follows the same approach used in `Cli` for other counters, such as MAC, MLE, IP, and BR counters.
> [cli] update `ba counters` to use counter name lookup array

- src/core/coap/coap_secure.cpp
- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
- src/core/radio/ble_secure.cpp
- tests/nexus/test_dtls.cpp
This commit simplifies and fixes the `Send()` method by sending the entire `aMessage` content and removing the extra `aLength` input parameter. In all calls, the input `aLength` was set to the message's length. The previous implementation of `Send()` did not correctly handle cases where the passed-in length was longer than the available bytes in the given message.
This commit also updates the documentation of `Send()` to clarify the behavior regarding the transfer of ownership of `aMessage`.
Additionally, this commit simplifies `CoapSecure` and `BleSecure` where `Send()` is called.
> [secure-transport] fix Send() method to send entire message

- src/core/thread/mle_router.cpp
If the new router is not in peer's route TLV, the link request would be ignored, causing the link establishment stuck at the Link Request stage until timeout when a new attempt could proceed. This commit adds a check on the initiator to make sure the peer router's Route TLV contains the initiator's router id before sending the link request, otherwise it refrains from initiating the link establishment.
> [mle] do not request link when not recognized

- src/core/mac/sub_mac.cpp
- tests/gtest/radio_spinel_rcp_test.cpp
This commit allows skip CSMA backoff but keep CCA enabled by respect the Max Backoffs parameter in TxInfo.
> [mac] skip backoff when MaxBackoffs is 0

- tests/scripts/thread-cert/node.py
- tests/scripts/thread-cert/test_diag.py
This commit expects echo of diag commands to make sure the command is received by the node when waiting for the expected output. This helps make this test less flaky.
> [test] make test_diag less flaky

- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
This commit adds a local member variable `mIsServer` to the `SecureTransport` class to track whether it is configured to act as a server or client.
> [secure-transport] track server/client role in `mIsServer`

- src/core/diags/README.md
- src/core/diags/factory_diags.cpp
- src/core/diags/factory_diags.hpp
- src/lib/spinel/radio_spinel.cpp
When running the command `diag frame -s fd874f68f1ca00efbe00adde5d4f4913e953845a154d4cbab10000000001820e390005009bb8ea011c58a065c39fbd` and `diag send 20` to send the specified diag frame, we found that the frame is modified by the RadioSpinel module. Which causes the diag sent frames are not the same.
This commit checks whether the frame header has been updated before sending, the RadioSpinel module won't update the frame header if the frame header has been updated before sending. This commit also adds an option `-u` to the `diag frame` command to specify the `mInfo.mTxInfo.mIsHeaderUpdated` field of the diag sent frame.
> [spinel] do not update the sent frame if the frame has been updated before sending

- .github/workflows/build.yml
There is a standalone CMake version check, no need to use this version in gcc specific build tests. This change should accelerate gcc build check, as it takes 8.5 minutes to build cmake.
> [test] skip installing cmake 3.10.3

- examples/platforms/utils/mac_frame.cpp
- examples/platforms/utils/mac_frame.h
If the radio driver supports the radio capability `OT_RADIO_CAPS_TRANSMIT_SEC`, the radio driver should process the security of the send frame if the security is enabled and the frame security is not processed. The wakeup frame uses the KeyIdMode2, but the current method `otMacFrameProcessTransmitSecurity()` only process the frame with the KeyIdMode1. Which causes sent wakeup frame is not encrypted.
This commit enables the method `otMacFrameProcessTransmitSecurity()` to process the security of the wakeup frame.
> [mac-frame] process security of the wakeup frame

- src/core/diags/README.md
- src/core/diags/factory_diags.cpp
Commit adds new command to factory diag called `radio`.
- `enable` for enabling the interface to dfault mode,
- `disable` for disabling the interface
> [diag] add new command to factory diags

- src/core/diags/factory_diags.cpp
This PR fixes an issue related to https://github.com/openthread/openthread/pull/9554. In PR https://github.com/openthread/openthread/pull/9554, a new radio capability is introduced: RX_ON_WHEN_IDLE.
In this PR, we set `rx_on_when_idle` to be true when calling `diag start`, and false when calling `diag stop` for devices which support `rx_on_when_idle`. 
This fix ensures that packets can still be received if `diag` is used after `ifconfig down`.
> [diag] set rx_on_when_idle mode when diag start/stop

- examples/platforms/utils/mac_frame.cpp
The wakeup frame is sent from the wakeup coordinator rather than the wakeup end device. Current code processes the key id mode 2 only when the device is the wakeup end device. This commit corrects this issue.
> [mac-frame] process key id mode 2 only when WC is enabled

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
This commit adds a mechanism to remove any scheduled (delayed) Link Request transmissions to a neighboring router when a link is established with it.
----
Background:
- We set the state to `kStateLinkRequest` when scheduling a Link Request transmission to a neighboring router (from which we receive an Advertisement).
- Currently, this state change blocks replies to "link requests" from the neighbor itself, which can create a deadlock situation (resolved after time out and next advertisment tx).
- https://github.com/openthread/openthread/pull/11030 addresses this by relaxing the state check.
- This change prepares for this update to ensure that the scheduled "Link Request" transmission is canceled if the link is already established, avoiding extra message exchanges between the routers.
> [mle] remove scheduled Link Request to a router if a link is established

- src/core/thread/mle_router.cpp
The current MLE Link Request handler would result in dead lock if two routers sends Link Request to each other at very close time points, when either node tracks the other node in LinkRequest state, so rejects the request until timeout.
This commit changes the handler so that a node will accept the Link Request even if the peer is in LinkRequest state.
> [mle] avoid link dead lock

- src/cli/cli.cpp
- src/core/diags/README.md
- src/core/diags/factory_diags.cpp
- src/core/diags/factory_diags.hpp
The `diag frame` command can set the frame to be sent. But developers has no command to check if the received frame is the same as the sent frame. This commit adds the command `diag receive [async] <number> [lpr]` to show the detailed info of specified number of received frames.
> [diag] add diag receive command to show received specified number of frames

- src/core/diags/README.md
- src/core/diags/factory_diags.cpp
- tests/scripts/expect/cli-diags.exp
- tests/scripts/expect/posix-diag-rcp.exp
- tests/scripts/expect/posix-power-calibration.exp
- tests/scripts/thread-cert/test_diag.py
All diagnostic commands (instead of `diag start`) should fail if device is not in diagnostic mode. Previously it was verified by each command's process method (with a missing check in `ProcessEcho` and `ProcessGpio`). This commit moves the check directly to `ProcessCmd` and cleans up redundant code.
> [diag] move `otPlatDiagModeGet()` check to `ProcessCmd`

- src/core/api/coap_secure_api.cpp
- src/core/coap/coap_secure.cpp
- src/core/coap/coap_secure.hpp
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/joiner.cpp
- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
- src/core/radio/ble_secure.cpp
- tests/nexus/test_dtls.cpp
This commit updates and simplifies how `Connect` and `Receive` callbacks are set on `SecureTransport` and `CoapSecure`. Instead of using the `Open()` method to set these, they are now directly set using the corresponding `SecureSession` methods. This commit also harmonizes the method name for setting the "connect" callback, ensuring the same name is used by different classes.
----
~This PR currently contains the commit from https://github.com/openthread/openthread/pull/11044 and https://github.com/openthread/openthread/pull/11046. Please check and review the last commit. Thanks.~
> [secure-transport] simplify how `Connect/Receive` callbacks are set

- src/core/common/linked_list.hpp
- src/core/net/netif.cpp
- src/core/net/tcp6.cpp
- src/core/thread/address_resolver.cpp
- tests/unit/test_linked_list.cpp
This commit contains the following changes to `LinkedList`:
- Removes the `FindMatching()` version that searches within a given sub-section of the list, as this method is no longer needed.
- Renames the method that finds a matching entry and also returns the `prev` entry in the list to `FindMatchingWithPrev()`. This distinguishes it from other `FindMatching()` overloads and clarifies its purpose. This method is often used when the caller wants to find the matching entry and later remove it from the list.
> [linked-list] remove unused method & rename FindMatchingWithPrev()

- examples/apps/cli/main.c
- examples/platforms/simulation/trel.c
- include/openthread/instance.h
- include/openthread/platform/trel.h
- src/core/mac/mac.cpp
- src/core/radio/trel_interface.cpp
- src/core/radio/trel_interface.hpp
- src/core/radio/trel_link.cpp
- src/core/radio/trel_link.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/posix/platform/trel.cpp
- tests/gtest/fake_platform.cpp
- tests/toranj/cli/cli.py
- tests/toranj/cli/test-706-multi-radio-trel-peer-addr-port-change-discovery.py
- tests/toranj/start.sh
- tests/unit/test_platform.cpp
This commit introduces a new mechanism for the TREL link to detect and handle discrepancies between the IPv6 address and port used by a TREL peer in a received TREL packet, and the information previously reported by the platform layer (through DNS-SD discovery) for the same peer.
Ideally, the platform underlying DNS-SD should detect changes to advertised ports and addresses by peers. However, there are situations where this is not detected reliably.
As a received frame over the TREL radio link is processed by the MAC or MLE layers, if the frame passes receive security checks at either layer (indicating it is a secure and authenticated/fresh frame from a valid neighbor), the TREL peer socket address is automatically updated from the received TREL packet info. This ensures the TREL peer …
> [trel] detect and handle socket addr discrepancy for TREL peers

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
This commit rearranges the method definitions in the `BorderAgent` class so that related methods are next to each other. This improves code readability and organization. This commit contains no logic changes.
----
The new code organization:
- `BorderAgent` constructor
- `Start`/`Stop` and event/timer handlers (state management)
- TMF command handler from the commissioner (forward to leader)
- `ForwardToLeader()` and its related callbacks (`UdpReceiver`)
- `ForwardToCommissioner()`
- `Send` related helper methods (send message or error)
- TMF handler (commissioner candidate) and dataset getter
- Ephemeral key-related methods
- `ForwardContext` nested type
> [border-agent] rearrange method definitions

- src/core/diags/README.md
- src/core/diags/factory_diags.cpp
- src/core/diags/factory_diags.hpp
- src/core/mac/mac_types.cpp
- src/core/mac/mac_types.hpp
The current diag module will count any packets received. This commit adds the command 'diag radio receive filter` to allow the diag module receives only frames with the specified destination mac address.
> [diag] add `diag radio receive filter` command support

- src/core/meshcop/commissioner.cpp
- src/core/meshcop/joiner.cpp
- src/core/meshcop/joiner.hpp
- src/core/meshcop/meshcop.cpp
- src/core/meshcop/meshcop.hpp
This commit adds `LogCertMessage()` to generate a message dump log for certification test. This function is used by both `Joiner` and `Commissioner`, removing duplicate code.
> [meshcop] add `LogCertMessage()`

- src/core/common/linked_list.hpp
- src/core/common/owning_list.hpp
- src/core/net/mdns.cpp
- src/core/net/nat64_translator.cpp
- src/core/net/srp_advertising_proxy.cpp
- src/core/net/srp_client.cpp
- src/core/utils/link_metrics_manager.cpp
- tests/unit/test_linked_list.cpp
This commit updates `LinkedList` and `OwningList` to enhance `FindMatching()`, `RemoveMatching()`, and related methods to use `Matches()` with a variable number of arguments. The implementation uses a variadic template function and forwarding references.
> [linked-list] allow use of `Matches()` with variable number of arguments

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
This commit removes the unused `GetUdpProxyPort()` method and the related code tracking the proxy port in `BorderAgent`.
> [border-agent] remove unused `GetUdpProxyPort()` method

- src/core/meshcop/dataset.cpp
This commit updates the `Dataset::IsTlvValid()` method to also validate the Active/Pending Timestamp and Delay Timer TLVs, ensuring they have the minimum required length. This ensures that a dataset with invalid TLVs is correctly rejected when set on a device.
> [dataset] validate Active/Pending Timestamp and Delay Timer TLVs

- src/core/meshcop/secure_transport.cpp
This commit improves the organization of `secure_transport.cpp` by grouping method definitions for `SecureSession` and `SecureTransport` into separate sections.
The recent PR #11046 introduced `SecureSession`, separating the session and transport functionality. To keep the `git diff` smaller and easier to review, the methods were left in the same order as previously defined. This resulted in methods of `SecureSession` and `SecureTransport` being mixed and interleaved. This PR rearranges the methods and defines separate sections for each class. This commit does not contain any code logic changes.
---
~This PR currently contains the commit from #11056. Please check and review the last commit. Thanks.~
> [secure-transport] reorder method definitions in cpp file

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- src/core/thread/tmf.cpp
- src/core/thread/tmf.hpp
This commit updates `BorderAgent` to utilize its own DTLS `Transport` and CoAP `SecureSession`, separating it from the shared `Tmf::SecureAgent` used by `Commissioner` and `Joiner` modules. This change enables future support for multiple sessions within `BorderAgent`.
---
~This PR currently contains the commit from https://github.com/openthread/openthread/pull/11056. Please check and review the last commit. Thanks.~
> [border-agent] use separate DTLS transport and CoAP secure session

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- src/core/meshcop/commissioner.cpp
This commit updates the interaction between `BorderAgent` and the native `Commissioner`, removing the unnecessary mechanism to stop and restart the Border Agent when the commissioner is enabled and disabled.
This was previously required because both modules shared the same underlying `Tmf::SecureAgent` and DTLS transport. This has been changed recently so that `BorderAgent` uses its own DTLS transport and sessions.
> [border-agent] update interactions with native `Commissioner`

- include/openthread/instance.h
- include/openthread/platform/radio.h
This commit clarifies the expected behavior with CSMA/CA parameters in TxInfo.
* non-zero mTxDelay or non-zero mTxDelayBaseTime or falsy mCsmaCaEnabled disables CSMA backoffs, thus ignores the mMaxCsmaBackoffs field.
* Zero mMaxCsmaBackoffs disables CSMA backoffs.
* CCA is solely controlled by mCsmaCaEnabled.
> [api] clarify CSMA/CA behavior in TxInfo

- src/core/api/thread_ftd_api.cpp
- src/core/thread/mle_router.cpp
The MleRouter::BecomeRouter already checks the device role and the API claims only return OT_ERROR_INVALID_STATE when the role is disabled.
This commit consolidates the device role check in
MleRouter::BecomeRouter.
> [mle] remove redundant checks in otThreadBecomeRouter

- src/core/diags/README.md
- src/core/diags/factory_diags.cpp
- src/core/diags/factory_diags.hpp
- tests/scripts/expect/cli-diags.exp
- tests/scripts/thread-cert/test_diag.py
- tools/cp-caps/rcp_caps_test.py
- tools/otci/otci/otci.py
When using the `diag frame -c xxxx` command to enable the CSMA-CA for transmitting the frame, the command `diag send` won't output any message when the CCA failure happens. It is difficult for users to know whether the CSMA-CA is actually effective via diag commands.
This commit counts the number of packets that are sent succeed and failed, and do not re-transmit the frame after it fails to send.
> [diag] count the number of packets that are sent succeed and failed

- src/core/thread/mle.cpp
This commit fixes the warning:
```
openthread/src/core/thread/mle.cpp: In member function 'ot::Error ot::Mle::Mle::TxMessage::AppendDatasetTlv(ot::MeshCoP::Dataset::Type)':
src/core/thread/mle.cpp:5312:27: error: 'tlvType' may be used uninitialized in this function [-Werror=maybe-uninitialized]
5312 |     error = Tlv::AppendTlv(*this, tlvType, dataset.GetBytes(), dataset.GetLength());
|             ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> [mle] fix warning of maybe-uninitialized tlvType

- src/core/thread/thread_netif.cpp
This commit updates the code so that `Tmf::SecureAgent` is not closed when the Thread network interface is brought down. The `SecureAgent` is directly controlled and used by either the `BorderAgent` or `Commissioner` during network operation, which may continue to function even if the Thread network interface is offline. It may also be used by the `Joiner`, but in that case, it will be closed by the `Joiner` itself upon finishing the join attempt.
----
~This PR currently contains the commit from #11056. Please check and review the last commit. Thanks.~
> [thread-netif] do not close `Tmf::SecureAgent` on `Down()`

- tools/ot-fct/CMakeLists.txt
- tools/ot-fct/cli.cpp
When configuration file defined in build parameter(command line argument), ot-fct is wouldn't take into an account and accessed default path.
This commit fixes to access configuration file from path which is defined from build command line parameter. Also, it fixes some compilation issues while building from ot-br-posix.
> [ot-fct] fix access file from path defined in build parameter

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
This commit adds a new variable, `mDidConnectWithEphemeralKey`, which tracks whether a successful secure session is established using the ephemeral key. This variable is used in `HandleConnected()` to determine whether to stop using the ephemeral key when the Border Agent is notified that the secure session is disconnected.
This change ensures that ephemeral key use is not stopped after a failed connection attempt, while still guaranteeing that an ephemeral key can only be used once.
Without this fix, a failed connection attempt would immediately stop the use of the ephemeral key. With this change, the intended `kMaxEphemeralKeyConnectionAttempts` will be applied.
> [border-agent] track successful connection with ephemeral key

- tests/nexus/CMakeLists.txt
- tests/nexus/platform/nexus_core.cpp
- tests/nexus/platform/nexus_core.hpp
- tests/nexus/test_border_agent.cpp
This commit adds `test_border_agent`, using the Nexus framework, to cover the functionality of `BorderAgent`. The test cases include:
- Border Agent initial state.
- Establishing a secure session to the Border Agent an   disconnecting.
- Handling "Commissioner Petition" to accept a full commissioner.
- Handling "Commissioner Keep Alive" and timeouts.
- Ephemeral key use and its initial state.
- Establishing a connection with an ephemeral key and disconnecting.
- Ephemeral key timeout mechanism (with or without a session).
- Ephemeral key use stopping after the maximum number of failed connection attempts.
----
~This PR contains the commit from https://github.com/openthread/openthread/pull/11109. Please check and review the last commit. Thanks.~
> [test] add `test_border_agent` to nexus test cases

- script/check-size
This simplifies doing local check by enhancing the script to accept extra cmake options and specifying the commit to compare.
Example usage:
```bash
OT_SHA_OLD=e4a390f34 ./script/check-size nrf52840 -DOT_FULL_LOGS=ON
```
> [script] enhance check-size for local use

- src/core/crypto/storage.cpp
- src/core/crypto/storage.hpp
- src/core/instance/instance.cpp
- src/core/instance/instance.hpp
- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
- src/core/net/srp_client.cpp
- src/core/net/srp_client.hpp
- src/core/thread/key_manager.cpp
This commit introduces `Crypto::Storage::KeyRefManager`, which manages and selects the `KeyRef` values. `ot::Instance` now will have its own `KeyRefManager`. Under `MULTIPLE_INSTANCE_ENABLE`, this allows different `ot::Instance`s to use different `KeyRef` ranges by setting an instance-specific offset. This offset is used when determining the `KeyRef` numerical value for secure storage access.
> [crypto-storage] add `KeyRefManager` to select `KeyRef` values

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager.hpp
- src/core/meshcop/joiner.cpp
- src/core/meshcop/joiner.hpp
- src/core/meshcop/joiner_router.cpp
- src/core/meshcop/joiner_router.hpp
- src/core/thread/anycast_locator.cpp
- src/core/thread/anycast_locator.hpp
- src/core/thread/dua_manager.cpp
- src/core/thread/dua_manager.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
- src/core/thread/mlr_manager.cpp
- src/core/thread/mlr_manager.hpp
- src/core/thread/network_data_notifier.cpp
- src/core/thread/network_data_notifier.hpp
- src/core/thread/network_diagnostic.cpp
- src/core/thread/network_diagnostic.hpp
- src/core/utils/channel_manager.cpp
- src/core/utils/channel_manager.hpp
- src/core/utils/mesh_diag.cpp
- src/core/utils/mesh_diag.hpp
This commit changes CoAP handlers to use otError in the function or method definitions. This ensures the definitions are consistent with the declaration in coap.h.
> [coap] use otError in C handlers

- .gitignore
Ignore unit test binaries. For example, 'tests/nexus/nexus_border_agent'.
> [gitignore] ignore nexus unit test binaries

- tools/tcat_ble_client/cli/cli.py
- tools/tcat_ble_client/cli/tlv_commands.py
This commit adds 'tlv' command tree to the BBTC CLI. The 'tlv' command has two subcommands: 'list' and 'send'. The 'tlv list' prints available TLVs types that can be used in the 'send' subcommand. The 'tlv send <TLV_TYPE> <TLV_PAYLOAD>' allows sending specific TLV with arbitrary payloads.
Example:
`tlv send a 1234`
Send ping TLV(0x0a) with payload '1234'
The 'tlv' command tree is to gain the ability to send the TLV with any payload at any time. This feature allows to check the behavior of TCAT device against:
- receiving of unexpected TLV
- receiving of TLV with corrupted payload
- receiving of TLVs sent in custom order
> [tcat] add tlv command tree

- src/core/coap/coap.cpp
- src/core/coap/coap.hpp
- src/core/coap/coap_secure.cpp
- src/core/coap/coap_secure.hpp
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
- src/core/thread/tmf.cpp
- src/core/thread/tmf.hpp
- tests/nexus/test_dtls.cpp
This commit updates `SecureTransport` to support multiple `SecureSession`s on the same transport. The transport tracks a list of sessions that it owns and manages. Two new callbacks are introduced:
- `AcceptCallback`: Used to accept a new connection request, providing
the `SecureSession` instance to use (passing ownership of the
session to the transport).
- `RemoveSessionCallback`: Signals that a session is removed,
releasing ownership of the session.
`BorderAgent`, `Tmf::SecureAgent`, and `ApplicationCoapSecure` are updated to adopt the new model.
This commit also updates the Nexus `test_dtls`, adding `TestDtlsMultiSession` to validate multiple session support behavior.
----
~This PR currently contains the commit from https://github.com/openthread/openthread/pull/11101. Please check and …
> [secure-transport] support multiple sessions on the same transport

- src/cli/cli.cpp
- src/cli/cli.hpp
This commit simplifies the `Cli::ProcessLine()` implementation and adds comments to improve readability and clarity.
> [cli] simplify `ProcessLine()` implementation

- src/core/net/nat64_translator.cpp
This commit fixes the release of expired mappings by ensuring that `ReleaseExpiredMappings()` is always called from the timer callback `HandleMappingExpirerTimer()`, regardless of the logging level. Previously, `ReleaseExpiredMappings()` was called as an input to `LogInfo()`, which could become an empty macro (ignoring its input) if info-level logs were disabled.
----
Thanks and credit to @marius-preda for finding and fixing this issue. This fix was originally included in #11043. We add this fix as its own smaller PR due to its importance and to allow easier cherry-picking (please see https://github.com/openthread/openthread/pull/11043#discussion_r1907869326)).
> [nat64-translator] ensure expired mappings are released in timer callback

- src/core/config/mle.h
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
This commit introduces a "gradual router link establishment" mechanism for FTD children. An FTD child device communicates through its parent but can establish links with other neighboring routers to receive multicast messages (forwarded MPL) from them, improving multicast reliability.
An FTD child tries to establish links with the first `ChildRouterLinks` routers quickly (sending an MLE Link Request to initiate the link upon receiving advertisements from a neighboring router). The `ChildRouterLinks` is configurable through an OT configuration option (specifying the default value) and at run-time using the `otThreadSetChildRouterLinks()` API.
After the first `ChildRouterLinks`, the "gradual router link establishment" mechanism allows `kExtraChildRouterLinks` additional router links to be …
> [mle] introduce "gradual router link establishment" on FTD children

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
- src/core/thread/router_table.cpp
This commit adds a mechanism to expedite recovery from temporary router link quality mismatches. If a received `RouteTlv` (from a received Advertisement) indicates that the neighboring router claims no link to us by setting its `GetLinkQualityOut()` towards us as `0`, and our two-way link quality to this router is at least Link Quality 2, we schedule a unicast MLE Advertisement to be sent to this neighbor. This advertisement is sent after a randomly selected delay within a one-second window using `Mle::DelayedSender`.
This helps with link recovery on the neighboring router, which otherwise may take longer due to reliance on the next trickle timer-triggered Advertisement transmission, which can be up to 32 seconds later and, being multicast, may be missed.
---
Related to …
> [mle] expedite recovery from temporary router link quality mismatch

- tools/cp-caps/README.md
- tools/cp-caps/rcp_caps_test.py
- tools/otci/otci/command_handlers.py
- tools/otci/otci/otci.py
This commit adds an option for users to set the adb key when connecting devices via the adb interface.
> [otci] add adb key support for adb interface

- src/cli/cli.cpp
When running the sync command, such as `diag radio receive 10000`, the cli doesn't allow running other commands before the sync command returns. Which causes that the sync command may be blocked for a very long time and users can't do anything to terminate the sync command. This will also cause the test script to fail to run the second case after running the first case fails.
This commit allows the cli to execute the `factoryreset` command when running the sync command.
> [cli] allow executing the `factoryreset` command when running sync commands

- src/core/net/ip4_types.cpp
- src/core/net/ip4_types.hpp
- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
- src/core/net/tcp6.hpp
This commit adds a new class, Ip4::Headers that offers support for
managing an IPv4 header along with UDP/TCP/ICMP4 headers from a received
message/frame. This functionality is equivalent to the one already
present for IPv6.
Added GetId() and SetId() methods to ICMP4 class.
Improved the Ip6::Headers functionality:
- added SetSourcePort() method to allow easier translation of ports in NAT64.
- added GetIpLength() and GetIpHopLimit() methods.
Added SetSourcePort() and SetDestinationPort() methods for TCP.
> [ip-utils] extend and improve ip4/ip6 headers

- src/lib/spinel/radio_spinel.cpp
- src/lib/spinel/radio_spinel.hpp
- src/posix/platform/CMakeLists.txt
- src/posix/platform/openthread-posix-config.h
- src/posix/platform/radio.cpp
- src/posix/platform/radio.hpp
- src/posix/platform/tmp_storage.cpp
- src/posix/platform/tmp_storage.hpp
The `otRadioSpinelMetrics` includes metrics that record the count of the RCP timeout and the count of RCP reboot and so on. After these events happen, the Thread stack will exit and the system will re-start the Thread stack again. In this case, metrics of the `otRadioSpinelMetrics` will be cleared, and metrics values are always 0.
This commit adds a temporary storage to store the radio spinel metrics. The temporary storage will clear all values that are stored in the temporary storage after the system reboots.
> [spinel] save the radio spinel metrics to temporary storage

- src/core/mac/mac.cpp
- src/core/thread/link_quality.cpp
- src/core/thread/link_quality.hpp
- src/core/thread/neighbor.hpp
- src/core/thread/router.hpp
- tests/unit/test_link_quality.cpp
This commit updates `LinkQualityInfo` to track the "link quality out", which is the link quality from the neighbor's perspective. This value is currently tracked by the `Router` class. The existing methods in `LinkQualityInfo` that return the "link quality in" are renamed to use `LinkQualityIn` to clarify and distinguish them.
This change uses existing bits in `LinkQualityInfo`, freeing up bit fields in the `Router` class to be used for other information.
> [link-quality] track "link quality out" in `LinkQualityInfo`

- src/cli/cli_br.hpp
- src/core/net/tcp6.hpp
- src/core/thread/mle.cpp
- src/core/utils/parse_cmdline.cpp
- src/ncp/ncp_base.hpp
- tests/unit/test_message.cpp
- tests/unit/test_pool.cpp
This commit updates a few remaining places where anonymous enums were used to declare constants, replacing them with `static constexpr`.
> [style] use `constexpr` instead of anonymous `enum` for constants

- src/core/meshcop/border_agent.cpp
This commit removes unnecessary Border Agent state checks in `CoapDtlsSession` methods. When the Border Agent is stopped, the DTLS transport is closed, and all associated sessions are cleared and removed.
> [border-agent] remove unnecessary state checks in `CoapDtlsSession` methods

- tools/cp-caps/README.md
- tools/cp-caps/rcp_caps_test.py
The original code counts the number of received frames to check whether the specified frame format is supported. It doesn't check whether the sent and the received frames are the same. The test results may have some deviation.
This commit compares the sent and received frame to check whether the specified frame format is supported. This commit also add a case to test the wake-up frame format.
> [cp-caps] compare sent and received frames to check whether specified frame format is supported

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_types.hpp
- src/core/thread/router.hpp
This commit updates `Router` to track the number of remaining Link Request attempts during link re-establishment (when no Advertisement is received from a router, and the router is aged out). This helps simplify the code managing link re-establishment.
---
~This PR currently contains the commit from https://github.com/openthread/openthread/pull/11155 (which freed the bit-fields that are now used for `mLinkRequestAttempts`). Please check and review the last commit. Thanks.~
> [mle] track remaining Link Request attempts when re-establishing links

- src/core/net/tcp6.cpp
- third_party/tcplp/bsdtcp/tcp.h
- third_party/tcplp/bsdtcp/tcp_fsm.h
- third_party/tcplp/bsdtcp/tcp_input.c
- third_party/tcplp/bsdtcp/tcp_output.c
- third_party/tcplp/bsdtcp/tcp_reass.c
- third_party/tcplp/bsdtcp/tcp_sack.c
- third_party/tcplp/bsdtcp/tcp_subr.c
- third_party/tcplp/bsdtcp/tcp_timer.c
- third_party/tcplp/bsdtcp/tcp_timewait.c
- third_party/tcplp/bsdtcp/tcp_usrreq.c
- third_party/tcplp/bsdtcp/tcp_var.h
This commit redefines tcplp symbols that conflict with LWIP's TCP implementation:
- tcp_input has been renamed tcplp_input
- tcp_output has be renamed tcplp_output
- tcp_close has been renamed tcp_close_tcb
- tcp_init was already removed but the prototype was still present and was deleted
- TCP_MSS and TCP6_MSS have been renamed to TCP_MAXSS and TCP6_MAXS
This PR fixes issue #10926
> [tcp] redefine conflicting symbols

- include/openthread/instance.h
- include/openthread/nat64.h
- src/cli/cli.cpp
- src/core/config/nat64.h
- src/core/net/nat64_translator.cpp
- src/core/net/nat64_translator.hpp
This commit adds support for port translation in NAT64. Currently the translator only supports a direct mapping between an IPv4 and an IPv6 address requiring a large IPv4 pool to work effectively. This implies the need for an additional NAT 4 to 4 translator as the border router will only have one private IPv4 in the LAN.
This commit enhances the current functionality according to NAT64 RFC and dynamic PAT mechanism. This is used by any home router to share a public IPv4 address with a range of devices using private addresses. The port translation ensures the source port or the ICMP identifier is always unique in the mapping table allowing a reply packet to be matched with the request using the destination port and address. This functionality can be disabled at compile time.
> [nat64] add support for port translation

- src/core/diags/factory_diags.cpp
- src/core/diags/factory_diags.hpp
When "diag radio sleep" is followed by "diag send" or "diag repeat", the radio switches to and stays in the receive mode after a transmission. Normally, the MAC layer is responsible for putting the radio back to sleep but the MAC layer is  bypassed when using the diag commands.
Make sure that the radio goes back to sleep after a transmission when the sleep mode is on. This helps command like "diag repeat" work more reliably as the transmission is less likely to be interferred with the accidental frame reception.
> [diag] go back to sleep after transmission

- tools/cp-caps/README.md
- tools/cp-caps/rcp_caps_test.py
This commit adds test cases for testing the `mTxInfo` field of the radio frame.
> [cp-caps] test the mTxInfo of the radio frame

- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
This commit updates neighbor aging and recovery on FTD children. An FTD child establishes links with neighboring routers to receive multicast MPL (re)transmissions.
If the device is an FTD child and has more than `mChildRouterLinks` neighbors, it uses a longer neighbor age (`kMaxNeighborAgeOnChild = 150s`) and removes the neighboring router upon expiration without attempting to re-establish the link.
This differs from the existing behavior (which is still used when the device is a router or an FTD child with `mChildRouterLinks` or fewer neighbors), where a 100-second age is used, and the device attempts to re-establish links upon expiration by sending Link Requests.
Link Requests from FTD children are suppressed when a neighboring router becomes unavailable, and the child already has more …
> [mle] enhance neighbor aging & suppress Link Requests on FTD children

- src/core/common/random.cpp
- src/core/common/random.hpp
- src/core/crypto/aes_ccm.cpp
- src/core/crypto/aes_ccm.hpp
- src/core/crypto/crypto_platform.cpp
- src/core/crypto/mbedtls.cpp
- src/core/crypto/mbedtls.hpp
- src/core/mac/mac_frame.cpp
- src/core/mac/mac_types.cpp
- src/core/mac/mac_types.hpp
- src/core/thread/key_manager.hpp
This commit replaces the `#if !OPENTHREAD_RADIO` checks with explicit `#if OPENTHREAD_FTD || OPENTHREAD_MTD` checks.
The existing check relied on the assumption that exactly one of the three options `FTD`, `MTD`, or `RADIO` will be set, and therefore `#if !RADIO`  was used indirectly as a check for `FTD` or `MTD`. This change improves clarity and allows for future addition of new configurations (where this assumption may no longer hold true).
> [core] replace `#if !OPENTHREAD_RADIO` with explicit FTD or MTD check

- src/cli/README_UDP.md
- src/cli/cli_udp.cpp
This commit updates the default CLI bind interface to be consistent with the description. The default behavior should apply to all Thread nodes, not just devices that define UDP platform layer. For Thread nodes that only use the Open Thread Stack, netif type OT_NETIF_THREAD_HOST has no meaning.
Support for OT_NETIF_THREAD_HOST has been kept using the -h option.
Updated the CLI bind command readme to make it clear when the netif options are valid and what is the default behavior.
> [cli] update default bind interface

- src/core/config/misc.h
MTDs built out of the OpenThread stack fail a 1.4 network diagnostics test that tracks connection time and role time in MLE counter TLVs (test case 4.2). We can workaround manually defining UPTIME for MTDs, but it's better to make it the default behavior.
> [config] define uptime feature for MTDs

- src/core/meshcop/joiner.cpp
The otJoinerStart enables a mechanism for Thread commissioning. The traditional Thread commissioning process uses factory assigned EUI-64 of the device to derive the Joiner ID and identify/filter a joiner (through steering data bloom filter).
But otJoinerStart does not allows users to have a new EUI-64 set at run time.
On joiner side, when a new EUI-64 value is provided, the Joiner code uses this new value to derive the Joiner ID and identify/filter a joiner (through steering data bloom filter).
On commissioner side, users can use this new EUI-64 value.
> [joiner] support a new EUI-64 at run time

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
This commit introduces `TxMessage::AppendAddressRegistrationEntry()` which appends an address entry in an MLE Address Registration TLV. The new helper method determines whether a given address can be appended as a compressed (using a lowpan context ID) or as an uncompressed entry. This simplifies the code by moving all checks into a common method. It also adds an explicit check to ensure the associated Context TLV has the "compress" flag set before using the compressed format.
> [mle] introduce `TxMessage::AppendAddressRegistrationEntry()`

- src/core/diags/factory_diags.cpp
- src/core/diags/factory_diags.hpp
- tests/scripts/expect/cli-diags.exp
The current diag module allows users running the 'diag send' and 'diag repeat' concurrently. The command run later will change the settings of the command run earlier, which will cause unexpected test results.
This commit does not allow running 'diag send' and 'diag repeat' concurrently.
> [diag] do not allow running `diag send` and `diag repeat` concurrently

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
This commit updates the Border Agent so that the `CoapDtlsSession` tracks the forwarded CoAP request and the allocated `ForwardContext` to the leader using `Tmf::Agent` in a list.
If the CoAP session disconnects before the forwarded request finishes, the pending transaction is explicitly aborted in the session's `Cleanup()` method using `Tmf::Agent::AbortTransaction()`. This ensures that the response handler, `HandleCoapResponse()`, is invoked while the session remains valid.
> [border-agent] track `ForwardContext` and abort TMF txn on disconnect

- src/cli/cli_tcp.cpp
- tests/scripts/expect/cli-tcp.exp
This adds the `-x` flag to the `tcp send` command so send specific data defined by a hexadecimal string.
The purpose is to use this in testing, for example to emulate HTTP GET requests.
> [cli] add '-x' flag to tcp client to send hexadecimal data

- tests/scripts/thread-cert/test_srp_register_500_services.py
Previously there's a delay for every router (10 seconds) and child (3 seconds) for it to start. The serialized waiting times are unnecessary. This PR removes such waitings to speed up the test case. This is especially useful in the BR test `test_srp_register_500_services_br.py` which uses non-virtual time.
> [tests] reduce waiting time in the test of registering 500 SRP services

- tests/scripts/thread-cert/node.py
https://github.com/openthread/ot-br-posix/actions/runs/13192276355/job/36827304346?pr=2677
When resolving a hostname, `dns-sd` may output a line saying `No Such Record` with an all-zero address which should be discarded.
```
2025-02-07 03:15:14,335 - INFO - Host<3> $ 'DATE: ---Fri 07 Feb 2025---'
2025-02-07 03:15:14,335 - INFO - Host<3> $ ' 3:15:12.260  ...STARTING...'
2025-02-07 03:15:14,335 - INFO - Host<3> $ 'Timestamp     A/R  Flags         IF  Hostname                               Address                                      TTL'
2025-02-07 03:15:14,335 - INFO - Host<3> $ ' 3:15:12.260  Add  40000003     105  my-host.local.                         0000:0000:0000:0000:0000:0000:0000:0000%<0>  1   No Such Record'
2025-02-07 03:15:14,335 - INFO - Host<3> $ ' 3:15:12.260  Add  40000002 …
```
> [tests] deal with the `No Such Record` lines in the output of `dns-sd` 

- src/core/diags/factory_diags.cpp
- src/core/diags/factory_diags.hpp
The radio driver will set the 'mInfo.mTxInfo.mIsSecurityProcessed' field to True after the radio driver encrypts the frame. Which causes subsequent frames to be sent will not be encrypted.
This commit sets the 'mInfo.mTxInfo.mIsSecurityProcessed' field before sending each frame.
> [diag] set `mIsSecurityProcessed` field before sending frames

- tools/cp-caps/rcp_caps_test.py
- tools/otci/otci/command_handlers.py
When running the command `diag receive 1 rlp`, the DUT may fail to receive the frame, then the otci will try the command again and again. These retries are useless, and they will take lots of time before timeout.
This commit sets the number of retry to 0 before executing the command, and restore the number of retry after the command is executed. This commit also captures the timeout exception from the adb_shell.
> [tests] set the number of retry when executing the command

- examples/platforms/simulation/radio.c
- examples/platforms/utils/mac_frame.cpp
The simulation platform radio driver doesn't set the 'mInfo.mTxInfo.mIeInfo' field of the ACK frame. And the function 'otMacFrameUpdateTimeIe()' directly use the 'mInfo.mTxInfo.mIeInfo' field, this may cause the program crash.
This commit checks whether 'mInfo.mTxInfo.mIeInfo' is null before using it and sets the 'mInfo.mTxInfo.mIeInfo' field of the ACK frame to null in simulation platform.
> [utils] check whether `mInfo.mTxInfo.mIeInfo` is null before using it

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit enhances the `OmrPrefixManager` to track and log changes to the favored OMR prefix. The new log includes the old favored prefix (if any) along with the new one, and provides additional information such as its preference, whether it is a domain prefix, or whether it matches the local OMR prefix. This replaces and enhances the previous logs.
This new mechanism can also be used to signal (to other modules) when the favored OMR prefix changes.
---
Here is example of new log:
```
RoutingManager: Favored OMR prefix: fd2d:2086:d293:1::/64 (prf:low, local) -> 2000:0:1111:4444::/64 (prf:medium)
```
> [routing-manager] track and log favored OMR prefix changes

- tests/scripts/thread-cert/border_router/test_mdns_restart.py
Fixes the flakiness after enable the OpenThread Core Advertising Proxy.
> [tests] extend the waiting time in `test_mdns_restart` for SRP server to start

- src/core/border_router/routing_manager.cpp
This commit updates `PdPrefixManager::Evaluate()` to directly use the helper method `FavoredOmrPrefix::IsInfrastructureDerived()` when deciding to pause and change to `kDhcp6PdStateIdle`. This helps improve code readability.
> [routing-manager] use `IsInfrastructureDerived()` in `PdPrefixManager`

- src/core/api/border_routing_api.cpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit updates `otBorderRoutingDhcp6PdState` to be properly mapped using `DefineMapEnum()` to its related core-internal `enum` definition. This avoids the use of `static_cast` for conversion and ensures only associated `enum` types can be mapped to each other.
> [routing-manager] map `otBorderRoutingDhcp6PdState` to core type

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit renames `PrefixEntry` to `PdPrefix` within the `PdPrefixManager` class. Associated variables are also updated, improving readability.
> [routing-manager] rename `PrefixEntry` to `PdPrefix`

- src/core/border_router/routing_manager.hpp
This commit simplifies `PdPrefixManager::HasPrefix()` by simply checking if `mPrefix` is not empty (rather than `IsValidOmrPrefix()`). A favored PD prefix is always validated before it is assigned to `mPrefix`, and when the prefix is removed, `mPrefix` is cleared.
> [routing-manager] simplify `PdPrefixManager::HasPrefix()`

- src/posix/platform/trel.cpp
---
Related to [SPEC-1342](https://threadgroup.atlassian.net/browse/SPEC-1342)
> [posix] set `IPV6_ADDR_PREFERENCES` on trel socket

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit simplifies the `PdPrefixManager` class by removing the `currentPrefixUpdated` flag. The flag was used to track PD prefix changes during prefix processing, solely to determine if a prefix was deprecated. This deprecation check can be performed independently, eliminating the need for the flag and simplifying the code.
----
~This PR currently contains the commit from https://github.com/openthread/openthread/pull/11241. Please check and review the last commit. Thanks.~
> [routing-manager] remove prefix change tracking in `PdPrefixManager`

- tests/nexus/README.md
Putting all build caches in the default directory makes it less clear when we do 'ls'.
> [doc] instruct to build nexus test in a directory

- include/openthread/instance.h
- include/openthread/platform/radio.h
This commit clarifies the documentation for `otPlatRadioReceiveAt()` regarding its behavior when called multiple times after successfully scheduling a reception window.  If a subsequent call occurs before the start of the previous window, it MUST cancel the previous window and effectively replace it. If the call occurs after the start of the previously scheduled window, even if still within it, it MUST NOT impact the ongoing reception.
----
Resolves https://github.com/openthread/openthread/issues/10784
> [radio] clarify `otPlatRadioReceiveAt()` behavior

- src/core/radio/radio.cpp
- src/core/radio/radio.hpp
This commit addresses an issue introduced in #10892 where the Extended Address byte order was not properly handled when calling `otPlatRadio` APIs. OpenThread core uses big-endian encoding for Extended Addresses, while the `otPlatRadio` APIs expect little-endian, as per documented behavior.
PR #10892 refactored the byte-order reversal code from `SourceMatchController` and `LinkRaw` into the `Radio` class. While `Radio::AddSrcMatchExtEntry()` was updated properly to reverse the byte order, `Radio::ClearSrcMatchExtEntry()` was not. This leads to Extended MAC addresses not being properly removed from the source match table, potentially causing issues with indirect transmission. This commit resolves the issue.
It is strongly recommended to cherry-pick this fix into builds that include #10892.
> [radio] fix `ClearSrcMatchExtEntry()` Extended Address byte order

- tests/scripts/thread-cert/border_router/test_dnssd_server.py
- tests/scripts/thread-cert/border_router/test_dnssd_server_multi_border_routers.py
This commit relaxes the tests that assume mDNS resolve would provide a single IPv6 answer and explicitly check and require one address. This behavior of the mDNS API is improved/changed in the `ot-br-posix` implementation, allowing multiple addresses to be collected and passed in the "resolved" callback.
This commit updates the `_assert_dig_result_matches()` function to  have an additional parameter, 
`allow_extra_answer`, which is then  used in specific test steps.
----
This is related to 
- https://github.com/openthread/ot-br-posix/pull/2712
- https://github.com/openthread/ot-br-posix/issues/2711
> [test] relax BR tests that expect a single address on mDNS resolve

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit simplifies state tracking and updates within `PdPrefixManager`. Previously, three boolean flags (`mEnabled`, `mStarted`, and `mPaused`) and a `GetState()` method were used to represent the state as a `Dhcp6PdState`.
This commit replaces the boolean flags with a single `mState` variable of type `Dhcp6PdState`.  New `UpdateState()` and `SetState()` methods handle all state transitions, ensuring PD prefix withdrawal (OMR prefix removal from Network Data) and state change signaling.
----
Resolves https://github.com/openthread/openthread/issues/10741.
> [routing-manager] simplify state management in `PdPrefixManager`

- include/openthread/border_agent.h
- include/openthread/instance.h
- src/core/api/border_agent_api.cpp
- src/core/border_router/routing_manager.cpp
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- src/core/net/dns_types.hpp
- tests/nexus/test_border_agent.cpp
This PR adds a new OT API to set callback for border agent state change: `otBorderAgentSetMeshCoPServiceChangedCallback `
This PR is part of the effort to refactor BorderAgent MeshCoP Service Publisher: https://github.com/openthread/ot-br-posix/issues/2658
`otBorderAgentStateChangedCallback` is invoked when the 'IsActive' state of BorderAgent changes or the MeshCoP TXT data from Thread stack changes. For example, the network name, the EXT PAN ID. This is used to update the MeshCoP TXT data that will be published on the host and notify the platform to start/stop the UDP Proxy.
After applying the UdpProxy design, the UDP port of published MeshCoP service will be provided by the UdpProxy on the host (in ot-br-posix) instead of OT core.
> [border-agent] add new apis for refactoring meshcop service publishing

- tests/gtest/fake_platform.cpp
- tests/gtest/fake_platform.hpp
- tests/gtest/radio_spinel_rcp_test.cpp
This commit adds tests to cover the handling of Src Match entries, including adding, removing and clearing of short addr entries and extended addr entries.
> [test] cover src match handling

- src/core/meshcop/border_agent.cpp
If the EphemeralKey Manager is enabled, when no active CoAP DTLS session is found in the Border Agent's mDtlsTransport, it should attempt to retrieve one managed by the EphemeralKey Manager.
This issue was discovered when using Thread devices, a Border Router , and `ot-commissioner` for commissioning with an ephemeral key. The process is as follows:
Using `ot-commissioner` commit: `8fffd186b28809257bad73eab2459c97240fe535`
Using `openthread` commit: `36a8f71d0693bfb1407fc48444c4da6e7f2d32d6`
1. Using the ephemeral key, the BR and `ot-commissioner` established a DTLS connection over the Wi-Fi link. This process worked as expected, and the Border Agent successfully created `mCoapDtlsSession` in the EphemeralKey Manager.
2. The `ot-commissioner` executed the command `joiner enableall meshcop …
> [border-agent] try getting coap dtls session from ephemeral key manager

- src/core/common/time.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
This commit updates `SetTimeout()` to ensure the child timeout remains within the minimum and maximum allowed values (per the specification, the maximum value of 8 hours is used).
These limits are also enforced when the parent requests a different timeout value in an MLE Child Update Response to the child's request.
> [mle] clamp child timeout to min/max range

- src/core/BUILD.gn
- src/core/CMakeLists.txt
- src/core/meshcop/border_agent.cpp
- src/core/thread/version.cpp
- tests/nexus/test_border_agent.cpp
This PR adds thread version string for the "tv" entry in border agent MeshCoP TXT records.
The PR also replaces "1.3.1" with "1.4.0".
> [version] add thread version string

- .github/workflows/otbr.yml
- .github/workflows/posix.yml
- .github/workflows/simulation-1.1.yml
- .github/workflows/simulation-1.4.yml
- script/install_socat
This PR changes the installation of socat from using 'apt' to manual installation.
We found the latest socat version 1.8.0.3 has an issue when running with OTBR docker. To avoid the error caused by version and facilitate local development, the PR provides a script to install socat of version 1.7.4.4 and replaces the installation in CI and scripts..
We add the install script in openthread and ot-br-posix will use the script in openthread to install socat.
Fixes: https://github.com/openthread/ot-br-posix/issues/2719
> [test] fix socat version to 1.7.4.4

- tests/gtest/fake_platform.cpp
This commit fix build error when running `./script/cmake-build posix -DOT_BUILD_GTEST=ON`
> [gtest] fix build error when building posix

- src/core/mac/mac.cpp
- src/core/mac/mac_links.hpp
- src/core/mac/sub_mac.cpp
- src/core/mac/sub_mac.hpp
This commit moves the calling `CslSample()` logic from `Mac` to the `SubMac`. It will make it easier for us to move CSL receiver to RCP in the future.
> [csl] set the `SubMac` to handle the `CslSample()` method

- include/openthread/border_agent.h
- include/openthread/instance.h
- src/core/api/border_agent_api.cpp
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- tests/nexus/test_border_agent.cpp
This PR adds a new OT API `otBorderAgentGetMeshCoPServiceTxtData` to get MeshCoP Service TXT data from OT core.
The intention is to facilitate the NCP property update for MeshCoP Service TXT data. With the get API, NCP property update can use the `ChangedPropsSet` way which is more robust as discussed [here](https://github.com/openthread/openthread/pull/11271#discussion_r1969298582).
> [border agent] add OT API to get Border Agent MeshCoP Service TXT data

- src/posix/platform/radio_url.cpp
- src/posix/platform/spi_interface.cpp
- src/posix/platform/spi_interface.hpp
The RCP should assert the interrupt pin to notify the SPI interface of an impending data frame transfer to the host. This commit removes the polling mode from the spi interface.
> [posix] remove the polling mode from spi interface

- src/lib/platform/exit_code.c
- src/lib/platform/exit_code.h
- src/posix/platform/radio_url.cpp
- src/posix/platform/spi_interface.cpp
This commit modifies the process exit behavior to introduce a new exit code, `OT_EXIT_RCP_RESET_REQUIRED`. This code signals that a hardware reset is required by the POSIX platform, rather than being initiated directly by OpenThread itself.
This change is necessary to accommodate scenarios where the platform or a separate stack (e.g., Wifi/BT) is responsible for managing hardware resets of integrated chips (like Wifi/BT/Thread combo chips).  Previously, OpenThread might have attempted to handle resets directly, which is not always appropriate in these integrated environments.
This commit includes the following changes:
- **Adds a new exit code:** `OT_EXIT_RCP_RESET_REQUIRED` is now defined to indicate a platform-requested hardware reset.
- **Makes reset parameters optional:** The …
> [posix] introduce `OT_EXIT_RCP_RESET_REQUIRED` for platform reset requests

- include/openthread/instance.h
- include/openthread/srp_server.h
- src/cli/cli_srp_server.cpp
- src/core/net/srp_server.cpp
- src/core/net/srp_server.hpp
- tests/toranj/cli/cli.py
- tests/unit/test_srp_server.cpp
This commit adds a new option in `otSrpServerAddressMode` as `OT_SRP_SERVER_ADDRESS_MODE_UNICAST_FORCE_ADD`. This allows faster SRP server start up by bypassing the Network Data publisher and adding the "SRP/DNS unicast" entry directly to Network Data upon enabling of the SRP server, regardless of how many other similar entries are present.
This option is intended for testing and specific situations. A warning is added to indicate that using this option will make the device non-compliant with the Thread specification.
The unit test `test_srp_server` is updated with a new test case to validate the new `AddressMode` and its related behavior.
> [srp-server] add new `otSrpServerAddressMode` for faster start up

- src/core/mac/mac.cpp
- src/core/mac/mac_links.hpp
- src/core/mac/sub_mac.hpp
- src/core/mac/sub_mac_csl_receiver.cpp
- src/core/radio/radio.hpp
This commit updates `SubMac::UpdateCsl()` and related methods to use the core types `Mac::ExtAddress` and `Mac::ShortAddress` instead of C-style public/platform types. The extended address input is also changed from a pointer to a reference.
> [csl] update CSL methods to use core MAC address types

- src/core/meshcop/border_agent.cpp
This PR posts a MeshCoP service changed task after Epskc feature is enabled/disabled.
After Epskc feature is enabled/disabled, the 'EpskcSupported' bit in the statebitmap in MeshCoP Txt value should change accordingly.
This PR fixes the CI failure of the change in ot-br-posix: https://github.com/openthread/ot-br-posix/pull/2727
> [border-agent] change meshcop service TXT value after enabling/disabling Epskc

- src/core/mac/sub_mac.hpp
- src/core/mac/sub_mac_csl_receiver.cpp
This commit refactors the `sub_mac_csl_receiver.cpp` to handle `ReceiveAt()` and `Sleep() or Receive()` operations in different functions to simplify the code logic.
> [csl] handle `ReceiveAt()` and `Sleep() or Receive()` operations in different functions

- src/core/meshcop/border_agent.cpp
This PR fixes an issue in BorderAgent when handling Notifier events.
If the events contain 'Epskc' and BA is not running, then the meshcop service update will be skipped.
--
Depends-On: openthread/ot-br-posix#2727
> [border-agent] fix meshcop service update issue

- include/openthread/instance.h
- include/openthread/srp_server.h
- src/core/net/srp_server.cpp
- src/core/net/srp_server.hpp
- tests/unit/test_srp_server.cpp
This commit updates the `Srp::Server` so that Fast Start Mode can be disabled by a call to `otSrpServerSetAutoEnableMode()`, in addition to the existing method of calling `otSrpServerSetEnabled()`.
The `test_srp_server` unit test is updated to validate this new behavior.
> [srp-server] allow disabling "Fast Start Mode" via auto-enable

- src/core/net/srp_server.cpp
When in fast-start mode, the SRP server will be disabled and then immediately
enabled again if the device transfers from Child to Router. This commit fixes this
issue by also matching the ML-EID with the SRP server address in the Network Data.
> [srp-server] fix fast-start mode disruption when device role changes

- src/core/mac/sub_mac.hpp
- src/core/mac/sub_mac_csl_receiver.cpp
This commit updates how the CSL sample time is tracked in `SubMac`, ensuring that it is tracked using both radio time based on `otPlatRadioGetNow()` and the local time (`TimeMicro::GetNow()`). These two time sources may not necessarily be the same.
This change addresses the issue where the same time value was used for both scheduling `mCslTimer` (which should be based on local time) and for calls to the radio APIs (which should use radio time).
> [csl] use correct time basis for CSL sample time

- src/core/meshcop/joiner.cpp
This commit fixes the issue that the joiner starts joining process immediately when an invalid Joiner UDP Port is encountered. This issue was introduced by #9445 which attempts to ignore joiner routers having invalid Joiner UDP Port.
> [joiner] keep discovering when UDP port is bad

- src/core/thread/mesh_forwarder_ftd.cpp
This commit modifies `UpdateIp6RouteFtd()` to handle errors returned by `NetworkData::Leader::RouteLookup()`, ensuring that messages are dropped appropriately when a route lookup fails. It also initializes `mMeshDest` to an invalid RLOC16 at the beginning of the method.
> [mesh-forwarder] handle route lookup errors in `UpdateIp6RouteFtd()`

- src/core/mac/mac.cpp
This commit updates the CSL channel selection logic. When a CSL channel is not explicitly set, the code now uses the tracked `mPanChannel` (the current Thread PAN channel) instead of `mRadioChannel` (the current channel the radio is listening on). This ensures that the CSL channel aligns with the Thread PAN channel, even when the radio temporarily switches to other channels, such as during an MLE discover scan.
> [csl] use `mPanChannel` as default CSL channel

- include/openthread/border_routing.h
- include/openthread/instance.h
- src/cli/README_BR.md
- src/cli/cli_br.cpp
- src/core/api/border_routing_api.cpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- src/core/net/nd6.cpp
- src/core/net/nd6.hpp
- tests/unit/test_routing_manager.cpp
This commit introduces a mechanism in `RoutingManager` to parse and process Recursive DNS Server (RDNSS) options within received Router Advertisement (RA) messages. The list of discovered RDNSS addresses is tracked (per router) by `RoutingManager`, applying the advertised lifetime to properly age the discovered entries.
This commit adds a new public API to retrieve the list of tracked RDNSS addresses, along with a callback mechanism where OpenThread users can register to be notified of changes to the RDNSS list. This callback is invoked when any of the following changes occur:
- A new RDNSS address is advertised by a router.
- A previously discovered address is removed due to the router advertising it with a zero lifetime.
- A previously discovered address has aged out (its lifetime …
> [routing-manager] process RDNSS options and track addresses

- src/core/api/link_api.cpp
- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/mac/mac_links.hpp
- src/core/mac/sub_mac.hpp
- src/core/mac/sub_mac_csl_receiver.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
The current MLE and MAC layers will trigger a call to "SubMac::UpdateCsl()" when the status or CSL parameters change. This will bring a lot of unnecessary interface call overhead when we make RCP support CSL receiver in the future.
This commit refactors the code so that the MLE and MAC layers only trigger a call to `UpdateCsl` when a valid state or parameter change occurs. This commit also separates the logic of enabling CSL and setting CSL parameters, making the code logic easier to understand.
> [csl] update CSL parameters only when necessary

- src/core/net/ip6.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
Let's consider this scenario:
Topology:
```
TED1 --- TBR --- TED2
```
All devices have joined the same Thread network, with the TBR connected to the infrastructure network interface. The TBR publishes an OMR prefix in the Thread network via the Thread network data. As a result, all other devices assign themselves an OMR prefix address on the Thread link (referred to as OMR1 on TED1 and OMR2 on TED2).
Within the Thread network, devices can communicate using their OMR prefix addresses. For example, on the TBR, both OMR1 and OMR2 are accessible via the ping command.
However, if the TBR loses its connection to the infrastructure network interface, it updates its service configuration: the OMR prefix is removed.Other device will also update their network data. However, the OMR prefix address …
> [mesh-forwarder] fix Ip6 route selected when OMR prefix has been removed but the OMR address is still valid

- src/core/meshcop/joiner.cpp
- src/core/meshcop/secure_transport.cpp
- src/core/meshcop/secure_transport.hpp
This commit aims to add the posibility to specify a netif identifier for SecureTransport::Open method. This method has now a default parameter, kNetifUnspecified, if no argument is explicitly passed by the user.
> [secure-transport] add option to specify NetifIdentifier

- src/posix/platform/resolver.cpp
- src/posix/platform/resolver.hpp
This PR enhances the DNS resolver (`resolver.cpp`) to support IPv6 addresses in upstream DNS server configurations, allowing for greater flexibility and compatibility in IPv6-enabled environments.
**Key Changes:**
*   **IPv6 Parsing in `LoadDnsServerListFromConf`:**
*   The `LoadDnsServerListFromConf` function now parses both IPv4 and IPv6 addresses from `/etc/resolv.conf` using `inet_pton` with `AF_INET` and `AF_INET6`.
*   Parsed addresses are stored in `mUpstreamDnsServerList`.
*   **IPv6 Handling in `Query`:**
> [posix] update Posix::Resolver to support IPv6 addresses for servers.

- include/openthread/instance.h
- include/openthread/mdns.h
- src/cli/cli_mdns.cpp
- src/cli/cli_mdns.hpp
- src/core/api/mdns_api.cpp
- src/core/net/dns_types.cpp
- src/core/net/dns_types.hpp
- src/core/net/mdns.cpp
- src/core/net/mdns.hpp
- tests/unit/test_mdns.cpp
This commit enhances the native mDNS implementation by adding `RecordQuerier`, which enables continuous queries for arbitrary record types and query names. The `RecordQuerier` follows a pattern similar to service/address browsers and resolvers, allowing multiple queriers to be started for the same record type and name (provided they use different callbacks).
Record results are cached, and the cache correctly handles and reports when new records are added or removed (either explicitly or due to timeouts), including when the "cache-flush" flag is used in a response.
Public OpenThread APIs and corresponding CLI commands are added for `RecordQuerier` functionality.
The `test_mdns` unit test is updated with a detailed test case covering the newly added `RecordQuerier` functions.
> [mdns] introduce `RecordQuerier` for continuous record queries

- src/core/coap/coap.cpp
- src/core/coap/coap.hpp
This commit introduces `CoapBase::ScheduleRetransmissionTimer()`, a new method that calculates the next retransmission timer fire time based on all queued messages in `mPendingRequests` and then schedules (starts or stops) the timer.
This method is now used whenever `mPendingRequests` is updated (a new message is added or an existing message is removed). It is also used in `HandleRetransmissionTimer()`, the timer's callback. This change centralizes timer scheduling, simplifying the logic.
This also addresses an issue in the existing code where `HandleRetransmissionTimer()` iterated over `mPendingRequests` to determine expired messages and calculate the next fire time. However, finalizing an expired message could trigger its `ResponseHandler` callback, from which the caller may start or …
> [coap] ensure correct retransmission timer scheduling

- tests/scripts/thread-cert/node.py
Previously, the code relied on the return code of the `service radvd status` command to determine if `radvd` was running. This was unreliable because the command could succeed even if the service was not actually active.
The `is_radvd_running` function now parses the output of `service radvd status` and specifically checks for the line "running" to confirm that the service is truly running.
> [tests] fix: ensure radvd service starts correctly

- src/posix/README.md
- tools/cp-caps/README.md
Nrfjprog is not longer recommended and was replaced by the nrfutil. Replaced documentation occurrences mentioning nrfjprog with nrfutil.
> [cp-caps] replace nrfjprog with nrfutil in docs

- include/openthread/instance.h
- src/core/api/instance_api.cpp
Add otInstanceGetIdx function that can be useful in multi-instance context at platform level.
> [instance] add `otInstanceGetIndex()`

- include/openthread/instance.h
- include/openthread/netdata.h
- src/cli/README_NETDATA.md
- src/cli/cli_network_data.cpp
- src/cli/cli_network_data.hpp
- src/core/thread/network_data_types.cpp
- tests/toranj/cli/test-019-netdata-context-id.py
- tests/toranj/cli/test-035-context-id-change-addr-reg.py
This commit updates `otLowpanContextInfo` to include the `mStable` flag, indicating whether the 6LoWPAN Context TLV is marked as stable or not. The `netdata show` CLI command is also updated to display the stable flag when outputting the list of contexts. Additionally, this commit updates the `test-019-netdata-context-id` test to adjust how it checks and validates the "compress" flag.
> [netdata] add stable flag to `otLowpanContextInfo` and CLI output

- tests/scripts/thread-cert/node.py
This commit fixes `get_srp_server_port()` in `thread-cert/node.py`. This function parses Network Data service entries, searching for an SRP/DNS unicast (non-preferred) entry, and then attempts to parse the published port number of the SRP server by examining the last  bytes of the "server data".
The SRP/DNS unicast entry was previously updated to optionally include a "version" field at the end of the "server data". This update caused the port number parsing to fail, as the code did not account for the extra byte corresponding to the version field.
This commit resolves this issue by ensuring that the two bytes are correctly read and interpreted as the port number, regardless of the presence of the version field.
> [test] fix `get_srp_server_port()` to handle the version field

- include/openthread/instance.h
- include/openthread/platform/radio.h
This commit enhances the documentation of certain `otPlatRadio` APIs for improved clarity.
Most importantly, regarding the `otExtAddress` input parameters, earlier APIs such as `otPlatRadioSetExtendedAddress()`, `otPlatRadio {Add/Clear}SrcMatchExtEntry()` assume little-endian byte order. This is already noted in their documentation. However, some more recent APIs, namely `otPlatRadioConfigureEnhAckProbing()` and `otPlatRadioEnableCsl()` do not explicitly specify the byte order. Common radio platform implementations (and how the APIs are used) assume big-endian byte order. While this discrepancy is unfortunate, changing it would create backward compatibility with existing platform implementations. This commit updates the documentation of these APIs to mention the byte order and highlight …
> [radio] clarify `otExtAddress` byte order and `otPlatGetRssi` behavior

- include/openthread/instance.h
- include/openthread/netdiag.h
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/thread/network_diagnostic.cpp
- src/core/thread/network_diagnostic.hpp
- src/core/thread/network_diagnostic_tlvs.cpp
- src/core/thread/network_diagnostic_tlvs.hpp
- tests/toranj/cli/test-023-mesh-diag.py
This commit adds support for the Network Diagnostics Enhanced Route TLV (TLV number 37). This TLV provides information about established links between routers, including the next hop and associated cost for routes to all routers. This commit also adds CLI support and test coverage for the new TLV.
---
Related to [SPEC-1361](https://threadgroup.atlassian.net/browse/SPEC-1361).
> [netdiag] add support for Enhanced Route TLV

- src/core/mac/mac_frame.cpp
This is a follow up to #11190 where more indirect `!OPENTHREAD_RADIO`
checks are replaced with direct MTD and FTD checks
> [mac] replace more `!OPENTHREAD_RADIO` with direct FTD/MTD check

- include/openthread/instance.h
- include/openthread/mdns.h
- include/openthread/platform/mdns_socket.h
- src/cli/cli_mdns.cpp
- src/core/api/mdns_api.cpp
- src/core/instance/instance.cpp
- src/core/net/mdns.cpp
- src/core/net/mdns.hpp
- tests/unit/test_mdns.cpp
This commit enhances the native OpenThread mDNS implementation to streamline the registration of the local host and its IPv6/IPv4 addresses.
Previously, registering the local host required tracking host addresses and using `otMdnsRegisterHost()`, similar to registering any other host. This commit introduces a simpler alternative that handles both IPv6 and IPv4 addresses.
The changes in this PR include:
- The local host name can be explicitly set by the caller using new API `otMdnsSetLocalHostName`. However, if not provided, the mDNS module automatically generates a name derived from the device's Extended MAC address.
- A new platform API callback, `otPlatMdnsHandleHostAddressEvent`, is introduced to notify the OpenThread mDNS module of host address changes.
- The OpenThread mDNS maintains …
> [mdns] support registering local host and its IPv6/IPv4 addresses

- .github/workflows/simulation-1.1.yml
Resolves:
```
CMake Error at third_party/googletest/repo/CMakeLists.txt:4 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```
> [github-actions] add `-DCMAKE_POLICY_VERSION_MINIMUM=3.5` to ot-commissioner build

- .github/workflows/build.yml
Resolves:
```
CMake Error at third_party/mbedtls/repo/CMakeLists.txt:23 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```
> [github-actions] add `-DCMAKE_POLICY_VERSION_MINIMUM=3.5` to mbedtls2 build

- include/openthread/border_routing.h
- include/openthread/instance.h
- src/cli/README_BR.md
- src/cli/cli_br.cpp
- src/core/api/border_routing_api.cpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- tests/unit/test_routing_manager.cpp
This commit introduces a new mechanism in `RoutingManager` to configure OMR prefix handling on a Border Router. This provides manual administration options to explicitly set a custom OMR prefix or disable it, in addition to the existing default behavior where the BR automatically selects and manages the OMR prefix. These new administrative configurations can also be used during testing, particularly for certification tests.
This commit adds new public OpenThread APIs and a CLI command, `br omrconfig`, for this functionality. Notably, the new APIs allow updating the OMR configuration while the BR is enabled and running, and the implementation correctly adjusts to the new requested behavior.
A new detailed test case is added to the `test_routing_manager` unit test, covering the new …
> [routing-manager] add manual OMR prefix configuration on BR

- src/core/instance/instance.cpp
This commit adds a check in `instance.cpp` to ensure that exactly one of the `OPENTHREAD_CONFIG_FTD`, `OPENTHREAD_CONFIG_MTD`, or `OPENTHREAD_CONFIG_RADIO` configuration options is enabled. This enforces a clear definition of the build type and prevents potential conflicts or unexpected behavior arising from ambiguous or incorrect configurations.
> [core] check exclusive selection of FTD, MTD, or RADIO configs

- src/core/border_router/routing_manager.cpp
- src/core/common/uptime.cpp
- src/core/common/uptime.hpp
- src/core/thread/mle.cpp
- src/core/thread/neighbor.cpp
This commit introduces a new method, `Uptime::GetUptimeInSeconds()`, which returns the device's uptime in seconds. This new method simplifies existing code that performed manual conversion of the uptime from milliseconds to seconds.
> [uptime] add `GetUptimeInSeconds()` method for simplified uptime retrieval

- src/core/api/coap_api.cpp
- src/core/api/coap_secure_api.cpp
- src/core/coap/coap.hpp
- src/core/instance/instance.cpp
- src/core/instance/instance.hpp
This commit updates the template method `Instance::Get<Type>()` to support retrieving the `ApplicationCoap` and `ApplicationCoapSecure` sub-components within the `Instance` hierarchy. This change replaces the previous direct methods used to access these CoAP components, providing a more consistent approach to accessing sub-components.
> [coap] update `Instance::Get<Type>()` to support application CoAP comonents

- src/core/thread/indirect_sender.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
This commit simplifies the process of determining the destination MAC address. Specifically, when the destination is a link-local unicast address, the MAC address is derived directly from its Interface Identifier (IID). This commit replaces and removes the `GetMacDestinationAddress()` method, with the calling code now directly determining the destination MAC address.
> [mesh-forwarder] simplify destination MAC address determination

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
This method inspects a received message to perform two key actions:
- Updating the EID-to-RLOC cache (for snoop optimization) and
- Detecting whether a former child device has moved to a new parent.
The renaming clarifies the specific responsibilities of this method.
> [mesh-forwarder] rename `UpdateEidRlocCacheAndStaleChild()`

- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
This PR contains two related commits. They are kept as separate commit to make it easier to review.
**[ip6] refactor `HandleDatagram()` to use `DetermineAction()`**
This commit introduces the `DetermineAction()` method to refactor the code within `HandleDatagram()`. This new method centralizes the logic for determining the appropriate action (e.g., `forwardThread`, `forwardHost`, `receive`) for an IPv6 message based on its destination address and origin.
This commit only focuses on code refactoring and does not introduce any changes to the existing message processing logic.
----
**[ip6] simplify `DetermineAction()`**
This commit simplifies the `Ip6::DetermineAction()` method, which determines the appropriate actions (`forwardThread`, `forwardHost`, `receive`) for an IPv6 message based on …
> [ip6] refactor and simplify `HandleDatagram()`

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
This commit renames methods related to reachability checks and the sending of ICMP unreachable errors for better clarity and consistency. The primary method for determining reachability is renamed to `IsReachable()`. Methods that perform a reachability check and, upon failure, send an ICMP unreachable error are renamed as `CheckReachabilityToSendIcmpError()`, clearly indicating their additional action of sending an ICMP error.
> [mesh-forwarder] improve reachability check method names

- src/core/coap/coap.cpp
- src/core/coap/coap.hpp
- src/core/common/message.cpp
- src/core/common/message.hpp
- src/core/instance/instance.cpp
- src/core/net/ip6.hpp
- src/core/net/ip6_mpl.hpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mle.hpp
This commit simplifies how information about the message queue, such as the number of messages, data buffers, or total bytes in the queue, is retrieved. The `MessageQueue::GetInfo()` method is changed to clear the passed-in `Info` structure (instead of adding the counts to the existing fields and expecting the caller to clear it).
A new helper method, `MessageQueue::AddQueueInfos()`, is added to aggregate queue information when needed.
Various modules, such as `MeshForwarder`, `Ip6`, and `Mle`, are updated to provide methods to retrieve their queue information instead of exposing a reference to their internal queues.
In particular, `Coap` is updated to provide combined information for all its queues, including request and cached response queues. This simplifies the …
> [message-queue] simplify retrieval of message queue information

- include/openthread/dns_client.h
- include/openthread/instance.h
- src/cli/README.md
- src/cli/cli_dns.cpp
- src/cli/cli_dns.hpp
- src/core/api/dns_api.cpp
- src/core/config/dns_client.h
- src/core/net/dns_client.cpp
- src/core/net/dns_client.hpp
- src/core/net/dns_types.hpp
This commit introduces a new feature in `Dns::Client` to support sending DNS queries for arbitrary record types. Callers are notified of received response via a callback. New methods are provided to parse and read all records in the response. Public APIs and related CLI commands for this new feature are also added.
The `OPENTHREAD_CONFIG_DNS_CLIENT_ARBITRARY_RECORD_QUERY_ENABLE` build configuration is added to control this feature. This allows projects that do not require arbitrary DNS query functionality to disable it, avoiding its associated firmware code size overhead.
Importantly, if a retrieved record type is PTR, CNAME, DNAME, NS, or SRV, the record data in the received response contains a DNS name which may use DNS name compression. For these specific record types, the record data …
> [dns-client] add support for arbitrary DNS record type query

- src/core/meshcop/tcat_agent.cpp
- src/core/meshcop/tcat_agent.hpp
- src/core/radio/ble_secure.cpp
- src/core/radio/ble_secure.hpp
- src/core/thread/network_diagnostic.cpp
- src/core/thread/network_diagnostic.hpp
- tests/scripts/expect/cli-tcat-diagnostics.exp
- tools/tcat_ble_client/cli/base_commands.py
- tools/tcat_ble_client/cli/cli.py
- tools/tcat_ble_client/tlv/diagnostic_tlv.py
Adds implementation of Tcat TLV 0x26 Get Diagnostic TLVs.
It also adds support for long BleSecure messages >1280 bytes in BleSecure::Flush(void).
> [tcat] implement get diagnostic tlvs in command class commissioning

- include/openthread/instance.h
- include/openthread/platform/mdns_socket.h
- src/core/net/mdns.cpp
- src/core/net/mdns.hpp
- tests/unit/test_mdns.cpp
This commit introduces an alternate mechanism for the platform layer to signal local host address changes to the OpenThread mDNS module.
The existing approach, where the platform invokes
`otPlatMdnsHandleHostAddressEvent()` for each added or removed address, remains supported.
The new approach allows the platform to call the newly added `otPlatMdnsHandleHostAddressRemoveAll()` callback once, immediately followed by invoking `otPlatMdnsHandleHostAddressEvent` for every currently assigned IPv4 and IPv6 address on the interface.
These two approaches offer flexibility for platforms with varying capabilities accommodating different operating systems and network stacks. Some network stacks may provide mechanisms to identify the added or removed addresses, while others may only provide the new …
> [mdns] alternate platform API for signaling local address changes

- src/core/meshcop/secure_transport.cpp
Due to CVE-2025-27809, on newer versions of mbedtls, handshake will fail unless hostname is set earlier.
TLS clients are not affected if they operate in a closed ecosystem where the trusted certificate authority only issues certificates to trusted hosts.
In this case, `mbedtls_ssl_set_hostname` with nullptr should be called to avoid failures.
More information on CVE-2025-27809: https://mbed-tls.readthedocs.io/en/latest/security-advisories/mbedtls-security-advisory-2025-03-1/
> [mbedtls] call `mbedtls_ssl_set_hostname` on setup

- include/openthread/border_agent.h
- include/openthread/instance.h
- src/core/meshcop/border_agent.cpp
The PR fixes the issue of missing OMR entry in MeshCoP TXT record.
In previous PR, a wrong macro is used so `AppendOmrTxtEntry` is never enabled.
> [border-agent] fix meshcop service omr entry

- include/openthread/instance.h
- include/openthread/mdns.h
- src/cli/cli_mdns.cpp
- src/core/api/mdns_api.cpp
- src/core/net/mdns.cpp
- src/core/net/mdns.hpp
- tests/unit/test_mdns.cpp
This commit introduces an API to iterate over the local host IPv6 and IPv4 addresses known to the OpenThread mDNS module.
The platform layer is responsible for monitoring and reporting all host IPv4 and IPv6 addresses to the OpenThread mDNS module, which then tracks the full address list
(see `otPlatMdnsHandleHostAddressEvent()`). The newly added function allows iteration through this tracked list, primarily intended for information and debugging purposes.
This commit also adds a CLI command to utilize the new API. Additionally, the `test_mdns` unit test has been updated to validate the functionality of the newly added API.
> [mdns] add API to get the list of local host IP addresses

- src/posix/platform/openthread-posix-config.h
- src/posix/platform/platform-posix.h
This commit enhances the `openthread-posix-config.h` header by:
- Moving configurations defined in other headers (`platform-posix.h`) into this common header.
- Making sure the section containing guard checks for removed or renamed POSIX configurations is at the end of the header file.
> [posix] enhance config header file

- include/openthread/instance.h
- include/openthread/mdns.h
- src/core/net/dns_types.cpp
- src/core/net/dns_types.hpp
- src/core/net/mdns.cpp
- tests/unit/test_dns.cpp
This commit updates the mDNS `RecordQuerier` to handle record types where the RDATA contains one or more potentially compressed DNS names. For these types, the reported record data is now decompressed to include the full DNS names. This enhancement applies to the following record types: NS, CNAME, SOA, PTR, MX, RP, AFSDB, RT, PX, SRV, KX, DNAME, and NSEC.
To achieve this, a helper `ResourceRecord::DecompressRecordData()` method is introduced. This method uses a "recipe" formula specific to each supported record type. The recipe defines the number of prefix bytes before the first embedded name, the number of DNS names, and the minimum number of suffix bytes after the names. A common implementation then uses this recipe to parse and decompress the RDATA. This approach makes the …
> [dns] introduce `DecompressRecordData()` and use it in mDNS

- include/openthread/border_routing.h
- include/openthread/instance.h
- src/cli/README_BR.md
- src/cli/cli_br.cpp
- src/cli/cli_br.hpp
- src/core/api/border_routing_api.cpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- src/core/config/border_routing.h
- tests/toranj/cli/cli.py
- tests/toranj/cli/test-505-multi-ail-detection.py
- tests/toranj/start.sh
This commit introduces the `MultiAilDetector` feature within the `RoutingManager`. This feature detects whether Border Routers(BRs) on the Thread mesh might be connected to different Adjacent Infrastructure Links (AILs).
The feature can be enabled using the configuration option `OPENTHREAD_CONFIG_BORDER_ROUTING_MULTI_AIL_DETECTION_ENABLE`.
The detection mechanism operates as follows: The Routing Manager monitors the number of peer BRs listed in the Thread Network Data and compares this with the number of peer BRs discovered by processing received Router Advertisements (RAs) on its local AIL.
If the count derived from Network Data consistently exceeds the count derived from RAs for a detection period of ten minutes, the detector concludes that BRs are likely connected to different AILs. …
> [routing-manager] introduce `MultiAilDetector`

- src/core/net/tcp6.cpp
- third_party/tcplp/bsdtcp/tcp_subr.c
- third_party/tcplp/bsdtcp/tcp_usrreq.c
Temporary solution for #11255?
---
Why is `(void) tcplp_output(tp)` called *after* `tcp_state_change(tp, TCPS_CLOSED)`? Shouldn't `tcplp_output(tp)` be called *first* to send any remaining data or to send a RST/FIN, *before* calling `tcp_state_change(tp, TCPS_CLOSED)`?
```
struct tcpcb *
tcp_drop(struct tcpcb *tp, int errnum)
{
if (TCPS_HAVERCVDSYN(tp->t_state)) {
tcp_state_change(tp, TCPS_CLOSED);
(void) tcplp_output(tp);
}
if (errnum == ETIMEDOUT && tp->t_softerror)
errnum = tp->t_softerror;
tp = tcp_close_tcb(tp);
tcplp_sys_connection_lost(tp, errnum);
return tp;
}
```
> [tcp] send RST and clear send buffer on abort

- examples/platforms/simulation/dnssd.c
- include/openthread/instance.h
- include/openthread/mdns.h
- include/openthread/platform/dnssd.h
- src/core/net/dns_types.cpp
- src/core/net/dns_types.hpp
- src/core/net/dnssd.cpp
- src/core/net/dnssd.hpp
- src/core/net/dnssd_server.cpp
- src/core/net/dnssd_server.hpp
- src/ncp/platform/dnssd.cpp
- tests/scripts/thread-cert/border_router/test_dnssd_server.py
- tests/scripts/thread-cert/border_router/test_dnssd_server_multi_border_routers.py
- tests/scripts/thread-cert/node.py
- tests/scripts/thread-cert/test_dnssd.py
- tests/unit/test_dns_client.cpp
- tests/unit/test_dnssd_discovery_proxy.cpp
- tests/unit/test_platform.cpp
This commit enhances the OpenThread DNSSD name server/resolver and its native Discovery Proxy to support queries for arbitrary record types.
To enable this, a new set of `otPlatDnssd` APIs are introduced for generic `RecordQuerier`. These APIs mirror the existing APIs in the OpenThread native mDNS module, allowing direct use of the native mDNS implementation.
The discovery proxy implementation is updated to start and stop the mDNS `RecordQuerier` when receiving a query for an arbitrary record type, passing the first response record back to the client.
The unit tests `test_dnssd_discovery_proxy` and `test_dns_client` are updated to cover all the newly added behaviors in discovery proxy. 
-----
~This PR currently contains the commit from #11359. Please check and review the last commit on …
> [dnssd] support generic record queries via discovery proxy and SRP

- include/openthread/dns_client.h
- include/openthread/instance.h
- src/core/net/dns_client.cpp
This commit updates the DNS client to use `DecompressRecordData()` helper method when processing `QueryRecord()` responses for arbitrary record types.
This enables decompression of embedded DNS names within the received record data for a wider range of record types. In particular, name decompression is now supported for PTR, CNAME, DNAME, NS, SRV, SOA, MX, RP, AFSDB, RT, PX, KX, and NSEC records.
----
~This PR currently contains the commit from https://github.com/openthread/openthread/pull/11408. Please check and review the second commit. Thanks.~
> [dns-client] use `DecompressRecordData()` for broader record type support

- src/core/net/dnssd_server.cpp
- src/core/net/dnssd_server.hpp
This commit contains a few smaller enhancements in the DNS-SD server implementation:
- `ShouldForwardToUpstream()` now checks the `mEnableUpstreamQuery`.
- The `ResolveByUpstream()` method now handles its own error logging.
- Comments are added/updated to improve code readability.
> [dnssd] smaller enhancements in `Server`

- src/core/net/dnssd_server.cpp
- src/core/net/dnssd_server.hpp
This commit introduces a template helper `AppendServiceRecords()` designed to append service-related records (SRV, TXT, and host AAAA addresses) to the appropriate sections within a DNS `Response` message.
This helper simplifies the codebase by removing repeated patterns. These patterns occur when resolving queries using either SRP service data or `ServiceInstanceInfo` retrieved from the platform (when the platform implements discovery proxy function).
> [dnssd] introduce `AppendServiceRecords()` helper

- src/core/BUILD.gn
- src/core/CMakeLists.txt
- src/core/common/message.hpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/thread_link_info.cpp
- src/core/thread/thread_link_info.hpp
This commit refactors the `ThreadLinkInfo` definition by moving it into its own dedicated header (`thread_link_info.hpp`) and source (`.cpp`) files. Previously, this definition was part of `mesh_forwarder.hpp`.
This change simplifies the overall code structure. It also allows the new `thread_link_info.hpp` header to be included by other modules, such as `message.hpp`, thereby avoiding the need for forward declarations.
> [core] move `ThreadLinkInfo` to its own header and source files

- src/core/net/dns_types.cpp
- src/core/net/dns_types.hpp
- src/core/net/dnssd_server.cpp
- src/core/net/dnssd_server.hpp
- tests/unit/test_dnssd_discovery_proxy.cpp
This commit adds implementation for RDATA translation in the OpenThread native discovery proxy. Specifically, for certain record types (like CNAME) where the record data includes one or more embedded DNS names, this translation applies. If the embedded DNS name in RDATA uses the local mDNS domain (`local.`), it is replaced with the corresponding domain name for the Thread mesh network (`default.service.arpa.`). Otherwise, the name is included unchanged in the record data.
A new method, `AppendTranslatedRecordDataTo()`, is added to perform this translation. It utilizes the `DataRecipe` table, similar to `DecompressRecordData()`, to parse the record data and update the embedded DNS names as needed.
The `test_dnssd_discovery_proxy` unit test is updated to cover the new record data …
> [dnssd] support RDATA translation in discovery proxy

- src/core/thread/mle_ftd.cpp
This commit adds a safeguard check in `Mle::HandleTimeTick()` to protect against cases where scheduling or sending a Link Request message to a new neighboring router fails. This can happen, for example, if the device is temporarily out of message buffers.
This scenario is determined by checking if `router.IsStateLinkRequest()` is true, there is no Link Request message scheduled to be sent to this router, and the device is not waiting for a Link Accept (`!router.IsWaitingForLinkAccept()`). In such a case, the neighbor is removed using `RemoveNeighbor()`.
----
Related to  [discussions/11052](https://github.com/orgs/openthread/discussions/11052).
> [mle] add safeguard for link request scheduling failures

- src/core/api/border_agent_api.cpp
- src/core/border_router/routing_manager.cpp
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- tests/nexus/test_border_agent.cpp
This commit updates `BorderAgent` method and variable names to use shorter forms where possible. Specifically, the term `MeshCoP` is removed from many variable and method names, as the `BorderAgent` class itself is already defined within the `MeshCoP` namespace.
This commit is purely a style and naming change and contains no modification to the code logic.
> [border-agent] shorten method and variable names

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- tests/nexus/test_border_agent.cpp
This commit updates the `BorderAgent` to ensure that if its `Id` is changed using the `SetId()` method, any consequent changes to the generated TXT data for the MeshCoP service are correctly signaled. This signaling is performed using the "Service TXT Data changed callback". This commit also updates `test_border_agent` to validate this.
----
~This PR contains the commit from https://github.com/openthread/openthread/pull/11456.~
> [border-agent] signal TXT data change when Id is updated

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
This commit simplifies the preparation of the State Bitmap, which is included in the Border Agent's TXT data using the `sb` key.
Specifically, constants for field values are now directly used to construct the `uint32_t` bitmap, making the process more
straightforward.
Additionally, relevant constants are converted to use `static constexpr`, avoiding the use of unnamed `enum` definitions.
> [border-agent] simplify State Bitmap preparation

- src/core/net/udp6.cpp
This commit relaxes the `SocketHandle::Matches()` method to allow a socket associated with `kNetifUnspecified` to match when `IsHostInterface()` is set. This is in addition to the existing behavior of matching a backbone socket under the same condition.
> [udp] relax `SocketHandle::Matches()` for host interface

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- src/core/net/dns_types.cpp
- src/core/net/dns_types.hpp
- src/core/radio/trel_interface.cpp
This commit moves and enhances the `TxtDataEncoder` class, relocating it to the common `dns_types.hpp` header file.
The new `TxtDataEncoder` provides helper methods to append TXT entries with a variety of value types, including `NameData`, C-strings, or an unsigned integer (in big-endian format). This enhanced encoder is then used by the `BorderAgent` when preparing MeshCoP TXT data and also by the TREL module.
> [dns] add common `TxtDataEncoder`

- include/openthread/instance.h
- include/openthread/trel.h
- src/core/radio/trel_interface.cpp
- src/core/radio/trel_interface.hpp
This commit updates the internal data structure used for tracking TREL peers. Peer tracking now uses a `LinkedList` of `Peer` objects allocated from a pre-allocated `Pool<Peer>`, instead of using a fixed-size `Array<Peer>`.
This change allows for future enhancements, such as using heap-allocated `Peer` entries and/or extending the `Peer` object to track additional (dynamically allocated) information.
> [trel] use `LinkedList` for TREL peer tracking

- src/posix/platform/CMakeLists.txt
- src/posix/platform/infra_if.cpp
- src/posix/platform/infra_if.hpp
- tests/scripts/thread-cert/border_router/internet/test_multi_border_routers.py
- tests/scripts/thread-cert/border_router/internet/test_with_infrastructure_prefix.py
Thread Specification is transitioning from [RFC 7050](https://tools.ietf.org/html/rfc7050) to [RFC 8781](https://tools.ietf.org/html/rfc8781) for discovering the NAT64 prefix. This commit removes RFC 7050 behavior.
> [nat64] remove support for `ipv4only.arpa`

- src/core/BUILD.gn
- src/core/CMakeLists.txt
- src/core/radio/trel_interface.cpp
- src/core/radio/trel_interface.hpp
- src/core/radio/trel_link.hpp
- src/core/radio/trel_peer.cpp
- src/core/radio/trel_peer.hpp
This commit contains smaller changes related to the TREL `Peer` class and the parsing of TXT data within the `PeerInfo` class.
The `Peer` class definition is now moved into its own `trel_peer.hpp` and `trel_peer.cpp` header and source files, separating it from the `Trel::Interface` class. Additionally, the `Log()` method within the `Peer` class has been enhanced (now using an `Action` enum).
The `PeerInfo` class remains a nested class of `Interface` and now provides a `ParseTxtData()` method to parse the included TXT data entries.
> [trel] refactor `Peer` class and enhance `PeerInfo` parsing

- src/core/thread/dua_manager.cpp
In `PerformNextRegistration()`, there are many reasons why no
registration message will be sent. For example, device is not attached
or there are no DUAs to register.
This commit suppresses warn-level log messages when no registration
message is expected and normal behavior.
> [dua] suppress warning logs on normal behaviors

- src/posix/platform/netif.cpp
- src/posix/platform/openthread-posix-config.h
This PR allows to configure the link-local route's metric via macro on Linux. By using a larger metric, we can prevent host processes from accidentally sending traffic to Thread network interface. 
For example, when the mDNS daemon on the BR wants to respond to a `QU` mDNS question, it will send the mDNS response to a link-local address. In a multi-network environment, it could wrongly go to the Thread network interface if the socket is not explicitly bound to the desired interface.
> [posix] make the link-local route's metric configurable

- src/core/BUILD.gn
- src/core/CMakeLists.txt
- src/core/instance/instance.hpp
- src/core/radio/trel_interface.cpp
- src/core/radio/trel_interface.hpp
- src/core/radio/trel_link.cpp
- src/core/radio/trel_link.hpp
- src/core/radio/trel_peer.hpp
- src/core/radio/trel_peer_discoverer.cpp
- src/core/radio/trel_peer_discoverer.hpp
This commit introduces `PeerDiscoverer` as a class responsible for TREL peer discovery, separating this logic from `Trel::Interface`. The new class currently handles the preparation of TXT data, calling the platform API to register the TREL service, and handling callbacks from the platform layer with newly discovered or updated peer information.
This separation helps with TREL module organization and enables future extensions, such as performing discovery using the native OpenThread mDNS module or the platform-specific DNS-SD (`otPlatDnssd`) module, in addition to the existing approach where discovery is delegated to the platform layer.
> [trel] introduce `Trel::PeerDiscoverer` class

- include/openthread/border_agent.h
- include/openthread/instance.h
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- tests/nexus/test_border_agent.cpp
This commit updates `BorderAgent::PrepareServiceTxtData()` to include the "rv" key. This key represents the version of the TXT record format. Per the Thread specification, it must be set to "1". Values other than "1" are reserved for the future and MUST NOT be used.
This commit also updates `test_border_agent` to validate this key.
> [border-agent] add 'rv' key to MeshCoP TXT data

- src/include/common/code_utils.hpp
Previously, the `VerifyOrExit()` macro's condition caused clang-tidy to issue false positives regarding "boolean readability," suggesting simplifications via De Morgan's Theorem. This occurred because the macro wrapped the entire condition and then checked its negative.
This commit refactors the macro to evaluate the condition directly, which:
1. Eliminates the erroneous clang-tidy warnings.
2. Potentially enhances CPU branch prediction performance, as the condition is more likely to evaluate to true.
> [utils] fix clang-tidy false alarm in VerifyOrExit

- src/core/net/dnssd_server.cpp
- tests/unit/test_dns_client.cpp
This commit updates the DNSSD server/resolver to ensure it includes the questions in the response message when the returned RCODE is `NameError` (NXDOMAIN). It also clears the question count and any partially appended content if there is a failure to append all questions (when `kResponseServerFailure` (SERVFAIL) is returned).
It also adds a test case in `test_dns_client` to resolve a non-existent name and validate the included questions.
---
- Resolves #11505
> [dnssd] echo all questions in the response on `NameError`

- src/core/net/dns_types.hpp
This adds comments to DNS types, to ensure that official names from the IANA DNS parameters registry can be found in the OT source code when starting to search from that starting point. This will make development and code analysis easier for those not familiar with OT, or coming from the DNS world. The IANA names (which may deviate from RFC names) are from: https://www.iana.org/assignments/dns-parameters
> [dns] update comments DNS-types to match IANA

- src/core/radio/trel_peer.cpp
- src/core/radio/trel_peer.hpp
- src/core/radio/trel_peer_discoverer.cpp
- src/core/radio/trel_peer_discoverer.hpp
This commit updates `Trel::Peer` and `PeerTable` to allow scheduling a `Peer` for removal from the table after a given delay. This enables smoother peer removal, especially for transient issues, by avoiding abrupt disconnections.
To implement this, a `State` has been added to the `Peer` class, tracking whether a peer is in `kStateValid` or `kStateRemoving`. If a peer scheduled for removal is discovered again, it will be re-added and marked as valid. Logging is also updated to show these new state transitions. Additionally, `EvictPeer()` is updated to prioritize evicting peers already scheduled for removal.
To ensure consistent API behavior, peers that are scheduled for removal are skipped when iterating over the peer table using `otTrelGetNextPeer()` or `otTrelGetNumberOfPeers()`.
> [trel] implement delayed peer removal in `PeerTable`

- examples/apps/cli/ftd.cmake
- examples/apps/cli/mtd.cmake
- examples/apps/cli/radio.cmake
> [examples] define `OPENTHREAD_FTD` and `OPENTHREAD_MTD`

- src/core/net/dnssd_server.cpp
- src/core/net/dnssd_server.hpp
- tests/unit/test_dns_client.cpp
This commit updates the DNS-SD server to support responding to SOA and NS record queries (including `ANY` record type queries) for the default service domain. The recommended values for SOA record data from RFC-8766 section 6.1 are used. The server name included in SOA/NS answers is derived from the Extended Address of the device, ensuring it remains fixed and consistent over reboots as long as the device's Extended Address stays the same.
A new detailed test case is added in the `test_dns_client` unit test to cover all the newly added behavior. This test verifies multiple scenarios, in particular, when a query is made for a name not hosted by the server. In such cases, the response will contain no records in the answer section but include the SOA or NS record for the zone in the …
> [dnssd-server] support SOA and NS query

- .gitignore
python venv is used when running test in tools/cp-caps
> [gitignore] add python virtual env folder

- tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py
This commit updates `test_publish_meshcop_service` to relax the checks when verifying mDNS browse response. Specifically, after `br1` is factory reset, the Border Agent and other functions are not given the chance to stop properly and remove previously registered mDNS entries. This can result in stale entries remaining in the mDNS cache, leading to more service entries appearing in `browse` results. This commit relaxes the check from `assertEqual` to `assertGreaterEqual`, allowing the test to pass when additional entries are observed.
----
- Related to https://github.com/openthread/openthread/issues/10568
> [test] relax checks in `test_publish_meshcop_service`

- src/core/common/num_utils.hpp
- src/core/common/serial_number.hpp
- src/core/common/tlvs.hpp
- src/core/common/type_traits.hpp
- src/core/net/dns_types.hpp
- src/core/net/mdns.cpp
This commit adds `TypeTraits::IsUint<Type>` and `IsInt<Type>` to determine (at compile time) whether a given `Type` is an unsigned or signed integer type (8, 16, 32, or 64 bit length). These help simplify `static_assert()` checks in template methods that work with integer types.
> [type-traits] add `IsUint<Type>` and `IsInt<Type>`

- tools/cp-caps/README.md
Added comprehensive Python virtual environment setup guide to the cp-caps README.md file.
This includes detailed sections for creation,activation, dependency installation, and deactivation of virtual environments to help users properly set up their testing environment and avoid package conflicts.
> [docs] add guide on using python venv for cp-caps test

- tests/nexus/CMakeLists.txt
- tests/nexus/platform/nexus_core.cpp
- tests/nexus/platform/nexus_mdns.cpp
- tests/nexus/platform/nexus_mdns.hpp
- tests/nexus/platform/nexus_misc.cpp
- tests/nexus/platform/nexus_node.hpp
- tests/nexus/test_border_agent.cpp
This commit updates `Nexus` simulation platform to implement and emulate `otPlatMdns` APIs. This allows Nexus test cases to be written which require and use the OpenThread's native mDNS.
This commit also enhances `test_border_agent` to validate that the Border Agent's registered `_meshcop._udp` can be queried and resolved (using mDNS) from other devices.
> [nexus] add support for `otPlatMdns` APIs simulation

- src/core/net/dhcp6_client.cpp
- src/core/net/dhcp6_client.hpp
This commit removes an undefined method declaration in `Dhcp6::Client` and inlines a simple method used for prefix checks.
> [dhcp6-client] remove undefined method declaration

- src/core/radio/trel_interface.cpp
- src/core/radio/trel_interface.hpp
- src/core/radio/trel_link.hpp
This commit modifies the TREL module to explicitly request TREL acknowledgements for broadcast transmissions directed to known neighbors. This ensures quicker discovery of when a TREL peer is no longer available.
> [trel] explicitly request trel ack for broadcast tx to known neighbors

- src/core/net/dhcp6.hpp
- src/core/net/dhcp6_client.cpp
- src/core/net/dhcp6_client.hpp
- src/core/net/dhcp6_server.cpp
- src/core/net/dhcp6_server.hpp
This commit contains style fixes and smaller enhancements in DHCP6-related definitions and types. Mainly, the DHCP6 `Option` sub-classes are renamed to include the `Option` suffix (e.g., `IaAddressOption`), harmonizing the naming style with `Tlv` and other `Option` classes (e.g., `Nd6` or `Dns` options).
> [dhcp6] style fixes and minor enhancements

- src/posix/platform/config_file.cpp
- src/posix/platform/config_file.hpp
- src/posix/platform/configuration.cpp
- src/posix/platform/configuration.hpp
- src/posix/platform/radio.cpp
- src/posix/platform/radio_url.cpp
This commit enhances the POSIX platform configuration system to support
dynamic configuration file paths at runtime instead of only build-time paths.
ConfigFile class:
- Replace const char* mFilePath with char mFilePath[kFilePathMaxSize] to allow
dynamic path updates after construction
- Add SetFilePath() and GetFilePath() methods
- Update constructor to use SetFilePath() with proper bounds checking
Configuration class:
- Add SetFactoryConfigFile() and SetProductConfigFile() methods to update
factory and product config file paths
Radio URL parameter support:
- Add support for 'product-config-file' parameter in radio URL
- Add support for 'factory-config-file' parameter in radio URL
> [posix] add runtime configuration file path support

- src/core/backbone_router/bbr_leader.cpp
- src/core/backbone_router/bbr_leader.hpp
- src/core/common/notifier.cpp
- src/core/net/dhcp6_client.cpp
- src/core/net/dhcp6_client.hpp
- src/core/net/dhcp6_server.cpp
- src/core/net/dhcp6_server.hpp
- src/core/net/nd_agent.cpp
- src/core/net/nd_agent.hpp
- src/core/thread/mle.cpp
This commit updates the `Notifier` to directly signal events to `BackboneRouter::Leader`, `Dhcp6::Server`, `Dhcp6::Client`, and `NeighborDiscovery::Agent`. These classes were previously notified indirectly through `Mle::HandleNotifierEvent()`.
> [notifier] streamline event delivery to core modules

- src/core/common/message.hpp
This commit adds destructors for `MessageQueue` and `PriorityQueue`. This ensures that allocated `Message` instances in different queues are freed when the `ot::Instance` is destroyed.
> [message] add destructors for `MessageQueue` and `PriorityQueue`

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit simplifies the processing of PD prefixes provided by the platform to `PdPrefixManager`. The platform can report DHCPv6 PD prefixes in two ways: through a Router Advertisement (RA) message containing Prefix Information Options (PIOs) or by providing a PD prefix directly.
Previously, these two paths were processed in a single method, which made the code harder to read and follow. This commit refactors the logic to separate these two paths while using common helper methods.
This change introduces `EvaluateCandidatePrefix()`, which evaluates a single candidate prefix and tracks the most favored one. After all candidates are evaluated, `ApplyFavoredPrefix()` is called to apply the most favored prefix and update the current PD prefix if necessary.
> [routing-manager] simplify PD prefix processing

- src/posix/platform/resolver.cpp
The log message "No domain name servers found in %s, default to 127.0.0.1" is misleading because the code does not actually default to 127.0.0.1 if no nameservers are found. 
This commit updates the log message to accurately reflect the behavior.
> [posix] fix misleading log message in DNS resolver

- src/core/net/tcp6.cpp
- src/posix/platform/udp.cpp
This aims to fix some instances in core/tcp6 and posix/udp where the complete struct was not initialized. In otPlatUdpJoinMulticastGroup and otPlatUdpLeaveMulticastGroup an explicit redundant setting to '0' is added just for clarity for people reading the code.
> [tcp][posix] ensure struct fields are initialized

- examples/platforms/simulation/simul_utils.h
- src/posix/platform/udp.cpp
This will avoid the problem that scope id or ifindex remains 0 for a link-local transmission. If 0, the OS cannot decide which network interface to use based on address alone.
> [posix] set sin6_scope_id / ipi6_ifindex for all transmits to link-local

- src/core/coap/coap.cpp
Update coap message response matching according to CoAP [RFC 7252 - 8.2. Request/Response Layer](https://www.rfc-editor.org/rfc/rfc7252#section-8.2) resolving #11570.
I am not sure if anycast should also behave accordingly, currently expanded to anycast address aswell.
> [coap] match only token for multicast and anycast (#11570)

- src/posix/platform/radio.cpp
Fix the initialization order in ProcessRadioUrl() to ensure that configuration files are loaded before region settings are applied.
Previously, the region code was set before configuration files (product-config-file and factory-config-file) were processed. This caused region-specific settings such as target power to be applied from stale configuration data rather than the newly loaded configuration file.
The fix reorders the parameter processing sequence:
1. Basic radio parameters (fem-lnagain, cca-threshold)
2. Configuration file loading (product-config-file, factory-config-file)
3. Region setting (region)
4. Other parameters (bus-latency, max-power-table, coex settings)
This ensures that when a region is set, it will use the correct configuration data from the newly loaded files, …
> [posix] fix region configuration loading order

- src/posix/platform/mdns_socket.cpp
This commit updates how `MdnsSocket::SendQueuedMessages()` iterates over the message queue. The iteration is changed to get the next message before processing the current one. This is necessary because the current message may be dequeued and freed within the loop, which would invalidate the pointer to the next message.
> [posix] fix `MdnsSocket` iteration over message queue

- src/core/radio/trel_peer.cpp
According to precedents in other parts of the OpenThread source code, a 32-bit unsigned integer should be printed using `%lu` instead of `%u`.
> [trel] fix a format error of log

- src/core/border_router/routing_manager.cpp
There were duplicate logging lines for the received RA header.
```
otbr-agent[458170]: 00:00:35.453 [I] RoutingManager: - RA Header - flags - M:1 O:1 S:0
otbr-agent[458170]: 00:00:35.453 [I] RoutingManager: - RA Header - default route - lifetime:1800                                    
otbr-agent[458170]: 00:00:35.453 [I] RoutingManager: - RA Header - default route - lifetime:1800
otbr-agent[458170]: 00:00:35.453 [I] RoutingManager: - PIO 2001:db8:9:2::/64 (valid:5943, preferred:3943)
otbr-agent[458170]: 00:00:35.453 [I] RoutingManager: - RDNSS 2001:db8:9:2:0:0:0:1 (lifetime:1800)           
otbr-agent[458170]: 00:00:35.453 [I] P-Resolver----: Set recursive DNS server list, count: 1
```
> [routing-manager] remove duplicate logging of RA header

- src/core/common/locator.hpp
- src/core/common/message.cpp
- src/core/common/message.hpp
This commit simplifies the `Message::Metadata` so that it no longer tracks the `MessagePool`. Instead the `Message` now tracks the `ot::Instance` it is associated with and acts as a `GetProvider`, allowing access to any component within `Instance`, including the `MessagePool`.
> [message] remove `MessagePool` from the `Message::Metadata`

- tests/scripts/thread-cert/v1_2_test_backbone_router_service.py
This commit ensures `v1_2_test_backbone_router_service.py` uses the correct logic for checking the next seq number.
----
Resolves https://github.com/openthread/openthread/issues/11620
> [test] ensure `v1_2_test_backbone_router_service.py` uses correct seqno

- src/core/border_router/dhcp6_pd_client.cpp
- src/core/net/dhcp6_types.hpp
This commit updates `SendMessage()` to initialize the `msgType` variable before the `switch` statement.
This change addresses a compiler warning for a possibly uninitialized variable, flagged by `-Werror=maybe-uninitialized`.
Note that the situation where `mState` would be an undefined value is not technically possible in the current logic. However, the compiler cannot guarantee this and therefore generates a warning. Initializing the variable upfront resolves this issue.
----
This is an alternative fix from https://github.com/openthread/openthread/pull/11625. Thanks to @tanyanquan for reporting this.
> [dhcp6-pd-client] initialize `msgType` to fix compiler warning

- src/posix/platform/mdns_socket.hpp
This commit rearranges the method and member variable declarations in the `Posix::MdnsSocket` class to follow the recommended order, i.e., methods before member variables.
> [posix] reorder declarations in `MdnsSocket`

- src/cli/README_NETDATA.md
This commit fixes formatting issues in the netdata CLI README files to improve clarity and correctness of the documentation.
The changes include:
- Adding the '>' prompt character to CLI command examples where it was missing.
- Specifying 'bash' as the language for code blocks to enable proper syntax highlighting.
- Remove an extra colon
> [cli] fix command format in netdata README

- src/posix/platform/mdns_socket.cpp
- src/posix/platform/mdns_socket.hpp
- src/posix/platform/openthread-posix-config.h
This commit introduces an initial implementation in `Posix::MdnsSocket` to monitor and report all IPv4 and IPv6 addresses assigned to the infrastructure network interface. This mechanism is used by OpenThread's native mDNS module and was added in PRs #11353 and #11394.
A new configuration, `OPENTHREAD_POSIX_CONFIG_MDNS_ADDR_MONITOR`, is added to select the monitoring strategy. This commit implements the `OT_POSIX_MDNS_ADDR_MONITOR_PERIODIC` approach, where `getifaddrs()`
is used to enumerate addresses periodically. The polling interval is configured by  `OPENTHREAD_POSIX_CONFIG_MDNS_ADDR_MONITOR_PERIOD`.
Note that the OpenThread mDNS module itself tracks the list of reported addresses and will only take action when there is a change from what was previously announced. This allows the …
> [posix] implement address monitoring in `MdnsSocket`

- src/posix/platform/alarm.cpp
- src/posix/platform/daemon.cpp
- src/posix/platform/daemon.hpp
- src/posix/platform/infra_if.cpp
- src/posix/platform/infra_if.hpp
- src/posix/platform/mainloop.cpp
- src/posix/platform/mainloop.hpp
- src/posix/platform/mdns_socket.cpp
- src/posix/platform/mdns_socket.hpp
- src/posix/platform/multicast_routing.cpp
- src/posix/platform/multicast_routing.hpp
- src/posix/platform/netif.cpp
- src/posix/platform/resolver.cpp
- src/posix/platform/resolver.hpp
- src/posix/platform/trel.cpp
- src/posix/platform/udp.cpp
- src/posix/platform/udp.hpp
- src/posix/platform/virtual_time.cpp
This commit adds new helper methods to `Mainloop::Source` that allow a source to update the `Mainloop::Context`. These helpers can be used to update or check the read/write/error `fd_set` (file-descriptor sets) or the timeout value in the context.
> [posix] add helpers in `Mainloop::Source` to update `Context`

- src/core/thread/mle.cpp
This commit updates `Mle` to ensure that a device ignores a received "Child Update Request" message if it is currently detached. This prevents the device from sending a "Child Update Response" in this state. This behavior is particularly important when a device is trying to restore its previous role as a router or leader.
----
Thanks to @trebbert-lutron for finding this issue.
> [mle] ignore Child Update Request when detached

- src/posix/platform/alarm.cpp
The definition of sMicroTimer and sRealTimeSignal are wrapped by the `__linux__`, `OPENTHREAD_CONFIG_PLATFORM_USEC_TIMER_ENABLE` and `!OPENTHREAD_POSIX_VIRTUAL_TIME`. But the code using these two variables is not completely wrapped by these three macros. It causes the compile errors in some conditions.
This commit wraps all the code that uses these two variables with these three macros.
> [posix] fix the compile errors of src/posix/platform/alarm.cpp

- src/core/border_router/routing_manager.cpp
Previously we were relying on the platform to call `otPlatInfraIfDiscoverNat64PrefixDone` to trigger the evaluation of NAT64 prefix. Since https://github.com/openthread/openthread/pull/11481, we're no longer doing proactive DNS-based prefix discoveries and it never calls the callback `otPlatInfraIfDiscoverNat64PrefixDone`. 
That means NAT64 evaluation can only happen when `RoutingManager::EvaluateRoutingPolicy` is triggered, which can cause a at most 3-minute delay (`kRaBeaconInterval`), between enabling NAT64 feature and the feature starts to work.
This PR triggers the evaluation of routing policy when `Nat64PrefixManager::Discover()` fails to ensure the feature starts to work on time.
> [nat64] schedule evaluation of policy when `Nat64PrefixManager::Discover()` fails

- tests/nexus/platform/nexus_alarm.hpp
- tests/nexus/platform/nexus_node.hpp
- tests/nexus/platform/nexus_radio.cpp
- tests/nexus/platform/nexus_radio.hpp
This commit updates the `Nexus::Node` to initialize platform-specific components first. This is achieved by defining them in a `Platform` struct, which is inherited before `ot::Instance`.
This change ensures all platform components are ready and can be safely used from the `Instance` constructor and any of its sub-components.
> [nexus] ensure platform components are initialized first

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_ftd.cpp
This commit introduces `Mle::RetxTracker`, a new nested class that encapsulates the state and logic for managing MLE message retransmissions. It specifically handles Child Update and Data Request messages sent from a child to its parent, as well as the periodic keep-alive Child Update from an rx-on-when-idle child. This change centralizes all retransmission logic within `RetxTracker`, replacing direct state manipulation and leading to a cleaner, more modular design.
This change also includes the following improvements and fixes:
* The retransmission timeout (`kUnicastRetxDelay`) now includes a small random jitter.
* Fixes the logic for tracking the number of transmission attempts, ensuring the child detaches after `kMaxAttempts` (4) are reached. The previous code would incorrectly try one …
> [mle] introduce `RetxTracker` to manage retransmissions

- include/openthread/border_routing.h
- include/openthread/instance.h
- src/cli/README_BR.md
- src/cli/cli_br.cpp
- src/core/api/border_routing_api.cpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit introduces `otBorderRoutingGetInfraIfInfo()` to get the interface index and running state of the configured infrastructure interface. A corresponding CLI command is also added to retrieve this information.
> [routing-manager] new API to get infrastructure interface info

- src/core/thread/energy_scan_server.cpp
- src/core/thread/energy_scan_server.hpp
This commit updates the `EnergyScanServer` to use an `OwnedPtr<>` for its `mReportMessage` member.
This change ensures that the allocated report message is correctly freed when the `otInstance` is destroyed, preventing a potential memory leak.
> [energy-scan-server] use `OwnedPtr` to prevent memory leak

- src/lib/spinel/radio_spinel_metrics.h
- src/lib/spinel/spinel_encrypter.hpp
- Include `stdint.h` for `*int*_t` types. 
- Include `stddef.h` for `size_t` type.
> [build] include necessary headers in spinel

- src/core/net/srp_client.cpp
- src/core/net/srp_server.cpp
- src/core/thread/address_resolver.cpp
- src/core/thread/network_data.hpp
- src/core/thread/network_data_publisher.cpp
- src/core/thread/network_data_service.cpp
- src/core/thread/network_data_service.hpp
- tests/unit/test_network_data.cpp
This commit enhances the `NetworkData::Service::Iterator` class. The `Iterator` is now a separate class from `Service::Manager`. It provides `GetNextDnsSrpAnycastInfo()` & `GetNextDnsSrpUnicastInfo()` methods, simplifying the code for iterating over these service entries. The `Iterator` is also generalized to track a given `NetworkData` instance, allowing it to iterate over service entries on any `NetworkData` object, not just the Leader's.
> [netdata] enhance `NetworkData::Service::Iterator`

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
This commit refactors `Mle::Start()` by moving the logic for restoring the previous role into a new method, `RestorePrevRole()`.
This change simplifies the startup process and improves robustness by adding more validation checks within `RestorePrevRole()`. The new method ensures that the previously saved state information is consistent before it is applied. For example, it verifies that `mLastSavedRole` matches the saved RLOC16 and that parent information is valid if the saved role was Child. These checks protect against loading invalid settings and allow the device to start more quickly by ignoring inconsistent state.
> [mle] enhance role restoration logic in `Start()`

- examples/platforms/simulation/radio.c
- include/openthread/instance.h
- include/openthread/platform/radio.h
- src/core/diags/factory_diags.cpp
- src/core/radio/radio.hpp
- src/core/radio/radio_platform.cpp
- src/lib/spinel/radio_spinel.cpp
- src/lib/spinel/radio_spinel.hpp
- src/posix/platform/radio.cpp
The radio platform API otPlatDiagRadioTransmitDone() and otPlatDiagRadioReceiveDone() are the same with the API otPlatRadioTxDone() and otPlatRadioReceiveDone(). This commit removes the API otPlatDiagRadioTransmitDone() and otPlatDiagRadioReceiveDone() to let the MAC layer and the diag module to use the same radio API to send and receive 154 frames. So that the diag module could process the ACK frame in the future.
Depends-On: openthread/ot-nrf528xx#1072
> [diag] deprecate otPlatDiagRadioTransmitDone() and otPlatDiagRadioReceiveDone()

- src/core/diags/README.md
- src/core/diags/factory_diags.cpp
- src/core/diags/factory_diags.hpp
This change introduces a new "diag sweep" command that iterates over all channels and transmits a frame of a given length.
> [diag] add `diag sweep` command

- src/core/common/message.hpp
- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
This commit moves the `Message::Ownership` enum definition to the `Ip6` class. This enum is exclusively used by the `Ip6` class to determine whether to clone a message or take direct custody. This model is not intended for use by other components. `OwnerPtr<>` is the recommended approach for conveying ownership transfers.
> [ip6] move `Message::Ownership` enum to `Ip6` class

- src/core/instance/instance.cpp
This commit enhances the instance shutdown sequence by explicitly disabling the Border Agent in `Instance::Finalize()`.
Additionally, direct calls to the OpenThread C API, such as `otThreadSetEnabled()`, are replaced with their corresponding C++ method calls, like `Get<Mle::Mle>().Stop()`.
> [instance] improve shutdown sequence in `Instance::Finalize()`

- src/core/instance/instance.cpp
This commit removes the explicit call to disable the `BorderAgent` during instance finalization. This change prevents issues where the call may trigger platform interactions that can fail due to the platform layer being deinitialized before the `Finalize` is called.
> [instance] remove border agent disabling in `Finalize`

- tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py
- tests/scripts/thread-cert/node.py
The `test_publish_meshcop_service` is updated to explicitly disable the border agent before stopping the `otbr-service`. This makes the test more reliable by ensuring the MeshCoP service is unpublished before stopping `otbr-service`.
> [tests] explicitly enable/disable border agent in `test_publish_meshcop_service`

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_ftd.cpp
This commit changes the `aDelay` parameter type in `Mle::DelayedSender` methods from `uint16_t` to `uint32_t`.
This update supports specifying message transmission delays longer than the previous 65-second limit and avoids potential implicit integer downcasting.
> [mle] use `uint32_t` for delay parameter in `DelayedSender`

- src/core/border_router/dhcp6_pd_client.cpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- src/core/common/num_utils.hpp
- src/core/diags/factory_diags.cpp
- src/core/diags/factory_diags.hpp
- src/core/ftd.cmake
- src/core/meshcop/meshcop_tlvs.hpp
- src/core/mtd.cmake
- src/core/net/dhcp6_types.hpp
- src/core/net/dns_client.cpp
- src/core/net/dns_types.cpp
- src/core/net/dns_types.hpp
- src/core/net/ip4_types.hpp
- src/core/net/ip6.hpp
- src/core/net/mdns.cpp
- src/core/net/mdns.hpp
- src/core/net/nd6.hpp
- src/core/radio.cmake
- src/core/radio/trel_interface.cpp
- src/core/thread/network_diagnostic_tlvs.hpp
- tests/unit/test_routing_manager.cpp
This commit enables the `-Wimplicit-int-conversion` compiler flag for `ftd`, `mtd`, and `radio` builds to improve code quality by detecting potential data loss from implicit type conversions.
All resulting warnings have been addressed by either:
- Changing variable, parameter, or return types to ensure consistency and prevent overflows.
- Adding explicit `static_cast` where the type conversion is intended and safe.
> [core] fix implicit integer conversion warnings

- .github/workflows/size.yml
This commit changes the "post report" trigger event from `pull_request` to `pull_request_target` so to match the event type that triggers the `check-size` workflow.
> [check-size] use `pull_request_target` event to trigger post report

- src/core/net/ip6_filter.cpp
- src/core/net/ip6_filter.hpp
- src/core/thread/mesh_forwarder.cpp
This commit refactors the IPv6 filter by renaming `Filter::Accept()` to `Filter::Apply()` and changing its return type from `bool` to `Error`.
The new method now returns `kErrorNone` for an accepted message and `kErrorDrop` for a message that should be dropped. This change improves clarity and aligns the filter's logic with the common `SuccessOrExit` error handling pattern used throughout the codebase.
> [ip6] refactor `Filter::Accept` to `Filter::Apply` and return `Error`

- src/core/thread/mle.cpp
This commit adds a check in `RetxTracker::ScheduleTimer()` to ensure the timer is not scheduled if MLE operations are disabled.
This change improves safety by handling an edge case during the graceful detach process. In this scenario, a child sends a "Child Update Request" with a zero timeout and, upon receiving a response, immediately stops MLE. The added check prevents the retransmission timer from being incorrectly scheduled after MLE has been stopped.
> [mle] avoid scheduling `RetxTracker` timer when disabled

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
This commit inlines `RequestShorterChildIdRequest()`  into its only call site within `HandleChildIdRequestTxDone()`.
> [mle] simplify requesting shorter Child ID Request msg

- .github/workflows/build.yml
- .github/workflows/otbr.yml
- .github/workflows/otns.yml
- .github/workflows/posix.yml
- .github/workflows/simulation-1.1.yml
- .github/workflows/toranj.yml
- script/git-tool
This commit stops using GITHUB_TOKEN in git-tool for better security.
Depends-On: openthread/ot-nrf528xx#989
> [git-tool] do not use GITHUB_TOKEN

- .github/workflows/size.yml
The commit corrects the checkout ref to `pull/<number>/merge`, which is the ref after merging and should be used for size checking.
> [size-report] correct the checkout ref

- src/core/thread/mle.cpp
- src/core/thread/mle_ftd.cpp
This commit updates `RestorePrevRole()` to directly start the `RouterRoleRestorer` instead of calling `BecomeRouter()`.
Consequently, `BecomeRouter()` is simplified by removing the logic for handling the `kRoleDetached` state. The method now focuses on the child-to-router transition by sending an Address Solicit message, and its initial role validation is made more explicit.
This change ensures the logic for restoring a previous router/leader role is separate from the child-to-router transition logic.
> [mle] refactor previous router/leader role restoration

- src/core/radio/trel_interface.cpp
- src/core/radio/trel_link.cpp
- src/core/radio/trel_peer.cpp
- src/core/radio/trel_peer.hpp
- src/core/radio/trel_peer_discoverer.cpp
- src/core/radio/trel_peer_discoverer.hpp
- tests/nexus/test_trel.cpp
This commit modifies TREL to disregard mDNS (DNS-SD) service removal events when updating the peer table. Since mDNS peer removal signals can be unreliable, this change prevents such signals from causing a peer's removal. Instead, a peer entry is retained as long as TREL packets and acks are successfully exchanged, moving towards the goal of eliminating TREL's dependency on mDNS for peer discovery and tracking.
This commit also introduces a new mechanism to track the last interaction time with each peer. This information is used to evict the least recently used entry when the peer table gets full and to remove inactive peers after a long expiration period (7.5 min) passes.
The `test_trel` Nexus test is updated to validate these new behaviors.
----
Related to …
> [trel] ignore mDNS service removal for peer table update

- src/core/thread/mle.cpp
This commit moves the `Detacher::Detach()` method implementation to group it with other `Detacher` method definitions.
When the `Detacher` class was added in PR #11723, its methods were intentionally kept in their original locations to keep the `git diff` smaller and easier to review.
This is a pure code-move refactoring to improve code organization and has no functional changes.
> [mle] reorganize `Detacher` methods

- src/core/config/dns_client.h
This commit increases the default DNS response timeout config, `OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_RESPONSE_TIMEOUT`, to 7000 milliseconds.
The default value of 7000 is selected to be longer than the six-second wait time for queries resolved by the Discovery Proxy (per RFC 8766, Section 5.6, first bullet).
> [dns-client] increase default response timeout to 7 seconds

- include/openthread/history_tracker.h
- include/openthread/instance.h
- src/cli/README_HISTORY.md
- src/cli/cli_history.cpp
- src/cli/cli_history.hpp
- src/core/api/history_tracker_api.cpp
- src/core/config/history_tracker.h
- src/core/thread/network_data_service.cpp
- src/core/thread/network_data_service.hpp
- src/core/utils/history_tracker.cpp
- src/core/utils/history_tracker.hpp
This commit introduces a new feature in `HistoryTracker` to track Network Data DNS/SRP unicast/anycast address entries. This new functionality records when different Border Routers add or remove these entries in the Network Data. This change also introduces new public APIs and CLI command `history dnssrpaddr` to expose this information.
> [history-tracker] add Network Data DNS/SRP address entry tracking

- script/test
This PR removes the obsolete OT_NODE_TYPE in `script/test`.
The type `rcp-ncp` was meant to run nodes of NCP on posix. But we don't have NCP on posix anymore. So this can be removed.
> [test] remove the node type rcp-ncp

- src/core/thread/network_diagnostic_tlvs.hpp
The `kIndexMask` within `AnswerTlv` was incorrectly defined as `0x7f`, which only covers the lower 7 bits of the `mFlagsIndex` field. This would improperly truncate the message index value.
This change corrects the mask to `0x7fff`, which properly utilizes the lower 15 bits for the index, while the most significant bit remains reserved for the `kIsLastFlag`.
> [netdiag] fix incorrect bitmask for `AnswerTlv` index

- src/core/thread/child_table.cpp
- src/core/thread/child_table.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_ftd.cpp
This commit moves the child ID allocation logic from `Mle` to `ChildTable`.
A new `AllocateNewChildRloc16()` method is added to `ChildTable` to contain the allocation logic, and the `mNextChildId` counter is moved to `ChildTable`. `Mle` is updated to use this new method.
This refactoring improves code encapsulation by making the `ChildTable` responsible for managing all aspects of the children it contains, including ID allocation.
> [mle] move child ID allocation logic to `ChildTable`

- src/core/api/history_tracker_api.cpp
- src/core/common/notifier.cpp
- src/core/instance/instance.cpp
- src/core/instance/instance.hpp
- src/core/meshcop/border_agent.cpp
- src/core/net/netif.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle.cpp
- src/core/thread/neighbor_table.cpp
- src/core/thread/router_table.cpp
- src/core/utils/history_tracker.cpp
- src/core/utils/history_tracker.hpp
- tests/nexus/test_border_agent.cpp
This commit refactors `Utils::HistoryTracker` by moving it into its own dedicated `ot::HistoryTracker` namespace for better code organization.
The main implementation class is renamed from `HistoryTracker` to `Local`, making the new class `ot::HistoryTracker::Local`. This allows additional components (like server and client) to be defined within the `HistoryTracker` namespace.
Nested types, such as `Iterator`, are now direct members of the new `HistoryTracker` namespace.
> [history-tracker] move `HistoryTracker` to its own namespace

- include/openthread/instance.h
- include/openthread/mesh_diag.h
- src/cli/README.md
- src/cli/cli_mesh_diag.cpp
- src/core/api/mesh_diag_api.cpp
- src/core/utils/mesh_diag.cpp
- src/core/utils/mesh_diag.hpp
This change introduces new APIs to allow configuration of the response timeout for mesh diagnostic queries. A corresponding CLI command `meshdiag responsetimeout` is also added to get or set the timeout value.
When set, the new response timeout is used for subsequent queries and does not affect any that are ongoing. The timeout value is clamped between 50 milliseconds and 10 minutes to ensure it stays within a reasonable range.
> [mesh-diag] add API to configure response timeout

- src/core/config/logging.h
This commit includes `<openthread/platform/logging.h>` because it uses `OT_LOG_LEVEL_CRIT`.
> [config] include logging.h

- src/core/radio/trel_peer_discoverer.cpp
- src/core/radio/trel_peer_discoverer.hpp
This change fixes a potential use-after-free issue in the `PeerDiscoverer::HandleTxtResult()` method.
When processing a TXT record, the corresponding `Peer` object could be removed if it was identified as the device itself. However, a subsequent call to `UpdatePeerState()` would still use the dangling reference to the removed `Peer` object.
The fix merges the logic from the now-removed `ProcessPeerTxtData()` method directly into `HandleTxtResult()`. After a `Peer` is removed, the local `peer` pointer is set to `nullptr`, and the call to `UpdatePeerState()` is guarded by a null check to prevent using the invalid pointer.
----
Discovered by fuzzer -> https://github.com/openthread/openthread/actions/runs/16734588204/job/47370469916?pr=11779
> [trel] fix possible use-after-free in `HandleTxtResult()`

- src/core/api/backbone_router_ftd_api.cpp
- src/core/api/thread_ftd_api.cpp
- src/core/backbone_router/bbr_manager.cpp
- src/core/backbone_router/bbr_manager.hpp
- src/core/thread/dua_manager.cpp
- src/core/thread/dua_manager.hpp
- src/core/thread/mle.hpp
- src/core/thread/mle_ftd.cpp
- src/core/thread/mle_types.hpp
- src/core/thread/mlr_manager.cpp
- src/core/thread/mlr_types.hpp
- src/core/thread/network_data_notifier.cpp
- src/core/thread/thread_tlvs.hpp
The Status TLV is used in several TMF messages (Address Solicit, DUA Registration, MLR), and the meaning of its value is context-dependent.
This commit refactors the TLV definitions by moving the status enums from the generic `ThreadStatusTlv` class into the modules where they are used.
The main changes are:
- The Address Solicit status is split into two more specific enums:
- `RouterUpgradeReason` for Address Solicit requests.
- `AddrSolicitResponse` for Address Solicit responses.
- `MlrStatus` and `DuaStatus` enums are moved to `mlr` and `dua` modules respectively.
- `ThreadStatusTlv` is simplified to a `typedef`.
This change improves code clarity, modularity, and type safety by ensuring that status codes are defined and used within their proper context.
> [mle] simplify `ThreadStatusTlv` handling

- src/core/radio/trel_peer_discoverer.cpp
When using `OPENTHREAD_CONFIG_TREL_MANAGE_DNSSD_ENABLE` the TREL peer discovery platform code is not needed anymore.
Added `otPlatTrelNotifyPeerSocketAddressDifference` under the same logic as the rest of the TREL platform API that is not used when `OPENTHREAD_CONFIG_TREL_MANAGE_DNSSD_ENABLE` is true.
> [trel] fix compilation issue when `otPlatTrelNotifyPeerSocketAddressDifference` is undefined

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This change enhances the favored on-link prefix selection logic within the `RoutingManager::OnLinkPrefixManager`.
It introduces two new prefix state variables:
- `mAilPrefix`: Tracks the on-link prefix discovered from Router Advertisements received on the Adjacent Infrastructure Link (AIL). This renames the previous `mFavoredDiscoveredPrefix`.
- `mFavoredPrefix`: Tracks the final selected favored prefix, which can be either the local prefix or the `mAilPrefix`.
The setters `SetAilPrefix()` and `SetFavoredPrefix()` are added to manage these state changes and provide additional logging.
> [routing-manager] update tracking of favored on-link prefix

- src/cli/README.md
- src/cli/README_MDNS.md
Adds a new `README_MDNS.md` file to provide a comprehensive guide for the `mdns` CLI command. The guide includes:
- A quick start section with examples.
- A full list of all available sub-commands.
- Detailed explanation and usage examples for each sub-command.
> [cli] add `mdns` command guide

- src/core/thread/network_data_service.cpp
- src/core/thread/network_data_service.hpp
This commit reorders method implementations in the source file `network_data_service.cpp` to group them within their respective `Iterator` and `Manager` class sections.
In PR #11680, the `Iterator` class was enhanced to be a separate class from `Manager`. The method definitions in the `.cpp` file were kept in their original order at that time to simplify the review by keeping the `git diff` smaller.
Separator comments are also added to both the `.cpp` and `.hpp` files to improve code structure and readability.
No functional changes are introduced.
> [netdata] reorder methods under `NetworkData::Service`

- src/cli/README_MDNS.md
This commit adds documentation for the new `mdns verboselogging` CLI command.
> [cli] document mdns `verboselogging` command

- src/core/common/message.cpp
- src/core/common/num_utils.hpp
- tests/unit/test_serial_number.cpp
This commit adds checks to prevent potential integer overflow issues within the `Message` class.
Previously, calculations involving message offset and length, such as `offset + length`, assumed the caller would provide values within a safe range. However, in some edge cases where larger values are given, this addition could wrap around. This could lead to incorrect behavior, potential memory corruption, or assertion failures.
To address this, this change introduces a new generic utility function, `CanAddSafely()`, to detect unsigned integer addition overflows. This check is now applied in the following `Message` methods to validate lengths and offsets before performing arithmetic:
- `AppendBytes()`: Returns an error if `offset + length` overflows.
- `AppendBytesFromMessage()`: Returns an …
> [message] check for potential integer overflows

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_ftd.cpp
This commit introduces a new `Mle::Attacher` class to encapsulate all logic and state related to the device attach process.
This change moves the attach state machine, parent candidate management, attach timer, and message handling for Parent Request, Parent Response, Child ID Request, and Child ID Response from `Mle` into the new nested `Attacher` class.
This refactoring improves code organization and modularity by separating the attach logic from the main `Mle` class.
---
This is resubmission of https://github.com/openthread/openthread/pull/11831.
> [mle] introduce `Attacher` class

- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This commit introduces `Publish()` and `Unpublish()` private helper methods in `Nat64PrefixManager` to encapsulate and centralize the logic for managing the published NAT64 prefix in the Network Data.
- `Publish(aPrefix, aPreference)` adds the given prefix to the Network Data. It handles removing any previously published prefix if the new prefix or preference differs.
- `Unpublish()` removes the currently published NAT64 prefix from the Network Data, if one exists.
These new helpers simplify the logic within the `Evaluate()` and `Stop()` methods, reduce code duplication, and improve overall clarity.
> [routing-manager] add `Publish()`/`Unpublish()` in `Nat64PrefixManager`

- src/core/net/dhcp6_server.cpp
- src/core/net/dhcp6_server.hpp
- src/core/net/nd_agent.cpp
- src/core/thread/dua_manager.cpp
- src/core/thread/lowpan.cpp
- src/core/thread/lowpan.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle_ftd.cpp
- src/core/thread/network_data_leader.cpp
- src/core/thread/network_data_leader.hpp
- src/core/utils/slaac_address.cpp
- tests/unit/test_lowpan.hpp
This commit enhances the `FindContext()` methods and converts the `Lowpan::Context` struct into a class.
The `FindContext()` methods are updated as follows:
- Renamed to `FindContextForAddress()` and `FindContextForId()` to more accurately reflect their function.
- The return type is changed from `Error` to `void`. Success is now indicated by checking the `IsValid()` state of the output `Context` object (matching how `Lowpan` class uses the `Context`). This change simplifies the callers and harmonizes the context check across different modules.
The `Lowpan::Context` struct is converted into a class, encapsulating its members by making them private and introducing public getters.
> [netdata] enhance `FindContext()` methods and `Lowpan::Context`

- src/core/thread/mle.cpp
This commit improves the organization of `mle.cpp` by grouping all `Attacher` method definitions together.
When the `Attacher` class was introduced in #11835, its method definitions were intentionally kept in their previous order to minimize the `git diff` for easier review. This resulted in the `Attacher` methods being interleaved with other `Mle` methods.
This commit acts as a follow-up to rearrange the file and group all `Attacher` methods into a dedicated section for better readability and organization.
No logic changes are included in this commit.
> [mle] group `Attacher` method definitions in `mle.cpp`

- src/core/net/nat64_translator.cpp
- src/core/net/nat64_translator.hpp
This commit updates the `Translator` class to improve code style, readability, and consistency with the OpenThread coding conventions. This is a pure refactoring commit with no intended logic changes. Key changes include:
- Renamed types and variables for brevity (e.g., `AddressMapping` to `Mapping`).
- Renamed members within the `Mapping` struct for clarity(e.g., `mIp4` to `mIp4Address`).
- Standardized local variable names (e.g., `err` to `error`).
- Added `const` to methods that do not modify the class state.
- Improved and reformatted Doxygen and inline comments.
> [nat64-translator] enhance and harmonize code style

- src/core/net/nat64_translator.cpp
- src/core/net/nat64_translator.hpp
This commit introduces two new `static` helper methods, `GetSourcePortOrIcmp6Id()` and `GetDestinationPortOrIcmp4Id()`, to the `Translator` class. This eliminates repeated similar code and improves overall readability.
> [nat64] introduce helpers for getting port or ICMP ID

- src/core/api/nat64_api.cpp
- src/core/net/nat64_translator.cpp
- src/core/net/nat64_translator.hpp
This commit simplifies and enhances the NAT64 translator's counter implementation.
- The `mProtocolCounters` and `mErrorCounters` are explicitly cleared in the `Translator` constructor, ensuring they are properly zero-initialized.
- The `ErrorCounters` C++ wrapper class is removed, and the counters are now updated directly based on `DropReason`.
- The `ProtocolCounters::Count*Packet()` methods are updated to accept `Ip6::Headers` and `Ip4::Headers` inputs directly, which simplifies the call sites.
- Private helper methods, `Update6To4()` and `Update4To6()`, are introduced in `ProtocolCounters` to reduce code duplication when incrementing packet and byte counts.
> [nat64] simplify and enhance handling of counters

- tests/unit/test_mdns.cpp
This commit adds a test case to `TestMultiPacket` to validate the correct eviction of pending truncated queries.
The test scenario sends the same truncated query multiple times, followed by a query containing a matching known answer. It then verifies that no response is sent, confirming that the initial pending queries were successfully evicted from the message queue. This validates the fix from #11854.
> [mdns] add test for truncated query eviction

- include/openthread/history_tracker.h
- include/openthread/instance.h
- src/cli/README_HISTORY.md
- src/cli/cli_br.cpp
- src/cli/cli_br.hpp
- src/cli/cli_history.cpp
- src/core/api/history_tracker_api.cpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- src/core/config/history_tracker.h
- src/core/utils/history_tracker.cpp
- src/core/utils/history_tracker.hpp
This change introduces a new history list to record the DHCPv6 Prefix Delegation (PD) state and the delegated prefix.
The recorded history can be iterated using the new API `otHistoryTrackerIterateDhcp6PdHistory()` and viewed from the CLI using the new `history dhcp6pd` command.
> [history-tracker] add DHCPv6 PD state and prefix history

- src/core/net/ip4_types.cpp
- src/core/net/ip4_types.hpp
- tests/unit/test_ip4_header.cpp
This commit introduces several cleanups and smaller improvements to the IPv4 types.
- Optimizes `Cidr::ToString(StringWriter&)` by writing the address directly to the provided writer, avoiding the allocation of a temporary `String` object.
- Moves the IPv4 header field offset constants from the public `ip4_types.hpp` header into the unit test file, as this was their only place of use. This cleans up the `Ip4::Header` public API.
- Replaces hardcoded values for address and string sizes with the corresponding `OT_IP4_*` definitions for consistency.
- Corrects the format specifier in `Address::ToString()` from `%d` to `%u` to properly print unsigned octet values.
> [ipv4] smaller improvements in `Address`, `Cidr`, and `Header`

- src/core/net/nat64_translator.cpp
- src/core/net/nat64_translator.hpp
This change streamlines NAT64 mapping management by removing the `FindMapping()` and `FindOrAllocateMapping()` helper methods.
Following recent simplifications, such as adding new `Matches()` flavors, the logic within these `Find` methods became much simpler. Their functionality is now incorporated directly into `TranslateToIp6()` and `TranslateFromIp6()`, respectively.
Additionally, the `Mapping::Touch()` method is simplified to no longer require the current time as an argument. It now retrieves the time internally.
> [nat64] simplify mapping lookup and `Touch()` method

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
This change introduces `ShouldRegisterMulticastAddrsWithParent()` to consolidate the logic for determining when a child should register its multicast addresses with its parent, thereby avoiding repeated code.
The criteria for registration remain the same: a child registers its multicast addresses if it is a Sleepy End Device (SED), or if it is a Minimal End Device (MED) and its parent is running Thread 1.2 or a later version.
> [mle] simplify logic for multicast address registration

- src/core/thread/dua_manager.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mlr_manager.cpp
- src/core/thread/neighbor_table.cpp
This change updates multiple modules to consistently use `Get<Mle::Mle>()` for accessing the MLE component, removing the need for local `Mle::Mle &mle` references.
This approach aligns with the common `Get<Module>()` access pattern used across the codebase, improving consistency.
> [core] harmonize access to MLE component using `Get<Mle::Mle>()`

- src/core/net/ip4_types.hpp
The `Cidr` class was incorrectly inheriting from `Clearable<Address>` instead of `Clearable<Cidr>`. This oversight meant that calling `Clear()` on a `Cidr` object would not clear its `mLength` member, only the `mAddress` field. This change corrects the template parameter for the `Clearable` base class to `Cidr`, ensuring the entire object is properly zeroed out.
This bug could cause issues in the NAT64 translator. When a user calls `otNat64ClearIp4Cidr()` to disable translation, the underlying `mIp4Cidr.Clear()` method would fail to clear the CIDR length. The `Nat64::Translator` would check `mIp4Cidr.mLength > 0` in its `UpdateState()` method to determine if a valid CIDR is configured. Because `mLength` was not cleared, this check would pass incorrectly, causing NAT64 translation to …
> [ipv4] fix `Cidr::Clear()`

- src/core/net/nat64_translator.hpp
- tests/unit/test_nat64.cpp
This change enhances the unit tests for the NAT64 `Translator` to improve readability. The key improvements include:
- Replaced raw hex dumps of packets with new helper functions that parse and log IPv4/IPv6 headers in a human-readable format.
- Simplified the counter tests and validation of the `ProtocolCounters`.
- Reworked the main test case functions, `Verify6To4()` and `Verify4To6()`, to leverage the new logging and verification
helpers for better output.
> [nat64] improve unit tests for `Nat64::Translator`

- include/openthread/coap.h
- include/openthread/instance.h
- src/core/api/coap_api.cpp
- src/core/coap/coap.cpp
- src/core/coap/coap.hpp
- src/core/coap/coap_message.hpp
adding two extensions:
1. Add an api function to configure a response fallback callback with `otCoapSetResponseFallback`.
2. Enable fire and forget for NON requests, supporting requests which do not expect a response.
This PR is related and resolves #11582 as described in option 1 in the proposed solutions.
> [coap] add `otCoapSetResponseFallback` to process unmatched responses

- src/core/net/nat64_translator.cpp
- src/core/net/nat64_translator.hpp
This change updates the management of active NAT64 mappings to use an `OwningList`.
To support this, the `Mapping` struct now inherits from `InstanceLocatorInit` and includes a new `Free()` method. This method encapsulates the logic for releasing the associated IPv4 address and the `Mapping` entry back to their corresponding pools.
This new design simplifies the `Translator` class by removing the redundant `ReleaseMapping()`, `ReleaseMappings()`, and `ReleaseExpiredMappings()` methods. All mapping cleanup operations are now handled by the `OwningList` class (which invokes `Mapping::Free()` on entries as they are removed).
> [nat64] use `OwningList` to manage active mappings

- src/core/common/message.hpp
- src/core/meshcop/meshcop.cpp
- src/core/meshcop/tcat_agent.hpp
- tests/unit/test_checksum.cpp
- tests/unit/test_message.cpp
This commit moves two global constants, `kBufferSize` and `kNumBuffers`, into their respective class scopes to improve encapsulation and avoid potential name conflicts.
The `kBufferSize` constant is moved into the `Buffer` class as `Buffer::kSize`. As `kBufferSize` is a generic and commonly used name, this change prevents potential symbol collisions.
Similarly, the `kNumBuffers` constant is moved into the `MessagePool` class, as it is exclusively used within that class.
All usages of these constants have been updated throughout the codebase to reflect their new names.
> [message] improve scoping of `Buffer` constants

- src/core/net/nat64_translator.cpp
- tests/unit/test_nat64.cpp
This change adds an explicit check for `mState == kStateActive` at the beginning of the translation functions.
This single check replaces individual validations for a valid IPv4 CIDR and NAT64 prefix. This simplifies the entry logic and fixes a bug where the `Translator` could continue performing translations even after it was explicitly disabled via `SetEnabled(false)`.
Additionally, this change fixes a bug in `TranslateToIp6()` where an IPv4 message would be incorrectly marked as `kForward` when no IPv4 CIDR was configured (`mIp4Cidr.mLength == 0`). The correct behavior is to drop the packet, so the result is now set to `kDrop`.
> [nat64] ensure translator is active before translation

- src/core/thread/link_metrics_tlvs.hpp
Clang warns that mMetricsValue is less aligned that its union type. Make the union packed to fix this.
> [link-metrics] make union packed to fix warning

- src/core/common/linked_list.hpp
- src/core/net/ip4_types.hpp
- src/core/net/nat64_translator.cpp
- src/core/net/nat64_translator.hpp
- tests/nexus/test_nat64_translator.cpp
- tests/unit/test_linked_list.cpp
This change modifies the NAT64 translator to dynamically allocate IPv4 addresses by tracking a range of host IDs within the configured CIDR. This approach replaces the pre-allocated `mIp4AddressPool`, making it more memory-efficient by avoiding the storage of an entire address array.
The translator now maintains `mMinHostId` and `mMaxHostId` derived from the configured CIDR. When allocating an IPv4 address for a new mapping:
- If `PORT_TRANSLATION_ENABLE` is enabled, addresses are assigned sequentially by cycling through the host ID range. Mappings can share an IPv4 address as they are distinguished by translated port numbers.
- If `PORT_TRANSLATION_ENABLE` is disabled, a 1-to-1 address mapping is used. The translator cycles through host IDs to find an unused IPv4 address. If all …
> [nat64] use host ID tracking for IPv4 address allocation

- tests/toranj/cli/cli.py
This commit adds an environment for toranj script so that we can specify a default network key for local debugging.
> [toranj] support default network key for debug

- src/core/thread/indirect_sender.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/utils/history_tracker.cpp
- src/core/utils/history_tracker.hpp
The current history tracker only records direct transmissions, but indirect transmissions are also required for debugging. This PR adds support for tracking indirect transmissions.
> [history-tracker] enable tracking indirect tx

- src/core/thread/mle.cpp
Avoid overwriting parent candidate during child ID request phase.
Addresses issue here https://github.com/openthread/openthread/issues/11952
> [mle] avoid overwriting parent candidate during child ID request phase

- src/core/common/debug.hpp
- src/core/config/misc.h
This commit verifies NDEBUG is not defined when OT_ASSERT is enabled and is delegated to assert().
> [debug] check NDEBUG for OT_ASSERT

- src/cli/README.md
- src/cli/cli.cpp
- tests/scripts/expect/cli-neighbor.exp
This allows a node to asses its LinkQuality In to its neighbors. Similar to what is already available via router info. Useful when not all its neighbors are routers.
```
| Role | RLOC16 | Age | Avg RSSI | Last RSSI | LQ In |R|D|N| Extended MAC     | Version |
+------+--------+-----+----------+-----------+-------+-+-+-+------------------+---------+
|   R  | 0x2000 |   4 |      -68 |       -68 |     3 |1|1|1| fa97259e4eb574e4 |       5 | 
|   R  | 0xf000 |   0 |      -96 |       -97 |     1 |1|1|1| ba9fd148fba30fbd |       5 |
-----------------------------------------------^^^^^ added
```
> [cli] add LQ In to the neighbor table output

- src/core/border_router/br_tracker.cpp
- src/core/border_router/br_tracker.hpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This change moves the logic for iterating over the `NetDataPeerBrTracker` entries from `RoutingManager::RxRaTracker::Iterator` directly into the `NetDataPeerBrTracker::GetNext()` method.
This decouples the `NetDataPeerBrTracker` from the `RoutingManager`'s iterator implementation, allowing the removal of `RoutingManager` as a friend class of `NetDataPeerBrTracker`.
This commit also includes smaller enhancements and changes to the `RoutingManager::RxRaTracker::Iterator`:
- `Iterator::EntryType` is renamed to `PrefixType` for clarity.
- `Iterator::AdvanceToNextEntry()` is renamed to  `AdvanceToNextPrefixEntry()`.
> [br-tracker] move iteration logic out of `RoutingManager::Iterator`

- src/core/border_router/br_tracker.cpp
In `NetDataPeerBrTracker::CountPeerBrs()` method, the `aMinAge` output parameter is a `uint32_t` but it was incorrectly
initialized to `NumericLimits<uint16_t>::kMax`. 
This change corrects the initialization to use the `NumericLimits<uint32_t>::kMax` to ensure the minimum age calculation functions correctly over the full 32-bit range.
> [br-tracker] initialize `aMinAge` to `uint32_t::kMax`

- src/core/api/border_routing_api.cpp
- src/core/border_router/br_tracker.cpp
- src/core/border_router/br_tracker.hpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
- src/core/common/notifier.cpp
- src/core/instance/instance.cpp
- src/core/instance/instance.hpp
- tests/unit/test_dns_client.cpp
- tests/unit/test_routing_manager.cpp
This change enhances `NetDataBrTracker` to support filtering of Border Routers.
The `NetDataPeerBrTracker` is renamed to `NetDataBrTracker` to reflect that it can now track all Border Routers, not just peers.
A new `Filter` enum is introduced with `kAllBorderRouters` and `kExcludeThisDevice` options. This allows callers to specify whether to include the current device in the list of Border Routers.
The `CountPeerBrs()` and `GetNext()` methods are updated to `CountBrs()` and `GetNext()` respectively, and now accept a `Filter` parameter.
This change provides more flexibility to the `NetDataBrTracker` and makes the code more reusable. The unit tests are also updated to clean up resources to avoid heap allocation leaks at the end of tests.
> [br-tracker] enhance `NetDataBrTracker` to support filtering

- src/core/border_router/routing_manager.cpp
The PR removes the warn log when `DiscoverNat64Prefix` fails.
Note that `otPlatInfraIfDiscoverNat64Prefix` has an empty implementation now and it always returns UNIMPLEMENTED error. So now we constantly see the warn log on devices, which is confusing.
As I went through the previous [discussion](https://github.com/openthread/openthread/pull/11654#discussion_r2179211929), we are currently in a temporary state. Let's add the warn log back once the `otPlatInfraIfDiscoverNat64Prefix` is implemented again.
> [routing-manager] remove confusing log of nat64 prefix discovery

- src/posix/platform/spi_interface.cpp
For some products, `gpio-reset-device` is not needed in radio URL as the reset maybe management by other component in the system (e.g. by BT statck in some trinity chip). In this case, `gpio-reset-device` in the radio URL should not be given, and this is expected.
This pull request makes a minor logging change in the `SpiInterface::Init` method. The log level for the message indicating that `gpio-reset-device` is not provided has been changed from "Note" to "Info". 
* Changed log level from `LogNote` to `LogInfo` for the message about missing `gpio-reset-device` in `spi_interface.cpp`.
> [posix] use LogInfo if SPI reset device is not given

- src/core/border_router/routing_manager.hpp
make `RoutingManager::GetNextRdnssAddrEntry()` and `RoutingManager::GetNextIfAddrEntry()` const.
These methods are simple getters that do not modify the state of `RoutingManager` and call const methods on `mRxRaTracker`. This change makes them consistent with other similar getter methods in RoutingManager like `GetNextPrefixTableEntry()` and `GetNextRouterEntry()`.
> [routing-manager] make getter methods const

- include/openthread/instance.h
- src/core/api/instance_api.cpp
This commit adds a public getter function to acquire a pointer for an OpenThread instance associated with a provided index.
An index to instance reference getter function was previously implemented in the core instance interface, but this capability was not publicly accessible. The accessor function introduced in this commit will now allow for platforms or application code to perform this mapping.
> [instance] expose multi-instance getter as instance API

- src/core/meshcop/border_agent.cpp
- tests/nexus/test_border_agent.cpp
This change updates `BorderAgent::PrepareServiceTxtData()` to read the Network Name (`nn` key) and Extended PAN ID (`xp` key) from the Active Dataset, after verifying that the dataset is valid and has an active timestamp.
Previously, these values were read directly from `NetworkNameManager` and `ExtendedPanIdManager`, which could provide default or initial values (during stack initialization). Reading from the Active Dataset ensures that the advertised service TXT data is consistent with the dataset currently in use by the device.
The `ValidateMeshCoPTxtData()` test is updated to reflect this behavior.
> [border-agent] read NetName and XPanId from active dataset for TXT data

- tools/tcat_ble_client/bbtc.py
- tools/tcat_ble_client/ble/ble_stream.py
- tools/tcat_ble_client/ble/ble_stream_secure.py
- tools/tcat_ble_client/ble/udp_stream.py
- tools/tcat_ble_client/cli/cli.py
This PR provides more structured logging for ssl.py errors, and displays the OpenSSL verify error code. This is used for certification to validate reasons of handshake failure.
NOTE: the commit '[tcat] improved debug info format using hexadecimal + ASCII dump' is still included in this one - this comes from the other PR, #11881 .  That means the diff will not correctly show for this PR yet - will rebase once #11881 is merged.
> [tcat] improve TCAT Commissioner output logging for SSL errors

- include/openthread/ble_secure.h
- include/openthread/instance.h
- include/openthread/tcat.h
- src/cli/README_TCAT.md
- src/cli/cli_tcat.cpp
- src/core/api/ble_secure_api.cpp
- src/core/instance/instance.cpp
- src/core/instance/instance.hpp
- src/core/meshcop/tcat_agent.cpp
- src/core/meshcop/tcat_agent.hpp
- src/core/radio/ble_secure.cpp
- src/core/radio/ble_secure.hpp
- tests/scripts/expect/cli-tcat-advertisement.exp
- tests/unit/test_tcat.cpp
This adds a BLE 'non-advertising' state in which BLE is enabled for connections, but not advertising.
- If the TCAT agent is not started while BLE is started, BLE advertising will be enabled by default.
- If the TCAT agent is started, BLE advertising is under control of the TCAT agent - depending on state.
The TCAT agent, while started, can be now in standby mode or in active mode. In standby, it doesn't
advertise and doesn't allow incoming TCAT connections. In active mode, it allows both of these.
Timed activation of the active mode is also possible. CLI commands are added to test the new modes and
timed activation.
Existing architecture is not changed (BLE-Secure is in control and has all APIs to access TCAT agent).
It also fixes some (API) documentation and clarifies this where needed. …
> [ble][cli][tcat] add BLE 'non-advertising' state, TCAT active/standby states, timed activation, and some TCAT fixes

- src/core/BUILD.gn
- src/core/CMakeLists.txt
- src/core/border_router/br_log.cpp
- src/core/border_router/br_log.hpp
- src/core/border_router/routing_manager.cpp
- src/core/border_router/routing_manager.hpp
This change introduces new files `br_log.cpp` and `br_log.hpp` to house common logging helper functions for the border router modules.
Helper functions for logging Router Advertisement (RA) headers, Prefix Information Options (PIO), Route Information Options (RIO), and other related options are moved into this new module.
The log module name is also updated from `RoutingManager` to a more general `BorderRouting`.
This change improves code structure by decoupling logging functionalities from the `RoutingManager`.
> [border-router] introduce `br_log` for logging helpers

- tests/fuzz/cli.cpp
Increases the `nexus.AdvanceTime()` in the CLI fuzzer test from 10 to 60 seconds to make the test more robust.
For example, the previous 10-second wait was not sufficient for `Dns::Client` operations to complete, especially considering retries. This could cause false fuzzer memory leak reports.
> [fuzz] increase wait time in CLI fuzzer

- etc/cmake/options.cmake
host-RCP time sync interval is in configuration file. Added in cmake to use user defined RCP time sync internval during build.
> [cmake] added build command flag to set RCP time sync interval
