- include/platform/radio.h
This commit adds the requisite void to those API prototypes which take no arguments.
> Add void to API prototypes which take no arguments.

- examples/cli/main.cpp
- src/cli/cli_udp.cpp
1. fixed unused stack variable
2. cleaned the `memset`
> fix unused stack variable and code cleanup

- examples/cli/README.md
> Fix README to match CLI example output

- src/core/net/icmp6.cpp
- src/core/net/ip6.cpp
The caller should be responsible for freeing the message buffer.
Address the hang issue in #6 .
> Change SendDatagram to not free the message on error.

- src/cli/cli.cpp
> Adding argc checks to route and prefix to fix issue-4 and issue-7

- examples/platform/posix/radio.cpp
- include/openthread-types.h
- include/openthread.h
- src/cli/README.md
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/mac/mac_frame.cpp
- src/core/mac/mac_frame.hpp
- src/core/net/ip6_address.cpp
- src/core/openthread.cpp
- src/core/thread/address_resolver.cpp
- src/core/thread/mle.cpp
* Add active scan functions and definitions to core C api.
* Add active scan command to CLI.
* Add emulation of PHY channel isolation.
> Add active scan to API and CLI.

- examples/platform/posix/logging.c
- examples/platform/posix/serial.c
- src/cli/cli_serial.cpp
Various serial fixes from my own branch.
> For upstream/serial and logging fixes

- include/openthread.h
- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/openthread.cpp
Added a member function for determining if a scan is in progress.
> core: mac: Added new method: `Mac::IsActiveScanInProgress()`

- README.md
#23 requested language around logo use. Here it is!
> Adding language about logo

- Makefile.am
- configure.ac
- doc/Makefile.am
- examples/platform/Makefile.am
- examples/platform/posix/Makefile.am
- include/Makefile.am
- include/crypto/Makefile.am
- include/platform/Makefile.am
- src/cli/Makefile.am
- src/core/Makefile.am
- tests/Makefile.am
- tests/scripts/Makefile.am
- tests/unit/Makefile.am
- third_party/Makefile.am
* Include header files for distribution.
* Include tests scripts for distribution.
* Include docs for distribution.
> Fix 'make dist'.

- include/openthread.h
- src/core/thread/mesh_forwarder.cpp
- third_party/mbedtls/mbedcrypto.c
I discovered a few compile time issues while porting OT to a target platform.
> Resolve several compile warnings and errors.

- examples/platform/posix/radio.cpp
- include/platform/radio.h
- src/core/mac/mac.cpp
This is the new PR for the closed #33
> add otPlatRadioGetCaps method to check radio capabilities

- src/core/thread/network_data.cpp
- src/core/thread/network_data.hpp
- src/core/thread/network_data_leader.cpp
- src/core/thread/network_data_leader.hpp
change mVersion whenever NetworkData changes
change mStableVersion only when Stable NetworkData changes
@jwhui Please help to review, thanks!
> fix network data version and stable version issue

- include/openthread-types.h
- include/openthread.h
- src/core/openthread.cpp
> fix compilation issues

- src/core/common/timer.cpp
- src/core/common/timer.hpp
- tests/unit/Makefile.am
- tests/unit/test_timer.cpp
* Change timer logic to always fire the earliest Timer first.
* Fix issue with Setting an alarm for an already expired timer.
* Add unit tests for timer module.
> Timer logic improvements.

- src/core/thread/mle_router.cpp
correct link margin value issue for response to link request
append TLV request for LinkMargin in LinkAcceptAndRequest to adaptive for possible optional link margin in Link Accept implementation.
Hi @jwhui , please help to have a review, thanks.
> fix 3-handshakes link configuration issue

- examples/posix/app/cli/README.md
- src/cli/README.md
- src/cli/cli_serial.cpp
> Add simple command prompt '>'.

- src/core/openthread.cpp
fix ot udp socket api function name otSendUdp.
> fix otSendUdp function name

- include/platform/radio.h
> Update platform/radio.h doxygen to match implementation.

- examples/posix/platform/radio.c
This is a fix for #126.
* Only set Frame Pending in ACK in response to a Data Request message.
* Data Request sender uses the Frame Pending value in the ACK.
> Fix IEEE 802.15.4 Frame Pending handling.

- examples/posix/app/cli/README.md
> Fix relative link to src/cli/README.md.

- src/ncp/ncp.cpp
- src/ncp/ncp.hpp
> ncp: Remove unused mSendMessage from Ncp class.

- src/cli/README.md
- Minor grammatical updates, most capitalization
- Standardized on "OpenThread" for all instances of "Thread"
- Collected terms for a possible glossary - that's a separate discussion
> cli: Update README.md

- tests/unit/Makefile.am
- tests/unit/test_lowpan.cpp
- tests/unit/test_util.cpp
- tests/unit/test_util.h
- tests/unit/test_util.hpp
- tests/unit/test_vector.c
- tests/unit/test_vector.h
Added initial unit tests for 6LoWPAN layer decompression. 
Extended unit test framework with helper functions for setting up ASCI hex test vectors.
> test: Lowpan module unit tests

- src/ncp/PROTOCOL.md
*   Section 3.1: General clarification and rewording.
*   Section 4.6: Fixed a cut-and-paste typo. (#179)
*   Section 5: Added a sentence indicating that the encoding shorthand is described in section 7.1. (#179)
*   Appendix A: Clarified how HDLC-Lite works.
*   Appendix A: Added a section for SPI recomendations.
> ncp-spinel: Updates to `PROTOCOL.md`

- .travis.yml
- .travis/before_install.sh
- .travis/script.sh
> travis: add test for 32-bit target

- include/openthread.h
- src/core/net/icmp6.cpp
- src/core/net/icmp6.hpp
- src/core/openthread.cpp
- src/ncp/ncp_base.cpp
> Add ability to configure handling of ICMPv6 Echo Request/Reply messages.

- include/openthread-types.h
> Remove redefinition of OT_NETWORK_NAME_SIZE.

- examples/apps/cli/Makefile.am
- examples/apps/ncp/Makefile.am
- examples/platforms/cc2538/alarm.c
- examples/platforms/cc2538/radio.c
- examples/platforms/cc2538/random.c
- examples/platforms/cc2538/serial.c
> examples: fix cc2538 examples

- include/openthread-types.h
- include/openthread.h
- src/cli/README.md
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/openthread.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
> Add API to retrieve router diag information.

- include/openthread-types.h
- include/openthread.h
- src/cli/README.md
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/openthread.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
> Add API to retrieve child diag information.

- include/openthread-types.h
- include/openthread.h
- src/cli/README.md
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/mac/mac.cpp
- src/core/mac/mac_whitelist.cpp
- src/core/mac/mac_whitelist.hpp
- src/core/openthread.cpp
> Add API to retrieve whitelist diag information.

- include/openthread-types.h
- include/openthread.h
- src/cli/README.md
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/openthread.cpp
- src/core/thread/address_resolver.cpp
- src/core/thread/address_resolver.hpp
> Add API to retrieve EID cache diag information.

- include/openthread-types.h
- include/openthread.h
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/openthread.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
> Add API to retrieve Leader Data information.

- src/ncp/PROTOCOL.md
- src/ncp/spinel.h
Added a table of contents, wrote up proper descriptions for various properties.
> spinel: Protocol documentation update

- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
> Forward multicast datagrams when operating in NCP mode

- src/core/thread/mle.cpp
- src/core/thread/mle_constants.hpp
- src/core/thread/mle_router.cpp
> Make sure Child ID is not being used before allocating

- examples/platforms/cc2538/radio.c
The typo in otPlatRadioSleep() is the root cause for  issue #252, explained in #252
Hi @jwhui , please have a review.
> cc2538: fix radio driver issue which would impact device acting as SED

- tools/spi-hdlc-adapter/spi-hdlc-adapter.c
A more through code review with @abtink revealed several bugs
in the previous implementation. This commit addresses these issues.
Additional changes will likely be necessary once we are able to test.
> spi-hdlc-adapter: Various fixes.

- examples/apps/cli/README.md
> docs: update path to executables

- src/core/thread/lowpan.cpp
* Fix bug in 6LoWPAN UDP header decompression.
> Enable 6LoWPAN UDP header compression.

- tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Fixes issues with parsing command line arguments and
also makes the reset pin behavior work properly.
> spi-hdlc-adapter: Bug fixes and updates

- src/ncp/Makefile.am
- src/ncp/ncp_buffer.cpp
- src/ncp/ncp_buffer.hpp
- tests/unit/Makefile.am
- tests/unit/test_ncp_buffer.cpp
This commit is part of ncp buffer redesign - issue #59.
> Ncp: Introducing `NcpFrame Buffer` class and its unit test.

- include/openthread.h
- src/core/openthread.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
> Add API to constrain the use of the Router/Leader role.

- examples/platforms/posix/radio.c
This change avoids:
* processing stale messages that are queued in the socket.
* busy-looping in the Disabled and Sleep states.
> posix: pull out frames in Disabled and Sleep states

- src/cli/cli.cpp
> Change scanChannels to 32 bits.

- src/ncp/PROTOCOL.md
- src/ncp/ncp_spi.cpp
- src/ncp/ncp_spi.hpp
- tools/spi-hdlc-adapter/README.md
- tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Also fixex HDLC decoding in `spi-hdlc-adapter`.
> ncp-spi: Add padding byte to SPI header.

- src/ncp/ncp_base.cpp
This commit addresses some issues with the set/get property handlers of `NET_STAT` to ensure that wpantund/wpanctl commands "join"/"leave" operate as expected.
> NcpBase: Change/Fix the set/get property handlers for NET_STAT

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
- src/core/thread/mle_tlvs.hpp
* Remove Max Child Count, and Child Count fields.
* Add Parent Priority, Active Routers, SED Buffer Size, and SED Datagram Size fields.
* Update parent selection logic.
> Update Connectivity TLV.

- src/core/thread/mle.cpp
* Remove Leader Data TLV from TLV Request TLV.
* Always add Source Address TLV to Data Response.
* Always add Leader Data TLV to Data Response.
> Update MLE Data Request and Response messages.

- include/platform/Makefile.am
- include/platform/settings.h
This is the new API for the storage and retrieval of non-volatile
settings. Platforms would implement this API in order to allow various
types of information to be preserved across resets or power loss.
> otPlatform: New non-volatile settings API

- src/core/openthread.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
- src/core/thread/thread_tlvs.hpp
- tests/scripts/thread-cert/Cert_5_2_02_LeaderReject1Hop.py
- tests/scripts/thread-cert/Cert_5_2_03_LeaderReject2Hops.py
* Add Status TLV to Address Solicit message.
* Process Status TLV when receiving Address Solicit message.
> Update Address Solicit.

- src/core/thread/mesh_forwarder.cpp
* A detached device may only transmit link-local traffic.
* A child unicasts all secure traffic (including multicast) to its parent.
* A router/leader may use unicast or broadcast for secure traffic.
> Update link-layer packet forwarding logic.

- tools/spi-hdlc-adapter/spi-hdlc-adapter.c
These additions are for improving the debuggability of SPI issues.
This commit also changes the default maximum timeout from one minute to 24 hours, so as to not interfere with NCP sleep behavior.
> spi-hdlc-adapter: Added better debugging capabilities.

- tools/spi-hdlc-adapter/spi-hdlc-adapter.c
This commit makes sure that the specified delay period between
the assertion of C̅S̅ and the start of the SPI clock is enforced.
In order for this to work, both the delay part and the data part
must be in the same `ioctl()` call. The previous code (which used
two `ioctl()` calls) was entirely broken.
The trick is that not all Linux SPI drivers support multi-part
SPI transactions. When `spi-hdlc-adapter` is used with such
devices, the `--spi-cs-delay=0` argument must be added. This causes
the delay part of the transaction to be omitted entirely.
> spi-hdlc-adapter: Fixes for C̅S̅ delay

- tools/spi-hdlc-adapter/spi-hdlc-adapter.c
`syslog()` and `fprintf()` are not async-signal-safe. They can (and
do) cause deadlocks under various circumstances.
This change replaces the calls to these functions with calls to
`write()`. It also adds a watchdog of sorts to the `signal_critical()`
handler to make sure that even if we call some functions that
are not async-signal-safe that we will at least terminate eventually.
> spi-hdlc-adapter: Don't call `syslog()` or `fprintf()` from signal handlers

- src/core/thread/network_data_leader.cpp
- src/core/thread/network_data_local.cpp
- src/core/thread/thread_tlvs.hpp
- src/core/thread/thread_uris.hpp
minimum update for Server Data Notification
Further full feature update might be required in the future
@jwhui please help to have a review.
> update server data register (n/sd -> a/sd)

- third_party/mbedtls/Makefile.am
Thanks to @mszczodrak for identifying that mbedtls was not building properly.
> Use override directive to allow passing in CFLAGS and CPPFLAGS.

- src/core/thread/network_data_leader.cpp
"Leader MUST allocate 6LoWPAN context ID for every prefix in the Valid Prefix Set"
as stated in Chapter 5.15.9 of Thread 1.1 RC2
@jwhui , Please help to have a review.
> allocate 6LoWPAN context ID for every prefix in the Valid Prefix Set

- src/core/thread/meshcop_dataset_manager.cpp
- src/core/thread/meshcop_dataset_manager.hpp
- src/core/thread/meshcop_tlvs.hpp
MeshCoP State TLV is not optional MGMT_ACTIVE_SET.rsp and MGMT_PENDING_SET.rsp.
> Add MeshCoP State TLV

- src/core/thread/address_resolver.cpp
- src/core/thread/address_resolver.hpp
> update address error notification message with Confirmable flag.

- .gitignore
- src/core/common/message.cpp
This updates Message::SetLength and Message::ResizeMessage to handle running out of buffers.
> Message::SetLength and Message::ResizeMessage Bug Fix

- include/openthread.h
- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/openthread-core-default-config.h
- src/core/openthread.cpp
> Add API for setting the default/maximum transmit power.

- include/openthread.h
- src/core/openthread.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/ncp/ncp_base.cpp
> Implement otIsDiscoverInProgress.

- configure.ac
- examples/Makefile-cc2538
- examples/Makefile-posix
- examples/platforms/posix/logging.c
- tests/unit/test_diag.cpp
- tests/unit/test_lowpan.cpp
* Adds -Wextra, -Wshadow, and -Werror to global CFLAGS and CXXFLAGS.
> Require compiler warnings.

- src/ncp/spinel.h
This will bring come of the changes in spinel.h from wpantund into the OT.
> Spinel.h: Update the header file to sync with wpantund

- tools/harness-thci/ARM.py
- tools/harness-thci/README.md
* Add new Device Role MED/FED support in joinNetwork()
* Set default data poll rate for sleepy end device to 10s in joinNetwork()
* Add forceSetSlaac() method support
* Add 'int' type parameter support in removeRouter() for AUTO DUT
* Update README.md and supplement 'pexpect' dependency module
> THCI: update openthread thci with new fix and support.

- src/cli/README.md
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
Fixes a bug reported by @nibanks.
> Do not allow a device to become a leader when the router role is disabled

- .travis/script.sh
> travis: print size of resulting binaries.

- include/openthread.h
- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
- src/core/openthread.cpp
> Allow client to specify whether or not to filter Thread control traffic.

- README.md
> Add `tools` directory to README.

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/network_data_leader.cpp
> Handle Network Data updates via netif handler to coalesce message transmissions.

- src/core/thread/mle.cpp
This addresses spurious failures on the travis-ci checks.
> Fix bugs when comparing partitions during parent selection.

- src/core/net/netif.cpp
- src/core/net/netif.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
> Only send Child Update Request message when no more state changes are pending.

- src/core/openthread.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/network_data.cpp
- src/core/thread/network_data.hpp
- src/core/thread/network_data_leader.cpp
- src/core/thread/network_data_leader.hpp
- src/core/thread/network_data_local.cpp
- src/core/thread/network_data_local.hpp
- src/core/thread/thread_tlvs.hpp
> Implement Server Data Notify.

- src/core/thread/mle.cpp
- src/core/thread/mle_constants.hpp
- src/core/thread/mle_router.cpp
To resolve #477,  @jwhui please have a review. Thanks.
> cli: update link quality cli to take effect for neighoring router devices.

- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/net/icmp6.cpp
- src/core/net/icmp6.hpp
- Only support a single ICMPv6 Echo Reply handler.
- Remove large static ICMPv6 Echo Request buffer.
> Simplify ICMPv6 Echo Request/Reply implementation.

- src/ncp/ncp_base.cpp
- src/ncp/ncp_base.hpp
- src/ncp/spinel.h
This property will also be updated dynamically.
> ncp: Add the ability to get PROP_THREAD_ON_MESH_NETS

- src/core/net/ip6.cpp
> Ip6: Add the LinkSecurityMode info in the copied datagram message passed to host

- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/network_data.cpp
- src/core/thread/network_data.hpp
- src/core/thread/network_data_local.cpp
- src/core/thread/network_data_local.hpp
> Automatically update leader with network data.

- src/core/thread/mesh_forwarder.cpp
This commit changes the steps in `mesh_forwarder` so we check the ipv6 filter (security) check after payload is copied into the message buffer. This helps the IPv6 filter to pass along the TCP packets with unsecure dst port(s) properly.
> Mesh_formwarder: Do the ipv6 filter check after payload is copied in message

- tests/scripts/thread-cert/Cert_5_3_07_DuplicateAddress.py
This change was introduced in #364.
> Revert an incorrect change to the test script.

- tools/harness-automation/README.rst
- tools/harness-automation/autothreadharness/harness_case.py
- tools/harness-automation/autothreadharness/harness_controller.py
- tools/harness-automation/autothreadharness/open_thread_controller.py
- tools/harness-automation/autothreadharness/runner.py
- tools/harness-automation/autothreadharness/settings_sample.py
- tools/harness-automation/cases/leader_5_3_6.py
- tools/harness-automation/cases/med_6_3_2.py
- tools/harness-automation/cases/reed_5_2_4.py
- tools/harness-automation/cases/router_5_1_7.py
- tools/harness-automation/cases/router_5_3_11.py
- tools/harness-automation/cases/router_5_3_3.py
- tools/harness-automation/cases/router_5_7_1.py
- tools/harness-automation/cases/router_7_1_6.py
- tools/harness-automation/doc/quickstart.rst
This commit includes some bug fixes of the auto tool itself, and adds support for Thread Harness's auto DUT features.
> Support Thread Harness 1.1 R19

- doc/spinel-protocol-src/Makefile
The last commit was missing the makefile.
> Fixup for "Refinement of Spinel Protocol Documentation (#534)"

- src/core/meshcop/joiner.cpp
- src/core/meshcop/joiner.hpp
> Set joiner to be on the same channel with joiner router

- src/core/thread/mesh_forwarder.cpp
@jwhui , please have a review.
> fix forwarding issues for packets destinated to AllThreadNodes when multiple SEDs exist

- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/Makefile.am
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/meshcop/panid_query_client.cpp
- src/core/meshcop/panid_query_client.hpp
- src/core/openthread.cpp
- src/core/thread/panid_query_server.cpp
- src/core/thread/panid_query_server.hpp
- src/core/thread/thread_netif.cpp
- src/core/thread/thread_netif.hpp
- src/core/thread/thread_uris.hpp
- tests/scripts/Makefile.am
- tests/scripts/thread-cert/Cert_9_2_14_PanIdQuery.py
- tests/scripts/thread-cert/node.py
> Implement PAN ID Query/Conflict.

- src/cli/cli_dataset.cpp
- src/core/coap/coap_header.cpp
- src/core/coap/coap_header.hpp
- src/core/common/message.cpp
- src/core/meshcop/dtls.cpp
- src/core/net/ip6.cpp
- src/core/net/ip6_mpl.hpp
- src/core/thread/lowpan.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/meshcop_dataset_manager.cpp
- src/ncp/spinel.c
- tests/unit/test_vector.c
- tests/unit/test_vector.h
This fixes build warnings when built on Windows. See issue #570
> Fix build warnings on Windows

- examples/platforms/cc2538/radio.c
- examples/platforms/posix/radio.c
- include/platform/radio.h
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/meshcop/joiner.cpp
> When commissioning, set ext addr based on factory-assigned IEEE EUI-64.

- include/openthread.h
- src/cli/README.md
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/openthread.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
Resolve #542 , please have a review.
> Implement ROUTER_DOWNGRADE_THRESHOLD.

- include/openthread.h
- src/cli/cli.cpp
- src/core/openthread.cpp
- Change cli.cpp to use OpenThread API rather than platform API.
Resolves #589.
> Add otGetFactoryAssignedIeeeEui64() to API.

- include/openthread.h
- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/openthread.cpp
- src/ncp/ncp_base.cpp
This commit adds support for energy scan operation at mac layer.
> Mac: Add support for EnergyScan operation at mac layer.

- src/core/coap/coap_server.cpp
- src/core/coap/coap_server.hpp
- src/core/thread/meshcop_dataset_manager.cpp
- src/core/thread/meshcop_dataset_manager.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
- src/core/thread/network_data_leader.cpp
> Add/remove CoAP resources as needed.

- tools/harness-thci/ARM.py
* Add setRouterDowngradeThreshold() method support.
* Add new sendBeacons() method to ensure compile pass temporarily.
> THCI: update thci with new methods.

- include/openthread.h
- src/cli/README.md
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/meshcop/joiner.cpp
- src/core/openthread.cpp
- move Hash Mac address calculation from joiner.cpp to mac.cpp
- add hashmacaddr cli
resolves #609
> Add Hash MAC address get cli

- src/core/thread/mle.cpp
- src/core/thread/network_data.cpp
- src/core/thread/network_data.hpp
- src/core/thread/network_data_leader.cpp
- src/core/thread/network_data_local.cpp
> Implement DATA_RESUBMIT_DELAY.

- include/commissioning/commissioner.h
- include/openthread-types.h
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/Makefile.am
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/meshcop/energy_scan_client.cpp
- src/core/meshcop/energy_scan_client.hpp
- src/core/openthread-core-default-config.h
- src/core/openthread.cpp
- src/core/thread/energy_scan_server.cpp
- src/core/thread/energy_scan_server.hpp
- src/core/thread/meshcop_tlvs.hpp
- src/core/thread/thread_netif.cpp
- src/core/thread/thread_netif.hpp
- src/core/thread/thread_uris.hpp
- tests/scripts/Makefile.am
- tests/scripts/thread-cert/Cert_9_2_13_EnergyScan.py
- tests/scripts/thread-cert/node.py
> Energy scan.

- src/core/thread/network_data_local.cpp
> Change VerifyOrExit to if-statement for readability.

- .travis.yml
- .travis/script.sh
- src/ncp/ncp_spi.cpp
I guess ncp_spi.cpp isn't automatically built? This file got messed up in a previous merge but wasn't caught.
> Fixes a bad merge from my otInstance declarations change.

- examples/platforms/posix/Makefile.am
- examples/platforms/posix/flash.c
- include/platform/flash.h
This posix flash driver simulates a 256kB flash.
The page size is 2kB.
The page number is 128.
> Posix flash

- src/core/openthread.cpp
This commit changes otOpenUdpSocket() and otCloseUdpSocket() to
initialize and clear mTransport filed of otUdpSocket, respecitvely.
Fixes issues #571.
> Initialize mTransport field of otUdpSocket. (#571)

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle_constants.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
- src/core/thread/mle_tlvs.hpp
- src/core/thread/thread_tlvs.hpp
> Fixed bug with incorrect Router Id 62.

- CONTRIBUTING.md
Just a small reminder to format code.
> Added 'Code style' section to CONTRIBUTING.md

- include/openthread-types.h
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/meshcop/joiner_router.cpp
- src/core/thread/meshcop_tlvs.hpp
> Implement Joiner Router Locator TLV.

- include/commissioning/commissioner.h
- include/commissioning/joiner.h
- include/openthread-types.h
- src/cli/cli.cpp
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/meshcop/dtls.cpp
- src/core/meshcop/dtls.hpp
- src/core/meshcop/joiner.cpp
- src/core/meshcop/joiner.hpp
- src/core/openthread.cpp
- src/core/thread/meshcop_tlvs.hpp
> Implement Provisioning URL TLV.

- src/core/meshcop/dtls.cpp
> Send DTLS-Alert in response to any failures during handshake.

- src/core/thread/mle_constants.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
> Check only one response in Link Accept handler

- src/cli/README.md
- src/cli/cli.cpp
> CLI: Router and child table

- src/core/thread/meshcop_dataset_manager.cpp
This is needed to pass certificate test 9.2.4.
> Init StateTlv when transmit operational dataset set response

- src/core/thread/meshcop_dataset_manager.cpp
This is needed to pass certificate 9.2.4.
> Reject MGMT_ACTIVE_SET.req that includes fields affecting connectivity

- src/cli/README.md
> Add commissioner and joiner commands to README.

- configure.ac
- examples/platforms/cc2538/logging.c
- include/cli/cli-uart.h
- include/platform/uart.h
- src/cli/cli_uart.cpp
- src/ncp/ncp_uart.cpp
allow output logging through uart cli.
> Enable CLI logging

- tools/harness-thci/ARM.py
* add enableAutoDUTObjectFlag() and getChildTimeoutValue().
* add __setRouterSelectionJitter() for quick test.
> THCI: update the thci with new methods for Harness V1.1-R23.

- include/openthread-types.h
- include/openthread.h
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/meshcop/joiner.cpp
- src/core/meshcop/joiner.hpp
- src/core/meshcop/joiner_router.cpp
- src/core/meshcop/joiner_router.hpp
- src/core/openthread.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
Resolves #550.
Along with #675 , we have passed test 8.1.2 Commissioner and 8.2.2 Commissioner.
> Add Joiner UDP Port feature

- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle_constants.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/topology.hpp
- Move logic to invalidate Thread links to MeshForwarder.
Resolves #601.
> Set macMaxFrameRetries to 3.

- src/core/thread/mesh_forwarder.cpp
This commit makes the following changes in `HandleDataRequest()` in `MeshForwader` class:
- We use the counter `mQueuedIndirectMessageCnt` to determine if there  are any queued frames for a given child.
- Handle the data poll/request command differently for a child compared to a neighbor (not being in child table).
> MeshForwader: Update `HandleDataRequest()` to use the counter `mQueuedIndirectMessageCnt`

- src/core/thread/network_data_leader.cpp
> Signal network version increment callback to multicast data response automatically

- tools/harness-thci/ARM.py
> THCI: APIs for commissioning certification tests

- src/core/thread/mle.cpp
Transmit data request when
- vn_version is higher and dataset is not included
This is to pass 9.2.5 and 9.2.6.
> Enhance Mle::HandleDataResponse

- tools/harness-thci/ARM.py
9.2.13 four scenarios (DUT as Router, MED, SED, FED) pass.
> THCI: update thci with MGMT_ED_SCAN method.

- tools/harness-thci/ARM.py
Add support for
- MGMT_ACTIVE_SET
- MGMT_ACTIVE_GET
- MGMT_PENDING_SET
- MGMT_PENDING_GET
- MGMT_COMM_SET
- MGMT_COMM_GET
> Add Operational Dataset and Commissioning Data THCI

- examples/platforms/posix/random.c
This PR refers to #697. It randomizes seed value for posix RNG with current time.
> Add current time to posix RNG seed.

- src/ncp/spinel.c
This commit syncs `spinel.c` with some of recent changes from wpantund.
> Update `spinel.c` (adding debug string for new properties)

- examples/apps/cli/main.c
- examples/apps/ncp/main.c
- include/openthread.h
- src/core/common/tasklet.cpp
- src/core/common/tasklet.hpp
- src/core/openthread.cpp
> Process all currently queued tasklets in one shot.

- include/commissioning/commissioner.h
- src/cli/README.md
- src/cli/cli.cpp
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/meshcop/dtls.cpp
- src/core/meshcop/dtls.hpp
- src/core/openthread-core-default-config.h
- src/core/openthread.cpp
- tests/scripts/thread-cert/Cert_8_1_01_Commissioning.py
- tests/scripts/thread-cert/Cert_8_1_02_Commissioning.py
- tests/scripts/thread-cert/node.py
> Commissioner joiner list.

- tools/harness-thci/ARM.py
This helps to pass certification tests: 8.2.1(Joiner_Router) and 8.2.2(Joiner_Router)
> THCI: support joiner list and enhance log feature

- README.md
Fixes issue #684. See [here](https://github.com/nibanks/openthread/blob/pr/appveyor-badge/README.md).
> Add Appveyor Badge to readme.md

- etc/visual-studio/libopenthread.vcxproj
- etc/visual-studio/libopenthread_k.vcxproj
- include/commissioning/commissioner.h
- src/cli/cli.cpp
- src/core/Makefile.am
- src/core/common/message.cpp
- src/core/common/message.hpp
- src/core/mac/mac.cpp
- src/core/meshcop/announce_begin_client.cpp
- src/core/meshcop/announce_begin_client.hpp
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/meshcop/joiner_router.cpp
- src/core/openthread.cpp
- src/core/thread/announce_begin_server.cpp
- src/core/thread/announce_begin_server.hpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_tlvs.hpp
- src/core/thread/thread_netif.cpp
- src/core/thread/thread_netif.hpp
- src/core/thread/thread_uris.hpp
- tests/scripts/Makefile.am
- tests/scripts/thread-cert/Cert_9_2_12_Announce.py
- tests/scripts/thread-cert/node.py
> MLE Announce.

- src/core/thread/meshcop_tlvs.hpp
> Perform args checking before causing side effects.

- src/core/common/timer.hpp
- src/core/thread/key_manager.cpp
- src/core/thread/key_manager.hpp
- src/core/thread/mle.cpp
> Add key rotation timer and key switch guard timer.

- examples/platforms/cc2538/radio.c
- examples/platforms/posix/radio.c
- include/platform/radio.h
- src/core/mac/mac.cpp
- tests/unit/test_platform.cpp
- Fixes some of the issues causing spurious test failures on Travis.
> Radio API: set short address, extended address, and panid must not fail.

- examples/platforms/cc2538/Makefile.am
- examples/platforms/cc2538/cc2538-reg.h
- examples/platforms/cc2538/flash.c
- examples/platforms/cc2538/rom-utility.h
- include/platform/flash.h
> CC2538 Flash Driver

- tools/harness-thci/ARM.py
This helps to resolve some failure checks in certification test 8.3.1.
> THCI: start commissioner before adding joiner's data

- etc/visual-studio/libopenthread.vcxproj
- etc/visual-studio/libopenthread_k.vcxproj
- include/openthread-types.h
- src/core/Makefile.am
- src/core/common/crc16.cpp
- src/core/common/crc16.hpp
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/meshcop/joiner.cpp
- src/core/thread/meshcop_tlvs.hpp
- src/core/thread/mle.cpp
- tests/scripts/thread-cert/Cert_8_1_01_Commissioning.py
- tests/scripts/thread-cert/Cert_8_1_02_Commissioning.py
> Steering data.

- examples/platforms/posix/README.md
> Update path in README.

- src/core/thread/mle.cpp
Resolves #779.
With the help of #743 , we have passed certification test 8.3.1(Leader):
[Leader_8_3_1.zip](https://github.com/openthread/openthread/files/519253/Leader_8_3_1.zip)
> Set active timestamp to 0 if there is no valid active operational dataset

- tests/scripts/thread-cert/Cert_5_2_05_AddressQuery.py
- tests/scripts/thread-cert/Cert_5_3_03_AddressQuery.py
- tests/scripts/thread-cert/Cert_5_3_07_DuplicateAddress.py
- tests/scripts/thread-cert/Cert_5_3_10_AddressQuery.py
- tests/scripts/thread-cert/Cert_5_6_01_NetworkDataRegisterBeforeAttachLeader.py
- tests/scripts/thread-cert/Cert_5_6_02_NetworkDataRegisterBeforeAttachRouter.py
- tests/scripts/thread-cert/Cert_5_6_03_NetworkDataRegisterAfterAttachLeader.py
- tests/scripts/thread-cert/Cert_5_6_04_NetworkDataRegisterAfterAttachRouter.py
- tests/scripts/thread-cert/Cert_5_6_05_NetworkDataRegisterAfterAttachRouter.py
- tests/scripts/thread-cert/Cert_5_6_06_NetworkDataExpiration.py
- tests/scripts/thread-cert/Cert_5_6_07_NetworkDataRequestREED.py
- tests/scripts/thread-cert/Cert_5_6_08_ContextManagement.py
- tests/scripts/thread-cert/Cert_5_6_09_NetworkDataForwarding.py
- tests/scripts/thread-cert/Cert_6_3_02_NetworkDataUpdate.py
- tests/scripts/thread-cert/Cert_7_1_01_BorderRouterAsLeader.py
- tests/scripts/thread-cert/Cert_7_1_02_BorderRouterAsRouter.py
- tests/scripts/thread-cert/Cert_7_1_03_BorderRouterAsLeader.py
- tests/scripts/thread-cert/Cert_7_1_04_BorderRouterAsRouter.py
- tests/scripts/thread-cert/Cert_7_1_05_BorderRouterAsRouter.py
> Don't Use Special IPv6 Addresses

- tools/harness-thci/ARM.py
Harness may control commissioner to send MGMT_ACTIVE_GET.req from Leader after booting up.
> THCI: set active operational dataset

- src/core/meshcop/commissioner.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
Resolves #778.
This helps to pass certification test 8.3.1(Commissioner):
[Commissioner_8_3_1.zip](https://github.com/openthread/openthread/files/524464/Commissioner_8_3_1.zip)
> Add Leader ALOC feature support

- etc/visual-studio/libopenthread.vcxproj.filters
- etc/visual-studio/libopenthread_k.vcxproj
- etc/visual-studio/libopenthread_k.vcxproj.filters
- etc/visual-studio/mbedtls_k.vcxproj
- include/platform/Makefile.am
- include/platform/memory.h
- include/platform/toolchain.h
- src/core/common/new.hpp
- src/core/meshcop/dtls.cpp
- src/core/meshcop/dtls.hpp
- src/core/openthread.cpp
- third_party/mbedtls/mbedtls-config.h
This exposes the interface to fix #714. Once merged, I will implement the functions for Windows kernel mode in my driver.
> Platform Support for Dynamic Memory Allocation

- src/core/mac/mac.cpp
- src/core/mac/mac_frame.cpp
- src/core/mac/mac_frame.hpp
- src/core/thread/mle.cpp
Fixes the issue described in #816.
> Set the Key Source field for 802.15.4 Key ID Mode 2.

- src/core/openthread-core-default-config.h
Fixing the description/comment...
> Update the description/comment for `OPENTHREAD_CONFIG_MAX_STATECHANGE_HANDLERS`

- .travis.yml
- .travis/before_install.sh
- .travis/script.sh
- configure.ac
> Add arm-gcc54 to travis and -Wno-c++14-compat to CXXFLAGS.

- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/thread/meshcop_dataset_manager.cpp
- src/core/thread/network_data.cpp
- src/core/thread/network_data.hpp
This is to pass 9.2.4 (DUT as commissioner).
> Use Leader ALOC if it is commissioner

- src/core/common/settings.cpp
- write the actual setting's length into flash
- add getAlignLength() for address alignment
> Refine settings driver

- src/core/thread/network_data.cpp
Fixes the test failures experienced in #857.
> Fix Server Data Notification IPv6 source address to RLOC.

- examples/platforms/posix/logging.c
- src/cli/cli_uart.cpp
- src/core/common/logging.cpp
- src/core/common/message.cpp
- src/core/mac/mac.cpp
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/dtls.cpp
- src/core/meshcop/energy_scan_client.cpp
- src/core/meshcop/joiner.cpp
- src/core/meshcop/joiner_router.cpp
- src/core/meshcop/leader.cpp
- src/core/meshcop/panid_query_client.cpp
- src/core/net/icmp6.cpp
- src/core/openthread.cpp
- src/core/thread/address_resolver.cpp
- src/core/thread/announce_begin_server.cpp
- src/core/thread/energy_scan_server.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/meshcop_dataset_manager.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/network_data.cpp
- src/core/thread/network_data_leader.cpp
- src/core/thread/network_diag.cpp
- src/core/thread/panid_query_server.cpp
> Update otLog*() to not require line separators.

- src/core/common/message.cpp
I have started working on IP-in-IP encapsulation that is needed for MPL. During development i have found that one of the step that is required is to increase reserved space for potential second IPv6 header. The easiest solution is to just add another sizeof(Header) in Ip6::NewMessage() function and be ready for packet destined to multicast scope larger than Realm-Local.
I do think this solution is not good enough, since probably Thread will use IP-in-IP very few times if any. 
Currenly Ip6::NewMessage() allocates place for an IPv6 Header (40 bytes) and an MPL Option (8 bytes) but this looks reasonable.
This PR introduces feature of increasing Reserved space by adding a new buffer between first and second buffer in the chain, and copying (if any) actual payload from mHeadData of the first …
> Message: Resize reserved space

- tools/spinel-cli/spinel-cli.py
Resolves issue raised in #851.
> Print shorts as hex values.

- tests/scripts/Makefile.am
- tests/scripts/thread-cert/Cert_5_3_02_RealmLocal.py
- tests/scripts/thread-cert/Cert_6_4_02_RealmLocal.py
Fixes test issue pointed out by @nibanks.
> Update multicast tests to expect multiple ping replies.

- include/Makefile.am
- include/openthread-crypto.h
- src/core/Makefile.am
- src/core/crypto/openthread-crypto.cpp
This PR introduces ot C APIs for crypto operation HMAC and AES-CCM.
> Adding C APIs for crypto opereation HMAC and AES-CCM

- examples/platforms/cc2538/radio.c
> Disable receiver when changing the channel config.

- tools/harness-thci/ARM.py
Modified reading data functions to support ser2net devices.
> THCI support ser2net devices

- src/core/mac/mac.cpp
> Do not regenerate frame when retransmitting.

- src/core/common/message.cpp
- src/core/common/message.hpp
- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
- tests/scripts/Makefile.am
Fixes an issue raised in #827.
This PR does not address the need for IP-in-IP encapsulation.
> Insert MPL Option in host-generated realm-local mcast messages.

- tools/Makefile.am
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>
> Do not build tools if --disable-tools is set

- src/core/thread/mle_router.cpp
This commit changes the `MleRouter::SendChildIdResponse()` so that a new child id (and rloc16) is assigned to the child if it does not already have one. This ensures that it we receive multiple MLE ChildIdRequest from the same child, the child id remains the same on all the responses.
> Assign a new child id if the none is already assigned to the child.

- examples/apps/cli/README.md
- src/cli/README.md
- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router.hpp
> Remove Link Reject and link-local RLOC.

- tests/scripts/thread-cert/Cert_5_1_07_MaxChildCount.py
Fixes the issue raised in #869 and #882.
> Update to latest Thread Certification Test Spec.

- tools/harness-automation/autothreadharness/harness_case.py
GRL harness cannot reuse golden device box by replacing its serial port name. This fix the newly found issue by remove it and add new box for retrials.
> fix bad golden device retrial

- tools/harness-automation/autothreadharness/runner.py
This PR add a feature to select test cases by matching case name using the unix filename matching pattern.
> Grep case name

- doc/draft-spinel-protocol.html
- doc/draft-spinel-protocol.txt
- doc/spinel-protocol-src/draft-spinel-protocol.md.in
- doc/spinel-protocol-src/spinel-feature-jam-detect.md
- doc/spinel-protocol-src/spinel-prop-core.md
- src/ncp/spinel.c
- src/ncp/spinel.h
This commit outlines new Spinel properties for implementing a signal jamming detection feature into an NCP.
> spinel: Updated documentation for signal jamming detection

- src/core/mac/mac.cpp
This should also address lingering Travis test failures that involve SEDs.
> Disable receiver after receiving data frame during a poll.

- src/core/net/dhcp6_client.cpp
- src/core/net/dhcp6_server.cpp
Nit: I didn't have any tabs in the code on my local machine before.
This PR is the output of `make pretty` after performing `configure `with dhcp client and server enabled.
> DHCP: Make pretty on client and server

- tools/spinel-cli/MANIFEST.in
- tools/spinel-cli/setup.py
This PR fixes #795. Please verify if `author_email` field works for you.
> Added setup script for spinel-cli (#795)

- .appveyor/make_release.cmd
- .appveyor/test_driver.cmd
Added to more easily support building Windows application layer code outside of Git.
> Package libs in release.zip

- include/openthread-jam-detection.h
- src/core/utils/jam_detector.cpp
This PR also contains some other comment fixes...
> Update `JamDetector` to invoke handler every second when jam is detected

- examples/platforms/cc2538/radio.c
- src/core/mac/mac.cpp
- src/core/net/ip6_address.cpp
- src/core/net/ip6_address.hpp
- src/core/net/ip6_mpl.hpp
- src/core/thread/address_resolver.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
The main intention of this PR is to resolve device hang issue.
Mainly include:
- fix hang issue exposed when intensive traffic in dense network.
- mSockAddr should not be reset when send response for CoAP CON message.
- other code refinements.
@jwhui, please help to review it, thanks!
> fix hang issue exposed when intensive traffic in dense network

- src/core/thread/lowpan.hpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle_router_ftd.hpp
- src/core/thread/mle_router_mtd.hpp
This PR fixes #956 by introducing support for Deep Hops Left field.
> Mesh: Add Deep Hops Left field support.

- include/openthread-types.h
- src/cli/README.md
- src/cli/cli.cpp
- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/thread/topology.hpp
- src/ncp/ncp_base.cpp
- src/ncp/spinel.h
Adds separate MAC level Rx/Tx counters for unicast and broadcast packets.
> Add separate counters for unicast and broadcast

- src/core/coap/coap_client.cpp
This PR fixes a bug in CoAP Client that prevented processing of responses sent for multicast CoAP requests.
> Coap Client - multicast response processing bugfix.

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router_ftd.hpp
- src/core/thread/mle_router_mtd.hpp
- src/core/thread/thread_tlvs.hpp
- tools/harness-thci/ARM.py
The PR could let [REED_5_5_5.zip](https://github.com/openthread/openthread/files/612673/REED_5_5_5.zip) pass
@jwhui , please have a review!
> Restrict the condition to SendAddressRelease

- tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Pulling in changes to spi-hdlc-adapter from wpantund.
See wpantund commit 9cdc9dab7d245f39ad7a4cfc7190f3879e200b98
> Pulling in changes from Wpantund

- src/ncp/hdlc.cpp
> Escape XON and XOFF

- examples/drivers/windows/otLwf/eventprocessing.c
- src/core/net/ip6.hpp
- tests/scripts/thread-cert/Cert_5_1_07_MaxChildCount.py
> Reduce MTU to 1280 bytes

- etc/visual-studio/libopenthread.vcxproj
- etc/visual-studio/libopenthread_k.vcxproj
- etc/visual-studio/libopenthread_k.vcxproj.filters
- include/openthread-types.h
- src/cli/cli.cpp
- src/core/Makefile.am
- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/thread/network_diagnostic.cpp
- src/core/thread/network_diagnostic.hpp
- src/core/thread/network_diagnostic_tlvs.cpp
- src/core/thread/network_diagnostic_tlvs.hpp
- src/core/thread/thread_netif.hpp
Update network diagnostic to truly pass 5.7.1 Router 
[Router_5_7_1.zip](https://github.com/openthread/openthread/files/624187/Router_5_7_1.zip)
@jwhui please help to review it.
> fix diagnostic feature and code cleanup

- tools/harness-thci/OpenThread.py
To pass [Router_5_3_5.zip](https://github.com/openthread/openthread/files/626801/Router_5_3_5.zip)
> THCI: add new constant required by Harness

- doc/draft-spinel-protocol.html
- doc/draft-spinel-protocol.txt
This PR just updated the `draft-spinel-protocol` documents,
> Update the `draft-spinel-protocol` documents

- examples/platforms/cc2538/radio.c
SFD bit should be 0 before transmission.
@jwhui please have a review.
> cc2538: fix radio driver issue

- src/core/thread/mesh_forwarder.cpp
- Allow cleanup even when mSendBusy is true.
- Set mSendMessage to NULL to indicate that the message has been freed.
- In HandleSentFrame(), simply schedule next transmission if mSendMessage is NULL.
Thanks to @abtink for identifying the bug.
> Fix cleanup of indirect messages when a child is removed.

- examples/platforms/cc2538/radio.c
- examples/platforms/posix/logging.c
- include/platform/logging.h
- src/core/common/logging.cpp
- src/core/common/logging.hpp
- src/core/openthread-core-default-config.h
Note, the platform logging is disabled by default.
> CC2538 Radio Logging

- src/core/meshcop/dataset_manager.cpp
To address issue #967 , verify this PR with modification based on test case 9.2.7.(Also set a different extended PanId on Router when it forms its partition, so it will send MGMT_ACTIVE_SET.req including a mech_local prefix TLV that would affect connectivity when it migrates to Leader's partition).
Below is the result based on current master branch, we can see that lots of register attempts during dataset transition.
[Leader_9_2_7_master.zip](https://github.com/openthread/openthread/files/645094/Leader_9_2_7_master.zip)
Below is the result based on this PR, we can see that Router stops to register when it finds that active timestamp in pending dataset network version is ahead of active timestamp in local active dataset.
[Leader_9_2_7_no_register.zip](https://github.com/openthread/openthrea …
> Stop registration attempts if active timestamp in Pending dataset is ahead of value in Active dataset.

- include/openthread.h
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/openthread.cpp
- src/core/thread/network_diagnostic.cpp
- src/core/thread/network_diagnostic.hpp
This PR proposes a simple solution for #1055.
> DIAG: Add CLI support for Diagnostic DIAG_GET.rsp message.

- tools/harness-automation/autothreadharness/harness_case.py
- tools/harness-automation/autothreadharness/harness_controller.py
- tools/harness-thci/OpenThread.py
This PR includes a walk-around for harness hanging issue and let THCI to retrieve version on runtime.
> Improvements for r33

- tests/scripts/thread-cert/ipv6.py
- tests/scripts/thread-cert/test_ipv6.py
Fixed spurious test errors in test_ipv6.py.
> Fix spurious test errors in test_ipv6.py

- tests/scripts/Makefile.am
- tests/scripts/thread-cert/message.py
- tests/scripts/thread-cert/sniffer.py
- tests/scripts/thread-cert/sniffer_transport.py
I've redesigned sniffer class. Currently the socket transport isn't a part of sniffer. Changes also should allow to add any other transport to the sniffer.
> Improve the sniffer design.

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router_ftd.hpp
- src/core/thread/mle_router_mtd.hpp
> Implement 2-hop loop avoidance.

- src/core/common/message.hpp
- src/core/net/ip6_mpl.cpp
- src/core/thread/mesh_forwarder.cpp
> Reduce amount of multicast messages send to SED.

- tests/scripts/thread-cert/config.py
- tests/scripts/thread-cert/ipv6.py
- tests/scripts/thread-cert/test_ipv6.py
- tests/scripts/thread-cert/test_lowpan.py
Improvement that fixes problem with the issue: #1146
> Add the default factory option to the ICMP body factory.

- tools/harness-thci/OpenThread.py
Certification test 9.2.16 needs to check the Active Timestamp TLV in Child ID Request during first attach, this PR will set the default active dataset with the default network parameters for each device,  I have verified that it will not break any passed tests.
I had proposed to not check Active Timestamp TLV in Child ID Request from a fresh device ([TESTPLAN-303](https://threadgroup.atlassian.net/browse/TESTPLAN-303)), and it is blocked by another proposal ([SPEC-561](https://threadgroup.atlassian.net/browse/SPEC-561)) which is under TC DISCUSS.
> THCI: set default active dataset for each device.

- tools/harness-thci/OpenThread.py
A fix to #1184, it helps to repass Certification test Leader_9.2.3.
> THCI: Set default security policy flags.

- tools/harness-automation/autothreadharness/harness_case.py
- tools/harness-automation/autothreadharness/harness_controller.py
- tools/harness-automation/autothreadharness/runner.py
I've tried to run the harness automation tool, but it had some issues that prevented me to do this. I've fixed found issues that causes that this tool doesn't work. Please take a look on the proposed changes and if made changes are relevant, merge it to the master branch.
> Stabilize the harness automation tool.

- include/platform/messagepool.h
- src/core/common/message.cpp
- src/core/common/message.hpp
Make mNumFreeBuffers a uint rather then an int since the number of free buffers should never be negative.
> Make mNumFreeBuffers unsigned

- src/core/thread/key_manager.cpp
Neighboring devices may reset their frame counters when changing the master key.  As a result, receive frame counters also need to be reset.
> Reset receive frame counters on master key change.

- src/ncp/ncp_base.cpp
This commit separates the sending of full network data and the list
of on-mesh prefixes when an `OT_THREAD_NETDATA_UPDATED` event is
received. The list of on-mesh prefixes is sent out only after the
network data is sent out (or queued) successfully. This handles
the case where the NCP tx buffer may not have enough space to fit
both messages.
> NcpBase: Separate sending of network data from list of on-mesh prefixes

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- Fixes Active and Pending Timestamp TLV processing when handling Child Update Response messages.
> Unify Network Data, Active Timestamp, and Pending Timestamp processing in MLE.

- examples/platforms/cc2538/diag.c
- examples/platforms/nrf52840/diag.c
- examples/platforms/posix/diag.c
- include/platform/diag.h
- src/diag/diag_process.cpp
- src/diag/diag_process.hpp
- Pass otInstance to otPlatDiagProcess
- Add handler for channel change in diag.c
- Add handler for tx power change in diag.c
- Add handler for frame received in diag.c
- Add handler for alarm fired in diag.c
- Add custom diagnostic commands for nrf52840
> Add more flexibility to diagnostic module

- src/core/meshcop/joiner.cpp
- src/core/meshcop/joiner_router.cpp
- src/core/meshcop/joiner_router_ftd.hpp
- tools/harness-thci/OpenThread.py
impact OT(TB) Joiner or OT(DUT)Commissioner -related cases in which JOIN_ENT.req would be checked in V39
eg 8.1.1Commissioner on NXP DUT v.s. OT TB in V39
> THCI: fix JOIN_ENT log

- src/core/thread/mle_router.cpp
- src/core/thread/mle_router_ftd.hpp
Test case 5.8.4 is not robust. This PR should help.
> Add jitter before sending Discovery Response.

- src/core/thread/mle_router.cpp
> In `ResetAdvertiseInterval()`, replace `assert()` with `VerifyOrExit()`.

- src/core/thread/mesh_forwarder.cpp
- This commit add comments to clarify how the `SendFragment()`
handles (insecure) MLE messages requiring fragmentation and
modifies the logic to have the caller enable security when
trying again.
> `MeshForwader`: Add comments and modify handling of (insecure) MLE message requiring fragmentation

- examples/drivers/windows/include/otLwfIoctl.h
- examples/drivers/windows/otApi/otApi.cpp
- examples/drivers/windows/otLwf/filter.h
- examples/drivers/windows/otLwf/iocontrol.c
- examples/drivers/windows/otLwf/thread.c
- examples/drivers/windows/otLwf/thread.h
> Fixes for otJoinerStart on Windows

- examples/platforms/da15000/radio.c
Fixed functionalities:
SED (frame pending manipulation, ACK)
Reattachment
RadioSleep
> Radio fixes

- tools/harness-thci/OpenThread.py
Makes the certification test 8.x.x more stable by checking the joiner callback log.
> THCI: Refine joinCommissioned method

- src/core/meshcop/commissioner.cpp
> Fix for Commissioner::RemoveJoiner

- src/cli/cli.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
> Add args check to `SetRouterSelectionJitter()`.

- tools/harness-automation/autothreadharness/harness_case.py
- tools/harness-automation/autothreadharness/pdu_controller.py
- tools/harness-automation/autothreadharness/pdu_controller_factory.py
- tools/harness-automation/autothreadharness/settings_sample.py
This pull request adds a PDU controller abstraction to the harness automation. It contains also an implementation of the PDU controller that allows to reset Nordic dev-kits.
> Add PDU controller that allows to reboot Nordic dev-kits.

- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router_ftd.hpp
- src/core/thread/mle_router_mtd.hpp
> Delay transmission of Data Request in response to a multicast message.

- src/core/mac/mac.cpp
In `Mac::ProcessReceiveSecurity()`, if the frame is from a neighbor
not in valid state (e.g., it is from a child being restored), we
skip the key sequence and frame counter checks but continue to
verify the security tag/MIC. Such a frame is later filtered in
`RxDoneTask()` which only allows "MAC Data Request" frames from a
child being restored.
> Mac: Check and pass up (only) "Data Request" frames from a child being restored

- include/commissioning/commissioner.h
- include/openthread-types.h
- include/openthread.h
- src/cli/README.md
- src/cli/cli_dataset.cpp
- src/core/Makefile.am
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/meshcop/dataset_manager_ftd.cpp
- src/core/openthread.cpp
- src/core/thread/network_data_leader_ftd.cpp
- src/core/thread/network_data_leader_ftd.hpp
- src/core/thread/network_data_leader_mtd.hpp
- third_party/mbedtls/Makefile.am
- Resolves [build failure](https://travis-ci.org/openthread/openthread/builds/202121764) by reducing code size requirement when Commissioner role is not enabled.
> Move PSKc generation functionality to Commissioner role.

- examples/drivers/windows/otLwf/command.c
- examples/drivers/windows/otLwf/command.h
- examples/drivers/windows/otLwf/datapath.c
- examples/drivers/windows/otLwf/filter.h
- examples/drivers/windows/otLwf/precomp.h
- examples/drivers/windows/otLwf/radio.c
- examples/drivers/windows/otLwf/thread.c
- examples/drivers/windows/otLwf/tunnel.c
Sends the Spinel reset command first thing for initializations.
> Windows: Reset the Device on Initialization.

- tools/harness-automation/README.rst
- tools/harness-automation/autothreadharness/harness_case.py
- tools/harness-automation/autothreadharness/runner.py
- tools/harness-automation/autothreadharness/settings_sample.py
- tools/harness-automation/cases/router_5_2_7.py
- tools/harness-automation/doc/quickstart.rst
> [Harness-Automation] Fix issues until harness r40

- src/cli/README.md
> update CLI README

- src/ncp/ncp_base.cpp
- src/ncp/ncp_base.hpp
Making sure all lines wrap at 120 characters.
> `NcpBase`: Adjust spacing/formatting (no code logic change)

- tools/harness-thci/OpenThread.py
This PR corrected some typos and fixes some issues found by Python's static analysis.
> THCI: fix some typos and SA issues

- tools/harness-automation/autothreadharness/harness_case.py
- tools/harness-automation/autothreadharness/harness_controller.py
- tools/harness-automation/autothreadharness/settings_sample.py
This PR enhanced automation by
> [Harness Automation]: detect harness configuration

- include/openthread.h
- src/core/openthread.cpp
Expanded the amount of parent info provided and added a function to get the average RSSI for the parent link.
> Parent Info

- src/core/thread/mle_router.cpp
In current implementation, when a neighbor Router goes down and is removed due to failed transmission, it's state is set to disabled, but link quality information remains unchanged, which causes bizzare entries in routing table:
This PR moves the logic related to link removal to RemoveNeighbor function to fix the issue.
> Fix incorrect link quality after router removal

- include/openthread-coap.h
- src/core/coap/coap_header.cpp
- src/core/coap/coap_header.hpp
- src/core/openthread.cpp
* Observe
* Max-Age
* Uri-Query
> Implement more CoAP Options

- configure.ac
- tests/scripts/Makefile.am
- tests/scripts/thread-cert/Makefile.am
Eases addition of other functional test groups under tests/scripts.
> Modularized tests/scripts Makefile.

- examples/platforms/nrf52840/alarm.c
- examples/platforms/nrf52840/openthread-core-nrf52840-config.h
- examples/platforms/nrf52840/platform-config.h
- include/platform/Makefile.am
- include/platform/usec-alarm.h
- src/core/api/link_raw_api.cpp
- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/openthread-core-default-config.h
I've created new implementation of microsecond timer according to @pvanhorn suggestions. We are performing intensive tests right now. It seems to be stable.
> Implementation of platform usec-alarm API to support correct delays in CSMA/CA

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mle.cpp
> Fix polling behaviour on Thread Stop.

- src/core/thread/network_data_leader_ftd.cpp
> Add NULL pointer checks to `IsStableUpdated()`.

- etc/visual-studio/libopenthread.vcxproj
- etc/visual-studio/libopenthread.vcxproj.filters
- etc/visual-studio/libopenthread_k.vcxproj
- etc/visual-studio/libopenthread_k.vcxproj.filters
> Clean up Visual Studio Project Files

- include/openthread/platform/radio.h
- src/core/thread/mesh_forwarder.hpp
This commit adds/updates comments. It contains no code/logic change.
- Adds comments to describe expected behavior and use of source match
feature and the related radio platform functions.
- Updates comments to describe the selection of poll period and the
`SetAssignPollPeriod()`.
> Update comments: Source Match feature and poll period selection

- src/core/api/link_api.cpp
- src/core/mac/mac.cpp
- src/core/mac/mac_frame.hpp
- src/core/thread/mle.cpp
> Make disabled 'B' bit of SecurityPolicy take effect

- examples/platforms/nrf52840/alarm.c
- examples/platforms/nrf52840/logging.c
- examples/platforms/nrf52840/misc.c
- examples/platforms/nrf52840/platform-nrf5.h
- examples/platforms/nrf52840/platform.c
- examples/platforms/nrf52840/radio.c
- examples/platforms/nrf52840/random.c
- examples/platforms/nrf52840/uart.c
- include/openthread/platform/platform.h
- third_party/NordicSemiconductor/drivers/nrf_drv_radio802154.c
- third_party/NordicSemiconductor/drivers/nrf_drv_radio802154.h
> Platform deinitialization function.

- src/core/meshcop/commissioner.cpp
- src/core/meshcop/joiner.cpp
TH V43 add StatusTLV("Reject") verification in JOIN_FIN.rsp when provisioningurl mismatch
> Add payload dump for JOIN_FIN.rsp

- .travis/script.sh
- examples/Makefile-cc2538
- examples/Makefile-cc2650
- examples/Makefile-da15000
- examples/Makefile-nrf52840
- examples/platforms/cc2538/README.md
- examples/platforms/cc2650/README.md
- examples/platforms/da15000/README.md
- examples/platforms/nrf52840/README.md
- third_party/dialog/DialogTools/imgprep.sh
> Separate build output based on target.

- README.md
- Switch to the "production" URL.
> Update URL to certified.svg

- include/openthread/types.h
- src/cli/cli.cpp
- src/core/api/instance_api.cpp
- src/core/api/message_api.cpp
- src/core/coap/coap_base.hpp
- src/core/coap/coap_client.cpp
- src/core/coap/coap_client.hpp
- src/core/coap/coap_header.cpp
- src/core/coap/coap_header.hpp
- src/core/coap/coap_server.cpp
- src/core/coap/coap_server.hpp
- src/core/coap/secure_coap_server.cpp
- src/core/openthread-core-default-config.h
- src/core/thread/thread_netif.cpp
Implementation of RFC 7252 4.5.
> [CoAP Server] Message deduplication

- third_party/NordicSemiconductor/drivers/nrf_drv_radio802154.c
This bug appeared when rx buffer was freed during receiving of an empty (invalid) frame.
> Fix assert in nRF52840 radio driver.

- src/core/mac/mac.cpp
- src/core/thread/mesh_forwarder.cpp
This commit updates the source address matching feature's debug logs.
It mainly adds a prefix of "SrcAddrMatch" to the log string.
> Update source address matching logs

- .gitignore
- etc/vagrant/.gitignore
- etc/vagrant/Vagrantfile
Tested with both posix and wpantund on a mac host
> Basic Vagrantfile for simulation

- examples/apps/windows/MainPage.xaml.cpp
- examples/apps/windows/otApi.h
- src/ncp/ncp_base.cpp
This should get AppVeyor builds clean of warnings.
> Fix Warnings in Windows Build

- examples/drivers/windows/otApi/otApi.cpp
- include/openthread/link.h
- src/core/api/link_api.cpp
- src/core/api/thread_api.cpp
* Add otSendMacDataRequest declaration to API headers
* Move otSendMacDataRequest from thread to link API
> Fix otSendMacDataRequest API

- include/openthread/coap.h
- src/core/api/coap_api.cpp
- src/core/coap/coap_header.cpp
- src/core/coap/coap_header.hpp
- src/core/coap/coap_server.cpp
* Add GetFirstOption
* Remove GetCurrentOption
* Change corresponding APIs
* Do not drop requests that have unknown CoAP options
> CoAP option update

- tools/harness-thci/OpenThread.py
Next harness would include some crypto lib and verify PSKc field in 9.2.4
> THCI: update for Harness

- doc/spinel-protocol-src/spinel-tech-thread.md
- include/openthread/commissioner.h
- include/openthread/types.h
- src/core/api/commissioner_api.cpp
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
- src/core/meshcop/dataset_manager.cpp
- src/core/thread/topology.hpp
- src/ncp/ncp_base.cpp
- src/ncp/ncp_base.hpp
- src/ncp/spinel.c
- src/ncp/spinel.h
Adding support for the commissioning commands from the wpanctl.
This pr is complementary to the https://github.com/openthread/wpantund/pull/134.
> Add initial commissioning commands support to the NCP

- examples/drivers/windows/otLwf/radio.c
- src/core/api/link_raw.hpp
- src/core/api/link_raw_api.cpp
- src/ncp/ncp_base.cpp
Some clean up of the raw link layer to improve logging usefulness.
> Logging and Raw Link Layer Cleanup

- src/core/thread/mle.cpp
> Use fast poll after sending an MLE Data Request.

- src/core/coap/coap_client.cpp
- src/core/net/udp6.cpp
This PR make UdpSocket::Bind to act more like the posix version. http://man7.org/linux/man-pages/man7/ip.7.html
> Choose ephemeral port at udp layer

- include/openthread/thread.h
- src/core/api/thread_api.cpp
Added thread api call to get the last rssi for the parent
> Parent last rssi

- src/core/thread/mle_router.cpp
> Remove Active and Pending Datasets from unsolicited Data Response.

- src/core/thread/network_diagnostic.cpp
- src/core/thread/network_diagnostic.hpp
- src/core/thread/network_diagnostic_tlvs.hpp
> Remove use of zero-length arrays.

- src/core/thread/data_poll_manager.cpp
- src/core/thread/data_poll_manager.hpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle.cpp
No logic/algo change in this PR. Updated some variable/method names (to help with code readability) and some of the comments/documentation.
> `DataPollManager`: Update some of the methods/variables names.

- Makefile.am
- src/cli/Makefile.am
- src/cli/README.md
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/cli/cli_coap.cpp
- src/cli/cli_coap.hpp
Adds CLI commands for a simple CoAP client and server with one resource called "test". Supports Non- and Confirmable requests...
I was playing around and thought due to the many requests on the google group it might be useful to have this functionality as an example working "out of the box". It's by far not finished but I just wanted to see if something like is wanted/useful.  And I'm also just getting warm with C again...
> [CoAP] Adding CLI commands

- src/core/api/thread_api.cpp
- src/core/mac/mac.cpp
- src/core/thread/address_resolver.cpp
- src/core/thread/key_manager.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/network_diagnostic.cpp
- src/core/thread/src_match_controller.cpp
- src/core/thread/thread_tlvs.hpp
- src/core/thread/topology.hpp
- tests/unit/test_toolchain.cpp
This PR makes no changes to existing logic.
> Add accessor methods to neighbor/child/router objects.

- examples/platforms/cc2538/README.md
> Update CC2538 flashing instructions.

- src/core/thread/src_match_controller.cpp
Need to check IndirectMessageCount before addition.
> Fix incorrect logic in IncrementMessageCount() method

- tools/harness-thci/OpenThread.py
> THCI: enhancements

- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
> Restrict 15.4 Beacon transmissions to REEDs/Routers/Leaders.

- .travis/script.sh
- src/cli/cli_coap.cpp
> Fix compiler warning and code style.

- src/cli/cli_coap.cpp
- src/core/api/coap_api.cpp
Resolves #1601 and creates adds check for NULL header in the API to avoid a similar issue in the future
> Coap fixes

- src/cli/cli.cpp
This PR simply appends the text message of error for CLI.
> Print error message on cli failure

- configure.ac
> #1600 - Resolve issues with missing ./configure messages

- src/core/thread/data_poll_manager.cpp
Thanks to @librasungirl  for finding this...
> `DataPollManager`: Fix the reseting of the `mNoBufferRetxMode`.

- src/core/crypto/pbkdf2_cmac.cpp
- src/core/meshcop/dtls.cpp
- tests/unit/test_lowpan.cpp
- tests/unit/test_platform.cpp
Every time `make pretty`, these issues are made. This PR just submit what `make pretty` result in so that one don't have to remove these changes after `make pretty`.
> Fix code style issues.

- src/core/meshcop/leader.cpp
- src/core/meshcop/leader_ftd.hpp
- src/core/thread/mle_router.cpp
- tests/scripts/thread-cert/config.py
- tests/scripts/thread-cert/network_data.py
> Set Commissioner Data when becoming Leader

- src/diag/README.md
Minor fixes to render list of commands correctly:
Current one:
https://github.com/openthread/openthread/tree/master/src/diag
> [DOC] Fix command list of Diag module

- examples/platforms/efr32/random.c
Thanks to @beriberikix for pointing this out!
> Fix efr32 `otPlatRandomGetTrue()` declaration.

- src/core/openthread-core-default-config.h
This commit contains no logic change. It updates the comments in
default config header file.
> Update default config header file to add comments on link-raw related options

- examples/platforms/nrf52840/nrf52840.ld
This PR fixes two minor issues with nrf52840 linker script.
> Update nrf52840 linker script.

- doc/spinel-protocol-src/spinel-prop-net.md
- examples/drivers/windows/include/otLwfIoctl.h
- examples/drivers/windows/otApi/otApi.cpp
- examples/drivers/windows/otLwf/iocontrol.c
- examples/drivers/windows/otLwf/iocontrol.h
- examples/drivers/windows/otNodeApi/otNodeApi.cpp
- include/openthread/thread.h
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/api/thread_api.cpp
- src/core/meshcop/dataset_manager.cpp
- src/core/meshcop/dataset_manager_ftd.cpp
- src/core/thread/key_manager.cpp
- src/core/thread/key_manager.hpp
- src/ncp/ncp_base.cpp
- src/ncp/ncp_base.hpp
- src/ncp/spinel.c
- src/ncp/spinel.h
This PR adds the API to set and get PSKc before forming network.
> Add PSKc API

- .travis/before_install.sh
- tests/scripts/thread-cert/node_cli.py
This PR partially solves #961.
> Use pyspinel package

- src/core/thread/mle.cpp
> Request Network Data if new one is available but missing in the MLE message.

- src/core/mac/mac.cpp
* Add initializer for 'mNoiseFloor'
* Initialize class Mac's member variables in its constructor
> Add initializer for 'mNoiseFloor'

- include/openthread/coap.h
I keep missing defines, so just added all message code and option type enums that are defined in RFC7252.
> Add more CoAP code and option enums

- src/core/net/ip6.cpp
This PR aims at making a better choice between RLOC and EID when selecting source.
> Select better mesh local address

- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
fixed code style issue in ip6.
> sync parameter names in ip6.cpp with ip6.hpp

- src/core/api/thread_api.cpp
- src/core/common/settings.hpp
- src/core/meshcop/dataset.cpp
- src/core/meshcop/dataset.hpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router_ftd.hpp
> Co-locate settings structs and document rules for updating.

- src/ncp/ncp_base.cpp
- src/ncp/ncp_base.hpp
- src/ncp/spinel.h
Follow up on https://github.com/openthread/openthread/pull/1703.
> `NcpBase`: Adding support for MLE Discovery scan related spinel porperties.

- doc/spinel-protocol-src/spinel-prop-core.md
Introduces a new core property (`PROP_HOST_POWER_STATE`) which is used
by the host to inform the NCP of the power state of the *host*.
The NCP can then use this state to determine which properties need
asynchronous updates. The states are defined in similar terms to
those used for the `PROP_POWER_STATE` property.
> spinel: Introduce PROP_HOST_POWER_STATE

- include/openthread/coap.h
- src/core/api/coap_api.cpp
- src/core/coap/coap.cpp
- src/core/coap/coap.hpp
> CoAP: Implement default request handler

- include/openthread/thread.h
- include/openthread/thread_ftd.h
- src/core/api/thread_api.cpp
- src/core/api/thread_ftd_api.cpp
> Move PSkc Get and Set functions to thread_ftd

- doc/spinel-protocol-src/Makefile
- doc/spinel-protocol-src/draft-rquattle-spinel-basis.md.in
- doc/spinel-protocol-src/draft-rquattle-spinel-unified.md.in
- doc/spinel-protocol-src/spinel-basis-glossary.md
- doc/spinel-protocol-src/spinel-feature-jam-detect.md
- doc/spinel-protocol-src/spinel-prop-core.md
- doc/spinel-protocol-src/spinel-prop-debug.md
- doc/spinel-protocol-src/spinel-prop-mac.md
- doc/spinel-protocol-src/spinel-prop-overview.md
- doc/spinel-protocol-src/spinel-prop.md
- doc/spinel-protocol-src/spinel-security-considerations.md
- doc/spinel-protocol-src/spinel-tech-thread.md
This pull request contains various minor changes to help with readability.
> Spinel Changes

- src/cli/cli_coap.cpp
> Fix typo when coap error message is received

- src/core/meshcop/dataset_manager.cpp
> Fix inconsistency between prototype and implementation.

- include/openthread/openthread.h
- src/ncp/ncp_spi.cpp
No code/logic change in this PR. Updating comments only.
> Change/fix few remaining `kThreadError` (referenced in comments) to `OT_ERROR`.

- AUTHORS
Add Synopsys, Inc. to the AUTHORS file. Thanks.
> Add Synopsys to the AUTHORS file

- examples/platforms/nrf52840/radio.c
- third_party/NordicSemiconductor/drivers/nrf_drv_radio802154.c
- third_party/NordicSemiconductor/drivers/nrf_drv_radio802154.h
This PR prepares the nRF52840 platform for #1790
> Pass ACK frames to OT Radio Platform layer in nRF52840 platform

- src/ncp/hdlc.cpp
- src/ncp/ncp_base.cpp
- src/ncp/ncp_base.hpp
- src/ncp/ncp_buffer.cpp
- src/ncp/ncp_uart.cpp
This commit contains no code/logic change. It is cosmetic change only,
fixing alignments/spacing in some of file under `/ncp` folder.
> Fix spacing and alignments for `src/ncp` source code

- examples/platforms/kw41z/openthread-core-kw41z-config.h
- examples/platforms/kw41z/radio.c
> KW41Z: Pass up ACK frames to support the new transmit done callback

- examples/platforms/nrf52840/openthread-core-nrf52840-config.h
- examples/platforms/nrf52840/radio.c
- third_party/NordicSemiconductor/drivers/nrf_drv_radio802154.c
- third_party/NordicSemiconductor/drivers/nrf_drv_radio802154.h
> Pass link quality of ACK frame to MAC layer from nRF52840 radio driver.

- src/ncp/ncp_buffer.hpp
(no code/logic change in this PR)
> NcpFrameBuffer: Update documentation/comments about in/out frame buffer pointers

- examples/common-switches.mk
> Add common switch to enable MTD network diagnostic

- examples/platforms/emsk/openthread-core-emsk-config.h
- examples/platforms/emsk/radio.c
#1841 Add new transmit done callback support.
> Support new transmit done callback otPlatRadioTxDone()

- src/core/utils/child_supervision.cpp
- src/core/utils/child_supervision.hpp
- src/core/utils/jam_detector.hpp
This is to follow the coding style guide.
> Change the `#include` header file style under `core/utils`

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle.hpp
> Full End Devices should initiate mesh-under forwarding.

- src/ncp/ncp_base.cpp
NCP handler MLE Prefix, remove duplicate answer
If this is useful, can you explain me?
> NCP handler MLE Prefix, remove duplicate answer

- examples/platforms/nrf52840/alarm.c
This PR fixes a small bug in nrf52840 alarm driver, which caused the alarm to hit  1 ms earlier occasionally.
> Bugfix in nrf52840 alarm driver.

- include/openthread/thread.h
- include/openthread/types.h
- src/core/api/thread_api.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/ncp/ncp_base.cpp
- src/ncp/ncp_base.hpp
- src/ncp/spinel.c
- src/ncp/spinel.h
This PR adds in counters for IP level packets.
> Added ip level counters

- include/openthread/border_router.h
- include/openthread/config.h
- include/openthread/ncp.h
- include/openthread/openthread.h
- include/openthread/thread.h
Also some minor doxygen fixup for public APIs.
> [docs] create separate Border Router doxygen module

- include/openthread/platform/toolchain.h
Update the macro as suggested in #1918.
> [toolchain] update IAR OT_UNUSED_VARIABLE macro

- tools/harness-thci/OpenThread.py
Harness will update the way to pass security policy, e.g.
Present way:
listSecurityPolicy=[True, True, 3600,False, False, True]
Updated Way:
listSecurityPolicy=[3600, 0b11001000]
> [cert] update for new security policy passing way

- src/core/thread/mle.cpp
Frame counter values are stored to non-volatile memory whether or not
the device is attached to a network, since MLE messages are sent prior
to being attached to a network.
> [settings] updates to non-volatile frame counter storage

- .travis/script.sh
- examples/Makefile-posix
(need to rebase after https://github.com/openthread/openthread/pull/1974)
> [build] update configure options in travis script and Makefile-posix

- include/openthread/types.h
- src/core/common/timer.hpp
- src/core/mac/mac_filter.hpp
- src/ncp/ncp_base.cpp
No code/logic change - just alignments and some typo fixes.
> [ncp] fix spacing/alignments and typos in comment

- src/core/crypto/pbkdf2_cmac.cpp
- tests/unit/Makefile.am
- tests/unit/test_ncp_buffer.cpp
- tests/unit/test_pskc.cpp
This PR aims at reducing memcpy() when calculating PSKc. This PR also added unit test for calculating PSKc.
> [crypto] reduce memcpy() usage

- src/core/api/link_api.cpp
- src/core/mac/mac.cpp
> [mac] validate channel in Mac::SetChannel()

- src/core/thread/lowpan.cpp
- src/core/thread/lowpan.hpp
- src/core/thread/mesh_forwarder.cpp
> [lowpan] validate received fragment headers

- examples/platforms/posix/radio.c
- include/openthread/link_raw.h
- include/openthread/platform/radio.h
- src/core/api/link_raw.hpp
- src/core/api/link_raw_api.cpp
- src/core/mac/mac.cpp
- src/ncp/ncp_base.cpp
- src/ncp/ncp_base.hpp
This PR delivers ACK frames to host side by appending this frame content and its metadata to the reply of sending raw stream request.
> [ncp] deliver ACK frame to host side.

- examples/drivers/windows/include/otLwfIoctl.h
- examples/drivers/windows/otApi/otApi.cpp
- examples/drivers/windows/otLwf/radio.c
- examples/drivers/windows/otLwf/tunnel.c
- examples/drivers/windows/otNodeApi/otNodeApi.cpp
- examples/platforms/cc2538/radio.c
- examples/platforms/cc2650/radio.c
- examples/platforms/cc2652/radio.c
- examples/platforms/da15000/radio.c
- examples/platforms/efr32/radio.c
- examples/platforms/emsk/radio.c
- examples/platforms/gp712/radio.c
- examples/platforms/kw41z/radio.c
- examples/platforms/nrf52840/radio.c
- examples/platforms/posix/radio.c
- include/openthread/link.h
- include/openthread/link_raw.h
- include/openthread/platform/radio.h
- src/cli/cli.cpp
- src/core/api/link_api.cpp
- src/core/api/link_raw_api.cpp
- src/core/mac/mac.cpp
- src/core/thread/src_match_controller.cpp
- src/ncp/ncp_base.cpp
- tests/fuzz/fuzzer_platform.c
- tests/unit/test_platform.cpp
- tests/unit/test_platform.h
> [radio] unify around otExtAddress type

- src/core/mac/mac_frame.cpp
- src/core/mac/mac_frame.hpp
- src/core/net/ip6_address.cpp
- src/core/net/ip6_address.hpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
This PR simply decouples mac frame from `ip6_address`.
> [mac] decouple mac frame from ip6 address

- STYLE_GUIDE.md
> [style-guide] note that openthread/config.h must appear first

- src/core/thread/mesh_forwarder.cpp
Update `mStartChildIndex` to next child after the scheduled Indirect Transmission has completed.
> [mesh_forwarder] stay committed to send scheduled Indirect Transmission

- src/core/coap/coap.cpp
This PR fixes the issue responding to CoAP request with message id 0.
> [coap] fix handling message id 0.

- examples/Makefile-da15000
- examples/platforms/da15000/Makefile.am
- examples/platforms/da15000/cortex-m_cstartup.c
- examples/platforms/da15000/crypto/aes_alt.c
- examples/platforms/da15000/crypto/aes_alt.h
- examples/platforms/da15000/crypto/da15000-mbedtls-config.h
- examples/platforms/da15000/custom_config_qspi.h
- third_party/dialog/DialogSDK/bsp/include/system_DA14680.h
- third_party/dialog/DialogSDK/bsp/peripherals/include/hw_aes_hash.h
- third_party/dialog/DialogSDK/bsp/peripherals/include/hw_crypto.h
- third_party/dialog/DialogSDK/bsp/peripherals/src/hw_aes_hash.c
- third_party/dialog/DialogSDK/bsp/peripherals/src/hw_crypto.c
- third_party/dialog/DialogSDK/bsp/peripherals/src/hw_dma.c
- third_party/dialog/DialogSDK/bsp/peripherals/src/hw_otpc.c
HW accelerator is used for AES in DA15000 platform.
> [da15000] AES Hardware support

- examples/platforms/da15000/radio.c
- third_party/dialog/DialogSDK/interfaces/ftdf/src/ad_ftdf_phy_api.c
* Radio Recieve is based on interrupts
* Retransmit mechanism is corrected
> [da15000] various improvemets for da15000 radio

- tests/scripts/thread-cert/Cert_6_1_01_RouterAttach.py
- tests/scripts/thread-cert/message.py
This commit adds traffic analysis to test Cert_6_1_01_RouterAttach.
> [tests] add traffic analysis to Cert_6_1_01_RouterAttach

- src/core/mac/mac_frame.cpp
It helps to reduce 176 bytes image size.
> [mac_frame] simplify ValidatePsdu() function

- examples/platforms/efr32/radio.c
Fix #2138 building efr32 platform error.
> [efr32] fix build casting warnings on pointer type

- tools/harness-automation/autothreadharness/runner.py
Restart of explorer.exe at the end of every test suite interferes with our continuous integration test plans, so we always have to comment this section before running our tests. I added an option to disable this feature when running the script.
> [harness-automation] add option to not restart explorer.exe at the end

- src/ncp/ncp_base_mtd.cpp
This commit also simplifies the implementation for `ON_MESH_NETS`
get handler.
> [ncp] reset iterator in get handler of `OFF_MESH_ROUTES` for local network data.

- src/core/thread/network_data.cpp
- src/core/thread/network_data_leader_ftd.cpp
> [network-data] stable flag fix

- src/core/meshcop/dataset_manager.cpp
The Delay Timer value has a 32-bit range.  However, the current Timer
implementation does not support the full 32-bit range.
This commit fixes the handling of large Delay Timer values by splitting
the delay across multiple timer triggers.
> [pending-dataset] fix handling of large Delay Timer values

- src/core/meshcop/dataset_manager.cpp
sorry, have to create new PR due to stupid operations making #2163 unable to be reopened.
> [pending-dataset] MGMT_PENDING_GET.rsp must include Delay Timer TLV

- tests/scripts/thread-cert/Cert_5_2_05_AddressQuery.py
- tests/scripts/thread-cert/Makefile.am
- tests/scripts/thread-cert/command.py
- tests/scripts/thread-cert/config.py
- tests/scripts/thread-cert/node.py
- tests/scripts/thread-cert/node_cli.py
Add two fuctions in node.py node_cli.py to get mesh local prefix and get
node's address.
Modify the mesh local prefix in config.py.
> [tests] Add traffic analysis for Cert_5_2_05_AddressQuery.py.

- src/ncp/spinel.c
This change addresses an input validation error when parsing malformed Spinel string fields. This change may have security implications.
This change also proactively adds an additional sanity check on the size of the data buffers being passed to the pack/unpack functions, limiting the maximum input size to 32767 bytes.
With the Spinel data packing format, fields with the type `U` are zero-terminated strings. Failure to zero-terminate a string is a syntax error that usually causes `spinel_datatype_vunpack_` to explicitly fail. However, if there were no bytes left in the unparsed data buffer when the parser gets to parsing a string field, then this condition is triggered and undefined behavior results.
This bug could allow an attacker that is already in control of either the NCP or the host …
> [spinel] Improve string field parse checks

- include/openthread/cli.h
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/cli/cli_uart.cpp
This PR adds a simple method to extend built-in CLI with user defined commands.
> [cli] add support for extending CLI with user commands

- src/ncp/ncp_buffer.cpp
Fixing Coverity identified issues...
> [ncp-buffer] initialize mReadDirection

- src/core/mac/mac.hpp
- src/core/net/icmp6.hpp
- src/core/openthread-core-default-config.h
- src/core/thread/lowpan.cpp
- src/core/thread/lowpan.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/network_data_leader.hpp
- src/core/thread/thread_netif.cpp
nit: This PR fixes some variable names. Accumulated from some time :)
> [style] minor coding standard fixes

- src/core/thread/link_quality.cpp
Add in filtering for invalid 127 RSSI in the last rssi field
> [link-quality] last RSSI ignore invalid RSSI

- examples/platforms/nrf52840/diag.c
- examples/platforms/nrf52840/usb-cdc-uart.c
- include/openthread/platform/toolchain.h
- src/core/meshcop/dataset_manager.cpp
- src/ncp/spinel.c
- third_party/NordicSemiconductor/dependencies/sdk_config.h
- third_party/NordicSemiconductor/drivers/radio/fem/nrf_fem_control_common.c
- third_party/NordicSemiconductor/drivers/radio/fem/nrf_fem_control_direct.c
- third_party/NordicSemiconductor/drivers/radio/fem/nrf_fem_control_softdevice.c
A couple of IAR warning fixes, mostly in nRF52840 platform.
> [iar] warning fixes

- src/core/thread/thread_tlvs.hpp
> [network-data] fix pointless integer comparison warning

- examples/platforms/nrf52840/radio.c
This PR will help to handle MAC layer receive error counters properly in nRF52840 platform.
> [nRF52840] add receive error handler to radio driver

- include/openthread/border_router.h
> [docs] fix Doxygen error

- include/openthread/types.h
- src/cli/cli.cpp
- src/core/api/message_api.cpp
* Include application CoAP messages and buffers
* Include cached messages and buffers
> [message] extend buffer info provided by otMessageGetBufferInfo()

- examples/drivers/windows/otApi/otApi.cpp
- include/openthread/types.h
- src/cli/README.md
- src/cli/cli.cpp
- src/core/common/logging.cpp
- src/core/mac/mac.cpp
- src/core/mac/mac_filter.cpp
- src/core/mac/mac_filter.hpp
- src/ncp/ncp_base_mtd.cpp
Supplemental updates for mac filter in #1967
> [mac] rename mRxWhitelistFiltered to mRxAddressFiltered

- tools/harness-automation/autothreadharness/pdu_controller.py
- tools/harness-automation/autothreadharness/pdu_controller_factory.py
- tools/harness-automation/autothreadharness/settings_sample.py
I added new pdu controller class for devices which we want to use to perform power cycles before test cases.
> [harness-automation] add IpPowerSocketPduController class

- tests/scripts/thread-cert/Cert_5_2_07_REEDSynchronization.py
- tests/scripts/thread-cert/Cert_5_3_01_LinkLocal.py
- tests/scripts/thread-cert/Cert_5_3_02_RealmLocal.py
- tests/scripts/thread-cert/Cert_5_3_03_AddressQuery.py
- tests/scripts/thread-cert/command.py
- tests/scripts/thread-cert/config.py
- tests/scripts/thread-cert/message.py
- tests/scripts/thread-cert/node_cli.py
-Add a method in message.py to verify if receive a ICMPv6 message.
-Add two methods in command.py to verify link request and link accept.
>  [tests] add traffic to 4 test cases: from Cert_5_2_07 to Cert_5_3_03

- include/openthread/commissioner.h
- include/openthread/openthread.h
- include/openthread/server.h
- Moved Server API into the proper Doxygen group
- Minor wording / tag corrections
> [docs] Doxygen fixes

- src/core/thread/mle_router.cpp
Since #2217,  RouterId would be released immediately when not heard for `kMaxNeighborAge` as `RemoveNeighbor() `would update last heard time but `age` is not re-computed after `RemoveNeighbor() ` https://github.com/openthread/openthread/blob/master/src/core/thread/mle_router.cpp#L1963
Also include some other minor fixes for right initial routing information of new active router.
> [mle] fix router id release issue introduced in #2217

- tests/scripts/thread-cert/Cert_5_3_03_AddressQuery.py
Both #2316 and #2314 are easily fail on this case.
> [tests] fix the unstable Cert_5_3_03

- examples/platforms/nrf52840/uart.c
The main purpose behind is to configure UART GPIOs only when CLI/NCP is used.
> [nrf52840] move UART initialization from PlatformInit to otPlatUartEnable

- src/core/common/instance.cpp
> [instance] fix strict-aliasing warning for gcc6

- src/core/coap/coap.cpp
See https://github.com/openthread/openthread/issues/2369
> [coap] set the interfaceId on retransmission

- src/diag/diag_process.cpp
- src/diag/diag_process.hpp
- tests/unit/test_diag.cpp
So then platforms could define their own sleep behavior.
> [diag] remove diag sleep command

- src/core/mac/mac.cpp
This commit moves `StartCsmaBakcoff()` and `SentFrame()` methods in
`Mac.cpp` so that all tx related methods are close to one another.
> [mac] move tx related methods close to each other

- script/bootstrap
> [setup] add basic macos tools

- tools/harness-thci/OpenThread.py
TH needs this new API for new TCs
> [cert] THCI: add diagnosticQuery() API

- src/core/mac/mac.cpp
- src/core/mac/mac.hpp
This commit contains the following changes: It simplifies the MAC
scan implementation by adding common helper  methods such as
`UpdateScanChannel()`.  It also fixes an issue where invoking back-to-
back scan could cause the handler to be overwritten with NULL. It adds
support for special case of Energy Scan with zero scan duration to
collect a single RSSI sample per channel.
> [mac] simplify scan implementation

- src/core/api/thread_ftd_api.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/mle_router_ftd.hpp
> [meshcop] use joiner id when enabling discovery response filter

- src/core/mac/mac.cpp
This commit changes the implementation of zero-duration energy scan
operation so that all RSSI samples (for different channels) are taken
within the same tasklet. This ensures that the zero-duration energy
scan operation can be performed quickly and radio is switched to its
normal channel avoiding any delays caused by other tasklets and/or
platform operations.
> [mac] zero-duration energy scan from single tasklet

- include/openthread/ip6.h
- include/openthread/types.h
Fixing a few mistakes and updating for consistency.
> [docs] update Doxygen comments

- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
Thanks for @zhaxia's observations during stress tests on Cert_5_5_08 when not removing tmp/ directory and his help on validating these fixes.
> [mle] fix some corner cases when trying to attach to a better partition

- include/openthread/types.h
Missed one from my last update...
> [docs] add Doxygen tag

- src/core/thread/mle_router.cpp
This commit fixes the following issues:
1. The advertise timer is no longer stopped when sending an Address Solicit
message.  This ensures that a REED continues to send MLE Advertisements.
2. The advertise timer is always started after becoming a child, even when
the router upgrade threshold is not yet met.  This ensures that a REED
will start sending MLE Advertisements.
> [mle] updates to advertise timer management

- src/core/thread/mle.cpp
This commit changes the checks in `Mle::SendChildUpdateRequest()` so
that if there is no valid/restoring parent the device immediately
becomes detached and will go through full attach process.
This addresses an issue with an end-device failing to re-attach after
reset in case the device can restore its network info from
settings/flash but there is no parent info entry in the settings.
> [mle] become detached if no valid parent when sending "Child Update Request"

- examples/platforms/samr21/Makefile.am
- examples/platforms/samr21/README.md
This pull request contains fixes addressed in https://github.com/openthread/openthread/issues/2548.
> [samr21] Fix gcc 7 compilation issue and update README.md

- etc/visual-studio/libopenthread-windows.vcxproj
- examples/platforms/cc2538/Makefile.am
- examples/platforms/cc2538/diag.c
- examples/platforms/cc2650/Makefile.am
- examples/platforms/cc2650/diag.c
- examples/platforms/cc2652/Makefile.am
- examples/platforms/cc2652/diag.c
- examples/platforms/efr32/Makefile.am
- examples/platforms/efr32/diag.c
- examples/platforms/efr32/platform-efr32.h
- examples/platforms/gp712/Makefile.am
- examples/platforms/gp712/diag.c
- examples/platforms/kw41z/Makefile.am
- examples/platforms/kw41z/diag.c
- examples/platforms/posix/Makefile.am
- examples/platforms/posix/diag.c
- examples/platforms/posix/spi-stubs.c
- examples/platforms/samr21/Makefile.am
- examples/platforms/samr21/diag.c
- tests/unit/Makefile.am
- tests/unit/test_diag.cpp
Running "make pretty" (new code-style) with `--enable-diag` configure option.
> [code-style] make diag related file pretty

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mle.cpp
> [mle] set rx-on-when-idle when stopping Thread

- examples/platforms/gp712/Makefile.am
> [gp712] fix typo in Makefile.am

- examples/platforms/efr32/platform-efr32.h
> [efr32] fix compile error due to include ordering

- tests/scripts/thread-cert/Cert_5_1_09_REEDAttachConnectivity.py
This commit adds necessary delay to allow the REEDs to establish links with
neighboring routers.
> [tests] fix occasional failures in Cert_5_1_09_REEDAttachConnectivity.py

- tests/scripts/thread-cert/Cert_5_2_01_REEDAttach.py
This commit adds delay to allow routes to form between REED1 and Leader.
> [tests] fix occasional failures in Cert_5_2_01_REEDAttach.py

- src/core/Makefile.am
- src/core/api/link_raw_api.cpp
- src/core/coap/coap.cpp
- src/core/coap/coap_header.cpp
- src/core/common/random.hpp
- src/core/common/trickle_timer.cpp
- src/core/mac/mac.cpp
- src/core/net/dhcp6_client.cpp
- src/core/net/ip6_mpl.cpp
- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle_router.cpp
- src/core/thread/topology.cpp
- src/core/thread/topology.hpp
- src/core/utils/channel_manager.cpp
- src/core/utils/channel_monitor.cpp
- src/core/utils/jam_detector.cpp
- src/core/utils/slaac_address.cpp
- src/core/utils/slaac_address.hpp
This commit adds a new header file `common/random.hpp` which
provides functions related to generating random numbers including
a helper function `FillBuffer()` which fills a given buffer with
random bytes. The OpenThread core files are updated to use the
new helper functions.
> [random] adding random utility functions

- src/core/meshcop/leader.cpp
> [meshcop] update Border Agent Locator TLV on keep alives

- src/core/meshcop/dataset_local.cpp
This commit reduces stack usage when writing operational datasets to
non-volatile by writing out dataset as given and moving the cleanup of TLVs
when reading the dataset out of non-volatile.
> [operational-dataset] optimize storing dataset to non-volatile

- examples/platforms/efr32/logging.c
- examples/platforms/kw41z/logging.c
> [logging] remove deprecated use of OPENTHREAD_ENABLE_CLI_LOGGING

- .travis/before_install.sh
This seems to help with recent posix travis failures like [this](https://travis-ci.org/openthread/openthread/builds/354706060?utm_source=github_status&utm_medium=notification).
> [travis] fix pip install issue

- examples/platforms/efr32/radio.c
> [efr32] pass up received ACK frame

- examples/platforms/nrf52840/radio.c
> [nrf52840] fix IAR warning in radio.c

- examples/platforms/nrf52840/radio.c
- third_party/NordicSemiconductor/drivers/radio/mac_features/nrf_802154_filter.c
- third_party/NordicSemiconductor/drivers/radio/nrf_802154.c
- third_party/NordicSemiconductor/drivers/radio/nrf_802154.h
- third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.c
- third_party/NordicSemiconductor/drivers/radio/nrf_802154_critical_section.c
- third_party/NordicSemiconductor/drivers/radio/nrf_802154_priority_drop.h
- third_party/NordicSemiconductor/drivers/radio/nrf_802154_priority_drop_direct.c
- third_party/NordicSemiconductor/drivers/radio/nrf_802154_priority_drop_swi.c
- third_party/NordicSemiconductor/drivers/radio/nrf_802154_request_direct.c
- third_party/NordicSemiconductor/drivers/radio/nrf_802154_request_swi.c
- third_party/NordicSemiconductor/drivers/radio/nrf_802154_revision.c
- third_party/NordicSemiconductor/drivers/radio/nrf_802154_swi.c
- third_party/NordicSemiconductor/drivers/radio/nrf_802154_swi.h
- third_party/NordicSemiconductor/drivers/radio/raal/single_phy/single_phy.c
- third_party/NordicSemiconductor/drivers/radio/raal/softdevice/nrf_raal_softdevice.c
> [nrf52840] update radio driver to version 1.1.0

- configure.ac
- script/bootstrap
- script/clang-format.sh
Different version *clang-format* have different pretty results. This PR make sure to use clang-format 5.0.
> [code-style] require clang-format-5.0

- tools/spi-hdlc-adapter/spi-hdlc-adapter.c
This commit changes the `spi-hdlc-adapter` retry logic when the slave
is busy (it refuses a transmission). There are three levels, initially
the retries happen almost immediately, then up to certain number of
attempts at a fast rate and finally it drops to a slow rate.
This change helps with the average delay of spinel message exchange
between NCP and host (connected using an SPI interface).
> [spi-hdlc-adapter] enhance the retry logic when slave is busy

- tests/toranj/start.sh
This commit adds `cleanup()` function in the `toranj` start script.
The cleanup code removes logs and any flash files, issues a `killall`
to remove any lingering `wpantund` instances (`wpantund` processes may
still be running from previous `wpan.Node` objects which are not yet
garbage collected by python). It also deletes any `wpan<num>` network
interfaces (this addresses the situation where even after `killall
wpantund` the network interface may stay active by kernel for some
short time, not allowing the next test-case to create network
interface with same name).
> [toranj] add cleanup code after every test-case

- src/core/Makefile.am
- src/core/common/instance.hpp
- src/core/crypto/mbedtls.cpp
- src/core/openthread-core-default-config.h
- src/core/utils/heap.cpp
- src/core/utils/heap.hpp
- tests/unit/Makefile.am
- tests/unit/test_heap.cpp
* move heap into utils namespace
* add api to get free space of heap
> [utils] make heap for general use

- src/core/api/link_raw_api.cpp
Allow software implementations of link layer features even when hardware
supports.
> [radio] fix link raw caps calculation

- examples/platforms/nrf52840/radio.c
This pull request should fix issue #2664 
Signed-off-by: Duda, Lukasz <Lukasz.Duda@nordicsemi.no>
> [nrf52840] fix race condition when reporting channel busy event

- examples/platforms/cc2538/radio.c
It seems TI (for whatever reason) chose to use a rather unorthadox
mixed-endian representation for the MAC address in the CC2538, where the
most significant 4 octets are given first in little-endian order,
followed by the least significant 4 octets (again in little-endian).
The OpenThread code expects a big-endian representation of the MAC, so
we need to read in and byte-swap each half individually.
> [cc2538] fix IEEE EUI-64 address word ordering

- src/core/mac/mac.cpp
- src/core/meshcop/joiner_router.cpp
- src/core/thread/data_poll_manager.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/mle_router.cpp
- src/core/thread/network_data_local.cpp
- src/core/thread/network_diagnostic.cpp
This commit adds helper methods in `Mle` class to check whether
different flags are set in device mode, such as `IsRxOnWhenIdle()`,
`IsFullThreadDevice()`.
> [mle] add helper methods to check device mode flags

- src/core/net/ip6_mpl.cpp
- src/core/thread/router_table.hpp
Modify the interface for dynamic MPL interval (update to #2738)
> [mpl] update dynamic MPL interval according to new interface

- src/cli/cli.cpp
- src/cli/cli_dataset.cpp
- src/cli/cli_udp_example.cpp
- src/core/common/code_utils.hpp
- src/core/meshcop/commissioner.cpp
- src/core/net/netif.cpp
- src/core/thread/mle.cpp
- src/ncp/changed_props_set.cpp
- src/ncp/ncp_base.cpp
- src/ncp/ncp_base_mtd.cpp
- tests/unit/test_child.cpp
- tests/unit/test_child_table.cpp
- tests/unit/test_link_quality.cpp
- tests/unit/test_mac_frame.cpp
- tests/unit/test_network_data.cpp
- tests/unit/test_timer.cpp
This commit adds helper macro `OT_ARRAY_LENGTH()` to get the number
of elements in an array.
> [code-utils] adding helper macro OT_ARRAY_LENGTH()

- examples/drivers/windows/include/otLwfIoctl.h
- examples/drivers/windows/otApi/otApi.cpp
- examples/drivers/windows/otLwf/iocontrol.c
- examples/drivers/windows/otLwf/iocontrol.h
- include/openthread/thread_ftd.h
- src/cli/cli.cpp
> [cli] fix router table command

- src/core/thread/mle_router.cpp
During application development i found that Thread routers cannot transmit frames for couple of seconds to other routers after re-synchronization (after reset).
Normally, router uses the value in the **Link Margin TLV** that it receives to calculate an initial outgoing quality for that neighbor. This avoids the need to wait for the neighbor to send an MLE Advertisement before establishing a routing cost to the neighbor.
However, when we are in DETACHED state, we don't analyze Link Margin TLV in Link Accept message.
This PR fix this problem, and analyze Link Margin TLV in detached state only if it appears in the packet. I found Thread Specification very ambiguous when it comes to this TLV in the Link Accept message.
Section 4.7.7.3 does not include Link Margin TLV, but in other hand table …
> [mle] read Link Margin TLV from Link Accept in detached state

- src/core/thread/mle.cpp
This commit adds MLE Data Request timeout and retransmissions for
rx-off-when-idle devices.  rx-on-when-idle devices do not require explicit
retransmissions because MLE Advertisements will trigger an rx-on-when-idle
device to send the MLE Data Request again.  However, if an rx-off-when-idle
device fails to receive an MLE Data Response, it will never attempt to
request again.
> [mle] implement MLE Data Request retransmissions

- src/core/thread/network_diagnostic.cpp
> [network-diagnostic] REED should omit ChildTable TLV request

- tests/toranj/start.sh
- tests/toranj/test-011-child-table.py
- tests/toranj/wpan.py
This test covers the following:
- `wpantund` child table property "Thread:ChildTable" 
- Child recovery after router/parent reset.
> [toranj] add test-case for child table and child recovery

- etc/docker/Makefile
- etc/docker/README.md
- etc/docker/arm32v7_ubuntu_wpantund/Dockerfile
- etc/docker/ot_sim/Dockerfile
- etc/docker/ot_sim/README.md
- etc/docker/ot_sim/add_node
- etc/docker/ot_sim/start_sim
- etc/docker/ot_sim/stop_sim
- etc/docker/x86_ubuntu_wpantund/Dockerfile
These Dockerfiles build two wpantund images for ARMv7 and x86, as well as a tiny image for OpenThread simulator.
> [docker] dockerfiles for openthread sim and wpantund

- src/core/thread/network_diagnostic_tlvs.hpp
- src/core/thread/router_table.cpp
Code cleanups, as discussed in #2802
> [mle] minor TLV and route table cleanup

- src/core/thread/mle_router.cpp
This is intended to avoid situations that can trigger the assert in `MleRouter::HandleParentRequest()`:
https://github.com/openthread/openthread/blob/7c7c179a38843e83f7fc27990fc0aa6076168659/src/core/thread/mle_router.cpp#L1530
> [router-table] clear router table when changing partitions

- examples/platforms/nrf52840/radio.c
> [nrf52840] fix building with link raw enabled

- src/core/thread/child_table.cpp
- src/core/thread/child_table.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
- tests/unit/test_child_table.cpp
Thanks to @zhanglongxia for noticing this.
> [child-table] fix typo in constant name

- src/ncp/ncp_base.hpp
- src/ncp/ncp_base_dispatcher.cpp
This commit contains no code/logic change.
> [ncp] update/add comments and re-order handler lookup

- src/core/thread/mle_router.cpp
This commit changes the code such that the logs are emitted only if
the route table is updated. It also changes the log format.
> [mle-router] update the route table log message

- src/core/thread/thread_netif.cpp
fix no response issue for `networkdiagnostic get ff02::1 0 1`
> [core] update tmf rules to allow link local multicast address as dest

- .travis.yml
- .travis/before_install.sh
- .travis/script.sh
- Android.mk
- include/openthread-config-android.h
- src/posix/platform/flash.c
- src/posix/platform/misc.c
- src/posix/platform/openthread-core-posix-config.h
- src/posix/platform/radio_spinel.cpp
* add makefile to build on android build system
* add a test verifying building on android environment
> [posix-app] add Makefile for building with android build system

- include/openthread/openthread.h
- Remove TMF Proxy entry
- Add UDP Proxy, Network Time Synchronization, and Time Service entries
- Add UDP grouping
> [docs] update API menu for new APIs

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
The keep alive timer was not restarted on receiving COMM_KA.
> [meshcop] fix handling commissioner keep alive

- examples/Makefile-efr32
- examples/platforms/efr32/Makefile.am
- examples/platforms/efr32/Makefile.platform.am
- examples/platforms/efr32/fem-control.c
- third_party/mbedtls/Makefile.am
> [efr32] update to Gecko SDK v2.3

- include/openthread/commissioner.h
- src/core/api/commissioner_api.cpp
- src/core/meshcop/commissioner.cpp
- src/core/meshcop/commissioner.hpp
----
Added this to simplify/enable exposing the URL as a spinel property later.
> [commissioner] add new API to get Provisioning URL

- examples/platforms/kw41z/radio.c
The MKW41Z Reference Manual Section 44.6.2.7 states:
- "The 802.15.4 Link Layer software prepares data to be transmitted, by
loading the octets, in order, into the Packet Buffer."
This commit maintains a separate buffer for building the transmit frame
then copies the buffer just before the transmit frame is submitted to the
radio.
> [kw41z] load bytes into TX Packet Buffer in order

- include/openthread/types.h
- include/openthread/udp.h
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
- src/core/meshcop/joiner_router.cpp
- src/core/meshcop/joiner_router.hpp
- src/core/meshcop/meshcop.cpp
- src/core/meshcop/meshcop.hpp
- src/core/meshcop/meshcop_tlvs.hpp
- src/core/net/socket.hpp
- src/core/net/udp6.cpp
- src/core/net/udp6.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mle.cpp
- src/core/thread/mle.hpp
- src/core/thread/thread_uri_paths.hpp
This PR implements the Mesh Commissioning UDP proxy.
> [meshcop] implement commissioning UDP proxy

- examples/platforms/posix/radio.c
- include/openthread-config-android.h
- src/posix/platform/radio_spinel.cpp
* don't compute CRC in promiscuous mode
* call `otPlatDiagRadioTransmitDone()` when transmit is done
* don't wait for ACK in promiscuous mode
> [posix-app] fix diag issues of radio only mode

- examples/platforms/efr32/radio.c
> [efr32] fix em_system.h include

- .travis/before_install.sh
- .travis/script.sh
This fixes the host tool acp compile error.
> [test] enhance android build check

- src/core/meshcop/dataset_manager_ftd.cpp
This commit corrects one misunderstanding and fixes the 9.2.9R in TH R49.3.
> [dataset] update active/pending dataset based on existing active dataset

- tools/harness-thci/README.md
> [docs] revise THCI README

- .travis.yml
- .travis/script.sh
- examples/Makefile-posix
- examples/platforms/posix/platform-posix.h
- examples/platforms/posix/sim/alarm-sim.c
- examples/platforms/posix/sim/platform-sim.c
- examples/platforms/posix/sim/radio-sim.c
- examples/platforms/posix/uart-posix.c
- src/core/net/icmp6.cpp
- src/posix/Makefile-posix
- src/posix/platform/Makefile.am
- src/posix/platform/alarm.c
- src/posix/platform/openthread-core-posix-config.h
- src/posix/platform/platform-posix.h
- src/posix/platform/radio_spinel.cpp
- src/posix/platform/radio_spinel.hpp
- src/posix/platform/sim.c
- src/posix/platform/system.c
- src/posix/platform/uart.c
- tests/scripts/thread-cert/Cert_5_1_07_MaxChildCount.py
- tests/scripts/thread-cert/Cert_6_3_02_NetworkDataUpdate.py
- tests/scripts/thread-cert/Cert_6_5_01_ChildResetSynchronize.py
- tests/scripts/thread-cert/node.py
- tests/scripts/thread-cert/node_cli.py
- tests/scripts/thread-cert/simulator.py
- tests/unit/Makefile.am
- tests/unit/test_diag.cpp
- third_party/openthread-test-driver/test-driver
This PR mainly adds virtual time support for posix-apps. This PR depends on openthread/pyspinel#43
> [posix-app] enhance virtual time for posix app

- .travis.yml
- .travis/before_install.sh
- .travis/script.sh
- src/posix/platform/alarm.c
This PR also fakes a radio only device to check posix app working in device mode.
> [posix-app] fix alarm issue on real device

- include/openthread/platform/radio.h
> [radio] update definition of `otRadioCaps` and the related constants

- src/ncp/Makefile.am
- src/posix/platform/Makefile.am
- src/posix/platform/frame_queue.cpp
This may help improve code coverage.
> [tests] enable self tests

- src/core/thread/mle.cpp
This commit adds a log line(at log level `OT_LOG_LEVEL_NOTE`) to
indicate the mode change and the new mode value.
> [mle] log Thread Mode change

- src/posix/platform/radio_spinel.cpp
----
Should help address https://github.com/openthread/openthread/issues/3043.
> [posix-app] clear and free mTxRadioTid from Receive

- examples/drivers/windows/otApi/otApi.cpp
> [windows] resolve uninitialized memory warning

- tests/toranj/start.sh
- tests/toranj/test-024-partition-merge.py
---
```
Network Topology:
r1 ---- / ---- r2
|       \      |
|       /      |
c1      \      c2
```
Test covers the following situations:
- `r2` forming its own partition when it can no longer hear `r1`
- Partitions merging into one once `r1` and `r2` can hear each other again
- Adding on-mesh prefixes on each partition and ensuring after merge the info in combined.
> [toranj] new test to check partition formation and merging

- src/posix/platform/radio_spinel.cpp
----
This commits addresses an issue where TxDone callback may be invoked with a long delay.
> [poisx-app] fix delayed TxDone callback

- src/core/coap/coap.cpp
- src/core/coap/coap.hpp
- src/core/common/message.cpp
- src/core/common/message.hpp
- src/core/meshcop/joiner_router.cpp
- src/core/net/ip6.cpp
- src/core/net/ip6.hpp
- src/core/net/udp6.cpp
- src/core/net/udp6.hpp
- src/core/thread/mesh_forwarder.hpp
- src/core/thread/mesh_forwarder_ftd.cpp
- src/core/thread/mesh_forwarder_mtd.cpp
- src/core/thread/mle.cpp
Free low priority messages when there is no enough memory for the high priority message.
> [message] create new messages with priority

- src/ncp/spinel.c
- src/ncp/spinel.h
> [spinel] add spinel_command_to_cstr() and update strings

- include/openthread/error.h
- include/openthread/instance.h
- Add api-coap-secure to main Doxygen menu
- Remove @ sa tag that doesn't render properly on openthread.io
> [docs] minor Doxygen fixes

- tools/harness-thci/OpenThread.py
- tools/harness-thci/OpenThread_WpanCtl.py
> [thci] wpanctl firmware validation and modify getGUA according to GRL change

- src/posix/platform/logging.c
- src/posix/platform/platform-posix.h
- src/posix/platform/system.c
---
This PR moves the init of syslog to the `logging.c` from `system.c`.
> [posix-app] update the logging implementation

- tests/toranj/start.sh
- tests/toranj/test-026-slaac-address.py
---
This test is expected to fail now. It would pass with https://github.com/openthread/wpantund/pull/355 merged.
> [toranj] adding test-026 for addition/removal of SLAAC IPv6 address

- src/core/thread/mesh_forwarder.cpp
- src/core/thread/mesh_forwarder_ftd.cpp
This commit makes the following changes in `MeshForwarder`:
- It separates the logging of sent direct and indirect messages,
ensuring that for indirect messages the status (success/failure)
is logged after all retry attempts.
- It updates the log message (status of transmission) for a larger
message requiring fragmentation and multiple frame transmissions
when `CONFIG_DROP_MESSAGE_ON_FRAGMENT_TX_FAILURE` is not enabled.
- It fixes managing of `IpCounters` to only account for messages
with type `kTypeIp6`.
> [mesh-forwarder] update indirect message logs

- src/posix/platform/radio_spinel.cpp
> [posix-app] exit on untimely RCP crash/reset

- .travis/script.sh
- examples/platforms/posix/radio.c
- include/openthread/network_time.h
- src/core/mac/mac.cpp
- src/core/mac/mac_frame.cpp
- src/core/thread/time_sync_service.cpp
- src/core/thread/time_sync_service.hpp
Also enable time sync in a travis check.
> [time-sync] fix build issue with time sync enabled

- include/openthread/Makefile.am
- include/openthread/border_agent.h
- include/openthread/instance.h
- src/core/api/border_agent_api.cpp
- src/core/meshcop/border_agent.cpp
- src/core/meshcop/border_agent.hpp
> [border-agent] border agent state event

- src/posix/platform/udp.cpp
Set interface id of message received from interfaces other than Thread network interface to 0.
> [platform-udp] fix processing message received from other interface 

- examples/platforms/efr32/platform-efr32.h
> [efr32] add missing instance header include

- tools/harness-thci/OpenThread_WpanCtl.py
- differentiate serial login scenarios and improve serial login experience
- shorten command sending and validating process
- fix ping issue (no impact on NCP DUT certification)
> [thci] enhancements for ncp device

- .travis/script.sh
- configure.ac
- examples/common-switches.mk
- include/openthread/Makefile.am
- include/openthread/error.h
- include/openthread/sntp.h
- src/cli/README.md
- src/cli/cli.cpp
- src/cli/cli.hpp
- src/core/Makefile.am
- src/core/api/sntp_api.cpp
- src/core/common/instance.hpp
- src/core/net/sntp_client.cpp
- src/core/net/sntp_client.hpp
- src/core/openthread-core-default-config.h
- src/core/thread/thread_netif.cpp
- src/core/thread/thread_netif.hpp
This PR introduces support for SNTP that includes:
- Basic SNTP Client implementation
- Retransmission mechanism
- CLI example
- CI extension
SNTP client takes around 1.5kB of FLASH and 70 bytes of RAM on nRF52840 platform.
> [sntp] initial implementation of sntp client

- include/openthread/instance.h
- src/core/thread/thread_netif.cpp
This PR adds notification for thread interface up or down.
> [netif] add notification for up or down

- src/core/coap/coap_secure.cpp
- src/core/coap/coap_secure.hpp
This PR defer transmitting CoAP secure messages in order to reduce stack depth.
> [coaps] defer sending coaps message

- include/openthread/error.h
- change udp-proxy to udp-forward
- add api-sntp
> [docs] update Doxygen TOC

- examples/platforms/nrf52840/platform-config.h
- examples/platforms/nrf52840/uart.c
> [nrf52840] fix uart configuration of HWFC

- tests/toranj/test-010-on-mesh-prefix-config-gateway.py
This commit changes `test-010-on-mesh-prefix-config-gateway` to use
`wpan.verify_within` instead of using fixed delays.
> [toranj] update test-010 to use verify_within

- src/posix/platform/radio_spinel.cpp
This commit removes the destination address and PAN Id checks in
`RadioSpinel::RadioReceiev()` method. Radio Co-Processor (RCP)
typically provides such filtering. If not, the same checks are
performed by OpenThread core in `Mac:: HandleReceivedFrame()`.
> [radio-spinel] remove dst address check logic

- src/core/meshcop/border_agent.cpp
- src/core/meshcop/commissioner.cpp
> [meshcop] initialize commissioner ALOC

- etc/docker/README.md
- etc/docker/codelab_otsim/Dockerfile
- etc/docker/environment/Dockerfile
- Added the source Dockerfiles for the codelab_otsim and environment images on Docker Hub
- Updated README
> [docs] added new Dockerfiles

- include/openthread/link.h
- include/openthread/link_raw.h
- src/core/api/link_raw_api.cpp
- src/ncp/ncp_base_radio.cpp
> [link] move otLinkSetShortAddress() decl to link_raw.h

- .travis/check-android-build
- Android.mk
Building spi-hdlc-adapter in this project can save time if there's fix for spi-hdlc-adapter. Together with openthread/wpantund#371
> [android] build spi-hdlc-adapter in OpenThread

- tools/Makefile.am
- tools/spi-hdlc-adapter/spi-hdlc-adapter.c
This PR makes pretty `spi-hdlc-adapter` only, no logic changes in spi-hdlc-adapter.
> [spi-hdlc-adapter] make pretty

- examples/Makefile.am
> [examples] always build examples/platforms/utils

- src/cli/README.md
- src/cli/cli.cpp
- tools/harness-thci/OpenThread.py
After convert s to ms, here is the cmd log
pollperiod
236000
Done
pollperiod 500
Done
pollperiod
500
Done
pollperiod 1
Done
pollperiod
1
Done
> [thci] update `pollperiod` command to accept ms resolution configuration

- Android.mk
This PR fixes newline issue on android build.
> [android] disable UART echo

- tools/harness-automation/cases/med_9_2_10.py
- tools/harness-automation/cases/med_9_2_18.py
- tools/harness-automation/cases/med_9_2_6.py
This pull request fixes changes in Thread Harness v49
> [harness-automation] update device category

- src/core/thread/router_table.cpp
---
No logic change, just loop variable renaming for readability  :)
> [router-table] rename loop variables in UpdateAllocation()

- src/cli/cli.cpp
- src/cli/cli.hpp
- src/cli/cli_dataset.cpp
- src/cli/cli_dataset.hpp
This PR adjusts implementation of dataset sub commands according to #3470 . I hope to do more enhancements after cleaning up as preparation for #3463
> [cli] cleanup dataset implementation

- examples/platforms/da15000/crypto/aes_alt.h
- src/core/Makefile.am
- src/core/coap/coap_message.hpp
- src/core/common/code_utils.hpp
- src/core/utils/heap.cpp
- src/core/utils/heap.hpp
- src/core/utils/static_assert.hpp
This is borrowed from Loki library.
> [code] add static assert

- src/cli/cli_console.cpp
- src/cli/cli_console.hpp
- src/cli/cli_server.cpp
- src/cli/cli_server.hpp
- src/cli/cli_uart.cpp
- src/cli/cli_uart.hpp
Simplify backend interface so that rich output methods can be shared.
> [cli] move output format to server

- src/core/coap/coap_secure.cpp
- src/core/meshcop/dtls.cpp
- src/core/meshcop/dtls.hpp
This commit also adds checks to ensure there is only one outstanding
connection at a time.
> [dtls] simplify dtls state machine

- tests/scripts/thread-cert/Cert_9_2_04_ActiveDataset.py
I found that the class name of Cert_9_2_04 is incorrect, so I changed it.
> [tests] fix class name for Cert_9_2_04

- src/core/net/ip6_mpl.cpp
This commit improves MPL delivery performance by allowing a single Seed ID
to burst multiple MPL packets without suppressing previous transmissions.
> [mpl] allow multiple entries from the same Seed ID

- src/posix/platform/udp.cpp
I didn't notice that some of them are missed in #3579
> [posix-app] fix aliasing issues in platform UDP

- examples/platforms/efr32/flash.c
- examples/platforms/efr32/openthread-core-efr32-config.h
> [efr32] unify flash config around SETTINGS_CONFIG_PAGE_NUM

- Android.mk
- configure.ac
- include/openthread-config-android.h
- src/Makefile.am
- src/posix/Makefile.am
- src/posix/main.c
- src/posix/platform/Makefile.am
- tests/toranj/openthread-core-toranj-config.h
- tests/unit/Makefile.am
This PR merges `OPENTHREAD_ENABLE_POSIX_APP` into `OPENTHREAD_PLATFORM_POSIX_APP`.
> [posix-app] clean up posix app defines

- examples/platforms/efr32/radio.c
Building on recent work that implemented `otPlatRadioGetRssi()`
> [efr32] implement otPlatRadioEnergyScan API

- examples/Makefile-posix
- examples/common-switches.mk
- src/core/thread/mle_router.cpp
* fix typo in common-switches
* fix segment fault with time sync enabled
> [time-sync] fix time sync and typo

- examples/common-switches.mk
> [build] fix SLAAC switch

- src/diag/README.md
- src/diag/diag_process.cpp
- src/diag/diag_process.hpp
> [diag] add radio sleep / receive mode for RF certification

- src/core/meshcop/dtls.cpp
use port number to identify the DTLS session.
> [dtls] simplify logging

- .travis.yml
> [travis] remove posix-app-ncp test due to frequent failures

- src/posix/platform/hdlc_interface.cpp
Convenient for developing on macOS
> [posix-app] more baudrates on macOS

- src/core/meshcop/meshcop_tlvs.cpp
Allows arbitrary number of Channel Mask entries.
> [meshcop] process ChannelMaskTlv in message

- src/cli/README.md
This PR updates CLI documentation related to changes done in #3605
> [doc] update documentation of CLI counters command

- src/core/net/udp6.cpp
> [udp] return error on source port mismatch in Udp::SendTo()

- src/core/thread/network_data_leader_ftd.cpp
previously not compare properly
> [netdata] fix stable network data version when service updates

- include/openthread/message.h
- src/core/api/message_api.cpp
> [core] change return type of otMessageRead()

- src/core/meshcop/dtls.cpp
- src/core/net/udp6.cpp
- src/core/net/udp6.hpp
> [udp] add Udp::IsBound() method

- examples/platforms/nrf52811/spi-slave.c
- examples/platforms/nrf52811/uart.c
- examples/platforms/nrf52840/spi-slave.c
- examples/platforms/nrf52840/uart.c
This PR is an equivalent of #3715 for SPI Slave transport
> [nrf528xx] add otSysEventSignalPending call in spi-slave driver

- Android.mk
- src/cli/cli.cpp
- src/posix/Makefile.am
This PR just add legacy stubs for cli. In future we may fully support
this feature.
> [cli] add legacy stubs in cli
