examples/platforms/nrf52840/Makefile.am, examples/platforms/nrf52840/flash.c, examples/platforms/nrf52840/nrf52840.ld
A couple of minor platform fixes for compability with upcoming Thread SDK:
* Remove unnecessary files from SDK versions of nRF52840 platform libraries,
* Rename section for OpenThread persistent data.
=> [nRF52840] minor platform refactoring

src/core/thread/mle_router.cpp
This commit fixes an overflow issue when forming the Address Registration
TLV within an MLE Child ID Response message.  The overflow can cause the
resulting message to be malformed.
=> [mle] fix bug in forming Child ID Response message

include/openthread/thread_ftd.h, src/core/api/thread_ftd_api.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base.hpp, src/ncp/ncp_base_ftd.cpp, src/ncp/ncp_base_mtd.cpp
This commit adds new public OpenThread API to set callbacks for user to be notified when a child table entry is being added or removed. These callbacks provide info about the child entry and are always invoked before the `otStateChangedCallback`.
This commit also updates the `NcpBase` implementation to use the new callbacks and emit a `VALUE_INSERTED` or `VALUE_REMOVED` async spinel frame to host whenever child table gets updated. If the async spinel frame can not be sent (running out of NCP buffer space), an async `LAST_STATUS(NOMEM)` spinel frame is sent and the entire child table is sent later (when buffer becomes available) as an async `VALUE_IS` spinel message.
The related PR in wpantund: https://github.com/openthread/wpantund/pull/247
=> [child-table] emit child entry inserted/removed from NCP

doc/spinel-protocol-src/spinel-data-packing.md, src/ncp/spinel.c, src/ncp/spinel.h, src/ncp/spinel_decoder.cpp, src/ncp/spinel_decoder.hpp, src/ncp/spinel_encoder.cpp, src/ncp/spinel_encoder.hpp, tests/unit/test_spinel_decoder.cpp, tests/unit/test_spinel_encoder.cpp
This commit adds support for encoding/decoding `uint64_t`/`int64_t`
to spinel as primitive types. `X` and `x` are used as format ASCII
character associated with `uint64_t` and `int64_t` respectively.
This commit also updates the `SpinelEncoder` and `SpinelDecoder`
to add methods related to 64-bit long integer. The related unit test
are also updated.
=> [spinel] add support for 64-bit long signed/unsigned integer

src/diag/diag_process.cpp
The extra receive operation may abort the process of transmit.
=> [diag] remove unnecessary receive operation in DiagReceiveDone()

tests/scripts/thread-cert/Cert_5_6_07_NetworkDataRequestREED.py
Multicast Network Data Response might already have finished in 2s after prefix register. So after restoring the link between Leader and REED, the only way for REED to know there is new Network Data is from the MLE advertisement from Leader. Extending waiting time here may help to stabilize this test.
=> [tests] fix the unstable Cert_5_6_07

tools/harness-thci/OpenThread.py
Fix the abnormal logging in Test Harness Command Window for 8.x tests when TH's resetting device with the default values after each run. It is caused by the competition of serial data reading by _readCommissioningLogs() and __sendCommand().
This issue doesn't impact the test, while this PR is just to ensure expecting logging in TH for 8.x.
=> [cert] THCI: only record commissioning log during 'joining' status

examples/platforms/nrf52840/platform.c
We've decided not to keep assert definition for Keil within platform library.
=> [nRF52840] remove __aeabi_assert definition from platform

examples/platforms/posix/misc.c
When embedding OpenThread CLI in more complex application, it is possible that the application will do utilize `alarm()` or `setitimer()` calls, which cause `SIGALRM` to be delivered to the application with specified delay. For example, linux port of FreeRTOS uses that to implement kernel ticks. Calling `execve` in `otPlatReset()` breaks/conflicts with this behavior: `SIGALRM` handler is being cleared, but the timer itself is not.
So, the resulting situation is that the signal will be delivered to the new application, which might have not set up its own `SIGALRM` handler yet (specifically FreeRTOS sets 1 millisecond ticks) - resulting in the whole process to be killed by system due to unhandled signal.
That accumulates into bigger problems with `wpantund`, which in such situation does …
=> [posix] clear pending alarms in posix platform which could persist execve call

include/openthread/thread_ftd.h, include/openthread/types.h
Some missing parameter documentation was flagged when updating the reference on openthread.io
=> [docs] adding missing parameter documentation

third_party/microchip/include/samr21x18a.ld
Initially fixed size 8k was allocated for stack.
As result there was almost no free RAM. This
change creates stack on all free RAM.
Signed-off-by: Oleksandr Grytsov <al1img@gmail.com>
=> [SAMR21] change stack allocation to use all free RAM

include/openthread/thread_ftd.h, include/openthread/types.h, src/core/thread/mle_router.cpp, src/core/thread/topology.hpp
This commit adds new fields in `otChildInfo` to include the list
of registered IPv6 addresses by the child.
=> [childinfo] include list of registered IPv6 addresses in otChildInfo

src/core/thread/mle_router.cpp
There may be short windows where a device does not have the proper Thread
Network Data.  For example, when a device is coming out of reset and
resynchronizing with the rest of the network.
This commit suppresses MLE Data Response transmissions while the device is
trying to receive the latest Thread Network Data from a neighbor.  This
eliminates the possibility that the device may propagate inconsistent
Thread Network Data.
This commit fixes spurious failures in Cert_9_2_15_PendingPartition.py.
=> [mle] suppress Data Response when trying to update network data

src/cli/cli_udp_example.cpp
The interface identifier is necessary to support link-local and multicast
communication.
=> [cli] add OT_NETIF_INTERFACE_ID_THREAD to UDP example

include/openthread/types.h
Default Router Preferences and More-Specific Routes is RFC 4191.
=> [docs] fix typo in RFC reference

include/openthread/platform/radio.h, src/core/mac/mac.cpp, src/core/openthread-core-default-config.h
Defining OPENTHREAD_CONFIG_DISABLE_CCA_ON_LAST_ATTEMPT to use this
feature.
=> [radio] add field to radio packet enable/disable CCA

doc/spinel-protocol-src/spinel-tech-thread.md, src/ncp/spinel.h
This commit updates the docs in spinel header file to provide
info about format (struct fields) of some properties.
=> [spinel] update docs - property formats

src/core/thread/mle_router.cpp
Recently we have seen a random crashing of NCP.
After debugging I see that there is a problem with assert: 
`mle_router.cpp:4892: void ot::Mle::MleRouter::SignalChildUpdated(..): Assertion error == OT_ERROR_NONE failed.`
This was introduced in #2280 
So basically, whenever Router/Leader (NCP) has stored child in persistent storage, and after reboot previous child does not exist anymore, node tries to remove the child after stored child timeout.
This results in following calls: `MleRouter::RemoveNeighbor -> MleRouter::SignalChildUpdated -> MleRouter::GetChildInfo`
Currently `GetChildInfo `method returns `OT_ERROR_NOT_FOUND `for children with other than valid state. However in the scenario described above, the state of a child is either `kStateRestored `(rx-off) or `kStateChildUpdateRequest …
=> [mle] allow to use GetChildInfo method on restored children

src/ncp/ncp_base_ftd.cpp
GCC 7.2.0 throws: `ncp_base_ftd.cpp:733: error: this statement may fall through.`
I did not analyze the code in great detail, but it seems, that `break` is missing.
=> [ncp] add missing break statement

include/openthread/types.h, src/core/thread/mle_router.cpp, src/ncp/ncp_base_ftd.cpp
This commit adds a new field `mIsStateRestoring` to `otChildInfo`
struct to inform the if the child is being restored. This field is
used in `NcpBase` to filter child entries in restoring state.
---------------------
The fix from https://github.com/openthread/openthread/pull/2353 changes the behavior of `SPINEL_PROP_THREAD_CHILD_TABLE` property (to now include children in "restoring" state). The change in this PR adds logic to filter children in restoring state in `NcpBase` (this is to ensure compatibility with earlier drivers and keeping behavior same).. 
As a possible future improvement it may be good to expose the full child table (all child entries in valid and/or restoring states) from a separate Spinel property.
=> [child-info] add mIsStateRestoring to otChildInfo 

src/cli/cli_uart.hpp, src/core/openthread-core-default-config.h
At present, the buffer sizes for the CLI are hard-coded, to 512 bytes for the receive buffer, 1kB for transmit, and a 128 byte line limit.  In tight memory scenarios, these figures can be unworkable.
The following commits add some configuration parameters to the `openthread-core-config-default.h` header to enable adjustment of these buffer sizes.
=> [cli] make CLI buffer sizes configurable

.travis/script.sh, examples/platforms/cc2650/Makefile.am, examples/platforms/cc2652/Makefile.am
=> [cc26xx] remove -pedantic-errors from cc26xx driverlib build

configure.ac, src/ncp/Makefile.am, src/ncp/example_vendor_hook.cpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base.hpp
This change (requested by @pvanhorn) allows developers to add a hook source file to the NCP build that contains hook for implementing vendor-specific commands. This is done via a new configure script argument, `--with-ncp-vendor-hook-source=<C++FILE>`, with the argument being a single C++ source file containing the hook.
This isn't a terribly elegant solution to this sort of problem, so long-term we should consider major refactoring of the NCP codebase to enable the flexibility of allowing the vendor to implement a library that can be linked in, instead of a file which must be compiled in.
=> [ncp] added support for external NCP vendor hook

include/openthread/server.h, include/openthread/types.h, src/core/api/server_api.cpp, src/core/thread/network_data.cpp
Current implementation doesn't allow to read service ID assigned by the leader after calling `otServiceAdd`+register. This PR adds support for iterating over leader data and retrieving the resulting ID.
=> [network-data] added support for iterating over services from leader data

examples/apps/cli/Makefile.am, examples/apps/ncp/Makefile.am, examples/platforms/Makefile.platform.am, examples/platforms/cc2538/Makefile.platform.am, examples/platforms/cc2650/Makefile.platform.am, examples/platforms/cc2652/Makefile.platform.am, examples/platforms/da15000/Makefile.platform.am, examples/platforms/efr32/Makefile.platform.am, examples/platforms/emsk/Makefile.platform.am, examples/platforms/gp712/Makefile.platform.am, examples/platforms/kw41z/Makefile.platform.am, examples/platforms/nrf52840/Makefile.platform.am, examples/platforms/posix/Makefile.platform.am, examples/platforms/samr21/Makefile.platform.am
The Makefile.am for each application has to duplicate a large ifdef chain for all possible platforms.
This PR simplifies this aspect of the build system, and allows a more scalable solution for a platform maintainer to control the CPPFLAGS, LDFLAGS, and LDADD options required by their platform.
=> [build] simplify platform-specific Makefile configuration.

src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp
This commit makes the following fixes:
- Relax the length check in `RemoveStoredChild()`
- Remove children that do not match router ID
- Simplify restoring logic and remove `mIsRouterrestoringChildren` state var
=> [mle] fixes to restoring children

src/ncp/ncp_buffer.cpp, src/ncp/ncp_buffer.hpp
This commit adds code in `NcpFrameBuffer` to check and limit the
number of segments in a frame (being read). This is to help detect
cases where the underlying buffer may get corrupted.
=> [ncp-buffer] limit number of segments in a frame (being read)

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp, src/core/thread/mle_router_mtd.hpp
This commit changes the `MleRouter::RestoreChildren()` such that it
can detect invalid child info in non-volatile settings (i.e., if there
are more entries than max allowed/supported children, or if there are
duplicate entries with same ext address in the list). If an invalid
settings is detected, the non-volatile child info is refreshed
(erased and re-written).
=> [mle] detect duplicate/invalid child info in non-volatile

examples/platforms/nrf52840/Makefile.am, examples/platforms/nrf52840/flash_sd.c, examples/platforms/nrf52840/platform-config.h, third_party/NordicSemiconductor/drivers/radio/raal/nrf_raal_config.h, third_party/NordicSemiconductor/hal/nrf_egu.h
Should fix #2380 . I don't have NCP USB setup to test it, but I've verified that now radio driver uses clock driver to enable and disable HF clock.
=> [nrf52840] Fix HF clock stop procedure in radio driver

examples/platforms/nrf52840/logging.c
This commit addresses a misunderstanding of what the return value of `vsnprintf()` means.
This fixes issue #2382.
=> [nrf52480] Fix for buffer overrun in otPlatLog

examples/Makefile-cc2538, examples/Makefile-cc2650, examples/Makefile-cc2652, examples/Makefile-da15000, examples/Makefile-efr32, examples/Makefile-emsk, examples/Makefile-gp712, examples/Makefile-kw41z, examples/Makefile-nrf52840, examples/Makefile-posix, examples/Makefile-samr21
COMMONFLAGS in common-switches.mk #2315 would be override by COMMONFLAGS defined afterwards (as in https://github.com/openthread/openthread/blob/master/examples/Makefile-cc2538#L61)
Here adjusts the order to make COMMONCFLAGS defined in common-switches.mk take effect
=> [build] let COMMONCFLAGS defined in common-switches.mk take effect

examples/platforms/nrf52840/misc.c
Calling `PlatformDeinit()` before calling `NVIC_SystemReset()` reduces the reliability of `otPlatReset()` to always work properly, and doing so seems superfluous if you are just going to reset the chip anyway.
This fixes issue #2383.
=> [nrf52480] Don't call PlatformDeinit() before NVIC_SystemReset()

examples/platforms/nrf52840/usb-cdc-uart.c
USB driver entered `assert` if it was deinitialized while USB was still enabled. This PR fixes it.
=> [nrf52840] fix USB driver deinitialization

src/core/mac/mac.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp, src/core/thread/mle_router_mtd.hpp
Fixes #2364 
Also simplified the existing MleRouter::GetNeighbor() slightly
=> [mac] process security for neighbors on FFD Children

src/core/thread/data_poll_manager.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/topology.hpp
This commit allows a device to execute the MLE attach protocol without first
having to detach from it's existing parent.  This change allows a device to
search for a better parent without disrupting existing connectivity.
This commit involves the following changes:
1. Support sending MLE Parent Request and receiving MLE Parent Response
while attached.
2. If the set of MLE Parent Responses yields a better parent than the
one the device is currently attached to, the device proceeds to complete
the attach process with the better parent.
=> [mle] support MLE attach without having to detach first

src/core/openthread-core-default-config.h, src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit implements a "Periodic Parent Search" feature in MLE.
This feature is disabled by default and can be enabled through
`OPENTHREAD_CONFIG_ENABLE_PERIODIC_PARENT_SEARCH` configuration
option.
When enabled, an end-device/child (while staying attached) will
periodically search for a possible better parent and will switch
if it finds a better one.
The child will periodically check the average RSS value for the
current parent, and only if it is below a specific threshold, a
parent search is performed. Since the parent search process can be
power consuming (child needs to stays in RX mode to collect parent
response) and to limit its impact on battery-powered devices, after a
parent search is triggered, the child will not trigger another one
before a specified longer backoff interval. …
=> [mle] Periodic Parent Search feature

src/core/openthread-core-default-config.h, src/ncp/ncp_base.cpp, src/ncp/ncp_base.hpp, src/ncp/ncp_base_ftd.cpp, src/ncp/ncp_base_mtd.cpp, src/ncp/ncp_base_radio.cpp
This commit adds a new feature in `NcpBase` to allow spinel responses
for property "get/set" commands to be saved/queued by NCP. This in turn
helps to ensure that the responses are never dropped/missed due to NCP
buffer space not being available at the time of processing of the command.
The responses are sent when NCP buffer space becomes available.
=> [ncp] enhance handling of outbound Spinel responses (to host)

examples/platforms/efr32/radio.c
OpenThread uses dBm to set power. RAIL_TxPowerSet expects dBm * 10.
=> [efr32] Fix incorrect transmit power setting

src/ncp/ncp_base.cpp, src/ncp/ncp_base.hpp
When an OpenThread NCP starts up, the only thing it should emit is a `CMD_PROP_VALUE_IS` for `PROP_LAST_STATUS`, with a reset reason as the status code.
However, up until this point we have been also dumping out lots of other details which happen to be triggrered by OpenThread's start-up code. This is effectively noise, since a properly implemented host driver would be explicitly fetching the values of properties it needs to know at startup.
This change fixes this by supressing all property updates at startup except `PROP_LAST_STATUS`.
=> [ncp] Supress all output except PROP_LAST_STATUS at startup.

examples/platforms/efr32/alarm.c
Before this commit if otPlatAlarmMilliGetNow were called from an interrupt
the timer state could be corrupted.
=> [efr32] Allow calling otPlatAlarmMilliGetNow from an interrupt

doc/spinel-protocol-src/spinel-feature-jam-detect.md, src/ncp/ncp_base_mtd.cpp, src/ncp/spinel.h
This commit changes the `JAM_DETECT_HISTORY_BITMAP` format to use spinel primitive type of `uint64_t` added in #2309 instead of two `uint32_t`.
----
Please note that this does not change the (over-the-wire) encoding of this property (instead of `LL` we use `X` (all using little-endian)).
=> [ncp] update JAM_DETECT_HISTORY_BITMAP to spinel uint64_t

examples/platforms/nrf52840/platform-config.h, examples/platforms/nrf52840/usb-cdc-uart.c
This change addresses some issues that was noticed while working to bring up the OpenThread NCP on the nRF52840. The most important change is the introduction of the macro `USB_HOST_UART_CONFIG_DELAY_MS`, which will slightly delay the output of queued data once the fake UART is opened. On some slow Linux systems, the USB-CDC-UART driver sends the data so quickly after the port opens that the application hasn't had time to get the TTY properly configured using tcsetattr(). While this is technically a host-side problem, fixing this problem host-side is architecturally infeasible in many cases. Ensuring the reliable delivery of the first bytes of the HDLC stream from the NCP after a reset is critical to the host driver being able to identify that a reset has indeed occurred. Waiting a few …
=> [nrf52840] Improvements to USB-CDC-UART

include/openthread/types.h
The maximum sizes for the Server Data and the Service Data are not really an enum. They could at some point have the same value which is a bit strange in an enum.
Additionally the style used to define the enum is outdated (using `kMax...` instead of `OT_MAX_...`
Propose to change them to a `#define`
=> [network-data] changing kMaxServerDataSize and kMaxServiceDataSize to #defines

src/ncp/ncp_base.hpp, src/ncp/ncp_spi.cpp, src/ncp/ncp_uart.cpp
This change satisfies issue #2410.  The strategy for a vendor that desires to extend the Spinel responses can subclass either the ncp_uart or ncp_spi class with a new ncp_vendor class to which the vendor may add new API's to be called by vendor specific code for the purpose of sending vendor specific messages to a host.  The members of class ncp_base have all been designated as protected rather than private to allow the new subclass full access to all the facilities necessary for constructing and sending spinel messages.
The instantiation of an ncp_spi object or ncp_uart object has been conditionally compiled out when OPENTHREAD_ENABLE_SPINEL_VENDOR_SUPPORT is enabled. The expectation is that the vendor will implement similar code to instantiate a vendor specific subclass which will serve …
=> [ncp] allow a vendor defined subclass of ncp_uart or ncp_spi to access ncp_base members

include/openthread/types.h, src/core/common/logging.cpp, src/core/openthread-core-default-config.h, src/core/thread/mle_router.cpp
This commit applies a hysteresis to establishing new links or merging
partitions.  In particular, this commit introduces new minimum link
margin thresholds that must be met before attempting to establish a
new link or merging to a different partition.  Enforcing a mininmum
link margin threshold before establishing new links helps avoid links
that will quickly become invalid due to normal time-varying link
qualities.
=> [mle] implement hysteresis for establishing links and merging

include/openthread/types.h, src/core/api/ip6_api.cpp, src/core/api/link_api.cpp, src/core/api/thread_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_filter.cpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/meshcop/joiner.cpp, src/core/net/dhcp6.hpp, src/core/net/dhcp6_client.cpp, src/core/thread/address_resolver.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/network_diagnostic.cpp, src/core/thread/thread_netif.cpp, src/core/thread/thread_tlvs.hpp
- Replace `memcmp` with `==` and `!=` operators.
- Replace `memcpy` with `=` assignment.
- Change pointers to reference where applicable.
=> [mac] clean up extended address usage

src/core/net/netif.cpp, src/core/net/netif.hpp, src/core/thread/address_resolver.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/thread_tlvs.hpp
- Replace `memcmp` with `==` and `!=` operators.
- Change pointers to reference where applicable.
=> [ip6] clean up ip6 address usage

src/core/mac/mac.cpp, src/core/mac/mac.hpp
This commit combines and simplifies the two methods`Mac::TransmitDoneTask()` and `Mac::SentFrame()` into a single `HandleTransmitDone()` which includes the same logic.  It also changes some of the method names (removing `Task` suffix).
=> [mac] simplify the tx processing

src/core/mac/mac.cpp, src/core/mac/mac.hpp
This commit changes how MAC operations (frame tx, active/energy scan, etc.) get started by adding a new tasklet `mOperationTask` which is used to start/perform any pending operation. This ensures that callbacks related to an operation are invoked after the method which initiates the operation returns. For 
example, when a new `Mac::Sender` is registered with a call to `Mac::SendFrameRequest()`, its callback `FrameRequestHandler` would be invoked after the `SendFrameRequest()` call itself returns.
The `mOperationTask` serves two purposes:
- It's mainly used for starting a new operation. 
- It is also used during Energy Scan to take an RSSI sample.
=> [mac] ensure MAC operations get started from a tasklet

include/openthread/instance.h, include/openthread/types.h
As suggested by @al1img [here](https://groups.google.com/forum/#!topic/openthread-users/a6504oYEgU8).
=> [instance] co-locate OT_CHANGED_* flags with otStateChangedCallback

examples/platforms/posix/platform.c
=> [posix] print error and exit when node id is invalid

src/core/thread/mle_tlvs.hpp
Properly formed Route TLVs should never have more than 32 route entries.
This fix follows a "be liberal in what you accept" approach.
=> [mle] increase Route TLV length to avoid buffer overflow

src/ncp/spinel.c
This commit brings/syncs the change in `spinel.c` from wpantund. This change was done as part of wpantund commit https://github.com/openthread/wpantund/commit/d77e7cbf23a942a65dd8078405240e5fe3b67b8d which addressed some of the fuzzer test issues.
=> [spinel] change parsing of boolean

examples/platforms/nrf52840/openthread-core-nrf52840-config.h, include/openthread/platform/toolchain.h, src/core/common/instance.cpp, src/core/mac/mac.cpp, src/core/thread/thread_tlvs.hpp
This PR provides some minor fixes to restore warningless build of OpenThread libraries in IAR and Keil compilers.
=> [build] fix IAR and Keil build warnings

src/core/api/instance_api.cpp, src/core/api/ip6_api.cpp, src/core/api/tasklet_api.cpp, src/core/api/thread_api.cpp, src/core/coap/coap_secure.cpp, src/core/common/logging.hpp, src/core/common/timer.cpp, src/core/mac/mac.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/joiner.cpp, src/core/meshcop/joiner_router.cpp, src/core/net/ip6.cpp, src/core/thread/mle.cpp
This commit removes the `otLogFuncEntry` and `otLogFuncExit` (and other related) macros and their use within OT core.
These macros were currently unused on all platforms except for windows. They do not follow the model used by all other `otLog` APIs (there is no way to specify log region, or log level or to pass in `ot::Instance` to them).
=> [logging] remove otLogFunc<Entry/Exit> macros

src/core/thread/mesh_forwarder.cpp
Changing the string for `kMessageReassemblyDrop` from `"Dropping (reassembly timeout)"` to `"Dropping (reassembly queue)"` to note that message is not necessarily being dropped due to timeout. For example,  message in reassembly queue may be dropped on SED if a fragment is missed or a fragment for a new message (different tag) is received.
=> [logging] change log strings in LogIp6Message

src/ncp/example_vendor_hook.cpp
Fix build error caused by lack of compilation flag.
=> [da15000] fix for Dialog IDE

src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp
This commit changes the logic for preparing a data poll (802.15.4 MAC
Data Request) frame and selecting short/extended address. It ensures
that during a parent switch attempt on a sleepy-end-device, the data
polls use the extended address as the source MAC address.
=> [mesh-forwarder] use extended address for data poll during parent switch attempt

src/core/utils/child_supervision.cpp
This commit changes the `SupervisionListener` implementation by
relaxing the checks for when to start the supervision listener timeout
timer, in particular removing the check for role to be `ROLE_CHILD`.
This addresses an issue where timer may not start during (re-)attach
process after a "Child Id Request" transmission where the device
becomes sleepy but its role is not yet set to child.
=> [child-supervision] relax the check for starting the supervision timeout timer

src/core/thread/address_resolver.cpp, src/core/thread/address_resolver.hpp, src/core/thread/mle_router.cpp
Currently, OpenThread detects several situations where RLOC16 of our neighbor is stale (based on extended MAC address).
For example, when our child sends Link Request from different RLOC16, we remove him from the child list.
Unfortunately in many such places, EID-to-RLOC cache is not cleared, which may lead to single packet drop.
You can reproduce this situation for example like that:
```
1. Node A:
panid 0
ifconfig up
thread start
2. Node B:
panid 0
routerrole disable
ifconfig up
thread start
3. Node A:
ping Node B ML-EID (new Address Query is generated)
Reply from Node B SUCCESS
4. Node B:
routerrole enable
state router
5. Node A:
ping Node B ML-EID (internal ICMPv6 Dest Unreachable message is sent to ourself, and EID-to-RLOC cache entries are removed)
**No Reply**
ping Node B ML-EID …
```
=> [mle] delete stale EID-to-RLOC entries of removed neighbors

src/core/thread/mesh_forwarder.cpp
This commit changes the `ClearChildIndirectMessages(aChild)` method in `MeshForwarder` to ensure that it also clears the indirect message pointer on the child entry.
This addresses a subtle bug in the code in the following situation: If we happen to receive a "Child Id Request" from an already valid child for which we are in the middle of an indirect transmission, from `MleRouter::HandleChildIdRequest()` all queued indirect messages for the child  are removed (through `MleRouter::RemoveNeighbor()` call). This would then free the indirect message while the child still kept a pointer to the freed message.
=> [mesh-forwarder] Clear child's indirect message pointer when removing all its messages

tests/scripts/thread-cert/Cert_5_5_08_SplitRoutersLostLeader.py
The unstable failing lies in when Leader has lower partition id and switches to better partition
formed by original routers.  The default RouterSelectionJitter of Leader is 120s, however the
migration waiting time in script is 60s, thus there are chances that the ping happens when the
Leader just becomes router in the new partition but before link sychronization, causing the ping
packet dropped on ROUTER3.
Two options to resolve this: 1) increase the waiting time for migration to a value > 120s or
2) configure router selection jitter to a small value to relax the waiting time requirements.
The second option reduces test time which is selected to resolve this issue.
=> [tests] fix the unstable test case Cert_5_5_08_SplitRoutersLostLeader

src/ncp/ncp_base.cpp
This commit changes the `StreamWrite` logic to allow logs/prints
when there is a pending async property update.
---
This ensures that after a assert/watchdog reset, if the platform code provide backtrace, the logs are not dropped/masked.
=> [ncp] allow log/prints while an async property update is pending

etc/visual-studio/openthread.sln
Visual Studio does not like commented lines in sln files.  This PR simply
removes the commented lines.
Resolves #2414.
=> [appveyor] remove OpenThread project due to expired certificate

configure.ac, src/core/Makefile.am, src/core/common/instance.cpp, src/core/common/instance.hpp, src/core/openthread-core-default-config.h, src/core/thread/thread_netif.cpp, src/core/utils/channel_monitor.cpp, src/core/utils/channel_monitor.hpp
This commits introduces channel monitoring feature which monitors
signal level on all channels to help determine the cleaner channels
(channels with less interference).
When enabled and started, `ChannelMonitor` class will perform a
zero-duration Energy Scan collecting a single RSSI sample per channel,
every sample interval (which is a build-time configurable parameter).
The RSSI samples are then compared with a (build-time configurable) RSSI
threshold. As an indicator of channel quality, the `ChannelMonitor`
class maintains and provides the average rate/percentage of RSS
samples that are above the threshold within (approximately) a
specified sample window length.
=> [utils] implementing channel monitoring feature

examples/platforms/cc2538/radio.c
CC2538 data sheet indicates -88 dBm across entire operating conditions.
=> [cc2538] adjust receiver sensitivity

configure.ac, src/ncp/ncp_spi.cpp, src/ncp/ncp_uart.cpp
This fixes a couple issues related to the Spinel Vendor Hook feature.
1) otNcpInit in ncp_spi.cpp and ncp_uart.cpp was controlled by the wrong definition.
2) The enable_vendor variable no longer exists in configure.ac and so should be removed.
=> [ncp] Fix some issues with the spinel vendor hook.

src/ncp/ncp_base_ftd.cpp
Due to issue #2110 there was a conclusion to not set lock on local network data when a new joiner is added. As a result the openthread/wpantund#256 pull request has been created.
However despite removing following [lines](https://github.com/openthread/wpantund/pull/256/files#diff-816a041f7db348e0472f042be4dab42fL329) from wpantund, the OpenThread code still checks if mLocalNetworkDataChange variable is set before joiner can be added.
This PR removes the check, allowing to add a new Joiner from the Host side again.
=> [ncp] do not check local network data lock when adding a joiner

.travis/script.sh
This commit enables the "channel monitor" feature in the posix FTD build representing a common router Thread device.
=> [travis] enable "channel monitor" feature in posix ftd (router) build

src/core/thread/mesh_forwarder.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp, src/core/thread/mle_router_mtd.hpp
Thread 1.1.1 Section 5.10.1.3 states:
```
MEDs do not receive or process mesh headers and do not have a link-layer routing table.
```
This PR helps ensure that mesh headers are never sent to MTD children.
=> [mesh-forwarder] do not forward mesh headers to MTD

src/core/thread/mle.cpp
This commit adds a Network Data TLV request to the MLE Child Update Request
message when trying to resynchronize with a parent after reset.  This
eliminates the need for an MLE Data Request/Response exchange following the
MLE Child Update Request/Response exchange.
=> [mle] request network data on child reattach after reboot

src/core/thread/mle_router.cpp
This commit moves restarting the state update timer to the top of
`MleRouter::HandleStateUpdateTimer()`.  This ensures that the timer
continues to fire periodically.  Prior to this change, the state update
timer is not properly restarted when operating in the Child role and
`mRouterSelectionJitterTimeout` expires.
=> [mle] fix bug in restarting router state update timer

src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp
REEDs periodically transmit MLE Advertisement messages to support merging
partitions.  However, REEDs do not include Route64 TLVs in their MLE
Advertisement messages.
This commit removes the strict requirement check when handling MLE
Advertisement messages, allowing such messages sent by REEDs to trigger
the partition merging process.
=> [mle] fix partition merging with REEDs

src/core/coap/coap.cpp, src/core/coap/coap.hpp
Calling the associated response handler simplifies the client's handling of
CoAP transactions.
This commit also fixes a bug in aborting multiple pending transactions.
=> [coap] have AbortTransaction() call the associated response handler

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp, src/core/thread/mle_router_mtd.hpp
This commit aborts the Address Solicit transaction on a partition change.
Doing so avoids having Address Solicit messages being sent to the wrong
Leader address and delays caused by waiting for the previous Address Solicit
transaction to time out.
=> [mle] abort Address Solicit on partition change

include/openthread/diag.h, src/diag/diag_process.cpp, src/diag/diag_process.hpp, src/diag/openthread-diag.cpp, src/ncp/ncp_base_mtd.cpp, tests/unit/test_diag.cpp
This commit contains fixes and enchantments for diagnostics module
in OpenThread. In particular, the following changes are made to the
implementation of `otDiagProcessCmdLine()`:
- Fixes an issue with the parsing of command line input (where if
more than 8 arguments were given, it could cause an out-of bound
array access and a possible NCP crash). The new code will check for
this and outputs an error if too many arguments are provided.
- Parsing logic is simplified and now allows for extra spaces between
arguments.
- A local buffer is used to store the arguments to avoid modifying
the passed-in input string.
This commit also simplifies and does a code clean-up of `Diag`
class (variable name changes, removing extra method paramters, and
minor style changes).
The `test_diag` unit test …
=> [diags] fix parsing command line and enhancements

etc/visual-studio/libopenthread.vcxproj, etc/visual-studio/libopenthread.vcxproj.filters, etc/visual-studio/libopenthread_k.vcxproj, etc/visual-studio/libopenthread_k.vcxproj.filters, src/core/Makefile.am, src/core/api/message_api.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mesh_forwarder_mtd.cpp
- Reduces MTD code by 2,544 bytes and RAM by 16 bytes.
- Reduces FTD code by 16 bytes and no change in RAM.
Before:
```
$ arm-none-eabi-size output/cc2538/bin/ot-cli-ftd
text	   data	    bss	    dec	    hex	filename
147540	   4568	  15508	 167616	  28ec0	output/cc2538/bin/ot-cli-ftd
$ arm-none-eabi-size output/cc2538/bin/ot-cli-mtd
text	   data	    bss	    dec	    hex	filename
96212	   4568	  10932	 111712	  1b460	output/cc2538/bin/ot-cli-mtd
```
After:
```
$ arm-none-eabi-size output/cc2538/bin/ot-cli-ftd
text	   data	    bss	    dec	    hex	filename
147524	   4568	  15508	 167600	  28eb0	output/cc2538/bin/ot-cli-ftd
$ arm-none-eabi-size output/cc2538/bin/ot-cli-mtd
text	   data	    bss	    dec	    hex	filename
93668	   4568	  10916	 109152	  1aa60	output/cc2538/bin/ot-cli-mtd
```
=> [mesh-forwarder] MTD code size optimizations

src/core/thread/mle.cpp
This reverts commit 87d8940abfc379c0748055fc0bf6f4870d5e73ce.
Adding Network Data to the MLE Child Update Response message increases the
message size beyond what can fit in a single IEEE 802.15.4 frame.  The
Thread specification requires all fragmented MLE message to have MAC
security enabled.
=> [mle] revert request network data on child reattach after reboot (#2466)

src/core/thread/mle_router.cpp
This commit removes the unused errors (such as when the device is not
joinable or PAN Id from message does not match the device's PAN Id) in
`MleRouter::HandleDiscoveryRequest()`. This suppresses the (inaccurate)
MLE warning log "Failed to process Discovery Request" for above
scenarios.
=> [logging] remove unnecessary errors when handling MLE Discovery Request

include/openthread/link.h, src/core/api/link_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp
These changes allow for 3rd party code to provide a 15.4 frame that OpenThread will transmit in conjunction with its other operations.  The frame will be taken as-is, unmodified and transmitted by OpenThread at the earliest opportunity.  It is currently the job of the 3rd party code to know when the frame transmission has completed.
=> [mac] add feature to transmit out of band 15.4 frames

src/core/common/message.cpp, src/core/common/message.hpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp
This commit helps to reduce additional message exchanges when multiple network data updates in short time.
=> [mle] remove existing MLE Data Response in queues when there is newer Network Data

src/core/thread/mle.cpp
This is related to this PR https://github.com/openthread/openthread/pull/2492 and the issue notcied during re-attach process.
=> [mle] do not delete the ParentInfo settings

include/openthread/link.h, src/core/api/link_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/openthread-core-default-config.h, src/core/thread/link_quality.cpp, src/core/thread/link_quality.hpp, tests/unit/test_link_quality.cpp
This commit adds a new class `SuccessRateTracker` which can be used to
tracker success/failure rate of an operation. It uses an exponentially
moving average IIR filter to maintain the rate using  a `uint16_t` as
its storage. Unit test `test_link_quality` is updated to include a new
test case ``ot::TestSuccessRateTracker()` verifying the behavior of
the new class.
This commit uses the new class to track the CCA failure rate (over all
frame transmissions) at MAC layer.
=> [link-quality] adding SuccessRateTracker and tracking CCA failure rate

examples/platforms/efr32/Makefile.am, examples/platforms/efr32/hal-config.h, examples/platforms/efr32/uart.c
Remove redundant retargetserial.c as retargeting may
conflict with OT UART. Also retargeting doesn't work
without retargetio.c and just consumes flash and RAM.
Signed-off-by: Oleksandr Grytsov <al1img@gmail.com>
=> [efr32] Remove UART retargeting

src/core/thread/mle.cpp
Specification only mentions 
> A REED MAY also request a Route64 TLV as an aid in determining whether or not it should become an active Router
Not see the point for MTD to request Route64 TLV.
=> [mle] MTD doesn't request Route64 TLV when attach

src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, src/core/thread/address_resolver.cpp, src/core/thread/mle_router.cpp, src/core/thread/topology.cpp, src/core/thread/topology.hpp, tests/unit/test_child.cpp
This commit changes how a mesh-local IPv6 address is stored in
`Child` class. Instead of storing the entire IPv6 addresses (16
bytes), only the Interface Identifier (8 bytes) is saved.  The full
address is derived (when needed) using the mesh-local prefix from
`Mle`. This reduces the memory required for storing registered IPv6
addresses in the child table.
This commit also updates the unit test `test_child` to use mesh-local
IPv6 address as part of the test and verify the behavior of new
implementation.
=> [child] enhance how mesh-local IPv6 address is stored in a child entry

src/core/thread/topology.cpp, src/core/thread/topology.hpp, tests/unit/test_child.cpp
This commit adds a new method `Child::GetMeshLocalIp6Address()`
to get the mesh-local IPv6 address registered by a child. The
unit test `test_child` is also updated to verify the new method.
=> [child] adding Child::GetMeshLocalIp6Address()

src/core/thread/topology.hpp
This commit makes removes the unused `mChannelLength` and moves the
`mRloc16` outside of `mValidPending` union.
=> [topology] reorder member variables in `Neighbor` class

examples/Makefile-nrf52840
Addresses #2513 by adding conditional inclusion of -Wno-expansion-to-defined based on GCC version
=> [nrf52840] add conditional -Wno-expansion-to-defined for GCC7

src/core/mac/mac.cpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, src/core/thread/lowpan.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/topology.cpp, tests/unit/test_lowpan.hpp
This commit updates the implementation of `Mac::Address` class by
adding getter and setter and other helper methods. When the address
is updated using the setter methods (`SetShort()` or `SetExtended()`
the `Address` class itself will update its type (remembering whether
it is an IEEE 802.15.4 Short Address or an Extended Address). This
helps simplify how this class is used in other modules.
=> [mac-frame] update Mac::Address to track its type (Short vs Extended)

src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp, src/core/thread/mle_tlvs.hpp
OT would fail to process address registration with more than 4 entries as `IsValid()` would always fail.
This commit processes the address registration entry one by one directly from message.
=> [mle] fix the issue when the number of registered addresses exceeds the parent's capacity

include/openthread/types.h, src/core/common/message.hpp, src/core/mac/mac.cpp, src/core/openthread-core-default-config.h, src/core/thread/link_quality.cpp, src/core/thread/link_quality.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle_router.cpp, src/core/thread/topology.hpp
This commit implement a new feature to allow the tracking of tx error
rates at two layers:
- At PHY/MAC layer for MAC frame transmissions (frame tx error rate):
Error rate is maintained per link/neighbor. A frame transmission
attempt is considered failed if the frame is sent over the channel,
but no acknowledgment frame is received from the neighbor.
- Above MAC layer for message transmissions (message drop rate):
A larger (IPv6) message may be fragmented and sent as multiple MAC
frames. The message is dropped (transmission is considered as
failure), if any of its fragments fail after all retry attempts.
Message drop rate is maintained per link/neighbor and includes
both direct and indirect message transmissions.
Configuration option `OPENTHREAD_CONFIG_ENABLE_TX_ERROR_RATE_TRACKING`
can …
=> [link-quality] track MAC frame tx error rate and message drop rate

include/openthread/types.h, src/core/common/logging.cpp, src/core/common/logging.hpp, src/core/openthread-core-default-config.h, src/core/utils/channel_monitor.cpp
This commit adds `OT_LOG_REGION_CORE` and `OT_LOG_REGION_UTIL` as
two new log regions. The Core is intended for any core module that
does not fit any other category. The `UTIL` is intended for all
modules under `/core/util` folder.
=> [logging] add two new regions for core and utility modules

src/core/meshcop/commissioner.cpp, src/core/meshcop/commissioner.hpp
**observation:** assert in `src/core/common/timer.cpp:78`
**cause:** timer calculated in `UpdateJoinerExpirationTimer` is negative (or very large from an unsigned int point of view)
**root cause:**
RemoveJoiner is accessed by `HandleJoinerExpirationTimer`. It uses the joinerId as an argument (it gets the value from `joiners[i].mJoinerId`), but `RemoveJoiner` expects a `Eui64`, from which it then calculates the joinerId). Therefore the `joinerId` is calculated from the wrong source. The joiner to be removed is never found and the expired timer is never removed, causing the `ExpirationTimer` to be updated with the value `0 - now`, resulting in the assert.
=> [commissioner] joiner timing out causes an assert in timer.cpp

src/core/thread/mle_router.cpp
Is it necessary to clear Address Query Cache while transition to the router role? I have already submitted [patch](https://github.com/openthread/openthread/commit/41e4b3202bf60388020287eff6880a360d2332c9) for Parent<->Child interaction with Address Query mechanism so personally i don't see any other potential issues.
There is a problem with current approach:
Use case: Streaming application, that floods data packets to the ML-EID address of other node in the network, blocks and drains message buffers when stack switches role from Child to Router. All in all, the problem is caused by sending Address Query before any Routers reply with Link Accept.
Simplified visualization of the problem:
Important note: I have observed some random Travis fails (maybe it is caused by the new virtual time …
=> [mle] do not clear address query cache when switching to the router role

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp, src/core/thread/mle_router_mtd.hpp
This commit delays sending Announce for FTD after it has become Router and decided to stay in REED on the safe side:
OT device would try to attach on the announced channel only once, and if it fails, the device would switch back to old channel. However the FTD may get a different router id, or it will take longer for REED to become router especially in linear topology, causing the attaching device fail to attach and may no chance to attach again on the announced channel.
=> [mle] delay to send announce for FTD

tools/spi-hdlc-adapter/README.md, tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Testing has determined that some SPI slave interfaces sometimes emit
even more than 6 0xFF bytes before sending the first header byte. Upping
this value to 16 in order to provide some future proofing.
=> [spi-hdlc-adapter] increase max spi-align-allowance from 6 to 16

configure.ac, include/openthread/Makefile.am, include/openthread/channel_manager.h, src/core/Makefile.am, src/core/api/channel_manager_api.cpp, src/core/common/instance.cpp, src/core/common/instance.hpp, src/core/openthread-core-default-config.h, src/core/utils/channel_manager.cpp, src/core/utils/channel_manager.hpp
This commit adds a new module/class `ChannelManager` which provides a
mechanism to perform a network-wide channel change. It internally
uses Pending Operational Dataset updates to trigger the channel change
in the network. It also manages retries in case of errors/failures.
This commit also adds public OT APIs for user to request a channel
change and get/set different parameters related to operation of
Channel Manager (e.g., supported channels mask).
This feature can be enabled using `--enable-channel-manager` configure
option (by default it is disabled).
=> [channel-manager] adding Channel Manager module

examples/platforms/efr32/radio.c
Worked fine without this but just to be safe.
=> [efr32] initialise timeReceived as required by Rail

examples/platforms/efr32/radio.c
Sometimes when transmission is started RAIL_EVENT_RX_OVERFLOW
happens and then otPlatRadioTxDone is never called ( see #2530 ).
This commit makes sure the RX FIFO is always drained, even when
transmitting so RAIL_EVENT_RX_OVERFLOW never happens.
=> [efr32] fix otPlatRadioTxDone sometimes not being called

include/openthread/channel_manager.h, src/core/api/channel_manager_api.cpp, src/core/utils/channel_manager.hpp
This commits adds a new API to `ChannelManager` class (and a
a corresponding public OT API) to get the channel for the last
successfully requested channel change.
=> [channel-manager] API to get the last requested channel

src/core/utils/channel_manager.cpp, src/core/utils/channel_manager.hpp
This commit adds new logic in `ChannelManager` to help handle
situations where multiple devices within network request channel
change around the same time. This simplifies how the channel change
can be triggered by users allowing them to request a channel change on
all routers/devices simultaneously (this would help with cases where
the Thread network contains multiple partitions).
In particular, this commit adds a jitter delay to start processing of
a channel change request (random delay before a Pending Dataset is
prepared and sent to leader). Also this commit changes how the Pending
Dataset is prepared and sent. The code now checks if there is a valid
Pending Dataset and if it is changing the channel to same one as the
current channel change request, then it skips updating the Pending …
=> [channel-manager] handle simultaneous channel change requests

src/core/mac/mac.cpp, src/core/mac/mac.hpp, tests/unit/test_mac_frame.cpp
This commit adds a `Mac::ChannelMask` class to define a channel (a
`uint32_t` bit-vector specifying a set of channels). The `ChannelMask`
class provides methods to add/remove channel to the mask, intersect
two masks, and iterate through the channels in the mask. A unit test
for the new class is also added.
=> [mac] adding Mac::ChannelMask class

src/core/mac/mac.cpp
This commit changes how `Mac::HandleReceivedFrame()` handles duplicate
received frame when a sleepy device is waiting for data after a data
poll ack from parent indicating a pending frame. This change ensures
that the sleepy device can go to sleep faster and avoid a data poll
timeout.
=> [mac] avoid data poll timeout when a duplicate frame is received

tests/scripts/thread-cert/Cert_5_3_05_RoutingLinkQuality.py
Updating the bidirectional link quality requires a two-way exchange via MLE
Advertisements.  In the worst case, this can take 2.5x the worst-case MLE
Advertisement period.  This commit increases the delay after updating link
quality configurations.
=> [tests] fix occasional failures in Cert_5_3_05_RoutingLinkQuality.py

tests/scripts/thread-cert/Cert_5_1_08_RouterAttachConnectivity.py
This commit adds necessary delay to allow the router topology to establish
links with neighboring routers.
=> [tests] fix occasional failures in Cert_5_1_08_RouterAttachConnectivity.py

script/clang-format-check.sh
Like this:
```
PRETTY   cli.cpp
+clang-format -style=file ./cli.cpp
+diff ./cli.cpp -
1006,1009c1006,1009
<     int id;
<     const char *mgrName = otFIGetManagerName();
<     const char *faultName = NULL;
<     uint32_t faultCounter = 0;
---
>     int         id;
>     const char *mgrName      = otFIGetManagerName();
>     const char *faultName    = NULL;
>     uint32_t    faultCounter = 0;
make[2]: *** [pretty-check] Error 1
make[1]: *** [pretty-check-recursive] Error 1
make: *** [pretty-check-recursive] Error 1
+die
+echo  *** ERROR:
```
=> [code-style] make pretty-check output something better

tests/scripts/thread-cert/Cert_6_1_03_RouterAttachConnectivity.py
This commit adds necessary delay to allow the router topology to establish
links with neighboring routers.
=> [tests] fix occasional failures in Cert_6_1_03_RouterAttachConnectivity.py

examples/Makefile-efr32, examples/platforms/efr32/Makefile.am, examples/platforms/efr32/README.md
As discussed in issue #2324, the support for Silabs Thunderboard Sense 2 will be added through this pull request.
The user can now  provide the board, for example for WSTK:
```
make -f examples/Makefile-efr32 COMMISSIONER=1 BOARD=BRD4161A
```
or for Thunderboard Sense 2
```
make -f examples/Makefile-efr32 COMMISSIONER=1 BOARD=BRD4166A
```
=> [efr32] configurable board

src/core/mac/mac.cpp, src/core/mac/mac.hpp, tests/unit/test_mac_frame.cpp
Adds new method `Mac::ChannelMask::ToString()` which helps convert the channel mask into a human-readable NULL-terminated string.
=> [mac] add method ToString() to Mac::ChannelMask

src/core/net/netif.cpp
Thread does not support address resolution for link-local unicast addresses.
As a result, any link-local unicast address other than the one based on the
IEEE 802.15.4 Extended Address is not useful.
Helps avoid the issued identified in #2571.
=> [netif] do not allow external link-local unicast addresses

src/core/thread/mle.cpp
This commit changes `Mle:Stop()` so that leader and local network data
are not cleared.
This is related to https://github.com/openthread/openthread/pull/2589
=> [mle] do not clear network data on MLE stop

src/core/openthread-core-default-config.h, src/core/thread/mesh_forwarder.cpp
This commit adds a new config option which determines if the source
and destination IPv6 addresses of received/sent messages are logged
from `MeshForwarder::LogIp6Message()`.
------
This is useful when NCP (with logs enabled) is being used with `wpantund` (with logs enabled). `wpantund` logs any inbound/outbound IP message from/to NCP (the logs contains the message  checksum and src/dst IPv6 address). So even with removing the src/dst address in OT logs, we can still map the message using the checksum and infer its src/dst from `wpantund` logs.
=> [mesh-forwarder] config option if to log src/dst IPv6 addresses

tests/scripts/thread-cert/Cert_5_2_07_REEDSynchronization.py
This commit adds delay to allow topology to form and allow the REED to
establish receive-only links.
=> [tests] fix occasional failures in Cert_5_2_07_REEDSynchronization.py

src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/commissioner.hpp, src/core/meshcop/joiner.cpp
This commit makes the following changes:
- Only print logs on success.
- Remove use of `HostSwap64()`, which can cause hard faults.
- Add `ExtAddress::ToString()` method.
=> [meshcop] improve logging of adding/removing joiners

src/cli/cli_dataset.cpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset_local.cpp
Resolves an issue reported [here](https://groups.google.com/d/msg/openthread-users/sS1WqMSbBFg/VSvBpftzBQAJ).
=> [operational-dataset] fix bug in getting the channel mask

src/core/meshcop/dataset_local.cpp, src/core/meshcop/dataset_local.hpp, src/core/meshcop/dataset_manager.cpp
This commit caches the Active/Pending Timestamp value in memory so that
subsequent calls to `DatasetLocal::Compare()` does not require reading
from non-volatile settings and allocating another dataset buffer on the
stack to do so.
=> [operational-dataset] cache Active/Pending Timestamp value

include/openthread/ncp.h, src/core/openthread-core-default-config.h, src/ncp/ncp_base.cpp
This commit adds `OPENTHREAD_CONFIG_NCP_SPINEL_LOG_MAX_SIZE` as
a config option to set the max log string size supported by NCP
`otNcpPlatLogv()`. This commit also increases the default to 150
characters.
=> [ncp] config option for max log string size in otNcpPlatLogv()

.travis.yml, .travis/before_install.sh, .travis/script.sh, tests/toranj/README.md, tests/toranj/openthread-core-toranj-config.h, tests/toranj/start.sh, tests/toranj/test-001-get-set.py, tests/toranj/test-002-form.py, tests/toranj/test-003-join.py, tests/toranj/test-004-scan.py, tests/toranj/test-005-discover-scan.py, tests/toranj/test-006-traffic-router-end-device.py, tests/toranj/test-007-traffic-router-sleepy.py, tests/toranj/test-008-permit-join.py, tests/toranj/test-nnn-template.py, tests/toranj/wpan.py
This commit adds the base implementation of `toranj`, a test framework
for OpenThread and `wpantund`.
- It enables testing of combined behavior of OpenThread (in NCP mode),
spinel interface, and `wpantund` driver on linux.
- It can be used to simulate multiple nodes forming complex network
topologies, testing network interactions between many nodes
(e.g., IPv6 traffic exchanges).
This commit also sets up the new test-cases to run as part of travis
pull request validation in OpenThread GitHub projects.
---
The [README](https://github.com/abtink/openthread/blob/9adcbf52f0360d4b679ec81f9977ef8e88f5b966/tests/toranj/README.md) provides an overview of how the test frame-work works.
This PR adds the core implementation of the test frame-work and 8 test-cases. We can add more test-cases over …
=> [tests] adding `toranj` test framework

src/core/thread/mle.cpp, src/core/thread/mle_tlvs.hpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp, tests/unit/test_lowpan.cpp
This commit reduces stack usage when receiving/updating network data via MLE
by copying the network data directly out of the message and skipping the TLV
read.
=> [network-data] optimize network data update via MLE

src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp
This commit helps reduce stack usage by refactoring logging related
code for frame rx/tx failure and beacon rx/tx into separate methods.
=> [mac] refactor frame rx/tx logging logic into methods

src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp
This commit helps reduce stack usage by refactoring logging related
code in `MeshForwarder` into separate methods.
=> [mesh-forwarder] refactor logging code into method

examples/apps/cli/main.c, examples/apps/ncp/main.c, examples/platforms/cc2538/platform.c, examples/platforms/cc2650/platform.c, examples/platforms/cc2652/platform.c, examples/platforms/da15000/platform.c, examples/platforms/efr32/platform.c, examples/platforms/emsk/platform.c, examples/platforms/gp712/platform.c, examples/platforms/kw41z/platform.c, examples/platforms/nrf52840/alarm.c, examples/platforms/nrf52840/misc.c, examples/platforms/nrf52840/platform-config.h, examples/platforms/nrf52840/platform.c, examples/platforms/platform.h, examples/platforms/posix/misc.c, examples/platforms/posix/platform.c, examples/platforms/posix/sim/platform-sim.c, examples/platforms/samr21/platform.c
Pseudo resets allow for `otPlatReset()` to reset the OpenThread state without resetting the chip. This is important if the SoC is presenting itself as a USB device.
The build option `OPENTHREAD_PLATFORM_USE_PSEUDO_RESET` can be used to force this feature to be enabled or disabled by setting it to `1` or `0` accordingly. Otherwise it will be set to a platform-specified default value.
=> [examples] Introducing pseudo resets

.travis/before_install.sh, tests/toranj/start.sh, tests/toranj/wpan.py
This commit updates the `start.sh` script under `toranj` test
framework so that failed tested are tried again up to 3 times.
It also modifed how wpantund project is build and installed
under `toranj`.
=> [tests] Update toranj test script to retry failed tests

etc/visual-studio/libopenthread.vcxproj, etc/visual-studio/libopenthread.vcxproj.filters, etc/visual-studio/libopenthread_k.vcxproj, etc/visual-studio/libopenthread_k.vcxproj.filters, src/core/Makefile.am, src/core/api/thread_api.cpp, src/core/common/instance.cpp, src/core/common/instance.hpp, src/core/common/settings.cpp, src/core/common/settings.hpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_local.cpp, src/core/meshcop/dataset_local.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp
This commit adds a new class `Settings` to manage the OpenThread
core modules interactions (saving and restoring information) with
non-volatile memory. It also adds logs to show the saved content
for `NetworkInfo`, `ParentInfo` and `ChildInfo` keys.
Here are samples on how the logs would look like:
```
On a router node with children
wpantund[253126]: NCP => [INFO]-CORE----: Non-volatile: Saved NetworkInfo {rloc:0x5c00, extaddr:6e812de1ef670fd3, role:Leader, mode:0x0f, keyseq:0x1, ...
wpantund[253126]: NCP => [INFO]-CORE----: Non-volatile: ... pid:0x2d96aa52, mlecntr:0x32f5, maccntr:0x32c8, mliid:f3fead611eecae7d}
wpantund[253126]: NCP => [INFO]-CORE----: Non-volatile: Saved NetworkInfo {rloc:0x5c00, extaddr:6e812de1ef670fd3, role:Leader, mode:0x0f, keyseq:0x1, ...
wpantund[253126]: NCP => …
```
=> [settings] adding Settings class

src/cli/cli.cpp, src/cli/cli_coap.cpp, src/cli/cli_dataset.cpp, src/cli/cli_udp_example.cpp
To avoid issues like:
```
> ifconfig u
Done
> ipmaddr addd ff05::2
Done
```
Which returns 'Done', but actually the command was not executed correctly.
After the change, it will be like this:
```
> ifconfig u
Error 7: InvalidArgs
> ipmaddr addd ff05::2
Error 7: InvalidArgs
```
=> [cli] return error when the command's argument is not supported

src/core/common/notifier.hpp, src/core/thread/thread_netif.cpp, src/core/utils/child_supervision.cpp, src/core/utils/child_supervision.hpp
This commit removes the `Start()/Stop()` APIs from `ChildSupervisor`
class. Instead `ChildSupervisor` class itself would decide when to
start/stop. It registers a `Notifier` callback to be notified when the
Thread role changes and/or when a child is added or removed. If MLE
operation is enabled and there is at least one "valid" child in the
child table, child supervision starts, otherwise it is stopped.
=> [child-supervision] change how child supervision gets started/stopped

examples/platforms/nrf52840/radio.c, src/core/openthread-core-default-config.h
This change allows to define custom otPlatRadioGetIeeeEui64 function on nrf52840 platform.
=> [nrf52840] custom EUI-64 get

src/core/thread/key_manager.cpp, src/core/thread/thread_netif.cpp
This commit moves the setting/initialization of default key from
`ThreadNetif` to `KeyManager` class.
=> [key-manager] set default key from KeyManager

examples/platforms/nrf52840/platform-config.h, examples/platforms/nrf52840/usb-cdc-uart.c
Remove initial delay for USB driver, as it is unnecessary after pseudo reset was introduced.
Additionaly, after USB driver was updated, it behave incorrectly in applications using WFE (for example CLI with WFE enabled got stuck after being flashed, until USB cable was plugged out and in).
=> [nrf52840] remove startup delay after software reset in USB driver

src/core/mac/mac.cpp, src/core/thread/mesh_forwarder.cpp
This commit allows processing of the frame pending bit to occur even if the
received frame is a duplicate.
=> [mac] process frame pending bit at the MAC layer

src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager.hpp, src/core/meshcop/joiner_router.cpp, src/core/thread/mle.cpp
```cpp
const Tlv *DatasetManager::GetTlv(Tlv::Type aType) const
```
The above function returns pointer to stack memory, which could be overwritten before actually using it. I found this issue when debugging commissioning entrust process, which appends SecurityPolicy TLV.
However, the memory pointed by `tlv` returned by the above function was overwritten because the next call to `Message::Append()` will go very deep and the stack goes beyond the `tlv` pointed address.
This PR fixes this issue by removing this convenient function and let the caller provide memory for the wanted dataset.
=> [meshcop] fix dataset manager returning stack pointer

examples/platforms/posix/alarm.c, examples/platforms/posix/platform-posix.h, examples/platforms/posix/platform.c, examples/platforms/posix/sim/alarm-sim.c, examples/platforms/posix/sim/platform-sim.c, tests/toranj/wpan.py
This commit adds a new feature under posix platform to emulate
time (platform Alarm APIs) with a given speed up factor (i.e., as
if time runs `x` times faster). The speed up factor can be given
when running the NCP app as an input argument (default is 1).
=> [posix] enable time speed up feature

tests/toranj/wpan.py
This commit updates the `verify()` definition in `toranj/wpan.py`
module to print the file-name and line number when the condition
fails.
=> [toranj] update verify() to print line-no and test-name

examples/platforms/posix/misc.c, tests/toranj/openthread-core-toranj-config.h, tests/toranj/start.sh, tests/toranj/test-100-mcu-power-state.py, tests/toranj/wpan.py
This commit adds a new test-case (under `toranj`) related to
controlling of NCP's MCU power state and iterations between
NCP and wpantund (related to MCU sleep).
Related PR in wpantund: https://github.com/openthread/wpantund/pull/289
The test covers the following:
- Check newly added wpantund property get and set operations
- Check the `wpantund` state changes between "deep-sleep" and "offline"
- Check the `wpantund` state changes between "offline:commissioned" and "deep-sleep"
- Verify the behavior of `begin-low-power` wpanctl command
- Verify sleep behavior after disabling `wpantund` ("Daemon:Enabled" property) when state is "offline"
- Verify sleep behavior after disabling `wpantund` ("Daemon:Enabled" property) when state is "associated"
=> [toranj] add test case related to MCU power state control

src/core/mac/mac.cpp
This commit changes the `Mac` logic for handling ack timeout to put
the radio in receive mode before invoking the `HandleTransmitDone()`
callback with the `OT_ERROR_NO_ACK` status. This ensures that the
radio can be put to sleep after a no-ack error.
-------
Noticed this in posix simulation mode (when joining as sleepy). This only applies if the radio platform implementation does not implement the ack timeout (and OT `Mac` is used to handle the ack timeout).
=> [mac] on ack timeout switch the radio to receive mode

src/core/utils/channel_manager.cpp, src/core/utils/channel_manager.hpp
This commit fixes an issue to allow "channel manager" feature to be
enabled without requiring the channel-monitor feature.
=> [channel-manager] allow channel manager feature without channel-monitor

src/core/openthread-core-default-config.h, src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit changes how MLE Announce messages are sent in response to
a received MLE Announce. In addition to a multicast MLE Announce
message, a unicast MLE Announce is also sent. This behavior can be
controlled using `OPENTHREAD_CONFIG_SEND_UNICAST_ANNOUNCE_RESPONSE`
config option. By default this is enabled.
This commit also changes actions taken after receiving an MLE Announce
in `Mle::HandleAnnounce()` to handle the situation where a device may
receive multiple MLE Announce messages with same info. No action is
taken if the device is detached, and current channel and panid match
the values from the received MLE Announce message.
=> [mle] send a unicast MLE Announce in response to a received Announce

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp
This commit adds a new method `Mle::SetRole()` to update the device
role. This method is used in MLE class instead of direct assignment to
`mRole` variable. The `SetRole()` will ensure to set flag on
`Notifier` (when there is a role change) and also log the role change.
This change simplifies the code and addresses a (rare) issue where
notifier callback would not be invoked on transition from "detached"
to "disabled" role.
=> [mle] adding SetRole() method to change device role

tests/toranj/start.sh, tests/toranj/test-009-insecure-traffic-join.py
This commit adds a new test-script in `toranj` to test the insecure
traffic exchange (during partial join). The test covers the
following functionalities:
- Using specific insecure port through wpantund `permit-join`
- `wpantund` keeping track of insecure traffic flow (source  address/port) and sending replies insecurely.
- `wpantund` switching to secure mode after receiving a secure message from a source.
=> [toranj] add new test script for insecure traffic exchange (during join)

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_constants.hpp, src/core/thread/mle_router.cpp, tests/toranj/start.sh, tests/toranj/test-603-channel-manager-announce-recovery.py
This commit changes the attach state machine and how the MLE Announce
messages are sent as part of the attach process. A new attach state
`kAttachStateAnnounce` is added where the device sends MLE Announce on
all channels (in Active Dataset's channel mask).
This commit also adds a new `toranj` test-case which tests the
situation where a device misses a channel change and then reattaches
by sending MLE Announce messages.
=> [mle] change the attach MLE Announcement transmissions

examples/platforms/nrf52840/openthread-core-nrf52840-config.h
This PR alignes openthread-core-nrf52840-config.h to the latest heap related define changes introduced in openthread-core-default-config.h.
Signed-off-by: Piotr Szkotak <piotr.szkotak@nordicsemi.no>
=> [nrf52840] fix mbedtls define names in openthread-core-nrf52840-config.h

etc/visual-studio/libopenthread.vcxproj, etc/visual-studio/libopenthread.vcxproj.filters, etc/visual-studio/libopenthread_k.vcxproj, etc/visual-studio/libopenthread_k.vcxproj.filters, src/core/Makefile.am, src/core/common/instance.cpp, src/core/common/instance.hpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/openthread-core-default-config.h, src/core/thread/announce_begin_server.cpp, src/core/thread/announce_begin_server.hpp, src/core/thread/announce_sender.cpp, src/core/thread/announce_sender.hpp, src/core/thread/mle_router_mtd.hpp, tests/unit/test_mac_frame.cpp
This commit adds a new feature/class namely `AnnounceSender` which
enables periodic transmission of MLE Announce messages on all
channels. The feature can be enabled using the config option
`OPENTHREAD_CONFIG_ENABLE_ANNOUNCE_SENDER` (disabled by default).
--------
In terms of implementation, this change refactors common code for 
scheduling/sending MLE Announcements into a base class which is then
sub-classed by `AnnounceSender` and also `AnnounceBeginServer`.
=> [announce-sender] feature to enable periodic tx of MLE Announce

src/core/meshcop/dataset.cpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/thread/mle.cpp
This commit adds new methods/classes related to parsing of Channel
Mask Entries in a Channel Mask TLV.
A new class `ChannelMask0Entry` is added for a Channel Mask Entry
with Channel Page 0.
`ChannelMaskTlv::GetFirstEntry()` and`ChannelMaskEntry:GetNext()`
methods are added and can be used to iterate through all the
entries in a Channel Mask TLV.
New method `ChannelMaskTlv::GetMask0Entry()` can be used to search
among all entries to find the one with Channel Page 0 (if one exist).
=> [meshcop-tlvs] new methods for parsing Channel Mask Entry

tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Without linux/ioctl.h compilation fails on this platform, because _IOC_SIZEBITS will not be defined.
resolves #2711
=> [spi-hdlc-adapter] fix compilation on Alpine Linux with musl libc

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_constants.hpp
This commit changes how the received MLE Announce messages are
processed.
The new implementation adds a delay before taking action when it
receives an MLE Announce message that has a more recent Active
timestamp (compared to device's current Active Dataset timestamp).  A
timeout interval of `kAnnounceProcessTimeout` (250ms) is used before
the device switches to the new channel or pan-id from the received MLE
Announce message. During the timeout interval, device can receive and
parse other MLE Announce messages and it will ignore any with the same
timestamp.
=> [mle] update processing of received MLE Announce messages

tests/toranj/start.sh, tests/toranj/test-010-on-mesh-prefix-config-gateway.py, tests/toranj/wpan.py
This commit adds a new `toranj` test script which covers the
following functionalities:
- Adding on-mesh prefixes using wpantund `config-gateway`
command.
- Prefixes with different flags/priorities on routers/end-devices.
- `wpantund` behavior adding SLAAC based IPv6 address.
- `wpantund` retaining user-added prefixes and adding them back
after an NCP reset.
=> [toranj] adding test-case for adding on-mesh prefix (config-gateway)

src/core/mac/mac.cpp
This commit contains two changes:
- When PAN channel is changed, the CCA success rate tracker is reset
- CCA tracker is updated only for frame transmissions on PAN channel
=> [mac] reset CCA success rate tracker on channel change

include/openthread/types.h, src/core/thread/address_resolver.cpp, src/core/thread/address_resolver.hpp
This commit adds `mAge` field as part of `otEidCacheEntry`. Also
updates comments and fixes minor typo/style issues.
=> [address-resolver] include age field as part of otEidCacheEntry

src/ncp/ncp_base.cpp, src/ncp/ncp_base.hpp
These properties are required for using radio only mode as Thread sniffer.
=> [ncp] enable missing properties in radio only mode

src/core/common/trickle_timer.cpp, src/core/common/trickle_timer.hpp
This commit makes the following changes in `TrickleTimer` class:
- Member variable are renamed to follow the code style guideline.
- New methods added for handling of "end of interval" vs. "middle
of interval" timer fired callbacks.
- The random range selections for mode `kModeNormal` are updated
to follow RFC6206 (closed vs. open range).
=> [trickle-timer] improve/simplify the implementation

src/core/openthread-core-default-config.h, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_constants.hpp
This commit adds "attach backoff" feature in MLE. When enabled, an
exponentially increasing backoff wait time is added between attach
attempts. If device is sleepy, the radio will be put to sleep during
the wait time. This ensures that a battery-powered sleepy end-device
does not drain its battery by continuously searching for a parent to
attach to (when there is no router/parent for it to attach).
`OPENTHREAD_CONFIG_ENABLE_ATTACH_BACKOFF` configuration option can be
used to enable/disable this feature. It is enabled by default.
=> [mle] attach backoff feature

examples/platforms/nrf52840/openthread-core-nrf52840-config.h, examples/platforms/nrf52840/platform-config.h, third_party/NordicSemiconductor/libraries/crypto/aes_alt.c, third_party/NordicSemiconductor/libraries/crypto/aes_alt.h, third_party/NordicSemiconductor/libraries/crypto/aes_alt_cc310.h, third_party/NordicSemiconductor/libraries/crypto/aes_alt_soft.c, third_party/NordicSemiconductor/libraries/crypto/aes_alt_soft.h, third_party/mbedtls/Makefile.am
These are some use cases to do AES in interrupt context in some new features (for example: #2618 network-wide time sync service), it works well with software AES provided by mbedtls, but there are some problems when hardware acceleration is enabled: 
- Some platform's hardware AES has only one AES engine, so it doesn't support concurrent access;
- Some platform's hardware AES doesn't support interrupt context (for example, nRF52840).
This PR resolves the issue by introducing a simple software AES under platform layer:
* Enhance AesCcm to indicate whether it is used in interrupt context
* Introduce a simple software AES under nRF52840 platform layer for AES usage in interrupt context
=> [nrf52840] support aes usage in interrupt context

src/core/openthread-core-default-config.h, src/diag/diag_process.hpp, src/diag/openthread-diag.cpp
Make ot diag output buffer size configurable.
Make ot diag command line max argument number and buffer size configurable.
=> [diags] make diag output & cmd line buffer params configurable

examples/platforms/kw41z/radio.c
The NXP KW41Z radio driver prohibited changing channels while in receive mode; this prevented the leader properly responding to MLE Announces from orphaned child devices. With this fix, the leader will correctly jump to the child's channel (if the child's active timestamp is less than the leader's active timestamp) and perform the proper sequence of announces. Please reference ["ParentRequest/ParentResponse and MLE Announce Timing issue"](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/openthread-users/EGlHwc0Rtbs) for more detailed information.
=> [kw41z] radio driver fix to allow channel change

src/core/thread/mle_router.cpp, src/core/thread/router_table.cpp
After attaching to a network, a device may need to wait until receiving the
next MLE Advertisement before populating the router table.
This commit makes the following changes:
- When receiving an MLE Advertisement, always process the Route TLV when the
router table is not yet populated.
- Have RouterTable::GetLeaderAge() return max value when the router table
is not yet populated.
- When generating a Connectivity TLV, populate the max routing cost when
no leader information is available.
Resolves #2748.
=> [mle] properly handle cases where router table is not populated

src/core/thread/mle_router.cpp
Type value of Connectivity and Route TLV are different under different namespaces
Fix 5.7.x certification issue introduced in #2678
=> [network-diagnostic] fix Connectivity and Route TLV type issue when get

include/openthread/platform/logging.h, src/core/common/logging.hpp, src/ncp/ncp_base.cpp
This commit adds a new log level `NOTE` between `INFO` and `WARN`. The `INFO` level is intended for informational message about behavior of  the network (e.g., info about received/transmitted messages). `NOTE` level is intended for normal but significant events that require special handling (e.g., device getting detached) and are expected to be less frequent that `INFO` level events and logs.
=> [logging] adding a new log level NOTE

src/core/thread/data_poll_manager.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp
Thread 1.1.1 Section 5.9.4 states: "Note that failures to transmit due to
failed clear channel assessments do not count as a failure to receive an
ACK."
=> [mesh-forwarder] do not treat CCA failures the same as no-ack

src/ncp/ncp_spi.cpp, src/ncp/ncp_spi.hpp
This commit makes the following changes in `NcpSpi` class:
- It adds a new class `NcpSpi::Header` which provide helper
methods to parse and update the fields in the header of an SPI
frame.
- It simplifies/enhances the `SpiTransactionComplete()` callback
implementation by combining the parsing of input/output frame
headers with the rx/tx frame processing.
- It adds a check for correct pattern bits in a received frame
flag byte (frames with incorrect pattern bits are ignored).
- Code format is changed to follow the "pretty" style.
=> [ncp-spi] improve callback implementation, change code style format

etc/visual-studio/libopenthread.vcxproj, etc/visual-studio/libopenthread.vcxproj.filters, etc/visual-studio/libopenthread_k.vcxproj, etc/visual-studio/libopenthread_k.vcxproj.filters, src/core/Makefile.am, src/core/common/settings.cpp, src/core/common/string.cpp, src/core/common/string.hpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/joiner.cpp, src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, src/core/thread/address_resolver.cpp, src/core/thread/announce_sender.cpp, src/core/thread/link_quality.cpp, src/core/thread/link_quality.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/utils/channel_manager.cpp, tests/unit/Makefile.am, tests/unit/test_link_quality.cpp, tests/unit/test_mac_frame.cpp, tests/unit/test_string.cpp
This commit adds a new template class `ot::String<size>` which
implements a fixed-length character string. This class is then used as
return value of `ToString()` methods from different classes. This
simplifies the `ToString()` implementation and its use. This commit
also adds a unit test for `String`.
=> [string] adding ot::String<size> class

src/core/thread/mesh_forwarder.cpp
This change removes the log message indicating dropping of a
received beacon frame.
----
This change helps reduce the not-so-useful log message  (which is observed a lot in busy test environment).
=> [mesh-forwarder] do not log dropping of received beacon frames

include/openthread/openthread.h, include/openthread/platform/ble.h
To ensure everything shows up properly in the output of the openthread.io reference script.  Moved one note to the end of a section for consistency and script purposes.
=> [docs] updating Doxygen tags for ble module

examples/platforms/posix/radio.c
This commit changes the posix platform radio implementation by not
invoking the `RadioReceiveDone` callback with error `OT_ERROR_ABORT`.
This is added to help remove extra logs when simulating OpenThread in
posix mode.
=> [posix] skip calling RadioReceiveDone with OT_ERROR_ABORT

tests/toranj/start.sh, tests/toranj/test-012-multi-hop-traffic.py
This commit adds a new `toranj` test script to test IPv6 traffic  exchange over multiple hops in a network with chain topology:
```    
r1 ----- r2 ---- r3 ----- r4
/\       |       |        /\
/  \      |       |       /  \
fed1 sed1  sed2    sed3   sed4 fed4
```
Traffic flow:
- From first router to last router
- From SED child of last router to SED child of first router
- From FED child of first router to FED child of last router
The test covers the following:
- Verifies Address Query process over multi-hop to routers and FEDs.
- Verifies Mesh Header frame forwarding over multiple routers.
- Verifies forwarding of large IPv6 messages (1000 bytes) requiring lowpan fragmentation.
=> [toranj] adding test-case for multi-hop traffic exchange

include/openthread/link.h, include/openthread/platform/radio.h, src/core/mac/mac.cpp, src/core/mac/mac_frame.hpp
The mSecurityValid in otRadioFrame structure is not in use, its functionality was replaced by GetSecurityEnabled() since the change: [link](https://github.com/openthread/openthread/pull/111/files#diff-475cd0819c812a3145866a316ae19af6R1009).
=> [radio] remove unused mSecurityValid from otRadioFrame structure

src/cli/cli_uart.cpp
This could better support gdb debugging. Use ctrl-d as the only elegant way to exit OpenThread.
=> [cli] recover default behavior of ctrl-c

src/core/meshcop/dataset_manager.cpp
For 9.2.7, two partitions at the beginning,
(Leader + Commissioner): only have active dataset with lower timestamp value.
(Commissioner): lower partition id priority, have active and pending dataset with higher timestamp value.
Before this PR, when migrating
issue 1: for pending dataset, when ClearNetwork(), if simply restore from flash, there would be no chance to start the timer and trigger /c/ps
issue 2: When deciding whether to register /c/as in HandleTimer(), the active timestamp in Pending Dataset would always be larger than the active timestamp in Active Dataset. That is, when there is pending dataset, there would be no chance to update the active dataset to Leader (/c/as). 
For 9.2.9, the major difference is that (Leader + Commissioner) have both active/pending Dataset with lower …
=> [dataset] fix dataset update issue

src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp
This commit fixes a bug when calling `MeshForwarder::Stop()` while the
discover operation is ongoing.  In particular, while the send queue is
flushed, `mDiscoverTimer` is not stopped, resulting in a NULL pointer
dereference in the timer handler.
This commit also moves common cleanup code for the discover operation into
a single method.
=> [mesh-forwarder] fix bug when stopping discover request

src/core/meshcop/leader.cpp
This commit fixes Leader's accepting more than one on-mesh commissioners.
For the scenario that two thread network with individual on-mesh commissioner,
both session ids may be 1. When network migrates, the Leader should reject the /c/la
from the commissioner which has just migrated.
This issue is noticed when looking into the traffic of 9.2.7 - after migration, the Leader would accept both /c/la and BA Rloc in commissioning data frequently changes the between the two original on-mesh commissioners.
I don't think it is an expecting behavior.
For this fix, I am not quite sure if it is the best option. Randomizing the session id might be another option.
@jwhui , looking forward to hear your thoughts. Thanks.
=> [commissioner-dataset] initialize mSessionId to a random value

src/core/thread/lowpan.cpp, src/core/thread/lowpan.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp
This commit adds a new method `MeshForwarder::LogMeshMessage()` to log
info about messages with `MeshHeader` (messages that are forwarded by
device). The new logs indicate  when a message is received/sent or
possibly dropped. The immediate source and destination for the
received or sent frame is logged. The new logs include info from
`MeshHeader` such as mesh source, mesh destination, number of hops
left. If the message is fragmented, info from fragment header such as
datagram tag and offset is included in the logs. For a non-fragmented
or a  first fragment `LogMeshMessage()` will also decompress the IPv6
and transport (UDP/TCP) headers and  provide info from them such as
IPv6 payload length, UDP/TCP checksum and IPv6 source/destination
addresses in the logs.
In addition to the new logs, …
=> [mesh-forwarder] add logs for forwarded MeshHeader messages

include/openthread/platform/radio.h, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_frame.hpp
Create a new ProcessTransmitAesCcm() method, which is safe to be called in
interrupt context.
=> [mac] separate aes ccm process from ProcessTransmitSecurity() method

src/core/thread/mle.cpp
This changes addresses the situation where we have a single device
in network configured as sleepy end-device going through attach
backoff intervals and then user changes the device mode to be
non-sleepy and FTD. This change ensures that device become leader
quickly.
=> [mle] reset the attach counter and restart backoff on "mode" change

examples/platforms/efr32/Makefile.am, examples/platforms/efr32/fem-control.c, examples/platforms/efr32/platform.c
On platforms that do not have or need FEM disabled the build is broken now. The solution is to only compile fem-control.c file on platforms that need it.
=> [efr32] fix building errors on boards without FEM

include/openthread/platform/radio.h
Based on finding from today's openthread.io reference update, add missing Doxygen comments for the radio API.
=> [docs] add missing Doxygen comments for radio

include/openthread/platform/logging-windows.h, src/core/net/ip6.cpp, src/core/thread/address_resolver.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/router_table.cpp
This commit changes some of the log messages in `mle`, `ip6`,
`address_resolver` and `router_table` from INFO level to NOTE level.
It also adds missing `otLogNote<>` implementation for windows.
=> [logging] change some log messages from INFO level to NOTE level

include/openthread/platform/logging-windows.h, src/core/common/instance.hpp, src/core/common/logging.cpp, src/core/common/logging.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp
This commit also contains
- Adding `Instance::GetLogLevel()` to get current log level on
device.
- Adding new `otLogMac()` macro to log at MAC region with a run-time
given log level.
=> [mesh-forwarder] update `LogMessage` to use NOTE level for failure/error cases

src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp
This commit changes the way the mesh forwarder layer handles transmit
attempt failures due to CCA failures.  Prior to this commit, the mesh
forwarder layer would simply drop the packet.  This commit keeps the
packet in the queue so that it can be retransmitted at a later time.  This
applies to both direct and indirect transmissions.
=> [mesh-forwarder] retransmit on CCA errors

tests/toranj/wpan.py
----
This should help get rid of logs like this in `travis` (the exit code is expected/normal when many wpantund instances are created at same time). 
```
Starting 'test-601-channel-manager-channel-change'
-> '' exit code: 28
-> '' exit code: 28
-> '' exit code: 28
-> '' exit code: 28
-> '' exit code: 28
-> '' exit code: 28
-> '' exit code: 28
-> '' exit code: 28
-> '' exit code: 28
-> '' exit code: 28
-> '' exit code: 28
'test-601-channel-manager-channel-change' passed.
```
=> [toranj] limit the logs during init of all nodes

src/core/net/ip6.cpp, tests/toranj/start.sh, tests/toranj/test-013-off-mesh-route-traffic.py, tests/toranj/wpan.py
This commit addresses an issue with forwarding of off-mesh traffic
on FED. It also adds a `toranj` test-case to test adding of off-mesh
routes (on routers and FEDs) and traffic flow to off-mesh addresses.
-------------
Test topology:
```
r1 ---- r2
|       |
|       |
fed1    sed2
```
The off-mesh-routes are added as follows:
- `r1`   adds OFF_MESH_ROUTE_1,
- `r2`   adds OFF_MESH_ROUTE_2,
- `fed1` adds OFF_MESH_ROUTE_3.
Traffic flow:
- From `sed2` to an address matching OFF_MESH_ROUTE_1 (verify it is received on `r1`),
- From `r1`   to an address matching OFF_MESH_ROUTE_2 (verify it is received on `r2`),
- From `r2`   to an address matching OFF_MESH_ROUTE_3 (verify it is received on `fed1`)
=> [ip6] fix forwarding of off-mesh traffic on FED

third_party/NordicSemiconductor/drivers/clock/nrf_drv_clock.c
Fix an issue that application could not reinitialize the clock again after nrf_drv_clock_uninit().
=> [nrf52840] set initialized state to false in nrf_drv_clock_uninit()

tests/toranj/test-010-on-mesh-prefix-config-gateway.py, tests/toranj/wpan.py
This commit updates `wpan.py` module to include newly added wpanctl
commands `add-prefix` and `remove-prefix` and include new `stable`
argument for `add-route`. It also updates `test-10` to test the
behavior of the new commands.
=> [toranj] add support for `add-prefix` and `remove-prefix`

tests/toranj/start.sh, tests/toranj/test-014-ip6-address-add.py, tests/toranj/wpan.py
This commit adds a `toranj` test for adding/removing IPv6 addresses
on routers, FEDs, and SEDs (on network interface).
The test then covers the following:
- Verify "IPv6:AllAddresses" wpantund property.
- Verify that prefixes are present in network data corresponding to added addresses (on all nodes).
- Verify that a SED does register the address with its parents ("Thread:ChildTable:Addresses" wpantund property).
- Verify that addresses/prefixes are retained by wpantund over NPC resets.
- Verify that when an address is removed on network interface its corresponding prefix is also removed (on all nodes).
=> [toranj] test-case for adding IPv6 addresses

doc/spinel-protocol-src/spinel-tech-thread.md, src/ncp/ncp_base_mtd.cpp, src/ncp/spinel.h
This commit appends new fields to format of `PROP_THREAD_PARENT`
spinel property. The new fields provide age, avrerage RSSI and
last RSSI, etc. This commit also updates the spinel documentation.
Related PR in wpantund: https://github.com/openthread/wpantund/pull/326
=> [ncp] add new fields (age, rssi, etc) to PARENT spinel property

src/posix/platform/radio_spinel.cpp
* adds missing checks for two radio APIs which don't return error.
* fixes a issue that can cause a failed spinel property operation be treated as success.
=> [posix-app] add missing check for spinel radio

examples/platforms/nrf52840/platform-nrf5.h, examples/platforms/nrf52840/platform.c, examples/platforms/nrf52840/radio.c
Introduce a nrf5RadioPseudoReset() method, it will put the radio to sleep mode, and clear the pending events during pseudo reset. So to avoid unexpected transmit done callback after pseudo reset, which may cause the device to hang.
=> [nrf52840] avoid unexpected transmit done callback after pseudo reset

examples/platforms/nrf52840/platform-nrf5.h, examples/platforms/nrf52840/platform.c, examples/platforms/nrf52840/radio.c, third_party/NordicSemiconductor/drivers/radio/platform/clock/nrf_802154_clock_sdk.c
There are some problems if radio is not reinitialized during pseudo reset:
* It may trigger unexpected otPlatRadioTxDone(), and cause the device to hang;
* The uncleared radio timer queue is invalid, it may block the new added timer which has a larger targer time.
Note: The clock init/deinit is disabled during radio init/deinit.
=> [nrf52840] reinitialize all peripherals except uart for pseudo reset

doc/spinel-protocol-src/spinel-tech-thread.md, src/ncp/ncp_base_dispatcher.cpp, src/ncp/spinel.h
This commit 
- adds `UDP_PROXY_STREAM` in the NCP dispatcher
- removes the deleted/deprecated `TMF_<>` properties in NCP dispatcher
- updates spinel docs, header file and `spinel-tech-thread.md`
=> [ncp] add `UDP_PROXY_STREAM` to dispatcher list and update documents

tests/toranj/test-007-traffic-router-sleepy.py, tests/toranj/test-010-on-mesh-prefix-config-gateway.py, tests/toranj/test-011-child-table.py, tests/toranj/test-012-multi-hop-traffic.py, tests/toranj/test-013-off-mesh-route-traffic.py, tests/toranj/test-014-ip6-address-add.py, tests/toranj/test-602-channel-manager-channel-select.py, tests/toranj/test-603-channel-manager-announce-recovery.py, tests/toranj/wpan.py
This commit changes `wpan.init_all_nodes()` to disable OT/logs on
all nodes as the default behavior.
=> [toranj] disable OT/NCP logs (by default) during initialization of nodes

src/ncp/changed_props_set.cpp, src/ncp/changed_props_set.hpp
This commit increases the maximim number of entries that can be
supported by `Ncp::ChangePropsSet` to 64 by using `uint64_t` to
save the flags instead of `uint32_t`.
=> [ncp] increase ChangedPropsSet max supported entries to 64

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_constants.hpp
To introduce additional time delay for aggregating Child Update Request Messages as discussed in #2858, this commit replaces the task with a timer which has a fixed aggregation delay (1s).
=> [core] update Child Update Request aggregation feature

examples/platforms/posix/radio.c, src/posix/platform/frame_queue.cpp, src/posix/platform/frame_queue.hpp, src/posix/platform/radio_spinel.cpp, src/posix/platform/radio_spinel.hpp
This PR fixes the frequently failures of posix app checks in travis.
1. avoid possibility of reentrant to Hdlc::Decode
2. do not send unwanted ACK to core stack
=> [posix-app] fix bugs of posix apps

examples/platforms/nrf52840/openthread-core-nrf52840-config.h, examples/platforms/nrf52840/platform-config.h, examples/platforms/nrf52840/radio.c, examples/platforms/posix/radio.c, src/core/api/link_raw_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/openthread-core-default-config.h, src/core/thread/mesh_forwarder.cpp
Add a configure option to enable/disable Header IE support: OPENTHREAD_CONFIG_HEADER_IE_SUPPORT
So then the Header IE generation and parsing feature could be enabled separately.
=> [build] separate Header IE feature from time sync code

tests/toranj/wpan.py
This commit also moves the disabling of the logs within the `try`
region to ensure it is retried in case wpantund instance is not
yet ready.
=> [toranj] update wpan.init_all_nodes to allow wait time per node

src/ncp/ncp_base_mtd.cpp
This triggers `variable "error" was set but never used` warning on some compilers.
=> [ncp] remove unused variable from ncp_base_mtd.cpp

include/openthread/platform/radio.h, src/core/Makefile.am, src/core/api/link_raw.hpp, src/core/api/link_raw_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_frame.hpp, src/core/openthread-core-config-check.h, src/core/openthread-core-default-config.h, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, src/ncp/ncp_base_radio.cpp
This commit aligns the MAC CSMA backoff and retransmit configuration more
closely with IEEE 802.15.4-2006.
This PR also reverts #2846.
=> [mac] separate configs for macMaxCSMABackoffs and macMaxFrameRetries

examples/platforms/nrf52840/platform.c
The device hangs when reinitialize cc310 (details in #2898).
=> [nrf52840] don't reinitialize cc310 during pseudo reset

third_party/NordicSemiconductor/libraries/crypto/cc310_mbedtls.c, third_party/NordicSemiconductor/libraries/crypto/cc310_mbedtls.h
Fixes #2896
Linker will discard libmbedcrypto_a-cc310_mbedtls.o when searching mbedTLS library, if it finds weak implementation of nrf5CryptoInit/Deinit before strong ones. Adding additional symbols to this file will prevent this behavior and make linker search libmbedcrypto_a-cc310_mbedtls.o even after weak implementations are found.
=> [nrf52840] prevent linker from dicarding strong nrf5CryptoInit implementation

src/cli/cli.cpp, src/cli/cli_coap.cpp, src/cli/cli_uart.cpp, src/core/api/dataset_api.cpp, src/core/common/message.cpp, src/core/meshcop/border_agent.cpp, src/core/net/dhcp6_client.cpp, src/core/net/dhcp6_server.cpp, src/core/net/ip6_address.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/network_data.cpp, src/core/thread/network_data_leader_ftd.cpp, src/ncp/hdlc.cpp
There should be one return statement per free function or method at the end
of the free function or method.
=> [code-style] remove multiple return statements per free function or method

doc/spinel-protocol-src/spinel-prop.md, src/ncp/spinel.h
This commit updates the documentation of spinel property sections
and also adds a new range `0x080 - 0x08F, 0x1800 - 0x18FF` 
for MeshCop related properties.
=> [spinel] add a section for MeshCop properties and update documentation

tests/toranj/wpan.py
This allows the underlying wpantund process associated with a `Node`
instance to be executed while we are waiting for it to be initialized.
It also protects against any unexpected termination of an instance.
This change would help with the speed of initialization of all nodes,
mainly when there are many instances running in parallel.
=> [toranj] perform a subprocess.poll() on wpantund instance during init

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp
This commit ensures that the `mChildUpdateRequestTimer` timer is used
for retranmission of Data Request messages when there is no pending or
active Child Update Request. It also adds logic to ensure device gets
detached after some number of Data Request attempts with no response.
=> [mle] fix mChildUpdateRequestTimer use for retranmission of Data Reqeust

src/core/mac/mac.cpp
=> [mac] fix build failure with CONFIG_DISABLE_CSMA_CA_ON_LAST_ATTEMPT

src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp, src/core/thread/mle_router_mtd.hpp, tests/toranj/start.sh, tests/toranj/test-011-child-table.py, tests/toranj/test-017-parent-reset-child-recovery.py
The first commit addresses an bug where the child info was not being saved in non-volatile settings. It fixes the following cases in the code where a child id was used to search for a child (using `FindChild()`) instead of the RLOC16 address:
- StoreChild() is changed to accept a const Child & as input parameter avoiding the need to look up the child by ID or RLOC16.
- `SendChildIdResponse()` and `GetChildInfoById()` are updated to perform the search for a child using its RLOC16.
The second  commit adds a new test-case under `toranj`. The test covers the following situation:
- A single parent node with three sleepy and two rx-on children.
- Parent node is reset.
- It is verified that all children are recovered and are present in the parent's child table after …
=> [mle] fix issue with child info being saved in non-volatile settings + toranj test-case

src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit fixes the issue when building at `LOG_LEVEL_NOTE`
ensuring methods such as `AttachModeToString` are included.
=> [mle] fix logging at NOTE level

tests/toranj/start.sh, tests/toranj/test-015-same-prefix-on-multiple-nodes.py
This commit adds a new test script for `toranj` test frame-work
covering the situation when IPv6 addresses with same prefix are
added/removed on multiple nodes. The test verifies that the on-mesh
prefix list on all nodes stays consistent and updated as the addresses
are added/removed and nodes are reset.
-----
Related PR in wpantund: https://github.com/openthread/wpantund/pull/334
This test-case is expected to fail without the related change in `wpantund`.
=> [toranj] test case for adding IPv6 addresses with same prefix on multiple nodes

src/core/thread/mle.cpp, src/core/utils/slaac_address.cpp
This commit makes the following changes:
1. A child that is resynchronizing with its parent after reset always
requests the network data to ensure that it has the latest version.
2. When autoconfiguring SLAAC addresses in response to a network data update
always attempt to add the netif address buffer in case the netif
structure was removed (e.g. due to reset).
Resolves #2932.
=> [ip6] ensure slaac addresses are added back after reset

src/core/common/tlvs.hpp
Reduces code size by 1616 bytes.
Before:
```
$ arm-none-eabi-size output/nrf52840/bin/ot-cli-ftd  
text	   data	    bss	    dec	    hex	filename
175688	    548	  37536	 213772	  3430c	output/nrf52840/bin/ot-cli-ftd
```
After:
```
$ arm-none-eabi-size output/nrf52840/bin/ot-cli-ftd 
text	   data	    bss	    dec	    hex	filename
174072	    548	  37536	 212156	  33cbc	output/nrf52840/bin/ot-cli-ftd
```
=> [tlv] remove unnecessary user-specified constructor

src/core/mac/mac.cpp, src/core/thread/link_quality.cpp, src/core/thread/link_quality.hpp, src/core/thread/mle_router.cpp, tests/unit/test_link_quality.cpp
The child/router entries are generally cleared using `memset()` to avoid
explicitly setting all fields to zero.  As a result, it is necessary to
explicitly clear the link quality state to properly initialize the last
RSSI reading.  The user-specific constructors are also removed.
=> [link-quality] explicitly clear link quality for new child/router

src/ncp/ncp_base_dispatcher.cpp, src/ncp/ncp_base_ftd.cpp, src/ncp/ncp_base_mtd.cpp
-----
Setting `SPINEL_PROP_THREAD_CHILD_TIMEOUT` property is (and should be) supported on MTD build.
=> [ncp] include prop set support for THREAD_CHILD_TIMEOUT in MTD build

examples/platforms/posix/platform-posix.h, examples/platforms/posix/platform.c, tests/toranj/test-001-get-set.py, tests/toranj/test-002-form.py, tests/toranj/test-003-join.py, tests/toranj/test-004-scan.py, tests/toranj/test-005-discover-scan.py, tests/toranj/test-006-traffic-router-end-device.py, tests/toranj/test-007-traffic-router-sleepy.py, tests/toranj/test-008-permit-join.py, tests/toranj/test-009-insecure-traffic-join.py, tests/toranj/test-010-on-mesh-prefix-config-gateway.py, tests/toranj/test-011-child-table.py, tests/toranj/test-012-multi-hop-traffic.py, tests/toranj/test-013-off-mesh-route-traffic.py, tests/toranj/test-014-ip6-address-add.py, tests/toranj/test-015-same-prefix-on-multiple-nodes.py, tests/toranj/test-016-neighbor-table.py, tests/toranj/test-017-parent-reset-child-recovery.py, tests/toranj/test-100-mcu-power-state.py, tests/toranj/test-600-channel-manager-properties.py, tests/toranj/test-601-channel-manager-channel-change.py, tests/toranj/test-602-channel-manager-channel-select.py, tests/toranj/test-603-channel-manager-announce-recovery.py, tests/toranj/test-nnn-template.py, tests/toranj/wpan.py
This PR includes two commits:
**[toranj] add new method to finalize all nodes at end of each test**
The first commit adds a new method `finalize_all_nodes()` in `wpan.Node` class to finalize all previously created instances of `wpan.Node`. It terminates the associated `wpantund` process and waits. 
**[posix] handle signals SIGHUP or SIGTERM and exit**
----
The two changes together should help `toranj` test cases to be included in code coverage results.
=> [toranj] add new method to finalize all nodes at end of each test

.travis.yml, src/core/meshcop/dataset.cpp, src/core/thread/network_diagnostic.cpp
This commit resolves compiler errors generated by gcc8.
This commit also adds gcc8 build checks to travis.
Resolves #2931.
=> [gcc8] resolve compiler errors

examples/platforms/cc2538/radio.c, examples/platforms/cc2650/radio.c, examples/platforms/cc2652/radio.c, examples/platforms/da15000/radio.c, examples/platforms/emsk/radio.c, examples/platforms/kw41z/radio.c, examples/platforms/nrf52840/radio.c, examples/platforms/posix/radio.c, examples/platforms/posix/sim/radio-sim.c, examples/platforms/samr21/radio.c
Sniffing using radio only mode firmware results in packets without timestamp information. This PR attaches timestamp info when in promiscuous mode.
=> [platform] attach timestamp in promiscuous mode

tests/toranj/test-016-neighbor-table.py
---
Reason for this change: Noticed occasional travis CI `toranj` test failures which seem to be due to large number of `wpantund` instances running in parallel . This change should help make such failures less frequent.
=> [toranj] reduce number of routers/children in test-016-neighbor-table

tests/toranj/start.sh, tests/toranj/test-019-inform-previous-parent.py, tests/toranj/wpan.py
This commit adds a new test-case under `toranj` frame-work to verify
the behavior of devices under the "inform previous parent" feature.
With this feature enabled, when a child attaches to a new parent, it
will send an IP message (with empty payload) to its previous parent.
Upon receiving this message the previous parent would immediately
remove the child from its child table.
The test network topology consists of two routers/parents and a single
sleepy child. The child is first attached a parent and is then forced
to switch its parent. It's then verified that the child is removed
from first parent's child table.
=> [toranj] test behavior of "inform previous parent" feature

src/cli/cli.cpp
Both Linux and macOS return number of bytes including the ICMP header.
=> [cli] return number of bytes of ping reply

tests/toranj/start.sh, tests/toranj/test-020-router-table.py, tests/toranj/wpan.py
This commit adds a test-case under `toranj` to verify router table
entries on a network with 4 routers: {r1, r2, r3} forming a loop
with r4 connecting to r3.
```
r1 ------ r2
\        /
\      /
\    /
r3 _____ r4
```
=> [toranj] add test-case for router table

tests/toranj/test-002-form.py, tests/toranj/test-003-join.py, tests/toranj/wpan.py
This commit updates the `toranj` tests related to forming/joining
a network to cover newly added capabilities to wpanctl `form`/`join`
commands (allowing all parameters to be given as part of the
command itself).
--------
PR  in wpantund adding new capability to `form` and `join` commands: https://github.com/openthread/wpantund/pull/340  (merged)
=> [toranj] update form/join tests to cover new wpanctl capabilities

tools/gerrit/README.md, tools/gerrit/git-squash-merge.sh
This commit adds a new script `git-squash-merg` which can help with
performing squash merge of a branch into another. The commit message
includes the list of squashed commits. This script is helpful for
synchronization of git repositories that work with gerrit.
=> [tools] add bash script git-squash-merge

tests/toranj/start.sh, tests/toranj/test-021-address-cache-table.py, tests/toranj/wpan.py
This test verifies the behavior of `AddressResolver` module and entries in Address Cache Table. It also test behavior of nodes when there are topology changes in the network (e.g., a child switches parent). In particular, the test covers the address cache update through snooping, i.e., the logic which inspects forwarded frames to update address cache table if source RLOC16 source differs from entry in the cache table.
----
```
Network topology
r1 ---- r2 ---- r3
|       |       |
|       |       |
c1      c2      c3
```
`c1` and `c3` are FED children, `c2` is an SED.
- Send UDP message from `r1` to `c2` and `c3`
- Verify the address cache entries on `r1` are correct (`c2`  should point to `r2` and `c3` to itself)
- Force a topology change, `c2` attach to `r3`
```
r1 ---- r2 ---- r3
| …
```
=> [toranj] add test-case for address cache table

examples/platforms/nrf52840/alarm.c
=> [nrf52840] fix TimeToTicks function in the alarm port

examples/platforms/posix/flash.c, include/openthread-config-android.h, src/core/openthread-core-default-config.h, src/posix/platform/flash.c
configure settings path on andriod to "/data/thread" as default, which will persist after reboot.
=> [posix] make posix settings path configurable

tests/toranj/start.sh, tests/toranj/test-023-multicast-traffic.py, tests/toranj/wpan.py
This commit adds a test-case under `toranj` covering multicast
traffic exchange over a multi-hop network to the following multicast
IPv6 addresses: link-local/mesh-local all-nodes address, link-local
/mesh-local all-routers address, link-local/mesh-local all-thread-
nodes address, and user-specified multicast address.
---------------
```
r1 ---- r2 ---- r3 ---- r4
|               |
|               |
fed             sed
```
Test covers the following traffic:
-  `r2` =>> link-local all-nodes. Expected to recv on `[r1, r2, r3, fed]`
- `r3` =>> mesh-local all-nodes. Expected to recv on `[r1, r2, r3, r4, fed]`
- `r3` =>> link-local all-routers. Expected to recv on `[r2, r3, r4]`
- `r3` =>> mesh-local all-routers. Expected to recv on all routers
- `r1` =>> link-local all-thread.Expected to recv …
=> [toranj] test covering multicast traffic over multi-hop

tests/scripts/thread-cert/Cert_5_3_03_AddressQuery.py
Before this PR, the average propagation time for bad routing is used in order to shorten the test time. 
As  virtual_time is introduced now and this case fails quite frequently recently, this PR moves to use the worst propagation time for bad routing.
=> [tests] fix unstable Cert_5_3_03

examples/apps/ncp/Makefile.am, src/core/api/link_raw_api.cpp
The main diags module is built together with OT core, which runs on host side, radio only ncp will only act as transceiver and support platform specific diags features. It helps to reduce code size of radio-only NCP.
=> [ncp] remove diags module from radio only ncp

src/core/coap/coap.cpp
The current code make make people misunderstand that it will call the function CoapBase::Receive or Coap::Receive . In fact, when aContext is a CoapSecure object, it will call CoapSecure::Receive.
=> [coap] improve readability

examples/platforms/cc2538/cc2538-reg.h, examples/platforms/cc2538/uart.c
Fix a minor flaw in cc2538 uart initialization. This won't be a problem for default GPIO pin PA0 since it's the default value for the corresponding register. If a user wants to use a custom GPIO, however, the uart rx will not work as expected.
=> [cc2538] fix wrong uart rx ioc config

src/core/meshcop/dataset.cpp, src/core/thread/mle.cpp
This commit changes the code to treat Channel Mask TLV from
Operational Dataset and the MAC layer supported channel mask as
two different (unrelated) network parameters. In particular:
- With this commit, the Channel Mask TLV value is ignored when
applying a Dataset from `Dataset:ApplyConfiguration()`.
- However, when we create an Active Operational Dataset as leader in
`ActiveDataset::GenerateLocal()` method, the MAC layer's supported
channel mask is still used for the Dataset Channel Mask TLV value.
- This commit also adds a check in `Mle::SendAnnounce()` to ensure
that MLE Announcements are not sent on channels that are are not
included in the MAC layer's supported channel mask.
-----------
Should help address Issue  https://github.com/openthread/openthread/issues/3056.
=> [dataset] do not use Channel Mask TLV as MAC supported channel mask

src/posix/platform/Makefile.am, src/posix/platform/hdlc.cpp, src/posix/platform/radio_spinel.cpp, src/posix/platform/spinel.c
The symbolic link file and the real file are treated as different files when performing code coverage tests. This PR removes link file and generate `inc_*` files to work around the `distcleancheck` issue(see [travis failure](https://travis-ci.org/bukepo/openthread/jobs/427109480)).
=> [posix-app] remove link file from posix-app

src/ncp/ncp_base.cpp, src/ncp/ncp_base_dispatcher.cpp, src/ncp/ncp_base_mtd.cpp
-----
PR https://github.com/openthread/openthread/pull/3051 helped add support for getting (real) RSSI from the RCP (NCP in radio mode) using the `SPINEL_PROP_PHY_RSSI` property.
This PR chanages the this propery from MTD/FTD mode only to a common one (supported in all builds including radio mode RCP)
=> [ncp] add support for SPINEL_PROP_PHY_RSSI property in radio only mode

src/core/net/icmp6.cpp
I believe the idea behind [this change](https://github.com/openthread/openthread/pull/3016/files#diff-4eeb1f333894faf7f7e14d1c228b453bL162) in #3016 was too check if `HandleEchoRequest` is not failing.
The result is that ICMPv6 Echo Requests are not passed to user-defined ICMPv6 callback registered via `otIcmp6RegisterHandler` function (see couple line below my change).
This feature is very important for us.
=> [icmp6] pass Echo Request messages to user-defined callback

.travis.yml, .travis/before_install.sh, .travis/check-android-build, .travis/script.sh
The android check used to download the latest ndk-bundle. However there is some big change in the latest ndk-bundle which causes the check fails. This PR stick the ndk-bundle to `https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip`
=> [travis] fix android check for ndk upgrade

src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp
This commit adds check in `Leader::RegisterNetworkData()`to validate
the received network data and ensure it only contains entries matching
the RLOC16 of the device registering the network data. It updates
`RlocLookup()` method to add a new mode to allow or not allow any
entries that do not match the given RLOC16.
=> [network-data] check and validate received network data before registering

src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp, src/core/thread/network_data_tlvs.hpp, tests/toranj/start.sh, tests/toranj/test-025-network-data-timeout.py, tests/toranj/wpan.py
This commit makes changes to ensure the `Leader::RemoveRloc` methods
remove all matching entries from a `BorderRouterTlv` or `HasRouteTlv`
It adds new methods to `BorderRouterTlv` and `HasRouteTlv` to get the
first entry or last entry and allow an easier way to iterate over all
the entries.
This commit also adds a new helper method `RlocMatch()` to simplify
the comparison of RLOC16 values (exact match vs router id match).
----
PR https://github.com/openthread/openthread/pull/2905 helped fix the issue to clean a child-added network data when its parent is removed. This PR address a related issue where if there were multiple matching entries, only the first one would have been removed (we would `break` from the loop going over entries upon finding a match).
=> [network-data] remove all matching entries from `RemoveRloc` methods

include/openthread/thread.h, src/core/api/thread_api.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp
This Feature allows OT to share some of the parent response stats with application when a callback for the same is installed.
=> [mle] API to provide MLE Parent Response information

.travis.yml, tests/toranj/openthread-core-toranj-config.h, tests/toranj/start.sh, tests/toranj/test-602-channel-manager-channel-select.py, tests/toranj/wpan.py
This commit updates `toranj` framework to allow a different mode of
operation where tests are run using posix-app along with an RCP (NCP
in radio only mode) build. This commit also adds a new job for the
new model in travis CI build matrix.
=> [toranj] enable new mode "posix app and RCP"

tests/toranj/test-100-mcu-power-state.py
---
This relates to the change in https://github.com/openthread/wpantund/pull/352 (which can add a delay between state transitions).
=> [toranj] relax wpan state transition checks in test-100-mcu-power-state

examples/drivers/windows/README.md
- added note about lack of maintenance
- fixed links to AppVeyor and updated binary download instructions
=> [docs] update Windows 10 README

tools/harness-thci/OpenThread_WpanCtl.py
Fix 7.1.2,  some reference device looks requiring preferred flag
=> [thci] fix preferred flag when config border router for ncp device

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp
This commit distinguishes the attach same process during downgrade from
the one caused by losing connectivity as for the former downgrade
scenario, there must be enough active routers to provide connectivity,
and additional benefits is to avoid the impact of possible flooding parent
responses if there are lots of REEDs in large scale thread network.
=> [core] update first parent request with only R flag during downgrade

src/core/meshcop/joiner_router.cpp
Port should only be set with `UdpSocket::Bind()`.
=> [meshcop] do not set joiner port in constructor

src/core/thread/mle_router.cpp, tests/toranj/start.sh, tests/toranj/test-027-child-mode-change.py, tests/toranj/wpan.py
This PR contains two separate commits:
**[mle] save child info in settings on mode or timeout change**
This commit changes `MleRouter::HandleChildUpdateRequest()`:
- If the child entry is modified (i.e., timeout value or device mode changes) on an already attached child, the child info is updated and saved in the non-volatile settings. This ensures that after a parent reset the child can be recovered correctly.   
- If the "Child Update Request" causes a mode change from rx-on to sleepy on a child in `kStateValid` (already attached), the source match controller is set to perform source address matching on the short address.    
- This commit also adds a log to indicate mode change of a child.
----
A new `toranj` test-case covering the scenario causing the issue:
**[toranj] test-case to …
=> [mle] save child info in settings on mode change

configure.ac, examples/platforms/posix/Makefile.platform.am, src/cli/cli_server.hpp, src/core/net/netif.hpp, src/posix/Makefile.am
Some platforms don't have libstdc++
* removed pure virtual function `__cxa_pure_virtual`
* added option use `-fno-exceptions -fno-rtti`
=> [core] remove dependency on libstdc++

include/openthread/instance.h, include/openthread/platform/radio.h, src/core/api/instance_api.cpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base_dispatcher.cpp, src/ncp/ncp_base_mtd.cpp, src/ncp/spinel.c, src/ncp/spinel.h, src/posix/platform/radio_spinel.cpp, src/posix/platform/radio_spinel.hpp, tests/toranj/openthread-core-toranj-config.h
This commit contains the following changes:
- It adds `otPlatRadioGetVersionString()` as an optional radio
platform API. If the radio platform does not implement this
function, OpenThread core provides a default weak implementation
of this function which return the OpenThread version.
- A public OpenThread API `otGetRadioVersionString()` is added which
provides the radio version string.
- POSIX App is updated to get the version from its RCP and provide
`otPlatRadioGetVersionString()`
- A new spinel capability `SPINEL_CAP_POSIX_APP` is added which
corresponds to `ENABLE_POSIX_APP` configuration.
- A new spinel property `SPINEL_PROP_RCP_VERSION` (only available
in POSIX_APP) is added which gets the RCP version.
-----------
Related PR in wpantund: …
=> [posix-app] get RCP (NCP in radio mode) version

src/ncp/spinel.h
The `sys/cdefs.h` is an internal header of `glibc` and is not meant to
be used by user code.  The macros needed from it can be trivially
implemented where required, relying on this header being present
excludes OpenThread from being used on systems where `glibc` is not the
used C library (e.g. OpenWRT, where `uclibc` or `musl` is standard).
https://wiki.musl-libc.org/faq.html#Q:-When-compiling-something-against-musl,-I-get-error-messages-about-%3Ccode%3Esys/cdefs.h%3C/code%3E
=> [spinel] do not use glibc-internal header sys/cdefs.h

.travis/before_install.sh, .travis/check-posix-app-pty, .travis/posix-app-pty, .travis/script.sh, configure.ac, include/openthread/platform/Makefile.am, include/openthread/platform/udp.h, include/openthread/udp.h, src/core/api/udp_api.cpp, src/core/net/ip6.cpp, src/core/net/udp6.cpp, src/core/net/udp6.hpp, src/posix/Makefile-posix, src/posix/platform/Makefile.am, src/posix/platform/platform-posix.h, src/posix/platform/system.c, src/posix/platform/udp.cpp
This PR defines a set of platform APIs to integrate UDP layer of OpenThread with that of platform.
With this PR, services or applications developed upon OpenThread can be also accessed through platform's own network interface, e.g. socket() on POSIX.
The following figure shows how this works.
```
App
|
+----------------------------------------+------+
|               OpenThread Core          |      |
|                                        |      |
|   MLE          TMF      BorderAgent    |      |
|    |            |           |          |      |
| ot Socket    ot Socket   ot Socket  ot Socket |
|    |            |           |          |      |
|    |   +--------+--------+  |          |      |
|    |   |Joiner Entrust   |  |          |      |
|    +-+-+                 +--+--+-------+ …
```
=> [posix-app] platform UDP

configure.ac
Addresses the following build error by OSS-Fuzz.
```
Step #12: clang-8: error: invalid argument '-fsanitize=vptr' not allowed with '-fno-rtti'
```
=> [fuzz] exclude -fno-rtti when fuzzer is enabled

src/core/mac/link_raw.cpp
----
This makes the `link-raw` behavior similar to how `mac.cpp` behaves.
=> [link-raw] retransmit frames on any error

include/openthread/coap_secure.h, src/cli/cli_coap_secure.cpp, src/core/api/coap_secure_api.cpp, src/core/coap/coap_secure.cpp, src/core/coap/coap_secure.hpp, src/core/meshcop/joiner.cpp, src/core/net/socket.hpp
This PR make the CoAP connect API consistent to the UDP's connect API.
=> [coaps] refine definition of CoapSecure::Connect

src/ncp/ncp_base.cpp, src/ncp/ncp_base.hpp, src/ncp/ncp_base_ftd.cpp, src/ncp/spinel.c, src/ncp/spinel.h
- Register a callback API to receive parent response info in "ncp_base" class constructor.
- Added a new Spinel key to send the parent response info data to host.
=> [ncp] send Parent Response info on NCP FTD configuration

examples/platforms/nrf52840/alarm.c
It may cause the issue that the timestamp provided by nrf_802154_received_timestamp_raw()
is not consistent with otPlatAlarmMicroGetNow().
=> [nrf52840] fix the k802154Sync timer

.travis/script.sh, configure.ac, src/core/Makefile.am, src/core/common/extension.hpp, src/core/common/extension_example.cpp, src/core/common/instance.cpp, src/core/common/instance.hpp, src/ncp/ncp_base.cpp
This commit contains the following changes:
- It adds a new configure option "--with-vendor-extension" allowing
users to add a source file to be built along with OpenThread core
library. `OPENTHREAD_ENABLE_VENDOR_EXTENSION` indicates whether
this feature is enabled or not.
- It adds a class `Extension::ExtensionBase` which defines the hooks
from OpenThread into the vendor extension module. Vendor extension
code should inherit from this class and provide the implementation
of the defined methods.
- A source file `extension_example.cpp` is added to provide an example
on how to implement an OpenThread vendor extension.
- One of the build configuration under Travis CI posix target is
updated to enable the vendor extension feature and verify the
build.
=> [core] add support for external OT vendor extension

.travis/script.sh, src/core/meshcop/dtls.cpp, third_party/mbedtls/mbedtls-config.h
Reduces code size by **20,756 bytes** when DTLS is enabled.
```
$ arm-none-eabi-size output/cc2538/bin/ot-cli-ftd 
text	   data	    bss	    dec	    hex	filename
218360	   4588	  21648	 244596	  3bb74	output/cc2538/bin/ot-cli-ftd (before)
197604	   4588	  21644	 223836	  36a5c	output/cc2538/bin/ot-cli-ftd (after)
```
=> [mbedtls] disable debug by default

src/core/coap/coap_secure.cpp, src/posix/platform/udp.cpp
Disconnect socket in `CoapSecure::Disconnect()`
More Info:
[connect() on Linux]: https://linux.die.net/man/2/connect
[connect() on macOS]: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/connect.2.html
=> [coaps] fix disconnect in CoAP secure

src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp
This commit changes `Mac` implementation to use direct callbacks into
`MeshForwarder` to inform it of a frame reception or status of a
requested frame transmission. This changes replaces the `Mac::Sender`
and `Mac::Receiver` model.
=> [mac] use direct callbacks into mesh forwarder for send/recv

src/posix/platform/radio_spinel.cpp, src/posix/platform/radio_spinel.hpp, tests/toranj/openthread-core-toranj-config.h
This commit contains the following changes:
- It adds code to `RadioSpinel::Init()` to get and check the RCP
capabilities (`SPINEL_PROP_CAPS`) ensuring RCP supports radio/raw
mode (`SPINEL_CAP_MAC_RAW`).
- It adds support for handling stream log `SPINEL_PROP_STREAM_LOG`
property from RCP.
- It moves the existing code checking spinel version and radio
capabilities of RCP into helper methods `CheckSpinelVersion()`
and `CheckRadioCapabilities()`.
=> [posix-app] check RCP capabilities and add support for stream log

.travis/script.sh, configure.ac, examples/common-switches.mk, include/openthread/crypto.h, src/core/Makefile.am, src/core/api/crypto_api.cpp, src/core/crypto/ecdsa.cpp, src/core/crypto/ecdsa.hpp, third_party/mbedtls/mbedtls-config.h
This PR adds support for ECDSA signing, needed e.g to authenticate device with Google Cloud Platform. It does not fit ideally in the OT core, but its useful especially because of mbedtls additional config options. 
Alternatively i can propose change only in the `third_party/mbedtls/mbedtls-config.h` file.
I checked that this PR does not add any Flash or RAM when compiling ot-cli-ftd for nRF52840 without ECDSA flag set.
=> [crypto] add support for ECDSA signing

src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/meshcop/joiner.cpp
This commit adds method `GenerateRandom()` to `Mac::ExtAddress` to
generate a random IEEE 802.15.4 Extended Address with either a given
or default Group and Local bit settings. This method replaces the
`Mac` class `GenerateExtAddress()` method.
=> [mac] add "Mac::ExtAddress::GenerateRandom()" to create random address

src/core/mac/mac.cpp, src/core/mac/mac.hpp
This commit changes the `Mac` operation scheduling to allow
users to start a new operation from the done callback handler of
a previous operation. For example, calling `Mac::ActiveScan()`
from a previous `mActiveScanHandler` callback handler should
succeed.
This is realized by ensuring to call `FinishOperation()` before
invoking the done callback and after the callback, perform any
pending next operation by calling `PeformNextOperation()`.
=> [mac] allow same operation to start from done callback handler

src/core/coap/coap_secure.cpp, src/core/coap/coap_secure.hpp
This PR removes transmit task and send data directly in `CoapSecure`, otherwise Dtls stills relies on CoapSecure after success call to Close(), because it relies on it to send Close Alert.
=> [coaps] directly send DTLS message

examples/platforms/posix/platform-posix.h, examples/platforms/posix/sim/platform-sim.c, examples/platforms/posix/sim/radio-sim.c, include/openthread/link_raw.h, src/core/api/link_raw_api.cpp, src/core/common/instance.hpp, src/core/mac/link_raw.cpp, src/core/mac/link_raw.hpp, src/core/mac/mac_frame.hpp, src/ncp/ncp_base_radio.cpp
`otPlatRadioGetTransmitBuffer()` may return different values and even null on certain platform. This PR changed link raw so that this API is only called once. Otherwise, it may result in null pointer crash.
Besides,
* avoided reentrance issue of InvokeTransmitDone by deferring transmit in a tasklet.
* corrected how software retransmissions behavior when radio itself supports retransmission.
=> [link-raw] fix radio with multiple transmit buffers

include/openthread/thread.h, src/core/api/thread_api.cpp, src/core/net/netif.cpp, src/core/net/netif.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/thread_netif.cpp
This PR adds link local address when MLE is enabled. Adding address in constructor gives no chance to notify address change with address callback.
=> [mle] add address outside of constructor

.travis/script.sh, configure.ac, examples/Makefile-posix, examples/common-switches.mk, include/openthread-config-android.h, include/openthread/udp.h, src/core/api/udp_api.cpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/border_agent.hpp, src/core/net/udp6.cpp, src/core/net/udp6.hpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base.hpp, src/ncp/ncp_base_dispatcher.cpp, src/ncp/ncp_base_mtd.cpp, src/ncp/spinel.c, src/ncp/spinel.h, src/posix/Makefile-posix
Thread defines UDP proxy as a feature to allow secure, two-way
communication of Thread Management Commands between the Commissioner
and any Thread Device in the Thread Network via the Border Agent.
This PR renames the existing UDP proxy feature which forwards UDP
packets back and forth between Host and NCP to UDP forward.
=> [core] rename UDP proxy to UDP forward

src/cli/cli.cpp
Network time is a uint64 aka unsigned long `%lu`
=> [cli] fix network time format specifier

include/openthread/ip6.h, src/core/api/ip6_api.cpp
This PR exposes the API to select a proper source address so that upper layer can easily choose a source address when it wants to send a packet through OpenThread but the source address is unspecified.
=> [api] expose API to select source address

third_party/NordicSemiconductor/libraries/crypto/nrf52840-mbedtls-config.h
This PR suppresses warning on Keil and IAR introduced with new mbedtls:
`openthread\third_party\mbedtls\repo\library\pkparse.c(1146) : Error[Pe550]: variable "ret" was set but never used`
The other IAR warnings have been fixed and so workarounds are removed.
=> [nrf52840] suppress warning in mbedtls in Keil and IAR compiler

src/core/thread/time_sync_service.cpp
After a reboot, `TimerMilli::GetNow()` begins counting from 0 (at least on the efr32). This has the effect that when `mLastTimeSyncReceived` is 0 (its initialised value), the check for
`timeSyncLastSyncMs > resyncNeededThresholdMs` returns false within the first 60 seconds of uptime, and the status of `OT_NETWORK_TIME_SYNCHRONIZED` is inadvertently taken.
Add a check to prevent this and return `OT_NETWORK_TIME_UNSYNCHRONIZED` when `mLastTimeSyncReceived` is 0
=> [time-sync] fix incorrect status after boot

examples/platforms/efr32/radio.c, examples/platforms/efr32/uart.c
These variables are modified from interrupt context and therefore should be marked as volatile
=> [efr32] add missing volatile qualifiers

Android.mk, src/posix/platform/Makefile.am, src/posix/platform/hdlc_interface.cpp, src/posix/platform/hdlc_interface.hpp, src/posix/platform/radio_spinel.cpp, src/posix/platform/radio_spinel.hpp
This commit adds a new class `HdlcInterface` under POSIX App which
performs HDLC encoding/decoding and read/write operations on the
interface to Radio Co-Processor (RCP). `RadioSpinel` is updated to
use the new class.
----------
This PR mainly moves existing logic related to RCP interface and HDLC encoding/decoding from `RadioSpinel` into a separate `HdlcInterface` class. 
**Motivation for this change:** The `RadioSpinel` class currently does 3 related tasks.
- It implements the interface to RCP and perform HDCL encoding and decoding
- It processes Spinel messages (providing blocking Spinel property `Set`, `Get`, `Insert`, `Remove` methods).
- It implements a radio platform abstraction (implementing `otPlatRadio<>` equivalent).
The idea is to break it into 3 components. This is the first …
=> [posix-app] add HdlcInterface class

include/openthread/ip6.h, src/core/api/ip6_api.cpp, src/core/net/dhcp6_client.cpp, src/core/net/netif.cpp, src/core/net/netif.hpp, src/core/utils/slaac_address.cpp
This PR adds API to register a callback for *internal address* changes on Thread network interface. External address changes will not be notified by this callback.
=> [netif] add address callback

src/posix/platform/radio_spinel.cpp, src/posix/platform/radio_spinel.hpp
---
Quick follow-up on https://github.com/openthread/openthread/pull/3293. `HandleHdlcError` is moved to `HdlcInterface` class (from `RadioSpinel`) so removing it from `RadioSpinel`.
=> [radio-spinel] remove unused method HandleHdlcError

src/posix/platform/radio_spinel.cpp, src/posix/platform/radio_spinel.hpp
---
This commit uses a separate frame buffer (`mAckRadioFrame`) for saving acks instead of using `mRxRadioFrame` (which is used for received frames). 
**Why this change?**
This ensures that the ack frame won't be overwritten by a subsequently received frame. 
- Ack frame is read and saved in `HandleTransmitDone()` (which we get to from `HandleSpinelFrame() -> HandleResponse() -> HandleTransmitDone()`).
- But note that the saved ack frame is not immediately used, it is passed from `RadioSpinel::Process()` to next layer using `otPlatRadioTxDone()` callback.
- We can technically read and decode multiple spinel frames from a single call to `mHdlcInterface.Read()`:
- So we can possibly get a TxDone spinel frame response where we read and save the ack frame;
- And before getting the chance to …
=> [radio-spinel] use a dedicated mAckRadioFrame for acks

src/core/thread/mle_router.cpp
Also do not respond to MLE Parent Requests when trying to merge partitions.
=> [mle] do not respond to MLE Parent Requests in detached state

src/core/net/dhcp6_server.cpp, src/core/thread/mle.cpp
This change is made so that address callback can use prefix length to determine if the changed address is multicast or not.
=> [ip6] use mesh local prefix length as ALOC prefix length

src/posix/platform/hdlc_interface.cpp, src/posix/platform/hdlc_interface.hpp
This commit changes `HdlcInterface` method `SendFrame()` to handle
the case where the socket associated with the HDLC interface is
not immediately ready to accept the frame. With the change in this
commit `SendFrame()` will block and wait for socket to become
writable within a timeout interval.
---
- Note that `RadioSpinel` does check the socket to be writable when sending raw 15.4 frame (from `Process() -> RadioTransmit() -> ... -> SendFrame()`)
- But `otPlatRadioGet/Set` APIs (like `otPlatRadioSetPanId()`)  can be called at any point and they can trigger a call to `SendFrame()` when the socket may not be writable.
=> [hdlc-interface] wait for socket to be writable when sending a frame

src/posix/platform/hdlc_interface.cpp
This commit changes `HdlcInterface::Read()` method to ignore `errno`
`EINTR` (interrupt by a signal) during socket `read()`. It also
uses `exit()` on error.
=> [hdlc-interface] ignore errno EINTR in socket read

src/posix/platform/radio_spinel.cpp, src/posix/platform/radio_spinel.hpp
This commit defines as new set of `State` enumerations which
combines the two state variables `otRadioState` and `TxState`
into a single `mState` variable.
------------
```
kStateDisabled         ->    OT_RADIO_STATE_DISABLED   && (mTxState == kIdle)
kStateSleep            ->    OT_RADIO_STATE_SLEEP      && (mTxState == kIdle)
kStateReceive          ->    OT_RADIO_STATE_RECEIVE    && (mTxState == kIdle)
kStateTransmitPending  ->    OT_RADIO_STATE_TRANSMIT   && (mTxState == kIdle)
kStateTransmitting     ->    OT_RADIO_STATE_TRANSMIT   && (mTxState == kSent)
kStateTransmitDone     ->    OT_RADIO_STATE_TRANSMIT   && (mTxState == kDone)
```
=> [radio-spinel] simplify state definitions in RadioSpinel

include/openthread/coap.h
Since RFC-7252 a number of additions have been made to the CoAP
Content-Format registry which is maintained by the IANA.  This patch
updates the list in OpenThread.  Notably:
- Standards references are made for each entry
- Some invalid assignments have been removed (notably PKCS10, PKCS7 and
JWS)
- New entries have been added for COSE, JSON patches, merge patches,
CBOR, CWT, CoAP groups, SENML and SENSML.
=> [coap] update the Content-Format enumeration

src/posix/platform/radio_spinel.cpp
This commit changes the logic in `RadioSpinel` such that the HDLC
socket is always added to read fd set in `UpdateFdSet()` replacing
the existing code where read was not allowed during an ongoing 15.4
frame transmission. Note that during a frame transmission, radio can
potentially receive a frame (e.g. during CSMA backoffs). Also other
spinel frames such as logs can be received during tx.
=> [radio-spinel] always be ready to read from socket

Android.mk
It introduces a way that user can define product specific configuration
for OpenThread build in Android Environment.
Also ensure that ot-cli and ot-ncp use the same mbedtls config with ot-core.
=> [android] include user defined configuration in Android.mk

src/posix/platform/radio_spinel.cpp, src/posix/platform/radio_spinel.hpp
This commit changes `RadioSpinel` to determine if Ack is present
directly from the received spinel TxDone frame (i.e. check the
remaining unparsed length of spinel frame to determine if ack frame is
included by Radio Co-Processor (RCP)). This change helps simplify the
code by removing the requirement for `RadioSpinel` as the layer
between OpenThread core and RCP to parse the 15.4 frame.
=> [radio-spinel] determine presence of Ack from spinel TxDone frame

Android.mk, etc/visual-studio/libopenthread.vcxproj, etc/visual-studio/libopenthread.vcxproj.filters, etc/visual-studio/libopenthread_k.vcxproj, etc/visual-studio/libopenthread_k.vcxproj.filters, src/core/Makefile.am, src/core/api/link_raw_api.cpp, src/core/common/instance.hpp, src/core/common/timer.hpp, src/core/mac/link_raw.cpp, src/core/mac/link_raw.hpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/mac/sub_mac_callbacks.cpp
This commit introduces sub-MAC layer (class `Mac::SubMac`) in OpenThread implementing a subset of IEEE802.15.4 MAC primitives which are shared by both MAC layer (in FTD/MTD modes) and Raw Link (Radio only mode).
The sub-MAC layer handles the following (if not provided by radio platform):
- Ack timeout for frame transmission,
- CSMA backoff logic,
- Frame re-transmissions,
- Energy scan on a single channel and RSSI sampling.
It also act as the interface (to radio platform) for setting/getting radio configurations such as short or extended addresses or PAN Id.
In addition, this commit contains following improvements in `Mac`:
- The implementation of `STAY_AWAKE_BETWEEN_FRAGMENTS` (delay sleep)   feature is simplified by adding a new state variable tracking if  sleep is being delayed and …
=> [mac] adding sub-MAC layer

tools/harness-thci/OpenThread_WpanCtl.py
Test log of certification test case 9.2.14:
COM39 call MGMT_PANID_QUERY
sudo wpanctl -I wpan0 commissioner pan-id-query 0xface 11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26 fd00:db8:0:0:46e7:955e:c25f:c2af
sending [sudo wpanctl -I wpan0 commissioner pan-id-query 0xface 11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26 fd00:db8:0:0:46e7:955e:c25f:c2af]
[COM39] Expecting [sudo wpanctl -I wpan0 commissioner pan-id-query 0xface 11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26 fd00:db8:0:0:46e7:955e:c25f:c2af]
[COM39] Got line [sudo wpanctl -I wpan0 commissioner pan-id-query 0xface 11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26 fd00:db8:0:0:46e7:955e:c25f:c2af]
[COM39] Expected [sudo wpanctl -I wpan0 commissioner pan-id-query 0xface 11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26 …
=> [thci] pass the channel mask as a comma separated channel string

src/core/thread/mle_router.cpp
Print partition id as unsigned int to be consistent with all other prints
of partition id.
=> [mle] print partition id as unsigned int

examples/Makefile-nrf52840, examples/platforms/nrf52840/Makefile.am, examples/platforms/nrf52840/README.md, examples/platforms/nrf52840/platform-config.h, examples/platforms/nrf52840/usb-cdc-uart.c, third_party/NordicSemiconductor/README.md, third_party/NordicSemiconductor/dependencies/nrf_log_ctrl.h, third_party/NordicSemiconductor/dependencies/nrf_log_ctrl_internal.h, third_party/NordicSemiconductor/dependencies/sdk_config.h, third_party/NordicSemiconductor/libraries/usb/app_usbd_nrf_dfu_trigger.c, third_party/NordicSemiconductor/libraries/usb/app_usbd_nrf_dfu_trigger.h, third_party/NordicSemiconductor/libraries/usb/app_usbd_nrf_dfu_trigger_internal.h, third_party/NordicSemiconductor/libraries/usb/app_usbd_nrf_dfu_trigger_types.h, third_party/NordicSemiconductor/libraries/usb/nrf_dfu_trigger_usb.c, third_party/NordicSemiconductor/libraries/usb/nrf_dfu_trigger_usb.h
This PR adds support for the USB DFU trigger used to enter the bootloader from the application in order to flash it on compatible platforms (requires a device with a GPIO connected to the RESET pin).
PCA10059 is an example of the compatible hardware.
The feature has been requested in #3271.
To enable the support, compile the OpenThread with the following flags:
openthread$ make -j -f examples/Makefile-nrf52840 USB=1 BOOTLOADER=1
It has been tested with the latest nrfconnect 2.6.1 with programmer 1.0.0 app.
=> [nrf52840] add support for the USB DFU software trigger

src/core/common/instance.cpp, src/core/openthread-core-default-config.h
Add OPENTHREAD_CONFIG_INTITIAL_LOG_LEVEL config setting to enable
starting OpenThread with a lower log level that the maximum compile-time
setting. Useful when OPENTHREAD_CONFIG_ENABLE_DYNAMIC_LOG_LEVEL is
defined to 1.
=> [logging] add initial log level config option

src/posix/platform/hdlc_interface.cpp, src/posix/platform/hdlc_interface.hpp
`HdlcInterface` doesn't wait for spi-hdlc-adapter exit when exit() is called. This PR adds destructor to wait such that there will not be untracked process warnings in android.
=> [android] fix untracked pid

src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp
This PR should fix #3351.
I was able to replicate incorrect behavior and after applying this fix i don't see this problem anymore.
Additionally, state update timer resolution has been increased to 1 minute (there is no need to wake up MCU each 1 second).
=> [network-data] synchronize 6LoWPAN Contexts after Leader is reset

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp
The leader does not maintain network data in non-volatile memeory. As a
result, it is necessary for a recently-restored leader to obtain network
data from a neighboring device.
This PR is related to #3351.
=> [network-data] retrieve network data when restoring as leader

src/core/crypto/ecdsa.cpp
This PR fixes potential stack corruption. In case private key contains incorrect format, `rMpi` and `sMpi` are freed without initialization.
=> [ecdsa] do not free mpi context before initializing it

src/core/thread/mesh_forwarder_ftd.cpp
This commit moves the logging of a message transmission status and
updating of the counters in `MeshForwarder::HandleSentFrameToChild()`
inside the `if` block checking for the message to be indirect. This
change addresses an issue where message transmissions to a non-sleepy
child could be logged and counted twice from both `HandleSentFrame()`
and `HandleSentFrameToChild()`.
=> [mesh-forwarder] fix double logging msg tx to non-sleepy child

third_party/NordicSemiconductor/libraries/crypto/nrf52840-mbedtls-config.h
ECDSA is already enabled in
https://github.com/openthread/openthread/blob/master/third_party/mbedtls/mbedtls-config.h#L137
=> [nrf52840] only enable ecdsa when OpenThread configures

src/core/mac/mac.hpp
This class removes unused method definitions in `Mac` class. Note
that these methods are now provided and used in `SubMac`.
=> [mac] remove unused method definitions

src/core/thread/src_match_controller.cpp
This commit changes/simplifies the `SourceMatchController` class to
use the `Mac::Address` class API to reverse an extended address
when adding/clearing an address.
=> [src-match-controller] update to use Mac::Address

src/core/thread/mle_router.cpp
This commit ensures to not re-start the `mStateUpdateTimer` from its
callback, when router role is disabled. This addresses the issue where
a mode change (disabling router role) could cause the timer to
continue to fire indefinitely, further causing device to attempt to
reattach from each timer callback.
Thanks to Conor O'Neill (@conormoneill) for discovering and debugging
this issue.
----
This should help address Issue https://github.com/openthread/openthread/issues/3372
=> [mle-router] stop mStateUpdateTimer on mode change

src/core/coap/coap.cpp, src/core/coap/coap.hpp, src/core/coap/coap_secure.cpp, src/core/coap/coap_secure.hpp, src/core/common/instance.cpp, src/core/common/instance.hpp, src/core/common/tasklet.hpp, src/core/common/timer.hpp, src/core/meshcop/meshcop.hpp
Goal of this PR is to simplify the COAP modules. 
It contains four related commits: 
>**[timer] adding ContextTimerMilli class**
>  
>This commit adds a new class `ContextTimerMilli` which is a
>millisecond timer also tracking an arbitrary context information
>provided by user in the object constructor.
>**[tasklet] adding ContextTasklet class**
>    
>This commit adds a new class `ContextTasklet` which is a `Taskelt`
>that is also tracking an arbitrary context information provided
>by user in the object constructor.
>**[coap] update Coap/CoapSecure to use Context tracking Timer/Tasklet**
>    
>This commit simplifies `ResponseQueue`, `CoapBase`, `CoapSecure` to
>use `ContextTimerMilli`/`ContextTaskelt`. This change removes the need
>for sub-classes to provide the timer and tasklet …
=> Simplify Coap (using context-tracking Timer and Tasklet)

src/cli/cli_uart.cpp, src/posix/Makefile-posix, src/posix/main.c, src/posix/platform/uart.c, tests/scripts/thread-cert/node_api.py, tests/scripts/thread-cert/node_cli.py
OpenThread UART configures stdin and stdout if it's tty device. However this may cause issues when use OpenThread working as a component together with other components which also uses stdin and stdout. For example, other components may print newline with single `\n`.
This PR leaves stdin and stdout as is and provides a configure option so that UART CLI does not echo inputs.
=> [posix-app] simplify UART on POSIX app

src/posix/platform/hdlc_interface.cpp
This commit changes the `HdlcInterface::HandleHdlcFrame()` callback
which handles a received and decoded HDLC frame such that it
discards a bad/incorrect frame from the multi frame buffer (i.e,
discard the frame on any error).
=> [posix-app] discard received HDLC frame on error

tests/scripts/thread-cert/Cert_5_1_06_RemoveRouterId.py, tests/scripts/thread-cert/command.py
1. verify messages' format;
2. remove pass criteria not required by R67 [5.1.6];
=> [tests] enhance Cert_5_1_06_RemoveRouterId

src/ncp/hdlc.cpp, tests/unit/test_hdlc.cpp
This commit changes the `Hdlc::Decoder` implementation to report
non-zero length received frames shorter than FCS size as an error
`OT_ERROR_PARSE` (instead of ignoring such frames during decoding).
Since the recent changes in `Hdlc::Decoder` buffer model delegates
the management of the frame buffer to the user of `Decoder`,
clearing frame buffer after an error should be be performed by the
`Decoder` user from the `FrameHandler` callback. The change in this
commit addresses an issue where a small (single-byte) frame would
not have been cleared from the decoder buffer and included in the
next frame. This commit also updates the `test_hdlc` unit test to
cover small frame error.
=> [hdlc] report frames smaller than FCS size as error frame

src/core/api/ip6_api.cpp, src/core/api/udp_api.cpp
This PR changes the API of allocating messages, so that a allocated message will have properly reserved memory for headers. This can help reduce memory copy in `Message::Prepend()` for adding UDP and IP headers.
=> [message] allocate message with corresponding component

src/ncp/ncp_base.hpp
This commit moves the definition of legacy related member variables
in `NceBase` into a `#if OPENTHREAD_MTD || OPENTHREAD_FTD` block. 
This addresses Coverity warning for un-initialized member variables from
constructor.
=> [ncp-base] limit legacy related member variable definitions to FTD/MTD builds

src/core/net/udp6.cpp
I'm not sure if we are allowing a UDP packet to be handled by multiple handlers.
Currently otUdpSocket::mHandler is of the following prototype:
```cpp
typedef void (*otUdpReceive)(void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo);
```
which means the handler can modify the message. This PR makes it clear that a packet will have at most one handler.
I came up with this concern because a message's offset is modified by UDP handlers, if we allow a second handler, this modified offset may result in parse errors.
=> [udp] call at most one handler

src/core/net/udp6.cpp
This commit initializes `mUdpForwarder` and `mUdpForwarderContext`
from `Udp::Udp` class constructor. Credit to coverity
=> [udp6] init member variable from constructor

src/core/net/socket.hpp
This change helps address a coverity warning (about memory overrun).
=> [socket] use "this" pointer in memset while initialization SockAddr

src/core/meshcop/border_agent.cpp
This commit verifies that the read length of `UdpEncapsulationTlv`
from a message is valid before processing it. Credit to Coverity.
=> [border-agent] check read UdpEncapsulationTlv length

src/core/meshcop/dtls.cpp, src/core/meshcop/dtls.hpp
`Dtls::Start` might fails for various reasons, data allocated when trying
initializing mbedtls are not freed. This PR addresses this issue.
This PR also moves initialization of pk and x509 certificate which is freed in `Dtls::Close()` from constructor to `Dtls::Start()`.
=> [mbedtls] free mbedtls on initialization failure

src/core/thread/mle.cpp
This change avoids the use of (potentially) undefined "1U << 32"
when calculating the backoff delay for attach re-attempt in MLE.
Credit for this bug goes to Coverity.
=> [mle] avoid "1U << 32" when calculating attach start delay backoff

src/core/mac/channel_mask.hpp, src/core/mac/sub_mac.cpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base_mtd.cpp
This commit replaces `1U` constants with `1UL` in bit shift
statements like `1U << shift` when dealing with a variable shift
value that can be larger than 15. This helps make it explicit to the
compiler that the constant should be considered as a `uint32_t`.
-----
I think practically all compilers will correctly use `uint32_t` bitshift in all usages in OT code (i.e, determine the size from the statement context) but it's better/safer to be explicit about it. 
`1U` constant can be treated as `unsigned int` and C++ standard [requires minimum of 16 bits](https://en.cppreference.com/w/cpp/language/types) for `unsigned int` type
=> [core] use `1UL` instead of `1U` when working with `uint32_t`

src/ncp/ncp_base.cpp
This change adds `IgnoreReturnValue` when the returned error can be
safely ignored. This should help address a Coverity warning.
=> [ncp-base] add IgnoreReturnValue when error should be ignored

src/core/mac/channel_mask.hpp, src/core/mac/mac.cpp
The range of `mSupportedChannelMask` is less than or equal to the range between `OT_RADIO_CHANNEL_MIN` and `OT_RADIO_CHANNEL_MAX`. There is no need to do double checks.
=> [mac] remove redundant checks

src/core/mac/mac.cpp
The `SetRxOnWhenIdle()` is changed such that if it needs to stop
operation `WaitingForData`, the next operation gets started from
the `mOperationTask` tasklet. This change makes the behavior of
the `SetRxOnWhenIdle()`  consistent with other MAC APIs (i.e.,
new operations are started only from tasklet or from a radio/timer
callback and not from any MAC APIs). This commit also updates the
`HandleTimer()` to check for operation being `kOperationIdle` when
timer is used for delaying sleep.
=> [mac] post operation task on rx-on-idle mode change

src/core/mac/mac.cpp
This commit changes `SetRxOnWhenIdle()` to stop the timer (data poll
timeout) if there is a pending `kOperationWaitingForData` when rx-on-
when-idle is being enabled. This addresses an issue where the timer
could remain active if the `SetRxOnwhenIdle(true)` is called before
the operation `kOperationWaitingForData` actually starts. Note that
the data poll timeout timer gets started while current operation is
`kOperationTransmitData` (from `HandleTransmitDone()` on a successful
data request frame transmission with a received ack indicating a
pending frame).
=> [mac] stop timer on pending WaitingForData operation on rx-on-idle change

src/core/mac/mac.cpp
---
This commit contains no logic change. It removes the `bool framePending` variable (which is used only once in subsequent `if`) and combines the two `if`s into a single one.
=> [mac] simplify the check for frame pending in data request ack

src/core/meshcop/dtls.cpp
I've ran into an issue where function mbedtls_ssl_write returns MBEDTLS_ERR_SSL_WANT_READ in CoapSecure's HandleTransmit method. Mbed's documentation has the following to say regarding [mbedtls_ssl_write](https://tls.mbed.org/api/ssl_8h.html#a5bbda87d484de82df730758b475f32e5):
> Returns
...
MBEDTLS_ERR_SSL_WANT_READ or MBEDTLS_ERR_SSL_WANT_WRITE if the handshake is incomplete and waiting for data to be available for reading from or writing to the underlying transport - in this case you must call this function again when the underlying transport is ready for the operation.
...
The way that I was able to get this error was by re-starting my DTLS server (tinydtls) with an active DTLS session. Once re-started, tinydtls ignores incoming application data and does not send any alerts (not sure …
=> [dtls] handle MBEDTLS_ERR_SSL_WANT_READ during send

examples/platforms/nrf52840/Makefile.am
This PR fixes the issue with multiple jlink RTT libs being linked by the SDK examples.
Signed-off-by: Szkotak, Piotr <Piotr.Szkotak@nordicsemi.no>
=> [nrf52840] do not include libjlinkrtt in the SDK version of OT libs

src/core/thread/mesh_forwarder_ftd.cpp
nit: This PR only removes invalid information about support of Commissioner ALOC. This support has been implemented in #2926
=> [docs] fix invalid TODO comment

src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_local.cpp, tests/unit/test_network_data.cpp
This commit changes `NetworkData` to use an enumeration `Type` to
specify whether a `NetworkData` instance represents local network
data or leader network data.
=> [network-data] use enumeration Type for local vs leader

Android.mk
This PR suppresses the warning on building Android.
=> [android] disable warning no virtual destructor

src/core/common/code_utils.hpp
On macOS and my docker environment, otALIGN() does not behave as
expected, because `~(aAlignment - 1)` is not of the pointer size.
This PR force converts it to pointer size.
This bug is introduced in #3419
=> [code-utils] fix wrong pointer size in otALIGN

src/core/api/thread_api.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit simplifies the `Mle::Start()` by combining its parameters.
With the new definition `Start()` would always try to reattach using
any saved active/pending dataset unless it is asked to attach on an
announced network (i.e., `aAnnounceAttach` is `true`).
----
In current code `Start()`  has two `bool` parameters: `Start(bool aEnableReattach, bool aAnnounceAttach)`.  But in our usage of this API the two parameters seems to be related (and always opposite of each other). This API is used from two places in code. 
- From `otThreadSetEnabled` used as `Start(true, false)`
- From `ProcessAnnounce()` used as `Start(false, true`).
=> [mle] simplify Start()

src/core/utils/slaac_address.cpp
This PR changes the SLAAC policy so that if there is an existing address
with of a prefix, no new address will be created for this SLAAC enabled
prefix.
=> [slaac] no second address for a single prefix

Android.mk, etc/visual-studio/libopenthread-cli-windows.vcxproj, etc/visual-studio/libopenthread-cli-windows.vcxproj.filters, etc/visual-studio/libopenthread-cli.vcxproj, etc/visual-studio/libopenthread-cli.vcxproj.filters, src/cli/Makefile.am, src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_coap.cpp, src/cli/cli_coap_secure.cpp, src/cli/cli_console.cpp, src/cli/cli_console.hpp, src/cli/cli_dataset.cpp, src/cli/cli_dataset.hpp, src/cli/cli_instance.cpp, src/cli/cli_server.cpp, src/cli/cli_server.hpp, src/cli/cli_uart.cpp, src/cli/cli_uart.hpp, src/cli/cli_udp.cpp
This problem was spotted in Zephyr CLI integration which uses `cli_console` backend.
Current implementation of GetOwner function for single-instance CLI
assumed that `cli_uart` backend is used. This caused application
crash when different backend was used and `cli_uart` was not
initialized (and in result sUartServer static pointer was not set).
This commit fixes the issue by moving static CLI Server pointer and
the mInterpreter field to the to the base Server class and providing
getter method to obtain the Interpreter instance. With this approach,
any backend derived from the Server class will be able to initialize
the static pointer and will provide a valid reference to the
Interpreter class instance.
=> [cli] fix GetOwner function for console CLI backend

src/core/meshcop/border_agent.cpp, src/core/meshcop/border_agent.hpp
`MeshCoP::Dtls` session will restart listening by itself. It's not
necessary for border agent to restart `MeshCoP::Dtls`.
=> [border-agent] reuse dtls restart

src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp
This commit changes the `const` methods in `Mac::Frame` class
returning a pointer type to return a pointer to `const`. It also
changes the implementation of non-`const` `GetPayload()` and
`GetFooter()` methods to re-use the corresponding `const` methods.
=> [mac-frame] change const methods to return pointers to const

src/posix/platform/alarm.c, src/posix/platform/hdlc_interface.cpp, src/posix/platform/logging.c, src/posix/platform/misc.c, src/posix/platform/netif.cpp, src/posix/platform/radio_spinel.cpp, src/posix/platform/random.c, src/posix/platform/settings.cpp, src/posix/platform/sim.c, src/posix/platform/spi-stubs.c, src/posix/platform/system.c, src/posix/platform/uart.c, src/posix/platform/udp.cpp, tests/scripts/thread-cert/test_diag.py
This PR fixes a bug that `alarm.c` misses definition of
OPENTHREAD_ENABLE_DIAG for not including `openthread-core-config.h`.
This PR adds the `openthread-core-config.h` to every platform sources.
Besides, this PR enhances the test_diag.py to make sure diag can send
packets out.
=> [posix] fix diagnostics for missing diag alarm

include/openthread/link.h, src/core/mac/mac.cpp, src/core/mac/mac.hpp
This commit changes the `SendOutOfBandFrameRequest()` implementation
to check `mOperation` and `mPending<>` state variables to determine
if MAC layer is still busy with a previous OOB tx request (instead of
using the `mOobFrame` pointer variable). This change makes the OOB tx
implementation behave similarly to other APIs (e.g., `ActiveScan()`
or `SendFrameRequest()`). This commit also enhances the documentation
for the OOB API in header files.
=> [mac] update "out of band tx" to check current operation state

include/openthread/cli.h, src/cli/cli.cpp, src/cli/cli_uart.cpp
These APIs are not specified to UART. This PR moves these functions to a proper place and renames these APIs to proper names.
=> [cli] refine CLI APIs

src/core/meshcop/commissioner.cpp
Forgot to set message's offset when commissioner send JOIN_FIN.rsp message.
It results in unexpected prefix of outputted cert log.
=> [meshcop] set message offset when sending JOIN_FIN.rsp

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_WpanCtl.py
This PR recovers the behavior for FTD(small routerselectionjitter setting after reset) changed when adding MTD cert support in #3339
=> [thci] update routerselectionjitter before start thread

src/core/coap/coap.cpp, src/core/coap/coap.hpp, src/core/coap/coap_secure.cpp, src/core/coap/coap_secure.hpp
This PR makes CoapBase::Send() private so that only safe methods
are exposed, such as SendMessage(), SendEmptyMessage(), SendAck().
=> [coap] make CoapBase::Send() private

include/openthread/link.h, include/openthread/platform/radio.h, src/cli/cli.cpp, src/cli/cli.hpp, src/core/mac/mac_frame.hpp, src/core/mac/sub_mac.cpp, src/ncp/ncp_base.hpp, src/ncp/ncp_base_mtd.cpp, src/ncp/ncp_base_radio.cpp
mDidTx indicates whether a frame is received or transmitted, which is
only useful for capturing packets. This PR removes this field, and make
this flag a temporary argument to the pcap callback.
=> [mac] remove mDidTx from otRadioFrame

tests/unit/Makefile.am, tests/unit/test_string.cpp
The `test_string` source is also made "pretty".
=> [test] fix PRETTY_FILES definition in unit test makefile

include/openthread/dataset.h, src/core/meshcop/border_agent.hpp, src/core/meshcop/meshcop.hpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/net/ip6_filter.cpp, src/core/net/ip6_filter.hpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp
This PR enables a node serve as the border agent of native commissioner
by adding the border agent UDP port to unsecure port when the security
policy allows.
To fully test verify this PR, we need a native commissioner, which I
will submit a separate PR to enable that.
=> [meshcop] border agent of native commissioner

src/core/thread/mle.cpp
The call to `SetStateDetached()` will stop the attach timer.
=> [mle] remove redundant mAttachTimer stop

src/core/thread/mle.cpp
This commit changes `SetStateChild()` to stop `mAttachTimer`. This
ensures that as the `mAttachState` is set to idle, the attach timer is
also stopped (note that the attach timer callback asserts on idle
attach state). This addresses a rare issue where an inopportune device
mode change request on an already attached device while it is
performing periodic parent search (or possibly delaying processing of
a received announce) could cause an assert; `SetDeviceMode()` would
call `SetStateChild()` setting the attach state to idle while attach
timer would continue to run.
=> [mle] stop attach timer from SetStateChild()

src/core/thread/mle.cpp, src/core/thread/mle.hpp
The attach state `kAttachStateSynchronize` was intended for sending
"Child Update Requests" after a reset (if device was previously
attached) using the `mAttachTimer` for retransmissions. However,
"Child Update" transmissions use `mMessageTransmissionTimer`
instead.
=> [mle] remove unused attach state kAttachStateSynchronize

.travis.yml, examples/common-switches.mk, examples/platforms/posix/Makefile.am, examples/platforms/posix/sim/alarm-sim.c, examples/platforms/posix/sim/radio-sim.c, include/openthread/platform/time.h, tests/scripts/thread-cert/config.py, tests/scripts/thread-cert/mac802154.py, tests/scripts/thread-cert/mle.py, tests/scripts/thread-cert/network_layer.py, tests/unit/test_platform.cpp
This PR adds the missing test with ie present by enabling `TIME_SYNC`
feature, so that IE code are covered.
=> [ci] test with time sync and header ie

tests/toranj/wpan.py
This PR changes toranj to use wpantund in $PATH.
This also allows using OpenThread binaries in different build path.
=> [toranj] allow specifying wpantund path

src/core/thread/topology.hpp
Found that there is no overflow check for the `SourceMatchController::IncrementMessageCount()` method.
=> [topology] add static assertion to exclude counter overflow

examples/platforms/efr32/random.c
Random numbers in EFR32 example where artificially large because a variable wasn't being cleared between iterations of a for-loop.
=> [efr32] random number generation fix

examples/platforms/utils/settings_flash.c
This commit uses `#if (SETTINGS_CONFIG_PAGE_NUM > 1)` instead of
run-time check in `utils/settings_flash.c`. This helps simplify the
code and also address Coverity warnings for unreachable code.
=> [settings-flash] use #if to avoid unreachable code errors

src/core/common/settings.cpp
This commit adds new check in `settings.cpp` for saving of
`NetworkInfo` and `ParentInfo` in non-volatile memory to verify that
the new value is different from previously saved content. This reduces
number of writes after a device reboot.
=> [settings] skip non-volatile save with same NetworkInfo/ParentInfo

src/core/thread/mle.cpp
This commit changes the behavior of `Mle` to skip the saving of
network info (to non-volatile memory) on role change to detached. Note
that `Store()` does only update the MAC/MLE counters if device is not
attached. The MAC/MLE counters update is tracked already by
`KeyManager`.
=> [mle] skip saving network info on role change to detached

src/core/common/notifier.cpp, src/core/common/notifier.hpp, src/core/meshcop/joiner_router.cpp, src/core/thread/announce_sender.cpp, src/core/thread/energy_scan_server.cpp, src/core/thread/mle.cpp, src/core/thread/time_sync_service.cpp, src/core/utils/channel_manager.cpp, src/core/utils/child_supervision.cpp, src/core/utils/jam_detector.cpp
This commit helps simplify the implementation and use of `Notifier`
by having the `Callback` constructor registering the callback with
the `Notifier`.
=> [notifier] auto-register callback from its constructor

.travis/script.sh
- enable gcc 7 and 8 build checks
- upgrade to asf-standalone-archive-3.45.0.85
=> [travis] enhance samr21 build checks

src/ncp/ncp_base_dispatcher.cpp, src/ncp/ncp_base_mtd.cpp, src/ncp/spinel.c, src/ncp/spinel.h
A new spinel property `SPINEL_PROP_CNTR_MLE_COUNTERS` is defined,
which can be used to get Thread MLE counters (`otMleCounters`).
This is related to wpantund https://github.com/openthread/wpantund/pull/380
=> [ncp] add support for getting MLE counters

src/core/api/link_api.cpp
This commit updates `otLinkGetChannel()` and `otLinkSetChannel()`
to handle the situation where raw-link mode is enabled.
=> [link-raw] handle get/set channel when LinkRaw is enabled

examples/Makefile-nrf52840, examples/platforms/nrf52840/spi-slave.c, examples/platforms/nrf52840/system.c, examples/platforms/nrf52840/uart.c
This commit uses SPIS_TRANSPORT_DISABLE definition to disable compilation of spi-slave.c routines, if NCP_SPI flag is not set. This is done to avoid linker errors with SPI interrupt function if project uses SPI for other purposes.
=> [nrf52840] do not compile spi-slave.c if NCP_SPI is not used

src/core/api/link_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/thread/energy_scan_server.cpp, src/core/thread/energy_scan_server.hpp, src/core/thread/panid_query_server.cpp, src/core/thread/panid_query_server.hpp, src/core/utils/channel_monitor.cpp, src/core/utils/channel_monitor.hpp
This commit changes the scan callback handlers to use `ot::Instance`
as a parameter replacing a given `void *` context.
=> [mac] use ot::Instance reference in scan callback handlers

.travis/script.sh
This PR increases CI test coverage of nRF52 platforms by building OpenThread with all available transport interfaces: UART, USB, SPI (for NCP), bare stack.
While this PR increases the time of single jobs, the overall travis test time seems not to be affected.
=> [nrf528xx] test all transport variants in CI

src/posix/platform/system.c
This allows another options parser before initializing OpenThread.
=> [posix-app] explictly set optind

.travis.yml, .travis/check-posix-app-pty, .travis/script.sh, src/posix/platform/misc.c, src/posix/platform/platform-posix.h, src/posix/platform/uart.c
In daemon mode, UART write should be processed even when no client
is connected. This PR writes UART to STDERR in such situation.
* add test for daemon mode
* remove useless code for UART restore
* fix a typo of assert
* set FD_CLOEXEC flag to better support reset.
=> [posix-app] fix write in daemon mode

include/openthread/platform/toolchain.h
As comment suggests we should define UINT32_MAX here only for C++.
=> [build] don't define UINT32_MAX for C

include/openthread/ip6.h
Clarify in the documentation that callback transfers the ownership
of the `aMessage` instance.
=> [ip6] update documentation for otIp6ReceiveCallback

include/openthread/platform/ble.h
Separate PR for just the header changes for new BLE API updates from #3033.
Adds support for L2CAP Connection-oriented-Channel (CoC) transport.
Simplifies GATT services registration to simply point to a set of statically allocated structures.
Added new asynchronous OnEnabled callback to stack initialization flow.
Adds concept of uninitialized UUID structure.
=> [ble] BLE API improvements: add l2cap and gatt services registration.

configure.ac, src/core/common/instance.hpp, src/core/crypto/mbedtls.cpp, src/core/meshcop/dtls.cpp, src/core/openthread-core-default-config.h
This PR guard using mbedTLS's buffer allocator API with a more accurate
macro, so that even in single instance mode, we can use other memory
allocator.
=> [mbedtls] guard allocator with accurate macro

src/core/net/ip6.cpp, src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp
Messages sent to Service Locator will not be filtered out, when thread
control traffic filtering is enabled via SetReceiveIp6FilterEnabled().
This PR is related to issue:
https://github.com/openthread/openthread/issues/3582
=> [ip6] messages sent to Service Locator will not be filtered out

.travis/script.sh, examples/common-switches.mk, examples/platforms/posix/openthread-core-posix-config.h, src/core/openthread-core-default-config.h, src/core/thread/mle.cpp, src/core/thread/thread_netif.cpp, src/core/thread/thread_netif.hpp, src/posix/platform/openthread-core-posix-config.h
This commit adds `OPENTHREAD_CONFIG_ENABLE_SLAAC` as a build
configuration option to enable/disable SLAAC support within
OpenThread.
=> [slaac] add config option to enable/disable SLAAC support

src/posix/platform/netif.cpp
This PR disables ICMP echo so that a ping will only got one response.
=> [platform-netif] disable icmp echo

src/core/net/ip6_mpl.cpp
The #3557 greatly improved the MPL performance. However, while looking at logs from our stress tests where multiple nodes ping each other using ff03::1 address I spotted that nodes very rarely receive more Echo Responses for single Echo Request that they should. In short, something is wrong with de-duplication mechanism.
I think i found three problems, however, this PR tries to address only two.
1. With hundreds of MPL messages sent over the air, I spotted that the default timeout of 5 seconds for removing the MPL entry does not work as it should. The issue was related to not checking the `mSeedSetTimer` status and starting it again before it has a chance to fire. This code is inherited from the last implementation, although it leads to different behavior now.
2. While debugging …
=> [mpl] fix inserting mechanism and timer handling

src/core/net/ip6_mpl.cpp
Fix serial number arithmetic due to value wrap.
Credit to @LuDuda for finding the issue (see #3587).
=> [mpl] fix bug in comparing sequence numbers

STYLE_GUIDE.md
For better or worse, the existing C code style follows camel case. Rather
than changing the code, simply update the style guide.
=> [style] remove snake case from style guide

examples/Makefile-nrf52811, examples/Makefile-nrf52840
Disabling diag module causes linker errors due to unresolved symbols when building NCP example with NCP_SPI flag set to 1 on some toolchains.
=> [nrf528xx] always enable diag module

src/cli/README.md, src/cli/cli.cpp, src/cli/cli.hpp
I experimented with `strtof` or `strtod` but they increase the FLASH size by ~10k, so the simplified float parser has been implemented.
This `ping` behavior aligns more with Linux `ping` command and allows for easier stress testing.
=> [cli] allow to define ping interval in milliseconds

examples/Makefile-efr32, examples/platforms/efr32/Makefile.am, examples/platforms/efr32/Makefile.platform.am, examples/platforms/efr32/README.md, examples/platforms/efr32/fem-control.c
Updated makefiles and sources for efr32 platform to use the v2.5 SDK from Silicon Labs released in January 2019.
=> [efr32] update to Silicon Labs Flex SDK v2.5

examples/Makefile-nrf52840
flash: Flashes the board using the nrfjprog tool.
make -f examples/Makefile-nrf52840 flash
gdb: Starts a tethered debug session with jlink and gdb.
Requires installation of Segger tools visible in path.
make -f examples/Makefile-nrf52840 gdb
=> [nrf52840] add nrfjprog target for flashing

src/core/thread/lowpan.cpp, src/core/thread/lowpan.hpp, src/core/thread/mesh_forwarder.cpp, tests/unit/test_lowpan.cpp
This PR fixes the following issues in 6LoWPAN header compression:
1. Protect against overflowing the IEEE 802.15.4 frame buffer.
2. Protect against malformed IPv6/Extension/UDP headers during compression.
This PR makes the following changes:
1. Introduce a `Lowpan::BufferWriter` to simplify writing out the compressed IPv6 header.
2. Leave message buffer and buffer writer objects unmodified upon a compression error.
3. Indicate an error when processing a malformed IPv6/Extension/UDP header.
4. Progressively fallback to lower compression levels when an error is returned.
=> [lowpan] increase robustness of 6lowpan header compression

src/core/crypto/mbedtls.cpp
The `<mbedtls/debug.h>` is included in `mbedtls.cpp` file which is
needed for `mbedtls_debug_set_threshold()`.
=> [mbedtls] include debug.h

include/openthread/sntp.h
The callback gets called with UNIX time, rather than NTP timestamp. See [sntp_client.cpp](https://github.com/openthread/openthread/blob/795a7e91972250539b7c2d0e0b74e95eca7798cf/src/core/net/sntp_client.cpp#L368).
=> [doc] fix incorrect SNTP comment

include/openthread/ip6.h
It seems that #3484 removed the implementation, but did not clear the header.
This PR fixes it.
=> [slaac] remove otIp6SlaacUpdate leftover from the ip6.h header

examples/Makefile-cc2538, examples/platforms/cc2538/README.md, examples/platforms/cc2538/cc2538-reg.h, examples/platforms/cc2538/openthread-core-cc2538-config.h, examples/platforms/cc2538/platform-cc2538.h, examples/platforms/cc2538/radio.c
This adds support for the CC2538-CC2592 EM board from TI which is basically identical to the standard CC2538 board, but has an additional CC2592 front-end to boost the transmit power and receive sensitivity.
=> [cc2538] add support for CC2538-CC2592-EM

src/posix/platform/uart.c
This PR address an issue in daemon mode that the `otPlatUartSendDone()` is not properly called when no client is connected.
=> [posix-app] fix daemon uart send done

examples/platforms/efr32/system.c
=> [efr32] fix cannot compile with log output OPENTHREAD_CONFIG_LOG_OUTPUT_APP

src/core/common/message.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp
#3015 introduced the ability to evict messages queued in MeshForwarder.
Processing a message may trigger an Address Solicit message to be sent.
Because Thread control messages have higher priority, it is possible for the
Address Solicit message to evict the data message that caused the generation
of the Address Solicit message.
This commit present a message that's being processed from being evicted.
=> [mesh-forwarder] do not allow eviction of message being processed

include/openthread/coap_secure.h, src/cli/cli_coap_secure.cpp, src/core/api/coap_secure_api.cpp, src/core/coap/coap_secure.cpp, src/core/coap/coap_secure.hpp, src/core/meshcop/border_agent.cpp
When DTLS is disconnected, the socket should also be disconnected from
the previous peer.
This fixes openthread/borderrouter#254.
=> [coaps] fix disconnected

examples/platforms/nrf52811/README.md, examples/platforms/nrf52840/README.md
This PR enhances nRF52811 and nRF52840 documentation:
- add detailed documentation about Segger J-Link tools (@turon can you review it?) - mainly how to run it on Linux
- update links to point to the new website
- address tech writer review comments
=> [nrf528xx] update platforms README.md

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_WpanCtl.py
We met some errors running Test Harness for 1.2 features when calling `getDUA`. The `getDUA` function in our THCI is implemented using `getGUA`. And the critical code that cause the problem in `OpenThread.py` is as below:
```
def __getIp6Address(self, addressType):
ip6AddrPrefix = ip6Addr.split(':')[0]
if ip6AddrPrefix == 'fe80':
if ip6Addr.split(':')[4] != '0':
linkLocal64Addr = ip6Addr
elif ip6AddrPrefix == 'fd00':
if ip6Addr.split(':')[4] == '0':
rlocAddr = ip6Addr
else:
meshEIDAddr = ip6Addr
def getGlobal(self):
#......
return self.__getIp6Address('global')
def getGUA(self, filterByPrefix=None):
"""get expected global unicast IPv6 address of Thread device
Args:
filterByPrefix: a given expected global IPv6 prefix to be matched
Returns:
a global IPv6 address
"""
print '%s call getGUA' % …
```
=> [thci] match meshlocalprefix accurately to classify the addresses correctly

src/core/thread/lowpan.cpp, src/core/thread/mle_constants.hpp, src/core/thread/mle_router.cpp, src/core/thread/network_data_leader.cpp, tests/scripts/thread-cert/Cert_5_2_05_AddressQuery.py, tests/scripts/thread-cert/Cert_5_3_07_DuplicateAddress.py, tests/scripts/thread-cert/Cert_5_6_01_NetworkDataRegisterBeforeAttachLeader.py, tests/scripts/thread-cert/Cert_5_6_02_NetworkDataRegisterBeforeAttachRouter.py, tests/scripts/thread-cert/Cert_5_6_03_NetworkDataRegisterAfterAttachLeader.py, tests/scripts/thread-cert/Cert_5_6_04_NetworkDataRegisterAfterAttachRouter.py, tests/scripts/thread-cert/Cert_5_6_05_NetworkDataRegisterAfterAttachRouter.py, tests/scripts/thread-cert/Cert_5_6_06_NetworkDataExpiration.py, tests/scripts/thread-cert/Cert_5_6_07_NetworkDataRequestREED.py, tests/scripts/thread-cert/Cert_5_6_08_ContextManagement.py, tests/scripts/thread-cert/Cert_5_6_09_NetworkDataForwarding.py, tests/scripts/thread-cert/Cert_6_1_02_REEDAttach_MED.py, tests/scripts/thread-cert/Cert_6_3_02_NetworkDataUpdate.py, tests/scripts/thread-cert/Cert_7_1_01_BorderRouterAsLeader.py, tests/scripts/thread-cert/Cert_7_1_02_BorderRouterAsRouter.py, tests/scripts/thread-cert/Cert_7_1_03_BorderRouterAsLeader.py, tests/scripts/thread-cert/Cert_7_1_04_BorderRouterAsRouter.py, tests/scripts/thread-cert/Cert_7_1_05_BorderRouterAsRouter.py, tests/scripts/thread-cert/command.py
Thread 1.1 Spec 4.7.1 says
> The ML-EID address is always registered and does not need to be acknowledged
=> [mle] not echo back ML-EID registered by MTD

src/core/thread/router_table.cpp, src/core/thread/router_table.hpp
This commit adds a simple internal helper class `RouterIdSet` in
`RouterTable` to store the allocated router IDs bitset. This commit
also renames the `for` loop variable names (`routerId` when iterating
over all router IDs and `index` used for `mRouters` array index)
=> [router-table] simplify router table code

src/core/net/dhcp6_server.cpp, src/core/net/dhcp6_server.hpp
* introduce a new class for managing Prefix Agent state
* combine prefix and ALOC into the same class
=> [dhcp6] clean up Prefix Agent state management in DHCPv6 server

include/openthread/coap_secure.h, src/cli/cli_coap_secure.cpp, src/cli/cli_coap_secure.hpp, src/core/api/coap_secure_api.cpp, src/core/coap/coap_secure.cpp, src/core/coap/coap_secure.hpp, src/core/common/instance.hpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/border_agent.hpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/dtls.cpp, src/core/meshcop/dtls.hpp, src/core/thread/thread_netif.cpp, src/core/thread/thread_netif.hpp
`CoapSecure` is always used by joiner, border agent or commissioner.
DTLS should not be shared with the application CoapSecure.
This PR includes the following changes:
* allow multiple DTLS by using `TimerMilliContext`
* move CoAP::mSocket into Dtls
* move ThreadNetif::mDtls into CoapSecure
* remove unnecessary getters of `Dtls` and `CoapSecure`
=> [dtls] refine CoAP secure and DTLS

examples/platforms/nrf52840/usb-cdc-uart.c
bInterfaceProtocol descriptor previously indicated that AT V.250 commands were supported by the device. This could cause issues with applications managing modems.
=> [nrf52840] do not specify interface protocol in USB CDC

include/openthread/ip6.h, src/core/api/ip6_api.cpp, src/core/common/instance.hpp, src/core/common/settings.hpp, src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, src/core/thread/mle.cpp, src/core/thread/thread_netif.cpp, src/core/thread/thread_netif.hpp, src/core/utils/slaac_address.cpp, src/core/utils/slaac_address.hpp
This commit enhances the SLAAC support in OpenThread core. It contains
the following changes and features:
The `Utils::Slaac` class is updated to include all the related code
for managing SLAAC addresses (e.g., `Slaac` class maintains the
address buffer and directly subscribes to `Notifier` to listen for
Network Data changes to update SLAAC addresses).
The SLAAC address module is changed to support and use semantically
opaque IID generation algorithm (RFC 7217) instead of random IID
generation. This ensures that SLAAC addresses are random but stable
(i.e., the same SLAAC address is added on a device for the same
prefix) and aligns the implementation with Thread specification
requirement.
The semantically opaque IID generation logic is updated to follow RFC
7217 with SHA-256 as the …
=> [slaac] enhance and simplify SLAAC support

include/openthread/ip6.h, src/core/api/ip6_api.cpp, src/core/utils/slaac_address.hpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base_dispatcher.cpp, src/ncp/ncp_base_mtd.cpp, src/ncp/spinel.c, src/ncp/spinel.h
**[ncp] add SLAAC related spinel capability and property**
This commit adds `SPINEL_CAP_SLAAC` which indicates to host whether
SLAAC feature is supported. It also adds `SPINEL_PROP_SLAAC_ENABLED`
spinel property to let host enable/disable SLAAC module at run-time.
------
**[slaac] add IsEnabled() method and public API otIp6IsSlaacEnabled**
=> [ncp] add SLAAC related spinel capability and property

.travis/script.sh, configure.ac, src/posix/Makefile-posix, src/posix/Makefile.am, src/posix/console_cli.c, src/posix/console_cli.h, src/posix/main.c, src/posix/platform/openthread-system.h, src/posix/platform/sim.c, src/posix/platform/uart.c
This PR uses the console API to support CLI on POSIX platform. The source is written in C with code style in https://github.com/openthread/openthread/blob/master/STYLE_GUIDE.md#naming. I'm not sure if the code style is applied correctly.
This PR also adds readline support under this mode, which is helpful to modify long commands. To avoid license issue, this PR also supports the BSD libedit as an alternative of readline.
=> [posix-app] add readline for CLI

src/core/mac/link_raw.cpp, src/core/mac/link_raw.hpp, src/core/mac/sub_mac_callbacks.cpp
This commit adds logs to indicate frame tx attempt failures on
`LinkRaw` class for RCP model.
=> [link-raw] log frame tx attempt failures

src/posix/Makefile-posix
`-g` should be present with `DEBUG=1`.
=> [posix-app] fix debug flag

tests/toranj/openthread-core-toranj-config.h, tests/toranj/start.sh, tests/toranj/test-026-slaac-address-wpantund.py, tests/toranj/test-030-slaac-address-ncp.py, tests/toranj/wpan.py
This commit updates and renames the existing `test-026-slaac-address`
to indicate that it covers the behavior of `wpantund` related to
SLAAC address management (in `test-026` we disable NCP SLAAC module).
It adds a new test `test-030-slaac-address-ncp` to cover behavior of
OpenThread/NCP SLAAC module:
- Verify that adding prefix (with SLAAC flag) causes a corresponding
SLAAC IPv6 address to be added.
- Verify that removing the prefix would remove the SLAAC address.
- Verify behavior when same prefix is added and removed on multiple nodes
(with or without SLAAC flag).
- Check behavior when an IPv6 address with the same prefix already exists.
- Check behavior when the address with same prefix is removed (SLAAC module
should add a SLAAC address upon removal of the address).
- Verify that …
=> [toranj] add test to cover OT/NCP SLAAC module behavior

.travis/before_install.sh
This PR removes unused sources from update list to prevent travis failing for unable to fetch updates from these sources.
=> [travis] remove unused sources

tests/scripts/thread-cert/README.md, tests/scripts/thread-cert/debug.py
This PR adds a inspector to inspect nodes status. This could be a start. Enhancements are welcome!
Usage:
1. import debug
```python
import debug
```
2. start inspector by adding this line to where you want to inspect.
```python
debug.Inspector(self).inspect()
```
=> [tests] add an inspector for travis certification tests

include/openthread/coap_secure.h, src/core/coap/coap_secure.hpp, src/core/meshcop/border_agent.hpp, src/core/meshcop/dtls.hpp, src/core/net/sntp_client.hpp, src/core/openthread-core-default-config.h, src/ncp/ncp_base_radio.cpp, src/ncp/ncp_buffer.hpp
One of these flagged in the recent openthread.io reference update, so I fixed that and all other instances that aren't in third party or the Spinel docs.
=> [docs] fix instances of "the the" in comments

src/core/api/dataset_api.cpp, src/core/meshcop/dataset_local.cpp, src/core/meshcop/dataset_local.hpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager.hpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/joiner_router.cpp, src/core/thread/mle.cpp, src/core/utils/channel_manager.cpp
This commit renames methods in `DatasetLocal`, `DatasetManager`,
'ActiveDataset' and `PendingDataset` to use `Read()` and `Save()`
in place of `Get()` and `Set()` respectively. This aligns the
names with `Setting` class indicating that these method do
read/save Dataset info in non-volatile memory.
=> [dataset] use Read/Save method names instead of Get/Set

third_party/NordicSemiconductor/libraries/app_error/app_error_weak.c
This PR fixes #3724. nRF Log module is used only in the nRF SDK.
=> [nrf528xx] remove unnecessary dependencies from app_error_weak

include/openthread/link.h, src/core/common/code_utils.hpp, src/core/mac/mac_filter.cpp, src/core/mac/mac_filter.hpp
This commit improves the `Mac::Filter` implementation. It mainly
removes the internally used `mFiltered` variable from the public
`otMacFilterEntry` definition and moves it inside `Mac::Filter`
private definitions.
---
Added a second (seperate) commit in the same PR:
**[code-utils] add OT_ARRAY_END() macro**
This commit adds `OT_ARRAY_END(aArray)` macro which returns a
pointer to the end of a given array (pointing to the past-the-end
element).
=> [mac-filter] hide the mFiltered in public filter APIs

.travis/before_install.sh, src/posix/platform/alarm.c, src/posix/platform/hdlc_interface.cpp, src/posix/platform/platform-posix.h, src/posix/platform/radio_spinel.cpp, src/posix/platform/sim.c
Current posix app uses gettimeofday() to get time, which will be affected
by system time changes, and results in alarm not fired in time. This PR uses
clock_gettime() instead to avoid this issue.
=> [posix-app] fix alarm issue when time changed

src/ncp/ncp_base.hpp, src/ncp/ncp_base_radio.cpp, src/posix/platform/radio_spinel.cpp
**[ncp] decode meta-data (CSMA/retry counts) in STREAM_RAW property set**
This commit adds logic to decode and use the optional meta-data fields
in a `VALUE_SET` command (frame tx request) for `PROP_STREAM_RAW` in
raw-link or radio only (RCP) mode. The optional meta-data fields map
to definitions in `otRadioFrame` to specify number of CSMA backoffs
attempts, frame retry attempts, whether to enable CSMA-CA for this
frame or not. If any optional field is not included, default value
is used instead. This aligns the implementation with specification
of `PROP_STREAM_RAW` in `spinel.h`.
(please see [spinel.h#L2517](https://github.com/openthread/openthread/blob/master/src/ncp/spinel.h#L2517))
----
**[radio-spinel] add meta-data (CSMA/retry counts) in …
=> [ncp/radio-spinel] pass frame info (max CSMA/retry count) to RCP

src/core/meshcop/joiner.cpp, src/core/meshcop/joiner.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp
This PR contains two different (related) commits:
**[joiner] update Joiner implementations**
This commit contains the following changes to `Joiner` class
implementations:
- Notifier events are signaled on all `Joiner` state changes
and are logged (through use of `Joiner::SetState()`).
- Discover scan during join uses filtering (removes the need
to perform filtering by the `Joiner` class itself).
- `Joiner::Stop()` is changed to allow it to be called at any
stage of join process and it correctly cleans all states.
- Priority assignment to discovered networks is updated/fixed
(prioritizing networks with an exact match of Joiner ID in their
Steering Data compared to ones that allow all joiners, and
sub-prioritize based on signal strength).
- Logs are updated.
-------
**[mle] update discover …
=> Update Mle and Joiner implementations

examples/platforms/posix/openthread-core-posix-config.h, src/cli/cli_coap_secure.cpp, src/cli/cli_coap_secure.hpp
replaces PR of https://github.com/openthread/openthread/pull/3686
=> [coap] remove otCoapMessage from CoapSecure::DefaultHandler()

src/ncp/ncp_base.cpp, src/ncp/ncp_base_dispatcher.cpp, src/ncp/ncp_base_mtd.cpp, tests/toranj/test-001-get-set.py, tests/toranj/wpan.py
**[ncp-base] fix the `#if` check for posix-app**
------
**[toranj] verify "RCPVersion" is gettable on posix-app mode**
This commit updates the `test-001` to allow extra properties to
be verified when running under posix-app model. The new test
ensures "POSIXApp:RCPVersion" is gettable.
------
This PR addresses an issue where the "RCP Version" property (through spinel/wpantund) is disabled (not supported) on posix-app build. It seems to be caused due to a rename of the build option `OPENTHREAD_ENABLE_POSIX_APP` to `OPENTHREAD_PLATFORM_POSIX_APP` from https://github.com/openthread/openthread/pull/3611.
=> [ncp] fix missing "RCPVersion" property under POSIX-app

include/openthread/error.h, src/ncp/ncp_base_radio.cpp, src/ncp/spinel.c, src/posix/platform/radio_spinel.cpp
This PR parses rx timestamp of radio frame received by RCP, no matter data
frames or ACK frames.
* add OT_NUM_ERRORS as number of defined errors.
* allow empty SPINEL_DATATYPE_DATA and SPINEL_DATATYPE_DATA_WLEN when parsing spinel packets.
=> [radio-spinel] parse frame rx timestamp

include/openthread/platform/radio.h, src/core/mac/sub_mac.cpp, src/posix/platform/radio_spinel.cpp
There's missing error definition for otPlatRadioDisable(). This PR adds
an error case OT_ERROR_INVALID_STATE to make sure this is only called
when the radio is in sleep mode.
=> [radio] only allow disable in sleep state

tools/spi-hdlc-adapter/README.md, tools/spi-hdlc-adapter/spi-hdlc-adapter.c
This commit contains the following improvements  in
`spi-hdlc-adapter`:
- It changes the default syslog log level to `LOG_WARNING`.
- It enhances the `--verbose[=num]` option to allow negative values
to reduce the log level. Note that this change keeps the behavior
backward compatible (it is an add-on).
- It updates the `print_help()` and the `README.md` files to document
new behavior of `--verbose` option.
=> [spi-hdlc-adapter] allow log level to be changed

include/openthread/joiner.h, src/core/meshcop/joiner.cpp, src/core/meshcop/joiner.hpp
This commit updates the `Joiner` class implementation to remove the
requirement for `Start()` vendor related parameters (vendor name,
model, sw version, data) to be static (string). This is done without
requiring the `Joiner` class to use member variables to store/copy
the strings by preparing the "Joiner Finalize" message early on (note
that these parameters are included in this message) and keeping track
of the dynamically allocated `Coap::Message` pointer instead.
=> [joiner] remove static requirement for vendor parameters in Start()

include/openthread/ip6.h, src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/net/ip6_mpl.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/network_diagnostic.cpp
- Return OT_ERROR_PARSE when encountering mal-formatted headers.
- Return OT_ERROR_NO_ROUTE when there is no route to host.
- Document possible return values for `otIp6Send()`.
=> [ip6] clean up return values for `otIp6Send()`

examples/platforms/nrf52811/radio.c, examples/platforms/nrf52840/radio.c, examples/platforms/posix/radio.c, examples/platforms/posix/sim/radio-sim.c
This PR fixes #3656.
Additionally, a small inefficiency with the nRF5x platform using FreeRTOS and multiprotocol (Thread + BLE) has been fixed.
=> [platform] return error on incorrect otPlatRadioDisable usage

src/core/common/message.cpp, src/core/common/message.hpp, src/core/common/tlvs.hpp, src/core/meshcop/announce_begin_client.cpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/energy_scan_client.cpp, src/core/meshcop/joiner.cpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/leader.cpp, src/core/meshcop/panid_query_client.cpp, src/core/thread/address_resolver.cpp, src/core/thread/energy_scan_server.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/network_data.cpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_diagnostic.cpp, src/core/thread/panid_query_server.cpp
This commit adds a new method `AppendTlv` to `Message` class which
appends a fully formed TLV to the message. This commit also changes
the core modules to use the new method when appending a TLV.
------------
In existing code, we have 2 different ways of appending TLVs:
- Two patterns to add a fully formed TLV  (the new API covers both cases and simplifies the code)
- The TLV size is fixed, 
- e.g. `Append(&stateTlv, sizeof(stateTlv))` -> `AppendTlv(stateTlv)`
- The TLV size can vary, e.g., 
- `Append(cur, sizeof(Tlv) + cur->GetLength())` -> `AppendTlv(*cur)`
- `Append(&vendorNameTlv, vendorNameTlv.GetSize())` -> `AppentTlv(vendorNameTlv)`
- The TLV is added in pieces (this remains as is and unchanged).
=> [message] add and use AppendTlv

examples/platforms/nrf52811/radio.c, examples/platforms/nrf52840/radio.c
otPlatRadioTransmit can return OT_ERROR_INVALID_STATE or OT_ERROR_NONE so inform about failed TX later.
This fixes #3726
=> [nrf528xx] don't return OT_ERROR_FAILED from otPlatRadioTransmit

src/core/thread/mle.cpp
A device should use the Active Dataset in use by the partition that it is
attached to, not the one stored locally in non-volatile.
=> [mle] do not apply active dataset from settings after attaching

src/core/thread/mle.cpp
Mle Data Request would be always delayed except the retransmitted ones. For sleepy device, it should enter fast poll mode after the delayed Mle Data Request is dequeued to send.  Besides, after received Mle Data Response, it should stop fast poll mode.
=> [mle] enter fast poll mode when dequeue delayed MLE Data Request

src/ncp/ncp_base_mtd.cpp, src/ncp/spinel.h
This commit updates `SPINEL_PROP_MESHCOP_JOINER_COMMISSIONING`
definition to allow vendor info (name, model, sw version, data) to be
specified. All new parameters are optional and if not specified in the
spinel frame, OpenThread default values will be used instead.
This change in `SPINEL_PROP_MESHCOP_JOINER_COMMISSIONING` format keeps
it backward compatible with previous definition, ensuring any driver
using the previous format will be parsed in the same way.
=> [ncp] update MESHCOP_JOINER_COMMISSIONING to allow vendor info to be given

examples/drivers/windows/otApi/otApi.cpp, examples/drivers/windows/otLwf/iocontrol.c, examples/drivers/windows/otNodeApi/otNodeApi.cpp, include/openthread/dataset.h, include/openthread/thread_ftd.h, src/cli/cli.cpp, src/core/api/thread_ftd_api.cpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/thread/key_manager.cpp, src/core/thread/key_manager.hpp, src/ncp/ncp_base_ftd.cpp
When generating a new Active Dataset, the current PSKc value is used. Because
the PSKc is initialized to all zeros, new Active Datasets have a default
PSKc value of all zeros.
This commit checks if the PSKc has been set (i.e. not all zeros) and, if not
set, generates a random PSKc when creating a new Active Dataset.
Also, this PR contains a commit to use `otPSKc` rather than byte arrays.
=> [pskc] set random PSKc when generating a new Active Dataset

src/core/mac/mac_frame.cpp
`BeaconPayload::GetNetworkName()` does not return a NULL-terminated string.
This commit fixes `BeaconPayload::ToInfoString()` to pass a NULL-terminated
string to the string formatter.
=> [logging] fix BeaconPayload::ToInfoString() print of network name

src/ncp/ncp_base_mtd.cpp, src/ncp/spinel.h
This commit defines an enumeration in spinel for Joiner state which
is related to property `SPINEL_PROP_MESHCOP_JOINER_STATE`.
=> [ncp] add spinel_meshcop_joiner_state_t enumeration

src/core/meshcop/commissioner.cpp, src/core/meshcop/meshcop_tlvs.hpp
This commit ensures that if the passed-in string args (vendor name,
model, sw version, data or provisioning URL) in `Joiner::Start()`
are too long, they are clipped to the max size defined by the
corresponding TLVs.
=> [meshcop] clip long strings for vendor name, model, version, data

include/openthread/dataset.h, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset_local.cpp, src/core/meshcop/dataset_local.hpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager.hpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp
When a partial dataset is stored, the device will attempt to attach to a
Thread network using the limited parameters available. If the device
successfully attaches, the device will then obtain the complete Active
Dataset from its Parent. If the device is router-capable, it will not
become a Router/Leader until it has successfully retrieved a complete Active
Dataset.
Saving a partial dataset supports out-of-band commissioning scenarios.
Resolves #3766.
=> [dataset] allow setting partially complete active dataset

examples/platforms/efr32/uart.c
- No longer queue 2x 32-byte buffers for UART receive. Upon investigation, the RAIL library switches these buffers in software (within the same ISR context as `receiveDone`), so it seems to be pointless from a performance perspective in queuing multiple buffers. Instead, now work with 64-byte buffers. 
- Refactored `updateReceiveProgress` so that extra variable `mLastCount` isn't required.
- Extensive testing at higher baud rates revealed race conditions and some issues with detecting buffer full conditions.
- Added comments to clarify the logic
- Removed asserts after returning from RAIL library functions. Contrary to my previous arguments, if the behaviour of the RAIL library functions changes in the future (with regards to the errors it returns), then somebody would have to remember to …
=> [efr32] further UART driver refactoring

src/core/coap/coap.cpp, src/core/coap/coap.hpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/joiner_router.hpp, src/core/net/dns_client.hpp, src/core/net/ip6_mpl.cpp, src/core/net/ip6_mpl.hpp, src/core/net/sntp_client.cpp, src/core/net/sntp_client.hpp, src/core/thread/mle.hpp
This PR contains 3 commits. Since they fix the same area of the code I decided to create just one PR but they may be merged separately.
---
**[coap] check error code on appending metadata**
This commit potentially fixes #3783 issue.
---
**[joiner] remove potential memory leak**
This commit fixes a situation where `message` may not be freed due to the fact that error code is not checked properly.
---
**[metadata] enhance ReadFrom and RemoveFrom methods**
This commit modifies `ReadFrom` and `RemoveFrom` methods to return `void`. The code itself didn't check return error code or length anyway. Instead, the assert has been added in these functions, which seems reasonable approach since only by bad usage of API fault situation may occur.
---
I think as a separate enhancement we can unify …
=> [metadata] modify error handling strategy

src/core/meshcop/dtls.cpp
---------
Notice these during joiner testing. Changed them to `DEBG` level. 
We can consider removing them as well.  Thoughts?
```
wpantund[136810]: NCP => [INFO]-MLE-----: Receive Discovery Response (fe80:0:0:0:1084:3e0:f6e:fc0b)
wpantund[136810]: NCP => [INFO]-MESH-CP-: Joiner discover network: 128403e00f6efc0b, pan:0xb89c, port:1000, chan:26, rssi:-20, allow-any:no
wpantund[136810]: NCP => [INFO]-MESH-CP-: Joiner connecting to 128403e00f6efc0b, pan:0xb89c, chan:26
wpantund[136810]: NCP => [INFO]-MESH-CP-: Dtls::SetTimer
wpantund[136810]: NCP => [INFO]-MESH-CP-: DTLS started
wpantund[136810]: NCP => [INFO]-MESH-CP-: Dtls::SetTimer
wpantund[136810]: NCP => [INFO]-MESH-CP-: Dtls::HandleMbedtlsTransmit
wpantund[136810]: NCP => [INFO]-MESH-CP-: Dtls::SetTimer
wpantund[136810]: NCP => …
```
=> [dtls] convert some of the info level logs to debug level

examples/drivers/windows/otApi/otApi.cpp, include/openthread/thread_ftd.h, src/cli/README.md, src/cli/cli.cpp, src/cli/cli.hpp
Personally I find it useful for basic connection testing - eidcache already works for FTD children, but not MTDs.
Not entirely sure how the windows otApi works, but I copied the OT_ERROR_NOT_IMPLEMENTED pattern I saw in other places in the file. Let me know if it would be worth me looking into this in more detail.
=> [cli] add 'childip' command to cli for getting ip addresses of MTD children

src/cli/cli.cpp, src/core/api/thread_api.cpp, src/core/coap/coap.cpp, src/core/common/timer.hpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset_local.cpp, src/core/net/dhcp6_client.cpp, src/core/net/dns_client.cpp, src/core/net/ip6_mpl.cpp, src/core/net/sntp_client.cpp, src/core/thread/address_resolver.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/network_data.cpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/router_table.cpp, src/core/thread/time_sync_service.cpp, src/core/utils/jam_detector.cpp
`uint32_t` cannot represents about 50 days in milliseconds. This PR
updates the implementation where uses simple minus to get the elapsed
time to avoid the elapsed overflow issue.
=> [timer] fix elapsed overflow

configure.ac, examples/platforms/Makefile.am, examples/platforms/efr32/Makefile.am, examples/platforms/efr32/README.md, examples/platforms/efr32/alarm.c, examples/platforms/efr32/platform-efr32.h, examples/platforms/efr32/radio.c, examples/platforms/efr32/sleepy-demo/Makefile.am, examples/platforms/efr32/sleepy-demo/README.md, examples/platforms/efr32/sleepy-demo/efr32-sleepy-demo-ftd/Makefile.am, examples/platforms/efr32/sleepy-demo/efr32-sleepy-demo-ftd/main.c, examples/platforms/efr32/sleepy-demo/efr32-sleepy-demo-mtd/Makefile.am, examples/platforms/efr32/sleepy-demo/efr32-sleepy-demo-mtd/main.c, examples/platforms/efr32/system.c
Added sleep function and changes to EFR32 alarm handling to allow entering low power mode.
Added sleepy-demo applications within examples/platforms/efr32/sleepy-demo to demonstrate low power mode.
=> [efr32] add support for entering EM2 low-power mode for sleepy devices

tools/spi-hdlc-adapter/spi-hdlc-adapter.c
This PR triggers resetting NCP/RCP on exit, which ensures NCP/RCP get
back to uninitialized state so that they will not respond to 15.4
messages.
Note, host should disable soft reset by passing `--no-reset` for RCP.
Thus OpenThread POSIX app doesn't need to reset RCP when it exits.
=> [spi-hdlc-adapter] reset NCP/RCP on exit

src/posix/platform/platform-posix.h, src/posix/platform/radio_spinel.cpp, src/posix/platform/radio_spinel.hpp, src/posix/platform/system.c
This PR adds a option `--no-reset` to OpenThread POSIX app to suppress
sending soft reset command when initializing OpenThread radio on host.
This is for NCP SPI bus scenario, where spi-hdlc-adapter is involved who
will trigger hardware reset at start.
=> [posix-app] add option to skip reset RCP

src/core/thread/mle.cpp, src/core/thread/mle_constants.hpp, src/core/thread/mle_router.cpp
When testing devices in crowded radio environment and with less capable radio functionalities, the filtered parent response will cause the parent request to be sent again but filtered by parent because the parent view the request as duplicated. The devices thus becomes the network leader rather than join the existing partition.
According to the specification, there is no requirement for link quality to be 3 so the filter is removed and the best parent can still be selected in the following comparison.
=> [mle] maintain best parent candidate during router-only search

examples/platforms/posix/alarm.c, src/posix/platform/alarm.c
This PR enhances both posix-app and posix simulation to use the clock
CLOCK_MONOTONIC_RAW, which is supported on Linux and macOS. However, if
this clock is not available, it will fall back to CLOCK_MONOTONIC(for
BSD system).
On windows, it continues to use `gettimeofday()`.
=> [posix] use monotonic raw timer

tests/scripts/thread-cert/node_cli.py
This PR fixes python warning "ResourceWarning: unclosed file" when set
pexpect to None.
=> [test] fix unclosed file

src/ncp/spinel.h
`OPENTHREAD_ENABLE_POSIX_APP` was merged into
`OPENTHREAD_PLATFORM_POSIX_APP`.
=> [spinel] fix outdated comment

examples/platforms/nrf52811/README.md, examples/platforms/nrf52811/openthread-core-nrf52811-config.h, examples/platforms/nrf52811/radio.c, examples/platforms/nrf52840/README.md, examples/platforms/nrf52840/openthread-core-nrf52840-config.h, examples/platforms/nrf52840/radio.c
This PR utilizes Nordic's MA-L (formerly called OUI).
It also addresses potential warning in wpantund due to M bit being set.
https://groups.google.com/forum/#!topic/openthread-users/tFcfhqjJiDc
=> [nrf528xx] use Nordic's OUI in factory assigned IEEE EUI-64

src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, tests/unit/Makefile.am, tests/unit/test_ip6_address.cpp
This PR facilitates the creation of the IPv6 address for NAT64 usage.
=> [ip6] add support for parsing embedded IPv4 address

examples/platforms/nrf52811/README.md, examples/platforms/nrf52811/radio.c, examples/platforms/nrf52840/README.md, examples/platforms/nrf52840/radio.c
FYI.. This PR fixes IAR warning: `undefined behavior: the order of volatile accesses is undefined in this statement`
=> [nrf528xx] fix undefined behavior warning in IAR

src/core/common/message.cpp, src/core/common/message.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, tests/toranj/start.sh, tests/toranj/test-032-child-attach-with-multiple-ip-addresses.py
This commit addresses the attach failure issue by an SED child trying
to register multiple IPv6 addresses in MLE "Child ID Request" message.
If the MLE "Child ID Request" requires fragmentation at 6LoWPAN layer,
this commit changes the code to abort the transmission and drop the
message and instead signal to MLE layer to prepare a shorter "Child ID
Request" by only including the mesh-local address in the `Address
Registration TLV`. After the child attaches, the new code will ensure
to trigger a "Child Update Request" exchange for the child to register
the remaining IPv6 addresses with its parents.
---------------
This PR also includes a separate commit adding a test-case covering this scenario.
[toranj] adding test-case for a SED child attaching with multiple IP addresses
This should …
=> [mle] send shorter "Child ID Request" if full version requires fragmentation

include/openthread/udp.h, src/core/api/udp_api.cpp
This PR exposes an API to send UDP datagram, this is usefully when the
udp receiver handler needs to send messages.
=> [udp] expose an API to send UDP datagram

tests/unit/Makefile.am, tests/unit/test_platform.h
This PR contains two small commits:
- First one is the output of "make pretty" fixing order in the `tests/unit/test_platform.h`
- Second one is adding header file explicitly in `PRETTY_FILES` var in the unit test `Makefile` to ensure it's covered by `travis` pretty check build.
=> [tests] make pretty and update makefile

src/core/Makefile.am, src/ncp/ncp_buffer.cpp, src/ncp/ncp_buffer.hpp, src/ncp/spinel_encoder.hpp
This commit changes the `NcpFrameBuffer` and `SpinelEncoder` classes
to include the support for adding of `otMessage` to the buffer and the
related APIs in the FTD/MTD builds (exclude it from the RADIO (RCP)
build).
-----------
[radio/rcp] remove `Message` related source files from radio mode Makefile
=> [ncp-buffer] include APIs using otMessage only in FTD/MTD builds

tools/harness-thci/OpenThread.py
The #3830 introduced additional parse validation to `otIp6AddressFromString`.
Probably due to this PR (or less likely this #3819), the following certification test cases fail with AutoDUT:
- `Leader_7_1_1`
- `Leader_7_1_3`
- `Router_7_1_2`
- `Router_7_1_4`
- `Router_7_1_5`
The reason for this is that prefix `2001:0000:0000:0000:` (one colon at the end) is no longer valid.
This PR updates `OpenThread.py` THCI file to construct valid prefix. Note that OpenThread_wpanctl.py has the correct version of this functionality already implemented.
=> [thci] correct conversion of IPv6 prefix

Android.mk, include/openthread-config-android.h
This PR remove unnecessary features of OpenThread on Android platform.
This PR also removes features disabled in openthread-config-android.h so
that these definitions can be overrided in Android.mk without warning.
=> [android] disable some optional features

include/openthread/thread_ftd.h, src/core/api/thread_ftd_api.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp, src/core/thread/router_table.cpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base.hpp, src/ncp/ncp_base_ftd.cpp, src/ncp/ncp_base_mtd.cpp
**[mle-router] signal a child/router neighbor entry being added or removed**
This commit updates the neighbor table callback to signal when
either a child or a router neighbor entry is being added or removed.
This change replaces and enhances the previous APIs relalted to child
table callback.
------------
**[ncp] emit router entry addition/removal from neighbor table**
This commit updates `NcpBase` to emit `VALUE_INSERTED/REMOVED` spinel
message to host for `PROP_NEIGHBOR_TABLE` when a router neighbor entry
is added or removed.
=> [mle-router] signal a child/router neighbor entry being added or removed

src/core/thread/mle.cpp
Fixes a bug introduced in 5a7faa5.
A device performing MLE attach first sends an MLE Parent Request looking
for routers. If no MLE Parent Response is received from a neighboring router
where the link quality is 3 in both directions, the device shall send a
second MLE Parent Request that includes both routers and REEDs.
This commit adds the bi-directional link quality check to determine whether
a second MLE Parent Request should be sent.
Resolves #3847.
=> [mle] fix bug in MLE attach behavior

tests/scripts/thread-cert/Cert_5_1_11_REEDAttachLinkQuality.py, tests/scripts/thread-cert/Cert_6_1_05_RouterAttachLinkQuality.py, tests/scripts/thread-cert/Cert_6_1_06_REEDAttachLinkQuality_ED.py, tests/scripts/thread-cert/Cert_6_1_06_REEDAttachLinkQuality_SED.py, tests/scripts/thread-cert/Makefile.am
This PR contains two separate but related commits:
---
**[cert] add additional validation for Router_5_1_11 test**
This commit adds an additional check for step 6 from Thread Certification Test Program.
---
**[cert] add additional validation for Cert_6_1_06 and fix link quality configuration**
This commit adds non-existing detailed checks for Cert_6_1_06. Additionally, two variants for MED and SED role have been added.
Despite the lack of the proper step checks, the above tests passed on #3803 because link-quality configuration was forced both on Golden Device and on DUT. However, it is not true in real certification, where only Golden Devices support this feature. Thus the configuration of link-quality on DUT has been removed.
---
This PR fails on the current master but passes with …
=> [cert] add additional validation for Router_5_1_11 and ED_6_1_06 tests

src/core/utils/channel_manager.cpp
The `aInterval` is in units of seconds.
=> [channel-manager] fix interval units

src/core/meshcop/dtls.cpp
This commit fix a small bug of checking the cipher suites:
Below is wrong because it takes the address of the first cipher suite; this is also not necessary because the checking it done by the `switch` statement following
```c++
VerifyOrExit(&mCipherSuites[0] != NULL, rval = MBEDTLS_ERR_SSL_BAD_INPUT_DATA);
```
instead, we should check if `mCipherSuites[1] == 0`, as mbedtls will depends on it.
=> [dtls] fix bug of cipher suites check

src/core/meshcop/commissioner.cpp, src/core/meshcop/commissioner.hpp, src/core/meshcop/dtls.cpp, src/core/meshcop/dtls.hpp
This commit moves the definition of provisioning URL TLV member
variable to `Commissioner` class (from `Dtls` class).
--------
It was originally defined in `Dtls` so that it can be shared between `Joiner` and `Commissioner` but with recent changes  `Joiner` does not use/need the `Dtls`  variable.
=> [commissioner] add provisioning URL member variable

src/core/thread/mle.cpp, src/core/thread/mle.hpp, tests/toranj/test-032-child-attach-with-multiple-ip-addresses.py
This commit changes preparation of "Child Update Response" (on a
child) such that only the mesh-local address is included in Address
Registration TLV. If the child has more addresses to register it
follows up with its own "Child Update Request".
------------
It also updates `toranj` test-032 to cover the address registration behavior by child after parent reset.
=> [mle] only include mesh-local address in "Child Update Response"

examples/platforms/cc2538/entropy.c
otPlatEntropyGet is called before OT instance is available. This PR adds check if sInstance is initialized. Should fix #3859 
Note:
entropy.c implementation should be OT instance independent but this one is...
=> [cc2538] fix entropy.c

src/core/thread/mle.cpp
This commit changes the `Mle::Store()` behavior such that if a device
is not attached and there is no previously saved `NetworkInfo`
(indicating that the device has never been attached before) we skip
saving/updating the `NetworkInfo`. Note that on a device reset the
MLE/MAC frame counters (which are part of `NetworkInfo`) would reset
but device would also start with a new randomly generated extended
address (so the security nonces would not be repeated).
=> [mle] skip saving NetworkInfo before device is attached (for first time)

src/core/mac/sub_mac.cpp
In the current the implementation, the second sample will be skipped
because the timer was not fired yet.
=> [mac] keep the second energy scan sample

src/ncp/hdlc.hpp, src/posix/platform/radio_spinel.cpp, tests/unit/test_hdlc.cpp
This commit updates the `MultiFrameBuffer` class implementation mainly
how the saved frames in buffer are read. The new code allows user to
re-read the frames again. This change makes the implementation simpler
and more flexible. The corresponding unit test is also updated to
verify new behavior.
=> [hdlc] update MultiFrameBuffer to allow saved frames to be re-read

src/cli/cli.cpp
I don't think we should skip decrementation of `mCount` value in case e.g. network is down, or there is no memory.
=> [cli] count failed ping try

src/core/thread/time_sync_service.cpp
Fixes #3879 - [time-sync] new devices joining a partition can cause the whole partition to lose synchronisation with the leader
Also added some logging under the 'core' channel. I'm not sure if this is quite right but I always find myself having to add temporary logging when working on this, so would be good to include some permanently.
Also removed setting `mLastTimeSyncReceived` to the current time in the constructor. I think could have introduced a bug where a device joining a non-time sync capable partition would cause it to believe for a short period that it was synchronised.
=> [time-sync] reset sequence upon joining a new partition & ensure leader is always authoritative

src/core/common/instance.cpp, src/core/common/instance.hpp
This commit updates order of member variable definitions in the
Instance class to ensure that objects that may be used by others are
initialized first. In particular, Tasklet and Timer Schedulers, and
RandomManager are initialized first. On FTD/MTD, this is followed by
Notifier, Settings, and MessagePool objects.
=> [instance] update order of member variables

src/core/net/dhcp6_client.cpp
A pointer was used to point to the IdentityAssociation Linked List for the valid DHCP prefix information in Thread Network.
In #3287, the pointer was removed and whether or not one entry in the `mIdentityAssociations` array is one DHCP prefix configuration becomes to depend solely on the the entry's status. 
Stricter status conditions should be applied when solicit, otherwise there is chance that the Short Address of the DHCP Server is 0x0000, matches the default reset value (all 0) of one invalid `mIdentityAssociations entry`.
=> [dhcp] fix solicit request issue introduced in #3287

src/core/common/message.cpp, src/core/common/message.hpp, tests/unit/test_priority_queue.cpp
This commit removes the all-messages queue from `MessagePool`. This
simplifies the `Message` header `MessageInfo` and allow a message
to be inserted into one linked list.
--------
The idea behind the all-message queue in `MessagePool` was for us to have a way to track all allocated messages and can possibly evict/drop a low-priority message to make room for other higher priority ones. Currently we allow eviction from the `mSendQueue` priority queue in `MeshForwarder` but the all-message queue is not really used for this. Talking with @jwhui , we decided to remove this feature from code. When needed we can get to all messages by keeping track of a list of message queues from which we allow message eviction. This model let us be selective and permit eviction from certain queues and disallow …
=> [message] remove the AllMessageQueue in MessagePool

src/core/meshcop/dtls.cpp
This PR fixes the DTLS bug that it returns to user before it is truly disconnected.
Previously, the DTLS implementation will call user's callback when it is in the `kStateCloseNotify` state. But this is not the true `DISCONNECTED` state because it doesn't allow user to start a new connection:
```c++
// Checked in Dtls::Connect
VerifyOrExit(mState == kStateOpen, error = OT_ERROR_INVALID_STATE);
```
Suppose the first connnection request failed and user reconnects in the callback, it would failed with `OT_ERROR_INVALID_STATE`. This is not reasonable.
=> [dtls] invoke callback after DTLS disconnect timeout

src/ncp/ncp_base_dispatcher.cpp, src/ncp/ncp_base_ftd.cpp, src/ncp/spinel.c, src/ncp/spinel.h
This commit adds a new property `SPINEL_PROP_THREAD_NEW_DATASET` in
spinel to create a new Operational Dataset to use when forming a new
network. This property maps to `otDatasetCreateNewNetwork()`
=> [ncp] spinel prop to get a new dataset (use when forming new network)

src/ncp/spinel.c
This commit adds `spinel_validate_utf8()` function which verifies
whether a given (null terminated) sequence of bytes (string) follows
the UTF8 encoding format. This function is then used to check any
decoded/unpacked spinel UTF8 type. This commit also adds test-cases
in spinel to check the behavior of the new function with a set of
UTF8 valid and invalid strings.
=> [spinel] validate decoded/unpacked UTF8 string

src/ncp/spinel.h
This commit removes unused macro definitions in spinel header file.
=> [spinel] remove unused definitions

include/openthread/coap.h, src/cli/cli_coap.cpp, src/cli/cli_coap_secure.cpp, src/core/api/coap_api.cpp, src/core/coap/coap.cpp, src/core/coap/coap_message.cpp, src/core/coap/coap_message.hpp, src/core/meshcop/announce_begin_client.cpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/energy_scan_client.cpp, src/core/meshcop/joiner.cpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/leader.cpp, src/core/meshcop/panid_query_client.cpp, src/core/thread/address_resolver.cpp, src/core/thread/energy_scan_server.cpp, src/core/thread/mle_router.cpp, src/core/thread/network_data.cpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_diagnostic.cpp, src/core/thread/panid_query_server.cpp
- Update Coap::Message::SetToken() to return error.
- Update Coap::Message::SetDefaultResponseHeader() to return error.
- Add error checking around calls to the above.
=> [coap] add checks for OT_ERROR_NO_BUFS

src/core/mac/mac.cpp, src/core/mac/mac.hpp
This PR contains two small changes/improvements in MAC (kept them seperate commits).
- [mac] rename methods preparing beacon and beacon request frames
- [mac] inline short/simple methods
=> [mac] inline shorter methods / rename frame preparing methods

src/core/common/message.hpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/thread/data_poll_manager.cpp, src/core/thread/data_poll_manager.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp
This commit moves the implementation of data poll transmission
related logic into `Mac` and `DataPollManagr` from `MeshForwarder`.
=> [mac] move data poll tx into Mac and DataPollManager

src/core/thread/data_poll_manager.cpp, src/core/thread/data_poll_manager.hpp
This commit remove the logic in `DataPollManager` related to handling
of the `NO_BUFS` error case when sending a data poll. This logic is no
longer needed since the data poll tx logic is now handled by `Mac`
layer directly and there is no need to allocate/use a `Message` instance
for data poll (which could earlier lead to `NO_BUFs` error situation).
-----------
This is PR/change that follows https://github.com/openthread/openthread/pull/3915 (and is on top of the commit from that PR). Submitted a seperate PR to keep https://github.com/openthread/openthread/pull/3915 easier to read/review.
The main change in this PR is in this commit: https://github.com/openthread/openthread/pull/3918/commits/781294b42dbf43a23b7de91e15ef646fadc28d78
=> [data-poll-manager] remove unneeded code handling NO_BUFS error

Android.mk, src/core/Makefile.am, src/core/api/link_api.cpp, src/core/common/instance.hpp, src/core/mac/data_poll_sender.cpp, src/core/mac/data_poll_sender.hpp, src/core/mac/mac.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mle.cpp, src/core/thread/network_diagnostic.cpp
This commit renames the `DataPollManager` to `DataPollSender` and
also moves the files in `src/core/mac` folder.
---------
This is in preparation for adding a new class `DataPollHandler` (to handle data polls and indirect tx by mac layer).
=> [data-poll-sender] rename DataPollManager as DataPollSender

src/core/coap/coap_message.cpp, src/core/coap/coap_message.hpp, src/core/common/message.cpp
#3419 introduced some setback about payload marker.
> RFC7252:  The presence of a marker followed by a zero-length payload MUST be processed as a message format error.
=> [coap] remove payload marker correctly and add payload marker check

src/core/thread/network_diagnostic.cpp
In #3284, the source for network diagnostic is explicitly specified as RLOC.
However when link local address is the destination, link local source might
be preferred.
=> [network-diagnostic] specify link-local source for link-local destination

src/core/thread/mesh_forwarder.cpp
This commit ensures to clear the indirect message pointer on all
children and reset the indirect message count (which in turn clear the
source match table) from `MeshForwarder::Stop()`. This addresses the
issue where on an `Stop()`/`Start()` call the source match table can
become out of sync with the send queue and/or a child may hold on to
an already freed `Message`.
=> [mesh-forwarder] clear children's indirect msg and src match table on stop

examples/platforms/posix/Makefile.platform.am, examples/platforms/posix/alarm.c
This PR enhances the microsecond timer implementation with POSIX timer
API. This only enhances simulation on Linux because the API is not
supported on macOS.
The idea is call `timer_settime()` when schedule a microsecond procision alarm.
Linux will notify the process with the configured signal
`OPENTHREAD_CONFIG_MICRO_TIMER_SIGNAL`. The signal handler does
nothing, but the process will be waken up and the existing micro timer process
can be performed on time.
=> [posix-sim] enhance microsecond alarm implementation

src/core/meshcop/commissioner.cpp
Adding the SendPetition error handling in Start and moving it before updating the state fixes
the potential issue of locking up the commissioner in the OT_COMMISSIONER_STATE_PETITION
state without having actually sent the petition.
=> [commissioner] add error checking to GetLeaderAloc and SendPetition in Start

src/posix/platform/hdlc_interface.cpp, src/posix/platform/misc.c
POSIX-app by default disables logs to platform region and even enabled
logs are handled by syslog without printing to stderr. This PR prints
the error information to stderr at exit so that user may know what
happens.
This PR also eliminates the failure message of wait for no child
process exists.
=> [posix-app] enhance RCP failure info

include/openthread/platform/radio.h, src/core/mac/mac.cpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/thread/lowpan.cpp, src/core/thread/lowpan.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp
This adds support for MAC frames greater than 255 bytes in preparation
for upcoming link layers which can support such long frames.
=> [mac] change frame length type from uint8_t to uint16_t

src/cli/cli.cpp, src/cli/cli.hpp
There are some unnecessary includes in the CLI. Maybe it makes sense to remove them. If not, this PR can also be closed again.
* `#include "cli_coap.hpp"` already in header
* `#include "cli_coap_secure.hpp"` already in header
* first `#include <coap/coap_message.hpp>` already included by `cli_coap.hpp`
* second  `#include <coap/coap_message.hpp>` already included by `cli_coap_secure.hpp`
=> [cli] delete redundant and unnecessary includes

src/core/mac/mac_frame.cpp
This fixes a linker error when buiding with OT_LOG_LEVEL_NOTE.
MeshForwarder depends on Mac::Frame::ToInfoString at the NOTE level.
Resolves #3961.
=> [logs] compile Mac::Frame::ToInfoString at NOTE log level

src/cli/cli.cpp, src/posix/Makefile.am, src/posix/platform/Makefile.am, src/posix/platform/hdlc_interface.hpp, src/posix/platform/radio_spinel.hpp
This PR aims to simplify the posix-app makefiles (remove the use `inc_hdlc.cpp` and `inc_spine.c` trick). The idea is to instead include the library `libopenthread-ncp-ftd.a` when linking the final posix-app executable `ot-ncp`,  `ot-cli` and/or, `o-daemon`.
The PR contains 3 separate (small) commits: 
-  [cli] ensure legacy callback APIs are defined as `OT_TOOL_WEAK`
-  [posix-app] simplify the makefile (link in ncp lib).
-  [posix-app] ensure header files from ncp folder have "ncp/" prefix
=> [posix-app] simplify makefiles

src/core/coap/coap.cpp
This PR prevents the CoAP stack from sending automatic 'Not Found' responses to multicast CoAP requests, as suggested in RFC7252 8.2:
```
When a server is aware that a request arrived via multicast, the
server MAY always ignore the request, in particular if it doesn't
have anything useful to respond (e.g., if it only has an empty
payload or an error response).
```
This PR also allows CoAP requests that are sent to multicast addresses to receive multiple responses, which will all be processed by the same handler callback (For instance, a multicast GET to discover network resources).
imo this change makes the inbuilt CoAP stack slightly more useful for simple applications.
=> [coap] Improve behaviour of CoAP multicast requests & responses

src/core/mac/link_raw.cpp, src/core/mac/link_raw.hpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/mac/sub_mac_callbacks.cpp
This commit changes the sub-mac callback model to simplify it such
that `SubMac::Callback` is itself an `InstanceLocator` and directly
calls into the correct next layers (`Mac` or `LinkRaw`). This model
relaxes the need for the other classes to sub-class the `Callback`
and will have `SubMac` itself define a `mCallbacks` instance (which
is an empty class) instead of tracking a reference to a callback
object.
=> [mac] change the sub-mac callback model

src/posix/Makefile-posix
This commit add 'HOST' to provide the option for changing compile target host for cross compiling.
=> [posix-app] add HOST flag for cross compiling

Android.mk, src/core/Makefile.am, src/core/api/link_raw_api.cpp, src/core/common/instance.hpp, src/core/mac/data_poll_handler.cpp, src/core/mac/data_poll_handler.hpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/thread/indirect_sender.cpp, src/core/thread/indirect_sender.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle_router.cpp, src/core/thread/src_match_controller.cpp, src/core/thread/src_match_controller.hpp, src/core/thread/topology.cpp, src/core/thread/topology.hpp
This PR changes the design of indirect frame tx in OpenThread core. The primary objective is move the handling of data polls and indirect tx closer to MAC layer. 
- This enables future enhancements to have RCP handle data polls and indirect tx (including retx of indirect frame tx).
- Also helps get the MAC layer definition closer (but not a 100% match) to 802.15.4 MCPS/MLME  style primitive definitions. 
- Helps simplify the code and reduce complexity and responsibility  of `MeshForwarder` module.
- Allows each module to define its own state/info it requires to be saved per child/neighbor in the `Child` class.
The PR contains multiple related commits each containing relatively smaller changes in the hope to structure the overall design and make it easier to review/read the code. Each …
=> [indirect-sender] new design for indirect tx and handling of data polls

tests/scripts/thread-cert/common.py, tests/scripts/thread-cert/mac802154.py, tests/scripts/thread-cert/net_crypto.py, tests/scripts/thread-cert/test_mac802154.py
Enhance the python script when parsing MAC frame. There's a bug when parsing `Header IE`. For Enhanced ACK, there is no `Termination IE`, which would cause wrong parsing of it.
In **<<IEEE Std 802.15.4>>, 7.4.1 IE list termination**, the table indicates that when there are Header IE and no Payload IE or data payload, `Termination IE` is not required. And the frame can
be determined from the frame length and FCS length. This cannot be done by our current parsing order. So I adjust the parsing order. After parsing **Auxiliary Security Header** from start, I jump to the end and get **FCS** and **MIC** first. **Header IE** and **data payload** are parsed at last. This order also works for the case when security is not enabled. I've verified with some tests at my local workspace.
Also sync up …
=> [tests] fix mac header ie parsing problem

examples/platforms/posix/platform-posix.h, examples/platforms/posix/radio.c, examples/platforms/posix/sim/platform-sim.c, examples/platforms/posix/system.c, tests/scripts/thread-cert/config.py, tests/scripts/thread-cert/sniffer.py, tests/scripts/thread-cert/sniffer_transport.py
This PR changes to use multicast to simulate radio transmission. This
avoids sending a frame multiple times, and also avoid duplicated packets
in captures which is annoying when analyzing traffic.
This implementation uses two separate sockets for tx and rx. This is
because the current implementation of thread-cert requires sniffer
reports the exact sender of each packet. This issue can be addressed by
stateful tracking state of each node, but I don't have the cycles for
now.
=> [posix] use multicast to simulate radio

tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Resolve build failure:
```
spi-hdlc-adapter.c:1829:27: error: implicit conversion changes signedness: 'int' to '__useconds_t' (aka 'unsigned int') [-Werror,-Wsign-conversion]
usleep(sSpiResetDelay * USEC_PER_MSEC);
~~~~~~ ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
```
=> [spi-hdlc-adapter] add cast to unsigned int on call to usleep

examples/platforms/efr32mg12/Makefile.am, examples/platforms/efr32mg12/alarm.c, examples/platforms/efr32mg12/radio.c, examples/platforms/efr32mg12/system.c, examples/platforms/efr32mg12/uart.c
Added otSysEventSignalPending calls and defined as a weak function to efr32mg12.  This is for the porting of OpenWeave to run on top of OpenThread on the EFR32 and is used as a way to wake up the Thread task to execute otSysProcessDrivers in response to uart, alarm and radio events. 
Added configuration of NVIC and interrupt priorities.
Moved RTCDRV Initialization from radio.c into system.c
Note that uart.c only calls otSysEventSignalPending when a transfer (currently 64-bytes) is complete.  This doesn't affect bare-metal CLI and NCP apps.   However we may modify this in a later commit to call otSysEventSignalPending on every byte received.
=> [efr32] add otSysEventSignalPending calls to efr32mg12

.travis/script.sh
This PR makes the travis run scan-build twice, for the UART and the SPI NCP configurations respectively.
So far the SPI has not been covered.
Is it preferred to restrict the number of passed flags to the second run or should we just leave a complete set as is?
=> [travis] extend ncp transport coverage

examples/platforms/efr32mg12/brd4161a/hal-config.h, examples/platforms/efr32mg12/brd4166a/hal-config.h, examples/platforms/efr32mg12/brd4304a/hal-config.h, examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/main.c, examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/main.c
Fixes build error on efr32mg12/brd4304a that resulted in a conflicting define of BSP_LED_POLARITY.
Removed hal-config-board.h from sleepy demo and moved some definitions into each hal-config.h in order to build.
=> [efr32] fix brd4304a build error of duplicate define

tests/toranj/test-002-form.py
This commit updates toranj `test-002` to verify behavior of `wpantund`
when a command is issued immediately after a `reset`.
----
This is tied to https://github.com/openthread/wpantund/pull/428 and expected to fail until the `wpantund` change is merged.
=> [toranj] update test-002 to verify immediate command after a reset

src/core/thread/indirect_sender.cpp, src/core/thread/indirect_sender.hpp, src/core/thread/mle_router.cpp, tests/toranj/test-027-child-mode-change.py
**[indirect-sender] convert queued child messages when mode changes**
This commit ensures all queued messages for a child are accordingly
converted (direct vs. indirect transmission) when a child switches its
mode (from sleepy to non-sleepy or vice versa).
**[toranj] update child mode change test for msg direct/indirect conversion**
This commit updates `test-027-child-mode-change` to verify the
behavior of a parent node related to conversion of any queued messages
(direct vs indirect tx) upon the child's mode change. It ensures
unicaset and multicast messages are correctly received by the children
on a mode change (sleepy to non-sleep or vice versa).
It should help address issue https://github.com/openthread/openthread/issues/3988.
=>  [indirect-sender] convert queued child messages when mode changes

src/posix/platform/hdlc_interface.cpp
This commit fix error that when using OpenWRT package otbr project,
there will be an error: missing sentinel in function execl.
=> [posix-app] fix missing sentinel in execl()

examples/platforms/nrf52811/platform-config.h, examples/platforms/nrf52811/spi-slave.c, examples/platforms/nrf52840/platform-config.h, examples/platforms/nrf52840/spi-slave.c, third_party/NordicSemiconductor/Makefile.am, third_party/NordicSemiconductor/dependencies/sdk_config.h
This PR modifies SPI Slave implementation to use the driver from the [nrfx](https://github.com/NordicSemiconductor/nrfx).
Additionally, a very rare race condition has been fixed.
=> [nrf528xx] use nrfx_spis driver

examples/platforms/cc1352/uart.c, examples/platforms/cc2538/uart.c, examples/platforms/cc2650/uart.c, examples/platforms/cc2652/uart.c, examples/platforms/efr32mg12/uart.c, examples/platforms/efr32mg21/uart.c, examples/platforms/gp712/uart-posix.c, examples/platforms/gp712/uart-socket.c, examples/platforms/kw41z/uart.c, examples/platforms/nrf52811/uart.c, examples/platforms/nrf52840/uart.c, examples/platforms/nrf52840/usb-cdc-uart.c, examples/platforms/posix/sim/platform-sim.c, examples/platforms/posix/spi-stubs.c, examples/platforms/posix/uart-posix.c, examples/platforms/qpg6095/uart.c, examples/platforms/samr21/uart.c, include/openthread/platform/uart.h, src/cli/cli_uart.cpp, src/posix/platform/uart.c
OpenThread's CLI relies on allocating a (by default) 1kB buffer into which it writes the text to be printed on the serial console so that the platform driver can organise for it to be transmitted to the terminal.
This may be done asynchronously via DMA (in the case of `nrf52840`, `efr32`, etc), or it may be done synchronously from the `otSysProcessDrivers` (e.g. `cc2538`, `emsk`, etc).
On memory-constrained devices like CC2538, it is helpful to reduce the size of this buffer, but this comes at a cost: output from commands such as `help` or `neighbor table` gets truncated as the buffer fills up.
This pull request introduces `otPlatUartFlush()` which when called, forces a blocking transmission of the pending data so that the buffer can be cleared to accept more data.  The buffer size can …
=> [platform] add a UART flush operation

src/core/mac/data_poll_sender.cpp, src/core/mac/data_poll_sender.hpp, src/core/mac/mac.cpp
This commit changes the interaction of `Mac` and `DataPollSender` such
that the selection of a data poll destination MAC address is delegated
to `DataPollSender` (related code is moved into `DataPollSender` from
`Mac`).
=> [data-poll-sender] add logic to select poll destination

src/core/meshcop/dtls.cpp, src/core/meshcop/dtls.hpp
A call to `mbedtls_ssl_set_client_transport_id()` is necessary when using
the SSL Server module. This commit ensures a call to the aforementioned
function when using CoAP Secure with PSK cipher suite.
=> [dtls] fix when SSL Server is enabled

src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp
This commit changes `MeshForwarder` to drop a direct supervision type
message. A direct supervision message is possible in the case where a
sleepy child switches its mode (becomes non-sleepy) while there is a
pending indirect supervision message in the send queue for it. The
message would be then converted to a direct tx. This commit also
removes the definitions/methods (e.g. `SendEmptyFrame()`) that were
being used for prepartion of supervision message which are no longer
needed.
=> [mesh-forwarder] drop direct supervision message

examples/platforms/efr32mg12/uart.c, examples/platforms/efr32mg21/uart.c
Revert uart.c in efr32mg12 and efr32mg21 to commit 4c06b47c34. 
This is a workaround for program counter / stack pointer corruption when used as NCP.
1) This is the commit prior to 5d2e6cd0d9, "[efr32] take advantage of DMA for efr32 USART receive (#3730)".
@josephn123 
We are reverting to the older uart.c until we can resolve the issue below.  Once resolved we intend to restore the changes to uart.c.
We have noticed that the EFR32 is often not starting or resetting correctly when used as an NCP and wpantund shows the following:
wpantund[1822]: The NCP is misbehaving: Repeatedly unable to initialize NCP. Entering fault state.
wpantund[1822]: State change: "uninitialized" -> "uninitialized:fault"
wpantund[1822]: Experiencing extended insomnia. Resetting internal state.
Using the O-Zone …
=> [efr32] revert uart.c in efr32mg12 and efr32mg21 to commit 4c06b47c34

Android.mk, src/core/Makefile.am, src/core/api/thread_api.cpp, src/core/thread/announce_sender.cpp, src/core/thread/device_mode.cpp, src/core/thread/device_mode.hpp, src/core/thread/indirect_sender.cpp, src/core/thread/indirect_sender.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_tlvs.hpp, src/core/thread/network_diagnostic_tlvs.hpp, src/core/thread/topology.hpp
This commit adds a `Mle::DeviceMode` class which is warpper over
a device mode bitmask (`uint8_t`) and provides the common helper
functions like `IsRxOnWhenIdle()`, `IsFullThreadDevice()`, etc.
=> [mle] adding DeviceMode class

src/ncp/ncp_base_radio.cpp, src/posix/platform/radio_spinel.cpp, src/posix/platform/radio_spinel.hpp
This PR changes the default timestamp of rx frames to be 64bit, which is
aimed to ensure the timestamp never wraps. This PR changes the protocol
of spinel.
**NOTE** Changing spinel protocol is not allowed normally, however, since the
timestamp is only used by sniffer, we exceptionally changed this for efficiency
consideration. Pyspinel is also updated accordingly.
=> [spinel] use 64bit timestamp for rx frames

src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle_router.cpp
Some configs of rsyslog() replace tabs with "#011" which makes for some not-so-stellar log reading. This commit replaces tabs with a fixed 4 spaces, instead.
=> [logging] replace tab char with 4 spaces

src/cli/cli.cpp, src/core/api/link_api.cpp, src/core/common/instance.cpp, src/core/mac/data_poll_sender.cpp, src/core/mac/mac.cpp, src/core/net/dns_client.cpp, src/core/net/ip6.cpp, src/core/thread/address_resolver.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/network_data_leader.cpp, src/core/utils/child_supervision.cpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base_ftd.cpp, src/ncp/ncp_base_mtd.cpp, src/ncp/ncp_uart.cpp
This commit simplifies boolean checks containing `== false` to use the
`!` operator instead, and removes redundant `== true` checks. This
commit aims to harmonize the boolean check style across core modules.
=> [style] harmonize boolean checks

src/posix/platform/radio_spinel.cpp
This commit removes the extra logging of spinel error status on
tx done callback. The error will be logged from `LogIfFail()` at
the exit of the `HandleTransmitDone()`.
=> [radio-spinel] remove extra log on tx done failure

src/core/Makefile.am, src/core/mac/data_poll_handler.cpp, src/core/mac/data_poll_handler.hpp, src/core/thread/indirect_sender.cpp, src/core/thread/indirect_sender.hpp, src/core/thread/indirect_sender_frame_context.hpp
This commit adds a `FrameContext` type (containing all info that need
to be saved along with a prepared frame for indirect transmission) and
its support in `IndirectSender` and `DataPollHandler`. While the
`FrameContext` is defined by the `IndirectSender`, the lower-layer
`DataPollHandler` is expected to provide the buffer/object for it to
be stored (when the frame is prepared). This model allows different
implementations of `DataPollHandler` to adopt different strategies on
how to store the context.
This is follow up from discussion in PR https://github.com/openthread/openthread/pull/3952#issuecomment-508266590.
=> [indirect-sender] add FrameContext class

src/core/api/link_raw_api.cpp, src/ncp/ncp_base.cpp
This commit changes the get handler for `SPINEL_PROP_HWADDR` to
use the public OT link API `otLinkGetFactoryAssignedIeeeEui64`
instead of the platform API.
=> [ncp] use OT public link API to get factory-assigned EUI64

examples/platforms/posix/radio.c
The PR #4015 missed setting the timestamp when the option TIME_SYNC is enabled
=> [posix] fix time sync issue

src/core/mac/data_poll_handler.cpp
This commit changes data poll handler to log an indirect tx failure
only when the tx attempt counter is increased (i.e., when there is a
no-ack error).
=> [data-poll-handler] update the logging of indirect tx failure

examples/platforms/posix/radio.c
This sets frame rx timestamp no matter in promiscuous mode or not. This is useful for debugging time related issues.
=> [posix-sim] always set timestamp

src/ncp/ncp_base.cpp
This PR fixes the problem with initializing the NCP with wpantund. The bug was apparent when the NCP image was built with the `FULL_LOGS` switch set.
The reason for the bug was that after the pseudo reset the OpenThread stack wrote logs to NCP's `otPlatLog` implementation that used the not yet initialized NCP object. This put the `mUartSendTask` and `mUpdateChangedPropsTask` to the `TaskletScheduler` linked list. 
Later when the NCP itself was initialized, the `mNext` pointer in the tasklets `mUartSendTask` and `mUpdateChangedPropsTask` was set to null, causing all tasklets scheduled after the `mUartSendTask` to be lost. The NCP reset status could not be in such case sent to the wpantund. The wpantund then retried resetting the NCP, which repeated the process until the wpantund gave up.
=> [ncp] set NCP instance pointer to NULL during pseudo reset

src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/sub_mac.hpp
The new model handles the case where frame retries are not handled
by sub-mac layer (e.g., delegated to radio platform).
-------
This helps improve the log message in posix-app model where the retx is handled by the RCP and not on the host side.
=> [mac] update the log message for frame tx failure

src/ncp/ncp_uart.cpp
This commit fixes the wrong name used in `npc_uart.cpp`. Note that
this config parameter is part of `configure.ac` definitions.
=> [config] fix config option ENABLE_NCP_SPINEL_ENCRYPTER

include/openthread/thread.h, src/core/config/dhcp6_server.h, src/core/config/joiner.h, src/core/config/tmf.h
This commit removes the unused duplicate definition in `tmf.h` for
`OPENTHREAD_CONFIG_INFORM_PREVIOUS_PARENT_ON_REATTACH` (this is
defined in `config/mle.h`). Also updates the comment/documentation
for `DHCP6_SERVER_NUM_PREFIXES` and `JOINER_MAX_CANDIDATES`.
=> [config] remove duplicate unused definitions and fix comments

tests/scripts/thread-cert/node.py
This is useful when more logs are enabled and the logs contain `leader`, `child`, `router` or `leader`.
=> [test] enhance getting state

src/core/thread/mle.cpp
This commit ensures to save the network info in non-volatile settings
when the MLE device mode is changed (`Mle::SetDevcieMode()`)
independent of whether the device is currently attached or not. This
helps address the situation where there is a single router/leader
device in network and user changes the MLE thread mode to make it a
sleepy (where due to device being the only node in the network it
would not attach). Then, later upon device reset (without the change
in this commit) the device would have started again as router/leader.
Note that network info is saved/updated in non-volatile memory after a
successful attach.
---------------
More info related to this: This is not an issue on devices which use `wpantund` as host-side driver
since `"Thread:DeviceMode"` is one of the persisted …
=> [mle] save network info on mle mode change

examples/platforms/efr32mg12/alarm.c
Added a fallback to the efr32mg12 where if an alarm set with an absolute expiry time (t0 + dt) has failed to start then we fallback to using a relative timer (dt).
This should fix the issue seen in (#4018).
It has been observed in testing that alarms have stopped working on the efr32mg12.  This has caused other issues such as buffers not being freed or the network splitting as no further alarms are scheduled.
The cause is due to an alarm being set to expire slightly in the past.  In this case we fallback to using a relative timer using only the dt value.  For the cases where it fails it will be set to 1ms into the future from the time the RAIL_SetTimer is called.  
RAIL maintains time in microseconds but is being rounded down for the time returned in milliseconds by …
=> [efr32] fallback to use relative timer if absolute timer fails to start

src/core/net/ip6.cpp
Thread defines a mesh-local scope for IPv6 unicast addresses. However,
the mesh-local scope can only be inferred by inclusion of the
mesh-local prefix.
This commit updates the IPv6 source address selection to infer the
destination address scope based on a prefix match with currently
assigned addresses.
=> [ip6] fix default source address selection

src/core/thread/mle_router.cpp
If already connected as a child when enabling the routerrole, then the timer won't start.
=> [mle] enable state update timer when enabling router role

src/core/meshcop/border_agent.cpp
This PR fix the bug in border agent that it assumes the _COM_PET.rsp_ from the leader is _CHANGED_. But it is possible for the leader to return a _4.XX_ error response. In that case, the border agent should forward that error response.
=> [border-agent] handle error responses from leader

.travis.yml, .travis/before_install.sh, .travis/check-pretty, .travis/check-size, .travis/script.sh
This PR merges the pretty checks into one to reduce the jobs and save time.
Besides, as many jobs were added, `.travis/before_script.sh` becomes very big. This PR removes pretty check and size report's dependency on that script. Since many job now differs much, it will be easier to maintain and use if each job itself manages its own prerequisites.
=> [travis-ci] merge pretty check

examples/platforms/posix/radio.c
---
Variable `socketaddr`  no longer needed/used after #3993 moving the socket creation to `initFds()`.
=> [posix-sim] remove unused variable

src/core/mac/sub_mac.cpp
This commit changes the `SubMac::BeginTrasnmit()` by moving the call
to `Transmit()` on radio platform after the state change to
`kStateTransmit` (and pcap callback). This relaxes the requirement for
radio platform implementation and allow it to invoke `TxDone` callback
directly from the `Transmit()` call itself (instead of requiring
`TxDone` to be called only after the `Transmit()` call returns).
=> [sub-mac] relax the requirement for TxDone callback

src/core/meshcop/border_agent.cpp
This PR fix the bug that border agent incorrectly appends the UDP Encapsulation TLV:
- _AppendTlv_ does not accept an Extended TLV;
- _AppendTlv_ expects a complete TLV object which includes the _value_ just behind the _length_.
=> [border-agent] fix appending extended UDP Encapsulation TLV

include/openthread/platform/logging.h, src/posix/platform/logging.c
* Simplified posix-app logging
* typedef otLogLevel to signed int so that when dynamic logging and
reference_device is enabled, there will not be always true error.
=> [posix-app] remove node id from logging

include/openthread/link.h
otSetChildTimeout -> otThreadSetChildTimeout
=> [docs] fix reference to old function name in link.h

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_WpanCtl.py
This PR fixed a OpenThread THCI bug that setXpanId might raise exception when called with xPanId of length 16. This PR also renamed __convertLongToString to __convertLongToHex to better reflect its functionality and optimized its implementation.
=> [thci] fix setXpanId bug and code cleanup

src/core/thread/address_resolver.cpp, src/core/thread/address_resolver.hpp, src/core/thread/mesh_forwarder_ftd.cpp
Thread 1.1 Spec 5.5.2.2:
```
FTDs MAY update EID-to-RLOC Map Cache entries by inspecting packets being sent/received
via a Thread Interface.
```
This PR would add EID-to-RLOC map cache entry by inspecting packets received, aiming to reduce  
RealmLocal multicast AQ when response is expected.
=> [core] EID-to-RLOC cache map optimization

examples/platforms/nrf52811/radio.c, examples/platforms/nrf52840/radio.c
`sInstance` was unused without `OPENTHREAD_CONFIG_MAC_HEADER_IE_SUPPORT`.
=> [nrf528xx] fix compiler warning

src/core/meshcop/commissioner.cpp
The PR fixes the issue that running "commissioner start" command when device role is detached will cause commissioner not be able to start or stop.
=> [commissioner] only allow attached device to become commissioner

src/core/mac/data_poll_handler.cpp
----
This PR removes the extra check remaining from before the change from https://github.com/openthread/openthread/pull/3785 and the related follow-ups. Before having the "Acked with FP" feature, we relied on  number of indirect msg in queue (for the child) or state of src-match-table to determine/guess if the data poll was acked with fp or not. That is now redundant and can be incorrect (e.g., if a message was removed/evicted after data poll was acked with fp set). 
If the data poll is acked with "frame pending" flag set, the child would stay in rx expecting a frame from parent. If we have no frame for the child, parent would send an empty frame to let the child know that it can go to sleep (and avoid the child having a data timeout and retx the data poll).
This change is required for …
=> [data-poll-handler] always process data poll when acked with "frame pending"

examples/Makefile-nrf52811, examples/Makefile-nrf52840
Later in Makefile we set BuildJobs to the number of threads supported by CPU (only if this value is not set). Assigning default value of 10 limits performance on high performance PCs.
=> [nrf528xx] remove default value for BuildJobs

src/core/meshcop/dataset_manager_ftd.cpp
This PR fix the bug that leader sends `MGMT_DATASET_CHANGED.ntf` to border agent rather than commissioner. 
With current implementation, border agent will not forward `MGMT_DATASET_CHANGED.ntf` to commissioner by `UDP_RX.ntf`:
```c++
// line 407 of HandleUdpReceive() in border_agent.cpp
VerifyOrExit(aMessageInfo.GetSockAddr() == mCommissionerAloc.GetAddress(),
error = OT_ERROR_DESTINATION_ADDRESS_FILTERED);
```
=> [meshcop]  fix sending MGMT_DATASET_CHANGED.ntf to commissioner

include/openthread/link.h, src/core/mac/data_poll_sender.cpp, src/core/mac/data_poll_sender.hpp, src/core/thread/network_diagnostic.cpp, tests/toranj/start.sh, tests/toranj/test-035-child-timeout-large-data-poll.py
This PR contains three related changes/commits.
It addresses an issue with child timing out on parent (kicked out of child table) if the data poll period is set (by user) to a value larger than the child's timeout.
[network-diagnostics] use the child timeout directly
This commit changes the `NetworkDiagnostic::FillRequestedTlvs()` to
directly use the child timeout value in appended `TimeoutTlv`. This
addresses an issue where a user-specified long data poll interval
could cause the timeout TLV in diags response to be set higher than
actual child's timeout value.
---------------
[data-poll-sender] always honor the default child timeout based poll interval
This commit changes the `DataPollSender` to ensure that a child device
will always send a data poll within its timeout interval. This …
=>  [data-poll-sender] always honor the default child timeout based poll interval

src/core/common/random_manager.cpp, src/core/common/random_manager.hpp, src/core/meshcop/dtls.hpp
If platform uses MbedTLS feature to add entropy source during context init (by platform entropy, HAVEGE or `MBEDTLS_ENTROPY_HARDWARE_ALT`) we shouldn't add second entropy source. This saves time and power as we don't have to poll two different entropy sources/poll same entropy source twice.
=> [crypto] don't add entropy source if it's done by mbedTLS

src/core/api/commissioner_api.cpp, src/core/api/thread_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/commissioner.hpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/meshcop_tlvs.hpp, tests/unit/test_pskc.cpp
The wrapper class `Mac::ExtendedPanId` mainly defines overloads of operators `==` and `!=` and `ToString()` method.
=> [mac] add Mac::ExtendedPanId type (wrapping otExtendedPanId)

src/core/api/link_raw_api.cpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/mac/sub_mac.cpp, src/core/net/ip6_address.cpp, src/core/thread/src_match_controller.cpp, tests/unit/test_lowpan.hpp, tests/unit/test_mac_frame.cpp
This commit updates `Mac::ExtAddress` and `Mac::Address` to add
helper methods to copy address from/to a byte array in normal or
reverse bye order. This commit also adds a unit test for the two
Address classes.
=> [mac-frame] helper methods to copy ExtAddress in normal/reverse byte order

src/core/coap/coap.cpp
The commits fixes the bug that Coap servers send invalid cached responses, specifically messages with Type=CONN, Code=0, MID=0. 
The cached responses should `Finish` before `Send`.
Please find the pcap traces regarding this issue in [pcap.zip](https://github.com/openthread/openthread/files/3619214/pcap.zip)
=> [coap] finish cached coap response before sending

src/posix/platform/netif.cpp
This PR fixes a crash issue triggered by system command ifconfig down.
This is because OpenThread's tries removing addresses when the platform
network interface is already down.
=> [posix-app] fix crash on os ifconfig down

configure.ac, src/posix/platform/Makefile.am, src/posix/platform/hdlc_interface.cpp, src/posix/platform/openthread-core-posix-config.h, src/posix/platform/platform-posix.h, src/posix/platform/radio_spinel.cpp, src/posix/platform/settings.cpp, tests/unit/Makefile.am, tests/unit/test_hdlc.cpp
This PR aims at adding the filename when die. Other enhancements:
* Enable PLATFORM region by default for posix-app
* Disable warning for zero variadic macro arguments
* Use VerifyOrExit to implement other assert utilities
* Do not call fprintf() and print exit code in assert utility
To print dying message to stderr, add `-v` when launching the app.
To get the exit code, use `echo $?` just after the app died.
=> [posix-app] log filename when die

examples/platforms/cc2538/openthread-core-cc2538-config.h, examples/platforms/cc2538/radio.c
So, I have a confession to make… in PR#3609 I accidentally included some code that would have enabled the receive interrupt on the CC2538 in the NVIC.
Given the receive interrupt handler just blindly clears the interrupt flags, this is probably not a good plan.  So, a better option, implement the rest of it, with a compile-time switch to turn interrupt driven reception off if desired.  This allows for up to two frames to be stored until such time as they can be processed by OpenThread (one frame in the radio's buffer, and one in `sReceivedFrame`).
I'm doing some more thorough tests with the GRL test suite to ensure it hasn't broken anything but indications are it is working as expected (I'd be expecting failures left-right and centre if receive was broken by this).
=> [cc2538] interrupt driven radio driver

include/openthread/commissioner.h, include/openthread/dataset.h, include/openthread/joiner.h, include/openthread/thread_ftd.h, src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_dataset.cpp, src/cli/cli_dataset.hpp, src/core/api/commissioner_api.cpp, src/core/api/joiner_api.cpp, src/core/api/thread_ftd_api.cpp, src/core/coap/coap_secure.hpp, src/core/common/random.hpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/commissioner.hpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/dtls.hpp, src/core/meshcop/joiner.cpp, src/core/meshcop/joiner.hpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/thread/key_manager.cpp, src/core/thread/key_manager.hpp, src/ncp/ncp_base_ftd.cpp, src/ncp/ncp_base_mtd.cpp, tests/unit/test_pskc.cpp
This commit adds a `Pskc` as a wrapper over `otPskc` and also
renames all the uses of `PSK` into `Psk` to follow our variable
and type naming convention which treats an acronym as a whole
word.
=> [key-manager] add Pskc class

src/cli/cli_coap_secure.cpp
This PR fixes possible memory loss in CoAP secure CLI.
=> [coap] add message free on error in Cli::CoapSecure::DefaultHandler

tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_route_table.py
The commits implement the `router_list` and `router_table` methods for Node in simulator. The methods should be useful someday. 
The commits also include a simple test to verify correctness.
=> [posix-sim] add method route_list & route_table to Node

src/core/api/thread_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/joiner.cpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, tests/unit/test_mac_frame.cpp
This commit adds `Mac::NetworkName` class as C++ wrapper over the
`otNetworkName`. It also adds `NetworkName::Data` to represent the
network name as a pointer to a char array buffer (not necessarily null
terminated) with a given length. This representation is used by
`Mac::BeaconPlayload` and `MeshCop::NetworkNameTlv`. This commit also
adds unit test for `Mac::NetworkName` class.
=> [mac] add Mac::NetworkName class

src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp
- Fix insufficient length checks.
- Avoid using a large stack buffer.
=> [meshcop] improve HandleCommissioningGet implementation

src/posix/platform/netif.cpp
This commit set link type to void. If not, there will be two link local
address.
=> [platform-netif] set link type to void

src/core/coap/coap.cpp
This commit add IsBound() judge before send message. Otherwise, it might
crash on Send() when the ifconfig is down.
=> [coap] add IsBound() check in Coap::Send

.travis.yml, .travis/before_install.sh, configure.ac, src/cli/cli_coap_secure.cpp
This PR adds missing definitions in configure.ac to fix configure with
options like `--disable-FEATURE`. This is because some features are
enabled by default, if missing defining as `0`, the `--disable-FEATURE`
will not work.
=> [build] fix missing definitions in configure.ac

include/openthread/commissioner.h, src/core/api/commissioner_api.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/commissioner.hpp, src/core/meshcop/meshcop_tlvs.hpp, src/ncp/ncp_base_ftd.cpp
This PR contains a collection of smaller commit changes/improvements in `Commissioner`.
_[commissioner] update how Provisioning URL is stored_
This commit updates how the `Commissioner` stores the Provisioning URL
(now saved as null terminated string). It also updates the related
APIs (including the public `otCommissionerGetProvisioningUrl`) and its
use in `NcpBase`.
_[commissioner] iterate over joiners using pointer
[commissioner] make simple getter methods inline
[commissioner] log commissioner state changes_
=> [commissioner]  update how Provisioning URL is stored

src/core/mac/mac.cpp
This commit ensures to prioritize a pending poll tx request after
handling a (direct) frame tx request. This addresses the situation
where back-to-back frame tx requests could have delayed a data poll
tx request.
--------
Note  that the back-to-back frame tx requests should not happen in current implementation (`MeshForwarder` would issue next frame tx request from a posted tasklet). However, the fix/change would ensure such a pattern of use behaves correctly.
=> [mac] prioritize a pending poll tx after handling of frame tx

src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, tests/unit/test_mac_frame.cpp
---
Also renamed `kMTU` -> `kMtu` to be consistent with code style.
=> [mac-frame] set kMtu from config param and inline simple getters

src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp
will submit a separate PR for service similarly afterwards
=> [mesh-forwarder] support DHCP traffic forward when DHCP is disabled

examples/Makefile-nrf52840, examples/platforms/nrf528xx/nrf52811/README.md, examples/platforms/nrf528xx/nrf52840/README.md, examples/platforms/nrf528xx/nrf52840/nrf52840_bootloader_ble.ld, examples/platforms/nrf528xx/nrf52840/nrf52840_bootloader_uart.ld, examples/platforms/nrf528xx/nrf52840/nrf52840_bootloader_usb.ld
This commit introduces serial and BLE DFU bootloader support
* Added new linker script for serial and BLE DFU bootloaders
* Added new nRF52840 switches (BOOTLOADER=USB/UART/BLE)
* Deprecated `BOOTLOADER=1` switch
=> [nrf52840] add UART and BLE bootloader support

tests/toranj/start.sh, tests/toranj/test-036-wpantund-host-route-management.py, tests/toranj/wpan.py
----
This test covers behavior of `wpantund` feature for managing of host interface routes (related to off-mesh routes within the Thread network). 
This feature can be enabled using `"Daemon:OffMeshRoute:AutoAddOnInterface"` property (is enabled by default).
A route corresponding to an off-mesh route would be added on host primary interface (by `wpantund`), if it is added by at least one (other) device within the Thread network and
-  either it is not added by host/this-device, or
- if it is also added by the device itself then filtering of self added routes is not enabled, and it is added at lower preference level.
=> [toranj] add test covering wpantund host route management feature

include/openthread/platform/toolchain.h
=> [toolchain] add definition of UINT16_MAX

src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp
The commits include following updates for `MleRouter::UpdateRoutes`
- Move updating link quality ahead of updating routes to fix potential wrong routing path switch
- In each do-while loop, the method traverse each router id and update the routing path to the router (`RU`) according to new Route64 TLV received from the neighbor, and also update link quality out to the neighbor (`LU`) when the router id is that of the receiver. So, there could be `RUs` before `LU` and also after `LU`. The `RUs` before `LU` are using wrong link quality to the neighbor for comparison, thus could cause lower cost routing path be replaced by higher cost routing path or even lost.
- This PR moves `LU` ahead of `RUs` to make sure all `RUs` are using correct link quality to the neighbor for calculation.
- Remove …
=> [mle] fix MleRouter::UpdateRoutes

script/test
I verified all test scripts in `tests/scripts/thread-cert` have `x` permission.
=> [script] use python version specified in test script

src/core/net/udp6.cpp
This PR suppresses warning of unused parameter `aInstance` when `OPENTHREAD_FTD` is not set.
=> [udp] suppress warning of unused parameter

examples/platforms/posix/radio.c
The commits fix the issue that when Src Match is disabled, ACK FramePending is never set for data requests , which on the contrary should always be set for data requests.
=> [posix] always set ACK FP for data requests when SrcMatch is disabled

include/openthread/coap.h, src/cli/cli_coap.cpp, src/cli/cli_coap_secure.cpp, src/core/api/coap_api.cpp
Message ID is managed by CoAP agent. Allowing user setting it may result
in invalid usage. This PR removes this API and adds a new API to
initialize CoAP response message.
=> [coap] remove otCoapMessageSetMessageId()

src/core/coap/coap.cpp, src/core/coap/coap.hpp
Method `ResponsesQueue::EnqueueResponse` was using `GetMatchedResponseCopy` to check if matched response already exists in the cache. The code might clone message only to release it right away, which is not efficient. 
The commits ...
1. Add a new method `ResponsesQueue::FindMatchedResponse` which try to find and return the matched response in the queue, without cloning the message
2. Optimize `EnqueueResponse` by using `FindMatchedResponse`
3. Re-implement `GetMatchedResponseCopy` using `FindMatchedResponse` to  to reduce code redundancy.
=> [coap] optimize call to GetMatchedResponseCopy

tests/scripts/thread-cert/config.py
When running test scripts related with DTLS, we would get some exceptions. For example, `test_coaps.py`:
```
EXCEPTION: Could not find factory to build UDP payload.
Traceback (most recent call last):
File "/usr/local/google/home/irvingcl/Documents/git/openthread/tests/scripts/thread-cert/sniffer.py", line 89, in _sniffer_main_loop
messages = self._message_factory.create(io.BytesIO(data))
File "/usr/local/google/home/irvingcl/Documents/git/openthread/tests/scripts/thread-cert/message.py", line 625, in create
ipv6_packet = self._lowpan_parser.parse(lowpan_payload, message_info)
File "/usr/local/google/home/irvingcl/Documents/git/openthread/tests/scripts/thread-cert/lowpan.py", line 1247, in parse
return self._handle_iphc_header(data, message_info)
File …
```
=> [tests] fix the wrong port of dtls

third_party/silabs/rail_config/rail_config.c
The PR [#3922](https://github.com/openthread/openthread/commit/0bb0b7424#diff-e9cef7a8ce52bf573877847ae819d53dR212) checks if the first channel equals to the minimum channel for the sub-GHz. The minimum channel of sub-GHz is set to 1, the first channel in the channel config entry also should be set to 1 to match the minimum channel of sub-GHz.
=> [efr32mg12] update the channel range of channel config entry

examples/platforms/cc1352/radio.c, examples/platforms/cc2538/radio.c, examples/platforms/cc2650/radio.c, examples/platforms/cc2652/radio.c, examples/platforms/efr32mg12/radio.c, examples/platforms/efr32mg21/radio.c, examples/platforms/gp712/radio.c, examples/platforms/kw41z/radio.c, examples/platforms/nrf528xx/src/radio.c, examples/platforms/posix/radio.c, examples/platforms/qpg6095/radio.c, examples/platforms/samr21/radio.c, include/openthread/platform/radio.h, src/core/radio/radio.hpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base_dispatcher.cpp, src/posix/platform/radio_spinel.cpp, src/posix/platform/radio_spinel.hpp
Changes:
- Radio interface simply passes calls to platform functions
- Platform implementation for nRF52840 and nRF52833
- Placeholders for other platforms (resulting with OT_ERROR_NOT_IMPLENTED)
- Spinel property configuration handlers
=> [radio] handle CCA ED threshold property configuration

src/core/mac/data_poll_handler.cpp, src/core/mac/data_poll_sender.cpp, src/core/mac/mac.cpp, src/core/mac/mac_frame.hpp, src/core/thread/indirect_sender.cpp, src/core/thread/mesh_forwarder.cpp
The TxDone callbacks can be invoked with `OT_ERROR_ABORT` from two
different paths: Either when OpenThread itself cannot prepare the tx
frame (e.g., message was removed while waiting for MAC to handle a tx
request and ask next layers to prepare the frame) or when the radio
platform itself need to abort the tx.
This commit changes the code such that in the first case, the frame
length is set to zero to mark it as empty. The empty frame helps
differentiate between the two cases and ensures that a previously tx
frame is not incorrectly used from the TxDone callbacks.
The TxDone callback handlers (in `MeshForwarder`, `DataPollHanlder`,
`IndirectSender` and `DataPollHandler` are updated to check for frame
not being empty when processing the frame.
=> [mac] set tx frame as empty when tx aborted during frame preparation

examples/Makefile-efr32mg12, examples/Makefile-efr32mg21, examples/platforms/efr32mg12/Makefile.am, examples/platforms/efr32mg21/Makefile.am, third_party/silabs/Makefile.am
Moved the definition  of __START from third_party/silabs/Makefile.am.
This is to allow an external project to be built so that constructors are called at startup. This can be done by removing the nostartfiles configure option and __START definition from their makefile.
The mg12 and mg21 example makefiles within OpenThread continue to build with the nostartfiles option.
=> [efr32] move __START definition to Makefile-efr32mgxx makefiles

examples/platforms/efr32mg21/Makefile.am, examples/platforms/efr32mg21/alarm.c, examples/platforms/efr32mg21/radio.c, examples/platforms/efr32mg21/system.c, examples/platforms/efr32mg21/uart.c
Added otSysEventSignalPending to efr32mg21.
Initialization of the NVIC interrupt priority registers for the efr32mg21.
=> [efr32] add otSysEventSignalPending and NVIC priorities to efr32mg21

src/core/net/netif.cpp, src/core/utils/slaac_address.cpp
This PR contains a couple of smaller changes (each their own small commit) in different modules, all around using `OT_ARRAY_END()` macro and/or changing how we iterate over array elements (using pointer).
- [slaac-address] use OT_ARRAY_END macro
- [netif] use OT_ARRAY_END() when iterating over external address arrays
=> [core] use OT_ARRAY_END and iterate using pointers

examples/platforms/efr32mg12/brd4166a/hal-config.h
Fix for Thunderboard Sense 2 (BRD4166A) LED GPIOs
This bug is inherited from SDK v2.6 bspconfig.h which is also incorrect.
=> [efr32] fix LED gpio port and pin allocation for BRD4166A

src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_types.cpp, src/core/mac/mac_types.hpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp
This PR contains two smaller commits:
**[mac] Adding SetTemporaryChannel()/ClearTemporaryChannel()**
This commit adds new method in `Mac` namely `SetTemporaryChannel()` and `ClearTemporaryChannel()` to allow user to temporarily change the radio channel and use a different channel (during receive) instead of the PAN channel (from `SetPanChannel()`). A subsequent call to
`ClearTemporaryChannel()` would clear the temporary channel and adopt the PAN channel again. The new implementation replaces and simplifies the previous `<Acquire/Release>RadioChannel()` model.
**[mac] add Mac::GenerateRandomPanId()**
This commit adds a helper function `Mac::GenerateRandomPanId()` which generates a random PAN Identifier (excluding the broadcast PAN Id `kPanIdBroadcast`).
=> [mac] Adding <Set/Clear>TemporaryChannel() & GenerateRandomPanId()

include/openthread/link.h, include/openthread/thread.h, src/core/api/link_api.cpp, src/core/api/thread_api.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base.hpp, src/ncp/ncp_base_dispatcher.cpp, src/ncp/ncp_base_mtd.cpp, src/ncp/spinel.c, src/ncp/spinel.h
This PR contains 3 related commits:
**[ncp] add support for clearing all/subset of counters**
This commit adds support in NCP/spinel for clearing counters. It also adds new `PROP_CNTR_ALL_IP_COUNTERS` property to get all IPv6 counters. All (MAC, MLE, IPv6, and NCP) counters can be cleared by writing (`PROP_VALUE_SET` with any value) to `SPINEL_PROP_CNTR_RESET` property. A specific subset of counters (MAC, MLE, IP) can be cleared by writing (any value) to the corresponding spinel property (`PROP_CNTR_ALL_MAC_COUNTERS`, `PROP_CNTR_MLE_COUNTERS`, or    `PROP_CNTR_ALL_IP_COUNTERS`).
**[link] add public OT API otLinkResetCounters to reset MAC counters**
**[mesh-forwarder] add method ResetCounters to clear IP counter**
This commit also adds a public API `otThreadResetIp6Counters()`.
=>  [ncp] add support for clearing all/subset of counters

include/openthread/heap.h
For visibility on https://openthread.io/reference/group/api-heap during future Doxygen runs, based on comments in #4143.
=> [docs] add note that use of the public Heap API is discouraged

src/core/meshcop/joiner_router.cpp
This PR removes redundant message copying when a joiner router is handling a RLY_TX.ntf message.
=> [meshcop] remove redundant message copying

src/core/thread/mle_router.cpp
The commits fix an issue that indirect messages for sleepy child are not correctly cleared in some case. 
In my posix-sim tests, this issue together with the issue fixed in PR #4232 can cause sleepy nodes unable to reattach for a long time, or even forever, as described in following steps:
1. Router R has a sleepy child S which has some indirect messages pending.
1. R changed role to Detached for any reason
2. R changed role to Child
3. R becomes router again with another Router ID
4. R removes the child S by calling `RemoveNeighbor`
* because now R has `mRole == OT_DEVICE_ROLE_CHILD`, R does not call `ClearAllMessagesForSleepyChild`, failed to clear indirect messages
5. R got another child, which reused S's slot in ChildTable (thus having same ChildIndex)
6. S tries to reattach to R, …
=> [mle] remove sleepy child in all roles

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/topology.cpp
We shouldn't rely on `Random::NonCrypto` when generating the challenge values as we don't know it's imperfections. Instead `Random::Crypto` should be used because truly random challenge values are required.
Also, I wonder if we don't have other security-related randoms generated using `Random::NonCrypto`.
The most suspicious for me is the `Slaac::GetIidSecretKey` which may fall back to `Random::NonCrypto` without any fail notification.
=> [security] use Random::Crypto for challenge generation

src/core/thread/key_manager.cpp, tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_WpanCtl.py
The first commit only enable guard timer protection when switching to network key index.
The second commit includes relative THCI updates considering possible further TP468 updates: allowing the initiate reference device to trigger possible multiple key sequence updates; and for DUT,  only default behavior is allowed, i.e. with the guard timer protection.
=> [key-manager] only enable guard timer protection when switching to network key index

.travis.yml
Bug fix will be included in next Arm GCC 8 release.
https://community.arm.com/developer/tools-software/oss-platforms/f/gnu-toolchain-forum/13503/gcc-g-version-8-very-slow-to-compile/159739#159739
=> [travis] disable arm-gcc-8 until compiler bug is fixed

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp, src/core/thread/mle_router_mtd.hpp
- Remove redundant calls to `GetNeighbor()`
- Move message authentication check to message-specific handlers.
- Move message replay check to top of message-specific handlers.
=> [mle] clean up message handling

src/core/thread/address_resolver.cpp, src/core/thread/address_resolver.hpp, src/core/thread/mle_router.cpp
This commits removes deprecated EID-to-RLOC cache if there is entry for
the unicast address registered by MTD child in case this child switches
its parent.
=> [address-resolver] update EID-to-RLOC cache when attaching MTD child

src/core/meshcop/dataset_local.hpp, src/core/meshcop/dataset_manager.hpp, src/core/meshcop/dataset_manager_ftd.cpp
Add check to see if Active Timestamp already exists in the Active
Operational Dataset. If Active Timestamp exists, do not generate
Active Operational Dataset again.
Submitting this as an alternative proposal to #4258.
=> [operational-dataset] only generate active dataset once

src/core/coap/coap.hpp, src/core/coap/coap_message.hpp, src/core/coap/coap_secure.hpp, src/core/net/dhcp6_client.cpp, src/core/net/dhcp6_client.hpp, src/core/net/netif.hpp, src/core/thread/key_manager.cpp
This PR contains couple of smaller unrelated commits:
- [coap] fix typos 
- [key-manager] use Notifier::Update when changing security policy
- [netif] remove unused type LinkAddress
- [dhcp6-client] use NetifUnicastAddress in IdentityAssociation struct
=> [misc] coap typo, key-manager, netif

src/core/common/tasklet.cpp, src/core/common/tasklet.hpp
This PR/commit contains the following changes:
- Changes `TaskletScheduler` to use a circular linked list.
- Adds `Tasklet::IsPosted()` which indicates whether a tasklet is posted or not (by checking `mNext` pointer against NULL).
- Simplifies  processing of tasklets from `ProcessQueuedTasklets()` by creating a copy of current list and clearing the main list (this way, a newly posted tasklet would automatically trigger a call to `otTaskletsSignalPending()`).
=> [tasklet] use circular linked list

tests/toranj/start.sh, tests/toranj/test-038-clear-address-cache-for-sed.py
This test verifies that address cache entry associated with a SED
child addresses is removed from new parent node ensuring we would not
have a routing loop.
----
This is related to issue https://github.com/openthread/openthread/issues/4240.
- The test does indeed fail on current master
- Verified that the test passes with fix from https://github.com/openthread/openthread/pull/4282
=> [toranj] add test-case covering address cache entry removal on SED attach

third_party/mbedtls/Makefile.am
third_party/mbedtls/ecp.c was excluded for mg12 and mg21.
=> [efr32] fix COAPS switch build error on mg12 and mg21

src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager_ftd.cpp
This PR contains the following commits:
**[dataset-manager] append SecurityPolicyTlv when present**
This commit updates `DatasetManager::SendSetRequest()` to include the `SecurityPolicyTlv` when it is present in the dataset.
**[dataset-manager] simplify checks in HandleSet** 
This commit simplifies the `VerifyOrExit()`/`ExitNow()` failure checks in `DatasetManager::HandleSet()` by starting the `state` as `kReject` and setting to `kAccept` after all checks are passed.
**[dataset-manager] check the read length from message on reading TLVs**
=> [dataset-manager] append SecPolicyTlv when present, simplify checks, check len on read

include/openthread/commissioner.h, src/core/api/commissioner_api.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/commissioner.hpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base.hpp, src/ncp/ncp_base_ftd.cpp, src/ncp/spinel.c, src/ncp/spinel.h, tests/unit/test_pskc.cpp
This PR also contains a smaller change in APIs:
[commissioner] change GeneratePskc to use otPskc/Pskc types (#4294)
----
Related PR in wpantund: https://github.com/openthread/wpantund/pull/443
=> [ncp] add support in spinel/NCP to generate PSKc from pass-phrase 

tools/harness-thci/OpenThread.py
TH's recent updates have side affects on CV tests and caused 5.2.3, 5.5.2 tests to fail. 
The commits try to ...
- add more delay interval to remedy for TH's delay updates
- merge TH's OT THCI update for `updateRouterStatus` 
The reduce in ping delay and joinNetwork delay have caused test 5.5.2 to fail by side affects described in `DEV-2008`. Even though it is a TH validation issue rather than an OT THCI issue, I increased ping & joinNetwork delay so that we have a more stable regression environment. 
**FYI: Both 5.2.3 and 5.5.2 get pass on TH 2.0.0  with this PR applied.**
=> [thci] add delay to joinNetwork and ping

tools/harness-thci/OpenThread.py
This commit enhances FED role configuration by `routerrole`. 
Not raised yet, however previous workaround by configuring `routerupgradethreshold` has risk in some scenario.
=> [thci] update FED role configuration

include/openthread/link.h
This PR clarifies the meaning of MAC counters. This is driven by customer questions.
Also in the future, we should address the problem with the inconsistency for the `mTxErrCca` and `mTxRetry` counters. The meaning of the counters depends on the platform's radio capabilities.
To solve this problem, I believe we should add more fields to `otRadioFrame::mRxInfo` structure, so that whenever OT delegates e.g. CSMA/CA or Retransmission fnction to platform layer, there is a way to communicate e.g. a number of CCA failures or number of retransmissions to the higher layer to collect correct data.
=> [doc] clarify mac counters meaning

examples/platforms/nrf528xx/src/radio.c, examples/platforms/posix/radio.c, examples/platforms/utils/mac_frame.cpp, examples/platforms/utils/mac_frame.h, include/openthread/platform/radio.h, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/mac/sub_mac_callbacks.cpp, src/core/radio/radio.hpp, src/core/radio/radio_callbacks.cpp, src/core/radio/radio_platform.cpp
`otPlatRadioFrameUpdated()` is declared not to access any state within
OpenThread. However the current implementation does read the extended
address. This PR moves AES process into `Mac::TxFrame`, which is free of
`otInstance`, which also eliminates the current deep callback stacks
when the radio driver wants to process tx AES from interrupt context.
=> [radio] process tx AES without otInstance

examples/Makefile-efr32mg12, examples/Makefile-efr32mg21, examples/platforms/efr32mg12/Makefile.platform.am, examples/platforms/efr32mg12/brd4161a/board_config.h, examples/platforms/efr32mg12/brd4166a/board_config.h, examples/platforms/efr32mg12/brd4170a/board_config.h, examples/platforms/efr32mg12/brd4304a/board_config.h, examples/platforms/efr32mg12/platform-band.h, examples/platforms/efr32mg12/radio.c, examples/platforms/efr32mg21/Makefile.am, examples/platforms/efr32mg21/Makefile.platform.am, examples/platforms/efr32mg21/brd4180a/board_config.h, examples/platforms/efr32mg21/platform-band.h, examples/platforms/efr32mg21/radio.c
Changes to radio.c for efr32mg12 and efr32mg21 to support DMP
Added DMP switch to makefiles.  Links with multiprotocol RAIL library when set.
=> [efr32] dynamic multi-protocol support for MG12 and MG21

.travis.yml, .travis/before_install.sh, .travis/script.sh, examples/platforms/cc1352/radio.c, examples/platforms/cc2650/radio.c, examples/platforms/cc2652/radio.c
Also addresses potential unaligned pointer value flagged by Arm GCC 9 in cc1352, cc2650, and cc2652 example drivers.
=> [travis] add arm gcc 9 to build tests

src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit compares data version properly according to the device
mode (whether or not requiring full network data), thus avoiding
unexpected data request when receiving MLE advertisement.
=> [mle] fix unexpected data request

src/core/api/border_router_api.cpp, src/core/api/netdata_api.cpp, src/core/api/server_api.cpp, src/core/net/dhcp6_client.cpp, src/core/net/dhcp6_server.cpp, src/core/thread/mle.cpp, src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_leader.cpp, src/core/utils/slaac_address.cpp, tests/unit/test_network_data.cpp
This PR contains two related commits in `NetworkData`: 
**[network-data] change iterator methods to use reference instead of pointer**
This commit contains t changes the methods in `NetworkData` class used for iterating over on-mesh prefix, external router, etc (e.g.,`GetNextOnMeshPrefix`()) to use reference input variables instead of
pointer type variables.
-----------------
**[network-data] fix how the OnMeshPrefixConfig structs are compared**
This commit ensures the entire struct size is used when comparing two `OnMeshPrefixConfig` (`otBorderRouterConfig`) instances from `NetworkData::ContainsOnMeshPrefixes()` method.
=> [network-data] fix prefix comparison / use reference param instead of pointer (during iter)

.travis.yml
The `posix-app-ncp` test seems to be stable again.
Resolves #3635
=> [travis] enable posix-app-ncp test

examples/platforms/nrf528xx/src/diag.c, examples/platforms/nrf528xx/src/platform-nrf5.h, examples/platforms/nrf528xx/src/radio.c, src/core/diags/factory_diags.cpp
This PR includes two commits:
**[diag] send frames only from the alarm handler in repeat mode**
In the current code base, when `diag repeat X Y` command is executed, we expect to transmit frame in regular intervals. For this purpose the alarm handler is used from which the `Diags::TransmitPacket()` method is executed. However, even in Diag repeat mode, also the `Diags::TransmitDone()` triggers the transmission of the frame via `Diags::TransmitPacket()` method in case of failure. This PR ensures this is not the case in repeat mode.
**[nrf528xx] ensure there is no radio pending events after diag is disabled**
Several times, with our WiFi/BLE coex feature, I was able to get this [assert](https://github.com/openthread/openthread/blob/master/src/core/mac/mac.cpp#L1287).
The root cause for that …
=> [diag] send frames only from the alarm handler in repeat mode

include/openthread/platform/toolchain.h, include/openthread/thread.h
This commit contains two small related commits:
**[thread] remove unnecessary use of OT_TOOL_ALIGN (#4344)**
This commit removes the use of `OT_TOOL_ALIGN` in definitions of `otLinkModeConfig` and `otRouterInfo` structures.
**[toolchain] remove OT_TOOL_ALIGN (#4344)**
@jwhui , I am not sure if we need the `otLinkModeConfig` and `otRouterInfo` to be defined as `OT_TOOL_ALIGN(4)` (history of change shows that these were added during windows API DLL from #882). Do you agree?
=> [toolchain] remove unnecessary OT_TOOL_ALIGN

examples/platforms/efr32mg21/system.c
Fixes interrupt priority asserts when used with FreeRTOS.
=> [efr32] change to MG21 NVIC interrupt PRIGROUP_POSITION

.gn, .travis.yml, .travis/before_install.sh, .travis/check-gn-build, .travis/script.sh, BUILD.gn, third_party/build_gn/BUILDCONFIG.gn, third_party/build_gn/README.md, third_party/build_gn/toolchain/BUILD.gn
The travis script ensures that build of an openthread-core build with gn
and ninja goes through. The run time is about 1 min.
Additional reviewers : @vaas-krish @abtink
=> [build] add a gn based build and corresponding travis script

src/posix/platform/hdlc_interface.cpp, src/posix/platform/hdlc_interface.hpp, src/posix/platform/radio_spinel.hpp
The function "RadioSpinel::IsSafeToHandleNow()" is finally called by the
function "HdlcInterface::Decode()". However, the variable "mIsDecoding"
is set to TRUE before calling "RadioSpinel::IsSafeToHandleNow()" in
function "HdlcInterface::Decode()". So the function "IsDecoding()"
always return TURE in function "RadioSpinel::IsSafeToHandleNow()". This
CL removes the function "IsDecoding()" to make the logic of the code easier.
=> [posix-app] remove function "HdlcInterface::IsDecoding()"

src/core/meshcop/joiner.cpp
This commit changes the `Joiner::HandleJoinerEntrust` implementation
to store Thread network configuration parmaeters in the Active
Operational Dataset. Using the operational dataset stores
configuration parameters in non-volatile memory.
This commit only utilizes Thread network parameters that are useful in
the Thread attach process. For example, parameters such as Extended
PAN ID, Mesh Local Prefix, and Active Timestamp are not useful during
the attach process.
=> [joiner] store network configuration using operational dataset

examples/platforms/nrf528xx/src/radio.c
Issue #4347 fix.
* sExtAddress defined if OPENTHREAD_CONFIG_MAC_HEADER_IE_SUPPORT == 1.
=> [nrf528xx] fix unused sExtAddress when OPENTHREAD_CONFIG_MAC_HEADER_IE_SUPPORT=0

src/core/common/debug.hpp
This prevent build error if the platform drivers have already defined
the assert macro.
=> [debug] override any existing assert definitions

examples/platforms/nrf528xx/nrf52811/openthread-core-nrf52811-config.h, examples/platforms/nrf528xx/nrf52833/openthread-core-nrf52833-config.h, examples/platforms/nrf528xx/nrf52840/openthread-core-nrf52840-config.h
This causes all platforms to have source match both in utils and in platform code - which may lead to erroneous behaviour if the wrong one is included by the linker.
=> [nrf528xx] disable soft source match

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router_ftd.hpp, src/core/thread/mle_router_mtd.hpp
- Ensure there are no side effects if MLE frame counters have not yet
been synchronized.
- Do not remove stale neighbor until end of processing
Advertisement. This allows for complete processing of Advertisement
if frame counters have already been established.
=> [mle] clean up MleRouter::HandleAdvertisement

include/openthread/netdata.h, include/openthread/server.h, src/cli/README.md, src/cli/cli.cpp, src/cli/cli.hpp, src/core/api/netdata_api.cpp, src/core/api/server_api.cpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp, src/core/thread/network_data_local.cpp, src/core/thread/network_data_local.hpp, src/ncp/ncp_base_dispatcher.cpp, src/ncp/ncp_base_mtd.cpp, src/ncp/spinel.h
The thought behind this commit is that Leader should be able to
process service registration by default, like prefix registration.
This commit:
- limit SERVICE to wrap code relative to service provider.
- support service traffic forwarding when SERVICE is disabled (as
a following up update after #4219).
- other minor updates.
=> [network-data] always support service registration at Leader

third_party/NordicSemiconductor/libraries/nrf_security/nrf_cc310_plat/src/nrf_cc310_platform_mutex_freertos.c
* Fixed bad mutex casting in nrf_cc310_platform_mutex_freertos.c file.
=> [nrf528xx] fix freertos mutex casting

src/core/mac/mac.cpp, src/core/mac/mac.hpp
This PR contains two small enhancements/changes in `Mac` class:
- [mac] scope timeIeOffset variable to code block where it is being used
- [mac] remove unused method definition
=> [mac] scope timeIeOffset variable to code block where it is being used
