examples/platforms/nrf52811/diag.c
examples/platforms/nrf52840/diag.c
examples/platforms/utils/code_utils.h
src/diag/diag_process.cpp

nordic ot-cli-ftd hex: 38874 -> 3886c

[diag] use OT_ARRAY_LENGTH to unify code and shrink image size

---

.travis.yml
.travis/check-posix-app-pty
examples/platforms/posix/radio.c
src/posix/platform/hdlc_interface.cpp
src/posix/platform/netif.cpp
src/posix/platform/radio_spinel.cpp

This PR fixes conversion warnings and also adjust one travis test to
check these kind of issues.

[posix-app] fix conversion warnings

---

examples/platforms/efr32/uart.c

Previously, efr32 USART receive worked with only 1 byte at a time.

[efr32] take advantage of DMA for efr32 USART receive

---

.travis.yml
.travis/after_success.sh
configure.ac

This PR adds support for clang code coverage

[travis] support clang code coverage

---

examples/platforms/nrf52840/README.md

.. and add a note about USB CDC ACM on Engineering sample A.

[nrf52840] update README.md after SDK release

---

src/posix/platform/radio_spinel.cpp
src/posix/platform/radio_spinel.hpp

[posix-app] timeout for rcp radio driver

---

examples/platforms/gp712/alarm_qorvo.h
examples/platforms/gp712/platform_qorvo.h

Fix some outstanding build issues in the gp712 build

[gp712] add include <stdbool.h> to resolve build issues

---

src/core/common/notifier.cpp

-----------
Fixes https://github.com/openthread/openthread/issues/3808

[notifier] fix the #if check testing LOG_CORE being enabled

---

include/openthread/channel_manager.h
include/openthread/instance.h
include/openthread/ip6.h
include/openthread/link.h
include/openthread/platform/debug_uart.h
include/openthread/thread.h
include/openthread/thread_ftd.h

Inlined `@sa` commands should not be used. See [example](https://openthread.io/reference/group/api-channel-manager.html#otchannelmanagerrequestchannelselect).

[docs] fix see also in doxygen

---

examples/platforms/nrf52811/radio.c
examples/platforms/nrf52840/radio.c

[nrf52xx] notify if ACK was sent with frame pending bit set

---

include/openthread/network_time.h
src/cli/cli.cpp
src/core/api/network_time_api.cpp
src/ncp/ncp_base_mtd.cpp

[time-sync] remove reference operator in C API

---

src/core/net/ip6.cpp

Protect against buffer overflow.

[mpl] add extra validation when removing MPL Option

---

src/cli/README.md
src/cli/README_COAPS.md
src/cli/cli.cpp
src/cli/cli.hpp
src/cli/cli_coap.cpp
src/cli/cli_coap_secure.cpp
src/cli/cli_udp.cpp

[cli] clean up IPv6 address printing

---

examples/drivers/windows/include/otLwfIoctl.h
examples/drivers/windows/otApi/otApi.cpp
examples/drivers/windows/otLwf/iocontrol.c
examples/drivers/windows/otLwf/iocontrol.h
include/openthread/thread.h
src/cli/README.md
src/cli/cli.cpp

I have added "thread" sub-prefix but can remove it as well.

[cli] extend ipaddr command

---

Android.mk

@bukepo In order to call related API.

[android] add random_crypto_api.cpp to Android.mk

---

src/core/meshcop/dataset_manager_ftd.cpp

This commit changes the `ActiveDataset::CreateNewNetwork()` to select
a random channel from the preferred channel mask if it is not empty,
otherwise a random channel from the supported mask is picked.

[dataset] choose a preferred channel when forming new dataset

---

tests/scripts/thread-cert/node.py

[tests] change string concatenation format in python scripts

---

.travis.yml
.travis/before_install.sh
.travis/script.sh
src/core/thread/mle_tlvs.hpp
src/ncp/spinel.c
tools/spi-hdlc-adapter/spi-hdlc-adapter.c

Also resolve warnings when using clang static analyzer v7.

[travis] set default build env to xenial

---

examples/platforms/nrf52840/README.md

This PR updates README.md and also fixes #3981

[nrf52840] update documentation and fix broken link

---

examples/platforms/posix/flash.c
src/posix/platform/hdlc_interface.cpp
src/posix/platform/logging.c
src/posix/platform/misc.c
src/posix/platform/netif.cpp
src/posix/platform/platform-posix.h
src/posix/platform/settings.cpp
src/posix/platform/sim.c
src/posix/platform/uart.c
src/posix/platform/udp.cpp
tools/spi-hdlc-adapter/spi-hdlc-adapter.c

This PR adds the *_CLOEXEC flags when open files, this ensures these
files are closed when spawning new processes.
This PR also changes the log facility to LOG_DAEMON.

[posix-app] close files on exec and change log facility

---

tests/toranj/test-001-get-set.py

depends on https://github.com/openthread/wpantund/pull/426

[toranj] add partition id set/get to test-001-get-set

---

src/diag/README.md
src/diag/diag_process.cpp
src/diag/diag_process.hpp
tests/scripts/thread-cert/test_diag.py

Added diagnostic statistic clearing.
Improved tx power setting.
Provide RSSI of the last received packet.

[diag] diagnostic module improvements

---

tools/harness-thci/OpenThread.py
tools/harness-thci/OpenThread_WpanCtl.py

nit...
I was curious if #4028 didn't introduce regression with THCI. I found that `panid` command is executed in the THCI file, however the method itself is unused (ITHCI - Thread Harness v49.3).

[thci] remove unused methods

---

src/core/config/openthread-core-default-config.h

[config] set message buffer size based on CPU word length

---

examples/apps/cli/README.md
examples/platforms/efr32mg12/README.md
examples/platforms/kw41z/README.md
examples/platforms/nrf52811/README.md
examples/platforms/nrf52840/README.md
examples/platforms/samr21/README.md
include/openthread/dataset.h
src/cli/README_DATASET.md
src/core/api/thread_api.cpp
src/core/thread/mle.cpp

[dataset] only master key is needed to attach

---

CONTRIBUTING.md

Missed these instances in #3878.

[docs] remove AppVeyor from CONTRIBUTING.md

---

examples/platforms/efr32mg12/radio.c
examples/platforms/efr32mg21/openthread-core-efr32-config.h
examples/platforms/efr32mg21/radio.c
third_party/silabs/Makefile.am

Fix for assert in otPlatRadioTransmit on efr32 platforms (#3768).

[efr32] fix assert triggered in otPlatRadioTransmit (#3768)

---

src/core/meshcop/border_agent.cpp

This PR fix the bug that border agent doesn't create error response with correct error code.

[border-agent] send error responses with correct error code

---

src/core/diags/factory_diags.cpp
src/ncp/ncp_base.cpp

The command is the string of index 0.

[diag] fix processing platform command

---

examples/platforms/posix/radio.c
include/openthread/thread_ftd.h
src/cli/cli.cpp
src/core/api/thread_ftd_api.cpp
src/core/common/message.cpp
src/core/common/message.hpp
src/core/thread/child_table.cpp
src/core/thread/child_table.hpp
src/core/thread/indirect_sender.cpp
src/core/thread/mle_router.cpp
src/core/thread/mle_router_ftd.hpp
src/core/thread/network_diagnostic.cpp
src/core/thread/network_diagnostic_tlvs.hpp
src/core/utils/child_supervision.cpp
src/ncp/ncp_base_ftd.cpp
tests/unit/test_child_table.cpp

[child-table] add support for more than 64 children

---

configure.ac
examples/platforms/efr32mg12/radio.c
examples/platforms/efr32mg21/alarm.c
examples/platforms/efr32mg21/platform-band.h
examples/platforms/efr32mg21/platform-efr32.h
examples/platforms/efr32mg21/radio.c
examples/platforms/efr32mg21/rail_config.h
examples/platforms/efr32mg21/sleepy-demo/Makefile.am
examples/platforms/efr32mg21/sleepy-demo/README.md
examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-ftd/Makefile.am
examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-ftd/main.c
examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-mtd/Makefile.am
examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-mtd/main.c
examples/platforms/efr32mg21/system.c

Sleepy Demo added to the efr32mg21 directory.
Updated efr32mg21 alarm.c to use changes for efr32mg12 in commit 89dca589.

[efr32] add sleepy demo for efr32mg21

---

src/core/thread/mle_router.cpp

The test case 8.2.1 in thread certification is likely to fail with SiLab DUT JR on OT TB. The OT joiner might fail in the DTLS handshake process after it resend the `ClientHello(with cookie)` for multiple times. We found that the OT Commissioner lost its route to neighbor JR and failed to send `Server Hello, Server Key Exchange, Server Hello Done` in these failed test cases. 
OT Commissioner lost its route because it have received `MLE advertisement` from JR and updated its route accordingly. However, the link between Commissioner and JR is not restored fast enough which can cause messages to be dropped. 
This PR resets the `MLE advertisement` when the link cost to a neighbor is changed to or from infinite, so that link between Commissioner and JR is restored ASAP. Together with [PR …

[mle] reset MLE adv timer when cost changes to/from infinite

---

src/core/api/thread_api.cpp
src/core/meshcop/dataset.cpp
src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager_ftd.cpp
src/core/meshcop/meshcop_tlvs.hpp
src/core/thread/key_manager.cpp
src/core/thread/key_manager.hpp

The `MasterKey` class mainly provides overloads of operators `==`
and `!=` which help simplfy the code comparing keys.

[key-manager] add MasterKey class (wrapper over otMasterKey)

---

script/make-pretty

This PR aads a script to make source pretty in a temporary directory.

[script] add a script to make source pretty

---

src/core/meshcop/joiner_router.cpp

This commit add IsBound() check in HandleStateChange before bound.

[meshcop] add IsBound check in JoinerRouter::HandleStateChanged

---

include/openthread/error.h
include/openthread/random_crypto.h
include/openthread/random_noncrypto.h

For the openthread.io reference pages:
- Add the Heap API
- Split the Random API into Crypto and Non-Crypto versions

[docs] update Doxygen groupings for new APIs

---

src/core/thread/network_data.hpp

As specified by Thread Conformance Specification.

[network-data] set max length to 254

---

include/openthread/commissioner.h
src/core/api/commissioner_api.cpp
src/core/meshcop/commissioner.cpp
src/core/meshcop/commissioner.hpp

This commit add GetNExtJoinerInfo() function to get joiner information
by iterator.

[commissioner] add GetNextJoinerInfo() function

---

AUTHORS
examples/platforms/efr32mg12/brd4161a/board_config.h
examples/platforms/efr32mg12/brd4166a/board_config.h
examples/platforms/efr32mg12/brd4170a/board_config.h
examples/platforms/efr32mg12/brd4304a/board_config.h
examples/platforms/efr32mg12/platform-band.h
examples/platforms/efr32mg12/radio.c
examples/platforms/efr32mg21/brd4180a/board_config.h
examples/platforms/efr32mg21/platform-band.h
examples/platforms/efr32mg21/radio.c

Debug counters added in radio.c for mg12 and mg21.

[efr32] add radio.c debug counters for efr32mg12 and efr32mg21

---

examples/platforms/posix/radio.c
examples/platforms/utils/Makefile.am
examples/platforms/utils/mac_frame.cpp
examples/platforms/utils/mac_frame.h
src/core/mac/mac_frame.hpp

This PR exposes several API for radio driver writers to manipulate MAC
frames.

[examples] provide APIs to manipulate 802.15.4 frames

---

tests/unit/test_child.cpp

---
Addresses https://github.com/openthread/openthread/issues/4245

[tests] update test_child to use Clear() instead of memset

---

tests/fuzz/fuzzer_platform.c

[fuzz] add stub for CCA ED radio APIs

---

examples/platforms/nrf528xx/Makefile.am

This PR fixes the problem reported in: #4271

[nrf528xx] add wildcards to PRETTY_FILES list for nrf528xx sources

---

src/core/common/notifier.hpp
src/core/mac/mac.cpp
src/core/thread/key_manager.cpp
src/core/thread/mle.cpp

This commit adds a new `Notifier::Update()` method which performs a
commonly used pattern in the code where a variable is updated with a
new given value and if the variable value does change a related
notifier `OT_CHANGED_<NAME>` is signaled.

[notifier] add Update method

---

src/posix/platform/radio_spinel.cpp

[posix-app] fix implementation of CCA ED threshold config

---

configure.ac

[configure] use "no" instead of "none" in AC_ARG_WITH

---

examples/platforms/cc2538/radio.c

The commits set `frame pending` correctly for cc2538 platform. 
When source match is enabled, `readFrame` reads the `SRC_MATCH_FOUND` flag from the register `RFCORE_SFR_RFIRQF0`. 
The `SRC_MATCH_FOUND` flag will be set whenever there is a message received and ACKed with FP=1 before `readFrame` is called. It is therefore read and cleared in `readFrame`. 
This is one of TODOs of PR #3785 .
**This RP conflicts with PR #4291 on `examples/platforms/cc2538/radio.c`**

[cc2538] set frame pending correctly

---

tools/harness-automation/autothreadharness/runner.py

Save failure times for each case for judging if case passes randomly.

[harness-automation] save case failure times

---

src/cli/README.md
src/cli/cli.cpp

MAC/MLE counters can be cleared with:
>counters mac reset
>counters mle reset

[cli] mac/mle counters reset

---

third_party/NordicSemiconductor/drivers/radio/platform/clock/nrf_802154_clock_ot.c

C file should end with a newline.

[nrf528xx] add newline at the end of file

---

Android.mk

This PR enhances the Android.mk to be more extensible.

[android] make Android.mk more extensible

---

examples/platforms/utils/settings_ram.c

[examples] add stub for otPlatSettingsDeinit to settings_ram.c

---

tests/scripts/thread-cert/Cert_9_2_02_MGMTCommissionerSet.py
tests/scripts/thread-cert/Makefile.am
tests/scripts/thread-cert/message.py
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/test_ipv6_source_selection.py

travis fail is expected before #4377 gets merged
verified pass with #4377 locally.

 [tests] add ipv6 source selection test

---

src/posix/main.c
src/posix/platform/hdlc_interface.cpp
src/posix/platform/hdlc_interface.hpp
src/posix/platform/openthread-system.h
src/posix/platform/platform-posix.h
src/posix/platform/radio_spinel.cpp
src/posix/platform/radio_spinel.hpp
src/posix/platform/system.c

This commit parses all parameters to a structure and puts all parameters parsing code in the function `ParseArg()`. It makes us easier to add new parameters to posix host.

[posix-host] parse all parameters to a structure

---

include/openthread/dns.h
src/cli/cli.cpp
src/cli/cli.hpp
src/core/net/dns_client.cpp
src/core/net/dns_client.hpp

- Also change CLI implementation to avoid reference binding to null pointer.

[dns-client] add const to address pointer

---

src/core/thread/mle_router.cpp

[mle] allow setting router eligible attr to false for MTD

---

examples/Makefile-efr32mg12
examples/Makefile-efr32mg21
examples/platforms/efr32mg12/Makefile.am
examples/platforms/efr32mg12/Makefile.platform.am
examples/platforms/efr32mg12/README.md
examples/platforms/efr32mg12/alarm.c
examples/platforms/efr32mg12/fem-control.c
examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/Makefile.am
examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/main.c
examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/Makefile.am
examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/main.c
examples/platforms/efr32mg12/system.c
examples/platforms/efr32mg21/Makefile.am
examples/platforms/efr32mg21/Makefile.platform.am
examples/platforms/efr32mg21/README.md
examples/platforms/efr32mg21/alarm.c
examples/platforms/efr32mg21/fem-control.c
examples/platforms/efr32mg21/radio.c
examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-ftd/Makefile.am
examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-ftd/main.c
examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-mtd/Makefile.am
examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-mtd/main.c
examples/platforms/efr32mg21/system.c
third_party/silabs/Makefile.am

Updated makefiles for v2.7 SDK
Replaced RAIL timers with sleeptimers.

[efr32] update to Silicon Labs SDK v2.7

---

tools/harness-sniffer/OT_Sniffer.py
tools/harness-sniffer/README.md

Run Test Harness with OT sniffer

[harness-sniffer] add OT sniffer support in Thread Test Harness

---

.travis/check-posix-app-pty
src/posix/client.c

ot-ctl will now send the command line arguments to ot-daemon and print
the reply.

[posix-host] add command mode for ot-ctl

---

examples/platforms/nrf528xx/Makefile.am
examples/platforms/nrf528xx/src/platform-softdevice.h
examples/platforms/nrf528xx/src/softdevice.h

This PR enhances the Makefile.am of nrf528xx to support make pretty out
of the source directory.

[nrf528xx] support pretty out of source directory

---

Android.mk
include/openthread-config-android.h

This enables other repositories to link against these libraries.

[android] build CLI and NCP libraries

---

.travis.yml
.travis/check-android-build
Android.mk
src/posix/platform/netif.cpp

* Add build ot-ctl
* Enable platform netif and platform UDP.

[android] build ot-ctl on Android.mk

---

tests/unit/test_lowpan.hpp

[test] fix check error, cast non-trivial class pointer to void *

---

src/posix/client.cpp

[posix-host] ot-cli: handle write() return values

---

script/make-pretty

Reformating cpp
```bash
./script/make-pretty clang
```
Reformating python
```bash
./script/make-pretty python
```

[script] make pretty python or clang

---

tests/scripts/thread-cert/node.py

This PR enhances the way to match patterns during tests, so that it can
also support with readline enabled.

[tests] enhance matching pattern

---

etc/cmake/options.cmake

Signed-off-by: Markus Becker <markus.becker@tridonic.com>

[cmake] allow configuration of NCP defines

---

tests/toranj/test-013-off-mesh-route-traffic.py

This commit changes the test to wait till network data is updated
on all nodes and they all see all the added off-mesh routes (instead
of waiting for fixed 0.5 seconds).

[toranj] make test-13-off-mesh-route more robust

---

src/core/mac/mac.cpp
src/core/meshcop/commissioner.cpp
src/core/meshcop/joiner_router.cpp
src/core/meshcop/joiner_router.hpp
src/core/thread/key_manager.cpp
src/core/thread/key_manager.hpp

This commit adds a class `Kek` in `KeyManager` representing a Key Encryption Key.

[key-manager] add Kek class

---

tests/scripts/thread-cert/net_crypto.py

[tests] fix logic error in net_crypto.py

---

src/core/thread/mle.cpp
src/core/thread/mle.hpp

This PR contains two small related commits. Kept them seperate to make it easier to read/review (but would suggest to squash for merge).
- Define `Metadata` (for delaying MLE responses) as innter type of `Mle` class
- Simplify `Header` class methods (move `enum` definitions to top of `class`).

[mle] define Metadata (for delaying response) as inner type of Mle class

---

examples/platforms/nrf528xx/src/radio.c
include/openthread/platform/radio.h
src/core/mac/sub_mac.cpp

Proposed fix to https://github.com/openthread/openthread/issues/4689

[mac] add capability to transition from Sleep to Transmit during data request

---

CONTRIBUTING.md
STYLE_GUIDE.md
script/clang-format
script/clang-format-check
script/make-pretty

- Also update CONTRIBUTING.md and STYLE_GUIDE.md.

[script] update pretty script to bash

---

src/posix/platform/netif.cpp
src/posix/platform/platform-posix.h
src/posix/platform/system.cpp

Close netif file descriptors to re-open after reset.

[posix] add platformNetifDeinit

---

.github/workflows/build.yml
script/check-arm-build
script/check-arm-build-autotools
script/check-arm-build-cmake
script/check-scan-build
script/check-simulation-build
script/check-simulation-build-autotools
script/check-simulation-build-cmake

GitHub Actions offers many more parallel build jobs than Travis CI.
Also cleaned up scripts in the transition.
This should reduce the check time to around 30 minutes.

[continuous-integration] initial migration to GitHub actions

---

src/posix/platform/hdlc_interface.cpp
src/posix/platform/hdlc_interface.hpp
src/posix/platform/radio_spinel.cpp
src/posix/platform/radio_spinel.hpp
src/posix/platform/spi_interface.cpp
src/posix/platform/spi_interface.hpp
src/posix/platform/spinel_interface.hpp

This commit mainly renames namespace PosixApp to Posix.

[posix] rename namespace to posix

---

examples/platforms/nrf528xx/nrf52811/platform-config.h
examples/platforms/nrf528xx/nrf52833/platform-config.h
examples/platforms/nrf528xx/nrf52840/platform-config.h
examples/platforms/nrf528xx/src/flash.c
examples/platforms/nrf528xx/src/flash_nosd.c
examples/platforms/nrf528xx/src/flash_sd.c
examples/platforms/nrf528xx/src/platform-nrf5.h

[nrf528xx] align flash driver to the new otPlatFlash* API

---

.travis/test_multicast_join.py
script/check-posix-pty
src/posix/platform/netif.cpp

Listen for mld reports sent by kernel to capture user multicast group
join and forward the addresses to OpenThread interface.
See https://github.com/openthread/wpantund/pull/444 for more background.

[posix] add support for multicast group join

---

include/openthread/netdiag.h
src/cli/cli.cpp
src/core/thread/network_diagnostic.cpp

[network-diagnostic] replace anonymous structs in netdiag.h

---

.github/workflows/build.yml

This PR compacts the `Build` github workfow by using matrix.

[github-actions] use matrix for gcc builds

---

src/posix/platform/misc.cpp
src/posix/platform/netif.cpp
src/posix/platform/platform-posix.h
src/posix/platform/uart.cpp
src/posix/platform/udp.cpp
src/posix/platform/virtual_time.cpp

Resolves https://github.com/openthread/openthread/issues/4770

[posix] open netif fds with O_NONBLOCK in a compatible way

---

src/core/meshcop/joiner.cpp

[joiner] fix code coverage typo

---

src/cli/README_COMMISSIONING.md

[cli] add `factoryreset` for Joiner in README_COMMISSIONING.md

---

script/test

Example:
```bash
OT_OPTIONS="-DOT_FULL_LOGS=ON -DOT_LOG_LEVEL_DYNAMIC=OFF" ./script/test clean build
```

[test] allow extra options

---

examples/platforms/cc1352/radio.c
examples/platforms/cc2538/radio.c
examples/platforms/cc2650/radio.c
examples/platforms/cc2652/radio.c
examples/platforms/gp712/radio.c
examples/platforms/gp712/radio_qorvo.h
examples/platforms/jn5189/radio.c
examples/platforms/kw41z/radio.c
examples/platforms/nrf528xx/src/radio.c
examples/platforms/qpg6095/radio.c
examples/platforms/qpg6095/radio_qorvo.h
examples/platforms/samr21/radio.c
src/core/api/link_raw_api.cpp
src/lib/spinel/radio_spinel.hpp
src/lib/spinel/radio_spinel_impl.hpp
tests/fuzz/fuzzer_platform.cpp
tests/unit/test_platform.cpp

As identified by @srickardti in #4885.

[style] remove const from uint16_t function/method params

---

script/check-simulation-build-autotools

with or without full logs. 
**This PR can not pass checks before #4848 is merged.**

[tests] add Thread 1.2 all features build test

---

doc/ot_api_doc.h

Added plat-otns and api-backbone-router to the Doxygen menu.  Also aligned all the labels for readability.

[docs] update Doxygen menu for OTNS and BBR

---

script/test

`./script/test build` does not work on macOS without this PR.

[test] fix script/test on macOS

---

.github/workflows/build.yml
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp
src/ncp/ncp_base.cpp
tests/toranj/build.sh
tests/unit/test_aes.cpp
tests/unit/test_link_quality.cpp
tests/unit/test_lowpan.cpp
tests/unit/test_lowpan.hpp
tests/unit/test_netif.cpp
tests/unit/test_string.cpp

---------
Follow up on #4784 adding missing `IgnoreError` in different modules.

[error] add missing IgnoreError

---

examples/platforms/simulation/CMakeLists.txt
examples/platforms/simulation/Makefile.am
examples/platforms/simulation/alarm.c
examples/platforms/simulation/flash.c
examples/platforms/simulation/openthread-core-simulation-config.h
examples/platforms/simulation/radio.c
script/test
src/core/thread/address_resolver.cpp
src/posix/platform/netif.cpp

* change package check build Release

[style] fix unused variables in release build

---

src/posix/platform/udp.cpp

After adding and removing addresses, sendmsg call will return EINVAL for
a short period of time. Return INVALID_STATE to inform callers to try
again later.

[posix] return INVALID_STATE on EINVAL

---

.github/workflows/build.yml
.github/workflows/simulation.yml
src/posix/CMakeLists.txt
src/posix/daemon.cmake
src/posix/standalone.cmake

[cmake] add ncurses dependency

---

src/posix/platform/netif.cpp

first, deal with the C++ crankiness about a structure defined inside another structure,
but make sure we don't get tripped up if the SDK ever changes
second, mac OS should not be using the IN6_IFF_NODAD, as rather than avoiding DAD,
it actually makes addresses remain in the "tentative" state indefinitely

[posix] two fixes for macOS and FreeBSD

---

tests/scripts/thread-cert/command.py
tests/scripts/thread-cert/dtls.py
tests/scripts/thread-cert/message.py
tests/scripts/thread-cert/network_data.py

I found these obvious issues are not revealed by our python pretty checks. 
Should we enhance our python code checks by also using tools like flake8? @bukepo @jwhui

[test] fix python issues in tests

---

.codecov.yml
.github/workflows/simulation.yml
script/check-simulation-build-autotools
script/check-simulation-build-cmake
tests/unit/test_platform.cpp

This PR imports unit tests from OTNS.

[github-actions] add test to verify OTNS works

---

src/posix/platform/platform-posix.h
src/posix/platform/system.cpp
src/posix/platform/virtual_time.cpp
tests/scripts/thread-cert/node.py

This simplify manually running posix virtual time mode when debugging.

[posix] get node id from command line argument

---

.github/workflows/simulation.yml

Add a check to build and run 1_2 using clang.

[continuous-integration] add item to build and run 1_2 using clang

---

src/posix/platform/uart.cpp

On platforms that have SO_NOSIGPIPE, use that to achieve the same result.
On platforms that have neither, emit a compile-time warning -- you may
still receive the signal on those systems.

[posix] some platforms don't support MSG_NOSIGNAL

---

script/bootstrap

This commit installs shfmt in script/bootstrap.

[script] install shfmt

---

script/check-posix-pty
src/posix/client.cpp
src/posix/platform/system.cpp
src/posix/platform/uart.cpp

* set close on exec
* explicitly close socket on reset
* enhance ot-ctl to exit on peer close

[ot-ctl] fix reset in non-interactive mode

---

src/core/thread/mle.cpp

The leader is the authoritative source when propagating active/pending
operational datasets. When the leader reboots, it is possible for the
leader to become out-of-sync. In particular, after the leader resets,
it restores its network data and active/pending operational datasets
using MLE Data Request/Response to retrieve them from a neighboring
device. If the neighboring device has an older active/pending
operational dataset, the leader will retrieve the older datasets and
never attempt to propagate the newer datasets that it may have stored
locally.
This commit makes the following changes:
- The leader does not accept any changes to the active/pending
operational datasets.
- After retrieving the latest network data from a neighboring device
(as part of resynchronizing after reset), the …

[mle] fix bug in leader active/pending dataset synchronization

---

Android.mk
script/check-ncp-rcp-migrate
script/check-posix-pty
src/posix/main.c
src/posix/platform/CMakeLists.txt
src/posix/platform/Makefile.am
src/posix/platform/hdlc_interface.cpp
src/posix/platform/hdlc_interface.hpp
src/posix/platform/include/openthread/openthread-system.h
src/posix/platform/platform-posix.h
src/posix/platform/radio.cpp
src/posix/platform/radio_url.cpp
src/posix/platform/radio_url.hpp
src/posix/platform/spi_interface.cpp
src/posix/platform/spi_interface.hpp
src/posix/platform/system.cpp
tests/scripts/expect/posix-diag-rcp.exp
tests/scripts/expect/posix-max-power-table.exp
tests/scripts/thread-cert/node.py
tests/toranj/wpan.py

Radio url provides a unified interface for users to specify the radio
peripheral device and arguments to the OpenThread core stack.

[posix] add radio url

---

script/check-ncp-rcp-migrate
script/check-posix-pty
src/posix/README.md
src/posix/main.c
src/posix/platform/hdlc_interface.cpp
src/posix/platform/include/openthread/openthread-system.h
src/posix/platform/radio_url.cpp
src/posix/platform/radio_url.hpp
src/posix/platform/system.cpp
tests/scripts/expect/posix-diag-rcp.exp
tests/scripts/expect/posix-max-power-table.exp
tests/scripts/thread-cert/node.py
tests/toranj/wpan.py

* fix max-power-table documentation
* rename `baudrate` to `uart-baudrate`, `arg` to `forkpty-arg`
* update command line enumeration
* update README
* remove trailing argument from node.py

[posix] clean up for radio url

---

examples/platforms/simulation/radio.c

Follow up with #4884
Use the util functions to generate Imm Ack in simulation.

[simulation] use ACK frame generation utils

---

src/posix/Makefile-posix

[posix] fix build daemon mode

---

CMakeLists.txt
examples/apps/cli/CMakeLists.txt
examples/apps/ncp/CMakeLists.txt
examples/platforms/cc1352/CMakeLists.txt
examples/platforms/cc2538/CMakeLists.txt
examples/platforms/cc2650/CMakeLists.txt
examples/platforms/cc2652/CMakeLists.txt
examples/platforms/kw41z/CMakeLists.txt
examples/platforms/qpg6095/CMakeLists.txt
examples/platforms/samr21/CMakeLists.txt
examples/platforms/simulation/CMakeLists.txt
examples/platforms/utils/CMakeLists.txt
src/cli/CMakeLists.txt
src/core/CMakeLists.txt
src/lib/hdlc/CMakeLists.txt
src/lib/platform/CMakeLists.txt
src/lib/spinel/CMakeLists.txt
src/ncp/CMakeLists.txt
src/posix/CMakeLists.txt
src/posix/platform/CMakeLists.txt
third_party/mbedtls/CMakeLists.txt

* add include directories to ot-config
* remove unused OT_PRIVATE_INCLUDES

[cmake] use ot-config to umbrella private includes

---

tests/scripts/expect/cli-ipmaddr.exp
tests/scripts/expect/cli-neighbor.exp

This adds `expect` tests for 3 commands: `ipmaddr`, `neighbor`, `leaderdata`.

[test] add expect tests for ipmaddr, neighbor, leaderdata

---

.clang-format
Android.mk
STYLE_GUIDE.md
configure.ac
tests/fuzz/fuzzer_platform.cpp

[style] advance C++ language standard to C++11

---

examples/platforms/simulation/radio.c
examples/platforms/simulation/system.c
include/openthread/instance.h
include/openthread/link_raw.h
src/core/api/link_raw_api.cpp
src/core/mac/link_raw.cpp
src/core/mac/link_raw.hpp
src/ncp/ncp_base.cpp
src/ncp/ncp_base_radio.cpp
tests/scripts/expect/posix-scan-tx-to-sleep.exp

This fixes openthread/ot-esp32#6.

[link-raw] set receive done callback when enabled

---

src/core/meshcop/commissioner.cpp
src/core/meshcop/commissioner.hpp

This commit includes a group of smaller enhancements in commissioner
module:
It adds `FindBestMatchingJoinerEntry()` which finds the best matching
joiner entry preferring an entry with full Joiner ID match over an
entry accepting any joiner.
`AddJoiner()` is changed to first try to find and update an existing
entry matching the given EUI64 before allocating a new entry. This
change in turn removes the need to call `RemoveJoiner()` from
`AddJoiner()` and the use of `JoinerOpFlag` to skip notifying the
leader of the unnecessary remove.
This commit also simplifies updating of joiner expiration timer,
changes the `SendCommissionerSet()` to be `void` (to avoid
`IgnoreError()`), adopts the use of `Ip6::InterfaceIdentifier` type to
store Joiner IID, and adds method `LogJoinerEntry()` to help …

[commissioner] prefer entry with Joiner ID match over one accepting any

---

.github/workflows/simulation.yml
tests/scripts/expect/_multinode.exp
tests/scripts/expect/cli-mac.exp
tests/scripts/expect/posix-rcp.exp
tests/scripts/expect/posix-scan-tx-to-sleep.exp
tests/scripts/expect/tun-dns-client.exp
tests/scripts/expect/tun-netif.exp
tests/scripts/expect/tun-sntp.exp

Also does some minor enhancements.

[test] add expect tests for sntp, mac, netif, and more

---

src/core/thread/mle_router.cpp

As discussed in https://github.com/openthread/openthread/pull/5106#discussion_r445917163
This commit introduces one extra parent response rule:
REED doesn't respond parent request if there are already
`kMaxRouters` active routers in the Thread network as it's
for sure that Leader will reject its address solicit.

[mle] suppress parent response when >= 32 active routers

---

script/bootstrap

- Indicate that pretty tools are primarily used for code contributions.
- Change to bash.
Resolves #5149

[bootstrap] update bootstrap user messages

---

doc/site/en/guides/thread-primer/ipv6-addressing.md
doc/site/en/guides/thread-primer/node-roles-and-types.md

[devsite] add clarifications to multicast addressing primer

---

src/posix/platform/hdlc_interface.cpp

This commit waits fd to be writable before try writing next time.

[posix] wait for writable before next try

---

.github/workflows/simulation.yml
src/cli/README_COAPS.md
src/cli/cli_coap.cpp
src/cli/cli_coap_secure.cpp
src/cli/cli_coap_secure.hpp
tests/scripts/expect/cli-coap.exp
tests/scripts/expect/cli-coaps.exp
tests/scripts/expect/cli-ping.exp

Also adds command `coaps set` to make it consistent with `coap set`.

[test] add expect tests for coap and coaps

---

examples/platforms/efr32mg12/flash.c
examples/platforms/efr32mg13/flash.c
examples/platforms/efr32mg21/flash.c

Fix compilation issues introduced with PR - https://github.com/openth…read/openthread/pull/5178

[efr32] fix compilation issues efr32*/flash.c

---

script/test

[script] fix unbound variable in macOS

---

include/openthread/backbone_router_ftd.h
include/openthread/instance.h
src/cli/cli.cpp
src/core/api/backbone_router_ftd_api.cpp
src/core/backbone_router/local.cpp
src/core/backbone_router/local.hpp
src/core/thread/mle_types.hpp

This PR makes sure BBR configuration is valid according to Thread Spec. 5.21.3.3.

[bbr] validate BBR configuration

---

examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/main.c
examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/main.c
examples/platforms/efr32mg13/sleepy-demo/sleepy-demo-ftd/main.c
examples/platforms/efr32mg13/sleepy-demo/sleepy-demo-mtd/main.c
examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-ftd/main.c
examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-mtd/main.c

The PR which resulted in the compilation issues is: https://github.com/openthread/openthread/pull/5231

[efr32] fix build errors due to recent change of otUdp APIs

---

Android.mk
CMakeLists.txt
configure.ac
src/core/common/code_utils.hpp
src/lib/CMakeLists.txt
src/lib/url/CMakeLists.txt
src/lib/url/Makefile.am
src/lib/url/url.cpp
src/lib/url/url.hpp
src/posix/Makefile.am
src/posix/platform/CMakeLists.txt
src/posix/platform/Makefile.am
src/posix/platform/hdlc_interface.cpp
src/posix/platform/hdlc_interface.hpp
src/posix/platform/include/openthread/openthread-system.h
src/posix/platform/platform-posix.h
src/posix/platform/radio.cpp
src/posix/platform/radio_url.cpp
src/posix/platform/radio_url.hpp
src/posix/platform/spi_interface.cpp
src/posix/platform/spi_interface.hpp
src/posix/platform/system.cpp

This commit moves the URL parser to `src/lib`. Also includes the following changes:
* Split URL on initialization.
* Make a GetValue() const method.
* Check aLastValue.
* Add some negative tests.

[url] move url to library

---

doc/site/zh-cn/guides/thread-primer/index.md
doc/site/zh-cn/guides/thread-primer/ipv6-addressing.md
doc/site/zh-cn/guides/thread-primer/network-discovery.md
doc/site/zh-cn/guides/thread-primer/node-roles-and-types.md
doc/site/zh-cn/guides/thread-primer/router-selection.md

I have made translations based on English sources, but there may be some style issues (such as `key points` and `notes`).
@Vyrastas

[docs] add Chinese translation for Thread Primer

---

src/core/common/settings.cpp
src/core/common/settings.hpp
src/core/thread/mle_router.cpp

This commit updates `ChildInfoIterator` in `Settings` class to
enable range-based `for` loop.

[settings] enhance Settings::ChildInfoIterator

---

src/core/api/ip6_api.cpp
src/core/coap/coap_message.cpp
src/core/coap/coap_message.hpp
src/core/thread/mle.cpp

Also remove few unncessary uses of `this` pointer.

[core] replace memcpy with assignment

---

src/core/thread/mle.cpp

When the child reboot, only register the mesh local address to avoid possible large Child Update Response which would be fragmented, thus avoiding reattach process.

[mle] `kAppendMeshLocalOnly` for Child Update Request in `Detached` state

---

src/core/common/bit_vector.hpp
src/core/common/message.cpp
src/core/thread/topology.cpp

This PR refactors BitVector to use one method for setting or clearing masks.

[bit-vector] refactor methods

---

src/core/thread/dua_manager.cpp

[dua] fix 1.2 compile issue without DUA flag

---

tests/scripts/thread-cert/Cert_5_8_02_KeyIncrement.py
tests/scripts/thread-cert/Cert_5_8_03_KeyIncrementRollOver.py

[thread-cert] refactor case 5.8.2 and 5.8.3 using pktverify

---

script/make-pretty

This PR enhanced `make-pretty` to only shfmt git files.

[pretty] shfmt only git files

---

include/openthread/platform/radio.h
src/core/mac/mac.cpp
src/core/mac/mac.hpp
src/core/mac/sub_mac.cpp
src/core/mac/sub_mac.hpp
src/core/radio/radio.hpp
src/core/thread/csl_tx_scheduler.cpp
src/core/thread/csl_tx_scheduler.hpp

Mostly renaming 'Csl' to 'CSL', and some other minor changes.

[style] prettier CSL comments and logs

---

examples/platforms/nrf528xx/src/radio.c

To enable CSL, it is necessary to get received Enh-ACK timestamp so that the next sample time could be calculated with this timestamp and CSL phase in CSL IE.

[nrf528xx] add received ACK timestamp info to mRxInfo

---

.github/workflows/posix.yml
.github/workflows/simulation-1.2.yml
.github/workflows/simulation.yml
script/test

This PR uploads thread-cert test results (e.g. pcap, log) as GitHub Action Artifacts which can be helpful for debugging purposes. 
Test log and PCAPs of these workflows are uploaded:
**Note: artifacts are not shown until the whole workflow is completed.**

[github-actions] upload test result artifacts

---

Android.mk
include/openthread/platform/udp.h
src/core/BUILD.gn
src/core/CMakeLists.txt
src/core/Makefile.am
src/core/backbone_router/backbone_tmf.cpp
src/core/backbone_router/backbone_tmf.hpp
src/core/backbone_router/bbr_manager.cpp
src/core/backbone_router/bbr_manager.hpp
src/core/coap/coap.cpp
src/core/coap/coap.hpp
src/core/common/instance.hpp
src/core/common/linked_list.hpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp
src/core/thread/thread_netif.hpp
src/core/thread/tmf.cpp
src/posix/main.c
src/posix/platform/CMakeLists.txt
src/posix/platform/Makefile.am
src/posix/platform/backbone.cpp
src/posix/platform/include/openthread/openthread-system.h
src/posix/platform/platform-posix.h
src/posix/platform/system.cpp
src/posix/platform/udp.cpp

This PR adds the Backbone TMF agent

[tmf] add Backbone TMF agent

---

.gitignore

This PR ignore more files from git:
- C-Lion / IDEA project files
- Python bytecode in \_\_pycache\_\_
- PCAP files

[gitignore] ignore more files

---

src/cli/README.md
src/cli/cli.cpp
tests/scripts/thread-cert/test_reed_address_solicit_rejected.py
tests/scripts/thread-cert/test_service.py

[cli] service and server data as hex-encoded binary values

---

src/posix/client.cpp
src/posix/main.c
src/posix/platform/include/openthread/openthread-system.h
src/posix/platform/misc.cpp
src/posix/platform/uart.cpp
tests/scripts/expect/cli-reset.exp

This PR includes: 
Fixes https://github.com/openthread/ot-br-posix/issues/474

[ot-ctl] auto reconnect session 

---

tests/scripts/thread-cert/Cert_9_2_04_ActiveDataset.py
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/pktverify/layer_fields.py
tests/scripts/thread-cert/pktverify/packet_filter.py
tests/scripts/thread-cert/pktverify/packet_verifier.py
tests/scripts/thread-cert/pktverify/test_info.py
tests/scripts/thread-cert/thread_cert.py

1. add timestamp parse and check
2. add leader aloc parse and check

[thread-cert] refactor case 9.2.4 using pktverify

---

.github/workflows/simulation-1.2.yml
tests/scripts/thread-cert/backbone/bbr_5_11_01.py

[github-actions] fix thread-wireshark missing

---

src/cli/README.md
src/core/backbone_router/bbr_manager.cpp
src/core/backbone_router/bbr_manager.hpp
src/core/coap/coap.cpp
src/core/coap/coap.hpp
src/core/coap/coap_message.hpp
src/core/thread/dua_manager.cpp
src/core/thread/dua_manager.hpp
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/v1_2_test_domain_unicast_address_registration.py

[dua] handle coap error code for DUA.rsp

---

tests/scripts/thread-cert/Cert_9_2_04_ActiveDataset.py

extend the mgmt set simulation execution and waiting time for potential miss-catching packets

[thread-cert] enhance case 9.2.4 for potential packets miss-catching

---

tests/scripts/thread-cert/Cert_9_2_18_RollBackActiveTimestamp.py

copy the pkt to verify Step 13 and Step 14 SED packets since the packets could be in front of the packet in Step 12

[thread-cert] enhance case 9.2.18 for SED packet order

---

.github/workflows/simulation.yml

Add `apt-get update` before `apt-get install`.

[github-actions] fix expect check

---

script/bootstrap

[script] fix arm-gcc toolchain install on ubuntu

---

include/openthread/instance.h
include/openthread/ip6.h
src/core/net/netif.cpp
src/core/net/netif.hpp
src/posix/platform/netif.cpp

* no DAD for anycast address.
* add anycast address as non-preferred address.
* update address callback to provide more address info.

[posix] map address with rtnetlink API on Linux

---

src/core/thread/indirect_sender.cpp
src/core/thread/indirect_sender.hpp

----
This is altenate fix from https://github.com/openthread/openthread/pull/5630.
Thanks to @bukepo for finding the root cause. Great job indeed. 👍

[indirect-sender] remove existing supervision msg on new msg add

---

doc/ot_api_doc.h
include/openthread/instance.h
include/openthread/link_metrics.h

- Remove the Platform BLE module
- Add the Link Metrics module

[docs] update Doxygen menu

---

tools/harness-automation/README.rst

update latest supported Test Harness version in README file

[harness-automation] update readme

---

include/openthread/cli.h
include/openthread/instance.h
script/check-posix-pty
src/cli/cli.cpp
src/cli/cli.hpp
src/posix/main.c

This makes using a class method as the cli handler easier.

[cli] add context for the user commands

---

src/core/coap/coap.cpp
src/core/coap/coap.hpp
src/core/coap/coap_message.cpp
src/core/coap/coap_message.hpp
src/core/utils/otns.cpp
src/core/utils/otns.hpp

Used by https://github.com/openthread/ot-ns/pull/107

[otns] emit COAP send/receive events to OTNS

---

examples/platforms/cc2538/alarm.c
examples/platforms/cc2538/cc2538-reg.h
examples/platforms/cc2538/platform-cc2538.h
examples/platforms/cc2538/radio.c

This commit provides a simple energy scan implementation on CC2538 platform.

[cc2538] add energy scan

---

src/core/api/border_router_api.cpp
tests/toranj/test-010-on-mesh-prefix-config-gateway.py

Resolves https://github.com/openthread/ot-br-posix/issues/560
Resolves #5527

[api] check on prefix length when slaac is enabled

---

src/core/net/ip6.cpp
src/posix/platform/netif.cpp
tests/scripts/thread-cert/backbone/test_mle_must_not_send_icmpv6_destination_unreachable.py
tests/scripts/thread-cert/pktverify/consts.py
tests/scripts/thread-cert/pktverify/packet_filter.py

Fixes https://github.com/openthread/ot-br-posix/issues/491

[posix] fix MLE sends ICMPv6 destination unreachable

---

examples/platforms/efr32/src/openthread-core-efr32-config.h

[efr32] disable OT software CSMA backoff and energy scan

---

examples/platforms/efr32/src/misc.c

Closes #5685
CC: @dismirlian @schinchani @wbober

[efr32] use OT_PLAT_RESET_REASON_OTHER for brown-out/EM4 reset

---

examples/platforms/efr32/src/radio.c

[efr32] remove sTxPowerDbm and use RAIL_GetTxPowerDbm()

---

src/posix/platform/udp.cpp

Fixes https://github.com/openthread/ot-br-posix/issues/561.

[posix] fix udp close

---

src/posix/platform/netif.cpp
src/posix/platform/udp.cpp

This fixes the build error by ignoring. Fixes https://github.com/openthread/openthread/issues/5647.

[posix] fix cast-align build error on ARM

---

src/posix/platform/udp.cpp

[posix] default hop limit to OPENTHREAD_CONFIG_IP6_HOP_LIMIT_DEFAULT

---

.github/workflows/build.yml
.github/workflows/simulation-1.2.yml
.github/workflows/simulation.yml
script/test
tests/scripts/expect/_common.exp
tests/scripts/expect/posix-max-power-table.exp
tests/scripts/expect/tun-realm-local-multicast.exp
tests/scripts/expect/v1_2-rcp.exp

This commit adds a test to verify the fix of #5736

[test] verify realm-local multicast on POSIX

---

examples/platforms/efr32/src/entropy.c

[efr32] call mbedtls_hardware_poll directly in otPlatEntropyGet()

---

.github/workflows/build.yml
CONTRIBUTING.md
STYLE_GUIDE.md
script/bootstrap
script/check-scan-build
script/clang-format
script/clang-tidy
src/core/backbone_router/ndproxy_table.hpp
src/core/common/settings.hpp
src/core/thread/topology.hpp

[pretty] downgrade to clang-format/tidy v9.0

---

examples/platforms/nrf528xx/src/flash.c
examples/platforms/nrf528xx/src/transport/spi-slave.c
examples/platforms/nrf528xx/src/transport/usb-cdc-uart.c
script/check-arm-build-autotools
script/check-arm-build-cmake
third_party/NordicSemiconductor/Makefile.am
third_party/NordicSemiconductor/drivers/radio/mac_features/ack_generator/nrf_802154_ack_data.c

`assert()` is not defined when `NDEBUG` is defined.

[style] fix build with NDEBUG

---

src/posix/platform/radio.cpp
src/posix/platform/radio_url.cpp
tests/scripts/expect/posix-fem-lnagain.exp

Fixes <https://github.com/openthread/openthread/issues/5787>.

[posix] add radio URL parameter fem-lnagain

---

script/test

Fixes <https://github.com/openthread/openthread/issues/5753>.

[github-actions] retry coverage uploading on failures

---

examples/platforms/efr32/src/radio.c

Currently, `processNextRxPacket` fills in the received frame's `mRxInfo` only for non-ack packets. When a SED polls its parent, the ACK frame is passed up to the OT core in `efr32RadioProcess`, but the rx info is incorrect (it is actually the rx info for the last received non-ack packet).
OT core uses the RSSI and LQI internally, and for applications that don't transmit/receive data frequenty, the rx info is stale. This PR changes this behavior, so the radio driver populates the rx info also for ACK packets.

[efr32] radio: fill in rx info for received ACKs

---

src/posix/platform/radio.cpp
src/posix/platform/radio_url.cpp
tests/scripts/expect/posix-ccathreshold.exp

Fixes <https://github.com/openthread/ot-br-posix/issues/609>.

[posix] add radio URL parameter cca-threshold

---

tools/harness-thci/OpenThread.py

This PR adds THCI for low power features. I refered to the current 1_2 THCI and update its implementation according to our latest code in OpenThread. I did some local testing.

[thci] add low power thci

---

src/core/thread/dua_manager.cpp
src/core/thread/dua_manager.hpp

Fixes https://github.com/openthread/openthread/issues/5806

[dua] delay DUA registration to avoid transmission failure

---

third_party/ti/README.md
third_party/ti/devices/cc13x2_cc26x2/startup_files/startup_gcc.c
third_party/ti/devices/cc26x0/linker_files/cc26x0f128.lds
third_party/ti/devices/cc26x0/startup_files/startup_gcc.c

Add constructor calls for global C++ objects.
Relates to openthread/ot-br-posix#559

[cc1352,cc26xx] add C++ constructor calls

---

.github/workflows/simulation-1.2.yml
.github/workflows/simulation.yml
.github/workflows/toranj.yml
script/git-tool
script/test

fixes #5896
Depends-On: openthread/ot-ns#112

[github-actions] add dependent PR support

---

.github/workflows/simulation-1.2.yml
.github/workflows/simulation.yml
script/test

This PR adds core dumps uploading for expects tests.

[github-actions] upload core dumps for expects tests

---

src/posix/platform/trel_udp6.cpp

This commit adds explicit error logs messages for the more common
error situation in trel platform implementation under posix, e.g., if
the trel netif cannot be found, or a unicast address cannot be added
to the netif. The new logs provide is included to provide more details
in addition to log message by `VerifyOrDie()` and/or `DieNow()`

[posix] add error logs in trel platform implementation under posix

---

examples/platforms/nrf528xx/src/radio.c
src/core/mac/sub_mac.hpp
src/core/thread/csl_tx_scheduler.cpp
src/core/thread/csl_tx_scheduler.hpp

Small code simplification in CSL part.

[low-power] small improvements in CSL code

---

tests/scripts/thread-cert/Cert_5_7_03_CoapDiagCommands.py
tests/scripts/thread-cert/Makefile.am
tests/scripts/thread-cert/pktverify/consts.py
tests/scripts/thread-cert/pktverify/utils.py

[thread-cert] add case 5.7.3 CoapDiagCommands using pktverify

---

src/posix/platform/backbone.cpp
src/posix/platform/multicast_routing.cpp
src/posix/platform/multicast_routing.hpp

This commit fixes Backbone Router build option compile issues.

[backbone-router] fix build option compile issues

---

src/posix/platform/udp.cpp

[posix] fix build warnings/errors on macOS

---

tests/scripts/thread-cert/Cert_8_1_06_Commissioning.py
tests/scripts/thread-cert/command.py
tests/scripts/thread-cert/mesh_cop.py
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/simulator.py

Add provisionURL set and check
Check all JOIN_ENT & JOIN_FIN

[thread-cert] add case 8.1.6 using pktverify

---

tests/scripts/thread-cert/Cert_9_2_04_ActiveDataset.py
tests/scripts/thread-cert/Cert_9_2_05_ActiveDataset.py
tests/scripts/thread-cert/Cert_9_2_07_DelayTimer.py
tests/scripts/thread-cert/Cert_9_2_08_PersistentDatasets.py
tests/scripts/thread-cert/Cert_9_2_09_PendingPartition.py
tests/scripts/thread-cert/Cert_9_2_17_Orphan.py
tests/scripts/thread-cert/Cert_9_2_18_RollBackActiveTimestamp.py
tests/scripts/thread-cert/Cert_9_2_19_PendingDatasetGet.py
tests/scripts/thread-cert/backbone/test_dua_dad.py
tests/scripts/thread-cert/pktverify/layer_fields.py
tests/scripts/thread-cert/pktverify/test_layer_fields.py

change thread_meshcop channel, net_name and pan_id to type list

[thread-cert] refactor case 9.2.9 using pktverify

---

BUILD.gn
src/lib/spinel/radio_spinel_impl.hpp
src/ncp/BUILD.gn
third_party/mbedtls/BUILD.gn

This change fixes some build issues faced in Fuchsia when trying to update OpenThread repo to latest changes. 
It fixes one issue in mbedtls where it is missing a file in BUILD.gn
Adds BUILD.gn target for src/ncp 
Fixes a warning/error of unused variable.

[gn] changes for fuchsia

---

tests/scripts/thread-cert/Cert_5_1_12_NewRouterNeighborSync.py

[thread-cert] fix case 5.1.12 intermittent failure

---

tests/scripts/thread-cert/Cert_7_1_06_BorderRouterAsLeader.py

[thread-cert] fix case 7.1.6 intermittent failure

---

tests/scripts/thread-cert/Cert_8_3_01_CommissionerPetition.py

[thread-cert] fix case 8.3.1 intermittent failure

---

examples/README.md

https://github.com/openthread/openthread/issues/4038

[doc] add description of common switches

---

src/cli/README.md
src/cli/cli.cpp
tests/scripts/thread-cert/node.py

This commit enhance OT CLI command `router table` to output whether Link Established  in `Link` field.

[cli] router table command to output `Link`

---

tests/scripts/thread-cert/Cert_7_1_05_BorderRouterAsRouter.py

[thread-cert] fix case 7.1.5 intermittent failure

---

examples/platforms/efr32/src/mbedtls_config.h

[efr32] conditional definition for MBEDTLS_SSL_MAX_CONTENT_LEN

---

tests/scripts/thread-cert/v1_2_LowPower_5_3_01_SSEDAttachment.py

[low-power] fix test case Low Power 5_3_01

---

examples/platforms/nrf528xx/nrf52811/platform-config.h

[nrf52811] use RTC1 instead of RTC0

---

src/posix/platform/openthread-core-posix-config.h

[posix] increase message buffer pool to 256

---

tests/scripts/thread-cert/simulator.py
tests/scripts/thread-cert/sniffer_transport.py

Fixes https://github.com/openthread/openthread/issues/5944

[simulation] increase simulator UDP buffer size

---

examples/platforms/nrf528xx/src/radio.c
examples/platforms/utils/Makefile.am
examples/platforms/utils/link_metrics.cpp
examples/platforms/utils/link_metrics.h
examples/platforms/utils/mac_frame.cpp
examples/platforms/utils/mac_frame.h
src/core/thread/link_metrics.cpp
third_party/NordicSemiconductor/drivers/radio/nrf_802154.c
third_party/NordicSemiconductor/drivers/radio/nrf_802154.h
third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.c
third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.h

This PR implements Enhanced-Ack Based Probing on nrf platform.

[nrf52840] implement enh-ack probing

---

src/core/common/random_manager.cpp

[random-manager] fail if unable to seed the CTR DRBG

---

tests/scripts/thread-cert/node.py

We see `self._expect('Done')` in many places, looks like it worthes a dedicated method.

[tests] use dedicated _expect_done method for success commands

---

script/bootstrap

Create links with forced overwrite flag to prevent a failing script if a link already exist.
Fixes https://github.com/openthread/openthread/issues/6093

[bootstrap] overwrite existing links

---

examples/platforms/k32w/src/radio.c
examples/platforms/k32w/src/system.c

- enable 15.4 to work together with BLE
- include an additional configure file

[k32w] Project CHIP fixes

---

src/ncp/ncp_base_mtd.cpp

----
Thanks to RQ (@darconeous) and Jiaming (@jmw-google) for finding this

[ncp-base] fix set hander for 'SPINEL_PROP_MAC_DENYLIST'

---

src/core/net/dns_headers.cpp
src/core/net/dns_headers.hpp
tests/unit/test_dns.cpp

This commit adds new helper methods in `Dns::Name` to parse and
compare a single name label `CompareLabel()` or an entire name
`ComapareName()` from a given message with a given string. Another
flavor of `CompareName()` compares the names read from two different
messages (or same message at different offsets). The name checks are
performed in place (without reading/copying the content from the
messages) and the implementation handles compressed names.
Unit test `test_dns` is updated to verify behavior of newly added
methods.
----
This PR contains the change/commit from https://github.com/openthread/openthread/pull/6101. 
Please review the last commit only. Thanks.

[dns-header] new methods to compare label/name from message

---

src/core/net/dns_headers.cpp
src/core/net/dns_headers.hpp
tests/unit/test_dns.cpp

This commit adds new helper methods in `ResourceRecord` class.
`ParseRecords()` parses and skips over a given number of resource
records in a message. `FindRecord()` searches in a given message to
find the first resource record matching a given record name. And
`ReadRecord<RecordType>()` tries to read a matching resource record
(of a given type) from a message. If the record type does not matches
the type, it skips over the record. This commit also adds methods in
`PtrRecord`, `SrvRecord`, `SigRecord` and `TxtRecord` to parse and
read the data fields such as PTR name, host name, signer name and
TXT data.
This commit updates the DNS unit test to add a detailed new test
constructing and parsing a DNS message (covering the behavior of
the newly added and some of the existing methods).
------ …

[dns-header] helper methods to parse/find/read record(s) in a message

---

src/core/thread/topology.cpp

It seems that moving the if statement out of the loop always brings the same result. So I think we can move it outside the loop.

[child-table] enhance address iterator method

---

src/core/net/dns_headers.cpp
src/core/net/dns_headers.hpp
tests/unit/test_dns.cpp

This commit adds a new template helper method in `ResoureRecord` to
search in a given message starting at a given offset and up to a
maximum given number of records, for the i-th occurrence of a specific
record (of given type) matching a given record name. If found, it reads
the record from the message into a given record object.
The unit test `test_dns` is updated to cover the behavior of newly
added helper method.
----
Quick background for this:
- This PR is on top of the change to `Dns::Name` from #6117, so please check and review the last commit only.
- I noticed that we end up having very similar pattern of code in #6116 (DNS-SD client PR) for parsing of different types and in different situations (e.g., name is from message or from string).
- Now having a flexible `Dns::Name` (which …

[dns-header] new helper method to find i-th record matching name and type

---

examples/platforms/simulation/trel.c

This commit updates the trel simulation platform implementation to
include the src/dst IPv6 addresses and port number (as part of new
simulation-specific packet header) in the exchanged message. It also
verifies the port and dest address (against the expected trel
interface unicast or multicast IPv6 addresses) on the received
message. This helps enhance the simulation platform implementation to
cover the behavior when/if the unicast address used by trel changes.

[trel] update simulation platform to verify port and IPv6 address

---

examples/platforms/nrf528xx/nrf52840/README.md

[nrf52840] update docs to list new cc310/mbedtls libs

---

src/lib/spinel/spinel.h
src/ncp/ncp_base_mtd.cpp

This commit update the spinel domain prefix property with new Nd Dns and Domain Prefix flags.

[spinel] update domain prefix spinel property

---

tools/harness-thci/OpenThread.py

Remove some `pylint` issue and fix `ValidateDeviceFirmware` method.

[harness-thci] remove `pylint` issues from THCI file and small fix

---

script/test

[tests] add OTBR_DUA_ROUTING=ON to OTBR build

---

.github/workflows/size.yml
script/check-size
script/git-tool

This commit fixes #6184
Depends-On: openthread/ot-nrf528xx#5

[git] pull dependency pull requests

---

tests/scripts/thread-cert/border_router/test_advertising_proxy.py
tests/scripts/thread-cert/test_srp_register_single_service.py

Test if we can update the host address.

[tests] test updating SRP host address

---

.github/workflows/simulation-1.2.yml
script/test

This PR updates the OTBR CI test script.
Depends-On: openthread/ot-br-posix#712

[tests] update OTBR CI test script

---

src/core/backbone_router/backbone_tmf.cpp
src/core/backbone_router/bbr_manager.cpp
src/core/common/logging.hpp

This commit refines BBR log level usage using `otLogResultBbr`.

[logging] refine BBR log level 

---

src/core/thread/dua_manager.cpp

This commit fix a potential DUA assertion failure.

[dua] fix assert failure

---

src/lib/spinel/radio_spinel_impl.hpp

This commit changes the `RestoreDatasetFromNcp()` to be performed on
single OT instance config and to be skipped when multiple OT instance
config is enabled. This change ensures that the `RadioSpinel` module
can be compiled with `MULTIPLE_INSTANCE_ENABLE` config. Note that the
"restore data set from NCP" mechanism is performed during platform
initialization from `RadioSpinel::Init()` which happens before
any OT instance is allocated or initialized (all platform layer
components/drivers should be initialized before OT instance). So the
"restore dataset from NCP" feature only makes sense under since OT
instance case.
----
Should help address issue https://github.com/openthread/openthread/issues/6224.

[radio-spinel] perform "RestoreDatasetFromNcp()" with single OT instance config

---

tests/scripts/thread-cert/test_reset.py

[tests] add allowlist after reset to restore same network topology

---

.codecov.yml

Fixes <https://github.com/openthread/openthread/issues/6133>.

[codecov] disable project coverage threshold

---

src/posix/platform/daemon.cpp

This commit adds logs for command line received by daemon which is
helpful debugging daemon issues.

[daemon] log command line

---

.github/workflows/docker.yml

[github-action] remove use of mplatform/mquery in docker build

---

src/posix/client.cpp

Fixes #6377 
Fixes #6376 
Fixes #6355

[ot-ctl] fix ot-ctl hang

---

.github/workflows/posix.yml
.github/workflows/simulation-1.1.yml
script/check-posix-pty
src/posix/platform/daemon.cpp
src/posix/platform/udp.cpp

This commit fixes binding interface on macOS and also build errors on
macOS. The pty check is also added on macOS.
Fixes #6339

[macos] fix binding interface and build

---

tests/scripts/thread-cert/backbone/test_mlr_multicast_routing_across_thread_pans.py

Fixes #6290
See https://github.com/openthread/openthread/issues/6290#issuecomment-811683247 for details.

[scripts] fix multicast routing test false fails

---

.github/workflows/simulation-1.2.yml

[github-actions] add setup for i386 arch

---

Android.mk

Enable ping sender for connectivity verification.

[android] enable ping sender

---

.github/workflows/build.yml
.github/workflows/posix.yml

[github-actions] run `brew update`

---

tests/scripts/thread-cert/node.py

This commit fixes parsing dig TXT RR that contains whitespace.

[scripts] fix dig txt RR parsing

---

script/test

See https://about.codecov.io/security-update/

[codecov] remove use of bash uploader

---

.github/workflows/otbr.yml
.github/workflows/posix.yml
.github/workflows/simulation-1.1.yml
.github/workflows/simulation-1.2.yml
.github/workflows/toranj.yml
script/test

Fixes <https://github.com/openthread/openthread/issues/6460>.

[codecov] use Codecov GitHub Action to upload coverage

---

tools/otci/tests/test_otci.py

[otci] fix test random fails

---

script/check-posix-pty

[github-actions] fix unstable issue of pty-macos

---

.github/workflows/simulation-1.1.yml
.github/workflows/simulation-1.2.yml
tests/scripts/thread-cert/test_ping.py

Packet verification of some test scripts were not executed. This commit runs these tests in packet verification checks.

[github-actions] add more packet verification tests

---

src/posix/cli.cmake
src/posix/daemon.cmake

[posix] update `ot-cli` to include `ot-config` definitions

---

include/openthread/instance.h
include/openthread/thread.h
src/core/api/thread_api.cpp

As [discussed on the openthread-users group ](https://groups.google.com/g/openthread-users/c/-SjEaPcoMGo) a PR to expose API

[api] expose API to obtain service ALOC for given service ID

---

src/core/border_router/router_advertisement.hpp

Thanks to @gabekassel for pointing this out.

[router-advertisement] fix implicit conversion loss

---

src/core/border_router/router_advertisement.cpp
src/core/border_router/router_advertisement.hpp
src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp
tests/scripts/thread-cert/border_router/test_radvd_coexist.py

[border-router] send RA message when RA parameters are updated

---

tests/scripts/thread-cert/node.py

This commit fixes `dig` output TXT parsing.

[tests] fix dig output TXT parsing

---

src/core/backbone_router/bbr_manager.cpp
src/core/thread/dua_manager.cpp

The last commit is to fix the unexpected re-registration behavior in #6538 
There are some other minor nits during issue debugging, submitted together this this fix. May keep separate commits when merge.

[dua] nits and fix unexpected re-registration in #6538

---

.github/workflows/docker.yml
etc/docker/codelab_otsim/Dockerfile
src/posix/platform/platform-posix.h
src/posix/platform/radio.cpp
src/posix/platform/radio.hpp
src/posix/platform/system.cpp

This commit avoid static local variable so that it will not fail to
build on multi-threading environment.
Fixes #6632.

[posix] avoid static local variable

---

Android.mk
src/posix/Makefile.am
src/posix/cli.cmake
src/posix/cli_readline.cpp
src/posix/cli_stdio.cpp
src/posix/daemon.cmake

This commit splits readline and stdio CLI handlers in POSIX app to
better demonstrate how to work with the CLI module.

[posix] split readline and stdio handler

---

.github/workflows/simulation-1.1.yml
.github/workflows/simulation-1.2.yml

To avoid llvm gcov version mismatch.

[github-actions] pin to clang-10 for coverage

---

src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp
tests/scripts/thread-cert/border_router/test_vicarious_router_solicit.py
tests/scripts/thread-cert/node.py

This commit adds vicarious router solicitation which is described in
https://www.ietf.org/archive/id/draft-lemon-stub-networks-02.html#section-3.1.1

[border-router] add vicarious router solicitation

---

src/posix/platform/netif.cpp
src/posix/platform/trel_udp6.cpp

[posix] make all sockets non-blocking

---

src/core/mac/data_poll_handler.cpp
src/ncp/ncp_base_mtd.cpp

We have run the static code analyzer on the OpenThread code and some
issues were discovered.
This commit addresses those that were marked as High impact and were not
marked false positive after the inspection.
Signed-off-by: Marek Porwisz <marek.porwisz@nordicsemi.no>

[static-analysis] address static code analysis issues

---

src/cli/README.md

- Add `-I interface` argument for ping command.
- Update ping examples

[docs] update README for ping command

---

include/openthread/instance.h
include/openthread/udp.h
src/core/api/udp_api.cpp
src/core/net/ip6.cpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp

Enhance frame filtering for UDP messages based on PR #6641.

[udp6] improve frame filtering (based on  #6641)

---

src/core/net/srp_server.cpp
src/core/net/srp_server.hpp

---
It also fixes few small typos in comments.

[srp-server] inline simple getter/setter methods

---

src/core/thread/mesh_forwarder.cpp

Noticed incorrect calculation of PAN ID compression.
Reference: https://mentor.ieee.org/802.15/dcn/15/15-15-0911-01-0mag-proper-pan-id-field-settings-for-802-15-4-2015.docx

[mesh-forwarder] calculate PAN ID compression according to 802.15.4-2015

---

tools/harness-thci/OpenThread.py

[thci] fix THCI issue on Thread Dev Harness 1.1

---

src/core/common/string.cpp
src/core/common/string.hpp
tests/unit/test_string.cpp

This commit adds a new flavor of function `StringFind()` which finds
the first occurrence of a given sub-string within a string. It also
adds `StringEndsWith()` function that works with a sub-string. The
unit test `test_string` is also updated to cover the new behavior of
the newly added function.
----
Background on this PR: The new helper methods will be useful for 
handling of sub-type service name in SRP code.

[string] new `StringFind()/StringEndsWith()` for a sub-string

---

include/openthread/instance.h
include/openthread/platform/radio.h
src/core/diags/README.md
src/core/diags/factory_diags.cpp

Extending checks done by diag send command and diag repeat command
to validate minimal size of frame.

[diags] add minimal IEEE 802.15.4 frame size check

---

src/core/thread/network_data_service.cpp
src/core/thread/network_data_service.hpp

Fixes Leader PBBR priority issue of #6750.

[backbone-router] fix Leader isn't always selected as PBBR

---

tests/scripts/thread-cert/pktverify/packet_verifier.py

Fixes #6312 
See https://github.com/openthread/openthread/issues/6312#issuecomment-868113264 for the cause.

[dua] fix `test_dua_dad` random fails

---

tools/otci/otci/otci.py

[otci] fix wait duration

---

src/core/thread/key_manager.hpp
src/core/thread/mle_router.cpp
src/core/thread/mle_types.hpp

Implement rules mandated by the network Security Policy for REED upgrading to router.

[mle] security policy router upgrading rules

---

src/core/net/dns_client.cpp

This commit updates `AddressResponse::GetNat64Prefix()` to search in
Network Data to find NAT64 prefixes added by BRs. Prefixes with
higher preference are selected first.

[dns-client] use NAT64 prefix from network data

---

src/core/thread/mle_router.cpp

Rules for partitions preference were updated.

[mle] prefer higher weight partition even if singleton

---

src/core/api/tasklet_api.cpp
src/core/common/instance.hpp
src/core/common/tasklet.cpp
src/core/common/tasklet.hpp

This commit also inlines simple constructors.

[tasklet] declare `Scheduler` as nested type of `Tasklet`

---

src/core/border_router/routing_manager.cpp

This commit updates the logs in `RoutingManager` so that the log
messages start with capital letter (making it consistent with other
modules).
------
Background on this:
I was looking at device logs recently and noticed the difference 
in `br` logs vs. other modules. 😃

[routing-manager] update log messages

---

src/posix/platform/netif.cpp

This commit updates the logging in `netif` module under posix platform
code. It adds a prefix `[netif]` to the log line to help distinguish
the logs from this module from other platform layer logs.
It also removes some of the extra logs (e.g., logging `processTx: OK`
or `processRx: OK` on every rx and tx) and only logs failures
(at warning log level).

[posix] update the logging in netif module

---

src/cli/cli_dataset.cpp
src/core/meshcop/dataset.cpp
src/core/meshcop/dataset.hpp
src/core/meshcop/dataset_local.cpp
src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager_ftd.cpp
src/core/meshcop/dataset_updater.cpp
src/core/meshcop/joiner_router.cpp
src/lib/spinel/radio_spinel_impl.hpp

This commit removes the mType field from the Dataset class to save RAM.

[dataset] remove mType from Dataset

---

include/openthread/instance.h
include/openthread/netdata.h

This commit contains no logic/behavior change and only contains
typos/style fixes and documentation updates and simplifications.

[netdata] update/simplify public API documentations

---

tests/scripts/thread-cert/border_router/test_dnssd_server.py
tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py
tests/scripts/thread-cert/node.py

- Removed the verification on the meshcop service's name.
- Added a new test case to verify the meshcop service is published with proper fields. This test case will be extended when https://github.com/openthread/ot-br-posix/issues/736 is fixed. 
Related to: https://github.com/openthread/ot-br-posix/issues/735

[border-agent] update meshcop test cases

---

tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py
tests/scripts/thread-cert/node.py

This PR includes a test case to verify that multiple border routers can publish their meshcop services successfully without instance name conflicts.

[tests] add test to verify name conflict resolution for meshcop service

---

include/openthread/dataset.h
include/openthread/instance.h
src/cli/README_DATASET.md
src/cli/cli_dataset.cpp
src/core/api/dataset_api.cpp
tests/scripts/expect/cli-dataset.exp

Adds an API to parse a dataset from TLVs.

[dataset] add API `otDatasetParseTlvs`

---

src/cli/README_SRP_SERVER.md

Give more informational description about the `srp server state` command.

[docs] update README_SRP_SERVER.md

---

src/core/thread/router_table.cpp

This commit updates `RouterTable` to ensure signalling removal of
neighbor routers when router table is fully cleared or when a
`Router` with a specific released router ID is cleared.
---
- Noticed these cases (where we can remove neighbor routers
without signlaing their removal) during testing of 
https://github.com/openthread/openthread/pull/6947.

[router-table] fix signalling when neighbor routers are removed

---

include/openthread/instance.h
include/openthread/platform/trel-udp6.h
src/cli/README.md
src/cli/cli.cpp
src/cli/cli.hpp
src/posix/platform/trel_udp6.cpp

This commit adds commands to enable or disable TREL radio link:
```
> trel enable
Done
> trel diable
Done
```

[cli-trel] add CLI command to enable/disable TREL

---

include/openthread/instance.h
include/openthread/platform/crypto.h
src/core/crypto/storage.hpp

We have some unused references to get key attribute feature. This PR aims to remove these.

[crypto] remove unused references to get key attributes

---

examples/platforms/simulation/alarm.c

This commit updates and simplifies the `alarm` platform implementation
under simulation by adding new functions to determine whether a timer
is expired and calculate the remaining time. The new code does not
use casting a `uint32_t` value to an `int32_t` (since its behavior is
toolchain/compiler dependent and it is not defined by the C++
standard).

[simulation] update `alarm` to avoid cast from `uint` to `int`

---

src/core/api/logging_api.cpp
src/core/common/instance.cpp
src/core/common/instance.hpp
src/core/thread/mesh_forwarder.cpp

Set mLoggingLevel as static member.

[posix] fix posix logging level

---

.github/workflows/otbr.yml
script/test

This commit runs all Border Router (OTBR) tests with TREL enabled.

[br-tests] enable BR tests with TREL

---

src/posix/platform/trel_udp6.cpp

This commit enhances `TREL UDP6` to retry adding the link-local interface address until it's successful.

[posix-trel] retry adding interface address if failed

---

tests/scripts/thread-cert/border_router/test_advertising_proxy.py

Add steps which verify the bugfix contributed to OTBR: https://github.com/openthread/ot-br-posix/pull/1020
That is, verify that SRP updates which modify both a host and a service can be successfully completed.
Depends-On: openthread/ot-br-posix#1020

[br-tests] add more steps to test_advertising_proxy.py

---

src/cli/cli.cpp
src/cli/cli_history.cpp
src/cli/cli_output.cpp
src/cli/cli_output.hpp
src/cli/cli_srp_client.cpp
src/cli/cli_tcp.cpp

-------
Adding new helper method for outputting `otSockAddr` in `cli_output`.

[cli] add `OutputSockAddr()` method

---

src/core/thread/mle_router.cpp

[dua] assume child does not have DUA if no space to store one

---

tools/harness-thci/OpenThread.py

This commit adds API method setCcmState to THCI file.

[thci] add setCcmState method in thci

---

src/core/common/heap_allocatable.hpp
src/core/net/srp_server.cpp
src/core/net/srp_server.hpp

This commit adds a new static method in `Heap::Allocatable` to
allocate a new object and initialize it using the underlying `Type`
constructor (passing all the parameters to the constructor). This is
in addition to the existing mechanism to use an `Init()` method to
initialize the allocated object. The `Init()` method returns an
`Error` allowing the initialization itself to potentially fail. This
commit also updates `Srp::Server` types `Host` and `UpdateMetadata`
to use the new method.
-----
_Background_:
- The constructor model is useful for some of the new heap
allocated object (used in SRP replication, e.g., 
a sub-class of `Dns::Dso::Connection`).
- I also used the name `Allocate()` instead of `New()` .
- Typically in C++ `new` and `delete` terms are used together,
while C functions …

[heap-allocatable] new method to allocate and init using constructor

---

src/core/common/string.cpp
src/core/common/string.hpp
src/core/mac/mac.cpp
src/core/mac/mac_frame.cpp
src/core/meshcop/joiner.cpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle_router.cpp
src/core/thread/mle_types.cpp
src/core/utils/channel_manager.cpp

----
Adds a simple helper function (used often in logging)

[string] add `ToYesNo()` to convert a boolean to "yes" or "no"

---

tests/scripts/thread-cert/border_router/test_manual_maddress.py
tests/scripts/thread-cert/node.py

Make sure a SBBR handles own multicast traffic routing.

[border-router] add test to verify multicast traffic on a SBBR

---

include/openthread/backbone_router_ftd.h
include/openthread/instance.h

Fix compile errors when including backbone_router_ftd.h in C files.

[bbr] fix bbr header C compliance

---

src/core/thread/mle.cpp

[mle] set ChannelPage value in MLE Announce messages

---

src/core/common/time.hpp
src/core/common/time_ticker.hpp
src/core/common/uptime.cpp
src/core/common/uptime.hpp
src/core/net/ip6.hpp
src/core/utils/history_tracker.cpp
src/core/utils/history_tracker.hpp
src/core/utils/jam_detector.cpp
src/core/utils/jam_detector.hpp

----
Small change to allow us to reuse the same definitions from different modules.

[time] add constants for one sec, minute, hour, or day interval in msec

---

tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/pktverify/consts.py
tests/scripts/thread-cert/pktverify/layer_fields.py
tests/scripts/thread-cert/pktverify/layers.py
tests/scripts/thread-cert/pktverify/packet.py
tests/scripts/thread-cert/pktverify/utils.py
tests/scripts/thread-cert/test_srp_client_change_lease.py

Verified that the test can be fixed by https://github.com/openthread/openthread/pull/7281

[srp-client] add lease changing test

---

tools/harness-thci/OpenThread.py

This commit adds implementation of setVrCheckSkip to THCI file.

[thci] add implementation of setVrCheckSkip in THCI

---

tools/otci/otci/command_handlers.py
tools/otci/otci/connectors.py

This commit fixes OTCI that CLI connection via serial may fail when closing.

[otci] fix read error after close

---

src/cli/cli.cpp

`bbr skipseqnuminc` should complete without error.

[bbr] fix `bbr skipseqnuminc` command response

---

src/core/mac/mac.cpp
src/core/mac/mac.hpp
src/core/mac/sub_mac.cpp
src/core/mac/sub_mac.hpp

This commit contain smaller style changes in `Mac` and `SubMac`.

[mac] smaller style changes

---

src/cli/cli.cpp
src/cli/cli.hpp

This commit also adds `MacFilterAddressModeToString()`.

[cli] add helper method to output an `otMacFilterEntry`

---

src/core/backbone_router/bbr_local.cpp
src/core/backbone_router/bbr_local.hpp
tools/harness-thci/OpenThread.py

"BBR Sequence Number Updating" section in Thread Specification
requires special wraps when increasing BBR Dataset Sequence Number.

[bbr] implement new Sequence Number increase rules

---

src/core/border_router/routing_manager.cpp

This commit enables BR to withdraw its local NAT64 prefix if a smaller one is found in network data.
It might happen when two BRs join the Thread network at merely the same time and thus both advertise its local NAT64 prefix. The BR with numerically greater prefix will withdraw its NAT64 prefix.

[nat64] withdraw greater NAT64 prefix in network data

---

src/core/thread/mle.cpp

This commit eliminates logs of broadcast security check failures
because it can be common to receive such messages from adjacent Thread
networks.

[mle] no failing logs for broadcast security check

---

.github/workflows/otns.yml
.github/workflows/simulation-1.1.yml

This commit runs OTNS stress tests in OpenThread CI.

[github-actions] add OTNS stress tests

---

tools/harness-thci/OpenThread.py

Per https://threadgroup.atlassian.net/browse/DEV-2164

[thci] prefix fix for TH 1.1 border router 7.x.x cases

---

.github/workflows/otns.yml

Also pin ubuntu image to 20.04.

[github-actions] fix branch filter in OTNS workflow

---

tools/otci/otci/connectors.py
tools/otci/otci/otci.py

This commit addresses several small reliability issues revealed during testing.

[otci] address small reliability issues

---

tests/scripts/thread-cert/border_router/test_mdns_restart.py

Depends-On: openthread/ot-br-posix#1221
Please merge after openthread/ot-br-posix#1221 is merged.

[tests] add a test case of mDNS service restarting

---

src/core/meshcop/dataset_manager.cpp
src/core/net/ip6.cpp

This commit fixes issues found during static code analysis.

[ip6] fix static code analysis errors

---

tests/scripts/thread-cert/border_router/test_advertising_proxy.py

Depends-On: openthread/ot-br-posix#1273

[tests] add advertising test case of removing a host

---

src/lib/spinel/radio_spinel_impl.hpp

This commit updates `GetNextTid()` in `RadioSpinel` so that it
searches for the next unused TID. The current implementation only
checked the `mCmdNextTid` and assumed that if it was in-use, then all
other TIDs were also in-use. This may not be valid since a TID may be
in-use for a pending radio tx in `mTxRadioTid` while TIDs after that
are still available.
This should help address the situation where while waiting for a
pending radio tx (holding on to `mTxRadioTid`) 15 other radio API
calls happen (each consuming a TID) causing the `mCmdNextTid` to wrap
around back to `mTxRadioTid`.
Thanks to @dismirlian and @tlifschitz for finding the issue and root-causing it. 👍 
This is related to and should help address issue https://github.com/openthread/openthread/issues/7513.

[radio-spinel] fix `GetNextTid()`

---

src/core/thread/address_resolver.cpp

[logging] fix log level for `LogCacheEntryChange`

---

src/core/thread/mle_router.cpp

This commit contains smaller enhancements in `MleRouter` related to
preparation and handling address solicit request/response:
- Simplify router id allocation logic (if RLOC16 is requested
in the address solicit message).
- Simplify `SendAddressSolicitResponse()` (remove `error`).
- Update logs.
- Remove simple comments.

[mle] simplify sending/processing of address solicit/response

---

src/core/net/srp_server.cpp

This commit adds more error tracing logs to help identify where a
SRP service registration fails. The log format is also updated to
capitalize the first char to align with rest of the codebase.

[srp-server] add more error tracing logs

---

tools/otci/otci/command_handlers.py

This commit enhances OTCI to filter new log formats introduced by #7385 .

[otci] support filter new log formats

---

examples/platforms/simulation/openthread-core-simulation-config.h

required by https://github.com/openthread/ot-ns/pull/260

[simulation] use 128 max children for simulation

---

src/core/thread/mle_router.cpp

The `routerCount` value was being reset to zero with each iteration
over the router table. As a result, the comparisons were only
happening on the first entry in the received Route64 TLV.
Fixes #7612

[mle-router] fix `HasOneNeighborWithComparableConnectivity()`

---

tools/harness-thci/OpenThread.py

Currently the official Thread Harness has support for device capabilities even for Thread 1.1 tests.

[thci] remove support for legacy Harness tool

---

src/cli/README.md
src/cli/cli.cpp
tests/scripts/expect/cli-misc.exp

Also add an expect test for getting/setting mesh-local prefix.

[cli] add command to set mesh-local prefix

---

include/openthread/instance.h
include/openthread/platform/radio.h
src/core/radio/radio.hpp
src/core/radio/radio_platform.cpp
src/core/thread/mle.cpp
src/core/thread/topology.hpp
src/ncp/ncp_base.cpp
src/posix/platform/radio.cpp

Make use of Thread Specification terminology.

[csl] rename to `CslUncertainty`

---

src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp

This commit contains smaller enhancement in `RoutingManager` related
to `ExternalPrefix` class (which represents a prefix discovered from
processing Router Advertisements from infrastructure netif). This
commit also uses `Array::Find()` methods when searching in the
`mDiscoveredPrefixes` array.

[routing-manager] simplify `ExternalPrefix`

---

src/lib/spinel/radio_spinel_impl.hpp
src/posix/platform/radio_url.cpp

This PR adds log to record the region code to help developers know
which region code is currently in use from log.

[log] add region code log

---

src/core/net/srp_client.cpp

Adopt proposal from [SPEC-1071](https://threadgroup.atlassian.net/jira/core/projects/SPEC/issues/SPEC-1071).

[srp-client] prefer the numerically lowest server address

---

tests/scripts/thread-cert/mcast6.py

`mcast6.py` is used by GitHub Actions CI to send or receive UDP messages in multicast groups. 
This commit adds a `-u` argument to allow `mcast6.py` to receive UDP messages without joining a multicast group.

[tests] `mcast6.py` to receive UDP messages without `JOIN_GROUP`

---

src/core/border_router/routing_manager.cpp

This commit updates `InvalidateDiscoveredPrefixes()` to remove
invalidated entries from the array directly. This is done by
replacing the invalidated prefix entry in array with the last entry
in list and popping the last entry. This helps simplify the code and
avoid the need to create a separate copy of the list.
This commit also makes other smaller enhancements in this method:
Tracking the `nextExpireTime` to avoid multiple calls to
`FireAtIfEarlier()` from the same method (avoid re-arranging the full
timer linked-list). Also using a boolean `containsOnLinkPrefix` to
track whether we have seen any on-link prefix in the discovered
prefix list (instead of keeping track of the number of such
entries).

[routing-manager] remove invalidated prefixes from array in place

---

src/core/border_router/routing_manager.cpp

This commit changes `EvaluteOnLinkPrefix()` so that when we decide to
start advertising the local on-link prefix, we go through the list of
discovered prefixes to check if the local prefix was previously discovered
and included in the list, and remove it from the list (without
unpublishing it from Thread Network Data). This change allows us to
simplify `InvalidateDiscoveredPrefixes()` which was earlier called and
was in charge of removing the local prefix.
This helps align the logic that when we are advertising the on-link
prefix, we do not allow it to be added in the discovered prefix list
from `UpdateDiscoveredOnLinkPrefix()`.

[routing-manager] directly remove on-link prefix from list on advert start

---

include/openthread/instance.h
include/openthread/platform/settings.h

[platform] update documentation of otPlatSettings API

---

src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp

This commit introduces `DiscoveredPrefixTable` class as a nested type
in `RoutingManager`. This class maintains the on-link and route
prefixes which are discovered by processing the received Router
Advertisement messages. It manages the lifetime of the discovered
prefixes (running a timer and removing entries when they expire). It
also handles publishing and unpublishing the prefixes in the Thread
Network Data as they are added and removed.
When there is any change in the table (an entry is added, removed,
or modified), it signals this through a callback to `RoutingManager`
which can then take action and decide whether or not to re-evaluate
the routing policy. A `Tasklet` is used for signalling which ensures
that if there are multiple changes within the same flow of execution,
the …

[routing-manager] add `DiscoveredPrefixTable`

---

src/cli/cli_history.cpp

To address a warning on some platform.

[cli] use snprintf instead

---

.github/workflows/build.yml
.github/workflows/posix.yml

[github-actions] update to macos-12

---

src/core/thread/mle_router.cpp

After upgrading to a router, the device will wait until it receives a
Route TLV from a neighboring node indicating that the new Router ID
has been allocated. In normal cases, this is not an issue since the
Leader will disseminate a new Router ID Sequence after allocating a
new Router ID. However, in some scenarios, a device may request the
same Router ID that was previously allocated and significantly delay
establishing links with neighboring routers. With this commit, a
device will immediately send a Link Request if the Router ID was
previously allocated.

[mle] send Link Request immediately if router id was previously allocated

---

tests/unit/test_routing_manager.cpp

This commit updates `test_routing_manager` unit test to validate the
behavior of `RoutingMangaer` related to default route prefix (when AIL
routers advertise default route in RA header or as ::/0 prefix in an
RIO).

[test] update `RoutingManager` unit test to check default-route

---

tools/harness-thci/OpenThread_BR.py

Add SSH keepalive to avoid disconnection after idle for a long time.

[thci] add SSH keepalive

---

tools/harness-simulation/harness/Thread_Harness/THCI/OpenThread_Sim.py

Now It connects to OpenThread FTD simulations via SSH without PTY and runs in non-blocking mode.

[thci] enhance SSH connection

---

src/core/thread/router_table.cpp

This commit updates `RouterTable::Allocate()` to use Reservoir
sampling algorithm to randomly select a router ID while iterating
through the list of available IDs.

[router-table] simplify `Allocate()` and random selection of ID

---

src/core/meshcop/border_agent.cpp

Update border agent logging for filtered messages to debug level to avoid confusion, because it's actually not a error case.

[border-agent] update logging for filtered messages

---

tools/harness-simulation/posix/build_docker_image.sh
tools/harness-simulation/posix/launch_testbed.py

Fix https://github.com/openthread/openthread/issues/8068 that building docker image fails.

[harness-simulation] fix `build_docker_image.sh` error

---

src/posix/platform/infra_if.cpp

[posix] initialize `hints` in `InfraNetif::DiscoverNat64Prefix`

---

.github/workflows/build.yml
.github/workflows/posix.yml
.github/workflows/simulation-1.1.yml
.github/workflows/toranj.yml
tests/toranj/start.sh

Ubuntu 18.04 is deprecated.
https://github.com/actions/runner-images/issues/6002

[github-actions] migrate to ubuntu 20.04 from 18.04

---

src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp

This commit adds a new method `ScheduleRoutingPolicyEvaluation()` in
`RoutingManager` which combines the logic from different related
methods. This helps simplify the code. The new method accepts an enum
`SchduleMode` input which indicates the rule to use when determining
the next policy evaluation time, e.g., schedule it immediately, or
after a random delay, or after short random jitter time to reply to
a received RS, etc.

[routing-manager] add `ScheduleRoutingPolicyEvaluation()`

---

.github/workflows/build.yml
src/core/net/dnssd_server.cpp
src/core/thread/mle.cpp
src/ncp/ncp_hdlc.hpp

[github-actions] add gcc-12 to build matrix and fix warnings

---

src/core/net/srp_server.cpp

This commit updates the `Srp::Server` to log the processed info in a
received SRP Update message, such as host name, lease times, host
addresses, all services (and sub-types) being added or removed. The
info is logged before invoking the "update handler" and/or committing
the info into existing data. This change can help with debugging
issues.
----
Example of logs:
```
00:00:14.383 [I] SrpServer-----: Received DNS update from fdde:ad00:beef:0:c03c:c900:90ff:d4d9
00:00:14.428 [I] SrpServer-----: Processed DNS update info
00:00:14.428 [I] SrpServer-----:     Host:host.default.service.arpa.
00:00:14.428 [I] SrpServer-----:     Lease:7200, key-lease:1209600, ttl:7200
00:00:14.428 [I] SrpServer-----:     1 host address(es):
00:00:14.428 [I] SrpServer-----:       fd00:0:0:0:0:0:0:cafe …
```

[srp-server] log the content of processed SRP update message

---

src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp

This commit adds `RsSender` class in `RoutingManager` which contains
the logic related to the transmission of Router Solicitation
(RS) messages to discover other routers. This class encapsulates all
variables, constants, and methods related to the RS transmission
mechanism(number of RS messages in a cycle, time intervals, etc).
----
~~This PR currently contains the commit from https://github.com/openthread/openthread/pull/8115.~~

[routing-manager] add `RsSender` nested class

---

tools/harness-simulation/README.md
tools/harness-simulation/harness/Web/data/updateDeviceFields.py
tools/harness-simulation/harness/install.bat

This commit automatically updates the device fields in `deviceInputFields.xml`, eliminating the need to update them manually.

[harness-simulation] update `deviceInputFields.xml` automatically

---

.github/workflows/otbr.yml
script/test
tests/scripts/thread-cert/border_router/nat64/test_single_border_router.py
tests/scripts/thread-cert/ipv6.py
tests/scripts/thread-cert/node.py

The test includes:
- Counters (protocol & error (4to6 no mapping, other errors are not expected))
- ICMP ping Connectivity
- UDP connectivity

[nat64] add functional tests

---

src/cli/cli.cpp

---
Thanks to @sarah-iot for finding this.

[cli] fix `log filename` command arg check

---

src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp

This commit renames `LocalOnPreifx` class to `OnLinkPrefixManager` and
moves all the code related to managing of the on-link prefix to this
class, e.g., method `Evaluate()` to evaluate and make a decision
about on-link prefix (whether we need to advertise our local on-link
prefix or there is a favored discovered on-link prefix provided by
another router on infra link).

[routing-manager] add `OnLinkPrefixManager`

---

Android.mk
script/check-android-build

fixes openthread/ot-br-posix#1571

[android] only set -std=c99 for mbedtls

---

src/posix/platform/netif.cpp

cc for review @jwhui @abtink @simonlingoogle

[netif] fix bug in print statement by removing a stray format tag with no corresponding argument

---

src/core/thread/network_diagnostic.cpp
src/core/thread/network_diagnostic_tlvs.hpp

This commit updates some of the `NetworkDiagnostic` TLV definitions to reuse similar MLE TLVs (e.g. `LeaderDataTlv`). It also updates the code to reuse helper methods to parse `Mle::DeviceMode` and `Mle::LeaderData`.

[net-diag] reuse similar MLE TLV definitions

---

tests/unit/test_network_data.cpp

[tests] fix comparison width warning

---

examples/platforms/simulation/diag.c
examples/platforms/simulation/radio.c
include/openthread/instance.h
include/openthread/platform/diag.h
src/core/diags/README.md
src/core/diags/factory_diags.cpp
src/posix/platform/radio.cpp
tests/scripts/expect/cli-diags.exp

This commit adds diag commands for setting the GPIO mode to resolve the conflict https://github.com/openthread/openthread/issues/8362.

[diag] add gpio mode commands

---

src/lib/spinel/radio_spinel_impl.hpp

[spinel] fix `printf` style output

---

tests/unit/test_routing_manager.cpp

This commit updates the `RoutingManager` unit test to check that there are no duplicate PIO/RIO prefixes in the emitted RA message.
It also updates the `TestSavedOnLinkPrefixes()` to check behavior after device resets/restarts while it was advertising its local on-link prefix or deprecating it.

[test] `test_routing_manager` to check duplicate PIO/RIO prefixes

---

tests/scripts/thread-cert/test_srp_lease.py

This PR adds a step in `test_srp_lease.py` to verify that SRP services are removed when their host expires.

[tests] verify that SRP services are removed when their host expires

---

include/openthread/instance.h
include/openthread/platform/diag.h

This commit modifies descriptions of diag gpio functions to better describe returned errors.

[diag] modify gpio diag functions description

---

third_party/tcplp/bsdtcp/tcp_input.c

Fixes #8378.
I believe that the added casts will fix the code scanning alerts, but if it is possible to re-run the code scanning on this pull request to double-check, that would be great.

[tcplp] fix code scanning alerts relating to integer overflow in multipication

---

src/core/net/ip6.cpp

This commit fixes a potential message leak when NAT64 translator feature is enabled in `Ip6::ProcessReceiveCallback()` where a cloned copy of message is not freed if `TranslateFromIp6()` returns an error or if `mReceiveIp4DatagramCallback` is not set.
This commit updates how we track and free the message in this method (to help simplify the code and avoid similar situations). Variable `message` points to the `Message` instance we own in this method. If we can take ownership of `aMessage`, we use it as `message`. Otherwise, we may create a clone of it. `message` will be set to `nullptr` if the message ownership is transferred to an invoked callback. At the end of this method we free `message` if it is not `nullptr` (indicating it was not passed to a callback).
----
More details on possible …

[nat64] fix message leak when NAT64 translator is enabled

---

src/core/thread/mle.cpp

This commit skips creating a local copy of DUA address and directly uses `Get<DuaManager>().GetDomainUnicastAddress()` which will be fully inlined.

[mle] use DUA address directly in `AppendAddressRegistrationTlv()`

---

src/core/thread/router_table.cpp
src/core/thread/router_table.hpp

---
This PR currently contains the commit from https://github.com/openthread/openthread/pull/8623.
Please check the second commit in this PR (https://github.com/openthread/openthread/pull/8624/commits/d3486d2d43fb11f26f71a88b9a6985c87ce58248).

[router-table] simplify `GetNextHop()`

---

.github/workflows/build.yml

To resolve this: https://github.com/openthread/openthread/actions/runs/3960760069/jobs/6787063971

[github-actions] fix cmake 3.10.3 install

---

src/core/coap/coap.cpp

This is the fix for https://github.com/openthread/openthread/issues/8641.

[coap] copy token from block2 request message to next response token

---

src/lib/spinel/CMakeLists.txt
src/lib/url/CMakeLists.txt

Resolves: https://github.com/openthread/ot-ifx/actions/runs/4137519696/jobs/7152795343

[cmake] guard unit tests with `BUILD_TESTING`

---

src/posix/platform/netif.cpp

This commit disables addrconf generating address by set addr_gen_mode to IN6_ADDR_GEN_MODE_NONE, otherwise linux may generate a link local address based on link type and presense of EUI64 address. This allows OpenThread to fully manage link local address of its network interface.

[posix] disable addrconf generating LL address

---

tests/unit/README.md

This PR adds a README about building and running unit tests.

[unit] add a README guide for unit tests

---

src/cli/cli.cpp

Updated RCP command documentation in CLI.
Merged RCP CLI commands in documentation.
Updated region and route CLI.
Updated region and route.
Updated route.
Updated route add.
Updated parameters for route add.
Added parameters for router.
Added formatting for parameters.
Updated route command function.
Updated rcp version parameter.

[cli] added documentation for rcp and route

---

src/core/net/ip6.cpp

This commit simplifies `Ip6::HandleDatagram()` by combining the two places where we call `PassToHost()` into one. It simplifies how we perform the three actions `receive`, `forwardHost`, and `forwardThread`.

[ip6] combine `PassToHost()` calls in `Ip6::HandleDatagram()`

---

include/openthread/instance.h
include/openthread/platform/radio.h
src/core/mac/mac_frame.hpp

[radio] clarify `mTimestamp` meaning in comments

---

include/openthread/instance.h
include/openthread/platform/crypto.h
src/core/common/instance.cpp
src/core/crypto/crypto_platform.cpp
src/core/crypto/ecdsa.hpp
src/core/crypto/storage.cpp
src/core/crypto/storage.hpp
src/core/mac/mac.hpp
src/core/mac/mac_types.cpp
src/core/mac/mac_types.hpp
src/core/mac/sub_mac.hpp
src/core/net/srp_client.cpp
src/core/net/srp_client.hpp
src/core/thread/key_manager.cpp
src/core/thread/key_manager.hpp
tests/unit/test_platform.cpp

Add new class to handle ECDSA using key refs.
Update SRP to use key refs.

[crypto] allow key reference usage for ECDSA

---

.github/workflows/otci.yml
tools/otci/otci/__init__.py
tools/otci/otci/command_handlers.py
tools/otci/otci/connectors.py
tools/otci/otci/otci.py
tools/otci/otci/types.py
tools/otci/otci/utils.py

This commit fixes some style issues of otci. Also includes some minor
changes:
* added pytype check in otci
* exported `OTCommandHandler`

[otci] fix some style issues

---

src/core/meshcop/dataset.cpp
src/core/meshcop/network_name.cpp
src/core/meshcop/network_name.hpp

[network-name] consolidate default network name definition

---

src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp

This commit adds the `OmrPrefixManager` class to the `RoutingManager`. The `OmrPrefixManager` class manages OMR prefixes. In particular, it determines the favored and local OMR prefixes, and decides when/if to add/remove the local OMR prefix to/from Network Data.
----
The changes in this PR are mostly refactors to improve code, without changing its behavior

[routing-manager] add `OmrPrefixManager`

---

src/posix/platform/hdlc_interface.cpp

tcsetattr() fails on mac OS when a non-standard baudrate, such as 1000000, is used. There is a separate ioct() that accepts non-standard baudrates though.

[posix] fix setting non-standard baudrate on mac

---

.code-spell-ignore
tests/scripts/thread-cert/coap.py

Fixes https://github.com/openthread/openthread/actions/runs/5271362597/jobs/9534403798

[coap] fix minor typo

---

tests/scripts/expect/_common.exp
tests/scripts/expect/cli-multicast-loop.exp
tests/scripts/expect/cli-networkname.exp
tests/scripts/expect/cli-reset.exp
tests/scripts/expect/posix-rcp-restoration.exp
tests/scripts/expect/tun-dns-client.exp
tests/scripts/expect/tun-sntp.exp
tests/scripts/expect/tun-udp.exp

Context: https://github.com/openthread/openthread/pull/6091
Depends-On: openthread/ot-ns#502
Depends-On: openthread/ot-commissioner#236

[expect] properly configure operational dataset

---

tools/otci/tests/test_otci.py

Context: https://github.com/openthread/openthread/pull/6091

[otci] properly configure operational dataset

---

src/core/border_router/routing_manager.cpp

Fix a format issue involved by PR [ [routing-manager] update logs #9095 ](https://github.com/openthread/openthread/pull/9095)

[logging] fix print format related to infra netif logs

---

include/openthread/instance.h
include/openthread/link.h
src/core/api/link_api.cpp

This PR adds functions to the C link API to allow conditional upgrade of SED to SSED links after successful check csl is supported.

[csl] add APIs to retrieve status

---

src/posix/platform/netif.cpp

This commit fixes the netlink ACK error logging by extracting error messages from the
`NLMSGERR_ATTR_MSG` attribute. The key point is that the error code in the `nlmsgerr`
header is not necessary `errno` and can't be used with `strerror()`. This is explicitly
specified by the netlink spec ([RFC 3549](https://www.rfc-editor.org/rfc/rfc3549.html#section-2.3.2.2)):
> A non-zero error code message is equivalent to a Negative ACK (NACK).
In such a situation, the Netlink data that was sent down to the
kernel is returned appended to the original Netlink message header.
**An error code printable via the perror() is also set (not in the
message header, rather in the executing environment state variable)**.
Background:
When `otbr-agent` runs without `CAP_NET_ADMIN`, an error message is printed like …

[posix] fix logging of netlink errors

---

src/core/thread/mle_router.cpp

This commit simplifies the `MleRouter::HandleChildIdRequest()` method by directly tracking the list of MLE TLVs to be included in the response in a `TlvList`. This replaces the previous approach of using boolean flags to track which TLVs should be included. The use of `TlvList` also protects against the case where the child may have included the same TLV type in the "TLV Request TLV" and ensures that we do not include duplicate TLVs in the response.

[mle] simplify `HandleChildIdRequest()`

---

src/core/net/srp_server.cpp
src/core/net/srp_server.hpp

This commit simplifies tracking of host key in `Srp::Server` by saving the `Key` directly in a `Host` instead of the saving the `KeyRecord`.

[srp-server] simplify tracking of host key

---

src/core/net/srp_server.cpp
tests/unit/test_srp_server.cpp

This commit updates `CommitSrpUpdate()` to ensure that `aHost` is freed when granted key lease is zero and host is fully removed.
This commit also updates unit test `test_srp_server` (which checks the heap allocations by server) to cover the situations where client sends an update to remove host and all its services with or without clearing key-lease.

[srp-server] ensure `Host` is freed when committing with zero key-lease

---

src/cli/cli_dataset.cpp
src/core/config/border_agent.h

This PR fix two docs typo issues.

[docs] fix some typos

---

tools/harness-thci/OpenThread.py

After recent reference device release, two THCI issues have been found.
This commit adds `"` around commands arguments that have escapable characters (like `ot networkname aa\ bb`), and skips lines containing only ANSI escape codes in commissioning logs.

[thci] fix for ncs thci issues

---

src/core/net/dnssd_server.cpp

When `ResolveByUpstream()` returns an error, we ensure that the error is cleared so that the transmission of the DNS response (with `kResponseServerFailure` rcode) is not skipped at the `exit` label.
------
The existing code works fine today because the `SuccessOrExit(error = responseMessage->SetLength(sizeof(Header)));` statement updates the `error` variable. However, it is safer and better to clear the `error` variable in the `DNS_UPSTREAM_QUERY_ENABLED` block directly, rather than relying on the next statements to do so. This is because the next statements could be changed in the future, and if they are, the `error` variable might not be cleared properly.

[dnssd-server] send response if `ResolveByUpstream()` fails

---

src/core/thread/mesh_forwarder.cpp

This commit updates the `ApplyDirectTxQueueLimit()` method. We mark the "do not evict" flag on the newly queued `aMessage` so that it will not be removed from `RemoveAgedMessages()`. This protects against the unlikely case where the newly queued `aMessage` may already be aged due to execution being interrupted for a long time between the queuing of the message in `SendMessage()` and the call to `ApplyDirectTxQueueLimit()`. This protects against the message being potentially removed and freed twice.
---
Related to https://github.com/openthread/openthread/pull/9347.
Thanks to @pkwiek for finding this.

[mesh-forwarder] disallow new message eviction in `ApplyDirectTxQueueLimit()`

---

src/cli/cli.cpp

For "version api" I didn't see any API in the code to tag, so I wasn't sure what to do there.  You will see that I didn't add a "@par api_copy" tag there - plz advise.

[docs] added Doxygen tags to 4 CLIs

---

src/core/net/dnssd_server.cpp
src/core/net/dnssd_server.hpp
tests/unit/test_dns_client.cpp

This commit enhances the DNSSD Server by updating how it stores and tracks information when trying to resolve a received query using a discovery proxy.
The previous approach used a fixed-size array to retain information for pending proxy queries. The new approach uses the already allocated `Response.mMessage` and appends the newly defined `ProxyQueryInfo` struct to it. The `ProxyQueryInfo` struct specifies all the information we need to track associated with a query. `ProxyQuery` message entries are placed in a message queue waiting for a callback from the proxy. Once a callback is received, the `ProxyQuery` message is converted back to a `Response.mMessage` and response is prepared and sent. The new approach removes the restriction on the number of outstanding proxy queries and …

[dnssd-server] simplify resolving of query by proxy

---

src/core/thread/mle.cpp

This commit updates MLE to skip sending an Announce response when receiving an Announce message from a detached/orphan device and the included channel and PAN ID in the received Announce message are the same as the current network's channel and PAN ID.
---
Related to [SPEC-1165](https://threadgroup.atlassian.net/browse/SPEC-1165).

[mle] suppress Announce response to orphan child on same channel and PAN ID

---

src/lib/url/CMakeLists.txt
src/lib/url/url.cpp
src/lib/url/url.hpp
src/posix/platform/hdlc_interface.cpp
src/posix/platform/radio.cpp
src/posix/platform/radio.hpp
src/posix/platform/spi_interface.cpp
tests/unit/CMakeLists.txt
tests/unit/test_url.cpp

This commit adds methods to parse parameter values directly from the url, moves the url unit test to the test/unit and updates the url processing methods in posix platform.

[url] add methods to parse parameters from url

---

src/core/meshcop/border_agent.cpp
src/core/meshcop/border_agent.hpp

This commit contains smaller changes in `BorderAgent` class:
- Define `kUdpPort` as a private constant in `BorderAgent` class.
- Add `SendMessage()` method to send message through `SecureAgent`.
- Add `LogError()` as a method so the correct log module is used.
- Remove unused `mMessageInfo` member variable.
- Harmonize log messages.

[border-agent] smaller enhancements

---

src/core/thread/mesh_forwarder_ftd.cpp

This commit simplifies the `MeshForwarder::SendMessage()` method and its logic for determining whether to send a multicast message to sleepy children. We first determine whether the destination address is link-local or realm-local all-nodes, meaning it is destined to all nodes. Otherwise, we need to check whether each sleepy child is subscribed to the address. We then iterate through the child table and mark the message for indirect transmission accordingly.

[mesh-forwarder] simplify multicast forward to sleepy children

---

src/core/net/ip6.cpp

This commit contains smaller changes in `Ip6` class:
- Rename constant `kForwardIcmpTypes` to follow naming convention
- Simplify how it it used to filter which ICMP types are forwarded to Thread mesh.

[ip6] fix constant name style and simplify filtering of ICMP types

---

src/core/net/ip6.cpp

This commit updates how `Ip6::HandleDatagram()` processes a tunneled IP-in-IP message. Previously, if a message was marked for both `receive` and `forwardThread` (e.g., this is possible for a multicast message from host with multicast-loop flag) it would be received but not forwarded to the Thread mesh. This commit ensures that such messages are handled properly.
Without this change, multicast transmission still works fine due to the MPL layer retransmitting the message, which would then be forwarded to the Thread mesh. However, this change improves the multicast behavior by ensuring that the original/first message is also forwarded to the Thread mesh.
This commit changes the code so that if we need to both `receive` and `forwardThread`, we create a copy of the message by cloning it. …

[ip6] update tunnel message receive in `HandleDatagram()`

---

src/cli/README_DATASET.md

Also fixes a pskc -> PSKc typo; and explain better how to init dataset.
Based on existing documentation I struggled a long time to create a Pending Dataset in the proper way, so I thought it would be good to document this better.

[cli] update Dataset documentation with Pending Dataset usage and time units

---

src/posix/platform/settings.cpp

The "assert" and "VerifyOrDie" were checking same condition, so the second validation was never executed if (rval != sizeof(key)). Additionally,"aSwapFd" was not freed on assertion. With this commit, addressed the memory leak to system resources.

[posix] addressing coverity warning: resource leak

---

src/core/meshcop/joiner_router.cpp

This commit updates `JoinerRouter::PrepareJoinerEntrustMessage()` to improve how TLVs from Active Operational Dataset are appended to the message. The TLV types that should be included in Joiner Entrust are now defined in an array `kTlvTypes`, and the code iterating over this array will find the TLV in Dataset and append it to the message.
Previously, if a required TLV type was not present in the Dataset, the code would have appended the TLV with an uninitialized and possibly random value, which could lead to unexpected behavior. The new code will fail if the required TLVs are not present in the Dataset instead, ensuring that only valid TLVs are included in the Joiner Entrust message.

[joiner-router] enhance & fix appending TLVs to Joiner Entrust msg

---

tests/toranj/cli/test-603-channel-announce-recovery.py

This commit updates the `test-603-channel-announce-recovery` test to verify router node channel recovery (following channel change) in addition to child recovery.

[test] update `channel-announce-recovery` test to check router recovery

---

src/posix/platform/netif.cpp

Clang Compilers warns about ignoring return values.
This PR does not change the existing behavior.
Ignoring errors in `processNat64StateChange` should be safe, and we may work under downgraded experience.
Ignoring errors in `nat64Init` should be safe like the outter if.

[posix] fix a few compiler warnings around nat64

---

tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py

Fixes https://github.com/openthread/openthread/issues/9340

[tests] reduce flakiness of `test_publish_meshcop_service.py`

---

src/cli/README.md
src/cli/cli.cpp
src/cli/cli.hpp
tests/scripts/expect/cli-debug.exp

This commit adds cli `debug` command. This command is specifically designed for testing and debugging purposes. It executes a series of CLI commands to gather information about the device and thread network.

[cli] add `debug` command

---

src/posix/platform/daemon.cpp
src/posix/platform/multicast_routing.cpp
src/posix/platform/netif.cpp
src/posix/platform/udp.cpp

Should be checking for definition rather than value.
Also prefer `#ifdef` over `#if defined`

[posix] fix usage of `__linux__`

---

src/core/common/heap_data.cpp
src/core/common/heap_data.hpp
tests/unit/test_heap_string.cpp

Also updates the unit test to validate the new method.

[heap-data] add `Matches()` to compare `Heap::Data` with a given buffer

---

src/core/BUILD.gn
src/core/config/trel.h
src/core/openthread-core-config.h
src/core/radio/trel_interface.hpp
src/posix/platform/openthread-posix-config.h
src/posix/platform/trel.cpp

Make size of trel peer table and trel tx packet pool configurable

[trel] add config for peer table size and packet pool size

---

src/cli/README_BR.md
src/cli/cli_br.cpp

print out the DHCPv6 PD feature's state
enable/disable DHCPv6 PD

[cli] add pd state

---

.github/workflows/otbr.yml
.github/workflows/otns.yml
.github/workflows/posix.yml
.github/workflows/simulation-1.1.yml
.github/workflows/simulation-1.2.yml
.github/workflows/toranj.yml
.github/workflows/unit.yml

- actions/upload-artifact from 3.1.3 to 4.0.0
- actions/download-artifact from 3.0.2 to 4.1.1

[github-actions] bump actions/upload-artifact and actions/download-artifact

---

.github/workflows/otbr.yml
.github/workflows/otns.yml
.github/workflows/posix.yml
.github/workflows/simulation-1.1.yml
.github/workflows/simulation-1.2.yml
.github/workflows/toranj.yml
.github/workflows/unit.yml

Simply set retention to 1 day for coverage artifacts.

[github-actions] remove use of geekyeggo/delete-artifact

---

src/core/net/ip6.cpp

This commit simplifies `Ip6::SelectSourceAddress()` by adding a new boolean `newAddrIsPreferred` tracking whether the new address is preferred over the previously chosen one as we iterate over all addresses.

[ip6] simplify `Ip6::SelectSourceAddress()`

---

src/cli/README_COAPS.md

Please review updates to the coaps start command.

[cli] update coaps readme

---

src/core/thread/child_table.cpp
src/core/thread/mle_router.cpp

PR to address the issue discussed [here](https://github.com/openthread/openthread/issues/9787)

[mle] generate challenge for "Child Update Request" early

---

tools/tcat_ble_client/tlv/tlv.py
tools/tcat_ble_client/utils/__init__.py

Some files were missing during repo migration,
this commit adds them.

[tools] add missing tcat ble client files

---

src/cli/README.md

---
Documenation already provided in `cli.cpp` => https://openthread.io/reference/cli/commands#nexthop

[cli] add documentation for `nexthop` command in `README.md`

---

src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp
src/core/net/nd6.cpp
src/core/net/nd6.hpp
tests/unit/test_routing_manager.cpp

This commit enhances flexibility in Router Advertisement (RA) message construction by employing `Heap::Array`. This eliminates the need for a pre-allocated buffer and removes the constraint of predetermining the maximum RA message size.
Additionally, introduces `TxMessage` and `RxMessage` nested classes within `Ip6::Nd::RouterAdvert` for efficient handling of outgoing and incoming RA messages:
- `TxMessage`: Facilitates appending elements to an RA message with dynamic buffer allocation.
- `RxMessage`: Enables parsing and iterating over options within a received RA message.

[routing-manager] construct RA dynamically using `Heap::Array`

---

src/core/thread/mle_router.cpp

This commit contains smaller enhancements in the code related to aging/updating router entries:
- Consolidate nested `if` blocks for readability.
- Add router's RLOC16 to logs for improved router tracking.
- Refactor duplicate code in `SEND_LINK_REQUEST_ON_ADV_TIMEOUT`.

[mle] simplify `HandleTimeTick()` code related to aging routers

---

src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp
tests/unit/test_routing_manager.cpp

This commit updates how `RoutingManager` differentiates between self-generated RA messages and those from other sources sending RA on the same device. This enables learning of the RA header, specifically the default route lifetime.
This commit introduces a new mechanism to calculate and store a SHA256 hash of recently emitted RAs. Received RAs are cross-referenced against the stored hashes to determine their origin. This replaces the prior method, which relied on parsing and analyzing the included options in the received RA.
A new test case is added in `test_routing_manager` to validate the learning of RA header from other sources on same device.
---
Background: 
- The hash-based model is simpler 
- It also allows additional vendor-specific custom options to be included in emitted RAs.

[routing-manager] employ RA hash tracking to detect self-originating RAs

---

src/core/thread/network_data.cpp

This commit relocates `NetworkData` and `MutableNetworkData` method implementations to improve code organization. There is no functional change.

[netdata] refactor `MutableNetworkData` methods for code organization

---

src/core/thread/mle.cpp
src/core/thread/mle_router.cpp

This commit streamlines MLE module comments by simplifying explanations and removing redundant ones that are clear from source code.

[mle] improve MLE module comments

---

src/core/meshcop/dataset_manager_ftd.cpp

This commit contains smaller enhancements in `HandleSet()`:
- Remove the redundant `IsLeader()` check since it is checked in `HandleTmf<kUriActiveSet>` and `HandleTmf<kUriPendingSet>` before calling `HandleSet()`
- While reading TLVs from message, ensure that entire TLV is contained in the `Message`.
- Simplify the code that verifies an `MGMT_ACTIVE_SET.req` from a commissioner does not affect connectivity (change boolean checks to positive instead of negative).
- Remove `hasNetworkKey` as the condition is tracked by `doesAffectNetworkKey`.

[dataset] simplify `DatasetManager::HandleSet()`

---

src/core/border_router/routing_manager.cpp

[routing-manager] update and simplify comments

---

src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp

This change leverages `OwningList<>` to manage discovered routers and prefix entries within `RoutingManager`. This ensures automatic deallocation of these items, streamlining memory management. It works independently of whether the items are heap-allocated or from a `Pool`.

[routing-manager] use `OwningList` for `Router` and `Entry` lists

---

src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp

This commit moves the scheduling and handling of the stale timer to `RxRaTracker`. This aligns with the responsibility of this class managing all discovered on-link/route prefixes and the locally generated RA header to mirror.
----
~This PR currently contains the commit from https://github.com/openthread/openthread/pull/10257. Please check and review last commit. Thanks.~

[routing-manager] move handling of prefix stale timer to `RxRaTracker`

---

src/core/common/string.cpp
src/core/common/string.hpp
src/core/meshcop/meshcop.cpp
src/core/net/ip6_address.cpp
src/core/utils/parse_cmdline.cpp
tests/unit/test_string.cpp

This commit adds a set of helper functions to parse a given digit or hex digit character to its numeric value, or to check if a given character is a digit, uppercase, or lowercase letter.

[string] add `ParseDigit()`, `ParseHexDigit()`, and other helper functions

---

src/core/thread/mle_router.cpp

Use the `Route64 TLV` to update the router table after adding a new neighbor in `HandleLinkAccept`.
With this change, when a router re-joins the network, it will restore its nexthop table while processing the `link accept`, rather than having to wait for an `mle advertisement`.

[mle] update router table after adding a new neighbor

---

src/core/net/dns_dso.cpp
src/core/net/dns_dso.hpp

Updates `Dns::Dso` class to use `NextFireTime`/

[dso] use `NextFireTime`

---

src/posix/platform/netif.cpp

This PR improves the logging of `posix/platform/netif.cpp` in following ways:
- Fix the false warning log when OT stack adds a unicast address.
1. When OT adds an address, it will add an address on host netif.
2. Then it causes a netlink `RTM_NEWADDR` event. 
3. It assumes the newly added address is added by the host, so tries to add the unicast address to OT again by `otIp6AddUnicastAddress`. 
4. `otIp6AddUnicastAddress` returns 'invalid arguments' error so it will log `Failed to process event...`.
- Improve the logging of `AddRoute` and `DeleteRoute`. Previously they silently sent out the requests so we don't know what the allocated netlink sequence numbers were used for.

[posix] improve the logging in netif

---

src/cli/README.md
src/cli/cli.cpp

---
Addresses https://github.com/openthread/openthread/issues/10373.

[cli] update `service add` command to allow empty server data

---

src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp

This commit enhances `RoutingManager::RxRaTracker`:
- A new private `Evaluate()` method centralizes logic for handling changes in tracked routers and advertised prefixes. It removes expired entries, determines decision factors used by other `RoutingManager` components, and schedules timers.
- A new class `DecisionFactors` is added to track factors used by `RoutingManager`, including the favored on-link prefix, presence of ULA/non-ULA prefixes, and M/O flags for mirroring in emitted RA messages.
- `Evaluate()` determines these factors and signals changes using `HandleRaPrefixTableChanged()` only when necessary, simplifying signaling and avoiding redundant calculations.
---
~This PR currently contains the commit from https://github.com/openthread/openthread/pull/10382. Please check and …

[routing-manager] centralize `RxRaTracker` decision logic and signaling

---

src/core/meshcop/tcat_agent.cpp
src/core/meshcop/tcat_agent.hpp
tests/scripts/expect/cli-tcat-decommission.exp
tools/tcat_ble_client/bbtc.py
tools/tcat_ble_client/cli/base_commands.py
tools/tcat_ble_client/cli/cli.py

Commits adds handling of TCAT TLV 0x60 `kTlvDecommission`.

[tcat] implement decommissioning in tcat_agent

---

tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py

Depends-On: openthread/ot-br-posix#2306

[test] supplement state bitmap test

---

include/openthread/instance.h
include/openthread/platform/radio.h
src/core/mac/mac_frame.hpp
src/core/mac/mac_links.hpp
src/core/radio/radio.hpp

This commit adds a new radio capability to indicates that the platform supports specifying tx power per frame.

[platform] add per-frame tx power capability

---

tools/otci/otci/command_handlers.py
tools/otci/otci/otci.py

This commit adds the iperf3 commands to `otci` for testing Thread network throughput.

[otci] add iperf3 commands to otci

---

src/core/thread/dua_manager.cpp

Fix [10557](https://github.com/openthread/openthread/issues/10557)

[dua] resume registration when fails to become router

---

tools/cp-caps/README.md
tools/cp-caps/rcp_caps_test.py

This commit adds a test case to the `cp-tests` to test the Thread network 1 hop throughput.

[test] test the Thread network 1 hop throughput

---

src/core/meshcop/border_agent.cpp

This commit updates logs on secure session establishment and commissioner for accuracy.

[border-agent] log enhancements

---

tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py
tests/scripts/thread-cert/node.py

Meshcop ePSKc mode supported bitmap check

[test] verify state bitmap when runtime enable/disable EphemeralKey mode

---

.gitignore

ot_testing/* are generated when running "script/test cert_suite"

[gitignore] ignore files in ot_testing folder

---

tests/scripts/thread-cert/run_cert_suite.py

This is helpful to know the exact time that each test take when running bunch of tests in cert suite.

[thread-cert] print elapsed time of each test when running cert suite

---

.github/workflows/docker.yml

Attempt to fix the following:
```
buildx-environment
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.319.0/_diag/Worker_20240814-174506-utc.log'
at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.Diagnostics.TextWriterTraceListener.Flush()
at System.Diagnostics.TraceSource.Flush()
at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
at GitHub.Runner.Common.TraceManager.Dispose()
at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
at GitHub.Runner.Common.HostContext.Dispose()
at GitHub.Runner.Worker.Program.Main(String[] …
```

[github-actions] free up disk space for docker build

---

tests/scripts/thread-cert/border_router/test_multi_ail.py

This PR:
1. update the topology to make 3 BRs running on 2 AILs;
2. specify the test name as `test_multi_backbone_infra`, which is focusing on verifying the multiple backbone framework works good;
3. fix bug that previously pinging through ethernet does not actually work.
For 3, previous `br1.ping(br2_infra_link_local, interface=br1_infra_link_local)` actually send ping command via ot-ctl instead of the docker bash. The new `br1.ping(br2_onlink_ula, backbone=True)` actually send a docker bash command to ping another node via ethernet. Here we choose to use onlink ULA address (9100::) instead of the link local address because only `ping [link-local-addr]%eth0` (by specifying the zone index) can work for link-local address, but this is not currently supported by `LinuxHost.ping_ether()` …

[tests] optimize multi-ail test case to run three BRs on two infra link 

---

src/core/meshcop/border_agent.cpp

This commit applies new pskc into secure transport when it's changed
via active/pending dataset, without impacting existing secure session
if any or ephemeralkey mode if it's activated

[border-agent] apply pskc if changed

---

tools/tcat_ble_client/bbtc.py
tools/tcat_ble_client/ble/ble_stream.py
tools/tcat_ble_client/ble/ble_stream_secure.py
tools/tcat_ble_client/cli/base_commands.py
tools/tcat_ble_client/cli/cli.py

Minor fixes and improvements on TCAT client including:
-  fix in handling cert-path in can command
-  adding timeouts during BLE TLS connection establishement.

Tcat client fixes

---

examples/platforms/simulation/radio.c
examples/platforms/utils/mac_frame.cpp
examples/platforms/utils/mac_frame.h

This commit adds a helper of SFD handler to process IEs and security in the SFD handler from ISR.

[radio] add a helper of SFD handler

---

src/core/thread/mle.cpp
src/core/thread/mle.hpp

This commit updates the graceful detach mechanism in `Mle`. A boolean `mDetachingGracefully` is added to track when the device is performing a "graceful detach". The `mAttachTimer` is reused for scheduling the detach delay, as any attach operation can be stopped during detach, and the timer can be reused. This simplifies the code and removes the need to use a specific timer for the graceful detach process.

[mle] simplify graceful detach mechanism and reuse `mAttachTimer`

---

tests/gtest/fake_platform.cpp
tests/gtest/fake_platform.hpp
tests/gtest/radio_spinel_rcp_test.cpp

This commit adds a test to verify RX channel is switched correctly after TX done.

[test] verify behavior of RxChannelAfterTxDone

---

src/core/api/ip6_api.cpp
src/core/api/nat64_api.cpp
src/core/net/ip6.cpp
src/core/net/ip6.hpp

This commit contains minor enhancements to the `Ip6` class, including variable and method renames (to use shorter names) and minor style changes.

[ip6] style changes and renames

---

src/core/net/ip6.cpp

This commit refactors the `InsertMplOption()` method for improved efficiency and readability. Cascading `if`/`else` blocks have been eliminated by handling the simpler `IsMulticastLargerThanRealmLocal()` case first. Redundant checks for multicast destination and scope have been removed, as these conditions are already covered by `IsRealmLocalMulticast()` and `IsMulticastLargerThanRealmLocal()`.

[ip6] simplify `Ip6::InsertMplOption()`

---

tests/toranj/build.sh

See: https://www.shellcheck.net/wiki/SC2086

[toranj] SC2086: double quote to prevent globbing and word splitting

---

src/core/net/ip6.cpp

This commit simplifies the filter checks that drop TMF UDP messages from untrusted origins. The `mTmfOriginFilterEnabled` flag is checked first, and then the full UDP header is read from the message.

[ip6] simplify applying of TMF UDP filter in `Ip6::HandleDatagram()`

---

script/test
tests/nexus/build.sh

See: https://www.shellcheck.net/wiki/SC2317

[scripts] SC2317: command appears to be unreachable

---

tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py
tests/scripts/thread-cert/node.py

Depends-On: openthread/ot-br-posix#2537

[test] add retain_active_session option for ePSKc deactivate API

---

src/core/thread/mle.cpp

This commit updates and fixes how the `mDataRequestState` variable, which controls retransmissions of MLE Data Request messages, is updated.
An MLE Data Request message can be sent for different purposes: either to request updated Network Data or to retrieve a Link Metrics Report from a neighbor/parent. The `mDataRequestState` retransmission mechanism is used to handle retx of Data Requests for retrieving Network Data. This commit ensures that the code that updates these variables is moved to `SendDataRequestAfterDelay()` and not in the common version, which can be used for both Network Data and Link Metric Reports. This ensures these states are not incorrectly updated when a Link Metrics Report is retrieved.

[mle] fix updating of `mDataRequestState` for Network Data

---

src/core/net/mdns.cpp
src/core/net/mdns.hpp

This commit simplifies the process of preparing response and query messages in the mDNS module. Instead of passing `TxMessage` and `aNow` separately,  a reference to `EntryContext` or `CacheContext` is now passed directly to `PrepareResponse()` and other related methods.
This direct approach streamlines the code and facilitates the potential inclusion of additional fields in `EntryContext` in the future.

[mdns] simplify response and query preparation by passing `Context`

---

src/core/meshcop/secure_transport.cpp
src/core/meshcop/secure_transport.hpp

This commit introduces the `EcdheEcdsaInfo` and `PskInfo` structs, which encapsulate all the tracked properties needed when the corresponding key-exchange mechanism is used. This helps simplify the code by keeping all code related to each feature within the same block.

[secure-transport] track key-exchange info in separate structs

---

src/core/meshcop/secure_transport.cpp
src/core/meshcop/secure_transport.hpp

This commit adds a new `CipherSuite` enum in `SecureTransport` to track the selected cipher suite. This helps simplify the code. A table is used to map the selected `mCipherSuite` to a constant array of `MBEDTLS_TLS_*` values to configure mbedTLS module.

[secure-transport] simplify tracking of selected cipher suite

---

tools/cp-caps/README.md
tools/cp-caps/rcp_caps_test.py

This commit add a command `--frame-format` to the `cp-caps` to test whether the RCP supports sending and receiving 802.15.4 frames of all formats.

[test] test whether the RCP supports tx/rx 154 frames of all formats

---

src/core/meshcop/secure_transport.cpp
src/core/meshcop/secure_transport.hpp

This commit removes unused variables/methods from the `SecureTransport` class. It also removes repeated code and implements other minor enhancements.

[secure-transport] remove unused variables and methods

---

tools/tcat_ble_client/ble/ble_advertisement_data.py
tools/tcat_ble_client/ble/ble_scanner.py
tools/tcat_ble_client/tlv/advertised_tlv.py
tools/tcat_ble_client/tlv/tlv.py

Commit adds TCAT advertisement pars and display during scan operation perormed in python client.

[tcat] add TCAT advertisement parsing in client

---

src/core/radio/ble_secure.cpp
tools/tcat_ble_client/bbtc.py
tools/tcat_ble_client/cli/base_commands.py
tools/tcat_ble_client/cli/cli.py
tools/tcat_ble_client/dataset/dataset_entries.py

Implementation of tcat disconnect command in python client.

[tcat] implementation of tcat disconnect command

---

src/core/meshcop/secure_transport.cpp

This commit updates the `Setup()` method to separate the preparation of the `mbedtls_ssl_config`, `mbedtls_ssl_cookie_ctx`, and `mbedtls_ssl_context` components. This allows for decoupling these components later, for example, to support multiple sessions using the same configuration.

[secure-transport] refactor `Setup()` to separate component setup

---

src/core/meshcop/secure_transport.cpp
src/core/meshcop/secure_transport.hpp

This commit updates how state is tracked in the `SecureTransport` class. It directly tracks whether the transport/socket has been opened or closed in a new member variable `mIsOpen`. The TLS/DTLS session state is tracked separately in `mSessionState`. This separation allows for future changes to support multiple sessions using the same transport/socket.
This commit also simplifies the session states, adding "disconnected" and "disconnecting" (replacing "close notify") states.

[secure-transport] separate transport/socket and session states

---

src/core/meshcop/secure_transport.cpp

This commit updates `Setup()`, which initializes and sets up `mbedtls_ssl_config` and `mbedtls_ssl_context`. The call `mExtension->SetApplicationSecureKeys()` (which updates the `mbedtls_ssl_config`) is now called before `mbedtls_ssl_setup()` associates the config with the `mbedtls_ssl_context`. This follows the recommendation that the config structure is not modified after `ssl_setup()` and while a session is active.

[secure-transport] set app keys on config before SSL context setup

---

src/core/meshcop/secure_transport.cpp
src/core/meshcop/secure_transport.hpp

This commit introduces the `SecureSession` class to manage session-related functionality, decoupling it from the `SecureTransport` class. `SecureSession` provides method such as `Connect()`, `Send()`, and `IsConnected()`, while `SecureTransport` focuses on transport-level operations and common configuration (e.g., setting PSK, cipher keys).
The `Dtls` and `Tls` subclasses now inherit from both `SecureTransport` and `SecureSession`, effectively providing the same methods as before and implementing a single DTLS/TLS session over a socket.
---
~This PR currently contains the commit from PR https://github.com/openthread/openthread/pull/11044. Please check and review the last commit on this PR. Thanks.~

[secure-transport] introduce `SecureSession` class

---

src/core/meshcop/border_agent.cpp

This commit simplifies the `BorderAgent::HandleUdpReceive()` method:
- All local variables are defined at the top of the method.
- Tracks whether the UDP message was handled in the new local `didHandle` variable (avoiding the reuse of a specific error code to track this).
- Simplifies log messages.

[border-agent] simplify `HandleUdpReceive()`

---

tests/scripts/thread-cert/run_cert_suite.py

Previously, it prints a line `PASS x FAIL y ...` when all the runs of a test case complete. However, such messages could be hard to find when multiple test runs fail so the messages are interspersed between other logs.
This PR moves such messages to the end of the output. This makes it easier to notice which test cases are failed. Also it will list the failed iterations, which is useful when MULTIPLY > 1. 
Example output:
```
---------------------------------------
Summary
---------------------------------------
PASS 0 FAIL 2 ./tests/scripts/thread-cert/border_router/test_advertising_proxy.py Failed iterations: [0, 1]
PASS 2 FAIL 0 ./tests/scripts/thread-cert/border_router/test_single_border_router.py
```

[continuous-integration] print summary for thread-cert tests

---

src/core/meshcop/border_agent.cpp
src/core/meshcop/border_agent.hpp

This commit updates the `CoapDtlsSession` class in `BorderAgent` to move all session-related functionality into this class. It now handles its own state and uses its own `Timer`, ALOC, UDP receiver, etc.
Many methods previously defined in `BorderAgent` are now defined in `CoapDtlsSession`, ensuring each session can be processed individually. The `ForwardContext`, which tracks forwarded TMF commands, is also moved into `CoapDtlsSession` and updated to track its associated session.
This change prepares `BorderAgent` to support multiple concurrent sessions in future PRs.
----
~This PR current contains the commits from #11101 and #11092. Please check and review the last commit. Thanks.~

[border-agent] update `CoapDtlsSession` to handle session functionality

---

src/core/meshcop/border_agent.cpp

This commit improves the organization of `border_agent.cpp` by grouping the method definitions for `CoapDtlsSession` into a separate section.
In PR #11131, many methods were moved into this class. To keep the `git diff` smaller and easier to review, the methods were left in the same order as previously defined. This resulted in the methods of `CoapDtlsSession` and `BorderAgent` being mixed and interleaved.
This PR rearranges the methods and defines separate sections for each class. This commit does not contain any code logic changes.
----
This PR currently contains the commit from #11131. Please check and review the last commit. Thanks.

[border-agent] organize `CoapDtlsSession` method definitions

---

.github/workflows/docker.yml

Fixes https://github.com/openthread/openthread/actions/runs/13183775231/job/36813995735

[docker] use `arm64` runner instead of `qemu`

---

src/posix/platform/spi_interface.cpp

the error was introduced in https://github.com/openthread/openthread/pull/11292

[posix] fix GPIO interrupt pin error when SPI init

---

.github/workflows/otbr.yml

See https://github.com/openthread/ot-br-posix/pull/2709

[github-actions] remove avahi + TREL test

---

src/core/thread/mesh_forwarder.cpp

This commit changes the mesh forwarder to avoid adding CSL IE when the message is not destined to a known neighbor. This change also eliminates the check to exclude the MLE Discovery Request for adding CSL IE.

[mesh-forwarder] do not add CSL IE for non-neighbors

---

src/posix/platform/alarm.cpp

This commit enhances the posix `otPlatAlarm` implementation by:
- Avoiding casting from unsigned int to signed int. While this usually works, it's technically undefined behavior.
- Adding new `IsExpired()` and `CalculateDuration()` methods to avoid unsigned to signed casting and simplify the code.
- Ensuring `static_cast<>` is used instead of C-style casts.

[posix] enhance `otPlatAlarm` implementation

---

src/core/radio/trel_peer_discoverer.cpp
src/core/radio/trel_peer_discoverer.hpp

This commit introduces `TxtData` and `TxtDataEncoder` as nested types in `Trel::PeerDiscoverer`. These classes handle the decoding and encoding of TXT data for the TREL service, separating this TXT data-related logic from the rest of the code. This helps simplify the code and enables future extensions, allowing the TXT data logic to be used irrespective of how services are registered or discovered.
----
- This PR contains the commit from https://github.com/openthread/openthread/pull/11493. Please check and review the last commit. Thanks.

[trel] introduce `TxtData` and `TxtDataEncoder` in `PeerDiscoverer`

---

src/posix/main.c

[posix] add conditional around `SIGRTMIN`

---

.github/workflows/simulation-1.1.yml
.github/workflows/simulation-1.4.yml
examples/platforms/simulation/virtual_time/platform-sim.c
script/test
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/simulator.py

This commit adds a reliable transport based on SEQPACKET unix socket to simulation platform and use this for tests on simulation platform.

[simulation] add reliable virtual time transport

---

src/core/net/srp_client.cpp
src/core/net/srp_client.hpp
tests/unit/test_srp_server.cpp

This commit updates the SRP client message ID assignment model. Message IDs are now selected randomly, ensuring they differ from the last ID used. The same message ID is reused when a message is retried.
This replaces the earlier design where all messages, including retries, used sequential message IDs.
The unit test is also updated to validate the new behavior.
----
Related to [SPEC-1400](https://threadgroup.atlassian.net/browse/SPEC-1400)

[srp-client] update message ID assignment model

---

src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_ftd.cpp

This commit introduces a new `Mle::Attacher` class to encapsulate all logic and state related to the device attach process.
This change moves the attach state machine, parent candidate management, attach timer, and message handling for Parent Request, Parent Response, Child ID Request, and Child ID Response from `Mle` into the new nested `Attacher` class.
This refactoring improves code organization and modularity by separating the attach logic from the main `Mle` class.

[mle] introduce `Attacher` class

---

src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_ftd.cpp

Reverts openthread/openthread#11831

Revert "[message] check for potential integer overflows"

---

src/core/net/ip6.cpp
tests/scripts/thread-cert/backbone/test_mlr_multicast_routing_across_thread_pans.py

This helps reduce header overhead.

[mpl] use RLOC as IPv6 source address
