include/openthread/thread_ftd.h
src/cli/README.md
src/cli/cli.cpp
src/cli/cli.hpp
src/core/api/thread_ftd_api.cpp
src/core/thread/announce_sender.cpp
src/core/thread/mle_router.cpp
src/core/thread/mle_router_ftd.hpp
src/core/thread/mle_router_mtd.hpp
src/core/thread/network_data_local.cpp
src/ncp/ncp_base_ftd.cpp
tools/harness-thci/OpenThread.py

This PR includes the following changes:
- change IsFullThreadDevice to IsRouterEligible where appropriate
- add return error to otThreadSetRouterEligible    
When trying to set router-eligible and the device is not capable of
becoming a router, return OT_ERROR_NOT_CAPABLE.
- rename RouterRoleEnabled to RouterEligible
- keep State Update Timer running on FTD  
The existing code did not keep the State Update timer running if the
device was not router-eligible. However, a Full End Device (FED) needs
to keep the State Update timer running to maintain its links to
neighboring routers.
This commit ensures that the State Update timer continues to run on
FTD devices, even if the device is operating as a FED. This commit
also removes some unncessary code to start the State Update timer if
the …

[mle] fixes and enhancements for REEDs

---

src/posix/platform/hdlc_interface.cpp
src/posix/platform/hdlc_interface.hpp
src/posix/platform/platform-posix.h
src/posix/platform/radio_spinel.cpp
src/posix/platform/radio_spinel.hpp
src/posix/platform/sim.c

This PR simplifies the API between RadioSpinel and HdlcInterface to improve the extensibility of
the API. So that we can easily add other low layer interfaces to send/receive spinel frames later.
The RadioSpinel is only responsible for encoding/decoding spinel frames. Lower layer interface is only responsible for sending/receiving spinel frames.
Some lower layer interfaces can't provide a file descriptor for RadioSpinel to wait for the file descriptor to become writable, so this PR removes the kStateTransmitPending state from RadioSpinel.c and directly calls the function Request() to send frames in method RadioSpinel::Transmit().

[posix-app] optimize the interface between radio_spinel and hdlc_interface

---

src/core/thread/mle.cpp

This commit ensures that the important MlEid would be the
first one in Address Registration TLV so that the parent
would always be able to store it.
(SPEC-899: A recipient MUST process address entries in an
Address Registration TLV sequentially from first entry to
last entry)

[mle] MTD prioritizes ML-EID registration

---

src/posix/Makefile.am
src/posix/platform/Makefile.am
src/posix/platform/hdlc_interface.cpp

This PR removes from posix-app dependency on `$(OPENTHREAD_TARGET_DEFINES)` which is defined by autoconf only.

[posix-app] remove dependency on OPENTHREAD_TARGET_DEFINES

---

src/core/net/ip6.cpp

Prefer ML-EID for any mesh-local traffic that does not have RLOC
destination.
This addresses the issue @librasungirl identified in #4362.

[ip6] prefer RLOC source with RLOC dest in SelectSourceAddress()

---

src/core/Makefile.am
src/core/coap/coap.cpp
src/core/coap/coap.hpp
src/core/common/linked_list.hpp
src/core/common/notifier.cpp
src/core/common/notifier.hpp
src/core/common/timer.cpp
src/core/common/timer.hpp
src/core/net/icmp6.cpp
src/core/net/icmp6.hpp
src/core/net/netif.cpp
src/core/net/netif.hpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp
tests/unit/Makefile.am
tests/unit/test_linked_list.cpp

This commit adds a linked list module which provides a template
implementation of a singly linked list. The new class is then used in
different core modules (netif (unicast/multicast addresses), UDP6
sockets/receiver, coap resources, etc). This commit also adds a
unit test `test_linked_list` for the linked list module.

[linked-list] adding `LinkedList` class

---

src/core/coap/coap_message.cpp
src/core/coap/coap_message.hpp
src/core/common/settings.hpp
src/core/diags/factory_diags.cpp
src/core/diags/factory_diags.hpp
src/core/mac/mac.cpp
src/core/mac/mac.hpp
src/core/mac/mac_filter.cpp
src/core/mac/mac_types.hpp
src/core/mac/sub_mac.cpp
src/core/meshcop/border_agent.cpp
src/core/meshcop/commissioner.cpp
src/core/meshcop/joiner.cpp
src/core/net/ip6.cpp
src/core/net/ip6_address.cpp
src/core/net/netif.hpp
src/core/net/socket.hpp
src/core/net/udp6.cpp
src/core/thread/address_resolver.cpp
src/core/thread/key_manager.cpp
src/core/thread/key_manager.hpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp
src/core/thread/mle_tlvs.hpp
src/core/utils/slaac_address.cpp

This PR contains a group of smaller commits related to adding/using `Clear()` method:
- [netif] add Clear() to netif unicast/multicast address types
- [mle-tlvs] add LeaderDataTlv::Clear()
- [ip6] use Ip6::Address::Clear() replacing memset to zero
- [mac-types] add Clear() and Fill() method to Mac::ExtAddress
- [mac-types] add Mac::ExtendedPanId::Clear() method
- [key-manager] add Pskc::Clear() method
- [socket] add SockAddr::Clear()
- [coap-message] add HelpData::Clear() method
- [factory-diags] add Diags::Stats::Clear() method
- [mac] use Mac::ResetCounters()
- [settings] add Clear() method for all setting structures

[misc] add `Clear()` method (replacing memset() zero)

---

include/openthread/ip6.h
src/cli/README.md
src/cli/cli.cpp
src/core/net/ip6.cpp
src/core/net/socket.hpp

HopLimit 0 is required for TC defined in Thread 1.2 Test Plan. And also as pointed out by @bukepo in #3089, 0 is a valid value.
> From section IPV6_UNICAST_HOPS and IPV6_MULTICAST_HOPS of http://man7.org/linux/man-pages/man7/ipv6.7.html, 0 is a valid value, and -1 means using the default value
Here were some relative PRs and discussions regarding hop limit 0 (#3077, #3089, #3092).
The first commit in PR introduces one flag to indicate whether to apply hop limit 0 to meet the hoplimit 0 requirement, as well as keep previous usage as is. 
The second commit extends existing `ping` command to allow hoplimit configuration.

[ip6] allow hoplimit 0

---

tools/harness-thci/OpenThread.py
tools/harness-thci/OpenThread_WpanCtl.py

Wpanctl THCI might returns wrong RLOC address when `RLOC16 == 0` due to incorrect call to `.lstrip('0x')`. 
We use `.lstrip('0x')` to strip `'0x'` at the beginning of a hex string, however this is not correct when the hex string is `'0x0'`, because `'0x0'.lstrip('0x') == ''`
**This PR fixes all incorrect calls to `.lstrip('0x')`.** There are 3 different kinds of fix:
- `s.lstrip('0x')` replaced by `self.__lstrip0x(s)` (`lstrip_0x` is a correct implementation of stripping '0x' at the beginning of a string)
- `hex(v).rstrip('L').lstrip('0x')` replaced by `'%x' % v`
- `hex(v).lstrip('0x').zfill(4)` replaced by `'%04x' % v`

[thci] fix wrong call to .lstrip('0x')

---

src/core/mac/mac.cpp

This PR contains a group of smaller changes/enhancments in `Mac` module:
**[mac] simplify ProcessReceiveSecurity (#4384)**
This method simplifies `Mac::ProcessReceiveSecurity()` method, by
initializing `error` as `OT_ERROR_SECURITY` and only setting it to
`OT_ERROR_NONE` after all checks are passed (allowing checks to use
`VerifyOrExit()` without updating of `error` variable).
**[mac] use VerifyOrExit for simpler checks (#4384)**
**[mac] simplify handling of Mac::Filter and fixed RSS (#4384)**
**[mac] update/clean-up comments (#4384)**

[mac] multiple smaller changes/enhancements

---

tools/harness-automation/autothreadharness/harness_case.py
tools/harness-automation/autothreadharness/settings_sample.py
tools/harness-automation/cases/leader_9_2_9.py
tools/harness-automation/cases/med_6_3_2.py
tools/harness-automation/cases/med_9_2_10.py
tools/harness-automation/cases/reed_5_6_7.py
tools/harness-automation/cases/router_9_2_10.py
tools/harness-automation/cases/router_9_2_9.py
tools/harness-automation/cases/sed_9_2_10.py
tools/harness-automation/cases_R140/leader_9_2_9.py
tools/harness-automation/cases_R140/med_6_3_2.py
tools/harness-automation/cases_R140/med_9_2_10.py
tools/harness-automation/cases_R140/reed_5_6_7.py
tools/harness-automation/cases_R140/router_9_2_10.py
tools/harness-automation/cases_R140/router_9_2_9.py
tools/harness-automation/cases_R140/sed_9_2_10.py

1. RF-shield needed cases 6.3.2, 5.6.7, 9.2.9, 9.2.10 automation both on CV and IV testbed
2. Added DUT2_DEVICE and SHIELD_GOLDEN_DEVICES in settings file which list the second DUT and golden devices in RF-box. The emulation of the required shielding/unshielding test environment is achieved by controlling the programmable RF-switch ( example: Agilent 3499B + HP 44476A microwave switch module) via scripts (configure SHIELD_CONTROLLER_TYPE and  SHIELD_CONTROLLER_PARAMS in settings file ) and final impacting the IN/OUT signal of the devices in the box.
3. Added case_need_shield and device_order parameters in RF-shield needed case scripts for checking if test case needs to use RF-shield box and its device order on the Test Harness Testbed page.

[harness-automation] support RF-shield test cases

---

src/core/common/code_utils.hpp
tests/unit/Makefile.am
tests/unit/test_address_sanitizer.cpp
tests/unit/test_aes.cpp
tests/unit/test_child.cpp
tests/unit/test_child_table.cpp
tests/unit/test_hdlc.cpp
tests/unit/test_heap.cpp
tests/unit/test_hmac_sha256.cpp
tests/unit/test_ip6_address.cpp
tests/unit/test_link_quality.cpp
tests/unit/test_linked_list.cpp
tests/unit/test_lowpan.cpp
tests/unit/test_mac_frame.cpp
tests/unit/test_message.cpp
tests/unit/test_message_queue.cpp
tests/unit/test_ncp_buffer.cpp
tests/unit/test_network_data.cpp
tests/unit/test_priority_queue.cpp
tests/unit/test_pskc.cpp
tests/unit/test_spinel_decoder.cpp
tests/unit/test_spinel_encoder.cpp
tests/unit/test_string.cpp
tests/unit/test_timer.cpp
tests/unit/test_toolchain.cpp
tests/unit/test_util.cpp
tests/unit/test_util.h
tests/unit/test_util.hpp

This PR contains a bunch of smaller commits all related to unit-tests:
**[unit-test] allow project to specify platform log config in unit tests (#4367)**
This commit removes the hard-coded `OPENTHREAD_CONFIG_LOG_PLATFORM=0`
configuration in the unit test makefile. This allows the project build
to specify whether the platform logging should be enabled in unit
tests or not (and removes the complier warning for possible re-definition
of this configuration option).
**[unit-test] add a common function to dump buffer content (#4367)**
This commit updates `test_utils.hpp/cpp` to include a common helper
function `DumpBuffer` to print the content of a buffer (as hex and char string)
to screen. It also removes unused helper functions and use of STL header
files and types.
**[unit-test] use …

[tests] multiple enhancements/clean-ups

---

CMakeLists.txt
examples/platforms/cc2538/CMakeLists.txt
examples/platforms/posix/CMakeLists.txt
tests/toranj/build.sh

**[cmake] add OT_CONFIG to specify project core config header file (#4374)**
This commit adds new parameter `OT_CONFIG` to main `CMakeLists.txt`
file. This parameter allows users to specify a project-specific core
config header file (mapped to `OPENTHREAD_PROJECT_CORE_CONFIG_FILE`)
during build configuration.
The default value for this parameter is "none". When not specified
(value is "none"), a platform cmake file may choose to change
`OT_COFNIG` variable to provide its own core config header file. This
commit updates platform 'posix' and 'cc2548' cmake files to provide
platform specific header files when `OT_CONFIG` is not specified by
user.
------
**[toranj] add cmake option to build script (#4374)**
This commit adds a `cmake` option to the `build.sh` to …

[cmake] add OT_CONFIG to specify project core config header file

---

src/core/common/linked_list.hpp
src/core/net/netif.cpp
src/core/net/netif.hpp
tests/unit/Makefile.am
tests/unit/test_linked_list.cpp
tests/unit/test_netif.cpp

This PR contains three related commits.
**[linked-list] add Find() and GetTail() methods (#4388)**
The `LinkedList::Find()` method searches for a given entry in the
linked list and if found returns a pointer to the previous entry
behind it. The `LinkedList::GetTail()` returns the tail of the list
(last entry in the list). This commit also updates the unit test
`test_linked_list` to verify the behavior of newly added methods.
**[netif] allow addition of external multicast addresses in any state (#4388)**
This commit updates the Netif's handling of multicast addresses to
allow user to subscribe to (or unsubscribe from) an external multicast
address in any state. This aligns the behavior of external multicast
addresses with how external unicast addresses are handled (user can
already …

[netif] allow addition of external multicast addresses in any state

---

.travis/script.sh
src/ncp/example_vendor_hook.cpp

This PR contains 3 commit related to ncp vendor hook example:
- [ncp-vendor-hook] fix example code to use new NcpBase method (#4405)
- [travis] check vendor ncp hook example build under posix (#4405)
- [ncp-vendor-hook] update example to show how to subclass (#4405)

[ncp-vendor-hook] fix example code, update example, add travis build

---

src/posix/platform/radio_spinel.hpp

`mWaitingKey != SPINEL_PROP_LAST_STATUS` means the NCP is waiting for a spinel
response from RCP. When `mWaitingKey` is set to `SPINEL_PROP_LAST_STATUS` and
`HdlcInterface` receives a `ChildIdResponse` message from RCP，`HdlcInterface`
calls the function `Decode()` to decode the received HDLC frame. Then the decoded
spinel frame is sent to `RadioSpinel` module. Because the function `IsSafeToHandleNow()`
returns true now. The `RadioSpinel` sends the received `ChildIdResponse` frame to
up layer immediately. Then the MLE layer calls the function `otPlatRadioSetShortAddress()`
to set short address. The function `otPlatRadioSetShortAddress()` sends spinel
frame `MAC_15_4_SADDR` to RCP and waits for the spinel response. When the
response frame is received, the `HdlcInterface` calls the function …

[posix-host] update IsSafeToHandleNow() to avoid re-entrant issue

---

src/core/net/ip6.cpp
src/core/net/ip6.hpp
src/core/net/ip6_headers.hpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp
src/core/thread/lowpan.cpp
src/core/thread/lowpan.hpp
tests/unit/test_lowpan.hpp

To avoid operating on unspecified values.

[ip6] replace IpProto type with uint8_t

---

src/ncp/spinel.c
src/ncp/spinel.h

This PR contains smaller changes/fixes in spinel:
**[spinel] define spinel_prop_key_t and spinel_status_t as uint32_t (#4402)**
This commit defines `spinel_prop_key_t` and `spinel_status_t` as
`uint32_t` instead of `enum` value. This allows these types to
take values not included in `enum` (e.g., vendor or experimental
values) and addresses "out-of-range enumeration value" compiler
warnings.
**[spinel] add spinel_command_t & spinel_capability_t types as uint32_t (#4402)**
**[spinel] relax spinel_mcu_power_state_to_cstr input to allow any uint8_t (#4402)**
**[spinel] remove unused type definition (spinel_cit_t) (#4402)**

[spinel] use direct uint type instead of enum

---

src/posix/main.c

This PR sets logging level just after parsing command line arguments so
that dying messages during initialization can be printed.

[posix-host] set logging level early

---

.travis/script.sh
src/ncp/ncp_base.cpp
src/ncp/ncp_base.hpp
src/ncp/ncp_base_dispatcher.cpp
src/ncp/ncp_base_mtd.cpp

The big `switch` generates a lot of code on some compilers. This PR
drops the switch way to find getters and setters, instead a biinary
search is used to find property handlers. This requires all handlers are
defined in a **sorted** array.

[ncp] reduce size by searching property handlers

---

src/core/common/logging.cpp

This PR reduces the code size of `otThreadErrorToString` by about 900 bytes

[logging] reduce otThreadErrorToString code size

---

script/bootstrap

`brew --prefix` is the correct way to find brew package location:
```shell
☁  ~  brew --prefix --help
Usage: brew --prefix [formula]
Display Homebrew's install path. Default: /usr/local on macOS and
/home/linuxbrew/.linuxbrew on Linux.
If formula is provided, display the location in the cellar where formula is
or would be installed.
-h, --help                       Show this message.
```
```shell
☁  ~  brew --repo --help  
Usage: brew --repository, --repo [user/repo]
Display where Homebrew's .git directory is located.
If user/repo are provided, display where tap user/repo's directory
is located.
-h, --help                       Show this message.
```

[script] fix linking clang-format-6.0 on Mac OS X

---

src/ncp/ncp_base.hpp
src/ncp/ncp_base_dispatcher.cpp

C++11 constexpr doesn't support local variables and loop. This PR uses
recursive way to assert handlers are sorted.
C++11 static_assert requires a message, this PR adds the missing
messages to static_assert calls.

[ncp] conform with c++11 constexpr and static_assert

---

src/posix/platform/Makefile.am
src/posix/platform/hdlc_interface.cpp
src/posix/platform/hdlc_interface.hpp
src/posix/platform/radio_spinel.cpp
src/posix/platform/radio_spinel.hpp
src/posix/platform/spinel_interface.hpp

This commit abstracts the API between radio_spinel and hdlc_interface into a common interface `spinel_interface`.  Users can use this interface to add new transport layers to send/receive spinel frames.

[posix-host] add spinel_interface to extend transport layers

---

src/core/thread/network_diagnostic_tlvs.hpp

The main reason for this PR is that I got failure when compiling ot-br on OpenWRT:
>   CXX      otbr_agent-otubus.o
> In file included from ../../third_party/openthread/repo/src/core/thread/key_manager.hpp:45:0,
>                  from ../../third_party/openthread/repo/src/core/meshcop/meshcop_tlvs.hpp:54,
>                  from ../../third_party/openthread/repo/src/core/thread/network_diagnostic_tlvs.hpp:46,
>                  from otubus.cpp:43:
> ../../third_party/openthread/repo/src/core/common/timer.hpp:77:40: error: 'Time' has not been declared
>      static const uint32_t kMaxDelay = (Time::kMaxDuration >> 1);
>                                         ^~~~
> ../../third_party/openthread/repo/src/core/common/timer.hpp:110:5: error: 'Time' does not name a type; did you mean 'Timer'? …

[network-diagnostic] remove useless include

---

src/core/api/thread_api.cpp
src/core/mac/data_poll_handler.cpp
src/core/mac/data_poll_sender.cpp
src/core/mac/data_poll_sender.hpp
src/core/thread/address_resolver.cpp
src/core/thread/child_table.cpp
src/core/thread/child_table.hpp
src/core/thread/indirect_sender.cpp
src/core/thread/key_manager.cpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_router.cpp
src/core/thread/network_diagnostic.cpp
src/core/thread/src_match_controller.cpp
src/core/thread/topology.cpp
src/core/thread/topology.hpp
src/core/utils/child_supervision.cpp
tests/unit/test_child_table.cpp

This PR contains a group of related  smaller commits to simplify the handling of parent and parent candidate from MLE: 
**[child-table] move StateFilter definition to Neighbor**
**[topology] move IsStateValidOrAttaching to Neighbor**
**[data-poll-sender] add GetParent()**
This commit changes the `Mle::GetParentCandidate()` to return a
reference to the parent candidate and moves the selection logic
between parent or parent candidate when sending data polls to
`DataPollSender` from the newly added `GetParent()` method.
**[mle] update Mle::GetParent() to return reference**
**[mle] add Mle::IsAttaching() method**

[mle] change GetParent and GetParentCandidate

---

src/core/thread/mle.cpp
src/core/thread/mle_router.cpp

A device's request to register network data information is triggered
by a call to NetworkData::Local::SendServerDataNotification().
However, the call was only made by devices operating in the router
or leader roles.
This commit moves the call so that network data registration is
triggered in the child role, in addition to the router and leader
roles.
Resolves #4424

[network-data] support registration on child devices

---

src/core/api/dataset_api.cpp

otDatasetIsCommissioned API first reads out the Active Dataset from
settings (i.e. non-volatile storage). However, the existing
implementation does not check if the Active Dataset is actually
present, as indicated by OT_ERROR_NOT_FOUND.
This commit adds a necessary check and returns false if the Active
Dataset is not present.

[dataset] check if dataset is present in otDatasetIsCommissioned

---

examples/platforms/utils/logging_rtt.c
examples/platforms/utils/logging_rtt.h

Buffer configuration is **fixed at compile time** for BufferIndex=0. See `SEGGER_RTT_ConfigUpBuffer`:
https://github.com/openthread/openthread/blob/5b0af03afb8e70e8216f69623bd18bcd3d4b8b43/third_party/jlink/SEGGER_RTT_V640/RTT/SEGGER_RTT.c#L1415-L1435

[platform/utils] RTT: remove non-functional config of Up Buffer's size

---

src/core/common/message.cpp
src/core/common/message.hpp
src/core/common/tlvs.cpp
src/core/common/tlvs.hpp
src/core/meshcop/announce_begin_client.cpp
src/core/meshcop/border_agent.cpp
src/core/meshcop/commissioner.cpp
src/core/meshcop/dataset.cpp
src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager_ftd.cpp
src/core/meshcop/energy_scan_client.cpp
src/core/meshcop/joiner.cpp
src/core/meshcop/joiner_router.cpp
src/core/meshcop/leader.cpp
src/core/meshcop/panid_query_client.cpp
src/core/thread/address_resolver.cpp
src/core/thread/energy_scan_server.cpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp
src/core/thread/network_data.cpp
src/core/thread/network_data_leader_ftd.cpp
src/core/thread/network_diagnostic.cpp
src/core/thread/panid_query_server.cpp

This PR adds AppendTo(Message) to Tlv, so that Message doesn't depend
on Tlv any more. This allows a concrete Tlv overriding its
serialization. This was discussed in #4104.

[tlv] add AppendTo to resolve mutual dependency

---

examples/platforms/nrf528xx/src/radio.c

This PR ensures that TX Power return via `otPlatRadioGetTransmitPower` is one that is actually set in the register. E.g. even if TX power is set to 100 via `otPlatRadioSetTransmitPower`, the maximum power is 8 for nRF52840.

[nrf528xx] return the TX power which was actually set in the register

---

src/core/thread/mle_router.cpp

There is chance for below scenario (as shown in below screenshot)
1) Device newly becomes router and sends multicast Link Request
(challenge1),
2) Device receives MLE advertisement from one neighbor, and sends
unicast Link Request (challenge2),
3) The neighbor ignores the unicast link Request in 2) and sends
out Link Accept and Request message as response for 1)
4) Device would drop the Link Accept adn Request message
in 3) as it compares the Response TLV value with challenge2, which
in fact matches challenge1.
The link between Device and the neighbor could not be established until
Device receives next MLE advertisement from the neighbor.
This commit suppresses unicast Link Request in 2) if there is multicast
Link Request ongoing. Thus the three-handshakes link sync could go well.

[mle] link sync enhancement

---

src/core/mac/mac_frame.cpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder_ftd.cpp

----
Background on this: 
Originally the frame length was `uint8_t`, but  PR https://github.com/openthread/openthread/pull/3939 changed the MAC frame length (from `uint8_t` to `uint16_t`) to enable support for different radio MTU sizes. This fix is needed to allow multi radio link support and TREL (from #4440) to use larger MTU sizes.

[mesh-forwarder] fix incorrect cast to uint8_t when setting frame length

---

include/openthread/coap.h
src/core/api/coap_api.cpp
src/core/coap/coap.cpp
src/core/coap/coap_message.cpp
src/core/coap/coap_message.hpp

As discussed in https://github.com/openthread/openthread/pull/4396#discussion_r357525060, this adds a `otCoapOptionIterator` structure which the user can use to iterate over the CoAP options of a `ot::Coap::Message` object without influencing any of the properties of that object.
Multiple `otCoapOptionIterator` structures may operate on the same `ot::Coap::Message` object without interference.
The code has been tested on nRF52840.

[coap] add otCoapOptionIterator and related API functions

---

examples/Makefile-efr32mg12
examples/Makefile-efr32mg21
examples/platforms/efr32mg12/Makefile.am
examples/platforms/efr32mg12/Makefile.platform.am
examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/Makefile.am
examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/Makefile.am
examples/platforms/efr32mg21/Makefile.am
examples/platforms/efr32mg21/Makefile.platform.am
examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-ftd/Makefile.am
examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-mtd/Makefile.am
third_party/silabs/Makefile.am

Fix for build issue with recent change to using Silicon Labs SDK v2.7.

[efr32] remove SDKVERSION in makefiles to fix SDK v2.7 build

---

src/posix/Makefile.am
src/posix/platform/Makefile.am
tests/unit/Makefile.am

This helps address undefined config macro warnings.

[build] define OPENTHREAD_FTD/MTD/RADIO in posix-app and unit test makefiles

---

src/core/thread/lowpan.cpp
src/core/thread/lowpan.hpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder.hpp
src/core/thread/mesh_forwarder_ftd.cpp
tests/unit/test_lowpan.cpp

This PR contains a group of related commits changing how `Lowpan::MeshHeader` is parsed and generated and its use in `MeshForwarder`. 
**[lowpan] simplify MeshHeader and its use in MeshForwarder**
This commit updates the `Lowpan::MeshHeader` class to provide methods to parse/write the Mesh Header from/to a given frame or message. The `MeshHeader` no longer provides a direct representation of the header (instead, it contains all fields required to generate the header). This is mainly due to fact the header format itself may vary depending on the "hops left" value. This change also removes the need for the `MeshHeader` to be a packed `OT_TOOL_PACKED` structure.
**[mesh-forwarder] skip mesh header immediately after parsing it**
This commit updates `HandleMesh()` method to skip the mesh …

[lowpan] simplify MeshHeader/FragHeader and their use in MeshForwarder

---

src/posix/client.c

Build failed because `write` was declared with attribute `warn_unused_result`.

[posix-host] explicitly ignore return value on write

---

examples/platforms/efr32mg12/openthread-core-efr32-config.h
examples/platforms/efr32mg12/radio.c

This is the first of 3 PR addressing the efr32mg12 radio driver.
PR# 1: 
- Features:
* 18b70b2 Implemented get/set CcaEnergyDetectThreshold.
- Sniffer mode fix:
* 981ee39 Implemented RX timestamping (at the SFD reception).
* 21f442a Handled promiscuous mode for ACK packets (ACK packets were discarded for sniffer mode).
- Misc bug corrections:
* 1042eda Corrected macAckWaitDuration (from 894us to 864us; it was a typo).
* 18b70b2 Honor mMaxCsmaBackoffs.
* f4dbf62 Signalled event pending when failed to start TX (event pending was not signalled for this case, even if TX operation was actually finished).
- Minor enhancements
* 1027145 Removed duplicate calls of RAIL functions which were called once per band, and did not need to (the call was exactly the same for all bands).
* f2e2755 Correct …

[efr32] Enhancements to radio driver (1/3)

---

.codecov.yml

From https://docs.codecov.io/docs/ignoring-paths, `third_party/*` will not recursively ignore all files in `third_party`. This PR changes `.codecov.yml` to use the correct pattern `third_party/**/*`.

[codecov] ignore third_party code

---

src/core/meshcop/joiner.cpp

This PR fix the bug that the `finalize message` will be prematurely freed if the joiner is started at the second time without waiting for the finish of the first initiation.

[meshcop] fix premature free of finalize message

---

examples/platforms/efr32mg12/radio.c

This is the second of 3 PRs addressing the efr32mg12 radio driver.
PR# 2: Implements correctly setting `mAckedWithFramePending` (See #4358).
**The idea is the following:** when receiving an IEEE802.15.4 Data Request Command, RAIL generates an event and calls `RAILCb_Generic` as early as possible (even before the packet is fully received; i.e. the CRC could be still wrong), from interrupt context.
In `RAILCb_Generic`, the driver calls `ieee802154DataRequestCommand`, which in turn decides whether to set the Frame Pending flag for the outgoing ACK, by analysing the soft source match table. If the Frame Pending flag is set, we have to report `mAckedWithFramePending = true` when we pass the Data Request Command packet to the upper layers.
Since the Data Request Command packet is held in the …

[efr32] Enhancements to radio driver (2/3)

---

src/core/api/thread_api.cpp
src/core/thread/address_resolver.cpp
src/core/thread/address_resolver.hpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_router.cpp
src/core/thread/network_data.cpp
src/core/thread/network_diagnostic.cpp
src/core/thread/router_table.cpp

This PR contains a group of smaller changes/enhancements mainly in `Mle`, adding/updating log  messages and renaming the static methods which convert from one simple type/value to another:
- [mle] log rlco16 changes 
- [mle] update route table log message 
This commit updates the route table log message to include if link
is established with router or not (router is a neighbor). Also the
`0xffff` is printed as next hop if it is invalid and we indicate
if the entry is for the device itself.
- [mle-router] use routerId as variable name 
- [mle] rename static method to Rloc16FromRouterId() from GetRloc16() 
This commit renames the static `Mle` method which derives RLOC16
from a given Router ID to `Rloc16FromRouterId()` from `GetRloc16()`.
This helps distinguish this method from other …

[mle] misc - log msg change, static method renames

---

src/cli/cli_uart.cpp

This PR emits SIGINT on ctrl-c so that gdb can work as expected.

[cli] emit SIGINT on ctrl-c

---

examples/platforms/posix/radio.c
src/posix/platform/radio_spinel.cpp
src/posix/platform/radio_spinel.hpp

This PR implements otPlatRadioGetState() on POSIX platforms, including
simulation and posix-host app.
This is for debugging purpose.

[posix-host] add otPlatRadioGetState()

---

.travis.yml
.travis/script.sh
tests/toranj/build.sh
tests/toranj/start.sh

Gcov sometimes cannot correctly find source files when the code is
configured with relative path. This PR enables using absolute path to
run toranj tests.

[toranj] improve code coverage by using absolute path

---

src/core/api/link_api.cpp
src/core/common/instance.cpp
src/core/common/instance.hpp
src/core/mac/mac.cpp
src/core/mac/mac.hpp
src/core/mac/mac_frame.hpp
src/core/thread/energy_scan_server.cpp
src/core/thread/energy_scan_server.hpp
src/core/thread/panid_query_server.cpp
src/core/thread/panid_query_server.hpp
src/core/utils/channel_monitor.cpp
src/core/utils/channel_monitor.hpp

This commit changes the energy and active scan callback handlers in
`Mac` class to make them follow the model used by external OpenThread
scan APIs. This in turn simplify their use and removes the need to
save energy/active callbacks and their context in `Instance` object.

[mac] simplify scan handlers

---

examples/platforms/efr32mg12/brd4161a/board_config.h
examples/platforms/efr32mg12/brd4166a/board_config.h
examples/platforms/efr32mg12/brd4170a/board_config.h
examples/platforms/efr32mg12/brd4304a/board_config.h
examples/platforms/efr32mg12/radio.c

This is the last of 3 PRs addressing the efr32mg12 radio driver.
PR# 3:
- Features:
- Allow per-band PA configurations:
- Supply selection (DCDC or VBAT).
- Ramp time configuration.
- Voltage configuration.
- Bug fixes:
- Corrected PA supply selection for BRD4166A (is supplied from DCDC instead of VBAT). This could cause an incorrect output power setting.
@andrasbiro-silabs please review.
Thanks

[efr32] Enhancements to radio driver (3/3)

---

src/core/mac/mac_frame.hpp

----
We already have `OT_TOOL_PACKED_END` for `Beacon` class. Most toolchains define `OT_TOOL_PACKED_BEGIN` as empty so it worked fine on those.

[mac-frame] add missing OT_TOOL_PACKED_BEGIN to Beacon class

---

script/bootstrap

The current source for arm-none-eabi-gcc on MacOS is an unofficial tap from PX4, drone flight control software. Instead, openthread should be using ARM's [official toolchain tap](https://github.com/ARMmbed/homebrew-formulae).

[build] change macOS bootstrapped GCC to official ARM brew tap

---

tests/toranj/test-012-multi-hop-traffic.py

This commit updates tornaj `test-012-multi-hop-traffic` to make it
more robust by waiting for entire chain topology to be discovered
(router table to be fully updated) before starting message exchange.
This should help with rare failures of this test, which happen when an
address query response is received before the "next hop" for the
destination router is discovered (through Link Advertisement
exchanges) on the first router `r1`.

[toranj] update test-012-multi-hop-traffic

---

src/core/net/ip6_address.cpp
src/core/net/ip6_address.hpp

This PR contains a group of smaller commits all in `Ip6::Address`.
**[ip6-address] use larger data fields when checking against constants**
This commit changes methods in `Ip6::Address` class to use larger
fields (`m16` or `m32`) for comparing portions of address sequence
against constant values when possible.
**[ip6-address] simplify IsAnycastServiceLocator()**
This change ensures we avoid comparing values with host-swapped
constants.
**[ip6-address] remove undefined/unused method declaration**
**[ip6-address] inline very simple methods**
This commit inlines the very simple methods (containing a single
basic operation) in `Ip6::Address` class.
------------
Adding a note regarding the second commit: The original code for `IsAnycastServiceLocator()` contained:
```
(mFields.m16[7] >= …
```

[ip6-address] multiple enhancements

---

src/core/thread/mle.cpp
src/core/thread/mle.hpp

This commit inlines and removes `ResetParentCandidate()` method.

[mle] simplify how parent candidate is cleared

---

src/core/net/ip6.cpp

This commit updates how the `otMessagePriority` enumeration variable
is updated in `otMessageSettings` structure. This addresses an issue
where the enum variable was being treated as an `uint8_t` which may
not necessarily be correct (since complier can choose any integral
type which covers all the enumerator values as the underlying storage
for an unscoped enumeration type).
------
`*reinterpret_cast<uint8_t *>(&settings.mPriority)` should work ok on most platforms/toolchains. I think it would be incorrect only if the platform is big-endian and complier uses a larger integral type (than `uint8_t`) for the enum variable.  A bug but not that critical :)

[ip6] fix conversion of enum value to uint8_t

---

src/ncp/hdlc.hpp
src/posix/client.c
src/posix/console_cli.h
src/posix/main.c
src/posix/platform/Makefile.am
src/posix/platform/alarm.c
src/posix/platform/entropy.c
src/posix/platform/hdlc_interface.cpp
src/posix/platform/hdlc_interface.hpp
src/posix/platform/logging.c
src/posix/platform/misc.c
src/posix/platform/netif.cpp
src/posix/platform/openthread-posix-config.h
src/posix/platform/platform-posix.h
src/posix/platform/radio_spinel.cpp
src/posix/platform/radio_spinel.hpp
src/posix/platform/settings.cpp
src/posix/platform/sim.c
src/posix/platform/spi_interface.cpp
src/posix/platform/spi_interface.hpp
src/posix/platform/spinel_interface.hpp
src/posix/platform/system.c
src/posix/platform/uart.c
src/posix/platform/udp.cpp
tests/toranj/build.sh
tests/toranj/openthread-core-toranj-config.h

This PR contains a group of (related) commits for posix-app.
**[posix-app] add missing config header file includes**    
This commit updates how posix-app source files include the config header file to follow a similar policy as for core modules. All header files and `cpp` files that do not have a corresponding `hpp` file should include "platform-config.h" first (which itself will include the core config header). The "cpp" files which have a related "hpp" should include the related hpp file first. This way we ensure all config macro definitions are correctly included in all modules.
**[posix-app-config] add UART/SPI config macros and their default value**    
This addresses undefined macro warnings when building posix-app.
**[toranj] move posix-app config defs into header file from build …

[posix-app] update config header file includes

---

src/core/common/settings.cpp
src/core/common/settings.hpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp

The choice of little-endian was made for the following reasons:
- The existing encoding remains unchanged for settings unchanged on little-endian platforms.
- Eliminates any code overhead for little-endian platforms.
Resolves #4461

[settings] encode as packed little endian structs

---

src/cli/cli.cpp
src/cli/cli.hpp

This commit updates/enhances the CLI `ping` command. It adds the
feature to track and match the ICMPv6 echo requests and responses
using an identifier. Each `ping` command will use a new value as the
identifier. A received ICMPv6 echo response not matching the current
identifier is ignored. This commit also makes the following (smaller)
changes:
- renames the ping related member variables as `mPing{Name}`,
- defines  constants for default ping parameters,
- changes `ping` to use public OT APIs/definition (instead of core
methods).
---
This should help address https://github.com/openthread/openthread/issues/4531.

[cli] use ICMPv6 Echo Request ID to match Responses

---

examples/platforms/nrf528xx/src/radio.c

This PR aligns `otPlatRadioGetRssi` implementation with the latest changes to radio driver.
Without this change, for example, Channel Monitor and Energy Scanning with duration of 0 (`energy scan 0` command) does not work.

[nrf528xx] fix synchronous GetRssi functionality

---

src/core/mac/sub_mac.cpp

This fixes the implementation of Energy Scanning in case the platform does not support it, but uses timer with microsecond resolution. This is not the case with nRF528xx but found it during code inspection.
I've verified that after removing `OT_RADIO_CAPS_ENERGY_SCAN` capability, the Energy Scan now works correctly.

[sub-mac] fix incorrect timer configuration for energy scanning

---

src/core/common/settings.cpp
src/core/common/settings.hpp
src/core/meshcop/dataset.hpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp

If the setting value read from non-volatile is smaller than the
expected size, make sure to zero out the remainder of the buffer to
ensure that the additional fields are initialized.

[settings] zero out any trailing bytes in buffer

---

include/openthread/coap.h
src/core/api/coap_api.cpp
src/core/coap/coap_message.cpp
src/core/coap/coap_message.hpp

This small feature addition is two helper functions to encode the Block1 and Block2 uint options described in RFC7959. This should help the effort in #4213 and #4247.

[coap] Add helper functions to encode coap block options

---

src/core/thread/network_data_leader_ftd.cpp

It is posisble for a leader to receive SVR_DATA.ntf messages
attempting to register with a router ID that is not valid on the
leader.
This commit does not allow registering network data with invalid
router IDs to avoid having stale network data that persists.
Addresses the issue raised by @mwilniewiec in https://github.com/openthread/openthread/issues/4472#issuecomment-584217141.

[network-data] add check for invalid router IDs

---

src/cli/README_DATASET.md

Resolves error reported by @markus-becker-tridonic-com in https://github.com/openthread/openthread/pull/4330.

[docs] correct `dataset activetimestamp` example

---

src/ncp/spinel.c

If strnlen is a normal function, the current code will result in duplicate definition error.

[spinel] fix when strnlen is not a macro

---

src/core/thread/address_resolver.cpp
src/core/thread/address_resolver.hpp

This PR includes four individual commits associated with the address resolver module. It should resolve #4535. It's the easiest to review them one-by-one.
**[address-resolver] accept multicast Address Error Notification**
This commit enables processing of Address Error Notification sent as non-confirmable CoAP multicast message. The code change relaxes the verification of CoAP type.
_____________________________________________________
**[address-resolver] fix last transaction time of entry created by packet inspection**
For cached entries created based on snooping message, the last transaction time was incorrectly set.
_____________________________________________________
**[address-resolver] dequeue a message from resolving queue before invalidate the entry**
During code inspection, I …

[address-resolver] resolve several issues

---

Android.mk

The macro OPENTHREAD_POSIX_RCP_UART_ENABLE should be defined for all
builds, not only for CI tests.
This PR also sorts the definitions and removes duplicate definitions.

[android] move OPENTHREAD_POSIX_RCP_UART_ENABLE

---

src/core/coap/coap_message.cpp

Fix for #4513
Accidentally introduced bug when checking for valid block size. My bad!
I've tested this fix with an outgoing block1 transfer.

[coap] fix comparison with block size validity check

---

third_party/silabs/Makefile.am

Restore the lines accidentally removed by commit 609665d0174042d6840a7d221cbc4dfd2a1f9b6f

[efr32] remove -Wundef for SDK sources

---

src/core/thread/mle.cpp

Current Thread certification needs Parent information even after the
node already become a router or leader. This PR sets parent state to
invalid to indicate information in mParent should not be used in normal
cases.

[mle] invalidate parent if not child

---

examples/platforms/cc1352/diag.c
examples/platforms/cc2538/diag.c
examples/platforms/cc2650/diag.c
examples/platforms/cc2652/diag.c
examples/platforms/efr32mg12/diag.c
examples/platforms/efr32mg13/diag.c
examples/platforms/efr32mg21/diag.c
examples/platforms/gp712/diag.c
examples/platforms/kw41z/diag.c
examples/platforms/nrf528xx/src/diag.c
examples/platforms/posix/diag.c
examples/platforms/qpg6095/diag.c
examples/platforms/samr21/diag.c
include/openthread/diag.h
include/openthread/platform/diag.h
src/cli/cli.cpp
src/core/api/diags_api.cpp
src/core/diags/factory_diags.cpp
src/core/diags/factory_diags.hpp
src/posix/platform/radio_spinel.cpp
tests/fuzz/fuzzer_platform.c
tests/scripts/thread-cert/test_diag.py

Always output command result, i.e. "Done" on success, error message
otherwise.
Factory commands also follow the same pattern. Their existing error
messages are not removed for backward compatibility consideration.

[cli] always output command result

---

include/openthread/Makefile.am

openthread/config is just used when building OpenThread, and does not
contains OpenThread API.

[build] do not export openthread/config.h

---

src/core/thread/mle_router.cpp

Commit a8638d7 added logic to invalidate the parent upon a role
change. However, when upgrading from child to router, the existing
implementation updates the role before copying the parent into into
the router table. As a result, a router may not have any connectivity
with the rest of the partition until after additional MLE exchanges.
This commit marks the newly created router entry as valid so that the
router retains connectivity.

[mle] mark former parent as valid after becoming router

---

src/core/common/locator.hpp
src/core/mac/mac.cpp
src/core/mac/mac.hpp
src/core/mac/sub_mac.cpp
src/core/mac/sub_mac.hpp
src/core/thread/address_resolver.cpp
src/core/thread/child_table.cpp
src/core/thread/link_quality.cpp
src/core/thread/link_quality.hpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp
src/core/thread/router_table.cpp
src/core/thread/topology.cpp
src/core/thread/topology.hpp
tests/unit/test_child.cpp
tests/unit/test_link_quality.cpp
tests/unit/test_platform.cpp

This PR contains a group of related commits:
**[locator] adding InstanceLocatorInit**
This commit adds a new class `InstanceLocatorInit` which is
similar to `InstanceLoator` but provides a default  constructor
(instead of a parameterized one) and allows an inheriting class to
initialize the object (set the OpenThread Instance) post constructor
call using the `Init()` method. This class is intended for types that
require a default constructor and cannot use a parameterized one. An
example of such a class is one that is used as type of a C array
element (e.g., `Neighbor`/`Child`/`Router` classes which are used as
array in `ChildTable`/`RouterTable`). The inheriting class from
`InstanceLocatorInit` should ensure that object is properly
initialized after the object is created and more …

[locator] adding InstanceLocatorInit (providing default constructor)

---

examples/platforms/efr32mg12/brd4161a/hal-config.h
examples/platforms/efr32mg12/brd4166a/hal-config.h

Fixes to build OpenThread with current and upcoming patch release of v2.7 SDK

[efr32] fix 4161a/4166a hal-config.h for upcoming v2.7 SDK patch release

---

src/ncp/Makefile.am

There should be some bug in automake when computing dependencies,
causing output error messages as following when installing:
```bash
/bin/bash: t: command not found
```
This issue is introduced in #4558.

[build] fix command t not found

---

src/core/thread/network_data_leader_ftd.cpp
tests/fuzz/fuzzer_platform.c

Reject Commissioner Dataset TLVs with extended TLV length.

[network-data] avoid buffer overrun in HandleCommissioningSet()

---

src/core/coap/coap.cpp
src/core/coap/coap_message.cpp

Per RFC 7252:
- Treat invalid token length as a message format error.
- Rejecting a Confirmable message is effected by sending a matching
Reset message and otherwise ignoring it.

[coap] validate token length on received messages

---

src/core/coap/coap.cpp
src/core/coap/coap.hpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp
src/core/thread/network_data.cpp
src/core/thread/network_data.hpp
src/core/thread/network_data_local.cpp
src/core/thread/router_table.cpp

Rebase and refine previous updates, also introduce network data check for invalid child entry when network data changes according to feedbacks.
See per commit message below for details.
commit1
[core] clear cached coap requests with rloc source when rloc changes
This commit helps to reduce unnecessary CoAP retransmission when rloc
changes. When comes to SRV_DATA.ntf, it also helps to avoid invalid
network data registration. Take the issue reported in #4472 as example,
in a Thread Network with packet loss, the child server may switch parents
frequently, there might be cached SRV_DATA.ntf including old rloc16,
both the cached one and new one might be sent after switched, causing
Leader contain two server entries in the Network Data.
commit2
[network_data] reuse `mLastAttempt` for the …

[network-data] remove stale network data with best efforts

---

src/core/api/coap_api.cpp
src/core/coap/coap.cpp
src/core/coap/coap.hpp
src/core/coap/coap_secure.cpp
src/core/coap/coap_secure.hpp

**Edit**: New pushed commit rebased all changes on master and squashes them into a single commit. There are some new changes as well:
This commits contains the following changes:
- Declare `Metadata` as a private inner class of `CoapBase`. Also replace constructors with `Init()` method and removes the default empty constructor (since it is not needed).
- Add `ResponseMetadata` as private inner struct in `ResposeQueue`.
- Simplify `ResponsesQueue::FindMatchedResponse()`.
- Declare `CoapBase::Sender` as a protected type.
- Use initializer list in `CoapBase` constructor.
- Use `for` loop for iterating over messages in a message queue.
- Define `ResponseHandler` and `RequestHandler` types.
- Update `TxParameters` class. Add helper method for common calculation of span window, and remove …

[coap] smaller enhancements

---

.travis/script.sh
script/test
src/core/thread/mle.cpp
src/core/thread/mle.hpp
tests/scripts/thread-cert/common.py
tests/scripts/thread-cert/mle.py
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/test_mle.py
tests/scripts/thread-cert/thread_cert.py
tests/scripts/thread-cert/v1_2_test_parent_selection.py

This PR depends on #4325, with the last two commits introducing parent selection rules and relative tests, specifically
The first commit
[mle] update parent selection rules
This commit updates parent selection rules according to Thread 1.2
Specification section 4.5.2.1, which supplements serveral Child Impacting
rules to existing rules defined in Thread 1.1 Specification.
These additional rules are not wrapped by `OPENTHREAD_THREAD_VERSION_1_2`
macro as Thread 1.1 has no restrictions regarding introducing extra rules.
The second commit
[travis] test parent selection rules
This commit has five scenarios to test the four Mesh Impacting
Criteria and one Child Impacting Criterion (version).

[mle] update parent selection rules

---

src/posix/main.c
src/posix/platform/radio_spinel.cpp

* signed/unsigned conversion error
* undefined behavior of embedding macros in string literal
> embedding a directive within macro arguments has undefined behavior

[posix-host] fix warnings caused by SPI arguments

---

src/posix/platform/spi_interface.cpp

On some platforms, inttypes.h is not included by other headers.

[posix-host] include inttypes.h in spi_interface.cpp

---

src/posix/platform/spi_interface.cpp

When SPI is already interrupted before select(), the wait timeout will
be set to 0, and select() will return 0 immediately if there are no new
events. As a result, cause an incorrect OT_ERROR_RESPONSE_TIMEOUT error.
This PR fixes this issue by check if data is ready before checking the
select() result.

[posix] fix handling SPI interrupts

---

src/core/meshcop/dtls.cpp

Cookies were being freed on the client when they were never allocated,
causing a hard fault.

[dtls] fix allocation and deallocation of ssl cookies

---

examples/Makefile-simulation
examples/common-switches.mk
include/openthread/coap.h
src/cli/README_COAP.md
src/cli/cli_coap.cpp
src/cli/cli_coap.hpp
src/core/api/coap_api.cpp
src/core/coap/coap.cpp
src/core/coap/coap.hpp
src/core/coap/coap_message.cpp
src/core/coap/coap_message.hpp
src/core/config/coap.h
src/posix/Makefile-posix
tests/scripts/thread-cert/Makefile.am
tests/scripts/thread-cert/config.py
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/test_coap_observe.py

The following pull request implements support for [RFC7641 Observations](https://tools.ietf.org/html/rfc7641).
Observations was based on an earlier proof-of-concept which was tested against `node-coap`.
The implementation given here has been successfully been tested with `aiocoap-client` (with OpenThread implementing the server) and with Californium (with OpenThread implementing the client), as well as between two OpenThread nodes.

[coap] add support for RFC7641

---

.travis.yml
script/test

This PR moves the package check into the first stage so that if there
are any cmake build errors jobs in stage 2 will be skipped.

[travis] move package check into lint stage

---

examples/platforms/efr32mg12/Makefile.am
examples/platforms/efr32mg12/Makefile.platform.am
examples/platforms/efr32mg12/alarm.c
examples/platforms/efr32mg12/brd4161a/board_config.h
examples/platforms/efr32mg12/brd4166a/board_config.h
examples/platforms/efr32mg12/brd4304a/board_config.h
examples/platforms/efr32mg12/crypto/efr32-mbedtls-config.h
examples/platforms/efr32mg12/diag.c
examples/platforms/efr32mg12/entropy.c
examples/platforms/efr32mg12/fem-control.c
examples/platforms/efr32mg12/flash.c
examples/platforms/efr32mg12/misc.c
examples/platforms/efr32mg12/openthread-core-efr32-config-check.h
examples/platforms/efr32mg12/openthread-core-efr32-config.h
examples/platforms/efr32mg12/platform-band.h
examples/platforms/efr32mg12/platform-efr32.h
examples/platforms/efr32mg12/radio.c
examples/platforms/efr32mg12/sleepy-demo/Makefile.am
examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/Makefile.am
examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/main.c
examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/Makefile.am
examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/main.c
examples/platforms/efr32mg12/startup-gcc.c
examples/platforms/efr32mg12/system.c
examples/platforms/efr32mg12/uart.c
examples/platforms/efr32mg13/brd4168a/board_config.h
examples/platforms/efr32mg13/openthread-core-efr32-config.h
examples/platforms/efr32mg13/radio.c

On the RAIL callback, received packets are held and passed to OT core in the event loop.
On a sleepy device, if there is nothing more to do, the OT core calls `otPlatRadioSleep` which in turn calls `RAIL_Idle(gRailHandle, RAIL_IDLE_ABORT, true)`.
If the time between `RAIL_EVENT_RX_PACKET_RECEIVED` and the call to `RAIL_Idle` is less than the turnaround + the ACK tx time, the call to `RAIL_Idle` aborts the auto-ack that was being transmitted by the radio, so there are received packets without ACK, like this:
<pre>
[0012727105] [WARN]-PLAT----: RX_ACK_RECEIVED
[0012727111] [WARN]-PLAT----: RX_PACKET_RECEIVED
[0012727112] [WARN]-PLAT----: <b>TXACK_ABORTED</b>
[0012727998] [WARN]-PLAT----: RX_ACK_RECEIVED
[0012728008] [WARN]-PLAT----: RX_ACK_RECEIVED
[0012728019] [WARN]-PLAT----: …

[efr32] Radio: don't abort current operation on switching to idle

---

src/core/thread/mle_tlvs.hpp
src/core/thread/network_diagnostic_tlvs.hpp

This PR increases readability of `RouteTlv` APIs, such as `uint8_t GetRouteCost(...)`. The argument of  `GetRouteCost` should be the index of route in `mRouteData`, but not the `Route ID`. This confused me and may confuse readers in the future.
Note: There should be no logic changes in this PR, please point out if there are.

[mle] improve readability of RouteTlv

---

src/cli/README.md
src/core/utils/parse_cmdline.cpp
src/core/utils/parse_cmdline.hpp
tests/scripts/thread-cert/node.py
tools/harness-thci/OpenThread.py

Fixing #4598
Now it's allowed to escape the space character `' '` using backslash `'\'`.
For instance:
```
> networkname Test\ Network                                                     
Done                                                                            
> networkname                                                                   
Test Network                                                                    
Done                                                                            
>
```

[cli] allow to escape separators

---

include/openthread/link.h

- Added the proper list formatting
- Removed `@sa` tags and replaced with `@ref` as needed
`@sa` tags should only be used at the very end of the full block of Doxygen comments, not inline or in a list, as this deletes any info just before or after it.
The removed `@sa` tags were being ignored since the CONFIG variables they referred to aren't part of the API Doxygen output.

[docs] update Doxygen for otMacCounters

---

src/ncp/CMakeLists.txt

---
I think this will help address https://github.com/openthread/openthread/issues/4623

[cmake] fix RCP cmake build to not include FTD/MTD source files

---

src/core/thread/network_data_leader_ftd.cpp

This PR makes sure that SVR_DATA.ntf messages are using RLOC source addresses according to Spec. 5.15.6.1. Otherwise `RegisterNetworkData` might be called with wrong RLOC16.

[network-data] add source address of SVR_DATA.ntf check

---

src/core/common/message.hpp

Since the priority levels were inverted in #3132, this comment was incorrect.

[docs] fix outdated priority comment in message.hpp

---

include/openthread/coap.h
src/core/api/coap_api.cpp
src/core/coap/coap_message.cpp
src/core/coap/coap_message.hpp

Hi all! In a recent pull request (#4396) new methods have been added to parse CoAP options using an option's number. The type these new functions receive as parameter is `otCoapOptionType`, which is an enumeration found in coap.h:
```
/**
* CoAP Option Numbers
*/
typedef enum otCoapOptionType
{
OT_COAP_OPTION_IF_MATCH       = 1,  ///< If-Match
OT_COAP_OPTION_URI_HOST       = 3,  ///< Uri-Host
...
OT_COAP_OPTION_PROXY_SCHEME   = 39, ///< Proxy-Scheme
OT_COAP_OPTION_SIZE1          = 60, ///< Size1
} otCoapOptionType;
```
This makes impossible to use vendor-specific options since the underlying type of the enum is implementation-defined, and in my particular case the option number gets casted to an 8 bit integer. I simply replaced the argument type in all protoypes with uint16_t.

[coap] Fix CoAP option data type in C/C++ API

---

include/openthread/coap.h
src/core/api/coap_api.cpp
src/core/coap/coap.cpp
src/core/coap/coap.hpp
src/core/config/coap.h

* Removed OpenThread's default CoAP configuration macro, because they are fixed values by Thread spec.
* Use 32bit multiple only to detect overflow of application CoAP transmission parameters.
* Added documentation describing conditions of valid CoAP transmission parameters.

[coap] reduce code size by avoiding using 64bit division

---

.travis/script.sh
script/test

Due to the build directory issue, Thread 1.2 relative tests could not run like https://travis-ci.org/openthread/openthread/jobs/657380743#L2143
This PR mainly includes:
first commit
`[script] fix 1.2 build and cert in test script`
second commit
`[script] support test suite mode`

[tests] fix 1.2 test env and travis

---

src/core/api/coap_api.cpp

There is "enumerated type mixed with another enumerated type" error during the iar compilation. This PR fixes that.

[coap] enum type conversion to int in otCoapBlockSizeFromExponent

---

src/core/thread/network_data.cpp

Fix the bug introduced in 5ebc583 when changing from `VerifyOrExit` to `if`

[network-data] fix to ensure resubmit delay

---

.travis/before_install.sh
etc/docker/arm32v7_ubuntu_wpantund/Dockerfile
etc/docker/codelab_otsim/Dockerfile
etc/docker/environment/Dockerfile
etc/docker/x86_ubuntu_wpantund/Dockerfile
script/bootstrap

By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

[script] optimization debian package manager tweaks

---

src/core/common/message.hpp
src/core/meshcop/joiner_router.cpp
src/core/meshcop/joiner_router.hpp

**[joiner-router] move JoinerEntrustMetadata as private inner type of JoinerRouter**
**[joiner-router] prepare Joiner Entrust msg after the delay**
This commit changes how the tx of Joiner Entrust is delayed. Instead of preparing the message (and appending metadata to it) and enqueueing it to be sent later after a delay, this commit changes the code such that only the metadata is saved and the Joiner Entrust message itself is prepared after the delay (when it is being sent).
----
I think it would be easier to check/review the commits separately.

[joiner-router] prepare Joiner Entrust msg after the delay

---

examples/Makefile-nrf52811
examples/Makefile-nrf52833
examples/platforms/nrf528xx/Makefile.am
examples/platforms/nrf528xx/nrf52811/Makefile.am
examples/platforms/nrf528xx/nrf52811/Makefile.platform.am
examples/platforms/nrf528xx/nrf52833/Makefile.am
examples/platforms/nrf528xx/nrf52833/Makefile.platform.am
examples/platforms/nrf528xx/nrf52840/Makefile.am
examples/platforms/nrf528xx/nrf52840/Makefile.platform.am
examples/platforms/nrf528xx/src/platform-nrf5-transport.h
examples/platforms/nrf528xx/src/platform-nrf5.h
examples/platforms/nrf528xx/src/system.c
examples/platforms/nrf528xx/src/transport/spi-slave.c
examples/platforms/nrf528xx/src/transport/transport-drivers.h
examples/platforms/nrf528xx/src/transport/transport.c
examples/platforms/nrf528xx/src/transport/uart.c
examples/platforms/nrf528xx/src/transport/usb-cdc-uart.c
third_party/NordicSemiconductor/Makefile.am

Transport-related functions for nrf528xx platform are moved to separated library.

[nrf528xx] Separate transport from platform

---

src/core/net/ip6_address.cpp
src/core/net/ip6_address.hpp
src/core/thread/lowpan.cpp
src/core/thread/mle.cpp
tests/unit/test_ip6_address.cpp

This commit adds a new method `SetPrefix()` in `Ip6::Address` class to
allow the prefix in an IPv6 address to be updated. Unit test
`test_ip6_address` is updated to verify behavior of new method. The
`Mle` and `Lowpan` classes are updated to use the new `SetPrefix()`
method.

[ip6-address] adding SetPrefix() to set the IPv6 address prefix

---

src/core/meshcop/meshcop_tlvs.hpp

---
Background for this change: This is more of convenience change.  Different builds of `clang-format` (version 6.0.0) behave slightly differently when sorting the `using` list.  This PR removes the `using ot::Encoding::Reverse32` to help address this. 
I notice the difference between  `clang-format version 6.0.0  (tag/google/stable/2017-11-14)`(on Mac OS X) vs. `tags/RELEASE_600/final` on other machines.

[meshcop-tlvs] remove "using ot::Encoding::Reverse32"

---

tests/scripts/thread-cert/node.py

This PR initializes `_initialized` of `Node` before doing initialization. Otherwise, we will have an `AttributeError` in desctructor when initialization failed:
```text
Exception ignored in: <function Node.__del__ at 0x7fd3a90b6560>
Traceback (most recent call last):
File "/usr/local/google/home/wgtdkp/openthread/tests/scripts/thread-cert/node.py", line 187, in __del__
self.destroy()
File "/usr/local/google/home/wgtdkp/openthread/tests/scripts/thread-cert/node.py", line 190, in destroy
if not self._initialized:
AttributeError: 'Node' object has no attribute '_initialized'
```

[tests] initialize _initialized

---

src/core/coap/coap.cpp
src/core/coap/coap.hpp

This PR has two related commits. The main one:
**[coap] ensure correct dequeue time for entries in response queue**
This commit changes the handling of timer for CoAP response queue to ensure that correct dequeue time is used. The existing code assumed that entries in the queue would be in order of their dequeue time (due to exchange lifetime being fixed). With the addition of configurable CoAP tx parameters feature, this is no longer valid. This commit changes the code to restart the timer with the earliest dequeue time. Also when evicting a message from the queue (due to the number of entries reaching the max limit of `kMaxCachedResponses`) we now search and find the message with earliest dequeue time to remove (instead of removing the entry at the head of queue).
**[coap] directly …

[coap] ensure correct dequeue time for entries in response queue

---

src/core/CMakeLists.txt

`mbedcrypto` target is only available when `OT_BUILTIN_MBEDTLS` is set,
therefore linking it unconditionally when external mbed TLS instance is
used results in a linking error.

[cmake] fix build with external mbedTLS

---

examples/platforms/nrf528xx/src/transport/uart.c

These buffers are touched in volatile and should be marked as volatile.

[nrf528xx] add volatile mark to nrf uart read/write buffers

---

src/core/coap/coap.cpp
src/core/meshcop/border_agent.cpp
src/core/meshcop/commissioner.cpp
src/core/meshcop/energy_scan_client.cpp
src/core/meshcop/joiner.cpp
src/core/meshcop/joiner_router.cpp
src/core/meshcop/panid_query_client.cpp
src/core/thread/address_resolver.cpp
src/core/thread/mle_router.cpp
src/core/thread/network_diagnostic.cpp

This commit changes code to use `IsConfirmable()`,
`IsNonConfirmable()`, `IsAck()` helper methods.

[coap] use Coap::Message helper methods checking CoAP type

---

examples/platforms/nrf528xx/src/transport/uart.c

After #4652 IAR compiles with warning: 
warning[Pa082]: undefined behavior: the order of volatile accesses is undefined in this statement

[nrf528xx] fix IAR undefined order of volatile accesses error

---

examples/platforms/nrf528xx/src/diag.c
include/openthread/error.h
include/openthread/platform/diag.h
src/cli/cli.cpp
src/cli/cli.hpp
src/cli/cli_coap.cpp
src/cli/cli_coap_secure.cpp
src/cli/cli_commissioner.cpp
src/cli/cli_dataset.cpp
src/cli/cli_joiner.cpp
src/cli/cli_udp.cpp
src/core/common/logging.cpp
src/core/diags/factory_diags.cpp
tests/fuzz/fuzzer_platform.cpp

This PR addresses https://github.com/openthread/openthread/issues/4611 with three changes:
1. Remove argument parsing failure from semantic of `OT_ERROR_PARSE`.
2. Add `OT_ERROR_INVALID_COMMAND` to indicate invalid CLI command error.
3. return `OT_ERROR_INVALID_ARGS` for invalid CLI arguments.

[cli] return OT_ERROR_INVALID_ARGS for invalid arguments

---

src/core/coap/coap.cpp
src/core/coap/coap_message.hpp
src/core/coap/coap_secure.hpp

This commit adds `Coap::MessageQueue` class as a subclass of generic
`ot::MessageQueue` as a queue of `Coap::Message` only. This type is
used in `coap.cpp` helping simplify the code (by removing the type
casting).

[coap-message] add Coap::MessageQueue class

---

examples/platforms/efr32mg12/flash.c
examples/platforms/efr32mg13/flash.c
examples/platforms/efr32mg21/flash.c

This PR updates the `otPlatFlash...` abstractions for the efr32:
- 2815bc9 Fully erase the swap region (not only the first page in swap).
- 2815bc9 Remove waiting loop after `MSC_ErasePage`. The SDK MSC functions already wait for the operation to finish.
- c9f7330 Avoid unlocking the flash before the actual write/erase operation. The SDK MSC functions already do the unlock/re-lock when needed.

[efr32] flash: fixes for new otPlatFlash* abstraction

---

.travis/script.sh
tests/toranj/build.sh
tests/toranj/openthread-core-toranj-config-posix.h
tests/toranj/openthread-core-toranj-config-simulation.h
tests/toranj/openthread-core-toranj-config.h

**[toranj] define platform specific config headers**
This commit adds platform specific config header for simulation and posix platforms for toranj. The common configuration definitions stay in the `openthread-core-toranj-config.h` and are shared for all platforms. The `build.sh` script is also updated to pick the correct platform-specific config header for both cmake or autoconf builds.
**[travis] add build checks for cmake with toranj configs (for simul/posix platforms)**
----
This change should also help address issue with the `./tests/toranj/build cmake` not defining the `OPENTHREAD_CONFIG_PLATFORM_FLASH_API_ENABLE=1`.

[toranj] define platform specific config headers + add travis test

---

examples/platforms/cc1352/Makefile.am
examples/platforms/cc1352/flash.c
examples/platforms/cc2650/Makefile.am
examples/platforms/cc2652/Makefile.am
examples/platforms/cc2652/flash.c

- Also fix a pointer arithmetic issue that was flagged.

[cc1352,cc26xx] include `-pedantic-errors` in platform code

---

src/core/meshcop/border_agent.cpp
src/core/meshcop/commissioner.cpp
src/core/meshcop/joiner_router.cpp
src/core/meshcop/leader.cpp
src/core/net/dhcp6_client.cpp
src/core/net/ip6_address.cpp
src/core/net/ip6_address.hpp
src/core/net/ip6_mpl.cpp
src/core/thread/address_resolver.cpp
src/core/thread/lowpan.cpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp

Here adds `GetLocator()` and `SetLocator()` to ease the coding experience as it is quite common to extract/assign the RLOC16 or ALOC16 from/to the RLOC or ALOC IP address.

[ip6-address] add `GetLocator()` and `SetLocator()`

---

src/core/net/netif.cpp

This commit changes the return value of subscribing a pre-defined address when it's already subscribed. Now returns OT_ERROR_ALREADY instead of OT_ERROR_INVALID_ARGS.
Resolves the return value issue in https://github.com/openthread/openthread/pull/4664

[netif] enhance return value of adding external addresses

---

src/core/coap/coap_message.cpp
src/core/thread/lowpan.cpp
src/core/thread/lowpan.hpp
src/core/thread/network_data_leader_ftd.cpp

- [network-data] avoid comparison of narrow type with wide type in loop
- [coap] avoid comparison of narrow type with wide type in loop
- [lowpan] do not try to compress large extension headers

Avoid comparison of narrow type with wide type in loop

---

src/core/api/commissioner_api.cpp
src/core/meshcop/commissioner.cpp
src/core/meshcop/commissioner.hpp

Commissioner should not call `SetState(OT_COMMISSIONER_STATE_DISABLED)` directly, rather it should call `Stop()` so that joiners and resources are cleaned up.
This PR ...
- Fixes this issue
- Adds argument name `/* aResign */` to Stop() calls
- Ignores petition/keep-alive response if commissioner is not in PETITION/ACTIVE state
- Calls `CoapSecure::Stop` when `Start` failed (suggested by @bukepo )
- Responds to `Leader Petition Response (accept)` by sending `KeepAlive(reject)` if commissioner is in disabled state

[meshcop] fix commissioner's invalid call to SetState

---

src/core/utils/flash.cpp
src/core/utils/flash.hpp

This PR improves the flash implementation robustness to power failure. The idea is the following:
The `Init` method now checks if a record has been partially written by seeing if the `kFlagAddBegin` flag is set, but the `kFlagComplete` flag is not. In this case, `Init` stops incrementing `mSwapUsed`. The new `SanitizeFreeSpace` method checks the (supposedly) free space, to see if it is writeable. If it isn't, it triggers a `Swap`, which sanitizes the flash area.
Please see #4710 and https://github.com/openthread/openthread/pull/4552#issuecomment-592943770.
There is an additional subtle detail: the `Delete` method, when called with `aIndex = 0`, erases the records without first marking the `index = 1` record with `kFlagFirst`. If the operation is interrupted at this point, no record will …

[flash] improve power failure robustness

---

.travis.yml

If/when we are comfortable with GitHub Actions, we can start disabling redundant Travis tests.

[travis] disable build checks that exist in GitHub Actions

---

third_party/NordicSemiconductor/nrfx/hal/nrf_ficr.h

Compilation error: #111-D: statement is unreachable.

[nrf528xx] fix Keil compilation error in nrf_ficr.h

---

src/core/thread/mesh_forwarder.cpp
src/core/thread/mle_router.cpp
src/core/thread/mle_router.hpp

A router coming out of reset sends a Link Request to re-establish its
router role and links to neighboring routers. The existing
implementation only responds to such Link Requests when a valid
neighbor entry is found. This check is too strict and can cause
partitions to remain for a couple minutes. The Thread Specification
only requires a router to check that the Router ID is currently
allocated.
This commit updates the implementation to be conformant with the
Thread Specification and allows routers coming out of reset to
resynchronize even when a neighboring router has detect a link
failure.

[mesh-forwarder] do not remove router on link failures

---

src/core/thread/network_data.cpp
src/core/thread/network_data.hpp
src/core/thread/network_data_leader.cpp
src/core/thread/network_data_leader.hpp
src/core/thread/network_data_leader_ftd.cpp
src/core/thread/network_data_local.cpp
src/core/thread/network_data_local.hpp
src/core/thread/network_data_tlvs.hpp

This PR contains a bunch of improvements and changes in `NetworkData` modules.
- Add helper `FindTlv()` and templated `FindTlv<TlvType>` methods to search within a sequence of TLVs  to find a TLV with a given type (and/or stable  status) along with 
- Add methods to help with iterating over Network Data content  (`FindTlv`, `IterateToNextTlv()`, etc).
- Add `AppendTlv()` and `RemoveTlv()` helper methods to simplify adding and removing of an entire TLV from the Network Data.
- Change `PrefixMatch()` to use `Ip6::Address` method.
- Simplify and fix `RemoveTemporaryData()` (use cast to get the sub-TLV during iteration).
- Simplify `GetNextServer()` implementation to use other methods to iterate over all on-mesh prefix, external route, and service entries in Network Data. 
- Simplify the …

[network-data] adding helper methods, simplify code

---

tests/toranj/start.sh

This commit changes the `start.sh` script to remove the check for the
environment variable (which is specific to travis) before allowing
retry of failed tests. This should help with robustness of the tests
on GitHub Actions.

[toranj] change start.sh to remove variable check to retry failed test

---

include/openthread/thread_ftd.h
src/cli/README.md
src/cli/cli.cpp
src/core/api/thread_ftd_api.cpp
src/core/thread/mle_router.cpp
src/core/thread/mle_router.hpp

Thread 1.2 requires to set the number of IP address the parent could store per child to test the reaction of the Child DUT. The number might be not conform to the Conformance Spec.  Since it is only used for reference device, here wraps relative APIs in the `OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE` macro.

 [cli] add `childip max` command

---

src/core/net/ip6_address.cpp
src/core/net/ip6_address.hpp
src/core/thread/mle.cpp

This commit also replaces the relative magic numbers with the constants
`MeshLocalPrefix::kLength` and `MeshLocalPrefix::kSize`

[ip6-address] add `SetMulticastNetworkPrefix()` for Prefix-Based Multicast Address

---

include/openthread/thread_ftd.h
src/cli/cli.cpp
src/core/api/thread_ftd_api.cpp
src/core/common/linked_list.hpp
src/core/config/tmf.h
src/core/net/netif.cpp
src/core/thread/address_resolver.cpp
src/core/thread/address_resolver.hpp
src/core/thread/mesh_forwarder_ftd.cpp
src/lib/spinel/spinel.h
src/ncp/ncp_base_ftd.cpp
tests/toranj/wpan.py
tests/unit/test_linked_list.cpp

This PR updates the `AddressResolver` and how cache entries are managed. This is related to Issue https://github.com/openthread/openthread/issues/4542. It contains the following related commits:
**[linked-list] change PopAfter() parameter to be a pointer**
This commit changes `LinkedList::PopAfter()` method to accept a pointer to a previous entry as a parameter. If the previous entry pointer is NULL the entry at the head of the list is popped. 
**[address-resolver] use linked-list and enable snooped entry timeout**
This commit contains multiple enhancements in `AddressResolver`:
- Cache entries are stored in different lists: Cached list (entries in use), query list (entries actively querying and waiting for address notification response), query-retry list (entries in delay wait mode due …

[address-resolver] use linked-list and enable snooped entry timeout

---

src/core/thread/network_data.cpp

---
Fix as a follow up to #4743.

[network-data] fix FindTlv() to return NULL when TLV sequence is malformed

---

tests/toranj/test-602-channel-manager-channel-select.py

This commit changes the `test-602-channel-manager-channel-select` to
wait for sample count to reach a limit (within a wait interval). This
should help make the test more robust (e.g., in RCP/POSIX mode) when
the simulation processing time may require more time (note that this
test is run with very high speed-up).

[toranj] update test-602-channel-select to add extra wait

---

tests/toranj/openthread-core-toranj-config.h
tests/toranj/start.sh
tests/toranj/test-039-address-cache-table-snoop.py
tests/toranj/wpan.py

This is related and a follow up to PR https://github.com/openthread/openthread/pull/4599.
It adds a toranj test-case verifying behavior of `AddressResolver` and management of cache table.
This PR is related to two other PRs. The change is broken due to dependency we have between new spinel property definitions in OT, wpantund changes and then the new `toranj` test-case.
- The main PR https://github.com/openthread/openthread/pull/4599 (should be merged first). 
- The wpantund PR: https://github.com/openthread/wpantund/pull/462
- This PR https://github.com/openthread/openthread/pull/4600 (which adds the test)

[toranj] add new test-case for cache table snoop

---

examples/Makefile-efr32mg13
examples/platforms/efr32mg12/Makefile.am
examples/platforms/efr32mg12/Makefile.platform.am
examples/platforms/efr32mg12/efr32mg12.ld
examples/platforms/efr32mg12/flash.c
examples/platforms/efr32mg12/openthread-core-efr32-config.h
examples/platforms/efr32mg13/Makefile.am
examples/platforms/efr32mg13/Makefile.platform.am
examples/platforms/efr32mg13/efr32mg13.ld
examples/platforms/efr32mg13/flash.c
examples/platforms/efr32mg13/openthread-core-efr32-config.h
examples/platforms/efr32mg21/Makefile.am
examples/platforms/efr32mg21/Makefile.platform.am
examples/platforms/efr32mg21/efr32mg21.ld
examples/platforms/efr32mg21/flash.c
examples/platforms/efr32mg21/openthread-core-efr32-config.h
third_party/silabs/Makefile.am

silabs nvm3 support is selected by setting following macro in
openthread-core-efr32-config.h :-
#define OPENTHREAD_CONFIG_PLATFORM_FLASH_API_ENABLE 0

[efr32] add nvm3 support

---

src/core/thread/mesh_forwarder.hpp
src/core/thread/mesh_forwarder_ftd.cpp

The existing implementation only considered the forwarding queue when
looking for a message to evict. This ignores message buffers that may
be buffered in other message queues.
This commit adds the ability to evict messages in the address resolver
queue. The lowest priority message from either the forwarding or
address resolver queue is selected for eviction.

[mesh-forwarder] include address resolving queue in message eviction

---

src/core/thread/mle_router.cpp
src/core/thread/network_data_leader_ftd.cpp
src/core/thread/network_data_leader_ftd.hpp

A parent is responsible for removing stale child entries from the
network data. The existing implementation only triggered a
SVR_DATA.ntf message when new network data is received. In some cases,
the SVR_DATA.ntf message may not be sent due to rate limiting or lack
of message buffers.
This commit turns this process into a periodic check to ensure that
stale child entires are removed even if a failure in sending the
SVR_DATA.ntf occurs.

[network-data] periodically check for stale child ids

---

src/core/thread/mle_router.cpp
src/core/thread/mle_tlvs.hpp
src/core/thread/mle_types.hpp
src/core/thread/network_diagnostic_tlvs.hpp
src/core/thread/router_table.cpp
src/core/thread/router_table.hpp
src/core/thread/thread_tlvs.hpp

Currently there are four similar copies regarding Router Id set separately in 1) `RouteTlv` in mle_tlvs.hpp; 2) `ThreadRouterMaskTlv` in thread_tlvs.hpp; 3) `RouterIdSet` in router_table.hpp; 4)`RouteTlv` in network_diagnostic_tlvs.hpp.
This PR extracts the common `RouterIdSet` class and apply it in the four components, meanwhile keep one copy for `RouteTlv` and `ThreadRouterMaskTlv` process in route_table (see [comments in #4749](https://github.com/openthread/openthread/pull/4749#discussion_r399736521))

[core] use the common `RouterIdSet` class

---

src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager_ftd.cpp
src/core/thread/network_data_leader_ftd.cpp
src/core/thread/network_data_leader_ftd.hpp

This commit replaces `IncrementStableVersion()` with a new method
`IncrementVersionAndStableVersion()` which increments both version and
stable version. It helps simplify its use by other modules and also
ensures stable version is not updated without version. This commit
also adds a common private `IncrementVersions()` used by other methods
in `NetworkData::Leader`.

[network-data] add IncrementVersionAndStableVersion()

---

src/core/common/message.hpp
src/core/thread/mesh_forwarder.cpp

Fixes a bug introduced in #4776 
The existing MeshForwarder::RemoveMessage() implementation is specific
to evicting messages from mSendQueue. This commit generalizes the
method by retrieving the queue from the message itself.

[mesh-forwarder] fix bug in evicting from address resolver queue

---

src/core/thread/network_data.cpp
src/core/thread/network_data_leader.cpp
src/core/thread/network_data_leader_ftd.cpp
src/core/thread/network_data_leader_ftd.hpp

This commit contains the following changes in `NetworkData::Leader`:
- Simplify methods `RemoveContext()`, `UpdateContextsAfterReset()`,
`FindServiceById()`, `RemoveRloc()` to use `FindTlv` when searching
for TLVs of a given type.
- Removes redundant checks in `RlocLookup()`.
- Uses pointer to iterate through `BoderRouterTlv` or `HasRouteTlv`
entries.
- Move simple getter/setter methods to header file (to be inline).

[network-data] simplify code, user helper methods

---

src/core/thread/address_resolver.cpp
src/core/thread/address_resolver.hpp

This commit simplifies the model for iterating through a linked
list by using a `prev` pointer as the iterator variable. This helps
fix an issue with the `prev` pointer not staying  valid when entry
is removed from the list during iteration.

[address-resolver] ensure prev pointer stays valid on entry removal

---

third_party/NordicSemiconductor/libraries/nrf_security/config/nrf-config.h
third_party/NordicSemiconductor/libraries/nrf_security/include/mbedtls/ecp.h

Error[Pe301]: typedef name has already been declared (with same type)

[nrf528xx] add defines needed for compilation with IAR in nrf_security

---

tests/toranj/openthread-core-toranj-config.h
tests/toranj/test-039-address-cache-table-snoop.py

This commit changes the `test-039` to add delay between the initial
message tx to stagger the address query send times. This helps verify
the query timeout behavior.
----------
This PR also include the fix from https://github.com/openthread/openthread/pull/4789.
Without this fix the test does indeed fail.

[toranj] update test-039 to stagger initial address queries

---

Android.mk
BUILD.gn
src/core/CMakeLists.txt
src/core/Makefile.am
src/core/api/border_router_api.cpp
src/core/api/server_api.cpp
src/core/backbone_router/local.cpp
src/core/common/instance.hpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp
src/core/thread/network_data.cpp
src/core/thread/network_data.hpp
src/core/thread/network_data_leader.cpp
src/core/thread/network_data_leader_ftd.cpp
src/core/thread/network_data_leader_ftd.hpp
src/core/thread/network_data_local.cpp
src/core/thread/network_data_local.hpp
src/core/thread/network_data_notifier.cpp
src/core/thread/network_data_notifier.hpp
src/core/thread/thread_netif.cpp
src/core/thread/thread_netif.hpp

This commit centralizes the timing logic for transmitting SVR_DATA.ntf
messages that are used to update network data at the leader.
This component helps ensure the following:
- At most one SVR_DATA.ntf message is outstanding at any given time.
- A timer to rety sending SVR_DATA.ntf messages if sending fails due
to lack of memory buffers.
- A timer to rate limit SVR_DATA.ntf messages that are acknowledged
but no corresponding change in the Thread Network Data was observed.
- Utilizes ot::Notifier to trigger logic on role, child state, and
network data changes.

[network-data] implement network data notifier

---

Android.mk

This allows libraries depending on ot-core not to specify OpenThread
path and share the OpenThread configs.

[android] export CFLAGS and include directories

---

src/core/api/link_api.cpp
src/core/api/network_time_api.cpp
src/core/api/thread_api.cpp
src/core/api/thread_ftd_api.cpp
src/core/backbone_router/local.cpp
src/core/common/instance.cpp
src/core/common/settings.cpp
src/core/mac/data_poll_handler.cpp
src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager_ftd.cpp
src/core/meshcop/meshcop_leader.cpp
src/core/thread/announce_sender.cpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_router.cpp
src/core/thread/mle_types.hpp
src/core/thread/network_data_leader.cpp
src/core/thread/network_data_leader_ftd.cpp
src/core/thread/network_data_local.cpp
src/core/thread/network_diagnostic.cpp
src/core/thread/router_table.cpp
src/core/thread/time_sync_service.cpp
src/core/utils/channel_manager.cpp
src/core/utils/child_supervision.cpp
src/core/utils/jam_detector.cpp

This commit defines a new enum type `Mle::DeviceRole` mirroring the
public `otDeviceRole` enumeration. The enumerator in the new type
follow `kRole{Value}` style and intended for use in the core modules.
It also adds helper method in `Mle`, `IsChild()`, `IsRouter()`,
`IsLeader()`, etc to check the current device role.
----------
I kept the commits seperate for easier review but would suggest to squash before merge (first commit has the full commit message).

[mle] add DeviceRole type, and IsChild, IsRouter, etc method

---

src/core/thread/network_data_notifier.cpp

This PR fixes IAR compilation error:
Error[Pa089]: enumerated type mixed with another enumerated type

[network-data-notifier] fix flag for child removed notification

---

src/core/meshcop/dataset_manager_ftd.cpp
src/core/meshcop/joiner_router.cpp
src/core/meshcop/meshcop.cpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle_router.cpp
src/core/thread/network_data.cpp
src/core/thread/network_data.hpp
src/core/thread/network_data_leader.cpp
src/core/thread/network_data_leader.hpp
src/core/thread/network_data_leader_ftd.cpp
src/core/thread/network_data_leader_ftd.hpp
src/core/thread/network_data_local.cpp
src/core/thread/network_data_local.hpp
src/core/thread/network_data_tlvs.hpp

This commit declares methods, input parameters, and local variables as
`const` whenever possible in `NetworkData` modules. `const` versions
of methods (returning `const` pointer) are also added, e.g.,
`NetworkDataTlv::GetNext()`, `HasRouteTlv::GetFirstEntry()`,
`NetworkData::FindTlv()`, etc. For simpler (inline) methods, the
`const` version is directly implemented but for more complex methods,
the const version is the main implementation (defined in `cpp` file)
and non-`const` version is implemented using `const_cast` conversions
from the `const` method.
This commit also declares methods not using any member variable/info
as `static` (e.g. `FindHasRoute()` or `FindContext()`). It also
declares `RemoveTemporaryData()` flavors removing internal sub-TLVs as
`private` (instead of `protected`) …

[network-data] adopt const for methods, parameters, and local vars

---

include/openthread/commissioner.h
include/openthread/instance.h
src/core/api/commissioner_api.cpp
src/core/common/notifier.cpp
src/core/meshcop/border_agent.cpp
src/core/meshcop/border_agent.hpp
src/core/meshcop/commissioner.cpp
src/core/meshcop/commissioner.hpp
src/core/meshcop/joiner.cpp
src/core/thread/mle.cpp

This PR fixes the bug found during the Commissioning procedure when i wasn't able to turn on native commissioner even though the actual state was `Disabled`.
----------------
In case both Commissioner and Border Agent are compiled in, there is a chance that Commissioner will change the state without user intervention e.g. from `Active` to `Disabled` (due to some network issue e.g. Keep Alives are lost) without calling the OpenThread API.
If that happens, it may not be possible to turn on/off the commissioner again. There are a couple of possible problems but just to give perspective:
- Border Agent may return `OT_ERROR_ALREADY` which prevents to call the `otCommisionerStart` API https://github.com/openthread/openthread/blob/master/src/core/api/commissioner_api.cpp#L54
- If the …

[commissioner] synchronize the state with Border Agent

---

src/core/backbone_router/leader.cpp
src/core/backbone_router/local.cpp
src/core/thread/network_data_leader.cpp
src/core/thread/network_data_leader_ftd.cpp
src/core/thread/network_data_local.cpp
src/core/thread/network_data_tlvs.hpp

This commit updates the `ServiceTlv` implementation and its use.
- Set the `ServiceTlv` fields through a new `Init()`
- Use union for managing presence of Enterprise Number field
- Add static helper `GetSize()` to get the size of a Service TLV
with a given Enterprise number and Service Data length.
- Add `ServiceTlv::kThreadEnterpriseNumber` constant replacing the
`THREAD_ENTERPRISE_NUMBER` definition.

[network-data] simplify ServiceTlv

---

src/core/thread/address_resolver.cpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp

Besides, we found that the `/a/ae` COAP message with link-local destination wouldn't be processed by by child's COAP layer. 
Thoughts on why it is unreachable by link-local address? @librasungirl @jwhui

[address-resolver] use RLOC dest when send `a/ae` to child

---

src/core/net/ip6.cpp

When removing unsecure port, we should not add aFromNcpHost filter since
the packet comes from the child.

[ip6] fix remove unsecure port behavior

---

src/core/thread/mle_types.hpp
src/core/thread/network_data.cpp
src/core/thread/network_data.hpp
src/core/thread/network_data_leader_ftd.cpp
src/core/thread/network_data_leader_ftd.hpp
src/core/thread/network_data_local.cpp
src/core/thread/network_data_tlvs.hpp
tests/toranj/start.sh
tests/toranj/test-040-network-data-stable-full.py
tests/toranj/wpan.py

This commit changes the model for updating Network Data on a leader.
It adds `ChangedFlags` type which is used to track whether full or stable version of Network Data gets changed as TLVs/sub-TLVs are being added or removed. This is then used to update version and stable version accordingly.
When registering new received Network Data on the leader, the new model updates the Network Data in place. First, newly added `Validate()` method is called to verify that the received Network Data contains well-formed TLVs and sub-TLVs (e.g., no duplicate Prefix/Service TLVs) and all sub-TLVs/entries match the sender's RLOC16. Then, all entries in the current Network Data associated with the sender's RLOC16 which are not present in the newly received data are removed. Afterwards, any new entry in the …

[network-data] enhance/simplify updating of network data on leader

---

src/core/thread/network_data.cpp
src/core/thread/network_data.hpp

This commit adds a common private `Iterate()` method which is used by
other methods iterating over different types of entries:
`GetNextOnMeshPrefix()`, `GetNextExternalRoute()`, `GetNextService()`,
and `GetNextServer()`. It also adds methods to help advancing the
iterator to next TLV or sub-TLV or entry index.

[network-data] define and use a common Iterate method for all entry types

---

src/core/net/dhcp6_client.cpp
src/core/net/ip6.cpp
src/core/net/ip6_address.cpp
src/core/net/ip6_address.hpp
src/core/net/netif.hpp
src/core/thread/address_resolver.cpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp

This commit adds methods to set an `Ip6::Address` to common multicast
addresses, link-local all-nodes/all-routers, realm-local all-nodes/
all-routers, or realm-local all MPL forwarders. The implementation
uses the constant addresses defined in `Netif` class.

[ip6-address] methods to set address to common multicast addresses

---

CMakeLists.txt

This allows to work-around a compile error that is happening in Zephyr
<https://github.com/zephyrproject-rtos/openthread/pull/9>.
Signed-off-by: Markus Becker <markus.becker@tridonic.com>

[cmake] disable -pedantic-errors together with -Werror

---

src/core/coap/coap.cpp
src/core/meshcop/joiner.cpp
src/core/meshcop/joiner_router.cpp
src/core/net/dhcp6_client.cpp
src/core/net/dhcp6_server.hpp
src/core/net/icmp6.cpp
src/core/net/ip6.cpp
src/core/net/ip6_address.cpp
src/core/net/ip6_address.hpp
src/core/thread/lowpan.cpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp
src/core/thread/network_data_leader_ftd.cpp

This commit adds and uses a new method `SetToLinkLocalAddress()` in
`Ip6::Address` class which sets the address to a Link-Local IPv6
address with a given Interface Identifier (either given directly or
generated from a MAC Extended Address).
It also adds methods to set the address to a Routing/Anycast Locator
and updates methods checking RLOC/ALOC addresses. It adds a common
`IsIidLocator()` to check if the IID matches the `0000:00ff:fe00:xxxx`
pattern. More specific checks for RLOC or ALOC can be done by
`IsIidRoutingLocator()` or `IsIidAnycastLocator()`. The `Mle` and
other modules are updated to use the new/updated methods.

[ip6-address] helper methods to set Link-Local and RLOC/ALOC addresses

---

examples/platforms/samr21/logging.c

- include "board.h" before its defines are used
Resolves #4845

[samr21] fix build when logging is enabled

---

src/core/mac/mac_frame.cpp
src/core/mac/mac_frame.hpp
tests/unit/test_mac_frame.cpp

This PR enhances some utility functions in mac frame for frame parsing and adds some basic testing. 
* Currently the mac frame parsing only doesn't include the rule for version 2015. This PR adds the parsing of dstPanId for 2015 frames.
* This PR adds some helper function dealing with Security Header so that later PR of CSL and setting security header in enhanced ACK would be easier.

[mac-frame] enhance utility functions

---

src/core/meshcop/dataset.cpp
src/core/meshcop/dataset.hpp
src/core/meshcop/dataset_local.cpp
src/core/meshcop/dataset_local.hpp
src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager.hpp
src/core/meshcop/dataset_manager_ftd.cpp
src/core/meshcop/joiner_router.cpp
src/posix/platform/radio_spinel.cpp

This commit contains multiple enhancements in `Dataset` modules. It
adds a new enumeration `Type` to specify the type of a Dataset
(active or pending). It also renames the methods that get or a set a
TLV within the dataset to `GetTlv()` and `SetTlv()`. It also renames
methods converting the TLV format to/from an `otOperationalDataset`
structure. With the renames, we can remove the re-definition of
`Get<Type>()` method (since no longer being shadowed by other
definitions). Finally this commit updates some of the method
documentation.
----
I kept the commits separate for easier review but for meting would suggest to squash them all. The first commit contains the full log message.

[dataset] multiple enhancements (add Type, rename to GetTlv/SetTlv, etc.)

---

src/core/common/logging.hpp

There is no `aFormat` parameter any more.

[logging] fix compile error for BBR region

---

src/core/thread/mle_router.cpp
src/core/thread/mle_router.hpp
src/core/thread/network_data_local.cpp
tests/scripts/thread-cert/Makefile.am
tests/scripts/thread-cert/test_reed_address_solicit_rejected.py

Currently, a REED which expects to become Router soon does not send any `SVR_DATA.ntf`. 
This PR handles rejecting `ADDR_SOL.rsp` to allow REED to send `SVR_DATA.ntf` after it's rejected. 
This PR addresses #4827 .

[mle] REED to handle rejected ADDR_SOL.rsp

---

CMakeLists.txt
script/test
tests/CMakeLists.txt
tests/unit/CMakeLists.txt

As we're transferring to cmake, I'm trying to replace `make -f examples/Makefile-simulation check` with cmake in our github actions. 
In this PR, we would be able to run all the simulation unit tests easier with cmake:
```
./script/test clean build unit_tests
```
I plan to also add `thread-cert` tests into cmake tests later and then gradually replace the 'make check' in github actions with cmake.

[cmake] enable running simulation unit tests using cmake

---

examples/platforms/nrf528xx/nrf52811/openthread-core-nrf52811-config.h

This PR resolves the issue #4861.
The nRF52811 is designed to work in RCP architecture where DTLS is
established on the host level. The nRF52811 doesn't support Joiner
or Border Agent roles. This PR enables nRF52811 to use default heap
size to save RAM.

[nrf52811] use the default heap size to save RAM

---

src/core/meshcop/dataset.cpp
src/core/meshcop/dataset.hpp
src/core/meshcop/dataset_local.cpp
src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager_ftd.cpp
src/core/meshcop/joiner_router.cpp
src/core/meshcop/meshcop_tlvs.cpp
src/core/meshcop/meshcop_tlvs.hpp
src/core/thread/network_data_leader.cpp

This commit adds helper method `MeshCoP::Tlv::FindTlv()` to search
within a given sequence of TLVs for a specific TLV type. This is used
to simplify `Dataset::GetTlv()` and provide a template version
`GetTlv<TlvType>()`. This commit also adds new flavors of `SetTlv()`
for simple TLVs, i.e, TLVs with a single value which is either an
`uint16_t` or `uint32_t` value or can be treated a data blob.

[dataset] add GetTlv<Type>(), and SetTlv() for simple TLVs

---

src/lib/platform/exit_code.c

Similar to the errno walkaround in `src/lib/spinel/spinel.c`.
```C
#if defined(errno) && SPINEL_PLATFORM_DOESNT_IMPLEMENT_ERRNO_VAR
#error "SPINEL_PLATFORM_DOESNT_IMPLEMENT_ERRNO_VAR is set but errno is already defined."
#endif
// Work-around for platforms that don't implement the `errno` variable.
#if !defined(errno) && SPINEL_PLATFORM_DOESNT_IMPLEMENT_ERRNO_VAR
static int spinel_errno_workaround_;
#define errno spinel_errno_workaround_
#endif // SPINEL_PLATFORM_DOESNT_IMPLEMENT_ERRNO_VAR
```

[platform] fix errno undefined on some libc

---

examples/platforms/cc1352/radio.c
examples/platforms/cc2650/radio.c
examples/platforms/cc2652/radio.c
examples/platforms/utils/encoding.h
include/openthread/platform/radio.h

Fix compilation errors on GCC 9.2.0 due to struct and class member alignment.

[cc1352,cc26xx] fix unaligned access of ext address in radio.c

---

examples/platforms/efr32mg12/efr32mg12.ld
examples/platforms/efr32mg12/flash.c
examples/platforms/efr32mg13/efr32mg13.ld
examples/platforms/efr32mg13/flash.c
examples/platforms/efr32mg21/efr32mg21.ld
examples/platforms/efr32mg21/flash.c
third_party/silabs/Makefile.am

In this PR, I am updating Silabs nvm3 support implementation to use the (built-in) nvm3 default instance instead of using a separate nvm3 instance. This approach enables the application to share the nvm3 system using a single default instance between OpenThread and any other stack/application used along with OpenThread. The implementation has also been updated to use a dedicated nvm3 key space region instead of utilizing the user key space region.
I am also adding the otPlatFlash* APIs back in flash.c that were incorrectly removed in a prior commit. These APIs are required when using the default NV system.

[efr32] update NVM3 to use default instance

---

.github/workflows/build.yml
CONTRIBUTING.md
STYLE_GUIDE.md
script/bootstrap

v0.30.0 (released on 2020-04-23) introduces formatting changes that
are not compatible with v0.29.0.

[pretty] fix yapf version to 0.29.0

---

src/core/thread/network_diagnostic.cpp

Reproduce by issuing `networkdiagnostic get ff03::1 0 1` on one router.

[cli] fix infinite loop on networkdiagnostic

---

src/core/mac/mac_frame.cpp
tests/unit/test_mac_frame.cpp

This commit directly updates the `mLength` from `InitMacHeader()` as it prepares the frame header (instead of setting it at the end). This ensures that `InitMacHeader()` can safely call other `Frame` helper methods (e.g. `GetFooterLength()` which itself does check the frame length).
[tests] update Mac::Frame unit test to check footer and frame length
--------
Background on this: This PR addresses an issue (introduced in #4826) where from `InitMacHeader()` before setting the length of frame, we would call `GetFooterLength()` which in turn calls `FindSecurityHeaderIndex()`  which would check the length from `VerifyOrExit(kFcfSize < GetLength(), index = kInvalidIndex);` (basically using the frame length uninitialized and before it is set). While it is a bug, I think it is not critial in …

[mac-frame] ensure frame length is correctly updated from InitMacHeader()     

---

src/core/meshcop/dataset.cpp
src/core/meshcop/dataset.hpp
src/core/meshcop/dataset_local.cpp
src/core/meshcop/dataset_manager.cpp

This commit contains a group of smaller enhancements/simplifications
in `Dataset` modules:
- Add helper `GetTlvsStart()` and `GetTlvsEnd()` to get start/end
of Dataset TLVs sequence.
- Use `for` loop when iterating over TLVs.
- Simplify `RemoveTlv()` to get a pointer to TLV as input
- Remove single-use local TLV variables (in switch statements).
- Simplify `DatasetLocal::Compare()`.

[dataset] misc enhancements

---

src/core/mac/mac_frame.cpp
src/core/mac/mac_frame.hpp

This commit adds new helper methods in `Mac::Frame` to calculate the
size (number of bytes) of headers or security MIC. These are used by
different methods to simplify the code and avoid repeated patterns:
- `CalculateAddrFieldSize(aFcf)` to calculate the size of Address
Fields given a Frame Control value.
- `CalculateSecurityHeaderSize(aSecurityControl)` to calculate size
of Security Header given a Security Control value.
- `CalculateMicSize(aSecurityControl)` to get the size of MIC given
a Security Control value.

[mac-frame] helper methods to calculate size of headers/MIC

---

src/core/thread/address_resolver.cpp
src/core/thread/topology.hpp

Thread 1.1 specification 5.4.2.4 says
> The ML-EID TLV contains the ML-EID associated with the Target EID

[address-resolver] fix ADDR_NTF.ans to use Child's Mesh Local IID

---

src/core/backbone_router/leader.cpp
src/core/backbone_router/local.cpp
src/core/backbone_router/local.hpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp

As discussed, this PR moves bbr relative addresses to `BackboneRouter::Local`

[bbr] move bbr relative addresses to BackboneRouter::Local

---

src/core/common/message.hpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder.hpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle_router.hpp
tests/toranj/test-021-address-cache-table.py

This PR contains the following commits:
- [mesh-forwarder] send all message fragments to the same mesh dest
All fragments for a given IPv6 datagram must be sent to the same
destination. Otherwise, there is not much point in transmitting the
messages.
- [mesh-forwarder] ensure mesh dst checks for dst unreach
An out-dated EID-to-RLOC map cache may lead a device to send an IPv6
datagram to a device that does not have the IPv6 Destination Address
assigned to its interface. However, the existing implementation would
not send back an ICMPv6 Destination Unreachable message necessary to
invalidate the originator's EID-to-RLOC cache entry.
This implementation adds reachability checks on the mesh destination
receive path to ensure that reachability checks are performed in the
above situation.
- …

[mesh-forwarder] ensure mesh dst checks for dst unreach

---

src/cli/cli.cpp
src/cli/cli_dataset.cpp
src/cli/cli_udp.cpp
src/core/meshcop/border_agent.cpp
src/core/meshcop/border_agent.hpp
src/core/meshcop/commissioner.cpp
src/core/meshcop/commissioner.hpp
src/core/net/dhcp6_client.cpp
src/core/net/dhcp6_server.cpp
src/core/net/dhcp6_server.hpp
src/core/thread/address_resolver.cpp
src/core/thread/mle.cpp
src/ncp/ncp_base_mtd.cpp

MeshLocalPrefix may change when applying Operational Dataset.
This PR applies mesh local prefix to the ALOCs which are not in `Mle` component.

[aloc] add ApplyMeshLocalPrefix() to applicable ALOCs

---

.github/workflows/build.yml
src/posix/platform/hdlc_interface.cpp
src/posix/platform/spi_interface.cpp

This makes narrowing conversions of time types explicit to fix build errors.
Also added a CI build to check for any errors like this. The new build uses clang because GCC's `-Wconversion` is too strict, making a huge number of compiling errors in our codebase.

[spinel] fix time narrowing conversion

---

src/posix/platform/netif.cpp

This code (likely a first attempt, as I'm sure there's some stuff in here that
folks will want to change) does the following:
- provides an implementation to manage networking notices from a PF_ROUTE socket,
instead of (the Linux-specific) PF_NETLINK
- breaks out some of the platform-specific mechanisms for configuring a tunnel
device (Linux, mac OS, and NetBSD are all different in some ways)
- provides handling of I/O to the tun drivers on BSDs (where there's a 4-byte
header prepended to identify the IP version)
- adds some debugging info and more deliberate error handling (I suspect
there are some more OpenThread-friendly ways to do some of the
debugging, but I didn't try to figure them out)
I've used most of this code for several months on mac OS and NetBSD, and I
wanted to get a …

[posix] refactoring of netif code, mostly to accommodate BSDs

---

src/core/meshcop/commissioner.cpp

This PR fixes the bug that duplicate `commissioner start` will incorrectly close `CoapSecure`.

[commissioner] fix duplicate commissioner start

---

src/core/common/instance.cpp
src/core/mac/mac.cpp

When OT is initialized after boot, finalized, and initialized again without reboot, assertion in SubMac::Enable is triggered. The reason is that SubMac::Disable is never called during finalization and platform radio is in unexpected state.

[mac] disable SubMac on instance finalization

---

src/core/mac/mac.cpp

This commit adds a check in `Mac::ProcessReceiveSecurity()` to verify
that the Security Level in a received frame is properly set to
`kSecEncMic32` before trying to decrypt and validate the frame. This
helps avoid performing AES-CCM when frame is invalid and also avoid
potentially reading beyond the frame length when checking MIC/footer.

[mac] verify that Security Level is correct in rx frame

---

.github/workflows/simulation.yml

The error logs of `check` will only be printed when VERBOSE=1.

[continuous-integration] recover verbose check

---

examples/platforms/cc1352/CMakeLists.txt
examples/platforms/cc2652/CMakeLists.txt
third_party/CMakeLists.txt
third_party/ti/CMakeLists.txt

move thirdparty related in cc1352&cc2652 cmake files into their respective cmake files

[cmake] move cc1352 & cc2652 libs to third-party cmake file

---

src/core/meshcop/commissioner.cpp
src/core/meshcop/commissioner.hpp
src/core/thread/mle_router.cpp

This PR:
1. Removes the unnecessary `MGMT_COMMISSISONER_SET.req` sent by Commissioner to Leader when a Joiner is removed only to be added back. 
2. Use proper error codes for `MleRouter::HandleDiscoveryRequest`

[commissioner] remove duplicate MGMT_COMMISSISONER_SET.req

---

CMakeLists.txt
examples/apps/cli/CMakeLists.txt
examples/apps/ncp/CMakeLists.txt

This is required for running commissioning related tests for the
commissioning messages are retrieved from logs.

[cmake] add log output option

---

src/posix/platform/netif.cpp

Missed a couple of places when building for Apple's utun driver.  Needed to streamline automated testing on mac OS.

[posix] fix two compile-time errors for mac OS utun driver

---

src/core/common/logging.hpp

otDumpNote definition looks like it was copy/pasted from otDumpInfo and hasn't been compiled with the appropriate compile options and an actual call to otDumpNote.

[logging] fix typo for otDumpNote definition

---

src/core/meshcop/joiner.cpp

This PR fixes the bug that OpenThread uses hash of EUI64 (joiner ID) as the source address of Discovery Request messages. Thread specification requires the source address to be random value:
> Discovery Request messages MUST have the Source Address in the IEEE 802.15.4 header
set to an extended (64-bit) random generated value.
(section 8.4.4.1.1.1 of Thread 1.1 specification).
While for subsequent messages, the joiner should use hash of EUI64 (joiner ID) value:
> When the Thread device is configured to obtain Thread Network security credentials using Thread
Commissioning as specified in Chapter 8, Mesh Commissioning Protocol, the specific value
provided by the device to the MAC sub-layer to represent the aExtendedAddress prior to obtaining
the network security credentials MUST be the …

[joiner] use random extended address for discovery request

---

tools/harness-automation/autothreadharness/pdu_controller.py
tools/harness-automation/autothreadharness/pdu_controller_factory.py
tools/harness-automation/autothreadharness/settings_sample.py
tools/harness-automation/requirements.txt

Another PDU Controller used to power cycle between tests. Based by SNMP protocol.
To use EATON_PDU_CONTROLLER is needed PySNMP module (added to `requirements.txt`)
Also extend `settings_sample.py` by comments with needed parameters to create EATON_PDU_CONTROLLER.

[harness-automation] add another PDU Controller for EATON by SNMP

---

src/core/backbone_router/leader.hpp
src/core/thread/dua_manager.cpp
src/core/thread/dua_manager.hpp
src/core/thread/mle.cpp

Thread 1.2 spec requires prioritizing DUA in AR TLV to ensure DUA could be stored in the limited addresses space for Child on the parent.
This PR depends on #4854 , please only review the last commit which is the purpose of this PR.

[dua] MTD prioritizes DUA in AR Tlv

---

configure.ac
examples/platforms/cc1352/Makefile.am
examples/platforms/cc2538/Makefile.am
examples/platforms/cc2650/Makefile.am
examples/platforms/cc2652/Makefile.am
examples/platforms/gp712/Makefile.am
examples/platforms/jn5189/Makefile.am
examples/platforms/kw41z/Makefile.am
examples/platforms/nrf528xx/nrf52811/Makefile.am
examples/platforms/nrf528xx/nrf52833/Makefile.am
examples/platforms/nrf528xx/nrf52840/Makefile.am
examples/platforms/qpg6095/Makefile.am
examples/platforms/samr21/Makefile.am
examples/platforms/utils/settings_ram.c
src/core/utils/heap.hpp
third_party/NordicSemiconductor/Makefile.am
third_party/jlink/Makefile.am
third_party/mbedtls/Makefile.am
third_party/silabs/Makefile.am

Hi all, this PR enables the -Wcast-align warning for the OT core, and for some platforms (very few that don't issue warnings).
For background, see #4796.

[build] add -Wcast-align to detect potential alignment issues when casting

---

include/openthread/platform/toolchain.h

With clang older than 3.9, the `warn_unused_result` feature works only with functions and classes, not enums. This disables it if the clang version is too old.

[error] disable error checking enforcement for old versions of clang

---

tests/scripts/thread-cert/mac802154.py
tests/scripts/thread-cert/message.py
tests/scripts/thread-cert/simulator.py

Sorry for my mistake in #3448 . This PR fixes `key_id_mode` handling and added exception handling when `key_id_mode` is `0`.
According to **IEEE Std 802.15.4-2015**, when Key Id Mode is `0x00`:
> Key is determined implicitly from the originator and recipient(s) of the frame, as indicated in the frame header.
So in our test scripts we cannot actually handle such packets. In case 8_1_01, as I remember, @wgtdkp checked such packets(`HandshakeType.SERVER_KEY_EXCHANGE` and `HandshakeType.CLIENT_KEY_EXCHANGE`) by other means. When we parse such packet we can simply drop them.
However if we leave `key_id_mode = 0` case unhandled, we would get some exceptions which makes people feel that something goes wrong. However dropping packets in this case is a normal behavior. So I added the handling to …

[tests] fix key_id_mode handling and add exception handle

---

.github/workflows/simulation.yml

The code coverage data generated by `./script/test build expect`
will be erased by `VIRTUAL_TIME=0 NODE_MODE=rcp ./script/test clean build expect`'s `clean` step, causing coverage less than actual value. This adds an upload step after the first run to avoid the data loss.

[continuous-integration] avoid coverage data loss

---

src/core/coap/coap_secure.cpp
src/core/common/notifier.cpp
src/core/common/tasklet.cpp
src/core/common/tasklet.hpp
src/core/mac/mac.cpp
src/core/net/ip6.cpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mesh_forwarder_mtd.cpp
src/ncp/ncp_base.cpp
src/ncp/ncp_base_ftd.cpp
src/ncp/ncp_base_mtd.cpp
src/ncp/ncp_uart.cpp

This commit changes the `Tasklet::Post()` method to return `void`
instead of `otError`. This helps simplify its use. The error indicated
whether the tasklet was already posted and was always ignored
(required `IgnoreError()` when posting tasklets). `IsPosted()` method
can be used to determine this when/if needed.

[tasklet] change Post() to return void

---

src/core/net/ip6.cpp
src/lib/spinel/spinel.h
src/ncp/ncp_base_mtd.cpp
tests/scripts/thread-cert/test_ipv6_fragmentation.py

This PR fixes and enhances the handling of IPv6 fragmentation.
It consists of three commits:
**[ncp] ensure IPv6 packet length does not exceed maximum size of SPINEL command payload**
With the current code, it is possible that NCP tries to send IPv6 packet larger than the maximum size of SPINEL command payload. This results in the following error in the wpantund:
```
wpantund[31934]: SpinelNCPInstance-DataPump.cpp:239: Requirement Failed (mInboundFrameSize < sizeof(mInboundFrame))
```
This commit adds additional defines to spinel.h and proper checks in NCP codebase.
**[ip6] do not free the same message twice while handling IPv6 fragment**
This commit fixes the serious bug when IPv6 fragmentation is enabled. It is possible that `HandleDatagram` which is called on complete reassembly, …

[ip6] fix and enhance IPv6 fragmentation

---

src/core/thread/mesh_forwarder.cpp
tests/toranj/start.sh
tests/toranj/test-041-lowpan-fragmentation.py

This commit relaxes the length check for the last 6LoWPAN fragment of
a message. The length of a 6LoWPAN fragment is truncated to be a
multiple of eight bytes (since fragment offset can only be expressed as
multiples of eight). However this requirement does not apply to the
last fragment. This change helps avoid an unnecessary extra fragment
for messages of certain length.
---------
**[toranj] add new test to verify lowpan fragmentation**
This commit adds a new test to verify 6LoWPAN fragmentation logic by
exchanging IPv6 messages with many different lengths between two
nodes.

[mesh-forwarder] allow last 6LoWPAN fragment to use longer length

---

src/posix/platform/radio.cpp

The arguments of the function `otPlatDiagProcess` in posix radio drivers different from 
the one defined in the `diag.h`. It causes the diag module uses the weak definition of
the function `otPlatDiagProcess`. Then all platform defined diag commands are not
available. This PR fixes this issue.

[posix] fix inconsistent function definitions issue

---

examples/platforms/nrf528xx/src/transport/transport.c

When the macro `SPIS_AS_SERIAL_TRANSPORT` is enabled,
`UART_AS_SERIAL_TRANSPORT` and `USB_CDC_AS_SERIAL_TRANSPORT`
are disabled, no one uses the argument `aPseudoReset`. The compiler generates a warning.

[nrf528xx] add `OT_UNUSED_VARIABLE` to avoid compiler warning

---

src/core/meshcop/commissioner.cpp
src/core/meshcop/joiner.cpp
src/core/meshcop/joiner.hpp
tests/scripts/thread-cert/Cert_8_1_01_Commissioning.py
tests/scripts/thread-cert/Cert_8_1_02_Commissioning.py
tests/scripts/thread-cert/Cert_8_2_01_JoinerRouter.py
tests/scripts/thread-cert/Cert_8_2_02_JoinerRouter.py
tools/harness-thci/OpenThread.py
tools/harness-thci/OpenThread_WpanCtl.py

This PR adds validation of joiner PSKd to conform to Thread specifiction:
> A Joining Device Credential is encoded as uppercase alphanumeric characters (base32-thread: 0-9,A-Y excluding I,O,Q, and Z for readability) with a minimum length of 6 such characters and a maximum length of 32 such characters.
Related PR: https://github.com/openthread/ot-commissioner/pull/101

[joiner] add validation of joiner PSKd

---

include/openthread/icmp6.h
src/core/coap/coap.hpp
src/core/net/icmp6.cpp
src/core/net/icmp6.hpp
src/core/thread/address_resolver.cpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mle_router.cpp

According to the Thread Conformance document, we should implement the following requirement:
> All Thread Devices MUST prioritize Thread control messages over other messages.
> Thread control messages include:
> - MLE messages
> - Address Solicit Request and Address Solicit Response messages
> - Address Query and Address Notification messages
> - ICMPv6 Error messages, including ICMPv6 Destination Unreachable
OpenThread currently does not meet three last bullets.

[coap] ensure Thread control messages are prioritized

---

src/core/net/ip6.cpp

When Border Router is built with `OPENTHREAD_CONFIG_IP6_FRAGMENTATION_ENABLE`
flag and receives the message to its Mesh-Local EID, for a small range of IPv6
lengths, NCP may forward both IPv6 fragments and reassembled packet. This commit
ensures the latter situation does not happen.

[ip6] do not pass reassembled IPv6 packet to the host

---

.codecov.yml

Immature comments from Codecov bot shows big reduce in code coverage and is confusing. 
This PR prevent Codecov comment until a number of builds are finished. 
However the number of `after_n_builds` is hardcoded and has to be revised whenever we add a new `codecov/codecov-action@v1` step. 
Do you think it's better to have `after_n_builds` defined? @wgtdkp @bukepo @jwhui

[codecov] only comment after a number of builds

---

src/core/api/channel_monitor_api.cpp

This removes the copying of `ChannelMonitor` in
`otChannelMonitorSetEnabled`, so channel monitor enable/disable can work.

[channel-monitor] remove channel monitor copying

---

include/openthread/link_raw.h
include/openthread/platform/radio.h
src/core/api/link_raw_api.cpp
src/core/crypto/aes_ccm.cpp
src/core/crypto/aes_ccm.hpp
src/core/mac/link_raw.cpp
src/core/mac/link_raw.hpp
src/core/mac/mac.cpp
src/core/mac/mac.hpp
src/core/mac/mac_frame.cpp
src/core/mac/mac_frame.hpp
src/core/mac/mac_types.hpp
src/core/mac/sub_mac.cpp
src/core/mac/sub_mac.hpp
src/core/radio/radio.hpp
src/core/radio/radio_platform.cpp
src/core/thread/key_manager.cpp
src/core/thread/key_manager.hpp
src/core/thread/mle.cpp
src/core/thread/mle_types.hpp
src/lib/spinel/radio_spinel.hpp
src/lib/spinel/radio_spinel_impl.hpp
src/ncp/ncp_base_radio.cpp
src/posix/platform/radio.cpp

This commit adds a new type `otMacKey` which represents a MAC security
key (used by AES-CCM to perform frame security) and core subclass of
this as `Mac::Key`. The same type is used as `Mle::Key`. The
`KeyManager`, `Mac`, `Mle`, and other modules are updated to use the
new `Key` types. The public OT API `otLinkRawSetMacKey` and radio
platform `otPlatRadioSetMacKey()` are also updated to use `otMacKey`.

[mac] adding otMacKey and Mac::Key

---

.github/workflows/build.yml
bootstrap
etc/docker/ot_sim/add_node
script/check-gn-build
script/check-ncp-rcp-migrate
script/check-posix-build-autotools
script/check-posix-build-cmake
script/check-posix-pty
script/check-scan-build
script/check-size
script/clang-format
script/clang-format-check
script/make-pretty
script/test
tests/toranj/build.sh
tests/toranj/start.sh
tools/gerrit/git-squash-merge.sh
tools/harness-automation/start.sh

An alternative to #4886.
This removes `shellharden` and only relies on `shfmt` and `shellcheck` - to address https://github.com/openthread/openthread/pull/4886#discussion_r415219630.
Do we prefer this PR or #4886?

[pretty] add support for shell scripts

---

src/core/Makefile.am
src/core/coap/coap.hpp
src/core/common/extension.hpp
src/core/common/instance.hpp
src/core/common/message.hpp
src/core/common/non_copyable.hpp
src/core/common/notifier.hpp
src/core/common/random_manager.hpp
src/core/common/settings.hpp
src/core/common/tasklet.hpp
src/core/common/timer.hpp
src/core/diags/factory_diags.hpp
src/core/mac/link_raw.hpp
src/core/net/ip6.hpp
src/core/net/netif.hpp
src/core/radio/radio.hpp
src/core/thread/announce_sender.hpp
src/core/utils/channel_manager.hpp
src/core/utils/channel_monitor.hpp
src/core/utils/heap.hpp
src/core/utils/otns.hpp

This PR makes `Instance` and its members non-copyable to prevent issues like https://github.com/openthread/openthread/pull/4970.

[instance] disable instance member copying

---

src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager.hpp

This commit helps ensure the following:
- At most one MGMT_ACTIVE_SET.req message is outstanding.
- At most one MGMT_PENDING_SET.req message is outstanding.

[meshcop] do not send MGMT_*_SET.req while one is outstanding

---

examples/platforms/simulation/platform-config.h

This PR allows use to build `OTNS=1` with or without `VIRTUAL_TIME_UART`.
Later I will enhance OTNS to support both virtual time UART and non virtual time UART.

[otns] allow virtual time UART

---

script/check-arm-build-cmake
script/check-posix-build-cmake
script/check-simulation-build-cmake
tests/toranj/build.sh

This removes the use of `git clean` in scripts to prevent accidental loss of work.

[continuous-integration] remove `git clean` in scripts

---

src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_router.cpp
src/core/thread/router_table.hpp
tests/scripts/thread-cert/config.py

This PR tries to fix the [assertion failure](https://github.com/openthread/openthread/issues/4508#issuecomment-615899675) that occurred when simulating 8x8 nodes forming one partition by [OTNS form_partition.py](https://github.com/openthread/ot-ns/blob/master/pylibs/examples/form_partition.py). 
This bug was found when trying to resolve an issue in #4508.

[mle] fix MLE Router handling errors

---

src/core/mac/mac_frame.cpp
tests/unit/test_mac_frame.cpp

This PR fixes small problems in #4884 
1. I used to assume security is always enabled in enhanced ack, however that's not always the case. So add security part only when it's required.
2. `FindHeaderIeIndex` would return `kInvalidIndex` when IE is not present. It's possible that no IE is in an enh ack, So I use `SkipSecurityHeaderIndex` instead.

[mac-frame] fix problems to generate enh ack

---

src/core/api/coap_api.cpp
src/core/api/ip6_api.cpp
src/core/api/udp_api.cpp
src/core/coap/coap.cpp
src/core/coap/coap.hpp
src/core/coap/coap_message.cpp
src/core/coap/coap_message.hpp
src/core/common/message.cpp
src/core/common/message.hpp
src/core/meshcop/dtls.cpp
src/core/meshcop/dtls.hpp
src/core/meshcop/joiner_router.cpp
src/core/meshcop/meshcop.hpp
src/core/net/icmp6.cpp
src/core/net/ip6.cpp
src/core/net/ip6.hpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder.hpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mesh_forwarder_mtd.cpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
tests/unit/test_priority_queue.cpp

This PR contains a bunch of smaller changes/enhancements in `message` modules:
- **[message] adding Message::Settings** 
The `Message::Settings` mirrors `otMessageSettings` and is used when allocating a new `Message`.
- **[message] add Message::Priority enumeration type** 
- **[message] add Message::SubType** 
- **[message] add Message::Type** 
- **[message] add helper methods to get Message Metadata** 
This commit renames the message metadata to `MessageMetadata` and adds helper method `Buffer::GetMetadata()` to get the metadata.
- **[message] update Buffer and MessagePool to use LinkedList methods** 
- **[message] update method decelerations, add documentation**

[message] misc enhancements 

---

src/core/thread/network_diagnostic.cpp
src/core/thread/network_diagnostic.hpp

This PR contains a bunch of smaller changes in `NetworkDiagnostics` modules (the commits are separate for easier review): 
- **[network-diagnostic] fix parsing of Type List TLV in `HandleDiagnosticReset()`**
- **[network-diagnostic] skip unrecognized TLV type in `FillRequestedTlvs()`**
- **[network-diagnostic] use `Tlv` helper methods to append simple TLVs**
- **[network-diagnostic] simplify `GetNextDiagTlv()` implementation**
This commit simplifies the implementation of `GetNextDiagTlv()` by
skipping unrecognized TLVs from `default` case and jumping to top of
the loop for a next TLV, and adding a common `ExitNow()` at the end of
`switch()` statement to handle when a TLV is found and successfully
parsed. This change helps remove the need for `OT_UNREACHABLE_CODE()`
use.
- …

[network-diagnostics] misc. enhancements/fixes

---

src/posix/platform/uart.cpp

Chances are that the ot-ctl client exits between read error check and
write. This will lead to a SIGPIPE crash. We can ignore this signal and
check the error code instead.

[posix] tolerate SIGPIPE under daemon mode

---

examples/apps/ncp/Makefile.am
third_party/mbedtls/Makefile.am

This PR changes libmbedcrypto_radio.a to libmbedcrypto-radio.a, since every other library uses dash rather than underscore in the name.

[build] change underscore to dash in libmbedcrypto name

---

src/cli/cli.cpp

This fixes the argument parsing for `counters` command. The lines calling `otLinkResetCounters` and `otThreadResetMleCounters` are unreachable and this fixes it.

[cli] fix argument parsing for counters command

---

tools/harness-automation/autothreadharness/harness_case.py

1. found setting browser window size before navigating to url may cause the browser stuck and get timeout exception:
File "autothreadharness\harness_case.py", line 323, in _init_browser
browser.get(settings.HARNESS_URL)
File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 248, in get
self.execute(Command.GET, {'url': url})
File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
self.error_handler.check_response(response)
File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
raise exception_class(message, screen, stacktrace)
TimeoutException: Message: timeout: Timed out receiving message from renderer: -0.005
related bug: …

[harness-automation] fix browser stuck in navigating to url

---

tools/harness-thci/OpenThread.py
tools/harness-thci/OpenThread_WpanCtl.py

This PR fixes existing issues in address filters.
- Fix misuse of address filter modes
- `disabled` should be `disable`
- `Whitelist` should be `whitelist`
- `Blacklist` should be `blacklist`
- Fix errors in removing `macfilter` entries
**Impact on 1.1 certification:**
This PR does not impact 1.1 certification because only `OpenThread_WpanCtl.py` is changed. In 1.1 certification, all **golden** devices are controlled by `OpenThread.py`. `OpenThread_WpanCtl.py` is used to control OTBR DUT, and `mac filter` feature is not useful for a DUT. @librasungirl @jwhui

[thci] fix address filter code issues

---

src/core/common/tlvs.cpp
src/core/common/tlvs.hpp
src/core/meshcop/border_agent.cpp
src/core/meshcop/commissioner.cpp
src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager_ftd.cpp
src/core/meshcop/energy_scan_client.cpp
src/core/meshcop/joiner.cpp
src/core/meshcop/joiner_router.cpp
src/core/meshcop/meshcop_leader.cpp
src/core/meshcop/meshcop_tlvs.cpp
src/core/meshcop/meshcop_tlvs.hpp
src/core/meshcop/panid_query_client.cpp
src/core/thread/address_resolver.cpp
src/core/thread/announce_begin_server.cpp
src/core/thread/energy_scan_server.cpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_router.cpp
src/core/thread/mle_tlvs.hpp
src/core/thread/network_data_leader_ftd.cpp
src/core/thread/network_diagnostic.cpp
src/core/thread/network_diagnostic_tlvs.hpp
src/core/thread/panid_query_server.cpp
src/core/thread/thread_tlvs.hpp

This PR contains 3 related commits:
**[tlvs] rename helper methods to FindTlv (FindUint8Tlv, etc)**
This commit renames the helper `static` methods in `Tlv` class. It
harmonizes the naming model to use `FindTlv()` for different flavors
of `Tlv` methods which search within a given `Message`/bufer to find a
TLV. It also removes the re-definition of same static methods in `Tlv`
sub-classes. This helps simplify the use of such methods and avoids
the shadowing of methods due to re-definition in the sub-class (the
sub-class re-definition allows more specific TLV `Type` enumeration
parameter to be used, however the base case version will continue to
work due to implicit conversion of `enum` to integer).
**[tlvs] change Tlv::AppendTlv value param to be `void *`**
This commit changes the …

 [tlvs] add ReadTlv (ReadUint8Tlv, etc) to read a TLV from a message at given offset

---

src/core/api/crypto_api.cpp
src/core/crypto/aes_ccm.cpp
src/core/crypto/aes_ccm.hpp
src/core/crypto/aes_ecb.cpp
src/core/crypto/aes_ecb.hpp
src/core/crypto/ecdsa.cpp
src/core/crypto/ecdsa.hpp
src/core/crypto/hmac_sha256.cpp
src/core/crypto/hmac_sha256.hpp
src/core/crypto/mbedtls.cpp
src/core/crypto/mbedtls.hpp
src/core/crypto/sha256.cpp
src/core/crypto/sha256.hpp
src/core/mac/mac.cpp
src/core/mac/mac_frame.cpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
tests/unit/test_aes.cpp

This PR contains a bunch of smaller changes in `Crypto` modules: 
**[aes-ccm] add Mode enum type to indicate encrypt vs decrypt mode**
This commit adds a new enumeration type `Mode` to indicate the
encryption vs decryption mode in AesCcm::Payload() method.
**[aes-ccm] add GetTagLength() method and simplify Finalize()**
**[aes-ccm] change AesCcm::Init() to assert on bad tag length input param**
Instead of returning `OT_ERROR_INVALID_ARGS` on bad input, the
`AesCcm::Init()` now asserts if the input tag length parameter is not
valid.
**[ars-ecb] fix the AesEcb::SetKey() document about key len being in bits**
**[aes-ccm] small enhancements**
- reorder AesCcm member variable to help with alignments
- use CHAR_BIT
- remove check of tag length from Finalize
- use `memcpy`/`memset` to copy/clear …

[crypto] misc enhancements in AesCcm and other crypto modules

---

tests/scripts/expect/cli-counters.exp
tests/scripts/expect/cli-misc.exp
tests/scripts/expect/cli-routereligible.exp

This adds `expect` tests for many CLI commands. Some simple commands are placed in `cli-misc.exp`.

[test] add various CLI command tests

---

src/core/net/ip6.cpp
src/core/thread/thread_netif.cpp
src/core/thread/thread_netif.hpp

Existing implementation only looks at addresses configured on the
network interface to determine what prefixes are on-link (on-mesh for
Thread). When the network interface does not have an assigned address
for a given on-mesh prefix, any packet with that on-mesh prefix will
not be forwarded to the Thread network.
This commit also checks the destination address against Thread's set
of on-mesh prefixes, independent of whether addresses out are assigned
out of the on-mesh prefix.
Resolves #5022

[ip6] forward any packet with on-mesh destination

---

.github/workflows/build.yml
.github/workflows/simulation.yml
.github/workflows/toranj.yml
etc/docker/arm32v7_ubuntu_wpantund/Dockerfile
etc/docker/x86_ubuntu_wpantund/Dockerfile
script/bootstrap

This commit change apt to apt-get for the WARNING in build logs:
```
WARNING: apt does not have a stable CLI interface. Use with caution in
scripts.
```

[continuous-integration] use apt-get instead of apt

---

src/core/common/message.cpp
src/core/common/message.hpp
src/core/mac/mac.cpp
src/core/mac/mac.hpp
src/core/mac/mac_frame.cpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder_ftd.cpp

OpenThread now have **TIME_SYNC** IE. And the presence of IE would also effect the frame version and IE present field. This PR encapsulate the process to update these things so that it could be easily extended to support other IEs that would be introduced later.

[low-power] encapsulate method to update header IE

---

src/core/Makefile.am
src/core/coap/coap_message.hpp
src/core/common/clearable.hpp
src/core/common/equatable.hpp
src/core/mac/mac_types.cpp
src/core/mac/mac_types.hpp
src/core/net/ip6_address.cpp
src/core/net/ip6_address.hpp
src/core/net/netif.hpp
src/core/net/socket.hpp
src/core/thread/key_manager.hpp
src/core/thread/mle_types.hpp
src/core/thread/network_data_tlvs.hpp

**[core] add Equatable class providing overloads of `==` and `!=` operator**
This commit adds new class `Equatable` (inherited by other types)
providing overloads of operators `==` and `!=`. The implementation
simply compares all the bytes of two instances of same type to be
equal (using `memcmp`).
**[core] add Clearable class providing simple Clear() method**
This commit adds new class `Clearable` (inherited by other types)
providing simple implementation of `Clear()` which sets all the
instance bytes to zero (using `memset()`).

[core] adding Equatable and Clearable subclasses

---

src/core/thread/mle_router.cpp

The leader is authoritative in the operational datasets that it
distributes. This commit ensures that a device becoming a leader
restores the operational dataset from non-volatile. This ensures that
the operational datasets that the leader attempts to distribute are
the same as in its non-volatile storage.

[mle] restore operational datasets when becoming leader

---

script/bootstrap

My host:
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```
The PPA source does not include the package `gcc-arm-embedded` for Ubuntu 20.04.
In fact, users can directly use the toolchain provided by official sources.
Has been tested and available on my machine.

[bootstrap] remove PPA on Ubuntu 20.04 and later

---

tests/scripts/expect/cli-2-nodes.exp
tests/scripts/expect/cli-ping.exp

This adds test cases for `child` command. Also moves `ping` tests with 2 nodes to `cli-2-nodes.exp`, future tests requiring 2 nodes will be placed in this file.

[test] add expect tests for `child`

---

tests/scripts/thread-cert/Cert_5_3_10_AddressQuery.py
tests/scripts/thread-cert/Cert_5_7_01_CoapDiagCommands_A.py
tests/scripts/thread-cert/Cert_8_1_01_Commissioning.py
tests/scripts/thread-cert/Cert_8_1_02_Commissioning.py
tests/scripts/thread-cert/Cert_8_2_01_JoinerRouter.py
tests/scripts/thread-cert/Cert_8_2_02_JoinerRouter.py
tests/scripts/thread-cert/Cert_9_2_02_MGMTCommissionerSet.py
tests/scripts/thread-cert/Cert_9_2_04_ActiveDataset.py
tests/scripts/thread-cert/Cert_9_2_07_DelayTimer.py
tests/scripts/thread-cert/Cert_9_2_08_PersistentDatasets.py
tests/scripts/thread-cert/Cert_9_2_09_PendingPartition.py
tests/scripts/thread-cert/Cert_9_2_10_PendingPartition.py
tests/scripts/thread-cert/Cert_9_2_11_MasterKey.py
tests/scripts/thread-cert/Cert_9_2_12_Announce.py
tests/scripts/thread-cert/Cert_9_2_13_EnergyScan.py
tests/scripts/thread-cert/Cert_9_2_14_PanIdQuery.py
tests/scripts/thread-cert/Cert_9_2_15_PendingPartition.py
tests/scripts/thread-cert/Cert_9_2_16_ActivePendingPartition.py
tests/scripts/thread-cert/Cert_9_2_17_Orphan.py
tests/scripts/thread-cert/Cert_9_2_18_RollBackActiveTimestamp.py
tests/scripts/thread-cert/Makefile.am
tests/scripts/thread-cert/test_coap_observe.py
tests/scripts/thread-cert/test_coaps.py
tests/scripts/thread-cert/test_diag.py
tests/scripts/thread-cert/test_ipv6_fragmentation.py
tests/scripts/thread-cert/test_ipv6_source_selection.py
tests/scripts/thread-cert/test_reed_address_solicit_rejected.py
tests/scripts/thread-cert/test_service.py
tests/scripts/thread-cert/thread_cert.py

This commit skip running expected fail tests so that it will be easier
to find real failures and saves some time.

[tests] skip running expected fail tests

---

examples/platforms/simulation/radio.c
examples/platforms/utils/mac_frame.cpp
examples/platforms/utils/mac_frame.h
src/core/mac/mac_frame.cpp

This commit change the simulation radio to send secured enh-ack for
secured frames. This enhances the security for real devices and improves
code coverage for testing.

[simulation] send enh-ack for 802.15.4-2015 frames

---

src/cli/cli.cpp
tests/scripts/expect/cli-2-nodes.exp

This adds `expect` tests for testing the pcap receiving function of promiscuous mode. Also makes `otLinkSetPromiscuous` be called before `otLinkSetPcapCallback` so that the callback won't be set when promiscuous mode fails to start.

[test] add expect tests for pcap receiving

---

src/core/meshcop/commissioner.cpp
src/core/meshcop/joiner.cpp
src/core/meshcop/meshcop.cpp
src/core/meshcop/meshcop.hpp
src/core/meshcop/meshcop_tlvs.cpp
src/core/meshcop/meshcop_tlvs.hpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_router.cpp
src/core/thread/mle_router.hpp
tests/unit/CMakeLists.txt
tests/unit/Makefile.am
tests/unit/test_steering_data.cpp

This commit adds a new class `MeshCoP::SteeringData` which manages
the Steering Data and bloom filter generating and filtering.

[meshcop] adding SteeringData class

---

tests/scripts/expect/_common.exp
tests/scripts/expect/_multinode.exp
tests/scripts/expect/cli-2-nodes.exp

This puts the scripts setting up Thread networks into separate files so that they can be reused by multiple test scripts. After this we can split the tests in `cli-2-nodes.exp` into multiple files without having to repeat codes in each file.

[test] modularize expect scripts

---

etc/cmake/options.cmake

In options.cmake `OPENTHREAD_CONFIG_`**EXTERNAL_HEAP**`_ENABLE` is used, while
in common-switches.mk and the source code the slightly different
`OPENTHREAD_CONFIG_`**HEAP_EXTERNAL**`_ENABLE` is used.
Signed-off-by: Markus Becker <markus.becker@tridonic.com>

[cmake] use the correct define for external heap

---

include/openthread/dataset.h
include/openthread/instance.h
src/cli/README_DATASET.md
src/cli/cli_dataset.cpp
src/cli/cli_dataset.hpp
src/core/api/dataset_api.cpp
src/core/meshcop/dataset.cpp
src/core/meshcop/dataset.hpp
src/core/meshcop/dataset_local.cpp
src/core/meshcop/dataset_local.hpp
src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager.hpp

**Problem**
Thread stores and distributes Active and Pending Operational Datasets as opaque binary objects. To support forward compatibility with newer Thread versions, Thread devices must store and propagate TLVs even when they are unknown. The existing dataset API only allows getting/setting dataset values that are defined.
**Solution**
Introduce new APIs (and associated CLI commands) that allow getting/setting Active/Pending Operational Datasets via binary-encoded TLVs. This allows higher layers to copy Operational Datasets from one device to another without losing any information.
Example CLIs:
Print Active Operational Dataset as hex-encoded TLVs.
```bash
> dataset active binary
0e080000000000010000000300001035060004001fffe002084eb74ab03c56e6d00708fdc7fe165c83a67805108e2104f183e698da87 …
```

[meshcop] support get/set operational dataset via raw TLVs

---

src/posix/platform/alarm.cpp

This makes it consistent with MilliGetNow() conterpart

[posix] fix otPlatAlarmMicroGetNow to use scaled time

---

src/core/common/settings.cpp
src/core/common/settings.hpp
src/core/thread/dua_manager.cpp
src/core/thread/dua_manager.hpp
src/core/thread/mle.cpp

This PR depends on #4900 (<-- #4862 <-- #4854).
Please review the last commit which serves the purpose of storing dad counter.
Due to that DUA DAD is not submitted yet, for this PR, just manually verified the dad counter storage and consistency of DUA address generated after reset on another fork branch [librasungirl:12_dua_store_dadcounter_test_only](https://github.com/librasungirl/openthread/commits/12_dua_store_dadcounter_test_only) which introduces some test APIs to manually update (and store) the dad counter.

[dua] save dad counter into non volatile memory

---

tests/scripts/expect/cli-child.exp
tests/scripts/expect/cli-promiscuous.exp
tests/scripts/expect/cli-router.exp
tests/scripts/expect/cli-scan.exp

This splits `cli-2-nodes.exp` into multiple files each of which contains tests for a single command.

[test] split cli-2-nodes.exp into multiple files

---

src/core/thread/network_data_leader_ftd.cpp

To avoid buffer overrrun issues.

[network-data] in Validate() only check dups against prior prefixes

---

src/posix/client.cpp

This PR resolves https://github.com/openthread/ot-br-posix/issues/468.
This issue occurs when ot-ctl reads the CLI output in multiple chunks in which the last line of a chunk does not ends with a '\r\n'. The last line is then dropped incorrectly. 
This PR fixes this issue:
- Output the last line (without `\r\n`) if it's not `">"` (have to drop `'>'` because we can not determine whether or not to output `'>'`)
- Output `">"` if the first char is not `' '` but the previous `promptState` is 1 (meaning `'>'` was dropped previous but should have been printed).
I think the fix is difficult to understand and in long term we should switch to a more readable implementation that just reads and processes one complete line at a time without these state transfers. Thoughts? @bukepo @gjc13 @jwhui

[posix] fix ot-ctl CLI output missing

---

examples/platforms/efr32mg12/crypto/efr32-mbedtls-config.h
examples/platforms/efr32mg13/crypto/efr32-mbedtls-config.h
examples/platforms/efr32mg21/crypto/efr32-mbedtls-config.h
third_party/silabs/Makefile.am

Turns on the following:
* SHA256 acceleration on all EFR32 devices (used for SHA256, HMAC-SHA256, ECDSA and DRBG)
* ECDSA/ECDH acceleration on EFR32MG21 (used in DTLS and exposed to application through otCryptoEcdsaSign)
* AES-CCM acceleration on EFR32MG21 (used in DTLS)
* AES-CMAC acceleration on EFR32MG21 (used for PBKDF2)
Not enabled yet, needs a new GSDK release:
* end-to-end EC-JPAKE acceleration on EFR32MG21 (used in DTLS)

[efr32] update EFR32 mbedTLS configuration to use more hardware acceleration

---

examples/Makefile-efr32mg21

Detected on EFR32MG21 with hardware acceleration turned on, all inside mbedTLS' library/ecdsa.c:
* Turning on ECDSA signing acceleration (MBEDTLS_ECDSA_SIGN_ALT) triggers an unused parameter on rs_ctx in mbedtls_ecdsa_write_signature_restartable
* Turning on ECDSA verification acceleration (MBEDTLS_ECDSA_VERIFY_ALT) triggers an unused parameter on rs_ctx in mbedtls_ecdsa_read_signature_restartable
* Turning on both ECDSA signing & verification acceleration (MBEDTLS_ECDSA_SIGN_ALT + MBEDTLS_ECDSA_VERIFY_ALT) triggers an unused function error on static function derive_mpi
Looking at the latest mbed TLS development branch, it seems this issue will not be resolved soon. Therefore, we're turning off unused parameter and unused function warnings when building mbedTLS for the specific platform …

[efr32] turn off specific warnings for certain mbed TLS configurations

---

script/bootstrap

I tried to build some nRF52840 examples on Ubuntu 20.04, but it failed with a `stdio.h: No such file or directory` error. It turns out `libnewlib-arm-none-eabi` is required and is a recommended dep of `gcc-arm-none-eabi`, but it was obviously not installed because of the `--no-install-recommends` flag.
This PR fixes this issue.

[bootstrap] add missing newlib on Ubuntu >= 20.04

---

tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/simulator.py

This PR makes 1.2 simulation tests much more stable by using longer timeouts. **Applying this fix, 1.2 simulation tests have passed 20 times continuously.**
Background:
- **The 1.2 simulation tests are failing frequently recently.**
- Tests show that this issue exists even at commit ab029e (Apr 17)
- Tests show that expecting `pexpect.EOF` in `Node.destroy` might take more than 5 seconds, and the current timeout is 4s.
- Tests show that socket timeout is likely to happen after node `reset`. Making sure `reset` complete in `Node.reset` can resolve this issue, but it turned out to be very tricky to implement. 
The test results and the fact that I can never reproduce this issue locally make me think that the fails are not due to any bug introduced by any commit, but just due to performance …

[tests] use longer timeouts for simulation tests

---

src/posix/client.cpp

This PR fixes 3 `implicit conversion changes signedness` errors, when trying to build the posix core in daemon mode on darwin.

[posix] fix build errors on macOS

---

include/openthread/instance.h
include/openthread/ip6.h
src/cli/cli.cpp
src/core/backbone_router/local.cpp
src/core/meshcop/border_agent.cpp
src/core/net/dhcp6_client.cpp
src/core/net/dhcp6_server.hpp
src/core/net/netif.cpp
src/core/thread/dua_manager.cpp
src/core/thread/mle.cpp
src/core/utils/slaac_address.cpp
src/ncp/ncp_base_mtd.cpp

Add a type flag to addresses so that applications are able to behave
differently on the type of address.
Signed-off-by: Markus Becker <markus.becker@tridonic.com>

[ip6-address] add a type flag to addresses

---

tests/scripts/expect/cli-childip.exp
tests/scripts/expect/cli-macfilter.exp

This adds `expect` tests for 3 commands: `macfilter`, `childip`, and `version`

[test] add expect tests for macfilter, childip, version

---

Android.mk
BUILD.gn
src/core/CMakeLists.txt
src/core/Makefile.am
src/core/api/thread_api.cpp
src/core/common/instance.hpp
src/core/meshcop/joiner.cpp
src/core/thread/discover_scanner.cpp
src/core/thread/discover_scanner.hpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder.hpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/thread_netif.cpp
src/core/thread/thread_netif.hpp
tests/toranj/test-005-discover-scan.py
tests/toranj/wpan.py

This commit adds new class `DiscoverScanner` which implements the MLE
Discover Scan process (moving and simplifying all the code related to
this from `Mle` and `MeshForwarder` into same file/class).
----
New commits:
**[toranj] enhance discover scan test - cover filtering, channel-mask**
This commit enhances `test-005-discover-scan` to cover discover
scan over subset of channels, PAN ID filtering, and joiner only,
bloom filter scan behavior.
**[discover-scanner] allow filtering based on a user given ID**
This commit enhances the filtering behavior of Discover Scan. When
filtering is enabled, MLE Discovery Responses with steering data
(bloom filter) not containing a given ID (MAC Extended Address) are
filtered. This commit updates the `DiscoverScanner::Discover()` to
allow the ID used for …

[discover-scanner] adding Mle::DiscoverScanner

---

script/check-size

`size-report` failed frequently recently. 
This PR improves the stability of `size-report ` by retrying multiple times (with exponential backoffs by default).
This PR allows [Glitch](https://glitch.com/) to wake up the App if the [App went to sleep](https://glitch.com/help/restrictions/). 
We should also need to change the [bash](https://openthread-size-report.glitch.me/size-report/1354027/bash) script. @bukepo 
**It seems not working since `size-report` check failed still.**

[size-report] retry multiple times

---

third_party/mbedtls/CMakeLists.txt

Fixes https://github.com/openthread/openthread/issues/5114 by checking the version of `unifdef`. Also renames `mbedtls-config.h` to `openthread-mbedtls-config.h` to enable in-source build.

[cmake] fix error messages on macOS

---

src/core/utils/otns.cpp

This PR fixes build errors for `OTNS=1 JOINER=0`

[otns] allow build without JOINER=1

---

examples/platforms/simulation/uart.c

These code hasn't been used since we remove OPENTHREAD_TARGET_DEFINES in
examples/ in 2016.

[simulation] remove linux specific prctl

---

examples/platforms/simulation/radio.c
examples/platforms/utils/mac_frame.cpp
examples/platforms/utils/mac_frame.h
src/core/mac/mac_frame.cpp

This commit adds transmit security support for simulation radio so that security Enh-ACK could be handled at radio layer. This commit also fixes issue #5041.

[simulation] support transmit security at simulation radio

---

src/lib/spinel/spinel.c

`spinel.h` and `spinel.c` are soruce files that may be used by host
side drivers and therefore the souurce code itself should not use any
of OT header files. Spienl file provide `SPINEL_PLATFORM_HEADER` to
allow platform to add their own includes if they want to.
-----
The inclusion of `#include "utils/wrap_string.h"` was added from #4885 (I think by mistake).

[spinel] fix use of OT header file in spinel.c

---

etc/docker/codelab_otsim/Dockerfile

To support the updated Docker Simulation Codelab.

[docker] build ot-daemon/ot-ctl in codelab_otsim

---

src/core/thread/network_data_leader.cpp
src/core/utils/slaac_address.cpp
src/core/utils/slaac_address.hpp
tests/scripts/thread-cert/Cert_5_6_05_NetworkDataRegisterAfterAttachRouter.py
tests/scripts/thread-cert/Cert_5_6_06_NetworkDataExpiration.py
tests/scripts/thread-cert/test_on_mesh_prefix.py

This PR includes the following fixes.
- fix `NetworkData::Leader::IsOnMesh()` to check on-mesh flags.
- fix tests to specify on-mesh flag in prefix 3.
- fix SLAAC to set prefix length to /128 when prefix is not on mesh.
Resolves #5112

[network-data] only send ADDR_QRY.qry for on-mesh prefixes

---

include/openthread/instance.h
include/openthread/link.h
src/cli/cli.cpp
src/core/api/link_api.cpp
src/core/mac/mac_filter.cpp
src/core/mac/mac_filter.hpp
src/ncp/ncp_base_mtd.cpp

This commit contains some smaller enhancements in `Mac::Filter`:
- Use C++11 range-based `for` loop when iterating over filter entries
- Define `Filter:Mode` enum (mirror of `otMacFilterAddressMode`)
- Change `Filter::SetMode()` and `otLinkFilterSetAddressMode()` to
return `void` (update its use from CLI/NCP code).
- Simplify `Filter::Apply()` implementation.
- Add new separate public OT and internal APIs to set/clear default
RSS-In (e.g., `SetDefaultRssIn()`/`ClearDefaultRssIn()`).
- Return no error (instead of `ALREADY`) from `Filter::AddAddress()`
and its corresponding public `otLinkFilter` API when entry is already
present in the list.
- Do not return `NOT_FOUND` error from `Filter::Remove{Address/RssIn}()`.
- Update public `otLinkFilter{API}` documentation.
- Update NCP and CLI code …

[mac-filter] misc enhancements

---

include/openthread/commissioner.h
include/openthread/instance.h
include/openthread/joiner.h
src/core/meshcop/joiner.hpp
src/core/meshcop/meshcop.hpp
tests/toranj/openthread-core-toranj-config.h
tests/toranj/start.sh
tests/toranj/test-042-meshcop-joiner-discerner.py
tests/toranj/wpan.py

This commit adds a `toranj` test-case covering the commissioning
behavior using a Joiner Discerner:
- Verifies setting and clearing discriminator with different values
and bit-lengths (on a Joiner).
- Verifies commissioning using discerner (and EUI64).
- Verifies that commissioner would prefer a Joiner entry with the
longest matching discerner length.
--------
This is on top of the changes from https://github.com/openthread/openthread/pull/5137. It also contains a commit to change `toranj` workflow to use `wpantund` branch from https://github.com/openthread/wpantund/pull/472.

[toranj] add test covering meshcop with Joiner Discerner

---

src/core/common/linked_list.hpp
tests/unit/test_linked_list.cpp

This commit fixes the `LinkedList::Find()` implementation when list is
empty. It also updates the unit test for linked-list to verify the
`Find()` (particularly when it is expected to fail and not find the
entry in the list).

[linked-list] fix Find() when list is empty

---

tests/scripts/expect/_common.exp
tests/scripts/expect/cli-channel.exp
tests/scripts/expect/cli-child.exp
tests/scripts/expect/cli-childip.exp
tests/scripts/expect/cli-coex.exp
tests/scripts/expect/cli-counters.exp
tests/scripts/expect/cli-dataset.exp
tests/scripts/expect/cli-extaddr.exp
tests/scripts/expect/cli-ipmaddr.exp
tests/scripts/expect/cli-log-level.exp
tests/scripts/expect/cli-mac.exp
tests/scripts/expect/cli-macfilter.exp
tests/scripts/expect/cli-misc.exp
tests/scripts/expect/cli-neighbor.exp
tests/scripts/expect/cli-ping.exp
tests/scripts/expect/cli-promiscuous.exp
tests/scripts/expect/cli-pskc.exp
tests/scripts/expect/cli-router.exp
tests/scripts/expect/cli-routereligible.exp
tests/scripts/expect/cli-scan-discover.exp
tests/scripts/expect/posix-diag-rcp.exp
tests/scripts/expect/posix-max-power-table.exp
tests/scripts/expect/posix-rcp.exp
tests/scripts/expect/posix-scan-tx-to-sleep.exp
tests/scripts/expect/tun-dns-client.exp
tests/scripts/expect/tun-netif.exp
tests/scripts/expect/tun-sntp.exp

This PR tries to reduce expects fails in GitHub actions:
- `wait_for` only sends command when it's not empty
- increases the default `expect` timeout from 1s to 3s.

[github-actions] fix expects fail by chance

---

src/core/common/logging.hpp
src/core/utils/otns.cpp

This PR adds a default implementation for `otPlatOtnsStatus`, which emits OTNS status messages to log, so that `OTNS=1` could be used with real devices. This is required for the Silk-OTNS integration work, as Silk will pick up these messages and reroute them to OTNS for visualization purposes.

[otns] add default implementation for otPlatOtnsStatus

---

.github/workflows/simulation.yml
examples/platforms/utils/CMakeLists.txt
examples/platforms/utils/Makefile.am
examples/platforms/utils/otns_utils.cpp
src/core/common/logging.hpp
src/core/utils/otns.cpp

This PR fixes #5170 
This PR also fixes the issue that OTNS tests failed to use openthread of the current PR, but used openthread master instead. 
@ctan-g could you verify if this fix works for Silk?

[otns] fix simulation to use strong otPlatOtnsStatus definition

---

doc/site/en/guides/thread-primer/index.md
doc/site/en/guides/thread-primer/ipv6-addressing.md

Fix some errors found in #5106 discussion. 
1. @Vyrastas 
> Yes you are correct. Can you change to:
"Thread is independent of other 802.15 mesh networking protocols, such a ZigBee, Z-Wave, and Bluetooth LE."
2. @librasungirl 
>  I think the text where the number on a Router (pentagon) is the Router ID, and the number on an End Device (circle) is the Child ID doesn't match the picture which demonstrates the RLOC16, but not Router ID or Child ID.

[devsite] fix wrong description in Thread Primer (en)

---

src/core/meshcop/dtls.cpp
src/core/net/ip6.cpp
src/core/net/netif.cpp
src/core/net/netif.hpp
src/core/thread/address_resolver.cpp
src/core/thread/dua_manager.cpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp

This commit contains some smaller enhancements in netif:
- Add method to check if unicast/multicast address is external or
internal (e.g., `IsUnicastAddressExternal`)
- Simplify iteration over (external) multicast addresses and remove
`GetNextExternalMulticast()`.
- Use range-based `for` loop for iteration over external address
arrays.
- Rename `IsUnicastAddress()` to `HasUnicastAddress()`.
- Clarify method documentation specially between internal and
external addresses (how the passed-in address parameter is used,
i.e., copied into another entry from an address pool for external
vs. directly used for internal addresses).

[netif] misc enhancement

---

src/core/net/dhcp6_client.cpp

This PR includes the following fixes:
- only close socket if no agents exist (resolves #5166)
- update DHCPv6 service RLOC on new network data (resolves #5167)

[dhcp6-client] only close socket when no agents and update service RLOC

---

src/core/common/linked_list.hpp
src/core/thread/address_resolver.cpp
src/core/thread/address_resolver.hpp
tests/unit/test_linked_list.cpp

This commit adds new methods in `LinkedList` to search in the list for
an entry matching a given entry indicator (specified with a template
`Indicator` type). To use these methods, users are expected to provide
method `bool Matches(const Indicator &aIndicator) const` on the entry
`Type` itself (which is then used to match each entry in the list with
the indicator). This commit also changes the linked-list methods to
use `Find()` internally. Finally it updates the linked-list unit test
to cover behavior of the newly added methods.
--------
**_[address-resolver] use new linked list method to find cache entry matching an EID_**
--------
The newly added `LinkedList` method will be helpful for `netif`, e.g.,we can find/remove an entry in unicast/multicast address list searching using a given …

[linked-list] add new template {Contains/Find/Remove}Matching() methods

---

src/core/meshcop/dtls.cpp
src/core/meshcop/dtls.hpp

This commit contains the following:
- Remove unused `SendHandler` type and `mSendHandler` variable.
- Follow style guide for `#endif` comments.
- Define `Dtls::State` as private.
- Define DTLS module constant enums as private.
- Ensure `mReceiveHandler` is not null before invoking.
- Inline simple setter `SetSslAuthMode()`.
- Follow style guide for param names in `HandleMbedtlsDebug()`.

[dtls] misc enhancements (remove unused defs, declare enum as private)

---

examples/platforms/efr32mg12/flash.c
examples/platforms/efr32mg13/flash.c
examples/platforms/efr32mg21/flash.c

This removes all unnecessary calls to nvm3 open and close that were being made when handling nvm operations.
In a normal mode of operation, the nvm open call should be made only once during initialization.
The only way these changes could be verified was by building a binary, flashing it on a node and making sure that the node's network operations (like forming a network) were okay.

[efr32] remove unnecessary nvm3 calls

---

src/core/net/netif.cpp
src/core/net/netif.hpp

This commit simplifies the `Netif` implementation by using newly added
`LinkedList::FindMatching()` methods to search in unicast/multicast
address list for an entry matching a given IPv6 address.

[netif] use newly added linked-list helper methods

---

src/core/net/udp6.cpp
src/core/net/udp6.hpp

This commit adds `UdpSocket::Matches()` to match a UDP socket with a
given `MessageInfo`. This is then used alongw with the newly added
linked-list `FindMatching()` method to find a matching socket from the
list of UDP sockets in `Udp::HandlePayload()`.

[udp6] use newly added linked-list to search for a matching socket

---

.gitignore
script/test

This stores debug logs from `expect` and prints them if a test fails to enable easier debugging.

[test] print debug info when expect tests fail

---

src/core/mac/mac_frame.hpp
src/core/radio/radio.cpp
src/core/radio/radio.hpp
src/core/utils/otns.cpp
src/core/utils/otns.hpp

This PR adds code in base radio implementation to emit radio events to logs, when OTNS is turned on. This is for Silk-OTNS integration's message visualizations.
This PR works together with https://github.com/openthread/ot-ns/pull/42

[otns] add radio event status emission

---

.github/workflows/simulation.yml

This adds tests of `ot-commissioner` as part of GitHub Action workflows.
This PR depends on https://github.com/openthread/ot-commissioner/pull/123.

[test] add external commissioner tests

---

src/core/thread/mle_router.cpp

This PR fixes #4541 
**We always need to update existing `router` references after calling `ProcessRouteTlv`.**
A similar bug was fixed by #4860

[mle] fix invalid router after ProcessRouteTlv

---

src/core/meshcop/joiner_router.cpp
src/core/meshcop/joiner_router.hpp

The existing Joiner Entrust process is as follows:
- The Joiner sends JOIN_FIN.req and receives JOIN_FIN.rsp from the Joiner Router.
- The Joiner sets up a 4000 ms timer to receive the JOIN_ENT.ntf.
- The Joiner Router generates the JOIN_ENT.ntf and enqueues it, setting up a 50 ms timer to send it.
- When the Joiner Router timer triggers it sends the heading message from the queue ONLY if the previous transaction already completed. This is done like this because whenever a new JOIN_ENT.ntf is sent the KEK in the KeyManager is changed, and it's required to keep it in order to decrypt the CoAP ACK.
This approach presents a couple of issues:
- It blocks the message queue up to the maximum CoAP transaction time, which can be much longer than the Joiner 4 seconds timeout.
- Even worse, if the …

[meshcop] JR: don't wait for previous rsp to send a new JOIN_ENT.ntf

---

src/core/Makefile.am
src/core/common/message.cpp
src/core/common/message.hpp
src/core/common/pool.hpp
src/core/net/netif.cpp
src/core/net/netif.hpp
src/core/thread/address_resolver.cpp
src/core/thread/address_resolver.hpp
tests/unit/CMakeLists.txt
tests/unit/Makefile.am
tests/unit/test_pool.cpp

This commit adds a template `Pool<Type, kPoolSize>` class representing
an object pool. `Message`, `Netif`, and `AddressResolver` classes are
respectively updated to use `Pool` for managing their buffer pool,
external unicast/multicast address pool, and address cache pool. This
commit also adds a unit test for the `Pool` class.

[pool] introducing a generic object pool class

---

src/core/meshcop/dtls.cpp
src/core/meshcop/dtls.hpp

This PR uses the mbedtls API to explicitly configure DTLS to use only the `secp256r1` curve and no signature hash algorithms when using ECJPAKE cipher suite.
This fixes https://github.com/openthread/openthread/issues/5142

[dtls] explicitly configure ECJPAKE parameters

---

.github/workflows/simulation.yml

This makes the external commissioner test to copy coverage files from `otbr` to `$PWD/build` so they are uploaded correctly.
Depends on https://github.com/openthread/ot-commissioner/pull/125 which enables coverage for `otbr`.

[test] fix external commissioner coverage data uploading

---

src/core/api/icmp6_api.cpp
src/core/api/udp_api.cpp
src/core/coap/coap.hpp
src/core/meshcop/border_agent.hpp
src/core/meshcop/dtls.hpp
src/core/meshcop/joiner_router.hpp
src/core/net/dhcp6_client.hpp
src/core/net/dhcp6_server.hpp
src/core/net/dns_client.hpp
src/core/net/icmp6.cpp
src/core/net/icmp6.hpp
src/core/net/ip6.cpp
src/core/net/ip6.hpp
src/core/net/ip6_filter.cpp
src/core/net/sntp_client.hpp
src/core/net/tcp.hpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp
src/core/thread/address_resolver.cpp
src/core/thread/address_resolver.hpp
src/core/thread/lowpan.cpp
src/core/thread/lowpan.hpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle.hpp
tests/unit/test_lowpan.hpp

This commit contains two main changes in `Ip6` modules: `Udp`, `Tcp`,
and `Icmp`. First, it simplifies the `Header` types defining constant
`enum` for byte offset of different fields in the header (these
replace the static methods and avoid use of `offsetof` macro). Second
change is it declare related types in each module as nested types of
the the main class (place them under the namespace of the main type).
For example `Icmp::Header`, `Udp::Socket` respectively replace
`IcmpHeader`, `UdpSocket` types.

[udp/tcp/icmp] simplify Header parsing, and declare related types as nested

---

CMakeLists.txt

To support automated armv7 docker builds.

[cmake] move minimum version to 3.10.2

---

examples/platforms/efr32mg1/README.md
examples/platforms/efr32mg1/radio.c
examples/platforms/efr32mg12/README.md
examples/platforms/efr32mg12/radio.c
examples/platforms/efr32mg12/sleepy-demo/README.md
examples/platforms/efr32mg13/README.md
examples/platforms/efr32mg13/radio.c
examples/platforms/efr32mg13/sleepy-demo/README.md
examples/platforms/efr32mg21/README.md
examples/platforms/efr32mg21/radio.c
examples/platforms/efr32mg21/sleepy-demo/README.md

When analyzing the energy mode transitions for a sleepy node, running the `sleepy-demo-mtd`  app, it was observed that, the current implementation of the platform radio driver (`efr32RadioProcess()`) although correct, can be optimized by processing the next received packet (`processNextRxPacket()`) before other actions being carried out in this routine. For example, in a situation where a 802.15.4 MAC Ack needs to be processed in response to a sent packet,  adding this call towards the end of this routine then delays stack notification (that a Tx was done) until the next call to `efr32RadioProcess()`.

[efr32] process received packet immediately

---

src/core/common/string.hpp
src/core/mac/mac_types.cpp
src/core/net/ip6_address.cpp

This method appends a given array of bytes in hex representation
(`%02x` style) to a `String` object. This method helps simplify the
`ToString()` methods in simpler types (e.g. `Mac::ExtAddress`).

[string] add String::AppendHexBytes()

---

src/core/utils/otns.cpp

The extended address already has byte order reversed when calling `aFrame.GetDstAddr(dst)`. The reversal logic is therefore not needed. This PR fixes that.

[otns] fix extaddr byte order

---

examples/platforms/efr32mg21/radio.c

`processNextRxPacket()` on the EFR32MG21 platform takes a RAIL handle as a second argument.

[efr32] fix broken radio.c in EFR32MG21

---

src/core/coap/coap_secure.cpp
src/core/coap/coap_secure.hpp
src/core/meshcop/border_agent.cpp
src/core/meshcop/dtls.cpp
src/core/meshcop/dtls.hpp
src/core/net/socket.hpp

This commit contains few small enhancements in `Dtls`:
- It renames the `GetPeerAddress()` to `GetMessageInof()` (to indicate
that it returns `Ip6::MessageInfo` and not just peer socket address).
(it also renames the variable to `mMessageInfo` from `mPeerAddress`).
- Declares `Ip6::MessageInfo` to be `Clearable` and uses the `Clear()
method instead of `new` operator to clear the `mMessageInfo`.
- Uses helper methods to set the peer socket address (remove `memcpy`).

[dtls] small enhancements

---

src/cli/cli.cpp
tests/scripts/thread-cert/v1_2_test_backbone_router_service.py
tests/scripts/thread-cert/v1_2_test_multicast_registration.py

In some test scripts,` %s` and `format()` are mix-used by mistake.

[test] fix python formatting in v1_2_* tests

---

tests/scripts/thread-cert/mesh_cop.py
tests/scripts/thread-cert/mle.py
tests/scripts/thread-cert/tlvs_parsing.py

This PR ignores unknown TLVs when parsing a message and continues to parse the rest parts of the message.
An unknown TLV can cause the simulator to drop the whole packet, which could lead to packet parsing issues. 
For example, if a `Child ID Response` message is dropped, the dissector will fail to add the Short Address and Extended Address to the Device Descriptors, causing subsequent secure packets unable to be decrypted. 
**PR #5219 requires this PR to pass tests stably.**

[tests] ignore unknown TLV

---

.github/workflows/build.yml
.github/workflows/posix.yml
.github/workflows/simulation-1.2.yml
.github/workflows/simulation.yml
.github/workflows/toranj.yml
script/bootstrap

These sources break easily, removing them so that `apt-get update` doesn't fail.

[github-action] remove unused apt source lists

---

src/core/mac/data_poll_handler.cpp
src/core/thread/address_resolver.cpp
src/core/thread/child_table.cpp
src/core/thread/child_table.hpp
src/core/thread/indirect_sender.cpp
src/core/thread/key_manager.cpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle_router.cpp
src/core/thread/network_diagnostic.cpp
src/core/thread/src_match_controller.cpp
src/core/utils/child_supervision.cpp
tests/unit/test_child_table.cpp

This commit updates `ChildTable` class. It mainly adds support for
using range-based `for` loops to iterate over all child entries
(matching a given state filter). It also simplifies the `Iterator`
implementation (removing the now unused behavior to start the
iteration from a specific child in the table). The unit test
`test_child_table` is also updated to add tests for the newly added
behavior.

[child-table] enable use of range-based "for" loop

---

src/ncp/ncp_base.cpp

Many existing IEEE 802.15.4 radios do not support both promiscuous
mode and auto generation of immediate ACKs. This commit prevents
promiscuous mode when the interface is up.
Resolves #4161

[ncp] only allow promiscuous mode in link raw mode

---

include/openthread/dataset.h
include/openthread/instance.h
src/core/meshcop/dataset_manager_ftd.cpp
src/core/net/ip6_address.cpp
src/core/net/ip6_address.hpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_types.hpp

This commit adds `Ip6::NetworkPrefix` mirroring `otIp6NetworkPrefix`
which represents the Network Prefix (most significant 64 bits) of an
IPv6 address. Methods in `Ip6::Address` are updated to use the new
type. The `otMeshLocalPrefix` and `Mle::MeshLocalPrefix` are also
updated to use the `NetworkPrefix` type.

[ip6] define NetworkPrefix type

---

src/core/thread/key_manager.cpp
src/core/thread/mle_router.cpp
src/core/thread/router_table.cpp
src/core/thread/router_table.hpp

This commit updates `RouterTable` class to add support for using
range-based `for` loops to iterate over all routers.

[router-table] enable use of range-based "for" loop

---

src/core/thread/address_resolver.cpp
tests/toranj/test-039-address-cache-table-snoop.py

Thread Specification 5.4.2.4
> The Time Since Last Transaction TLV contains the number of seconds since a keep-alive message (as defined in Section 4.6.3 Timing Out Children in Chapter 4, Mesh Link Establishment) was last received from the Child.

[address-resolver] TimeSinceLastTransaction should be in seconds

---

src/core/thread/mle.cpp
src/core/thread/mle.hpp

-- edited --
This PR introduces the `mHasRestored ` flag and a common `HasRestored()` method as devices may decide to introduce some jitter/randomization to avoid the burst of traffic in cases a bunch of devices nearby resets/reboots together. One typical usage defined in Thread 1.2 Specification 5.23.4.1 is that
> In the following cases, a random time delay chosen in the interval [0, Reregistration Delay], a random time delay chosen in the interval [0, Reregistration Delay] MUST be applied before sending the DUA.req
> - The Device reregisters its DUA due to a Device reboot/restart.

[mle] add `mHasRestored` flag

---

src/core/thread/mle.cpp
src/core/utils/otns.cpp
src/core/utils/otns.hpp

This PR allows [OTNS](https://github.com/openthread/ot-ns) to correctly visualize node mode when it changes.

[otns] emit device mode

---

.github/workflows/simulation.yml

- Install avahi-daemon and avahi-utils packages.
- Remove ot-br-posix dependencies.
Resolves #5278

[github-actions] fix external-commissioner test

---

src/ncp/CMakeLists.txt

Added include directories to enable including .hpp ncp files
outside src directory, what is needed for vendor hooks concept.
Signed-off-by: Kamil Kasperczyk <kamil.kasperczyk@nordicsemi.no>

[cmake] added ncp vendor hook include directories for .hpp files from src

---

src/core/Makefile.am
src/core/common/bit_vector.hpp
src/core/thread/child_mask.hpp

This adds the `BitVector` template class and changes `ChildMask` to inherit from `BitVector`.
This can help reduce redundant code for bit mask manipulations.

[core] add BitVector template class

---

.github/workflows/docker.yml

The openthread/environment and openthread/codelab_sim images are
currently built and updated via the Docker Hub service. Docker Hub
only allows a single runner at a time and is generally slower than
GitHub Actions.
This commit moves the Docker image build and update to GitHub Actions.

[github-actions] add building Docker images

---

src/core/api/thread_ftd_api.cpp
src/core/net/ip6_address.cpp
src/core/net/ip6_address.hpp
src/core/thread/mle_router.cpp
src/core/thread/mle_router.hpp
src/core/thread/topology.cpp
src/core/thread/topology.hpp
tests/unit/test_child.cpp

This commit enhances the iterator `Child::AddressIterator` which is
used to iterate over IPv6 address list of a `Child`. The new model
enables range-based `for` loops to be used. It also enables filtering
addresses based on type (e.g., iterate over multicast addresses only).
The unit test `test_child.cpp` is also updated to verify the newly
added functionalities of `AddressIterator`.

[child] enhance Child::AddressIterator

---

src/core/thread/mesh_forwarder.cpp
tests/unit/test_toolchain.cpp

This commit simplifies the `GetFramePriority()` implementation
mainly avoiding copying of ICMP/UDP header when possible.
It also updates unit test `test-toolchain` to verify alignment
behavior of packed structure.

[mesh-forwarder] simplify GetFramePriority()

---

src/core/net/netif.hpp
src/core/thread/mle.cpp

This commit updates `Mle` class to use the newly added `Netif`
iterator for external multicast addresses. It also adds a helper
method in `Netif` to indicate if it is subscribed to any external
multicast address.

[mle] use newly added Netif::IterateExternalMulticastAddresses

---

src/core/net/netif.hpp
src/core/thread/mlr_manager.cpp

This PR enhances `IterateExternalMulticastAddresses` to use further filter external multicast addresses.
**Should be rebased after #5269 is merged**

[netif] enhance IterateExternalMulticastAddresses 

---

src/core/backbone_router/bbr_leader.cpp
src/core/common/bit_vector.hpp
src/core/common/instance.hpp
src/core/config/tmf.h
src/core/thread/mle_router.cpp
src/core/thread/mle_types.hpp
src/core/thread/mlr_manager.cpp
src/core/thread/mlr_manager.hpp
src/core/thread/mlr_types.hpp
src/core/thread/thread_netif.cpp
src/core/thread/thread_netif.hpp
src/core/thread/thread_tlvs.hpp
src/core/thread/topology.cpp
src/core/thread/topology.hpp
tests/scripts/thread-cert/v1_2_test_multicast_listener_registration.py

This PR implements parents sending `MLR.req` on behave of Children.
- Parent sends MLR.req for Children after delaying for a random time < PARENT_AGGREGATE_DELAY (5s).
- Update test script to check for proxied `MLR.req`
- Parent proxy MLR.req for Children after a delay t in [0, 5]
**MLR PR List:**
- #5236 Parent send MLR.req on behave of Children **<== This PR**
- #5292 Add MulticastListenersTable on BBR 
- ~~#5248 Send MLR.req for locally Netfi MAs **MERGED**~~
- ~~#5250 Add the `MLR` log region  **MERGED**~~

[mlr] Parent send MLR.req on behalf of Children

---

src/core/common/instance.hpp
src/core/net/dhcp6.hpp
src/core/net/dhcp6_client.cpp
src/core/net/dhcp6_client.hpp
src/core/net/dhcp6_server.cpp
src/core/net/dhcp6_server.hpp
src/core/thread/mle.cpp
src/core/thread/thread_netif.hpp

This commit contains a bunch of smaller changes and enhancements
in dhcp6 modules:
- Add and use `TransactionId` class.
- Rename header to `Dhcp6::Header` and update `Dhcp6::Type`.
- Rename server/client to `Dhcp6::Server` and `Dhcp6::Client`.
- Rename/update `DuidType` constants.
- Use `Mac::ExtAddress` as link address in `Server/ClinetIndentifer`.
- Use `Ip6::Address` instead of `otIp6Address`.
- Add `enum` constants for default values (remove `#define`)
- Define `IdentityAssociation` as nested type of `Client`.
- Update documentation.
- ~~Use `BitVector` for `mPrefixAgentsMask`.~~ _(removed due to impact on code size)._

[dhcp6] misc enhancements

---

tests/unit/CMakeLists.txt

I think `openthread-ncp-ftd` is added to unit tests' link libraries by mistake. It's not required and as it depends on `OT_PLATFORM`, it would cause `openthread-simulation` linked in unit test executables, which would lead to a redefinition as some methods are defined in `test-platform.cpp`.

[cmake] fix link issues of unit tests

---

tests/scripts/expect/cli-scan-discover.exp
tests/scripts/expect/posix-scan-tx-to-sleep.exp

This fixes some `expect` test failures caused by the scenario below:
Sometimes the command prompt `> ` can be put after the echo of the input command when inputs come too fast, because we are sending the next command as soon as we see `Done`, we don't wait for the next `> `. An example case:
```
2020-07-23T07:58:23.4151267Z > panid
2020-07-23T07:58:23.4153883Z 0x56af
2020-07-23T07:58:23.4154163Z 
2020-07-23T07:58:23.4156623Z Done
2020-07-23T07:58:23.4156952Z extpanid
2020-07-23T07:58:23.4157776Z 
2020-07-23T07:58:23.4160948Z > 3bdf955e7ddd80f3
2020-07-23T07:58:23.4161216Z 
2020-07-23T07:58:23.4164133Z Done
2020-07-23T07:58:23.4164481Z networkname
2020-07-23T07:58:23.4165323Z 
2020-07-23T07:58:23.4174275Z > OpenThread-56af
2020-07-23T07:58:23.4174801Z 
2020-07-23T07:58:23.4175875Z Done
``` …

[test] fix network name capturing in expect scripts

---

src/posix/client.cpp

This PR enhance `ot-ctl` to process only after a full line is read in non-interactive mode. 
This eliminates the complex and error-prone states handling, which still has potential issues (despite of small chance):
- If `Done\r\n` is received in two chunks: `Done\r` and `\n`, the original implementation won't output `\n`
- If `Error 7: InvalidArgs` is received in two chunks: `Error ` and `7: InvalidArgs`, the original implementation won't output `7: InvalidArgs`

[posix] ot-ctl process lines for non-interactive mode

---

.github/workflows/simulation.yml

This PR aligns the external commissioner buliding options with OT commissioner.
Fixes test failures revealed in https://github.com/openthread/openthread/pull/5317/checks?check_run_id=934695903.

[tests] fix external commissioner building options

---

src/core/thread/network_data.cpp
src/core/thread/network_data.hpp

This commit updates `OnMeshPrefixConfig` and `ExternalRouteConfig` to
be `Equatable`. It also adds a `ServerConfig` and adds overloads of
operator `==` to `Service/Server` configs. It also adds new method
`SetFrom()` to all configuration types to set them from a given set of
related TLVs.

[network-data] enhance OnMeshPrefix/ExternalRoute/Service configs

---

include/openthread/dataset.h
include/openthread/instance.h
include/openthread/thread.h
src/core/api/thread_api.cpp
src/core/meshcop/meshcop_tlvs.hpp
src/core/thread/discover_scanner.cpp
src/core/thread/discover_scanner.hpp

This PR implements Thread based Joiner Advertisement from Joiner side, including:
- A new MeshCop TLV: Joiner Advertisement TLV which includes IEEE OUI and the Advertisement Data 
- New APIs to set Joiner Advertisement which will be sent along with Discovery Request messages

[joiner-adv] initial implementation of Joiner Advertisement

---

src/core/coap/coap.cpp
src/core/meshcop/dtls.cpp
src/core/meshcop/joiner.cpp
src/core/meshcop/joiner_router.cpp
src/core/net/dhcp6_client.cpp
src/core/net/dhcp6_server.cpp
src/core/net/dns_client.cpp
src/core/net/sntp_client.cpp
src/core/net/socket.hpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp
src/core/thread/mle.cpp

This commit adds new flavors of methods `Bind()` and `Connect()` in
`Udp6::Socket` allowing user to only specify a port number or provide
no input (address and/or port are determined by the UDP module itself
when not provided). The new methods help simplify `Socket` use in
different modules. This commit also enhances `SockAddr` class adding
new constructors to allow a `SockAddr` instance to be initialized with
a given port number or a given IPv6 address and port number.

[udp6] adding new flavors of Bind() and Connect() in Socket

---

src/core/thread/mle_router.cpp

This commit simplifies `MleRouter:GetNeighbor(const Ip6::Address &)`
handling of mesh-local router locator IPv6 addresses.

[mle-router] simplify 'GetNeighbor(const Ip6::Address &)'

---

tests/scripts/thread-cert/pcap.py
tests/scripts/thread-cert/sniffer.py

This PR enhances `sniffer.py` so that we can use it as a standalone sniffer for non Virtual Time simulations. 
Usage:
```bash
$ python3 sniffer.py | wireshark -k -i -
```

[scripts] add live capture for sniffer.py on simulation traffic

---

src/core/api/thread_api.cpp
src/core/api/thread_ftd_api.cpp
src/core/thread/mle_router.cpp
src/core/thread/mle_router.hpp
src/core/thread/router_table.cpp
src/core/thread/router_table.hpp
src/core/thread/topology.cpp
src/core/thread/topology.hpp

This commit adds new class definitions in `topology` to represent
neighbor/child/router info.

[topology] define 'Neighbor::Info', 'Child::Info', and 'Router::Info'

---

src/core/common/encoding.hpp
src/core/meshcop/meshcop_tlvs.hpp
src/core/thread/discover_scanner.cpp
src/core/thread/discover_scanner.hpp

This commit adds `ReadUint24()`, `WriteUint24()` in `encoding.hpp`
for both little and big endian formats. These methods are then used
for reading/writing OUI in `MechCop::Tlv` sub-classes. It also
adds a check in `DiscoverScanner` to ensure the given OUI in
`SetJoinerAdvertisement` is within the valid range.

[encoding] add '{Read/Write}Uint24()'

---

src/core/api/thread_ftd_api.cpp
src/core/net/ip6.cpp
src/core/thread/child_table.cpp
src/core/thread/child_table.hpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp
src/core/thread/mle_router.hpp

This commit moves `GetChildInfoById()`, `GetChildInfoByIndex()`, and
`HasSleepyChildWithAddress()`, along with methods for saving/restoring
child entries in/from non-volatile settings (e.g., `Restore()`,
`RemoveStoredChild()`, etc.) from `Mle` module to `ChildTable`. It also
removes/inlines the `MleRouter::IsSleepyChildSubscribed()` method.

[child-table] move child related methods to 'ChildTable'

---

examples/common-switches.mk

This option allows to pass Spinel Encrypter library to predefined Makefiles for different platforms.
Example usage:
```
make -f examples/Makefile-nrf52840 SPINEL_ENCRYPTER_LIBS=my_encrypter_lib.a
```

[build] add SPINEL_ENCRYPTER_LIBS option to common switches

---

include/openthread/coap.h
include/openthread/instance.h

Also add a note to clarify the set of valid CoAP transmission
parameters.
Resolves #5336

[coap] reduce OT_COAP_MAX_RETRANSMIT to 20

---

etc/cmake/options.cmake
script/check-simulation-build-cmake
src/core/mac/mac_frame.cpp
src/core/utils/otns.cpp

This PR adds a build test without OT_ASSERT to catch compile issues.

[tests]  add build test for OT_ASSERT=OFF

---

src/core/mac/mac_frame.cpp

This commit changes `MacFrame::FindPayloadIndex()`:
- Ensure that at least one Header IE is included when FCF indicates
that Header IE is present.
- Detect error case where Header IE(s) are partially included.
- Handle the case where frame contains Header IE(s) but no data
payload (spec does not require Header IE termination in this
case).

[mac-frame] fix/enhance parsing of Header IEs

---

src/core/mac/mac_frame.cpp
src/core/mac/mac_frame.hpp

- Use array indexing style `mPsdu[index]`.
- Update `InitMacHeader()` to use `mLength` directly.
- Add `using ot::Encoding::LittleEndian`
- Simplify `HeaderIe` definition (use `union`).
- Simplify `VendorIe` (use `uint32_t` for OUI).
- Simplify processing of Header IE(s) (using index) in
`FindPyalodIndex()`, `GetHeaderIe()`, and `AppendHeaderIe()`.

[mac-frame] misc enhancements and simplifications

---

src/lib/Makefile.am
src/lib/url/CMakeLists.txt

This sets the URL library to be included only in POSIX builds, removing unnecessary dependencies.

[build] exclude URL library where unused

---

Android.mk
BUILD.gn
src/core/CMakeLists.txt
src/core/Makefile.am
src/core/api/thread_api.cpp
src/core/common/instance.hpp
src/core/mac/mac.cpp
src/core/thread/child_table.cpp
src/core/thread/child_table.hpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_router.cpp
src/core/thread/mle_router.hpp
src/core/thread/neighbor_table.cpp
src/core/thread/neighbor_table.hpp
src/core/thread/router_table.cpp
src/core/thread/router_table.hpp
src/core/thread/topology.cpp
src/core/thread/topology.hpp
src/core/utils/child_supervision.cpp
tests/unit/test_child_table.cpp

**[topology] adding 'Neighbor::AddressMatcher'**
This commit adds a new type `Neighbor::AddressMactehr` which is used
to filter and find a neighbor (child/router) with a given MAC address
matching a given `Neighbor::StateFilter`. This new type helps simplify
related code in `ChildTable`/`RouterTbale`.
**[neighbor-table] add 'NeighborTable' class**
This commit adds a `NeighborTable` class which provides helper methods
dealing with neighbor, e.g., finding a `Neighbor` (i.e., a `Child`
from `ChildTable`, a `Router` from `RouterTable`, or parent or parent
candidate entries), or iterating through all neighbors.  These methods
use the newly added `Neighbor::AddressMacther` to simplify the
implementation. The `NeighborTable` methods replace the similar ones …

[topology] adding 'Neighbor::AddressMatcher' and 'NeighborTable'

---

.github/workflows/posix.yml
.github/workflows/simulation.yml
tests/scripts/thread-cert/Cert_5_1_07_MaxChildCount.py
tests/scripts/thread-cert/Makefile.am
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/pktverify/__init__.py
tests/scripts/thread-cert/pktverify/addrs.py
tests/scripts/thread-cert/pktverify/bytes.py
tests/scripts/thread-cert/pktverify/coap.py
tests/scripts/thread-cert/pktverify/consts.py
tests/scripts/thread-cert/pktverify/decorators.py
tests/scripts/thread-cert/pktverify/errors.py
tests/scripts/thread-cert/pktverify/layer_fields.py
tests/scripts/thread-cert/pktverify/layer_fields_container.py
tests/scripts/thread-cert/pktverify/layers.py
tests/scripts/thread-cert/pktverify/null_field.py
tests/scripts/thread-cert/pktverify/packet.py
tests/scripts/thread-cert/pktverify/packet_filter.py
tests/scripts/thread-cert/pktverify/packet_verifier.py
tests/scripts/thread-cert/pktverify/pcap_reader.py
tests/scripts/thread-cert/pktverify/summary.py
tests/scripts/thread-cert/pktverify/test_info.py
tests/scripts/thread-cert/pktverify/test_layer_fields.py
tests/scripts/thread-cert/pktverify/utils.py
tests/scripts/thread-cert/pktverify/verify_result.py
tests/scripts/thread-cert/requirements.txt
tests/scripts/thread-cert/simulator.py
tests/scripts/thread-cert/thread_cert.py

This PR introduces the packet verification (PV) framework for certification tests. 
**This PR is required by #5291**

[scripts] add packet verification framework

---

src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder.hpp
src/core/thread/mesh_forwarder_ftd.cpp

This commit simplifies management of "Fragment Priority Entries"
defining a new class `FragmentPriorityList` with helper method to
allocate/find entries in/from the list. The `Entry` types is also
moved/defined as a nested type of `FragmentPriorityList`.

[mesh-forwarder] simplify 'FragmentPriorityList'

---

src/core/thread/mle_router.cpp

This commit adds a few logs when handling MLE Parent Request, so that when a child failed to receive a response, the logs can tell what happened.

[mle] log handling parent request failures

---

src/core/thread/mle_router.cpp
src/core/thread/mle_router.hpp
src/core/thread/mle_tlvs.hpp
tests/scripts/thread-cert/Makefile.am
tests/scripts/thread-cert/test_router_reattach.py

This commit addresses an issue where the MLE Link Accept message may
be too large to fit within a single IEEE 802.15.4 frame. Thread
requires any MLE message transported using 6LoWPAN fragmentation to
also enable IEEE 802.15.4 MAC frame security. However, the purpose of
MLE Link Accept messages is to establish a secure link and cannot
itself be transported with IEEE 802.15.4 MAC frame security enabled.
An MLE Link Accept message may carry a Route64 TLV that has a length
dependent on the number of active routers in the network. When there
are many active routers, the Route64 TLV is large and the MLE Link
Accept message can no longer fit within a single IEEE 802.15.4
frame. The side effect is that a router coming out of reset will not
be able to diretly restore its router role and must …

[mle] work around MLE Link Accept messages that are too large

---

.github/workflows/simulation-1.2.yml
script/test

I found that when running `code-cov` for `thread-1-2` in our github actions, the uploaded `.gcov` report file is not correct(Some code that will surely be executed is not hit in the report). 
The possible reason is that in `thread-1-2`, we have 3 different build directories. Thus we have 3 `.gcda` and `gcno` files for one source file. And `codecov-action@v1` isn't smart enough to include all these into one `.gcov` and then upload. Though I don't know the underlying process(how does `codecov-action@v1` generate `.gcov` when there are 3 data files for one source file), I've verified that, uploading report when there's only one build directory and repeating three times for different build directories take effect.
This PR adds a function in `script/test` to tar and untar the build directory. …

[github-action] change the way to upload coverage report for 1_2 tests

---

.github/workflows/simulation.yml

This PR makes packet verification to run for multiple times.
Since now we are developing many packet verification scripts, this PR can help us reduce the chance of merging a verification code that could fail by chance, which is very often for packet verification code.
**Successfully ran for 10 times in 13 minutes.**

[github-actions] run packet verification for multiple times

---

src/core/api/thread_ftd_api.cpp
src/core/thread/mle_router.cpp
src/core/thread/mle_router.hpp
src/core/thread/neighbor_table.cpp
src/core/thread/neighbor_table.hpp
src/core/thread/router_table.cpp
src/core/utils/otns.cpp
src/core/utils/otns.hpp

This commit moves the code related to `otNeighborTableCallback`
and signaling `NeighborTable::Event` to `NeighborTable` class
(from `MleRouter`).

[neighbor-table] move "neighbor changed callback" and signaling

---

src/core/backbone_router/bbr_local.cpp
src/core/meshcop/border_agent.cpp
src/core/net/dhcp6_server.hpp
src/core/net/netif.cpp
src/core/net/netif.hpp
src/core/thread/dua_manager.cpp
src/core/thread/mle.cpp
src/core/utils/slaac_address.cpp

This commit adds a group of `Init` methods in `NetifUnciastAddress`
for common initializations of a unicast address with different
parameters (origin, scope, prefix length, and preferred/valid flags).

[netif] add helper methods to init 'NetifUnicastAddress'

---

.github/workflows/simulation.yml

This PR fixes OTNS test fails reported by #5402 @jwhui 
The OTNS test of OpenThread CI is supposed to be a subset of OTNS CI tests. So, Openthread's OTNS test should never fail if the merged OTNS PRs has all passed OTNS CI.
Turnout in OTNS CI, a setup is used to further setup the Python3 env which seems to make the Python env more reliable. 
```yml
- name: Set up Python 3.6
uses: actions/setup-python@v1
with:
python-version: 3.6
```
Adding this step in the OpenThread's OTNS test job fixes the issue.

[github-actions] fix otns test failure

---

src/core/thread/mle.cpp

This PR fixes #5293 
Testing if two `OT_ASSERT(leader != nullptr);` statements can be kept since they seems correct:
- OT Build: 
- **FTD Leader Data dropping removed**
- **`OT_ASSERT(leader != nullptr);` statements kept**
- kMinDowngradeNeighbors = 4
- OPENTHREAD_CONFIG_MLE_LONG_ROUTES_ENABLE = 1
- OTNS Stress Tests

[mle] fix FTD unable to restore link to parent

---

src/core/common/message.cpp
src/core/common/message.hpp
src/core/net/socket.hpp
src/core/thread/discover_scanner.cpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder.hpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp

The `ThreadLinkInfo` mirrors the `otThreadLinkInfo` definition.
It is mostly used in `MeshForwarder` and `Mle` class. Here are
some related helper methods:
- New helper methods in `Ip6::MessageInfo` to get and set the
link info as `ThreadLinkInfo`.
- Helper method `ThreadLinkInfo::SetFrom()` allows it to be set
from a given `Mac::RxFrame`.
- Helper method `Message::SetLinkInfo()` allows message link info
related fields (in message metadata) to be set/updated from a
given `ThreadLinkInfo`.

[mesh-forwarder] add new class 'ThreadLinkInfo'

---

src/posix/platform/system.cpp

This PR generates `[OTNS]` logs:
```
./cmake-build-debug/src/posix/ot-daemon[13954]: [NONE][OTNS] extaddr=7ac54b174025345b
./cmake-build-debug/src/posix/ot-daemon[13954]: [NONE][OTNS] rloc16=65534
./cmake-build-debug/src/posix/ot-daemon[13954]: [NONE][OTNS] rloc16=30720
./cmake-build-debug/src/posix/ot-daemon[13954]: [NONE][OTNS] extaddr=46ce26bba9f0b764
./cmake-build-debug/src/posix/ot-daemon[13954]: [NONE][OTNS] transmit=11,d849,128,ffff
./cmake-build-debug/src/posix/ot-daemon[13954]: [NONE][OTNS] transmit=11,d849,129,ffff
./cmake-build-debug/src/posix/ot-daemon[13954]: [NONE][OTNS] rloc16=30720
./cmake-build-debug/src/posix/ot-daemon[13954]: [NONE][OTNS] role=1
./cmake-build-debug/src/posix/ot-daemon[13954]: [NONE][OTNS] transmit=11,d841,130,ffff …
```

[otns] implement `otPlatOtnsStatus` for posix

---

src/core/net/udp6.cpp

----
This fixes an issue with new `Connect(uint16_t port)` added in #5319.
The new overload of the `Connect()` method seems to be only used from `Dtls::Disconnect()`

[udp6] fix 'Udp::Socket::Connect(uint16_t aPort)'

---

examples/platforms/efr32mg1/flash.c
examples/platforms/efr32mg1/radio.c
examples/platforms/efr32mg1/system.c
examples/platforms/efr32mg12/flash.c
examples/platforms/efr32mg12/radio.c
examples/platforms/efr32mg12/system.c
examples/platforms/efr32mg13/flash.c
examples/platforms/efr32mg13/radio.c
examples/platforms/efr32mg13/system.c
examples/platforms/efr32mg21/flash.c
examples/platforms/efr32mg21/radio.c
examples/platforms/efr32mg21/system.c

Use the config specified on the command line, so that overriding this
with a project specific config doesn't cause preprocessor macro
redefinition errors.

[efr32] switch to proper config #include style

---

src/cli/cli.cpp
src/cli/cli.hpp
src/cli/cli_console.cpp
src/cli/cli_uart.cpp

It is possible that log is printed before the Interpreter (UART or CONSOLE) object is created when `FULL LOGS` is enabled. In such case, OT crashes. 
This PR fixes this bug. 
This bug was introduced by #5387

[cli] fix crash when full logs is on

---

src/posix/platform/uart.cpp

This PR fixes potential socket resource leakage when preparing new UART session socket failed.

[posix] fix potential socket resource leakage

---

src/core/net/ip6.cpp
src/core/net/ip6.hpp
src/core/net/ip6_headers.hpp
src/core/net/ip6_mpl.cpp
src/core/thread/lowpan.cpp
src/core/thread/mesh_forwarder_ftd.cpp
tests/unit/test_ip6_address.cpp

This commit contain a list of smaller enhancements in `Ip6` modules:
- Simplify `Ip6::Header` removing the PoD definition and providing
`enum` constants for the byte offset to different fields in the header
(replacing/removing static methods).
- Declare some of the `Ip6` methods as `private`.
- Remove error logs (not used/applicable anymore).
- Simplify checking of `destPort` in `ProcessReceiveCallback()`.
- Specify `int` size of `enum` definitions (declare internally-used
`enum`s a `private`).
- Add unit test `TestIp6Header()`.

[ip6] simplify `Ip6:Header` and misc. enhancements

---

src/core/common/extension.hpp
src/core/common/extension_example.cpp
src/core/common/notifier.cpp

This commit adds `ExtnesionBase` (base class of vendor `Extension`)
as one of the event receivers from `Notifier` class.

[extension] add method to receive and handle notifier events

---

Android.mk

This PR moves `OPENTHREAD_CONFIG_FILE` to `OPENTHREAD_PROJECT_CFLAGS` in `Android.mk` to allow projects to specify their own config files.

[build] allow custom config file in Android.mk

---

.github/workflows/simulation-1.2.yml
.github/workflows/simulation.yml
script/test

This PR changes the coverage data uploading for `expects` job so that it only uploads data for one build at a time, to make coverage more stable. Applies the same strategy of https://github.com/openthread/openthread/pull/5375 to this job.

[github-action] fix coverage uploading for expects

---

CMakeLists.txt

OT_CONFIG was used to specify a customized OpenThread core config file
which is only included by OpenThread core library. This commit changes
the behavior so that it specifies the OPENTHREAD_CONFIG_FILE which is
used by all components of OpenThread including the core library.

[cmake] use OT_CONFIG for OPENTHREAD_CONFIG_FILE

---

Android.mk
src/core/BUILD.gn
src/core/CMakeLists.txt
src/core/Makefile.am
src/core/common/instance.cpp
src/core/common/instance.hpp
src/core/common/time_ticker.cpp
src/core/common/time_ticker.hpp
src/core/net/ip6.cpp
src/core/net/ip6.hpp
src/core/thread/address_resolver.cpp
src/core/thread/address_resolver.hpp
src/core/thread/dua_manager.cpp
src/core/thread/dua_manager.hpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder.hpp
src/core/thread/mesh_forwarder_ftd.cpp
src/core/thread/mle_router.cpp
src/core/thread/mle_router.hpp
src/core/thread/mlr_manager.cpp
src/core/thread/mlr_manager.hpp
src/core/thread/router_table.cpp
src/core/thread/router_table.hpp
src/core/utils/child_supervision.cpp
src/core/utils/child_supervision.hpp

This commit adds `TimeTicker` class which emits periodic ticks (with
one second period interval) to a set of registered tick receiver
modules. The `TimeTicker` would invoke `HandleTimeTick()` method
periodically on the registered receiver objects.
The `TimeTicker` model helps simplify the implementation of many
modules (such as `MeshForwarder`, `MleRoutuer`, `AddressResolver`,
`Ip6`, `DuaManager`, etc) which require periodic update/check of some
state (avoid each class using its own timer).

[time-ticker] adding 'TimeTicker' class

---

src/core/common/message.cpp
src/core/common/message.hpp
tests/unit/test_message.cpp

The `Message` data is stored in a sequence of linked-listed `Buffer`
instances. When reading or writing data in the `Message`, the internal
implementation iterates over the `Buffer` list and updates the data in
chunks. This commit adds two helper methods `GetFirstChunk()` and
`GetNextChunk()` to get first/next data chunk (contiguous buffer)
corresponding to a given offset and length into the message. These
helper methods are then used to simplify `Read()`, `Write()`, and
`UpdateChecksum()` methods. The unit test `test_message` is also
updated to verify reading and writing data at different offsets and
lengths.

[message] add helper methods to get first/next data chunks

---

src/core/thread/mle_router.cpp

A SSED uses the Child Update Request to start CSL synchronization. If the CSL Channel TLV is not present in the message, the parent assigns the Thread Network channel as the CSL channel for this child during the attachment.
However, it may happen that a child changes its CSL channel to a different one with a Child Update Request and decides to keep using it. In a subsequent Child Update Request it could omit the CSL Channel TLV (no changes) but the parent would change its CSL channel to the Thread Network channel. This PR avoids that.

[low-power] keep configured CSL channel for child

---

tests/scripts/thread-cert/v1_2_test_multicast_listener_registration.py

This PR adds one test to verify that if a node subscribed MAs when there is no PBBR in the network, it should still be able to send MLR.req after PBBR is enabled. 
This is a case that wasn't tested in existing tests.

[tests] check send MLR.req for MAs when PBBR is enabled

---

src/core/api/message_api.cpp
src/core/coap/coap.cpp
src/core/coap/coap.hpp
src/core/common/message.cpp
src/core/common/message.hpp
src/core/net/ip6.cpp
src/core/net/ip6_mpl.cpp
src/core/net/ip6_mpl.hpp
src/core/net/sntp_client.hpp
tests/unit/test_message.cpp

This commit changes `Message::Write()` to return `void` instead of
returning the number of bytes written. The `Write()` method does not
resize the message and requires that the given data can be fully
written into the message within its existing length. The `Write()`
already contains an `OT_ASSERT()` to verify this.
This commit also removes the redundant `OT_ASSERT()` checks in few
places where `Write()` method's returned value was being used.

[message] change 'Write()' to be a 'void' method

---

src/core/common/message.cpp
src/core/common/message.hpp
tests/unit/test_message.cpp

This commit updates `Message::CopyTo()` method to use data chunks
(this copies data directly from the source message to the destination
avoiding the need for an extra buffer copy). It also addresses an
issue where if the requested copy length is more than the available
bytes in the source message, incorrect bytes may be copied into the
destination message, and the returned value (i.e. number of bytes
copied) can be invalid.
This commit also updates the unit test `test_message` covering
behavior of `CopyTo()` for different offsets and copy lengths. It also
checks the behavior of `Read()` when the read length goes beyond the
end of the message (trying to read more bytes than available in the
message).
-------------
Checked all places where `CopyTo()` is currently used and the "read length" …

[message] update and fix 'CopyTo()'

---

examples/platforms/k32w/jn5189/Makefile.am
examples/platforms/k32w/k32w061/Makefile.am
examples/platforms/k32w/src/alarm.c
examples/platforms/k32w/src/radio.c
examples/platforms/k32w/src/system.c
examples/platforms/k32w/src/uart.c
third_party/nxp/JN5189DK6/middleware/wireless/framework/Common/EmbeddedTypes.h
third_party/nxp/JN5189DK6/middleware/wireless/framework/SerialManager/Source/UART_Serial_Adapter.h
third_party/nxp/JN5189DK6/middleware/wireless/framework/TimersManager/Source/TMR_Adapter.h
third_party/nxp/K32W061DK6/devices/K32W061/mcuxpresso/startup_k32w061.c
third_party/nxp/K32W061DK6/middleware/wireless/framework/Common/EmbeddedTypes.h
third_party/nxp/K32W061DK6/middleware/wireless/framework/SerialManager/Source/UART_Serial_Adapter.h
third_party/nxp/K32W061DK6/middleware/wireless/framework/TimersManager/Source/TMR_Adapter.h

This PR adds fixes which are needed for running Project CHIP on K32W.
Fixes are related to UART handling, radio interrupts and Free RTOS support.

[k32w] rtos uart fixes

---

src/core/thread/neighbor_table.cpp
src/core/thread/neighbor_table.hpp

---
The filtering is not currently used in any of existing code, however it adds flexibility without adding much of (code size or run-time) overhead. 
It is a functionality that is needed/used by the multi-link (TREL) PR (which earlier added it only when feature is enabled, but I think it make sense to add the filtering in general case).

[neighbor-table] add 'StateFilter' parameter in 'Find' methods

---

src/core/common/message.cpp
src/core/common/message.hpp
tests/unit/test_message.cpp

This change allows `CopyTo()` method to be used to copy bytes backwards
within the same message (i.e., src and dest messages are the same and
the dest offset is before src offset). Unit test `test_message` is
updated in this commit to cover such a use.
However, the `CopyTo()` implementing  can still potentially overwrite
the data when bytes are being copied forward within the same message,
i.e., source and destination messages are the same, and source offset
is smaller than the destination offset. This commit adds an assert not
allowing such a use and updates the method documentation mentioning
this restriction.
----------
This change should address https://github.com/openthread/openthread/issues/5460 and unblock the fuzzer error on PRs.
Checking the `Message::CopyTo()` uses in the code, …

[message] update 'Write()' to use 'memmove()' instead of 'memcpy()'

---

src/core/net/ip6.cpp

This commit also uses `VerifyOrExit` to check hop limit and removes
the `else` block indentation.

[ip6] avoid recursive call in 'HandleDatagram()'

---

src/core/diags/factory_diags.cpp

The `stop` command doesn't write anything to the output buffer.

[diag] clear output in case no output given

---

.github/workflows/simulation-1.2.yml
script/test

Currently `script/test` can only build 1.2 together with 1.1. This PR add supports to build 1.2 alone. And when `THREAD_VERSION=1.2` and `INTER_OP=1` are both set, both versions would be built. Sometimes we only want to build 1.2. This would save some time for us.

[build] add option to build 1.2 alone

---

include/openthread/backbone_router_ftd.h
src/cli/README.md
src/cli/cli.cpp
src/core/api/backbone_router_ftd_api.cpp
src/core/backbone_router/bbr_manager.cpp
src/core/backbone_router/bbr_manager.hpp
src/core/thread/thread_tlvs.hpp
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/v1_2_test_multicast_listener_registration.py

This PR allows BBR to configure response status for MLR.req (based on #5292):
**Please only review the last commit.**
**Only for reference Backbone Router device.**
**MLR PR List:**
- https://github.com/openthread/ot-br-posix/pull/532 add multicast forwarding for MLR Listeners
- https://github.com/openthread/openthread/pull/5346 Add Commissioner API to register Multicast Listeners 
- https://github.com/openthread/openthread/pull/5350 Configure MLR.req response status **<== This PR**
- https://github.com/openthread/openthread/pull/5388 send BMLR.ntf on Backbone link
- ~~https://github.com/openthread/openthread/pull/5292 Add MulticastListenersTable on BBR  **MERGED**~~
- ~~#5248 Send MLR.req for locally Netfi MAs **MERGED**~~
- ~~#5250 Add the `MLR` log region  **MERGED**~~
- …

[mlr] configure MLR.req response status

---

tests/scripts/thread-cert/Cert_5_5_02_LeaderReboot.py
tests/scripts/thread-cert/pktverify/coap.py
tests/scripts/thread-cert/pktverify/layer_fields.py
tests/scripts/thread-cert/pktverify/test_layer_fields.py

This PR includes several enhancements to `pktverify`
- Add more fields of `thread_meshcop` and `thread_address` layers
- Remove COAP TLV manual parsing for now since it's not correctly implemented
- Fix 5.5.2 which had already been using `p.coap.tlv.status`, `p.coap.tlv.rloc16`, ...

[pktverify] misc enhancement

---

src/core/common/message.hpp
src/core/net/ip6.cpp
src/core/net/ip6.hpp

This commit adds a new parameter to `Ip6::ProcessReceiveCallback()`
allowing caller to indicate whether the method can take custody of the
passed-in message or whether it needs to make a copy of it (to use in
receive callback). This is indicated by a new `enum` definition
`Message::Ownership`. In case of `kTakeCustody` value, the caller
transfers custody of message to the called method (i.e. the method can
`Enqueue()` the message and would need to `Free()` the message when no
longer needed).
The `Ip6::HandleDatagram()` uses this to avoid copying the message in
cases where it is not needed (e.g. for a message that is passed to
host through callback but does not need to be processed by Thread
core).

[ip6] skip copying message from 'ProcessReceiveCallback()'

---

src/core/thread/discover_scanner.cpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_router.cpp

This commit simplifies the logging in `Mle` modules. It renames and
simplifies the existing MLE logging methods. They are now defined as
`static` methods and the main implementation uses `#if` guards
checking the proper log level (when logs are not enabled they are
defined as empty inline methods).
This commit also adds new helper methods to log failure of sending or
processing of an MLE message, namely `Mle::LogSendError()` and
`Mle::LogProcessError()`. These are then used to simplify logging in
many methods in `Mle` and other related modules.

[mle] simplify logging and add helper log methods

---

src/core/thread/csl_tx_scheduler.cpp

This PR changes `TimeMicro::kMaxDuration` to `Time::kMaxDuration` because in posix `OPENTHREAD_CONFIG_PLATFORM_USEC_TIMER_ENABLE` is not set and `TimeMicro` is not defined.
And in the context, the intent is just to set the variable to a maximum value.

[low-power] fix csl posix build problem

---

src/core/mac/sub_mac.cpp
src/core/mac/sub_mac.hpp

This commit relaxes the assert checks when parsing raw-link frame from
the radio tx-done callback to update the security frame counter. In an
FTD/MTD build, if/when raw-link is enabled, the `TxFrame` is prepared
and given by user and may not necessarily follow 15.4 frame format
(raw-link can be used with vendor-specific format), so we allow
failure when parsing the frame. In other cases (in an RCP build or in
an FTD/MTD build without raw-link) since the `TxFrame` should be
prepared by OpenThread core, we expect no error and therefore assert
if parsing fails.
-------
This PR should help address an issue discovered by oss-fuzz testing.

[sub-mac] do not assert when parsing raw-link frames

---

Android.mk
src/core/BUILD.gn
src/core/CMakeLists.txt
src/core/Makefile.am
src/core/common/message.cpp
src/core/common/message.hpp
src/core/net/checksum.cpp
src/core/net/checksum.hpp
src/core/net/icmp6.cpp
src/core/net/icmp6.hpp
src/core/net/ip6.cpp
src/core/net/ip6.hpp
src/core/net/ip6_address.hpp
src/core/net/ip6_headers.hpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp
tests/unit/CMakeLists.txt
tests/unit/Makefile.am
tests/unit/test_checksum.cpp

This commit adds `Checksum` class which implements IP checksum
calculation and verification (all related code from other modules is
now moved to `Checksum` class). The new checksum calculation allows
any message chunk size (removes a limitation with previous model
of requiring even sized chunks). This commit also adds a unit test
`test_checksum` covering the behavior of `Checksum` methods.
----
This should help address Issue https://github.com/openthread/openthread/issues/5414.

[net] add 'Checksum' class

---

.github/workflows/posix.yml

This Applies the same strategy of #5375 to the `POSIX` workflow. Uploads data for one build at a time.

[github-actions] fix POSIX workflow coverage uploading

---

src/core/api/channel_manager_api.cpp
src/core/api/channel_monitor_api.cpp
src/core/api/child_supervision_api.cpp
src/core/api/entropy_api.cpp
src/core/api/network_time_api.cpp
src/core/api/random_crypto_api.cpp
src/core/api/random_noncrypto_api.cpp
src/posix/console_cli.cpp

This PR fixes some public include directives that uses `#include "xxx.h"`. It should be `#include <xxx.h>` for public headers.

[style] fix include directives

---

src/core/backbone_router/bbr_manager.cpp

This replaces the usage of `std::numeric_limits` with C macro `UINT32_MAX`. Removes the dependency of C++ header `limits`, which isn't available on some platforms.

[style] remove usage of std::numeric_limits

---

src/core/thread/discover_scanner.cpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_router.cpp

This commit declares MLE `Header` as a `private` nested type of `Mle`
class. It also  moves the `Command` enumeration definition into the
`Mle` class (from `Header`).

[mle] declare 'Header' as a private nested type of 'Mle'

---

src/core/thread/csl_tx_scheduler.cpp

Consider such a case:
1. The CSL transmitter has a buffered message for a CSL receiver and has scheduled that tx.
2. Before the CSL transmitter actually sends it, the receiver sends a data request.
3. The CSL transmitter immediately sends the buffered message to the receiver.
4. The scheduled time comes.
In current CSL implementation, though the buffered message has been sent through indirect tx, when the origin CSL tx time comes, it would send another 'empty frame' due to the missing of check and the implementation of `IndirectSender::PrepareFrameForChild`. This PR adds the check for this case and avoid to send the meaningless emtpy frame.

[low-power] remove extra csl tx after buffered message sent by indirect tx

---

script/test
src/core/mac/mac_frame.cpp
tests/unit/test_mac_frame.cpp

In current `Mac::Frame` implementation, when the frame is a Mac command, the `CommandId` is always not included as its **private payload**, which means we won't encrypt the `CommandId`.
According to _ieee802.15.4-2015_, 9.2.1:
> f) Secure the frame. For the frames specified in Table 9-1, the Private Payload field and Open Payload field shall be set as indicated in the table. For frames not specified in Table 9-1, the Private Payload shall be set to the MAC Payload field and Open Payload field shall be empty. The procedure shall then use the Private Payload field, the Open Payload field, the macExtendedAddress, the Frame Counter field (if TSCH is not being used), the ASN (if TSCH is being used), the SecurityLevel parameter, and the secKey element of the KeyDescriptor to produce the secured …

[mac-frame] handle exception case for payload index of mac cmd

---

src/core/thread/discover_scanner.cpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_router.cpp

This commit updates the logging in `Mle` modules by adding two
enumerations `MessageAction` and `MessageType` to indicate the action
(send, receive, delay, etc.) and the message type in the updated
`Log()` methods.

[mle] further simplifications of logging in MLE

---

script/check-size

This PR adds size-report for Thread 1.2 features in the simplest way that **does not require any change to [openthread-size-report](https://glitch.com/edit/#!/openthread-size-report) on Glitch**. 
Size reports for both Thread 1.1 and 1.2 are posted in the same comment with 1.2 report below 1.1 report.
This PR does not fully address style related comments in #5274, which we can leave to future enhancements.
**QUESTION: should we put 1.2 report above 1.1 report instead?**

[size-report] add size-report for Thread 1.2

---

tools/harness-thci/OpenThread_WpanCtl.py

This PR avoids globbing in `scanJoiner` since `xEUI` can be `"*"`

[thci] avoid globbing in scanJoiner 

---

tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/test_router_reattach.py

Fix `test_router_attach.py` failing by a small chance. 
**Root cause: `routerdowngradethreshold` restored back to default (23) after node reset, so the test had 5/120 chance to downgrade. We should set it back to 32 before starting it.**
This PR also enhance the test for a little bit:
- Make sure the node reattached as Router within 1 second
- Make sure the node does not downgrade after Router Selection Jitter (3s)
Fixes #5447

[scripts] fix test_router_reattach

---

src/core/api/joiner_api.cpp
src/core/meshcop/joiner.cpp
src/core/meshcop/joiner.hpp

Also changes discover scan callback to use `ScanResult` as its input
parameter type.

[joiner] add 'Joiner::State' enumeration (c++ style constants)

---

src/core/api/coap_api.cpp
src/core/coap/coap.cpp
src/core/coap/coap_message.cpp
src/core/coap/coap_message.hpp

This commit simplifies the generation/processing of CoAP Options in a
CoAP message. It adds helper methods `ReadExtendedOptionField()`,
`WriteExtendedOptionField` to decode/encode extended Option Header
fields (Option Number Delta or Option Length). It simplifies
`Option::Iterator` (using `Init()`/`Advance()` to parse and iterate
through all CoAP Options in a message). Note that the public OT
`otCoap` APIs and their behavior remain as before and unchanged.

[coap] update/simplify CoAP Options generation/processing

---

.github/workflows/simulation.yml

This PR introduces enhancements to the `cli-ftd-otns` test job:
- Use `Virtual Time UART`
- Upload test results as artifacts when failed
- Use Go 1.14

[github-actions] misc enhancements to otns test

---

src/cli/cli.cpp
src/cli/cli.hpp
src/cli/cli_coap.cpp
src/cli/cli_coap_secure.cpp
src/cli/cli_commissioner.cpp
src/cli/cli_dataset.cpp
src/cli/cli_joiner.cpp
src/cli/cli_udp.cpp
tests/toranj/build.sh

This commit contains a group of smaller enhancements in `Cli` modules:
- Add and use `OutputLine()` helper method which outputs a formatted 
string  line (appends newline `\r\n`).
- Use binary search when finding the command in `sCommands` array (also
adds`static_assert` check to ensure `sCommands` array is sorted).
- Define `Command` struct as a `private` nested type.
- Use `enum` constants (replacing `#define`).
- Rename method to `OutputResult()` (from `AppendReult`) to harmonize
with rest of a `Output{Something}()` methods.
- Remove comments at `#endif` when within 20 lines of `#if`
--------
I kept the commits separate for easier review but would suggest to squash them all before merge.

[cli] misc enhancements

---

script/check-posix-pty

This makes kill commands in pty checks run with sudo. Otherwise `ot-daemon` won't be killed and has to exit by itself, which makes `posix-pty-daemon` fail sometimes.

[continuous-integration] use sudo to kill daemon

---

tests/scripts/expect/cli-router.exp

Sometimes the `router` command returns `Link: 0` and makes the test fail. This fix it.

[continuous-integration] fix expect router link

---

src/posix/CMakeLists.txt
src/posix/cli.cmake

This fixes UART RAW mode not enabled in ot-br-posix.

[cmake] make UART RAW config visible in daemon mode

---

include/openthread/link.h
src/core/api/link_api.cpp
src/core/mac/mac.cpp
src/core/mac/mac.hpp
src/core/mac/sub_mac.cpp
src/core/mac/sub_mac.hpp
src/core/radio/radio.hpp
src/core/thread/csl_tx_scheduler.cpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp
tests/scripts/thread-cert/config.py
tests/scripts/thread-cert/mle.py
tests/scripts/thread-cert/v1_2_test_csl_transmission.py

Current implementation is a different of spec regarding CSL channel:
> 3.2.6.3.2    CSL Channel
> A CSL Receiver MAY configure macCslChannelMask to indicate an additional channel distinct from phyCurrentChannel. The macCslChannelMask is relayed by a CSL Receiver SSED Child to a CSL Transmitter Parent Router via the CSL Channel TLV sent in the Child Update Request as described in Section 4.6, Child Link Communication in Chapter 4, Mesh Link Establishment. A CSL Transmitter Parent Router MUST be capable of storing as many CSL Channel values as supported CSL Receiver SSED children.
> If configured, CSL data transmission and reception using the additional channel operates as described in Section 6.12.2.6 in [IEEE802154-2015]. The CSL Channel for a Thread Interface operating as a CSL Receiver …

[low-power] fix csl channel

---

tests/unit/CMakeLists.txt

This commit changes the unit tests `CMakeLists.txt` file to list
the targets in `set_target_properties()` call one per line. This
helps make it easier to read, also reduces the chance of merge
conflicts when new unit tests are added.

[cmake] list targets one per line in unit test CMakeLists

---

include/openthread/cli.h
include/openthread/error.h
include/openthread/instance.h
src/cli/cli.cpp
src/cli/cli.hpp
src/core/common/logging.cpp

This commit changes the CLI `Process{Cmd}()` handler methods to return
an `otError` (instead of outputting the result). This helps harmonize
the `Process{Cmd}()` handlers in different CLI modules. It also
enables the result of CLI command to be outputted from `ProcessLine()`
after the command is looked up in the table and the corresponding
`Process{Cmd}()` handler is invoked.
This commit also adds a new error code `OT_ERROR_PENDING`. This
special error code indicates the success or error status of an
operation is not yet known and is pending. This is then used by some
of the CLI `Process{Cmd}()` methods which perform an async operation,
e.g., `ProcessDiscover()` returns `OT_ERROR_PENDING` if the discover
scan starts successfully, and later the final result is outputted from
scan callback. …

[cli] return error from 'Process{Cmd}()' methods, adding 'OT_ERROR_PENDING'

---

src/posix/console_cli.cpp
src/posix/console_cli.h
src/posix/main.c

This PR fixes the problem #5520 
The root cause of #5520 turned out to be the absence of LIBREADLINE in the environment. However the error I got is confusing and doesn't indicate that because the options dependencies are not good. I think the options' dependency and relationship here should be:
1. When `DEAMON=0`(ot-cli, ot-ncp will be built and ot-cli depends on console), `CLI_TRANSPORT=CONSOLE` MUST be used. And otherwise (`DEAMON=1`), `CLI_TRANSPORT=UART`MUST be used. **So when users build posix, they don't need to consider the option `CLI_TRANSPORT`.**  It's reasonable to add the evaluation for `CLI_TRANSPORT` in `Makefile-posix`.
2. When `CLI_TRANSPORT=CONSOLE`, `(HAVE_LIBEDIT || HAVE_LIBREADLINE)` MUST be defined and `DAEMON=0` MUST be satisfied. I think `(HAVE_LIBEDIT || …

[posix] fix options dependency

---

src/core/mac/mac.cpp

Allows receiving a Joiner Entrust message even after the device has been commissioned.
Resolves #5526

[mac] only apply neighbor check when key id mode is 1

---

.codecov.yml

This adds 2 coverage checks to pull requests:
1. The overall coverage must not drop more than 1% against the parent commit.
1. ~~The diff coverage must be at least 85%.~~

[continuous-integration] add code coverage threshold

---

src/cli/cli_config.h
src/cli/cli_console.hpp

Fix compile warning: "OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE"
is not defined, evaluates to 0 [-Wundef]

[cli] fix compile warning

---

src/core/meshcop/meshcop.cpp

`LogError()` uses `otLogWarnMeshCoP()`, which was included by `thread/thread_netif.hpp -> meshcop/joiner.hpp -> common/logging.hpp`.
`thread_netif.hpp` includes `joiner.hpp` only if `OT_JOINER=ON`, so the build would fail if `OT_JOINER=OFF`. This PR fixes it.

[meshcop] include logging.hpp for helper function 'LogError()'

---

script/test

When no arguments are provided to `script/test`, the script prints `$1: unbound variable` and exits without printing the usage information. This is due to the `set -u` at the top. 
This PR has a small fix so that a newbie like me is presented with the usage information. Also, it prints an error when it detect an unknown command.
Please note that the arguments to the commands themselves are not validated.
Thanks!

[script] fix output when no arguments are specified

---

.github/workflows/simulation-1.2.yml
tests/scripts/thread-cert/Cert_8_1_01_Commissioning.py
tests/scripts/thread-cert/command.py
tests/scripts/thread-cert/config.py
tests/scripts/thread-cert/thread_cert.py

This PR runs Thread 1.1 certification tests with packet verification for 1.2 build because Thread 1.2 certified devices are supposed to be able to pass **Thread 1.1 certification** first.
**Note: changes to test `TOPOLOGY`:**
- Original: nodes use version=1.1 by default
- Now: nodes use version according to ENV, except explicitly specified

[github-actions] run Thread 1.1 cert tests for 1.2 build

---

.github/workflows/simulation-1.2.yml
.github/workflows/simulation.yml
script/test
src/posix/platform/netif.cpp
tests/scripts/thread-cert/backbone/bbr_5_11_01.py
tests/scripts/thread-cert/config.py
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/pktverify/addrs.py
tests/scripts/thread-cert/pktverify/consts.py
tests/scripts/thread-cert/pktverify/layer_fields.py
tests/scripts/thread-cert/pktverify/packet_verifier.py
tests/scripts/thread-cert/pktverify/utils.py
tests/scripts/thread-cert/run_bbr_tests.py
tests/scripts/thread-cert/simulator.py
tests/scripts/thread-cert/thread_cert.py

**Thread 1.2 CI with OTBR and Backbone link**
- incomplete, some steps can not pass yet, just to make sure Backbone traffic verification works
- **Verified that Codecov in Docker works**:
**Some implementation details:**
- Most existing code of `node.py` is shared by OTBR Docker
- Backbone related test scripts are found in `tests/scripts/thread-cert/backbone`
- A new script `tests/scripts/thread-cert/run_bbr_tests.py` is added to manage multiple running tests
- Test configuration differs according to `PORT_OFFSET`
- Backbone interface name: `Backbone{PORT_OFFSET}`
- Backbone network prefix: `91{PORT_OFFSET:02x}::/64`
- Docker instance name: `otbr_{PORT_OFFSET}_{nodeid}`
- Output Files:
- Pcap: 
- Thread: `{test_name}_{PORT_OFFSET}.pcap`
- Backbone: …

[thread-cert] Thread 1.2 CI with OTBR and Backbone link

---

include/openthread/thread.h
src/cli/README.md
src/cli/cli.cpp
src/cli/cli.hpp
src/core/api/thread_ftd_api.cpp
src/core/thread/address_resolver.hpp
tests/scripts/thread-cert/node.py

This PR allows Reference Devices to send fake Proactive Address Notification messages. 
This PR will be used by #5516 for testing purpose.

[reference-device] send fake ADDR_NTF.ntf

---

.codecov.yml

This makes codecov only check the 1% threshold for PRs, not for commits on master branch. Fixes https://github.com/openthread/openthread/issues/5571.

[codecov] only post coverage check statuses to PRs

---

tests/scripts/thread-cert/Makefile.am
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/test_route_table.py

Turn out `test_route_table.py` was never tested. 
This PR fixes and adds `test_route_table.py` to the test suite.

[scripts] fix test_route_table.py

---

script/test
tests/scripts/thread-cert/pktverify/verify.py
tests/scripts/thread-cert/thread_cert.py

This PR allows running packet verification on a test info (.json) directly without running the test procedure, which can be helpful for developing and debugging packet verification code. 
**Usage:**
1. Run the normal packet verification to generate the test info (.json) and pcap files:
```bash
$ VIRTUAL_TIME=1 PACKET_VERIFICATION=1 ./script/test cert ./tests/scripts/thread-cert/Cert_5_5_02_LeaderReboot.py
...
Packet verification passed: Cert_5_5_02_LeaderReboot.json
```
2. Verify the test info (Cert_5_5_02_LeaderReboot.json) independently: 
```bash
$ ./script/test pktverify Cert_5_5_02_LeaderReboot.json
...
Packet verification passed: Cert_5_5_02_LeaderReboot.json
```
**One known issue to be fixed in a future PR:**
- Does not support test script that has multiple tests (multiple …

[pktverify] verify offline test info

---

tests/scripts/thread-cert/test_route_table.py

Observed that `test_route_table.py` (introduced by #5558) might fail by chance. 
Verified that this PR fixes this isue.

[scripts] fix test_route_table.py fails by chance

---

script/check-api-version

API version check always passes with "no updates", this fixes it.

[continuous-integration] fix API change detector

---

src/cli/cli.cpp
src/cli/cli.hpp
src/cli/cli_coap.cpp
src/cli/cli_coap_secure.cpp
src/cli/cli_commissioner.cpp
src/cli/cli_dataset.cpp
src/cli/cli_joiner.cpp
src/cli/cli_network_data.cpp
src/cli/cli_uart.cpp
src/cli/cli_udp.cpp

This commit contains a group of style fixes and smaller enhancements
in CLI modules:
- Remove unnecessary use of `struct` when declaring variable.
- Remove use of single `"%s"` in `Output` methods.
- Fix order of `#include` headers.
- Remove unnecessary use of `OT_UNUSED_VARIABLE`.
- Remove unnecessary temp variables and casts.
- Add comments to `#endif` directives than are more than  than 20
lines away from the corresponding `#if` they are associated with.

[cli] style fixes and smaller enhancements

---

src/cli/cli.cpp
src/cli/cli.hpp
src/cli/cli_commissioner.cpp
src/cli/cli_dataset.cpp
src/cli/cli_dataset.hpp
src/cli/cli_joiner.cpp

This commit also adds a template version of `OutputBytes()` which
accepts a reference array of a specific length. This helps simplify
the calls to this helper method where the array length can be
inferred. It also changes the code to use `OutputBytes()` for
outputting master key, pskc, xpanid, etc.

[cli] add 'OutputExtAddress()' helper method

---

.github/workflows/docker.yml

Resolve annotation in docker build. 
```
This action is ARCHIVED and will not receive any updates, update your workflows to use the official Docker action docker/setup-buildx-action@v1
```

[github-actions] use docker/setup-buildx-action@v1

---

Android.mk
src/cli/cli.cpp
src/cli/cli.hpp
src/cli/cli_coap.cpp
src/cli/cli_coap.hpp
src/cli/cli_coap_secure.cpp
src/cli/cli_coap_secure.hpp
src/cli/cli_commissioner.cpp
src/cli/cli_commissioner.hpp
src/cli/cli_dataset.cpp
src/cli/cli_dataset.hpp
src/cli/cli_joiner.cpp
src/cli/cli_joiner.hpp
src/cli/cli_network_data.cpp
src/cli/cli_network_data.hpp
src/cli/cli_udp.cpp
src/cli/cli_udp.hpp
src/core/BUILD.gn
src/core/CMakeLists.txt
src/core/Makefile.am
src/core/api/link_raw_api.cpp
src/core/utils/lookup_table.cpp
src/core/utils/lookup_table.hpp
tests/unit/CMakeLists.txt
tests/unit/Makefile.am
tests/unit/test_lookup_table.cpp

This commit adds `LookupTable` module which provides helper methods to
perform binary search in a generic sorted lookup table for specific
entry matching a given name string. It also provides `constexpr`
methods to check (at build-time) whether a lookup table array is
sorted. This commit also updates CLI modules to use the `LookupTable`
methods for command lookup. It also adds a unit test for the lookup
table.

[utils] adding 'LookupTable' class and use it in CLI

---

src/core/net/ip6.cpp
src/core/net/udp6.cpp

This commit also fixes warning error with unused returned `otError`
value when calling `RemoveUnsecurePort()`.

[ip6] use 'Get<Filter>()' (remove unnecessary namespace)

---

doc/site/en/guides/border-router/beaglebone-black.md

Added language to show how to replace Connman with Network Manager to enable the default setup scripts.
Added pointers on setting up a WiLink 8 module for Wi-Fi AP development.
Removed explanation of downloading and flashing the BeagleBone image in favor of linking to the public BeagleBone documentation.
Removed explanation of expanding and truncating the filesystem in favor of using the helper tool from BeagleBone.

[docs] update BeagleBone setup guide

---

src/cli/cli_joiner.cpp

---
This should help with https://github.com/openthread/openthread/issues/5554.
In earlier projects, we faced similar problems with `PRIx64` use with some embedded toolchains. 
In general, I would suggest we try to avoid using it if/when we can.

[cli] replace 'PRIx64' use

---

src/cli/cli.cpp
src/cli/cli.hpp
src/cli/cli_coap.cpp
src/cli/cli_coap_secure.cpp
src/cli/cli_commissioner.cpp
src/cli/cli_dataset.cpp
src/cli/cli_joiner.cpp
src/cli/cli_network_data.cpp
src/cli/cli_udp.cpp
src/core/utils/parse_cmdline.cpp
src/core/utils/parse_cmdline.hpp
tests/unit/CMakeLists.txt
tests/unit/Makefile.am
tests/unit/test_cmd_line_parser.cpp

This commit adds new helper functions under `Utils::CmdLineParser` to
parse a given ASCII string as different simple types, namely signed or
unsigned integers of different bit lengths (`uint8/16/32/64`, and
`int8/16/32`). The new functions validate that the parsed value fits
within the supported range of the expected int type. This commit also
adds different flavors of `ParseAsHexString()` to parse a hex string
into sequence of bytes (with fixed/known size or unknown size allowing
or disallowing truncation). It also moves the parse related methods
(like `ParseAsIp6Prefix`) from CLI modules in `CmdLineParser`.
The CLI modules are then updated to use the new `ParseAs{Type}`
functions simplifying the code and adding extra checks when parsing
the CLI input.
Finally, this commit adds a unit …

[cmd-parser] adding helper 'ParseAs{Type}' functions

---

src/cli/README.md
src/cli/cli.cpp
src/cli/cli.hpp
tests/scripts/expect/cli-child-supervision.exp

This PR adds cli command to control child supervision in order to replacing `wpanctl` with `ot-ctl` in silk.

[cli] add cli command to control child supervision

---

.codecov.yml

Coverage reporting by codecov.io seems unstable. For example, it is
not respecting LCOV_EXCL_START/STOP. Disable until we figure out the
issue.

[codecov] disable project coverage threshold

---

include/openthread/instance.h
include/openthread/link.h
src/cli/README.md
src/cli/cli.cpp
src/cli/cli.hpp
src/core/api/link_api.cpp
src/core/common/message.hpp
src/core/thread/indirect_sender.cpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder.hpp
tests/scripts/expect/v1_2-sed_mac_send.exp
tests/scripts/thread-cert/node.py

This command allows an Rx-Off-When-Idle device to send an empty mac data frame or mac datarequest to its parent. This command is only used for certification.

[low-power] add cli command `macsend` for certification

---

tests/scripts/thread-cert/Cert_9_2_04_ActiveDataset.py

replace must_verify with filter to avoid possible verification of coap retransmission packets which could cause filter incorrect packets.

[thread-cert] enhance case 9.2.4 to avoid reverifying coap retransmission packets

---

tests/toranj/start.sh
tests/toranj/test-043-meshcop-joiner-router.py

This commit adds a new test-case in `toranj` to cover MeshCoP and
joiner-router behavior.

[toranj] add new test-case covering joiner-router behavior

---

tests/scripts/thread-cert/Cert_8_2_01_JoinerRouter.py
tests/scripts/thread-cert/Cert_8_2_02_JoinerRouter.py
tests/scripts/thread-cert/Cert_9_2_11_MasterKey.py

For 8.x.x, there is validation that joiner has the same keys as the commissioner after commissioning, it should be configured with a different master key before start commissioning.

[tests] init joiner with different masterkey before start

---

tests/scripts/thread-cert/node.py

This PR sets nodes' extaddrs to `0x166e0a0000000000 + nodeid`, which does not change node behavior but makes it easier for us to analyze pcaps.
Depends on https://github.com/openthread/pyspinel/pull/103. 
Please skip the commit that uses `simonlingoogle/pyspinel@fix-extaddr` for testing when merging. @jwhui

[thread-cert] set node addr64 to EXTENDED_ADDRESS_BASE + nodeid

---

doc/site/en/guides/border-router/beaglebone-black.md

Fixing a few formatting things I should've caught when reviewing the update to the BBB guide:
- The callouts should only have a single > on the first line
- The ### within a code block was causing issues with my import script... easier to just change them to a single #

[docs] update BBB guide formatting

---

src/core/BUILD.gn
src/core/Makefile.am
src/core/common/numeric_limits.hpp
src/core/utils/parse_cmdline.cpp

We don't have C++ STL on some platforms, so this replaces it.

[cmd-parser] remove dependency of <limits>

---

src/core/common/debug.hpp
src/posix/platform/misc.cpp

This allows users to enable OT_ASSERT in release builds on posix systems.

[debug] prefer user provided assert to system assert

---

include/openthread/instance.h
include/openthread/ip6.h
src/core/net/ip6.cpp
src/core/net/udp6.cpp
tests/scripts/expect/cli-anycast.exp
tests/scripts/expect/v1_2-rcp.exp

* Check source address of packets from users
* Determine anycast address by MLE API for accuracy
* Replace anycast address with a valid unicast address when sending with platform UDP in UDP layer
* Replace anycast address with a valid unicast address in IP layer

[ip6] no anycast as source address

---

src/core/coap/coap.cpp

This PR:
- allow max URI path length of 32
- change error to `OT_ERROR_PARSE` (used to be `OT_ERROR_NOT_FOUND`)

[coap] allow max URI path length

---

.github/workflows/simulation-1.2.yml
script/test

This PR fixes random fails in Thread 1.2 Backbone tests that uses OTBR Docker. 
The fails was caused by failing to start `tayga` service when there are many OTBR Dockers running. 
This PR turns off NAT64 feature of OTBR in 1.2 Backbone tests to avoid this issue since NAT64 is not useful for Backbone tests. 
Fixes https://github.com/openthread/openthread/issues/5651

[thread-cert] turn off OTBR NAT64 in 1.2 Backbone tests

---

script/check-posix-pty

This adds kill commands to POSIX pty check, to make sure all processes are stopped before the check completes. Fixes https://github.com/openthread/openthread/issues/5648.

[continuous-integration] kill ot-rcp and ot-cli in pty check

---

src/core/BUILD.gn
src/core/Makefile.am
src/core/common/arg_macros.hpp
src/core/common/logging.hpp
tests/unit/CMakeLists.txt
tests/unit/Makefile.am
tests/unit/test_macros.cpp

**[common] macros to get first/second/rest of variadic arguments**
This commit adds three macros in a new header `arg_macros.hpp`
`OT_GET_FIRST()`, `OT_GET_RESET(...)`, and `OT_GET_SECOND()`. These
macros help with parsing variadic arguments passed to a function/macro
and can handle the case where variadic macro arguments is empty
without requiring toolchain specific behavior/support. This commit
also adds a unit test `test_macros` for the newly added macros.
**[logging] update logging to use new helper macros**
--------
The macros provide some more functionality which we can use (in a follow-up PR)
to simplify `VerifyOrExit()` (allow second `aAction` argument to be optional).

[logging] add macros to get first/second/rest of variadic args and update logging (remove extra NULL arg)

---

configure.ac

The `configure` script runs with `#!/bin/sh`, but actually required
bash. POSIX sh does not have either the `function` keyword or pattern
replacement in variable subsititutions.

[autoconf] remove bashisms from configure.ac

---

.github/workflows/simulation.yml
examples/Makefile-simulation
examples/platforms/simulation/CMakeLists.txt
examples/platforms/simulation/platform-config.h
examples/platforms/simulation/platform-simulation.h
examples/platforms/simulation/radio.c
examples/platforms/simulation/system.c
examples/platforms/simulation/virtual_time/platform-sim.c
src/posix/platform/virtual_time.cpp
tests/scripts/thread-cert/simulator.py
tests/scripts/thread-cert/sniffer_transport.py

Currently, the `WELLKNOWN_NODE_ID = 34` is not properly defined. 
- In virtual time simulation, `WELLKNOWN_NODE_ID` limits the number of ports each `PORT_OFFSET` can occupy. The virtual time simulator listens at the `nodeid=0` port rather than `nodeid=34` port. So, there is no such thing as wellknown node ID in virtual time simulation. 
- In real time simulation, the sniffer listens at the `nodeid=34` port. **This PR changes it to `nodeid=0` port to be consistent with other parts.** 
- In posix virtual time, the simulator listens at the `nodeid=0` port. So, there is no such thing as wellknown node ID in Posix virtual time. 
Overall, I think `WELLKNOWN_NODE_ID = 34` is not intuitive and not properly defined. Thus this PR changes it to `MAX_NETWORK_SIZE = 33` and make it (configuration …

[simulation] add configuration MAX_NETWORK_SIZE

---

src/core/meshcop/dataset_local.hpp
src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager.hpp
src/core/meshcop/dataset_manager_ftd.cpp

This commit contains miscellaneous smaller enhancements in
`DataseManager` module:
- keep `public`, `protected` `private` definitions in this order
- add helper `GetType()`, `IsActiveDataset()`, `IsPendingDataset()`
- use `Read()` helper  instead of `mLocal.Read()`
- remove unused definitions of `HandleUdpReceive()`
- remove `mUriGet`, `mUriSet`, and determine them based on the
dataset type (active/pending).
- re-order member variables to help with packing
- update method documentations

[dataset-manager] misc enhancements

---

src/core/api/coap_api.cpp
src/core/coap/coap.cpp
src/core/coap/coap_message.cpp
src/core/coap/coap_message.hpp
src/core/meshcop/border_agent.cpp
src/core/thread/mlr_manager.cpp

This commit adds a new helper method to set the token on a CoAP
`Message` by copying it from another `Message`. It also renames the
method which generates a random token of a given length to
`GenerateRandomToken()`.

[coap] add helper method 'Message::SetTokenFromMessage()'

---

include/openthread/instance.h
src/core/common/notifier.cpp
src/core/common/notifier.hpp
src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager.hpp

**[notifier] signal change to active or pending Operational Dataset**
**[notifier] simplify 'EventToString()'**
This commit changes `EventToString()` to use an array instead of
`switch`. This helps with code size due to enumerator cases being
`uint32_t` bitmask values and therefore compliers may not be able to
optimize the `switch` statement as a table.

[notifier] signal change to active/pending dataset + simplify 'Notifier::EventToString'

---

script/cmake-build

This change ensures the cc2538 cmake build uses the release build type
and the compile option `-Os` (optimize for size). This harmonizes the
cmake build with automake version. It also helps address an issue with
recent PRs failing on cc2538 cmake build with arm-gcc-5 due to
reaching flash size limit (without `-Os` option).

[cmake-build] ensure cc2538 uses 'CMAKE_BUILD_TYPE=Release'

---

src/core/api/border_agent_api.cpp
src/core/meshcop/border_agent.cpp
src/core/meshcop/border_agent.hpp
tests/toranj/openthread-core-toranj-config.h

This commit contains smaller enhancements in `BorderAgent` module
- define `ForwardContext` as a private sub-type of BorderAgent
- change `ForwardContext` to be `InstanceLocatorInit` and avoid
`new` (use `Init()`)
- add `HandleCoapResponse()` method which is called from `static`
method `HandleCoapResponse()`.
- convert file `static` functions `SendErrorMessage()` to `BorderAgent`
methods
- Add `State` enum and inline/remove `SetState()`.
- Smaller style/documentation fixes (e.g., remove unnecessary `{ }`).

[border-agent] misc enhancements

---

.github/workflows/build.yml
script/bootstrap
script/make-pretty
src/core/common/timer.cpp
src/core/common/timer.hpp
src/core/meshcop/joiner_router.hpp
src/core/net/ip6_mpl.hpp
src/core/thread/csl_tx_scheduler.cpp
src/core/thread/csl_tx_scheduler.hpp
src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/network_data_leader_ftd.cpp
src/core/thread/network_data_leader_ftd.hpp
src/core/utils/channel_monitor.cpp
src/core/utils/channel_monitor.hpp

This PR introduces clang-tidy into `script/make-pretty`.
Only one clang-tidy check (readability-make-member-function-const) is enabled in this initial PR as an example.
Further checks will be enabled in future PRs.

[pretty] add clang-tidy to script/make-pretty

---

src/core/config/platform.h
src/lib/spinel/spinel_interface.hpp

Adds `OPENTHREAD_CONFIG_PLATFORM_RADIO_SPINEL_RX_FRAME_BUFFER_SIZE`
config option which specifies the rx frame buffer size used by
`SpinelInterface` in RCP host (posix) code. This is applicable/used when
`RadioSpinel` platform is used.
-----
This is related to openthread/openthread#5678.

[spinel-interface] add config option to change the rx frame buffer size

---

CMakeLists.txt
etc/cmake/functions.cmake

This commit adds support for external platforms into cmake build system.

[cmake] add support for external platforms

---

include/openthread/instance.h
include/openthread/platform/udp.h
src/core/backbone_router/backbone_tmf.cpp
src/core/backbone_router/backbone_tmf.hpp
src/core/backbone_router/bbr_local.cpp
src/core/backbone_router/bbr_local.hpp
src/core/backbone_router/bbr_manager.cpp
src/core/coap/coap.cpp
src/core/coap/coap.hpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp
src/posix/platform/udp.cpp
tests/scripts/thread-cert/backbone/test_bmlr.py
tests/scripts/thread-cert/v1_2_test_backbone_router_service.py
tests/scripts/thread-cert/v1_2_test_domain_unicast_address.py
tests/scripts/thread-cert/v1_2_test_domain_unicast_address_registration.py
tests/scripts/thread-cert/v1_2_test_dua_handle_address_error.py

This PR enhances Backbone TMF:
**DAD** feature of `Thread 1.2 DUA` requires this PR to receive `Backbone Query / Answer` on the Backbone network.

[backbone-router] backbone TMF enhancements

---

.github/workflows/build.yml
script/bootstrap
script/clang-tidy
script/make-pretty

This commit introduces misc clang-tidy enhancements:
- Avoid creating symlinks in `/usr/bin` directory
- Search for clang-tidy-10 executables
- Fix potential bootstrap fail: permission denied in /opt directory

[style] clang-tidy misc enhancements

---

examples/platforms/efr32/src/radio.c

This PR fixes #5679.
If the RAIL interrupt fires late (for example, when the MCU is heavily loaded), then `RAIL_IEEE802154_GetAddress` and `RAIL_IEEE802154_SetFramePending` return `RAIL_STATUS_INVALID_STATE` because it is too late to modify the outgoing Immediate ACK. The proposed solution is to avoid asserting and print a warning to make the user aware of such problems.

[efr32] avoid asserts during data requests

---

src/core/utils/parse_cmdline.cpp

Fixes the following compiler error:
utils/parse_cmdline.cpp:230:28: runtime error: negation of -2147483648
cannot be represented in type 'int32_t' (aka 'int'); cast to an
unsigned type to negate this value to itself

[cmdline-parser] avoid casting -INT32_MIN directly to int32_t

---

.github/workflows/build.yml
script/cmake-build
src/core/meshcop/commissioner.cpp
src/core/thread/network_data_leader_ftd.cpp

There is a warning with gcc/g++ 10.2.0 when clearing an object of non-trivial type with `memset`:
(build command: `cmake -GNinja -DOT_COMMISSIONER=ON .. && ninja`)
```shell
OPENTHREAD_CONFIG_THREAD_VERSION=OT_THREAD_VERSION_1_1
[65/132] Building CXX object src/core/CMakeFiles/openthread-ftd.dir/meshcop/commissioner.cpp.o
../src/core/meshcop/commissioner.cpp: In constructor ‘ot::MeshCoP::Commissioner::Commissioner(ot::Instance&)’:
../src/core/meshcop/commissioner.cpp:78:41: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct ot::MeshCoP::Commissioner::Joiner’; use assignment or value-initialization instead [-Wclass-memaccess]
78 |     memset(mJoiners, 0, sizeof(mJoiners));
|                                         ^
In file included from …
```

[build] fix warning of clearing non-trivial type

---

examples/platforms/nrf528xx/src/transport/spi-slave.c
third_party/NordicSemiconductor/nrfx/drivers/include/nrfx_spis.h
third_party/NordicSemiconductor/nrfx/drivers/src/nrfx_spis.c
third_party/NordicSemiconductor/nrfx/hal/nrf_spis.h

When the SPI is transmitting a frame, the ncp_spi sets the SPI to
transmit the second frame.  After the current frame is transmitted,
the SPI generates the END and ACQUIRED event at the same time. The
SPI driver processes the ACQUIRED event first and then the END event.
The ACQUIRED event notifies the up layer to set the SPI GPIO interrupt
pin. The END event notifies the up layer that the transmission has
completed. Because the SPI tx/rx buffer variables in the `spi_slave.c`
has been updated to the second frame buffer. The ncp_spi thinks that
the second frame has been transmitted in the END event. Then the second
frame is lost.
This CL processes the END event first then ACQUIRED event. To avoid
the cached frame buffer variables are passed to the ncp_spi, the SPI
driver gets the frame …

[nrf528xx] fix SPI issue

---

src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager.hpp

This commit simplifies `DatasetManager::SendSetRequest()` by adding a
method to `AppendDatasetToMessage()` which uses `Dataset::SetFrom()`
method to convert a given `otOperationalDataset` to a TLV sequence
before appending it to a given message. The conversion is performed in
a new method to ensure that the stack/temporary variable `Dataset` is
released before the call to process/send the prepared message.

[dataset-manager] simplify 'SendSetRequest()' 

---

src/core/meshcop/dataset.cpp
src/core/meshcop/dataset.hpp
src/core/meshcop/dataset_manager_ftd.cpp

This commit also adds two specializations of the `SetTlv()` for
`uint16_t` and `uint32_t` value types where the given integral value
is `BigEndian::HostSwap()`-ed before written as the TLV value (these
specializations replace `SetUint16Tlv()` and `SetUint32Tlv()`).

[dataset] add new helper 'SetTlv()' with a template 'ValueType'

---

examples/apps/cli/main.c
include/openthread/cli.h
include/openthread/instance.h
include/openthread/platform/logging.h
src/cli/cli.cpp
src/core/common/logging.cpp
src/ncp/ncp_base.cpp

This commit adds a new platform function `otPlatLogLine()`. This
function is optional and if not implemented by platform layer, a
default weak implementation is provided and used by the OpenThread
core using `otPlatLog()`.The new function is used by OpenThread core
when the feature `OPENTHREAD_CONFIG_LOG_DEFINE_AS_MACRO_ONLY` is not
enabled (which is the default behavior). In this case, the OT core
itself will prepare a full log line.
This commit also adds implementations of the new platform function for
NCP and CLI modules.

[logging] add optional `otPlatLogLine()` & use it in NCP/CLI

---

.github/workflows/build.yml

This commit changes the cmake version used to verify building on arm-based platforms.

[test] arm build with cmake 3.10

---

src/cli/README.md

`s` in mode has been deprecated.

[cli] update cli doc

---

.github/workflows/simulation-1.2.yml
include/openthread/instance.h
include/openthread/netdiag.h
src/cli/cli.cpp
src/cli/cli.hpp
src/core/thread/network_diagnostic.cpp

This PR fixes the bug that the Network Diagnostic callback is not called when we failed to get the response (e.g. the request timeouted). This results in no command output in the CLI.
Fixes https://github.com/openthread/ot-br-posix/issues/588.

[net-diag] invoke the callback when failed to get the response

---

src/core/BUILD.gn
src/core/Makefile.am
src/core/common/message.hpp
src/core/common/type_traits.hpp
src/core/meshcop/dataset.hpp

This commit adds a new header `common/type_traits.hpp` which provides
`IsPointer<Type>` to check whether a template `Type` is a pointer type
or not. This is then used in `Message` and `Dataset` methods where we
append/set a generic object to check (as an `static_assert`) that the
object type is not a pointer. This adds protection (causing a compile
time error) against potential incorrect use of these methods (i.e.,
passing a pointer instead of a reference to an object by mistake).

[type-traits] add 'IsPointer<Type>' and use it in message/dataset

---

.codecov.yml
.github/workflows/posix.yml
.github/workflows/simulation-1.2.yml
.github/workflows/simulation.yml
.github/workflows/toranj.yml
script/test
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/run_bbr_tests.py

This PR makes it use `lcov` to generate the coverage report and upload using the bash script, which may be more stable.
Resolves #5628.

[continuous-integration] use lcov to generate coverage data

---

examples/platforms/efr32/src/radio.c

This PR increases the FIFO size used for storing the handles of the data request packets that were ACKed with the frame pending bit set. This is a temporary "fix" for #5689; the actual reason for the assert is being investigated by Silabs.
The logic behind the original implementation is here: #4484.

[efr32] radio: increase FIFO size to allow handling of heavy traffic

---

src/core/api/dataset_api.cpp
src/core/api/dataset_ftd_api.cpp
src/core/meshcop/dataset.cpp
src/core/meshcop/dataset.hpp
src/core/meshcop/dataset_local.cpp
src/core/meshcop/dataset_local.hpp
src/core/meshcop/dataset_manager.cpp
src/core/meshcop/dataset_manager.hpp
src/core/meshcop/dataset_manager_ftd.cpp
src/core/meshcop/joiner.cpp
src/core/utils/channel_manager.cpp
src/lib/spinel/radio_spinel_impl.hpp

This commit adds `Dataset::Info` and `Dataset::Components` types
mirroring `otOperationalDataset` & `otOperationalDatasetComponents`
definitions and providing helper methods to get/set different fields
in the dataset.

[dataset] add 'Info' and 'Components' types

---

src/core/net/ip6.cpp

This commit allows IPv6 anycast as source address given it is not
forbidden in standards.
This PR addresses #5698

[ip6] allow anycast source

---

.github/workflows/simulation-1.2.yml
include/openthread/backbone_router_ftd.h
include/openthread/instance.h
script/test
src/core/api/backbone_router_ftd_api.cpp
src/core/backbone_router/bbr_leader.cpp
src/core/backbone_router/bbr_local.cpp
src/core/backbone_router/bbr_local.hpp
src/core/backbone_router/ndproxy_table.cpp
src/core/backbone_router/ndproxy_table.hpp
tests/scripts/thread-cert/backbone/bbr_5_11_01.py
tests/scripts/thread-cert/backbone/test_ndproxy.py
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/pktverify/addrs.py
tests/scripts/thread-cert/run_bbr_tests.py

This commit works with https://github.com/openthread/ot-br-posix/pull/581 to implement Backbone ND Proxy for Thread 1.2 DUA:
AdvAutonomous off; AdvRouterAddr off;`
TODO:
**Notes for merging:** @jwhui 
We need to merge this PR first and then revise https://github.com/openthread/ot-br-posix/pull/581 to use OpenThread master commit to pass all checks and be merged.

[dua] implement ND Proxy callbacks

---

examples/Makefile-efr32mg1
examples/Makefile-efr32mg12
examples/Makefile-efr32mg13

This fixes a bug where Series 1 chips are failing to boot when compiles with `arm-none-eabi-gcc` version 7.2.1

[efr32] Use -mfpu=fpv4-sp-d16 for efr32mg1x chips

---

script/make-pretty

This change limits the output (when clang-tidy check fails) to error
or warning messages along with next 5 lines (remove `^|`)
-----
_Background of this change:_ 
I have been looking at output in some builds where the `clang-tidy` check was failing and it was hard to find the error from output -> example: [gh-action-pretty](https://github.com/abtink/openthread/runs/1339414917?check_suite_focus=true).
I think the issue is with `^|`. Running the script locally with the change in this PR just shows the warning/error lines and few lines after (would help with fixing the issue).

[script] update 'make-pretty clang-tidy' to output warning/error only

---

src/core/mac/mac.cpp
src/core/thread/link_metrics.cpp
src/core/thread/link_quality.cpp
src/core/thread/link_quality.hpp
tests/unit/test_link_quality.cpp

This PR applies `Clearable` for some classes in `link_quality` to replace `Reset` method and enhance consistency.

[clearable] reuse clearable for some classes

---

src/core/thread/mle.cpp
src/core/thread/mle.hpp
src/core/thread/mle_router.cpp

This commits adds a common helper method to read Link and/or MLE Frame
Counters from a message. The Link Frame Counter TLV is expected to be
present in the message. The MLE Frame Counter TLV, however, is optional
and when not present the Link Frame Counter is also used as MLE Frame
Counter value.

[mle] add helper 'ReadFrameCounters()' to read Link/MLE Frame Counters

---

src/core/common/linked_list.hpp
src/core/net/netif.cpp
src/core/thread/topology.cpp

This PR adds an overload version for `LinkedList::FindMatching` which doesn't require `prev` as parameter. In many cases we don't need to get the previous item's pointer when finding in a list. This version would help in these cases.

[linked-list] add an overload for LinkedList::FindMatching for convenience

---

script/bootstrap

This commit allows bootstrap not to fail but print warning if installing llvm@9 or clang-format-9 or clang-tidy-9 failed. 
This has been the best practice for installing other pretty tools.

[bootstrap] show warning but not fail when install llvm@9 failed

---

.github/workflows/simulation-1.2.yml
script/test
tests/scripts/thread-cert/run_cert_suite.py

This PR enhances `script/test cert_suite` command to run multiple tests concurrently to reduce execution time. 
**Before this PR:**
```bash
~/src/openthread$ time ./script/test cert_suite ./tests/scripts/thread-cert/Cert_*.py
...
real    0m57.071s
```
**Using this PR:**
```bash
~/src/openthread$ time ./script/test cert_suite ./tests/scripts/thread-cert/Cert_*.py
...
real    0m9.720s
```
The `packet-verification` job's test execution time is reduced from [35m](https://github.com/openthread/openthread/pull/5563/checks?check_run_id=1171620975) to [12m](https://github.com/openthread/openthread/pull/5586/checks?check_run_id=1175646305).
This PR also allows running Backbone CI tests with `script/test cert_suite`.

[scripts] enhance cert_suite to run multiple tests concurrently

---

tests/scripts/expect/tun-realm-local-multicast.exp

Given the linear topology in this test, this commit
introduces wait time so that the Thread Links are
synced well before ping happens.

[tests] fix tun-realm-local-multicast.exp

---

src/lib/spinel/radio_spinel_impl.hpp

This PR makes ot-daemon print the RCP reset cause before exit, in case the RCP resets unexpectedly.

[spinel] print error on RCP reset before dying

---

src/posix/platform/openthread-core-posix-config.h

This commit increases the `OPENTHREAD_CONFIG_LOG_MAX_SIZE` from 150 to 1024 for posix.

[posix] increase max log size

---

examples/platforms/nrf528xx/src/fem.c
examples/platforms/nrf528xx/src/platform-fem.h
examples/platforms/nrf528xx/src/platform-nrf5.h
examples/platforms/nrf528xx/src/radio.c
examples/platforms/nrf528xx/src/system.c
third_party/NordicSemiconductor/drivers/radio/fal/nrf_802154_fal.c

When users add a FEM after the radio chip, the actual output power is
determined by both the radio chip and FEM. The radio driver only provide
a function to set the radio output power. This PR adds Macros and functions
to allow users to implement the power setting functions by themselves.

[nrf528xx] allow users to implement power setting functions

---

src/core/mac/sub_mac.cpp

This PR fixes #5783.
The cause is that, on nRF platform, `otPlatRadioGetNow` always gets the LSB part of an `uint64_t` time. However, on simulation platform, this is not the case. So in
```
if (otPlatRadioGetNow(&GetInstance()) <
mTransmitFrame.mInfo.mTxInfo.mTxDelayBaseTime + mTransmitFrame.mInfo.mTxInfo.mTxDelay)
```
we don't get the result expected. `otPlatRadioGetNow(&GetInstance())` is a very big number on simulation platform, and `mTxDelayBaseTime` is the LSB part of the rx time.

[low-power] fix csl simulation

---

tests/toranj/openthread-core-toranj-config.h

-------
Background on this:
I recently rebased the multi-radio/trel branch from #4440 on master, noticed that a bunch of test-cases under multi-radio/hybrid topology [were failing](https://github.com/abtink/openthread/runs/1409330167). After investigating further discovered that it is related to the change from https://github.com/openthread/openthread/pull/5792 where we use of heap for msg pool (mainly that the number of msg buffers (derived from default heap size) is not enough for the some test-cases where we send a lot of traffic).
We can increase the heap size but I prefer to continue to use msg pool with known/configured number of msgs in `toranj` test cases (we already have `#define OPENTHREAD_CONFIG_NUM_MESSAGE_BUFFERS 256` in `toranj-config` which ensures we have enough msg buffer …

[toranj] use msg pool (do not use heap) in toranj config

---

src/ncp/ncp_base_mtd.cpp

This commit adds missing error check during parsing of the input
parameters in property handlers for `NETWORK_NAME`, `THREAD_MODE`,
`STREAM_NET_INSECURE`, and `MAC_FIXED_RSS`.
It also changes the encoding of dataset and the msg buffer counter
to ensure to check for error.
----
Should help address Issue https://github.com/openthread/openthread/issues/5829

[ncp-base] fix missing error checks in some property handlers

---

src/lib/spinel/radio_spinel_impl.hpp

This commit addresses an issue in `RadioSpinel::Init()` to correctly
verify that device is connected to an RCP (i.e., capability list
includes `SPINEL_CAP_CONFIG_RADIO`) and if not then exit (`DieNow()`)
with `OT_EXIT_RADIO_SPINEL_INCOMPATIBLE` code.
It also simplifies the checking of capabilities for log stream support
(`SPINEL_CAP_OPENTHREAD_LOG_METADATA`) by changing the code to get and
process the `SPINEL_PROP_RADIO_CAPS` list only once from `IsRcp()`.

[radio-spinel] verify host is connected to an RCP

---

src/cli/cli.cpp
src/cli/cli.hpp

This commit contains small style changes in CLI module
- Not using `a{VariableName}` style for local variables
- Harmonize the use `char *aArgs[]` as the parameter type in command
handlers.

[cli] small enhancements and style fixes

---

src/cli/cli.cpp
src/cli/cli.hpp

This commit simplifies the CLI module by adding new flavors of helper
methods `OutputLine/Format(aIndentSize, ...)` which prepend a given
number of indentation space characters before the format string.
It also harmonizes the other `Output{Item}()` methods which output an
item with a given indentation to use `aIndentSize` as the parameter
name and as the first parameter of the method.
It also simplifies the implementation of `OutputSpaces()`.

[cli] add helper 'Output()' methods which prepend indentation space

---

script/test
tests/scripts/expect/_common.exp

This commit enables `script/test` to run cert tests on NCP nodes of
POSIX platform.

[test] add rcp-ncp node type

---

examples/platforms/simulation/radio.c
examples/platforms/utils/mac_frame.cpp
examples/platforms/utils/mac_frame.h
src/core/mac/mac_frame.hpp

MAC command frame has its command ID encrypted in frame version 802.15.4-2015. Radio driver cannot decrypt this frame payload without extended address. So the frame pending bit is not correctly set in the ACK in response to data request command with version 2015. This PR adds a special handling for frame version 2015 and only checks the frame type when deciding if it needs to set the frame pending bit.

[low-power] frame pending bit handling for enh-ack in simulation

---

third_party/mbedtls/CMakeLists.txt

This commit avoid unnecessary rebuilds. The issue is caused by the
openthread-mbedtls-config target added by add_custom_target will always
be run, so the generated openthread-mbedtls-config.h is always
re-generated. This commit changes to use add_custom_command to generate
the header file.
Test:
```bash
./script/test clean build
./script/test build
touch third_party/mbedtls/mbedtls-config.h
./script/test build
```

[cmake] avoid unnecessary rebuilds

---

src/core/config/tmf.h

This commit allows turning off TMF proxying for DUA and MLR by predefining `CFLAGS`.
It's still enabled by default for Thread 1.2 FTD.

[tmf] allow turning off TMF proxying for DUA and MLR

---

src/core/net/ip6.cpp
src/core/net/ip6.hpp

As I observed, `aForward` in `Ip6::HandleOptions` is a purely 'in' parameter. We should remove the reference to clear the confusion.

[ip6] tiny enhancement for HandleOptions

---

src/core/meshcop/dataset.cpp
src/core/thread/key_manager.cpp
src/core/thread/key_manager.hpp

This commit updates `Dataset::Info::GenerateRandom()` to set the Key
Rotation Time in Security Policy component on the Dataset using its
default value (from `KeyManager`). This addresses the issue where the
generated Operational Dataset could potentially use zero for Key
Rotation time.
This commit also changes Security Policy Flags to use default value
from `KeyManager`.
------
_Adding a note on this_:
With existing code, if we happen to generate and use an Operation Dataset with Key Rotation Time value set to zero, while the value in Dataset may not be correct, it would not impact the value used by `KeyManager` (`Dataset::ApplyConfigruation()` uses `keyManager.SetKeyRotation()` which itself would verify the given value to be valid, otherwise it would continue to the previous value for …

[dataset] set key rotation time in security policy on random generation

---

src/core/api/dns_api.cpp
src/core/net/dns_client.cpp
src/core/net/dns_client.hpp
src/core/net/dns_headers.hpp

This commit contains a set of smaller enhancements/changes in DNS
modules:
- Adds `Client::QueryInfo` class (mirroring `otDnsQuery`).
- Simplifies iteration over `mPendingQueries`.
- Uses `Ip6::Address` instead of `otIp6Address` (internally).
- Updates documentation style in `dns_headers.hpp` .
- Changes internal constant/enum definitions to be `private`.
- Adds `ResourceRecordAaaa::IsAaaa()` helper to check whether a
given Resource Record is of AAAA type.
- Small style fixes.

[dns] misc enhancements

---

src/core/config/openthread-core-config-check.h

`OPENTHREAD_CONFIG_COAP_ACK_TIMEOUT_MILLIS` was removed in #4612.

[coap] update OPENTHREAD_CONFIG_COAP_ACK_TIMEOUT error message

---

.github/workflows/build.yml
.github/workflows/docker.yml
.github/workflows/fuzz.yml
.github/workflows/posix.yml
.github/workflows/simulation-1.2.yml
.github/workflows/simulation.yml
.github/workflows/size.yml
.github/workflows/toranj.yml
.github/workflows/version.yml
tests/unit/test_link_quality.cpp

This commit update Github Actions workflows to use `ubuntu 20.04` whenever applicable. 
- Change `ubuntu-latest` to `ubuntu-20.04` to cleanup the annotations:
```
Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816
```
- Change `ubuntu-18.04` to `ubuntu-20.04` wherever `ubuntu-20.04` works.
- Fixed a compile issue in `tests/unit/test_link_quality.cpp` on `ubuntu-20.04`
- Can not get `Simulation/expects` work on `ubuntu 20.04` due to unknown issue. Leave for further enhancement.

[github-actions] use ubuntu-20.04 for github actions

---

src/lib/spinel/radio_spinel.hpp
src/lib/spinel/radio_spinel_impl.hpp

This commit removes the unused `aWait` parameter from `Request()`
and `RequestV()` methods.

[radio-spinel] simplify 'Request()'

---

.github/workflows/simulation-1.2.yml
CONTRIBUTING.md
script/test

This PR adds action to upload core dumps, so libs and binaries for 1.2 certification. This is intended to solve issues like #5802, #5774 where programs intermittently crash however hard to reproduce it. Related issue: #5805.
I added this for `thread-1-2` and `low-power-packet-verification` first as an experimental work. We can add same actions for other items when it's necessary.
I've verified that we can analyze the core dumps with the artifacts using gdb successfully on our local PC: https://github.com/openthread/openthread/pull/5812#issuecomment-732749457

[github-actions] upload core dump, so libs and binaries for crashed programs

---

include/openthread/backbone_router_ftd.h
include/openthread/instance.h
src/core/api/backbone_router_ftd_api.cpp
src/core/backbone_router/multicast_listeners_table.cpp
src/core/backbone_router/multicast_listeners_table.hpp

otBackboneRouterMulticastListenerGetNext is also used by non reference device code.

[backbone-router] fix otBackboneRouterMulticastListenerGetNext missing

---

src/core/api/border_router_api.cpp
src/core/thread/network_data_local.cpp

This PR moves the border router configuration check into NetworkData::Local.

[border-router] move configuration check from api to inner class

---

tests/scripts/thread-cert/Cert_5_3_03_AddressQuery.py
tests/scripts/thread-cert/pktverify/packet_filter.py

5.3.3 pktverify fail by small chance when the ping reply is forwarded from `Router3 -> Leader -> Router2` instead of  `Router3 -> Router2`. In such case, the direct `wpan.dst16` is not Router2's RLOC16, but Leader's RLOC16. 
This commit change 5.3.3 to check for both `6lowpan mesh dst16` and `wpan.dst16` against Router2's RLOC16.

[thread-cert] fix 5.3.3 random fail by small chance

---

src/core/net/udp6.cpp
src/core/net/udp6.hpp

It failed to start CoAP socket due to the `mSocket.IsBound()` check ([link](https://github.com/openthread/openthread/blob/master/src/core/coap/coap.cpp#L1003)), the root cause is that the Socket variables were not initialized properly.

[udp6] initialize Socket variables in its constructor

---

.github/workflows/posix.yml
.github/workflows/simulation.yml
examples/Makefile-simulation
script/check-ncp-rcp-migrate
script/check-posix-pty
script/test
src/posix/Makefile-posix
src/posix/README.md

This commit simplifies the build paths:
* remove cmake prefix from `script/test`
* use fixed name for simulation and posix platforms just like others
Depends-On: openthread/ot-ns#112

[style] simplify build paths

---

src/core/diags/factory_diags.cpp
tests/scripts/expect/cli-misc.exp

This commit restrict diagnostic mode only when network stack is not up,
which prevents some issues caused by switching to diag mode after the
device was attached. For example, timers may not be triggered properly
after returnning from diagnostic mode.

[diag] check state before entering diagnostic mode

---

include/openthread-config-android.h

This commit removes settings storage path from
`include/openthread-config-android.h` to allow users define
the settings storage path on Android platform.

[android] remove settings storage path from config file

---

.github/workflows/simulation-1.2.yml

#5888 updates the build path for binaries. I just found there were no binaries uploaded in artifacts of action where crash happened. This PR updates the path correspondingly in upload actions.
I will work on something which doesn't use hard-coding. Currently let's just keep it as it is.

[github-actions] update binaries path in upload action

---

src/core/mac/mac.cpp

This PR fixes issue #5802 (and probably #5774).
Luckily, I caught a failed run of the Heisenbug after the core dump uploading feature is enabled. So I analyzed the core dump:
```
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at: …
```

[mac] stop timer before starting non-idle operation

---

.github/workflows/posix.yml
.github/workflows/simulation-1.2.yml
.github/workflows/simulation.yml
script/gcda-tool
script/test
tests/scripts/expect/_common.exp
tests/scripts/thread-cert/Makefile.am
tests/scripts/thread-cert/node.py

This commit ensures each node create its own profile data, so that they
can be merged after tests to produce more accurate profile data.
This commit also prints the coverage data of message.cpp after all
profile data are merged.

[test] separate code coverage data files

---

src/core/backbone_router/bbr_manager.cpp
src/core/thread/dua_manager.cpp
src/core/thread/dua_manager.hpp

**Background:**
```
PBBR
/      \
ROUTER---LEADER
```
In the tests of #5910 , we found that it's possible that a Router, in a topology like above, could send DUA.req so quickly after receiving `Data Response` from Leader that the PBBR is not able to process the same `Data Response` message and update the network data accordingly. Consequently, PBBR sends DUA.rsp with `kDuaInvalid` status because it can't find a valid Domain Prefix in the Network Data. 
This commit help resolve this issue with two fixes:
- Node to delay for up to 1000ms before sending DUA.req when domain prefix addresses is generated
- PBBR to respond with `kDuaGeneralFailure` to allow the node to re-register the same DUA again.

[dua] delay registration for DUA newly added

---

script/check-posix-pty
src/core/net/ip6.cpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp

This commit fixes TMF issues related to the Host tun interface.

[tmf] TMF not to use platform udp

---

src/core/net/ip6.cpp
src/core/net/ip6.hpp
tests/scripts/thread-cert/backbone/test_mlr_multicast_routing_across_thread_pans.py
tests/scripts/thread-cert/mcast6.py
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/pktverify/bytes.py
tests/scripts/thread-cert/pktverify/layer_fields.py
tests/scripts/thread-cert/pktverify/packet_filter.py

**The ping reply can not reach ROUTER1 since DUA feature is not complete. But verified locally that ping works with https://github.com/openthread/ot-br-posix/pull/586 merged**

[scripts] test multicast routing across Thread and Backbone

---

examples/platforms/efr32/src/radio.c

From PR #5701 onwards, the efr32 platform shows the following behavior:
```bash
> txpower -10
Done
>
> txpower
-113 dBm
Done
```
The bug is caused by the C promotion rules during the division of int16_t by unsigned in `otPlatRadioGetTransmitPower`. This PR fixes the issue.

[efr32] radio: fix otPlatRadioGetTransmitPower

---

include/openthread/crypto.h
include/openthread/instance.h
src/core/api/crypto_api.cpp
src/core/crypto/hkdf_sha256.cpp
src/core/crypto/hkdf_sha256.hpp
src/core/crypto/hmac_sha256.cpp
src/core/crypto/hmac_sha256.hpp
src/core/crypto/sha256.cpp
src/core/crypto/sha256.hpp
src/core/meshcop/dtls.cpp
src/core/meshcop/meshcop.cpp
src/core/thread/key_manager.hpp
src/core/utils/slaac_address.cpp
tests/unit/test_hmac_sha256.cpp

This commit adds new public type 'otCryptoSha256Hash' and its internal
mirror `Sha256::Hash` type which represent a SHA-256 hash value.

[crypto] add 'Sha256::Hash' type

---

src/core/meshcop/meshcop_tlvs.cpp

Fix typo with ChannelMasEntry (Note missing 'k') introduced in PR: 5947

[meshcop-tlv] fix typo with ChannelMasEntry (Note missing 'k') 

---

src/core/mac/mac.cpp

Performing MAC frame encryption immediately after each copy results in
copying the already-encrypted frame, rather than the original frame
before encryption.

[multi-radio] copy all TX buffers before encryption

---

src/core/mac/link_raw.cpp

This commit addresses an issue with `LinkRaw` on FTD/MTD builds. In
FTD/MTD builds, we add code to disable/enable MAC layer when link-raw
is being enabled/disabled. This ensures to avoid any conflict in
control of radio and sub-mac between `Mac` and `LinkRaw`. In RADIO
build, we directly enable/disable sub-mac (note that in FTD/MTD build
then `Mac` layer would be enable sub-mac).
---------
Background on this:
This can address some edge-case  situations: For example, on FTD build/device, link-raw is enabled while in middle of other mac operation (e.g. an ongoing active scan). Without this, such a situation can lead to radio/sub-mac being potentially controlled by two modules (`LinkRaw` and `Mac`) and potential `assert` failures due to conflicting commands (e.g., both trying to send at the …

[link-raw] disable/enable MAC layer when link-raw is enabled/disabled

---

third_party/NordicSemiconductor/drivers/radio/rsch/nrf_802154_rsch.c

This PR fixes #5826.
Thanks @hubertmis for debugging and solving this problem. The cause is that in radio scheduler, after coex precondition is approved, no action is taken to notify the core. As a result, the coex precondition is not met when doing the transmission. Now we move the code before HFCLK handling so that HFCLK handling would notify the core.
As there's no recent plan for a new bug-fix release of nRF 802.15.4 driver, let's submit this change to the repo temporarily.

[nrf528xx] fix sleep_to_tx transition problem

---

src/lib/spinel/radio_spinel_impl.hpp
tests/scripts/expect/posix-rcp-restoration.exp

If `mError` is set to error state before entering the RCP recovery, this error will be recognized as an error in the recovery process, and cause it to die, while there is actually no error.
This fixes it by clearing `mError` when starting the recovery process. Fixes <https://github.com/openthread/openthread/issues/5928>.

[spinel] fix errors in RCP recovery

---

src/core/meshcop/border_agent.cpp

Avoids the following warning:
```
/usr/sbin/ot-daemon[3059]: [WARN]-MESH-CP-: Failed to notify commissioner on ProxyRx (c/ur): DestinationAddressFiltered
```
Thanks to @gabekassel for identifying this issue.

[border-agent] remove UDP receiver on commissioner disconnect

---

.github/workflows/simulation.yml
src/cli/cli.cpp

Currently if OpenThread dies with something like `VerifyOrDie`, we can't get any logs from GitHub Actions, so issues like <https://github.com/openthread/openthread/issues/5928> are hard to diagnose. This enables full logs and uploads them when `expect` tests fail, making it easier to diagnose such errors.

[github-actions] enable full logs in expect tests

---

Android.mk
src/core/crypto/ecdsa.cpp
src/core/crypto/ecdsa.hpp
src/core/crypto/mbedtls.cpp
src/core/crypto/sha256.hpp
tests/toranj/openthread-core-toranj-config.h
tests/unit/CMakeLists.txt
tests/unit/Makefile.am
tests/unit/test_ecdsa.cpp
third_party/mbedtls/Makefile.am
third_party/mbedtls/mbedtls-config.h

This commit adds support for ECDSA using NIST P-256 curve and SHA-256
hash. `KeyPair` type is added which represents a set of public and
private keys. It provides methods for generation a new key-pair and
getting a DER format byte sequence representation of the key-pair.
This commit also adds methods to calculate ECDSA signature and verify
a signature for a hashed message. The underlying implementation uses
`mbedtls` APIs.
It also adds a unit-test `test-ecdsa` to cover behavior of the newly
added types and methods. The unit test also verifies the signature
calculation using the test vector example from RFC 6979.

[crypto] add ECDSA (P-256 curve) key-gen, signing, and verification

---

tools/harness-automation/autothreadharness/harness_case.py

When using "status = self._browser.find_element_by_class_name('title-test').text", the variable "status" will not contain "Pass" or "Failed", so, the result always fails.
After using "get_attribute('innerText')",  the variable "status" will contain "Pass" or "Failed" as expected

[harness-automation] fix the result parsed uncorrectly using Chrome 80

---

tests/scripts/expect/cli-router.exp

The next hop here is not deterministic. This changes it to expect any 4-digit hex. Fixes <https://github.com/openthread/openthread/issues/5993>.

[expect] fix CLI router tests

---

tests/unit/test_platform.cpp

This PR fixes build warning:
```txt
../../tests/unit/test_platform.cpp: In function ‘otLinkMetrics otPlatRadioGetEnhAckProbingMetrics(otInstance*, otShortAddress)’:
../../tests/unit/test_platform.cpp:694:1: warning: no return statement in function returning non-void [-Wreturn-type]
694 | }
| ^
```

[tests] add "return" for dummy test platform API

---

script/check-posix-pty
src/core/net/ip6.cpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp

This change filters out unsupported ICMP packets, Tmf and Mle udp
packets from the host.
Depends-On: https://github.com/openthread/openthread/pull/5910

[ip6] add filter for packets from host

---

src/core/net/ip6.cpp
src/core/net/udp6.cpp
tests/scripts/thread-cert/Cert_8_3_01_CommissionerPetition.py
tests/scripts/thread-cert/Cert_9_2_01_MGMTCommissionerGet.py
tests/scripts/thread-cert/Cert_9_2_02_MGMTCommissionerSet.py
tests/scripts/thread-cert/Cert_9_2_03_ActiveDatasetGet.py
tests/scripts/thread-cert/Cert_9_2_19_PendingDatasetGet.py

#5632 convert ALOC source addresses to RLOCs.
This commit revert this feature.
**Background:**
[CoAP](https://tools.ietf.org/html/rfc7252#section-5.3.2) requires that the source address of a response must match the destination addresses of the request. So, if a device sends a TMF request using ALOC as destination address, the TMF response **SHOULD** use the ALOC as source address. Otherwise, CoAP implementations (beside OpenThread) may fail to match the request and response.

[ip6] use ALOC source address

---

.github/workflows/otci.yml
tests/scripts/thread-cert/simulator.py
tools/otci/LICENSE
tools/otci/README.md
tools/otci/otci/__init__.py
tools/otci/otci/command_handlers.py
tools/otci/otci/connectors.py
tools/otci/otci/constants.py
tools/otci/otci/errors.py
tools/otci/otci/otci.py
tools/otci/otci/types.py
tools/otci/otci/utils.py
tools/otci/setup.py
tools/otci/tests/test_otci.py

This commit introduces the Proof of Concept implementation of the OpenThread Controller Interface (OTCI) which can be used to connect and manage various kinds of OT devices.
This commit also adds the tests to verify that OTCI works for both simulation and real OT devices.
```
cd tests/scripts/thread-cert/otci && python3 setup.py install --user
REAL_DEVICE=1 OT_CLI_SERIAL=/dev/ttyACM0 python3 tests/test_otci.py
REAL_DEVICE=1 OTBR_SSH=172.16.243.151 python3 tests/test_otci.py
```

[otci] add OpenThread Controller Interface library

---

script/bootstrap

It seems to be unnecessary to install these format dependencies when setting up OpenThread on a Raspbian (Mostly people don't develop or submit PR from a Raspberry pi). So by default don't install these format dependencies on Raspbian to save time.

[scripts] optionally install pretty format for Raspbian in bootstrap

---

src/core/coap/coap.cpp

To match CalculateInitialRetransmissionTimeout() implementation.

[coap] fix order of operations in TxParameters::IsValid()

---

src/lib/spinel/radio_spinel_impl.hpp

By inlining static functions defined in the header file.
Since this increases the function size of functions which use the definition, an alternative is to define these functions as function templates with unused template parameters. This ensures that functions are created only in the files where they are used. Please let me know if I should do that instead.

[build] remove unneeded-internal-declaration warning on Fuchsia

---

examples/platforms/nrf528xx/nrf52811/Makefile.am
examples/platforms/nrf528xx/nrf52833/Makefile.am
examples/platforms/nrf528xx/nrf52840/Makefile.am
examples/platforms/nrf528xx/src/radio.c
examples/platforms/nrf528xx/src/transport/transport.c

This PR enables `unused-parameter` warning for NRF driver code except for soft-device.
Currently this warning is disabled for all NRF driver code, which makes `OT_UNUSED_VARIABLE` in driver code useless. I found that we only need to suppress the warning for soft-device code because only that part includes some headers in `third_party/NordicSemiconductor` that have unused parameters. We'd better to make the rest part of driver code consistent with OpenThread code.

[nrf528xx] enable unused-parameter warning for platform code

---

src/lib/spinel/radio_spinel.hpp
src/lib/spinel/radio_spinel_impl.hpp
src/posix/platform/radio.cpp
src/posix/platform/radio_url.cpp

This commit adds new option to skip RCP API version and capability
compatibility check during initialization. The radio URL key
`skip-rcp-compatibility-check` can be used to enable this behavior.
This is only intended for situations where RCP won't be operating as a
radio (e.g., host trying to perform an RCP firmware update).
----
Resolves #6042

[radio-spinel] add option to skip RCP compatibility check during init

---

examples/platforms/efr32/src/entropy.c

When obtaining entropy data, trng_get_random checks the status for any noise, and if so, cleans its queues and keeps the entropy accumulator of mbedtls running.
In the process, TRNG might not have any new samples available, so a zero length output is valid, and we should keep running rather than exit fatally.
Resolves #6013

[efr32] fix for trng entropy API

---

src/core/crypto/ecdsa.cpp

This commit fixes the assert check on MPI encoded size. Note that
`mbedtls_mpi_write_binary()` would fill the entire given buffer
(adding zero bytes if the MPI encoded size requires less bytes than
the given buffer size).

[ecdsa] relax/fix the assert check on MPI encoded size

---

src/core/BUILD.gn
src/core/Makefile.am
src/core/backbone_router/ndproxy_table.cpp
src/core/backbone_router/ndproxy_table.hpp
src/core/common/iterator_utils.hpp
src/core/net/netif.hpp
src/core/thread/child_table.cpp
src/core/thread/child_table.hpp
src/core/thread/router_table.cpp
src/core/thread/router_table.hpp

Many Iterators have the same pattern in our code: they have `++`, deference, equal operators, `IsDone` method and hold a pointer to the an object. This PR extracts the common pattern into a template class `ItemPtrIterator` and use it as a base class for those similar Iterator classes.

[utils] implement a item-pointer iterator template for many iterators

---

src/core/thread/network_data_leader.cpp

This commit adds a check in `GetBackboneRouterPrimary()` to verify
that the server sub-TLV data length is larger than an expected minimum
before casting it to `BackboneRouterServerData` and parsing/reading the
info.

[network-data] check serverTlv data length before parsing

---

src/core/net/dns_headers.cpp
src/core/net/dns_headers.hpp

This commit fixes some typos in the documentation/comments and
renames some of methods getting number of RRs in a DNS header
section (`Get{Section}RecordCount` <- `Get{Section}RecordsCount`).
--------
This is small follow up on #6048 addressing some comments by @librasungirl after 
the PR was merged

[dns-headers] fix typos, rename some methods

---

script/bootstrap

I made a mistake on this - the if-else branches in `install_packages` are not for command line arguments. `pretty-format` is not a `src`.

[bootstrap] fix pretty format install

---

.github/workflows/simulation-1.2.yml
.github/workflows/simulation.yml
script/test

Currently when a test fails, the core dump uploading action would be executed. (Even when there's no core dump, the binaries and so libs would be uploaded, which is a waste.)
This PR uses env variables of github actions to only execute the uploading action when crash actually happens.

[github-actions] upload core dump only when crash happens

---

tests/scripts/thread-cert/node.py

The `_expect_command_output(self, ...)` doesn't match exactly one line, it may returns a line in several splits. This commit fixes this issue.

[tests] fix expecting command output

---

src/core/common/message.cpp
src/core/common/message.hpp
tests/unit/test_message.cpp

This commit adds new helper `Compare` methods in `Message` class to
compare the bytes from the message (at a given offset) with a byte
array or bytes from a (template) object or bytes read from another
message.
This commit also updates the message unit test to cover the behavior
of the newly added methods.
------
Background on this PR: The new methods would be helpful in parsing messages
(mainly DNS/SRP messages, e.g. matching names and/or resource records, etc).

[message] new helper methods to compare bytes in a message

---

src/core/net/dns_client.cpp
src/core/net/dns_headers.hpp

This commit removes `QuestionAaaa` class. 
Since the format of each question type is exactly same, it seems unnecessary to define a dozen of `QuestionXxx` classes for different resource record types just with different `kType`.

[dns-client] remove QuestionAaaa class

---

script/bootstrap

Added fix to extract archive to /opt rather than current directory which is /tmp
Fixes #6080

[bootstrap] fix gcc-arm-none-eabi install

---

src/core/thread/mesh_forwarder.hpp

This method doesn't have definition and is not used anywhere.

[mesh-forwarder] remove unused UpdateIndirectMessages() declaration

---

src/posix/platform/openthread-core-posix-config.h

POSIX platform is generally less resource constrained.
This commit tune several OpenThread core configurations to better fit the POSIX platform.

[posix] tune core config for posix

---

src/core/utils/otns.cpp

This commit fixes an compile issue in otns.cpp when log region `CORE` is enabled.

[otns] fix compile issue when log region CORE is enabled

---

script/test

This commit allows specifying multiple arguments for `script/test cert path/to/script.py`.
This is useful for running a selected test case when the test script contains multiple test cases.

[script] script/test cert with multiple arguments

---

.github/workflows/simulation-1.2.yml
include/openthread/border_router.h
include/openthread/instance.h
include/openthread/platform/infra_if.h
src/cli/README.md
src/cli/cli.cpp
src/cli/cli.hpp
src/core/api/border_router_api.cpp
src/core/border_router/router_advertisement.cpp
src/core/border_router/router_advertisement.hpp
src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp
src/core/thread/network_data.hpp
src/posix/platform/infra_if.cpp
tests/scripts/thread-cert/border_routing/test_multi_border_routers.py
tests/scripts/thread-cert/border_routing/test_multi_thread_networks.py
tests/scripts/thread-cert/border_routing/test_single_border_router.py
tests/scripts/thread-cert/node.py

This PR includes the enhancement that
1. adds non-default external route for on-link prefixes.
2. add external route for OMR prefixes advertised by BRs in other Thread Networks.
3. a new API to disable/enable the Border Routing manager at run time. CLI commands are added for testing.
4. a new platform API to get the link-local address of the infra interface so that we can filter out the ICMPv6 packets from myself by the Border Routing Manager rather than the platform implementation.
enhancements that adds random delay before changing the prefixes/routes, multiple prefixes for fault tolerance and duplicate OMR prefixes detection will be added in future PRs.

[border-router] add external route for on-link prefix and external OMR prefixes

---

.github/workflows/simulation-1.2.yml
script/test

Currently when we build 1.2 binaries using `script/test`, we build it twice (one only with Low Power features, one only with Backbone Router feature).
As I remember,we separate it because when we implement it, we do the work individually. I think now it's not necessary to separate it anymore. We can always build one version and test all 1.2 features with it.

[scripts] add option to not build bbr when building 1.2

---

src/posix/platform/infra_if.cpp

This PR includes two small enhancements to the posix infra if module:
1. simplify logging of socket errors since the `VerifyOrDie` macro already prints the line number and `strerror()`.
2. suppress "drop ICMPv6 message" debug logs when there is no input data to be read on the socket.

[posix] logging enhancements to infra if

---

src/posix/platform/infra_if.cpp

This is for ensuring sending ICMP6 packets on only the specified infrastructure interface.

[posix] bind infra IF socket to specific interface

---

script/bootstrap

`mdv` is only used to post size report and can not format markdown. Update the warning string to avoid confusion.

[script] fix warning string for mdv

---

tests/scripts/thread-cert/node.py

This commit allows node.py to ignore log lines from node CLI output. 
Only if `_expect_command_output` is used.

[thread-cert] ignore CLI log lines

---

Android.mk

When compiling ot-cli and ot-ncp, the Android.mk will compile
the function `property_get` in `src/core/api/instance_api.cpp`.
The function `property_get` is provided by the library `libcutils`.
GitHub Action uses Android NDK to compile Android.mk, Android NDK
only allows adding the shared library `libcutils` for the library
`ot-core`. However, Android requires to add the shared library
`libutils` for the binary `ot-cli` and `ot-ncp`. Therefore, this PR
uses the macro `ANDROID_NDK` to distinguish these two cases.

[android] add library `libcutils` for compiling ot-cli and ot-ncp

---

tests/CMakeLists.txt

Following #5622, build unit tests only when FTD is enabled.
With #5622, we can build MTD only. However the unit tests would still be built in this case and it links the `ftd` lib, which causes a link error. This PR solves this problem.

[build] only build unit tests when FTD is enabled

---

src/core/thread/mle_types.hpp

The #5560 removed a need of setting the Secure Request Bit in the Mode TLV and supposed to set this bit to 1 always on transmission.
The reserved bit is set when `DeviceMode::Set()` method is invoked. If application uses MTD library, and does not call `otThreadSetLinkMode()`, stack does not set the reserve bit at all - since it doesn't call above method (even from [constructor](https://github.com/openthread/openthread/blob/master/src/core/thread/mle_types.hpp#L348)).
This PR ensures that reserved bit is set.
Note that i found this problem when End Device continously was deattaching from the parent after Child ID Timeout, and retried attachment procedure. The issue was that End Device [dropped](https://github.com/openthread/openthread/blob/master/src/core/thread/mle.cpp#L3679) `Child …

[mle] ensure reserved bit in Mode TLV is set

---

tools/otci/otci/otci.py
tools/otci/otci/types.py
tools/otci/tests/test_otci.py

This commit adds link information to the router table (i.e. get_router_table()).
**Verified by @jpkavita that this feature works.**

[otci] get router link information

---

src/core/net/dns_client.cpp
src/core/net/dns_headers.cpp
src/core/net/dns_headers.hpp
src/core/net/srp_server.cpp
src/core/net/srp_server.hpp
tests/unit/test_dns.cpp

This commit contains two changes in `Dns::Name` class. When reading or
parsing names/labels from a `Message`, we require that the message
offset (i.e., `aMessage.GetOffset()`) to be set by the caller to point
to the start of the DNS header in the message. This is then used to
decode compressed DNS names. This change helps simplify the code and
removes the need to pass `aHeaderOffset` as a separate parameter. The
second change is to the `ParseName()` implementation which now always
goes through and parses the entire compressed name before returning.
This ensures that we correctly detect invalid compressed names when
parsing the name in a message.
------
This is replacing PR https://github.com/openthread/openthread/pull/6087. 
I will inlcude this commit in other DNS-SD related PRs. My …

[dns-name] require message offset to point to DNS header

---

tests/scripts/thread-cert/simulator.py

This commit allows virtual time simulator to `go` (simulate) for less than 1s.

[scripts] allow virtual time simulator to `go` less than 1 second

---

src/core/net/ip6.cpp
tests/scripts/thread-cert/border_routing/test_plat_udp_accessiblity.py

This commit makes sure that UDP servers are accessible via all IPv6 addresses when PLAT_UDP is on.
We still need to pass the messages with ALOC/RLOC destinations to the tun interface when PLAT_UDP is used. Otherwise, UDP servers can not receive any message when PLAT_UDP is enabled.
This PR deprecates #6057

[udp] fix UDP not accessible via RLOC/ALOC with PLAT_UDP

---

src/core/net/dns_headers.cpp
src/core/net/dns_headers.hpp
tests/unit/test_dns.cpp

This commit allows `Dns::Name` instances to be created which can be
empty or specified from a string (a dot '.' separated sequence of labels) or
from a message at a given offset (i.e., name is already encoded in a
message). `CompareName` and `FindRecord()` helper methods are updated
to allow the new `Dns::Name` type to be used when comparing/searching
for a name.
--------
_Background for this_: During DNS-SD client implementation I noticed this model of having 
a common representation of a `Dns::Name` that "may be a string" or maybe "already encoded
in a message" can be very useful. I expect it to help simplify support for handling of `CNAME`
records in a received response message.

[dns-name] allow 'Dns::Name' to be given as string or from message

---

include/openthread/dns.h
include/openthread/instance.h
include/openthread/srp_client.h
include/openthread/srp_server.h
src/cli/cli_srp_client.cpp
src/cli/cli_srp_client.hpp
src/cli/cli_srp_server.cpp
src/cli/cli_srp_server.hpp
src/core/api/srp_server_api.cpp
src/core/net/dns_headers.cpp
src/core/net/dns_headers.hpp
src/core/net/srp_client.cpp
src/core/net/srp_client.hpp
src/core/net/srp_server.cpp
src/core/net/srp_server.hpp
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/test_srp_register_single_service.py

This PR returns parsed TXT entries for service from the SRP server, it enables prettier CLI output and
easier Advertising Proxy processing.  We moved the `otSrpTxtEntry` to `include/openthread/dns.h`
because this structure can ( and will) also be used by DNS-SD client. We also added one more `mKeyLength`
field in `otDnsTxtEntry` for saving length of the TXT key so that we can iterate over the encoded TXT
data without dynamically allocating memory for each entry.

[srp] get parsed TXT entry from SRP server

---

src/core/net/dns_headers.cpp
src/core/net/dns_headers.hpp
src/core/net/srp_server.cpp
src/core/net/srp_server.hpp
tests/unit/test_dns.cpp

This PR includes two small commits:
The first commit adds a new method `Dns::Name::IsSubDomainOf` that matches a DNS name with given domain.
This is useful for SRP and DNS-SD server to verify if a RR is in our authorized domain.
The second commit adds domain checks for names in a SRP update to the SRP server.

[dns] match DNS name with specific domain

---

src/posix/platform/system.cpp

This is a quick fix that allows heap usage in constructors.

[posix] set up heap before creating OT instance

---

tools/otci/otci/otci.py
tools/otci/tests/test_otci.py

This commit changes these methods to return corresponding entries from Thread Network Data rather than local network data.
- get_prefixes
- get_routes
- get_services
Added local version to retrieve entries from local network data.
- get_local_prefixes
- get_local_routes

[otci] get prefixes/routes/services in thread network data

---

src/posix/platform/openthread-posix-config.h
src/posix/platform/trel_udp6.cpp
tests/toranj/openthread-core-toranj-config-posix.h

This commit updates the trel platform posix implementation to use
linux netlink socket (instead of `ioctl()` command) to add/remove
unicast (link-local) address on the netif used by trel . When netlink
socket is used "Duplicate Address Detection" (DAD) is explicitly
disabled when the address is added. This helps speed up the start time
of OpenThread stack when using TREL.
The `OPENTHREAD_CONFIG_POSIX_TREL_USE_NETLINK_SOCKET` option
can be used to enable/disable the use of netlink socket by trel
platform layer implementation. By default it is enabled on all
linux-based platforms (determined by `__linux__` macro being
defined).

[trel-posix] disable DAD when adding unicast address on trel netif

---

src/cli/cli.cpp
src/cli/cli.hpp

This commit changes the order of member variables in `Cli` class
ensuring `mInstance` is initialized before other member variables.
This then allows the `mInstance` to be safely used from the
constructor of other `Cli` sub-types.

[cli] ensure to init 'mInstance' before other member variables

---

include/openthread/instance.h
include/openthread/srp_client.h
src/cli/README_SRP_CLIENT.md
src/cli/cli_srp_client.cpp
src/cli/cli_srp_client.hpp
src/core/api/srp_client_api.cpp
src/core/net/srp_client.cpp
src/core/net/srp_client.hpp
src/ncp/ncp_base.cpp
src/ncp/ncp_base_mtd.cpp

This commit adds new methods/APIs in `Srp::Client` class:
`GetServerAddress()` to get the SRP server's socket address that is
being used by the client, `IsRunning()` to check whether the SRP
client is started and running or not, and `SetCallback()` to allow
user to set the callback at any point (before/after call to
`Start()`). It also adds a new `srp client` CLI sub-command to get 
the server address and/or its port number.

[srp-client] new methods to get server address, set callback

---

Android.bp
Android.mk
src/core/BUILD.gn
src/core/CMakeLists.txt
src/core/Makefile.am
src/core/net/socket.cpp
src/core/net/socket.hpp
src/core/net/srp_client.cpp

This commit adds `SockAddr::ToString()` which coverts a socket
address to a string formatted as `"[<ipv6 address>]:<port number>"`.

[socket] add 'SockAddr::ToString()'

---

tests/scripts/thread-cert/test_srp_name_conflicts.py

The SRP service may in different intermediate states when rejected by the server and we only need to make sure that the state is not `Registered`. This fixes issue https://github.com/openthread/openthread/issues/6139.

[tests] fix test_srp_name_confclicts.py

---

examples/apps/cli/main.c
examples/apps/ncp/main.c
examples/platforms/efr32/src/system.c
include/openthread/instance.h
include/openthread/platform/memory.h
src/core/api/heap_api.cpp
src/core/common/instance.cpp
src/core/common/instance.hpp
src/core/common/message.cpp
src/core/crypto/mbedtls.cpp
src/core/meshcop/border_agent.cpp
src/core/net/srp_server.cpp
src/core/net/srp_server.hpp
src/core/utils/heap.cpp
src/core/utils/heap.hpp
src/posix/platform/CMakeLists.txt
src/posix/platform/Makefile.am
src/posix/platform/memory.cpp
src/posix/platform/system.cpp
tests/unit/test_heap.cpp
tests/unit/test_platform.cpp
third_party/mbedtls/mbedtls-config.h

The `Instance::HeapCAlloc()` method can not be used in constructors when `EXTERNAL_HEAP`
is enabled but works well when internal heap is used. This is because the external heap methods
are set by public `otHeapSetCAllocFree` API after the OT instance is constructed.
This PR fixes this issue by having `Instance::HeapCAlloc()` using `otPlatCAlloc` when `EXTERNAL_HEAP`
is enabled. It also fixes build issues when `MULTIPLE_INSTANCE` and `EXTERNAL_HEAP` are used together.
Replaces #6121.

[heap] fix external heap configuration

---

src/lib/url/url.cpp

This commit fixing returning empty value. The address of `""` is fixed
and cannot be used as `aLastValue` of `Url::GetValue()`.

[url] fix returning empty value

---

script/test

This PR makes the cmake output directory configurable in `script/test`. By default the build directory is still `./build`.

[script] support to specify cmake build directory in script/test

---

include/openthread/instance.h
include/openthread/platform/settings.h
src/core/common/settings.cpp
src/core/common/settings.hpp
src/lib/spinel/radio_spinel_impl.hpp
src/posix/platform/include/openthread/platform/secure_settings.h
src/posix/platform/openthread-posix-config.h
src/posix/platform/settings.cpp

All the settings are written into a local file on the posix platform. It is easy for
others to get the sensitive infomation, such as master key, from the local file.
This commit includes the following enhancement:
<1> Add API `otPlatSettingsSetCriticalKeys()` to tell the platform which keys
should be stored in the secure area.
<2> Expose all settings keys to the header file `settings.h`, which allows
the platform determines which settings should be processed specially.
<3> Add new posix APIs `otPlatSecureSettingsXxx` to posix platform to allow
the vendor to implement the functions to store the critical settings to
the secure area.

[settings] add APIs to securely store critical settings

---

Android.mk
etc/cmake/options.cmake
etc/gn/openthread.gni
examples/Makefile-simulation
examples/README.md
examples/common-switches.mk
script/check-size
script/test
src/core/BUILD.gn
src/core/CMakeLists.txt
src/core/Makefile.am
src/core/common/instance.hpp
src/core/config/dnssd_server.h
src/core/net/dns_headers.cpp
src/core/net/dns_headers.hpp
src/core/net/dnssd_server.cpp
src/core/net/dnssd_server.hpp
src/core/net/srp_server.cpp
src/core/net/srp_server.hpp
src/core/openthread-core-config.h
src/core/thread/thread_netif.cpp
src/core/thread/thread_netif.hpp
src/posix/Makefile-posix
tests/scripts/thread-cert/Makefile.am
tests/scripts/thread-cert/border_routing/test_dnssd_server.py
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/test_dnssd.py

This commit implements the DNS-SD server:

[dns-sd] DNS-SD server implementation

---

src/core/thread/mle_router.cpp

Issue:
Information regarding a neighbor's Thread version is lost.
Context:
This problem can be observed during playing with Link Metrics - few methods check whenever chosen neighbor supports Thread 1.2. This information is preserved when a child is promoted to the router role, but after the reset and Link Request - Link Accept sequence it is not stored in the neighbor table.

[mle] set router's Thread version in Link Accept handler

---

include/openthread/coap.h
include/openthread/instance.h

[coap] remove use of `nullptr` in coap.h

---

CMakeLists.txt
etc/cmake/print.cmake

The echo command of the host system may have slight variations between
shell built-in echo and the echo command provided by the OS.
Especially the Windows OS echo command is different from practical any
other echo command.
This means that the currently used `COMMAND echo -e "<text>"` does not
work universally.
This commit introduces `etc/cmake/print.cmake` which allow to print a
CMake list where each item is printed on a new line, to get the desired
behavior on the `print-ot-config` target.
Using `cmake -E echo <text>` ensures identical behaviour across
different systems.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

[cmake] using cmake -E echo instead of shell echo command

---

include/openthread/dns_client.h
include/openthread/instance.h
include/openthread/srp_client.h
src/core/net/dns_client.hpp

This commit updates the doxgen documentation of some of the SRP/DNS
client definitions to use list format.
----
The intention is to improve readability of the OT API docs,
e.g. https://openthread.io/reference/group/api-srp#otsrpclientcallback

[dns] update DNS/SRP client documentation to use doxygen lists

---

examples/platforms/efr32/sleepy-demo/sleepy-demo-mtd/main.c

This changes the sleepy-demo-mtd app's startup behavior. Prior to the change, the MTD would go to sleep immediately. Instead, the MTD will not sleep until the button is pressed

[efr32] change sleepy-demo-mtd to start awake

---

src/core/net/ip6.cpp

So that `mReassemblyList.Dequeue()` is always valid on any error.

[ip6] enqueue reassembly buffer immediately

---

src/posix/console_cli.cpp

The default screen size might be too small for CLI command input/output. 
This commit configures the screen cols to according to CLI configs.

[posix] set readline screen cols

---

src/cli/README.md
src/cli/cli.cpp
src/cli/cli.hpp

This commit adds new CLI command `multiradio` to get the list of
supported radio types by device and `multiradio neighbor` sub-command
to get the radio info (supported radios and the their preference) for
specific neighbor or for all neighbors.

[cli] add CLI commands for multi-radio feature

---

src/core/net/dnssd_server.cpp
src/core/net/dnssd_server.hpp
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/test_dnssd.py

This commit enhances the DNS-SD server to handle multiple questions. 
Specifically for DNS service resolving query with SRV+TXT questions, this commit would reply with SRV+TXT+AAAA RRs, so that the service instance can be fully resolved with one query. 
- This commit  enhances `NameCompressInfo` so that question names can be compressed together with RR names.
- **Full compression** is limited to only one instance / service / host name.
- For any RR type in the question, this commit will exclude it in additional RRs. For example, if the query contains a AAAA question, the response won't include  any additional AAAA RR, but will only have AAAA answer(s). The purpose is to avoid duplicate RRs in answer section and additional section. 
Depends on #6183 to fix a POSIX console bug.

[dns-server] handle multiple questions

---

include/openthread/instance.h
include/openthread/srp_client.h
src/cli/README_SRP.md
src/cli/README_SRP_CLIENT.md
src/cli/cli_srp_client.cpp
src/cli/cli_srp_client.hpp
src/core/api/srp_client_api.cpp
src/core/config/srp_client.h
src/core/net/srp_client.cpp
src/core/net/srp_client.hpp
tests/scripts/thread-cert/Makefile.am
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/test_srp_auto_start_mode.py

This commit adds auto-start SRP client feature. Config option
`OPENTHREAD_CONFIG_SRP_CLIENT_AUTO_START_API_ENABLE` adds support for
this feature in SRP client allowing auto-start mode to be enabled or
disabled. When enabled, the SRP client will monitor the Thread Network
Data for SRP Server Service entries and automatically start and stop
the client when an SRP server is detected. If multiple SRP servers are
found, a random one will be selected. If the selected SRP server is no
longer detected (not longer present in the Thread Network Data), the
SRP client will be stopped and then it may switch to another SRP
server (if available).
This commit also adds support for the new feature in CLI and adds a
new test `test_srp_auto_start_mode.py` covering the basic behavior of
this feature.
----- …

[srp-client] adding auto-start feature

---

script/check-size

This PR updates nrf building in size check to use cmake with the latest cmake support. The PR also refines the shell implementation.

[github-actions] use cmake to build nrf in size action

---

tests/scripts/thread-cert/simulator.py
tests/scripts/thread-cert/sniffer_transport.py

UDP buffer size was increased by #6006 to 10M so as to avoid potential UDP packet loss. However the buffer size is too large to run `thread-cert` tests on macOS.
This commit reduces the UDP buffer size to 2M.

[thread-cert] reduce simulator UDP buffer size

---

src/core/net/dns_types.hpp

This commit fixes and simplifies the `OptRecord` implementation. The
OPT RR re-purposes the existing TTL field (which is a `uint32_t`) and
uses it for Extended Response Code (`uint8_t`), Version (`uint8_t`),
and flags. The new implementation treats the `mTtl` as a byte array
and directly reads/writes bytes at different indexes corresponding to
different re-purposed data fields. This ensures that the fields are
encoded correctly independent of the endianness of the platform.

[dns] fix and simplify OPT record reuse of TTL field

---

src/lib/spinel/radio_spinel_impl.hpp

The otPlatSettings api isn't necessarily supported on every platform.
Replace with ot::SettingsDriver which supports both the settings and the
flash platform api.

[spinel] replace otPlatSettings with SettingsDriver

---

include/openthread/instance.h
include/openthread/netdiag.h
src/cli/cli.cpp
src/core/api/netdiag_api.cpp
src/core/thread/network_diagnostic.cpp
src/core/thread/network_diagnostic.hpp

This PR sets the DIAG_GET response callback every time the `otThreadSendDiagnosticGet` is called. This is because the callback may be changed to other modules (e,g. `OTBR_REST`, `OTBR_UBUS`).
Addresses issue: https://github.com/openthread/ot-br-posix/issues/689.
Depends-On: openthread/ot-br-posix#707

[netdiag] fix setting DIAG_GET response callback

---

src/lib/spinel/spinel.c

spinel.c provides functions to convert spinel values to printable
strings. These functions are written using huge switch case statements.
This patch replaces these statements with simple loops over arrays
containing the strings.
Thus, the new code takes 3 time less code than the previous. In add, the
value and the string are no more repeated so the new is less error
prone.
Note: I have used the following commands for the conversion:
sed -nre 's/case SPINEL_CMD_(.*):/SPINEL_COMMAND_CSTR(\1),/p' spinel.c
sed -nre 's/case SPINEL_PROP_(.*):/SPINEL_PROP_CSTR(\1),/p' spinel.c
...

[spinel] simplify functions spinel_*_to_cstr()

---

src/core/config/mle.h
src/core/thread/mle.cpp
src/core/thread/mle.hpp

This commit adds a new behavior related to MLE attach backoff feature.
It adds a configurable delay wait interval before resetting the attach
backoff interval to its minimum value upon a successful attach.
`OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_DELAY_TO_RESET_BACKOFF_INTERVAL`
specifies the delay interval.
If it is set to zero then the device resets its backoff attach
interval immediately after a successful attach. With a non-zero value,
if after a successful attach, the device happens to detach within the
delay interval, the reattach process resumes with the previous backoff
interval (as if the attach did not happen).
This behavior is helpful in the situation where a battery-powered
device has poor link quality to its parent and therefore attaches and
detaches frequently from its parent. …

[mle] add wait time for resetting attach backoff interval after attach

---

include/openthread/border_router.h
include/openthread/instance.h
include/openthread/platform/infra_if.h
src/core/api/border_router_api.cpp
src/core/border_router/infra_if_platform.cpp
src/core/border_router/routing_manager.cpp
src/core/border_router/routing_manager.hpp
src/posix/platform/infra_if.cpp
src/posix/platform/platform-posix.h
src/posix/platform/system.cpp
tests/scripts/thread-cert/border_router/test_single_border_router.py
tests/scripts/thread-cert/node.py

This commit includes below changes:
1. handles dynamic infrastructure interface status changes.
The Routing Manager will be started if the infra interface status turns
to be `RUNNING` and a valid link-local address is present. Otherwise,
the Routing Manager will be stopped.
2.  changes the default  status of the Routing Manager from `enabled`
to disabled and it is initially enabled for the posix platform.
3. the posix implementation now doesn't require the presence of the
link-local address at initialization stage. In this case, the Routing Manager
will not be started before a link-local address is added to the infra interface.
TODO:

[posix] handle dynamic infra interface status

---

src/core/thread/mle.cpp

This commit changes `ToString()` methods in MLE module which convert
from a given `enum` value to a string to use string array tables. It
also adds `statci_assert` checks to verify the values of `enum`
maps correctly to the array indexes.

[mle] update 'ToString()' methods in MLE to use string array

---

src/core/thread/indirect_sender.cpp

This commit fixes an issue with removal of supervision message
for child when another message is queued for the same child.
This fixes an issue added by PR #5638 (which itself addresses
an issue that if the supervision message was removed while MAC
was busy sending the message, the MAC layer would not be
notified of the removal).
----
Should address Issue https://github.com/openthread/openthread/issues/6211

[indirect-sender] free and dequeue the supervision message when removed

---

src/core/thread/indirect_sender.cpp
src/core/thread/mesh_forwarder.cpp
src/core/thread/mesh_forwarder.hpp
src/core/thread/mesh_forwarder_ftd.cpp

This commit adds a helper method `RemoveMessageIfNoPendingTx()` in
`MeshForwarder` which removes (dequeues from `mSendQueue` and frees
it) if there is no pending direct or indirect transmission.
This commit also changes `UpdateSendMessage()` to exit early when
there are remaining fragments of the message to be sent.

[mesh-forwarder] add helper 'RemoveMessageIfNoPendingTx()'

---

src/core/api/srp_server_api.cpp
src/core/net/srp_server.cpp
src/core/net/srp_server.hpp

This PR renames `*Advertising*` to `*ServiceUpdate*` to keep consistent with public APIs.
For example, change `HandleAdveretisingResult` to `HandleServiceUpdateResult`.

[srp] rename Advertising to ServiceUpdate

---

.github/workflows/makefile-check.yml
include/Makefile.am
script/check-core-makefiles
script/update-makefiles.py
src/core/Makefile.am

This commit adds `update-makefiles.py` script which helps update
different make/build files supported by OpenThread project including
`CMakeList.txt`, `BUILD.gn`, `Android.mk`, `Andriod.bp`, and
`Makefile.am` based on the source (`cpp`, `hpp`, and `h`) files in
`./src/core` and `./include/openthread` folders. This script is
intended to make it easier for developer when adding/removing/renaming
source files within OT core to help update all the make/build files.
This commit also updates `Makefile.am` ensuring the lists are sorted
alphabetically and adding some missing file (this is generated by 
running the script).

[script] adding 'update-makefiles.py' script

---

tests/scripts/thread-cert/border_router/test_plat_udp_accessiblity.py
tests/scripts/thread-cert/node.py

DHCP6 client (with PLAT_UDP) failed to process Reply after reset.
This commit fixes this bug and adds a test to verify.
Depends-On: openthread/ot-br-posix#649

[tests] add test to verify DHCP6 client works after reset

---

include/openthread/instance.h
include/openthread/message.h
include/openthread/platform/messagepool.h
src/core/common/message.hpp

This commit defines `otMessage` to be an opaque public `struct`. This
change ensures users of OpenThread APIs can only get `otMessage`
instances through OpenThread public APIs and callbacks. It also hides
the `mNext` field which is not intended for use/access by OT API users
(OT users may assume `mNext` is pointing to the next message when the
message is placed in an `otMessageQueue` which is not correct since
`mNext` is used to chain the fixed-size `Buffer` instances of the same
`Message` instance).
This commit adds `otMessageBuffer` in `platform/messagepool.h` which
is then used when the platform is configured to manage the buffer pool.
The `otMessageBuffer` struct defines `mNext` to ensure the returned
`otMessageBuffer` instances from platform layer are aligned correctly
in memory …

[message] use opaque 'otMessage' and add 'otMessageBuffer'

---

tests/scripts/thread-cert/border_router/test_single_border_router.py

This commit tests if a host is still reachable after leaving and rejoining the infrastructure network. This makes sure that the routing manager handles router solicitations.

[border-router] test host leaves and rejoins

---

src/core/BUILD.gn
src/core/Makefile.am
src/core/config/dtls.h
src/core/meshcop/dtls.cpp

On systems where OpenThread share mbedtls configuration with HTTPS and
other TLS based protocols, the TLS max content length can be way larger
than what OpenThread requires. Add an OpenThread config macro to reduce stack
consumption under such circumstance.

[dtls] make the max dtls buffer length configurable

---

src/core/mac/mac.cpp

Name is updated here to specified, latest name "DefaultDomain".
Some additional info:
Note that for non-CCM Thread Devices the domain name is not even available, so the code to "get" a domain name should in fact only be available for CCM Thread Devices. (They take it out of their LDevID certificate.) The "set" Domain Name should not be possible for that CCM Thread Device.
In Border Routers that are non-CCM, there should be code to both get and set the Domain Name but I would expect that to be in the ot-br-posix repo instead! 
Removing this code from 1.2 devices could save some bytes; I could create an issue for this. The "get" function could be kept in preparation for CCM devices.

[mac] fix default Thread Domain name per v1.2.1-draft4 spec

---

etc/cmake/options.cmake
examples/README.md
examples/common-switches.mk

This commit adds `OT_TREL` as a CMake option and `TREL` as an autoconf
switch option to enable support for TREL radio link for Thread over
Infrastructure feature.

[trel] add 'OT_TREL' CMake option & 'TREL' autoconf switch

---

src/lib/spinel/spinel.c

This function was defined without any declaration before it, causing build error when compiled with `-Werror=missing-prototypes`.

[spinel] fix missing prototype warning

---

tests/toranj/wpan.py

This commit relaxes the parsing of on-mesh prefix list `wpanctl`
output in toranj `wpan.py` allowing extra chars to be present between
"pref:" and "prio:".
---
Background:
This is related to https://github.com/openthread/wpantund/pull/482 to allow this PR to pass the CI tests.

[tests] allow extra chars in prefix list 'wpanctl' output in toranj

---

src/core/meshcop/dtls.cpp
src/core/meshcop/dtls.hpp

When using newer versions of mbed TLS, two issues appear when using `OPENTHREAD_ECDSA`:
- An empty list of configuration hashes is treated as a configuration error: DTLS fails.
https://github.com/ARMmbed/mbedtls/commit/e131bfec29565946cf1354449cc75b0fbe87378e
- Identifiers with double underscore are not used anymore: signature hashes configuration is not included.
https://github.com/ARMmbed/mbedtls/commit/eccd88871767e2fba5f3a079cfdfcb77c376cf20
This commit addresses both issues.

[dtls] fix ECDSA configuration for newer mbed TLS versions

---

src/core/net/dhcp6_client.cpp
src/posix/platform/infra_if.cpp
src/posix/platform/multicast_routing.cpp
tests/scripts/thread-cert/border_router/test_plat_udp_accessiblity.py

This commit fixes #6264 
I think there sockets in other modules that need to add `CLOSE_EXEC` flag too:
- TREL over UDP6
- ND Proxy
These can be addressed in future PRs.

[posix] fix socket issues

---

src/core/config/mac.h

As specified by Thread 1.2.1-draft4.

[mac] increase macMaxFrameRetries to 15

---

tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/requirements.txt

This PR addresses https://github.com/openthread/openthread/issues/6271. The cause of https://github.com/openthread/openthread/issues/6271 is that [zeroconf](https://pypi.org/project/zeroconf/) is not able ot discover the services after updating the host adress. zeroconf was working but maybe there are updates to the GitHub Action containers and it fails now.
We fixed this issue by replacing `zeroconf` with `dns-sd`.

[tests] fix advertising proxy tests

---

src/core/net/srp_server.cpp
src/core/net/srp_server.hpp
tests/scripts/thread-cert/border_router/test_advertising_proxy.py
tests/scripts/thread-cert/node.py

There is an issue that the SRP host or service are not deregistered by the `Advertising Proxy`
when the host or service is expired. This is because we didn't notifies the `Advertising Proxy` of
the host/service expiration. This PR fixes this issue and adds tests for it.
Depends-On: openthread/ot-br-posix#731

[srp-server] notify advertising proxy of host/service expiration

---

src/core/border_router/routing_manager.cpp

Per section 6.3 of RFC 4861:
> a host SHOULD send at least one solicitation in the case where an
advertisement is received prior to having sent a solicitation. Responses
to solicited advertisements may contain more information than unsolicited
advertisements.
In the Thread BR case, there seems no difference between solicited and unsolicited
RA. But consider that there are multiple BRs on the infra link, we may not learn
RIOs of other BRs if the router discovery process is stopped immediately
before sending any RS messages because of receiving an unsolicited RA.
This change ensures that at least one RS message will sent once started
the router discovery process.

[border-router] send at least one router solicitation

---

examples/platforms/nrf528xx/src/radio.c

Fill a CSL Phase IE with a value for the CSL transmitter to aim at the center of the receive window, instead of aiming at the beginning.
Find attached two test captures performed with two nRF52840 DKs. CSL is configured with 500 ms period and 60 s timeout. Pings are sent by the parent every 50 s. We can observe how the phase correction provides much better stability to the CSL communication.
[pcaps.zip](https://github.com/openthread/openthread/files/6148186/pcaps.zip)

[nrf528xx] improve CSL phase calculation

---

src/ncp/ncp_base.cpp

For the case when otInstanceReset returns during pseudo reset action
setting here SPINEL_STATUS_RESET_SOFTWARE is useless as line below
the current sNcpInstance is cleared. The new status never gets
a chance to be transmitted to the host.

[ncp] remove unused code

---

script/check-size

This commit enhances the size check by printing size diff symbol by symbol, which can help us better analyze size changes.

[test] print size diff symbol by symbol

---

src/cli/cli.cpp
src/core/backbone_router/bbr_manager.cpp
src/core/thread/mlr_manager.cpp
src/core/thread/mlr_manager.hpp
src/core/thread/thread_tlvs.hpp
src/ncp/ncp_base_mtd.cpp

This commit renames some of the definitions in `thread_tlvs.hpp`
to follow the camel-case naming style.

[thread-tlvs] rename to follow style

---

src/core/coap/coap.cpp
src/core/meshcop/dtls.cpp
src/core/net/dnssd_server.cpp
src/core/net/srp_server.cpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp

Bind to Thread network by default so that UDP sockets in CLI can send multicast packets through Thread network interface.

[udp] bind to Thread interface by default

---

src/core/common/trickle_timer.cpp
src/core/common/trickle_timer.hpp
src/core/net/dhcp6_client.cpp
src/core/net/dhcp6_client.hpp
src/core/thread/mle.cpp
src/core/thread/mle_router.cpp
src/core/thread/mle_router.hpp

This commit simplifies and enhances the `TrickleTimer` class. It adds
support for suppression behavior and removes unused `Mode` and unused
end of interval callback.

[timer] simplify 'TrickleTimer'

---

src/core/border_router/routing_manager.cpp

This commit includes a small enhancement that makes sure the routing manager is currently running
before evaluating the routing policy. This can help eliminating the misleading log information in `StartRoutingPolicyEvaluationDelay`:
```c++
void RoutingManager::StartRoutingPolicyEvaluationDelay(void)
{
OT_ASSERT(mIsRunning);
uint32_t randomDelay;
static_assert(kMaxRoutingPolicyDelay > 0, "invalid maximum routing policy evaluation delay");
randomDelay = Random::NonCrypto::GetUint32InRange(0, Time::SecToMsec(kMaxRoutingPolicyDelay));
otLogInfoBr("start evaluating routing policy, scheduled in %u milliseconds", randomDelay);
mRoutingPolicyTimer.Start(randomDelay);
}
```

[border-router] more strict state check before evaluating routing policy

---

src/core/config/srp_server.h
src/core/net/srp_server.cpp
src/core/net/srp_server.hpp
tests/scripts/thread-cert/node.py
tests/scripts/thread-cert/test_srp_auto_start_mode.py

This PR binds SRP Server to Thread netif.
We also add a configuration option for the SRP server UDP port to allow using a specific/static port.
See also discussions at https://github.com/openthread/openthread/pull/6318#discussion_r598065071.

[srp-server] bind SRP Server to Thread netif

---

src/core/api/udp_api.cpp
src/core/net/udp6.cpp
src/core/net/udp6.hpp

A follow up of #6318 to ensure a socket is bound to an interface when no Udp::Bind is called.

[udp] bind to an interface when sending/connecting

---

src/lib/platform/BUILD.gn

These are needed to enable logging when building with gn.
This fixes the bug #6316.

[gn] include lib/platform files in build
