openthread/openthread

third_party/silabs/cmake/imported_libs.cmake
NAME_WLE was [added](https://cliutils.gitlab.io/modern-cmake/chapters/intro/newcmake.html#cmake-314--file-utilities-aka-cmake-%CF%80) in CMake 3.14 and isn't available in 3.10, which is the default requirement for openthread
This switches `imported_libs.cmake` to NAME_WL, which is in 3.10
=> [efr32] switch NAME_WLE to NAME_WE to be CMake 3.10 compatible

src/core/common/equatable.hpp, src/core/common/settings.hpp, src/core/common/time.hpp, src/core/mac/channel_mask.hpp, src/core/meshcop/meshcop.hpp, src/core/net/ip6_address.hpp, src/core/net/socket.hpp, src/core/thread/network_data.hpp, src/core/thread/topology.hpp
This commit adds `Unequatable<Type>` class which adds an overload of
operator `!=` using an existing `==` overload provided by the `Type`
class. The `Unequatable` should follow CRTP-style inheritance, i.e.,
the `Type` class should publicly inherit from `Unequatable<Type>`.
This provides a solution to avoid repeating the simple implementation
of `operator!=()` overload in different classes.
=> [equatable] 'Unequatable' class adding overload of operator `!=`

src/posix/client.cpp
Calling write multiple times may casing different arguments of a command line reach to the daemon at different times. This commit composes arguments into a full command line and sends it at once.
=> [ot-ctl] send a line at once

src/core/border_router/router_advertisement.hpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit applies on-link validations described by https://www.ietf.org/archive/id/draft-lemon-stub-networks-02.html#section-3.1.1.
=> [border-router] enhance on-link prefix check

src/core/thread/link_metrics.cpp, src/core/thread/link_metrics.hpp, src/core/thread/link_metrics_tlvs.hpp, src/core/thread/topology.hpp
This commit addresses the header file include loop between
the `link_metrics.hpp` and `topology.hpp` by forward declaring
`Neighbor` in `link_metrics` header. It also removes some of the
unnecessary header includes and contains smaller style fixes.
=> [link-metrics] address header file loop with 'topology.h'

Android.mk, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/net/ip4_address.cpp, src/core/net/ip4_address.hpp, src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, tests/unit/CMakeLists.txt, tests/unit/Makefile.am, tests/unit/test_ip_address.cpp
This commit adds IPv4 address definitions in OpenThread:
- Adds `Ip4::Address` class.
- Adds methods to convert IPv4 address to/from string.
- Updates the `Ip6::Address::FromString()` to use the IPv4
`FromString()` for the case where the IPv6 address contains
an embedded IPv4 address.
- Renames unit test to `test_ip_address` and updates it to
cover the behavior of the newly added IPv4 definitions in 
addition to IPv6 related tests.
=> [net] add `Ip4::Address` class

src/core/net/dns_client.cpp, src/core/net/dns_client.hpp
This commit contains two small changes in `Dns::Client`: simplifying
the `SendQuery()` call and adding a comment about reason for parsing
the response in a separate method.
=> [dns-client] simplify `SendQuery()` and add comment

src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, tests/unit/test_ip_address.cpp
This commit adds `Ip6::Address::SetFromTranslatedIp4Address()` method
performing NAT64 address translation from an IPv4 address and a NAT64
prefix to construct a corresponding IPv6 address as specified in RFC
6052. This commit also updates the unit test `test_ip6_address.cpp` to
cover the behavior of the newly added method.
=> [ip6-address] add `SetFromTranslatedIp4Address()` for NAT64

Android.mk, include/Makefile.am, include/openthread/BUILD.gn, include/openthread/instance.h, include/openthread/srp_client_buffers.h, src/cli/cli_srp_client.cpp, src/cli/cli_srp_client.hpp, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/api/srp_client_buffers_api.cpp, src/core/common/instance.hpp, src/core/common/pool.hpp, src/core/config/srp_client.h, src/core/thread/thread_netif.cpp, src/core/thread/thread_netif.hpp, src/core/utils/srp_client_buffers.cpp, src/core/utils/srp_client_buffers.hpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base.hpp, src/ncp/ncp_base_mtd.cpp, src/ncp/ncp_config.h
This commit adds a new module `Utils::SrpClientBuffers` which provides
string/data buffers and a pool of service entries for use for SRP
client. OpenThread SRP client implementation requires that the
service, string/data buffers passed as parameters to its API to
persist. This allows flexibility in how the SRP client can be used
(users of API can decide on how to manage the memory). The new module
provides an option to OT API user to use the buffer and service pool
to allocate/free items (e.g., service entries). The new module is
enabled by `OPENTHREAD_CONFIG_SRP_CLIENT_BUFFERS_ENABLE`. A set of new
configs specifies the number of service entries in the pool, number of
host address entries, and the size of different string buffers (e.g,
size of service instance string, etc).
This commit …
=> [srp-client] adding buffer and service pool module

src/core/common/message.cpp, src/core/common/message.hpp, tests/unit/test_message.cpp
This commit adds `Message::AppendBytesFromMessage()` which appends
bytes to a message read from another or potentially the same message
at a given offset. The bytes are read and copied directly (chunk by
chunk) without requiring an intermediate buffer. This commit also
updates `test_message` unit test to cover the behavior of the newly
added method (for both cases where the source and the destination
messages are the same or different).
------
Background: I think this method will be helpful in general. The immediate use for this
is to append encoded DNS names in a message e.g., from one message to another
or within the same message (will add this in a follow-up PR).
=> [message] add method to append bytes read from another/same message

src/core/net/dns_types.cpp, src/core/net/dns_types.hpp, tests/unit/test_dns.cpp
This commit adds `AppendTo()` method in `Dns::Name` class. This method
allows appending an already encoded name from one message to another.
This is performed by directly copying labels one by one between the
messages and does not require an intermediate buffer to read and store
the labels or the full name. This commit also updates `test_dns` unit
test to cover the behavior of the newly added method.
=> [dns] adding `Name::AppendTo()` to copy DNS name from one message to another

tests/scripts/thread-cert/v1_2_LowPower_7_1_01_SingleProbeLinkMetricsWithEnhancedAcks.py, tests/scripts/thread-cert/v1_2_LowPower_7_2_01_ForwardTrackingSeries.py
In `tests/scripts/thread-cert/node.py`, the timeout parameter of `ping()` function is in seconds. However, in some test cases they called `ping()` with a timeout in milliseconds.
I used the following command to list `ping()` usages with a specified timeout:
```
grep -rn "ping.*timeout=" tests/scripts/thread-cert/*
```
=> [tests] fix wrong usage of ping timeouts

src/cli/README.md
Add documentation for channel manager/monitor CLI commands.
I wasn't sure if commands should be listed strictly alphabetically, or grouped based on functionality as in [`cli.cpp`](https://github.com/openthread/openthread/blob/a10af5a3d66549a51f72e8fa1e74a228b5cd83c1/src/cli/cli.cpp#L663). Please let me know what the preference is and I can make the according change.
=> [docs] add CLI documentation for channel manager/monitor

src/core/mac/data_poll_sender.cpp, src/core/mac/data_poll_sender.hpp
This PR replaces some enum definition with constexpr since these enum
are used for comparing. The compiler would always give warnings when 
comparing enum with other non-enumeral values. With this change, we 
can directly compare the consts with other values. And this PR replaces
`UpdateIfLarger` with `OT_MIN`.
=> [data-poll-sender] use OT_MIN and replace enum with constexpr

tests/scripts/thread-cert/backbone/test_bmlr.py, tests/scripts/thread-cert/thread_cert.py
Fixes #6299
In BMLR test, the commissioner may fail to start because the `/c/ps` COAP message failed to reach Leader due to unstable links. 
This commit makes sure the links are established before starting the commissioner.
=> [scripts] make BMLR test more reliable

include/openthread/dns.h, include/openthread/instance.h, src/cli/README.md, src/cli/cli.cpp, src/cli/cli.hpp, src/core/api/dns_api.cpp, src/core/common/instance.cpp, src/core/common/instance.hpp, src/core/net/dns_types.cpp
This commit adds support for "DNS name compression" mode. By default
the DNS name compression is enabled. When disabled, DNS names are
appended as full and never compressed. This is applicable to
OpenThread's DNS and SRP client/server modules. This is intended for
testing only and available when config option
`OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE` is enabled.
This commit also add a CLI command for this feature as 
`dns compression [enable|disable]` and updates the CLI's `README.md`.
=> [dns] allow disabling of DNS name compression for testing

tests/scripts/thread-cert/backbone/bbr_5_11_01.py, tests/scripts/thread-cert/backbone/test_dua_routing.py, tests/scripts/thread-cert/backbone/test_mlr_multicast_routing_across_thread_pans.py
This commit tests Backbone DUA routes implemented by https://github.com/openthread/ot-br-posix/pull/586
Depends-On: openthread/ot-br-posix#586
**Merging Tips:**
We should merge this PR first, and than merge https://github.com/openthread/ot-br-posix/pull/586 using latest OT master commit.
=> [scripts] add Backbone DUA routes test

src/core/meshcop/border_agent.cpp, src/core/meshcop/border_agent.hpp, src/core/meshcop/dataset_manager.cpp, src/core/net/ip6_address.hpp, src/core/net/udp6.cpp
The MeshCoP UDP Proxy packets should not be sent/received with platform UDP.
Depends-On: openthread/ot-commissioner#185
=> [meshcop] fix UDP proxy

src/lib/spinel/spinel.c
The openwrt toolchain complains
```
[ 90%] Building C object third_party/openthread/repo/src/lib/spinel/CMakeFiles/openthread-spinel-rcp.dir/spinel.c.o
/usr/src/toolchain/feeds/otbr/third_party/openthread/repo/src/lib/spinel/spinel.c: In function 'spinel_prop_key_to_cstr':
/usr/src/toolchain/feeds/otbr/third_party/openthread/repo/src/lib/spinel/spinel.c:1481:9: error: missing initializer for field 'str' of 'const struct spinel_cstr' [-Werror=missing-field-initializers]
{0},
```
The patch adds NULL for the char* argument of spinel_cstr.
=> [spinel] fix missing initializer compiler error

include/openthread/instance.h, include/openthread/ping_sender.h, src/cli/README.md, src/cli/cli.cpp, src/core/utils/ping_sender.cpp, tests/scripts/thread-cert/Cert_5_6_09_NetworkDataForwarding.py, tests/scripts/thread-cert/Cert_9_2_09_PendingPartition.py, tests/scripts/thread-cert/node.py, tools/otci/otci/command_handlers.py, tools/otci/otci/otci.py, tools/otci/tests/test_otci.py
Ping enhancements
- If it's not multicast, `ping` command in CLI will print `Done` in the end, after printing replies and statistics. The old behavior is, `ping` command prints `Done` before any replies.
- In OTCI, let `ping` function return statistics.
- Support timeout parameter in `ping` command.
- Fix a bug that the arguments are not properly passed to `ping` in `node.py`.
- Adjust timeouts in tests.
=> [ping-sender] let ping return statistics in OTCI

src/core/border_router/routing_manager.cpp, tests/scripts/thread-cert/border_router/test_single_border_router.py, tests/scripts/thread-cert/config.py, tests/scripts/thread-cert/node.py
Accept RA initiated from the infra interface so that we can detect the existence of another RA daemon
which is working on the same infra interface.
(We also did an enhancement to the `test_single_border_router.py` test script to make it more readable.
TODO:
=> [border-router] accept RA initiated from the infra interface

include/openthread/channel_manager.h, include/openthread/instance.h, src/cli/cli.cpp, src/core/api/channel_manager_api.cpp, src/core/config/channel_manager.h, src/core/utils/channel_manager.cpp, src/core/utils/channel_manager.hpp
I have found that the default channel manager [CCA failure rate threshold](https://github.com/openthread/openthread/blob/main/src/core/config/channel_manager.h#L109) is not necessarily ideal, and some experimentation is required to determine a good threshold depending on network characteristics and packet size/periodicity.
For example, I have a network that experiences ~40% packet loss, yet only ever reports a maximum 4% CCA failure rate, well below the default of 10%.
This pull request adds functions to get/set the threshold, the API layer, CLI hooks, and CLI documentation.
=> [channel-manager] add cli/api functions to modify the CCA failure rate threshold

.github/workflows/simulation-1.1.yml, Android.mk, doc/ot_api_doc.h, include/Makefile.am, include/openthread/BUILD.gn, include/openthread/dnssd_server.h, include/openthread/instance.h, script/test, src/cli/cli.cpp, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/api/dns_server_api.cpp, src/core/common/string.cpp, src/core/common/string.hpp, src/core/config/dnssd_server.h, src/core/net/dnssd_server.cpp, src/core/net/dnssd_server.hpp, tests/scripts/thread-cert/border_router/test_dnssd_server.py, tests/scripts/thread-cert/config.py, tests/scripts/thread-cert/node.py
This commit implements DNS-SD Discovery Proxy.
Depends-On: openthread/ot-br-posix#706
---
**Some implementation deitals:**
* Discovery Proxy subscribes to services/service instances/hosts through callbacks set by a public OT API. It is up to the platform mDNS implementation to collect service instance/host information and notify OT via a public OT API.
* Discovery Proxy can handle DNS browsing of one service or DNS resolving of one service instance/host. We leave browsing multiple services or resolving multiple service instances/hosts for future enhancements if necessary.
=> [dnssd] implement DNS-SD Discovery Proxy

tests/toranj/start.sh
Fix warnings when running `script/make-pretty check shell`:
```
========================================
check shell                                                             
========================================
In tests/toranj/start.sh line 117:                                           
./build.sh ${coverage_option} ncp-15.4 || die "ncp-15.4 build failed" 
^----------------^ SC2086: Double quote to prevent globbing and word splitting.
Did you mean:                                                                
./build.sh "${coverage_option}" ncp-15.4 || die "ncp-15.4 build failed"
In tests/toranj/start.sh line 119:                                           
./build.sh ${coverage_option} ncp-trel || die "ncp-trel build failed" 
^----------------^ SC2086: Double quote to prevent …
```
=> [tests] fix shell format check warnings

src/core/api/border_router_api.cpp, src/core/thread/network_data_local.cpp, src/core/thread/network_data_local.hpp
This commit adds validation of the on mesh prefixes.
With this change, the domain on mesh prefix can be directly configured after successfull verification.
=> [border-router] add validation of updated on mesh prefixes

tests/toranj/build.sh
This commit updates `toranj/build.sh` script to skip over empty ""
arguments at the start. This addresses an issue introduced in commit
531cb3484 (PR #6421) where the `start.sh` adds an empty arg when
invoking `build.sh` when coverage is not enabled.
=> [build] update `toranj` build script to skip over empty "" args

include/openthread/instance.h, include/openthread/srp_server.h, src/core/api/srp_server_api.cpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp
We are using the SRP Host pointer for indexing an outstanding SRP update when
the Advertising Proxy result is passed back with `otSrpServerHandleServiceUpdateResult`.
There are chances that an old, freed Host object may be matched again with a newly allocated
Host object which coincidentally has the same address with the old Host object.
This PR solves this issue by using a random generated `uint32_t` SRP service update ID for indexing
outstanding updates.
Depends-On: openthread/ot-br-posix#774
=> [srp-server] replace SRP Host pointer with SRP service update ID

src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_srp_client.cpp, src/cli/cli_udp.cpp
This commit adds a helper method `Cli::ParseEnableOrDisable()` which
checks a given string against two common commands "enable" or
"disable". This method is then used in CLI modules
=> [cli] adding helper method `ParseEnableOrDisable()`

tests/scripts/thread-cert/run_cert_suite.py
This commit allow specify `MAX_JOBS` via env to set the max number of tests running concurrently.
=> [thread-cert] specify MAX_JOBS via env

examples/platforms/nrf528xx/nrf52811/transport-config.h, examples/platforms/nrf528xx/nrf52833/transport-config.h, examples/platforms/nrf528xx/nrf52840/transport-config.h, examples/platforms/nrf528xx/src/transport/uart.c
* [nrf528xx] ensure HWFC is triggered when SW buffer is full
* [nrf528xx] use UARTE peripheral for TX path
=> [nrf528xx] ensure HWFC is triggered when SW buffer is full

include/openthread/dns_client.h, include/openthread/instance.h, src/core/config/dns_client.h, src/core/net/dns_client.cpp, src/core/net/dns_client.hpp, src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, tests/unit/test_ip_address.cpp
This commit adds support for NAT64 address translation (from IPv4 to
IPv6) during address resolution in `Dns::Client`. This feature is
enabled using `OPENTHREAD_CONFIG_DNS_CLIENT_NAT64_ENABLE` config
option. When enabled, the caller can specify in the address query
configuration whether to allow or disallow NAT64 address translation
for a specific query. The default behavior can also be set using the
default DNS client config.
When the NAT64 is allowed, if the response from server does not
provide an IPv6 address for the host name, we first check if the
server has provided IPv4 address information in the response, and if
not, start a new query for the IPv4 address. Once the IPv4 address(es)
of the host name are resolved, they are translated to IPv6 address(es)
and reported to the user in …
=> [dns-client] add support for NAT64 during address resolution

examples/platforms/nrf528xx/src/radio.c
For nRF52 platforms in order to achieve the best CSL accuracy frame security processing was moved to the nrf_802154_tx_started() radio driver callback which is called from the interrupt context when frame transmission is started by the hardware peripheral. 
There is a possibility that a requested transmission will be aborted before nrf_802154_tx_started() is called. The frame can be then retransmitted and if nrf_802154_tx_started() is called it will skip setting key index and frame counter (so they will remain unchanged with a value equal to whatever is present in RAM). 
It seems that we should always set these fields. Moreover, security is processed only once which is controlled by mTxInfo.mIsSecurityProcessed member so checking for retransmission is redundant. Thoughts?
=> [nrf528xx] set key id and frame counter for retransmissions

include/openthread/instance.h, include/openthread/platform/radio.h
This commit updates documentations in `radio.h` and adds more detail
on expected behavior on assigning of the frame counter (on retx or
first attempt frame) when radio provides `OT_RADIO_CAPS_TRANSMIT_SEC`
capability (i.e., radio platform layer handles the tx security and
frame counter management).
--------
It is related to PRs https://github.com/openthread/openthread/pull/6427 and https://github.com/openthread/openthread/pull/6446.
=> [radio] update docs on frame counter when `RADIO_CAPS_TRANSMIT_SEC`

script/cmake-build
This commit adds the option CMAKE_EXPORT_COMPILE_COMMANDS=ON to export
compile commands which is helpful for editors/IDEs.
=> [cmake] export compile commands

tests/scripts/thread-cert/node.py
This commit fixes parsing dig TXT RR that contains `"`.
=> [scripts] fix parsing TXT RR containing `"` 

examples/platforms/nrf528xx/src/radio.c
This change tackles both problems resolved and introduced by https://github.com/openthread/openthread/pull/6427.
For direct transmissions, if the first frame transmission fails, e.g. due to a CCA failure then retransmissions will contain an invalid frame counter. It causes problems especially for long IP packets - the receiver drops a fragment but the transmitter will flood it with the next fragments since it is not aware that the other party dropped a fragment. We have identified that it's a root cause of the problem reported in https://github.com/openthread/openthread/issues/6337.
Previous solution (remove the check if a frame is retransmitted) may cause problems with indirect transmissions where radio frames are created from scratch and then their frame counter would be overridden. …
=> [nrf528xx] set frame counter and key idx in otPlatRadioTransmit()

tests/scripts/thread-cert/v1_2_LowPower_5_3_01_SSEDAttachment.py, tests/scripts/thread-cert/v1_2_test_csl_transmission.py
Sometimes CSL cannot be sent out at the sample windows following the ping command and may need to wait for one or more CSL periods. Use the default ping timeout which covers several CSL periods.
Close #6041, close #6449
=> [scripts] increase CSL ping timeout value

src/core/common/instance.cpp, src/core/radio/trel_interface.cpp, src/core/radio/trel_link.cpp, src/core/radio/trel_link.hpp
to avoid checking `mInitialized` repeatedly in TX tasklet.
=> [trel] initialize TREL interface in `AfterInit`

src/core/thread/neighbor_table.cpp
Currently, if using `FindNeighbor(const Ip6::Address &aIp6Address, Neighbor::StateFilter aFilter)` when the `aIp6Address` is the device's parent's link local address, it cannot be found. This PR fixes this issue.
This PR fixes part of #6479
=> [neighbor-table] fix finding neighbor by Ip6 address issue

src/core/thread/network_data.cpp
This commit updates `NetworkData::Iterate()` to check that an entire
TLV (or sub-TLV) is contained within the Network Data (up to its
length) and skips over TLVs that are incomplete. It also updates
`FindTlv()` methods to directly use the stricter check in the
`for()` loop used to iterate over all TLVs.
=> [network-data] check and skip over incomplete TLVs during TLV iteration

src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, tests/unit/test_network_data.cpp
This commit adds a new method in `NetworkData` class to find and
iterate over all Service TLVs that start with a given Service Data.
Unlike the existing `FindService()` method which searches for a
Service TLV with an exact match with the given Service Data,  this
method performs a relaxed check allowing a matching Service TLV to
contain additional bytes after given data bytes to search for.
This commit also updates `test_network_data` unit test to add new
test to cover the behavior of newly added method.
----
This will be useful for parsing Service TLVs for SRP/DNS server info as
discussed/described in https://github.com/openthread/openthread/issues/6447.
=> [network-data] add `FindNextMatchingService()`

CMakeLists.txt
Print source directory during cmake, which is useful to find the source
code location when OpenThread is built by other projects.
=> [cmake] print source directory

include/openthread/border_router.h, include/openthread/instance.h, include/openthread/platform/infra_if.h, src/core/api/border_router_api.cpp, src/core/border_router/infra_if_platform.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/posix/platform/infra_if.cpp, src/posix/platform/platform-posix.h, src/posix/platform/system.cpp
This PR removes the need of getting LLA of infra interface but adds
a new platform API `otPlatInfraIfHasAddress` which matches the infra
interface and a given address.
background:
The infra interface LLA is used in the Routing Manager for only testing
if RA/RS message is initiated from the infra interface.
=> [border-router] add platform API otPlatInfraIfHasAddress

script/test
Since `OT_TREL` is going to be set to `ON` in OTBR, this commit makes sure we test OTBR with TREL off.
- Also removed `-DOTBR_DNSSD_DISCOVERY_PROXY=ON` since it's now ON by default.
=> [thread-cert] use `OT_TREL=OFF` for OTBR docker build

examples/apps/cli/cli_uart.cpp
The OpenThread cli may print false alarms when calling `OutputLine("")`.
Fix accordingly.
=> [cli] fix false alarm when printing empty line

examples/platforms/nrf528xx/nrf52811/openthread-core-nrf52811-config.h, examples/platforms/nrf528xx/nrf52833/openthread-core-nrf52833-config.h, examples/platforms/nrf528xx/nrf52840/openthread-core-nrf52840-config.h, examples/platforms/nrf528xx/src/radio.c, include/openthread/crypto.h, include/openthread/instance.h, include/openthread/platform/radio.h, src/core/config/mac.h, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/radio/radio.hpp, src/core/radio/radio_platform.cpp, src/posix/platform/radio.cpp
This PR uses the receive timing capability from the radio to schedule CSL receive operations with a higher precision, allowing for shorter receive windows.
`mCslTimer` is set up to be triggered `OPENTHREAD_CONFIG_CSL_RECEIVE_TIME_AHEAD` before the start of the receive window.
Depends on:
=> [low-power] add receive timing capability to CSL receiver

include/openthread/instance.h, include/openthread/thread.h, src/cli/README.md, src/cli/cli.cpp, src/cli/cli.hpp, src/core/api/thread_api.cpp, tests/scripts/expect/_common.exp, tests/scripts/expect/cli-ipmaddr.exp, tools/otci/otci/otci.py, tools/otci/tests/test_otci.py
This PR adds APIs to get Link/Realm Local All Thread Nodes multicast
addresses. This PR also adds cli command to get meshlocal prefix 
alone for writing tests.
=> [cli] add cli to get All Thread Nodes multicast address

src/core/api/message_api.cpp, src/core/backbone_router/bbr_manager.cpp, src/core/common/instance.hpp, src/core/meshcop/announce_begin_client.cpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/energy_scan_client.cpp, src/core/meshcop/joiner.cpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/meshcop_leader.cpp, src/core/meshcop/panid_query_client.cpp, src/core/thread/address_resolver.cpp, src/core/thread/announce_begin_server.cpp, src/core/thread/dua_manager.cpp, src/core/thread/energy_scan_server.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mlr_manager.cpp, src/core/thread/network_data.cpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_diagnostic.cpp, src/core/thread/panid_query_server.cpp, src/core/thread/thread_netif.cpp, src/core/thread/thread_netif.hpp, src/core/thread/tmf.cpp, src/core/thread/tmf.hpp
This commit renames the TMF agent class from `Tmf::TmfAgent` to
`Tmf::Agent` (to follow style used by other modules).
=> [tmf] rename TMF agent class to `Tmf::Agent`

src/core/thread/dua_manager.cpp, src/core/thread/dua_manager.hpp
This commit changes `DuaManager::HandleDuaResponse()` to use a pointer
to `aMessage` and `aMessageInfo` (instead of reference). Note that in
case of a failure, the `Coap` module may invoke the response handler
with `nullptr` for these parameters.
=> [dua-manager] avoid null dereference in CoAP response handler

src/cli/README.md, src/cli/cli.cpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/border_agent.hpp, src/core/meshcop/commissioner.cpp, tests/scripts/expect/cli-misc.exp
This PR includes several small changes:
1. Add logs for Border Agent `Start` and `Stop` events to help analysis commissioning issues such as https://github.com/openthread/ot-commissioner/issues/193#issuecomment-822120350.
2. Start Border Agent when the native commissioner is stopped.
3. Add CLI command `ba state` to get current Border Agent state.
=> [border-agent] add logging for border agent events

src/core/coap/coap_message.cpp, src/core/coap/coap_message.hpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/dataset_manager.cpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_diagnostic.cpp
This commit updates `Coap::Message` to check and remove the payload
marker byte which is added at the end of header options in the case
that the message contains no payload. This check is performed in
`Finish()` method which finalizes the message for transmission. Note
that the presence of a marker followed by a zero-length payload is
processed as a message format error by receivers.
This change helps simplify the preparation of CoAP message by other
modules (i.e., they no longer need to check for empty payload to
remove the marker themselves and can rely on common code in
`Coap::Message`).
=> [coap-message] remove the payload marker when no payload

include/openthread/instance.h, include/openthread/platform/infra_if.h, src/core/border_router/router_advertisement.cpp, src/core/border_router/router_advertisement.hpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, tests/scripts/thread-cert/border_router/test_radvd_coexist.py, tests/scripts/thread-cert/border_router/test_single_border_router.py, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/pktverify/packet_filter.py
The PR enhance the Routing Manager to learn RA header and parameters from
RA messages initiated from infra interface. This addresses the issue that the BR
may be using different RA header against another RA daemon which is working
on the same infra interface (Have BR and another RA daemon working on the
same interface is common for `Wi-Fi + Thread` routers).
We also changed to accept RS messages initiated from the infra interface:
this is for case that multiple Border Routers run on the same host (as we are
trying to support multiple ot-daemons on the same host).
----
TODO:
=> [border-router] learn RA header and parameters from infra interface

src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_coap.cpp, src/cli/cli_coap.hpp, src/cli/cli_coap_secure.cpp, src/cli/cli_coap_secure.hpp, src/cli/cli_commissioner.cpp, src/cli/cli_commissioner.hpp, src/cli/cli_dataset.cpp, src/cli/cli_dataset.hpp, src/cli/cli_joiner.cpp, src/cli/cli_joiner.hpp, src/cli/cli_network_data.cpp, src/cli/cli_network_data.hpp, src/cli/cli_srp_client.cpp, src/cli/cli_srp_client.hpp, src/cli/cli_srp_server.cpp, src/cli/cli_srp_server.hpp, src/cli/cli_udp.cpp, src/cli/cli_udp.hpp, src/core/diags/factory_diags.cpp, src/core/diags/factory_diags.hpp, src/core/utils/parse_cmdline.cpp, src/core/utils/parse_cmdline.hpp
This commit adds a new `Arg` class in `parse_cmdline` which represents
a single argument (wrapper over a C string). The `Arg` class is then
used in CLI modules. This helps simplify the CLI code mainly using
simpler syntax, e.g., using an overload of `==` operator to compare an
argument with a C string, or calling `ParseAs{Type}()` methods
directly on an `Arg` instance.
=> [cli] simplify arg checking/parsing with new `Arg` class

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp
This commit changes the `MleRouter::HandleChildUpdateRequest()` to
clear the "last rx fragment tag" only if the "Child Update Request" is
from a detached child trying to restore its link with its parent. This
is indicated by the presence of Challenge TLV in the received message.
The "last rx fragment tag" is used for duplicate frame detection when
`MULTI_RADIO` is enabled.
=> [mle] clear tag only on a "Child Update Req" Rx from a detached child

tests/scripts/thread-cert/v1_2_LowPower_7_1_01_SingleProbeLinkMetricsWithEnhancedAcks.py
This PR fixes #6525.
From the pcap, it looks like the ping is there. I think probably the cause is that the ping reply came after the ping timeout (3s) just exceeded:
=> [tests] fix v1_2_LowPower_7_1_01_SingleProbeLinkMetricsWithEnhancedAcks

src/cli/cli.cpp, src/cli/cli.hpp, tools/otci/otci/otci.py, tools/otci/tests/test_otci.py
This commit makes the CLI command for printing MLR listeners works for non Reference Devices.
=> [backbone-router] add cli command for MLR listeners

src/core/border_router/routing_manager.cpp
static_assert with no message is a C++17 extension.
Thanks to @gabekassel for pointing this out.
=> [routing-manager] add message to static_assert

src/cli/cli.cpp, tests/scripts/expect/cli-misc.exp
It also adds a check in `cli-misc.exp` to verify error on an invalid
CLI command.
------
Thanks to @lmnotran for noticing and reporting this (in https://github.com/openthread/openthread/pull/6524#discussion_r626058987).
=> [cli] fix extra error output when handling user CLI commands

.github/workflows/simulation-1.1.yml, src/core/meshcop/meshcop.hpp, src/core/net/ip6_filter.cpp, src/core/net/ip6_filter.hpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/thread_netif.cpp, src/posix/platform/netif.cpp
This commit adds native commissioner support with the following changes:
* Accept unsecure traffic when Thread is not enabled.
* Accept traffic to border agent service when native commissioner is
allowed.
Depends-On: openthread/ot-commissioner#201
=> [meshcop] support native commissioner

src/core/common/logging.cpp, src/core/common/notifier.cpp, src/core/common/string.cpp, src/core/common/string.hpp, src/core/mac/channel_mask.cpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_types.cpp, src/core/meshcop/meshcop.cpp, src/core/net/ip4_address.cpp, src/core/net/ip6_address.cpp, src/core/net/socket.cpp, src/core/radio/trel_packet.cpp, src/core/thread/link_quality.cpp, src/core/thread/mle.cpp, src/core/thread/mle_types.cpp, src/core/thread/radio_selector.cpp, src/core/utils/channel_monitor.cpp, tests/unit/test_string.cpp
This commit moves methods of String out of the header file to save code
size.
Since most use cases of String writers ignores errors, this commit
changes the return of writers to the Writer object itself for chained
writes.
=> [string] introduce StringWriter class

src/lib/url/url.cpp, src/posix/main.c, src/posix/platform/include/openthread/openthread-system.h, src/posix/platform/system.cpp, src/posix/platform/trel_udp6.cpp
This commit supports TREL URL (e.g. `trel://eth0`) for Posix.
Depends-On: openthread/ot-br-posix#803
=> [posix-trel] support TREL URL

tests/scripts/thread-cert/border_router/MATN_09_DefaultBRMulticastForwarding.py
The second to the last packet verification statement expects a ping request sent by Router_1 after BR_2 became the PBBR.
However, this statement wrongly matches a ping request sent by Router_1 before BR_2 became the PBBR. 
I added a restriction of the echo identifier to make sure the packet verification statement doesn't match the previous ping request.
=> [tests] fix MATN_09_DefaultBRMulticastForwarding.py

examples/platforms/simulation/system.c, tests/toranj/wpan.py
This PR extracts the `get_opt` enhancement part of #6536.
Since no new arguments is added to virtual simulation platform and 
it still only has one argument, I didn't use `get_opt` for it.
=> [simulation] enhance command line arguments by using get_opt

src/core/common/string.hpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_types.cpp, src/core/net/ip4_address.cpp, src/core/net/ip6_address.cpp, src/core/net/socket.cpp, src/core/thread/link_quality.cpp, src/core/thread/mle.cpp, src/core/thread/mle_types.cpp, src/core/thread/radio_selector.cpp, src/core/utils/channel_monitor.cpp, tests/unit/test_string.cpp
This commit fixes an issue with some of the log related methods where
`String` object may be used without being initialized (this was added
from commit b39f5b6dd and PR #6564).
This commit ensures that `String` variable definitions are always
immediately  followed by a `StringWriter()` definition which then
initializes the string buffer (sets it as empty).
This commit also updates `test_string` unit test.
-----
This should help address https://github.com/openthread/openthread/issues/6583.
=> [log] fix uninitialized string use

etc/cmake/options.cmake, src/core/config/border_router.h, tests/scripts/thread-cert/border_router/test_dnssd_server.py, tests/scripts/thread-cert/border_router/test_single_border_router.py
This commit updates the BR name in comments and documentation
(removes the uses of "duckhorn")
=> [doc] update the BR name in comments/documentations

script/check-posix-pty, src/posix/client.cpp, src/posix/main.c, src/posix/platform/daemon.cpp, src/posix/platform/openthread-posix-config.h, src/posix/platform/system.cpp, tests/scripts/misc/test_multicast_join.py
This commit adds the Thread interface name to unix socket of OpenThread daemon, so that `ot-ctl` can specify which daemon to connect to.
=> [posix] support interface name in ot-ctl

script/check-posix-pty, src/posix/client.cpp
With this change, both the following command should work:
```bash
ot-ctl -I wpan0 pskc -p 123456
ot-ctl -I wpan0 -- pskc -p 123456
```
=> [ot-ctl] support no separator --

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
This commit updates `MleRouter::HandleChildUpdateRequest()` related to
how a "Child Update Request" message from a child is processed on a
parent. If the child is present in the parent's child table but it is
not yet in valid state, the parent ignores the received "Child Update
Request". This applies to a child being restored due to parent's reset
(child is in `kStateRestored`) or a child which is in the middle of
attach process (e.g., child is in `kStateParentRequest`). If a
matching child entry cannot be found in the parent's child table, the
behavior remains as before (i.e., parent sends a response with an
error Status TLV to notify the child to re-attach).
This change ensures that after a parent reset to restore a child, the
parent node is the one initiating and sending a "Child …
=> [mle] ignore "Child Update Request" from a child not yet in valid state

include/openthread/instance.h, include/openthread/srp_client.h, src/core/net/srp_client.cpp, src/core/net/srp_client.hpp
This commit updates `Srp::Client::AddService()` to reject and return
`kErrorAlready` if the caller tries to add duplicate service entries
(services with matching service and instance names).
=> [srp-client] disallow adding of duplicate services (same service/instc name)

examples/apps/cli/main.c, src/cli/cli.cpp, src/cli/cli.hpp, src/posix/client.cpp, src/posix/main.c
The exit command should only exit ot-ctl itself in daemon mode. This
commit adds processing exit command in the ot-ctl.
This commit also moves the exit command implementation out from core
as a user command on simulation and posix cli mode.
=> [cli] process exit in ot-ctl

tests/scripts/thread-cert/border_router/MATN_15_ChangeOfPrimaryBBRTriggersRegistration.py
The test case failed because pktverify failed to find an ACK packet sent to `TD`. However, `TD_RLOC` has changed during the test while we were using the latter RLOC to verify the packet. Therefore it wasn't able to find the packet. 
As said by @simonlingoogle in: https://github.com/openthread/openthread/issues/6602
> One finding is that the TD registers it's MA just at the same moment as it sends ADDR_SOL.req.
This caused the TD to change its RLOC, so that it can not receive the MLR.rsp.
For this test case, we can verify the existence of that ACK packet using the source address of its according CON packet. 
Fixes #6602
=> [github-actions] fix MATN_15_ChangeOfPrimaryBBRTriggersRegistration.py

src/core/thread/dua_manager.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/network_data_local.cpp
If a device is a REED and waiting the random delay to upgrade to a
router, the device will wait to register its network data, since it
will have to register again after upgrading to a router. However, the
maximum delay for becoming a router is up to 2 minutes, which is a
long time to wait.
This commit limits the delay that a device will wait to register its
network data.
=> [network-data] limit router upgrade delay when registering

src/core/thread/address_resolver.cpp, src/core/thread/address_resolver.hpp, src/core/thread/mesh_forwarder_ftd.cpp
This commit updates `UpdateSnoopedCacheEntry()` to perform the
common checks before adding a snooped entry (e.g., ensuring the
snooped entry source is not the an MTD child of the device).
=> [address-resolver] simplify updating snooped cache entries

src/cli/cli.cpp, tests/scripts/thread-cert/test_diag.py
This commit makes the CLI command output consistent under all cases:
- Output `Error 6: Parse` when the command line is too long (no output originally).
- Output `Error 7: InvalidArgs` when the command line has too many arguments. The original output is `Error: too many args (max %d)`, which does not strictly follow the `Error <code>: <msg>` pattern.
- Output `Error 13: InvalidState` for running non-diag command in diagnosis mode to follow `Error <code>: <msg>` pattern.
=> [cli] make command output consistent

src/core/thread/dua_manager.cpp
Parent should send DUA.ntf to Child that requested the DUA when status is not `ST_DUA_SUCCESS`, according to Thread 1.2 Spec. 5.23.6.2. 
Fixes DUA-TC-17.
=> [dua] send DUA.ntf to notify Child of unsuccessful DUA registration

src/core/net/ip6.cpp
This commit allows Reference Devices to send UDP messages to TMF port, which was prohibited by #5911 .
**Background**:
TestHarness sends constructed TMF messages in many TCs to validate the behavior of nodes on receiving these TMF messages.   
Fixes DUA-TC-09
=> [udp] allow Reference Devices to send UDP messages to TMF port

src/posix/platform/trel_udp6.cpp
Thanks to @gabekassel for reporting this issue.
=> [trel] avoid compiler warning on use of strncpy

Android.mk, src/posix/platform/CMakeLists.txt, src/posix/platform/Makefile.am, src/posix/platform/infra_if.cpp, src/posix/platform/infra_if.hpp, src/posix/platform/mainloop.cpp, src/posix/platform/mainloop.hpp, src/posix/platform/multicast_routing.cpp, src/posix/platform/multicast_routing.hpp, src/posix/platform/platform-posix.h, src/posix/platform/system.cpp
This commit allows launching an OpenThread daemon which was built with
backbone-router and border-routing support but disabling them at runtime
by not specifying the `-B` option.
=> [border-router] border routing optional at runtime

src/core/thread/dua_manager.cpp, src/core/thread/dua_manager.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_types.hpp
This commit enhances DUA response handling for `ST_DUA_REREGISTER`:
- Parent will stop registering DUA for MTD Child until the next `Child Update Request`
- MTD Child will re-register its DUA by `Child Update Request` or `DUA.req`
=> [dua] fix Parent failed to send reregister for MTD Child on receiving `ST_DUA_REREGISTER`

src/posix/platform/misc.cpp
Encountered this problem while building POSIX stack with logging enabled.
=> [posix] fix unused variable when log level is less than OT_LOG_LEVEL_CRIT

src/posix/platform/daemon.cpp
The CLI input is already logged as info level messages. This commit
writes the CLI output as info level logging messages.
=> [daemon] logging CLI output

script/bootstrap
Summary of changes:
- Enable building OpenThread RCP image on the Raspberry Pi (`aarch64`) directly (using Ubuntu)
- Fix problem with not having access to the `/opt` folder as a user
=> [bootstrap] add support for Ubuntu on Raspberry Pi

include/openthread/instance.h, include/openthread/ip6.h, src/cli/cli.cpp, src/cli/cli_network_data.cpp, src/core/api/ip6_api.cpp, src/core/common/string.hpp, src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp
This commit adds new public OpenThread APIs to convert an IPv6 address
or an IPv6 prefix to a human-readable string representation. The
implementation is shared with the `Address/Prefix::ToString()` used by
core modules (through adding a private `ToString(StringWriter &)`
method which can then be used with a `String<kSize>` or a char
buffer).
=> [ip6] add public APIs to convert an IPv6 address or prefix to string

src/core/net/srp_server.cpp, tests/scripts/thread-cert/border_router/test_advertising_proxy.py
The SRP server tries to notify the advertising proxy when a service is expired.
The expired service is firstly removed from the service list and later added back
to the head of the service list if the service name should be retailed. This will result
in deadloop when there are two or more services on the same host.
This commit fixes this issue by keeping the expired service in the service list by simply
mark the service `deleted` and pass all services of the host to the advertising proxy. The
advertising proxy will republish those services that are not expired but this should be fine
since service expiration is not a common case.
Also update the advertising proxy test case to cover multiple services.
=> [srp-server] fix removing expired services

src/posix/platform/infra_if.cpp
Thanks to @gabekassel for reporting this issue.
=> [posix] avoid compiler warning on use of strncpy

include/openthread/dnssd_server.h, include/openthread/instance.h, src/core/api/dns_server_api.cpp, src/core/net/dnssd_server.cpp, src/core/net/dnssd_server.hpp
This commit allows the platform implementations to access the name and
the type of the queries, thus reducing the memory overhead of
extra bookkeeping.
Depends-On: https://github.com/openthread/ot-br-posix/pull/841
=> [dnssd] add api for accessing queries in the dnssd server

src/posix/cli.cmake, src/posix/daemon.cmake, src/posix/platform/CMakeLists.txt
This commit adds ot-posix-config for POSIX platform, so that when POSIX
configurations changed only, other components don't need recompile.
=> [posix] avoid unnecessary recompilation

CMakeLists.txt
This commit sets cxx stand as `-std=c++11` instead of `-std=gnu++11`.
=> [cmake] no cxx extensions

src/core/common/logging.cpp, src/core/common/notifier.cpp, src/core/common/string.hpp, src/core/mac/channel_mask.cpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_types.cpp, src/core/meshcop/meshcop.cpp, src/core/net/ip4_address.cpp, src/core/net/ip6_address.cpp, src/core/net/socket.cpp, src/core/radio/trel_packet.cpp, src/core/thread/link_quality.cpp, src/core/thread/mle.cpp, src/core/thread/mle_types.cpp, src/core/thread/radio_selector.cpp, src/core/utils/channel_monitor.cpp, tests/unit/test_string.cpp
This commit changes the `String<kSize>` class to inherit from
`StringWriter` class. It helps simplify their use allowing
`StringWriter` methods to be directly called on an `String` instance
while ensuring the implementation is still shared among all template
variants of `String<kSize>` class. This change also ensures that
`String<kSize>` is always initialized and set to an empty string from
its constructor.
=> [string] change `String<kSize>` to inherit from `StringWriter`

examples/platforms/simulation/radio.c, include/openthread/instance.h, include/openthread/platform/radio.h, src/core/mac/mac.cpp, src/core/radio/radio.hpp, src/core/thread/mle.cpp, tests/unit/test_platform.cpp
Include the peer's short address together with the extended address when enabling the CSL link. This removes the need for the platform to guess it.
Depends-On: openthread/ot-nrf528xx#60
=> [low-power] extend EnableCsl API

include/openthread/instance.h, include/openthread/platform/settings.h, src/core/common/settings.cpp, src/core/common/settings.hpp, src/core/config/srp_client.h, src/core/net/srp_client.cpp, tests/scripts/thread-cert/Makefile.am, tests/scripts/thread-cert/test_srp_client_save_server_info.py
This commit adds support for a new feature in SRP client which allows
it to save the selected server info (by the auto-start feature) in
non-volatile settings. On SRP client restart (e.g., due to a device
reset) the client will select the same server when searching to
discover and pick one from the Thread Network Data service entries.
Config `OPENTHREAD_CONFIG_SRP_CLIENT_SAVE_SELECTED_SERVER_ENABLE` can
be used to enable/disable this feature.
The server info is saved only after the host info is successfully
registered with the server and if it is selected by auto-start from a
network data SRP *unicast* service entry.
This commit also adds `test_srp_client_save_server_info.py` test-case
which verifies the behavior of the new feature.
=> [srp-client] support saving selected server info (by auto-start)

src/posix/platform/multicast_routing.cpp
This PR applies the same trick of `otLogXXXXPlat` for `DumpMulticastForwardingCache` and make it only defined when the log options match.
=> [logging] optimize dump log for multicast routing manager

src/posix/platform/backbone.cpp, src/posix/platform/infra_if.cpp
Add the empty string check for backbone interface.
Fixes #6684
=> [posix] allow empty backbone interface name

src/core/mac/sub_mac.cpp
For multi-layer application, the radio requires from the upper layer
to provide information for security processing like Key Identifier,
in the Auxiliary Security Header according to IEEE802.15.4-2015.
This change matters for handling security processing by radio only.
=> [mac] always set Key Identifier for Transmit Security

include/openthread/instance.h, include/openthread/srp_client.h, src/cli/README_SRP_CLIENT.md, src/cli/cli_srp_client.cpp, src/core/api/srp_client_api.cpp, src/core/net/srp_client.cpp, src/core/net/srp_client.hpp, src/lib/spinel/spinel.h, src/ncp/ncp_base_mtd.cpp
This method clears a service from SRP client, immediately removing it
from the list. Unlike `RemoveService()` which sends an update message
to server to remove/unregister the service, this method clears the
service from client list without any interaction with server. On a
successful call to this method, the `Callback` will NOT be called and
service entry can be reclaimed and re-used by the caller immediately.
This method can be used along with a subsequent call to `AddService()`
(potentially reusing the same service entry with the same service and
instance names) to update some of the parameters in an existing
service.
This commit adds `otSrpClientClearService()` as a related public OT
API and support for this in CLI (command `service delete`). It also
adds support for the deleting …
=> [srp-client] add `Srp::Client::ClearService()`

src/core/net/ip6.cpp
When using platform TCP, the `Ip6::HandlePayload` function will be called with `aIpProto = kProtoTcp` and `aMessageOwnerShip = kTakeCustody`.
The `FreeMessage(message);` will be called with `message = nullptr` currently, causing the message to leak. This PR fixes this issue.
=> [ip6] fix message leak when using platform TCP

examples/README.md
After changed the default Thread version, the description about it has not been updated. This commit fixes it.
=> [docs] fix info about default Thread version supported by OpenThread

src/core/BUILD.gn, src/core/Makefile.am, src/core/border_router/routing_manager.cpp, src/core/common/settings.cpp, src/core/common/settings.hpp, src/core/common/settings_driver.hpp, src/core/net/srp_client.cpp, src/core/thread/dua_manager.cpp, src/core/thread/mle.cpp, src/core/utils/slaac_address.cpp, src/lib/spinel/radio_spinel_impl.hpp
This commit updates the `Settings` implementation. It adds template
versions of methods `Read<EntryType>()`, `Save<EntryType>()`, and
`Delete<EntryType>()` which make it easier for other modules to use,
while ensuing to share a common underlying implementation for all
entry types.
The settings entry types (e.g., `NetworkInfo`, `ParentInfo`, etc.) are
changed in this commit to provide a constant `kKey` specifying the
associated setting key with the entry. For simple entries, a related
class is added to define the `kKey` constant and the associated value
type (e.g., `OmrPrefix` defines `Ip6::Prefix` as its `ValueType`).
This model makes it easier to add new setting keys and entries in
future.
This commit also simplifies the logging in `Settings`. The entry types
now provide `Log()` method …
=> [settings] simplify and enhance `Settings` (reuse similar patterns)

tests/scripts/thread-cert/test_srp_lease.py
https://github.com/openthread/openthread/issues/6690 indicates that there are chances that a SRP client may not be able
to upgrade to a router in 5 seconds. This commit gives it 10 seconds to upgrade.
```txt
2021-05-27T17:51:04.6018976Z ======================================================================
2021-05-27T17:51:04.6021398Z FAIL: test (__main__.SrpRegisterSingleService)
2021-05-27T17:51:04.6022746Z ----------------------------------------------------------------------
2021-05-27T17:51:04.6024043Z Traceback (most recent call last):
2021-05-27T17:51:04.6025888Z   File "./tests/scripts/thread-cert/test_srp_lease.py", line 88, in test
2021-05-27T17:51:04.6027733Z     self.assertEqual(client.get_state(), 'router')
2021-05-27T17:51:04.6029001Z AssertionError: 'child' != 'router' …
```
=> [tests] give more time for SRP client to upgrade to router

src/core/net/udp6.cpp
The previous code will go into an infinite loop when `mEphemeralPort == Tmf::kUdpPort`, since `rval` is never updated in the loop.
```
uint16_t Udp::GetEphemeralPort(void)
{
uint16_t rval = mEphemeralPort;
do
{
if (mEphemeralPort < kDynamicPortMax)
{
mEphemeralPort++;
}
else
{
mEphemeralPort = kDynamicPortMin;
}
} while (rval == Tmf::kUdpPort);
return rval;
}
```
=> [udp] fix potential infinite loop in `Udp::GetEphemeralPort`

src/posix/platform/backbone.cpp
I found a warining in src/posix/platform/backbone.cpp.
```
inlined from ‘void platformBackboneInit(otInstance*, const char*)’ at ../../src/posix/platform/backbone.cpp:56:12:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:34: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 16 equals destination size [-Werror=stringop-truncation]
```
It can reproduce with enable backbone router function and compiling with '-O2' option.
(It may occur in other conditions, I think.)
The warning means that the length of the destination string region is the same as the max length designated by the argument, so it cannot contain a null terminator.
Just need to reduce max length.
https://www.gnu.org/software/libc/manual/html_node/Interface-Naming.html
And IFNAMSIZ …
=> [posix] fix strncpy warning about null terminated string length

src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_srp_client.cpp, src/core/utils/parse_cmdline.hpp
This commit adds a set of helper methods in `Cli` to process simple
commands where we are getting and/or setting a single `uint` value.
This replaces common pattern in processing of commands where if there
are no arguments, we output the value we retrieve by calling a related
getter OT API, otherwise we parse the argument (to get the proper
`uint` value) and call a related setter OT API. For example, for
"channel" command, we use the `otLinkGetChannel()` as the getter and
`otLinkSetChannel()` as setter.
=> [cli] adding helper `ProcessGet/Set()` to handle simpler commands

include/openthread/dataset.h, include/openthread/instance.h, src/cli/cli_dataset.cpp, src/cli/cli_dataset.hpp, src/core/api/dataset_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_types.cpp, src/core/mac/mac_types.hpp
This commit adds a new public API `otNetworkNameSet()` to set an
`otNetworkName` instance from a given null terminated C string. The new
API will also validate that the given name string follows UTF-8
encoding and its length is not longer than max network name size.
This commit also simplifies the UTF-8 validation of `NetworkName` by
moving the check from `Mac::SetNetworkName()` to a newly added method
in `Mac::NetworkName` to set it from a C string.
It also defines `DomainName` as a `typedef` of `NetworkName` which
helps simplify its use and remove repeated code.
Finally, it updates the `Cli::Dataset` to use the new public API for
validating `otNetworkName`.
=> [mac] new public API to validate and set `otNetworkName`

src/core/mac/sub_mac.cpp
https://github.com/openthread/openthread/blob/f3671d5a758a3655fb9533986c297ffc190ce080/src/core/mac/mac_frame.cpp#L582
=> [mac] avoid potential assert with SetKeyId() on an invalid frame

src/posix/platform/daemon.cpp
This commit reverts the change from PR #6639 which added logging
of the CLI output. Note that the CLI output can be generated and
outputted in smaller pieces (not as a whole line) so the model
from PR #6639 would emit each piece as a different log line which
is not desirable.
----
This is to address Issue https://github.com/openthread/openthread/issues/6665.
=> [posix] fix issue with logging CLI output

src/cli/cli_coap.cpp, src/cli/cli_coap_secure.cpp, src/cli/cli_commissioner.cpp, src/cli/cli_joiner.cpp, src/cli/cli_srp_server.cpp
This commit updates how the arguments are passed to different CLI
command handles such that the same model is now used by all CLI
modules where all the previously parsed and consumed arguments are
removed and only the remaining un-parsed arguments are passed to the
next handler.
=> [cli] harmonize passing of arguments to command handlers

tests/scripts/thread-cert/border_router/test_single_border_router.py
The assertion is verifying the (linux) host SLAAC behavior which is not guaranteed on different
platform and linux distributions. Moreover, it is required for testing the BR behavior.
=> [tests] remove unnecessary host SLAAC assertions

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_BR.py
This commit enhances THCI for 1.2 Certification:
- OpenThread.py: 1.2 non-BR
- OpenThread_BR.py: 1.2 BR and Host (`otbr-agent` solution)
This commit should also makes the THCI works for both TH1.1 and TH1.2. 
TODO:
- ~~TC involving external Commissioners (Not supported)~~
=> [thci] enhance THCI for 1.2 Certification

src/core/coap/coap_message.cpp, src/core/utils/parse_cmdline.cpp
This commit replaces uses of `strchr()` with `StringFind()`.
=> [string] use `StringFind()` in core modules

src/core/common/settings.cpp
In this PR, I have updated the ActionToString and KeyToString functions to use the correct OT_LOG_LEVEL macro guards as specified in the settings header.
=> [settings] fix OT_LOG_LEVEL macros

src/core/net/srp_client.cpp
This commit relaxes the condition for invoking the callback from SRP
client allowing it to be invoked when client is stopped.
Note that the user can call SRP client APIs to add or remove services
while it is stopped. A remove request may be processed immediately
(if the service has not yet been registered) and then the callback is
invoked to notify the caller to reclaim the service entry.
=> [srp-client] allow callback to be invoked when client is stopped

src/core/thread/mesh_forwarder.cpp
MLE Announce messages are sent with link security enabled. This commit
ensures that REEDs always send MLE Announce messages to the broadcast
destination address.
=> [mle] ensure MLE messages are sent via broadcast

tests/scripts/thread-cert/Cert_9_2_16_ActivePendingPartition.py
Add additional delay to prevent link repair using MLE Link Request on
Adv timeout.
=> [tests] fix intermittent failures in Cert_9_2_16

Android.mk, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/common/heap_string.cpp, src/core/common/heap_string.hpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, tests/unit/CMakeLists.txt, tests/unit/Makefile.am, tests/unit/test_heap_string.cpp
**[common] adding `HeapString` class (heap allocated string)**
This commit adds a new class `HeapString` (a heap allocated string).
The buffer to store the string is allocated from heap and is managed
by the `HeapString` class itself, e.g., it may be reused and/or freed
and reallocated when the string is set. The `HeapString` destructor
will always free the allocated buffer.
This commit also adds a unit test `test_heap_string` for the new
class.
**[srp-server] update to use `HeapString` for names**
=> [common] adding `HeapString` class (heap allocated string) + use in `Srp::Server`

doc/ot_api_doc.h, include/Makefile.am, include/openthread/BUILD.gn, include/openthread/instance.h, include/openthread/tcp.h
At the TCP API developer meeting (see Issue #6411), there was broad support for designing a new TCP API in the spirit of OpenThread's existing APIs that is geared toward the RAM-constrained devices that OpenThread targets. This pull request constitutes a proposal for such a TCP API.
I met with @simonlingoogle, @jwhui, @abtink, and @StuartCheshire today to learn about their ideas for a TCP API and receive their feedback on this proposal. The TODO list below describes feedback items I intend to incorporate into this API but haven't yet. Here are my slides from that meeting, which show the intended usage of this API and explain the rationale behind this API: [openthread_tcp_api_design.pdf](https://github.com/openthread/openthread/files/6340616/openthread_tcp_api_design.pdf). That said, I do …
=> Proposal for a TCP API for OpenThread

src/core/mac/sub_mac.cpp
As for:
```
semiWindow = elapsed * (Get<Radio>().GetCslAccuracy() + mCslParentDrift) / 1000000;
```
Consider that the worst `Get<Radio>().GetCslAccuracy()` and `mCslParentDrift` are both `255`, the max of `uint32` is `4294967295`, so when `elapsed` is  about `8500000`(just 8.5s elapsed since the last CSL sync), the product of `elapsed` and `(Get<Radio>().GetCslAccuracy() + mCslParentDrift)` will be overflowed.
In this PR, use the type `uint64_t` instead of `uint32_t` to avoid the overflow.
=> [csl] fix overflow in calculating semiWindow

src/core/net/srp_server.cpp, src/core/net/srp_server.hpp
This commit changes the `Srp::Server` to take ownership of resources
(e.g., heap allocated buffer for TXT data) when updating an existing
`Service` entry (instead of copying the data). With this change, the
method `Service::SetTxtData()` is no longer needed and is removed.
---
_Background on this PR_:
- Taking ownership (move semantic) would be helpful for adding service subtype
support (https://github.com/openthread/openthread/issues/6714) - We will have a list of subtype `HeapString` labels in the `Service` 
and the move model would allow us to move/merge them (instead of copy).
- I added it as a separate PR (small change) to make it easier to review. Thanks.
=> [srp-server] take ownership of resources on updating existing `Service`

src/core/net/srp_server.cpp, src/core/net/srp_server.hpp
This commit ensures that in `Srp::Server::CommitSrpUpdate()` the
`aHost` parameter is correctly freed in case of an error and an early
jump to exit (e.g., from `SuccessOrExit(aError)` at the start of this
method). The `aHost` is now freed at the `exit` label and a boolean
`shouldFreeHost` tracks whether or not it needs to be freed. The
boolean variable is set to `false` when  the ownership of `aHost` is
taken over (e.g., from the call to `AddHost(aHost)`).
=> [srp-server] free `aHost` in `CommitSrpUpdate()` in case of error

tools/otci/otci/command_handlers.py, tools/otci/otci/otci.py
This commit contains misc enhancements to OTCI:
- Allow connecting to OTBR without password
- Allow not using `sudo` for `ot-ctl` commands
- Use `--` to separate OT-CLI commands.
=> [otci] misc enhancements

src/core/config/srp_client.h, src/core/net/srp_client.cpp, src/core/net/srp_client.hpp, src/core/thread/network_data_service.hpp
This commit adds new feature in SRP client to switch server on failure
(when auto-start feature is used). When enabled, the client will try
to select the next server from entries in Thread Network Data when
the current server rejects an SRP update or there are timeouts
(no response) after multiple attempts.
=> [srp-client] add feature for switching server on failure

include/openthread/instance.h, include/openthread/udp.h, src/cli/cli_udp.cpp, src/core/api/udp_api.cpp, src/core/net/dhcp6_server.cpp, src/core/net/udp6.cpp, src/core/net/udp6.hpp
This commit forbid opening a UDP socket twice.
=> [udp] forbid udp duplicate open

tools/harness-thci/OpenThread.py
In the case where the connection is over Telnet, `self.port` will be `None`.
Closes #6748
=> [thci] remove assert which checks if the port is unicode

src/core/net/srp_server.cpp, tests/scripts/thread-cert/test_srp_server_reboot_port.py
Added a second commit to this PR. First commit changes the test to do restart:
**[test] restart SRP server (instead of device reset) to validate port change (#6763)**
This commit updates `test_srp_server_reboot_port` to just restart the
SRP sever instead of performing a full device reset. The SRP restart
will trigger the port number change by the server which is the
behavior this test-case is intended to verify. This change should
help address intermittent failures of this test.
Second commit:
**[srp-server] ensure to clear `mHasRegisteredAnyService` on server stop (#6763)**
This commit updates `Srp::Server` to clear `mHasRegisteredAnyService`
when server is stopped and all the hosts and services are deleted.
This boolean flag is used to save the port number in non-volatile
settings so …
=> [tests] restart SRP server (instead of device reset) to validate port change

examples/platforms/simulation/radio.c
This commit updates the `simulation/radio.c` and removes the uses of
core internal macro `VerifyOfExit()` and replaces them with
`otEXPECT_ACTION()`. This ensures that radio platform layer does not
include the internal OT header like "common/code_utils.hpp".
----
Related PRs:
- https://github.com/openthread/ot-nrf528xx/pull/90
=> [simulation] remove use of internal definitions/headers in radio platform

src/core/common/tlvs.cpp, src/core/common/tlvs.hpp
This commit fixes errors in `Tlv` module documentations. It also moves
the private `Tlv::Find()` description to the `cpp` file.
=> [tlv] update and fix `Tlv` documentations

tools/otci/otci/otci.py
In wait, [match_line is called with the arguments flipped](https://github.com/openthread/openthread/blob/main/tools/otci/otci/otci.py#L78). The first argument is supposed to the be the line being checked, and the second is supposed to be the pattern to match. The reason this still works for strings is because output is treated as a list of lines to expect, and each is just compared with == to the actual expected line
=> [otci] fix OTCI.wait arg order

tools/harness-thci/OpenThread.py
Enable joining a network as SSED, which is required for several Thread 1.2 certification tests.
=> [thci] add support for SSED DUT

include/openthread/instance.h, include/openthread/link.h, src/core/api/link_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp
This commit removes the API to enqueue an out of band frame for
transmission by MAC layer. This API was added as a work-around to
enable legacy (non-Thread based) frames to be sent along with Thread
frames. This model is no longer used and generally not recommended.
The preferred way to handle multi-radio/multi-protocol is to add
support for it in radio platform layer.
=> [mac] remove the out-of-band frame tx API

include/openthread/instance.h, include/openthread/srp_client.h, include/openthread/srp_client_buffers.h, src/cli/README_SRP_CLIENT.md, src/cli/cli_srp_client.cpp, src/core/api/srp_client_buffers_api.cpp, src/core/config/srp_client.h, src/core/net/srp_client.cpp, src/core/net/srp_client.hpp, src/core/utils/srp_client_buffers.cpp, src/core/utils/srp_client_buffers.hpp
This commit adds support for service subtype in `Srp::Client`. The
`otSrpClientService` now includes a pointer to an array of service
subtype labels (which can be set to `NULL` if there is no subtype).
Each subtype is appended as a PTR record (i.e., a Service Discovery
Instruction) in the SRP update message.
This commit also updates The `Utils::SrpClientBuffers` to provide an
array for the subtype labels (pointers). The default size of the
service name buffer is also incremented so that it can be used for
saving subtype label strings.
The CLI `srp client` implementation is also updated to support service
subtypes where the `<servicename>` can optionally include a list of
subtype labels separated by comma (e.g., `_ser._udp,_s1,_s2`).
----
Relates to …
=> [srp-client] add support for service subtypes

include/openthread/instance.h, include/openthread/srp_server.h, src/cli/README_SRP_SERVER.md, src/cli/cli_srp_server.cpp, src/core/api/srp_server_api.cpp, src/core/net/dnssd_server.cpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, tests/scripts/thread-cert/Makefile.am, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_srp_register_single_service.py, tests/scripts/thread-cert/test_srp_server_reboot_port.py, tests/scripts/thread-cert/test_srp_sub_type.py, tools/otci/otci/otci.py
This commit adds support for service subtypes in SRP server. It
updates the internal data model to store services in `Srp::Server`.
Every `Host` now has a list of `Service` entries along with a list of
`Service::Description` entries. These types mirror the SRP update
message format and the set of instructions that form the SRP message.
The `Service` entries represent the "Service Discovery Instructions",
i.e., the PTR records mapping a service name or a subtype name to a
service instance. A `Service::Description` entry represents the the
SRV and TXT records. A `Service` entry is always associated with a
`Service::Description` and the subtypes of the same service instance
all share the same `Service::Description` entry.
This commit also adds a new method `Host::FindNextService()` and the …
=> [srp-server] add support for service subtypes

include/openthread/instance.h, src/core/net/dns_client.cpp, src/core/net/dnssd_server.cpp, src/core/net/dnssd_server.hpp, tests/scripts/thread-cert/test_dnssd.py
This commit updates `Dns::ServiceDiscovery::Server` to add support for
browsing a service subtype. In particular, it updates the code which
breaks a DNS name into its components such that it can correctly
parse and accept a service subtype name. It also updates how the
service name compression is done to handle the subtype names.
This commit also updates `Dns::Client` to remove the extra check of
service name (which is already verified) when trying to find a PTR
record for a given service instance name. This change enables browse
for service subtype (parsing the browse response).
This commit also updates and enhances the `test_dnssd.py` script
adding test-cases for browsing for service subtype.
----
This related to  issue 
- #6714
This PR includes the commits from 
-  #6760
-  #6724 …
=> [dnssd] add support for service subtypes in DNS-SD server and client

src/core/net/srp_server.cpp
We should remove the `UpdateMetadata`  before committing the SRP update to ensure that
the same `UpdateMetadata` (and the `Host` object) can never be touched again.
=> [srp-server] avoid re-accessing committed SRP updates

script/check-simulation-build-autotools, script/check-simulation-build-cmake
The default Thread version has been set to 1.2 when building. Our test
script which checks building hasn't been updated accordingly. Currently it
specifies the version when it 1.2 is wanted and doesn't specify it when 1.1
is wanted. However, if THREAD_VERSIOn is not specified, the version would be
1.2. This PR fixes this error.
=> [script] fix Thread version for check-simulation-build

src/core/thread/dua_manager.cpp
Fixes #6796 
Verified that this commit fixes the infinite DUA.req loop.
This is a quick fix. We still need to reactor `mChildIndexDuaRegistering` because there are still potential issues.
=> [dua] fix infinite DUA.req loop

src/core/thread/link_metrics.cpp, tests/scripts/thread-cert/v1_2_LowPower_7_1_01_SingleProbeLinkMetricsWithEnhancedAcks.py
When the Initiator requests a reserved Metric Type ID Flag the status value should be "Value 254: Failure – Other failure".
=> [link-metrics] fix Link Metrics Status Sub-TLV value

tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/v1_2_test_domain_unicast_address_registration.py
Modify DUA registration test to check that ML-EID TLV content is as expected for every DUA.req sent.
It catches https://github.com/openthread/openthread/issues/6796
Depends on:
=> [dua] increase DUA registration test coverage

tools/harness-thci/OpenThread.py
Some Thread 1.2 tests require that REED DUTs upgrade to Router. Allow it while keeping existent functionality for reference devices.
=> [thci] allow REED DUTs to upgrade

src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_srp_lease.py
The SRP draft 09 spec suggests that the SRP Servers SHOULD also track a lease time per service instance. 
>SRP Servers SHOULD also track a lease time per service instance.  The
reason for doing this is that a client may re-register a host with a
different set of services, and not remember that some different
service instance had previously been registered.  In this case, when
that service instance lease expires, the SRP server SHOULD remove the
service instance (although the KEY record for the service instance
SHOULD be retained until the key lease on that service expires).
This is beneficial because if the SRP client continues to renew the
host, but never mentions the stale service again, the stale service
will continue to be advertised.
=> [srp-server] track lease time per service instance

src/core/meshcop/meshcop_tlvs.hpp, src/core/thread/mle_router.cpp
Commercial Commissioning Mode flag from the Security Policy has to be set in the Discovery Response TLV of the MLE Discovery Response messages.
=> [mle] include the CCM flag in the Discovery Response

include/openthread/dns_client.h, include/openthread/instance.h, src/core/config/dns_client.h, src/core/net/dns_client.cpp, src/core/net/dns_client.hpp, src/core/net/srp_client.cpp, src/core/net/srp_client.hpp, tests/scripts/thread-cert/Makefile.am, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_dns_client_config_auto_start.py
This commit adds a new feature in DNS client to automatically set and
update the server's IPv6 address in the default config. This is done
only when user does not explicitly set or specify the server address.
This behavior requires SRP client and its auto-start feature to be
enabled. SRP client will then monitor the Thread Network Data for
DNS/SRP Service entries to select an SRP server. The selected SRP
server address is also set as the DNS server address in the default
config.
This commit also adds `test_dns_client_config_auto_start.py` which
verifies the behavior of the new feature. In particular, that the DNS
client's default config gets changed and mirrors the SRP client
selected server address (when not set by user) and that it remains
unchanged if user explicitly sets the address …
=> [dns-client] feature to auto set the default server address

src/core/thread/network_data_leader.cpp, src/core/thread/network_data_types.cpp, tests/scripts/expect/cli-misc.exp, tests/scripts/thread-cert/Makefile.am, tests/scripts/thread-cert/test_zero_len_external_route.py
This commit allows a zero-len prefix `::/0` to be added as an external
route in Network Data. Such a prefix can act as a default route.
=> [netdata] allow zero-len external route prefix

src/core/thread/mle_router.cpp, src/core/thread/network_diagnostic.cpp
`MleRouter::GetMaxChildTimeout` relies on the initial value of `maxTimeout`. This adds the correct initialization.
=> [network-diagnostic] fix initialization of max child timeout

src/core/config/tmf.h
The latest Thread Specification changes ADDRESS_QUERY_MAX_RETRY_DELAY
to 120 seconds.
See [SPEC-987](https://threadgroup.atlassian.net/browse/SPEC-987)
=> [address-resolver] change max retry delay to 120 seconds

src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager.hpp
This commit fixes a couple issues with sending MGMT_SET.req to update
the leader with a new operational dataset.
- When handling an MLE Child ID Response message,
DatasetManager::Save() is called before the role is updated to
child. As a result, a device with a newer dataset prior to attaching
the network will not send a MGMT_SET.req message. This commit adds a
delay to allow the role to change to child.
- When receiving a MGMT_SET.rsp, the device will immediately check if
it should send a MGMT_SET.req message again. However, the
operational dataset may not have had a chance to propagate from the
leader. This commit adds additional delay to allow the new
operational dataset to propagate.
Fixes #6804
=> [meshcop] fix issues in sending updated datasets to leader

include/openthread/diag.h, include/openthread/instance.h, include/openthread/platform/diag.h, src/cli/cli.cpp, src/ncp/ncp_base.cpp
This PR initializes the `output` buffer to all zero.
The output buffer isn't initialized to all zero currently. This makes it possible that `OutputFormat` prints some random bytes at the end of the original output generated by processing the command.
I checked the output buffer by dumping the buffer:
**Before processing command:**
**After processing command:**
So it is possible that non `\0` characters come after the output and cause incorret output at the end. (In the above case, it happens to be `\0` after the output.)
=> [diag] don't let the client of diag reserve the '\0' byte

src/core/common/instance.hpp, src/core/common/timer.cpp, src/core/common/timer.hpp, tests/unit/test_timer.cpp
**[timer] declare `Scheduler` as nested type of `Timer`**
This commit refactors and simplifies the `Timer` module, mainly
declaring the corresponding `Scheduler` as a nested type of `Timer`,
`TimerMilli` or `TimerMicro` classes. It also changes the `Scheduler`
methods to be `protected` or `private` limiting access to them.
----
**[timer] add `RemoveAll()` method for use by unit test**
This commit adds a new static method `Timer::RemoveAll()` which
removes all running timers from the `Scheduler`. This method is only
intended for use by by `test_timer` unit test, allowing it to remove
any timers that may be started from constructors of different objects
in an OT instance before starting the unit test. With this change, we
can have timers started from …
=> [timer] simplify `Scheduler`, add `RemoveAll()`, and update unit test

src/posix/platform/backbone.cpp, src/posix/platform/multicast_routing.cpp, src/posix/platform/multicast_routing.hpp, src/posix/platform/platform-posix.h, src/posix/platform/system.cpp
This fixes the infinite loop when OTBR is pseudo-reset by DBus API.
=> [backbone-router] add deinit API

Android.mk, include/openthread/instance.h, include/openthread/tcp.h, src/cli/BUILD.gn, src/cli/CMakeLists.txt, src/cli/Makefile.am, src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_config.h, src/cli/cli_tcp.cpp, src/cli/cli_tcp.hpp
This is the second in a series of pull requests (after #6744) bringing TCPlp to OpenThread. I'm making a series of small pull requests so that it's easier for the OpenThread community to review the code. If you'd like to preview a working version of TCPlp in OpenThread, see #6650.
This pull request adds support for TCP in OpenThread's CLI tool. As TCP isn't implemented, the TCP functions don't work yet, but the code complies and links due to the stubs added in the previous pull request (#6744). It's separated into three commits: one that restores functionality in the `Interpreter` class removed in #6691, one that implements a basic CLI tool, and one that adds a benchmark utility to the CLI tool.
The next pull request in the sequence, which implements TCP functionality, doesn't depend on …
=> [cli] add support for TCP in the CLI tool

src/posix/platform/infra_if.cpp
This commit fixes a potential bug that the netlink socket may fail to bind due to port ID conflict.
[man 7 netlink](https://man7.org/linux/man-pages/man7/netlink.7.html):
```
If the application sets nl_pid before calling bind(2), then it is up to 
the application to make sure that nl_pid is unique. If the application
sets it to 0, the kernel takes care of assigning it.
```
=> [posix] allow kernel to assign netlink socket port ID

examples/apps/cli/cli_uart.cpp, src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_config.h
This commit adds `OPENTHREAD_CONFIG_CLI_LOG_INPUT_OUTPUT_ENABLE`
option which configures the CLI module to log its input command
string and the resulting output. This is done in addition to emitting
the output string to the console. By default this config is enabled
on all POSIX based platforms and when `LOG_OUTPUT` is not set to use
CLI console itself.
--------
Notes:
- This should hopefully help with debugging test failures (e.g., on github 
workflows).
- Suggested this model from https://github.com/openthread/openthread/issues/6665#issuecomment-855443633
(related to https://github.com/openthread/openthread/pull/6639 which caused
the the CLI output to be logged in pieces).
- The implementation in this PR emits the CLI output line by line to the log 
(each output line is emitted as a …
=> [cli] new config to log input command and the resulting output

src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_local.cpp, src/core/thread/network_data_service.cpp, src/core/thread/network_data_service.hpp, tests/unit/test_network_data.cpp
This commit relaxes BBR dataset matching to only compare the first byte of Service Data (i.e. `0x01`). 
This commit also requires all Service TLV searching methods to explicitly specify `aExactServiceDataMatch` argument, helping to reduce unconscious mistakes.
=> [backbone-router] relax matching BBR dataset

tests/scripts/thread-cert/Cert_9_2_09_PendingPartition.py
Keeping network id timeout at 70 can result in ROUTER2 occasionally
creating its own partition. Reset back to 120 to avoid occasional test
failures.
Fixes #5992
=> [tests] fix intermittent failure in Cert_9_2_09_PendingPartition.py

src/posix/platform/system.cpp
This commit fixes the platform UDP compile error when platform Netif is not enabled.
=> [posix] fix platform UDP init compile error

src/posix/platform/netif.cpp
Fixes https://github.com/openthread/ot-br-posix/issues/931.
In the issue, compiler complained we were copying 16 bytes to a location of 12 bytes. This was because in the check, the compiler thought we are going to copy data to a `nlmsghdr` which is 12 bytes. The reality is that we're copying data to a place behind `nlmsghdr` in `req` struct.
=> [posix] fix memcpy compiler warning false positive

src/core/border_router/routing_manager.cpp, src/core/common/logging.hpp
Dump the RA messages sent/received on infra if for testing scripts.
This commit removes the requirement of `OT_REFERENCE_DEVICE`
but always dump the RA messages at log level `DEBG`.
=> [border-routing] dump sent/received RA messages on infra if

src/cli/cli.cpp
This commit updates the CLI modules to use `OutputExtAddress()`
when printing an `otExtAddress`. It also simplifies the uses of
`OutputBytes()`.
=> [cli] use `OutputExtAddress()`

src/lib/spinel/radio_spinel_impl.hpp
This commit fixes a bug in `RadioSpinel` platform implementation where
the request from OT core stack to enter RX mode may be ignored
causing the RCP/radio to stay in RX mode on an incorrect channel.
This situation can happen after a frame TX request on a different
channel (note that the `otRadioFrame` struct specifies the channel on
which the frame should be transmitted). After frame TX, radio driver
is expected to enter RX mode on the same channel on which the frame
TX happened. The OpenThread MAC layer always explicitly instructs the
radio to enter RX mode on the PAN channel (from `Mac::UpdateIdleMode()`
which in turn calls the radio platform API `otPlatRadioRecive()` with
the channel passed in as a parameter). The earlier `RadioSpinel`
platform implementation cached the channel in a …
=> [radio-spinel] fix incorrect RX channel after frame TX on another channel

examples/platforms/simulation/CMakeLists.txt, examples/platforms/simulation/Makefile.am, examples/platforms/simulation/infra_if.c, tests/unit/test_platform.cpp
This commit adds empty implementations of `otPlatInfraIf` platform
APIs under simulation. It also adds `otPlatInfraIfHasAddress()` in
`test_platform`. This allows the unit tests and simulation platform
builds to succeed when `OPENTHREAD_CONFIG_BORDER_ROUTING_ENABLE` is
enabled.
=> [simulation] add empty `otPlatInfraIf` platform APIs in simul/test

src/posix/platform/multicast_routing.cpp
The OpenThread instance has already been deinitialized before the platform
`MulticastRoutingManager` is deinitialized. We can never reference to `mInstance` in `Deinit`.
=> [backbone-router] fix deinit MulticastRoutingManager

script/check-android-build, src/core/api/instance_api.cpp
This commit adds a macro for specifying OpenThread build date time,
which can be empty so that this field can be omitted.
=> [build] allow specify build date time

src/core/mac/channel_mask.hpp, src/core/mac/data_poll_handler.hpp, src/core/mac/data_poll_sender.hpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_filter.hpp, src/core/mac/mac_frame.hpp, src/core/mac/mac_links.hpp, src/core/mac/mac_types.hpp, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/radio/radio.hpp
This commit replaces the `enum` constants with `constexpr` definitions
in all the modules under `core/mac`. The `constexpr` constants have
the advantage that thet are explicitly typed while still being
compile-time constants with no code size overhead.
This commit also contains some smaller changes: typo fixes in the
comments, removal of unused constants, and adding type to the named
`enum` definitions.
---
We originally used `enum` for constants due to OT complying to 
`C++03`  which we transitioned to `C++11` from PR https://github.com/openthread/openthread/pull/5077.
=> [mac] replace `enum` constants with `constexpr`

src/core/api/link_metrics_api.cpp, src/core/common/instance.hpp, src/core/mac/mac.cpp, src/core/thread/link_metrics.cpp, src/core/thread/link_metrics.hpp, src/core/thread/link_metrics_tlvs.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/thread_netif.hpp, src/core/thread/topology.cpp, src/core/thread/topology.hpp
This commit contains style changes, simplifications, and renames in
Link Metrics modules.  It moves all the definitions under a new
namespace `LinkMetrics` which allows the use of shorter and simpler
names for types, methods, and constants (omit the `LinkMetrics`
prefix from names). For example, `LinkMetricsTypeIdFlags` and
`LinkMetricsSeriesInfo` are renamed to simpler `TypeIdFlags` and
`SeriesInfo` respectively.
=> [link-metrics] renames, using namespace, and style changes

src/core/api/coap_api.cpp, src/core/coap/coap.hpp, src/core/coap/coap_message.hpp, src/core/common/crc16.hpp, src/core/common/logging.cpp, src/core/common/message.hpp, src/core/common/notifier.hpp, src/core/common/settings.hpp, src/core/common/time.hpp, src/core/common/time_ticker.hpp, src/core/common/tlvs.hpp, src/core/common/trickle_timer.hpp, src/core/crypto/aes_ccm.hpp, src/core/crypto/aes_ecb.hpp, src/core/crypto/ecdsa.hpp, src/core/crypto/pbkdf2_cmac.hpp, src/core/crypto/sha256.hpp, src/core/diags/factory_diags.cpp, src/core/diags/factory_diags.hpp
This PR contains a set of separate commits changing the constants 
to use `constexpr` instead of `enume` under under different 
sub-folders: `coap`, `common`, `crypto` and `diags`.
=> [core] replace `enum` constants with `constexpr`

src/core/BUILD.gn, src/core/Makefile.am, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/common/array.hpp, tests/unit/CMakeLists.txt, tests/unit/Makefile.am, tests/unit/test_array.cpp
**[routing-manager] Use `Array` for list of OMR or on-link prefixes**
This commit simplifies the `RoutingManager` class by using `Array`
to store lists of new or advertised OMR/on-link prefixes.
**[common] adding `Array` class**
This commit adds a generic `Array<Type, kMaxSize>` class which
represents a fixed size array of elements of template `Type` which
tracks its current length. Entries can be appended to the array
(`PushBack()`) and removed from the end of array (`PopBack()`). This
simple data model is used in some other modules, so having a generic
version can help simplify the code. This commit also adds a unit test
to verify `Array` methods.
=> [routing-manager] add `Array` & use it for OMR/on-link prefix list

src/cli/README_TCP.md
This is the fourth in a series of pull requests (after #6744, #6770, and #6790) bringing TCPlp to OpenThread. I'm making a series of small pull requests so that it's easier for the OpenThread community to review the code. If you'd like to preview a working version of TCPlp in OpenThread, see #6650.
This pull request adds a README_TCP.md file containing documentation for the TCP CLI functionality. This was requested in the review of Pull Request #6770.
=> [cli] add README for TCP CLI tool

examples/platforms/utils/logging_rtt.h, include/openthread/instance.h, include/openthread/platform/memory.h
When compiling OpenThread public header files independently, the
compiller generates errors, such as `unknown type name "size_t"`
and 'unknown type name "otLogLevel"'.
This commit adds the corresponding header files to the public
headers to resolve this issue.
=> [include] resolve the unknown type name issue

tests/scripts/thread-cert/border_router/test_dnssd_server.py, tests/scripts/thread-cert/border_router/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/test_multi_thread_networks.py, tests/scripts/thread-cert/border_router/test_plat_udp_accessiblity.py
This commit simplifies the border router tests by replacing
`self.nodes[<NODE_ID>]` with shorter names.
=> [tests] simplify border router tests

src/core/net/checksum.hpp, src/core/net/dhcp6.hpp, src/core/net/dhcp6_client.hpp, src/core/net/dhcp6_server.hpp, src/core/net/dns_client.hpp, src/core/net/dns_types.cpp, src/core/net/dns_types.hpp, src/core/net/dnssd_server.hpp, src/core/net/icmp6.hpp, src/core/net/ip4_address.cpp, src/core/net/ip4_address.hpp, src/core/net/ip6.hpp, src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, src/core/net/ip6_filter.hpp, src/core/net/ip6_headers.hpp, src/core/net/ip6_mpl.hpp, src/core/net/netif.hpp, src/core/net/sntp_client.cpp, src/core/net/sntp_client.hpp, src/core/net/socket.hpp, src/core/net/srp_client.cpp, src/core/net/srp_client.hpp, src/core/net/srp_server.hpp, src/core/net/tcp6.hpp, src/core/net/udp6.hpp
This commit replaces the `enum` constants with `constexpr` definitions
in all the modules under `core/net`. This commit also contains some
smaller changes: typo fixes in the comments, removal of unused
constants, and adding `uint` type to the named `enum` definitions.
=> [net] replace `enum` constants with `constexpr`

src/core/common/array.hpp, src/core/common/type_traits.hpp, tests/unit/test_array.cpp
This commit enhances the template `Array` class implementation to
allow the `uint` type used for array size (which is also used for
length and index) to be specified as a template type parameter. If
not explicitly specified, a default `uint` type is selected based on
the array size `kMaxSize`, i.e., if `kMaxSize <= 255` then `uint8_t`
will be used, otherwise `uint16_t` will be used.
------------
Added a second related commit in this PR:
**[array] add `FindMatching()` and `ContainsMatching()` (#6872)**
This commit adds template `Find/ContainsMatching<Indicator>()` methods
which search in the array to find the first element matching a given
indicator. Unit test `test_array` is also updated to check the
behavior of newly added methods.
=> [array] select the index/length `uint` type based on array size

src/core/thread/mesh_forwarder_ftd.cpp
This commit fixes a bug in `RemoveDataResponseMessages()` where
`GetNext()` method may be called on an already dequeued and freed
`Message` instance (within the `for` loop iteration). The change in
this commit ensures to get and retain the `next` message before
potentially removing the message from the `mSendQueue` and freeing
it.
=> [mesh-forwarder] fix `RemoveDataResponseMessages()` accessing freed msg

src/core/coap/coap_secure.cpp
This commit fixes an issue in `CoapSecure::Stop()` accessing an
already dequeued and freed `Message` instance (from the `for` loop
iteration trying to `GetNext()` message). The code in this commit
removes the head element one by one (`MessageQueue::GetHead()`)
until the queue becomes empty.
=> [coap] fix `CoapSecure::Stop()` accessing freed message instance

tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py
The test failed frequently because I forgot to add a delay before checking the meshcop service.
=> [tests] fix test_publish_meshcop_service.py

tools/otci/otci/command_handlers.py, tools/otci/otci/otci.py
This allows for registering a callback on all lines read from a device, making it possible to react to output from asynchronous cli commands while concurrently executing new commands on the same device. Normally, executing those new commands would result in the async command output being lost.
Known caveats:
1. The same limitations as with wait apply to `OtbrSshCommandRunner` (you can't get async output)
2. For `OtCliCommandRunner`, any commands sent to the device in the callback need to be offloaded to another thread. Otherwise the read routine thread will be blocked, and the command will timeout
=> [otci] allow callbacks on all read lines

src/core/thread/mle.cpp
This commit fixes methods `SendLinkMetricsManagementResponse()`,
`SendLinkMetricsManagementRequest()` and `SendLinkProbe()` in `Mle`
to ensure that the allocated MLE message is freed on an error. Note
that on success the `Mle::SendMessage()` will take the ownership of
the allocated `Message`.
=> [mle] ensure Link Metrics methods free newly allocated msg on error

tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py
This PR aims to update the meshcop service instance name in `test_publish_meshcop_service.py` to make it consistent with the change on ot-br-posix side. This should be merged at the same time with openthread/ot-br-posix#946.
Depends-On: openthread/ot-br-posix#946
=> [tests] update meshcop service instance name in test case

src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/thread/mle.cpp
This commit introduces two changes. First is adding capablility to turn
off CSL, by implementing missing 0 value handling.
Secondly adds proper transition between SSED (CSL on) and MED states
(CSL off).
=> [csl] fix switch between SSED -> MED -> SSED modes

script/test, src/core/config/dnssd_server.h, src/core/net/dnssd_server.cpp, src/core/net/dnssd_server.hpp, src/core/net/udp6.cpp
This commit allows DNS-SD server to configure the network interface to bind the UDP socket.
=> [dns-sd] add DNS-SD server network interface binding configuration

include/openthread/instance.h, include/openthread/tcp.h, src/core/net/tcp6.cpp, src/core/net/tcp6.hpp
This commit contains smaller style/code changes in `tcp6` modules.
=> [tcp] style changes, typo fixes, and smaller changes

configure.ac, examples/apps/cli/Makefile.am, examples/apps/ncp/Makefile.am, src/posix/Makefile.am, tests/fuzz/Makefile.am, tests/unit/Makefile.am, third_party/CMakeLists.txt, third_party/tcplp/CMakeLists.txt, third_party/tcplp/Makefile.am, third_party/tcplp/README.md
This is the fifth in a series of pull requests (after #6744, #6770, #6790, and #6857) bringing TCPlp to OpenThread. I'm making a series of small pull requests so that it's easier for the OpenThread community to review the code. If you'd like to preview a working version of TCPlp in OpenThread, see #6650.
This pull requests creates a module in `third_party` for TCPlp code. It is a placeholder for now; the actual code will be added in future pull requests. In reviewing this pull request, please focus on the changes I've made to Makefiles to add the new `third_party` module. For now, the `tcplp.a` archive doesn't actually contain any code.
=> [tcp] add third_party module for TCPlp

src/core/net/srp_server.cpp, tests/scripts/thread-cert/test_dnssd.py
When a new service with subtypes is added to an existing
host, the SRP server incorrectly merges the subtype service
copies so that the TXT information is lost, i.e. 0-length
TXT record is created.
Moreover, the OT DNS client cannot parse services with
0-length TXT record (instead of ignoring the TXT record
itself) causing that such a service cannot be examined
at all.
The problem is caused by incorrect merging of the service
description structure which is shared across all services
with the same instance name (i.e. among the base type
service and its subtypes).
Fixes #6900.
Signed-off-by: Damian Krolik <damian.krolik@nordicsemi.no>
=> [srp-server] fix adding service with subtypes to existing host

src/core/config/srp_client.h, src/core/net/srp_client.cpp, src/core/net/srp_client.hpp
This commit adds a new config in `Srp::Client` which specifies whether
the SRP client is allowed to switch server (when auto-start feature
is enabled) on timeouts when host or service info were previously
successfully registered with the currently selected server. Note that
independent of this config, auto-start will always switch and select
a new server when the entry in the Network Data corresponding to the
currently selected server gets removed.
-------
@jwhui, @simonlingoogle, @wgtdkp  we had an internal discussion related to
this a while back. I wrote this and added this config back then (from commit
date I think it was around Jul 14), I just noticed that I forgot to submit it as a 
PR (I need a better model to track my branches 😄)
I kept the default behavior as is (i.e. we don't …
=> [srp-client] config to allow/disallow server switch if host is registered

src/core/common/logging.cpp, src/core/common/logging.hpp
This commit simplifies the logging macros by removing the input
string parameter `aRegionPrefix` in the call to the underlying log
function and instead converts the `aLogRegion` to the proper string
from the private `Log()` function. The removal of the additional
argument in the call to the logging functions helps reduce the
overall code size. This is applicable to the default and commonly
used configuration where logging uses functions. In the case where
logging is fully implemented as macros the `aRegionPrefix` is still
needed and used.
=> [logging] simplify logging functions

include/openthread/instance.h, include/openthread/platform/udp.h, include/openthread/udp.h, src/cli/README_UDP.md, src/cli/cli_udp.cpp, src/core/api/udp_api.cpp, tools/otci/otci/__init__.py, tools/otci/otci/otci.py, tools/otci/otci/types.py, tools/otci/tests/test_otci.py
This commit binds the CLI UDP socket to an unspecified interface. 
CLI UDP failed to send/receives UDP messages to/from infrastructure devices since the socket is bound to the Thread interface.
=> [cli-udp] bind CLI UDP socket to unspecified interface

src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit changes MLE module such that during an attach attempt in
the third phase where we send MLE Announce on all channels we wait
till the end of the phase (i.e., after MLE Announce tx on all
channels and transition from `kAttachStateAnnounce`) to process any
received "Parent Response" and try to attach to a parent. This
ensures that we wait long enough to receive "Parent Response" from
all potential parents during this phase. Note that at the start this
phase we send an extra "Parent Request to routers/REEDs" to have
another chance to find a parent.
=> [mle] wait till end of announce tx on all channels to attach

examples/platforms/simulation/radio.c, include/openthread/instance.h, include/openthread/platform/radio.h, src/core/mac/data_poll_handler.cpp, src/core/mac/mac.cpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/mac/mac_links.hpp, src/core/mac/sub_mac.cpp, src/core/thread/csl_tx_scheduler.cpp, src/lib/spinel/radio_spinel_impl.hpp, src/lib/spinel/spinel.h, src/ncp/ncp_base_radio.cpp
When a platform provides `OT_RADIO_CAPS_TRANSMIT_SEC` capability,
it updates the frame header with the dynamic data (frame counter,
key id...) and returns it back to MAC together with the transmission
result.
So far the `mIsARetx` flag was being used to instruct the radio
whether to update the header or not, but there was no mean to know
if the radio was able to do so.
This commit introduces the `mIsHeaderUpdated` flag with is used in
both directions, so the MAC layer can react to cases in which the
frame header was not properly updated by the radio plaform.
The usage of `mIsARetx` remains restricted now to two cases:
- When a SSED decides to re-synchronize CSL parameters after a
retransmission.
- To check if sequence number was set for CSL/indirect retransmissions.
=> [mac] add `mIsHeaderUpdated` frame flag

src/posix/platform/openthread-core-posix-config.h
The compile-time log level definition is the lowest log level
that can be set by `otLoggingSetLevel`. This is useful for
dumping more logs for testing.
=> [posix] set compile-time minimum log level to debug

tests/scripts/thread-cert/border_router/MATN_12_HopLimitProcessing.py, tests/scripts/thread-cert/node.py
The test failed because the script failed to read the output of `ipaddr rloc`. I suspect it can be fixed by adding some wait time at the end of the test.
=> [tests] attempt to fix intermittent failures of MATN-12

src/core/meshcop/border_agent.hpp, src/core/meshcop/commissioner.hpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_manager.hpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/dataset_updater.hpp, src/core/meshcop/dtls.hpp, src/core/meshcop/joiner.hpp, src/core/meshcop/joiner_router.hpp, src/core/meshcop/meshcop.hpp, src/core/meshcop/meshcop_leader.hpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/meshcop/timestamp.hpp
This commit replaces the `enum` constants with `constexpr` definitions
in all the modules under `core/meshcop`. This commit also contains
some smaller changes: removal of unused constants, and adding `uint`
type to the named `enum` definitions.
=> [meshcop] replace `enum` constants with `constexpr`

src/core/utils/channel_manager.hpp, src/core/utils/channel_monitor.hpp, src/core/utils/child_supervision.hpp, src/core/utils/flash.hpp, src/core/utils/heap.hpp, src/core/utils/jam_detector.hpp, src/core/utils/ping_sender.hpp, src/core/utils/slaac_address.hpp, src/core/utils/srp_client_buffers.hpp
This commit replaces the `enum` constants with `constexpr` definitions
in all the modules under `core/utils`. This commit also contains
some smaller changes: typo fixes in the comments, removal of unused
constants, and adding `uint` type to the named `enum` definitions.
=> [utils] replace `enum` constants with `constexpr`

include/openthread/border_router.h, include/openthread/instance.h, src/cli/README.md, src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_network_data.cpp, src/cli/cli_network_data.hpp, src/core/api/border_router_api.cpp, src/core/border_router/router_advertisement.hpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, tests/scripts/thread-cert/border_router/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/test_multi_thread_networks.py, tests/scripts/thread-cert/border_router/test_radvd_coexist.py, tests/scripts/thread-cert/border_router/test_single_border_router.py, tests/scripts/thread-cert/border_router/test_vicarious_router_solicit.py, tests/scripts/thread-cert/node.py
This change includes three separate commits:
Per RFC 4862 section 5.5.3, the SLAAC address of a on-link prefix
will not immediately be invalidated even if the on-link prefix is
sent with zero PIO valid lifetime but we currently removes the
external route for the on-link prefix when we see zero valid lifetime.
This results in an error case that a Thread device can not reach
a valid SLAAC address of a Wi-Fi host on the same infra link because
there is no routes for this address.
This commit fixes this issue by delay removing the external route
for the discovered on-link prefix untill its valid lifetime expires.
Meanwhile, the Border Router now considers a deprecated (zero preferred
lifetime) on-link prefix not usable. Thus, the Border Router will
start advertising its own on-link prefix …
=> [routing-manager] delay removing external route for on-link prefix

src/core/border_router/router_advertisement.cpp, src/core/border_router/router_advertisement.hpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/net/dns_client.cpp, src/core/thread/network_data_tlvs.hpp, src/core/thread/network_data_types.cpp, src/core/thread/network_data_types.hpp
This commit adds helper functions to convert a `RoutePreference`
to/from a 2-bit unsigned encoded value. These are used in
`NetworkData` (for on-mesh prefix or external route) and also in
`RoutingManager` and `RouterAdv`. This change ensures that we do not
use bitwise shift of a signed and potentially negative value (`a >> b`
where `a` is negative). Note that the behavior of right bitwise shift
of a negative value is not specified by C++ standard and it is
implementation/toolchain dependent.
=> [netdata] add `RoutePreference` and related helper functions

src/posix/main.c, src/posix/platform/backbone.cpp, src/posix/platform/daemon.cpp, src/posix/platform/daemon.hpp, src/posix/platform/include/openthread/openthread-system.h, src/posix/platform/infra_if.cpp, src/posix/platform/infra_if.hpp, src/posix/platform/multicast_routing.cpp, src/posix/platform/multicast_routing.hpp, src/posix/platform/netif.cpp, src/posix/platform/platform-posix.h, src/posix/platform/system.cpp, src/posix/platform/udp.cpp, src/posix/platform/udp.hpp
This commit refines system initialization and deinitialization by separating the process before and after OpenThread instance creation and destruction:
```
otSysInit():
Call platformInit()
Create OpenThread Instance as `gInstance`
Call platformSetUp()
otSysDeinit():
Call platformTearDown()
Destroy OpenThread Instance `gInstance`
Call platformDeinit()
```
This commit should help fix the issue that platform UDP sockets can not be created when constructing OpenThread instance. 
This commit contain other related changes:
- otSysDeinit now destroyes the OpenThread instance
- posix/platform code use a global variable `gInstance` to track the single global OpenThread instance, instead of using multiple pointers in multiple files. 
Depends-On: openthread/ot-br-posix#954
=> [posix] refine system initialization and deinitialization

src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager.hpp
The CoAP response handler may pass nullptr if an error occurs.
=> [dataset-manager] avoid nullptr dereference

include/openthread/instance.h, include/openthread/thread.h, src/core/thread/discover_scanner.cpp, src/core/thread/discover_scanner.hpp, tests/scripts/expect/cli-scan-discover.exp
This commit updates `Mle::DiscoverScanner` to check that IPv6
interface is enabled from `Discover()` (returns `kErrorInvalidState`
if netif is not up).
=> [mle] check netif is up before processing discover scan

tests/scripts/thread-cert/test_netdata_publisher.py
This commit updates the `test_netdata_publisher` to add extra wait
time between adds (where the same on-mesh prefix is published on all
routers). This should help make the test robust and avoid the
situation where publishing the same prefix on all routers all
together could cause the number of entries in the Network Data to
temporarily go above the desired number. This can happen (though not
often) due to the randomness in how/when nodes using `Publisher` add
their entry in the Network Data.
----
This should help fix #6922. 
Please see https://github.com/openthread/openthread/issues/6922#issuecomment-898743403 for more details.
=> [test] extra wait on multiple prefix add in `test_netdata_publisher`

src/core/mac/mac.cpp, src/core/mac/mac.hpp
This commit updates `Mac` under `MULTI_RADIO` config to limit the
radio links used when sending a MAC Beacon frame (which uses
broadcast destination and therefore by default would be sent on all
radios) to the same radio links from which the triggering Beacon
Request frame(s) were received. This ensures that when a multi-radio
node scans another multi-radio node we get one Beacon response on
each radio link.
=> [mac] tx beacon on the same radio as the request in multi-radio config

src/core/ftd.cmake, src/core/mtd.cmake, third_party/tcplp/CMakeLists.txt
This is the sixth in a series of pull requests (after #6744, #6770, #6790, #6857, and #6885) bringing TCPlp to OpenThread. I'm making a series of small pull requests so that it's easier for the OpenThread community to review the code. If you'd like to preview a working version of TCPlp in OpenThread, see #6650.
This pull request changes the Makefiles so that the TCPlp module is linked in to the code when building OpenThread using CMake. This is necessary when `script/build` or `script/cmake-build` is used to build OpenThread.
=> [tcp] link third_party TCPlp module in CMake build

src/core/net/netif.hpp, src/core/thread/mle.cpp
This commit updates `Mle::SetRloc16()` to skip removing and re-adding
of the `mMeshLocal16` IPv6 address when it does not change.
It also updates how the cached COAP messages are cleared such that
they are cleared only if the address gets changed.
=> [mle] skip removing and re-adding of RLOC IPv6 address on no change

src/ncp/ncp_base_mtd.cpp
With current usage of `auto`, `flag` is a copy of the entries in `kFlags`, which causes an extra copy.
=> [ncp] fix auto in enhanced loop

src/core/api/ip6_api.cpp, src/core/backbone_router/bbr_local.hpp, src/core/meshcop/border_agent.hpp, src/core/meshcop/commissioner.hpp, src/core/net/dhcp6_client.cpp, src/core/net/dhcp6_client.hpp, src/core/net/dhcp6_server.hpp, src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/net/nd_agent.hpp, src/core/net/netif.cpp, src/core/net/netif.hpp, src/core/thread/address_resolver.cpp, src/core/thread/dua_manager.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mlr_manager.cpp, src/core/thread/network_diagnostic.cpp, src/core/utils/slaac_address.cpp, src/core/utils/slaac_address.hpp, tests/unit/test_netif.cpp
This commit renames and moves the related types in `Netif` module like
`UnicastAddress`, `MulticastAddress`, etc. under `Netif` class (as a
nested type). It also moves iterator types under the related type
(for example, `ExternalMulticastAddressIteratorBuilder` becomes
`Iterator::Builder` under `ExternalMulticastAddress` class. These
changes help simplify the code (allow us to use shorter names in the
`Netif` implementation).
=> [netif] define related types (unicast/mcast addr, iterator) as nested types

include/openthread/instance.h, include/openthread/thread_ftd.h, src/core/thread/mle_router.cpp, src/core/thread/neighbor_table.cpp, src/core/thread/neighbor_table.hpp, src/core/thread/router_table.cpp, src/core/thread/topology.cpp, src/core/thread/topology.hpp, src/core/utils/otns.cpp
This commits adds a new `otNeighborTableEvent` which indicates that a
child's Device Mode is changed (in addition to existing events which
indicate that a child or a router neighbor is being added or
removed).
-----
The first use for the new event would be in `HistoryTracker`.
=> [neighbor-table] new event to signal child mode change

src/core/thread/mesh_forwarder.cpp
MIC is a part of data payload, so if it's present, data payload is not empty even if the data message is empty
(ieee802154-2020 7.2.1 - General MAC frame format).
If so, according to Termination IE inclusion rules (ieee802154-2020 7.4.2.1 Table 7-6) Header Termination IE2 need to be applied.
=> [mac] append header termination IE2 when data payload is present

CMakeLists.txt, src/cli/CMakeLists.txt, src/core/CMakeLists.txt, src/ncp/CMakeLists.txt
This commit removes the PACKAGE_VERSION definition from the global
config target so that when the git commit id is changed, only a few
sources will be re-compiled.
=> [cmake] avoid unnecessary rebuild when git commit id changes

src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mle_types.hpp
Currently, we disable retries on radio/submac of data polls with CSL IE (I believe to avoid sending outdated CSL IE).
To compensate for this, we use kMaxCslPollRetxAttempts (default 15) instead of kMaxPollRetxAttempts (default 4), which gives us more possible retx on mac.
Assuming we get NoAck error, depending on the presence of CSL IE, there will be: 
a) 4 attempts (on mac) with up to 15 retries on radio/submac (if no CSL IE)
b) 4 attempts on mac (if CSL IE present) because child is considered detached from parent after 4 data poll transmissions that returned NoAck error. 
So in the end, the increased number of RetxAttempts does not have a full effect - we start to reattach after 4 retx while having 15 retx allowed.
This PR adds kFailedCslDataPollTransmissions constant that will be used …
=> [csl] allow more tx failures when sending CSL data poll

src/core/thread/mle.cpp
When child becomes detached the CSL wasn't disabled in the radio driver,
Which caused problems with sending ParentRequest.
=> [csl] disable CSL when detaching

tools/otci/otci/otci.py
Hi,
We discovered that `dns resolve` takes a little longer i.e. 15sec to finish (rather than default timeout of 10s). Thus using a larger timeout for dns resolve (and other dns commands), e.g. 30s has helped.
Thanks
=> [otci] dns query timeout fix

src/core/api/ip6_api.cpp, src/core/coap/coap.cpp, src/core/common/iterator_utils.hpp, src/core/common/linked_list.hpp, src/core/common/timer.cpp, src/core/net/icmp6.cpp, src/core/net/ip6.cpp, src/core/net/netif.cpp, src/core/net/netif.hpp, src/core/net/srp_client.cpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, src/core/net/tcp6.cpp, src/core/net/udp6.cpp, src/core/thread/address_resolver.cpp, src/core/thread/mle.cpp, src/core/thread/network_diagnostic.cpp, src/core/thread/topology.cpp, src/core/utils/slaac_address.cpp, tests/unit/test_linked_list.cpp, tests/unit/test_netif.cpp
This commit enables use of range-based `for` loop for iterating over
all the entries in a `LinkedList`. It adds private implementations of
`Iterator` and `ConstIterator` which inherit from `ItemPtrIterator`
and use the `GetNext()` to go to the next entry. The range-based
`for` loop practically acts as a syntactic sugar helping simplify the
code and does not add any code size (or any expected run-time)
overhead.
=> [linked-list] range-based `for` loop iteration over all entries

include/openthread/instance.h, include/openthread/srp_client.h, src/cli/README_SRP_CLIENT.md, src/cli/cli_srp_client.cpp, src/core/api/srp_client_api.cpp, src/core/net/srp_client.cpp, src/core/net/srp_client.hpp, src/core/net/srp_server.cpp, src/lib/spinel/spinel.h, src/ncp/ncp_base_mtd.cpp, tests/scripts/thread-cert/Makefile.am, tests/scripts/thread-cert/border_router/test_plat_udp_accessiblity.py, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_srp_client_remove_host.py
**[srp-client] add `aSendUnregToSevrer` param to `RemoveHostAndServices()`**
This commit adds a new parameter `aSendUnregToServer` to SRP client's
`RemoveHostAndServices()` API. This parameter determines the behavior
when the host info is not yet registered with the server. If it is
set to `false` (which is the default/expected value) then the SRP
client will immediately remove the host info and services without
sending an update message to server (no need to update the server if
nothing is yet registered with it). If it is set to `true` then the
SRP client will send an update message to the server. Note that if
the host info is registered then the value of `aSendUnregToServer`
does not matter and the SRP client will always send an update message
to …
=> [srp-client] add `aSendUnregToServer` param to `RemoveHostAndServices()`

src/core/thread/mle.cpp
This PR fix addresses few problems:
- Method ScheduleMessageTransmissionTimer at first call after
CSL is enabled calculated interval incorrectly.
- Data Polls after transition from MED to SED were triggered
with incorrect interval.
=> [csl] message transmission timer fixes

include/openthread/history_tracker.h, include/openthread/instance.h, src/cli/README_HISTORY.md, src/cli/cli_history.cpp, src/cli/cli_history.hpp, src/core/api/history_tracker_api.cpp, src/core/config/history_tracker.h, src/core/thread/child_table.cpp, src/core/thread/neighbor_table.cpp, src/core/utils/history_tracker.cpp, src/core/utils/history_tracker.hpp
This commit adds support in `HistoryTracker` to record the history of
changes to the neighbor table. An entry is recorded when a child or
router neighbor is added, removed, or changed. Each entry provides:
- Timestamp
- Type: Child or Router
- Event: Added, Removed, Changed
- Extended Address
- RLOC16
- MLE Link Mode (rx-on-when-idle, FTD/MDT, full-netdata).
- Average RSS (in dBm) of received frames from the neighbor at
the time the entry was recorded.
This commit also updates CLI and adds `history neighbor` command
to get the neighbor history. It also updates the documentation.
=> [history-tracker] add support for neighbor table history

src/cli/cli_tcp.cpp
This closes https://github.com/openthread/openthread/issues/6952
=> [tcp] fix uninitialized variable warning in TcpExample::ProcessBenchmark()

examples/platforms/simulation/platform-simulation.h, examples/platforms/simulation/virtual_time/alarm-sim.c, examples/platforms/simulation/virtual_time/platform-sim.c
This commit updates `platformAlarmGetNext()` in `alarm-sim` in
virtual-time simulation platform to return the remaining duration
to the next alarm as `uint64_t` (in microseconds). This fixes the
issue with potential overflow in calculating the next alarm time.
---
Please check the comment on this PR for more details on the 
issue: https://github.com/openthread/openthread/pull/6968#issuecomment-907726266.
=> [simulation] fix handling of overflow in virtual-time simulation

src/core/utils/history_tracker.cpp
-----
The change is `aEntryAge % kOneDayInMsec) / kOneMinuteInMsec` -> `aEntryAge % kOneHourInMsec) / kOneMinuteInMsec`
=> [history-tracker] fix `EntryAgeToString()` calculation of minutes

tests/unit/test_multicast_listeners_table.cpp, tests/unit/test_platform.cpp, tests/unit/test_platform.h, tests/unit/test_timer.cpp
This commit simplifies `test_platform` module which defines the
platform APIs used by unit tests. It removes the unused global
variables and the function pointer mechanism to override platform
APIs. Instead the platform APIs in `test_platform` are defined as
`OT_TOOL_WEAK` allowing individual tests to override any of the
default implementation with their own version (e.g. `test_timer`
provides its own alarm platform APIs).
=> [test] simplify unit test platform implementation

src/core/coap/coap.cpp
To remove compiler warning:
Value stored to 'isOptionSet' is never read
=> [coap] remove unnecessary value store

src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_local.cpp, src/core/thread/network_data_local.hpp, tests/unit/test_network_data.cpp
This commit simplifies the `NetworkData` class by removing the `mType`.
Instead we add a new parameter in `SendServerDataNotification()` which
indicates whether to append the Network Data TLV to the message or
not (which was previously determined by `mType`).
=> [netdata] remove `mType` in `NetworkData` class

src/core/BUILD.gn, src/core/Makefile.am, src/core/coap/coap_message.hpp, src/core/common/array.hpp, src/core/common/const_cast.hpp, src/core/common/linked_list.hpp, src/core/common/message.hpp, src/core/mac/mac_frame.hpp, src/core/meshcop/dataset.hpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/net/netif.cpp, src/core/net/netif.hpp, src/core/net/srp_server.cpp, src/core/thread/child_table.hpp, src/core/thread/network_data.hpp, src/core/thread/network_data_leader.hpp, src/core/thread/network_data_publisher.cpp, src/core/thread/network_data_tlvs.hpp, src/core/thread/router_table.hpp, src/core/utils/heap.hpp
This commit adds a new header `common/const_cast.hpp` which provides
template functions `AsConst()` and `AsNonConst()` to cast between
const and non-const references or pointers. The template functions
simplify the code (act as syntactic suagr) by allowing the compiler
to infer the underlying reference/pointer types.
=> [common] add template helper `AsConst()/AsNonConst()` functions

src/core/coap/coap_message.cpp, src/core/coap/coap_message.hpp, src/core/common/message.cpp, src/core/common/message.hpp
This commit simplifies the `Metadata` definition in `Message` by
rearranging the member variables (to avoid alignment gaps). It moves
the definition to be sub-type of `Buffer`. It also removes the
doxygen documentation for `private` or `protected` definitions
(mainly for simple getters/setters).
=> [message] simplify `Metadata`

.github/workflows/build.yml, .github/workflows/posix.yml
This is a PR attempting to fix https://github.com/openthread/openthread/issues/6989. 
When `brew install ninja`, python 3.9 is being installed as a dependency. However, the installation failed because there is a conflict on binary `/usr/local/bin/2to3`.
=> [github-actions] fix brew install issue on macOS

src/core/common/string.cpp, src/core/common/string.hpp, src/core/mac/mac_types.cpp, src/core/meshcop/meshcop_tlvs.cpp, tests/unit/test_string.cpp
According to [SPEC-981](https://threadgroup.atlassian.net/browse/SPEC-981), we need to verify 3 more things while setting a network name:
1. The name length >= 1.
2. There are no UTF control characters in the name.
3. There are no UTF NUL characters in the name. This is covered by the second rule.
=> [network-name] implement additional validation rules

src/core/mac/sub_mac.hpp, src/core/thread/mle.cpp
A couple of fixes:
- `kUsPerUncertUnit` was declared with two different values.
- `clockAccuracy` values were not properly read from the Parent Response.
=> [csl] fixes on the receiver window duration calculation

include/openthread/instance.h, include/openthread/message.h, src/core/api/coap_api.cpp, src/core/api/ip6_api.cpp, src/core/api/udp_api.cpp, src/core/common/message.cpp, src/core/common/message.hpp
This commit updates the `Message::Settings` such that it directly
inherits from the `otMessageSettings` C struct definition. This helps
simplify the initialization of the constant default `Settings`
instance (from `GetDefault()`) to avoid calling object constructor.
It also simplifies the conversion from an `otMessageSettings *` to
a `Settings` (if the pointer is not NULL, the `otMessageSetting`
instance itself can be directly used instead of creating a copy).
=> [message] update `Message:Settings` and the default settings

src/core/api/thread_api.cpp, src/core/thread/announce_sender.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit updates `Start()`, `Stop()` and `SendAnnounce()` in `Mle`
to remove the extra parameters from the `public` versions of these
methods (adding a `private` version with extra parameter for use by
`Mle` class itself). It also adds `StartMode`, `StopMode`, and
`AnnounceMode` enumerations to use as parameter type (instead of
`bool`) in these methods which helps with code readability.
=> [mle] simplify `Start()`, `Stop()`, and `SendAnnounce()`

examples/apps/cli/cli_uart.cpp, src/cli/cli.cpp, src/cli/cli.hpp, src/core/utils/ping_sender.cpp, src/posix/cli_readline.cpp, src/posix/cli_stdio.cpp, src/posix/platform/daemon.cpp, tests/scripts/expect/_common.exp, tools/otci/otci/command_handlers.py
This commit disallows concurrent commands. 
With this commit, the CLI only execute a new command after it complete the previous command. CLI can also prompt properly after the command execution is done. 
Other fixes and enhancements:
- Fixes premature command prompt:
**With this enhancement:**
```
> ping fdde:ad00:beef:0:0:ff:fe00:fc00 10 3 1
18 bytes from fdde:ad00:beef:0:0:ff:fe00:fc00: icmp_seq=1 hlim=64 time=0ms
18 bytes from fdde:ad00:beef:0:0:ff:fe00:fc00: icmp_seq=2 hlim=64 time=0ms
18 bytes from fdde:ad00:beef:0:0:ff:fe00:fc00: icmp_seq=3 hlim=64 time=0ms
3 packets transmitted, 3 packets received. Packet loss = 0.0%. Round-trip min/avg/max = 0/0.0/0 ms.
Done
> scan
| J | Network Name     | Extended PAN     | PAN  | MAC Address      | Ch | dBm | LQI | …
```
=> [cli] disallow concurrent commands

src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit fixes a potential bug that delayed Data Requests may use wrong Active and Pending Timestamps because the Active & Pending Timestamps may change while a Data Request is being delayed.
=> [mle] send Delayed Data Request with latest Active/Pending Timestamp

src/core/common/message.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit evicts delayed MLE Data Requests whenever the device is sending a newer one.
=> [mle] evicts delayed MLE Data Request when sending a newer one

src/cli/cli_coap.cpp
I still got such warning:
```
warning: ‘char* strncpy(char*, const char*, size_t)’ output may be truncated copying 31 bytes from a string of length 31 (make distcheck)
```
when building `dist-check`: `make -f examples/Makefile-simulation distcheck`
My gcc version is: **gcc version 10.2.1 20210110 (Debian 10.2.1-6+build2)**
This PR fixes the warning. Using `memcpy` seems to be simplest, most efficient way.
=> [cli] fix warning of strncpy

src/core/thread/network_data_publisher.cpp
Build error happens when building simulation with config:
```
cmake ../.. -GNinja -DOT_PLATFORM=simulation -DOT_DNSSD_SERVER=ON -DOT_DNS_CLIENT=ON -DOT_SRP_CLIENT=ON -DOT_ECDSA=ON -DOT_SRP_SERVER=ON -DOT_SERVICE=ON -DOT_NETDATA_PUBLISHER=ON -DOT_BORDER_ROUTER=ON
```
Error message is:
```
../../src/core/thread/network_data_publisher.cpp: In member function ‘void ot::NetworkData::Publisher::Entry::SetState(ot::NetworkData::Publisher::Entry::State)’:
../../src/core/thread/network_data_publisher.cpp:264:5: error: ‘otLogInfoNetData’ was not declared in this scope
264 |     otLogInfoNetData("Publisher: %s - State: %s -> %s", ToString(/* aIncludeState */ false).AsCString(),
|     ^~~~~~~~~~~~~~~~
```
This PR adds the missing header to fix the issue.
=> [network-data] fix missing header in `network_data_publisher.cpp`

src/core/thread/mesh_forwarder.cpp
This commit ensures to call `UpdateRoutes()` on rx of a first lowpan
fragment frame. `UpdateRoutes()` can then update the snooped address
cache entries and check if the message is from a previous child (which
indicates that the child has switched to a new parent). This change
should help address an issue with "inform previous parent" behavior
not removing the child when `MULTI_RADIO` is enabled (due to frag
header added to the frames for duplication detection under
multi-radio).
---
See https://github.com/openthread/openthread/pull/7005#issuecomment-920606847 for more details on the "inform previous parent" issue.
=> [mesh-forwarder] call `UpdateRoutes` on rx of first fragment frame

src/core/BUILD.gn, src/core/Makefile.am, src/core/api/server_api.cpp, src/core/common/data.hpp, src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_local.cpp, src/core/thread/network_data_local.hpp, src/core/thread/network_data_publisher.cpp, src/core/thread/network_data_service.cpp, src/core/thread/network_data_service.hpp, src/core/thread/network_data_tlvs.cpp, src/core/thread/network_data_tlvs.hpp, src/core/thread/network_data_types.cpp, src/core/thread/network_data_types.hpp, tests/unit/CMakeLists.txt, tests/unit/Makefile.am, tests/unit/test_data.cpp, tests/unit/test_network_data.cpp
This PR contain two related commits:
**[common] adding `Data` and `MutableData`**
This commit adds two new generic types `Data` and `MutableData` which
are simply wrappers over a pointer to a buffer and a given data
length. The data length can be either `uint8_t` or `uint16_t` which
is determined by a template parameter. The `Data` treats the content
of the buffer as immutable  whereas `MutableData` allows it to be
changed. This commit also adds a unit test `tes_data` to verify the
behavior of newly added types.
**[netdata] add `ServiceData` and `ServerData` types**
This commit adds new types `NetworkData::ServiceData/ServerData`
(which use the `ot::Data` class) which help simplify different
`NetworkData` methods dealing with Service and Server TLVs.
------
Notes on this change:
- The …
=> [netdata] add generic `Data` class & `NetworkData::Service/ServerData` 

examples/platforms/simulation/openthread-core-simulation-config.h, tests/scripts/thread-cert/Makefile.am, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_inform_previous_parent_on_reattach.py
This commit verifies that MEDs can inform previous parent on reattach with `OPENTHREAD_CONFIG_MLE_INFORM_PREVIOUS_PARENT_ON_REATTACH` enabled.
=> [thread-cert] add test to verify MED can inform previous parent on reattach

include/openthread/history_tracker.h, include/openthread/instance.h, src/cli/README_HISTORY.md, src/cli/cli_history.cpp, src/cli/cli_history.hpp, src/core/api/history_tracker_api.cpp, src/core/config/history_tracker.h, src/core/net/dhcp6_client.cpp, src/core/net/netif.cpp, src/core/net/netif.hpp, src/core/utils/history_tracker.cpp, src/core/utils/history_tracker.hpp
This commit adds support in `HistoryTracker` to record the history of
changes to the Thread interface's unicast and multicast IPv6 addresses.
An entry is recorded when an address is added or removed. For unicast
addresses, each entry provides:
- Timestamp
- Event: Added or Removed
- Address : Unicast address along with its prefix length (in bits).
- Origin: Thread, SLAAC, DHCPv6, or Manual.
- Address Scope.
- Flags: Preferred, Valid, and RLOC (whether the address is RLOC).
For multicast address history, each entry provides:
- Timestamp
- Event: Subscribed or Unsubscribed.
- Address : Multicast address.
- Origin: Thread or Manual.
This commit also updates CLI and adds `history ipaddr` and
`history ipmaddr` commands to get the lists. It also updates the
documentation in `README_HISTORY.md`.
=> [history-tracker] add unicast/multicast IPv6 address history

.github/workflows/posix.yml, include/openthread/instance.h, src/core/api/instance_api.cpp, src/core/common/instance.cpp, src/core/common/instance.hpp, src/core/mac/link_raw.cpp, src/core/mac/link_raw.hpp, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/radio/radio.cpp, src/core/radio/radio.hpp, src/lib/spinel/spinel.h, src/ncp/ncp_base.cpp, tests/scripts/expect/posix-rcp-stack-reset.exp, tests/scripts/expect/v1_2-rcp-stack-reset.exp, tests/scripts/misc/test_rcp_reset.py, tests/unit/test_platform.cpp
This commit makes RCP use a stack reset instead of doing a hard reset when a reset command is received.
=> [radio] use stack reset in RCP

src/core/mac/mac.cpp
----
This is small change, just removing the extra casting of `mMode2KeyMaterial` 
to `KeyMaterial` (since it is already defined as the same type).
=> [mac] remove unnecessary cast of `mMode2KeyMaterial` to `KeyMaterial`

src/core/common/data.hpp, src/core/common/message.cpp, src/core/common/message.hpp, src/core/crypto/hmac_sha256.cpp, src/core/crypto/sha256.cpp, src/core/net/checksum.cpp, tests/unit/test_data.cpp
This commit updates the `Message::Chunk` type to use `Data` as its
base class (thus inheriting the common helper methods from it) which
helps simplify its use. This commit also adds couple of new methods in
`Data` class (method `SetLength()` to  change the `Data` length, and
`MatchesBytesIn()` to compare the `Data` content with bytes from a
given buffer). The `test_data` unit test is also updated to check the
newly added `Data` methods.
=> [message] update `Message::Chunk` definitions to use `Data`

src/core/api/border_router_api.cpp, src/core/api/netdata_api.cpp, src/core/api/server_api.cpp, src/core/thread/mle.cpp, src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp, src/core/thread/network_data_local.cpp, src/core/thread/network_data_local.hpp, src/core/thread/network_diagnostic.cpp, tests/unit/test_network_data.cpp
This commit updates the `NetworkData` implementation to simplify it
and make it more flexible.  It changes `NetworkData` class such that
it delegates providing the buffer space to store the TLVs to its
sub-classes (`Local`/`Leader`) or its users. This allow us to remove
many `static` methods that expect inputs of `(aTlvs, aTlvsLength)`
and instead the use the `NetworkData` methods directly. Basically,
the `NetworkData` class can now be considered as a wrapper over a
pointer to a buffer containing a sequence of TLVs which provides
methods to parse and process the TLVs. `NetworkData` class assumes
that the TLVs (buffer content) is immutable and we have a new class
`MutableNetworkData` which provides methods to update (add, remove,
or modify) the TLVs.
=> [netdata] enhance and simplify `NetworkData` class

src/core/mac/mac_types.cpp, tests/unit/test_mac_frame.cpp
This commit fixes the `NetworkName` check (for its length to be larger
than zero) which was recently added in commit e2f0afab5d. This commit
moves the name length check to method `Set(const NameData &aNameData)`
and after the `newLen` is calculated.
This commit also updates `TestMacNetworkName()` in unit test to verify
that setting the network name to an empty string correctly fails with
`kErrorInvalidArgs`.
----
- This was added in https://github.com/openthread/openthread/pull/6988
- Please see [comment in #6988](https://github.com/openthread/openthread/pull/6988/files#r710812831) for why we need the change
=> [mac] fix the `Mac::NetworkName` length check (`length >= 1`)

src/core/meshcop/dataset_manager_ftd.cpp
This commit fixes `DatasetManager::HandleSet()` to add a check to
ensure that the message contains `PendingTimestampTlv` when the
Pending Dataset is being updated.
=> [meshcop] ensure msg has timestamp TLV in `DatasetManager::HandleSet()`

src/core/meshcop/dtls.hpp
For certain external mbedTLS configurations, there is no much sense to define `MBEDTLS_SSL_EXPORT_KEYS` when OT has Joiner || Commissioner || DTLS functionalities disabled.
This commit only ensures that such builds don't fail. The `mbedtls_ssl_key_export_type` type is defined only when `MBEDTLS_SSL_EXPORT_KEYS` is defined, while `dtls.hpp` is always taken into the build process.
=> [dtls] ensure mbedtls_ssl_key_export_type is defined

src/core/mac/mac_types.cpp, src/core/mac/mac_types.hpp, tests/unit/test_mac_frame.cpp
This commit updates `Mac::NameData` to use `Data` as its base
class and then use its method in the `NameData` implementation.
=> [mac] update `Mac::NameData` to use `Data`

include/openthread/instance.h, include/openthread/platform/radio.h, src/core/mac/mac_types.hpp
This commit removes the `OT_TOOL_PACKED` requirement from types
`otMacKeyMaterial` and `Mac::KeyMaterial`. Generally, we define a
type as "packed"  if it may be embedded in a message/buffer (e.g. a
TLV) and/or may be cast from a buffer pointer. Neither case applies
to `KeyMaterial`.
=> [mac] remove "packed" requirement for `Mac::KeyMaterial`

src/core/meshcop/dataset.cpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_local.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/dataset_updater.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/meshcop/timestamp.hpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_tlvs.hpp
This commit updates and simplifies processing of Active/Pending
Timestamp TLVs (in MeshCoP and MLE) by using TLV helper methods
that read/write the TLV's timestamp value from/in a message.
=> [meshcop] update handling of Active/Pending Timestamp TLVs

third_party/tcplp/CMakeLists.txt, third_party/tcplp/Makefile.am, third_party/tcplp/lib/bitmap.c, third_party/tcplp/lib/bitmap.h, third_party/tcplp/lib/cbuf.c, third_party/tcplp/lib/cbuf.h, third_party/tcplp/lib/lbuf.c, third_party/tcplp/lib/lbuf.h
This is the seventh in a series of pull requests (after #6744, #6770, #6790, #6857, #6885, and #6925) bringing TCPlp to OpenThread. I'm making a series of small pull requests so that it's easier for the OpenThread community to review the code. If you'd like to preview a working version of TCPlp in OpenThread, see #6650.
This pull request adds the libraries that I wrote as part of TCPlp to handle data buffering. These libraries are intended to replace the `mbuf`-based data buffering in the FreeBSD TCP implementation. They implement the send buffer as a linked buffer chain (consistent with `otLinkedBuffer` in OpenThread's TCP API) and the receive buffer as a circular buffer and bitmap (used to keep track of which bytes were received out-of-order).
You can look at Section 5.2 of [the TCPlp …
=> [tcp] add TCPlp data buffering code (used instead of FreeBSD's data buffering)

include/openthread/instance.h, include/openthread/platform/crypto.h, src/core/BUILD.gn, src/core/Makefile.am, src/core/config/crypto.h, src/core/crypto/aes_ecb.cpp, src/core/crypto/aes_ecb.hpp, src/core/crypto/context_size.hpp, src/core/crypto/crypto_platform.cpp, src/core/crypto/hkdf_sha256.cpp, src/core/crypto/hkdf_sha256.hpp, src/core/crypto/hmac_sha256.cpp, src/core/crypto/hmac_sha256.hpp, src/core/crypto/sha256.cpp, src/core/crypto/sha256.hpp, src/core/openthread-core-config.h
The context objects don't necessarily exist on every platform. 
This PR move the context to platform drivers to avoid build errors.
=> [crypto] move context to platforms

src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/mac/sub_mac_callbacks.cpp, src/core/thread/key_manager.cpp, src/core/thread/key_manager.hpp
This commit fixes two related aspects of updating of the frame counter
in `SubMac` and synchronizing the value with `KeyManager`.
It fixes an issue (when radio platform handles tx security and frame
counter management) where the counter value in `SubMac` and
`KeyManager` were set to old value used in the last transmission
(from `TxDone` callback). This would then lead to an already used
frame counter value to be included in MLE Link Frame Counter TLV.
Under `MULTI_RADIO` this could cause more harm since when appending
MLE Link Frame Counter TLV we move all counters for each radio link
up to max value among them and set the counter value on all radio
links(which would then cause the counter on radio platform to be set
to an older value).
This commit also updates the code to handle the case …
=> [sub-mac] fix frame counter update and its sync with `KeyManager`

src/cli/cli.cpp, src/cli/cli_output.cpp, src/cli/cli_output.hpp
This commit updates CLI to not include the CLI prompt string `"> "` when
emitting the command's input and output to the logs under the config
`OPENTHREAD_CONFIG_CLI_LOG_INPUT_OUTPUT_ENABLE`. It also changes how
the input command is logged to avoid logging empty lines or extra
spaces in between the args.
----
Backgorund on this: 
- I think the promot was changed recently to be added by the `Cli` class itself (instead of platform). 
- I noticed with this the prompt `"> "` was being included in the logs from #7028.
- This PR now also makes the input look nicer:
```bash
> panid      0x1234     
Done
00:00:21.931 [NOTE]-CLI-----: Input: panid 0x1234
00:00:21.931 [NOTE]-CLI-----: Output: Done
> panid
0x1234
Done
00:00:25.594 [NOTE]-CLI-----: Input: panid
00:00:25.594 [NOTE]-CLI-----: Output: …
```
=> [cli] skip CLI prompt when emitting command input/output to logs

src/core/thread/key_manager.cpp
This commit changes `KeyManager` to use `SetAllMacFrameCounter(0)` to
reset the frame counter(s). This would then ensure that the new
counter value is also set on `SubMac` and radio platform layer
(which can handle the 15.4 frame counter assignments). This addresses
an issue where on Key Sequence update the frame counter values on
`SubMac` and radio platform can remain unchanged.
----
Please see https://github.com/openthread/openthread/pull/7029#issuecomment-927463921 and related comment in the other PR.
I think it would good idea to add a test-case to verify the key seq change (and that the frame counter reset somehow) so we can detect it if it gets broken. I don't have any immediate ideas on how to add such a test (suggestions/ideas are welcome). But since I feel this is an important …
=> [key-manager] set frame counter on `SubMac` on a counter reset

src/core/thread/link_metrics.cpp
This commit add missing reverse operations for linear scale RSSI and link margin for enhance acknowledgments.
=> [link-metrics] add reverse linear scale for metrics in enh ack

src/lib/spinel/spinel_decoder.cpp
This commit updates some of the `SpinelDecoder::Read{Item}()` methods
to initialize their local pointer variables to `nullptr`. Though we
technically do not need this change (since the call to `Read(aPtr)`
will set the pointer value on success), some toolchains cannot infer
this from the code and generate error/warning of "pointer may be
used uninitialized".
----
Example of such failure:
- https://github.com/openthread/ot-br-posix/pull/1029/checks?check_run_id=3722574534
=> [spinel-decoder] add extra check to address compiler warnings

src/core/net/ip6.cpp, tests/toranj/test-703-multi-radio-mesh-header-msg.py
This commit addresses an issue when forwarding received messages under
`MUTI_RADIO` config. We clear the radio type (which indicates the
radio on which the `Message` is received) when the same `Message`
instance is forwarded back to the Thread mesh to be sent out to a
neighbor. This then ensures that `RadioSelector` picks the radio to
send deadpanning on the neighbor's supported radios and their
preference.
This commit also updates `test-703-multi-radio-mesh-header-msg.py` to
verify and cover this situation.
----
Please see [openthread-users msg](https://groups.google.com/g/openthread-users/c/0mQneIyGgQU/m/w42N9mX7AQAJ) for more details/discussions on this.
=> [ip6] clear radio type (link info) when forwarding received message

third_party/tcplp/CMakeLists.txt
The issue showed up when we upmerged the latest OpenThread revision to Zephyr.
tcplp uses stdio.h which, for some libc implementations, can depend on
Kconfig defines.
These Kconfig defines can be included through compile options in
ot-config.
Link with ot-config to get the compile options.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
=> [tcp] apply ot-config compile options

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, tests/scripts/thread-cert/border_router/test_single_border_router.py
Current implement will start evaluating on-link prefix before successfully sending
`kMaxRtrSolicitations=3` RS messages. This commit fixes this issue by retrying
sending failed RS messages in `kRtrSolicitationRetryFailDelay=60` seconds.
=> [routing-manager] retry sending failed RS messages

src/core/thread/link_metrics.cpp
This commit force Big Endian encoding for number of PDUs received in Link Mertics Report Sub-TLV.
=> [link-metrics] fix endianess for PDU in link metrics report sub-tlv

src/core/net/srp_server.cpp, tests/scripts/thread-cert/border_router/test_advertising_proxy.py
There are failure logs show that the test scripts failed to verify updated SRP services via mDNS, but the SRP service status on the SRP client and server are verified okay.
```txt
2021-10-22T13:57:35.4956943Z FAIL: test (__main__.SingleHostAndService)
2021-10-22T13:57:35.4957783Z ----------------------------------------------------------------------
2021-10-22T13:57:35.4958403Z Traceback (most recent call last):
2021-10-22T13:57:35.4959313Z   File "./tests/scripts/thread-cert/border_router/test_advertising_proxy.py", line 203, in test
2021-10-22T13:57:35.4960362Z     self.host_check_mdns_service(host, host_address, 'my-service', service_port)
2021-10-22T13:57:35.4961477Z   File "./tests/scripts/thread-cert/border_router/test_advertising_proxy.py", line 220, in host_check_mdns_service …
```
=> [tests] fix flaky advertising proxy tests

src/posix/platform/spi_interface.cpp
Use `OT_MAX` for bytes comparison logic. I think this way the code looks more intuitive.
=> [posix] use OT_MAX to simplify SPI code

include/openthread/instance.h, include/openthread/thread_ftd.h, src/cli/cli.cpp, src/cli/cli.hpp, src/core/api/thread_ftd_api.cpp, src/core/thread/mle_router.cpp, src/core/thread/router_table.cpp, src/core/thread/router_table.hpp, tests/scripts/thread-cert/backbone/test_dua_routing.py, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/thread_cert.py
This PR fixes #6566.
Added new API/CLI for reference devices to set allowed ranges of router IDs. When the allowed ID range is set, the leader will only assign router IDs in the range. In this way, we can assign non-overlapping router ID ranges to different thread networks so that no RLOC16s will collide across multiple thread networks. Hence #6566 can be fixed.
=> [continuous-integration] fix test_dua_routing.py

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_BR.py
Several fixes for Thread 1.2 Certification, including:
- getMAC
- setPollingRate
- joinCommissioned
- MGMT_ACTIVE_SET
- setCSLtout
- LinkMetricsMgmtReq
- send_udp
- setCSLsuspension
- set_max_addrs_per_child
- getMlrLogs
- mldv2_query
- mdns_query
- powerDown
- powerUp
=> [thci] add Thread 1.2 Certification fixes

tools/harness-thci/OpenThread.py
Make sure the variables are accessible in the child class and use proper line endings for first Zephyr command.
=> [thci] fix Zephyr detection

src/core/thread/network_data_publisher.cpp
This commit adds missing `#if` check in `network_data_publisher.cpp`
to ensure it can be built when `CONFIG_BORDER_ROUTER_ENABLE` is
disabled (i.e., with `CONFIG_TMF_NETDATA_SERVICE_ENABLE` only).
---
_Background_:
- We already have this check in `netdworkdata_publisher.hpp` which ensures
we either have `SERVCIE_ENABLE` or `BORDER_ROUTER_ENABLE`:
```c++
#if !OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE && !OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE
#error "OPENTHREAD_CONFIG_NETDATA_PUBLISHER_ENABLE requires either OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE"\
"or OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE"
#endif
```
- The header file already has the proper `#if` checks.
- I considered adding a CI config to cover the config (i.e., service enabled without 
border router) but decided against it, …
=> [netdata] allow `Publisher` to be built with service only

src/core/backbone_router/bbr_manager.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, tests/scripts/thread-cert/backbone/test_dua_routing_med.py, tests/scripts/thread-cert/pktverify/consts.py
Supersedes #7120 to fix TH 5.9.21: DUA-TC-21
This commit fixes a bug that PBBR does not send `Address Query` and `Backbone Query` on behalf of MED Children, and add a test to make sure DUA forwarding works on PBBR:
- Make sure PBBR sends `Address Query` and `Backbone Query` on behalf of MED Child
- Make sure PBBR does not send `Address Query` when the destination is MED Child
- Make sure MED Children do not send `Address Query` by itself
- Verifiy DUA reachability between PBBR and MED Child
- Make sure PBBR reduce IPv6 TTL by 1 when forwarding DUA destined messages
=> [dua] PBBR should resolve DUA dest for packet initiated from its MTD child

include/openthread/instance.h, include/openthread/thread.h, src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit allows `mParentChanges` counter which tracks number of
times device (as a child) switches its parent to be used without
`INFORM_PREVIOUS_PARENT` feature.
----
For background on this, please see: https://github.com/openthread/openthread/pull/2982#discussion_r742753755
=> [mle] `mParentChanges` counter without `INFORM_PREVIOUS_PARENT`

include/openthread/instance.h, include/openthread/platform/radio.h
=> [docs] clarify `otPlatRadioGetNow()` as free-running

src/core/common/logging.cpp
`otDump` will currently always dump to string and use the log level to
decide whether to print it. Since this function is in the key path of
packet handling, this behavior reduces network throughput. This PR adds
a log level check to fix the issue.
=> [log] check log level before dumping packet to string

src/core/net/srp_server.cpp, src/core/net/srp_server.hpp
This commit adds `enum` types to use as arguments `aRetainName` 
and `aNotifyHandler` in the calls to method `RemoveHost()` and
`Host::RemoveService()`.
=> [srp-server] simplify calls to `RemoveHost()` & `RemoveService()`

src/cli/cli.cpp
This commit fixes ccm command parameters handling.
=> [cli] fix parameter parse in ccm command

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
Existing IPv6 implementations may not implement DHCPv6 to acquire an
IPv6 address. As a result, a Thread Border Router must advertise a ULA
if there is no existing prefix that supports SLAAC (i.e. has A flag
set).
=> [routing-manager] require on-link prefix to support SLAAC

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_BR.py
Modify `mdns_query` to accept a unicast destination and parse the mDSN response to find the Border Router's Border Agent port.
=> [thci] retrieve BA port from mDNS response

src/core/net/dnssd_server.cpp
Background:
- mDNS implementations may return zero length TXT RR.
=> [dnssd-server] fix TXT RR format when TXT length is zero

tools/harness-thci/OpenThread_BR.py
Manually configured addresses need to be added to the TUN interface in order for the host to handle them.
Discussion in https://github.com/openthread/openthread/pull/7145
=> [thci] override `forceSetSlaac` for border router

Android.mk, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/common/heap_data.cpp, src/core/common/heap_data.hpp, tests/unit/test_heap_string.cpp
This commit adds new class `HeapData` which represents a heap
allocated data buffer of a given variable length. This class provides
methods to set/copy the `HeapData` from/to  a buffer or a `Message.
This commit also adds unit test for the new class.
---------
Background:
I think this common data type may be useful in different situations.
The main use-case for this is in SRPL (SRP Replication) where we need to 
save the original messages (from client) for every registered service which are 
then passed to other peers during SRPL initial synchronization. I submitted it as 
small seperate PR (adding the `HeadData` and its unit test).
=> [common] adding `HeapData` class

Android.mk, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/api/heap_api.cpp, src/core/common/heap.cpp, src/core/common/heap.hpp, src/core/common/heap_data.cpp, src/core/common/heap_data.hpp, src/core/common/heap_string.hpp, src/core/common/instance.hpp, src/core/common/message.cpp, src/core/crypto/mbedtls.cpp, src/core/meshcop/border_agent.cpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, src/core/utils/heap.hpp, tests/unit/test_heap_string.cpp
This commit moves the heap functions `CAlloc` and `Free` from
`instance.hpp` header to a separate `heap.hpp` header file. The main
reason is to make it easier to include this header file from other
modules (avoid the header dependency/loop issues by requiring to
include `instance.hpp` to get access to heap functions). This commit
also defines a `Heap` namespace and moves other heap allocated types
under this namespace (`Heap::String` and `Heap::Data`).
=> [common] adding `heap.hpp` header and `Heap` namespace     

src/core/net/srp_server.cpp, src/core/net/srp_server.hpp
This commit updates `Srp::Server` adding a new type `MessageMetadata`
which is used during processing of a received SRP Update message.
This class serves two purposes: (1) It helps simplify the code by
combining all related parameters (current offset in the message, DNS
`Header` and `Zone`, and `Ip6::MessageInfo`) into a single `struct`
which is then passed to different `Process{}()` methods. (2) It
defines new fields to represent the time when the message was
received (allowing us to process the message as if it was received
earlier than the current time) and the lease interval values to be
granted during processing of the message. These are added in
preparation for enabling SRP Replication (SRPL). With SRPL we can
receive an SRP Update message from an SRPL partner (i.e., another SRP …
=> [srp-server] adding `MessageMetadata`

src/core/thread/mle_router.cpp
Thread Specification allows a parent to update child network data by
sending a unicast MLE Data Response. Receiving the child's Leader Data
in a MLE Child Update Request message should serve as an
acknowledgment when the network data is received.
=> [mle] record child netdata versions in `HandleChildUpdateRequest()`

tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py, tests/scripts/thread-cert/node.py
HostNode is based on OtbrDocker, which has otbr-agent service started by default. We should disable this service on HostNode otherwise the border router test cases won't have the exact expected topology.
=> [tests] stop otbr-agent service for host nodes

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_BR.py
Some certification tests are failing because not enough delay is
applied after a Linux ping command is sent and the capture misses
the ICMP trasaction.
Also removing unneeded check for Thread 1.2 harness version when
reconnecting to the serial port after a reset.
=> [thci] allow for sufficient time after a ping from OTBR

tests/scripts/thread-cert/Makefile.am, tests/scripts/thread-cert/border_router/test_dnssd_instance_name_with_space.py, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_dnssd_name_with_special_chars.py, tools/otci/otci/otci.py
This commit adds tests to make sure Service Instance names with spaces are handled properly by SRP and DNS-SD.
=> [dnssd] add tests for Service Instance names with spaces

src/core/net/srp_server.cpp
This commit fixes the potential memory leak of `mTxtData` when a
`Description` instance is freed. Also addresses similar situation
with `mServiceName` when `Service` instance is freed.
=> [srp-server] free `mTxtData` buffer from `Description::Free()`

src/posix/platform/settings.cpp
We added a dry run option in #7031. So it is possible that the
settings fd is -1 when de-initialization. The assert here makes
the program crash. This PR updates it to a 'VerifyOrExit' to avoid
crashing.
=> [settings] do not assert when SettingsFd is -1 in `Deinit`

src/core/common/heap_data.cpp, src/core/common/heap_data.hpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, tests/unit/test_heap_string.cpp
This commit updates the `Srp::Server` to use the `Heap::Data` class
for storing the TXT record data bytes. This helps simplify the code.
This commit also adds a new helper method in `Heap::Data` to set
the data from a given number of bytes read from a `Message` at a
given offset. It also updates the unit test to cover the behavior
the new method.
----
This PR contains the commit from https://github.com/openthread/openthread/pull/7165.
=> [srp-server] use `Heap::Data` to store TXT record data bytes

src/posix/platform/multicast_routing.cpp
This commit removes incorrect calls to  `UpdateMldReport`. 
- `UpdateMldReport(MA, true)` should be called when a MA is registered, thus in `MulticastRoutingManager::Add`.
- `UpdateMldReport(MA, false)` should be called when a MA is expired, thus in `MulticastRoutingManager::Remove`.
Note that removing an Multicast Fowarding Cache (MFC) does not mean the MA is expired. The MFCs can be freely removed even when the MA is still registered and being renewed.
=> [mlr] remove unnecessary calls to `UpdateMldReport`

src/posix/platform/logging.cpp
This PR avoids link error of duplicate `otPlatLog` symbol.
=> [posix] add OT_TOOL_WEAK for otPlatLog

tools/harness-thci/OpenThread_BR.py
Avoid parsing responses for not expected cases.
Fixes some issues with Thread 1.2 certification test cases in which it's not required to parse the mDNS response.
=> [thci] fix `mdns_query`

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_BR.py
Some certification tests are failing because otbr-agent service is not started back after calling powerDown (isPowerDown flag is kept False and reset function fails on checking thread state - since the service is stopped, we can't return status)
Also minor fixes for printing logs, disabling paramiko DEBUG level
=> [thci] fix issue with isPowerDown flag and reset method 

third_party/tcplp/CMakeLists.txt, third_party/tcplp/Makefile.am, third_party/tcplp/bsdtcp/cc.h, third_party/tcplp/bsdtcp/cc/cc_module.h, third_party/tcplp/bsdtcp/cc/cc_newreno.c, third_party/tcplp/bsdtcp/icmp_var.h, third_party/tcplp/bsdtcp/ip.h, third_party/tcplp/bsdtcp/ip6.h, third_party/tcplp/bsdtcp/sys/queue.h, third_party/tcplp/bsdtcp/tcp.h, third_party/tcplp/bsdtcp/tcp_const.h, third_party/tcplp/bsdtcp/tcp_fsm.h, third_party/tcplp/bsdtcp/tcp_input.c, third_party/tcplp/bsdtcp/tcp_output.c, third_party/tcplp/bsdtcp/tcp_reass.c, third_party/tcplp/bsdtcp/tcp_sack.c, third_party/tcplp/bsdtcp/tcp_seq.h, third_party/tcplp/bsdtcp/tcp_subr.c, third_party/tcplp/bsdtcp/tcp_timer.c, third_party/tcplp/bsdtcp/tcp_timer.h, third_party/tcplp/bsdtcp/tcp_timewait.c, third_party/tcplp/bsdtcp/tcp_usrreq.c, third_party/tcplp/bsdtcp/tcp_var.h, third_party/tcplp/bsdtcp/types.h, third_party/tcplp/tcplp.h
This is the eighth in a series of pull requests (after #6744, #6770, #6790, #6857, #6885, #6925, and #6926) bringing TCPlp to OpenThread. I'm making a series of a small pull requests so that it's easier for the OpenThread community to review the code. If you'd like to preview a working version of TCPlp in OpenThread, see #6650.
This pull request adds TCPlp's TCP protocol logic, which is derived from the TCP protocol logic in the FreeBSD Operating System. The FreeBSD code had to be refactored to work for TCPlp, and I have added extensive comments explaining the code that was deleted and changed. The changes are primarily modifications to work with TCPlp's data buffering (see #6926), removal of features that depend on dynamic memory allocation to save memory (SYN cache, compressed TIME-WAIT …
=> [tcp] add TCPlp's FreeBSD-derived protocol code, with explanatory comments

third_party/tcplp/CMakeLists.txt
Add the following options `-Wno-sign-compare` and
`-Wno-unused-parameter` with target_compile_options to suppress
warnings. These options will be appended to the end of options
inherited from COMPILE_OPTIONS and CMAKE_C_FLAGS.
=> [tcplp] suppress warnings by target_compile_options

src/core/net/ip6.cpp, src/core/thread/mesh_forwarder.hpp
When an encapsulated IPv6 header is found, log the message.
=> [ip6] log encapsulated IPv6 messages

src/core/BUILD.gn, src/core/Makefile.am, src/core/common/heap_allocatable.hpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp
This commit adds a new class `Heap::Allocatable<Type>` which provides
`New()` and `Free()` methods to allocate and free instances of a
template `Type` on heap. The static `New()` method requires the
`Type` class to provide a method `Error Init(Args...)` to initialize
the allocated object as `Type`. The initialization itself can fail
(return `Error`) in which case `New()` will release any allocated
buffer and return `nullptr`. The `Free()` method invokes the `Type`
class's destructor before releasing the heap pointer. This ensures
that any heap allocated member variables in `Type` (e.g., any
`Heap::String` or `Heap::Data`) are freed before the `Type` instance
itself is freed.
----
The `Heap::Allocatable()` helps simplify the code, but another key
benefit is that it uses and invokes the …
=> [common] adding `Heap::Allocatable` and use it in `Srp::Server`

Android.mk, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/common/appender.cpp, src/core/common/appender.hpp, src/core/net/dns_types.cpp, src/core/net/dns_types.hpp, tests/unit/test_dns.cpp, tests/unit/test_message.cpp
**[common] adding `Appender` class**
This commit adds a `Appender` class which acts as a wrapper over
either a `Message` or a data buffer (e.g., `MutableData`) and
provides  different flavors of `Append()` method. This class helps in
construction of message content where the destination can be either a
`Message` or a buffer. This commit also adds a unit test for the new
class.
----
**[dns] `TxtEntry::AppendEntries()` to append to data buffer or message**
This commit adds new flavor of `Dns::TxtEntry::AppendEntries()` to
encode and append TXT record entries in a data buffer (in addition to
existing one which encodes and append to a `Message`). The underlying
implementation is updated to use `Appender`. This commit also updated
`test_dns` unit test to validate …
=> [common] `Appender` class / update `Dns::TxtEntry::AppendEntries()`

src/core/BUILD.gn, src/core/Makefile.am, src/core/common/owning_list.hpp, tests/unit/test_linked_list.cpp
This commit adds `OwningList<Type>`, a singly linked list which owns
its entries and frees them upon destruction of the list. This commit
also updates `test_linked_list` to validate the behavior of the new
class.
=> [common] adding `OwningList` (a linked list which owns its entries)

tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py, tests/scripts/thread-cert/node.py
There was a bug that avahi publisher may accidentally publish redundant meshcop services and leave the previous published one dangling. This PR https://github.com/openthread/ot-br-posix/pull/1104 fixes the bug.
=> [tests] verify the number of published meshcop services

tools/harness-thci/OpenThread.py
When the GRL starts, it calls initialize() reset() method on each device. Reset method call fails due to missing (uninitialized) attribute 'isPowerDown'.
=> [thci] fix issue with not initialized isPowerDown flag

.github/workflows/docker.yml
Reverts openthread/openthread#7194
Current method does not work with personal access tokens.
> level=error msg="error pushing readme to repo server. See error message below. Run with \"--debug\" for more details. \n\nerror pushing README, bad status code for response: 403 FORBIDDEN. Server responded: \"access to the resource is forbidden with personal access token\". Try \"docker logout\" and \"docker login\". You cannot use a personal access token to log in and must use username and password. If you have 2FA auth enabled in Dockerhub you'll need to disable it for this tool to work. (This is an unfortunate Dockerhub limitation, see docs for more infos.)"
https://github.com/openthread/openthread/runs/4304604819?check_suite_focus=true
=> Revert "[github-actions] push `README.md` to Dockerhub"

Android.mk, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/common/data.cpp, src/core/common/data.hpp, src/core/common/message.cpp, src/core/common/message.hpp, src/core/common/string.cpp, src/core/common/string.hpp, src/core/net/dns_types.cpp, src/core/net/dns_types.hpp, src/core/net/dnssd_server.cpp, src/core/net/dnssd_server.hpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, tests/scripts/thread-cert/test_dnssd.py, tests/unit/test_dns.cpp, tests/unit/test_string.cpp
This PR contains the following related commits:
**[string] new functions for case-insensitive comparison**
This commit adds new string helper functions to convert between
lowercase and uppercase letters. It also adds new function
`StringStartsWith()` which determines whether the string starts with
a given prefix string and `StringMatch()` which compares and matches
two strings.
This commit also adds a new mechanism in all string helper functions
allowing the caller to specify the match mode to be used when
comparing strings: Either an exact match of characters, or a
case-insensitive match where uppercase and lowercase characters are
treated as equal.
This commit also updates `test_string` unit test to validate the new
functions and behaviors.
----
**[dns] change …
=> [dns] use case-insensitive DNS name match

tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py, tests/scripts/thread-cert/thread_cert.py
This PR aims to fix https://github.com/openthread/ot-br-posix/issues/736.
The spec asks border router to publish meshcop service even when thread interface is inactive. I implemented this feature in openthread/ot-br-posix#991. I added a test case in this PR to verify the feature. 
I also introduced `boot_delay` to add delays between booting nodes. In this way we can let border routers not starting at the  same time, so that there will be fewer renaming conflicts. This can make the test more stable.
Depends-On: openthread/ot-br-posix#991
=> [tests] update meshcop service test case

src/core/BUILD.gn, src/core/Makefile.am, src/core/common/owned_ptr.hpp, src/core/common/ptr_wrapper.hpp, src/core/common/retain_ptr.hpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, tests/unit/test_smart_ptrs.cpp
This commit updates `Srp::Server` such that `Service` instances keep a
`RetainPtr` to a `Service::Description`. This allows a service and
all its sub-types to share the same `Description` instance and helps
simplify the management of the `Description` instances. When the last
`Service` that has a pointer to a shared `Description` is removed and
freed, the `Description` instance will be automatically freed as
well.
---------
Added a second smaller commit on this PR: 
**[common] add `Ptr` to use as base of `OwnedPtr` and `RetainPtr`**
This commit adds a new class `Ptr<Type>` which represents a wrapper
over a raw pointer. This is then used as the base class of `OwnedPtr`
and `RetainPtr` providing the common simple methods (avoiding repeating
the same code in each smart pointter). The new …
=> [srp-server] use `RetainPtr` to share `Description` among services

src/core/thread/mesh_forwarder_ftd.cpp
This commit fixes the incorrect call to `MessagePool::New()` to
allocate a message in `MeshForwarder::HandleMesh()` method. The
existing code calls `New(Message::kType6lowpan, priority)` with two
parameters which maps to the flavor `New()` method with three
parameters with last one (`Message::Settings`) being optional
(having a default value). Basically, the existing code treats the
`priority` (second argument) as `aReserveHeader` parameter in the
`New()` instead of the message priority.
-------
_A bit more detail on this_:
We have two flavors of `MessagePool::New()`:
```c++
Message *New(Message::Type aType, uint16_t aReserveHeader, Message::Priority aPriority);
Message *New(Message::Type            aType,
uint16_t                 aReserveHeader,
const Message::Settings &aSettings = …
```
=> [mesh-forwarder] ensure message allocation with correct priority

src/cli/cli.cpp, src/cli/cli_config.h
After changes in https://github.com/openthread/openthread/commit/6153855ae06f95903177d040dfc6fff994faf505, CLI prompt is printed on every CLI backend, not only CLI UART.
When running OT CLI in Zephyr, it's not desired to print a prompt after executing a command, as OT CLI is tightly integrated with Zephyr shell module which provides its own prompt.
Add a config option which allows to disable CLI prompt on the output.
=> [cli] add option to disable prompt

include/openthread/instance.h, include/openthread/link.h, src/cli/README.md, src/cli/cli.cpp, src/cli/cli.hpp, src/core/api/link_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, tests/scripts/thread-cert/Makefile.am, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_radio_filter.py
This commit implements new radio filter mechanism in OpenThread The
radio filter is mainly intended for testing. It can be used to
temporarily block all tx/rx on the IEEE 802.15.4 radio. When radio
filter is enabled, radio is put to sleep instead of receive(to ensure
device does not receive any frame and/or potentially send ack). Also
the frame transmission requests return immediately without sending
the frame over the air (return "no ack" error if ack is requested,
otherwise return success). This commit also add CLI command
`radiofilter` for this feature. It also adds `test_radio_filter` to
validate the behavior of the new feature. This feature requires
`OPENTHREAD_CONFIG_MAC_FILTER_ENABLE`.
=> [mac] add "Radio Filter" mechanism

src/core/coap/coap_secure.cpp, src/core/common/message.cpp, src/core/common/message.hpp, src/core/meshcop/dataset_updater.cpp, src/core/meshcop/joiner_router.cpp, src/core/net/dns_client.cpp, src/core/net/ip6.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/utils/child_supervision.cpp, tests/unit/test_dns.cpp, tests/unit/test_heap_string.cpp, tests/unit/test_hmac_sha256.cpp, tests/unit/test_lowpan.cpp, tests/unit/test_message.cpp, tests/unit/test_message_queue.cpp, tests/unit/test_priority_queue.cpp, tests/unit/test_spinel_buffer.cpp
This commit removes different `MessagePool` methods that can be used
to allocate a new message  and combines them into one `Allocate()`
method which uses `Message::Settings`. The `Message::Settings` is
also updated to provide new constructor initializing it with a given
message priority only.
---
Follow up from 
- https://github.com/openthread/openthread/pull/7203.
=> [message] simplify method for allocating new message from pool

tests/scripts/thread-cert/border_router/test_dnssd_server.py
We are switching from dd to xa to conform the latest spec.
Depends-On: openthread/ot-br-posix#1111
=> [tests] use xa instead of dd in the test case

include/openthread/instance.h, include/openthread/thread_ftd.h, src/cli/README.md, src/cli/cli.cpp, src/cli/cli.hpp, src/core/api/thread_ftd_api.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
Thread harness requirest to create thread network without checking the
if the thread protocol version is correct. This commit adds capability
to disable this check.
=> [cli] add command to skip VR check when upgrading to router or leader

src/core/common/timer.hpp
This commit updates `Timer` class constructor to be `protected` which
ensures that instances of `Timer` can not be created and only
instances of its sub-classes `TimerMilli` or `TimerMicro` can be
used. This helps avoid potential incorrect use of `Timer` class
directly.
=> [timer] declare `Timer` constructor as `protected`

src/core/crypto/storage.hpp, src/core/meshcop/dataset_local.cpp, src/core/meshcop/dataset_local.hpp, src/core/thread/key_manager.cpp, src/core/thread/key_manager.hpp
The support for crypto key references instead of literal keys was added some time ago, but the network key and PSKC are still persisted using the settings API, which typically just writes data to flash or other storage in unencrypted form.
When `OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE` is set, make sure that sensitive dataset items, such as the network key and PSKC, are persisted using the secure Crypto::Storage API (which should encrypt the stored data,
or use even secure hardware units) instead of  settings.
=> [crypto] store sensitive dataset items in ITS

src/core/thread/mle.cpp
fixing issue after static code analyzer run.
Signed-off-by: Marek Porwisz <marek.porwisz@nordicsemi.no>
=> [mle] fix out-of-bounds read (OVERRUN)

src/core/net/srp_client.cpp
This commit updates `Srp::Client` to skip appending services when the
host is being removed. On the first attempt the `mHostInfo.GetState()`
will be `kToRemove` but on the retries it will be `kRemoving`.
---
_Background:_
- Indirect follow up to https://github.com/openthread/openthread/pull/7216.
- It is an enhancement. There is no harm in including  services in a remove host
message but more efficient to omit them.
=> [srp-client] skip appending services on host remove retry

src/core/common/linked_list.hpp, src/core/common/owning_list.hpp, src/core/net/srp_client.cpp, src/core/net/srp_client.hpp, tests/unit/test_linked_list.cpp
This commit adds a new method `LinkedList::RemoveAllMatching()` which
removes all entries in the list matching a given entry indicator from
the list and adds them to a new "removed" list. A similar method is
also added in `OwningList`. This commit also updates the unit test
`test_linked_list` to validate the behavior of the new method.
This PR also contains a smaller related commit:
**[srp-client] use `LinkedList::RemoveAllMatching()`**
----
The `for` loop going over the linked-list entries while 
potentially removing some entries is kind of tricky (keeping
track of `prev`/`next` properly), so having a helper method
that does this can be helpful to avoid mistake.
=> [linked-list] add `RemoveAllMatching()` method

src/posix/platform/openthread-posix-config.h
In https://github.com/openthread/openthread/pull/6782, we add routes in linux kernel to enhance border routing feature. However, the current priority of the added routes too high so it may get preferred over routes learned from RA. Hence we increase the metric to de-prioritize the added routes.
=> [posix] deprioritize the added external routes

src/core/backbone_router/bbr_manager.cpp, tests/scripts/thread-cert/backbone/test_bmlr.py
BBR should send BMLR.ntf to the backbone upon successful de-registration as well.
This is verified in certification tests MATN-TC-17 and MATN-TC-18.
=> [mlr] send BMLR.ntf for de-registration

Android.mk, script/test, src/posix/platform/CMakeLists.txt, src/posix/platform/Makefile.am, src/posix/platform/firewall.cpp, src/posix/platform/firewall.hpp, src/posix/platform/netif.cpp, src/posix/platform/openthread-posix-config.h, src/posix/platform/system.cpp, src/posix/platform/utils.cpp, src/posix/platform/utils.hpp, tests/scripts/thread-cert/border_router/test_firewall.py, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/pktverify/packet_verifier.py, tests/scripts/thread-cert/pktverify/test_info.py, tests/scripts/thread-cert/run_cert_suite.py, tests/scripts/thread-cert/thread_cert.py
Re-sending the PR that implements firewall. It's the same as https://github.com/openthread/openthread/pull/7043. The previous PR was reverted due to flaky CI.
The following is copied from https://github.com/openthread/openthread/pull/7043.
-----
This PR implements OTBR firewall. It should be merged together with https://github.com/openthread/ot-br-posix/pull/1063. This implementation focuses on ingress filtering. We may also introduce egress filtering when necessary.
For security purpose, there are some packet forwarding rules to follow, which were originally introduced in the spec.
Inbound packets initiated with On-Link addresses source (OMR and mesh local prefix based addresses) should be blocked.
Inbound unicast packets whose destination address is not OMR address or DUA should be …
=> [firewall] ingress filtering

src/posix/platform/backbone.cpp, src/posix/platform/infra_if.cpp
The Backbone Router and Border Routing feature will be silently disabled when
the infra/backbone interface is not provided. We should at least print a warning
log in this case since it may not be intentional.
=> [posix] logging when infra/backbone interface is not provided

src/core/common/owning_list.hpp, tests/unit/test_linked_list.cpp
This commit fixes the `OwningList::RemoveAllMatching()` to use the
`LinkedList` one. It also updates unit test `test_linked_list` to
cover this method.
=> [linked-list] fix `OwningList::RemoveAllMatching()`

src/core/backbone_router/bbr_local.cpp
Thread Certification test plan requires that the reference device configures a MLR Timeout lower than the allowed by the specification.
=> [bbr] allow lower MLR Timeout for reference device

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_BR.py
Make use of the `mcast6.py` application in order to listen to multicast traffic on the host side when required by the harness.
=> [thci] register multicast addresses on the host side

src/cli/cli.cpp, src/cli/cli.hpp
This commit adds `OPENTHREAD_CONFIG_RADIO_LINK_IEEE_802_15_4_ENABLE`
check to CLI methods related to `radiofilter` command which ensures that this 
command is  only available when 15.4 radio is enabled. This
allows us to build CLI app successfully with TREL radio only.
=> [cli] limit `radiofilter` command to when 15.4 radio link is enabled

tools/harness-thci/OpenThread.py
In some cases the first element from the output from __executeCommand might be empty line, which casues command failures like on below trace:
__executeCommand('extaddr',) returns ['', '166e0a0000000001', '', 'Done']
FUNC getMAC failed: invalid literal for int() with base 16: ''
This PR filters out empty string from the result of __executeCommand
=> [thci] drop empty lines returned in command outout from the response

src/posix/platform/spi_interface.cpp
The `GPIOHANDLES_MAX` represents the maximum number of requested handles.
It should not be used to check the GPIO line offset.
=> [posix] remove GPIO line offset check

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
Currently, we will start routing policy evaluation when new OMR prefixes are received
as RIO options in RA messages. But it's not necessary to do so because whether
we need to advertise our own OMR prefix is not depending on the discovered OMR
prefixes from Wi-Fi link but the OMR prefixes in Thread network data.
=> [routing-manager] don't reevaluate routing policy for OMR prefixes in RA messages

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/config/border_router.h
This commit adds `OPENTHREAD_CONFIG_BORDER_ROUTING_VICARIOUS_RS_ENABLE` configuration to allow disabling `Vicarious Router Solicitation` feature.
=> [border-routing] add configuration for Vicarious Router Solicitation

tools/harness-thci/OpenThread_BR.py
Previous approach with `dig` was not enough because it was only parsing one mDNS response and not taking account that the response could be from an inactive Border Router.
Use Python Zeroconf to properly parse all services.
=> [thci] improve mDNS browsing using Zeroconf

src/core/border_router/routing_manager.cpp
This commit fixes the bug that BR may not respond to a `Router Solicit`  with a `Router Advertisement` when the BR itself is Router Soliciting. 
This bug may cause `Vicarious Router Solicitation` more likely to fail because BRs may failed to send RA for vicarious RS.
=> [border-routing] always respond to Router Solicit with `Router Advertisement`

src/core/border_router/routing_manager.cpp
We should re-evaluate routing policy only when a discovered on-link prefix
becomes deprecated or preferred. This change reduces sending RA messages
when another peer is keep advertising deprecated (preferred lifetime is zero)
on-link prefix.
=> [routing-manager] start routing policy evaluation when on-link prefix state changes

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
Current implementation will reschedule the Stale Timer when discovered on-link or
OMR prefixes or RA messages are updated, but it has a few issues:
1. It's counting the maximum stale time of all on-link prefixes so that we will schedule
Router Solicitation when all on-link prefixes become stale. But it failed to filter out
OMR prefixes in the `mDiscoveredPrefixes` list. This results in incorrect stale time
calculation.
2. A deprecated on-link-prefix is not removed from `mDiscoveredPrefixes` directly
but the preferred lifetime is set to zero. We are not filtering out deprecated
on-link prefixes when calculating stale time and this results in zero stale timer
delay if there are no non-deprecated on-link prefixes.
This commit fixes those issues by having a dedicated …
=> [border-routing] fix stale prefixes checking timer

src/core/backbone_router/bbr_manager.cpp
Thread specification defines `MLR_TIMEOUT_MIN` as the minimum value of the MLR Timeout in the BBR Dataset, but this does not affect to the Timeout TLV in the Multicast Registration Request messages.
=> [mlr] `MLR_TIMEOUT_MIN` does not apply to MLR.req

src/cli/README.md, src/cli/cli.cpp
This commit adds a new sub-command for `ipaddr` to print more informations .
=> [cli] add option to print more information for `ipaddress`

src/core/meshcop/border_agent.hpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dtls.cpp, src/core/net/dns_client.hpp, src/core/net/netif.hpp, src/core/net/socket.hpp, src/core/net/srp_client.hpp, src/core/net/udp6.hpp, src/core/radio/trel_interface.cpp, src/core/thread/network_data_types.hpp, src/core/utils/ping_sender.hpp
In PR #7128, the `DefineCoreType()` & `DefineMapEnum()` definitions
(which map the public and core types) were moved to header files
that define the corresponding core type. This allows us to use the
`AsCoreType()` in header files. This commit changes some of inline
methods in the core headers to use it.
=> [core] use `AsCoreType` in header files

src/core/backbone_router/bbr_manager.cpp, src/core/common/tlvs.cpp, src/core/common/tlvs.hpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/meshcop.cpp, src/core/meshcop/meshcop_leader.cpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/thread/network_data.cpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_local.cpp, src/core/thread/network_data_tlvs.hpp, src/core/thread/network_diagnostic.cpp
This commit adds a set of `As<TlvType>()` methods which cast from base
`Tlv` pointer or reference to a specific sub-class `TlvType` while
preserving whether the input parameter is `const` or not. This
basically acts as a syntax sugar for this commonly used pattern in the
code.
=> [tlv] add `As<TlvType>()` helper methods

src/cli/README_HISTORY.md, src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_history.cpp, src/cli/cli_history.hpp
This commit changes `AddressOriginToString()` to be a public `static`
method of `Cli::Interpreter` so we can reuse it in `Cli::History`
module and potentially other modules in future. It also removes
similar method from `Cli::History`.
=> [cli] reuse `AddressOriginToString()` among CLI modules

src/core/meshcop/announce_begin_client.cpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/energy_scan_client.cpp, src/core/meshcop/joiner.cpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/meshcop.hpp, src/core/meshcop/meshcop_leader.cpp, src/core/meshcop/panid_query_client.cpp, src/core/thread/energy_scan_server.cpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/panid_query_server.cpp
This commit removes the function `MeshCoP::NewMeshCoPMessage()` and
uses `NewPriorityMessage()` method directly on `Coap::CoapSecure` or
`Tmf::Agent`. This helps harmonize the message allocation model by
MeshCoP modules.
=> [meshcop] use `NewPriorityMessage()` for message allocation

include/openthread/instance.h, include/openthread/joiner.h, src/cli/README_JOINER.md, src/cli/cli_joiner.cpp, src/cli/cli_joiner.hpp, src/core/api/joiner_api.cpp, src/core/meshcop/joiner.hpp
This commit adds new CLI command `joiner state` to get the current
state of `Joiner`. It also adds new public OT API to convert a given
`otJoinerState` to a string.
=> [cli] add `joiner state` command

src/core/border_router/routing_manager.cpp
This commit enhances Border Routing to ignore discovered OMR Prefixes when Network Data change.
It's possible that a BR may learn an OMR prefix from RA, and later learn the same OMR Prefix from Network Data.
In such case, the BR should remove the discovered OMR Prefix.
=> [border-routing] invalidate discovered OMR prefixes when Network Data change

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit unifies how immediate or delayed routing policy evaluation is initiated. 
This commit also removes `mRouterAdvertisementTimer` to reduce memory footprint.
=> [border-routing] unify initiating routing policy evaluation

tools/harness-thci/OpenThread_BR.py
When looking for the Border Agent's link local address in the mDNS response do not consider a possible IPv4 address record.
=> [thci] discard IPv4 link local address in mDNS browsing

src/posix/platform/netif.cpp
This commit helps reduce posix-netif WARN logs when transmitting messages to Thread. 
There are certain ICMPv6 messages (e.g. MLDv2) that OpenThread will filter when transmitting, so the error `OT_ERROR_DROP` is expected. 
This commit also assumes that OpenThread knows what it's doing when it choose to drop a message, thus using lower log level for `OT_ERROR_DROP`.
=> [posix-netif] lower transmit log level for `OT_ERROR_DROP`

src/cli/cli.cpp
Proposed CLI change for same reason as #7252 . Because the 2 addresses are registered sequentially from the same method call, the OpenThread stack will not have had the opportunity to send out MLR.req with a single address. So this should result in sending out one MLR.req with two addresses inside, if 2 addresses are provided.  Without changes in the APIs.
=> [cli] support 1 or more mcast addresses for `ipmaddr add` command

src/posix/platform/netif.cpp
Set `OT_ICMP6_ECHO_HANDLER_ALL` when building reference device Posix border router.
=> [posix] enable all ICMPv6 echo handling for reference device

src/core/mac/mac.cpp, src/core/mac/mac.hpp
This commit updates how `Mac` tracks the pending operations by using
a bitset `mPendingOperations` replacing the current model using a
set of `bool` variables per operation.
=> [mac] simplify tracking of pending operations

src/core/diags/factory_diags.cpp, src/core/diags/factory_diags.hpp
Some platform diag commands (those not in factory_diags module) will
also do repeat sending and the same callback (Diags::TransmitDone)
will be called. However, in those cases, `mRepeatActive` won't be set.
And if some error (like 'CHANNEL_ACCESS_FAILURE') happened,
`TransmitPacket` will be called then, which makes the channel even
more busy, causing more 'CHANNEL_ACCESS_FAILURE', and so on. This PR
ensures that `TransmitPacket` will only be called again when using
`diag send`.
=> [diag] only do re-tx for diag sending

src/cli/cli.cpp, src/cli/cli_commissioner.cpp, src/cli/cli_history.cpp, src/cli/cli_output.cpp, src/cli/cli_output.hpp, src/cli/cli_srp_server.cpp, src/cli/cli_tcp.cpp, src/core/backbone_router/bbr_leader.cpp, src/core/radio/trel_link.cpp, src/core/thread/address_resolver.cpp, src/core/thread/topology.cpp
This commit updates different modules in OT core and CLI to use
`const` array lookup to convert an enumeration value to string.
=> [core] use const array lookup for converting enum to string

src/cli/README.md
The link was previously broken and was not pointing at the first `route` command.
=> [docs] fix the link to route command in CLI doc

src/core/crypto/ecdsa.hpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp
Current `Srp::Server` is comparing the entire KEY RRs to determine if the two SRP messages
are using the same signing key. But the TTL in the KEY RR can change even between two
SRP messages of the same client and this will result in false name conflicts.
This commit fixes this issue by changing to compare only the rdata of the KEY RR.
=> [srp-server] identify name conflicts by comparing only ECDSA public keys

examples/platforms/simulation/alarm.c
When the type `time_t` is 32 bits wide, the current code will truncate
the value of time and returns a wrong value.
=> [simulation] fix the wrong timeout value issue

src/lib/platform/exit_code.h
In some build systems, source files is passed as absolute path, log
messages may be truncated. This commit makes VerifyOrDie only prints
basename of the source file.
=> [logging] print basename of source file

src/core/mac/sub_mac.cpp
The RX window when not using RX AT mode is much larger than the correct time and
what is reported by the Open Thread log.
In the case of "receive at" we want the timer to fire before the next RX window to program the
exact RX activity in the radio and in the other case, the timer will fire when the current RX
window will end to close the receiver and go to sleep.
This commit fixes the issue by increasing the sample time with the CSL period before starting the
timer in the case of RX AT and after in the normal RX case.
=> [csl] fix the CSL RX window when not using RX AT mode (#7284)

src/core/mac/sub_mac.cpp
Do all the calculations on uint32_t to prevent
bad wraparound check due to mixing uint32_t with uint64_t.
Fixes #7054
=> [sub-mac] fix `elapsed` time in `GetCslWindowEdges()`

.github/workflows/otbr.yml
This commit sets `MAX_JOBS` to 3 for Border Router tests (using OTBR Docker) to improve reliability.
The original `MAX_JOBS` value is 10. 
Related metrics:
- Border Router tests takes 12 minutes with MAX_JOBS=10
- Border Router tests takes 24 minutes with MAX_JOBS=3
=> [github-actions] set MAX_JOBS=3 for `Border Router` tests

src/posix/platform/include/openthread/openthread-system.h, src/posix/platform/infra_if.cpp, src/posix/platform/infra_if.hpp
When setting the IP forwarding rule on Android platform, it needs to
specify the two interfaces between which IP forwarding is enabled.
This PR adds a method to get the infra interface name for setting IP
forwarding rule.
=> [posix] add a method to get the infra interface name

.github/workflows/otbr.yml, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/thread_cert.py
This commit introduces a number of enhancements to `thread-cert` Border Router tests to improve reliability:
- Checks `ot-rcp` process status for OTBR tests to help catch errors earlier
- Make sure `ot-rcp` processes are terminated after one test to avoid corrupting subsequent tests
- Upload core dump as artifacts if otbr-agent crashed
=> [thread-cert] misc enhancements to improve reliability

.github/workflows/otbr.yml, tests/scripts/thread-cert/thread_cert.py
This commit caches Border Router test results so that success BR tests will be skipped when re-running the workflow.
The cache keys are chosen in a way that:
- Each new PR push will trigger cache miss and run the tests
- Each ot-br-posix change will trigger cache miss and run the tests
=> [thread-cert] cache Border Router test results

src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_srp_client.cpp
This commit contains smaller changes in CLI modules:
- Remove unused method declarations.
- Remove unnecessary `SuccessOrExit()` or `ExitNow()`.
- Convert `else` blocks into `else if` sequence (to remove extra
indentation).
=> [cli] smaller style changes

src/core/api/ip6_api.cpp, src/core/common/instance.hpp, src/core/common/settings.hpp, src/core/net/dhcp6.hpp, src/core/thread/thread_netif.hpp
This commit removes the extra `#if` config checks in core files before
`#include` of different headers. Such a check is not necessary since
the OT core headers all start with any related `#if` config check.
=> [core] remove extra `#if` config check before header includes

include/openthread/backbone_router_ftd.h, include/openthread/instance.h, src/cli/README.md, src/cli/cli.cpp, src/core/api/backbone_router_ftd_api.cpp, src/core/backbone_router/bbr_local.cpp, src/core/backbone_router/bbr_local.hpp, tools/harness-thci/OpenThread.py
When building a reference device do not increase the BBR Dataset Sequence Number when restoring from the received Network Data.
The Thread Harness uses the THCI send_udp to publish convenient BBR dataset on behalf of the reference device.
=> [bbr] add `bbr skipseqnuminc` command for reference device

src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_local.cpp, src/core/thread/network_data_local.hpp
This commit adds new methods in `NetworkData` to indicate whether or
not it contains a given on mesh prefix, external route, or service
entry. It also adds a new method to check whether it contains all
entries as in another given Network Data all associated with a given
RLOC16. This is then used to simplify comparison between `Local` and
`Leader` network data.
----
Some more details on this PR:
- It replaces existing `Contains{Prefixes/Routes/Services}` which check for a set
of entries with simpler methods that check for one entry. I think these will be useful 
in other situations (e.g., will use them in `HistoryTracker` to track net data changes)
- Combine all the `Local::Is{Prefix/Route/Service}Consistent()` into one that does 
all the checks together.
=> [netdata] simplify checking if network data contains certain entries

src/core/mac/data_poll_sender.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp
The `aFrame.IsDataRequestCommand()` call was checking the frame that had been already encrypted.
This PR fixes that by using `aIsDataPoll` parameter instead.
=> [csl] properly provide IsDataPoll info for determining number of CSL retx

tests/scripts/expect/cli-commissioner.exp
This commissioner fix the wrong commissioner mgmt cli args which
uses "binary" to indicate following binary args in HEX string -
the format has been changed to "-x" in PR#5549.
The cause why cli-commissioner.exp doesn't fail consistently is
not fixed by this commit.
=> [cli] fix invalid `commissioner mgmtget` cli arguments in tests

src/core/meshcop/meshcop_tlvs.cpp, src/core/thread/key_manager.cpp
Existing deployed networks may have Operational Datasets where the
Security Policy TLV includes a Rotation Time value of 0. Not accepting
such datasets does not allow a Thread device to attach properly.
This commit removes the requirement that the Rotation Time value must
be greater than the minimum value of one hour.
---
See this [openthread-users email](https://groups.google.com/g/openthread-users/c/UsgEMScMQlQ/m/wYKu-plXBQAJ) for context.
=> [dataset] accept too small Rotation Time in Security Policy TLV

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/network_data.cpp, src/core/thread/network_data.hpp
This commit updates the handling of service ALOCs in `Mle` by adding a
new class `ServiceAloc` (subclass of `Ip6::Netif::UnicastAddress`)
which provides some simple helper methods (e.g., `IsInUse()` to
indicate whether the entry is currently added to `ThreadNetif`). It
also simplifies `UpdateServiceAlocs()` which adds and removes ALOCs
based on the service entries in the Thread Network Data. These changes
allow us to remove some service related methods from `NetworkData`
which are no longer needed or used (harmonizing how we iterate over
service entries in Network Data).
=> [mle] simplify management of service ALOCs

include/openthread/history_tracker.h, include/openthread/instance.h, src/cli/README_HISTORY.md, src/cli/cli_history.cpp, src/cli/cli_history.hpp, src/cli/cli_network_data.cpp, src/cli/cli_network_data.hpp, src/core/api/history_tracker_api.cpp, src/core/config/history_tracker.h, src/core/utils/history_tracker.cpp, src/core/utils/history_tracker.hpp
This commit adds a mechanism in `HistoryTracker` to track changes in
Thread Network Data maintaining a history of on-mesh prefix and
external route entries as they are added or removed by different
nodes in Network Data. This commit also adds new `cli history`
commands to retrieve the Network Data prefix/route history list and
updates the documentation in `cli/README_HISTORY.md`.
=> [history-tracker] support tracking netdata prefix and route entries

src/cli/cli_tcp.cpp, third_party/tcplp/bsdtcp/tcp_reass.c
This pull request fixes minor bugs in TCP.
1. The first change fixes a bug where the TCP CLI prints out an incorrect message when a connection is terminated. This appears to have been introduced in #7279.
2. The second change fixes a null pointer dereference when accepting a TCP connection. This issue is purely theoretical at the moment, because in the case where the dereferenced pointer is NULL, the dereferenced value is not used, and so the compiler optimizes out the memory access (so it seems). As a result, TCP actually runs without issues. But I've fixed it anyway, to avoid depending on that behavior.
=> [tcp] fix minor bugs

src/core/api/border_router_api.cpp, src/core/api/netdata_api.cpp, src/core/api/server_api.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_tlvs.hpp, src/core/thread/mle_types.cpp, src/core/thread/mle_types.hpp, src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp, src/core/thread/network_data_types.hpp, src/core/thread/network_diagnostic.cpp, src/core/thread/topology.cpp, src/core/thread/topology.hpp, src/core/utils/history_tracker.cpp, src/core/utils/otns.cpp, tests/unit/test_lowpan.cpp
This commit adds `NetworkData::Type` enumeration to indicate full set
or stable subset. It also adds helper method `GetNetworkDataType()`
in `Neighbor` and `Mle` to indicate what type of Network Data device
requests.
=> [netdata] add `NetworkData::Type` enum for full or stable subset

src/core/BUILD.gn, src/core/Makefile.am, src/core/common/serial_number.hpp, src/core/common/time.hpp, src/core/net/ip6_mpl.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/network_data_service.hpp, src/core/thread/topology.hpp, tests/unit/CMakeLists.txt, tests/unit/Makefile.am, tests/unit/test_serial_number.cpp
This commit adds `SerialNumber` class which provides `static` methods
`IsGeater<UintType>()` and `IsLess<UintType()` to compare two serial
numbers, taking into account the wrapping of serial number values
(similar to RFC-1982). This is then used in `MleRouter` and other
modules. This helps us avoid casting of `uint` to `int` for the
comparison (such a casting is undefined behavior in C++11 though
toolchains often implement it as expected). This commit also adds a
unit test `test_serial_number` to validate the new methods.
=> [common] add `SerialNumber::Is{Greater/Less}>()`

.github/workflows/otbr.yml
This commit sets set fail-fast=false for border router tests.
=> [github-actions] set fail-fast=false for border router tests

script/cmake-build
This commit allows calling this cmake-build script from a different directory. Currently it only supports root of OpenThread source.
=> [script] support cmake-build in different dir

src/cli/cli.cpp, src/cli/cli.hpp
----
- The main intention behind this PR is to simplify and harmonize the CLI 
`Process{Command}()` methods.
- This can help us move to new model later (in a future PR) where we can use
template specializations for each `Process<Command>` rather than defining different
methods (which in turn can help simplify the command lookup table  maintenance).
=> [cli] inline simple sub-command process methods

src/core/net/ip6.cpp
After #7187, we've observed MLDv2, RS and other ICMPv6 packets from the kernel forwarded to the Thread network. This is caused by the ICMP6 type check turned off by aFromNcpHost.
The PR turns ICMP filtering to always on when forwarding to the Thread network.
=> [ip6] always enable ICMP6 filtering when forwarding to Thread

src/core/backbone_router/bbr_manager.cpp, src/core/thread/address_resolver.cpp, src/core/thread/address_resolver.hpp, src/core/thread/mesh_forwarder_ftd.cpp
This commit adds `AddressResolver::LookUp()` method which resolves
an EID to an RLOC17 by checking if an existing entry already exists
in the address cache table.
=> [address-resolver] add `LookUp()` method to check cache entries

include/openthread/coap.h, include/openthread/instance.h, src/core/api/coap_api.cpp
Provide a setter for the message code to change it after
initialization of the message.
This complements the existing getter function 'otCoapMessageGetCode'.
=> [coap] add `otCoapMessageSetCode` (#7339)

src/core/backbone_router/backbone_tmf.cpp, src/core/backbone_router/backbone_tmf.hpp, src/core/backbone_router/bbr_manager.cpp, src/core/backbone_router/bbr_manager.hpp, src/core/common/logging.hpp, src/posix/platform/multicast_routing.cpp
This commit removes the `otLogResult{Bbr/Platform}()` macros from
`logging.hpp` and instead have each module implement `LogError()`
method. The main goal behind this change to simplify the logging
module and reduce number of macros/definitions in it (to prepare for
new logging model to be introduced).
=> [logging] remove `otLogResult` 

Android.mk, include/openthread/instance.h, include/openthread/tcp.h, src/core/api/tcp_api.cpp, src/core/net/tcp6.cpp, src/core/net/tcp6.hpp, tests/unit/Makefile.am, third_party/tcplp/bsdtcp/cc.h, third_party/tcplp/bsdtcp/cc/cc_module.h, third_party/tcplp/bsdtcp/icmp_var.h, third_party/tcplp/bsdtcp/ip.h, third_party/tcplp/bsdtcp/ip6.h, third_party/tcplp/bsdtcp/sys/queue.h, third_party/tcplp/bsdtcp/tcp.h, third_party/tcplp/bsdtcp/tcp_const.h, third_party/tcplp/bsdtcp/tcp_fsm.h, third_party/tcplp/bsdtcp/tcp_input.c, third_party/tcplp/bsdtcp/tcp_output.c, third_party/tcplp/bsdtcp/tcp_seq.h, third_party/tcplp/bsdtcp/tcp_subr.c, third_party/tcplp/bsdtcp/tcp_timer.c, third_party/tcplp/bsdtcp/tcp_timer.h, third_party/tcplp/bsdtcp/tcp_timewait.c, third_party/tcplp/bsdtcp/tcp_var.h, third_party/tcplp/bsdtcp/types.h, third_party/tcplp/tcplp.h
This is the ninth and final pull request in a series of pull requests (after #6744, #6770, #6790, #6857, #6885, #6925, #6926, and #7074) bringing TCPlp to OpenThread (see #6456). I'm making a series of small pull requests so that it's easier for the OpenThread community to review the code.
This pull request contributes support for the OpenThread TCP API (see #6411 and #6491) using the FreeBSD-derived functions from #7074. It is a rewrite of TCPlp's interface layer to support OpenThread's TCP API instead of the API used previously by TCPlp. Once this pull request is merged, the OpenThread CLI's TCP utility will work, and most of the OpenThread TCP API will work.
This pull request completes the sequence of pull requests bringing TCPlp to OpenThread. In previous pull requests, I pointed to …
=> [tcp] add rewrite of TCPlp's interface code to support OpenThread's TCP API

Android.mk, src/core/config/ip6.h, src/core/config/openthread-core-config-check.h, src/core/net/ip6.cpp
----
Background:
- Please see discussion at https://github.com/openthread/openthread/pull/7343#discussion_r792089798
- This config and its behavior was added to enable certain internal use-case (weave pairing) - which is no longer needed.
- If we need similar behavior (in future) it would be better to add this at next layer (e.g. otbr or wpantund), i.e. the next layer can perform a similar check (parse and get the UDP port to determine whether to disable link security  before passing the packet down to OT stack).
=> [ip6] remove `UNSECURE_TRAFFIC_MANAGED_BY_STACK_ENABLE` config

tools/harness-thci/OpenThread.py
THCI used to catch Exceptions and print errors using `ModuleHelper.WriteIntoDebugLogger`. However, in most of time it just help hide the actual issue and make it harder to debug. 
Re-raising the exceptions should be a better approach:
- @API decorator will print the full exception Traceback via `ModuleHelper.WriteIntoDebugLogger` and then re-raise.
=> [thci] print traceback and re-raise exceptions

tools/harness-thci/OpenThread.py
enabling registration to multiple mcast addresses on the same command line in THCI
=> [thci] update `registerMulticast` to align with #7253

src/core/net/tcp6.cpp, third_party/tcplp/bsdtcp/cc/cc_newreno.c, third_party/tcplp/bsdtcp/tcp.h, third_party/tcplp/bsdtcp/tcp_input.c, third_party/tcplp/bsdtcp/tcp_output.c, third_party/tcplp/bsdtcp/tcp_reass.c, third_party/tcplp/bsdtcp/tcp_sack.c, third_party/tcplp/bsdtcp/tcp_subr.c, third_party/tcplp/bsdtcp/tcp_timer.c, third_party/tcplp/bsdtcp/tcp_usrreq.c, third_party/tcplp/lib/bitmap.c, third_party/tcplp/tcplp.h
This pull request improves logging in TCP, by doing the following:
* Avoid calling `printf` from TCPlp code, even for error handling, and instead use OpenThread's logging
* Omit newlines in TCPlp log messages, since OpenThread's logging adds a newline already
* Add a new call, `tcplp_sys_panic`, to use to handle assertion failures in TCPlp
In removing `printf` from TCPlp, this pull request resolves openthread/ot-qorvo#210.
=> [tcp] improve logging in TCPlp

src/core/crypto/crypto_platform.cpp
To avoid "unused variable" compiler warning.
```
/Users/runner/work/ot-br-posix/ot-br-posix/third_party/openthread/repo/src/core/crypto/crypto_platform.cpp:70:33: fatal error: unused variable 'kEntropyMinThreshold' [-Wunused-const-variable]
static constexpr uint16_t       kEntropyMinThreshold = 16;
^
1 error generated.
```
https://github.com/openthread/ot-br-posix/runs/5009245865?check_suite_focus=true
=> [crypto] add feature flag around kEntropyMinThreshold

tests/scripts/expect/cli-tcp.exp
This pull request adds a test that uses the CLI tool to verify basic TCP functionality. The test runs as part of `script/test expect` and therefore will be run as part of the OpenThread CI test suite (as requested by @jwhui in #7190).
Currently the test fails. But once #7190 and #7335 are merged, I believe that this test will pass.
=> [tcp] add basic CLI-based test

include/openthread-config-android.h
This commit disables the legacy network support.
Tested by GitHub workflow.
=> [android] disable legacy support

include/openthread/instance.h, include/openthread/link.h, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mle.cpp
This commit adds a flag in Thread link info to indicate whether
destination PAN ID is broadcast.
Verfied by running two simulation nodes (modified announce sender
interval) of different Thread networks and make sure there are no
logs of `[WARN]-MLE-----: Failed to process UDP: Security` when
receiving MLE Announce messages.
=> [mle] fix comparing PAN ID to skip logging

src/core/net/dns_types.hpp, src/core/radio/trel_interface.cpp
This commit changes the TXT record data format to use binary value
for extended address and extended PAN ID entries.
Depends-On: openthread/ot-br-posix#1234
=> [trel] change TXT data format to use binary value

script/test, tests/scripts/thread-cert/border_router/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/test_multi_thread_networks.py, tests/scripts/thread-cert/border_router/test_nat64_multi_border_routers.py, tests/scripts/thread-cert/border_router/test_nat64_single_border_router.py, tests/scripts/thread-cert/border_router/test_radvd_coexist.py, tests/scripts/thread-cert/border_router/test_single_border_router.py, tests/scripts/thread-cert/border_router/test_vicarious_router_solicit.py, tests/scripts/thread-cert/node.py
This PR adds tests for NAT64 prefix advertisement. BORDER_ROUTING_NAT64 is set to 1 to enable the feature in tests.
It also adjusted some util functions for prefixes and routes in netdata.
Testing outbound connectivity to IPv4 hosts is not covered yet. It will be added after we update OTBR.
=> [tests] add tests for NAT64 prefix advertisement

src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/thread/mesh_forwarder_ftd.cpp
----
The parameter name was added when OT was mainly being used in NCP mode. 
This PR is renaming it to `aFromHost` to be more generic and applicable to all
all use-cases.
There are possibilities of other optimizations/simplifications related to this (e.g., 
the `Netif *` can be  be used to indicate origin of message in `HandleDatagram()`). 
We can tackle these in future PRs.
=> [ip6] rename `aFromNcpHost` to `aFromHost`

src/core/thread/mle_router.cpp
This commit updates the `SendChildIdResponse()` to check in the case
that the child already has a previously assigned RLOC16 that it
matches the current router ID of the parent and if not we assign a new
RLOC16 to it in the "Child ID Response".
----
Should help address https://github.com/openthread/openthread/issues/7366.
=> [mle] check router ID match when sending Child Id Response

src/core/thread/mle.cpp
The Child ID Response message contains the RLOC16 that the Parent
assigns to the Child. Add a check to ensure that Parent's and Child's
Router IDs match. If the Router IDs do not match, drop the Child ID
Response message.
=> [mle] drop Child ID Response if Router IDs do not match

src/posix/platform/spi_interface.cpp, src/posix/platform/spi_interface.hpp
This commit updates the `SpiInterface` implementation to send any
pending tx SPI frame from `WaitForFrame()` while waiting for a
response frame from RCP. This should help address rare RCP response
timeout which can potentially happen if RCP is not yet ready to
accept a frame in a first SPI transaction from a `SendFrame()` call
followed by a call to `WaitForFrame()`.
This commit updates the `WaitForFrame()` to reuse `UpdateFdset()` and
`Process()` methods which in turn handle the situation that central
is being rate-limited by the peripheral.
---
- This is related to https://github.com/openthread/openthread/issues/7429
=> [spi-interface] send pending frame from `WaitForFrame()`

src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_coap.cpp, src/cli/cli_coap.hpp, src/cli/cli_commissioner.cpp, src/cli/cli_commissioner.hpp, src/cli/cli_dataset.cpp, src/cli/cli_dataset.hpp, src/cli/cli_history.cpp, src/cli/cli_history.hpp, src/cli/cli_joiner.cpp, src/cli/cli_joiner.hpp, src/cli/cli_network_data.cpp, src/cli/cli_network_data.hpp, src/cli/cli_output.hpp, src/cli/cli_srp_client.cpp, src/cli/cli_srp_client.hpp
This commit updates how the CLI command handlers are defined. A
template `Process<CommandId>()` method is now used to process a CLI
command where the `CommandId` is a `uint64` hash ID derived from
the command string itself.
This model helps simplify the CLI modules. With this change, there is
no need to declare different process methods for every CLI command in
the header files. It also makes the association between a CLI command
and its command string explicit and simple (e.g., `"state"` command
with `Process<Cmd("state")>` method).
=> [cli] use template `Process<Cmd("command")>` to simplify handlers

src/core/meshcop/dtls.cpp
Some of the private fields are changed to public again in MbedTLS 3.1, update dtls to match these changes
=> [crypto] changes to dtls code to match mbedtls 3.1.0

include/openthread/instance.h, include/openthread/ip6.h, src/cli/cli_output.cpp, src/core/backbone_router/ndproxy_table.cpp, src/core/border_router/routing_manager.cpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/meshcop.cpp, src/core/net/netif.cpp, src/core/net/netif.hpp, src/core/thread/address_resolver.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/lib/spinel/radio_spinel_impl.hpp, src/posix/platform/netif.cpp, tests/unit/test_netif.cpp
This commit refines `NOTE` and `WARN` logs:
- Certain `INFO` and `WARN` logs are changed to `INFO` since they are normal situations.
=> [logging] refine `NOTE` and `WARN` logs

src/core/net/dns_client.cpp
This commit updates `Dns::Client` such that when parsing a query
response we allow and accept a message with empty question section if
the response code in header indicates an error. This ensures that the
`Dns::Client` can work with DNS name resolvers that may not echo back
the question section in case of an error response.
=> [dns-client] allow empty question section in response with error code

tests/unit/test_ecdsa.cpp
This commit updates `kMessage` in `test_ecdsa.cpp` function which
verifies the signature generation to be an array of char instead of a
`char *`. This ensures that the use of `sizeof(kMessage)` correctly
gives the length of the message string (which is used during hash
calculation).
----
- Should help resolve https://github.com/openthread/openthread/issues/7444.
=> [test] fix `test_ecdsa` to use array of char as message string

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/thread/network_data_local.cpp, src/core/thread/network_data_local.hpp
This commit fixes two small issues regarding OMR prefix election:
- This commit handles the case where `mLocalOmrPrefix` is already in Leader's Network Data, but not locally added. It is possible when the BR restores the Network Data from Leader. In such case the BR should re-add `mLocalOmrPrefix` to local Network Data so that it keeps advertising OMR Prefix. Otherwise, the OMR Prefix will be removed from Leader's Network Data because of Network Data inconsistentency, and then all BRs start to re-elect OMR Prefix. So, the change will make the OMR Prefix more stable in some corner cases.
- The change here checks if `mLocalOmrPrefix` was added to the Local Network Data, instead of checking if `mLocalOmrPrefix` is added to the Leader's Network Data.
Here the BR has already decided that it …
=> [routing-manager] fix small OMR prefix election issue

tests/scripts/thread-cert/border_router/test_dnssd_server_multi_border_routers.py, tests/scripts/thread-cert/border_router/test_mdns_restart.py, tests/scripts/thread-cert/node.py
I just found that we don't have a test case covers the scenario of DNS-SD when there are multiple BRs. Specially, one of the BRs starts with no mDNS cache.
There was a time that our mDNS publisher answered the queries correctly, even when there was a bug in mDNS publisher that it cancelled resolving/browsing too early (was fixed in https://github.com/openthread/ot-br-posix/pull/1120). That bug was hidden because mDNS cache already contained the needed information.
=> [tests] add a multi-BR DNS-SD server test case

src/core/net/ip6.cpp
IPv6 fragments are unconditionally forwarded to the host even if the option: OT_IP6_FRAGM for internal reassembling is enabled. It results with e.g. for RCP echo request are handled twice, by the OpenThread and by the host.
This commit changes it in this way that when OT_IP6_FRAGM is enabled IPv6 fragments are not forwarded to the host any more but handled internally only. When OT_IP6_FRAGM is disabled the IPv6 fragments are always forwarded to the host. This case is especially important for NCP architecture with spinel maximum frame size limitation (1500B).
Now the option: OT_IP6_FRAGM should be disabled for NCP to allow forwaring IPv6 fragments to the host.
=> [ip6] forward IPv6 fragments only if reassebling is disabled

include/openthread/dns_client.h, include/openthread/instance.h, src/cli/cli.cpp, src/core/api/dns_api.cpp, src/core/net/dns_client.cpp, src/core/net/dns_client.hpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp, tests/scripts/expect/tun-dns-client.exp
This commit adds a new mechanism in `Dns::Client` along with a new
public OT API `otDnsClientResolveIp4Address()` and its related CLI
sub-command to allow a user to request an address resolution DNS
query specifically for A records or IPv4 addresses for a given host
name.
This API requires `OPENTHREAD_CONFIG_DNS_CLIENT_NAT64_ENABLE` to be
enabled. Upon receiving a successful query response the addresses are
reported to user (in callback) as NAT64 IPv6 translated versions of
the IPv4 addresses from the received query response.
The new API is added in addition to the existing behavior where address
resolution query from `otDnsClientResolveAddress()` first queries for
IPv6 addresses and only if no IPv6 address is found and NAT64 is
enabled and allowed by the query config, `Dns::Client` …
=> [dns-client] add support address resolution query for IPv4 directly

tests/unit/test_data.cpp
This commit addresses "uninitialized reference use" warning in
`test_data`.
=> [test] address uninitialized reference use warning

tests/scripts/thread-cert/find_border_agents.py, tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_BR.py
Without this fix some Border Agents will not send mDNS responses
with AAAA record for IPv6 link local address.
=> [thci] find IPv6 border agents only

src/core/BUILD.gn, src/core/Makefile.am, src/core/common/heap_array.hpp, src/core/config/openthread-core-config-check.h, src/core/config/srp_server.h, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, tests/unit/CMakeLists.txt, tests/unit/Makefile.am, tests/unit/test_heap_array.cpp
**[common] adding `Heap::Array<Type>` a heap allocated flexible-length array**
This commit adds `Heap::Array<Type>` class which allocates the
buffer to store array elements from the heap. The `Array`
implementation automatically grows the buffer when new entries
are added. It also provides optional method `ReserveCapacity()`
to allow user to allocate and reserve a certain capacity
(number of elements user expects to add).
The `Array` can safely be used with element `Type`s that are
themselves heap allocated (manage allocated items). The `Array`
implementation uses the move constructor and destructor of the
`Type` class to ensure that copying the entries when growing the
array is performed efficiently and that the removed entries are
properly deleted. …
=> [heap-array]`Heap::Array` & allow any num of host addrs in SRP srvr

src/core/config/mac.h, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/radio/radio.hpp
This commit adds a new feature in `SubMac` to add random delay before
frame retransmissions. The delay is added only if the previous tx
resulted in `kErrorNoAck`. A backoff algorithm similar to one used
for CSMA is used to determine the random delay, i.e., starting with a
min backoff exponent (BE) which is incremented each time delay is
added up to a max backoff exponent. The backoff interval is derived by
selecting a random value from `[0, 2^BE]` range multiplied by
`kUnitBackoffPeriod=20` times radio symbol time (20x16=320 usec).
The `OPENTHREAD_CONFIG_MAC_ADD_DELAY_ON_NO_ACK_ERROR_BEFORE_RETRY`
is added to enable this behavior (which is enabled by default).
This commit also adds other configs for this feature including
minimum and maximum backoff exponents (the values are from Thread …
=> [mac] feature to add delay on no-ack error before tx retry

tools/harness-thci/OpenThread.py
Test L5.3.5 is failing sometimes because there are unwanted data
requests during the second ping round. This can be mitigated by
finishing earlier with this round so there is no need for children
to synchronize CSL.
=> [thci] avoid further delay after `ping` command

include/openthread/instance.h, include/openthread/platform/settings.h, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/common/settings.cpp, src/core/common/settings.hpp, src/core/net/ip6_address.hpp
This commit updates the local NAT64 prefix and OMR prefix to be allocated from the same /48 BR ULA prefix. The /48 prefix is generated randomly and is saved in Settings for recovery. The subnet id of prefixes are statically assigned to avoid conflict with each other in a simple way.
=> [nat64] allocate NAT64 prefix and OMR prefix from the same /48 BR ULA prefix

src/core/config/radio_link.h, src/core/thread/topology.cpp, src/core/thread/topology.hpp
This commit adds a new mechanism in `Neighbor` to timeout the last
received fragment tag being tracked per neighbor. The fragment tag is
used when `MULTI_RADIO` is enabled to suppress duplicate received
frames (over different radios).
=> [multi-radio] add mechanism to timeout last received frag tag

tests/scripts/thread-cert/node.py
This commit replaces `ifconfig` command with `ip` command in node.py for testing. `ifconfig` is not available on BR when bind9 is disabled.
=> [tests] replace ifconfig command with ip command in node.py

src/core/mac/data_poll_sender.cpp
Thread Certification Harness makes use of CSL Timeout configurations
as low as 10 seconds, with the expectation that the SSED will try to
autosync very near to the end of the CSL Timeout.
However, the default configuration is to send a Data Request 4 secs
before, which makes several certification tests to fail due to
unexpected polling.
This commit sets the default `pollAhead` to 1 second, aligning better
with the certification testing expectations.
For the on field deployments it shouldn't be an issue that the Data
Request does not reach the parent exactly before the CSL Timeout
expiration since it will resynchronize anyway once one of the
retransmissions reaches the parent.
=> [csl] adjust polling closer to the CSL Timeout end

src/core/thread/mle.cpp, src/core/thread/mle.hpp
----
This change just moves the existing implementation to a method,
so that we can use `SuccessOrExit()` to exit early on error, replacing
lines such as:
```c++
error = (error == kErrorNone) ? AppendPendingTimestamp(*message) : error;
```
=> [mle] add `SendDelayedResponse()` method

src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit adds `Mle::RemoveDelayedMessage()` helper method which
removes messages with a given sub-type and an optional destination
IPv6 address from the `mDelayedResponses` message queue.
=> [mle] add `RemoveDelayedMessage()` helper method

tools/harness-thci/OpenThread.py
Switch to IPv6 dotted-quad format in all uses.
See https://threadgroup.atlassian.net/browse/DEV-2195
=> [thci] unify IPv6 prefix representation

src/core/border_router/routing_manager.cpp
This commit fixes a small issue introduced by https://github.com/openthread/openthread/pull/7473
=> [routing-manager] fix BR can't send RA in the first 3 seconds

.github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/otci.yml, .github/workflows/otns.yml, .github/workflows/posix.yml, .github/workflows/simulation-1.1.yml, .github/workflows/simulation-1.2.yml, .github/workflows/toranj.yml
This commit sets `fail-fast: false` for matrix in GitHub Actions so that tests in a matrix do not fail all at once. 
It's more convenient now that we can re-run failed tests.
=> [github-actions] set `fail-fast: false` for matrix

src/core/mac/mac_types.hpp
Deleting a copy constructor without specifying an explicit assignment operator causes an error in clang10 (-Wdeprecated-copy). Since explicit assignment operator defined in OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE case, added the copy constructor deletion also under the same. If the macro is not enabled, implicit copy constructor and assignment operator would take effect.
=> [crypto] compilation fix for clang10 -Wdeprecated-copy

tools/harness-thci/OpenThread_BR.py
Implement changes in `setupHost` method to be able to selectively
configure the RA for the Domain Prefix.
See https://threadgroup.atlassian.net/browse/DEV-2191 discussion.
=> [thci] selectively configure Domain Prefix advertisement on the host

src/core/coap/coap.cpp, src/core/coap/coap_message.cpp, src/core/coap/coap_message.hpp, src/core/common/message.cpp, src/core/common/message.hpp, src/core/net/dns_client.cpp, src/core/net/ip6.cpp, src/core/net/ip6_mpl.cpp, src/core/net/sntp_client.cpp, src/core/thread/indirect_sender.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, tests/unit/test_message_queue.cpp, tests/unit/test_priority_queue.cpp
This commit adds support for range-based `for` loop iteration over
`MessageQueue` and `PriorityQueue`. It adds `ConstIterator` and
`Iterator` in `Message` class. The non-const `for` loop iteration
(which uses `Message::Iterator`) works properly and is safe to use
even when the entry is removed from the queue during iteration. This
commit updates other core modules to use the new `for` loop iteration
model which helps simplify the code. It also updates the unit tests
to validate the behavior of the newly added iteration mechanisms.
----
The non-const version implements and hides the common pattern where we 
update and remember the `nextMessage` at the start of loop iteration (so 
we can remove the `message` entry from the queue while iterating over it), into 
the `Message::Iterator` class …
=> [message] add range-based `for` loop for message/priority queue

src/core/border_router/routing_manager.hpp, tests/scripts/thread-cert/border_router/test_single_border_router.py
Current `Routing Manager` implementation will try to send the failed RS messages in 60 seconds.
RS failures happen often when the infra interface is re-enabled which is the case of rebooting, and
it could not be acceptable for the border router to take 1 minute to recover the IPv6 connectivity
after reboot.
To resolve this issue, this commit changes the delay to `kRtrSolicitationInterval` (4 seconds)
which is the interval between two successful RS messages.
=> [routing-manager] resend failed RS messages in 4 seconds

src/core/thread/mesh_forwarder.cpp
----
Looks like we had this assert for frame length check against 7 since the very first commit on OT. Not sure if this is assert is still useful.
=> [mesh-forwarder] remove assert in `HandleFrameRequest`()`

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_BR.py
`accept_ra` was not being set properly for host reference device.
Some cleanup is added for simplificaiton.
=> [thci] fix RA configuration for eth0 in the host device

src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp
This commit renames the method `MeshForwarder::GetDirectTransmission`
to `PrepareNextDirectTransmission()`. This is to help make this method
different from `Message::GetDirectTransmission()` (which indicate if a
`Message` is marked for direct tx).
=> [mesh-forwarder] rename method to `PrepareNextDirectTransmission()`

src/core/thread/mle_router.cpp
Fixes the following issue introduced in #7481:
```
../openthread/src/core/thread/mle_router.cpp:3163:26: note: ‘message’ was declared here
Message *            message;
^~~~~~~
```
=> [mle-router] fix uninitialized `message` in `SendChildUpdateRequest()`

src/core/thread/network_data_service.cpp, src/core/thread/network_data_service.hpp, tests/unit/test_network_data.cpp
This commit updates `NetworkData::Service::DnsSrpUnicast` to indicate
`Origin` of the entry, whether the server IPv6 address and port
number is included as part of service data or server data. This will
be used by clients to prefer entries with the info in service data
(which coveys the infra-structure provided (authoritative) server)
over the ones in server data (which are used by Thread BRs).
This commit also updates the unit test `test_network_data` to validate
the new behavior.
=> [netdata] update `Service::DnsSrpUnicast` to include `Origin`

src/core/mac/mac.cpp
This commit changes the log level used by `Mac` to log frame rx error
when error is `kErrorAddressFiltered` (from "info" to "debug" log
level). This error is used when the frame is filtered `Mac::Filter`.
This helps reduce the logs during simulation/testing when allow-list
or deny-list are used to form specific network topology.
=> [mac] log `AddressFiltered` rx errors at debug level

src/posix/platform/CMakeLists.txt
This commit adds an option to the POSIX platform CMake module to turn on/off the secure settings API.
=> [cmake] add option to enable secure settings API

examples/platforms/utils/settings_ram.c, include/openthread/instance.h, include/openthread/platform/settings.h, src/core/common/settings.cpp, src/core/common/settings.hpp, src/core/common/settings_driver.hpp, src/lib/spinel/radio_spinel_impl.hpp, src/posix/platform/settings.cpp, tests/fuzz/fuzzer_platform.cpp, tests/unit/test_platform.cpp
This commit makes the core pass the sensitive keys to the platform settings initialization, so that the platform settings implementation can know which keys are sensitive keys during the initializing and do the migration when needed.
=> [settings] set sensitive keys in platform settings initialization

src/posix/platform/settings.cpp, src/posix/platform/settings.hpp
This commit adds the `src/posix/platform/settings.hpp` file to make other components able to access the POSIX data file, so that secure settings implementation can use the same file as platform settings.
=> [posix] expose platform settings interfaces

src/core/api/thread_api.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_types.hpp
This commit contains small changes in `Mle`:
- Renames `mParentRequestMode` to `mAttachMode` (to match its type).
- Shortens `ParentRequestType` enumerator names.
- Changes `SendParentRequest()` to return `void`.
- Adds a protected method `Mle::Attach()` (which replaces
`BecomeChild()`).
- Moves `AttachMode` enum as a protected definition in `Mle`
class itself and renames the `AttachMode` constants.
=> [mle] renames and small changes

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp
This commit adds a new enumerator `kBetterParent` in `AttachMode`
enumeration. This new value is used by periodic parent search
feature only when searching for a better parent to help make
it explicit that attach process is started for this purpose.
----
_Background_:
The is used so we can tell an ongoing attach is triggered by the 
"periodic parent search" mechanism or not. In most situations 
we can treat this mode same as `kAnyPartition`. But this will be
useful in an upcoming change to the attach process (from SPEC-1036)
where we want different behavior (e.g., different number of parent 
requests) based on what started the attach cycle.
The PR contains the commit from https://github.com/openthread/openthread/pull/7515, please check and review the 
last commit on this PR. Thanks.
=> [mle] add `kBetterParent` in `AttachMode` enum

src/core/thread/network_diagnostic_tlvs.hpp
The value is unintentionally changed to `0x1f` in https://github.com/openthread/openthread/pull/6895.
=> [net-diag] fix `kChildIdMask` value

include/openthread/instance.h, include/openthread/platform/settings.h, src/core/common/settings.hpp
This PR reserves a range of settings keys for vendors to use in their extensions.
=> [settings] reserve settings keys for vendor use

src/core/thread/mle.cpp
When building with `OPENTHREAD_MTD` make sure that the device is
not configured as Full Thread Device, whether by the API or by the
stored settings.
=> [mle] avoid setting mode `D` flag on MTD builds

src/core/border_router/routing_manager.cpp
This commit updates some legacy comments when evaluating routing policy, especially about the legacy Router Advertisement timer.
=> [routing-manager] update legacy comments in routing manager

include/openthread/backbone_router_ftd.h, include/openthread/instance.h, src/cli/README.md, src/cli/cli.cpp, src/core/api/backbone_router_ftd_api.cpp, src/core/backbone_router/bbr_local.cpp, src/core/backbone_router/bbr_local.hpp, tools/harness-thci/OpenThread.py
This reverts commit c9066b650695494917a87cc9e560a30dc397d3b8 (#7283).
Not needed after changes introduced by DEV-2179.
=> [bbr] revert add `bbr skipseqnuminc` command for reference device

etc/gn/openthread.gni, src/core/BUILD.gn
This commit enables defining OPENTHREAD_CONFIG_PLATFORM_RADIO_COEX_ENABLE,
which can be used by external build system (i.e. MATTER) to override the
platform defaults. This is useful for platforms having transceivers that
also support coexistence between multiple protocols (WiFi/BLE etc.)
=> [build] enable coexistence parameter build

src/core/BUILD.gn, src/core/Makefile.am, src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/net/ip6_headers.cpp, src/core/net/ip6_headers.hpp, src/core/net/ip6_types.hpp, src/core/net/socket.hpp, src/core/net/srp_client.hpp, src/core/net/srp_server.hpp
This commit adds new header file `ip6_types.hpp` which includes
common IPv6 related types (enumerations) and constants. It also
moves the `Ecn` constants and define them as an `enum`.
---
_Background for this:_
Adding new header file is mainly to avoid header `#include` loops
and be able to see and use the same types/constants from different
headers (e.g., `socket.hpp` and `ip6_headers.hpp`, ect.).
=> [ip6] add header `ip6_types.hpp` for common types and constants

src/core/net/ip6.cpp
This commit changes `Ip6::HandleDatagram()` so to copy the ECN value
parsed from IPv6 header of the message in the accompanying
`MessageInfo` data structure.
=> [ip6] copy the parsed ECN value from IPv6 msg in `MessageInfo`

src/core/net/ip6.cpp
This commit updates `Ip6::FragmentDatagram()` to set the priority on
every fragment message to match the original IPv6 message. This
ensures that as fragments are enqueued in the priority queue they
follow the same priority as the original IPv6 message.
=> [ip6] set priority on fragments when fragmenting an IPv6 datagram

src/core/mac/sub_mac.cpp
Prevent possible overflow in semiWindow calculation by converting it to uint64_t accuracy.
On platforms with clock accuracy = 50ppm the overflow happens in 43 seconds from last CSL synchronization.
`semiWindow = 43000000 * (50 + 50) = 4300000000 > UINT32_MAX (4294967295)`
=> [sub-mac] fix semiWindow overflow in GetCslWindowEdges()

src/core/net/ip6.cpp, src/core/thread/indirect_sender.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp
This commit updates `LogMessage()` in `MeshForwarder`:
- Fixes `MessageActionToString()` so when there is a passed-in error
it correctly returns the related action string (and only when
`aAction == kMessageTransmit` it returned "Failed to send").
- Changes the order of parameters in `LogMessage()` and uses default
value for parameters to simplify its use.
=> [mesh-forwarder] fix and enhance `LogMessage()`

tools/harness-thci/OpenThread.py
According to the Thread Specification the `P_slaac` flag should be
set to false for the Domain prefix.
See: https://threadgroup.atlassian.net/browse/DEV-2220
=> [thci] do not set `P_slaac` flag for Domain prefix

src/core/common/message.hpp, src/core/net/ip6.cpp, src/core/thread/mesh_forwarder.cpp
This commit adds a `TimeMilli mTimestamp` field in `Message` metadata.
This replaces the `mTimeout` which was used during lowpan and/or IPv6
fragment reassembly to drop the message if the next fragment is not
received within a time window.
----
_Background for this:_
The timestamp will also be used to track "time-in-the-queue" for 
outbound messages (for delay-aware queue management feature 
from [SPEC-1041](https://threadgroup.atlassian.net/browse/SPEC-1041)).
=> [message] add timestamp field in `Message` metadata

tests/scripts/thread-cert/border_router/test_firewall.py
This PR aims to fix https://github.com/openthread/openthread/issues/7567.
The test failed when verifying that HOST sends a ping packet to BR while the destination is a link local address. That requires adding a route on HOST before the ping. In this specific step, HOST added a route to link local prefix going to BR. However, HOST failed to send the echo request to BR using this newly added route. Since the impact of disabling this step is small, I'll skip this step as for now and look for a long term fix in the future.
=> [tests] disable check in test_firewall.py

src/core/net/ip6.cpp, src/core/net/ip6_headers.cpp, src/core/net/ip6_headers.hpp, src/core/net/ip6_types.hpp, src/core/net/tcp6.hpp, src/core/net/udp6.hpp, src/core/thread/lowpan.cpp, tests/unit/CMakeLists.txt, tests/unit/Makefile.am, tests/unit/test_ip6_header.cpp, tests/unit/test_ip_address.cpp, tests/unit/test_lowpan.hpp
This commit adds new methods in `Ip6::Header` to get and set Traffic
Class, Flow fields. It also updates and renames some of the existing
methods. This commit also adds a unit test `test_ip6_header.cpp` to
validate the IPv6 header parsing and preparation.
=> [ip6] new methods in `Header` and add unit test

src/posix/platform/settings.cpp, src/posix/platform/system.cpp
Initialization of these modules is not called when dry run, so setup and de-initialization should not be called either.
=> [posix] stop setting up and de-initializing uninitialized modules when dry run

src/core/net/tcp6.cpp, src/core/net/tcp6.hpp, third_party/tcplp/bsdtcp/tcp.h, third_party/tcplp/bsdtcp/tcp_input.c, third_party/tcplp/bsdtcp/tcp_reass.c, third_party/tcplp/bsdtcp/tcp_var.h, third_party/tcplp/tcplp.h
This pull request fixes #7552.
First, this pull requests changes `third_party/tcplp/bsdtcp/tcp.h` so that it no longer does `#define __func__`. This line was necessary on one of the original platforms for which TCPlp was written. However, OpenThread assumes that `__func__` is appropriately defined by the toolchain, so there is no need to define it again.
The above change fixes issue #7552, but #7552 illustrates a broader problem, which is that global-scope artifacts (variables and macros) defined by TCPlp can affect other code in OpenThread. This is hard to avoid completely, as C does not have the notion of a namespace. However, it can be mitigated by limiting global-scope artifacts to as few translation units as possible. Therefore, this pull request also limit global-scope TCPlp …
=> [tcp] remove extraneous #define and restrict inclusion of TCPlp headers

tools/harness-thci/OpenThread.py
Make sure BBR Sequence Number is increased when Re-registration
Delay or MLR Timeout changes.
See https://threadgroup.atlassian.net/browse/DEV-2221
=> [thci] increase BBR Sequence Number when dataset changes

src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp
This commit adds a helper `Ip6::EncToString()` and updates logging of
messages in `MeshForwarder` to include the ECN field from IPv6
header.
=> [mesh-forwarder] update `LogMessage()` to include ECN from IPv6 header

src/cli/cli.cpp
Before starting a test case, our test script calls the 'factoryreset'
to make the device enters a known state . But the previous test case
may fail to call the 'diag stop' before exiting. This case the next
test case failed to call the 'factoryreset '.
This commit allows the users to call 'factoryreset' under the diag mode.
=> [cli] allow to run `factoryreset` under the diag mode

src/core/api/message_api.cpp, src/core/common/instance.cpp, src/core/common/instance.hpp
This commit moves the implementation of `otMessageGetBufferInfo()`
from the `message_api.cpp` file to  `Instance` class.
=> [instance] move `otMessageGetBufferInfo()` impl to `Instance`

tests/scripts/thread-cert/Cert_9_2_17_Orphan.py
This commit updates `Cert_9_2_17_Orphan` packet verification to check
that the two leaders are sending MLE advertisement before checking
for child attach (Child ID response). The current test checked this
after the child attach but leader 1 is turned off 5 seconds after
the child is attached which may not be enough time to ensure rx
of an advertisement (which every 30 seconds on average).
----
_Background:_
- Discovered this from https://github.com/openthread/openthread/pull/7538 (trying to update the tests after the change in this PR)
=> [test] update `Cert_9_2_17_Orphan` to make it more robust

src/core/common/instance.cpp, src/core/common/message.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp
This commit updates how the messages waiting for address query
resolution are queued. It adds a boolean flag in `Message` metadata
to indicate whether or not a message is waiting for address
resolution. Message that require address query are marked and kept in
`mSendQueue` instead of being placed in a different queue
`mResolvingQueue`. When the address is resolved the messages are
updated accordingly. This ensures that the order or messages in
`mSendQueue` are preserved.
---
- Resolves https://github.com/openthread/openthread/issues/7542.
=> [mesh-forwarder] keep msgs waiting for address resolution in `mSendQueue`

tests/scripts/thread-cert/test_srp_name_conflicts.py
This commit updates `test_srp_name_conflicts.py` to cover the
situation where different clients try to register services with the
same service instance label but under different services.
=> [test] update SRP name conflict test to cover more cases

src/core/meshcop/dataset_local.cpp
In the current implementation, **EmplaceSecurelyStoredKeys** tries to read the network key and PSKc from secure storage to update the TLVs and asserts if the read fails. But if the device was previously running a non-PSA application, it won't have the keys in secure storage, and the device asserts. 
This PR proposes a way to move the the keys to secure storage, if the ExportKey fails. Once it is moved to secure storage, literal key stored in the settings is cleared.
=> [crypto] update emplace method to expect read failure during key export

src/lib/spinel/radio_spinel.hpp
The current implementation does not differentiate the max spinel frame size that is used to pack a spinel command and the radio spinel RX frame buffer size which could contain multiple frames.
In radio_spinel_impl.hpp, only one spinel frame can be written when calling function “SendCommand” or “SendReset”.
Therefore the aim of this commit is to allocate, in such a context, only a buffer of one frame instead of a buffer that could contain multiple frames.
=> [spinel] map `kMaxSpinelFrame` to `SPINEL_FRAME_MAX_SIZE`

include/openthread/instance.h, include/openthread/platform/logging.h, src/core/common/instance.cpp, src/core/common/instance.hpp
Adds a log level platform handler that allow platform code to handle OT log level changes. 
Used by https://github.com/openthread/ot-br-posix/pull/1319.
=> [logging] add log level platform handler

src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_types.hpp, tests/unit/test_network_data.cpp
This commit adds a new method in `NetworkData` to find the list of
RLOC16 of all border routers providing external IPv6 connectivity. A
border router is considered to provide external IPv6 connectivity if
it has added at least one external route entry or
an on-mesh prefix with default-route and on-mesh flags set. It also
adds a method to count the number of border routers. The methods
allow filtering based on the border router device role, including
devices in any role, or in router role only or in child role only.
This commit also updates `test_network_data` unit test to validate
the behavior of the newly added methods.
-----
This is related to [SPEC-1033](https://threadgroup.atlassian.net/jira/core/projects/SPEC/issues/SPEC-1033).
=> [netdata] get the list or count of RLOC16s of border routers

src/core/meshcop/announce_begin_client.cpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/energy_scan_client.cpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/meshcop_leader.cpp, src/core/meshcop/panid_query_client.cpp, src/core/thread/address_resolver.cpp, src/core/thread/anycast_locator.cpp, src/core/thread/dua_manager.cpp, src/core/thread/energy_scan_server.cpp, src/core/thread/mle_router.cpp, src/core/thread/mlr_manager.cpp, src/core/thread/network_data.cpp, src/core/thread/network_diagnostic.cpp, src/core/thread/panid_query_server.cpp, src/core/thread/tmf.cpp, src/core/thread/tmf.hpp
This commit adds `Tmf::MessageInfo` which is a sub-class of the
`Ip6::MessageInfo` class intended for use when sending TMF messages.
The peer port number is by default set to the TMF port from the
constructor. This class also provides helper methods for commonly
used patterns, e.g., source or `SockAddr` set to device's RLOC
address and/or the destination or `PeerAddr` set to leader ALOC or
RLOC, or a given address.
=> [tmf] add `Tmf::MessageInfo` 

src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/thread_tlvs.hpp
This commit adds support for new Status TLV values and updates
the processing of Address Solicit request messages on leader.
The new status `kBorderRouterRequest` can be used by a BR to request to
upgrade to router role. If there are fewer routers than "router
upgrade threshold" leader will accept the request. If the number of
routers is more than the threshold but less than max, the leader will
accept the BR request only if the number of current Border Routers
(as indicated by Network Data) that are acting as router is less than
two (thus allowing up to two BRs to use this status reason to become
router when already above the threshold).
The other change in this PR, is that when processing Address Solicit
request if the included status value is not known or invalid, a
response with …
=> [mle-router] leader to handle "BR request" in an Address Solicit

src/core/thread/network_diagnostic.cpp
This commit updates how the `MessageInfo` for a "GetQuery" response
is prepared so that we use link-local source if the destination of
response is also using link-local address.
----
I think the code as is behaves correctly as well, since we expect the
sender to use link-local source when using a link-local destination.
But determining the local sock address based on destination (peer address)
is a more direct check and more reasonable. It also hamonizes the code 
for "GetQuery" with other similar situations in `network_diagnostics.cpp` 
where `MessageInfo` is prepared.
----
Digging into history I see this was added from 
- #3935
which I think intended to use the same pattern , i.e. determine the source (link-local 
or mesh-local) based on destination address type.
=> [net-diags] set the sock addr based on dest in GetQuery response

src/core/net/srp_client.cpp, src/core/net/srp_client.hpp, tests/scripts/thread-cert/test_srp_auto_start_mode.py
This commit updates the auto-start behavior in `Srp::Client` which
monitors the Thread Network Data entries to discover and select SRP
sever to register with. There are three types of entries in Network
Data and are selected in the order below:
1) Preferred unicast entries with address in service data,
2) Anycast entries (each having a seq number,
3) Unicast entries with address info included in server data.
This commit also defines `AutoStart` class which includes all the
state and data variables related to auto-start feature. It also
updates `test_srp_auto_start_mode` test to cover the newly added
behaviors.
=> [srp-client] update how auto-start mode prefers netdata entries

src/core/thread/network_data_service.cpp, src/core/thread/network_data_service.hpp, tests/unit/test_network_data.cpp
This commit enhances the selection algorithm for the preferred entry
when there are multiple "DNS/SRP Service Anycast" entries in the
Thread Network Data. The sequence number (which is `uint8_t`) is used
for selecting the preferred entry and the larger value is preferred.
The seq numbers are compared using "serial number arithmetic"
(RFC-1982) but if we have 3 or more entries the notion of a largest
seq number may not be well-defined under the "serial number
arithmetic" comparison (e.g., for `{10, 130, 250}` there is no
largest seq number since `130 > 10`, `250 > 130` and `10 > 250`). In
such a case the algorithm selects the entry with largest seq number
in normal sense.
This commit updates `FindPreferredDnsSrpAnycastInfo()` to implement
the new algorithm. It also updates …
=> [netdata] update srp/dns anycast entry seq num selection

src/core/meshcop/dataset.cpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager.hpp, src/core/thread/mle.cpp
This commit contains the following changes:
- The `Dataset` method which reads the dataset TLVs from a message
is renamed to `ReadFromMessage()` and after reading the TLVs, it
checks that the TLVs in the Dataset are valid (well-formed).
- The `Active/PendingDataset::Save()` methods are updated to return
error in case the parsed dataset from message is not well-formed.
- The `Mle::HandleChildIdRequest()` rejects the response if the
included dataset is not well-formed (device can stay detached).
=> [mle] reject parent when processing `ChildIdResponse` with ill-formed dataset TLV

src/core/thread/mle_router.cpp, src/core/thread/network_data.cpp
This commit changes to use Thread control traffic priority level
for "Server Data" and "Address Release" TMF messages.
=> [tmf] use priority message for ServerData and AddressRelease

include/openthread/instance.h, include/openthread/message.h, src/cli/README.md, src/cli/cli.cpp, src/core/common/instance.cpp, src/core/common/message.cpp, src/core/common/message.hpp, src/ncp/ncp_base_mtd.cpp, tests/unit/test_message_queue.cpp, tests/unit/test_priority_queue.cpp
This commit updates the `otMessageGetBufferInfo()` and its related
types. In particular, this commit adds `otMessageQueueInfo` to
indicate number of messages, number of data buffers, and total
message length (number of bytes) for all messages in the queue.
=> [message] update and simplify `otBufferInfo`

src/posix/platform/netif.cpp, src/posix/platform/openthread-posix-config.h
This commit allows configuring route metric for the prefix routes of IPv6 addresses added to the Thread network interface.
This commit also simplifies `UpdateUnicastLinux` by using `AddRtAttr`.
--- 
Background:
We found a routing issue for the OMR prefix where there are two BRs within the same Thread network, and both BRs are connected to the same infrastructure link. When forwarding a message with OMR destination, one BR would redirect the message to the other BR and the other BR would redirect the message back. This creates message looping until the TTL is decreased to zero. 
The cause is that the BRs could add OMR routes by hearing RA RIO with a smaller metric than that of the prefix routes via Thread interface (usually 256). 
So, this commit uses smaller metric for prefix routes to …
=> [posix-netif] configure metric for prefix routes

src/core/config/mac.h, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp
This commit adds a new feature in `MeshForwarder` to add wait delay
after a successful frame tx to a neighbor which is expected to
forward the frame. This wait time applies before the next direct tx
to any neighbor. This mechanism is intended to help prevent
self-interference when messages are sent to a destination that is
at least 2-hops away. This commit adds new OT build configs to
enable/disable this behavior and specify the wait interval
(default is set to 8 msec).
Depends-On: openthread/ot-ns#257
=> [mesh-forwarder] collision avoidance delay mechanism

Android.mk, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/api/thread_api.cpp, src/core/common/instance.hpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_types.cpp, src/core/mac/mac_types.hpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/extended_panid.cpp, src/core/meshcop/extended_panid.hpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/meshcop.cpp, src/core/meshcop/meshcop.hpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/radio/trel_interface.cpp, src/core/radio/trel_interface.hpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_types.hpp, src/core/thread/thread_netif.cpp, src/core/thread/thread_netif.hpp, tests/unit/test_pskc.cpp
With the removal of Thread payload from IEEE 802.15.4 Beacons, the MAC
layer no longer needs to maintain the Extended PAN ID.
=> [meshcop] separate Extended PAN ID from Mac

src/cli/README_DATASET.md
Beacon support in the "dataset securitypolicy" command was removed in PR #7472 but the README was not updated to reflect the removal of the "b" option.
=> [cli] update `dataset securitypolicy`  README

include/openthread/instance.h, include/openthread/tcp.h, src/core/api/tcp_api.cpp, src/core/net/tcp6.cpp, src/core/net/tcp6.hpp, third_party/tcplp/bsdtcp/tcp_input.c, third_party/tcplp/bsdtcp/tcp_reass.c, third_party/tcplp/lib/lbuf.c, third_party/tcplp/lib/lbuf.h, third_party/tcplp/tcplp.h
This pull request adds support for the remaining TCP callback, which was not yet supported.
Originally, the unimplemented callback was `otTcpSendReady`, which would indicate to the application when new data added to the TCP send buffer would be sent out immediately. There was also discussion of adding an `otTcpBytesAcked` callback, which, together with the `otTcpSendByExtension()` call, would allow a circular buffer to be implemented efficiently on top of the otLinkedBuffer API. (See #6491 for this discussion.)
Ultimately, it seemed best to generalize the `otTcpSendReady` callback to include both cases where bytes are acked by the connection peer, and  where the send buffer drains, allowing new data to be sent immediately. The reasoning behind this decision is that both the …
=> [tcp] add support for otTcpForwardProgress callback

include/Makefile.am, include/openthread/BUILD.gn, include/openthread/instance.h, include/openthread/tcp_ext.h
In Pull Request #6491, there was much discussion about the API for sending out data on a TCP connection. While we ultimately converged on the linked-buffer-based API that has been merged into OpenThread, it was also discussed that we should provide a circular buffer library that is implemented on top of the linked buffer API, to support applications that find a circular-buffer-based interface easier to use. This pull request proposes an API for the circular buffer library.
This API was written assuming that the `otTcpForwardProgress` callback, implemented in Pull Request #7583, exists. However, there are no strict dependencies between Pull Request #7583 and this one (i.e., either can be merged first).
=> [tcp] add TCP circular send buffer API

src/core/common/message.hpp, src/core/crypto/aes_ccm.cpp, src/core/crypto/aes_ccm.hpp, src/core/thread/mle.cpp, tests/unit/test_aes.cpp
This commit adds a new method in `AesCcm` to encrypt/decrypt the
payload content in place within a given `Message`. This is then used
in `Mle` for processing MLE messages. This commit also updates unit
test `test_aes.cpp` to validate the new method.
=> [mle] perform in-place AES-CCM encryption/decryption

.github/workflows/build.yml, examples/apps/cli/main.c, examples/apps/ncp/main.c, src/lib/platform/Makefile.am, src/lib/platform/reset_util.h, src/posix/main.c
__gcov_flush is removed from gcc 11.
=> [gcov] use __gcov_dump() instead for gcc 11

src/posix/platform/netif.cpp
`IFA_RT_PRIORITY` not defined basically means that the feature is not present. 
Defining it to 9 does not make it effective. 
This commit removes the `IFA_RT_PRIORITY` definition so that it would not compile on platforms that do not support `IFA_RT_PRIORITY`.
=> [posix-netif] remove IFA_RT_PRIORITY definition

src/core/thread/discover_scanner.cpp, src/core/thread/discover_scanner.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
This commit adds a new struct `RxInfo` which includes a received
MLE `Message` along with additional info about it such as the
`Ip6::MessageInfo` and key sequence from security header and
pointer to `Neighbor` from which the message was received.
The `RxInfo` is used as the input parameter in different MLE
`Handle{MleMsg}`()` methods.
---
_Background_:
This helps simplify the calls to `Handle{MleMsg}()`. This is also
in preparation for more changes to support [SPEC-1025](https://threadgroup.atlassian.net/browse/SPEC-1025).
=> [mle] add `RxInfo` struct and pass in `Handle{MleMsg}()` methods

src/core/api/dataset_api.cpp, src/core/api/dataset_ftd_api.cpp, src/core/api/link_api.cpp, src/core/api/thread_api.cpp, src/core/api/thread_ftd_api.cpp, src/core/common/instance.hpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager.hpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/dataset_updater.cpp, src/core/meshcop/joiner.cpp, src/core/meshcop/joiner_router.cpp, src/core/thread/announce_sender.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/thread_netif.hpp
This commit renames dataset managers ActiveDataset and PendingDataset to
ActiveDatasetManager and PendingDatasetManager for readability.
=> [meshcop] rename dataset managers

src/posix/platform/openthread-posix-config.h, src/posix/platform/trel.cpp
This commit adds the configuration `OPENTHREAD_CONFIG_POSIX_TREL_UDP_PORT` to allow TREL to use a fixed UDP port number on Posix platform.
=> [posix-trel] allow using fixed TREL UDP port

src/core/thread/discover_scanner.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp
This commit updates `NewMleMessage()` to allocate and also
initialize an MLE message adding MLE header and setting the
`Message::SubType`.
=> [mle] enhance `NewMleMessage()` to prepare the MLE header

.github/workflows/otbr.yml
Caching OTBR test results to avoid re-running all tests is no longer necessary now that GitHub Actions supports it natively.
=> [github-actions] remove caching OTBR test results

src/core/thread/network_data_local.cpp, src/core/thread/network_data_local.hpp
This commit removes the `#if OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE`
around the call to `IsConsistent()` which checks whether there is any
difference between local network entries and ones from leader network
data and decide to send a "Server Data Notification" message to
leader. This change ensures that services are updated correctly under
the uncommon config combination where `TMF_NETDATA_SERVICE_ENABLE` is
enabled without `BORDER_ROUTER_ENABLE`.
=> [netdata] always check `IsConsistent()` before netdata registration

src/core/thread/network_data_local.cpp, src/core/thread/network_data_local.hpp
The current implementation attempts to remove existing on-mesh prefix
entry when adding an on-mesh prefix entry with the same prefix. The
same logic exists for external routes. However, the existing code does
not work properly when both on-mesh prefixes and external routes exist
with the same prefix.
This commit simply updates the logic to always remove existing entries
with the same prefix, regardless of whether they are on-mesh prefix or
external route. This is in contrast to trying to keep both on-mesh
prefix and external route with the same prefix simultaneously. There
is no obvious use case for having both the on-mesh prefix and external
route exist at the same time.
Thanks go @gabekassel for identifying this issue.
=> [netdata] remove duplicate prefixes in local network data

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_BR.py
Remove excesive logging redundancy:
- `API` decorator is enough to show test script calls with arguments
- `__executeCommand` already prints all OT commands and arguments
- Command timestamp is irrelevant in most cases
- Some extra detail logging lines are left commented in case they
are needed for some debugging
As a result test logs are much easier to follow and resulting files
are much smaller.
=> [thci] logging cleanup

src/core/backbone_router/bbr_manager.cpp, src/core/coap/coap.cpp, src/core/coap/coap.hpp, src/core/coap/coap_message.cpp, src/core/coap/coap_message.hpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/joiner.cpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/meshcop_leader.cpp, src/core/thread/address_resolver.cpp, src/core/thread/anycast_locator.cpp, src/core/thread/dua_manager.cpp, src/core/thread/energy_scan_server.cpp, src/core/thread/mle_router.cpp, src/core/thread/mlr_manager.cpp, src/core/thread/network_data.cpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_diagnostic.cpp, src/core/thread/panid_query_server.cpp, src/core/thread/tmf.cpp, src/core/thread/tmf.hpp
This commit adds new helper methods in `Coap` to allocate a new
message and initialize it as a confirmable or non-confirmable post to
a given URI path. It also adds a new helper method to allocate a CoAP
response message for a given request. These methods help simplify the
preparation of CoAP and TMF messages.
=> [coap] add new helper methods to allocate and init CoAP message

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
This commit updates `MleRouter::ProcessRouteTlv()` to not only read
and process Route TLV from a received MLE message but also to update
the `mNeighbor` pointer (in `RxInfo`) which indicates the neighbor
from which the MLE message was received.
During processing of Route TLV, the entries in the router table may
shuffle. If the `mNeighbor` was pointing to an entry in `RouterTable`
it may be invalid afterwards. The new implementation ensures that
`mNeighbor` is correctly updated to point the same entry.
This change addresses a scenario where in `Mle::HandleAdvertisement()`
a potentially invalid (or set to null) `mNeighbor` may be checked
after Route TLV is processed from `MleRouter::HandleAdvertisement()`
call.
----
_Background_:
- This change should help make `ProcessRouteTlv()` safer to …
=> [mle] enhance `ProcessRouteTlv()` to update neighbor pointer

src/core/api/link_api.cpp, src/core/thread/link_quality.cpp, src/core/thread/link_quality.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_tlvs.hpp, src/core/thread/router_table.cpp, src/core/thread/topology.hpp
This commit adds `LinkQuality` enumeration which represents the
2-bit [0-3] link quality values.
=> [link-quality] define `LinkQuality` enumeration

src/posix/platform/radio.cpp, src/posix/platform/radio_url.cpp, tests/scripts/expect/posix-url-enable-coex.exp
This commit adds a new option of radio url to enable/disable RCP coex
feature on boot without changing the RCP firmware.
Verified by the expect test with simulated RCP.
=> [rcp] add enable-coex switch

tools/harness-thci/OpenThread.py
Return different output of `ValidateDeviceFirmware` depending on the
device's capabilities. This allows to have a single THCI file for the
same vendor for different device's versions.
=> [thci] version string depending on capabilities

.github/workflows/otbr.yml, .github/workflows/posix.yml, .github/workflows/simulation-1.1.yml, .github/workflows/simulation-1.2.yml, .github/workflows/toranj.yml
Coverage upload can fail intermittently for various reasons. Do not
delete coverage artifacts if upload fails to avoid needing to re-run
the entire workflow.
=> [github-actions] do not delete artifacts if coverage upload fails

include/openthread/instance.h, include/openthread/netdata.h, src/core/api/netdata_api.cpp, src/core/border_router/routing_manager.hpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp, src/core/thread/network_data_types.hpp, src/posix/platform/netif.cpp, src/posix/platform/openthread-posix-config.h
This commit allows a POSIX BR to install high priority kernel routes for OMR prefixes in Network Data.
The commit also slightly revise the logs for External Routes feature.
--- 
Background on this PR and #7605:
#7605 uses `IFA_RT_PRIORITY` attribute to set the metric of prefix routes, however it does not work on Linux kernels before v4.18. This PR provides an alternative way of adding high priority route for OMR prefix.
=> [posix] install high priority kernel routes for OMR prefixes

src/core/mac/sub_mac.cpp
When radio supports receive timing it makes no sense to restrict
scheduling future reception slots while the radio state is for
instance transmitting or receiving, as long as CSL parameters are
properly configured.
=> [csl] allow scheduling delayed reception in any radio state

tests/toranj/ncp/test-018-child-supervision.py
This commit adds a small wait time between steps in the toranj
`test-018-child-supervision` to help make the test more robust. The
test adds some extra time for child to finish the "child update
request/response" exchange with the parent before enabling MAC
filter.
----
Background
- This was discovered from PR: https://github.com/openthread/openthread/pull/7686
- Stress test of the change here : https://github.com/abtink/openthread/runs/6379042520?check_suite_focus=true
=> [toranj] update `test-018-child-supervision` to make it more robust

src/core/border_router/routing_manager.cpp, tests/scripts/thread-cert/border_router/test_manual_omr_prefix.py, tests/scripts/thread-cert/node.py
This commit fixes the bug that BRs would recognize `P_on_mesh=0` or `P_stable=0` prefixes as OMR prefixes.
=> [routing-manager] BR not to use `P_on_mesh=0` or `P_stable=0` prefixes as OMR prefixes

src/core/api/thread_api.cpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/net/dhcp6_server.hpp, src/core/net/ip6_address.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_types.cpp, src/core/thread/mle_types.hpp, tests/scripts/thread-cert/config.py, tests/unit/test_lowpan.cpp
Deriving the Mesh Local Prefix from the Extended PAN ID was carried
forward from legacy implementations. Removing this coupling to conform
to the existing Thread Specification.
=> [mesh-local-prefix] remove coupling to Extended PAN ID

src/core/common/instance.hpp, src/core/common/locator.hpp, src/core/common/locator_getters.hpp, src/core/common/message.hpp
This commit introduces a base class `GetProvider` which provides
`Get<Type>()` methods using `GetInstance()` (which is expected to be
provided by the derived class in a CRTP style inheritance). The class
`GetProvider` is used as base class of `InstanceLocator`.
This model allows us to provide `Get<Type>()` methods on types that
may not be directly an `InstanceLocator`. For example, this commit
uses this model on `Message` class. `Message` always retains the
`MessagePool` which can be used to get to the `Instance` that owns
the `Message`. Note that it is not straight-forward to to have
`Message` directly inherit from `InstanceLocator` (due to way
`Message` is built from `Buffer` and uses `Metadata` header and that
`InstanceLocator` behaves differently under single vs multi instance …
=> [locator] add `GetProvider` base to provide `Get<Type>()` on `Message`

.github/workflows/otbr.yml, tests/scripts/thread-cert/border_router/LowPower/v1_2_LowPower_5_3_01_SSEDAttachment_BR.py, tests/scripts/thread-cert/border_router/LowPower/v1_2_LowPower_7_1_01_SingleProbeLinkMetricsWithEnhancedAcks_BR.py, tests/scripts/thread-cert/border_router/LowPower/v1_2_LowPower_7_2_01_ForwardTrackingSeries_BR.py, tests/scripts/thread-cert/v1_2_LowPower_5_3_01_SSEDAttachment.py, tests/scripts/thread-cert/v1_2_LowPower_6_1_07_PreferringARouterOverAReed.py, tests/scripts/thread-cert/v1_2_LowPower_7_1_01_SingleProbeLinkMetricsWithEnhancedAcks.py, tests/scripts/thread-cert/v1_2_LowPower_7_2_01_ForwardTrackingSeries.py
This commit runs LowPower cert test cases for OTBR Posix (Docker).
Tests include:
- v1_2_LowPower_5_3_01_SSEDAttachment.py
- v1_2_LowPower_7_1_01_SingleProbeLinkMetricsWithEnhancedAcks.py
- v1_2_LowPower_7_2_01_ForwardTrackingSeries.py
Note: OTBR Posix plays FTD DUT roles
=> [thread-cert] run LowPower cert tests for OTBR Posix

src/core/border_router/routing_manager.cpp
While using sizeof(*icmp6Header) before it is initialized to something
is not wrong, it is possible this will be flagged by some code checker
tools. Lets check using direct type.
=> [routing-manager] use sizeof explicit type `Ip6::Icmp::Header`

src/core/border_router/routing_manager.cpp, tests/scripts/thread-cert/border_router/test_manual_omr_prefix.py
This commit fixes the issue that the OMR prefix with higher Pref is not preferred.
=> [routing-manager] prefer OMR prefix with higher Pref

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, tests/scripts/thread-cert/border_router/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/test_single_border_router.py, tests/scripts/thread-cert/border_router/test_vicarious_router_solicit.py, tests/scripts/thread-cert/thread_cert.py
To align with latest Thread Specification.
=> [routing-manager] derive on-link prefix from Extended PAN ID

src/core/thread/discover_scanner.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
This commit adds new `Mle::TxMessage` and `Mle::RxMessage` classes
(as sub-classes of `Message`). `TxMessage` represents an MLE message
to be sent out providing `Append{Some}Tlv()` methods and `RxMessage`
represent a received MLE message providing helper methods 
`Read{Some}Tlv()`.
---
This PR contains the commit from 
- https://github.com/openthread/openthread/pull/7679
- Basically having `Message` act as if it is `InstanceLocator` and 
provide `Get<Type>()` methods allows us to change the methods
like `Append{Something}(Message &aMessage)` to a method on 
a (sub-class of )`Message` itself.
=>  [mle] add `Tx/RxMessage` providing `Append/Read{Tlv}` methods

src/core/border_router/router_advertisement.cpp, src/core/border_router/router_advertisement.hpp, src/core/border_router/routing_manager.cpp, tests/toranj/openthread-core-toranj-config.h
This commit contains smaller enhancements in `RoutingManager `
and `Prefix/RouteInfoOption`.
This commit changes how the options are added in a message so that we
directly construct the option in the message buffer (instead of
creating it separately and then copying the bytes).
It also changes `RouteInfoOption::IsValid()` to validate that the
option length can fit the specified prefix length.
=> [routing-manager] prepare route/prefix info options in place

src/core/border_router/routing_manager.cpp
This commit changes `RoutingManager::PublishExternalRoute()` method
to return `kErrorAlready` as `kErrorNone` (i.e., if the prefix to be
published was previously published). This commit keeps the logging
the same (i.e. we still log on `Already` error so we can see when/if
this happens).
----
This is on top of a **modified** version of commit from @jwhui from https://github.com/openthread/openthread/pull/7707
I hope/expect this will address the test failure in [comment](https://github.com/openthread/openthread/pull/7707#issuecomment-1129517409).
=> [routing-manager] `PublishExternalRoute()` to return  success on `kErrorAlready`     

tests/scripts/thread-cert/border_router/test_border_router_as_fed.py
This commit adds some wait time before connectivity
validation to mitigate the impact of #7660 which
introduces some random delay before publishing
external route into network data.
=> [tests] add wait time in test_border_router_as_fed.py

src/core/net/tcp6.cpp, src/core/net/tcp6.hpp
This commit updates `Tcp::Endpoint` and `Tcp::Listener` types to
inherit from `GetProvider` (which provides `Get<Type>()` methods
allowing them to directly access different components in an
OpenThread `Instance`).
=> [tcp6] `Endpoint` and `Listener` to act as `GetProvider`

examples/platforms/simulation/platform-simulation.h, examples/platforms/simulation/radio.c, examples/platforms/simulation/system.c, include/openthread/instance.h, include/openthread/link_raw.h, include/openthread/platform/radio.h, src/core/mac/link_raw.hpp, src/core/mac/mac_links.hpp, src/core/mac/sub_mac.hpp, src/core/radio/radio.hpp, tests/scripts/expect/posix-rcp-energy-scan.exp
This commit implements energy scan in simulation platform.
Verified locally
```bash
> ifconfig up
Done
> scan energy 100
| Ch | RSSI |
+----+------+
| 11 |  -98 |
| 12 |  -98 |
| 13 |  -98 |
| 14 |  -98 |
| 15 |  -98 |
| 16 |  -98 |
| 17 |  -30 |
| 18 |  -98 |
| 19 |  -98 |
| 20 |  -30 |
| 21 |  -30 |
| 22 |  -98 |
| 23 |  -30 |
| 24 |  -98 |
| 25 |  -30 |
| 26 |  -30 |
Done
```
=> [simulation] simulate energy scan

src/core/border_router/router_advertisement.cpp, src/core/border_router/router_advertisement.hpp, src/core/border_router/routing_manager.cpp
This commit updates and simplifies `RouterAdvMessage`:
- Adds new method to get and set the "default router preference"
- Removes custom overloads of operator `=` and `==` (which
excluded the checksum field). Instead when we save a received RA
in `RoutingManager` we directly set the checksum to zero so the
normal (byte by byte) comparison would work.
=> [router-advert] `RouterAdvMessage` to provide default router prf

include/openthread/instance.h, include/openthread/link.h, src/core/mac/data_poll_sender.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp
There are no use cases where `kErrorAlready` is useful.
---
This also addresses intermittent failures in `v1_2-sed_mac_send.exp` due to this check:
https://github.com/openthread/openthread/blob/5107ee623837ed5b20cae4e6758644c1ca772c56/tests/scripts/expect/v1_2-sed_mac_send.exp#L39
=> [data-poll-sender] return `kErrorNone` when Data Request is already enqueued

include/openthread/instance.h, include/openthread/srp_client.h, src/cli/README_SRP_CLIENT.md, src/cli/cli_srp_client.cpp, src/core/api/srp_client_api.cpp, src/core/net/srp_client.cpp, src/core/net/srp_client.hpp, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_srp_client_change_lease.py
---
The SRP Server and Advertising Proxy also need updating to make use of the TTL.
=> [srp-client] add API to specify TTL

src/core/border_router/routing_manager.cpp
This commit fixes a bug that BR could incorrectly remove the route of the local on-link prefix in Network Data when it's still advertising the local on-link prefix. 
This is a short-term fix because in the long term we want to refactor how `RoutingManager` manages external routes and the default route.
=> [routing-manager] fix BR incorrectly removing route for local on-link prefix

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/config/border_router.h, src/core/config/openthread-core-config-check.h, tests/scripts/thread-cert/border_router/test_on_link_prefix.py
The vicarious router discovery feature depends on the ability to
receive Router Advertisement messages sent in response to Router
Solicitation messages from other hosts. However, this does not work
since Router Advertisement messages are often sent unicast in
response.
=> [routing-manager] remove vicarious router discovery feature

src/core/net/srp_server.cpp, src/core/net/srp_server.hpp
----
Please check the last commit.
Added it on top of commits from https://github.com/openthread/openthread/pull/7715
=> [srp-server] check allocated `UpdateMetadata` is not `nullptr`

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit changes `EvaluateOnLinkPrefix()` to directly update
`mIsAdvertisingLocalOnLinkPrefix`. The `SendRouterAdvertisement()` is
also simplified to directly use this boolean variable (instead of
a pointer to prefix being passed as input parameter) to determine
whether or not to include a PIO with the local on-link prefix.
=> [routing-manager] simplify `EvaluateOnLinkPrefix()` and sending RA

include/openthread/dnssd_server.h, include/openthread/instance.h, src/core/api/dns_server_api.cpp, src/core/net/dnssd_server.cpp, src/core/net/dnssd_server.hpp
This PR implements `otDnssdGetCounters` to report the statistics of the DNS-SD server.
=> [dnssd-server] add `otDnssdGetCounters` for telemetry

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit simplifies the mechanism to invalidate/remove a specific
prefix entry in `mDiscoveredPrefixes` list. Instead of passing the
prefix to invalidate as an input to `InvalidateDiscoveredPrefixes()`
method, we directly set the valid lifetime to zero on the entry in
the list before calling the `InvalidateDiscoveredPrefixes()` to then
remove all expired entries.
This change addresses an issue in `HandleRouterSolicitTimer()` where
while iterating over the `mDiscoveredPrefixes` list we could call
`InvalidateDiscoveredPrefixes()` which then removed an entry from the
list (thus changing the list).
=> [routing-manager] simplify invalidation of specific prefix

src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/mle_types.hpp, tests/scripts/thread-cert/Cert_5_2_04_REEDUpgrade.py, tests/scripts/thread-cert/v1_2_test_parent_selection.py, tools/otci/tests/test_otci.py
A device sends a multicast Link Request message after becoming a
router to quickly and efficiently establish links with neighboring
routers. However, sending a Link Request too quickly can fail in cases
where the neighboring router(s) have not yet received the updated
Router ID set from the Leader.
This commit delays sending the Link Request to allow time for
neighboring routers to receive the updated Router ID from the Leader.
---
See discussion in #7359
=> [mle] delay sending multicast Link Request

tests/scripts/thread-cert/Cert_9_2_09_PendingPartition.py
Disable steps 32, 33, and 34 until a solution is found. Depending on
timing, there may be one MLE Data Request/Response exchange for both
Active and Pending Operational Datasets or individual MLE Data
Request/Response exchange for each Active and Pending Operational
Dataset separately.
---
See #7763
=> [tests] disable some checks in Cert_9_2_09

src/core/thread/mle_router.cpp
=> [mle-router] fix uninitialized pointer in `SendLinkRequest()`

src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, tests/scripts/thread-cert/Makefile.am, tests/scripts/thread-cert/test_router_upgrade.py
OpenThread only establishes links when the link margin is above a
certain threshold, to help ensure that links in the routing topology
are stable. However, if a device has no existing links to neighboring
routers above threshold, then upgrading to a router is useless and
disruptive.
This commit adds a check to ensure there is at least one neighbor
above the link margin threshold before upgrading to a router.
---
See discussion in #7359
=> [mle] evaluate neighbor links before upgrade to router

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/thread/network_data_types.hpp
This commit updates `RoutingManager` to track the preference of the
discovered OMR prefixes from Thread Network Data and advertise the
OMR prefixes with the same preference in Route Info Options in the
emitted Router Advertisements.
This commit adds `OmrPrefix` class (which tracks an OMR prefix along
with its preference) and provides helpers method (e.g., method to
compare two OMR prefixes to determine which one is favored, `ToString()`
method). The `EvaluateOmrPrefix()` is updated to use the new
`OmrPrefix` class.
=> [routing-manager] add `OmrPrefix` class, include OMR preference in RIO

etc/cmake/options.cmake
#7767 added a define for outgoing beacon payloads that is defaulted off `OPENTHREAD_CONFIG_MAC_OUTGOING_BEACON_PAYLOAD_ENABLE`
this adds a cmake option to configure this on. tested by passing this through as a cmake option when building OTBR and testing that beacon payloads were enabled.
=> [cmake] add build option to configure outgoing beacon payload

examples/apps/cli/radio.cmake, src/cli/radio.cmake, src/core/radio_cli.cmake
This PR enables a different mbedtls library to be used for RCP builds.
Proposed change will make it possible to use a PSA Crypto mbedtls library for FTD/MTD images while using a non-PSA crypto library on RCPs
=> [cmake] add option for RCP specific mbedtls library

src/core/meshcop/timestamp.hpp, src/core/thread/mle.cpp
MLE Orphan Announce messages include a timestamp value that has both
seconds and ticks set to zero, but authoritative bit set. However, the
default Active Timestamp value is all zeros. As a result, an MLE
Orphan Announce timestamp can appear to be greater than the default
Active Timestamp value and cause a device to detach.
This commit adds a special case to check for the Orphan Announce
timestamp.
Fixes #7785
=> [mle] fix handling of MLE Orphan Announce messages

tests/scripts/thread-cert/Cert_5_3_06_RouterIdMask.py
Time delay between MLE Advertisements after reset can be up to 3.5
seconds. For example:
- 0.0s: Reset Interval, reset interval to 1 seconds, random interval
at 0.5 second
- 0.5s: Transmit MLE Advertisement
- 1.0s: Set interval to 2 seconds, random interval at 2 seconds
- 3.0s: Receive MLE Advertisement, reset interval to 1 second, random
interval at 1.0 second
- 4.0s: Transmit MLE Advertisement
Fixes  #7787
=> [tests] relax MLE Adv delay check in Cert_5_3_06_RouterIdMask

src/core/net/srp_client.cpp, src/core/net/srp_client.hpp, src/posix/platform/openthread-core-posix-config.h, tests/scripts/thread-cert/Makefile.am, tests/scripts/thread-cert/test_srp_many_services_mtu_check.py
This commit adds a new mechanism in `Srp::Client`: When preparing an
update message, client will check whether the prepared message fits
in an IPv6 MTU (1280 bytes). If it does not, the SRP client would
temporarily enable "single service mode" which ensures only a single
service (along with its sub-types) to be appended in the SRP update
message. After the message is sent SRP client would switch back to
normal behavior and disables the single service mode.
This change addresses situation where user may register many services
(with multiple sub-types and long TXT data) which then may not fit
in a single UDP message payload.
This commit also adds `test_srp_many_services_mtu_check` test which
verifies the newly added behavior.
=> [srp-client] message MTU check and single service mode

tests/scripts/thread-cert/test_router_multicast_link_request.py
This commit adds a test to make sure delay sending multicast Link Request (#7745) works as intended.
=> [tests] verify a Router can establish links quickly via multicast Link Request

src/core/net/srp_server.cpp, src/core/net/srp_server.hpp
This commit updates `Srp::Server` to treat the update instructions in
a received SRP message for a service and all its sub-types as atomic.
It adds a new method `ValidateServiceSubTypes()` which performs two
checks. First, it verifies that there is a matching base service for
all sub-type services in a received SRP Update message. Second, it
treats the sub-types in the message as atomic, i.e., whatever
information appears in the message is considered the entirety of
information about the service and its sub-types. In particular, any
previously registered service sub-type that does not appear in a new
SRP Update is removed (marked as deleted).
This commit updates `test_srp_sub_type.py` test-case to validate the
behavior of newly added mechanism (i.e. removal of older sub-types
when not …
=> [srp-server] validate sub-types and treat as atomic

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_BR.py
A BR with `BORDER_ROUTING` feature may add OMR prefix and external routes to the network data when Thread is started. 
The network data changes may incur additional Thread communications that may interfere with certification traffic.
This commit enhances THCI to wait for the network data to stabilize after the BR is started.
=> [thci] wait for netdata to stabilize if `BORDER_ROUTING` is enabled

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/net/nd6.cpp, src/core/net/nd6.hpp
This commit adds a new class `RouterAdvertMessage` representing an RA
message. It provides methods to append options (PIO or RIO) to the RA
message or parse and iterate over the options in the RA message
(using newly added `Option::Iterator` which allows use of range-based
`for` loop). These method are used by `RoutingManager` and help
simplify the code.
----
~This PR contains the  commit from~
~- https://github.com/openthread/openthread/pull/7780~
~Please review and check the last commit. Thanks.~
=> [routing-manager] simplify RA message parsing and preparation

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp
This commit is a cosmetic change and contains no change in the code
logic. It is a follow-up from #7689 which added `Mle::Tx/RxMessage`
types. This commit moves all `TxMessage` and `RxMessage` method
definitions close to one another (at the end of `mle.cpp`).
----
Background:
Avoided moving method definitions in #7689 to help keep the `diff` 
smaller and easier to review.
=> [mle] move method definitions of the `Tx/RxMessage` close to each other

src/core/border_router/routing_manager.cpp
This commit updates the calculation of the next stale time in
`ResetDiscoveredPrefixStaleTimer()` in (unlikely) cases where the
stale time of a discovered prefix or RA header happens to be in past
(compared to `GetNow()`). In such a case, we use `now` as the stale
time of the entry. This then ensures that we can correctly
compare the stale time with `now.GetDistantFuture()`.
---
I expect the situation where stale time of an entry is in past would be unlikely, 
but better to do the proper thing in such cases.
=> [routing-manager] fix calculation if an entry's stale time is in past

src/core/common/array.hpp, src/core/net/dns_dso.cpp, tests/unit/test_array.cpp
This commit adds `Remove/RemoveMatching()` in `Array` class which
remove a given or a matched element from the array. To remove the
element, it is replaced by the last element from array, so the order
of items in the array can change after call to these method.
This commit also updated unit test `test_array` to verify the behavior
of newly added methods.
----
This PR also contains a small related seperate commit:
- [dns-dso] use `Array::RemoveMatching()`
The new `Array` methods will be used in follow-up PR in 
`RoutingManager` as well
=> [array] add `Remove()` and `RemoveMatching()`

src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, tests/unit/test_ip_address.cpp
This commit updates `Ip6::Prefix` comparison (overload of `<`
operator). If the two prefixes have same length N, then the bytes are
compared directly (as two big-endian N-bit numbers). If the two
prefix have different lengths, the shorter prefix is padded by `0`
bit up to the longer prefix length N before the bytes are compared
(as big-endian N-bit numbers). If all bytes are equal, the prefix
with shorter length is considered smaller.
This commit also updates `test_ip_address` unit test to validate
the new comparison behavior.
=> [ip6] update `Ip6::Prefix` comparison

src/core/thread/network_data_notifier.cpp, src/core/thread/network_data_notifier.hpp, src/core/thread/network_data_publisher.cpp, src/core/thread/network_data_publisher.hpp
**[netdata] perform `SynchronizeServerData()` from a `Tasklet`**
This commit adds a `Taskelt` in `NetworkData::Notifier` to perform
`SynchronizeServerData()` and post this tasklet when there is a
change and `HandleServerDataUpdated()` is called. This ensures that
if there are multiple changes triggered within the same flow of
execution, they are all synchronized together and included in the
same message to register with leader.
**[netdata] simplify `Publisher` to use `HandleServerDataUpdated()`**
This commit simplifies `NetworkData::Publisher` to rely and use the
new `HandleServerDataUpdated()` behavior which uses a `Tasklet` to
start the registration with leader. With this, we can directly call
`HandleServerDataUpdated()` whenever there is a change …
=>  [netdata] perform `SynchronizeServerData()` from a `Tasklet`

src/core/common/time_ticker.cpp, src/core/common/time_ticker.hpp, src/core/config/border_router.h, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/mle_types.hpp, src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_notifier.cpp, src/core/thread/network_data_notifier.hpp, src/core/thread/thread_tlvs.hpp, tests/scripts/thread-cert/Makefile.am, tests/scripts/thread-cert/test_br_upgrade_router_role.py, tests/unit/test_network_data.cpp
This commit adds a new mechanism to allow border routers to request
router role upgrade.
A border router which provides IP connectivity (either adding an
external route prefix or an on-mesh prefix with default route flag)
and is acting as a REED is eligible to request a router role upgrade
by sending an "Address Solicit" request to leader with status reason
`BorderRouterRequest`. This reason is used when the number of active
routers in the Thread mesh is above the threshold, and only if the
number of existing eligible BRs (determined from the network data)
that are acting as router is less than two. This mechanism  allows up
to two eligible border routers to request router role upgrade when
the number of routers is already above the threshold.
This commit also adds a new test-case …
=> [netdata] add feature for BR to request router role upgrade

include/openthread/instance.h, include/openthread/netdata_publisher.h, src/core/thread/network_data_publisher.cpp, src/core/thread/network_data_publisher.hpp, tests/scripts/thread-cert/test_netdata_publisher.py
This commit updates `NetworkData::Publisher` so that a call to
`PublishOnMeshPrefix()` or `PublishExternalRoute()` replaces a
previous request for the same prefix. In particular, if the new call
only changes the flags (e.g., preference level) and the prefix is
already added in the Network Data, the change to flags is immediately
reflected in the Network Data. This ensures that existing entries in
the Network Data are not abruptly removed. Note that a change in the
preference level can potentially later cause the entry to be removed
from the Network Data after determining there are other nodes that
are publishing the same prefix with the same or higher preference.
This commit also updates `test_netdata_publisher.py` to test the newly
added behavior.
----
_Background:_
The new behavior, …
=> [netdata] update `Publisher` to allow change to previous entries

script/check-simulation-build-autotools
This commit updates `check-simulation-build-autotools` to use the
`LOG_OUTPUT` switch directly. This addresses an issue where
we could end up with multiple `OPENTHREAD_CONFIG_LOG_OUTPUT`
definitions in the `CPPFLAGS`.
----
- Should help address #7832.
=> [script] fix multiple `LOG_OUTPUT` definitions

include/openthread/instance.h, include/openthread/ip6.h, src/cli/cli.cpp, src/core/backbone_router/bbr_manager.cpp, src/core/thread/mlr_manager.cpp, src/core/thread/mlr_manager.hpp, src/core/thread/thread_tlvs.hpp, src/ncp/ncp_base_mtd.cpp
This commit moves the definitions of constants related to min/max
number of IPv6 addresses that can be included in an IP6 Addresses TLV
to `Ip6AddressesTlv` class. It also adds a public OT constant in
`ip6.h` related to this for MLR feature which is then used in `cli`
and `ncp` modules so to avoid the use of OT core internal constant
from CLI/NCP.
=> [thread-tlvs] define min/max num of addrs under `Ip6AddressesTlv`

src/core/thread/child_table.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, tests/scripts/thread-cert/Makefile.am, tests/scripts/thread-cert/test_mle_msg_key_seq_jump.py
This commit implements new mechanism in `Mle` related to key sequence
update when an MLE message is received with a larger key sequence
compared to the one being used by `KeyManager`. The MLE messages are
categorized into classes of Authoritative, Tentative, or Peer
depending on the MLE command type and included TLVs. The class
determines different actions: ~Tentative is used where the sender of
MLE message may not be sure that its key seq is in sync with the rest
of the Thread network, so the receiver will not adopt the key seq.~
Authoritative indicates sender is confident that its key seq is in
sync, so receiver will adopt the larger key seq. Peer class is used
when both sender and receiver think they are in sync. In this case,
if the MLE message is from a known neighbor, receiver will …
=> [mle] handle rx key seq update based on MLE message class

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_BR.py
- Adding support for 1.3 style border router configurations which are different from the 1.2 style border router configurations.  The 'device capabilities' is used to differentiate between these 2 device types to assign them their needed configuration parameters.
- Also moving restartAgentService to the proper class.
=> [thci] support 1.3 border router configurations

src/core/radio.cmake
This should have been included in #7781
=> [cmake] add option for RCP specfific mbedtls library

src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/mle_types.hpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp
This commit adds a new mechanism related to Network Data recovery on
leader after restart. We determine whether device is starting normally
as leader or restoring its role as leader after restart. In the
latter case, we do not allow the device to accept any new Network Data
registrations until it has successfully recovered the Network Data
(received MLE Data Response).
This change help address situation where Network Data entries
registered with leader before it syncs and restores the Network Data
can be removed and then take a while to be re-registered.
----
- This should help address #7811
=> [netdata] wait for sync before accepting new data on leader restart

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit updates how `RoutingManager` learns the RA header from
host daemons. It adds a new method to determine whether a received RA
message is prepared by the `RoutingManager` itself by checking the
options (PIO and RIO) from the RA message. When learning/updating the
host RA header, we check and skip over such self-prepared RA
messages.
----
Addresses #7815
=> [routing-manager] skip self-prepared RA when learning host RA header

src/core/common/instance.cpp, src/core/common/instance.hpp, src/core/thread/thread_netif.cpp, src/core/thread/thread_netif.hpp
This commit moves all the OT core member variable definitions into
`Instance` class (from `ThreadNetif`).
=> [instance] move definition of all OT core objects in `Instance`

include/openthread/border_router.h, include/openthread/instance.h, src/cli/README.md, src/cli/cli.cpp, src/core/api/border_router_api.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit adds new mechanism in `RoutingManager` to allow user to
get or set the preference level to use when advertising discovered
OMR prefixes as RIO entries in emitted RA messages on infra netif. By
default 'medium' preference is used. As example user can choose to
set the preference to 'low' when the device is acting as a temporary
BR (a mobile or battery-powered BR) to indicate that other BRs should
be preferred over this BR on the infra link.
An OMR prefix entry in the Thread Network Data has its own preference
value which is used to compare OMR prefixes and determine the favored
OMR prefix. This preference is unrelated to the preference value used
when advertising the discovered OMR prefix in RA message.
This commit also adds CLI sub-commands for newly added APIs and
updates the …
=> [routing-manager] get/set preference to advertise OMR prefix in RA msg

src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_links.hpp, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/thread/mle.cpp
After enabling the scheduling of delayed reception slots in #7677 they would be configured even when the device switched to MED mode.
This commit introduces some simplifications around the CSL states and scheduling:
- Mantain the CSL timer stopped if not in CSL Receiver mode.
- Keep the CSL Period and Channel values in the MAC in order to use them as an indication of CSL Receiver mode in the Sub-Mac.
=> [csl] simplify receiver states and scheduling

src/lib/spinel/radio_spinel.hpp, src/lib/spinel/radio_spinel_impl.hpp, src/lib/spinel/radio_spinel_metrics.h, src/posix/platform/include/openthread/openthread-system.h, src/posix/platform/radio.cpp
When the RCP is not stable, it causes the Thread stack crashed.
To better know the stability of the RCP, this PR adds an API to
return the radio spinel metrics.
=> [spinel] add an API to get the radio spinel metrics

src/core/thread/mle_router.cpp
This commit adds a call to `Get<Mac::Mac>().UpdateCsl()` when there
is role change from `SetStateLeader()` or `SetStateRouter()`. This
ensures to disable CSL at `SubMac` and radio platform.
----
This is follow up from #7783 where a common `UpdateCsl()` is added to make decision when there is a change
- This is not critical change (since after we switch to router/leader role we won't enter sleep or CSL sample satte)
- But make sense for us to invoke the `UpdateCsl()` to disable it.
`UpdateCsl()` looks into 3 things from `Mle`:
- `Get<Mle::MleRouter>().IsChild()`
- `Get<Mle::Mle>().GetParent().IsEnhancedKeepAliveSupported()`
- `Get<Mle::Mle>().IsRxOnWhenIdle()`
We need to ensure to call`UpdateCsl()` when there is change in any of these. Here is what I tracked related to this:
- Role changes …
=> [csl] update CSL on role change to router or leader

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit contain smaller enhancements related to managing the
local OMR prefix:
- It adds a new class to encapsulate all the related data and
methods.
- We directly track whether or not the prefix is added to the local
Network Data (using a boolean)
- The methods are renamed to use the terms "add/remove" instead of
"publish/unpublish" since the Network data publisher is not used
for OMR prefix and it is directly added or removed.
=> [routing-manager] adding `LocalOmrPrefix` class

.github/workflows/build.yml, src/core/thread/mlr_manager.cpp, src/lib/platform/reset_util.h
Use gcov_dump when using clang on MacOS and the version is 13 or above
or when using clang on a non MacOS system and the version is 12 or above.
This is a follow on change to #7629.
=> [gcov] use __gcov_dump() instead for clang 12/13

src/core/net/srp_client.cpp
This commit updates the SRP client to not include sub-types PTR
records when the base service is being removed.
---
Please see https://github.com/project-chip/connectedhomeip/issues/18507#issuecomment-1178050134 for background
Addresses https://github.com/project-chip/connectedhomeip/issues/18507
=> [srp-client] exclude sub-type PTR when service is being removed

Android.mk, include/Makefile.am, include/openthread/BUILD.gn, include/openthread/border_router.h, include/openthread/border_routing.h, include/openthread/instance.h, src/cli/cli.cpp, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/api/border_router_api.cpp, src/core/api/border_routing_api.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
**[api] add `border_routing.h` header for `otBorderRouting` APIs**
This commit adds `<openthread/border_routing.h`> header and moves
all the `otBorderRouting` APIs (which are related to Border Routing
Manager) into this header. It also adds a note that these APIs are
available when `OPENTHREAD_CONFIG_BORDER_ROUTING_ENABLE` is enabled.
It also adds `border_routing_api.cpp` source file for the API
implementation.
**[routing-manager] add public API to get discovered prefix table**
This commit adds new public OT APIs to iterate over the Border Router
discovered prefix table from received Router Advertisement messages.
It also adds new CLI command to output the prefix table. The new APIs
are primary intended for testing.
=> [routing-manager] add public API to get prefix table & new header file

src/core/net/icmp6.cpp, src/core/net/icmp6.hpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
A new flavor of `Icmp::SendError()` is added which allows the caller
to provide the parsed `Ip6::Headers` of the error-causing message
instead the full `Message` instance. Note that the implementation of
`SendError()` only includes the IPv6 header of the error-causing
message in the payload of the ICMPv6 error message.
`MeshForwarder::CheckReachability()` method is updated to use the
recently added `Ip6::Headers` to parse the IPv6 headers from the
received frame. With the changes in this commit, we no longer need to
allocate a temporary `Message` which was used for reading the
decompressed IPv6 header and also to pass to `Icmp::SendError()` in
case of "destination unreachable" error.
=> [mesh-forwarder] simplify `CheckReachability()` and `Icmp::SendError()`

tests/toranj/ncp/test-017-parent-reset-child-recovery.py
This commit updates `test-017-parent-reset-child-recovery.py` to make
it more robust by increasing the wait time for children to be
recovered after parent/leader reset. This is related to the increase
in data poll period of sleepy children to 10 sec which was done
previously to accommodate for the increased start-up time of leader
(due to change in number of MLE Parent Requests).
=> [toranj] make `test-017` more robust

src/core/thread/tmf.cpp, src/core/thread/tmf.hpp
This commit updates `Tmf::IsTmfMessage()` method to check source and
destination addresses. This change helps make this method more
generic(allow it to be used for both rx/tx messages). This commit
also simplifies the implementation (avoid using complex expression
containing multiple `&&` and `||`).
=> [tmf] update `IsTmfMessage()` method

Android.mk, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/common/frame_data.cpp, src/core/common/frame_data.hpp, src/core/common/message.hpp, src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/thread/lowpan.cpp, src/core/thread/lowpan.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, tests/unit/test_lowpan.cpp
This commit adds a new class `FrameData` which is a sub-class of
`Data` (acts as a wrapper over a buffer pointer and a length). It is
used in `MeshForwarder` and `Lowpan` to simplify the method calls
(can pass `FrameData` instance instead of pointer and length). It
also provides helper methods for parsing the frame content (e.g.,
reading `uint16/32` value assuming big or little endian encoding).
When read successfully, the `FrameData` is updated to skip over the
read content. These methods help simplify `Lowpan` parsing and
decompression code. In particular the `Lowpan` methods now directly
update the passed-in `FrameData` to skip over the parsed header
portion (instead of returning the parsed header length).
=> [core] adding `FrameData` class for parsing frames

src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp
Cover the case of parent change while the CSL child is still attached.
=> [csl] update CSL information in radio when parent changes

tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_BR.py
This commit uses `Param9` to specify custom commands for Thread BR THCI to control `otbr-agent`.
=> [thci] allow to specify custom commands

tests/scripts/thread-cert/find_border_agents.py, tools/harness-thci/OpenThread_BR.py
Thread BR may advertises IPv6 GUA rather than LLA. For example, Avahi stops publishing LLA when any GUA is found on the network interface.
This commit enhances mdns_query to find border agents with non link-local addresses.
=> [thci] find border agents with non link-local addresses

doc/ot_api_doc.h
This is a follow-up to: https://github.com/openthread/openthread/pull/7824
I added the group definition under IPv6 Networking.
=> [docs] add NAT64 to Doxygen

src/core/thread/router_table.cpp
The Last Heard timestamp should not be updated when removing Router Link.
=> [routing-table] do not reset LastHeard timestamp when removing router link

src/core/mac/mac.cpp, tests/scripts/thread-cert/v1_2_test_csl_transmission.py
This commit changes `Mac::UpdateCsl()` to ensure we inform `SubMac`
and disable CSL when CSL support changes (e.g., device gets
detached). This ensures that `SubMac` internal variables (CSL period,
channel) are updated on a detach and if the device later attaches
again, we detect the change in CSL configuration and trigger the tx
of MLE Child Update Request.
---
Please see https://github.com/openthread/openthread/pull/7915 for more details.
=> [csl] ensures `SubMac`is informed when CSL support changes

script/test
This commit fixes the build options for NAT64 tests. A new option was added in ot-br-posix recently ([ref](https://github.com/openthread/ot-br-posix/pull/1455)).
=> [nat64] fix build options for NAT64 tests

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/config/border_router.h
This commit changes `RoutingManager` so to include all on-mesh
prefixes from Thread Network Data (which include OMR prefixes)
as Route Info Option in the emitted Router Advertisement messages.
----
This is related to [SPEC-1087](https://threadgroup.atlassian.net/browse/SPEC-1087).
=> [routing-manager] advertise all on-mesh prefixes as RIOs in emitted RAs

include/openthread/border_routing.h, include/openthread/instance.h, src/cli/cli.cpp, src/core/api/border_routing_api.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit updates `RoutingManager` to remember the currently favored
OMR prefix (which can be an OMR prefix discovered from Network Data
or device's local OMR prefix). It adds a new public API to retrieve
this prefix and adds a related CLI sub-command.
---
This PR currently contains the commit from https://github.com/openthread/openthread/pull/7900.
Please read and review the last commit in this PR.
=> [routing-manager] new API to get currently favored OMR prefix

tests/unit/CMakeLists.txt, tests/unit/Makefile.am, tests/unit/test_routing_manager.cpp
This commit adds a unit test for `RoutingManager` which builds a
foundation for writing test cases covering different behaviors of
`RoutingManager`, e.g., validating emitted router advertisements,
sending custom RA messages from different routers on AIL, adding or
removing entries in Network Data while monitoring the behavior of
`RoutingManager`.
=> [test] add unit test `test_routing_manager`

tools/harness-simulation/README.md, tools/harness-simulation/harness/Thread_Harness/Sniffer/SimSniffer.py, tools/harness-simulation/harness/Thread_Harness/THCI/OpenThread_Sim.py, tools/harness-simulation/harness/Thread_Harness/simulation/config.py, tools/harness-simulation/harness/Web/data/deviceInputFields.xml, tools/harness-simulation/harness/install.bat, tools/harness-simulation/posix/harness_dev_discovery.py, tools/harness-simulation/posix/sniffer_sim/pcap_codec.py, tools/harness-simulation/posix/sniffer_sim/sniffer.py, tools/harness-simulation/posix/sniffer_sim/sniffer_transport.py
It can run all the Thread 1.1 test cases with simulations as a role of Router now except those requiring RF enclosure.
=> [harness] add functionality to discover and control simulations

etc/cmake/options.cmake
Change the definition of OPENTHREAD_CONFIG_COAP_OBSERVE_API_ENABLE
through target_compile_detinifions().
Signed-off-by: Luis Ubieda <luisubiedas@gmail.com>
=> [cmake] update option to enable CoAP Observe through CMake

include/openthread/instance.h, include/openthread/message.h, script/check-simulation-build-autotools, src/core/common/message.cpp, src/core/common/message.hpp
This commit updates the code to allow the config combination of
`OPENTHREAD_CONFIG_MESSAGE_USE_HEAP_ENABLE` along using external heap
`OPENTHREAD_CONFIG_HEAP_EXTERNAL_ENABLE`. This commit updates `Message`
`GetFreeBufferCount()` and `GetTotalBufferCount()` methods to return
special value `0xffff` under this config combo indicating the numbers
cannot be estimated.
This commit also updates `check-simulation-build-autotools` to add
such a build config so to be covered as part OT CI tests.
----
Should address https://github.com/openthread/openthread/issues/7931.
=> [message] allow msg pool using external heap

Android.mk, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/common/appender.hpp, src/core/common/frame_builder.cpp, src/core/common/frame_builder.hpp, src/core/thread/lowpan.cpp, src/core/thread/lowpan.hpp, src/core/thread/mesh_forwarder.cpp, tests/unit/CMakeLists.txt, tests/unit/Makefile.am, tests/unit/test_frame_builder.cpp, tests/unit/test_lowpan.cpp
This commit adds a new class `FrameBuilder` which helps with
construction of frames in a given buffer. It provides helper methods
to append different items to the frame, e.g., bytes from a buffer or
`Message`, a `uint8`, `uint16` or `uint32` value assuming big or
little endian encoding, or a given object. It also provides methods
to overwrite previously appended content in the frame at a given
offset. This class is used in `Lowpan` (replacing `BufferWriter`)
which helps simplify the code. This commit also updates `Appender` to
use the `FrameBuilder` and adds a new unit test for `FrameBuidler`.
=> [core] adding `FrameBuilder` for constructing frames

src/core/border_router/routing_manager.cpp, tests/unit/test_routing_manager.cpp
This commit fixes an issue with the potential overwriting of `mNext`
when existing entry in the list is updated (avoid calling `Clear()`).
It also updates `test_routing_manager` to check such a situation
and ensure that the fix is addressing the issue.
----
Please see https://github.com/openthread/openthread/pull/7943.
=> [routing-manager] fix `DiscoveredPrefixTable::Entry` leak

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit updated how `RoutingManager` selects the set of prefixes
to advertise as RIO in emitted RA messages from the BR.  The related
code is now moved to `SendRouterAdvertisement()` method (instead of
previously being in `EvaluateOmrPrefix()`). Since the array for
storing the advertised prefixes has a limited size (configurable
through an OT build-time setting), we add more important prefixes
first in the array to ensure that they are advertised in the RA
message. The following order is used: (1) Local OMR prefix (if
added in Network Data), (2) currently favored OMR prefix, (3) any
other OMR prefixes from Network Data, (4) any other on-mesh prefix
(excluding Domain Prefix) from Network Data.
----
This is related to [SPEC-1087](https://threadgroup.atlassian.net/browse/SPEC-1087).
=> [routing-manager] enhance selection of prefixes to advertise as RIO

bootstrap
```
========================================
check shell
========================================
--- bootstrap.orig
+++ bootstrap
@@ -39,7 +39,8 @@
abs_srcdir=$(cd "$(dirname "${0}")" && pwd)
-(cd "$abs_srcdir" && exec "$abs_srcdir/$nlbuild_autotools_stem/scripts/bootstrap" -I "$abs_srcdir/$nlbuild_autotools_stem" "${@}") 2> \
-    >(grep -v "installing 'third_party/nlbuild-autotools/repo/third_party/autoconf/missing'" \
+(cd "$abs_srcdir" && exec "$abs_srcdir/$nlbuild_autotools_stem/scripts/bootstrap" -I "$abs_srcdir/$nlbuild_autotools_stem" "${@}") 2> >(
+    grep -v "installing 'third_party/nlbuild-autotools/repo/third_party/autoconf/missing'" \
| grep -v "installing 'third_party/nlbuild-autotools/repo/third_party/autoconf/compile'" \
-        | grep -v "installing …
```
=> [bootstrap] apply `shfmt` diffs

src/core/border_router/routing_manager.cpp
This commit fixes the method setting the prefix table entry from
RA header as a default route by clearing `mPrefix` variable so
to set it as `::/0`.
----
Follow up to #7945. Thanks to @simonlingoogle  for noticing this.
=> [routing-manager] ensure to clear the prefix for default route

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit renames the `DiscoveredPrefixTable::Entry` method to
`SetFrom()` from `InitFrom()` to make it clear that this method can
be used on an existing entry to update it.
=> [routing-manager] rename `DiscoveredPrefixTable::Entry` method to `SetFrom()`

tests/toranj/ncp/test-017-parent-reset-child-recovery.py
This commit relaxes the pass condition for `test-017` which checks
that after a parent is reset it uses "MLE Child Update Request" to
recover its previous children. This is indirectly validated by
monitoring number of state/role changes on the children. With the
recent change which increases the number of MLE Parent Requests, the
window of time where parent is detached is increased and if during
this time a child tries to send to the parent it can detect that
parent is reset and detach itself causing the test to fail. This
commit relaxes the pass condition to at least one child recovering
using "Child Update" mechanism.
----
The recovery using MLE Child Update is already well-covered by 
other cert test, so we can consider disabling this test. I went for
relaxing the pass condition in …
=> [toranj] relax test-017-parent-reset-child-recovery pass condition

src/core/config/misc.h, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mesh_forwarder_mtd.cpp
This commit adds a new feature in `MeshForwarder` to specify a max
limit for the number of frames in tx queue marked for direct
transmission. `OPENTHREAD_CONFIG_MAX_FRAMES_IN_DIRECT_TX_QUEUE`
specifies the maximum number. If set to zero then this behavior is
disabled, i.e., no check is performed on tx queue length.
This commit also adds a new message action log "Dropping (dir queue
full)" which indicates when a message is being dropped due to the
newly added check.
---
This is related to [SPEC-1041](https://threadgroup.atlassian.net/browse/SPEC-1041).
=> [mesh-forwarder] allow limiting max num of frames in direct tx queue

tests/scripts/thread-cert/test_mle_msg_key_seq_jump.py
This commit updates `test_mle_msg_key_seq_jump` to increase the wait
time after key index change for MLE advertisement transmissions. The
MLE advertisement uses trickle timer with max interval of 32 seconds.
Based on this the max interval between two consecutive advertisement
transmissions can be 1.5 times the trickle timer max interval or 48
seconds. The test uses 52 sec as wait time which includes a 4 sec
additional guard time to account for any action and/or message
exchanges after rx of an advertisement. This change should help
address the occasional failures of this test.
=> [test] fix `test_mle_msg_key_seq_jump`

src/core/thread/mle_router.cpp
This commit fixes `MleRouter::HandleChildUpdateResponse()` to use the
MLE `StatusTlv` instead of `ThreadStatusTlv` when parsing a received
MLE Child Update Response (from a child).
----
_Background and More Details:_
Discovered this while trying to debug the occasional failure of `test_mle_msg_key_seq_jump` (e.g. [link](https://github.com/openthread/openthread/runs/7552277940?check_suite_focus=true)).
- The "Thread Status TLV" type is `4` which maps to "MLE Response TLV" (uses 4 as type). 
- Before this fix  if the Child Update Response includes a `ResponseTlv`, the first byte of challenge/response bytes is read and treated as status which is then checked against `StatusTlv::kError = 1` to determine whether the child rejected the parent. 
- So if the first byte happens to be `1` then the …
=> [mle] fix incorrect `StatusTlv` when processing Child Update Response

tests/unit/test_routing_manager.cpp
This commit updates `test_routing_manager` unit test and adds a new
set of helper methods to simplify the implementation of test-cases:
- `VerifyOmrPrefixInNetData()` to check OMR prefix in Network Data.
- `VerifyExternalRoutesInNetData()` to check external route prefixes
in Network Data.
- `VerifyPrefixTable()` to check the on-link and route prefixes in
discovered prefix table.
- Different flavors of `SendRouterAdvert()` to send RA with different
PIOs, RIOs, and default route info (in header).
This commit also breaks the test-cases into multiple functions each
covering specific aspect.
=> [test] update `RoutingManager` unit test adding new helper methods

.github/workflows/build.yml
To avoid errors such as this: https://github.com/openthread/openthread/runs/7621940586?check_suite_focus=true
=> [github-actions] remove clang-6,7,8 from build check

etc/docker/environment/Dockerfile
To avoid errors such as this: https://github.com/openthread/openthread/runs/7621948528?check_suite_focus=true
=> [docker] upgrade pip before installing cmake

src/core/common/frame_builder.cpp, src/core/common/frame_builder.hpp, src/core/net/ip6.cpp, src/core/thread/lowpan.cpp, src/core/thread/lowpan.hpp, src/core/thread/mesh_forwarder.cpp, tests/unit/test_frame_builder.cpp, tests/unit/test_lowpan.cpp
**[frame-builder] add `Insert()`, `Remove()` and other helper methods**
This commit adds `Insert()` and `Remove()` methods in `FrameBuilder`.
`Insert` can be used to insert new content in the frame at a given
offset moving any previously written content forward. `Remove()` can
be used to remove previously appended content from the frame moving
any content after the removed bytes backward. This commit also adds
`GetRemainingLength()` to get the remaining length (number of bytes
that can be appended) in the frame buffer, and `SetMaxLength()`. Unit
test `test_frame_builder` is also updated to validate all the newly
added methods.
**[mesh-forwarder] use `FrameBuidler` in `PrepareDataFrame()`**
This commit updates `MeshForwarder::PrepareDataFrame()` to use …
=>  [mesh-forwarder] use `FrameBuidler` in `PrepareDataFrame()`

src/core/BUILD.gn, src/core/Makefile.am, src/core/config/border_agent.h, src/core/config/border_router.h, src/core/config/border_routing.h, src/core/config/netdata_publisher.h, src/core/openthread-core-config.h
This commit adds `border_routing.h` and `border_agent.h` header
files for OT configuration related to Border Routing Manager and
Border Agent (removing the definitions from `border_router.h`).
=> [config] add `border_routing.h` and `border_agent.h`

src/core/thread/lowpan.cpp, src/core/thread/lowpan.hpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp
This commit contains smaller enhancements in `Lowpan` related to
`Context`. It adds a new member variable `mIsValid` to this struct
which indicates whether we have a valid context. It also adds new
methods `FindContextForId()` and `FindContextToCompressAddress()`.
These methods will either retrieve a related context or `Clear()`
it (to indicate that there is no valid context and also set its ID
to zero which is the default used in lowpan compression).
=> [lowpan] update `Context` and add `FindContext()` methods

src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, src/core/thread/lowpan.cpp, src/core/thread/lowpan.hpp, tests/unit/test_ip_address.cpp
**[ip6] add `ApplyPrefix()` to `Ip6::InterfaceIdentifier`**
This commit adds a new method `InterfaceIdentifier::ApplyPrefix()`
which applies a given prefix to an IID. This is applicable only when
the prefix length is longer than 64 bit. In this case, only the bits
in the IID up the prefix length are changed to match the prefix and
the remaining bits are left unchanged. This commit also updates the
unit test to validate the behavior of the new method.
**[lowpan] update `ComputeIid()` and simplify `CompressIid()`**
This commit contains smaller enhancements and fixes in `Lowpan`
related to IID calculation and compression:
- It updates `ComputeIId()` to return `Iid` only
- `ComputeIid()` now uses newly added `ApplyPrefix()` which
ensures the prefix bits …
=> [ip6] add `ApplyPrefix()` to IID & simplify lowpan `ComputeIid()`

tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py
Depends-On: openthread/ot-br-posix#1479
=> [border-agent] refine meshcop service state bitmap checks

src/core/mac/mac_types.hpp, src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/thread/indirect_sender.cpp, src/core/thread/lowpan.cpp, src/core/thread/lowpan.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, tests/unit/test_lowpan.cpp, tests/unit/test_lowpan.hpp
This commit adds a new struct `Mac::Addresses` which represents two
MAC addresses corresponding to source and destination. This type
is then used in `MeshForwarder` and `Lowpan` methods allowing us
to pass both source and destination addresses as one parameter.
=> [mesh-forwarder] add `Mac::Addresses` (src and dst address)

src/core/coap/coap_message.hpp, src/core/common/message.hpp, src/core/config/misc.h
With changes in #7554 the `Metadata` stuct size in `Message` increased,
leading to unsufficient message buffer size when the maximum number
of children is configured, due to the variable size of `ChildMask`.
Furthermore, enabling CoAP Blockwise option also extends the message
buffer size requirements.
This commit documents those cases and makes it clearer
for users how to overcome the possible building issues.
=> [message] document buffer size needs

include/openthread/instance.h, include/openthread/thread.h, src/cli/README.md, src/cli/cli.cpp, src/core/api/thread_api.cpp, src/lib/spinel/spinel.h, src/ncp/ncp_base_mtd.cpp
This commit extends the Thread API to allow a CSL Receiver application
to adjust its CSL parameters depending on the parent capabilities.
Specifically, it might decide to switch to polling operation instead of
CSL syncrhonization when the attached parent does not support CSL Transmitter
role (Thread Version 2) or it advertises poor CSL accuracy or uncertainty.
=> [api] allow CSL receiver to gather parent CSL capabilities

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp
This commit contains smaller enhancements in MLE:
- We use `static const` to define array of TLVs to request.
- Rename the const arrays to `kTlvs`.
- Adds template `AppendTlvRequestTlv()`.
- Adds template `SendDataRequest()`.
=> [mle] helper method appending TLV Request TLV

src/core/thread/mle_router.cpp
---
The overflow issue is very unlikely since "Data Request" message can only contain `Tlv::kNetworkData` (today).
Quick overview:
- We have a fixes array of `tlvs[4]`
- We parse the "TLV Request" TLV from request message and populate `tlvs[]` array
```c++
SuccessOrExit(error = aRxInfo.mMessage.ReadTlvRequestTlv(requestedTlvs));
VerifyOrExit(requestedTlvs.mNumTlvs <= sizeof(tlvs), error = kErrorParse);
memset(tlvs, Tlv::kInvalid, sizeof(tlvs));
memcpy(tlvs, requestedTlvs.mTlvs, requestedTlvs.mNumTlvs);
numTlvs = requestedTlvs.mNumTlvs;
```
- Afterwards, we may add more elements to this array (which may be already full).
=> [mle] add array bound check to avoid overflow in `HandleDataRequest()`

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_tlvs.hpp
This commit contains fixes and enhancements related to processing
of CSL Channel TLV and CSL Clock Accuracy TLV in MLE messages:
- Updates/adds `IsValid()` method to check if TLV is well-formed.
In particular, we check the TLV length to be at least the
expecte length (but can be larger) to allow for future changes
to the TLV format (adding new fields while remaining backward
compatible).
- Ensure to verify that the read TLV is valid before using its
content.
- Fix processing of Accuracy TLV in `HandleChildUpdateResponse()`
(where we could use incorrect values if TLV was not present).
=> [mle] fix processing of CSL TLVs

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, tests/scripts/thread-cert/v1_2_test_csl_transmission.py
This commit updates how unspecified CSL channel is conveyed in MLE
messages. Special value of zero in CSL Channel TLV is used to
indicate that the CSL channel is unspecified. The exclusion of the
TLV keeps the CSL channel as before (no change to the previously
set CSL channel).
-----
- This PR contains commit from https://github.com/openthread/openthread/pull/8004.
- This is related to [SPEC-1095](https://threadgroup.atlassian.net/browse/SPEC-1095). 
- FYI: @Irving-cl
=> [csl] update CSL Channel TLV process to allow for unspecified case

tools/harness-thci/OpenThread.py
https://github.com/openthread/openthread/pull/7826 removed BBR related configurations for Thread 1.3 BRs.
However, when running 1.2 test case for a Thread 1.3 BR, these configurations are still necessary.
This commit restore BBR dataset configurations for 1.2 BR_1/BR_2 roles.
=> [thci] restore BBR config for 1.2 BR_1/BR_2 roles

src/core/common/array.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
This commit adds `Mle::TlvList` type which represents a list of MLE
TLV types. It provides helper methods to `Add()` TLVs to the list
ensuring that any TLV type is included only once. The `TlvList` is
used when parsing "TLV Request TLV" or preparing which TLVs to
include in an MLE message.
---
This PR contains the commit from https://github.com/openthread/openthread/pull/8001.
=> [mle] add `TlvList` to track list of TLV types

src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, tests/unit/test_ip_address.cpp
This commit moves more complex methods of `Ip6::Prefix` class to the
`cpp` file. It also simplifies the `IsLinkLocal()` implementation. It
also updates unit test `test_ip_address` to validate `IsLinkLocal()`,
`IsMulticast()`, and `IsUniqueLocal()` methods.
=> [ip6-address] move more complex `Prefix` methods to `cpp` file

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit updates `IsValidOmrPrefix()` to use `IsUniqeLocal()`
method of `Ip6::Prefix`. This relaxes the check to allow any ULA
prefix and not necessarily with 64 bits prefix length.
=> [routing-manager] use `Ip6::Prefix::IsUniqeLocal()` to check OMR prefix

Android.mk, include/openthread/border_routing.h, include/openthread/instance.h, include/openthread/ip6.h, include/openthread/nat64.h, include/openthread/platform/infra_if.h, script/test, src/cli/cli.cpp, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/api/border_routing_api.cpp, src/core/api/ip6_api.cpp, src/core/api/nat64_api.cpp, src/core/border_router/infra_if.cpp, src/core/border_router/infra_if.hpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/net/ip6_address.hpp, src/core/thread/network_data_leader.cpp, src/posix/Makefile.am, src/posix/platform/CMakeLists.txt, src/posix/platform/infra_if.cpp, src/posix/platform/infra_if.hpp, tests/scripts/thread-cert/border_router/nat64/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/nat64/test_single_border_router.py, tests/scripts/thread-cert/border_router/nat64/test_with_infrastructure_prefix.py, tests/scripts/thread-cert/node.py, tests/unit/test_platform.cpp
This commit fetches the NAT64 prefix on infrastructure interface and advertise it to Network Data at medium preference.
- Use `getaddrinfo_a()` function to asynchronously lookup the ipv6 address of the special domain `ipv4only.arpa`. The infrastructure NAT64 prefix is extracted from the domain answer.
- `mInfraIfNat64PrefixStaleTimer` is scheduled to monitor the presence and change of infrastructure NAT64 prefix.  
- `EvaluateNat64Prefix` evaluates whether to advertise the infrastructure prefix or the local ULA prefix or neither. When there is a new infrastructure prefix, it will withdraw the legacy one and add the new one. When the infrastructure prefix no longer exists, it will withdraw the legacy one and add the local ULA prefix. When the infrastructure prefix presents again, it will …
=> [nat64] fetch NAT64 prefix from infrastructure interface and advertise it to netdata

.github/workflows/build.yml, src/core/meshcop/dtls.cpp, src/core/meshcop/dtls.hpp
- Updated the following deprecated APIs with their respective alternatives -
- `mbedtls_ssl_conf_min_version` => `mbedtls_ssl_conf_min_tls_version`
- `mbedtls_ssl_conf_max_version` => `mbedtls_ssl_conf_min_tls_version`
- `mbedtls_ssl_conf_sig_hashes` => `mbedtls_ssl_conf_sig_algs`
- Updated the parameter data-type for `mbedtls_ssl_conf_sig_algs` (list of allowed signature algorithms) from `int` to `uint16_t`
- Added macros for backward compatibility
=> [meshcop] update deprecated functions for Mbed TLS  `v3.2.1`

src/core/BUILD.gn, src/core/Makefile.am, src/core/backbone_router/bbr_manager.cpp, src/core/backbone_router/ndproxy_table.cpp, src/core/border_router/routing_manager.cpp, src/core/common/data.hpp, src/core/common/log.cpp, src/core/common/min_max.hpp, src/core/mac/data_poll_sender.cpp, src/core/mac/sub_mac.cpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/net/dns_dso.cpp, src/core/net/dns_dso.hpp, src/core/net/dns_types.cpp, src/core/net/ip6_address.cpp, src/core/net/srp_client.cpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, src/core/net/tcp6.cpp, src/core/thread/link_quality.cpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle.cpp, src/core/utils/history_tracker.cpp, src/core/utils/ping_sender.cpp, tests/unit/test_serial_number.cpp
This commit adds generic helper functions:
- `Min()` to get the minimum of two values,
- `Max()` to get the maximum of two values, and
- `Clamp()` to clamp a value to a given closed range from a minimum
up to a maximum value. It also adds functions
- `ClampToUint8()` and `ClampToUint16()` to clamp a `uint` value to
a smaller bit-size (`uint8_t` or `uint16_t`) range.
=> [core] add new generic `Min()`, `Max()` and `Clamp()` functions

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit adds a new struct `RaInfo` in `RoutingManager` which
tracks info about emitted RA messages: Number of RAs sent, last tx
time, header to use and whether the header is discovered from
receiving RAs from the host itself. This helps encapsulate all
related info in one data structure.
=> [routing-manager] add `RaInfo` tracking all RA related info

src/core/border_router/routing_manager.cpp
This commit updates `IsValidOmrPrefix()` to accept any ULA/GUA
prefix with 64-bit length as OMR prefix.
=> [routing-manager] accept any ULA/GUA with 64-bit len as OMR prefix

src/core/api/thread_api.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/topology.cpp
This commit moves the code for getting the parent info from the
`thread_api.cpp` to `Mle` class `GetParentInfo()` method. It also
updates the `Router::Info::SetFrom()` to populate the `mVersion` and
the newly added CSL related fields. This allows us to re-use the
same code for both router or parent info.
=> [mle] add method to get parent info

include/openthread/instance.h, include/openthread/thread.h, src/cli/cli.cpp, src/core/api/thread_api.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit adds `otThreadSearchForBetterParent()` to start the
process on a child to search for a better parent while staying
attached to its current parent. This commit also adds a related CLI
command `parent search`.
----
This can be useful for testing (e.g. [SPEC-1005](https://threadgroup.atlassian.net/browse/SPEC-1005)).
Also useful if next layer code want to control when to trigger the search.
=> [mle] new API to trigger search for better parent

tools/harness-thci/OpenThread_BR.py
Some mDNS implementations do not respond to mDNS queries sent by `dig`.
=> [thci] send mdns queries without `dig`

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit increase the routing policy evaluation jitter from 1 second to 2~4 seconds to avoid adding on-link prefix when the AIL GUA prefix is unavailable for a very short duration (usually during GUA prefix renewing).
=> [routing-manager] increase routing policy evaluation jitters

src/core/thread/mle_types.hpp
After BBR restarting, in order to receive the packets from multicast group, the devices, which have registered multicast group addresses to that BBR, needs to re-register these groups. In current logic, the default max reregisteration delay is too large(1200 seconds).
=> [bbr] reduce the default reregistration delay

src/core/utils/slaac_address.cpp
This commit updates `Slaac` module to only allow prefixes with
64-bit length.
----
Related to 
- discussion in https://github.com/openthread/openthread/issues/8010 
- and [RFC 4944 Section 6](https://www.rfc-editor.org/rfc/rfc4944#section-6).
=> [slaac] only allow SLAAC for prefixes with 64-bit length

src/core/border_router/routing_manager.cpp
Fixes issue introduced with merging #7982 
```
../../third_party/openthread/repo/src/core/border_router/routing_manager.cpp:261:44: error: 'kRoutingPolicyEvaluationJitter' was not declared in this scope
StartRoutingPolicyEvaluationJitter(kRoutingPolicyEvaluationJitter);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```
=> [routing-manager] fix call to `StartRoutingPolicyEvaluationJitter()`

src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit adds `Mle::ParentSearch` class which encapsulates all
definitions (variables, constants, and methods) related to "Parent
Search" feature.
=> [mle] define `ParentSearch` class
