openthread/openthread

src/core/net/ip6.cpp
This commit adds a smaller enhancement in `Ip6::HandlePayload()`. If
support for TCP `OPENTHREAD_CONFIG_TCP_ENABLE` is not enabled, we
exits early from this method before potentially creating a clone of
the message (to free later).
=> [ip6] update `HandlePayload()` (avoid msg clone if not needed)

src/core/BUILD.gn, src/core/Makefile.am, src/core/api/thread_api.cpp, src/core/common/settings.hpp, src/core/thread/child_table.cpp, src/core/thread/discover_scanner.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_types.hpp, src/core/thread/topology.cpp, src/core/thread/topology.hpp, src/core/thread/version.hpp
This commit adds `thread/version.hpp` which defile Thread Version
constants. It also changes the `mVersion` in `Neighbor` class to
use `uint16_t` to track the version. This help harmonize it with
the MLE Version TLV and and version in `Settings`. Due to memory
alignment of existing member variables the change (from `u8` to
`u16`) does not increase the memory requirement for child or router
table.
=> [thread] add version consts & use `uint16_t` for `Neighbor::mVersion`

src/core/mac/mac.hpp, src/core/mac/mac_types.hpp, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/radio/radio.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/topology.cpp, src/core/thread/topology.hpp
The CSL accuracy is represented as two parameters: clock accuracy in
ppm, and uncertainty in units of 10 microseconds. These two parameters
are often used together. This commit adds a new class `CslAccuracy`
encapsulating both. This new type is used in `Mac` and `Mle` methods
allowing us to pass both in one object.
This commit also adds `Mle::RxMessage::ReadCslClockAccuracyTlv()` to
read and parse the CSL Accuracy TLV value from a given received MLE
message.
=> [csl] add `CslAccuracy` type

src/core/thread/link_metrics.cpp
This commit updates `LinkMetrics::AppendReport()` to ensure
the `values.mPduCountValue` (which is a `uint32_t`) is stored in
the host MCU encoding and not in big-endian encoding.
This was originally added in #7046 as a fix (basically saving the
value in local variable in the encoding we expect to later include
in the Report TLV), however #8006 updates the `ReportSubTlv` methods
to do the encoding change in the `Get/SetMetricsValue32()` (similar
to other OT `Tlv` definitions).
----
Adding a note on the change. There are 3 places in https://github.com/openthread/openthread/pull/7046 where `HostSwap32()` was added:
- The first two are now removed in new PR.
- The last one is when we read the value directly from message which is fine/correct.
```c++
case TypeIdFlags::kPdu: …
```
=> [link-metrics] fix the endian-ness of `mPduCountValue`

src/core/net/ip6.cpp, src/core/net/ip6.hpp
This PR contains two smaller enhancements in `Ip6`:
**[ip6] remove extra param from `Ip6::HandleExtensionHeaders()`**
This commit updates `Ip6::HandleExtensionHeaders()` removing
`aIsOutbound` input and instead using `(aNetif == nullptr)` to
determine this.
**[ip6] simplify `Ip6::HandleDatagram()` - remove `netif` local var**
This commit updates `Ip6::HandleDatagram()` and removes the local
`netif` variable and directly uses `ThreadNetif` instead. Note that
the input parameter `aNetif` is either `nullptr` or points to
`ThreadNetif`, and in both cases the local variable `netif` will be
set to point to `ThreadNetif`.
----
Kept the commits separate to help with review of the change.
=> [ip6] smaller enhancements

src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/topology.cpp, src/core/thread/topology.hpp
This commit adds `Parent` class as a sub-class of `Router` and moves
the CSL accuracy definitions in `Parent` class (from `Router`) since
we need to track CSL info only for the parent and not other entries
in the router table. This helps reduce the memory/RAM used by router
table.
=> [mle] add `Parent` class (tracking CSL accuracy info)

src/posix/platform/multicast_routing.cpp, tests/scripts/thread-cert/backbone/test_mlr_multicast_routing_across_thread_pans.py
According to Thread Spec, PBBR should not forward a multicast packet from Thread interface to Backbone interface when the source address is Mesh-Local.
=> [multicast-routing] don't add MFC entries using mesh local as the source address

src/core/api/ip6_api.cpp, src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp
This commit adds a new enum `Ip6::MessageOrigin` which indicates the
origin of the message: From Thread Netif or from host. In case the
message is originating from host, it also indicates whether or not it
is allowed to pass back the message to the host.
----
The new `MessageOrigin` replaces two inputs: `aNetif` and `aFromHost`:
```
- kFromThreadNetif          --> aNetif = &ThreadNetif, aFromHost = false
- kFromHostDisallowLoopBack --> aNetif = nullptr,      aFromHost = true
- kFromHostAllowLoopBack    --> aNetif = nullptr,      aFromHost = false
```
The combination of `aNetif = &ThreadNetif` and `aFromHost = true` is not possible/used.
For example `if (aNetif != nullptr)` becomes `if (aOrigin == kFromThreadNetif)`
This PR currently contains commit from …
=> [ip6] add `MessageOrigin` to indicate origin or IPv6 message

src/core/thread/link_metrics.cpp, src/core/thread/link_metrics.hpp
This commit addresses integer conversion warnings in `LinkMetrics`.
In particular it updates `ReadTypeIdFlagsFromMessage()` to use
`uint16_t` as offset value (instead of `uint8_t`).
----
Background:
- I noticed that link-metrics does not seem to be enabled/covered in CI `build` workflow 
(e.g. in `check-simulation-build-autotools`).
- Enabling it seems to result in many [errors/warnings related to int conversion](https://github.com/abtink/openthread/runs/7907974276?check_suite_focus=true) (under `clang`)
- This PR addresses some of the warnings.
- There are other cases (e.g., related to metric value conversions "RSSI from [-130, 0] to [0, 255]") which probably want to address separately.
=> [link-metrics] fix integer conversions & use of `u8` for offset

include/openthread/instance.h, include/openthread/tcp.h, src/core/net/tcp6.cpp, third_party/tcplp/lib/bitmap.c, third_party/tcplp/lib/bitmap.h, third_party/tcplp/lib/cbuf.c, third_party/tcplp/lib/cbuf.h
This pull requests the `otTcpReceiveContiguify` function in the OpenThread TCP API.
This function reorganizes data within the TCP receive buffer so that it is contiguous in memory. The purpose of this function was to ease programming for applications where the cost of reorganizing data within the receive buffer is acceptable.
The first commit modifies the circular buffering used by TCPlp to make it more memory efficient. The original implementation maintained the indices in to the array in such a way that it could not use all of the array at once; there always had to be one spare byte. This commit removes that restriction.
The second commit actually implements the `otTcpReceiveContiguify`. The algorithm itself can be understood as array rotation; the implementation runs in linear time in …
=> [tcp] implement  otTcpReceiveContiguify

tests/scripts/thread-cert/border_router/nat64/test_multi_border_routers.py
This commit extend the wait time after disabling border routing and a new case is added to verify that the netdata is stable again.
=> [nat64] extend wait time between test cases and verify netdata stabilized

src/core/thread/link_metrics.cpp, src/core/thread/link_metrics.hpp
This commit simplifies the `LinkMetrics::AddReport()` method so that
when preparing the MLE Link Metrics Report TLV (and its sub-TLVs) we
determine the TLV length after all sub-TLVs are appended to the
message from the number of written bytes in the message (difference
between `aMessage.GetLength()` and initial offset of the TLV). This
allows to simplify methods `AppendReportSubTlvToMessage()` and
`AppendStatusSubTlvToMessage()` as well.
=> [link-metrics] simplify `AddReport()`

src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/router_table.cpp, src/core/thread/topology.cpp, src/core/thread/topology.hpp
This commits add `GetTwoWayLinkQuality()` method to `Router` class
which returns the minimum of router's Link Quality In and Out
values. It also adds `GetLinkQualityIn()` to `Neighbor`. These
are used in `Mle` and `MeshForwarder`.
=> [topology] add `Router::GetTwoWayLinkQuality()` method

src/posix/platform/multicast_routing.cpp, tests/scripts/thread-cert/backbone/test_mlr_multicast_routing_across_thread_pans.py
According to the Spec, egress packets from LLA should not be forwarded. Linux kernel doesn't automatically block such forwardings so that we need to check this before adding the MFC entry.
=> [multicast-routing] block egress multicast packets from LLA

src/core/thread/link_metrics.cpp, src/core/thread/link_metrics.hpp, src/core/thread/link_metrics_tlvs.hpp
Status sub-TLV has a single `uint8_t` status value so we can use
declare it as `UintTlvInfo<SubTlv::kStatus, uint8_t>` and then use
helper `Append<StatusSubTlv>` and `Read<StatusSubTlv>` to append
and read it.
---
~~This PR contains commit from https://github.com/openthread/openthread/pull/8042.~~
=> [link-metrics] define `StatusSubTlv` to simplify appending/parsing it

src/core/thread/mesh_forwarder.cpp
This commit fixes random 2015 frame version issue while attaching to
REED. the problem was caused by unconditionally casting Router structure
to Child structure and making out of original structure memory access.
=> [mesh-forwarder] fix random ieee frame version 2015 while attaching

src/posix/platform/CMakeLists.txt, src/posix/platform/infra_if.cpp, src/posix/platform/openthread-posix-config.h
This commit is to mitigate the OTBR compile error in [ot-br-posix/tests/scripts/openwrt](https://github.com/openthread/ot-br-posix/blob/main/tests/scripts/openwrt). This test uses the `openwrtorg/sdk` docker, which depends on the `musl` toolchain and lacks the `libanl` library. We can re-enable it for OpenWRT if `libanl` can be linked in the sdk (e.g. import the library, or build an sdk with `glibc`).
The ot-br-posix PR is: https://github.com/openthread/ot-br-posix/pull/1512.
=> [nat64] disable discovering NAT64 AIL prefix for OpenWRT

src/core/thread/link_metrics.cpp, src/core/thread/link_metrics_tlvs.hpp, src/core/thread/mle.cpp
This commit updates `LinkMetrics::HandleReport()` method:
- Fixes issue where `Status` sub-TLV would not be read.
- Uses `Tlv` helper methods to read the sub-TLVs.
- Reads `ReportSubTlv` directly from message and uses its methods
to get the metrics values.
- Fixes issue where we would not skip over unknown sub-TLVs
correctly.
---
~~This PR contains commits from https://github.com/openthread/openthread/pull/8051 and https://github.com/openthread/openthread/pull/8042. Please check the last commit.~~
=> [link-metrics] simplify `HandleReport()`

src/core/api/link_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_links.hpp, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/radio/radio.hpp, src/core/thread/link_metrics.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp
This commit adds a helper method in `Mac` to compute link margin
from a given received signal strength (in dBm) using the radio
noise floor.
=> [mac] add `ComputeLinkMargin()`

tools/harness-thci/OpenThread.py
`setActiveDataset` and `setCommisionerMode` have been removed from
the `iThci` abstract class in the latest harness release.
=> [thci] remove unused methods

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/common/locator_getters.hpp, src/core/common/notifier.cpp, src/core/common/notifier.hpp, src/core/common/tasklet.hpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/net/tcp6.cpp, src/core/net/tcp6.hpp, src/core/radio/trel_interface.cpp, src/core/radio/trel_interface.hpp, src/core/radio/trel_link.cpp, src/core/radio/trel_link.hpp, src/core/thread/dua_manager.cpp, src/core/thread/dua_manager.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/network_data_notifier.cpp, src/core/thread/network_data_notifier.hpp
This class adds a template sub-class of `Tasklet` which allows
us to directly specify an `Owner` of tasklet along with handler
callback as a member method of `Owner`. This helps simplify the
use of `Tasklet` in core module.
---
This change helps simplify how we use `Tasklet`. 
- Today we need to define a `static` member function (e.g. `HandleTasklet`) to use as callback of `Tasklet`.
- Then from this callback, we call a method on the owner of `Tasklet` to process/handle it.
- With the new `template` model, there is no need to define the `static` member function and we can directly specify the method.
- And the `template` definition takes care of defining a function callback and hooking it to the method for us.
We should be able to do the same for `Timer` classes (can do in a follow-up …
=> [tasklet] add template `TaskletIn` to simplify handler functions

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp
This commit adds `ParentCandidate` in `Mle` class (as a sub-class of
`Parent`) and moves all member properties related to parent candidate
to this new class.
=> [mle] add `ParentCandidate` class

src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle_router.cpp, src/core/thread/neighbor_table.cpp
This commit adds a check `Get<ChildTable>().Contains(Neighbor &)`
to ensure that the neighbor is from the child table before casting
the neighbor entry to `Child`. This adds safety and protection against
potential corner-case where we have a neighbor entry which is
`Parent` or `ParentCandidate` that is a REED.
---
- This is follow up to https://github.com/openthread/openthread/pull/8067 
- And related to [comment](https://github.com/openthread/openthread/pull/8067#discussion_r952893483). 
- Thanks to @canisLupus1313 for finding this issue. 
- Went through all other places where we cast `Neighbor` to `Child`.
- None seem critical and should not cause any bugs/issues but safer to add a check .
=> [child-table] check neighbor is in `ChildTable` before cast as `Child`

src/core/common/num_utils.hpp, src/core/thread/link_metrics.cpp, src/core/thread/link_metrics.hpp, tests/unit/test_link_quality.cpp, tests/unit/test_serial_number.cpp
This commit updates the scaling of the link margin and RSSI metrics.
The metric values are scaled when appended in the message (in a
Report sub-TLV) or when they are read back from received message. The
stored value in `MetricsValues` are changed to be always the actual
metric value (not the scaled value). This ensures that the value are
stored in proper int type (e.g., RSSI is `int8` vs the scaled value
which is `[0,255]`). Methods are added to perform the scaling which
now rounds to closest integer ensuring the reverse scaling gives back
the original value. Unit test is added to validate the scaling
methods.
=> [link-metrics] update the scaling of link margin and RSSI metrics

src/core/border_router/routing_manager.cpp
This commit updates the `RoutingManager` such that if we see that that
current favored discovered on-link prefix (from processed RAs from
other routers) matches our local on-link prefix, we start/continue
advertising it as well. The local on-link prefix is derived from
extended PAN ID and therefore is the same for all BRs on the same
Thread mesh. Having multiple BRs advertise the same on-link prefix
adds redundancy (in case one BR goes offline).
=> [routing-manager] advert local on-link prefix if same as discovered prefix

src/core/net/srp_server.cpp
This commit updates `ProcessServiceDiscoveryInstructions()` method
to use `Dns::Name::IsSubDomainOf()` to validate the relation between
service instance name and the base service name.
---
Background:
- See https://github.com/openthread/ot-br-posix/issues/1425
- Using `IsSubDomainOf()` since it will check the label boundary
Fixes https://github.com/openthread/openthread/issues/8037
Fixes https://github.com/openthread/ot-br-posix/issues/1425
=> [srp-server] update validation of instance and service names

src/core/thread/link_metrics.cpp, src/core/thread/link_metrics.hpp, src/core/thread/link_metrics_tlvs.hpp, src/core/thread/link_metrics_types.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit adds `FwdProbingRegSubTlv` which is used to simplify
`SendMgmtRequestForwardTrackingSeries()` implementation. Similarly
`EnhAckConfigSubTlv` is updated and used to simplify method
`SendMgmtRequestEnhAckProbing()`.
=> [link-metrics] simplify sending MLE Mgmt Request

examples/platforms/utils/link_metrics.cpp, src/core/api/link_api.cpp, src/core/mac/mac.cpp, src/core/thread/link_quality.cpp, src/core/thread/link_quality.hpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp
This commit simplifies the helper functions that convert between
link margin, link quality and RSS (replacing the `static` methods
in `LinkQualityInfo`).
=> [link-quality] helper fn to convert link margin, link quality, RSS

src/core/thread/link_metrics.cpp
---
- Unlike `Tlv::FindTlv()` methods, `Tlv::ReadTlv()` only reads the TLV value (not the full TLV).
- May be safer to rename this to `ReadTlvValue()`.
=> [link-metrics] fix reading of Report sub-tlv from message

src/core/api/thread_api.cpp, src/core/common/message.hpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_links.hpp, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/meshcop/joiner.cpp, src/core/radio/radio.hpp, src/core/radio/trel_link.cpp, src/core/thread/link_quality.cpp, src/core/thread/link_quality.hpp, src/core/thread/mle.cpp, src/core/utils/channel_monitor.cpp, src/core/utils/history_tracker.cpp, src/core/utils/history_tracker.hpp, src/core/utils/jam_detector.cpp, tests/unit/test_link_quality.cpp
This commit harmonizes the constant used to indicate an "Invalid RSSI
value". It defines `Radio::kInvalidRssi` which is then used in all
core modules replacing `OT_RADIO_INVALID_RSSI` and similar constants
in `SubMac/Mac`.
=> [radio] define `Radio::kInvalidRssi` constant

src/core/common/tlvs.cpp, src/core/common/tlvs.hpp, src/core/thread/discover_scanner.cpp
This commit renames the method from `ReadTlv()` to `ReadTlvValue()`
to emphasize that it read the TLV value only (unlike `FindTlv()` helper
methods which find and read the whole TLV).
----
Follow up from https://github.com/openthread/openthread/pull/8099 and contains its commit.
=> [tlvs] rename method to `ReadTlvValue()` from `ReadTlv()`

tests/scripts/thread-cert/net_crypto.py
This commit imports `Crypto` module only when it's used.
This helps thread-cert tests that do not use message factory to run without having to install `Crypto` module.
=> [thread-cert] import `Crypto` on demand

src/core/border_router/routing_manager.hpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
This commit updates `Mle::DetachGracefully()` to stop Border Router
`RoutingManager`. This ensures that BR will have the chance to send
a final Router Advertisement message desecrating/removing its
previously advertised on-link or route prefixes.
=> [mle] update `DetachGracefully()` to stop BR routing manager

src/cli/cli.cpp, src/cli/cli.hpp, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/v1_2_LowPower_7_2_01_ForwardTrackingSeries.py, tests/scripts/thread-cert/v1_2_test_single_probe.py
This commit updates CLI `linkmetrics query` command to allow it
to be used in blocking mode (wait for response to query). This
is then used in different tests to validate the `LinkMetrics`
module behavior. In particular, `v1_2_test_single_probe` and
`v1_2_LowPower_7_2_01_ForwardTrackingSeries` are updated to
validate that the received query report message is correctly
parsed.
=> [link-metrics] add blocking CLI query command and enhance tests

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit renames the variable representing the NAT64 prefix
which is published in Network Data to `mPublishedNat64Prefix`.
---
This change has no code/logic change here. Just a rename to make the used terms consistent:
- Let's use the term "advertise" for infra if side (entries we include in emitted RA messages),
-  e.g. `mAdvertisedPrefixes` (on-mesh prefixes advertised as RIO in the last sent RA message)
- On Thread side and for entries in Network Data, we can use "publish" or "add":
-  e.g., we have `PublishExternalRoute()`.
=> [routing-manager] rename published NAT64 prefix

src/core/thread/discover_scanner.cpp, src/core/thread/discover_scanner.hpp
This commit updates `DiscoverScanner` so when scan operation is
finished it uses a `Tasklet` to clear the state and invoke the
callback. This allows users to safely call OT APIs from the
callback.
---
Should resolve https://github.com/openthread/openthread/issues/8110
=> [discover-scanner] invoke handler when scan is done from a tasklet

src/core/api/link_metrics_api.cpp, src/core/thread/link_metrics.cpp, src/core/thread/link_metrics.hpp, src/core/thread/link_metrics_tlvs.hpp, src/core/thread/link_metrics_types.cpp, src/core/thread/link_metrics_types.hpp
This commit updates `SeriesFlags` definition to map to the public
`otLinkMetricsSeriesFlags` struct and adds helper methods to convert
to or set it from a `uint8_t` flags bitmask which is read or written
in the TLVs.
=> [link-metrics] simplify processing of `SeriesFlags`

include/openthread/instance.h, include/openthread/srp_client.h, src/core/net/srp_client.hpp
This commit updates `otSrpClientEnableAutoStartMode` documentation
to describe how the preferred server is determined from Network Data
entries (different Network Data entry categories, their order of
preference, and how to handle when there are multiple options within
the same category).
=> [srp-client] update document about selected preferred server

tests/scripts/expect/cli-tcp.exp
Make sure `otTcpStopListening` is verified.
=> [tcp] extend test to cover `otTcpStopListening` API

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, tests/unit/test_routing_manager.cpp
This commit updates `RoutingManager` to deprecate a previously
advertised local on-link prefix when extended PAN ID gets changed.
The local on-link prefix is derived from Thread network extended PAN
ID.  On extended PAN ID change, we continue to include the the old
prefix (if it was being advertised) in the emitted RAs as PIO (with
zero preferred lifetime) and continue to publish it in Network Data
up to its lifetime. This ensures that any device on infrastructure
link side that may be using an IPv6 address based on this old prefix
can continue to communicate with the Thread mesh devices.
This commit also adds a test-case in `test_routing_manager` to
validate the behavior of the newly added mechanism when ext PAN ID
changes while the local on-link is being advertised and also while
it was …
=> [routing-manager] deprecate previous local on-link prefix on xpanid change

src/core/config/srp_client.h
This ensures that `OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE`  is 
defined in `config/srp_client.h` and can be safely used for defining `OPENTHREAD_CONFIG_SRP_CLIENT_BUFFERS_MAX_HOST_ADDRESSES`.
----
This should help address errors such as 
- https://github.com/openthread/openthread/actions/runs/3029810959/jobs/4875470037
=> [config] include `misc.h` in `srp_client.h`

.github/workflows/posix.yml, third_party/tcplp/lib/test/Makefile, third_party/tcplp/lib/test/test_all.c
In his review for Pull Request #7634, @abtink suggested that I add a test case for the contiguify behavior. This pull request includes some ad-hoc tests I wrote to verify that functionality. I'm very open to suggestions to integrate this more carefully into the rest of OpenThread's testing infrastructure.
=> [tcplp] add test for contiguify functionality

src/core/thread/link_metrics.cpp, src/core/thread/link_metrics.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit simplifies the preparation of MLE Data Request message
which include a Link Metrics Query TLV and its sub-TLVs.
=> [link-metrics] simplify preparation of MLE Data Request

examples/apps/cli/main.c, examples/platforms/simulation/platform-simulation.h, examples/platforms/simulation/radio.c, examples/platforms/simulation/virtual_time/platform-sim.c, include/openthread/cli.h, include/openthread/instance.h, src/cli/cli.cpp, src/posix/main.c, src/posix/platform/virtual_time.cpp, tools/harness-simulation/harness/Thread_Harness/Sniffer/SimSniffer.py, tools/harness-simulation/harness/Thread_Harness/THCI/OpenThread_BR_Sim.py, tools/harness-simulation/harness/Thread_Harness/THCI/OpenThread_Sim.py, tools/harness-simulation/posix/launch_testbed.py, tools/harness-simulation/posix/simulation.conf, tools/harness-simulation/posix/sniffer_sim/sniffer.py, tools/harness-thci/OpenThread.py
This commit adds support for RF enclosure simulation. It can pass *Leader 9.2.9*, *Router 9.2.9* and *Router 9.2.10* in *Thread Test Harness v56.0* now.
=> [harness-simulation] add support for RF enclosure simulation

examples/platforms/zephyr/CMakeLists.txt, examples/platforms/zephyr/README.md, zephyr/module.yml
This commit adds CmakeLists and west config in order to be able to directly integrate the openthread with zephyr build system.
=> [cmake] add files allowing direct integration to Zephyr's west

tools/harness-thci/OpenThread_BR.py
This commit fixes the bug that `mdns_query` inserts `ip6tables` rules in an incorrect order.
It also uses `ip6tables -F INPUT` to flush the `INPUT` chain after mDNS query is done.
=> [thci] fix `mdns_query` incorrect `ip6tables` rules

src/core/meshcop/dtls.cpp
This commit fixes two DTLS session issues on Posix:
- Fix the issue that UDP connect would cause the kernel socket to bind to an address that might be different from the address used by the Commissioner.
- Set the socket address to avoid kernel selecting an incorrect source address.
=> [dtls] fix DTLS connection issues

tools/harness-thci/OpenThread.py
This commit fixes `powerDown` to wait for connection reset after issuing `reset` command.
=> [thci] wait for connection reset in `powerDown`

src/core/border_router/infra_if.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit adds `Nat64PrefixManager` class in `RoutingManager` which
contains the NAT64 related logic including generation of local NAT64
prefix, discovery of infra interface prefix, maintaining the
discovered prefix lifetime, and selection of the NAT64 prefix to
publish in Network Data. This class encapsulates all variables and
methods related to NAT64.
=> [routing-manager] add `Nat64PrefixManager` nested class.

src/core/ftd.cmake, src/core/mtd.cmake, tests/unit/CMakeLists.txt, third_party/tcplp/CMakeLists.txt
This commit adds separate `tpclp-ftd` and `tcplp-mtd` libraries. 
Each library is then `target_link_libraries()` with the related 
`openthread-ftd/mtd`. This should help avoid situation where both
`openthread-ftd` and `openthread-mtd` are included as dependency
and linked and address linker failures under certain versions of 
`clang`.
-----
This is related to https://github.com/openthread/openthread/issues/8174
=> [cmake] add separate `tcplp` libraries for `ftd` and `mtd`

.github/workflows/toranj.yml
This commit adds a new case under GitHub `toranj.yml` workflow to 
build and run all unit test using the `toranj` OT configuration.
=> [gh-action] add new case to run unit test with `toranj` config

include/openthread/instance.h, include/openthread/srp_server.h, src/cli/cli_srp_server.cpp, src/cli/cli_srp_server.hpp, src/core/api/srp_server_api.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, tests/unit/test_routing_manager.cpp
This commit adds new APIs and mechanisms to support `AutoEnableMode`
in SRP server. This mode allows us to delegate the control of SRP
server (when it is enabled or disabled) to the Border Routing
Manager.
Under this mode, SRP sever is auto-enabled after `RoutingManager` is
done with the initial prefix and route setup, i.e., when the OMR and
on-link prefixes are determined, advertised in the emitted Router
Advert message on infrastructure side and published in the Thread
Network Data. This ensures that bi-directional connectivity is set up
before allowing service registration and discovery to start. The SRP
server is auto-disabled when BR is stopped, for example, when the
infrastructure network interface is brought down or when the BR gets
detached.
This commit also adds CLI commands for …
=> [srp-server] add `AutoEnableMode` to give control to BR

examples/apps/cli/main.c, examples/apps/ncp/main.c
This will allow platforms to define their own `otPlatCalloc` and `otPlatFree` functions which may not map directly to `calloc()` and `free()`
See https://github.com/SiliconLabs/ot-efr32/blob/main/src/src/memory.c#L37-L45 for example
=> [examples] make built-in otPlatCalloc and otPlatFree definitions weak

src/core/border_router/routing_manager.cpp
This commit fixes `EvaluateOnLinkPrefix()` to use local on-link 
prefix (instead of OMR prefix).
----
Marked as P3 since it does not seem to be critical (worse-case we keep adv
the local on-link prefix and won't deprecate it).
It is interesting that none of our CI tests detected this. I guess/think in our tests the 
discovered on-link prefix is often smaller than both local OMR and  local on-link 
prefix. Should later consider adding a test case to maybe check this specific 
situation.
=> [routing-manager] fix prefix comparison in `EvaluateOnLinkPrefix()`

src/core/border_router/routing_manager.cpp
This commit updates `IsReceivedRouterAdvertFromManager()` which checks
if a received RA message was prepared by the `RoutingManager module
itself to allow deprecating PIOs in the RA message. These will handle
the case when old on-link prefix(es) (e.g., on extended PAN ID change)
are being deprecated.
=> [routing-manager] allow old deprecating PIOs when checking RA is from router

src/core/border_router/routing_manager.cpp, tests/unit/test_routing_manager.cpp
This commit updates `RoutingManager` to ensure to unpublish the old
local on-link prefix being deprecated on ext PAN ID change if the ext
PAN ID happens to change again before the previous deprecating prefix
is expired. Note that the code supports retaining one old deprecating
prefix entry since back-to-back ext pan ID change is not expected as
a typical use-case. This commit also updates `test_routing_manager`
to cover and test this scenario.
=> [routing-manager] remove old deprecating prefix on multiple xpanid change

src/core/backbone_router/ndproxy_table.hpp, src/core/border_router/routing_manager.hpp, src/core/common/clearable.hpp, src/core/common/message.hpp, src/core/common/settings.hpp, src/core/net/ip6.hpp, src/core/net/nd6.hpp, src/core/net/srp_client.hpp
This commit updates `Clearable<Type>::Clear()` method to perform `static_cast<Type *>(this)`. This ensures CRTP-style use and also allows the `Clearable` to be used for types that may not be a standard layout type (and/or more generally in cases where empty base optimization may not be applied).
=> [clearable] update `Clearable` to ensure CRTP-style use

src/core/common/equatable.hpp
This commit updates `Equatable<Type>` to ensure CRTP-style use.
=> [equatable] update `Equatable` to ensure CRTP-style use

examples/apps/cli/main.c
This commit adds the usage of the CLI command "nodeidfilter". This command is supposed to only be run via THCI.
=> [harness-simulation] add the usage of the CLI command `nodeidfilter`

src/posix/platform/CMakeLists.txt
We have to add the `OPENTHREAD_POSIX_CONFIG_DAEMON_ENABLE` definition
to `ot-config` because openthread core libraries will set config file to "openthrad-core-posix-config.h"
which depends on `OPENTHREAD_POSIX_CONFIG_DAEMON_ENABLE` to correctly enable
PLATFORM_NETIF and PLATFORM_UDP features. Otherwise, openthread core and
posix libraries will use different feature definitions.
------
help fix https://github.com/openthread/openthread/discussions/8200
=> [posix] fix OT_DAEMON flag definitions

src/core/net/srp_server.hpp, tools/otci/tests/test_otci.py
This commit updates the default `LeaseConfig` intervals used by 
`Srp::Server` to accept any requested lease time between 30 seconds
and 27 hours and any requested key lease time between 30 seconds
and 189 hours.
-----
This is related to [SPEC-1101](https://threadgroup.atlassian.net/browse/SPEC-1101).
=> [srp-server] update the default min/max lease/key-lease intervals

src/core/net/srp_server.cpp
This commit updates the `Srp::Server` to allow lease info (in 
particular the key-lease) to be retrieved for a deleted service or
host entry.
----
We now check if the entry is deleted and set the `mLease` and 
`mRemainingLease` to zero and avoid calling `GetExpireTime()`
(and trigger assert).
Note that we have `OT_ASSERT()` check in `GetExpireTime()`
```c++
TimeMilli Server::Service::GetExpireTime(void) const
{
OT_ASSERT(!mIsDeleted);
OT_ASSERT(!GetHost().IsDeleted());
return mUpdateTime + Time::SecToMsec(mDescription->mLease);
}
```
=> [srp-server] lease info  for a deleted service or host entry

src/cli/cli.cpp
Some mac counters were inaccessible from the CLI. This commit prints these counters.
=> [cli] print missing mac counters

src/core/net/srp_client.cpp, tests/scripts/thread-cert/test_srp_many_services_mtu_check.py
This commit fixes the "single service mode" behavior to handle
if there are many simultaneous service removes. It also updates the
test to cover this situation.
=> [srp-client] update "single service mode" to handle many removes

src/core/meshcop/dtls.cpp, src/core/meshcop/dtls.hpp
`mbedtls_ssl_conf_sig_hashes` was deprecated in 3.2.0, and we attempted to move over to the new recommended function. That new function expects `MBEDTLS_TLS1_3_SIG_`  type arguments.
=> [crypto] update the signature algorithm used for 3.2.0 mbedTLS

tests/fuzz/fuzzer_platform.cpp
Fixes the following build error:
```
src/ncp/libopenthread-ncp-ftd.a(ncp_base.cpp.o): in function `otPlatLog':
ncp_base.cpp:(.text.otPlatLog[otPlatLog]+0x0): multiple definition of `otPlatLog'; /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
tests/fuzz/CMakeFiles/ot-ncp-hdlc-received-fuzzer.dir/fuzzer_platform.cpp.o:fuzzer_platform.cpp:(.text.otPlatLog[otPlatLog]+0x0): first defined here
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
=> [fuzz] declare `otPlatLog` as weak

include/openthread/dns_client.h, include/openthread/instance.h, src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_config.h, src/core/net/dns_client.cpp, src/core/net/dns_types.cpp, src/core/net/dns_types.hpp, tests/unit/test_dns.cpp
This commit updates `Dns::Client` so that when reading service info
`otDnsServiceInfo` if the received TXT data does not fit in the given
buffer, it is read partially. A new field `mTxtDataTruncated` is added
in `otDnsServiceInfo` to indicate that TXT data was not fully read.
This commit also updates `dns` related commands in CLI so to output
the partially read TXT data and add a new config specifying the max
TXT data size used by CLI.
----
- Related to https://github.com/openthread/openthread/discussions/8229
-  Example of CLI output with `OPENTHREAD_CONFIG_CLI_TXT_RECORD_MAX_SIZE` set to only 4 bytes.
```
> DNS browse response for _srv._udp.default.service.arpa.
ins
Port:7777, Priority:1, Weight:1, TTL:7191
Host:myhost.default.service.arpa. …
```
=> [dns] allow partial read of TXT data and add config for max size in CLI

src/core/meshcop/energy_scan_client.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/thread/energy_scan_server.cpp, src/core/thread/energy_scan_server.hpp
This commit updates `EnergyScanClient` and `EnergyScanServer`.
On server side, we prepare the report message after we parse the
request and directly append the results in the report message as
energy scans are performed. Client side is also updated to
correctly handle the case where the report message contains
greater number of results that can be supported on the client
based on its configuration.
=> [meshcop] simplify energy scan client and server

tests/unit/test_dso.cpp, tests/unit/test_routing_manager.cpp, tests/unit/test_srp_server.cpp
---
Though it is unlikely that we ever need to run a test for more 24 days (for 
overflow to happen) but no harm in handling it (and be safe).
=> [test] update `AdvanceTime()` in unit tests to handle overflow

src/core/net/ip6.cpp, src/core/net/ip6.hpp
Two changes made together broke fragmented packets handling:
Some time ago forwarding packets outside of thread was limited to 1280 bytes
Recently forwarding IP packet fragments was disabled.
This makes it not forward packet fragments nor fully assembled packets.
According to later change author this was to prevent packets from being handled
twice.
To fix this, forwarding of IP fragments was restored and instead forwarding of
reassembled frames was disabled regardless of the frame size. This approach
should save the need of fragmenting already reassembled packets to fit
into the OPENTHREAD_CONFIG_IP6_MAX_DATAGRAM_LENGTH.
Signed-off-by: Marek Porwisz <marek.porwisz@nordicsemi.no>
=> [ip6] fix packets not being forwarded outside of Thread

src/core/thread/link_metrics.cpp, src/core/thread/link_metrics.hpp, src/core/thread/link_metrics_tlvs.hpp, src/core/thread/link_metrics_types.cpp, src/core/thread/link_metrics_types.hpp
This commit simplifies the handling of Type IDs in `LinkMetrics` modules.
=> [link-metrics] simplify handling of Type IDs

src/core/common/instance.cpp, src/core/common/instance.hpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/border_agent.hpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/commissioner.hpp, src/core/meshcop/joiner.cpp, src/core/thread/thread_netif.cpp, src/core/thread/tmf.cpp, src/core/thread/tmf.hpp
**[tmf] add `SecureAgent` and simplify URI resource processing**
This commit adds a new class `Tmf::SecureAgent` as a sub-class of
`Coap::CoapSecure`. It also simplifies the handling of TMF URI
resources by secure agent (similar model as in `Tmf::Agent` added
in #8233.
**[border-agent] simplify `ForwardToLeader()`**
This commit updates `BorderAgent::ForwardToLeader()` to determine the
`petition` and `separate` boolean flags from the passed-in `aUri`.
=> [tmf] add `SecureAgent` and simplify URI resource processing

src/core/backbone_router/backbone_tmf.cpp, src/core/backbone_router/backbone_tmf.hpp, src/core/backbone_router/bbr_manager.cpp, src/core/backbone_router/bbr_manager.hpp
This commit updates `BackboneTmfAgent` to handle TMF URI resources 
(similar to the model used by `Tmf::Agent` added in #8233).
=> [backbone-router] simplify TMF URI resource handling

src/core/api/netdata_publisher_api.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/config/netdata_publisher.h, src/core/thread/network_data_publisher.cpp, src/core/thread/network_data_publisher.hpp
This commit updates `NetworkData::Publisher` to reserve a set of
prefix entries for use by `RoutingManager` only. This allow us to
simplify how `RoutingManager` publishes route prefixes in Network
Data (assert on failure). In particular, this commit defines a new
enum `Requester` which specifies the requester (`kFromUser` or
`kFromRoutingManager`) associated with a published prefix. This is
used by methods `PublishExternalRoute()`/`PublishOnMeshPrefix()`.
When allocating new entries, we ensure that each requester is
limited to its maximum number of entries.
=> [netdata] update `Publisher` to reserve entries for `RoutingManager`

script/cmake-build
This commit allows using OT_CMAKE_NINJA_TARGET to specify multiple targets.
Verified by running the following commands:
```bash
./script/cmake-build simulation
OT_CMAKE_NINJA_TARGET="ot-cli-ftd ot-cli-mtd" ./script/cmake-build simulation
```
=> [cmake-build] allow specify multiple targets

src/core/thread/link_metrics.cpp, src/core/thread/link_metrics.hpp
This commit renames and updates the `LinkMetrics::FindNeighbor()`
helper method which finds the neighbor for a given link-local address
for use in `LinkMetrics` class. This method now also validates that the
neighbor's Thread version is 1.2 or higher.
=> [link-metrics] update method finding neighbor to validate its version

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, tests/unit/test_routing_manager.cpp
This commit updates and enhances the mechanism in `RoutingManager`
to publish/unpublish external route prefixes in Thread Network Data.
Instead of each sub-component (e.g., `DiscoveredPrefixTable`,
`LocalOnLinkPrefix`, `Nat64PrefixManager`, ...) directly trying to
publish/unpublish its entries which can lead to conflicting requests
that then needs to be checked and handled by each component, this
commit adds a new method `EvaluatePublishingPrefix()`. This method
makes a collective decision by checking with different sub-components
to see whether or not each wants this prefix published and if so at
what preference level and flags.
This change help simplify the code and handling of conflicting
situations and edge cases (e.g., while deprecating current/old local
on-link prefix, other routers …
=> [routing-manager] enhance mechanism to publish/unpublish route prefixes

src/core/coap/coap.cpp, src/core/mac/data_poll_handler.cpp, src/core/mac/sub_mac.cpp, src/core/meshcop/joiner.cpp, src/core/thread/indirect_sender.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/network_data_local.cpp, src/core/thread/network_data_notifier.cpp, src/ncp/ncp_base.cpp
This commit removes `OT_UNREACHABLE_CODE(break)` which is used in `case` statements performing an `OT_ASSERT()` in a `switch` block. If the `case` is the last one in the `switch` we can skip the `break` and therefore we don't need to use `OT_UNREACHABLE_CODE()`.
=> [core] remove `OT_UNREACHABLE_CODE(break)`

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, tests/unit/test_routing_manager.cpp
This commit enhances `RoutingManager` so that when we decide to
advertise the local on-link prefix and publish it in Network Data as
an external route, we wait for it to be seen in the leader's Network
Data before including it in the emitted RA messages as PIO. If the
prefix is already present in Network Data (e.g., may have been added
by another BR on the same Thread mesh) we start advertising it
immediately. When publishing prefixes in Network Data, it may take a
short random time before the entry is registered with leader and the
updated Network Data is propagated to all Thread nodes. This change
delays the advertisement of the on-link prefix on the infra link side
till it is configured as an external route on the Thread side.
-----
- ~This PR contains the commit from …
=> [routing-manager] adv local on-link prefix after added in net data

src/cli/cli_tcp.cpp, third_party/tcplp/bsdtcp/tcp_input.c
This pull request fixes a bug in TCPlp that causes an illegal memory access when refusing an incoming TCP connection using the `OT_TCP_INCOMING_CONNECTION_ACTION_REFUSE` action in the `otTcpAcceptReady` callback. It also fixes a bug in the TCP CLI tool that causes it to attempt to accept every incoming TCP connection (which should not normally be a problem, but in this case was triggering the above bug). Since there are really two separate bugs here, I separated their fixes into separate commits.
This fixes #8281.
=> [tcplp, cli-tcp] fix illegal memory access when refusing incoming TCP connection

include/openthread/instance.h, include/openthread/ip6.h
For various reasons, we're not able to use `<` and `>` in our Doxygen descriptions. I made some minor edits, LMKWYT. In the HTML, it renders similar to this:
The IPv6 socket address string is formatted as [`address`]:`port` where `address` is shown as 16 hex values separated by `:` and `port` is the port number in decimal format, for example "[%x:%x:...:%x]:%u".
=> [docs] Doxygen formatting updates

src/lib/spinel/CMakeLists.txt, src/ncp/radio.cmake
This change is needed to enable SPI vs UART NCP interface.
=> [cmake] disable `OPENTHREAD_CONFIG_NCP_HDLC_ENABLE` when `OT_NCP_SPI` is set

src/core/common/instance.cpp, src/core/common/instance.hpp
Move static heap construction to singleton accessor to avoid non-trivial construction at global scope, which has an unpredictable ordering.
=> [heap] move static heap construction to singleton accessor

src/core/net/srp_client.cpp
This commit updates `Srp::Client` so that on `RemoveService()` we 
always send an SRP Update message to server to remove the service 
even if the service is not yet registered (from perspective of client).
----
This should help resolve https://github.com/openthread/openthread/issues/8295.
=> [srp-client] inform server on service remove even if not added yet

src/core/coap/coap.cpp
Update CoAP base handler to correctly detect when a handler is not found and send a 4.04 response.
Prior to this change, the error code would be overridden in the case where a URI handler was not found to kErrorNone. This meant that when the exit code was reached, no 4.04 message was generated. This fixes the logical flow to ensure the error message is sent on the link.
=> [coap] Bugfix: CoAP not sending 4.04 when URI handler is not found

src/core/mac/mac.cpp
When a message is received that does not contain a source address (ex: IEEE 802.15.4 Beacon Request) find neighbor should not be called to attribute the message to a particular device in the network.
The bug was found in the following scenario:
* Network operating with REED devices.
* Other non-Thread IOT devices in the space periodically sending beacon requests.
* Note that the REED devices have unexpectedly low average RSSI values for their parents.
When the child processes the beacon request, it calls FindNeighbor(), which defaults to returning the parent of the device if srcaddr is none. The RSSI of the beacon request is then averaged into the value for the device's parent.
Fix: Do not look up the neighbor if there is no source address in the message, because there's no way to know …
=> [mac] Bugfix: Messages without a source address handled incorrectly

include/openthread/instance.h, include/openthread/platform/toolchain.h, src/core/common/num_utils.hpp, src/core/common/string.hpp, src/core/common/uptime.cpp, src/core/meshcop/meshcop.cpp, src/core/radio/trel_packet.cpp, src/core/thread/network_data_publisher.cpp
This commit adds `OT_TOOL_PRINTF_STYLE_FORMAT_ARG_CHECK` macro in
`toolchain.h`. It specifies that a function or method takes `printf`
style args. It asks the compiler to check the args for consistency
with the passed-in format string.
The commit uses the new macro in `String::Append()` and its uses are
updated to ensure consistency between format string and the args.
----
- This PR adds `OT_TOOL_PRINTF_STYLE_FORMAT_ARG_CHECK` and uses in `String::Append()`. 
- The goal is to add same check in `Log()` and also CLI `Output` methods
- Though it may not be as straight-forward (will tackle this in follow-up PRs).
=> [string] add compile-time check for `printf` style arg consistency

include/openthread/instance.h, include/openthread/thread.h, src/cli/README.md, src/cli/cli.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, tools/otci/tests/test_otci.py
A useful metric for a device is the amount of time it spends in each mle role. This could help to identify connectivity issues on SED with weak signal and frequent detaches by checking the time spent in detached mode. It would also be useful to know the time spent in leader state when having multiple FTDs frequently joining and splitting in different partitions.
This information is not available from the role counters, since time spent in each state is not related to the number of entries to that state.
This commit adds mle counters to track time spent in each role, when uptime feature is enabled (`OPENTHREAD_CONFIG_UPTIME_ENABLE=1`).
Some notes:
- With this changes `Mle::GetCounters` is no longer const since time counters must be updated.
- Time will not be all zero after resetting the …
=> [mle] add time tracking to mle roles

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/config/border_routing.h, tests/unit/test_routing_manager.cpp
This commit updates how `OnLinkPrefixManager` retains and deprecates old local on-link prefixes. Instead of remembering a single old prefix, a list of old prefixes are remembered (number of entries in the list is configurable using an OT build-time config).
If the BR is stopped the deprecating prefixes are still remembered and the the expire timer keeps running. They are removed from the list when they expire. If the BR is started again the deprecating old prefixes are again included as PIO in the emitted RA and also published in Network Data.
The changes in this commit also ensure we can correctly handle the situation where the extended PAN ID is changed to a previous value before the corresponding on-link prefix expires, i.e. when a currently deprecating prefix becomes the current local …
=> [routing-manager] new mechanism for deprecating old on-link prefixes

src/core/mac/mac_frame.cpp
Fails parsing of an IEEE 802.15.4 frame if the source addressing field is set to a reserved value.
=> [mac] add reserved value to source address parsing

include/openthread/icmp6.h, include/openthread/instance.h, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/config/border_routing.h, src/core/net/icmp6.hpp, src/core/net/nd6.cpp, src/core/net/nd6.hpp, tests/unit/test_routing_manager.cpp
This commit adds a new mechanism in `RoutingManager` to periodically
check that discovered routers are still active and operational, so
that if the router providing the favored on-link prefix becomes
offline, we can detect it more quickly (instead of waiting for the
prefix lifetime to expire) and then the BR can start advertising its
own on-link prefix.
Receiving a Router or Neighbor Advertisement message from a router
indicates that it is active. After a timeout interval passes from the
last receive from a router we start sending Neighbor Solidification
(NS) probes to it. This timeout interval can be specified by
newly added build-time OT config parameter (default value is set to
2 minutes). If no response is received after multiple NS attempts, the
router is considered to be inactive …
=> [routing-manager] add Neighbor Solicit probe mechanism

src/core/config/tmf.h, src/core/thread/address_resolver.cpp, src/core/thread/address_resolver.hpp, src/core/thread/mle_types.hpp, src/core/thread/network_data_service.cpp, src/core/thread/network_data_service.hpp, tests/unit/test_network_data.cpp
This commit implements a new optimization in `AddressResolver` allowing it to resolve on-mesh IPv6 addresses using info from Thread Network Data DNS/SRP Service (Unicast Address) entries.
When determining EID-to-RLOC mapping in `Resolve()`, we first try to match the EID against unicast addresses discovered from DNS/SRP service entries. This is limited to entries where the address/port info is encoded as part of server data. If a match is found the associated RLOC16 of the BR which added the entry in Network Data will be used (i.e., the `server16` field from Network data server sub-TLV). This optimization is used on devices where MLE Mode indicates they receive full Network Data and not the stable subset (since stable subset will not provide RLOC16 info).
This commit adds a similar check …
=> [address-resolver] allow addr resolution using net data service

third_party/tcplp/bsdtcp/tcp_input.c
`aAddr` should be the source address not the destination address.
=> [tcplp] fix call to tcplp_sys_accept_ready()

tests/scripts/thread-cert/border_router/test_single_border_router.py
This commit increases the wait time in `test_single_border_router` 
after re-enabling `ether` link. It also changes the order of pings in the
test (first ping from host to Thread router and the opposite direction).
=> [test] increase wait time after `ether` re-enable

src/core/thread/mle_router.cpp
This commit updates `SendLinkAccept()` method so to log the message 
type (whether we send "Link Accept and Request" or "Link Accept").
=> [mle] log sending of "Link Accept and Request"

include/openthread/instance.h, include/openthread/platform/settings.h, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/common/settings.cpp, src/core/common/settings.hpp, tests/unit/test_platform.cpp, tests/unit/test_routing_manager.cpp
This commit adds mechanism to save deprecating old on-link prefixes
in non-volatile `Settings`. With this, if the BR is restarted, it
will remember the old prefixes and keep deprecating them (advertising
them in emitted RA and publish them in Thread Network Data).
This commit also adds `TestSavedOnLinkPrefixes()` test case in
`test_routing_manager` to cover the behavior of the newly added
mechanism.
=> [routing-manager] persist deprecating old prefixes in `Settings`

src/cli/cli.cpp
This commit enhances `ParseRoute()` method allowing flags to be specified in one arg (sequence of char indicating different flags) or potentially over different args. This commit also allows `-` to be used in `route` or `prefix` commands to indicate empty flag.
---
Existing code only allowed:
`netdata publish prefix fd00:1234::/64 n s med`
New code still allows the previous model but also 
`netdata publish prefix fd00:1234::/64 ns med`
Just FYI: @gabekassel
=> [cli] enhance parsing of flags for `route` commands

src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_coap.cpp, src/cli/cli_coap.hpp, src/cli/cli_coap_secure.cpp, src/cli/cli_coap_secure.hpp, src/cli/cli_commissioner.hpp, src/cli/cli_dataset.hpp, src/cli/cli_history.hpp, src/cli/cli_joiner.hpp, src/cli/cli_network_data.hpp, src/cli/cli_output.cpp, src/cli/cli_output.hpp, src/cli/cli_srp_client.cpp, src/cli/cli_srp_client.hpp, src/cli/cli_srp_server.hpp, src/cli/cli_tcp.cpp, src/cli/cli_tcp.hpp, src/cli/cli_udp.cpp, src/cli/cli_udp.hpp
This commit updates the `Cli::Output` class and the related types. A new type `OutputImplementer` is added which provides the basic output functionality, i.e., method `OutputV()`. `Output` class requires a reference to an `OutputImplementer` which it then uses to provide all the different `Output{}()` method flavors. The new model allows all CLI sub-modules to directly inherit `Output` class while reusing a single and common underlying `OutputImplementer` provided by the `Cli::Interpreter`.
----
This PR is in preparation of adding `OT_TOOL_PRINTF_STYLE_FORMAT_ARG_CHECK` (build-time printf style arg check) to CLI `Output{}()` methods.
=> [cli] update CLI `Output` class

src/core/backbone_router/bbr_leader.cpp, src/core/backbone_router/bbr_local.cpp, src/core/backbone_router/bbr_manager.cpp, src/core/backbone_router/multicast_listeners_table.cpp, src/core/backbone_router/ndproxy_table.cpp, src/core/border_router/routing_manager.cpp, src/core/common/log.hpp, src/core/common/notifier.cpp, src/core/common/settings.cpp, src/core/mac/mac.cpp, src/core/mac/sub_mac.cpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dtls.cpp, src/core/net/srp_client.cpp, src/core/net/srp_server.cpp, src/core/net/tcp6.cpp, src/core/net/tcp6_ext.cpp, src/core/thread/announce_sender.cpp, src/core/thread/link_metrics.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mlr_manager.cpp, src/core/thread/network_data_publisher.cpp, src/core/thread/time_sync_service.cpp, src/core/utils/channel_manager.cpp, src/core/utils/channel_monitor.cpp
This commit adds compile-time check of format string to all log
functions and macros. It also updates different core modules to make
arg string formats consistent under different platforms. In particular
we use `'%lu` for `uint32_t` arguments and they are explicitly cast
to `unsigned long` using `ToUlong()`.
=> [log] add compile-time check for `printf` style arg check to log functions

src/posix/platform/netif.cpp
Because there is no corresponding argument, a crash occurs when outputting the log.
=> [netif] fix bug in print statement with no corresponding argument

examples/platforms/utils/soft_source_match_table.c, include/openthread/instance.h, include/openthread/logging.h, src/posix/platform/daemon.cpp, src/posix/platform/netif.cpp
---
This should help find issues like https://github.com/openthread/openthread/pull/8353 in future.
This may impact platform implemenations and require fixes.
=> [log] add arg format check to `otLog{Level}Plat()` functions

src/core/thread/network_diagnostic.cpp, src/core/thread/network_diagnostic.hpp
This commit adds a common `SendDiagnosticCommand()` which is then used for sending `DiagnosticGet` or `DiagnosticReset` commands.
=> [net-diag] add a common `SendDiagnosticCommand()` method

src/core/common/tlvs.cpp, src/core/common/tlvs.hpp
This commit changes `ReadTlv()` methods so that they can be used independent of whether the read TLV is an Extended TLV or not. This makes them similar to `FindTlv()` methods.
=> [tlv] `ReadTlvValue()` to handle regular or extended TLVs

src/cli/cli.cpp, src/cli/cli_commissioner.cpp, src/cli/cli_dataset.cpp, src/cli/cli_joiner.cpp, src/cli/cli_output.cpp, src/cli/cli_output.hpp
The new method allow us to output `uint64_t` values without needing to cast to `unsigned long long` and/or use of `%llu` (which may not be provided by certain embedded libraries).
----
This is in preparation for adding `OT_TOOL_PRINTF_STYLE_FORMAT_ARG_CHECK` to CLI `Output{}` methods.
=> [cli] add `OutputUint64()` for 64-bit integer value in decimal format

src/core/thread/network_diagnostic.cpp, src/core/thread/network_diagnostic.hpp, src/core/thread/network_diagnostic_tlvs.hpp
This commit updates `NetworkDiagnostic` class's generation and processing of TLVs. When appending list based TLVs (IPv6 Address List TLV or Child Table TLV) depending on the number of entries we use regular or extended TLV. When processing the message and reading the TLVs, this commit updates the code to handle extended TLVs as well.
This commit changes the behavior of `GetNextDiagTlv()`. The `otNetworkDiagTlv` data structure defines limited-size arrays for IPv6 address list and child table. When processing a received message if the number of entries is larger than the array size, the first set entries (as many as fits in the array) are read and the rest are ignored. This changes the existing behavior which returned a `kErrorPrase` error in such a case.
=> [net-diag] simplify processing of TLVs, allow extended TLV

src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_coap.cpp, src/cli/cli_coap_secure.cpp, src/cli/cli_commissioner.cpp, src/cli/cli_dataset.cpp, src/cli/cli_network_data.cpp, src/cli/cli_output.cpp, src/cli/cli_output.hpp, src/cli/cli_srp_server.cpp, src/cli/cli_tcp.cpp
This commit adds compile-time check of format string to all CLI
`Output` methods. It also updates CLI module to  make arg string
formats consistent. In particular we use `'%lu` for `uint32_t`
arguments and they are explicitly cast to `unsigned long` using
`ToUlong()`.
-----
This PR contains the commit from 
- https://github.com/openthread/openthread/pull/8354
=> [cli] add compile-time `printf` style arg check in CLI

src/posix/platform/backtrace.cpp
The `execinfo.h` is a glibc specific header, and the glibc doesn't exist under openwrt. It causes the compile errors under openwrt in ot-br-posix. This commit uses __GLIBC__ instead of __linux__ to avoid the compile errors when the OS doesn't contain the glibc.
=> [posix] use __GLIBC__ instead of __linux__ in backtrace

src/cli/cli.cpp
When `OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE` is enabled.
=> [cli] fix `printf` style output

src/core/net/ip6.cpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp, src/core/thread/thread_netif.cpp, src/core/thread/thread_netif.hpp
This commit updates the `RouteLookup()` methods in `NetworkData` and `ThreadNetif`:
- Removes the unused `aPrefixMatchLength` parameter.
- Requires `aRloc` to be a reference instead of a pointer.
=> [netdata] simplify `RouteLookup()` methods

src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp
This commit adds `CompareRouteEntries()` which performs a three-way comparison between two network data BR route entries:
- Entry with higher preference is selected first.
- If the same preference, prefer BR that is this device itself.
- If all same, prefer the one with lower mesh path cost.
=> [netdata] add helper method to compare two BR entries

src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp, src/core/thread/network_data_local.cpp, src/core/thread/network_data_local.hpp, src/core/thread/network_data_notifier.cpp, src/core/thread/network_data_notifier.hpp
This class moves all the related code for preparing and sending `kUriServerData` message to `NetworkData::Notifier`. In particular, `RemoveStaleChildEntries()` and `UpdateInconsistentData()` are moved to the `Notifier` class.
----
Background:
- This change is in preparation for an upcoming PR (an idea/mechanism to help detect when netdata gets full - we can check if combining the current local netdata into leader would be successful or not).
- And also makes sense for `Notifier` to be in charge of preparing and sending the message (in addition to the timings of retries).
=> [netdata] update `Notifier` to prepare and send SVR_DATA.ntf msg

.github/workflows/build.yml
- install `ninja` binary directly
- use pre-installed clang on macos
=> [github-actions] fix macos build checks

src/cli/cli_output.cpp
This commit updates `OutputSpaces()` to use literal format string. 
----
This should help address build-time checks which require string literal with `__attribute__((format(printf,x,y))` (related to `Werror=format-nonliteral`).
=> [cli] update `OutputSpaces()` to use literal format string

script/bootstrap
This commit chages incorrect pkg manager tool used in `install_packages_pretty_format` from brew to apt-get.
=> [bootstrap] remove brew from apt package installations

src/core/meshcop/dataset_manager.cpp, src/core/meshcop/meshcop_tlvs.hpp
This commit simplifies `StateTlv` and updates the reading of TLV in `DatasetManager::HandleMgmtSetResponse()` (which could previously allow a TLV with empty value).
=> [meshcop] simplify `StateTlv`

src/core/meshcop/commissioner.cpp
This commit fixes the comparison of the received Provisioning URL string with the commissioner's one when handling Joiner Finalize TMF message.
=> [commissioner] fix provisioning URL comparison

src/core/meshcop/dataset.cpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager.hpp, src/core/thread/discover_scanner.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp, tests/unit/test_lowpan.cpp
This commit updates `Mle` modules to use `FindTlvValueOffset()` instead of `FindTlvOffset()` when trying to find a variable length TLV (e.g., Network Data TLV or Address Registration TLV). This helps simplify the code (we avoid reading the TLV again and can directly read and process the TLV's value).
----
The goal is later to remove `Tlv::FindTlvOffset()`.
=> [mle] use `Tlv::FindTlvValueOffset()` instead of `FindTlvOffset()`

src/core/backbone_router/bbr_manager.cpp, src/core/common/tlvs.cpp, src/core/common/tlvs.hpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/joiner.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/thread/thread_tlvs.hpp
This commit adds new methods in `Tlv` to read, find, or append simple TLVs with a UTF8 string value. `StringTlvInfo<Type, kMaxStringLen>` can be used to define constants and types for such TLVs. This helps simplify implementation of many such TLVs, e.g., Vendor Name TLV, Provisioning URL TLV, Network Name TLV, etc.
=> [tlv] helper methods to read/find/append TLVs with UTF8 string value

include/openthread/instance.h, include/openthread/platform/radio.h, src/lib/spinel/radio_spinel_impl.hpp, src/lib/spinel/spinel.h, src/posix/platform/radio.cpp
When adding a new spinel property or updating the existing spinel
property, it may cause the host can't work with the old RCP. The
host can be updated independently on some of our products. If the
compatibility issue happens, it causes the host dies after the
host is updated.
To reduce the compatibility issues between the host and RCP, this
commit updates the guideline of updating/adding RCP spinel properties.
=> [spinel] update the updating/adding RCP spinel property guideline

.github/dependabot.yml
Add a Dependabot configuration that checks once a week if the GitHub Actions are still using the latest version. If not, it opens a PR to update them.
It will actually open few PRs, since only major versions are specified (like v3), so only on a major release (like v4) it will update and open a PR. But it helps actively keep GitHub Actions workflows up to date and secure.
See [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot).
=> [github-actions] add Dependabot configuration for GitHub Actions updates

src/core/common/tlvs.cpp, src/core/common/tlvs.hpp, tests/unit/CMakeLists.txt, tests/unit/Makefile.am, tests/unit/test_tlv.cpp
This commit adds new private type `ParsedInfo` in `Tlv` class which contains parsed TLV info such as TLV type, length, size, value offset. This class provides `ParseFrom()` and `FindIn()` methods to parse or find a TLV from a message.
This commit also adds a unit test `test_tlv` to validate the TLV methods.
=> [tlv] add private helper methods to parse and find TLVs in a message

src/core/meshcop/border_agent.cpp, src/core/meshcop/meshcop_tlvs.hpp
This commit updates how UDP Encapsulation TLV is processed. In particular, when handling a received TMF `kUriProxyTx` message containing this TLV, we allow the TLV to be extended or not. This is aligned with the Thread specification for this TLV. When appending this TLV in `kUriProxyRx` TMF message, we continue to use Extended TLV so to keep the behavior same as before.
=> [meshcop] update processing of UDP Encapsulation TLV

tests/scripts/thread-cert/border_router/nat64/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/nat64/test_single_border_router.py, tests/scripts/thread-cert/call_dbus_method.py, tests/scripts/thread-cert/node.py
Replace the CLI commands used in NAT64 tests by DBus API introduced in openthread/ot-br-posix#1598
The functions:
- nat64_state
- nat64_mappings
- nat64_counters
- nat64_traffic_counters
Are simple wrappers for corresponding DBus methods and properties.
=> [nat64] use DBus API for NAT64 tests

src/core/border_router/routing_manager.cpp, tests/unit/test_routing_manager.cpp
This commit updates `RoutingManager` to check if a change to xpanid does impact the generated local on-link prefix. This can address two situations: (1) when BR is started before Thread/MLE operation where we can get a signal that xpanid is changed on MLE start (without it actually changing), (2) if the xpanid does change but since not all the xpanid bytes are used in the derivation of the local prefix, it can remain as before.
This commit also updates the unit test to start the BR early (along with MLE operation) under the `TestSavedOnLinkPrefixes()` case.
=> [routing-manager] ensure local prefix is changed on xpanid change

Android.mk
`LOCAL_EXPORT_CFLAGS` is exporting `OPENTHREAD_PROJECT_CFLAGS` which contains quotes. This sometimes can cause compile errors due to limitation of Android build system.
Also, `ot-cli` is repeating the flags in `LOCAL_CFLAGS`, which can cause macro redefinition error. Since `ot-cli` depends on `ot-core`, it already gets the flags from `LOCAL_EXPORT_CFLAGS`.
=> [build] fix `LOCAL_EXPORT_CFLAGS` 

src/core/mac/data_poll_handler.cpp
Fix an issue in which a CSL Transmitter would start to send malformed frames to the radio in the occasion of a data poll arriving while a delayed CSL transmission was already scheduled.
Notice that `CslTxScheduler::HandleSentFrame` is resetting both CSL Tx attempts and Indirect Tx attempts, so it makes sense to do the same in `DataPollHandler::HandleSentFrame`.
=> [indirect-sender] reset CSL Tx attempts in `DataPollHandler`

src/core/thread/network_data_publisher.hpp
I recently saw a log line:
```
ExternalRoute fdde:ad00:beef:cafe::/64 (state:Add in netdata - total:1, preferred:0, desired:10
```
The string `(state:Add` is truncated. The actual string should be `(state:Added)`.
The info string of a prefix entry can be as long as 55 characters excluding the 
`\0`.
Example:
```
ExternalRoute fdde:ad00:beef:cafe::/64 (state:Removing)
```
=> [netdata] increase `kInfoStringSize`

Android.mk, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/common/num_utils.hpp, src/core/thread/mle_tlvs.cpp, src/core/thread/mle_tlvs.hpp, src/core/thread/mle_types.cpp, src/core/thread/mle_types.hpp, src/core/thread/router_table.cpp, tests/unit/test_serial_number.cpp
This commit contains smaller enhancements in `RouteTlv`:
- `RouteTlv::IsValid()` checks that number of allocated IDs in the Router ID Mask is less than max number of routers.
- It also checks that the TLV contains correct number of Route Data entries matching the number of allocated router IDs.
- A new method `SetRouteData()` is added to set all the data fields (link quality in/out and route cost) for a given router index.
- These changes help ensure that messages containing invalid `RouteTlv` are rejected (avoid situation where we may have more allocated router IDs than max routers).
=> [mle] update `RouteTlv` to check number of allocated IDs

src/core/thread/csl_tx_scheduler.cpp, src/core/thread/csl_tx_scheduler.hpp
This commit fixes how we determine the CSL timings when preparing a
frame for CSL transmission. When scheduling the next CSL, we use
`mCslFrameRequestAheadUs` time in `GetNextCslTransmissionDelay()`. We
basically schedule `Mac` to start the CSL tx operation a bit earlier
than the desired CSL tx time. In `HandleFrameRequest()` (when we are
preparing the frame to be sent) we should be already within
`mCslFrameRequestAheadUs` time from the tx time. So this commit changes
the code such that we invoke `GetNextCslTransmissionDelay()` with zero
`aAheadUs` interval when preparing the frame. This ensures that we do not
skip the current CSL window and move to the next.
This commit also adds a check in `HandleFrameRequest()` to ensure that
we did not miss the current CSL window. This situation can …
=> [csl] ensure current window is not missed when preparing CSL frame

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
---
This PR contains no logic change. 
Just renames variables that are `Tlv` to make it consistent across MLE modules.
=> [mle] rename variables to indicate if they are a TLV

tests/scripts/thread-cert/border_router/nat64/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/nat64/test_single_border_router.py, tests/scripts/thread-cert/border_router/nat64/test_with_infrastructure_prefix.py
This PR deletes calling nat64_set_enabled() when starting BR in tests. NAT64 is enabled by default.
=> [nat64] delete nat64_set_enabled() when starting BR in tests

src/core/thread/network_data_leader_ftd.cpp
This commit updates `RegisterNetdataData()` to ensure that versions are updated if there is any change even if there is an error during integration of new entries (e.g., running out of space in Network Data, or failing to allocate new service ID).
=> [netdata] ensure to update version on leader if there is any change

src/core/net/ip6_mpl.cpp
This commit updates `Mpl::UpdateSeedSet()` to reset the `SeedEntry` lifetime to `kSeedEntryLifetime` if we rx/tx a message with same ID and sequence. This ensures that the entry is kept in the array while other routers are forwarding the same message.
=> [mpl] reset seed entry lifetime on rx/tx

src/cli/README.md, src/cli/cli.cpp
Sometime we need to identify which platform we are currently using, especially in a test cases, where a unified interface is provided to control devices, the test cases have no idea about current platform.
=> [cli] add `platform` command which returns current platform

src/cli/cli.cpp, src/core/border_router/infra_if.cpp, src/core/border_router/routing_manager.cpp, src/core/common/settings.cpp
Fix some `uint32_t` variables using `%u` format.
related: [[log] add compile-time check for printf style arg check to log functions](https://github.com/openthread/openthread/pull/8339)
=> [logging] fix print format using `%lu` for `uint32_t` variables

script/bootstrap
I needed to add these symlinks because `script/clang-tidy` couldn't find these files
=> [clang-tidy] add missing symlinks to bootstrap

src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit adds a new variable `mInitiallyAttachedAsSleepy` which tracks whether or not device was initially attached as a sleepy child. This is then used to determine whether or not we need to re-attach on mode changes between rx-on and sleepy (rx-off). If we initially attach as sleepy, then rx-on/off mode changes are allowed without re-attach (device sends "Child Update Request" to its parent to update its mode). Otherwise mode transition from rx-on to sleepy requires a re-attach.
----
Follow up on https://github.com/openthread/openthread/pull/8484.
=> [mle] allow rx-on/off with no re-attach based on initial attach mode

src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit updates `Mle` to store the current RLOC16 in a member variable `mRloc16` (in addition to setting it on `Mac` as device's short address). This allows `Mle::GetRloc16()` to be defined as an inline method instead of using `Get<Mac::Mac>().GetShortAddress()`.
=> [mle] remember current RLOC16 in a member variable

tests/scripts/thread-cert/border_router/nat64/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/nat64/test_single_border_router.py, tests/scripts/thread-cert/border_router/nat64/test_with_infrastructure_prefix.py
We cannot ensure NAT64 is enabled when running tests, and calling an extra nat64_set_enabled has no side-effects.
=> [test] ensure NAT64 is enabled when running NAT64 tests

src/core/common/array.hpp, src/core/radio/trel_link.cpp, src/core/thread/key_manager.cpp, src/core/thread/mle_router.cpp, src/core/thread/router_table.cpp, src/core/thread/router_table.hpp, src/core/thread/thread_tlvs.hpp
This commit simplifies how `RouterTable` tracks the allocated Router IDs and the `Router` entries. A new class `RouterIdMap` is added which tracks the currently allocated Router IDs. For allocated IDs, it also tracks the index of the `Router` entry in `mRouters` array. For unallocated IDs, it tracks the remaining reuse delay time in seconds (using the same underlying `uint8_t` per Router ID). This new class makes it easier to find a `Router` by its ID. With this change, we no longer need to keep the `mRouters` array sorted based on Router ID (this was used when populating `RouteTlv`).
This commit also changes the `mRouters` to use `Array<Router>` which will then tracks its length and also simplify range-based `for` iteration over `RouterTable` entries.
=> [router-table] simplify tracking of routers and allocated IDs

src/posix/platform/infra_if.cpp
This PR enables receiving Neighbor Advertisements (NA) on the infra link.
OTBR relies on receiving Neighbor Advertisement to check if a router is active (#8090). Without receiving NA, OTBR may wrongly see a router as inactive and remove the discovered prefixes from Network Data too early, which breaks the border routing feature.
=> [posix] enable receiving Neighbor Advertisement on infra interface

src/core/thread/mle_router.cpp
----
Change to follow our style guide.
```
- There should be one return statement per free function or method at the end of the free function or method.
```
=> [mle] avoid multiple `return` in `HasSmallNumberOfChildren()`

.github/workflows/toranj.yml, etc/cmake/options.cmake, examples/README.md, tests/toranj/build.sh
**[cmake] add `OT_15_4` option for `RADIO_LINK_IEEE_802_15_4_ENABLE`**
This commit adds new cmake option `OT_15_4` to enable 802.15. radio
link. It also adds additional `message(STATUS)` to output the common
`OT_APP_CLI/NCP/RCP` and `OT_FTD/MTD/RCP` options.
**[toranj update `build.sh` to use `cmake` for CLI builds**
=> [cmake] add `OT_15_4` option for `RADIO_LINK_IEEE_802_15_4_ENABLE` and update toranj builds

src/lib/spinel/radio_spinel_impl.hpp, src/ncp/ncp_base_radio.cpp
There are two issues fixed in this PR:
- Separate out max power table related code.
- Cache the transaction ID for async response only if otLinkRawTransmit() succeeds.
=> [rcp] fix transaction ID caching and guard max power table code

src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
This commit updates `NeighborHasComparableConnectivity()` method which is used as one of conditions to decide whether the router needs to downgrade to REED. This method check whether a given neighboring router has as good or better-quality links to all our neighboring routers with two-way link quality of two or better.
The previous implementation assumed that routers in `RouterTable` would match the same set of routers and their order as in the received `RouteTlv` from the peer router. This may not necessarily be the case (particularly after #8483). This commit changes the implementation so that we iterate over all Router IDs and directly track the index of each allocated router ID in the received `RouteTlv`.
=> [mle] fix `NeighborHasComparableConnectivity()`

src/posix/platform/infra_if.cpp, src/posix/platform/infra_if.hpp, src/posix/platform/openthread-posix-config.h, src/posix/platform/system.cpp
On some platforms, we need to support the cases that
1. the infrastructure interface can't be determined when the Thread daemon is started
and we need to enable the Border Router features after the infra interface is available.
3. Some BR devices want to send/recv RAs in a coordinated way to be more efficient
and consistent. For example, a BR which is also a Wi-Fi router may want to send/recv
RAs by a single component.
This commit add a new `OPENTHREAD_POSIX_CONFIG_INFRA_IF_ENABLE` for
disabling the default posix infra if implementation so that posix platforms can add their
own version.
=> [posix] add build option for posix infra if implementation

src/posix/platform/infra_if.cpp, src/posix/platform/infra_if.hpp
We should not use static member fields given the `posix::InfraIf` is already a singleton.
Instead, let's make it consistent with the rest of the fields which are all non-static.
=> [posix] make `mInfraIfIndex` non-static for `posix::InfraIf`

src/core/thread/mle_router.cpp
This commit removes the `#if` checks for `OPENTHREAD_FTD` in `MleRouter` method implementations as the entire `mle_router.cpp` is covered with a `#if OPENTHREAD_FTD` check at the top of the file.
=> [mle] remove redundant `OPENTHREAD_FTD` checks in `mle_router.cpp`

src/cli/cli_config.h, src/cli/cli_output.cpp
This commit adds `OPENTHREAD_CONFIG_CLI_LOG_INPUT_OUTPUT_LEVEL` to specify the log level to use when CLI input/output is emitted to logs (`OPENTHREAD_CONFIG_CLI_LOG_INPUT_OUTPUT_ENABLE` is enabled).
---
This is currently hardcoded as `OT_LOG_LEVEL_DEBG`. This PR allows us to configure it on a specific build which would be helpful to collect logs during CI tests.
=> [cli] add config for log level for emitting cli input/output to logs

src/ncp/ncp_hdlc.cpp, tests/unit/test_platform.cpp
It also removes stale comments in `ncp_hdlc.cp` about use of `sprintf`.
---
This is to avoid getting warning/errors below:
```
[6/57] Building CXX object tests/unit/CMakeFiles/ot-test-platform.dir/test_platform.cpp.o
/Users/abtink/github/openthread/tests/unit/test_platform.cpp:198:5: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
sprintf(aOutput, "diag feature '%s' is not supported\r\n", aArgs[0]);
^
```
=> [test] replace `sprintf` with `snprintf` in `otPlatDiagProcess()`

src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
This commit adds `MleRouter::ShouldDowngrade()` which determines whether all conditions are satisfied for the router to downgrade after receiving info for a neighboring router. This method is then used in `HandleAdvertisement()`. It effectively combines some of the other methods into one.
=> [mle] add `ShouldDowngrade()` method

src/cli/README_SRP_SERVER.md
Adding some clarification around the display of TXT records in `srp server service` based on the discussion in #8459
=> [docs] SRP Service Clarification

tests/scripts/thread-cert/node.py
---
Background:
On Mac OS running `./script/make-pretty python` always creates a `diff` (it tries to put the two strings on different lines):
(which I think is different from outcome under other Linux OSes?).
```bash
$ git diff
diff --git a/tests/scripts/thread-cert/node.py b/tests/scripts/thread-cert/node.py
index 1904c7199..516a53175 100755
--- a/tests/scripts/thread-cert/node.py
+++ b/tests/scripts/thread-cert/node.py
@@ -2876,7 +2876,8 @@ class NodeImpl:
else:
timeout = 5
-        self._expect(r'Received ACK in reply to notification ' r'from ([\da-f:]+)\b', timeout=timeout)
+        self._expect(r'Received ACK in reply to notification '
+                     r'from ([\da-f:]+)\b', timeout=timeout)
(source,) = self.pexpect.match.groups()
source = source.decode('UTF-8')
```
By combining …
=> [pretty] combine strings in `node.py`

src/core/net/netif.cpp, src/core/net/netif.hpp
This commit adds a private method `SignalMulticastAddressChange()`
which signals changes to fixes multicast addresses.
=> [netif] add helper to signal fixed multicast address changes

examples/platforms/simulation/logging.c, examples/platforms/simulation/platform-simulation.h, examples/platforms/simulation/system.c
This commit adds a new option in simulation platform to allow us to specify a file name to write the logs into. This is applicable when `LOG_OUTPUT` is set to `PLATFORM_DEFINED`. The filename can be specified by `-l <name>` or `--log-file=<name>` options. If no log file is provided then logs are emitted to syslog.
=> [simul-plat] new option to write logs to a given file

src/core/thread/link_quality.cpp, src/core/thread/link_quality.hpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/mle_types.hpp, src/core/thread/router_table.cpp
This commit renames and moves the function which coverts a given `LinkQuality` value to a link cost to `link_quality` source files.
=> [link-quality] move `CostForLinkQuality()` to `link_quality.hpp`

.github/workflows/otbr.yml
The `harden-runner` action causes the OTBR workflow jobs to hang for some reason. Disable until we are able to resolve the issue.
Thanks to @superwhd for identifying this in #8566.
=> [github-actions] disable `harden-runner` in OTBR workflow

src/cli/cli.cpp
In #8570 an issue with the channel mask output for the favored channel mask is identified. This changes the output to use the correct mask.
=> [cli] fix incorrect mask "channel manager" CLI output

src/core/border_router/routing_manager.cpp, src/core/net/nat64_translator.cpp, src/core/net/nat64_translator.hpp, tests/scripts/thread-cert/border_router/nat64/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/nat64/test_with_infrastructure_prefix.py, tests/scripts/thread-cert/thread_cert.py
AIL NAT64 is present, there is another NAT64 service on the infra network, so we should bypass the NAT64 translator to let the border router forward the packet to the infra NAT64 service.
=> [nat64] NAT64 translator should be active only when local prefix is published

tests/toranj/cli/cli.py, tests/toranj/openthread-core-toranj-config-simulation.h
This commit updates `toranj-cli` to use the simulation platforms "log
to file" feature and CLI feature to emit CLI input/output to log. This
helps simplify the log collection during testing and decouple it from
parsing/processing the CLI output while performing the test.
----
~This PR also contains commits from the following PRs:~
- ~https://github.com/openthread/openthread/pull/8545~
- ~https://github.com/openthread/openthread/pull/8516~
=> [test] update toranj-cli logging to use log to file model

src/core/api/link_metrics_api.cpp, src/core/thread/link_metrics.hpp
This commit fixes the placement of the preprocessor directive to avoid linking errors.
=> [link-metrics] fix build flags for Link Metrics Initiator

src/core/thread/lowpan.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp
This commit updates how we set the `hopsLeft` when preparing a lowpan `MeshHeader` frame so to use a constant max value. The max hops lefts value is determined based on `kMaxRouteCost`(estimate on max hops between routers within Thread mesh) and additional guard increment (e.g., adding for two for source or destination being child and require one more hop).
This change replaces the previous model where number of hops was predicted on source using the routing cost towards the destination. While the cost can be a good estimate for number of hops, it may not necessarily be correct, as the source's view of route cost may be less than what its neighbor and next hops on the path currently have (e.g., sender can have stale information).
=> [mesh-forwarder] use constant for `hopsLeft` in lowpan `MeshHeader`

src/core/thread/router_table.cpp
This commit updates the `RouterTable::RemoveRouter()` to check if `Router` being removed is a neighbor and signal its removal. This ensures that we correctly signal neighboring router removal from a call to either `UpdateRouterIdSet()` or `Release(aRouterId)`.
----
_Related note on this:_
- Method `RouterTable::RemoteRouterLink()` does not actually change the `State` of the neighboring router.
- It just changes the the Link Quality to zero (making the link unusable). 
- So even after `RemoveRouterLink()` the `Router` is still technically present in the `NeighborTable` (seen as a neighbor though we would never send any data frame to it directly due to its link quality being zero). 
- Such a Router will be removed later once it ages (when/if we fail to get MLE Adv from it and fail to …
=> [router-table] signal if router is removed from `UpdateRouterIdSet()`

src/cli/README.md, src/cli/cli.cpp, src/cli/cli_output.cpp, src/cli/cli_output.hpp
This commit adds a new CLI command `neighbor linkqulaity` which prints the collected link quality info (such as frame error rate, message error rate, average/last RSSI) for all neighbors.
=> [cli] add new command `neighbor linkquality`

include/openthread/border_routing.h, include/openthread/instance.h, src/cli/cli.cpp, src/core/api/border_routing_api.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/thread/network_data_types.cpp, src/core/thread/network_data_types.hpp
This commit updates how BR determines the preference to use when advertising Route Info Options (RIO) in emitted Router Advertisement (RA) messages.
User can explicitly set the preference by calling OpenThread API `otBorderRoutingSetRouteInfoOptionPreference()`.
But if not set or the previously set value is cleared by user, RIO preference is determined based on device's current role:
- Medium preference when device is in router/leader role,
- Low preference when in child role.
If a role change causes RIO preference to change, BR schedules to send a new RA using the updated RIO preference.
---
This is related to [SPEC-1126](https://threadgroup.atlassian.net/browse/SPEC-1126).
=> [routing-manager] determine RIO preference based on current role

src/core/border_router/routing_manager.cpp
This commit adds a new behavior in `RoutingManager` to skip performing NS probe with a router with an address belonging to device infra interface itself. This addresses the situation where platform may not be be able to receive and pass the NA message responses from device itself.
=> [routing-manager] add feature to skip NS probe with router on same device

src/core/thread/network_data_leader.cpp
This commit updates the `ExternalRouteLookup()` to ensure we pick the longest match before checking the route preference.
---
While updating some of the test scripts,  noticed that we may in some cases select a higher preference shorter off-mesh route match over a longer match. If I am not mistaken per spec we need to prefer a longer match (independent of preference) first and use the preference only if we have multiple options with same length. Here is the related text from section 5.10.2:
> - Find the External Route Set prefix(es) that have the longest prefix match to the IPv6 destination address.
> - If more than one External Route prefix matches, choose the one with higher preference (R_preference).
> - ...
Here is how this situation may happen in the code:
- In …
=> [network-data] ensure `ExternalRouteLookup()` picks longest match

src/core/net/ip6.cpp
This commit is fix to avoid dual processing on single TCP packet, added fix which restricts TCP packet to pass from opentghread stack. These changes are applicable only when openthread TCP stack is used and it is implemented under feature flag - OPENTHREAD_CONFIG_TCP_ENABLE
=> [tcplp] TCP support on 15.4 (#8590)

src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/network_data_leader.cpp
This commit updates `GetPathCost()` method to handle the cases where the destination RLOC16 is the device itself or if it is the child of the device. It also handles when the device itself is acting as a child (cost is calculated if destination is the parent).
This change addresses situation where `GetPathCost()` is used in `NetworkData::CompareRouteEntries()` to select between BRs (e.g., multiple BRs providing the same off-mesh route prefix) ensuring a direct child BR is preferred over other routers that are multiple hops away.
----
Background
Detected this situation when updating a test-case:
```
#
#
#
```
When we send from `r1` (to an address matching the off-mesh prefix)  noticed `r4` was being selected over `fed1` as the destination BR. Digging deeper figured out the issue with how …
=> [mle] update `GetPathCost()` calculation to handle child dest

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp
This commit adds a new helper method in `RxInfo` to check whether or not the `mNeighbor` field (the neighbor from which message was received) is non-null and in valid state.
=> [mle] add helper `RxInfo::IsNeighborStateValid()`

src/core/common/callback.hpp, src/core/common/notifier.cpp, src/core/common/notifier.hpp
This commit updates `Notifier` class to use the recently added `Callback<HandlerType>` for the external callbacks.
=> [notifier] update to use `Callback<HandlerType>`

src/cli/cli.cpp, src/cli/cli.hpp, tests/scripts/expect/cli-scan-discover.exp
This commit add `discover reqcallback {enable/disable}` CLI command
which registers callback to output whenever device gets a "MLE
Discovery Request". This command allows the callback to be explicitly
set when needed and avoid having it be enabled by default (since the
extra output from this callback can be treated as unexpected result by
tests that parse the CLI output).
---
(old text) 
~This commit removes the CLI code which generates an output whenever device gets a "MLE Discovery Request". These outputs can be treated as unexpected result by tests which parse the CLI output.~
---
This was added from https://github.com/openthread/openthread/pull/5131. I am not sure if this is helpful so opted to remove it from CLI. If we need this output, we should consider adding it under `CONFIG` or …
=> [cli] new command to enable/disable discovery request callback

src/posix/platform/openthread-posix-config.h
The ot-br-posix uses the posix platform's config file as its config file. So the ot-br-posix can't set different configurations with posix platform via the config file. This commit adds a config macro `OPENTHREAD_POSIX_CONFIG_FILE` for ot-br-posix to specify a config file to overwrite the posix platform's configurations.
=> [posix] add posix config file configuration

src/core/api/ip6_api.cpp, src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/net/tcp6.cpp
This commit updates `Ip6::SelectSourceAddress()`. A new version of is added which as its input gets a destination `Ip6::Address` instead of an `Ip6::MessageInfo`, and returns the selected source address as an `Ip6::Address *`. This helps simplify its use (no need to create or pass `MessageInfo` instances). This commit also moves the implementation of `otIp6SelectSourceAddress()` from `ip6_api.cpp` to `Ip6` class adding a version of `SelectSourceAddress()` which updates a passed-in `MessageInfo`directly.
=> [ip6] simplify `SelectSourceAddress()`

src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp
This commit contains smaller changes in `NetworkData::Leader` class:
- Use `FindNextMatchingPrefixTlv()` in methods to iterate over Prefix TLVs matching a given address.
- Simplify `IsOnMesh()` to iterate over Border Router sub-TLVs.
- Rename local variables to include `tlv` if they are a TLV.
=> [netdata] use `LeaderBase::FindNextMatchingPrefixTlv()`

.github/workflows/toranj.yml, src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_config.h, tests/toranj/cli/cli.py, tests/toranj/cli/test-004-scan.py, tests/toranj/cli/test-005-traffic-router-to-child.py, tests/toranj/cli/test-006-traffic-multi-hop.py, tests/toranj/cli/test-007-off-mesh-route-traffic.py, tests/toranj/cli/test-008-multicast-traffic.py, tests/toranj/cli/test-009-router-table.py, tests/toranj/cli/test-010-partition-merge.py, tests/toranj/cli/test-011-network-data-timeout.py, tests/toranj/cli/test-012-reset-recovery.py, tests/toranj/cli/test-013-address-cache-parent-switch.py, tests/toranj/cli/test-014-address-resolver.py, tests/toranj/cli/test-015-clear-addresss-cache-for-sed.py, tests/toranj/cli/test-016-child-mode-change.py, tests/toranj/cli/test-017-network-data-versions.py, tests/toranj/cli/test-601-channel-manager-channel-change.py, tests/toranj/cli/test-602-channel-manager-channel-select.py, tests/toranj/cli/test-603-channel-announce-recovery.py, tests/toranj/cli/test-700-multi-radio-join.py, tests/toranj/cli/test-701-multi-radio-probe.py, tests/toranj/cli/test-702-multi-radio-discover-by-rx.py, tests/toranj/cli/test-703-multi-radio-mesh-header-msg.py, tests/toranj/cli/test-704-multi-radio-scan.py, tests/toranj/cli/test-705-multi-radio-discover-scan.py, tests/toranj/openthread-core-toranj-config.h, tests/toranj/start.sh
This commit updates cli-based `toranj` test framework and adds new test-cases using this framework. The new test-cases re-implement all the current ncp/wpantund based ones that cover OpenThread core behavior (including the multi-radio and trel test-cases). Some of the tests are enhanced (e.g. adding new checks) and some related tests are combined into a single script.
This commit also updates the `toranj` CI GitHub workflow to use the new cli-based model for multi-radio and trel (removing the ncp based versions).
=> [toranj] add cli-based test-cases

src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/router_table.cpp, src/core/thread/router_table.hpp
This commit moves existing methods for cost and next hop calculation and updating router table entries to `RouterTable` class from `MleRouter`.
=> [router-table] move cost calc and related methods to `RouterTable`

src/cli/README.md, src/cli/cli.cpp
There's a use case to check the CSL state of one certain child from the parent. For now this can only be done by showing the full child table. This PR adds the CSL state in the display of single child info (cli command `child <id>`).
=> [cli] add csl info in single child info

src/lib/spinel/radio_spinel_impl.hpp, src/posix/platform/openthread-posix-config.h
This PR renamed the configuration `RCP_TIME_OFFSET_CHECK_INTERVAL`
to `OPENTHREAD_POSIX_CONFIG_RCP_TIME_SYNC_INTERVAL` and moved it to
posix configuration file because this configuration may need to be
configured on different platforms.
=> [posix] rename and move the configuration of host-rcp time sync interval

examples/platforms/simulation/radio.c, include/openthread/instance.h, include/openthread/link.h, include/openthread/platform/radio.h, src/core/radio/radio.hpp
This PR simplied the definition of `OT_RADIO_SYMBOL_TIME` and
provided the reference of the value from IEEE 802.15.4-2015.
=> [radio] refine the definition of SYMBOL_TIME

src/core/thread/network_diagnostic_tlvs.hpp
The `network_diagnostic_tlvs.hpp` defines the net diag TLVs and uses the public definitions (constants) from `openthread/netdiag.h` but did not include it directly. This commit ensures we include it directly.
=> [netdiag] include `netdiag.h` header in `network_diagnostic_tlvs.hpp`

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/router_table.cpp, src/core/thread/router_table.hpp, src/core/thread/topology.cpp, src/core/thread/topology.hpp, tests/toranj/cli/test-008-multicast-traffic.py
This commit adds new method `RouterTable::UpdateRoutesOnFed()` which
tracks cost towards all routers on an FED child based the parent's
cost towards them. This method is called whenever we receive an MLE
Advertisement from the parent (replacing the code which tracked the
cost only towards the leader) and also during attach process upon
receiving a Child ID Response containing `RouteTlv` from the parent.
This commit also updates `GetPathCost()` to handle more case:
- Where device is detached or disabled, we return `kMaxRouteCost`.
- If device is a child, we derive the path cost as the link cost
to the parent plus the cost from parent towards the destination.
- If device is a child and destination is another child of the
same parent, we use link cost to parent plus an estimated cost
towards …
=> [router-table] update cost on FED and enhance `GetPathCost()`

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
This commit contains smaller enhancements in `MleRouter` method
`HandleAdvertisement()` processing received MLE Advertisement
message:
- We remove all the `IsFullThreadDevice()` checks in this method
since it is only called from `Mle` when device is FTD (already
checked by `Mle` before calling).
- Also this method is called only when device is attached (in child,
router, or leader role). So we can simplify the checks related to
the device's role.
- We pass the already read TLV values (e.g., `LeaderDataTlv`) to
this method (to avoid re-reading the same TLVs from message).
-----
Added this on top of commit from PR https://github.com/openthread/openthread/pull/8629
=> [mle] simplify `HandleAdvertisement()`

src/core/thread/mle_router.cpp
This commit updates `MleRouter::HandleAdvertisement()` to not call `ExitNow()` and exit early when as a child we decide to try to promote to router role and set `mRouterSelectionJitterTimeout`. This ensures that we continue processing the message and call `UpdateRoutesOnFed()` and `router->SetLastHeard()`.
=> [mle] update `HandleAdv` to not exit when deciding to promote to router

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp
This commit contains smaller fixes and enhancements in `Mle` method `Mle::HandleAdvertisement()`
- We add `VerifyOrExit(IsAttached())` at the top of the method.
- We always perform the check for stale parent i.e., check if we got an MLE Advertisement from parent but with a different RLOC16. The `MleRouter` method also does the same check, however in certain cases (e.g., when there is Partition ID or leader ID mismatch) the `MleRouter` method will exit early and expect the `Mle` method to handle these cases.
- When on `Mle` method we handle Partition ID or leader ID mismatch and then process `RouteTlv` we now also call `UpdateRoutesOnFed()`.
=> [mle] always check for stale parent in `HandleAdv()`

src/core/thread/router_table.cpp, src/core/thread/router_table.hpp
This commit changes `RouterTable::UpdateRoutes()`. Before updating the routes, we track which routers have finite path cost. After the update we check again to see if any path cost changed from finite to infinite or vice versa and use this to decide whether to reset the MLE Advertisement interval. This helps simplify the code and handle some edge-cases related to resetting the Advertisement interval where changing the Link Quality on the neighbor may impact the cost towards routers which used it as next hop.
=> [router-table] simplify `UpdateRoutes()` and how to reset Adv interval

src/core/mac/mac_links.hpp, src/core/radio/radio.hpp
This commit applies to edge-case where OT is built with only TREL radio link and no 15.4 radio link.
We define `Radio::kDefaultReceiveSensitivity` as the default rx sensitivity value returned from `GetReceiveSensitivity()` and use the same constant for noise floor returned from `SubMac::GetNoiseFloor()`.
This ensures that fixed RSS value applied through `macfilter add-lqi` CLI command uses the same value for noise floor when calculating the typical RSS for a given Link Quality value.
=> [trel] use same constant for noise-floor under TREL radio link only

src/core/mac/link_raw.cpp, src/core/mac/link_raw.hpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/mac/mac_filter.cpp, src/core/mac/mac_filter.hpp, src/core/mac/sub_mac.hpp, src/core/mac/sub_mac_callbacks.cpp, src/core/thread/link_quality.hpp
This commit updates how we apply `Mac::Filter` ensuring the fixed RSS filter is applied to all rx frames including received ack frames.
We add a new method `Mac::Filter::ApplyToRxFrame()` which applies the filter rules directly to a rx frame, potentially updating its signal strength to a fixed RSS. This common method is then called from `Mac::HandleReceivedFrame()` replacing the existing code and also from `Mac::RecordFrameTransmitStatus()` to a received `aAckFrame`. This ensures that fixed RSS is correctly tracked on the corresponding neighbor.
This commit also updates `Mac::Filter` methods which do not change the `Filter` to be marked as `const`.
=> [mac] ensure to apply RSS filter on all rx frame including ack

src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle_router.hpp, src/core/thread/network_data_leader.cpp
This commit updates `CompareRouteEntries()` so that on MTD we replace the `PathCost()` check with a check to see if entry's RLOC matches the device itself. This handles the uncommon case where an MTD itself may be acting as a BR. This then allows us to remove the `MleRouter` `PathCost()` method (which on MTD was returning zero).
=> [netdata] update `CompareRouteEntries()` on MTD to prefer self

src/core/thread/mle_router.cpp
This commit updates `MleRouter` such that on promotion from REED to router role, we keep the router table's next hop and cost as what we had as a REED, i.e., our parent being the next hop towards all other routers and we tracked its cost towards them. As an FED, device may have also established links with a subset of neighboring routers. We ensure to clear the link to these neighbor to avoid using them since the neighboring router will drop messages from us till we re-establish link using our new RLOC16.
=> [mle] keep router table next hop and cost on REED to router promotion

src/core/mac/data_poll_sender.cpp, src/core/mac/mac.hpp, src/core/thread/mle.cpp
Make sure that retransmission of data polls happens at least at the CSL period rate, when this is lower than OPENTHREAD_CONFIG_MAC_RETX_POLL_PERIOD.
This greatly improves latency under situations of heavy traffic, where CSL synchronization might be lost ocassionaly due to the mix of CSL and indirect transmissions.
=> [data-poll-sender] faster rtx polling for CSL

include/openthread/instance.h, include/openthread/thread_ftd.h, src/cli/cli.cpp, src/core/api/thread_ftd_api.cpp, src/core/thread/router_table.cpp, src/core/thread/router_table.hpp, tests/toranj/cli/cli.py, tests/toranj/cli/test-018-next-hop-and-path-cost.py, tests/toranj/start.sh
This commit updates `RouterTable` to provide a common method to determine both the next hop and the path cost towards a given destination. This helps us combine and reuse similar code.
This commit also adds `otThreadGetNextHopAndPathCost()` as a new public OT API to get the next hop and path cost along with a related CLI command `nexthop`.
It also adds `test-018-next-hop-and-path-cost.py` in `toranj-cli` which validates the next hop and path cost calculation on different network topologies and from different nodes (FEDs, routers).
----
This PR current contains the commit from two changes/fixes in #8650 and #8651
(both issues were discovered from the newly added test running with trel radio only).
=> [router-table] new API to get next hop and cost

examples/platforms/utils/mac_frame.cpp, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/Makefile.am, src/core/common/frame_builder.cpp, src/core/common/frame_builder.hpp, src/core/mac/data_poll_sender.cpp, src/core/mac/mac.cpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/mac/mac_types.hpp, src/core/radio/trel_link.cpp, src/core/radio/trel_link.hpp, src/core/thread/link_metrics_types.cpp, src/core/thread/link_metrics_types.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, tests/unit/test_mac_frame.cpp
This commit updates how we prepare the MAC headers:
- New `enum`s are defined in `Mac::Frame` to specify the frame `Type`,  `Version`, `SecurityLevel`, etc.
- `InitMacHeader()` will itself determine the Frame Control Field from the given address info.
- It now uses `FrameBuilder` to prepare the headers.
- New helper `MeshForwarder::PrepareMacHeaders()` is added which takes care of adding MAC (address, security header) along with any IE headers.
- These changes ensure that PAN ID Compression bit is properly set on MAC frames when using 2015 version (ensure that PAN IDs are not omitted when both addresses use Extended format).
----
- IEEE802.15.4-2015 adds a new (special) cases related to how PAN ID Compression flag in FCF is interpreted 
- …
=> [mac-frame] update `InitMacHeader()`

src/core/mac/sub_mac.cpp
Fix some `uint32_t` variables using `%u` format when enable csl debug.
related: [[log] add compile-time check for printf style arg check to log functions](https://github.com/openthread/openthread/pull/8339)
=> [log] fix some print format when enable csl debug

src/core/net/ip6.cpp, src/core/net/ip6.hpp
This commit renames the method which passes a message to host by invoking the registered receive callback to `PassToHost()`. It also contains smaller style enhancements.
=> [ip6] style enhancements and renames

src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp
This commit updates `Ip6::HandleDatagram()` to check the device role to determine whether to allow messages received from the Thread mesh to be forwarded back to the Thread mesh. This is allowed only when device is acting as router or leader. This then lets us remove `SetForwardingEnabled()` method.
=> [ip6] check role to allow forwarding back to Thread

include/openthread/instance.h, include/openthread/link_raw.h, include/openthread/platform/radio.h, src/core/api/link_raw_api.cpp, src/core/mac/link_raw.cpp, src/core/mac/link_raw.hpp, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/radio/radio.hpp, src/core/radio/radio_platform.cpp, src/core/thread/key_manager.cpp, src/core/thread/key_manager.hpp, src/core/thread/mle.cpp, src/lib/spinel/radio_spinel.hpp, src/lib/spinel/radio_spinel_impl.hpp, src/lib/spinel/spinel.h, src/ncp/ncp_base_radio.cpp, src/posix/platform/radio.cpp
This commit adds a new radio platform API which updates the MAC Frame Counter only if the new value is larger than current value being used by radio platform, i.e., `otPlatRadioSetMacFrameCounterIfLarger()`. OT stack provides a default weak implementation of this API which calls the existing `otPlatRadioSetMacFrameCouter()`.
This API is used when radio provides `OT_RADIO_CAPS_TRANSMIT_SEC` capability and thereby is responsible for assigning the frame counter to tx frames. It helps address an edge-case where OT stack may not yet know of the latest frame counter values used by radio platform (e.g., due to enhanced acks processed by radio platform directly or due to delay between RCP and host) and then setting the value from OT stack may cause the counter value on radio to move back (OT …
=> [radio] new API to update frame counter only if new value is larger

src/core/net/ip6_mpl.cpp, src/core/net/ip6_mpl.hpp
This commit enhances/fixes how we validate an `OptionMpl` we read from a received message. In `Mpl::ProcessOption()`, we first ensure that we can read the minimum expected size of an MPL Option and then check based on the read Control field, the Seed ID length and ensure we can read the full `OptionMpl` under `kSeedIdLength2`.
=> [ip6-mpl] check the length when reading MPL Option

examples/platforms/simulation/diag.c, include/openthread/instance.h, include/openthread/platform/diag.h, src/core/diags/README.md, src/core/diags/factory_diags.cpp, src/core/diags/factory_diags.hpp, src/core/utils/power_calibration.cpp, src/core/utils/power_calibration.hpp, src/posix/platform/openthread-core-posix-config.h, src/posix/platform/radio.cpp, tests/scripts/expect/cli-diags.exp, tests/scripts/expect/posix-power-calibration.exp
The power calibration is supported by OT, this commit adds diag commands that are used to measure the mapping between the actual power and raw power settings, show the platform used power settings table.
<1> add "diag powersettings" to show the platform currently used power settings table.
<2> add "diag rawpowersetting" to make the platform to use the given raw power settings to transmit frames.
<3> add "diag cw" to transmit the continuous carrier wave.
=> [diag] add power calibration related diag commands

src/core/net/ip6.cpp, src/core/net/ip6_headers.hpp, src/core/net/ip6_mpl.hpp, src/core/thread/lowpan.cpp
This commit adds `GetSize()` to `Ip6::ExtensionHeader` and base class `OptionHeader`. This method returns the size (number of bytes) of the header/option. In case of `ExtensionHeader` the size is derived from "Length" field which is in 8-bye unit and does not count the first 8 bytes.
=> [ip6] add `GetSize()` to `ExtensionHeader` and `OptionHeader`

src/core/thread/csl_tx_scheduler.cpp
This commit contains two updates/fixes in `CslTxScheduler`:
In `CslTxScheduler::Update()` method, this commit adds a new call to `ResetCslTxAttempts()` on `mCslTxChild` when the current indirect message associated with the child gets changed (replaced or purged), while MAC is busy with tx of a CSL frame to this child. This ensures that the next CSL tx associated this child will be correctly treated as a new frame (and not a retx) and gets its own frame counter.
This commit also updates `HandleSentFrame()` to ensure that we always call `RescheduleCslTx()` from this method. `Update()` method is called whenever there is a change to the head of indirect message queue of any sleepy child. If we are not in the middle of CSL tx at MAC layer, `RescheduleCslTx()` is called immediately to determine …
=> [csl] reset tx attempt on `mCslTxChild` when msg is replaced/purged

include/openthread/instance.h, include/openthread/netdiag.h, src/cli/cli.cpp, src/core/thread/network_diagnostic.cpp, src/core/thread/network_diagnostic_tlvs.hpp
This commit updates the `ChildTableEntry` which is included in Network Diagnostic "Child Table TLV" to also provide the Link Quality In info for the child (using the unused two-bit field in the existing entry format).
-----
This is prototype PR as a proposal to update TLV entry definition in Thread spec.
Related to [SPEC-1128](https://threadgroup.atlassian.net/browse/SPEC-1128)
=> [net-diags] include link quality in child table entry

src/core/common/message.cpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/joiner_router.cpp, src/core/net/dns_client.cpp, src/core/net/icmp6.cpp
This commit updates multiple core modules to use the `Message` helper method `AppendBytesFromMessage()` to append bytes read from one message at a given offset and length to the end of another message.
----
This replaces the use `Message::CopyTo()` (which is not as readable).
=> [core] use `AppendBytesFromMessage()` to copy bytes between messages

src/cli/cli_tcp.cpp, src/cli/cli_tcp.hpp
This commit addresses two issues:
- Use agnostic crypto API regardless of `OPENTHREAD_CONFIG_CRYPTO_LIB` choice.
- Limits the configured ciphersuites in order to avoid client-server conflicts during handshake.
=> [cli-tcp] fix TLS configuration for different platforms

include/openthread/instance.h, include/openthread/thread.h, src/core/thread/topology.cpp
Included mLinkMargin in the otNeighborInfo struct to retrieve Link margin via otThreadGetNextNeighborInfo
=> [api] include `mLinkMargin` in `otNeighborInfo`

.github/workflows/posix.yml, .github/workflows/unit.yml
The tcplp test is not testing POSIX platform. This commit creates a new workflow unit to host this test. In future, we may put all unit tests in this workflow after automake support is removed.
=> [test] move tcplp tests into unit workflow

src/core/coap/coap_message.hpp, src/core/net/ip6.cpp, src/core/net/ip6_headers.hpp, src/core/net/ip6_mpl.cpp, src/core/net/ip6_mpl.hpp, src/core/thread/lowpan.cpp
This commit renames the `Ip6::Option` and its sub-classes, e.g., we use `MplOption` instead of `OptionMpl` to follow similar naming pattern as `Tlv`s.
----
This commit contains no logic/code change,  just a rename of types and variables.
=> [ip6] rename `Option` sub-classes

src/core/net/ip4_types.cpp, src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, tests/unit/test_ip_address.cpp
This commit updates comments to refer to correct RFC number. RFC 6052 instead of 6502 (typo in some comments).
=> [ip6] refer to correct RFC in comments/docs

.github/workflows/toranj.yml, tests/toranj/start.sh
This commit updates the github actions `toranj` workflow and the toranj `start.sh` script to trigger `toranj-ncp` tests on a Pull Request only if there are changes in any of the `src/ncp` files.
----
Follow-up from #8599 where all the main tests are re-implemented to use `toranj-cli` so we can limit the run of `toranj-ncp` only if there is any change in `ncp` source files.
This was tested in runs from https://github.com/openthread/openthread/pull/8647 -> [link to runs](https://github.com/openthread/openthread/actions?query=branch%3Agh%2Fconditional-toranj).
=> [github-actions] update `toranj-ncp` to trigger on pull request only

src/core/net/ip6_headers.cpp, src/core/net/ip6_headers.hpp, src/core/thread/lowpan.cpp
All sub-classes of `Option` provide `Init()` method to initialize the Option.
This commit also updates `Lowpan::CompressExtensionHeader()` to check that we did read an option from message before checking if it can be compressed.
=> [ip6] remove default constructor for `Ip6::Option`

src/core/net/ip6.cpp
In `InsertMplOption()` we need to insert the Option at the original end of Hop-by-hop Extension header which we track in `hbhSize`. Note that he read `hbh` is updated (we increment the `Length` field which increases the `hbh.GetSize()` by 8 bytes).
The code before this commit which inserted the header at the new `hbh.GetSize()` offset still works correctly since we copy all the bytes before the insertion offset back. It just copies more bytes than necessary.
=> [ip6] ensure to make room for new header at correct offset

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/mle_types.hpp, tests/scripts/expect/_common.exp, tests/scripts/thread-cert/Cert_5_3_06_RouterIdMask.py, tests/scripts/thread-cert/Cert_5_5_02_LeaderReboot.py, tests/scripts/thread-cert/Cert_5_5_03_SplitMergeChildren.py, tests/scripts/thread-cert/Cert_5_5_04_SplitMergeRouters.py, tests/scripts/thread-cert/Cert_5_5_07_SplitMergeThreeWay.py, tests/scripts/thread-cert/Cert_7_1_06_BorderRouterAsLeader.py, tests/scripts/thread-cert/Cert_9_2_15_PendingPartition.py, tests/scripts/thread-cert/Cert_9_2_16_ActivePendingPartition.py, tests/scripts/thread-cert/config.py, tests/scripts/thread-cert/test_detach.py, tests/scripts/thread-cert/test_history_tracker.py, tests/scripts/thread-cert/test_leader_reboot_multiple_link_request.py, tests/scripts/thread-cert/test_router_reboot_multiple_link_request.py, tests/scripts/thread-cert/test_set_mliid.py, tests/scripts/thread-cert/v1_2_test_backbone_router_service.py, tests/scripts/thread-cert/v1_2_test_csl_transmission.py, tests/scripts/thread-cert/v1_2_test_multicast_listener_registration.py, tests/toranj/ncp/test-017-parent-reset-child-recovery.py, tests/toranj/ncp/test-027-child-mode-change.py, tests/toranj/ncp/test-600-channel-manager-properties.py, tests/unit/test_routing_manager.cpp, tests/unit/test_srp_server.cpp
According to Thread 1.3.0 Section 4.7.1.3, router synchronization after reset requires the multicast link request message to be retransmitted until a response is received, or the maximum transmission limit has been reached. If the router was a leader or had more than 5 children prior to reset, it MUST be retransmitted as a critical message. Each multicast retransmission of an MLE Message on a TL1 or TL2 Link must be delayed by MLE_MULTICAST_RETRANSMISSION_DELAY multiplied by a random value between 0.9 and 1.1 with a resolution of at least 1 ms.
This PR implements the above requirement. With this requirement, in the cases when a router is reset and there is no other router to respond to the link request then it takes longer time for the router to join thread network. Thus some test cases …
=> [mle] retransmit link request after router reset

src/core/net/ip6.cpp, src/core/net/ip6_headers.cpp, src/core/net/ip6_headers.hpp, src/core/net/ip6_mpl.cpp, src/core/net/ip6_mpl.hpp, src/core/thread/lowpan.cpp
This commit contains changes related to handling of IPv6 Options. It adds a new method `Option::ParseFrom()` which parses and validates an IPv6 Option from a given message. This method handles the Pad1 Option as well as other Option Types. This makes it easier (and safer) to iterate through Options in an Extension Header. `Option::GetSize()` is also updated to return the correct size for Pad1 Option since Pad1 Option does not follow the common Option format (has Type field with no Length field).
This commit also adds a common `PadOption` class which based on the desired padding size uses Pad1 or PadN as its type. It also provides `InitToPadHeaderWithSize()` which prepares the option with proper length to pad an Extension Header with a given current size (also determining whether or not …
=> [ip6] add `Option::ParseFrom()` and common `PadOption`

src/core/thread/router_table.cpp, src/core/thread/router_table.hpp
This commit updates `RouterTable` class to use a `Tasklet` to track and signal when there is any change to the table, e.eg., new router added or removed and/or next hop or cost for a router gets changed.
=> [router-table] use `Tasklet` to signal changes

include/openthread/instance.h, include/openthread/thread_ftd.h, src/cli/cli.cpp, src/core/api/thread_ftd_api.cpp
This commit extends `nexthop` command such that when it is used without any input, it lists all currently allocated router IDs and the next hop and path cost for each. Note that this info is different from `router table` (which provides direct link along with any backup next hop option).
This commit also adds a new API `otThreadIsRouterIdAllocated()` to indicate whether or not a given router ID is currently allocated.
=> [cli] `nexthop` command to output next hop and path cost table

src/core/mac/mac.cpp
Fix bug that prevented to initialize CSL parameters for non-FTD builds.
=> [mac] ensure CSL parameters are initialized to zero

include/openthread/history_tracker.h, include/openthread/instance.h, src/cli/README_HISTORY.md, src/cli/cli_history.cpp, src/core/api/history_tracker_api.cpp, src/core/config/history_tracker.h, src/core/thread/router_table.cpp, src/core/thread/router_table.hpp, src/core/utils/history_tracker.cpp, src/core/utils/history_tracker.hpp
This commit adds anew feature in `HistoryTracker` to track the history of changes to routers. In particular we track when a new router is added or removed, or when next hop and/or path cost towards a router is changed. On a cost change the recorded entry, provides the old cost value along with the new path cost. This helps to track the cost changes more easily (no need to look back at history to find the old cost value).
This commit also adds CLI command `history router` for the new feature.
=> [history-tracker] track changes to router table (next hop, cost)

examples/apps/cli/main.c, examples/platforms/simulation/radio.c, tests/toranj/cli/cli.py
This commit updates the custom CLI command `nodeidfilter` defined for simulation platform enabling filtering at radio level. This commit enhances this command so it can be used as both a deny-list or an allow-list. It also adds support to output the list and filter mode when no arg is given.
=> [simul-platform] enhance radio `nodeidfilter` command

src/core/thread/network_diagnostic.cpp, src/core/thread/network_diagnostic.hpp, src/core/thread/network_diagnostic_tlvs.hpp
This commit contains smaller enactments in `NetworkDiagnostic` class:
- `SendCommand()` method is updated to accept a `Uri` for the intended diag command.
- `PrepareMessageInfoForDest()` method is added which prepares a `Tmf::MessageInfo` for sending diag commands to a destination deciding which source address to use.
- The TLV class is renamed to `Tlv` from `NetworkDiagnosticTlv` (since it is under the namespace `NetworkDiagnostic` already). This makes it similar to TLVs from other modules, `Mle::Tlv`, `MeshCoP::Tlv`, etc).
- Logging in `NetworkDiagnostic` is updated and simplified, now using `Log(Action, Uri)` method. The logs provide more info like the IP6 address of sender/receiver of a message.
=> [net-diag] simplify `NetworkDiagnostic`

include/openthread/instance.h, include/openthread/trel.h, src/cli/cli.cpp, src/core/api/trel_api.cpp, src/core/radio/trel_interface.cpp, src/core/radio/trel_interface.hpp
This is a follow up PR of https://github.com/openthread/ot-br-posix/pull/1708#discussion_r1067685893 to add `otTrelSetEnabled` API.
=> [trel] add `otTrelSetEnabled` API

tools/harness-simulation/harness/Thread_Harness/Sniffer/SimSniffer.py, tools/harness-simulation/posix/sniffer_sim/proto/sniffer.proto, tools/harness-simulation/posix/sniffer_sim/sniffer.py
This commit keeps capture files in sync at runtime. Therefore, Harness can obtain the addresses directly from the capture files in manual DUT mode without having to enter the addresses manually.
=> [harness-simulation] keep capture files in sync at runtime

src/cli/cli.cpp, src/cli/cli_coap.cpp, src/cli/cli_coap_secure.cpp, src/core/api/backbone_router_ftd_api.cpp, src/core/common/message.cpp, src/core/crypto/crypto_platform.cpp, src/core/diags/factory_diags.cpp, src/core/thread/mlr_manager.cpp, src/lib/spinel/radio_spinel_impl.hpp
This PR uses `Min` and `Max` from num_utils to replace Ternary operators.
=> [code-utils] use `num_utils` `Min`/`Max` to simplify code

tests/unit/test_srp_server.cpp
This commit updates `PrepareService()` functions to `memset` the `Service` instance to zero before populating its fields. This ensures that all new properties (e.g., recently added `mLease`/`mKeyLease`) are set to zero and use the corresponding default value.
=> [test] update `test_srp_server` to clear the service instances

src/core/mac/data_poll_handler.cpp
Bugfix for an issue where any frame which fails CSL transmission  gets treated as a new frame (instead of a retransmission) for a subsequent indirect retransmission (in the data poll handler). This fix checks for the previous CSL transmit attempts and if it is greater than 0, retransmits with the same frame counter, sequence number and key id as previous attempt.
=> [csl] fix indirect retransmission of frame previously transmitted via CSL

tests/scripts/thread-cert/border_router/test_trel_connectivity.py, tests/scripts/thread-cert/node.py
There is work planned in ot-br-posix to set trel to disabled at start if feature flags are used. 
This PR updates the test_trel_connectivity to set trel to enabled if it's disabled by default.
=> [test] allow TREL disabled by default

include/openthread/instance.h, include/openthread/trel.h, src/core/api/trel_api.cpp
Removed deprecated `otTrelEnable/otTrelDisable` apis
(In a previous PR the comment for `otTrelIsEnabled` was removed by accident, restored the comment.)
=> [trel] remove deprecated `otTrelEnable`/`otTrelDisable` APIs

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit updates `ProcessNeighborAdvertMessage()` method in `RoutingManager` to use the Target Address included in Neighbor Advertisement to find the related `Router` (instead of sender's IPv6 address). This addresses situations where the router responding may use a different address.
---
Please check https://github.com/openthread/openthread/issues/8773#issuecomment-1435379150 for more details.
=> [routing-manager] use NA target address

script/test
This PR lets `do_build_otbr_docker()` skip unnecessary files when copying the source code for building a docker image. It can save time and disk space for the user.
=> [docker] avoid unnecessary copying when building an image for testing

src/core/net/ip6.cpp, src/core/net/ip6.hpp
This commit updates `HandleDatagram()` simplifying the code related to determining `forwardThread` and `forwardHost` based on the destination address.
=> [ip6] simplify `Ip6::HandleDatagram()`

src/cli/README_DATASET.md
The dataset examples are generated by version 1.1 OT stack where the Security Policy value has length of 3 bytes but 1.2 extends it to 4 bytes.
The real problem is that spec requires that **ZERO** Key Rotation **SHALL NOT** be allowed:
```
Key rotation period in hours. The
minimum key rotation period SHALL be
1 hour and a key rotation period of 0
SHALL NOT be allowed.
```
But the example is using ZERO.
This commit fix this by updating the examples to 1.2 version. This commit fix also problems that incomplete TLV HEX string (Pending Timestamp and Delay Timer are missing) are used for setting the Pending Dataset (e.g. `dataset set pending`).
=> [cli] update dataset readme with the latest output

src/core/config/commissioner.h, src/core/meshcop/commissioner.cpp, src/core/meshcop/commissioner.hpp
This PR adds a session timeout for the integrated Commissioner.
When the Joiner and Commissioner have a weak link, and the session doesn't time out after a communication failure, the Joiner may fail to join in subsequent attempts if the Commissioner is not stopped and restarted. With the proposed modification, the Commissioner times out the session after a configurable time, so the Joiner may be able to join in a future attempt.
Please see https://github.com/openthread/openthread/discussions/8763 for context.
=> [commissioner] add joiner session timeout

src/posix/platform/CMakeLists.txt, src/posix/platform/memory.cpp
The `openthread-posix` library calls OT public APIs and library APIs (e.g. radio_spinel, HDLC), but it doesn't link against the library targets.
------
This commit also adds `extern "C"` for posix impl of `otPlatFree` and `otPlatCAlloc`.
=> [posix] add missing dependencies to "openthread-posix" target

src/core/api/backbone_router_ftd_api.cpp, src/core/backbone_router/bbr_leader.cpp, src/core/backbone_router/bbr_leader.hpp, src/core/backbone_router/bbr_local.cpp, src/core/backbone_router/bbr_local.hpp, src/core/backbone_router/bbr_manager.cpp, src/core/backbone_router/multicast_listeners_table.cpp, src/core/backbone_router/multicast_listeners_table.hpp, src/core/backbone_router/ndproxy_table.cpp, src/core/backbone_router/ndproxy_table.hpp, src/core/thread/dua_manager.cpp, src/core/thread/dua_manager.hpp, src/core/thread/mlr_manager.cpp, src/core/thread/mlr_manager.hpp, src/core/thread/network_data_service.cpp, src/core/thread/network_data_service.hpp
This commit defines C++ style types for use in core module mirroring the public OT C definitions. It also contains renames and smaller enhancements in BackBone Router modules.
=> [backbone-router] define C++ enum/types mirroring public definitions

src/core/thread/network_diagnostic.cpp, src/core/thread/network_diagnostic.hpp
This commit adds `AppendDiagTlv()` to append a dig TLV with a given type to a `Message`. It also simplifies the `AppendRequestedTlvs()` to directly parse the "Type List TLV".
=> [net-diag] define `AppendDiagTlv()`

include/openthread/border_routing.h, include/openthread/instance.h, src/cli/BUILD.gn, src/cli/CMakeLists.txt, src/cli/Makefile.am, src/cli/README.md, src/cli/README_BR.md, src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_br.cpp, src/cli/cli_br.hpp, src/core/api/border_routing_api.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, tests/scripts/thread-cert/node.py, tools/harness-thci/OpenThread.py
This commit adds new public OT APIs in `border_routing.h` to get the
current state of `RoutingManager` and to get the current favored
on-link prefix.
This commit also updates CLI `br` commands:
- It moves the CLI `br` implementation into own `cli_br` module.
- It adds `br state` to get the current state
- It changes `br omrprefix`, `br onlinkprefix`, and `br nat64prefix`
to output both local and favored prefixes when no additional arg
is provided and allow the use of `local` or `favored` extra arg to
specify the type.
- It updates the documentation of `br` related commands in the source
code and in `cli/README_BR.md`.
=> [routing-manager] new APIs to get state and new CLI commands

src/core/api/network_time_api.cpp, src/core/thread/time_sync_service.cpp, src/core/thread/time_sync_service.hpp
This PR defines C++ style types for TimeSync module mirroring the public OT C definitions to follow the OT style.
=> [time-sync] define cpp enum/types mirroring public definitions

include/openthread/instance.h, include/openthread/message.h, src/cli/README.md, src/cli/cli.cpp, src/core/api/message_api.cpp, src/core/common/instance.cpp, src/core/common/instance.hpp, src/core/common/message.cpp, src/core/common/message.hpp
This commit updates `MessagePool` to track number of in use buffers
along with max used so far since OT stack initialization or since
last time counter was reset. This info is then provided in
`otBufferInfo` and in CLI command `bufferinfo`. A new OT API
`otMessageResetBufferInfo()` is added to reset this counter.
----
This info can be useful to tell how much of the buffer pool is used during operation.
=> [message-pool] track max used buffers

src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/mle_types.hpp
This commit contains smaller enhancements in `MleRouter` class, defining `kChallengeTimeout` constant, using ternary `? :` replacing `if/else` checks, combining `#if` blocks, etc.
=> [mle] smaller enhancements

src/cli/cli.cpp
Invalid Doxygen tag from #8796 breaks the reference import into openthread.io (all commands documented before it are being dropped).
@kylorene for viz
=> [cli] fix bad CLI command tag

src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
`SetStateRouter()` and `SetStateLeader()` share a bunch of common code (things that need to be updated on transition to either router or leader role). This commit adds `SetStateRouterOrLeader()` method for this.
=> [mle-router] add common `SetStateRouterOrLeader()`

script/clang-format
`script/clang-format` is supposed to add an EOF newline for every file passed in as an argument. However, the script only processed the first file. This can cause `script/make-pretty check` to fail even after `script/make-pretty clang`.
=> [pretty] fix `script/clang-format`

doc/ot_api_doc.h
New API module from #8668 wasn't added to the high-level Doxygen menu.  This causes the module to show up incorrectly when we import reference docs into openthread.io.
@kylorene for viz
=> [docs] add plat-dns module to Doxygen menu

src/cli/README.md
Explain dns-sd proxy zone with an example.
=> [docs] dns browse: explain dns-sd proxy zone

src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, tests/scripts/thread-cert/Cert_5_1_01_RouterAttach.py, tests/scripts/thread-cert/Cert_5_2_04_REEDUpgrade.py, tests/scripts/thread-cert/Cert_5_3_06_RouterIdMask.py, tests/scripts/thread-cert/Cert_5_5_02_LeaderReboot.py, tests/scripts/thread-cert/Cert_5_5_05_SplitMergeREED.py, tests/scripts/thread-cert/Cert_7_1_07_BorderRouterAsLeader.py, tests/scripts/thread-cert/test_router_multicast_link_request.py, tests/scripts/thread-cert/v1_2_router_5_1_1.py
This PR contains 3 related commits:
**[test] update tests impacted by the changes**
- `v1_2_router_5_1_1`
- `Cert_5_1_01_RouterAttach`
- `Cert_5_2_04_REEDUpgrade`
- `Cert_5_5_02_LeaderReboot`
- `Cert_5_5_05_SplitMergeREED`
**[mle] accept former child as router on receiving advertisement**
This commit updates `Mle` so if we receive an MLE advertisement
from a former child (which is recently get promoted to router)
to accept it immediately and copy the info from `Child` entry to
`Router`.
**[mle] send MLE Advisement on promotion to router role**
This commit updates `MleRouter` to send an immediate MLE Advertisement
on promotion to `router` role and assignment of new Router ID. This
helps inform our former parent of our newly allocated Router ID and
cause it to reset it own advertisement …
=> [mle] send MLE adv on promotion router role / accept former child as router

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/topology.hpp
This commit adds a helper method `MleRouter::InitNeighbor()` which perform common initialization done using `RxInfo` like setting the Extended MAC address from the sender's IPv6 address IID, updating the `LinkInfo`, and setting `LastHeard` time. This method is used from different methods in `MleRouter` where a new neighbor (router or child) is initialized.
=> [mle] add `InitNeighbor()` method

include/openthread/instance.h, include/openthread/netdata.h, src/cli/README_NETDATA.md, src/cli/cli_network_data.cpp, src/core/api/netdata_api.cpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp, src/core/thread/network_data_leader_ftd.cpp
This commit adds new mechanism in `NetworkData::Leader` to track the the maximum observed length of the Thread Network Data since OT stack initialization or since the last time user reset the tracking mechanism by calling `otNetDataResetMaxLength()`. This commit also adds public OT API and  CLI commands for this.
=> [netdata] mechanism to track max Network Data length since start/reset

include/openthread/instance.h, include/openthread/platform/radio.h, src/core/mac/mac_frame.hpp, src/core/mac/sub_mac.cpp, src/core/thread/csl_tx_scheduler.cpp, src/core/thread/mesh_forwarder.cpp, src/lib/spinel/radio_spinel_impl.hpp, src/lib/spinel/spinel.h, src/ncp/ncp_base_radio.cpp
This commit adds `mRxChannelAfterTxDone` in `otRadioFrame` which specifies the RX channel  after frame TX is done (after all retries and ack received).
This is intended for situations where they may be delay in interactions between OT stack and radio, as example this is used in RCP and host architecture to make sure RCP switches to PAN channel more quickly. In particular, this can help with CSL tx to a sleepy child, where the child may use a different channel for CSL than the PAN channel. After frame tx, we want the radio/RCP to go back to PAN channel quickly to ensure that parent does not miss any tx from child afterwards, e.g., child responding to the earlier CSL transmitted frame from parent using PAN channel while radio still staying on CSL channel.
This commit adds support for the …
=> [radio] mechanism to switch to PAN channel more quickly after CSL tx

include/openthread/instance.h, include/openthread/mesh_diag.h, include/openthread/netdiag.h, src/cli/README.md, src/cli/cli.cpp, src/core/thread/network_diagnostic.cpp, src/core/thread/network_diagnostic_tlvs.hpp, src/core/utils/mesh_diag.cpp, src/core/utils/mesh_diag.hpp
This commit adds support for Net Diag Version TLV (TLV number 24) which returns the Thread version of device (as `uint16_t`). It also updated the `MeshDiag` to query for the Version TLV and provide it in `otMeshDiagRouterInfo`. The related CLI commands are also updated.
----
This is related to [SPEC-1146](https://threadgroup.atlassian.net/jira/core/projects/SPEC/issues/SPEC-1146).
=> [mesh-diag] add Net Diag Version TLV

src/core/net/srp_server.cpp
Build errors are raised by arm-none-eabi-gcc 10 toolchain when building with -Og option and this commit aims to fix them:
```
/ot/openthread/src/core/net/srp_server.cpp:906:12: error: 'error' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  906 |     return error;
      |            ^~~~~
/ot/openthread/src/core/net/srp_server.cpp: In member function 'void ot::Srp::Server::CommitSrpUpdate(ot::Error, ot::Srp::Server::Host&, const ot::Dns::UpdateHeader&, const ot::Ip6::MessageInfo*, const ot::Srp::Server::TtlConfig&, const ot::Srp::Server::LeaseConfig&)':
/ot/openthread/src/core/net/srp_server.cpp:526:25: error: 'grantedKeyLease' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  526 |             SendResponse(aDnsHeader, grantedLease, …
```
=> [srp-server] fix -Werror=maybe-uninitialized

src/posix/Makefile-posix
Use the command `make -f src/posix/Makefile-posix` to build the POSIX platform on macOS, it generates the warning `-Wunused-command-line-argument` (refer to #8828).
This commit moves the linker option `-rdynamic` from `COMMONCFLAGS` to the `LDFLAGS` to remove the warning.
Fixes #8828
=> [build] fix the warning `-Wunused-command-line-argument` on macOS

include/openthread/dataset.h, include/openthread/instance.h, src/cli/README_DATASET.md, src/cli/cli_dataset.cpp, src/core/api/dataset_api.cpp
This commit adds `otDatasetConvertToTlvs()` to covert a given Operational Dataset `otOperationalDataset` to TLVs. It also adds a related CLI command `dataset tlvs`.
=> [dataset] add `otDatasetConvertToTlvs()` API

src/core/utils/mesh_diag.cpp, src/core/utils/mesh_diag.hpp
This commit updates `kMaxTlvsToRequest` constant to account for the recently added `VersionTlv`. It also moves its definition from header file to cpp file in `SendDiagGetTo()` method so to make it easier to track and update it when/if new TLV types are added.
=> [mesh-diag] update `kMaxTlvsToRequest` constant

src/core/thread/network_data_leader_ftd.cpp
This commit updates `NetworkData::Leader::HandleTimer()` such that once the reuse delay time for a previously used Context ID is reached and the ID is freed, the `mContextLastUsed` is also set to zero. This ensures that context ID is freed only once from `HandleTimer()`(which avoids incrementing the version again).
----
This is follow up from https://github.com/openthread/openthread/pull/8859 (reading the related code we noticed this situation).
=> [netdata] ensure to free context ID once

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/router_table.cpp, src/core/thread/router_table.hpp
This commit updates how we process Route TLV in a received "MLE Link Accept" message when device is already acting as router or leader:
- We ensure that the Router ID Sequence number in the received Route TLV is more recent compared to the current one being used before adopting the Router ID Set. We still update the router table (next hops and costs) based on the received Route TLV even if Sequence number is older.
- We also check that the ID of the router which sent the Link Accept is marked as allocated in the Route TLV that it includes in the message. This protects against an edge-case where the sending router may be misbehaving.
In addition to the above two changes, this commit contains some enhancements and simplifications:
- `RxMessage::ReadRouteTlv()` is added which reads and …
=> [mle] update and enhance processing of Route TLV

include/openthread/instance.h, include/openthread/tcp.h
This commit updates the documentation for `otTcpConnect()` indicating that caller need to wait for `otTcpEstablished` callback indicating that TCP connection was established  before it can start sending data (e.g., calling `otTcpSendByReference()`).
It also removes the mention of "TCP Fast Open" which is not yet supported.
----
@samkumar can you please check/verify this?
- I think "fast open" is not yet supported. I see in `Tcp::Endpoint::Connect()` we ignore `aFlags` (we have `OT_UNUSED_VARIABLE(aFlags);`)
- Also `otTcpSendByReference()` cannot be called until connection is established
- `SendByReference()` calls `tcp_usr_send()` which has this `tp->t_state` check:
```c++
/*
* samkumar: This if statement and the next are checks that I added
*/
if (tp->t_state < TCPS_ESTABLISHED) {
error …
```
=> [tcp] update `otTcpConnect()` doc to indicate currently supported behavior

src/core/mac/sub_mac.cpp
The current code in `SubMac::HandleCslTimer` is not very intuitive.
This PR adds some explanation of the mechanism in the comment.
=> [csl] add code comment & explanation for `HandleCslTimer`

src/core/config/mac.h, src/core/mac/mac.hpp
This setting is targeted for SEDs which may need to decrease the timeout for receiving a Data Frame (which follows an ACK with FP bit set) for power saving reasons.
IEEE 802.15.4/2015 specification doesn't enforce a specific timeout value for this parameter so the application should be able to configure it.
=> [mac] add build config for timeout for receiving a Data Frame

src/core/thread/mle_router.cpp, src/core/thread/mle_tlvs.cpp, src/core/thread/mle_tlvs.hpp
This method helps when preparing the `ConnectivityTlv` and counting the neighbors with which device shares a link at different Link Quality values (1,2,3).
=> [mle] add `IncrementLinkQuality()` to `ConnectivityTlv`

include/openthread/instance.h, include/openthread/netdata.h, src/cli/README_NETDATA.md, src/cli/cli_network_data.cpp, src/cli/cli_network_data.hpp, src/core/api/netdata_api.cpp, src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_types.cpp, src/core/thread/network_data_types.hpp, tests/scripts/thread-cert/node.py, tests/toranj/cli/cli.py, tools/harness-thci/OpenThread.py, tools/otci/otci/otci.py
This commit adds `otNetDataGetNextLowpanContextInfo()` to iterate through the list of LoWPAN Context entries in Thread Network Data providing info about the prefix, its LoWPAN Context ID and Compress flag (relating to `ContextTlv` sub-TLVs of `PrefixTlv`s in Network Data).
This commit also updates CLI command `netdata show` to list the context IDs in addition to prefixes, routes, and services.
=> [netdata] new API to get lowpan context IDs

src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp, tests/toranj/cli/test-019-netdata-context-id.py, tests/toranj/start.sh
This commit simplifies how the 6LoWPAN Context IDs are assigned and
tracked by `NetworkData::Leader` using a new nested class
`ContextIds`. A Context ID can be in one of the 3 states:
- It is unallocated.
- It is allocated and in-use.
- It is scheduled to be removed (after reuse delay interval).
This commit also adds a test-case `test-019-netdata-context-id.py`
which validates the assignment and removal of Context IDs under
different scenarios.
--------
~- This PR contains the commit from https://github.com/openthread/openthread/pull/8870.~
~- Please read and review the last commit.~
=> [netdata] simplify tracking of lowpan context IDs

src/core/thread/mle_tlvs.cpp, src/core/thread/mle_tlvs.hpp
This commit updates `ConnectivityTlv` methods which get/set the Parent Priority field (high, medium, low). This change ensures that we do not use bitwise shift of a signed and potentially negative value (`a >> b` where `a` is negative). Note that the behavior of right bitwise shift of a negative value is not specified by C++ standard and it is implementation/toolchain dependent.
=> [mle] update how we set/get Parent Priority on `ConnectivityTlv`

src/core/thread/dua_manager.cpp
If there is no DUA request sent/scheduled to be sent, then there is no need to trigger the periodic one second ticker timer.
This helps SEDs to be more power efficient and to avoid unnecessary wakeups.
=> [dua] avoid unnecessary time ticker processing

src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/thread/child_supervision.cpp, src/core/thread/thread_netif.cpp, src/core/thread/thread_netif.hpp
This commit simplifies `ThreadNetif` class by removing methods like `IsOnMesh()` and `SendMessage()` which just call the same method on other modules (`NetworkData::Leader` and `MeshForwarder`). It also moves the `RouteLookup()` method to `Ip6` class.
=> [netif] simplify `ThreadNetif`

src/core/thread/dua_manager.cpp, src/core/thread/mle.cpp
Fix for the following bug:
Leader/Parent (OTBR) is reset (taken off the network), leading to its MTD child being detached. When the parent is brought back on the network without configuring the previous DUA prefix, the MTD asserts complaining that its DUA prefix is not valid anymore.
1. We don't assert anymore in this situation, rather the MTD just won't include the DUA address in its address registration TLV.
2. More importantly, we remove a "cached" DUA address if we find that the network leader is no longer configured with a DUA prefix.
=> [dua] remove DUA address if network data no longer contains DUA prefix

etc/cmake/options.cmake, include/openthread/instance.h, include/openthread/thread_ftd.h, src/cli/README.md, src/cli/cli.cpp, src/core/api/thread_ftd_api.cpp, src/core/config/misc.h, src/core/config/mle.h, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/mle_types.cpp, src/core/thread/mle_types.hpp, tests/unit/CMakeLists.txt, tests/unit/test_mle.cpp
This commit adds `otDeviceProperties` which represents a set of device
configurations which are used to calculate and set the local Leader
Weight on the device.
The device config contains a `otPowerSupplyConfig` enum value
specifying the device power supply:
- Battery powered.
- Externally powered (mains-powered).
- Stable external power with a battery backup or UPS.
- Unstable external power (e.g., a light bulb powered via a switch).
It also indicates whether or not device is a border router, supports
CCM, and specifies a Leader Weight adjustment value.
The `otDeviceProperties` can be set through the newly added OT public API
`otThreadSetDeviceProperties()`. Its default value (upon OT stack start)
can also be configured using OT configs:
- Newly added …
=> [mle] add `otDeviceProperties` to calculate local leader weight

src/core/radio/trel_interface.cpp
This commit adds checks to protect against an edge-case where TXT data entries from a TREL peer mat contain invalid and long keys. If the TXT data happens to include keys longer than `Dns::kMaxKeyLength`, the `mKey` in `Dns::TxtEntry` will be set to `nullptr` and the entire entry will be provided in `mValue`. This commit adds code to skip over such entries (check that `entry.mKey` is not null) at beginning of the loop to avoid using a potential null `mKey` in `strcmp`.
=> [trel] protect against invalid long TXT data keys from TREL peer

src/core/common/tlvs.cpp
This commit fixes `ReadStringTlv()` avoid returning an extra character and making sure `\0` is added at the correct index at `[length]`.
----
This is not critical since `StringTlv` is currently only used for "vendor name, model" etc in MeshCoP (part of joining/commissioning process).
=> [tlv] fix `ReadStringTlv()`

src/core/net/dns_types.cpp, src/core/net/dns_types.hpp, src/core/net/srp_client.cpp, src/core/net/srp_client.hpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, tests/unit/test_srp_server.cpp
This commit updates SRP client and server to support short variant format for Update Lease Option. The short variant includes the lease interval only (4 bytes) vs the long variant which includes both lease and key lease intervals (8 bytes). Client and server can parse and process both formats in received messages. Client by default uses the long variant. Server will also use the long variant in its response unless the request message uses the short variant format, i.e., if the client uses the short variant, the server will also respond using the short variant. This behavior is required by the latest Update Lease draft.
This commit also updates `test_srp_server` unit test, adding a new test-case to validate the behavior of client and server when short Update Lease Option is used. A new …
=> [srp] add support for short (4-bytes) lease option variant

src/core/mac/sub_mac.cpp, src/core/utils/history_tracker.cpp
cc for code review: @jwhui @abtink
=> [logging] fix print format for some variables requiring `%u` or `%lu`

src/cli/cli.cpp
Fixes an issue where the word "Joiner" was being linked in the description for the `parent` CLI command.
=> [docs] disable Doxygen autolink for the word "Joiner"

src/core/net/ip6.cpp
The added log may assist in diagnosing problems where packet transmission over the air is absent.
OpenThread quietly discards the packet when a valid route is not found. This happened recently in Matter testing where the Border Router sent an IPv6 packet to the Thread node, but had improperly set up external routes and/or had not been designated as the default route.
=> [netif] add diagnostic log for when no valid route is found

include/openthread/instance.h, include/openthread/thread.h, src/core/mac/sub_mac.cpp, src/core/thread/discover_scanner.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mle_router.cpp, tests/scripts/expect/_common.exp, tests/scripts/expect/cli-discover.exp, tests/scripts/expect/cli-multicast-loop.exp, tests/scripts/expect/cli-scan.exp, tests/scripts/expect/posix-rcp-restoration.exp, tests/scripts/expect/posix-scan-tx-to-sleep.exp, tests/scripts/expect/tun-realm-local-multicast.exp, tests/scripts/expect/tun-sntp.exp, tests/scripts/expect/tun-udp.exp
Currently, MLE Discovery does not work for SED or SSED devices (#8614).
This PR is a simple attempt to address the issue by:
- turning off Data Polling and turning on the receiver for the SED device during discovery (to receive MLE Discovery Response)
- disabling including CSL IE and Auxilary Security Header in the MLE Discovery Request
- make sure Routers transmit MLE Discovery Response as a direct unicast message (e.g. currently it is sent as an indirect message to SED children).
So far tested with a simulated platform and CLI.
=> [discovery] allow (S)SED devices to perform MLE Discovery

script/test, src/posix/platform/resolver.cpp, tests/scripts/thread-cert/border_router/nat64/test_single_border_router.py, tests/scripts/thread-cert/border_router/nat64/test_upstream_dns.py, tests/scripts/thread-cert/border_router/test_dnssd_instance_name_with_space.py, tests/scripts/thread-cert/border_router/test_dnssd_server.py, tests/scripts/thread-cert/border_router/test_dnssd_server_multi_border_routers.py, tests/scripts/thread-cert/node.py
This commit adds a new file `tests/scripts/thread-cert/border_router/nat64/test_upstream_dns.py` to test scripts for testing the DNS forwarding functions.
The test adds a record `test.domain` to the bind9 interface since when adding to DNSSD tests, the OpenThread's DNSSD server will be conflict with the Docker's DNS forwarding functions.
=> [test] add tests for DNS forwarding

src/core/thread/network_data_leader_ftd.hpp, tests/toranj/cli/cli.py, tests/toranj/cli/test-019-netdata-context-id.py
This commit changes the context ID reuse delay from 48 hours to 5 minutes. It also updates `test-019-netdata-context-id.py` to check the default value.
----
Related to [SPEC-1163](https://threadgroup.atlassian.net/browse/SPEC-1163).
=> [network-data] change 6LoWPAN context ID reuse delay to 5 minutes

include/openthread/instance.h, src/core/config/mac.h, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/radio/radio.hpp, src/core/thread/csl_tx_scheduler.cpp, src/core/thread/mle_tlvs.hpp
This commit fixes CSL operations timing taking into account that the
CSL phase should refer to the beginning of the SHR.
On the CSL transmitter, corrects the transmission delay timing taking
into account that the timestamp of the received frame from the CSL
receiver refers to the start of the PHR.
On the CSL receiver, no changes are needed assuming the platform
injects the proper CSL phase value.
=> [csl] take into account radio header for aiming at the CSL phase

include/openthread/dns_client.h, include/openthread/instance.h, src/cli/README.md, src/cli/cli.cpp, src/cli/cli.hpp, src/core/config/dns_client.h, src/core/net/dns_client.cpp, src/core/net/dns_client.hpp, src/core/net/dnssd_server.cpp, src/core/net/dnssd_server.hpp, tests/scripts/expect/tun-dns-over-tcp-client.exp, tests/unit/CMakeLists.txt, tests/unit/test_dns_client.cpp
This commit updates DNS client to add `otDnsServiceMode` to the `otDnsQueryConfig`. This new config property determines which records to query and allow the API user to control the behavior during service resolution: We can query for SRV record only or TXT record only, or query for both SRV and TXT records in the same message, or in parallel in different messages, or an "optimized" mode where client will first try to query for both records together in the same message but if server responds with an error, it then retries using two parallel separate queries.
This gives flexibility and control to the API user. It also helps address situations where the server (DNS resolver) may not accept queries with more than one questions.
To support this new feature, this commit updates and enhances the …
=> [dns-client] add `ServiceMode` to control service resolution

src/lib/spinel/openthread-spinel-config.h
This commit adds the openthread config header file to the spinel config file to allow developers to configure the spinel configurations in the openthread config file.
=> [spinel] add openthread config header file

src/core/meshcop/announce_begin_client.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/energy_scan_client.cpp, src/core/meshcop/joiner.cpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/meshcop_leader.cpp, src/core/meshcop/panid_query_client.cpp, src/core/thread/address_resolver.cpp, src/core/thread/announce_begin_server.cpp, src/core/thread/dua_manager.cpp, src/core/thread/energy_scan_server.cpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_notifier.cpp, src/core/thread/network_diagnostic.cpp, src/core/thread/panid_query_server.cpp, src/core/thread/uri_paths.cpp, src/core/thread/uri_paths.hpp
This commit adds a help function `UriToString<Uri>()` to convert a given `Uri` enumeration value to a human-readable string. This is used for logging by different TMF modules.
=> [tmf] add `UriToString()` for logging

src/posix/platform/backtrace.cpp
When compiling the otbr-agent in Android, Android will link the function [debuggerd_init()](https://android.googlesource.com/platform/system/core/+/refs/heads/master/debuggerd/handler/debuggerd_handler.cpp#715) and call it before calling the function main(). The function debuggerd_init() sets signal handlers to catch signals. This commit resets the signal actions to default and re-raises the original signal to let the pre-configured functions to catch signals.
=> [posix] reset the signal actions after processing signals

examples/platforms/simulation/diag.c, src/cli/cli.cpp, third_party/mbedtls/CMakeLists.txt
This commit adds two small changes to address new warnings when
building with clang-14.
It also updates `mbedtls` CMakeLists to set `MBEDTLS_FATAL_WARNINGS`
option as `OFF` (so that compiler warnings are not treated as errors).
This avoid issues with new warning for `unused-but-set-variable` emitted
by clang-14.
----
This should help address https://github.com/openthread/openthread/issues/8923.
=> [build] address new warnings with clang-14

src/core/coap/coap.cpp, src/core/coap/coap.hpp, src/core/common/message.cpp, src/core/common/message.hpp
This commit adds overloads of commonly used methods in `Coap` and `MessagePool` replacing default parameter values. This helps reduce code size.
=> [coap] avoid using default parameter values for common methods

src/core/net/ip6.cpp, src/core/net/ip6_types.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/tmf.cpp, src/core/thread/tmf.hpp
This commit adds new IPv6 header DSCP values which indicate a TMF
message priority. This allows intermediate routers forwarding TMF
message to be able to determine and use the TMF message priority that
originator of the message selects (e.g. address query/notification
use net-level priority whereas network diagnostics message use normal
priority). This replaces the previous behavior where on intermediate
routers all TMF messages were treated as net-level priority.
The new DSCP values are allocated from local codepoint range
`0bxxxx11` (per RFC 2474 - section 6). If the sender does not use
TMF-specific DSCP values, we use `kPriorityNet` as default on
intermediate router. This ensures that senders that are using older
code (do not use the new) experience the same behavior as before.
---- …
=> [tmf] add local IPv6 DSCP values to indicate TMF message priority

src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit updates `Mle::SendChildUpdateRequest()`:
- It removes the use of default parameter.
- It adds a private version which accepts `ChildUpdateRequestMode` indicating actions like whether to append challenge TLV, or whether to append zero timeout value (used for graceful detach).
=> [mle] simplify `SendChildUpdateRequest()`

.github/workflows/simulation-1.2.yml, script/test
This commit disables `INTER_OP_BBR` by default to avoid unnecessary build in most times.
=> [test] disable INTER_OP_BBR by default

src/core/thread/network_diagnostic.cpp
This commit fixes `GetNextDiagTlv()` to correctly return error `kErrorNotFound` if the message happens to end with an unknown TLV. We ensure to set the `error` after the end of `while()` loop. With the previous code we could return `kErrorNone` (since we would successfully read and skip over the unknown TLV which would set `error`).
=> [net-diags] fix `GetNextDiagTlv()` when skipping over unknown TLVs

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_tlvs.hpp
This commit adds helper methods to append an IPv6 Address Entry in an Address Registration TLV using compressed format where the entry contains a lowpan context ID and the address's IID, or uncompressed format where the full IPv6 address is appended.
=> [mle] simplify appending of Address Registration TLV entries

.github/workflows/docker.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> [github-actions] replace deprecated `set-output` commands

src/core/net/dns_client.cpp
This commit fixes an issue in `HandleTimer()` where we need to use `break` instead of `continue` after calling `FinalizeQuery()`. Note that we now have two loops, an outer loop on `mMainQueries` and then an inner loop on queries associated with a `mainQuery`. When we finalize a query, its related `mainQuery` (along with all its sub-queries) are finalized and removed.
=> [dns-client] fix finalizing query from `HandleTimer()`

src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp
This commit ensures to check that `KeyId` on a frame matches the current `mKeyId` before `SignalFrameCounterUsed()`. This addresses corner-case situation where on key sequence change, an ongoing frame tx (or enhanced ack to a received frame) can be processed  after the `mKeyId` change.
=> [sub-mac] check key-id to match before `SignalFrameCounterUsed()`

tests/scripts/thread-cert/node.py
This commit relax the requirement of mDNS so that it's OK when either mdns or avahi is present.
=> [test] require either mdns or avahi

src/posix/platform/daemon.cpp
This commit removes logging of the CLI input in `Daemon::Process()`. This ensures that sensitive info (e.g. dataset and/or network key) is not emitted in the logs. The CLI input/output can be logged using the CLI related configs `OPENTHREAD_CONFIG_CLI_LOG_INPUT_OUTPUT_ENABLE` and/or `OPENTHREAD_CONFIG_CLI_LOG_INPUT_OUTPUT_LEVEL`.
=> [daemon] remove log of CLI input

examples/apps/cli/main.c, include/openthread/cli.h, include/openthread/instance.h, src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_config.h, src/posix/main.c
Calls to otCliSetUserCommand overwrite the pointer user command list pointer each time it is invoked, which results in successive calls to otCliSetUserCommand replacing the previously registered command list instead of appending to it. This is particularly relevant for the posix platform in which the main function registers a set of posix specific commands without any way to extend the set.
This commit replaces the command list pointer with a container of command lists associated with a registered context in order to support prepending the active list of user commands up to a configurable value which defaults to 1 to maintain current behavior.
=> [cli] store cli user commands in container and support list prepend

etc/cmake/options.cmake, examples/apps/cli/ftd.cmake, examples/apps/cli/mtd.cmake, examples/apps/cli/radio.cmake, examples/apps/ncp/ftd.cmake, examples/apps/ncp/mtd.cmake, examples/apps/ncp/rcp.cmake, src/posix/cli.cmake, src/posix/daemon.cmake
This adds the CMake option `OT_LINKER_MAP` which will generate `.map` files for any executables built when the option is `ON`. 
This should be functionally equivalent to the Makefile option [`OPENTHREAD_ENABLE_LINKER_MAP`](https://github.com/openthread/openthread/blob/674cbfaa5c02b8be443de02c4db489049f6ea007/configure.ac#L779)
To test: 
```bash
matran@matran-ubuntu in ~/openthread
$ rm -rf build/ && ./script/cmake-build posix -DOT_LINKER_MAP=ON
...
OPENTHREAD_CONFIG_FILE=openthread-core-posix-config.h
OPENTHREAD_CONFIG_NCP_HDLC_ENABLE=1
[862/862] Linking CXX executable tests/unit/ot-test-tlv
matran@matran-ubuntu in ~/openthread
$ find build -type f -name '*.map'
build/posix/ot-cli.map
```
=> [build] add cmake option for generating .map files

include/openthread/dns_client.h, include/openthread/instance.h
This commit updates `otDnsClient` API documentation making the service resolution `otDnsClientResolveService()` behavior more clear, in particular that it sends queries for SRV/TXT records. The new documents also highlight how records in Additional Data section in a query response is parsed and provided in the callbacks and that servers/resolvers may not provide the records.
=> [dns-client] update API docs

include/openthread/instance.h, include/openthread/thread.h, src/core/api/thread_api.cpp, src/core/config/mle.h, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/ncp/ncp_base.cpp, src/ncp/ncp_base.hpp, src/ncp/ncp_base_ftd.cpp, tests/toranj/openthread-core-toranj-config.h
This commit adds `MLE_PARENT_RESPONSE_CALLBACK_API_ENABLE` config which enables support for `otThreadRegisterParentResponseCallback()` API. This API registers a callback to notify user of received Parent Response message(s) during attach. This API is mainly intended for debugging and therefore is is disabled by default. It is enabled in `toranj-config` so to validate the code (i.e. it causes no build errors) during CI GitHub action runs.
=> [mle] add parent request callback config

src/core/thread/address_resolver.cpp, src/core/thread/address_resolver.hpp, src/core/thread/mle_router.cpp, src/core/thread/router_table.cpp
This commit contains two related changes where we clear any address cache entries associated with an old (child) RLOC16:
- On a parent, when we detect that a former child has been promoted to router role by receiving an MLE Advertisement from it.
- On leader, when we successfully reply to an "Address Solicit" message and assign a new RLOC16 to a node.
=> [mle] clear address cache entries on promotion of child to router

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/thread/network_data_publisher.cpp, src/core/thread/network_data_publisher.hpp, tests/scripts/thread-cert/border_router/test_manual_maddress.py, tests/scripts/thread-cert/border_router/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/test_multi_thread_networks.py, tests/scripts/thread-cert/border_router/test_on_link_prefix.py, tests/scripts/thread-cert/border_router/test_single_border_router.py, tests/unit/test_routing_manager.cpp
This commit updates the `RoutingManager` module to implement a new model for publishing routes. The new model replaces the previous model, which explicitly published all discovered routes and on-link prefixes (from processing Router Advertisements on AIL) as external routes in the Network Data.
The new model simplifies this logic by publishing either a `fc00::/7` (ULA) route or a `::/0` (default) route in the Network Data, depending on the set of discovered routes and on-link prefixes, and the currently favored OMR prefix.
This commit adds the `RoutePublisher` class, a nested sub-component of the `RoutingManager` class. The `RoutePublisher` class is responsible for determining the route prefix to publish and its preference. The preference of the published route is determined based on the …
=> [routing-manager] `RoutePublisher` and new route publishing model

src/posix/platform/CMakeLists.txt, src/posix/platform/FindExampleVendorDeps.cmake, src/posix/platform/radio_url.cpp, src/posix/platform/vendor.cmake
A vendor interface implementation for the posix library is currently supported through linking a specified c++ source file. However, this is unable to accomodate dependencies for external libraries or header files that this vendor implementation source file may need.
The posix vendor support is changed to allow a vendor to specify a cmake RcpVendorDeps module file to resolve missing dependencies for a provided vendor support source file.
Additionally, this commit adds the ability for a vendor to define a radio url help message when the vendor rcp bus is selected instead of defaulting to the UART help message.
=> [posix] vendor support with lib dependencies

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_types.hpp
This commit fixes an issue with tracking time spent in each role after `Mle::ResetCounters()`. The  `mLastUpdatedTimestamp` is now updated from `ResetCounters()`.
=> [mle] fix how time per role is tracked after counters are reset

src/core/thread/link_metrics.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, tests/toranj/cli/test-012-reset-recovery.py
This commit allows an FED child to request Route TLV (in "TLV Request TLV") in an MLE Data Request message. Parent will include the Route TLV when requested by the child.
After successfully performing a quick re-attach upon reset, an FED child requests Route TLV when sending MLE Data Request to its parent. This is tracked by a newly added boolean `mRequestRouteTlv`, which is set after quick re-attach and cleared when Route TLV is successfully processed.
This commit also simplifies methods related to sending Data Request.
-------
This is related to [SPEC-1145](https://threadgroup.atlassian.net/browse/SPEC-1145).
=> [mle] request "Route TLV" after quick re-attach as FED

src/core/thread/network_data_leader.cpp
This commit updates the `CompareRouteEntries()` method so that if all of the earlier checks (preference, path cost) are the same, it will prefer a border router (BR) acting as a router over one acting as an end device. The reason is that a device can more accurately calculate the path cost to a router node than to an end device. This is because the link quality between an end device and its parent is not known to other devices.
=> [netdata] prefer BR acting as router over ED (when all other checks are same)

include/openthread/instance.h, include/openthread/ip6.h, src/core/api/ip6_api.cpp, src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, src/core/utils/parse_cmdline.cpp, tests/unit/test_ip_address.cpp
This commit adds the `Ip6::Prefix::FromString()` method, which parses a human-readable IPv6 prefix string into a binary representation. It also updates the unit test `test_ip_address` to validate the new method, and updates the `parse_cmdline` module to use the new function.
=> [ip6] add `otIp6PrefixFromString()`

src/cli/cli_br.cpp, src/cli/cli_br.hpp
In the PR for DHCPv6 PD, we are adding another new type of prefix. This PR refactors `ParsePrefixTypeArgs` to make it more flexible,
=> [cli] refactor br command prefix type

src/core/api/link_metrics_api.cpp, src/core/common/instance.cpp, src/core/common/instance.hpp, src/core/mac/mac.cpp, src/core/thread/link_metrics.cpp, src/core/thread/link_metrics.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/topology.cpp, tests/unit/test_link_quality.cpp
This PR breaks Link Metrics Initiator and Subject into two classes
and fixes incorrect swtich guard. For example, code for Initiator 
was guarded by macro of Subject.
=> [link-metrics] refactor link metrics module

src/posix/platform/resolver.cpp, src/posix/platform/resolver.hpp
On some platforms, the /etc/resolv.conf might be a generated file, and is not available at the first few minutes after boot.
This PR records the time when we read the DNS server addresses from the upstream, and reload the server list when it expires.
We may want to use inotify or add a platform specific API to notify the openthread about the change of DNS server list in the future.
=> [posix] update upstream DNS addresses after a few minutes 

include/openthread/instance.h, include/openthread/netdata_publisher.h, src/cli/README_NETDATA.md, src/cli/cli_network_data.cpp, src/core/api/netdata_publisher_api.cpp, src/core/thread/network_data_publisher.hpp, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_netdata_publisher.py
This commit adds a public OT API to replace a previously published external route entry in the Thread Network Data. It also adds a related CLI command, and updates `test_netdata_publisher` to validate the new behavior.
=> [netdata] add `otNetDataReplacePublishedExternalRoute()` API

src/core/mac/mac.hpp, src/core/thread/topology.cpp
Link metric macros `OPENTHREAD_CONFIG_MLE_LINK_METRICS_INITIATOR_ENABLE` and `OPENTHREAD_CONFIG_MLE_LINK_METRICS_SUBJECT_ENABLE` were guarding incorrect parts of code.
=> [link-metrics] fix compilation errors

src/core/common/string.cpp, src/core/common/string.hpp, src/core/net/ip4_types.cpp, src/core/net/ip6_address.cpp, tests/unit/test_ip_address.cpp, tests/unit/test_string.cpp
This commit adds a helper function to parse a decimal number from a given string as `uint8_t` and skip over the parsed characters. This is used to simplify the methods parsing IPv6/IPv4 address or prefix from a string.
=> [string] add `StringParseUint8()` helper function

src/posix/platform/radio.cpp, src/posix/platform/radio.hpp
When adding cli commands to be used by a posix platform is is useful to have access to the spinel interface when trying to communicate with a RCP using vendor specific spinel properties. It is inadvisable to create a separate spinel interface for custom properties as the two interfaces would need to avoid contention on the hardware interface.
This accessor method allows access to the static spinel interface defined in radio.cpp for external code segments. Dependent source files can do so with:
`(RadioSpinel<InterfaceType, ProcessContextType>*)Posix::Radio::getSpinelInstance()` or similar.
=> [posix] define posix `RadioSpinel` accessor

src/core/api/ip6_api.cpp, src/core/net/ip6.cpp, src/core/net/ip6.hpp
This commit simplifies and updates the `NewMessageFromData()` method to always determine the priority from the IPv6 header, even if a `Message::Settings` is provided. This change aligns the behavior of `NewMessageFromData()` with the documented and intended behavior of `otIp6NewMessageFromBuffer()`.
---
The doc for `otIp6NewMessageFromBuffer()`:
https://github.com/openthread/openthread/blob/1203ea6426a906d62a3921b6d4c6a4a6c8e0abde/include/openthread/ip6.h#L400-L406
=> [ip6] simplify and update `NewMessageFromData()`

src/core/meshcop/border_agent.cpp, src/core/meshcop/dtls.cpp, src/core/net/dhcp6_client.cpp, src/core/net/dhcp6_server.cpp, src/core/net/dns_client.cpp, src/core/net/dnssd_server.cpp, src/core/net/icmp6.cpp, src/core/net/icmp6.hpp, src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/net/srp_client.cpp, src/core/net/srp_server.cpp, src/core/net/udp6.cpp, src/core/net/udp6.hpp, src/core/utils/ping_sender.cpp
This commit adds new versions of `NewMessage()` in `Ip6`, `Udp` with different set of parameters. It also updated the code to avoid use of default parameter value.
=> [ip6] add new versions of `NewMessage()`

src/core/net/dns_client.cpp
This commit fixes an issue with `ServiceResponse::GetHostAddress()` method. The issue only occurs when separate queries (e.g., for SRV and TXT records) are used, and therefore separate `Response` objects are collected and chained together as a linked list. The change ensures that we check every response in the list when getting host addresses.
=> [dns-client] check all responses in `GetHostAddress()`

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, tests/unit/test_routing_manager.cpp
This commit adds a new mechanism to update the default route flag on the local OMR prefix based on whether or not the BR is publishing the `::/0` external route prefix.
When `RoutePublisher` (the component that determines which route prefix to publish) decides to publish/unpublish the default route as `::/0`, it will inform `LocalOmrPrefix` (the component that manages when the local OMR prefix is added/removed in Thread Network Data) of the def-route flag to use.
- If the local OMR prefix is not yet added, the def-route flag will be remembered to be used when/if it is added.
- If the local OMR prefix is already added, the entry in Network Data is updated to use the new def-route flag.
This change addresses a backward compatibility issue with devices running 1.2 or earlier Thread versions. …
=> [routing-manager] update OMR prefix def-route flag when publishing `::/0`

src/core/border_router/routing_manager.cpp, tests/scripts/thread-cert/border_router/nat64/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/nat64/test_with_infrastructure_prefix.py, tests/toranj/openthread-core-toranj-config.h, tests/unit/test_routing_manager.cpp
This PR adds a check on OMR prefix before selecting AIL prefix as the favored NAT64 prefix for publishing.
=> [nat64] check OMR prefix before favoring AIL NAT64 prefix

src/core/thread/mle_router.cpp, src/core/thread/topology.hpp
This commit updates the `MleRouter` to echo back the "Supervision TLV" in MLE Child ID Response message when it is included in MLE Child ID Request by a child.
=> [mle] echo back "Supervision TLV" in Child ID Response

src/lib/spinel/radio_spinel_impl.hpp
This commit adds new logs to `HandleRcpTimeout()` when an RCP timeout occurs during initialization. This error is often incorrectly reported as a bug, but it is usually caused by an incorrect configuration or a bad RCP image. The new logs aim to provide information and hints to the user about the cause of the error.
=> [radio-spinel] add log on RCP timeout error during init

include/openthread/cli.h, include/openthread/instance.h, script/check-simulation-build-cmake, src/cli/CMakeLists.txt, src/cli/cli.cpp, src/cli/cli_config.h, src/cli/cli_extension_example.c, src/cli/cli_extension_example.cmake, src/cli/ftd.cmake, src/cli/mtd.cmake
See the following discussion for reference:
https://github.com/openthread/openthread/discussions/8988
=> [cli] support adding vendor command list to cli apps

include/openthread/dns_client.h, include/openthread/instance.h, src/cli/README.md, src/cli/cli.cpp, src/core/api/dns_api.cpp, src/core/net/dns_client.cpp, src/core/net/dns_client.hpp, src/core/net/dnssd_server.cpp, src/core/net/dnssd_server.hpp, tests/unit/test_dns_client.cpp
This commit adds `otDnsClientResolveServiceAndHostAddress()` function as a new DNS Client API. This function starts a DNS service instance resolution for a given service instance, with a potential follow-up address resolution for the host name discovered for the service instance (when the server/resolver does not provide AAAA/A records for the host name in the response to SRV query).
In order to test the behavior of the newly added function, `TestMode` in `Dns::ServiceDiscovery::Server` is updated to add a new mode where no RR is added in the Additional Data section of a DNS query response.
This commit adds a related CLI command for the new API and updates `test_dns_client` to validate the behavior of new API using the new `TestMode` on `Server`.
=> [dns-client] new API resolve host and address

include/openthread/border_agent.h, include/openthread/instance.h, src/cli/cli.cpp, src/core/api/border_agent_api.cpp, src/core/common/settings.cpp, src/core/common/settings.hpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/border_agent.hpp
This commit adds
1. a new `otBorderAgentSetId()` API to override the auto generated random ID
2. CLI commands to read write the Border Agent ID
Depends-On: openthread/ot-br-posix#1869
=> [border-agent] set Border Agent ID via CLI

src/ncp/ncp_base.cpp
This commit fixes an issue where 'RegisterPeekPoke' was called instead of 'RegisterPeekPokeDelegates', causing compilation errors in some builds.
=> [ncp] fix RegisterPeekPokeDelegates call

src/cli/README.md, src/cli/cli.cpp
The `"vendor"` command should be available on both FTD and MTD.
=> [cli] fix config check for "vendor" command

include/openthread/instance.h, src/cli/README.md, src/cli/cli.cpp, src/core/api/instance_api.cpp, src/core/common/instance.cpp, src/core/common/instance.hpp, tests/scripts/expect/cli-misc.exp
It is difficult for testers to know whether the stack has been automatically restarted in the background. This commit adds an instance id to indicate whether the stack has been restarted. The instance id is set to a random value when the OpenThread instance is constructed and its vaule will not change after initialization.
=> [core] add instance id

include/openthread/instance.h, include/openthread/platform/alarm-micro.h, include/openthread/platform/alarm-milli.h
Based on discussion in https://github.com/openthread/openthread/discussions/9065#discussioncomment-5940126, it appears the requirement in the code comments is not completely accurate wrt to the example implementations. As such, the requirements are updated to match what is implemented for the posix platform.
=> [alarm] `otPlatAlarm` requirements clarification

src/cli/cli.cpp, src/cli/cli.hpp
This commit adds a new helper method `OutputNat64Counters()` which outputs a table row for NAT64 counters (4to6/6to4 packets/bytes). This helps simplify the `nat64` commands.
=> [cli] add helper `OutputNat64Counters()`

src/core/radio/radio.hpp
Add missing return code in API comment of radio LInk Metrics API.
=> [radio] fix return code doc of link metrics api

src/posix/client.cpp, src/posix/main.c, src/posix/platform/daemon.cpp, src/posix/platform/openthread-posix-config.h
The default Thread interface name `wpan0` has been occupied by other programs in Android. Thread network has to use other network interface name. Then users have to specify an interface name when they are using the command `ot-ctl`. It's very inconvenient.
This commit adds a configuration for developers to set the default Thread interface name.
=> [posix] add Thread network default interface name configuration

src/core/mac/mac.cpp, src/core/mac/mac_frame.hpp, src/core/mac/mac_links.hpp, src/core/thread/mesh_forwarder.cpp
The CSL present flag was not cleared in the frame structure, causing that the MAC security was not be processed for Key ID Mode 2 frames. Consequently, MLE Announcements would be rejected by the sub-MAC layer after a CSL receiver detached from its parent.
=> [csl] fix 15.4-secured broadcast frames

src/core/common/random.cpp, src/core/common/random.hpp, src/core/mac/mac_types.cpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/dataset.cpp, src/core/net/dhcp6.hpp, src/core/net/ip6_address.cpp, src/core/net/nat64_translator.cpp, src/core/net/tcp6.cpp, src/core/thread/key_manager.hpp, src/core/utils/slaac_address.cpp, tests/unit/test_checksum.cpp, tests/unit/test_ndproxy_table.cpp, tests/unit/test_spinel_buffer.cpp
This commit adds template `Fill<ObjectType>(ObjectType &aObject)` functions for both `Crypto` and `NonCrypto` random number generation modules. These functions fill a given object with random byes.
=> [random] add `Fill<ObjectType>()` function

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/common/uptime.hpp
This commit updates logs in the `RoutingManager` module:
- The log module name is changed to "RoutingManager".
- State changes are logged (enabling, disabling, starting, etc.).
- The `ScheduleRoutingPolicyEvaluation()` log will show the delay in both milliseconds and `"<mm>:<ss>.<msec>"` format(e.g. `05:15.234`).
- Logging of PIOs and RIOs are harmonized (when preparing RA to send or processing a received RA).
- Local on-link prefix logs are harmonized in `OnLinkPrefixManager`.
- `RsSender` logs are simplified.
=> [routing-manager] update logs

src/core/common/num_utils.hpp, src/core/thread/link_metrics.cpp, tests/unit/test_link_quality.cpp
Currrently if we call `ScaleRawValueToRssi` with value 0 or 1, the result is incorrect. 
Because it tries to static_cast `-130` or `-129` to `int8_t`. I think it's not worthwhile
to widen int8_t to int16_t only for the 2 corner cases. So I prefer returning the smallest
value -128 for the 2 cases.
=> [link-quality] fix corner case of `ScaleRawValueToRssi`

src/cli/cli.cpp, src/core/net/nat64_translator.cpp, src/core/net/nat64_translator.hpp, src/posix/platform/netif.cpp, src/posix/platform/platform-posix.h, src/posix/platform/system.cpp, tests/scripts/thread-cert/border_router/nat64/test_single_border_router.py, tests/scripts/thread-cert/node.py
We should notice that the default CIDR (`192.168.255.0/24`) is not safe to use, however, in most cases, the CIDR used can only be determined during runtime since the single binary might be distributed to BRs in different network conditions. And we cannot conclude an always safe CIDR in all conditions.
This PR will emit an event when NAT64 CIDR is changed. So the platform driver can update the route for NAT64.
=> [nat64] notify platform when NAT64 CIDR is updated

src/core/border_router/routing_manager.cpp
This commit fixes `RemoveOrDeprecateEntriesFromInactiveRouters()` to ensure to skip over an already deprecating on-link prefix (and not remove it).
---
Thanks to @superwhd  for finding this issue.
=> [routing-manager] fix deprecating on-link prefix from inactive router

src/lib/spinel/spinel_interface.hpp, src/posix/platform/hdlc_interface.hpp, src/posix/platform/spi_interface.hpp, src/posix/platform/vendor_interface.hpp, src/posix/platform/vendor_interface_example.cpp
This commit adds all Spinel interface functions to the `SpinelInterface` as pure virtual functions and inherits all Spinel interfaces from `SpinelInterface`, so that the Thread Network HAL can dynamically create the Spinel interface based on the configuration of the radio URL in Android. This commit also removes the macro guard from the Spinel interface header files.
=> [posix] unify the spinel interface functions

src/posix/platform/netif.cpp
From the kernel code, addr_gen_mode should be uint8_t.
=> [netif] use fix type to u8 for addr_gen_mode

src/core/common/tlvs.cpp, src/core/common/tlvs.hpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/thread/discover_scanner.cpp, src/core/thread/link_metrics.cpp, src/core/thread/mle_router.cpp, src/core/thread/network_diagnostic.cpp, src/core/utils/mesh_diag.cpp
This commit adds two changes to the `Tlvs` class:
- A new method, `FindTlvValueStartEndOffsets()`, has been added to find the start and end offsets of a TLV value within a `Message`. This method is useful for code that needs to find the value of a TLV and then search within that value.
- The unused method, `FindTlvOffset()`, has been removed. This method was previously only used by the `Tlvs` class itself.
=> [tlvs] new helper to find the start and end offsets of a TLV value

src/core/backbone_router/bbr_leader.cpp, src/core/backbone_router/bbr_leader.hpp, src/core/backbone_router/bbr_local.cpp, src/core/backbone_router/bbr_local.hpp, src/core/backbone_router/ndproxy_table.cpp, src/core/backbone_router/ndproxy_table.hpp, src/core/thread/dua_manager.cpp, src/core/thread/dua_manager.hpp
- Rename to `DomainPrefixEvent` from `DomainPrefixState`
- Remove the unused `kDomainPrefixNone` enumeration
=> [bbr] simplify `DomainPrefixEvent`

include/openthread/instance.h, include/openthread/thread_ftd.h, src/cli/cli.cpp, src/core/api/thread_ftd_api.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/mle_types.cpp, src/core/thread/mle_types.hpp, tests/unit/test_mle.cpp
This commit restricts the `otDeviceProperties` functionality to OpenThread builds with `OT_THREAD_VERSION` set to `1.3.1` or later. This functionality was added in PR #8670 and is used to calculate and set the local Leader Weight on the device based on its properties, such as power supply configuration and whether or the device is acting as a Border Router, etc.
---
Related to [DEV-2376](https://threadgroup.atlassian.net/browse/DEV-2376).
=> [mle] restrict `otDeviceProperties` to version 1.3.1 or later

src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/radio/radio.hpp
Improve logging in CSL debug mode by properly calculating the drift of the received frame compared with the established CSL sample time.
The new log also shows what was the accepted margin for the drift at the reception time, and increases the logging level when the drift is outside the margin.
Neither kCslReceiveTimeAhead or kMinCslWindow are considered for the margin since they have no impact on understanding possible drift errors between transmitter and receiver.
=> [csl] improved CSL debug logging

tests/toranj/build.sh
This commit updates toranj `build.sh` script to use Thread version 1.3.1. This ensures that we can cover features that are restricted to this version in `toranj` test-cases.
----
This PR contains the commit from the following two PRs:
- https://github.com/openthread/openthread/pull/9158
- https://github.com/openthread/openthread/pull/9157
=> [toranj] update `build.sh` script to use Thread version 1.3.1     

src/core/thread/mle_router.cpp
This commit adds a new mechanism to send a unicast MLE Link Request to
the device's former parent if its version is earlier than 1.3.0, when
the device is promoted from a child to a router role. This is to
address a potential compatibility issue with some non-OpenThread
stacks which may ignore MLE Advertisements from a previous/existing
child.
----
Related to [SPEC-1131](https://threadgroup.atlassian.net/browse/SPEC-1131).
=> [mle] unicast Link Request to 1.2.1 or earlier parent on router role promo

src/lib/hdlc/CMakeLists.txt, src/lib/hdlc/Makefile.am, src/lib/hdlc/hdlc.cpp, src/lib/hdlc/hdlc.hpp, src/lib/spinel/Makefile.am, src/lib/spinel/multi_frame_buffer.hpp, src/lib/spinel/spinel_interface.hpp, src/ncp/ncp_hdlc.hpp, src/posix/platform/hdlc_interface.cpp, src/posix/platform/hdlc_interface.hpp, src/posix/platform/spi_interface.cpp, src/posix/platform/spi_interface.hpp, tests/unit/test_hdlc.cpp
The `MultiFrameBuffer` is not only used by `hdlc.hpp`, it is also used by `spi_interface.hpp` and `radio_spinel.hpp`. This commit moves the  `MultiFrameBuffer` implementation from `hdlc.hpp` to `multi_frame_buffer.hpp` as a dependent module.
=> [spinel] move the `MultiFrameBuffer` implementation to multi_frame_buffer.hpp

src/core/BUILD.gn, src/core/Makefile.am, src/core/config/mesh_forwarder.h, src/core/config/misc.h, src/core/openthread-core-config.h
This commit adds the `config/mesh_forwarder.h` header file, which defines all of the configurations used by the `MeshForwarder`. These configs were previously included in `misc.h`.
=> [config] add `mesh_forwarder.h` config header file

src/core/border_router/routing_manager.cpp
Context: https://mailarchive.ietf.org/arch/msg/snac/0wzbsMx_1uHFHEdw-cftEufoi-k/
=> [routing-manager] require valid on-link prefix to be /64

src/cli/cli.cpp
This commit updates `OutputEidCacheEntry()` and how it converts cache entry state to string.
=> [cli] update `OutputEidCacheEntry()`

src/cli/README_TCP.md, src/cli/cli_tcp.cpp, src/cli/cli_tcp.hpp
This PR updates the cli command of TCP benchmark so that the result
of TCP benchmark could be queried any time. This enables test scripts
to automate TCP benchmark test. Currently the command `tcp benchmark`
is asynchronous and return immediately. If we use `ot-ctl tcp benchmark`
on posix, it's hard to fetch the test results. With the newly added
command, we can write a script to poll and get the result.
=> [cli] add command to get tcp results

src/core/mac/mac.cpp, src/core/mac/mac.hpp
Fix the behavior of `Mac::SetEnabled` for also enabling/disabling the radio.
This ensures that the radio is turned off when `otLinkSetEnabled(false)` is used.
=> [mac] enable/disable radio together with MAC

src/core/net/netif.cpp, src/core/net/netif.hpp
This commit adds two new methods, `SignalUnicastAddressChange()` and `SignalMulticastAddressChange()`. These methods signal changes to unicast or multicast addresses to the `Notifier`, `HistoryTracker`, and user address callback.
=> [netif] simplify signaling address events

.code-spell-ignore, tools/harness-thci/OpenThread.py, tools/harness-thci/OpenThread_WpanCtl.py
Reverting name change intialize -> initalize. To fix thread harness issues.
=> [thci] revert spellcheck in THCI method names

src/core/thread/csl_tx_scheduler.cpp
Avoid potential CSL Transmitter crash when using a CSL period with 0 value in `GetNextCslTransmissionDelay`.
=> [csl] ensure child is synchronized when preparing a CSL transmission

tests/unit/test_dns_client.cpp, tests/unit/test_routing_manager.cpp, tests/unit/test_srp_server.cpp
This commit updates the unit tests that emulate the radio platform API to define `otPlatRadioGetCaps()`, which returns the ACK_TIMEOUT and CSMA capabilities. This is to avoid having CSMA being implemented by the `SubMac`, which then uses the microsecond timer that is not emulated in the unit test platform.
It also updates the `InitTest()` function to clear the radio platform variable `sRadioTxOngoing`. This is to avoid the possible (though unlikely) situation where an earlier test finishes in the middle of a transmission, causing an extra `TxDone` event in the following test.
=> [test] update unit test emulating radio

src/core/net/dns_types.cpp, src/core/net/dns_types.hpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, tests/unit/test_dns.cpp, tests/unit/test_srp_server.cpp
This commit updates the `Srp::Server` class to correctly handle the case where a service is registered with a dot character in its service instance name. The first label in a service instance name is intended as a user-friendly name and can contain dot characters (it has fewer restrictions than other labels in a DNS name).
In particular, this commit contains the following changes:
- The `PtrRecords::ReadPtrName()` method is used in `Srp::Server` to read and validate the first label and the rest of the labels separately. This also validates the format of the parsed PTR record.
- The `Service::Description` class now remembers the instance label in addition to the full instance name. This allows the instance label to be easily retrieved.
- The `Dns::Name::ReadName()` method is updated to …
=> [srp-server] allow service instance label with dot character

src/core/common/message.cpp, src/core/common/message.hpp, src/core/thread/mesh_forwarder.cpp
Saves a few bytes in MTD message metadata since they don't need the child mask.
=> [message] remove child mask from message metadata in MTD

src/core/meshcop/dtls.hpp
Fix compilation error mbedtls_base64_encode not defined when compiling with MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED disabled.
The logic for including the mbedtls/base64.h header file is doing the wrong define check.
=> [meshcop] fix compilation error mbedtls_base64_encode not defined

src/cli/README_DATASET.md, src/cli/cli_dataset.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, tests/scripts/thread-cert/Cert_9_2_05_ActiveDataset.py, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_router_downgrade_on_sec_policy_change.py, tools/otci/otci/otci.py
This commit adds a mechanism to delay the downgrade of routers or leader when the security policy TLV changes in the Active Operational Dataset such that the device is no longer eligible to act as a router.
If the decision to become a child is made due to a security policy change, the device first delays a random period up to the "router selection jitter" before downgrading. If the device is the leader, an additional fixed delay of 10 seconds is added to the random period.
If the security policy changes again while the device is waiting to downgrade such that it becomes router-eligible again, the downgrade is cancelled and the device remains in its current role.
This commit adds a `test_router_downgrade_on_sec_policy_change` to validate the behavior of newly added mechanism.
This commit …
=> [mle] delay router role downgrade on security policy change

examples/platforms/simulation/infra_if.c, include/openthread/border_routing.h, include/openthread/instance.h, src/cli/README_BR.md, src/cli/cli_br.cpp, src/core/api/border_routing_api.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/common/notifier.cpp, src/core/common/notifier.hpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, tests/toranj/cli/cli.py, tests/toranj/cli/test-021-br-route-prf.py, tests/toranj/start.sh
This commit updates how `RoutePublisher` determines the published route preference:
- Medium preference is used on a border router (BR) acting as a router or a BR acting as an end-device (ED) connected to a parent with link quality 1.
- An ED BR with lower link quality publishes its route with low preference.
For ED BRs, the preference is updated if the parent's link quality changes. However, to avoid frequent preference changes due to link variability, the following rules are used:
- If the link quality goes to 2 or 3, the route preference is immediately changed to low.
- On transition to link quality 1, we wait for 5 minutes before changing the preference to medium.
- If the ED BR switches parents, the link quality to the new parent is used to determine preference.
It also adds new APIs …
=> [routing-manager] determine route preference from parent link quality

include/openthread/instance.h, include/openthread/thread_ftd.h, src/cli/cli.cpp, src/core/thread/address_resolver.cpp, src/core/thread/address_resolver.hpp, tests/toranj/cli/test-014-address-resolver.py
Address resolver retry delay determines how long the device needs to wait after a failed address query for a target address to allow a next query attempt. This is tracked per target (in `CacheEntry`).
The retry delay starts with an initial value (15 seconds). If consecutive queries fail, the retry delay doubles each time, up to a maximum value (120 seconds). In the current code, the retry delay is only reset to the initial value after a successful address resolution.
This commit implements a new mechanism to reduce the retry delay over time when there is no activity (no queries for the target address). The ramp-down countdown starts after a previous retry delay has expired. If no query is requested within the maximum retry delay interval (120 seconds), the retry delay is divided by two. …
=> [address-resolver] implement ramp-down mechanism for retry delay

src/ncp/ncp_base_ftd.cpp
This commit updates the NCP code to set the timeout field in spinel `SPINEL_PROP_THREAD_ADDRESS_CACHE_TABLE` as zero when in ramp-down mode. This ensures that the behavior of the NCP remains unchanged and that test cases like `ncp/test-039-address-cache-table-snoop.py`, which expect the timeout to reach zero, to pass.
=> [ncp] keep timeout zero during ramp-down in spinel `ADDRESS_CACHE_TABLE`

src/core/border_router/routing_manager.cpp
This commit updates the `RoutingManager::PdPrefixManager::Process()` method to `Tidy()` the prefix before setting the prefix length and potentially extending the prefix to `kOmrPrefixLength` (64 bits). This ensures that extended bits in the prefix are set to zero.
----
Should help address #9248
=> [routing-manager] `PdPrefixManager` to clear prefix bits when extending length

include/openthread/instance.h, src/lib/spinel/multi_frame_buffer.hpp, src/lib/spinel/radio_spinel_impl.hpp
`SaveFrame()` makes assumptions that there is enough space in the buffer to store the received buffer. This PR adds a error check to ensure that there is at least 4 bytes before initiating the save.
=> [spinel] return error from `SaveFrame` if not enough space is available

include/openthread/child_supervision.h, include/openthread/instance.h, src/cli/README.md
Previous documentation could be wrongly interpreted as that the supervision interval should be set on the parent (FTD).
=> [cli] fix `childsupervision` commands documentation

tests/unit/test_hdlc.cpp
This commit updates unit test `test_hdlc` to check the returned error from `SaveFrame()` (which was recently changed in #9244).
=> [test] fix unused returned value warning in `test_hdlc`

src/core/meshcop/commissioner.cpp, src/core/meshcop/commissioner.hpp
This commit simplifies scheduling of `mJoinerExpirationTimer` by using `FireAtIfEarlier()` when adding or updating a `Joiner` entry instead of recalculating the fire time. When a `Joiner` entry is removed, we keep the timer unchanged and let it be rescheduled when the currently scheduled timer expires. The next expiration time is determined in `HandleJoinerExpirationTimer()`, which ensures that all expiration times are strictly after `now` and avoids any potential issue with the order of comparison between `now` and `next` being `now.GetDistantFuture()`.
----
Should help address https://github.com/openthread/openthread/issues/9255, also related to https://github.com/openthread/openthread/pull/9258
=> [commissioner] simplify and fix scheduling of expiration timer

include/openthread/instance.h, include/openthread/mesh_diag.h, include/openthread/netdiag.h, src/cli/README.md, src/cli/cli.cpp, src/cli/cli.hpp, src/core/BUILD.gn, src/core/CMakeLists.txt, src/core/api/mesh_diag_api.cpp, src/core/common/tlvs.cpp, src/core/common/tlvs.hpp, src/core/thread/network_diagnostic.cpp, src/core/thread/network_diagnostic.hpp, src/core/thread/network_diagnostic_tlvs.cpp, src/core/thread/network_diagnostic_tlvs.hpp, src/core/utils/mesh_diag.cpp, src/core/utils/mesh_diag.hpp, tests/scripts/thread-cert/Cert_5_7_02_CoapDiagCommands.py, tests/scripts/thread-cert/Cert_5_7_03_CoapDiagCommands.py, tests/toranj/cli/test-023-mesh-diag.py, tests/toranj/start.sh
This commit contains multiple changes to Network Diagnostics modules.
It adds three new TLVs: Child TLV, Child IPv6 Address List TLV, and Neighbor TLV. Child TLV contains information about a child entry including RLOC16, extended MAC address, mode (rx-on-idle, FTD/MTD, full netdata, CSL-sync), timeout, age, supervision interval, CSL period and timeout, and link quality info such as RSS (last and average) and frame/message error rates. Neighbor TLV provides similar info for a router neighbor. The Child IPv6 Address List TLV allows to query a parent to get the list of IPv6 addresses registered by its MTD children.
The new TLVs can be requested in Network Diagnostic Get Query "d/dq" message to a router (unicast) or multiple routers (multicast). The router responds with one or more Network …
=> [net-diag] define child and Child IPv6 Address List TLV

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, tests/scripts/thread-cert/test_mle_msg_key_seq_jump.py
Processing of the Key Sequence is happening after each individual MLE command processing, which leads to generating MLE responses with outdated Key Sequence.
Make sure that the new greater Key Sequence is applied before generating any MLE response.
A test case is updated to catch the case in which fragmented Child Id Response was generated with the old Key Sequence whereas each individual MAC fragment is already updated with the new Key Sequence, leading to a security error.
=> [mle] ensure key sequence is updated in MLE responses

include/openthread/instance.h, include/openthread/srp_server.h, src/cli/cli_srp_server.cpp, src/core/api/srp_server_api.cpp, src/core/net/dnssd_server.cpp, src/core/net/dnssd_server.hpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp
This commit updates and simplifies how `Srp::Server` stores the sub-type services. The earlier implementation treated each sub-type as its own service, which was tracked by a `Service` object. This design allowed sub-type services to be registered and deleted individually. However, the latest SRP RFC draft requires SRP servers to treat updates to a service and all its sub-types as atomic. This means that when a service and its sub-types are being updated, the SRP Update message must contain the entirety of information about that service and its sub-types. As a result of this change, we can simplify the server implementation by tracking sub-types as an array of sub-type names in the `Service` object.
This commit also updates the way the server commits a received SRP update info into its …
=> [srp-server] simplify sub-type services

src/lib/spinel/radio_spinel_impl.hpp
The PR [[posix] unify the RCP reset sequence](https://github.com/openthread/openthread/pull/8858) refactors the logic related to RCP reset and recover. But there is a bug: 
For the RCP waiting response timeout handle logic: https://github.com/openthread/openthread/blob/main/src/lib/spinel/radio_spinel_impl.hpp#L255, the error code of processing `WaitResponse()` will be checked, if there is no error, the function `ResetRcp` will return with a log "Software reset RCP successfully". But the implementation of the [`WaitResponse`](https://github.com/openthread/openthread/blob/main/src/lib/spinel/radio_spinel_impl.hpp#L1496) it will always return OT_ERROR_NONE even if waiting response timeout.
In this PR fix, if waiting response timeout, `OT_ERROR_RESPONSE_TIMEOUT` will be returned from …
=> [spinel] fix error code when waiting rcp response timeout

include/openthread/border_agent.h, include/openthread/instance.h
I encountered a compiling issue `unknown type name 'otBorderAgentId'` related to function `otBorderAgentGetId(otInstance *aInstance, otBorderAgentId *aId)` and `otBorderAgentSetId(otInstance *aInstance, const otBorderAgentId *aId)` when I update the upstream code for ESP. I found this struct variable does not use `typedef` like other struct variables under the directory `include/openthread`.
related MR: [[border-agent] set Border Agent ID via CLI](https://github.com/openthread/openthread/pull/9049)
=> [border-agent] fix struct typedef for `otBorderAgentId`

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit adds `SetState()` method to the `OnLinkPrefixManager` class. This method allows the state of the on-link prefix manager to be changed in a single place, which simplifies the logging and makes it easier to take additional actions on state change. For example, the `SetState()` can be used to update the Advertising PIO (AP) flag in the published route in Network Data.
=> [routing-manager] add `SetState()` in `OnLinkPrefixManager`

.github/workflows/build.yml
This commit adds command to install `prettier@2.0.4` from the Bootstrap step in `pretty` job of `build.yml` GitHub Action workflow. This should help with occasional failure of `pretty` check.
=> [github-action] install `prettier@2.0.4` in `pretty` job

tests/toranj/openthread-core-toranj-config-posix.h, tests/toranj/openthread-core-toranj-config-simulation.h, tests/toranj/openthread-core-toranj-config.h
This commit removes the unnecessary Doxygen-style documentation of used configuration options from toranj config header files. This makes the test-specific config header simpler and avoids confusion with the main config parameters documentation, which is included in the corresponding `src/config/<name>.h` header files.
=> [toranj] remove docs from test specific config headers

include/openthread/instance.h, include/openthread/netdata.h, src/cli/README.md, src/cli/README_NETDATA.md, src/cli/cli.cpp, src/cli/cli_network_data.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/thread/network_data_tlvs.hpp, src/core/thread/network_data_types.cpp, tests/toranj/cli/test-021-br-route-prf.py, tests/unit/test_network_data.cpp, tests/unit/test_routing_manager.cpp
This commit adds support for the Advertising PIO (AP) flag in Network Data `ExternalRoute` entries. It also updates the `RoutingManager` class to set the AP flag on its published Network Data route when the local on-link prefix is included as PIO in emitted RA messages, which is equivalent to when the local on-link prefix is being published, advertised, or deprecated.
This commit also updates the `test_routing_manager` unit test to validate the AP flag in the published route under different scenarios.
----
This is related to [SPEC-1180](https://threadgroup.atlassian.net/browse/SPEC-1180).
~This PR currently contains the commit from PR https://github.com/openthread/openthread/pull/9273.~
=> [routing-manager] support Advertising PIO (AP) flag in published route

src/cli/README.md, src/core/net/dnssd_server.cpp, tests/scripts/thread-cert/border_router/test_dnssd_instance_name_with_space.py, tests/scripts/thread-cert/border_router/test_dnssd_server.py, tests/scripts/thread-cert/border_router/test_mdns_restart.py, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_dnssd.py, tests/scripts/thread-cert/test_srp_server_anycast_mode.py
This commit updates `Dns::ServiceDiscovery::Server` such that when answering a PTR query with more than one answer, it does not include additional records. This is to keep the size of the response small.
This commit also updates the test scripts validating browse (PTR query) function to check the new behavior. In particular, a common python function `_parse_dns_service_info()` is added to parse service info in CLI output of "dns browse" or "dns service" commands and handle if output of "dns browse" does not include service info.
----
Related to [SPEC-1181](https://threadgroup.atlassian.net/browse/SPEC-1181).
=> [dnssd-server] skip additional records on a PTR query with multiple answers

CMakeLists.txt, etc/cmake/functions.cmake, etc/cmake/options.cmake
This commit simplifies the definition of CMake configurations by adding new macros:
- `ot_string_option` for string-valued options (`OT_VENDOR_NAME`)
- `ot_int_option` for int-valued options (`OT_MLE_MAX_CHILDREN`)
- `ot_multi_option` for multi-valued options (`OT_LOG_LEVEL`)
Some of the option definitions have also been moved to the `options.cmake` file from `./CMakeLists.txt`.
=> [cmake] add macros to simplify CMake config definition

src/core/config/mle.h, src/core/thread/link_metrics.hpp, src/core/thread/topology.hpp
Currently to support Link Metrics Subject, we pre-allocate 128
entries. But this is unnecessary for MTD since it will only have one
neighbor. This PR minimizes the number to 2. (One for Enhanced-ACK
Probing and one for Forward Tracking Series.)
=> [link-metrics] minimize the Link Metrics entry count for MTD

include/openthread/instance.h, include/openthread/random_crypto.h
When trying to opaquely bind to the public facing API, including <mbedtls/ctr_drbg.h> forces an external dependency on mbedtls.
=> [random] remove mbedtls header from api

src/posix/platform/FindExampleVendorDeps.cmake, src/posix/platform/vendor_extension_example.cmake
This change updates the mechanism used by vendor.cmake to include a cmake file to define the required vendor targets used by the rcp vendor interface library instead of the find_package command that was previously used.
The find_package command would allow for a package to be searched for and a target to be linked unconditionally if defined by the CMake project. This would lead to problems if the target was already defined, perhaps as a subdirectory of a super project, and the cache variable is still set for the openthread build. Additionally, this change also brings the vendor extension of the posix library more in line with the cli vendor extension, which was created after find_package was used in vendor.cmake.
=> [posix] replace RCP vendor extension find package with include command

src/posix/platform/netif.cpp
`NETLINK_EXT_ACK` and `NETLINK_CAP_ACK` are for getting netlink reply details from the kernel
and we can still function without the two options.
This commit loose the check of enabling the two options to make ot-posix works on platforms where
the features are missing.
-------
Background: https://github.com/openthread/openthread/issues/9298
=> [posix] loose check for NETLINK_EXT_ACK and NETLINK_CAP_ACK

src/core/net/srp_server.cpp, src/core/net/srp_server.hpp
This commit simplifies the `Sever::RemoveHost()` method by removing the input parameter `aNotifyServiceHandler`. This is because, unlike the `RemoveService()` method, the `RemoveHost()` method always needs to notify the service handler.
=> [srp-server] simplify `RemoveHost()` method

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/mle_types.cpp, src/core/thread/mle_types.hpp, src/core/thread/topology.cpp, src/core/thread/topology.hpp
This commit defines two types to track challenge or response TLV data in MLE messages:
- `TxChallenge` represents the maximum-sized challenge data to include and send in MLE messages. OpenThread always uses the maximum size of 8 bytes for challenge data in the messages it sends.
- `RxChallenge` represents variable-length challenge data read from a received MLE message.
The two separate types help to simplify their use in code.
=> [mle] define separate `TxChallenge` and `RxChallenge` types

include/openthread/border_routing.h, include/openthread/instance.h, src/cli/README_BR.md, src/core/border_router/infra_if.hpp, src/core/border_router/routing_manager.cpp
This commit adds `ChangeInfraIf()` method to `RoutingManager` class. This method allows the infrastructure interface to be changed. The user may initialize multiple interfaces and choose one interface as infrastructure interface. Around the run-time, there might be some  networking congestion or other network issue. The user can change the infrastructure interface via this function.
There is a missing introduction to the command `init` for the `README_BR.md`, this PR also adds it.
=> [routing-manager] add `SetIfIndex` in `RoutingManager`

include/openthread/instance.h, include/openthread/thread_ftd.h, src/cli/cli.cpp, src/core/api/thread_ftd_api.cpp, src/core/common/trickle_timer.cpp, src/core/common/trickle_timer.hpp, src/core/net/ip6_mpl.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/mle_types.hpp, src/core/thread/neighbor_table.cpp, src/core/thread/router_table.cpp, src/core/thread/router_table.hpp, tests/toranj/cli/cli.py, tests/toranj/cli/test-024-mle-adv-imax-change.py, tests/toranj/start.sh, tests/unit/CMakeLists.txt, tests/unit/test_trickle_timer.cpp
This commit updates the `TrickleTimer` to allow `IntervalMax` and `IntervalMin` to be changed while the timer is running. In particular, when `IntervalMax` is changed to a value that is shorter than the current interval being used by the timer, the timer will adapt the new shorter interval and may fire immediately.
A unit test `test_trickle_timer` has been added to validate the behavior of `TrickleTimer` in detail. All different scenarios where `IntervalMax` or `IntervalMin` are changed are covered by the unit test.
The new mechanism to change the trickle timer `IntervalMax` is used to update the MLE Advertisement trickle timer. The `IntervalMax` is determined based on the number of router neighbors of the device with link quality 2 or better. If the device has fewer router neighbors, it …
=> [mle] update Avd trickle timer interval based on router neighbor count

src/core/mac/mac_frame.cpp
This commit updates the `Mac::TxFrame::GenerateEnhAck()` method to check the security level of the received frame. If the security level is not `kSecurityEncMic32`, it will return `kErrorParse`. This should help prevent radio platform implementations from trying to perform tx security on an invalid generated enhanced ack frame. Specifically, it can help prevent radio platforms from calling `ProcessTxSecurity()` on an enhanced ack frame with a security level of `kSecurityNone` which can cause an assert in `AesCcm::Init()` due to the tag length being zero.
----
Thanks and credit to Jordan Crafts (@jcrafts-lutron) for finding and reporting this issue.
=> [mac-frame] check rx frame security level in `GenerateEnhAck()`

src/core/thread/mle.cpp, src/core/thread/mle.hpp
This commit changes the `protected` declarations in the `Mle` class to be `private` since `Mle` class and its subclass, the `MleRouter`, are declared as `friend` classes.
The commit also re-arranges the `private` definitions in the `Mle` class into five sections: constants, enumerations, nested classes, methods declarations, and member variable definitions.
With the change to `private`, this commit also removes the redundant documentation of methods.
----
This is mainly a re-ordering of nest type and method declarations in `Mle` class. In this PR, we intentionally keep the order of member variables unchanged (we can later re-arrange the member variables, e.g., combine booleans into bit-fields, or try to avoid obvious alignment gaps).
=> [mle] change `protected` declarations as `private` in `Mle` class

src/lib/spinel/radio_spinel_impl.hpp, tests/scripts/expect/posix-rcp-restoration.exp
Current implementation of RestoreProperties() assumes there's always a networkInfo structure stored in the settings. But, it's possible the RCP device needs to be recovered before this structure is populated.
This commit change this behavior and allows the structure to not exist yet.
=> [spinel] networkInfo may not exist when recovering from RCP failure

examples/platforms/simulation/CMakeLists.txt, examples/platforms/simulation/dns.c, src/core/net/dnssd_server.cpp, src/core/net/dnssd_server.hpp
This commit contains changes and enhancements in the DNS-SD server/resolver class `Dns::ServiceDiscovery::Server`.
- It defines `Request` and `Response` structures, which contain all related information for a DNS query request and response. These structures simplify the code by encapsulating all the related information in one place.
- The `Response` class provides methods for preparing the response, such as appending records, DNS names to the response, or checking the questions or updating the header. These methods replace the previous `static` methods, which required all the information to be passed as input parameters.
- The `QueryTransacation` type is simplified by declaring it as a subclass of `Response`. It inherits all the helper methods from `Response`. Other previously defined …
=> [dnssd-server] simplifications and enhancements

src/core/thread/network_data_leader.cpp, tests/scripts/thread-cert/border_router/test_firewall.py
In `LeaderBase::RouteLookup()`, OT currently checks the source address of the packet to ensure it matches any of the Prefix TLV in leader's netdata. Actually it should also verify that the Prefix TLV has a Border Router sub-TLV. 
In the current implementation, OT may wrongly send/forward a packet to BR when its source address matches with a Prefix TLV which only contains an External Route sub-TLV. This lets BR accidentally forward packets from Thread to infra network. For example, a packet from Mesh-Local address to On-Link address will be wrongly forwarded to infra network.
I recently noticed this problem because we're now using either `fc00:/7` or `::/0` for external routes in netdata, which always matches Mesh-Local source addresses and makes the issue more obvious.
=> [netdata] fix the source address check in `LeaderBase::RouteLookup()`

src/core/net/dns_client.cpp, src/core/net/dns_client.hpp
This commit updates the `CheckForHostNameAlias()` method to handle the case where the response may include multiple CNAME records. For example, host name mapped to another name which is itself mapped again. In order to detect CNAME record loops, we limit the number of CNAME record name changes to `kMaxCnameAliasNameChanges = 40`.
---
Thanks to @tom-brown-kr for finding and reporting [this](https://github.com/openthread/ot-nrf528xx/issues/623) and also helping validate the change.
=> [dns-client] handle multiple CNAME record in response

src/lib/spinel/radio_spinel_impl.hpp, src/posix/platform/hdlc_interface.hpp
Remove call to `WaitResponse` after calling `HardwareReset` which didn't
trigger any spinel transaction.
`kOpenFileDelay` change form 500 to 50.
=> [posix] fix rcp reset flow in `ResetRcp`

include/openthread/instance.h, include/openthread/link_metrics.h, src/cli/cli.cpp, src/cli/cli.hpp, src/core/thread/link_metrics.cpp, src/ncp/ncp_base.hpp, src/ncp/ncp_base_mtd.cpp
This PR updates the type of parameter `status` in `otLinkMetricsReportCallback`
and `otLinkMetricsMgmtResponseCallback` from `uint8_t` to `otLinkMetricsStatus`
for better readability.
=> [link-metrics] update link metrics callback parameter

src/core/mac/data_poll_sender.cpp, src/core/mac/mac.cpp, src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, src/core/mac/mac_types.cpp, src/core/mac/mac_types.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder_ftd.cpp, tests/unit/test_mac_frame.cpp
This commit updates the `InitMacFrame()` method to allow the caller to specify whether the source or destination PAN IDs are present or not. It also handles all cases related to PAN ID compression as defined by IEEE 802.15.4-2015. While these cases are not used by the Thread stack itself, adding them to `InitMacFrame()` makes it more capable allowing future use-cases of this method such as generating enhanced ACKs based on a received frame.
The `test_mac_frame` unit test has been updated to cover the newly added cases.
=> [mac-frame] update `InitMacFrame()`

src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/mle_types.cpp, src/core/thread/mle_types.hpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp, src/core/thread/router_table.cpp, src/core/thread/router_table.hpp
This commit reorganizes the MLE constants that were previously defined in the `mle_types.hpp` header file.
Global constants (those that are used by multiple classes) are kept in `mle_types.hpp`. Other constants are moved to the specific class that uses them. For example, many of the delay and timeout definitions are now defined in the `Mle` and `MleRouter` classes as `private` constants.
Some of the constants are renamed to simplify or shorten their names, or to make it clear how they are used. Also, some of the time interval constants are now defined directly in milliseconds (avoid using `Time::SecToMsec()`).
=> [mle] reorganize MLE constants

src/core/mac/mac_frame.cpp, src/core/mac/mac_frame.hpp, tests/unit/test_mac_frame.cpp
This commit updates the `GenerateEnhAck()` method to add checks to validate the received frame before preparing the ACK. These checks are added as a safeguard in case the caller (radio platform implementation) does not validate the received frame before calling this method to generate the ACK.
Specifically, the checks verify that the received frame is using the 2015 version, has the "Ack Request" flag, has a valid source address (which is used as the destination in the generated ACK), and has a valid destination address that is not broadcast. The checks also verify that if the received frame is secured, it uses security level `kSecurityEncMic32`.
The commit also simplifies the code by using `InitMacHeader()` to prepare the header and addresses. Enhanced ACK frames always have a …
=> [mac-frame] update `GenerateEnhAck()` to use `InitMacHeader()`

src/core/net/dns_types.cpp, src/core/net/dns_types.hpp, src/core/net/dnssd_server.cpp, src/core/net/dnssd_server.hpp, tests/unit/test_dns.cpp, tests/unit/test_dns_client.cpp
This commit simplifies and enhances the DNSSD Server implementation:
- A new method, `ParseQuestions()`, has been added to process the questions in a received `Request` message and determine the `QueryType`.
- The processing and appending of the query DNS name has been simplified. The query name is now read and copied label by label from the `Request` message into the `Response`. When matching the name against SRP entries, the names are compared with the query name directly as it is encoded in the `Response` message using the `Dns::Name::CompareName()` method. This approach is more flexible and simpler, and it works for all query types and name formats, including service instance names where the first label can itself contain a dot (`.`) character. This simplification allows us to remove …
=> [dnssd-server] determine query type & simplify processing of query name

src/posix/main.c, src/posix/platform/daemon.cpp, src/posix/platform/daemon.hpp, src/posix/platform/openthread-posix-config.h
The CLI interface for the posix daemon ise useful for testing and debugging
but may not be useful for release/user builds. on size sensitive plaforms such
as Android (disabling the daemon CLI will reduce the ot-daemon binary size
on Android by around 150 KB).
So this commit defines config "OPENTHREAD_POSIX_CONFIG_DAEMON_CLI_ENABLE"
to make the daemon CLI interface optional.
When CLI is disabled for the daemon, the ot-ctl output will be like:
```
➜  openthread git:(ot-optional-daemon-cli) ✗ sudo ./build/src/posix/ot-ctl -I wpan7    
[sudo] password for wgtdkp: 
Error: CLI is disabled!
Error: CLI is disabled!
```
=> [posix] allow disabling CLI for daemon

src/core/thread/indirect_sender.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp
This commit removes default parameters from methods in `MeshForwarder` class
=> [mesh-forwarder] minimize use of default parameters in methods

include/openthread/dataset.h, include/openthread/instance.h, src/cli/cli_dataset.cpp, src/cli/cli_dataset.hpp
This commit simplifies the `Cli::Dataset` implementation by defining an array of `ComponentMapper` structures. Each `ComponentMapper` structure corresponds to a Dataset component, and provides the following information:
- The component's CLI name
- A method pointer to output that component
- A method pointer to parse that component
- A pointer to the component's mIsPresent boolean flag
A new `LookupMapper()` method allows us to find (using binary search) the entry corresponding to a given component name. This model allows us to reuse code patterns for the main dataset sub-commands, `mgmtsetcommand`, and `mgmtgetcommand` commands when outputting or parsing dataset components.
=> [cli] simplify `dataset` commands

src/core/mac/mac.cpp
In multi-radio scenarios, any key sequence change currently resets the MAC frame counter for the PHY link over which the first frame (with new keyId and frame counter) is received. Since the neighbor key sequence is already modified, any subsequent frame received over the alternate PHY would have match the neighbor key sequence, but potentially smaller frame counter, which leads to drops due to security failure
=> [trel] bugfix for MAC security failure on key sequence change

src/core/meshcop/commissioner.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/meshcop/meshcop_tlvs.hpp
Hi,
Because of problems that I encountered while using `commissioner mgmtset` command (described [here](https://github.com/openthread/openthread/discussions/9326)), I decided to extend the log message to include a State value sent by the Leader.
=> [meshcop] print TLV State after receiving responses

examples/platforms/utils/uart_rtt.c
This PR fix a compiling issue involved by PR  [[cli] support RTT as cli interface #9148 ](https://github.com/openthread/openthread/pull/9148). If macro `OPENTHREAD_UART_RTT_ENABLE` is not enabled, the file `SEGGER_RTT.h` and related should not be inlcuded.
=> [cli] fix RTT compiling issue

src/core/mac/data_poll_handler.cpp, src/core/mac/data_poll_handler.hpp
Whenever an indirect/CSL transmitted frame is being purged or replaced,
make sure that both indirect and CSL transmission attempts counts are
reset in order to avoid issues like considering a new frame as a
retransmission.
=> [data-poll-handler] reset tx attempts when replacing a frame

.github/workflows/size.yml, script/check-size
This commit updates the `check-size` script to generate a formatted table on a branch push. The table will first include the code size difference for all binary files, followed by the difference for all library files. This allows us to use the `check-size` script on local machines during development to get a full size impact report, similar to what will be reported on the GitHub Action branch push.
This commit also generates a size report for posting on a pull request in Markdown format. In particular, the table with the size difference for all library files is added as a collapsible section after the main table for binary files.
---
This is part of a sequence of PRs. The generated PR report (in makrdown format) is not yet posted on PR (requires changes to the `size.yml`). Example of how …
=> [script] `check-size` to generate formatted table on push

src/core/common/linked_list.hpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, tests/unit/test_linked_list.cpp
This commit enhances `Srp::Server` to process and commit the completed `UpdateMetadata` entries (signaled by the "proxy service handler" calling `HandleServiceUpdateResult()`) from a `Tasklet`. This change is helpful in the case where the `HandleServiceUpdateResult()` callback is invoked directly from the "update service handler" itself. While `Srp::Server` can handle this situation, the change makes it easier for platform implementations of advertising proxy.
In particular, it addresses an issue with the `otbr` advertising proxy implementation. This implementation can potentially access an already freed `Host` object. This can happen because the implementation may hold on to the `Host` object while iterating over its `Service` entries as advertising an earlier `Service` of the same …
=> [srp-server] process completed update from proxy from taskelt

include/openthread/instance.h, include/openthread/platform/radio.h, include/openthread/platform/time.h, src/core/mac/mac_frame.hpp, src/core/mac/sub_mac.cpp, src/core/mac/sub_mac.hpp, src/core/thread/csl_tx_scheduler.cpp, src/core/thread/csl_tx_scheduler.hpp
Hi OpenThread community and above all @edmont , I'm heading over to you guys to adjust OpenThread to a recent unification of timing concepts in the Zephyr IEEE 802.15.4 implementation.
In a nutshell this small change set proposes to align some of the timing sensitive aspects of OpenThread even more closely with concepts from the underlying standards. Unification and closer specification of timing along original IEEE 802.15.4 concepts enables implementation of additional non-Thread IEEE 802.15.4 features in Zephyr (namely TSCH).
Most of this change set is documentation - only a small change is being made to the interpretation of the TX timestamp that seems not to be particularly restricted in OpenThread so far. I propose that we make use of this leeway to jointly move closer to …
=> [mac] document and adjust to standards based timing concepts

src/core/mac/mac.cpp, src/core/mac/mac.hpp
Ignore a CSL IE with period set to 0.
Accepting it would eventually lead to a division by 0 fault in `CslTxScheduler::GetNextCslTransmissionDelay`.
=> [csl] ignore zero valued CSL IE period

include/openthread/instance.h, include/openthread/link_metrics.h
The core config file shouldn't be included in public API headers
because they will be included from high level project code (like 
ot-br-posix) and the config file cannot be located if included here.
=> [include] remove include of core config file

src/core/thread/address_resolver.cpp
This commit updates `AddressResolver::Resolve()` to validate that the associated RLOC16 is reachable in the sense that a valid next hop can be found towards it, before using a matching cache entry in `mCachedList` or `mSnoopedList`. If the RLOC16 is not reachable, the cache entry is removed to trigger a new address query.
----
Should address https://github.com/openthread/openthread/issues/9409
=> [address-resolver] remove cache entry if its RLOC16 is unreachable

src/core/mac/mac.cpp
- This commit resolves inconsistency between Host and RCP channel on scan energy when network not created.
- Added fix in MAC layer to update the channel on scan energy
Fixes #9394
=> [mac] fix channel switching issue during energy scan

src/core/thread/network_data_leader_ftd.cpp
This commit updates `HandleNetworkDataRestoredAfterReset()` which is called when a leader device is reset and recovers the Network Data from other routers. With the new code, leader will now check and remove entries in the restored Network Data that are from any currently unallocated router ID.
This change acts as a safeguard against an edge case where the leader is reset at an inopportune time, such as right after it removed an allocated router ID and sent MLE advertisement but before it got the chance to send the updated Network Data to other routers.
=> [netdata] remove unallocated router ID entries on recovery after reset

.github/workflows/otbr.yml, script/test, src/core/net/ip6.cpp, src/core/net/ip6.hpp, tests/scripts/thread-cert/border_router/test_firewall.py, tests/scripts/thread-cert/node.py
This PR implements the packet logic in OT core. It aims to have the same effect as what's already achieved by our iptables-based firewall. Instead of leveraging iptables, this PR filters the border routing packets in user space by checking the source/destination addresses of a packet. 
This PR also adds a job to do BR regression test when this feature is enabled and iptables-based firewall is disabled.
Depends-On: openthread/ot-br-posix#1997
=> [firewall] implement packet filtering in OT core

src/lib/spinel/radio_spinel.hpp, src/lib/spinel/radio_spinel_impl.hpp
This commit saves the MAC counter to a local variable to avoid calling the core function `Get<Settings>().Read()` in `radio_spinel_impl.hpp`. This is useful when spinel module is used as a lib in other projects.
=> [spinel] save MAC frame counter to a local variable

src/posix/platform/openthread.conf.example, tests/scripts/expect/posix-channel-mask.exp
The default supported channel mask is set to 0x7fff000 in the default configuration file. The dbus client test case sets the channel to 11 which is not valid in the supported channel mask. It causes the CI test failures in https://github.com/openthread/ot-br-posix/pull/2027.
This commit updates the default supported and preferred channel masks in the configuration file to avoid the ot-br-posix CI test failures.
=> [posix] update the default channel masks in the configuration file

src/core/meshcop/border_agent.cpp, src/core/meshcop/border_agent.hpp
This commit updates `ForwardContext` to be `Heap::Allocatable` and uses `OwnerPtr` to simplify the ownership (and freeing) of allocated `ForwardContext` objects.
=> [border-agent] simplify `ForwardContext` allocation and ownership

src/posix/platform/CMakeLists.txt
This PR is associated with [ot-br-posix/pull/2011](https://github.com/openthread/ot-br-posix/pull/2011#issuecomment-1726709515) and [openthread/pull/8065](https://github.com/openthread/openthread/pull/8065).
According to the description of https://github.com/openwrt/openwrt/pull/11559, libanl is already included in the musl c library, so we can turn this option on.
We enable OPENTHREAD_POSIX_CONFIG_NAT64_AIL_PREFIX_ENABLE on OpenWrt platform for better experience.
=> [nat64] enable discovering NAT64 AIL prefix for OpenWRT

src/core/config/tmf.h
This commit sets the default value of the configuration `TMF_ADDRESS_CACHE_MAX_SNOOP_ENTRIES` to `1/16` of the total number of address cache entries. This ensures that the snoop entries scale with the total number of entries.
~To accommodate this change, the default configuration for the total number of entries on a Border Router is also increased to 273, of which 17 can be used for snoop optimization~.
=> [tmf] set default snoop cache entry count to 1/16 of total

src/lib/spinel/radio_spinel_impl.hpp
This commit changes openthread rcp recovery code to keep mstate as kStateDisabled if the state before recovery was kStateDisabled. This is needed to avoid otbr-agent crash in the scenario where rcp recovery is triggered before otbr initialization.
=> [spinel] reset `mState` to `kStateDisabled` if recovering from `kStateDisabled`

src/core/thread/address_resolver.hpp
Resolves issues when `OPENTHREAD_CONFIG_TMF_ADDRESS_CACHE_ENTRIES` is too small.
Example: https://github.com/openthread/ot-cc2538/actions/runs/6300278091/job/17102757934
=> [address-resolver] set minimum `kMaxNonEvictableSnoopedEntries` to `1`

script/test
This PR excludes `ot_testing` and `__pycache__` directories when copying the files before building the docker.
Such files are usually generated by root user and will cause errors when copying them as a non-root user.
=> [script] exclude `ot_testing` and `__pycache__` when building the OTBR docker

src/posix/platform/netif.cpp
Added validation to check for the negetive value of sMLDMonitorFd, as setsockopt parameter cannot be negative
=> [posix] address coverity warning: argument cannot be negative

src/core/meshcop/joiner.cpp
An invalid Discovery Response that carries no Joiner UDP Port TLV will be accepted by the joiner, but we shouldn't qualify it as a valid joiner router since we can only open a connection with a non-zero port.
=> [joiner] check for non-zero joiner UDP port before electing a joiner router

src/core/thread/mle_router.cpp
This commit simplifies the checks to decide whether or not to call `ProcessRouteTlv()` in `MleRouter::HandleAdvertisement()`. The whole check is guarded by `aRxInfo.IsNeighborStateValid()`, which ensures that we only process Route TLVs for Advertisements received from valid neighbors. In particular, we can remove the additional checks in the case where the device is itself `IsChild()` (i.e., acting as an FED). In this case, `aRxInfo.mNeighbor` will be determined using `NeighborTable::FindNeighbor()`, which checks and accepts the parent as the only valid neighbor of the FED child.
=> [mle] simplify `ProcessRouteTlv()` call in `HandleAdvertisement()`

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/net/nd6.cpp, src/core/net/nd6.hpp
This commit adds the `RaFlagsExtOption` class to represent an "RA Flags Extension" Option. It also adds code to `RoutingManager` class to process this option in received RA messages and check whether or not the Stub Router Flag is set. Additionally, it checks and tracks whether or not the `M` (Managed Address) and `O` (Other Config) flags are set in the received RA message's header.
----
Related to [SPEC-1217](https://threadgroup.atlassian.net/browse/SPEC-1217)
=> [nd6] add `RaFlagsExtOption` and track flags in received RAs

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/config/border_routing.h, tests/unit/test_routing_manager.cpp
This commit introduces a new configuration option for the routing manager to use heap-allocated entries in the `DiscoveredPrefixTable`, which maintains a list of discovered routers and their advertised on-link prefixes. This makes the implementation more flexible when dealing with a large number of routers and/or discovered prefix entries.
The config option `OPENTHREAD_CONFIG_BORDER_ROUTING_USE_HEAP_ENABLE` enables this behavior. By default, it is enabled. When disabled, the previous model, which uses pre-allocated arrays and pools, is used instead.
This commit also updates the unit test `test_routing_manager` to track heap allocations and validate that all heap allocations by the routing manager are freed when it is stopped.
-------
- This PR currently contains the commit from …
=> [routing-manager] new config to use heap for `PrefixTable` entries

.github/workflows/build.yml
This commit fixes the version of `codespell` installed in the `spell-check` job of `build` workflow to version `2.2.4`.
----
- Addresses https://github.com/openthread/openthread/issues/9480
=> [github-actions] fix the `codespell` version in `spell-check` job

src/core/api/backbone_router_ftd_api.cpp, src/core/backbone_router/bbr_local.cpp, src/core/backbone_router/bbr_local.hpp, src/core/thread/mle_router.cpp
This commit contains smaller changes in `BackbonRouter::Local`:
- `AddService()` now gets a `RegisterationMode` enum as its input either decide based on current state or force registration.
- We remove the `NetworkData::Notifier::HandleServerDataUpdated()` calls after calling `AddService()` since `AddService()` method itself will already call this (when successfully adds the service to Network Data)
- We also remove the extra state check before calling `AddService()` as it is done by the `AddService()` method itself.
=> [bbr-local] simplify `AddService()` and its use

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp
This commit updates the attach process to the same partition after a router/REED losing connectivity to the leader. It removes the `kSamePartitionRetry` enumerator from `AttachMode`. With this change, after trying to attach using `kSamePartition` attach mode (with a total of six Parent Request attempts to Routers and REEDs), the device will switch to `kAnyPartition` attach mode. This helps to reduce the total number of attempts before the device can decide to take the leader role.
----
- Related to [disc#9478](https://github.com/orgs/openthread/discussions/9478) and [SPEC-1036](https://threadgroup.atlassian.net/browse/SPEC-1036).
=> [mle] simplify reattach on losing connectivity to leader

src/core/thread/mesh_forwarder.cpp, src/core/thread/mle.cpp, src/core/thread/mle.hpp
Currently, when SED sends out the Child ID request, the first data poll goes out immediately (from the SendChildIDRequest method in MeshForwarder (snippet A). This does not check for any failures in RCP or SubMac (Channel Access failures or Abort which can cause Child ID request to fail transmission). In such failure scenarios, additional data polls are sent out (to retrieve Child ID response which seems like wasted OTA transmissions).  Request to delay the start of data polling procedure after the Child ID request is sent successfully. 
Please check if this PR can address the requested change under all scenarios. Thanks for the review. 
Snippet A (SendChildIDRequest):
SuccessOrExit(error = message->SendTo(destination));
Log(kMessageSend,
(mAddressRegistrationMode == kAppendMeshLocalOnly) …
=> [mle] send data polls after Child ID Request ack

include/openthread/crypto.h, include/openthread/instance.h, include/openthread/joiner.h, include/openthread/nat64.h, include/openthread/netdata_publisher.h, include/openthread/thread_ftd.h, src/core/border_router/routing_manager.hpp, src/core/coap/coap.hpp, src/core/mac/mac_frame.hpp, src/core/meshcop/dataset.hpp, src/core/thread/network_diagnostic_tlvs.hpp, src/core/thread/router_table.hpp, src/core/utils/mesh_diag.hpp
This commit fixes typos in Doxygen documentation, ensuring that `@param` variable names match the function/method declaration. It also adds any missing `@param` tags and removes extra ones.
=> [docs] fix typos in Doxygen documentation

src/core/radio/trel_interface.cpp, src/core/thread/mle.cpp, src/core/thread/neighbor_table.cpp, src/core/thread/neighbor_table.hpp
This commit updates `Mle` class such that on an FED (FTD child) when an MLE message is received, we use `FindRxOnlyNeighborRouter()` in addition to `FindNeighbor()` before performing security check. This ensures that the key sequence and frame counters are validated for all messages from rx-only neighbors.
After security check and before calling `Handle{MleCommand}()` we clear the `neighbor` if it is a rx-only except for a subset of MLE messages such as MLE Advertisement. This ensures that, as an FED, we are selective about which messages to process from rx-only neighbors.
This commit also adds a new flavor of `FindRxOnlyNeighborRouter()` that accepts an `Mac::ExtAddress` as its input parameter.
=> [mle] handle received Advertisements from `RxOnlyNeighbor` on FED

src/core/border_router/routing_manager.cpp, src/core/config/border_routing.h, src/core/net/nd6.cpp, src/core/net/nd6.hpp, tests/unit/test_routing_manager.cpp
This commit updates `RoutingManager` to include the Flags Extension Option with Stub Router flag in its emitted Router Advertisement messages.
Config `STUB_ROUTER_FLAG_IN_EMITTED_RA_ENABLE` can be used to enable or disable this behavior which is enabled by default.
=> [routing-manager] include Stub Router flag in emitted RAs by BR

src/core/api/thread_ftd_api.cpp, src/core/backbone_router/bbr_local.cpp, src/core/thread/dua_manager.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp, src/core/thread/network_data_notifier.cpp
This commit adds `RouterRoleTransition` nested class to `MleRouter`. This class tracks the timeout and jitter intervals for router role transitions, i.e., device upgrading to router role from REED or downgrading from router to REED. It provides helper methods like `IsPending()` and `StartTimeout()` to check if role transition is pending or to start the timeout countdown. These methods help to simplify the code.
=> [mle-router] add `RouterRoleTransition` nested class

.github/workflows/build.yml, src/core/crypto/crypto_platform.cpp, third_party/mbedtls/mbedtls-config.h
As per the mbedTLS v3.5.0 release notes:
Ref: https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-3.5.0
`MBEDTLS_CIPHER_BLKSIZE_MAX is deprecated in favor of MBEDTLS_MAX_BLOCK_LENGTH (if you intended what the name suggests: maximum size of any supported block cipher) or the new name MBEDTLS_CMAC_MAX_BLOCK_SIZE (if you intended the actual semantics: maximum size of a block cipher supported by the CMAC module).`
This commit fixes the build issue keeping the backward compatibility intact.
=> [crypto-platform] fix build issue with mbedtls v3.5.0

src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp
This commit updates `MeshForwarder::SendMessage()` on FTD to check if the message is marked for direct transmission and/or indirect transmission to a sleepy child. If there is no pending transmission, the message is removed.
This situation can occur if the message destination is a multicast address larger than realm-local scope. In such a case, `SendMessage()` skips `SetDirectTransmission()` on the message (since such message will be forwarded using IP-in-IP encapsulation by `Ip6` module) and assumes the message is for a sleepy child. However, if none of the children are subscribed to this address, the message will not be marked for indirect transmission either. Without the fix in this commit, such messages would have remained in the `mSendQueue` and not been removed or freed, as messages …
=> [mesh-forwarder] remove message if no pending tx in `SendMessage()`

src/core/api/coap_api.cpp, src/core/api/ip6_api.cpp, src/core/api/udp_api.cpp, src/core/common/message.hpp, src/core/net/ip6.cpp
This commit adds helper methods to the `Message` class to check if the message origin matches a specific origin. These methods are used in the code as syntactic sugar to simplify the code.
=> [message] add `IsOrigin{}()` helper methods

src/cli/README.md, src/cli/cli.cpp
This commit updates the `ip6addr -v` CLI command to provide more information about each address including origin, prefix length, and preferred and valid flags.
=> [cli] update `ip6addr -v` to include more info about address

src/core/net/ip6_mpl.cpp, src/core/net/ip6_mpl.hpp
This commit contains smaller changes in `HandleRetransmissionTimer()`:
- Remove nested if/else blocks and use `continue`.
- We clone the MPL message if more retx are needed, otherwise use the `message` directly.
- In both cases, we now use the same code path for preparing and sending the `message`, avoiding repeated code.
- Rename `GetTimerExpirations()` to `DetermineMaxRetransmissions()`.
=> [ip6-mpl] simplify `Mpl::HandleRetransmissionTimer()`

src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/net/ip6_mpl.cpp, src/core/net/ip6_mpl.hpp
With the recent addition of `GetOrigin()`, the origin of a message is tracked by `Message` itself. With this change, we no longer need to pass `aIsOutbound` to `Ip6::Mpl` methods, as it can be determined from the origin of `aMessage`. This commit simplifies the code by removing the `aIsOutbound` input parameter.
=> [ip6-mpl] remove `aIsOutbound` input and use `aMessage.GetOrigin()`

include/openthread/instance.h, include/openthread/ping_sender.h, src/cli/README.md, src/cli/cli.cpp, src/core/utils/ping_sender.cpp, tests/toranj/cli/test-008-multicast-traffic.py
This commit updates `PingSender` and its config to include a `mMulticastLoop` flag and allow the caller to set this flag. When set, multicast ping echo request messages are looped back and received by the device itself if it is subscribed to the same address. The `ping` CLI command is also updated to allow setting this flag.
This commit also updates `test-008-multicast-traffic.py` to add new test cases to cover the multicast loop flag behavior (pinging with or without this flag). In particular, it covers when the ping destination is a realm-local multicast address and when it is a larger-than-realm-local multicast address (where the `ot::Ip6` module would use a tunnel header for forwarding the message).
=> [ping-sender] allow setting multicast loop

src/core/net/ip6.cpp, src/core/net/ip6.hpp
This commit adds `Ip6::PrepareMulticastToLargerThanRealmLocal()`, which prepares to transmit a multicast message with destination larger than realm-local address. It checks if any sleepy child of device is subscribed to the multicast address and clones the message for indirect tx if needed, before adding the IP-in-IP tunnel header. The new method helps remove repeated code in `SendRaw()` and `SenDatagram()`.
=> [ip6] add `PrepareMulticastToLargerThanRealmLocal()`

include/openthread/instance.h, include/openthread/ip6.h, src/cli/cli.cpp, src/core/api/ip6_api.cpp, src/core/net/netif.cpp, src/core/net/netif.hpp, src/posix/platform/netif.cpp
This commit contains the following smaller changes in `Ip6` and its public APIs:
- Updates the `otNetifAddress.mNext` field to be a pointer to `const`. This prevents users of OT APIs from modifying addresses as they iterate over the list of addresses. The `otNetifMulticastAddress` structure already uses this model.
- Adds new API `otIp6HasUnicastAddress()` to check whether or not a unicast IPv6 address is assigned to the Thread interface. This is used to simplify CLI and `posix/platform/netif.cpp`.
- Fixes the returned error from `otIp6AddUnicastAddress()` to be `OT_ERROR_INVALID_ARGS` when the address is a Thread internal address, to match the documentation.
- Fixes documentation and style in `ip6.h`.
=> [ip6] update `otNetifAddress.mNext` to be pointer to `const`

src/core/mac/mac.cpp
This commit updates `Mac::LogFrameTxFailure` to skip logging when `Trel::Interface` is disabled.
=> [mac] skip logging trel frame tx error when trel interface is disabled

src/core/meshcop/meshcop_leader.cpp
This commit adds an `IsLeader()` check to ensure that the device is acting as the leader before processing `kUriLeaderPetition` or `kUriLeaderKeepAlive` TMF messages. This adds a safeguard to ensure that only the leader can update the commissioner dataset.
=> [meshcop] check `IsLeader()` before processing `LeaderPetition/KeepAlive`

.github/workflows/size.yml
This commit uses `GITHUB_STEP_SUMMARY` to add a summary (in markdown format) to the GitHub action workflow `size.yml` runs.
----
Example of the output: https://github.com/openthread/openthread/actions/runs/6518855521
=> [github-actions] add job summary to `size.yml` workflow

src/core/api/ip6_api.cpp, src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/net/nat64_translator.cpp, src/core/thread/child_supervision.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mesh_forwarder_mtd.cpp
This commit updates the `Ip6` class to use `OwnedPtr<Message>`. This smart pointer automates the freeing of messages and helps to simplify the code by removing all the logic that tracks whether a message needs to be freed. It also makes the transfer of ownership of `Message` instances between methods more clear.
=> [ip6] use `OwnedPtr<Message>` to simplify message lifetime

src/core/meshcop/dataset.hpp
This commit updates the `Dataset::SetTlv<ValueType>()` documentation to mention its specifications for `uint` types (which use big-endian encoding). It also adds `static_assert` checks to ensure that the general template implementation is not used with `uint16/32/64` types.
=> [dataset] highlight `SetTlv<ValueType>()` specializations in the docs

src/core/common/tlvs.cpp, src/core/common/tlvs.hpp, src/core/meshcop/dataset.cpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/thread/network_data_leader.cpp
This commit moves the helper methods to find a specific TLV in a sequence of TLVs from the `MeshCoP::Tlv` class to the base `Tlv` class. This makes these helper methods accessible to all subclasses.
=> [tlv] add helper method to find/read TLVs in a sequence of TLVs

include/openthread/instance.h, include/openthread/logging.h, src/core/api/logging_api.cpp, src/lib/spinel/radio_spinel.cpp, src/lib/spinel/radio_spinel.hpp
This commit adds new public OT logging APIs `otLogPlat()` and `otLogPlatArgs()`, which allow the caller to specify a platform sub-module name to be included in the emitted log. This makes it easier to distinguish logs from the platform layer and filter the logs.
This commit also updates the `RadioSpinel` class to use the new API, ensuring that its logs use the "P-RadioSpinel" module name.
=> [logging] add new `otLogPlat()` APIs with sub-module name

src/lib/spinel/radio_spinel.cpp
In RadioSpinel::SetMacKey we try to reuse the otMacKey passed to export the literal key from PSA to be sent over SPINEL to RCP. But as the passed param is const, we cant really use this. Better option is to extract it into a local buffer and use that to pass the keys to RCP.
Use OT_MAC_KEY_SIZE instead of sizeof.
Simplify RCP restoration code.
Fixes #9515
=> [spinel] use local variables to export mac key before sending over SPINEL

src/core/meshcop/meshcop_leader.cpp, src/core/meshcop/meshcop_leader.hpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp
This commit contains smaller changes in` MeshCoP::Leader` class:
- Changes `CommissioningData` to be a `private` type in this class
- Adds `Init()` to `CommisioningData()` to init all sub-tlvs.
=> [meshcop-leader] simplify adding `CommissioningData`

src/lib/spinel/radio_spinel.cpp, src/lib/spinel/radio_spinel.hpp
This commit simplifies the `RadioSpinel::SetMacKey()` method. A common `private` overload of `SetMacKey()` is added that uses `const otMacKey &` as its input key type.
When `KEY_REFERENCES_ENABLE` is not enable the `SetMacKey()` simply passes the key from the `otMacKeyMaterial` directly. This avoids the unnecessary copying of the key into a local variable.
When `KEY_REFERENCES_ENABLE` is enabled, the keys are read from secure storage. A new `ReadMacKey()` helper method is added which also validates that the read key size is correct.
=> [radio-spinel] simplify `SetMacKey()`

src/core/backbone_router/bbr_manager.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/joiner_router.hpp, src/core/meshcop/meshcop.cpp, src/core/meshcop/meshcop.hpp, src/core/meshcop/meshcop_leader.cpp, src/core/thread/energy_scan_server.cpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle_router.cpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp, src/core/thread/network_data_leader_ftd.cpp
This commit contains changes related to parsing of Commissioning Dataset sub-TLVs in `NetworkData::Leader`:
- Adds `FindInCommisioningData<SubTlvType>` to search for a given `SubTlvType` in Commissioning Data.
- Adds `FindCommissioningSessionId()`, `FindBorderAgentRloc()`, and `FindJoinerUdpPort()` to parse and get get the info from Commissioning Dataset.
=> [netdata] simplify parsing of Commissioning Dataset sub-TLVs

src/core/thread/network_data_leader.hpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp
This commit simplifies the handling of `kUriCommissionerGet` TMF message and preparation of its response.
=> [netdata-leader] simplify `HandleTmf<kUriCommissionerGet>`

src/core/api/udp_api.cpp, src/core/meshcop/border_agent.cpp, src/core/net/udp6.cpp, src/core/net/udp6.hpp
This commit removes the input `aIpProto` in `Upd::HandleDatagram()` method and assumes `kProtoUdp`.
=> [udp] remove `aIpProto` from `Ip6::Udp::SendDatagram()`

src/core/meshcop/meshcop_leader.hpp, src/core/thread/network_data_leader_ftd.cpp
This commit updates `HandleNetworkDataRestoredAfterReset()`, which is called after Network Data is restored on the leader after a leader reset and recovery.
We now resign any active Commissioner by clearing the Commissioning Data and adopt the Session ID from the restored Network Data Commissioning Data. This ensures that any stale Commissioning Data is not retained in Network Data for longer after a leader reset
=> [netdata] resign active commissioner on NetData restore on leader

src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_leader_ftd.hpp
This commit updates `HandleTmf<kUriCommissionerSet>()`, which is used to set the Commissioning Dataset. The following changes have been made:
- `Tlv::Find<TlvType>()` methods are used to find and parse TLVs in the received request message.
- The existing code required the dataset to contain either Joiner UDP or Steering Data TLVs. This check has been removed, making the implementation aligned with the Thread specification. This permits a commissioner to disallow MeshCoP Joining by not including Steering Data.
- A new flavor of `SetCommisioningData()` is added, which reads the TLVs directly from a given `aMessage`. This method is now used when processing `kUriCommissionerSet` to avoid using temporary local buffers to read and copy the TLVs.
- `SetCommisioningData()` and its related methods …
=> [netdata] simplify and update `HandleTmf<kUriCommissionerSet>()`

include/openthread/commissioner.h, include/openthread/instance.h, include/openthread/netdata.h, src/cli/README_NETDATA.md, src/cli/cli_network_data.cpp, src/cli/cli_network_data.hpp, src/core/api/netdata_api.cpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/commissioner.hpp, src/core/meshcop/meshcop.hpp, src/core/thread/network_data_leader.cpp, src/core/thread/network_data_leader.hpp, tests/scripts/thread-cert/node.py, tests/toranj/cli/cli.py, tools/harness-thci/OpenThread.py
This commit adds `otNetDataGetCommissioningDataset()` as a public API to retrieve the Commissioning Dataset from the Network Data.
It also updates CLI `netdata show` command to output the Commissioning Dataset information. The documentation in `README_NETDATA.md` and in `cli_network_data` are also updated. The test scripts that parse `netdata show` output are also updated.
=> [nedata] add API to retrieve Commissioning Dataset

include/openthread/instance.h, include/openthread/link.h, include/openthread/platform/radio.h, src/cli/cli.cpp, src/core/api/link_api.cpp, src/core/mac/mac.cpp, src/core/mac/mac.hpp, src/core/radio/radio.hpp, src/core/thread/mle.cpp, tests/scripts/expect/posix-channel-mask.exp
The current code of the `mac.cpp` caches the supported channel mask to a local variable. But the supported channel mask may be changed after the country code is changed. This will cause the supported channel mask used in `mac.cpp` to be inconsistent with the actual supported channel mask.
This commit adds an API `otLinkSetRegion()` to set the region code and then update the cached supported channel mask to avoid the channel mask inconsistencies. The current Thread channel may be not included in the new supported channel mask. When the Thread stack detects this case, it detaches the current Thread network gracefully.
=> [mac] update the cached supported channel mask when the region code changes

src/core/border_router/infra_if.cpp, src/lib/platform/exit_code.h, src/posix/platform/include/openthread/openthread-system.h, src/posix/platform/infra_if.cpp, src/posix/platform/infra_if.hpp, src/posix/platform/system.cpp
This PR adds a new API `otSysSetInfraNetif` to support specifying the infrastructure network interface for the platform. This can be useful in following cases:
- The infra link cannot be determined at the start up of `otbr-agent`. We can call this API to specify the infra link without specifying it in the command line arguments.
- Let Thread Border Router switch to another infra link without restarting the whole OpenThread stack.
=> [posix] add `otSysSetInfraNetif` API

src/posix/platform/infra_if.cpp
This commit added validation for whether the pointer (reqs) being freed is nullptr or not.
=> [posix] fix uninitialized pointer read (#9552)

src/lib/spinel/CMakeLists.txt, src/posix/cli.cmake, src/posix/daemon.cmake, src/posix/platform/CMakeLists.txt
The lib `openthread-spinel-ncp` is used by the NCP build and the lib `openthread-spinel-rcp` is used by the RCP build. Both of them don't need the file `radio_spinel.cpp`. This commit removes the `radio_spinel.cpp` from lib `openthread-spinel-ncp` and  `openthread-spinel-rcp`, and adds a new lib `openthread-radio-spinel` to include the `radio_spinel.cpp`. This commit also remove some useless configurations from `src/lib/spinel/CMakeLists.txt`.
Depends-On: openthread/ot-br-posix#2068
=> [build] move `radio_spinel.cpp` to new lib `openthread-radio-spinel`

src/core/thread/dua_manager.cpp, src/core/utils/slaac_address.cpp, src/core/utils/slaac_address.hpp
This commit makes the following smaller enhancements in `Slaac` class:
- Adds a new `ShouldUseForSlaac()` method to check if a network data prefix should be used for SLAAC, checking flags and applying the filter if set.
- Introduces separate `RemoveAddresses()` and `AddAddresses()` methods to manage SLAAC addresses, replacing the previous `Update()` method.
- Adds helper methods to `RemoveAllAddresses()`, `RemoveAddress()` to remove a specific address, and `AddAddressFor(prefix)` to  generate and add an address for a given prefix.
- Simplifies `GenerateIid()` by removing unused input parameters.
=> [slaac] simplify adding/removing addresses and other enhancements

src/core/thread/mesh_forwarder.cpp
This commit updates the duplicate detection mechanism for the frag header tags under `MULTI_RADIO` config. The tag check is now performed upon receiving the first fragment. For subsequent fragments, older tags are permitted to be processed, but they will be discarded if there is no matching entry in the reassembly list.
This change addresses an issue where lowpan fragment frames using older tags could be erroneously discarded if they are interrupted by higher-priority messages (e.g., an MLE message).
----
Should help address https://github.com/openthread/openthread/issues/9588.
=> [multi-radio] perform tag duplication check for first fragment

tests/unit/test_routing_manager.cpp
This commit addresses occasional failures in `test_routing_manager` in the `TestBorderRoutingProcessPlatfromGeneratedNd` case. Unlike other tests, this test sets the `heapAllocations` after the call `InitTest (/* aEnableBorderRouting */ true)` (which enables `RoutingManager`). This means that depending on the random timing, the `heapAllocations` may already count some allocated heap items by `RoutingManager` itself. With the change in this commit, at the end of the test, we check that the number of remaining heap allocations is less than `heapAllocations`.
----
Should address #9602.
=> [test] address occasional failure of `test_routing_manager`

tests/unit/test_routing_manager.cpp
---
Add missing `FinalizeTest()` to `TestBorderRoutingProcessPlatfromGeneratedNd()`. 
The test ran okay today since this test case is the last one (so not finalizing did not cause any issue).
=> [test] ensure to `FinalizeTest()` in `TestProcessPlatfromGeneratedNd()`

src/core/thread/mle.cpp, src/core/thread/mle.hpp
After a router with children downgrades, it's former children will still send child update requests until they timeout. This allows the downgraded device to respond with status TLV indicating error to help those children realize they need to reattach sooner.
=> [mle] fix responding to "Child Update Request" from non-parent device

src/core/api/thread_api.cpp, src/core/instance/instance.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.hpp
---
Under `MTD` the `MleRouter` class provided the following methods: 
- `bool IsSingleton(void) const` - Used from `otThreadIsSingleton()` - Now directly returns `false` when `MTD`
- `Error RemoveNeighbor(Neighbor &)` - Was not used under `MTD`
- `void  RemoveRouterLink(Router &)` - Used in `MeshForwarder` - Now directly calls `BecomeDetached()` when `MTD`
And the following 3 which called the `Mle::` methods of the same name (which now works directly due `typedef Mle MleRouter`).
- `uint16_t GetNextHop(uint16_t aDestination) const;` (changed to be `public` method in `Mle`)
- `Error SendChildUpdateRequest(void)`
- `Error CheckReachability(uint16_t aMeshDest, const Ip6::Header &aIp6Header)`
=> [mle] remove `MleRouter` class definition under `MTD` build

src/posix/platform/netif.cpp
1st commit:
Check and ensure at least the netlink header is received in the netlink socket to be safe before interpreting the buffer as a netlink message.
2nd commit:
Per https://linux.die.net/man/3/netlink, check current message type is not NLMSG_DONE before calling NLMSG_NEXT to properly handle multi-part netlink message.
=> [posix] more robust netlink message handler

include/openthread/dns.h, include/openthread/instance.h, src/core/net/dns_types.cpp, src/core/net/dns_types.hpp, src/core/radio/trel_interface.cpp, tests/unit/test_dns.cpp
This commit introduces `OT_DNS_TXT_KEY_ITER_MAX_LENGTH` with a value of `64` to represent the maximum TXT data key length supported by `otDnsTxtEntryIterator`. We intentionally set this value higher than the recommended maximum key length of `9` (as specified in RFC 6763 section 6.4) to enable the parsing of TXT data when longer keys are employed.
=> [dns] support longer key length in `otDnsTxtEntryIterator`

include/openthread/border_routing.h, include/openthread/instance.h, src/cli/README_BR.md, src/cli/cli_br.cpp, src/cli/cli_br.hpp, src/core/api/border_routing_api.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, tests/unit/test_routing_manager.cpp
This commit adds `otBorderRoutingGetNextRouterEntry` as a new API to iterate over discovered routers on the infrastructure link and get information about them such as their address, their Managed Address Configuration (`M`), Other Configuration (`O`), and Stub Router flags.
The `otBorderRoutingPrefixTableEntry` is also updated to contain the same information.
This commit also updates the CLI `br` sub-commands to provide this information, adding `br routers` to obtain a list of discovered routers.
=> [routing-manager] new API to get list of discovered routers

src/core/thread/mlr_manager.cpp
Compiling with GCC 13.2.0, got the maybe-uninitialized error. This commit fixes it by initializing the array.
=> [lint] explicitly initialize failedAddresses

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/net/nd6.hpp, tests/unit/test_routing_manager.cpp
This commit implements a mechanism in `RoutingManager` to learn the Managed Address Config (`M`) and Other Config (`O`) flags in received RA message from discovered routers on the infrastructure link and copy the same flags in the emitted RA 
message from BR.
If any discovered router on the infrastructure that is not itself a stub router (i.e., does not include the Stub Router flag) includes the `M` or `O` flags, the same flag are included in the emitted RA message. If a discovered router has failed to respond to the maximum number of NS probe attempts, we consider it as offline and ignore its flags.
This commit also adds a detailed test case in `test_routing_manager` to validate the newly added mechanism.
---
- This is related [SPEC-1217](https://threadgroup.atlassian.net/browse/SPEC-1217 …
=> [routing-manager] learn and copy `M` & `O` flags from discovered routers

include/openthread/instance.h, include/openthread/message.h, src/core/api/message_api.cpp
At the moment, C API does not allow to get/set the configuration flag which the message to be looped back to the Thread interface. It is important within the context of sending already prepared IPv6 mutlicast packets with `otIp6Send()`.
=> [ip6] add API functions to enable multicast looping of a message

src/lib/spinel/radio_spinel.hpp
When running border routers, users have the option to perform RCP firmware updates. After completing the update, users prefer not to restart or reinitialize the master device but only want to restart and restore the RCP device.
Restarting can be initiated by the user; for example, they can restart the RCP device by triggering the reset pin. However, after this restart is done, certain RCP information needs to be restored, such as the panid and extended address.
Typically, the master device can restore the RCP by triggering `RecoverFromRcpFailure`, but this behavior is not user-controllable. So there's a need to implement a callable API for RCP restoration.
If the `RestoreProperties` is made public, users can actively restore the RCP by calling it and some other public functions.
=> [spinel] expose RestoreProperties as a public method within RadioSpinel

.github/workflows/simulation-1.1.yml
Seems adding `sudo apt-get update` can fix the bootstrap failure of `ot-commissioner` CI.
=> [continuous-integration] fix bootstrap issue for ot-commissioner

src/lib/platform/BUILD.gn, src/lib/platform/exit_code.h
Missing a header file included in the file `exit_code.h`, and 'otLogCritPlat' will not be declared. If using the function `SuccessOrDie` with only inlcude the file `src/lib/platform/exit_code.h`, it will have a compiling error `'otLogCritPlat' was not declared in this scope`. 
This PR fix it.
=> [platform] fix compiling issue when use `SuccessOrDie`

src/core/net/ip6.cpp
This commit updates `SelectSourceAddress()` to ensure that non-deprecated addresses are always preferred over deprecated ones. When iterating over addresses, the best option is tracked in `bestAddr`. If the new address is not preferred and the currently selected `bestAddr` is, the new address is skipped to ensure that it is not picked.
=> [ip6] update `Ip6::SelectSourceAddress()` to prefer non-deprecated addresses

src/core/api/ip6_api.cpp, src/core/thread/mlr_manager.cpp, src/core/thread/mlr_manager.hpp
This commit contains smaller enhancements in `MlrManager`:
- Use shorter names for variables and methods
- Avoid the use of normal `enum` name as a namespace
- Use core type `Ip6::Address` instead of `otIp6Address`
---
This PR contains commit from https://github.com/openthread/openthread/pull/9633 (please check the second commit on this PR).
=> [mlr] use shorter variable/method names

src/posix/platform/configuration.cpp, src/posix/platform/configuration.hpp
This commit fixes the unused private variable kKeyCalibratedPower error when `OPENTHREAD_CONFIG_PLATFORM_POWER_CALIBRATION_ENABLE` isn't enabled.
This commit also eliminates some unnecessary member variables.
=> [posix] fix unused private variables

.github/workflows/simulation-1.2.yml, src/core/mac/sub_mac.cpp
Add missing `.GetValue()` for getting values from `TimerMicro`
related PR: https://github.com/openthread/openthread/pull/9568
=> [csl] fix `TimerMicro::GetNow()` call in `sub_mac.cpp`

tests/scripts/thread-cert/border_router/test_multi_thread_networks.py
There was a check `self.assertNotEqual(br1_external_routes, br2_external_routes)` that verifies the external route entries of BR1 and BR2 are different, based on the fact that their external route prefixes (in /64) were different. However, today we're using generic external routes like `fc00::/7` so the external route entries will be the same when BR1 and BR2 have the same RLOC16. 
I updated the test case to verify that the devices have expected external route entries respectively.
=> [tests] fix the check of external routes in `test_multi_thread_networks.py`

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
When InfraIf is down and we received a RA from the host interface, we may trigger the EvaluateRoutingPolicy unexpectly.
This might happen when infra if and uplink are separate interfaces.
This PR fixes this by adding Start and Stop to `PdPrefixManager` to start / stop handling RA messages.
=> [dhcp6-pd] stop `PrefixManager` when `RoutingManager` is stopped

src/core/meshcop/dataset.cpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_local.cpp, src/core/meshcop/dataset_local.hpp
This commit simplifies the handling of Dataset TLVs that need to be securely stored when the `PLATFORM_KEY_REFERENCES_ENABLE` feature is enabled. Two new methods are added to the `Dataset` class:
- `SaveTlvInSecureStorageAndClearValue()` which  saves the value of a given TLV type in secure storage and clears the TLV value by setting all value bytes to zero.
- `ReadTlvFromSecureStorage()` which reads the TLV value back from secure storage and updates it in the `Dataset`.
These methods are used by `DatasetLocal` to manage the set of TLVs that need to be securely stored defined by a constant array of `SecurelyStoredTlv` entries. Each entry provides the TLV type along with the associated `Crypto::Storage::KeyRef` to use for active or pending Dataset.
=> [dataset] simplify saving/reading of TLVs in/from secure storage

include/openthread/border_routing.h, include/openthread/instance.h
This commit adds `otBorderRoutingDhcp6PdGetState()` function declaration in `border_routing.h` which was already implemented in `border_routing_api.cpp` file.
=> [border-router] add missing `otBorderRoutingDhcp6PdGetState()` declaration

src/lib/spinel/radio_spinel.hpp
`MULTIPAN RCP` is enabled when `OPENTHREAD_CONFIG_MULTIPAN_RCP_ENABLE` is set to `1`, so `#if` should be used instead of `#ifdef`.
=> [spinel] fix multipan rcp enable config

src/core/backbone_router/bbr_leader.hpp, src/core/backbone_router/bbr_local.cpp, src/core/backbone_router/bbr_local.hpp
This commit contains smaller change in `bbr_local` module:
- `LogDomainPrefix()` and `LogService()` methods are updated to use newly added `Action` enumeration.
- `HandleDomainPrefixUpdate()` is simplfied to pass the event directly to `mDomainPrefixCallback`.
- `SetState()` is updated so we we first remove ALOC/multicast addresses based on the previous state before adding/updating any addresses  based on the new state.
- Some methods/variables are renamed (e.g., use shorter name).
=> [bbr-local] smaller enhancements

src/core/common/encoding.hpp, src/core/common/tlvs.hpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset_local.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager.hpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/dataset_updater.cpp, src/core/meshcop/meshcop_leader.cpp, src/core/meshcop/meshcop_leader.hpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/meshcop/meshcop_tlvs.hpp
This commit introduces template methods `ReadValueAs<>()` and `WriteValueAs<>()` in `Tlv` class for handling simple TLV types (single value and uint value). These methods are employed to simplify the handling of `MeshCoP::Tlv` in `Dataset`. Specifically, the following TLVs are simplified:
- `PanIdTlv`
- `ExtendedPanIdTlv`
- `PskcTlv`
- `NetworkKeyTlv`
- `MeshLocalPrefixTlv`
- `ActiveTimestampTlv`
- `PendingTimestampTlv`
- `DelayTimerTlv`
- `NetworkKeySequenceTlv`
- `JoinerUdpPortTlv`
These enhance the code by reducing repeated boilerplate code for the these simple TLVs.
=> [tlvs] add `ReadValueAs()` & `WriteValueAs()` to simplify `MeshCop::Tlv`

include/openthread/instance.h, include/openthread/srp_client.h, src/cli/README_SRP_CLIENT.md, src/cli/cli_srp_client.cpp, src/core/net/srp_client.cpp, tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_srp_auto_host_address.py
This commit updates the `AutoAddress` mode in `Srp::Client` to exclude any deprecated (non-preferred) address when registering host addresses.
It also updates `test_srp_auto_host_address` to validate the new behavior.
=> [srp-client] exclude non-preferred addresses in `AutoAddress` mode

.github/workflows/toranj.yml, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_manager_ftd.cpp
This commit introduces two new methods, `ContainsTlv()` and its template variant `Contains<TlvType>()`, in the `Dataset` class. These methods enable checking whether a specified TLV type exists among the Dataset's TLVs.
----
This PR also include a second commit:
**[github-actions] cover NCP build with `OT_OPERATIONAL_DATASET_AUTO_INIT`**
This commit updates  `unittest` job in `toranj.yml` workflow to validate `ncp` builds (with `OT_OPERATIONAL_DATASET_AUTO_INIT` feature enabled).
=>  [dataset] introduce `ContainsTlv()` method

src/core/meshcop/meshcop_tlvs.hpp
Use `Ccm` instead of `CCM` to follow the naming style conversion for constants and variable names.
=> [meshcop-tlvs] update name style in `DiscoveryResponseTlv`

include/openthread/instance.h, include/openthread/ip6.h, src/core/net/netif.cpp, src/core/net/netif.hpp, src/core/net/srp_client.cpp, src/core/net/srp_client.hpp, src/core/thread/address_resolver.cpp, src/core/thread/mle.hpp
This commit enhances the SRP client to track registered addresses when auto host address mode is enabled. A new field `mSrpRegistered` is added to `Ip6::Netif::UnicastAddress` to track whether the address is registered by the SRP client.
This optimization ensures that the SRP client only performs registration when there is a change to the list of addresses that
need to be registered, preventing unnecessary re-registration and reduces communication overhead, e.g., when a deprecating non-preferred address which is not registered by SRP client is timed out and removed.
----
- ~The PR contains the commit from https://github.com/openthread/openthread/pull/9642 (Please check and review the last commit on this PR. Thanks).~
=> [srp-client] track registered addresses

src/core/meshcop/dataset.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/thread/mle_tlvs.cpp, src/core/thread/mle_tlvs.hpp
This commit introduces `IsValid()` and `SetChannelAndPage()` methods to `Mle::ChannelTlvValue`, enabling its use as the value of `MeshCoP::ChannelTlv`.
=> [meshcop] `MeshCoP::ChannelTlv` to utilize `Mle::ChannelTlvValue`

include/openthread/border_routing.h, include/openthread/instance.h, include/openthread/ip6.h, src/core/api/border_routing_api.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/net/ip6.cpp
Add MVP Telemetry metrics of OTBR DHCPv6 PD feature
1. The number of platform generated RA message processed
- bool mRequirePD
- int64_t mNumPlatformRaReceived
- int64_t mNumPlatformPIOProcessed
- int64_t mLastPlatformRaTimestamp
2. The hashed PD prefix allocated to the Thread network
3. The (packet and byte) count of incoming and outgoing internet traffic on the border router
- Incoming traffic counter
- Outgoing traffic counter
Fixes #9574
=> [telemetry] add api for DHCPv6 PD telemetry

src/posix/platform/include/openthread/openthread-system.h, src/posix/platform/infra_if.cpp, src/posix/platform/platform-posix.h
This PR exposes `otSysInfraIfIsRunning()`.
When we are switching to another infra netif via `otBorderRoutingInit()`, we may want to read the state of the new infra netif via  `otSysInfraIfIsRunning()`.
=> [posix] expose `platformInfraIfIsRunning()` as `otSysInfraIfIsRunning()`

tests/scripts/thread-cert/border_router/nat64/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/nat64/test_single_border_router.py, tests/scripts/thread-cert/border_router/nat64/test_with_infrastructure_prefix.py, tests/scripts/thread-cert/border_router/test_multi_border_routers.py, tests/scripts/thread-cert/border_router/test_multi_thread_networks.py, tests/scripts/thread-cert/border_router/test_on_link_prefix.py, tests/scripts/thread-cert/border_router/test_radvd_coexist.py, tests/scripts/thread-cert/border_router/test_single_border_router.py, tests/scripts/thread-cert/node.py
As @abtink mentioned in https://github.com/openthread/openthread/pull/9648#pullrequestreview-1751025580, `get_netdata_nat64_prefix()` is actually getting NAT64 routes from netdata. Therefore it seems more appropriate to call it `get_netdata_nat64_routes()`.
=> [tests] rename `get_netdata_nat64_prefix()` to `get_netdata_nat64_routes()`

src/core/meshcop/announce_begin_client.cpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/energy_scan_client.cpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/meshcop/meshcop_tlvs.hpp, src/core/meshcop/panid_query_client.cpp, src/core/radio/radio.cpp, src/core/radio/radio.hpp, src/core/thread/announce_begin_server.cpp, src/core/thread/energy_scan_server.cpp, src/core/thread/mle_tlvs.cpp, src/core/thread/network_diagnostic.cpp, src/core/thread/panid_query_server.cpp
This commit simplifies `ChannelMaskTlv` generation and parsing. Notably, it ensures that when we read this TLV from a `Message` the TLV value format is validated. The changes include:
- `Entry` class representing a channel page entry is now defined as a `private` nested class within `ChannelMaskTlv`.
- A shared `EntriesData::Parse()` method is added that validates and parses the entries in the TLV, whether the TLV value resides in a buffer (e.g., within `Dataset`) or in a `Message`.
- `ChannelMaskTlv::AppendTo()` method is added to construct entries from a given combined channel mask (for all pages) and append the `ChannelMaskTlv` to a given `Message`.
- `Radio::kSupportedChannelPages` is changed to an array (containing all supported pages) instead of mask.
- Helper functions added in …
=> [meshcop-tlvs] simplify and enhance `ChannelMaskTlv`

src/core/thread/discover_scanner.cpp, src/core/thread/discover_scanner.hpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mesh_forwarder_mtd.cpp
This commit adds `FinalizeMessageDirectTx()`, which clears the `DirectTx` flag on a given message, updates the IPv6 counter, and signals other modules about the transmission status(particularly for `MleDiscoverRequest` and `MleChildIdRequest` messages so their internal state can be updated).
This commit ensures `FinalizeMessageDirectTx()` is called in various scenarios:
- Successful message delivery (all fragments reach destination).
- Any fragment transmission failure (frame tx failure)
- Message drop due to address query failure or malformed message.
- Message drop by queue management.
- Message eviction to prioritize higher-priority messages.
This commit also updates `DiscoverScanner` to stop an ongoing discover scan if the "MLE Discover Request" message transmission fails (with error …
=> [mesh-forwarder] finalize message direct tx on drop or eviction

src/core/coap/coap_secure.hpp, src/core/meshcop/secure_transport.cpp, src/core/meshcop/secure_transport.hpp, src/core/radio/ble_secure.cpp
Documentation of `HandleSecureTransportReceive` previously called `HandleUdpReceive`. As requested in #9631
=> [secure-transport] rename `HandleUdpReceive` to `HandleReceive`

src/core/api/coap_secure_api.cpp, src/core/coap/coap_secure.hpp
This commit removes `CoapSecure::SetClientConnectedCallback()` which is the same as `SetConnectedCallback()`.
=> [coap] remove duplicate method for setting `ConnectedCallback`

src/core/thread/mle.cpp
[MLE] class member variable mLinkRequestAttempts is not initialized to zero causing it to get a random value during power cycle. This causes MTD thread device to send linkrequest after power cycle.
Create a thread network with two devices with DUT with mode rn. Reset both devices simultaneously, enable leader and then child device (DUT). Because class member variable mLinkRequestAttempts is not initialized to zero during initialization. it will get random value, and value greater than zero will lead to send a link request message which should not be the case for a MTD device.
=>  [mle] fix uninitialized `mLinkRequestAttempts`

src/core/meshcop/secure_transport.cpp, src/core/meshcop/secure_transport.hpp
This commit adds `SetState()` in `SecureTransport` class which also logs the state changes. New helper methods `IsState{}()` is also added to simplify the code.
=> [secure-transport] add `SetState()` and log state changes

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit adds `OmrPrefixManager::ShouldAdvertiseLocalAsRio()` which determines whether the local OMR prefix should be advertised as RIO in emitted RAs. To advertise, we must have decided to publish it, and it must already be added and present in the Network Data. This ensures that we only advertise the local OMR prefix in emitted RAs when, as a Border Router, we can accept and route messages using an OMR-based address destination, which requires the prefix to be present in Network Data. Similarly, we stop advertising (and start deprecating) the OMR prefix in RAs as soon as we decide to remove it. After requesting its removal from Network Data, it may still be present in Network Data for a short interval due to delays in registering changes with the leader.
---
- ~To avoid rebase, I …
=> [routing-manager] advertise local OMR in RA after present in netdata

tests/unit/test_routing_manager.cpp
This ensures that the function defined in the unit test would be correctly picked over weak implementations.
=> [unit-test] make sure `otPlatLog()` is defined as `extern "C"`

src/posix/platform/udp.cpp
Commit adds check to `otPlatUdpBindToNetif` if backbone interface is set to correct value to prevent `setsockopt` from crashing the ot-daemon.
=> [posix] verify in `otPlatUdpBindToNetif` if Backbone Interface is set

src/posix/platform/radio.cpp, src/posix/platform/radio_url.cpp, src/posix/platform/radio_url.hpp
When compiling `mRadioUrl=aUrl` in `Radio::Init()`, some compilers may implicitly convert `aUrl` to a temporary `RadioUrl` object and then copy the temporary `RadioUrl` to `mRadioUrl` via a default copy constructor. The pointer members of `mRadioUrl` point to the content of the temporary `RadioUrl`, and it eventually causes the program to access the memory that has been released, which causes the program to crash.
This commit disables the compiler from implicitly converting `aUrl` to a `RadioUrl` object and deletes the default copy and move constructors.
=> [posix] prevent implicit conversion of `aUrl` to `RadioUrl`

.github/dependabot.yml
OpenThread forks typically inherit all commits in the repo, including the `dependabot` changes, so it's not needed to generate the same PRs in the forks as well.
=> [github-actions] avoid `dependabot` pull requests in forks

src/core/net/dns_types.hpp, src/core/net/dnssd_server.cpp, src/core/net/dnssd_server.hpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, tests/unit/test_dns.cpp, tests/unit/test_dns_client.cpp
This commit introduces template variants for `ReadName()` and other related methods, allowing flexible reading of DNS names and labels from messages into a given array buffer. This simplifies the code and improves readability.
Additionally, this commit defines new types, `Dns::Name::Buffer` and `Dns::Name::LabelBuffer`, as arrays of char with fixed sizes to hold DNS names and labels, respectively.
=> [dns-types] add template variants for reading DNS names or labels

src/lib/spinel/spinel.c, src/lib/spinel/spinel.h
This PR adds net role 'DISABLED' into `spinel_net_role_t` to
differentiate between 'DISABLED' and 'DETACHED' status of NCP.
Since this is only used for NCP and not related with RCP, the `RCP_API_VERSION`
is not updated.
=> [spinel] add spinel net role DISABLED

src/core/net/dns_types.cpp, src/core/net/dns_types.hpp, tests/unit/test_dns.cpp
This commit adds `Name::Matches()` method which compares a `Name` instance (which can be from a C string or encoded in a `Message`) with a given set of labels and domain name strings. This method allows the caller to specify name components separately, enabling scenarios like comparing "service instance name" with separate instance label, service type, and domain strings. Unit test `test_dns` is also updated to validate the behavior of the newly added method.
=> [dns] add `Name::Matches()` to compare DNS names

include/openthread/instance.h, include/openthread/ip6.h, src/posix/platform/netif.cpp
Ignore Required Anycast address  when it is added to or deleted from wpan0 interface in openthread
=> [posix] ignore required anycast address

src/core/net/dns_types.hpp, tests/unit/test_dns.cpp
This commit updates `ExtractLabels()` documentation to clarify that name and suffix name can include or exclude the trailing dot but both inputs must follow the same style. It also updates `test_dns` unit test to validate this behavior.
=> [dns] clarify trailing dot in `Name::ExtractLabels()`

src/core/net/dns_types.cpp, src/core/net/dns_types.hpp, tests/unit/test_dns.cpp
This commit introduces a new method, `Name::CompareMultipleLabels()`, to efficiently parse and compare multiple DNS name labels directly from a message. This is then used to optimize `Name::Matches()` eliminating the need to read the entire name into a separate buffer.
This commit also updates `Name::Matches()` method to treat the first label as a single label allowing it to include dot 
character (which is useful for service instance label).
Additionally, `test_dns` unit test is updated to validate the functionality of the new methods.
=> [dns] add `Name::ComapreMultipleLabels()` and update `Matches()`

examples/platforms/simulation/trel.c, include/openthread/instance.h, include/openthread/platform/trel.h, include/openthread/trel.h, src/cli/cli.cpp, src/cli/cli.hpp, src/core/api/trel_api.cpp, src/core/radio/trel_interface.cpp, src/core/radio/trel_interface.hpp, src/posix/platform/trel.cpp, tests/scripts/thread-cert/border_router/test_trel_connectivity.py, tests/scripts/thread-cert/node.py, tests/unit/test_platform.cpp, tests/unit/test_platform.h
Create OT API to support trel telemetry which is supported through platform API
and also add cli support to get/reset trel counters
Metrics we are adding are:
- trel_frames_tx
- trel_bytes_tx
- trel_frames_rx
- trel_bytes_rx
- trel_frames_tx_failed
- num_trel_peers
Metrics already supported through API:
- trel_enabled
=> [telemetry] add API for TREL telemetry

src/ncp/ncp_base_mtd.cpp
Following PR #9731, this PR differentiates net role DETACHED and
DISABLED when getting spinel property from NCP.
=> [ncp] differentiate DETACHED role and DISABLED role

src/core/net/srp_client.cpp
In method ReadOrGenerateKey removing call to `GetPublicKey` which was unnessesery operatoin. (value was't used afterward.)
=> [srp] simplify crypto `ReadOrGenerateKey` in srp client

src/posix/platform/netif.cpp
Currently, when netlink informs that the network interface is up, an IPv4 route is added if a valid one is specified. However, elsewhere we only add/update the route when NAT64 is actually enabled. Since IPv4 route is not useful when NAT64 is not enabled, apply the same logic when the network interface is started.
This avoids warnings when NAT64 is compiled in but disabled: incoming message is an IPv4 datagram but no NAT64 prefix configured, drop
=> [posix] only add IPv4 route if NAT64 is enabled

src/core/thread/network_diagnostic.cpp, tests/toranj/cli/test-020-net-diag-vendor-info.py
Adds support for responding to `MleCounterTlv` in `AppendDiagTlv()` Processing the TLV is a received response is already implemented and supported. Updates `test-020-net-diag` to check query of MLE counters TLV.
=> [net-diag] handle `MleCounterTlv` in `AppendDiagTlv()`

src/posix/platform/netif.cpp
This PR fixes the netif address deletion issue on posix. 
Currently there is an issue when using netlink to delete ip addresses on the 
network interface. The operation of deletion actually failed. For example, if we start ot-daemon, then `ifconfig up` and `ifconfig down`. We can see error in the log:
```
2024-01-16T23:18:17.543742+08:00 ./build/posix/src/posix/ot-daemon[29108]: 00:01:49.870 [I] Platform------: [netif] Sent request#3 to remove fe80::e8f2:97e2:362e:bcfe/64                                                                                                                                                                                  
2024-01-16T23:18:17.544987+08:00 ./build/posix/src/posix/ot-daemon[29108]: 00:01:49.871 [W] Platform------: [netif] Failed to process request#3: …
```
=> [posix] fix netlink address deletion on posix

examples/platforms/simulation/radio.c, include/openthread/instance.h, include/openthread/platform/radio.h, src/core/radio/radio.cpp, src/core/radio/radio.hpp, src/core/radio/radio_platform.cpp, tests/unit/test_platform.cpp
Add `ResetCslParameters` and `otPlatRadioResetCslParameters`.
This allows handling stack reset as separate call instead of using `kShortAddrInvalid` as `otShortAddress` and
`nullptr` as `otExtAddress` which can be difficult to handle on vendor's side.
Default implementation still calls
`otPlatRadioEnableCsl(aInstance,0, Mac::kShortAddrInvalid, nullptr)` So no action is needed if vendor has already implemented handling this case.
=> [radio] add API for resetting CSL parameters

src/lib/spinel/radio_spinel.cpp
For the Spinel layer, when the state is transmitting, if the received Spinel frame fails parsing, the current implementation passes the `OT_ERROR_PARSE` error code to the sub_mac layer via the tx done handler. This causes an assert because the error code `OT_ERROR_PARSE` is not a valid one for `SubMac::HandleTransmitDone`. Additionally, I believe that when the received Spinel frame fails parsing, we should not trigger a transmit done to the sub_mac layer, as the `TxFrame` and the `AckFrame` may not be valid for further processing.
In this corner case, I suggest considering ignoring the parsing-failed received packets, waiting for the tx timeout, and then raising a tx timeout failure to recover the RCP. This might be a reasonable approach.
=> [spinel] fix passing an unexpected transmit error to mac layer

src/core/coap/coap_secure.cpp, src/core/coap/coap_secure.hpp, src/core/meshcop/secure_transport.cpp, src/core/meshcop/secure_transport.hpp
This commit introduces a new feature in `SecureTransport` and `CoapSecure` that allows us to specify the maximum number of allowed connection attempts before the socket is automatically closed and the CoAP agent is stopped. This can be used to enhance security by preventing attacks and excessive retries. This commit also adds a callback mechanism to notify when the limit is reached and the CoAP agent is stopped.
----
Related to [SPEC-1216](https://threadgroup.atlassian.net/browse/SPEC-1216) and for use with ephemeral PSK mechasnim (PR https://github.com/openthread/openthread/pull/9435)
=> [coap-secure] introduce maximum connection attempt limit for CoAP agent

include/openthread/instance.h, include/openthread/nat64.h, src/core/api/nat64_api.cpp, src/core/net/ip4_types.cpp, src/core/net/ip4_types.hpp, src/core/net/ip6_address.cpp, src/core/net/ip6_address.hpp, tests/unit/test_ip_address.cpp
The IPv4-mapped IPv6 address is useful in certain platform/public APIs where we need to support both IPv6 or IPv4 address. We can use IPv4-mapped IPv6 address to represent an IPv4 address. This commit adds simple helper functions to validate, create and parse such addresses.
=> [ip6] add method for creating/parsing IPv4-mapped IPv6 address

etc/cmake/options.cmake, src/lib/spinel/radio_spinel.cpp
This PR contains following changes:
1. Address the issue of handling tx timeout in case of multipan enabled. When RCP recovery initiates due to a timeout, the SPINEL attempts to transition to the Rx state and switch channels to initialize the RCP. However, these actions should be ignored when operating as Multiprotocol RCP, as another host/protocol might be scanning, and encountering the Rx state or channel switch could result in an error. Considering such scenarios, ignore the error rather than assert it for multipan.
2. Make the CMake option OT_MULTIPAN_RCP depend on the compile time value OPENTHREAD_CONFIG_MULTIPAN_RCP_ENABLE, rather than being initialized to OFF.
=> [multipan] fix for multipan use case to handle tx timeout

src/core/thread/key_manager.cpp
While trying to read the Pskc or networkkey, we check if the keyref is valid. We instead need to check if the key is present. There is a possibility that the persistent data was erased before trying to read the key, which might result in asserts.
=> [key-manager] check if the key is present before exporting the key

src/lib/spinel/radio_spinel.cpp, src/lib/spinel/radio_spinel.hpp
Currently the `RadioSpinel::RestoreProperties` only restores some properties defined in `spinel.h`. 
But if `OPENTHREAD_SPINEL_CONFIG_VENDOR_HOOK_ENABLE` is selected, users may set some properties of RCP via vendor command. So the radio spinel should allow users to register a callback to restore the vendor properties of RCP.
=> [spinel] allow registering callback to restore vendor properties

src/core/thread/network_data_publisher.cpp, tests/scripts/thread-cert/test_netdata_publisher.py
This commit updates how the `NetworkData::Publisher` handles "DNS/SRP Service Unicast Address" entries. Specifically, when a "DNS/SRP Service Anycast" entry is added by another BR, the publisher will set the desired count of unicast entries to zero. This effectively removes any previously added unicast entry. This new behavior is only applied when the address and port are included in the Server TLV data in a "DNS/SRP Service Unicast Address" entry.
The `test_netdata_publisher` has been updated to verify this new behavior.
---
Related to [SPEC-1240](https://threadgroup.atlassian.net/browse/SPEC-1240)
=> [netdata-publisher] remove SRP unicast on anycast entry added by a BR

src/core/border_router/routing_manager.cpp, tests/unit/test_routing_manager.cpp
This commit fixes `DiscoveredPrefixTable::Entry::IsDeprecated()` to properly handle larger preferred lifetime values. It uses the method `CalculateExpireDelay()` to handle time delay calculation, avoiding overflow. The `test_routing_manager` test has also been updated to check for larger preferred/valid lifetime values.
=> [routing-manager] fix `IsDeprecated()` to handle large lifetime

src/ncp/ncp_base_mtd.cpp
The IPv6 packets received from host is from a different network stack, which is untrusted.
=> [ncp] set message origin to host untrusted

src/core/net/ip6.cpp
This commit always delivers multicast traffic to the host.
Without this change, host will not be able to receive link-local and mesh-local multicast traffic, even the host subscribes to some multicast addresses in these scopes.
Note that this does not change the host forwarding rules, as link-local and mesh-local traffic are not supposed to be forwarded to adjacent links.
=> [ip6] always deliver multicast to host

src/posix/platform/netif.cpp
There's no clear use case for looping back packets to host. And it would probably result in host processing duplicate messages. This commit disables looping packets back to host.
=> [posix] do not loop back to host

src/core/net/ip6.cpp
This commit moves the check for rule 1 on preferring same address as the destination before the `(bestAddr == nullptr)` check. This ensures that rule 1 will be correctly applied even when the address happens to be first one in the `GetUnicastAddresses()` list.
=> [ip6] `SelectSourceAddress()` rule 1 on preferring same address

include/openthread/instance.h, include/openthread/ip6.h, src/core/net/netif.cpp, src/core/net/netif.hpp, src/core/thread/mle.cpp, src/posix/platform/netif.cpp
This commit updates mesh-local addresses to be marked as preferred (reverting the change from #6532). This ensures that mesh-local addresses are not skipped over in `Ip6::SelectSourceAddress()`.
The intention behind #6532 was to ensure that mesh-local addresses, when added to the platform host IPv6 stack (such as lwIP or the Linux kernel), are not preferred and therefore not selected by the host stack as the source address of application layer traffic unless explicitly assigned.
This PR delegates this responsibility to the platform code and updates `posix/platform/netif` to change the preferred flag for mesh-local addresses when adding them on the platform IPv6 stack.
To make this easier, the `otIp6AddressInfo` is updated to include `mMeshLocal` to indicate whether or not the address is …
=> [ip6] mesh-local addresses as preferred, platform control flag on host stack

src/core/mac/mac.cpp
Currently the the data poll timer is used to maintain synchronization with the parent. It sends a data poll once per csl timeout. However often this is not necessary as other packets that are sent cause synchronization to be maintained. This commit resets the data poll timer each time a frame containing the csl ie is successfully transmitted.
=> [csl] reset data poll timer after successful csl transmission

src/core/instance/instance.cpp, src/core/instance/instance.hpp
This commit moves the `mBackboneRouterLocal` before `mMleRouter` in `Instance` class to ensure that it is initialized and its constructor is called before. This ensures when `Mle()` constructor invokes the `ApplyNewMeshLocalPrefix()` method on `BackboneRouter::Local`, it is already initialized.
----
Should help address: https://github.com/openthread/openthread/issues/9841
=> [instance] init `BackboneRouter::Local` before `Mle`

src/core/crypto/mbedtls.cpp
Currently mbedtls debug logging can only be set for builtin mbedtls. With an extenal mbedtls the log level does not get configured. This commit removes the builtin requirement.
=> [mbedtls] make debug logging independent from builtin

include/openthread/instance.h, include/openthread/netdiag.h, src/cli/cli.cpp, src/core/api/netdiag_api.cpp, src/core/config/network_diagnostic.h, src/core/thread/network_diagnostic.cpp, src/core/thread/network_diagnostic.hpp, src/core/thread/network_diagnostic_tlvs.hpp, tests/toranj/cli/cli.py, tests/toranj/cli/test-020-net-diag-vendor-info.py
This commit contains the following:
- Adds support for the Vendor App URL TLV.
- Includes new public OT APIs and configurations to get and set the TLV value.
- Enables use of the TLV in the CLI `networkdiagnostic` command.
- Updates `test-020-net-diag-vendor-info.py` to validate the new TLV.
----
Related to [SPEC-1249](https://threadgroup.atlassian.net/browse/SPEC-1249).
=> [netdiag] add support for Vendor App URL TLV

include/openthread/instance.h, include/openthread/netdiag.h, src/cli/cli.cpp
This commit contains smaller enhancements in `netdiag.h`:
- Changes TLV type constants to use `#define`.
- Removed unused definitions/constants.
- Move constants used by CLI module to related CLI method.
- Update comments and fix style.
=> [netdiag] update comments and fix style

src/core/config/ip6.h, src/core/net/ip6.cpp
On Android, the platform doesn't restrict link-local/mesh-local source addresses when forwarding multicast packets. For multicast packets sent from link-local/mesh-local address to scope larger than realm-local, set the hoplimit to 1 so the packet can be delivered to host, and will not be forwarded to infrastructure link.
The feature is guarded by `OPENTHREAD_CONFIG_IP6_RESTRICT_FORWARDING_LARGER_SCOPE_MCAST_WITH_LOCAL_SRC `, set as 1 to enable.
=> [ip6] filter multicast packets to host

src/cli/cli.cpp, src/cli/cli.hpp, src/cli/cli_dns.cpp, src/cli/cli_ping.cpp, src/cli/cli_tcat.cpp, src/cli/cli_tcp.cpp, src/cli/cli_udp.cpp
This commit contains small changes in the CLI modules:
- Replace use of core-internal `kError` with `OT_ERROR` constants.
- Remove `#endif` comments when the corresponding `#if` is less than 20 lines away adhering to OT style guide.
- Adhere to single `return` policy (use `ExitNow()`).
- Avoid calling `static` method `ParseToIp6Address()` with an object.
- Smaller style fixes: New lines after variable declaration, use shorter local variable names, etc.
=> [cli] style fixes & remove core defined error constants

src/cli/cli_tcat.cpp, src/cli/cli_tcat.hpp
Change `mVendorInfo` to be a member variable of `Tcat` class instead of a static variable.
=> [cli-tcat] define `VendorInfo` as a member variable

src/core/backbone_router/bbr_manager.cpp, src/core/radio/radio.hpp, src/core/radio/radio_platform.cpp, src/core/thread/link_quality.cpp
Use `NumericLimits<UintType>::kMax` constants in core files.
=> [core] use `NumericLimits<>` constants

src/core/thread/link_quality.cpp
This commit updates `LqiAverager::Add()` to explicitly use a `uint16_t` local variable for calculating the new running average. This prevents potential overflows.
=> [link-quality] prevent overflow in `LqiAverager` calculation

src/lib/spinel/multi_frame_buffer.hpp, src/lib/spinel/radio_spinel.cpp, src/lib/spinel/spinel_encoder.cpp, src/lib/spinel/spinel_encoder.hpp, src/ncp/ncp_base.cpp
when device sends SPINEL frames during RCP reset procedure. This is not handled correctly on host device. It tries to handle the received frames right after the reset, but there are some issues when handling them.
- Cleared reset buffer after reset.
- In GetNextSavedFrame method from class MultiFrameBuffer, Check that the parameter used as read pointer is in the buffer range, else return nullptr.
=> [spinel] drop received frames between RCP disable and reset

include/openthread/instance.h, include/openthread/ip6.h, include/openthread/link.h, include/openthread/message.h, src/core/api/message_api.cpp, src/core/common/message.cpp, src/core/common/message.hpp, src/core/net/ip6.cpp, src/core/net/ip6.hpp, src/core/net/socket.hpp, src/core/thread/discover_scanner.cpp, src/core/thread/mesh_forwarder.cpp, src/core/thread/mesh_forwarder.hpp, src/core/thread/mesh_forwarder_ftd.cpp, src/core/thread/mle.cpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
This commit changes how the link information is tracked for a received message over Thread radio.
It removes the `const void *mLinkInfo` field in `otMessageInfo`. Instead a new public API `otMessageGetThreadLinkInfo()` is added to retrieve the `otThreadLinkInfo` from an `otMessage`.
All the `ThreadLinkInfo` properties are now directly tracked in `Message` as part its `Metadata`. The `Message::Clone()` method is updated to properly copy the link info from the original message to its clones.
This change helps simplify the code, avoid passing `ThreadLinkInfo` references. More importantly, it prevents potential errors due to incorrect use of a pointer to stack-allocated `ThreadLinkInfo` object. This is especially important for modules that save/enqueue `Message` and its `Ip6::MessageInfo` for …
=> [message] track received `ThreadLinkInfo` in `Message` metadata

examples/platforms/simulation/CMakeLists.txt, examples/platforms/simulation/radio.c, examples/platforms/simulation/simul_utils.c, examples/platforms/simulation/simul_utils.h, examples/platforms/simulation/trel.c, examples/platforms/simulation/uart.c
This commit introduces a new module, `simul_utils.h`, under `simulation` platform. This module provides common utility functions, primarily related to socket operations (for emulation of radio or TREL interface). The new functions are used by `radio.c` and `trel.c`, consolidating code and preventing repetition.
=> [simulation] add `simul_utils.h` for socket operation helpers

src/posix/platform/infra_if.cpp
Fixes accessing of member variables of `InfraNetif` class from `static` method `CreateIcmp6Socket()`.
---
- It seems like this might be an unintended change from https://github.com/openthread/openthread/pull/9528.
=> [posix] fix member var access from static `CreateIcmp6Socket()`

src/core/common/string.cpp, src/core/common/string.hpp
This commit ensures that segfault won't happen if `nullptr` is passed  to `StringLength()`.
=> [string] return `0` if `nullptr` is passed to `StringLength`

src/core/border_router/routing_manager.cpp
This commit modifies the `RoutingManager` to not send any Router Advertisements (RAs) until the initial policy evaluation has completed.
This change leverages the `IsInitialPolicyEvaluationDone()` method which ensures that both OMR and on-link prefixes have been determined. Specifically, this guarantees that we wait for the initial set of Router Solicitation (RS) messages to be sent and that we discover all other routers on the AIL before sending the first RA. This is because on-link prefix evaluation itself is dependent on the `mRsSender.IsInProgress()` check that waits till all RS messages are sent and RAs from other routers are received and processed.
Without this change, the BR could receive its own RS message, triggering it to send an RA prematurely, potentially with incorrect M and …
=> [routing-manager] delay sending RAs until after initial policy evaluation

examples/platforms/simulation/infra_if.c, examples/platforms/simulation/platform-simulation.h, examples/platforms/simulation/system.c, tests/toranj/cli/cli.py, tests/toranj/cli/test-500-two-brs-two-networks.py, tests/toranj/start.sh
This commit implements a subset of `otPlatInfraIf` platform APIs in simulation platforms using the `utilsSocket` to emulate communication between BRs. This can be used for testing.
This commit also adds one (simple) example test case with two BRs attached to two different network on same infra-if.
=> [simulation] implement `otPlatInfraIf` APIs in simulation platform

include/openthread/instance.h, include/openthread/thread.h, src/cli/README.md, src/core/api/thread_api.cpp, src/core/mac/mac.cpp, src/core/thread/key_manager.cpp, src/core/thread/key_manager.hpp, src/core/thread/mle.cpp, src/ncp/ncp_base_mtd.cpp, tests/scripts/thread-cert/test_mle_msg_key_seq_jump.py
This commit makes changes/fixes to `KeyManager` regarding key switch guard time.
Key Rotation Time updates:
- When the Key Rotation Time changes (due to security policy updates), the key switch guard time (`mKeySwitchGuardTime`) is also adjusted. It's set to 93% of the Rotation Time (rounded down).
- Immediately checks if the new rotation time indicates a rotation is due and keys are rotated.
New variable `mKeySwitchGuardTimer`:
- This is reset to the current guard time whenever the key sequence is updated.
- It decrements hourly until reaching zero.
- Key switch guard comparison is made with this value, aligning the implementation with the Thread specification.
`SetCurrentKeySequence()` modification:
- Now accepts a new input parameter that determines whether to apply or ignore the key …
=> [key-manager] update how key guard time is determined and applied

tests/scripts/thread-cert/node.py, tests/scripts/thread-cert/test_key_rotation_and_key_guard_time.py
- Validates that key guard time is updated to 93% of key rotation time when it changes.
- Checks for proper key sequence updates after key rotation expiration.
- Confirms key guard mechanism blocks key sequence increments while mesh nodes staying connected.
=> [test] add `test_key_rotation_and_key_guard_time`

src/core/common/tasklet.hpp
The forward declaration in `tasklet.hpp` is stale. This PR removes it.
=> [misc] remove stale forward declaration

src/posix/platform/daemon.cpp
Preivously the OT CLI won't be re-iniitalized when it finds there's already a listening socket. It's actually necessary to do the initialize, considering this scenario:
1. Run `otSysDeinit()` and `otSysInit()` to reset the OT application.
1. Note that the OT instance is replaced by a new one in `otSysInit()`. We need to call `otCliInit()` in `Daemon` to initialize the CLI with the new instance. However, this step has been skipped in `Daemon` because the listening socket is not cleared.
=> [daemon] always initialize the OT CLI when setting up the daemon

tests/scripts/thread-cert/test_mle_msg_key_seq_jump.py
Fixes the following intermittent failure:
```
======================================================================
FAIL: test (__main__.MleMsgKeySeqJump)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/runner/work/openthread/openthread/tests/scripts/thread-cert/test_mle_msg_key_seq_jump.py", line 260, in test
self.assertEqual(child.get_state(), 'child')
AssertionError: 'router' != 'child'
- router
+ child
```
=> [thread-cert] set device mode in `test_mle_msg_key_seq_jump`

tests/scripts/thread-cert/border_router/test_manual_maddress.py
Fixes https://github.com/openthread/ot-br-posix/issues/2149 by extending the wait time. 
I locally ran the test 20 times and they all passed.
=> [tests] fix `test_manual_maddress.py` 

src/posix/platform/configuration.cpp, src/posix/platform/configuration.hpp, src/posix/platform/daemon.cpp, src/posix/platform/daemon.hpp, src/posix/platform/firewall.cpp, src/posix/platform/hdlc_interface.cpp, src/posix/platform/hdlc_interface.hpp, src/posix/platform/infra_if.cpp, src/posix/platform/infra_if.hpp, src/posix/platform/logger.hpp, src/posix/platform/multicast_routing.cpp, src/posix/platform/multicast_routing.hpp, src/posix/platform/netif.cpp, src/posix/platform/radio.cpp, src/posix/platform/radio.hpp, src/posix/platform/resolver.cpp, src/posix/platform/resolver.hpp, src/posix/platform/spi_interface.cpp, src/posix/platform/spi_interface.hpp, src/posix/platform/trel.cpp, src/posix/platform/udp.cpp, src/posix/platform/udp.hpp
This commit updates logging in posix platform modules so that the emitted logs will include the platform log module name. This uses the `otLogPlatArgs()`.
=> [posix] ensure module names are included in platform logs

examples/platforms/simulation/simul_utils.c, examples/platforms/simulation/simul_utils.h, examples/platforms/simulation/system.c, tests/scripts/expect/posix-rcp-local-host.exp
This commit adds an argument `-L`/`--local-host` to simulation platform to specify the source IP address of packets simulating 15.4 frames. This allows the simulation packets being transmitted over a specific network interface instead of the loopback interface, so that the simulation can run on different hosts. This can be used to enable multiple emulation devices(e.g. Android Virtual Device) communicating to each other over emulated Thread radio.
The argument accepts either an IPv4 address or a network interface name. In the latter case, the first found IPv4 address on that interface will be used.
=> [simulation] allow specify local host

src/core/thread/mle.cpp
When detaching, a child transmits a Child Update Request message with Timeout TLV set to 0. The child waits for 1 second after sending the Child Update Request message before stopping Thread operation. However, during this time, the MLE retransmission timer may fire and retransmit the Child Update Request message, which can cause it to send a new Child Update Request message with a non-zero Timeout TLV.
This commit update the behavior to avoid retransmitting the Child Update Request message when detaching.
=> [mle] disable MLE retransmissions when detaching

tests/scripts/thread-cert/test_detach.py
Fixes intermittent failures: https://github.com/openthread/openthread/actions/runs/8283753232/job/22673887232
=> [thread-cert] use `ROUTER_STARTUP_DELAY` in `test_detach`

tests/scripts/thread-cert/test_netdata_publisher.py
Updates validation logic after published route entry replacement to prevent occasional failures due to a race condition.This increases test stability.
----
Should help address failures like [gh-action-run](https://github.com/openthread/openthread/actions/runs/8283753244/job/22667701935).
=> [test] enhance `test_netdata_publisher` robustness

src/core/border_router/routing_manager.cpp
Avoid using the regular `enum` name (as a namespace) when referring to one of its enumerator value.
=> [routing-manager] update use of `Ip6::Nd::Option` enumerator

src/lib/platform/reset_util.h
Addresses warnings generated on some toolchains.
=> [lib] include `(void)` in function prototype in `reset_util.h`

src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit introduces `using` declarations in the `RoutingManager` class for types defined within the `Ip6::Nd` namespace. This allows for shorter, more readable type names to be used.
=> [routing-manager] simplify `Ip6::Nd` type usage

src/core/coap/coap.cpp, src/core/coap/coap_message.cpp, src/core/coap/coap_message.hpp
- remove typo that passed a uint64_t pointer to a function which need a sufficiently large buffer [#9884](https://github.com/openthread/openthread/issues/9884)
-  this bug has led to segmentation faults.
- fix bug that coap copying uri path option or any other long option failed
- this bug causes coap fail to request next block.
=> [coap] fix copying option

src/core/thread/mle_router.cpp
Previously, when a child was promoted to a router role, the leader upon sending "Address Solicit Response" would clear cache entries associated with the child's old RLOC16. This commit modifies the code to retain these cache entries when the sender is a direct child of the leader. By retaining the cache entries, they can be associated with the promoted router's new RLOC16 when the Link Advertisement is received.
=> [mle] retain direct child cache entries on Addr Solicit Response TX

src/core/config/misc.h
This commit updates the documentation for two configs `OPENTHREAD_CONFIG_DEFAULT_SED_BUFFER_SIZE` and `SED_DATAGRAM_COUNT` clarifying their intended use.
=> [config] update docs for `SED_BUFFER_SIZE` & `SED_DATAGRAM_COUNT`

src/core/thread/network_data.cpp, src/core/thread/network_data.hpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/network_data_notifier.cpp, src/core/thread/network_data_types.hpp, tests/unit/test_network_data.cpp
This commit introduces `NetworkData::FindRlocs()` which returns the list of RLCO16 of all border routers and servers in the Network Data matching specified filter conditions. The `BorderRouterFilter` can be used to filter the entry type. It can be set to `kAnyBrOrServer` to include all BRs and servers, or `kBrProvidingExternalIpConn` to restrict the list to BRs providing external IP connectivity. The new `FindRlocs()` replaces `FindBorderRouters()` and `GetNextServer()` methods and help simplify the code. Unit test `test_network_data` is updated to validate the new method.
=> [netdata] add `FindRlocs()` to retrieve RLOC16 of entries

src/cli/cli_network_data.cpp, src/cli/cli_network_data.hpp
This commit simplifies `netdata show` implementation by combining all different `Output{Entry}()` methods into a single `OutputNetworkData()` method.
=> [cli] add `OutputNetworkData()`

include/openthread/border_routing.h, include/openthread/instance.h, src/cli/README_BR.md, src/cli/cli_br.cpp, src/core/api/border_routing_api.cpp, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp, src/core/net/nd6.hpp
This commit introduces new API for setting vendor-specific extra options to append to emitted Router Advertisement messages. Support for this is also added in CLI under `br raoptions` command.
---
~This PR contains the commit from~
- ~https://github.com/openthread/openthread/pull/9939~
=> [routing-manager] support setting extra options to append to emitted RAs

src/core/thread/mle_router.cpp
This commit contains small changes to logs in `HandleTimeTick()` method in `MleRouter` to include the RLOC16 of child entries when updating the child table.
=> [mle] include child RLOC16 in the logs from `HandleTimeTick()`

src/cli/cli_coap.cpp
CoAP response code 2.04 Changed is the default response to a successful POST request. See RFC 7252 5.8.2 and 5.9.1.4.
=> [cli] fix CoAP response code for POST 2.03 -> 2.04 per RFC 7252

src/cli/README_NETDATA.md, src/cli/cli_network_data.cpp, src/cli/cli_network_data.hpp, tests/toranj/cli/cli.py, tests/toranj/cli/test-011-network-data-timeout.py
This commit updates the CLI `netdata show` command to allow an optional RLOC16 as input. Providing an RLOC16 filters the output to display prefix, route, and service entries associated specifically with the specified RLOC16. This is helpful for checking entries added by a specific border router.
`test-011-network-data-timeout.py` is updated to validate the new CLI functionality.
=> [cli] `netdata show` to support filtering by RLOC16

src/core/thread/network_data.cpp, src/core/thread/network_data.hpp
This commit simplifies `MutableNetworkData::RemoveTemporaryData()`:
- The `RemoveTemporaryDataIn()` methods return a `bool` indicating whether the whole TLV can be removed.
- The code is refactored to combine the call to `RemoveTlv()` for all TLV types.
=> [netata] simplify `RemoveTemporaryData()`

src/core/thread/mesh_forwarder_ftd.cpp
This commit ensures `MeshForwarder::CheckReachablity()` rejects frames where `Ip6::Header::DecompressFrom(FrameData)` returns a parse error. This prevents the processing of potentially malformed messages.
=> [mesh-forwarder] update `CheckReachablity()` to handle malformed msg

src/core/mac/mac_frame.cpp
Currently for Enh-ACK based probing feature, the result IE is written in ISR context (for example, `nrf_802154_tx_ack_started`, just like CSL IE). This may cause a race condition:
When the device configures Enh-ACK Probing for a neighbor, [otPlatRadioConfigureEnhAckProbing](https://github.com/openthread/ot-nrf528xx/blob/main/src/src/radio.c#L1429) is called:
```
error = otLinkMetricsConfigureEnhAckProbing(aShortAddress, aExtAddress, aLinkMetrics);
otEXPECT(error == OT_ERROR_NONE);
updateIeData(aInstance, aShortAddress, aExtAddress);
```
If `otLinkMetricsConfigureEnhAckProbing` is completed but `updateIeData` hasn't been done, and `nrf_802154_tx_ack_started` is called, then it will think there should be link metrics IE for this neighbor however the IE hasn't been added into the ACK …
=> [link-metrics] fix race condition

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp
This commit simplifies `MleRouter::CheckReachablity()`:
- Remove and inline `Mle::CheckReachability()` which is used when `IsChild()`.
- Uses local `isReachable` boolean variable.
=> [mle] simplify `CheckReachablity()`

src/core/net/ip6.cpp
Filtering out traffic to/from RLOC/ALOC was added by #423 for #419. The intention was to filter out Thread's control traffic.
Now we already added filtering out traffic by checking whether it is destined to a service hosted in OpenThread stack(https://github.com/openthread/openthread/pull/6711), so filtering out by RLOC/ALOC is not necessary anymore.
This commit removes this filter, as a result, the core lib gets rid of the `PLATFORM_NETIF` flag.
=> [ip6] allow delivering RLOC/ALOC traffic to host

src/core/meshcop/dataset.cpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_local.cpp, src/core/meshcop/dataset_local.hpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager.hpp, src/core/meshcop/tcat_agent.cpp
This commit defines `Dataset::Tlvs` as a core type corresponding to public OT `otOperationalDatasetTlvs` structure.
=> [dataset] define `Dataset::Tlvs` type

src/core/net/srp_server.cpp, src/core/net/srp_server.hpp
This commit adds `LogError()` helper method in `Srp::Server` to simplify logging failures.
=> [srp-sever] add `LogError()`

tests/toranj/cli/cli.py, tests/toranj/cli/test-501-multi-br-failure-recovery.py, tests/toranj/cli/test-502-multi-br-leader-failure-recovery.py, tests/toranj/start.sh
This commit adds new test cases for a topology with two BRs when the primary BR is abruptly powered off. It validates that the second BR takes over and all nodes successfully re-register their SRP services with the new BR using new OMR addresses.
The first test (`501`) covers the case where neither BR is acting as mesh leader. The second test (`502`) covers the case where the powered-off BR is also acting a mesh leader.
=> [test] add tests for multi-BR network resilience during BR removal

src/core/common/log.cpp, src/core/common/log.hpp, src/core/meshcop/border_agent.cpp, src/core/meshcop/border_agent.hpp, src/core/meshcop/commissioner.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/joiner.cpp, src/core/meshcop/joiner_router.cpp, src/core/meshcop/meshcop.cpp, src/core/meshcop/meshcop.hpp, src/core/meshcop/meshcop_leader.cpp, src/core/meshcop/tcat_agent.cpp, src/core/meshcop/tcat_agent.hpp, src/core/net/dhcp6_client.cpp, src/core/net/dhcp6_server.cpp, src/core/net/dnssd_server.cpp, src/core/net/ip6.cpp, src/core/net/sntp_client.cpp, src/core/net/srp_server.cpp, src/core/net/srp_server.hpp, src/core/thread/dua_manager.cpp, src/core/thread/energy_scan_server.cpp, src/core/thread/mle.cpp, src/core/thread/network_data_leader_ftd.cpp, src/core/thread/panid_query_server.cpp, src/core/utils/channel_manager.cpp, src/core/utils/otns.cpp
This commit adds `LogWarnOnError()` to emit warning-level logs on errors. The emitted log includes the error code. This replaces custom `LogError()` across modules, simplifying the code.
=> [logging] introduce `LogWarnOnError()` for standardized error logging

src/core/thread/network_data_publisher.cpp, src/core/thread/network_data_publisher.hpp, tests/scripts/thread-cert/test_netdata_publisher.py
This commit refines the `NetworkData::Publisher` to differentiate between DNS/SRP unicast entries based on whether the address information resides in service data (part of service TLV) or server data (part of server sub-TLV).
Additionally, if another BR adds a service data unicast entry, `Publisher` will zero out the desired count for server data unicast entries, effectively removing any previously published server data unicast entries.
The `test_netdata_publisher` has been updated to validate all the newly added behaviors.
=> [netdata-publisher] distinguish SRP/DNS unicast entries

examples/platforms/utils/mac_frame.cpp
This commit updates `otMacFrameDoesAddrMatch()` to ensure it does not match if frame is malformed (`Frame::GetDstAddr()` fails).
=> [plat-utils] enhance `otMacFrameDoesAddrMatch()`

src/core/thread/mle.cpp, src/core/thread/mle.hpp, src/core/thread/mle_router.cpp, src/core/thread/mle_router.hpp
This commit add the possibility to handle a udp time sync message when configurated as MTD.
Without this modification, the result was : 
With the modification, the time sync message is read and processed by the MTD, the result is now :
=> [mle] MTD to handle udp time sync message

src/core/instance/instance.cpp, src/core/instance/instance.hpp
Provided  two methods  for OpenThread multipan : 
1. Get the index by an openthread instance reference.
2. Get the reference by an openthread instance index.
=> [instance] support get multi instance reference or index

src/lib/spinel/radio_spinel.cpp, src/lib/spinel/radio_spinel.hpp
This commit add the structure needed to support time sync to spinel. 
Resolve :
https://github.com/openthread/openthread/issues/6028
Also resolve the same null pointer problem when time sync was enable on a multi core with a radio core device like nrf5340.
=> [spinel] add time sync feature to the spinel

src/core/meshcop/dataset.cpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_updater.cpp, src/core/meshcop/joiner.cpp, src/core/meshcop/tcat_agent.cpp, src/core/utils/channel_manager.cpp
This commit introduces a `Component` enum to represent dataset components, and defines templated methods (`IsPresent<>`, `Get<>`, `Set<>`, etc) for streamlined access. This reduces boilerplate code for individual component management.
=> [dataset] define template method to check/get/set components

src/core/meshcop/dataset_manager.cpp
This commit simplifies `DatasetManager::SendSetRequest()` by using `Tv::Find<TlvType>()` helper method to search within the given sequence of TLVs for `CommissionerSessionIdTlv`.
=> [dataset] use `Tlv::Find<>()` to check commissioner session ID

src/core/net/udp6.cpp
This commit aims to add more flags to the `ShouldUsePlatformUdp` function, to let sockets with ports belonging to the stack send their packets without using the UDP platform abstractization layer.
Without this change, when Platform UDP is enabled, packets originating from the DHCPv6 Server/Client will take an undesired route from socket -> platform UDP -> external IPv6 stack -> Thread IP stack -> packet over the air.
=> [udp] add DHCP ports to `ShouldUsePlatformUdpFunction`

src/posix/platform/daemon.cpp
This PR replaces `defined(__ANDROID__) && !OPENTHREAD_CONFIG_ANDROID_NDK_ENABLE` macro checks with `OPENTHREAD_POSIX_CONFIG_ANDROID_ENABLE`. This is to make the build options more configurable. E.g. there are cases where `__ANDROID__` is defined but the platform is not fully Android-compatible so we don't want to enable the Android platform implementation.
=> [daemon] avoid using `defined(__ANDROID__)` macro in `daemon.cpp`

src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager.hpp
This commit contains the following:
- Use `FindTlvValueOffset()` to find `Tlv::kGet` in message.
- Define and use `TlvList` to get list of requested TLV type.
- `TlvList` is an array of TLV types, not allowing duplicate values to be added to the list.
- Simplify `SendGetResponse()` to handle including all or a subset of TLVs in response.
=> [dataset] simplify `DatasetManager::HandleGet()` & `SendGetResponse()`

src/core/meshcop/dataset.cpp, src/core/meshcop/dataset_local.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager.hpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/meshcop_leader.cpp, src/core/meshcop/meshcop_leader.hpp, src/core/meshcop/meshcop_tlvs.cpp, src/core/meshcop/meshcop_tlvs.hpp
This commit makes the following improvements to Delay Timer TLV handling in Pending Operational Datasets:
- Enforces maximum delay adhering to the Thread spec's maximum Delay Timer value (72 hours), clamping larger values.
- Defines min, max, and default delay timer constants in `DelayTimerTlv`.
- Adds `CalculateRemainingDelay()` helper method to calculate remaining delay.
- Removes code handling delay values exceeding the OpenThread `Timer` limitation (now redundant due to the stricter 72-hour maximum).
=> [dataset] enforce maximum delay timer value and improve handling

src/core/thread/mle_router.cpp
Updates `MleRouter::SetRouterEligible()` to restart the role transition timer if the device is a child and the router eligibility is changed to `true`.
=> [mle] restart role transition timeout from `SetRouterEligible(true)`

src/cli/README_COMMISSIONER.md, src/cli/README_COMMISSIONING.md, src/cli/README_DATASET.md
Based on discussion in #9901 , this clarifies in the documentation that the CLI `dataset` commands can only be used in specific situations (like testing), and that these commands allow setting invalid (combinations of) parameters also. It points to the Commissioner as the correct way of doing dataset updates in production.
It also adds "Overview" sections that were missing in two README files.
=> [cli] update README files to clarify a Commissioner is used for changing datasets

src/lib/spinel/BUILD.gn, src/lib/spinel/CMakeLists.txt, src/lib/spinel/radio_spinel.cpp, src/lib/spinel/radio_spinel.hpp, src/lib/spinel/spinel_driver.cpp, src/lib/spinel/spinel_driver.hpp
This PR is a breakdown of PR#9898 for easier review.
The PR separates the spinel handling from other rcp specific handling
in `RadioSpinel` by putting the spinel handling into a new class
`SpinelDriver`. The purpose is to make the spinel handling resuable
in further change (for new architecture).
`SpinelDriver` has the following functions:
1. Co-processor initialization
2. Send a spinel command to the co-processor without waiting
3. Drive the processing of received spinel frames. But it will not do the
actual handling.
In this PR, `SpinelDriver` is added as a member of `RadioSpinel` and
`RadioSpinel` uses `SpinelDriver` to implement some of the existing
functions.
With `SpinelDriver`, it is possible to implement a new RadioSpinel-like
module that provides non-blocking APIs (No …
=> [spinel] breakdown radio spinel

src/core/net/dns_types.cpp, src/core/net/dns_types.hpp, tests/unit/test_dns.cpp
- Updates `Dns::Name::ExtractLabels()` for in-place label extraction, optimizing string operations.
- Introduces `Name::StripName()` to efficiently remove a suffix name from a DNS name in place.
- Updates and simplifies unit tests `test_dns` to validate new functionality.
=> [dns] add `Name::StripName()` and support in-place `ExtractLabels()`

src/core/common/tlvs.hpp, src/core/meshcop/dataset.cpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_manager_ftd.cpp
- Inlines `AppendMleDatasetTlv()` in `DatasetManager` (removing from `Dataset` class).
- Updates the locally read `dataset` directly by removing the timestamp before appending it to the message as an MLE TLV value.
- Leverages `Read()` which already updates the `DelayTimerTlv` with the remaining delay, eliminating the need to re-calculate and update the delay.
- Uses `Tlv::AppendTlv()` to append the MLE TLV with `dataset` bytes as value.
=> [dataset] simplify `AppendMleDatasetTlv()`

src/core/mac/sub_mac.cpp
Fix -Wformat trigger on some platforms as an int32_t is printed using %d
```
src/core/mac/sub_mac.cpp:336:73: warning: format '%d' expects argument of type 'int', but argument 5 has type 'int32_t' {aka 'long int'} [-Wformat=]
336 |     logString.Append("Expected sample time %lu, margin ±%lu, deviation %d", ToUlong(sampleTime), ToUlong(ahead),
|                                                                        ~^
|                                                                         |
|                                                                         int
|                                                                        %ld
337 |                      deviation);
|                      ~~~~~~~~~
|                      |
|                      int32_t {aka long int}
```
=> [logging] fix print format when enabling csl debug

zephyr/module.yml
This MR adds the module name in zephyr/module.yml, as is stated in the [official documentation](https://docs.zephyrproject.org/latest/develop/modules.html#module-name):
> Each Zephyr module is given a name by which it can be referred to in the build system.
> The name should be specified in the zephyr/module.yml file. This will ensure the module name is not changeable through user-defined directory names or west manifest files.
=> [zephyr] add module name

include/openthread/instance.h, include/openthread/platform/border_routing.h, src/core/border_router/routing_manager.cpp, src/core/border_router/routing_manager.hpp
This commit adds support for adding a DHCPv6 delegated prefix to the `Routing Manager` via a new Open Thread API. Previously this feature was only supported using a platform-generated RA on a Posix-based BR. For platforms that can get the prefix directly from a DHCPv6 PD client API, there is no point in creating an RA for setting the prefix. It's much easier to use a direct call to configure it.
This new API uses an `otBorderRoutingPrefixTableEntry` structure as an input parameter and evaluates the prefix based on the same rules as one coming from a platform RA. The prefix's lifetime can be updated by calling the function again with new time values.
=> ﻿[routing-manager] add support for to use a prefix received from DHCPv6 PD

src/lib/spinel/radio_spinel.cpp, src/lib/spinel/radio_spinel.hpp
The RCP Restoration feature missed restoring the source address match feature configuration. It causes the source match table to be disabled by default after the RCP restarts. This commit restores the source address match feature configuration.
Fixes https://github.com/openthread/ot-br-posix/issues/2261
=> [spinel] restore the source address match feature configuration

src/core/meshcop/dataset.cpp, src/core/meshcop/dataset.hpp, src/core/meshcop/dataset_local.cpp, src/core/meshcop/dataset_manager.cpp, src/core/meshcop/dataset_manager_ftd.cpp, src/core/meshcop/dataset_updater.cpp
This commit introduces several smaller changes to the `Dataset` class:
- Provides template methods `Read<Tlv>()` for flexible reading of any TLV from dataset, mirroring the existing `Write<Tlv>()` methods.
- Replaces `SetTimestamp()` method with the `Write<Tlv>()` with specific timestamp TLVs
- Renames `GetTimestamp()` to `ReadTimestamp()`, aligning the naming convention with other methods.
=> [dataset] add generic `Read<Tlv>()` methods, refactor timestamp handling
